### ISSUE TITLE
Font Pecita version 5

### ISSUE THREAD

**Issue by Pecita** [google/fonts#100]
*Wish: upgrade Pecita.otf*
Version 5.1 - Sun 2015-08-23 - of the font Pecita: http://pecita.eu/b/

The previous version generalizes the connection mechanism of letters.
This version generalizes the accent mechanism of letters in keeping the connection mechanism.

This allows the font to be used across the spectrum of LCG scripts and in transliterations of tonal languages that make extensive use of diacritical and IPA characters.

With 4717 characters this typeface is heavy: 843K.
Its use on the web requires the activation of opentype features calt and liga which are sadly not the default in Chrome. `-webkit-font-feature-settings: "calt" on, "liga" on, "rlig" on;`

**Comment by davelab6** [comment]
Philippe, thanks for posting this request again :) I wonder if you might
consider making a special web version that has just 1 or 2 alternates and
will work with the features available by default.

Google Fonts aims to make web fonts fast, easy and free - so while your
font is an amazing showcase of a libre font, it's requirement for specific
advanced css does not make it easy, and it's file size does not make it
fast, so as it is, I still can not include it :(

**Comment by Pecita** [comment]
Dave,
Thank you for considering my request kindly.
I fully understand the specifications of Google fonts and the inequation of the Pecita font. I will think about a lighter version...
I allow myself to change topic. It seems to me to be a mistake not to activate `liga` and `calt` by default in Chrome. According to the specification, they should be. Can you do something on this side?
Best regards,
Philippe

**Comment by Pecita** [comment]
Dave,
Even turning the problem around I am not able to adjust the Pecita font to Google fonts requirements.
By cons, please, helps to change the otf default values in Chrome :pushpin:

**Comment by davelab6** [comment]
Thanks @Pecita - I have asked your question in https://code.google.com/p/chromium/issues/detail?id=523650 and https://code.google.com/p/chromium/issues/detail?id=401641 may also be relevant.
