### ISSUE TITLE
Attempting download of a .ZIP of a collection results in a 404

### ISSUE THREAD

**Issue by f8k8** [google/fonts#101]
When attempting to download a .ZIP of a collection, a 404 not found error is returned.

Steps to reproduce:

1) Navigate to https://www.google.com/fonts
2) Out of the fonts listed, click "Add to collection". Have tried it with Open Sans and Roboto.
3) Press the download button in the top right.
4) Select "Download the font families in your Collection as a .zip file".

Expected result

The font collection should download as a .zip

Actual result

A 404 error page is displayed, stating:

"404. That’s an error.
The requested URL was not found on this server. That’s all we know."

An example of the link the browser is trying to access:
https://www.google.com/fonts/download?kit=3hvsV99qyKCBS55e5pvb3ltkqrIMaAZWyLYEoB48lSQ

Tried on:
Chrome Version 44.0.2403.157 m
Windows 10

**Comment by garretrieger** [comment]
Thanks for the report, I've resolved the problem.  Download links should work again.
