### ISSUE TITLE
Where is Noto Hebrew?

### ISSUE THREAD

**Issue by jomortal** [google/fonts#1012]
Noto Sans Hebrew  and Noto Serif Hebrew  don't seem to be installing properly. I get default Arial instead.

**Comment by davelab6** [comment]
> Where is Noto Hebrew? 

Please download any Noto font from https://www.google.com/get/noto/

> Noto Sans Hebrew and Noto Serif Hebrew don't seem to be installing properly. I get default Arial instead.

Could you send a screenshot?

**Comment by jomortal** [comment]
Here is what the install file looks like when I open it. Note that for the
Latin characters it is not showing a serif, and when installed it seems
like Hebrew Unicode is not existing in the character set. The second photo
is while I'm in Word if I try to switch the font to Noto Serif it switches
automatically to some other font like it would if I were trying to use a
font that does not support Hebrew, thus I am unable to get a screenshot of
it having Noto Serif selected.

Question: will the Hebrew eventually just be combined with Noto Sans and
Noto Serif instead of being listed as a separate font? I do academic papers
in English, Greek and Hebrew, and was hoping that I would be able to use
Noto Serif as a font I could type the whole paper in without having to
switch fonts.

[image: Inline image 2]
[image: Inline image 3]

Thanks,
Jonathan

**Comment by jomortal** [comment]
Here is what I get if I have English and Hebrew selected and try to set a
font


*Noto Serif Hebrew*

[image: Inline image 1]

*Noto Serif*
[image: Inline image 2]

Thanks,
Jonathan

Where is Noto Hebrew?

**Comment by davelab6** [comment]
GitHub doesn't accept images via email, please go to the webpage and edit
your​ posts to upload the images

**Comment by davelab6** [comment]
@jomortal could you add the images using the Github web UI?

**Comment by davelab6** [comment]
> will the Hebrew eventually just be combined with Noto Sans and Noto Serif instead of being listed as a separate font? 

I don't know if the Noto team will do this, but there are no plans to do that in this repo; since this issue should be reported and resolved upstream - https://github.com/googlei18n/noto-fonts/issues - I'm closing this for now

@jomortal when you re-file this upstream, please do add the images using the Github web UI :)
