### ISSUE TITLE
Update EkType/Mukta with correct fsSelection Bold bit values

### ISSUE THREAD

**Issue by felipesanches** [google/fonts#1013]
EkType/Mukta fonts need to be updated to address issue originally reported at https://github.com/EkType/Mukta/issues/26

**Comment by davelab6** [comment]
@m4rc1e is on it :)

**Comment by m4rc1e** [comment]
Fixed in #1017

**Comment by davelab6** [comment]
PR #1017 is merged but this isn't pushed out yet, so leaving open, but should be pushed soon

**Comment by laerm0** [comment]
I just downloaded the files from our site and the version number is the newest version so it looks like we're good here. I'm closing.
