### ISSUE TITLE
Aref Ruqaa umlauts

### ISSUE THREAD

**Issue by bardware** [google/fonts#1015]
![grafik](https://cloud.githubusercontent.com/assets/802702/26396579/e9bd4fa8-4073-11e7-93be-194f6db1bea7.png)

Font is rendered one line lower than expected. May be the font viewer, though.

**Comment by davelab6** [comment]
Hmm, interesting! cc @khaledhosny

**Comment by khaledhosny** [comment]
Sorry, but I don’t think I get the issue being reported here.

**Comment by bardware** [comment]
I use the font viewer program from http://us.fontviewer.de/Download/. I enter a sample text that should be rendered directly below the name of the font. In case of `Aaref Ruqaa` it's rendered on whole line below. You see a heading, an empty line, another heading, the `Regular` sample and finally the `Bold` sample.
Then actually you see some wild dots. These should be German Umlauts `ü`, `ö` and `ä` in lower and upper case. For `Regular` none of these characters is shown. `Bold` misses 3 of 6: `ö`, `ä` and `Ä`.

**Comment by khaledhosny** [comment]
Looks like a broken version of the font or a viewer issue. I can’t reproduce any of this:
![umlauts](https://user-images.githubusercontent.com/93914/27072969-e1e3596e-502a-11e7-9120-bd2e7c392be3.png)

**Comment by laerm0** [comment]
I can't reproduce this either from the current GF deliverables. I'm calling it a viewer issue.

![screen region 2017-08-03 at 15 12 56](https://user-images.githubusercontent.com/10780161/28939155-517d4d56-785e-11e7-8aa2-1ac767e6b99f.png)

**Comment by davelab6** [comment]
Thanks @laerm0 :)
