### ISSUE TITLE
The regular font weight for the Catamaran font does not have a semi colon character. 

### ISSUE THREAD

**Issue by nagoshiashumari** [google/fonts#1021]
The regular font weights for the Catamaran font does not have a semi colon character. It instead uses a comma. Can be seen when previewing text on the Catamaran page.

<img width="994" alt="screen shot 2017-05-30 at 3 57 27 pm" src="https://cloud.githubusercontent.com/assets/8682221/26608500/c9378032-4550-11e7-96a8-a6492fb40ead.png">

**Comment by Jimmylet** [comment]
I have the same problem. It's possible to fix that (especially since the font are already integrated into a web project) ? Thanks

**Comment by Jimmylet** [comment]
@nagoshiashumari after investigation, Google font contains errors. You can download the font here https://github.com/VanillaandCream/Catamaran-Tamil/tree/master/Fonts with semicolon

**Comment by m4rc1e** [comment]
#716 fixes this. Its in the queue, waiting to get pushed.

**Comment by davelab6** [comment]
@nagoshiashumari @Jimmylet thanks for reporting

**Comment by laerm0** [comment]
This is in production now so I'm closing.

![screen region 2017-09-19 at 16 20 59](https://user-images.githubusercontent.com/10780161/30613582-97fe82dc-9d56-11e7-9f81-73027a22741f.png)
