### ISSUE TITLE
open sans for Georgian alphabet

### ISSUE THREAD

**Issue by kaitmic** [google/fonts#1027]
Looking to use Open Sans font by Google across many languages including Georgian, which the font currently does not support. Is it possible to hire for extension of the font to further languages? Can you supply an information about the steps for this?
Thanks

**Comment by fitojb** [comment]
What you ask for already exists: [Noto Sans Georgian](https://www.google.com/get/noto/#sans-geor).

**Comment by davelab6** [comment]
@kaitmic yes, @fitojb is right; this family began as Droid Sans (regular + bold) and then was adjusted for print usage and a large range of weights + italics were drawn, and released as Open Sans; then the family was further adjusted and expanding to everything in Unicode as the Noto Fonts.
