### ISSUE TITLE
Update Old Standard

### ISSUE THREAD

**Issue by davelab6** [google/fonts#103]
@fzembow reported in https://code.google.com/p/googlefontdirectory/issues/detail?id=405 that installing OldStandard-Bold.ttf and OldStandard-Regular.ttf on Mac OSX (10.10.2) shows a strong warning from Font Book's validatot about the kern tables.

**Comment by phorust** [comment]
Any updates on this?

**Comment by alexeiva** [comment]
The TTF fonts validate fine after [v.3.000](https://github.com/alexeiva/oldstand) update.
Tested on 10.11.6 with FontBook. Fonts now install properly. 

<img width="735" alt="screen shot 2016-09-16 at 15 12 03" src="https://cloud.githubusercontent.com/assets/16634089/18586988/f195cd0e-7c1f-11e6-84d0-f2b140ab3229.png">

**Comment by laerm0** [comment]
These fonts are good now. Closing.
