### ISSUE TITLE
Oswald Cyrillic Й

### ISSUE THREAD

**Issue by m4rc1e** [google/fonts#1039]
From a mail sent to me

---
I'd like to ask for your help as a contributor to Oswald font at Google fonts.
We have issue with cyrillic version of Oswald - there is no letter "й Й" in Oswald at Google fonts. Instead of letter Й there is second letter И. Check it.
I have found corrected version with Й letter here https://fontstorage.com/font/oswald and I attached picture of letter Й in Oswald Regular.

It is extremely important for all cyrillic websites. Is it possible to fix it and bring back letter Й to Google fonts Oswald?
Thank you in advance!

![letter](https://user-images.githubusercontent.com/7525512/26970186-5c0f45e6-4d00-11e7-9419-624f5e331263.png)

**Comment by alexeiva** [comment]
Will update this next week.
@m4rcle what is the GitHub link for Oswald?

**Comment by davelab6** [comment]
@alexeiva its https://github.com/googlefonts/OswaldFont/

**Comment by davelab6** [comment]
@m4rc1e was this fixed in the VF PR?
