### ISSUE TITLE
Add Renner* font family

### ISSUE THREAD

**Issue by EwonRael** [google/fonts#1040]
https://github.com/indestructible-type/Renner

Hopefully this conforms to the standards set out by the team!

This is a passion project of mine.

**Comment by m4rc1e** [comment]
I've always loved Paul Renner's work so I'm a fan of this.

cc @davelab6

**Comment by davelab6** [comment]
Thanks for this! There is a queue at the moment for adding new fonts, but I'll review this with the GF team and keep you posted :)

**Comment by laerm0** [comment]
This is at 3.0 just recently, is variable, and looks great. I'm with @m4rc1e, let's get this one in there. Nice one @EwonRael.

**Comment by hmaesta** [comment]
This font would be a wonderful addition to Google Fonts.

**Comment by davelab6** [comment]
The non-alphabetic name is an issue; it would be onboarded as "Renner" if
it is added, not "Renner*"

**Comment by EwonRael** [comment]
That's a fair compromise for me. Or I could possibly come up with an alphabetic naming alternative.

**Comment by GitBruno** [comment]
An alternate name would be good as Renner is a trademark of Monotype GmbH

**Comment by davelab6** [comment]
Thanks for pointing that out Bruno! In the CONTRIBUTING file in this repo,
we do say we can't accept not unique names.

**Comment by EwonRael** [comment]
Could you add link to Renner as a trademark or non unique name? I'm not seeing it [registered anywhere](http://tmsearch.uspto.gov/bin/showfield?f=toc&state=4806%3Avnrhk7.1.1&p_search=searchss&p_L=50&BackReference=&p_plural=yes&p_s_PARA1=&p_tagrepl~%3A=PARA1%24LD&expr=PARA1+AND+PARA2&p_s_PARA2=Renner&p_tagrepl~%3A=PARA2%24COMB&p_op_ALL=AND&a_default=search&a_search=Submit+Query&a_search=Submit+Query) and when I search a font market place such as myFonts I'm only getting [fonts that include the word Renner](https://www.myfonts.com/fonts/linotype/renner-antiqua/), not just "Renner". 

I want to do this in the most kosher way possible, and I'm worried that I'm missing some essential step to verifying something such as a unique name.

All that being said, I want it to have some additional word/words to the name to help identify it as one coming from my foundry, so even if it was okay to call it "Renner" I'd want to name it something like "Renner indestructible" or "Renner it".

Would such a name be usable or would I have to dropped the use of "Renner" entirely?

**Comment by davelab6** [comment]
Google Fonts also doesn't accept foundry names or initials in family names;
it's caused problems in the past where there is no longer only one
contributor to a project.

Renner is asserted as a resend trademark on the page you link to. I would
prefer to avoid it.

**Comment by GitBruno** [comment]
Hope this info helps. Not sure which country they registered; might be Germany?

[Trademarks of Monotype](https://www.monotype.com/legal/trademarks/r/)

[Monotypes efforts to advertise and enforce its trademarks](https://books.google.com.au/books?id=c6IS3RnN6qAC&pg=PA47&dq=Monotypes+efforts+to+advertise+and+enforce+its+trademarks&hl=en&sa=X&ved=0ahUKEwi7xaqMzrLcAhWFTLwKHeK4C80Q6AEIKzAA#v=onepage&q=Monotypes%20efforts%20to%20advertise%20and%20enforce%20its%20trademarks&f=false)

As for naming alternative `Friedrich` or `Frankfurt`, `Frankfurt New`

**Comment by EwonRael** [comment]
I've been doing a lot of thinking about this whole situation the past couple of days because its implications to my life are sizeable. 

I would absolutely love to have my fonts added to the Google Fonts library. In part due to obvious financial and businessy reasons, but mostly because of the scale of impact. Knowing that something I created has touched the lives of millions, even in a small way, would be truly profound. 

Changing the name of Renner* to something completely different is a really smart move and one I want to make.

When I first started indestructible type* I made decisions about what it as a type foundry was, and how its brand identity would operate. I made those decisions before having any actual experience running the foundry. Now that I've been doing it a while, and I've had a couple of font releases, my ideas about mission and brand identity need to be re-examined.

On the grand scheme of things this is not that big of a deal, but to me it's a very big deal, and one that I want to make with care. 

I want to thank you, @davelab6 and @GitBruno for your guidance and patience. The suggestions for new font names are all great and clearly considered. I don't want to come across laissez-faire by not responding quickly. I care deeply and will get back to you all when I've made more progress on this decision.

**Comment by davelab6** [comment]
Thanks Owen, I super appreciate your thoughtfulness and look forward to
seeing your continued journey into the type community :)

**Comment by laerm0** [comment]
I'm glad to hear that, @EwonRael. I'm excited to help you get your work out there.

**Comment by EwonRael** [comment]
There is a point at which further consideration reveals no greater truths or options. I think I have reached that point.

I would like to rename `Renner*` `Laconic*`, or for the Google Fonts library, `Laconic`.

I really liked the name `Frankfurt`, but [it's already a font](https://www.dafont.com/frankfurt.font), and I wish for my font names to be just a single word, which rules out `Frankfurt New` and other variants. 

I am ready with a new release of the font, that addresses many of the issues being currently reported. I would like to include the name change with the 3.2 update, as well as some other changes to the brand identity of indestructible type*.

I have two questions.

1. What is the consensus on `Laconic*`? Is there some issue with the new name I am unaware of?

2. How likely is the inclusion of Laconic into the Google Fonts library? Can I explain my primary motivation for the change of name in my update newsletter, or should I stick with "intellectual property rights concerns?" The first is a mix of good and bad news instead of just bad news, but the second is safer.

I'm looking forward to it all. 

Let me know what you all think.

**Comment by m4rc1e** [comment]
Thanks for your reply.

There's https://namecheck.fontdata.com. 

I see there's already a free font using this name, https://namecheck.fontdata.com/?q=Laconic

Unfortunately, font naming is hard

**Comment by EwonRael** [comment]
Hey thanks for pointing this out Marc.

I know I made this check because the existing font on FontSquirrel is familiar to me. The fact that somehow it still ended up on my list is an embarrassing oversight! I am very glad that I checked here, though, before moving forward.

I will do my best to get back to you all by the end of the day with a better font name.

Thank you all for your patience. 

:(

**Comment by davelab6** [comment]
Subliminal advertising ;)

**Comment by EwonRael** [comment]
Hey folks!

I can't say I'm feeling too confident about this as the last couple of suggestions haven't worked out, but how do we feel about `Jost*`? This would be named after Heinrich Jost, who was instrumental in realizing Paul Renner's ideas. I can't find any other font of that name, and it would stick with the last-name theme I have going on, so I wouldn't have to rename any other fonts.

Let me know!

**Comment by davelab6** [comment]
Works for me

**Comment by EwonRael** [comment]
Okay I'll get on making the changes shortly

**Comment by EwonRael** [comment]
Okay!

The font has been updated and is now called `Jost*`!

Let me know what the next step is.

**Comment by Dabolus** [comment]
Any updates on this? Would love to see Jost* added to Google Fonts API

**Comment by tom-aniol** [comment]
Hi @EwonRael - great font! 
Is there any chance to add Jost* to Google Fonts by the end of this year?

**Comment by EwonRael** [comment]
@tom-aniol that's kind of in the hands of the folks over at Google, not myself. If I get any word on what further steps I can do on my part, you have my word I'll do best.

**Comment by dhritijain** [comment]
This is such an awesome font! Any idea as to when we can see this on Google fonts?

**Comment by dhritijain** [comment]
This is such an amazing font and addition to GF! Any idea when would this be releasing?

**Comment by dhritijain** [comment]
@EwonRael This is such an amazing font and addition to GF! Any idea when would this be releasing?

**Comment by EwonRael** [comment]
@davelab6 it's been almost two years and Jost* has seen a lot of updates, including a name change which was done specifically to accommodate Google Fonts. Any idea if/when this typeface might be included in the GF library?

**Comment by JohnJordan1985** [comment]
Just leaving a comment in support of having Jost* included in the Google Fonts library: it's an excellent evolution of the Futura typeface and I'm proud to use it on one of my sites. As much as I'd (selfishly!) like to keep its web usage low to maintain its unique, it really does deserve a wider audience.

**Comment by uncinarynin** [comment]
This is a contemporary re-interpretation of the "Futura-like geometric" style of typeface, constantly under development. I've been using it for quite some time and found it versatile, it certainly deserves being included in Google Fonts.

**Comment by Chrisfrrs** [comment]
This font is very versatile and so clean.  I love that it is variable.  Google- please add it!

**Comment by CreativeDuo-FR** [comment]
I wanted to voice the support of my wife and I for adding this font to Google Fonts. We really appreciate it as a modern interpretation of Futura for the digital age. We are web designers and this font has ended up on the list of fonts proposed to our clients for their projects several times. Its multi-language support is much appreciated as well as its 9 weights, making it a very versatile and high quality font. We hope to see it on Google Fonts soon!

**Comment by charlesroper** [comment]
Another vote for Jost on Google Fonts. It's a superb font – mind-blowing that it's free. It's my go-to geometric sans and an excellent alternative to Futura.

Btw, THANK YOU @EwonRael for putting this wonderful piece of craftsmanship out into the world. We're all better off for it. ❤️🤝

**Comment by elea** [comment]
Writing in support of Jost* being a part of Google Font offerings. The care and details incorporated make Jost* a versatile, modern, and robust geometric sans and I'd love to see more websites put it to good use!

**Comment by jsheathelm** [comment]
Would love to see the excellent Jost* font added to GF!

**Comment by m4rc1e** [comment]
I reviewed the upstream today, https://github.com/indestructible-type/Jost/issues/42. Some metadata tweaks are needed but the design is pretty good.

**Comment by ScottWerley** [comment]
It would be awesome to see the Jost* font added to the Google Fonts repository! Please consider. Thank you!

**Comment by AlfMarty** [comment]
I would love to see Jost in the Google Fonts repository. It's such a great take on a classic, I'm sure it would be widely used!

**Comment by driehuis** [comment]
@davelab6 Just wondering, you added a Needs Confirmation tag, but what's left that needs confirmation? The naming issue seems to be taken care of, the font is actively maintained but stable, and everybody seems to love this typeface to pieces. Enquiring minds want to know!

**Comment by jgajera** [comment]
WE WANT JOST*!!!

**Comment by ikeahloe** [comment]
Would love to see this added.

**Comment by fitojb** [comment]
Please stop spamming the thread.

**Comment by m4rc1e** [comment]
Jost has landed, https://fonts.google.com/specimen/Jost?vfonly

Thanks @EwonRael and @bghryct for your hard work on this.

**Comment by EwonRael** [comment]
Looks Great! My name is in all caps though which looks a little funny.

Is it possible to include link to indestructible type* website when foundry is mentioned in description?

Thanks for all the help and support this is very exciting!

**Comment by m4rc1e** [comment]
We'll roll and update in a week or two. Thanks.
