### ISSUE TITLE
Add missing cp437 characters for Inconsolata

### ISSUE THREAD

**Issue by tracker1** [google/fonts#1047]
It would be really nice to have the missing translated characters for CP437 to unicode[1] added (namely shaded blocks, box,, and other "drawing" characters), which would aid in making this a more useful font for web-based terminal emulators.

I did not go through to identify all the missing characters, but did notice quite a few that were missing.

```
0xb0	0x2591	#LIGHT SHADE
0xb1	0x2592	#MEDIUM SHADE
0xb2	0x2593	#DARK SHADE
...
0xdb	0x2588	#FULL BLOCK
0xdc	0x2584	#LOWER HALF BLOCK
0xdd	0x258c	#LEFT HALF BLOCK
0xde	0x2590	#RIGHT HALF BLOCK
0xdf	0x2580	#UPPER HALF BLOCK
```

[1] ftp://www.unicode.org/Public/MAPPINGS/VENDORS/MICSFT/PC/CP437.TXT

**Comment by davelab6** [comment]
@tracker1 thanks for suggesting this, I'm moving the discussion to the upstream repo.
