### ISSUE TITLE
Add Spectral in this repository

### ISSUE THREAD

**Issue by thlinard** [google/fonts#1061]
https://fonts.google.com/specimen/Spectral
https://github.com/productiontype/Spectral

Enhancement request (unless Spectral is an exceptional case): could the normal process be that the fonts are added here, on Google Fonts GitHub, before being put on GF?

**Comment by davelab6** [comment]
That is the normal process, this was an exception for the surprise launch
at 2017.Typographics.com

I was in the middle of checking them in but got distracted; I'll do so and
add the small caps family too

**Comment by thlinard** [comment]
OK, thanks Dave.

**Comment by davelab6** [comment]
Closing as dupicate of #1101
