### ISSUE TITLE
Hinted version of Rubik

### ISSUE THREAD

**Issue by m4rc1e** [google/fonts#1075]
I've finally managed to stitch Micah's VTT ttfs. I've written a transfer [script](https://github.com/m4rc1e/rubik/blob/hinted/sources/generate_hinted_ttfs.py) which will swap the hinted glyphs with the unhinted glyphs. It will also transfer over the relevant tables. Roboto uses a similar approach.

Here's some Win 10 render previews using GF Regression.
![rubik-bold-win10](https://user-images.githubusercontent.com/7525512/27907193-93c46428-623e-11e7-868c-563456002663.gif)
![rubik-regular-win10](https://user-images.githubusercontent.com/7525512/27907195-93e19d0e-623e-11e7-8d9a-36c1f6f28496.gif)

@davelab6 if you're happy with this, I'll file a pr. Some of the hinted cvt values have changed the x-height and cap height at certain sizes. This usually leads to complaints.

**Comment by davelab6** [comment]
Awesome! Please do

**Comment by davelab6** [comment]
Superceded by https://github.com/google/fonts/pull/1076
