### ISSUE TITLE
Changa version 2

### ISSUE THREAD

**Issue by thlinard** [google/fonts#1079]
Hi,

#271 was closed, but [Changa version 2](https://github.com/etunni/Changa) (expanded to 7 weights) is on http://fonts.google.com/ but still not here.

**Comment by davelab6** [comment]
Thanks for noting this! FontBakery has a script to diff the API and github, I am to bring the difference to zero :)

**Comment by davelab6** [comment]
@laerm0 the open PR #1090 will, when merged, auto-close this issue

**Comment by davelab6** [comment]
Done :)
