### ISSUE TITLE
Nunito-Medium is missing

### ISSUE THREAD

**Issue by hindupuravinash** [google/fonts#1081]
Is this intentionally left out or got left out by mistake? We want to migrate from existing font to Nunito but are missing the -Medium font which we use extensively.

**Comment by m4rc1e** [comment]
@hindupuravinash As far as I remember, the versions of Nunito hosted on GF have never had a Medium. I know Vernon's v2.0 has a Medium but that version is incomplete, https://github.com/vernnobile/NunitoFont/tree/master/version-2.0. 

In 2016, We took over the project from Vernon, https://github.com/googlefonts/NunitoFont. @FontHausen did much of the design work.

**Comment by hindupuravinash** [comment]
Oh, thanks for the info. Will take a look. I did find some Medium version online, but it had some bugs in rendering which made it unusable. 

@fonthausen Do you have any plans to work on the Medium version then?

**Comment by Fonthausen** [comment]
Hello @hindupuravinash. 

Nunito now has 7 Roman and 7 Italic weights. The SemiBold weight will probably be the one you are looking for. The weights are now named according to the latest W3C standards.

If you still need the original Nunito Medium, you can download it and host it locally on your web server.

**Comment by davelab6** [comment]
@Fonthausen is your thinking that the Medium that is possible between the Regular and SemiBold is not dissimilar enough to be worthwhile? 

@hindupuravinash can you migrate to the SemiBold?

**Comment by Fonthausen** [comment]
Hi Dave,

> @Fonthausen is your thinking that the Medium that is possible between the Regular and SemiBold is not dissimilar enough to be worthwhile?

I had a look at the weight/stroke of the original Medium compared to the new Nunito. 
The weight of the original Nunito Medium was ≈ 98. The new Nunito SemiBold = 101. (Regular = 81, Bold = 125)

The difference can almost be neglected.

**Comment by davelab6** [comment]
I'm satisfied with that :)

**Comment by davelab6** [comment]
Closing as @hindupuravinash can migrate to the SemiBold :)
