### ISSUE TITLE
Rubik italics: opening question mark is excessively slanted

### ISSUE THREAD

**Issue by fitojb** [google/fonts#1097]
The glyph _¿_ in Rubik's italic styles is too slanted w.r.t. the rest of the characters. In addition, its advance width is insufficient and makes this puctuation mark adhere too much to the following letter. See this screenshot.

![rubik s question marks](https://user-images.githubusercontent.com/554953/28509517-8c5b39e6-7008-11e7-9de8-8845644ea9b4.png)

**Comment by davelab6** [comment]
@m4rc1e was this solved in the update that just rolled back?

**Comment by fitojb** [comment]
This is still reproducible.
