### ISSUE TITLE
Add Open Sans

### ISSUE THREAD

**Issue by crispinbixler** [google/fonts#11]
Open Sans is missing, please add :)

**Comment by adrientetar** [comment]
https://www.google.com/fonts/specimen/Open+Sans
&
https://github.com/google/fonts/tree/master/apache/opensans

?

It is one of the most viewed fonts on GWF.

**Comment by davelab6** [comment]
@crispinbixler where do you expect it? :)

**Comment by rsheeter** [comment]
To clarify, it is not the intent for paths in this repo to mirror the paths on www.google.com/fonts. Here the fonts should be under`license/family`, hence apache/opensans.

**Comment by crispinbixler** [comment]
Ok, makes sense. I'm a beginner and sometimes the wording of things goes over my head even though as I re-read the README it makes perfect sense. I just jumped in too quickly and only looked in the ofl and ufl folders and didn't check apache! Thanks for the clue :) :)
