### ISSUE TITLE
Repo has fonts that are not present on fonts.google.com

### ISSUE THREAD

**Issue by poiru** [google/fonts#1102]
The following PostScript names are present in font files in this repo, but are not present in the font files from the Google Fonts API (https://www.googleapis.com/webfonts/v1/webfonts). Is this intentional?

This mismatch makes it really difficult to use this repo. We were using the API to fetch fonts, but we recently switched back to the repo because we thought it was in sync again. It seems like that is not the case. (See also #1101.)

* AbyssinicaSIL-Regular
* AdobeBlank-Regular
* AksaraBaliGalang-Regular
* AlmendraSC-Bold
* AlmendraSC-BoldItalic
* AlmendraSC-Italic
* AmstelvarAlpha-Default
* Andada-Bold
* Andada-BoldItalic
* Andada-Italic
* AndadaSC-Bold
* AndadaSC-BoldItalic
* AndadaSC-Italic
* AndadaSC-Regular
* Antonio-Bold
* Antonio-Light
* Antonio-Regular
* Archivo-Bold
* Archivo-BoldItalic
* Archivo-Italic
* Archivo-Medium
* Archivo-MediumItalic
* Archivo-Regular
* Archivo-SemiBold
* Archivo-SemiBoldItalic
* ArchivoVFBeta-Italic
* ArchivoVFBeta-Regular
* AsapCondensed-Bold
* AsapCondensed-BoldItalic
* AsapCondensed-Italic
* AsapCondensed-Medium
* AsapCondensed-MediumItalic
* AsapCondensed-Regular
* AsapCondensed-SemiBold
* AsapCondensed-SemiBoldItalic
* AsapVFBeta-Condensed
* AsapVFBeta-Italic
* AsapVFBeta-Regular
* BalooTammudu-Regular
* Bhavuka-Regular
* BMHANNA
* BrunoAce-Regular
* BrunoAceSC-Regular
* ButchermanCaps-Regular
* CabinVFBeta-Italic
* CabinVFBeta-Regular
* Clara-Regular
* Corben-Bold
* CreepsterCaps-Regular
* cwTeXFangSong
* cwTeXHei
* cwTeXKai
* cwTeXMing
* cwTeXYen
* Dhyana-Bold
* Dhyana-Regular
* DigitalNumbers-Regular
* Dinah-VAA
* DinahVAA-Bold
* DosisVFBeta-Light
* DroidArabicKufi
* DroidArabicKufi-Bold
* DroidArabicNaskh
* DroidArabicNaskh-Bold
* DroidSansEthiopic
* DroidSansEthiopic-Bold
* DroidSansJapanese
* DroidSansTamil
* DroidSansTamil-Bold
* DroidSansThai
* DroidSansThai-Bold
* DroidSerifThai
* DroidSerifThai-Bold
* EaterCaps-Regular
* EncodeSans-Black
* EncodeSans-Bold
* EncodeSans-ExtraBold
* EncodeSans-ExtraLight
* EncodeSans-Light
* EncodeSans-Medium
* EncodeSans-Regular
* EncodeSans-SemiBold
* EncodeSans-Thin
* EncodeSansCondensed-Black
* EncodeSansCondensed-Bold
* EncodeSansCondensed-ExtraBold
* EncodeSansCondensed-ExtraLight
* EncodeSansCondensed-Light
* EncodeSansCondensed-Medium
* EncodeSansCondensed-Regular
* EncodeSansCondensed-SemiBold
* EncodeSansCondensed-Thin
* EncodeSansExpanded-Black
* EncodeSansExpanded-Bold
* EncodeSansExpanded-ExtraBold
* EncodeSansExpanded-ExtraLight
* EncodeSansExpanded-Light
* EncodeSansExpanded-Medium
* EncodeSansExpanded-Regular
* EncodeSansExpanded-SemiBold
* EncodeSansExpanded-Thin
* EncodeSansSemiCondensed-Black
* EncodeSansSemiCondensed-Bold
* EncodeSansSemiCondensed-ExtraBold
* EncodeSansSemiCondensed-ExtraLight
* EncodeSansSemiCondensed-Light
* EncodeSansSemiCondensed-Medium
* EncodeSansSemiCondensed-Regular
* EncodeSansSemiCondensed-SemiBold
* EncodeSansSemiCondensed-Thin
* EncodeSansSemiExpanded-Black
* EncodeSansSemiExpanded-Bold
* EncodeSansSemiExpanded-ExtraBold
* EncodeSansSemiExpanded-ExtraLight
* EncodeSansSemiExpanded-Light
* EncodeSansSemiExpanded-Medium
* EncodeSansSemiExpanded-Regular
* EncodeSansSemiExpanded-SemiBold
* EncodeSansSemiExpanded-Thin
* EncodeSansVFBeta-CondensedLight
* Exo-SemiBold
* Exo-SemiBoldItalic
* Faustina-Bold
* Faustina-BoldItalic
* Faustina-Italic
* Faustina-Medium
* Faustina-MediumItalic
* Faustina-Regular
* Faustina-SemiBold
* Faustina-SemiBoldItalic
* FaustinaVFBeta-Italic
* FaustinaVFBeta-Regular
* GemunuLibre-Bold
* GemunuLibre-ExtraBold
* GemunuLibre-ExtraLight
* GemunuLibre-Light
* GemunuLibre-Medium
* GemunuLibre-Regular
* GemunuLibre-SemiBold
* Hannari-Regular
* HermeneusOne-Regular
* HindColombo-Bold
* HindColombo-Light
* HindColombo-Medium
* HindColombo-Regular
* HindColombo-SemiBold
* HindJalandhar-Bold
* HindJalandhar-Light
* HindJalandhar-Medium
* HindJalandhar-Regular
* HindJalandhar-SemiBold
* HindKochi-Bold
* HindKochi-Light
* HindKochi-Medium
* HindKochi-Regular
* HindKochi-SemiBold
* HindMysuru-Bold
* HindMysuru-Light
* HindMysuru-Medium
* HindMysuru-Regular
* HindMysuru-SemiBold
* IndieFlower-Regular
* IrishGrowler
* JejuGothic
* JejuHallasan
* JejuMyeongjo
* Jomolhari
* JosefinSansStd-Light
* jsMath-cmbx10
* jsMath-cmex10
* jsMath-cmmi10
* jsMath-cmr10
* jsMath-cmsy10
* jsMath-cmti10
* KarlaTamilInclined-Bold
* KarlaTamilInclined-Regular
* KarlaTamilUpright-Bold
* KarlaTamilUpright-Regular
* Kokoro-Regular
* KoPubBatang-Bold
* KoPubBatang-Light
* KoPubBatang-Regular
* LaoMuangDon
* LaoMuangKhong
* LaoSansPro
* Lato-ExtraBold
* Lato-ExtraBoldItalic
* Lato-ExtraLight
* Lato-ExtraLightItalic
* Lato-Medium
* Lato-MediumItalic
* Lato-SemiBold
* Lato-SemiBoldItalic
* Lato-Thin
* Lato-ThinItalic
* LibreCaslonText-Bold
* LibreCaslonText-Italic
* LibreCaslonText-Regular
* LifeSavers-ExtraBold
* Lohit-Bengali
* Lohit-Devanagari
* Lohit-Tamil
* Maitree-Regular
* Manuale-Bold
* Manuale-BoldItalic
* Manuale-Italic
* Manuale-Medium
* Manuale-MediumItalic
* Manuale-Regular
* Manuale-SemiBold
* Manuale-SemiBoldItalic
* ManualeVFBeta-Italic
* ManualeVFBeta-Regular
* MavenProVFBeta-Regular
* MergeOne-Regular
* MervaleScript-Regular
* Miama-Regular
* Mina-Bold
* Mina-Regular
* Mplus1p-Black
* Mplus1p-Bold
* Mplus1p-ExtraBold
* Mplus1p-Light
* Mplus1p-Medium
* Mplus1p-Regular
* Mplus1p-Thin
* Mukta-Bold
* Mukta-ExtraBold
* Mukta-ExtraLight
* Mukta-Light
* Mukta-Medium
* Mukta-Regular
* Mukta-SemiBold
* MuktaMahee-Bold
* MuktaMahee-ExtraBold
* MuktaMahee-ExtraLight
* MuktaMahee-Light
* MuktaMahee-Medium
* MuktaMahee-Regular
* MuktaMahee-SemiBold
* MuktaMalar-Bold
* MuktaMalar-ExtraBold
* MuktaMalar-ExtraLight
* MuktaMalar-Light
* MuktaMalar-Medium
* MuktaMalar-Regular
* MuktaMalar-SemiBold
* MyanmarKhyay
* MyanmarSansPro
* NanumBrush
* NanumGothic
* NanumGothic-Bold
* NanumGothic-ExtraBold
* NanumGothicCoding
* NanumGothicCoding-Bold
* NanumMyeongjo
* NanumMyeongjoBold
* NanumMyeongjoExtraBold
* NanumPen
* NATS
* NicoMoji-Regular
* Nikukyu-Regular
* Nobile-Medium
* Nobile-MediumItalic
* NosiferCaps-Regular
* NunitoSansVFBeta-Light
* NunitoVFBeta-Light
* OFLGoudyStMTT
* OFLGoudyStMTT-Italic
* OpenSansHebrew-Bold
* OpenSansHebrew-BoldItalic
* OpenSansHebrew-ExtraBold
* OpenSansHebrew-Italic
* OpenSansHebrew-Light
* OpenSansHebrew-LightItalic
* OpenSansHebrew-Regular
* OpenSansHebrewCondensed-Bold
* OpenSansHebrewCondensed-BoldItalic
* OpenSansHebrewCondensed-ExtraBold
* OpenSansHebrewCondensed-Italic
* OpenSansHebrewCondensed-Light
* OpenSansHebrewCondensed-Regular
* OpenSansHebrewCondensedExtraBold-Italic
* OpenSansHebrewCondensedLight-Italic
* OpenSansHebrewExtraBold-Italic
* OswaldVFBeta-Regular
* OverpassVFBeta-Italic
* OverpassVFBeta-Regular
* Pecita
* Phetsarath-Bold
* Phetsarath-Regular
* PodkovaVFBeta-Regular
* PoetsenOne-Regular
* Ponnala
* PorterSansBlock
* PostNoBillsColombo-Bold
* PostNoBillsColombo-ExtraBold
* PostNoBillsColombo-Light
* PostNoBillsColombo-Medium
* PostNoBillsColombo-Regular
* PostNoBillsColombo-SemiBold
* PostNoBillsJaffna-Bold
* PostNoBillsJaffna-ExtraBold
* PostNoBillsJaffna-Light
* PostNoBillsJaffna-Medium
* PostNoBillsJaffna-Regular
* PostNoBillsJaffna-SemiBold
* RalewayVFBeta-Regular
* RedactedRegular
* RedactedScriptBold
* RedactedScriptRegular
* RokkittVFBeta-Regular
* RoundedMplus1c-Black
* RoundedMplus1c-Bold
* RoundedMplus1c-ExtraBold
* RoundedMplus1c-Light
* RoundedMplus1c-Medium
* RoundedMplus1c-Regular
* RoundedMplus1c-Thin
* RubikOne-Regular
* Saira-Black
* Saira-Bold
* Saira-ExtraBold
* Saira-ExtraLight
* Saira-Light
* Saira-Medium
* Saira-Regular
* Saira-SemiBold
* Saira-Thin
* SairaCondensed-Black
* SairaCondensed-Bold
* SairaCondensed-ExtraBold
* SairaCondensed-ExtraLight
* SairaCondensed-Light
* SairaCondensed-Medium
* SairaCondensed-Regular
* SairaCondensed-SemiBold
* SairaCondensed-Thin
* SairaExtraCondensed-Black
* SairaExtraCondensed-Bold
* SairaExtraCondensed-ExtraBold
* SairaExtraCondensed-ExtraLight
* SairaExtraCondensed-Light
* SairaExtraCondensed-Medium
* SairaExtraCondensed-Regular
* SairaExtraCondensed-SemiBold
* SairaExtraCondensed-Thin
* SairaSemiCondensed-Black
* SairaSemiCondensed-Bold
* SairaSemiCondensed-ExtraBold
* SairaSemiCondensed-ExtraLight
* SairaSemiCondensed-Light
* SairaSemiCondensed-Medium
* SairaSemiCondensed-Regular
* SairaSemiCondensed-SemiBold
* SairaSemiCondensed-Thin
* Sansation-Bold
* Sansation-BoldItalic
* Sansation-Italic
* Sansation-Light
* Sansation-LightItalic
* Sansation-Regular
* SansitaOne-Regular
* SansitaVFBeta-Italic
* SansitaVFBeta-Regular
* Sarabun
* Sarabun-Bold
* Sarabun-BoldItalic
* Sarabun-Italic
* SawarabiGothic-Regular
* SawarabiMincho-Regular
* Sedan-Italic
* Sedan-Regular
* SedanSC-Regular
* SeH-CB
* SeH-CBL
* SeH-CEB
* SeH-CL
* SeH-CM
* SeN-CB
* SeN-CBL
* SeN-CEB
* SeN-CL
* SeN-CM
* SeoulHangangB
* SeoulHangangEB
* SeoulHangangL
* SeoulHangangM
* SeoulNamsanB
* SeoulNamsanEB
* SeoulNamsanL
* SeoulNamsanM
* SeoulNamsanvert
* Sitara-Bold
* Sitara-BoldItalic
* Sitara-Italic
* Sitara-Regular
* SouliyoUnicode
* SourceCodePro-SemiBold
* SourceSerifPro-Black
* SourceSerifPro-ExtraLight
* SourceSerifPro-Light
* SourceSerifPro-SemiBold
* StalinOne-Regular
* Strong-Regular
* TerminalDosis-Light
* Thabit
* Thabit-Bold
* Thabit-Bold-Oblique
* Thabit-Oblique
* TharLon
* Tuffy-Bold
* Tuffy-BoldItalic
* Tuffy-Italic
* Tuffy-Regular
* UnnaVFBeta-Regular
* Varta-Bold
* Varta-Light
* Varta-Regular
* Varta-SemiBold
* Vollkorn-Black
* Vollkorn-BlackItalic
* Vollkorn-SemiBold
* Vollkorn-SemiBoldItalic
* YaldeviColombo-Bold
* YaldeviColombo-ExtraLight
* YaldeviColombo-Light
* YaldeviColombo-Medium
* YaldeviColombo-Regular
* YaldeviColombo-SemiBold
* YanoneKaffeesatzVFBeta-Light
* Yinmar-Regular

**Comment by poiru** [comment]
cc @m4rc1e

**Comment by m4rc1e** [comment]
@poiru The fonts on fonts.google.com and the repo are in the process of being synced. When a pr is merged in the repo, it still needs to be pushed into production. Most of the fonts you've listed are in the process of being pushed into production.

Feel free to email me what you need to accomplish?
I'd be more than happy to help.

**Comment by poiru** [comment]
@m4rc1e In that case, I'll go ahead and close this PR. Note that #1101 is still a problem.
