### ISSUE TITLE
Issue loading the site in Chrome 60

### ISSUE THREAD

**Issue by alexciarlillo** [google/fonts#1105]
This is quite a strange one. For some reason - only on my desktop - I cannot get this site to load. I am running identical versions of Chrome (60) on identical versions of Linux (Mint 18.2) and I only get this error on my desktop. I have uninstalled/purged chrome, reinstalled from the latest .deb and have wiped my profile directory. 

![screenshot on fresh install, no profile](https://user-images.githubusercontent.com/656039/28677703-558a93ba-72bc-11e7-9ac1-107270cdde64.png)

Not sure what else I can add, but happy to include any further information as requested.

**Comment by davelab6** [comment]
@alexciarlillo thanks for reporting this! Will take a look

**Comment by shyndman** [comment]
Hi @alexciarlillo,

Mind taking a screenshot of your network panel?

**Comment by alexciarlillo** [comment]
@davelab6, @shyndman - good news and bad news. Good news is I resolved the problem. The bad news is I was not very careful during my experimentation and lost track of what exact change fixed it. I can tell you that this was related to font configurations on my local machine and was limited to Chromium and Chrome installs. I strongly believe it was tied to an installation of "Infanality" fonts which is a popular package of fontconfig settings for linux. I even tried going back and restoring some files to see if I could re-create the issue but was unable to. Sorry - I know this is *the* worst kind of bug report. I appreciate you looking into it.

**Comment by shyndman** [comment]
Bizarre.

That exception occurs when [Adobe Blank](https://github.com/adobe-fonts/adobe-blank) fails to load. Does that bring anything to mind?

**Comment by alexciarlillo** [comment]
Nope, sorry. I do have Adobe Source Code Pro installed which should include Adobe Blank I think? But I did not have this font enabled for any part of my system at the time of the issue.

**Comment by shyndman** [comment]
I tried with a locally installed Adobe Blank, and was unable to reproduce.

Dave/Alex, how much do you know about Infanality? Do you know of any Linux font settings that may impact the width of characters? I know that sounds a little strange, but it's now I detect that Adobe Blank loads successfully.

**Comment by davelab6** [comment]
@Infinality worked on freetype to improve the rendering quality, and that could likely effect the way Adobe Blank renders.... But I'm not sure on any more specifics than that. @lemzwerg might know more

**Comment by lemzwerg** [comment]
'Infinality' is both a special fontconfig configuration *and* a quite large patch to (a meanwhile quite old version of) FreeType.  If you only have the former, nothing special will happen, I believe...

I don't know which GNU/Linux distribution still provides the Infinality changes, since its author no longer maintains it.

**Comment by alexciarlillo** [comment]
Yes, I do believe Infanility is considered deprecated so this really may be a non-issue. It was a hold over from when I first setup this desktop some years ago. When I realized my laptop was unaffected, I went through my packages and rc files and found that this was the only difference which led me to removing it and clearing up the problem.

**Comment by davelab6** [comment]
cool - glad we got to the bottom of this :)

**Comment by Infinality** [comment]
The Infinality changes that were merged into Freetype should be OK and not cause issues like this, but the patch with the more "wild" code in it (not merged into Freetype but still floating around) could very well cause this.  If you do have that installed, you could set the environment variables to disable stem snapping and other tweaks.
