### ISSUE TITLE
Roboto-regular and -bold contain redundant cmap_format_12 table?

### ISSUE THREAD

**Issue by Ziriax** [google/fonts#111]
When inspected using Google's TTX, the Roboto Regular and Bold fonts contain a cmap_format_12 table. 

However, the content of this table is exactly the same as the cmap_format_4 table.

Furthermore, the presence of this table seems to cause problems with the Win32 API CreateFontPackage

**Comment by davelab6** [comment]
Please report to https://github.com/google/roboto :)

**Comment by Ziriax** [comment]
Ouch, mea culpa  :-)
