### ISSUE TITLE
Alfa Slab not rendering properly

### ISSUE THREAD

**Issue by olgageletina** [google/fonts#1125]
It appears the type face has a stroke, particularly when rendered against a dark background:
https://codepen.io/geletina/pen/EvWKaP

Any thoughts?

Thank you!

**Comment by kalapi** [comment]
Hello @olgageletina 

Could you elaborate on what you mean by 'stroke'? This is the preview for me on Safari Version 10.1.1 (11603.2.5) on OSX El Capitan (v. 10.11.6).

![screen shot 2017-08-08 at 3 57 07 pm](https://user-images.githubusercontent.com/15804460/29067981-7e5b196e-7c52-11e7-8392-15cbd7110bdb.png)

Many thanks!

**Comment by olgageletina** [comment]
Thank you for responding! Indeed the rendering is quite different from the one displayed in google fonts: https://fonts.google.com/specimen/Alfa+Slab+One. The weight appears to be thicker. However, I was able to figure out that despite being a display font, adding a CSS font-weight property: 100 seems to work: https://codepen.io/geletina/pen/EvWKaP

**Comment by davelab6** [comment]
What you are seeing is the browser applying font-weight:bold to the h1 as part of its 'default styling' - its standard practice for web designers to use https://www.google.com/search?q=css+reset techniques to prevent this.

When a font doesn't have a 'true' bold (700) weight, the browser will "auto bold" by using some kind of stroking or double-printing method.

**Comment by davelab6** [comment]
What you are seeing is the browser applying font-weight:bold to the h1 as
part of its 'default styling' - its standard practice for web designers to
use https://www.google.com/search?q=css+reset techniques to prevent this.

When a font doesn't have a 'true' bold (700) weight, the browser will "auto
bold" by using some kind of stroking or double-printing method.
