### ISSUE TITLE
Black Ops One "R" overlap

### ISSUE THREAD

**Issue by davelab6** [google/fonts#1131]
https://fonts.google.com/specimen/Black+Ops+One has a winding direction bug (or perhaps a lack of overlap removal bug) on the "R"

![screen shot 2017-08-08 at 17 25 46](https://user-images.githubusercontent.com/261579/29095405-b6c2b1de-7c5e-11e7-982c-7b471859efc8.png)

cc @EbenSorkin

**Comment by Hackgets** [comment]
Why has this problem been left unaddressed for so long?

**Comment by EbenSorkin** [comment]
I can probably fix it this week - but getting it published again will take longer I think.

**Comment by EbenSorkin** [comment]
I fixed this today and I'll see about getting it live next.

-e.
