### ISSUE TITLE
Update Aref Ruqaa to 0.8

### ISSUE THREAD

**Issue by khaledhosny** [google/fonts#1132]
This fixes the bad Latin spacing:
https://github.com/alif-type/aref-ruqaa/releases/tag/v0.8

**Comment by davelab6** [comment]
Thank you Khaled! @m4rc1e updated this recently so should be quick to work on again :)

**Comment by khaledhosny** [comment]
Any progress on this?

**Comment by thlinard** [comment]
https://github.com/alif-type/aref-ruqaa/releases/tag/v0.9 now.

**Comment by khaledhosny** [comment]
Finally updated!
