### ISSUE TITLE
Telex has wrong family name

### ISSUE THREAD

**Issue by Ziriax** [google/fonts#114]
Is has the  family name "Telex-regular", but should just be called "Telex"?

**Comment by rsheeter** [comment]
Good catch, thank you. Filed #115 as a broader version of this as there are a number of fonts with issues of this nature. Closing this one and tracking via #115.

**Comment by m4rc1e** [comment]
Hey,

I have rebuilt [Telex](https://github.com/m4rc1e/Telex) Family names now match the [gf-checklist.md spec](https://github.com/googlefonts/gf-docs/blob/master/ProjectChecklist.md).

![screen shot 2016-09-01 at 11 59 11](https://cloud.githubusercontent.com/assets/7525512/18163535/be191d04-703b-11e6-947b-eb3a8eab3bc9.png)

Cheers,
Marc
