### ISSUE TITLE
Update fontTools

### ISSUE THREAD

**Issue by scheinercc** [google/fonts#1141]
As per https://bugzilla.mozilla.org/show_bug.cgi?id=1331797#c41 this change[1] in fontTools is required for Firefox with `gfx.downloadable_fonts.otl_validation` set to `true` to display GF again.

Is there any rough estimate when this change might find its way into production?

Thanks!

[1] https://github.com/fonttools/fonttools/commit/6eb807b55f4fcc55a9b5fd8f3e320c89428462dd

**Comment by davelab6** [comment]
The version of fontTools used by the API is updated from time to time, family by family. Sadly I can't give any estimates, but I will close this issue when this is fully resolved.

**Comment by scheinercc** [comment]
Thanks Dave!

**Comment by davelab6** [comment]
Its done :)

**Comment by scheinercc** [comment]
Thank you!
