### ISSUE TITLE
The web page about the Carlito font does not work.

### ISSUE THREAD

**Issue by Ganton** [google/fonts#1142]
Dear Sirs:

The web page ( https://fonts.google.com/specimen/Carlito ) about the Carlito font does not work.

Thanks!

**Comment by laerm0** [comment]
It looks like the API isn't pulling this font anymore, as fontbakery-family-html-snippet.py can't get it anymore as well.

**Comment by thlinard** [comment]
And https://fonts.google.com/specimen/Caladea too.

Why Carlito and Caladea have been deleted?

**Comment by m4rc1e** [comment]
I don't think Carlito has ever been served by Google Fonts. Possibly the same situation with Caladea as well. We can't just remove a font family.

**Comment by thlinard** [comment]
Oh, sorry, I assumed the links given in https://en.wikipedia.org/wiki/Croscore_fonts worked in the past.

**Comment by Ganton** [comment]
> Oh, sorry, I assumed the links given in https://en.wikipedia.org/wiki/Croscore_fonts worked in the past.

Yes, https://fonts.google.com/specimen/Carlito worked in the past, I downloaded those fonts from there (when I needed their files), but... this time didn't work.

**Comment by laerm0** [comment]
So I guess if these were never really here, can we close this issue?

**Comment by davelab6** [comment]
I can categorically state that those fonts were never checked into the GF system; however they were distributed as a part of ChromiumOS and are available from other distributors (eg https://fontlibrary.org/en/font/carlito)

**Comment by samboy** [comment]
The best place to get those fonts is on the Debian pages: https://packages.debian.org/search?keywords=fonts-crosextra-carlito and https://packages.debian.org/search?keywords=fonts-crosextra-caladea
