### ISSUE TITLE
Exo 2 has two swapped Cyrillic characters

### ISSUE THREAD

**Issue by laerm0** [google/fonts#1151]
The outlines (or code points) for ћ (0x045B) and ђ (0x0452) need to be swapped. Typing one produces the other and vice versa.

https://code.google.com/archive/p/googlefontdirectory/issues/319

**Comment by m4rc1e** [comment]
Thanks for reporting these @laerm0

**Comment by davelab6** [comment]
@ndiscover please could you take a look at this?

**Comment by NDISCOVER** [comment]
Fixed long ago in the last uptade we have on our GitHub.

**Comment by zlaja** [comment]
Um, not fixed, it's still there

**Comment by m4rc1e** [comment]
We recently pushed an update. It's now fixed.

<img width="592" alt="Screenshot 2019-10-01 at 09 55 49" src="https://user-images.githubusercontent.com/7525512/65948201-aee0a880-e431-11e9-98e2-456483423027.png">
