### ISSUE TITLE
Droid Arabic Kufi missing period (0x002E)

### ISSUE THREAD

**Issue by laerm0** [google/fonts#1152]
The period is missing. I think it's in GFont's subset, but it's definitely missing from the fonts.

https://code.google.com/archive/p/googlefontdirectory/issues/335

**Comment by davelab6** [comment]
Droid fonts are deprecated and unmaintained; the solution for existing users will be to hotfix this and remove it from the (early access) directory

**Comment by laerm0** [comment]
Closing re @davelab6's comment on the unmaintained status.
