### ISSUE TITLE
Exo 2 upright weights have defective × (0x00D7)

### ISSUE THREAD

**Issue by laerm0** [google/fonts#1153]
(an accidental enter in the title field submits the issue?)

Exo 2's upright weights have just a single slash for the multiplication sign.

https://code.google.com/archive/p/googlefontdirectory/issues/352

**Comment by davelab6** [comment]
<img width="197" alt="screen shot 2017-11-12 at 23 48 38" src="https://user-images.githubusercontent.com/261579/32710156-06bc9fd8-c804-11e7-99d8-05bf6e3b101f.png">

@ndiscover please could you take a look at this? :)

**Comment by NDISCOVER** [comment]
Fixed long ago in the last update we have on our GitHub.

**Comment by m4rc1e** [comment]
Issue fixed in latest release.

<img width="432" alt="Screenshot 2019-10-01 at 09 52 00" src="https://user-images.githubusercontent.com/7525512/65947929-2a8e2580-e431-11e9-9b4a-c15e9991c985.png">
