### ISSUE TITLE
EB Garamond Registered Mark sized too small

### ISSUE THREAD

**Issue by laerm0** [google/fonts#1156]
It's not very readable at text sizes.

<img width="97" alt="screen region 2017-08-22 at 09 43 11" src="https://user-images.githubusercontent.com/10780161/29571296-71efb91a-871e-11e7-8f38-4ca960fb8ebc.png">

https://code.google.com/archive/p/googlefontdirectory/issues/190

**Comment by thlinard** [comment]
Fixed in https://github.com/octaviopardo/EBGaramond12

**Comment by davelab6** [comment]
Closing as fixed upstream; update request tracked in #85
