### ISSUE TITLE
Font request: DejaVu

### ISSUE THREAD

**Issue by laerm0** [google/fonts#1158]
The [license](https://dejavu-fonts.github.io/License.html) is neither SIL nor Apache but it looks good.

Source is available on [sourceforge](https://sourceforge.net/projects/dejavu/files/dejavu/2.37/dejavu-fonts-2.37.tar.bz2/download).

https://code.google.com/archive/p/googlefontdirectory/issues/377

**Comment by davelab6** [comment]
As a rule we will only onboard fonts under OFL going forwards, but will accept Apache fonts under special circumstances. 

DejaVu has a complex licensing situation - many parts are "public domain" which is unwise (eg https://meshedinsights.com/2017/03/16/public-domain-is-not-open-source/) - and we can't onboard it.
