### ISSUE TITLE
Oxygen Sans kerning + update

### ISSUE THREAD

**Issue by laerm0** [google/fonts#1161]
Oxygen Sans has no kerning and some pairs conglutinate, such as l. (as reported originally [here](https://code.google.com/archive/p/googlefontdirectory/issues/267)).

[Source](https://github.com/KDE/oxygen-fonts) has no kerning. Vern Nobile has forked Oxygen and updated it as Comme ([source](https://github.com/vernnobile/commeFont)). Comme also has no kerning. 

We could add kerning to Oxygen, or we could add it to Comme when we add the family to GFonts. The latter makes more sense to me. Thoughts?

**Comment by emmamarichal** [comment]
**Notes**
When I inspect the current version on the API, I can see some kerning. The 'l." is a bit tighter than the 't.' indeed, but the rest of the font looks fine I think. 
I added Comme anyways, with kerning: https://github.com/google/fonts/pull/6081
<img width="948" alt="Capture d’écran 2023-04-06 à 12 01 18" src="https://user-images.githubusercontent.com/64773544/230345589-3162e910-98f1-4589-bf90-a5077df20e6b.png">
<img width="374" alt="Capture d’écran 2023-04-06 à 12 01 36" src="https://user-images.githubusercontent.com/64773544/230345604-a0c16c48-c61c-42ae-865a-e47abddba717.png">

**Comment by chrissimpkins** [comment]
This project does not have sources and we cannot modify the kerning.  Will not fix.

**Comment by fitojb** [comment]
> This project does not have sources

False. SFD might not be Glyphs, but that does *not* mean it isn’t a source format.
