### ISSUE TITLE
Add Interface

### ISSUE THREAD

**Issue by davelab6** [google/fonts#1167]
https://github.com/rsms/interface/issues/12

**Comment by rsms** [comment]
😃🎉

**Comment by codeman38** [comment]
Likely needs a rename in order to avoid another "Clear Sans" issue (#4). Went ahead and filed a ticket about that: https://github.com/rsms/interface/issues/15

**Comment by rsms** [comment]
Version 1.2 released https://github.com/rsms/interface/releases/tag/v1.2 and I think it's a good start.

**Comment by m4rc1e** [comment]
Another good spot @codeman38! this definitely needs a rename

**Comment by rsms** [comment]
Since there's no existing "interface" font on google fonts, I don't see why we would need to rename it.

"InterFace" from Dalton Maag is commercial and not available from google fonts, so there really shouldn't be a scenario where someone loads "InterFace" and "Interface" from google fonts at the same time (and thus gets a case-insensitive mismatch in CSS in web browsers.) Renaming the family would just be too much work and pain for a hobby project, and a bit too late into it already being used in quite a few places.

**Comment by m4rc1e** [comment]
@rsms Interface is a pretty popular DaMa typeface (used to work there a few years back). Many designers will have this family installed via typekit. 

Sorry if this sounds like sucking eggs. Some browsers will use a local font over the web font. Admittedly I'm not sure the case sensitivity difference will cause a problem here.

I also don't know if DaMa has trademarked this name?

If you and @davelab6 are happy using Inferface, then I have no problem. 

Just thought I'd point out my concerns. Nice family btw.

**Comment by m4rc1e** [comment]
Just checked out DaMa's legal info, https://www.daltonmaag.com/legal. InterFace is trademarked. They're a friendly bunch so I'd give them a call.

**Comment by rsms** [comment]
@m4rc1e Self-proclaimed trademarks (™) is simply saying "I'm using this as a trade mark." Registered trade marks (®) is a different thing and does bear legal weight, and are thus copyrighted names (within the area where it's registered.) Additionally common words and names can't be copyrighted (an in effect can't be claimed as registered trademarks) in most countries, including the USA. (See https://www.copyright.gov/circs/circ34.pdf)

If you work at Dalton Maag, feel free to DM me and we can have a conversation in private if you are uncomfortable with other people also using common English words.

Let's not have a flame war here. You've made your point.

**Comment by dm-dama** [comment]
@rsms Hi Rasmus,

InterFace is a *registered* trademark of Dalton Maag across various typeface and font classes (EUIPO number 007159544 https://euipo.europa.eu/eSearch/#details/trademarks/007159544 ).

The document you cite is about copyright, not trademarks, despite the brief mention on the second page. There's no bar on "common" words being registered as trademarks (think "Dove", "Bounce", etc.) only that they're not a literal description of the goods they're applied to, and you have to be first to apply.

Likewise a trademark holder can't object to every use of the word, only when it's actively attached to something related in a way that's confusable.

In this case you've attached our font-related registered trademark to a different font, so we're going to have to ask you to change the name of this project to something that's not this close to any of our registered trademarks.

We appreciate that naming fonts is hard. We go through it every time we have a new release.

Thanks
David

**Comment by davelab6** [comment]
Namecheck.fontdata.com has a handy database of typeface names. 

When the family is renamed, please file a new issue :)

**Comment by rsms** [comment]
It's a hobby project that I spend my free time at nights and weekend on. It's a huge deal to rename it and I simply don't want to spend all that time renaming it.

Feel free to reopen this issue if you'd like to have it added to Google fonts 🙂

If you feel strongly about including it in Google fonts, we can rename the family specifically for Google fonts (like "Interface 2", "Interface (other)", etc.) It would remain "Interface" everywhere else, but at least it wouldn't conflict in Google fonts.

**Comment by vitya2nd** [comment]
There aren't a hobby project. I do not know google's special naming conventions. I would like that this font would be in the Noto project. I agree change font family name. There are several free e-books on website mek.oszk.hu (without www!) used Old-Hungarian glyps, but some of them used pdf format with non correct codepoints. Who wrote, doesn't a font-specialist. I want to help them.

**Comment by dm-dama** [comment]
@rsms Hi Rasmus,

To be clear, we are asking that you change the name of the distributed typeface and its project everywhere, not just in Google Fonts, as it is identical to our registered trademark, see above.

"Interface 2" and "Interface (other)" would still be unacceptably close, but there are other variations which we would regard as distinct enough to be non-confusable, e.g. "UserInterface".

Thanks
David
