### ISSUE TITLE
OLD-Hungarian font does not exist in repos

### ISSUE THREAD

**Issue by ghost** [google/fonts#1169]
When will implemented Old-Hungarian script, UNICODE range U10c80-U10cff?

**Comment by vitya2nd** [comment]
Listen! I have got Implementation of Old-Hungarian script, but I do not know, how can I grant and upload for Google! What should I do!
Please tell me a concrete method!

**Comment by fitojb** [comment]
Please contact the team through [this form](https://docs.google.com/a/google.com/forms/d/1w2JOnVv_Vfcg1H_nploj1FRz4LcFsLaFmFkEj50PyW4/viewform).

**Comment by vitya2nd** [comment]
Please tell me, if I did something wrong!

**Comment by vitya2nd** [comment]
It strongly recomended. Please modify, rename the font family to a google confort font familyname!
Is it possible noto project?

**Comment by davelab6** [comment]
I'll close this; eventually we will process submissions to that form. 

@fitojb thanks for your help responding to issues :)
