### ISSUE TITLE
BerkshireSwash (bold) rendering differences between browsers

### ISSUE THREAD

**Issue by Ziriax** [google/fonts#117]
Because this "regular" font has a weight-class of 700, requesting a bold style will apply bold simulations in some browsers (Firefox), but not in others.

Setting the OS/2 weight-class to 400 should fix this problem. 

This might also be by design, since this is a "boldy" font,  but I guess then the macStyle property in the head block should be set to 1 (bold), while now it is 0? 

Or, it might be a Firefox bug :-)

**Comment by m4rc1e** [comment]
Hey,

This may have been an issue with previous versions of FireFox.

FireFox 42.0 looks fine to me. 

![screen shot 2016-09-02 at 11 49 14](https://cloud.githubusercontent.com/assets/7525512/18200077/6b609f6a-7103-11e6-8f0e-950ef0906589.png)
**Left: Safari Centre: FireFox Right: Chrome**

Cheers,
Marc

**Comment by laerm0** [comment]
This is no longer an issue so I am closing.
