### ISSUE TITLE
"Josefin+Sans" woff2 font suddenly increased in size by approx 2px

### ISSUE THREAD

**Issue by jap64** [google/fonts#1185]
https://fonts.googleapis.com/css?family=Josefin+Sans:100,100i,300,300i,400,400i,600,600i,700,700i

Font has worked on a website for several months with no problems and yesterday(30th Aug) has suddenly increased in size by about 2px. Worked around issue by using a locally hosted copy of the font.

**Comment by jap64** [comment]
https://fonts.googleapis.com/css?family=Josefin+Sans:100,100i,300,300i,400,400i,600,600i,700,700i

Font has worked on a website for several months with no problems and yesterday(30th Aug) has suddenly increased in size by about 2px. Worked around issue by using a locally hosted copy of the font.

**Comment by davelab6** [comment]
The typeface was redesigned to make it much better. You are free to self-host under the terms of the font license :)
