### ISSUE TITLE
Raleway has latin-extended, yet Google Font reports only latin

### ISSUE THREAD

**Issue by bmarkovic** [google/fonts#119]
Raleway font hosted on Google Font actually has latin-extended charset (at least it appears so on Ubuntu having downloaded the font). I beleive this should be fixed so that the font can be used directly from Google Web fonts in localities that need the latin-ext charset. Image below (Ubuntu font viewer).

![image](https://cloud.githubusercontent.com/assets/468895/9808901/ddeffca6-5863-11e5-9f09-c28180250638.png)

**Comment by rsheeter** [comment]
It doesn't support very much of latin-ext (Raleway-Regular.ttf latin-ext 150/810). Dave, do you think it has enough to be useful?

**Comment by WP-jk** [comment]
It surely would be great to have that support.
For czech language for example Ralleway's latin-ext is good enough. 
Example of czech pangram is "Příliš žluťoučký kůň úpěl ďábelské ódy." 
Raleway has all the characters needed.

**Comment by impallari** [comment]
Raleway v3 (https://github.com/impallari/Raleway) has full AL3 + Italics.
Romans styles also include Cyrillic

**Comment by mat-b-** [comment]
Polish is good too. Please please please enable latin-ext for it!

**Comment by Swistaku** [comment]
:+1: for this, noticed that typekit also doesn't provide the latin-ext version. at the moment need to provide font from own server :/

**Comment by micalm** [comment]
+1

**Comment by Kaspik** [comment]
:+1:

**Comment by martinsnajdr** [comment]
+1

**Comment by kajka** [comment]
Did you check out version on [brick.im](brick.im). I think that they have extended latin version.

**Comment by davelab6** [comment]
Fixed in https://github.com/google/fonts/commit/78978169aecd5086a7bc883e1800dba751063b00

**Comment by davelab6** [comment]
cc @impallari

**Comment by mat-b-** [comment]
Question: if old version of this font is present on user's computer (which don't have latin-extended), does Google Fonts use proper downloaded version, or user's copy?

**Comment by davelab6** [comment]
Locally installed copies are always used.

**Comment by m4rc1e** [comment]
Closing this since its [METADATA.pb](https://github.com/google/fonts/blob/master/ofl/raleway/METADATA.pb#L170) and the website list Latin-ext

![screen shot 2017-06-13 at 11 41 14](https://user-images.githubusercontent.com/7525512/27078854-4181c2c8-502d-11e7-9ed7-bc9579e58c52.png)
