### ISSUE TITLE
Artifacting in ASAP font at certain sizes

### ISSUE THREAD

**Issue by neokoenig** [google/fonts#1190]
I'm seeing some dodgy rendering for ASAP at certain font sizes on https://fonts.google.com/specimen/Asap?selection.family=Asap - i.e, 15px.

This behaviour has crept in recently I think? (Check the 7's, T's, P's etc:)

![image](https://user-images.githubusercontent.com/381268/30056157-a49e2e44-9229-11e7-9954-e926189a7779.png)

I'm seeing it on live sites in Chrome/FF/Edge. Anyone know how to resolve this or what might be causing it? (Other than changing the actual font size)

**Comment by laerm0** [comment]
I can reproduce this in Windows. It's a hinting issue. Rehinting the fonts for DWrite solves the problem.

Thanks for pointing it out, @neokoenig. We'll get new fonts online <drum roll> ASAP.

**Comment by techtolentino** [comment]
@neokoenig - is this happening on a Windows machine for you? I'm on a Mac and am not seeing it in Chrome/FF/Safari.

Also interested in the status of this bug for a client.

**Comment by davelab6** [comment]
Will be only visible on windows I expect

Latest ttfautohint should fix it

**Comment by neokoenig** [comment]
Can anyone give me an idea on when this fix might be pushed out? (honestly, I've no idea how often a rebuild is done, not trying to be pushy!)
Ta

**Comment by davelab6** [comment]
Id like Micah to take a look at this in early October but I can't give a
time frame for the fix being in production

**Comment by jonathonmilne** [comment]
Any update on this?

**Comment by kirbyanders** [comment]
still having this issue. any update?

**Comment by asdevargas** [comment]
I'm facing the same issue. For the moment, I solved it with a little trick and adding to my classes:
`<-webkit-text-stroke: 1px rgba(0,0,0,.3)>`
It adds a blurry effect to the font so it doesn't look so pixeled.
Looking forward the fix!

**Comment by neuropass** [comment]
same here please publish the new font fix. its been a while now...

**Comment by CrazyC0d3r** [comment]
Six months and counting... :/

**Comment by Jaervinen** [comment]
Still having the same issue here.

**Comment by Jaervinen** [comment]
@davelab6 Is this issue still on the table? Just asking because Micah(laerm0) seems to be not active anymore.

**Comment by laerm0** [comment]
Hi @Jaervinen, I am still active on GFonts, but I am on another, longer-form project now. We'll get to it...

**Comment by SiteSplat** [comment]
hmmm When though... cannot possibly be such a daunting task.  7+ months to update it?

**Comment by dadju75** [comment]
@laerm0 please don't lock out an entire community with your others projects !

If you can't do anything in a reasonnable amount of time, please leave this task to an other GFonts engineer

**Comment by davelab6** [comment]
I'm a project manager at Google and I manage the Google Fonts collection. Micah is working through hinting issues, but working on the highest priority families first, so while this is in his queue, he is working on other families. Thanks for your patience.

**Comment by o11w** [comment]
Hi,
Is it possible to get an idea of when the problem will be treated or from when will a person get down to font correction? I strongly wait the resolution to use the font within a project in production. I guess not the only one in this situation.
Cheers,
o.

**Comment by SiteSplat** [comment]
It's been like this for almost a year now. I recommend an alternative for you all looking to stay with the ASAP. Go for the condensed version instead: https://fonts.google.com/specimen/Asap+Condensed

**Comment by hugolalouve** [comment]
Hey,
Could someone tell us if this issue has started being addressed yet? Like @o11w I'm waiting for this fix to push a project in production. +6 months for an issue labeled as Urgent and Important, this doesn't seem to get a lot of attention.

For those who don't want to use the Condensed version, [here's the 0.0.35 version](https://github.com/google/fonts/files/2123647/typeface-asap-0.0.35.zip), which doesn't have the hinting issue. Regular, Medium and Bold are there, however, I couldn't seem to find the SemiBold.

Cheers!

**Comment by ShaneK** [comment]
@hugolalouve Thanks for the heads up with that link, this helped me out!

**Comment by benjaminSe1** [comment]
Change the font size from pixel to rem solve the issue for me.

**Comment by tibortasi** [comment]
I had the same problem till I found this (the original?) version: https://github.com/Omnibus-Type/Asap/tree/master/fonts
