### ISSUE TITLE
Add a dyslexia font

### ISSUE THREAD

**Issue by laerm0** [google/fonts#1191]
There have been many requests for a font for dyslexics and [Open Dyslexic](https://opendyslexic.org/) is the most commonly mentioned one. The [license](https://github.com/antijingoist/open-dyslexic) looks good – it opens with "♡ Copying is an act of love. Please copy." – but it is the Bitstream Vera license. I dunno if we can accept this license as it specifically calls out a font that isn't the font being licensed.

**Comment by laerm0** [comment]
@davelab6 commented in [an earlier request](https://github.com/google/fonts/issues/558) for a dyslexic font that there is no research that shows a "dyslexic font" is better for dyslexics, which is true, but I bring the issue up again in a spirit of "give 'em what they want."

**Comment by davelab6** [comment]
Alas I think us a disservice to promote this stuff
