### ISSUE TITLE
Add Bebas and Bebas Neue

### ISSUE THREAD

**Issue by laerm0** [google/fonts#1192]
Both fonts are [SIL](https://www.myfonts.com/fonts/flat-it/bebas-neue/) but do not have source readily available. We would need to reach out to [the developer](http://dharmatype.com/contact) to find out.

**Comment by dharmatype** [comment]
https://github.com/dharmatype/Bebas-Neue

**Comment by davelab6** [comment]
@dharmatype thank you!!

**Comment by zubairabid** [comment]
What's the status on the inclusion of this font?

**Comment by dharmatype** [comment]
How is the progress?

**Comment by zubairabid** [comment]
Hey, I'd really like to see this one added.

@davelab6 could I help add the font, if possible?

**Comment by Hitaxas** [comment]
[BebasNeue.zip](https://github.com/google/fonts/files/2969685/BebasNeue.zip)

I would love to see this added.

**Comment by dharmatype** [comment]
I also hope Bebas Neue become one of google font.
https://github.com/dharmatype/Bebas-Neue

**Comment by sladen** [comment]
* https://github.com/dharmatype/Bebas-Neue/blob/master/README.md

1. Appears to be SIL OFL 1.1, with no reserved name.
2. "Bebas Neue is a trademark of Dharma Type."
3. Appears to be at least two variants;  '"Bebas Neue Family (2014)" was designed based on the "Bebas Neue version 1.xxx (2010)". Therefore, some part of the design, character set, style name and some setting between the Family (2014) and version 2.000 (2018) are slightly different."' and 'When you use these fonts together, please be carefull. [sic] They have same "Family Name", but they are not same fonts. Please contact to Font fabric when you need to talk about "Bebas Neue Family (2014)"'

Latter appears to be:

* https://www.fontfabric.com/fonts/bebas-neue/

For reasons of general sanity, it would probably be ideal if that had an unambiguous and unique name.

**Comment by Hitaxas** [comment]
I am confused on the full conflict. We have the permission of the publisher, Dharma Type.

**Comment by sladen** [comment]
@Hitaxas, can not see any conflict.  It **would be great** to get the font added to Google Fonts, if it is technically and realistically possible to do so.  The contribution guidelines are at:

* google/fonts/blob/master/CONTRIBUTING.md
* https://namecheck.fontdata.com/?q=Bebas+Neue

It may be useful to have further input from @dharmatype / Ryoichi Tsunekawa about the relationship between the various versions of fonts using the name "Bebas Neue".

**Comment by dharmatype** [comment]
What is the best solution?
I use the name "Bebas Neue" for a few font family including commercial fonts.
SIL OTF allows copyright holder to make commercial derivative fonts using same font name.

Should I change font name only for Google? (Beebas Neeue)

**Comment by dcambria** [comment]
awsome!

**Comment by thinkshawn** [comment]
Hi, I'm wondering if this was resolved. We're wanting to leverage Bebas Neue in Book and Bold as a webfont on our site. Any direction or help on that would be great. We love the font, but if we can't get it as a webfont we'll have to select something else for the brand project we're working on.

**Comment by m4rc1e** [comment]
Bebas Neue is now in production, https://fonts.google.com/specimen/Bebas+Neue.

Do we plan on releasing the other family Bebas? if not, I'll close this issue.

**Comment by dharmatype** [comment]
> Bebas Neue is now in production, https://fonts.google.com/specimen/Bebas+Neue.
> 
> Do we plan on releasing the other family Bebas? if not, I'll close this issue.

Thank you m4rc1e
I don't plan to release other weights and family.

**Comment by davelab6** [comment]
Closing as this is on https://fonts.google.com/specimen/Bebas+Neue

Thank you again @dharmatype
