### ISSUE TITLE
Josefin Sans regular is now much more bold at 400

### ISSUE THREAD

**Issue by MTphilclothier** [google/fonts#1193]
It looks like the latest version of Josefin sans is now much more bold. Here is a before and after shot of some text set to 400 weight:

Before - https://i.imgur.com/73Zy6tb.png
After - https://i.imgur.com/bl7euZc.png

I also tried setting the new version to weight 300 which was too thin compared to the previous version of 400.

Is this an intentional change in design of the font itself?

Thanks!

**Comment by m4rc1e** [comment]
@MTphilclothier Yep, its a refreshed design. See the project here: https://groups.google.com/forum/#!topic/googlefonts-discuss/v4RUY3u2HW4

**Comment by MTphilclothier** [comment]
Ah ok, thanks for the confirmation.  Is there a way to download the older version from the repo? I was looking for the previous version but can't seem to find it.

**Comment by MTphilclothier** [comment]
Spoke too soon! Just in case anyone else wanted to use the old version, it is available at https://github.com/ThomasJockin/JosefinSansFont-master/tree/master/old/version-1.000

**Comment by davelab6** [comment]
You can also use the 300 weight, which is closer to the old 400

**Comment by Varin6** [comment]
those ttf font's wont work in the browser (chrome, firefox, edge) for some reason, I tried converting to woff with no luck. I'm using @font-face, but chrome doesn't even show those fonts in network tab. Any ideas?
