### ISSUE TITLE
Passion One doesn't support latin-ext

### ISSUE THREAD

**Issue by laerm0** [google/fonts#1194]
Passion One is listed as supporting latin-ext but it's missing many characters.

These are the only glyphs it has from latin-ext:
hbar
Itilde
itilde
IJ
ij
Jcircumflex
jcircumflex
kcommaaccent
kgreenlandic
ldot
Lslash
lslash
Nacute
nacute
Racute
Rcommaaccent
rcommaaccent
Rcaron
rcaron
Scaron
scaron
Ydieresis
Zcaron
zcaron
florin

**Comment by davelab6** [comment]
Since those are not supported in the `latin` subset, but are in the font and in the `latin-ext` subset, it was enabled. Of course it should have more, but 100s of fonts are in this state. This is working as intended for the purposes of this issue tracker :)

**Comment by laerm0** [comment]
That's good info to know, @davelab6. Thanks!
