### ISSUE TITLE
devanagari: Add 0x1CDA (VEDIC TONE DOUBLE SVARITA)

### ISSUE THREAD

**Issue by laerm0** [google/fonts#1196]
A user reported some time ago:

"1CDA        VEDIC TONE DOUBLE SVARITA ​ ​
​(two vertical lines on top of letter) ​​belongs right next to 
0951        DEVANAGARI STRESS SIGN UDATTA (one vertical line on top of the letter) ​but I guess it was not added initially in unicode.

​In case, it is possible to add this one additional accent, it will be helpful. "

**Comment by roozbehp** [comment]
U+1CDA is already in devanagari and telugu subsets.
