### ISSUE TITLE
Open Sans tilde flat at small sizes

### ISSUE THREAD

**Issue by laerm0** [google/fonts#1199]
![screen region 2017-09-05 at 16 44 45](https://user-images.githubusercontent.com/10780161/30082651-96ec3432-9259-11e7-9829-451196e98267.png)

The tilde is flat at 9, 10, and 13px. Rehinting for DW helps. Assigning myself to develop new hinting standards.

**Comment by davelab6** [comment]
Closing as duplicate of https://github.com/google/fonts/issues/399
