### ISSUE TITLE
Q of Cutive Mono has overlaps

### ISSUE THREAD

**Issue by adrientetar** [google/fonts#120]

**Comment by m4rc1e** [comment]
![screen shot 2016-08-11 at 23 31 11](https://cloud.githubusercontent.com/assets/7525512/17605645/b8af0aac-601b-11e6-9aa0-7b830cfe1e57.png)

Ok, found the issue and merged contours.

Update will be rolled out soon.

**Comment by m4rc1e** [comment]
Closed, LGTM.

![screen shot 2017-06-16 at 11 12 38](https://user-images.githubusercontent.com/7525512/27222591-bfc464b6-5284-11e7-82c5-5586a31480f6.png)


http://jsbin.com/fofaluhogo/edit?html,output
