### ISSUE TITLE
Titillium ÷ broken at all sizes

### ISSUE THREAD

**Issue by laerm0** [google/fonts#1200]
Only the extra light and bold weights look okay. Everything else is weirdly broken.

![screen region 2017-09-05 at 16 49 59](https://user-images.githubusercontent.com/10780161/30082886-66fc60c0-925a-11e7-8562-1559bba9310c.png)

Assigning myself to work on improving hinting.

**Comment by Gue3bara** [comment]
This issues and many others with interpolations i Fixed while working on Font [Cairo](https://github.com/Gue3bara/Cairo) https://fonts.google.com/specimen/Cairo

**Comment by davelab6** [comment]
Duplicate of #1064
