### ISSUE TITLE
HindGuntur-Bold.ttf, InknutAntiqua, Khula and Padauk Hinting issues (reported by HintingDebugger)

### ISSUE THREAD

**Issue by felipesanches** [google/fonts#1204]
Issues reported on HindGuntur-Bold (on current master at https://github.com/google/fonts/commit/8382674661d70b35dcfec78c7d4b705685ed6a4f) by running https://github.com/felipesanches/HintingDebugger/commit/955e0cd7194cf00f4b5d9a3fa78c2ef10c0eda95

```
/home/felipe/gfonts/ofl/hindguntur/HindGuntur-Bold.ttf (12 pt): "CVT Out of range." at IP=0x0ABA (RCvt)
/home/felipe/gfonts/ofl/hindguntur/HindGuntur-Bold.ttf (12 pt): "CVT Out of range." at IP=0x005F (RCvt)
/home/felipe/gfonts/ofl/hindguntur/HindGuntur-Bold.ttf (12 pt): "CVT Out of range." at IP=0x005F (RCvt)
/home/felipe/gfonts/ofl/hindguntur/HindGuntur-Bold.ttf (12 pt): "CVT Out of range." at IP=0x005F (RCvt)
```

**Comment by felipesanches** [comment]
The whole family is affected by this issue.

**Comment by felipesanches** [comment]
InknutAntiqua, Khula and Padauk are some of the other families that also have this kind of problem.

**Comment by davelab6** [comment]
Those are all likely old ttfautohint versions

**Comment by laerm0** [comment]
Will send through ttfautohint again.
