### ISSUE TITLE
Josefin Sans Regular is very tracked out and bold

### ISSUE THREAD

**Issue by eselle13** [google/fonts#1206]
Josefin Sans regular is very tracked out now. There are very big ugly spaces between all the letters!
The letters are also as bold as the semibold weight.

<img width="435" alt="400 regular" src="https://user-images.githubusercontent.com/31875773/30307922-b98970cc-974f-11e7-97fe-3094ada7a800.png">

<img width="410" alt="600 semibold" src="https://user-images.githubusercontent.com/31875773/30307924-be1b3544-974f-11e7-80b4-fd69103e0ac0.png">

**Comment by davelab6** [comment]
This wider spacing makes the typeface work better at small (eg 12px) sizes. 

In your CSS, use negative `letter-spacing` (https://www.w3schools.com/cssref/pr_text_letter-spacing.asp) to track it in.
