### ISSUE TITLE
Add League Gothic

### ISSUE THREAD

**Issue by davelab6** [google/fonts#1212]
It is in popular demand, we should add this; it was blocked years ago on too small a glyph set, but I think that has now changed :) 

**Production note:**
- [x] compare https://github.com/bghryct/league-gothic and https://github.com/theleagueof/league-gothic and see which one is more advanced
- [x] robot QA
- [x] visual QA
- [x] build system
- [x] PR upstream
- [ ] Package

**Comment by thundernixon** [comment]
Upstream Repo: https://github.com/theleagueof/league-gothic
