### ISSUE TITLE
Advent Pro Font version was down accidentally

### ISSUE THREAD

**Issue by sapics** [google/fonts#1219]
Current Advent Pro font version is 2.002 in master branch.
But, the version was up to 2.004 in #745 (hotfix-adventpro: v2.004 added).
I guess that the version was down in #1124 (ofl/adventpro fixed QU kerning).

**Comment by davelab6** [comment]
@sapics thanks for reporting. @laerm0 please take a look

**Comment by laerm0** [comment]
Everything is fine on my end and github says my fork is identical to source so I dunno what's going on here. @m4rc1e let's find time to look at this together.

**Comment by laerm0** [comment]
This can be closed when #1235 is merged.
