### ISSUE TITLE
nam file for Armenian

### ISSUE THREAD

**Issue by davelab6** [google/fonts#1220]
Solved in #1107 and needed for https://github.com/google/fonts/issues/1051 but needs to be plumbed all the way through

**Comment by roozbehp** [comment]
We already have an Armenian subset.

**Comment by davelab6** [comment]
Then we need to publish it in https://github.com/googlefonts/tools/tree/master/encodings :)

**Comment by simoncozens** [comment]
We now have a nam file for Armenian in the glyphsets repo.
