### ISSUE TITLE
Minor mistake in Google "DroidNaskh-Regular.ttf" and "DroidNaskh-Bold.ttf" fonts

### ISSUE THREAD

**Issue by shujaatak** [google/fonts#1222]
I have found a mistake in Google early access [Droid Arabic Naskh (Arabic)](https://fonts.google.com/earlyaccess#Droid+Arabic+Naskh) font. [Here ](https://github.com/google/fonts/tree/7a4070f65f2ca85ffdf2d465ff5e095005bae197/apache/droidarabicnaskh) is the GitHub link.

No doubt that this font is designed very elegantly which can be used for many Arabic like languages i.e Urdu, Persian, Pashto, etc. 
I gave it a try to use it for Urdu and I found it amazing! but I found a minor mistake:

- In the mid of a word, instead of a ARABIC LETTER HEH GOAL **MEDIAL FORM**, ARABIC LETTER HEH GOAL **FINAL FORM** is used.
- Similarly in the beginning of a word, instead of a ARABIC LETTER HEH GOAL **INITIAL FORM**, ARABIC LETTER HEH GOAL **FINAL FORM** is used.

Here I have attached two test HTML projects:

1. **With-Error:** for testing the online version of the Google early access [Droid Arabic Naskh (Arabic)](https://fonts.google.com/earlyaccess#Droid+Arabic+Naskh) font.
2. **Without-Error:** contains a version of DroidNaskh-Regular.ttf font file downloaded from [some other project](https://github.com/vokal/android_frameworks_base/tree/master/data/fonts) on GitHub. This font doesn't produce those errors mentioned above.

I have also attached a picture which illustrate what I'm talking about.

![visualize](https://user-images.githubusercontent.com/14161646/30781960-7440df30-a142-11e7-99ab-d05fca02e7e3.PNG)

[Test-Projects.zip](https://github.com/google/fonts/files/1327234/Test-Projects.zip)

**Comment by davelab6** [comment]
Thanks for reporting this

The droid fonts are obsolete and replaced with the Noto fonts. Does the Noto Nastakiq, designed for Urdu, work better for you? 

Of course if Google Fonts serves an older version, it should be updated

**Comment by shujaatak** [comment]
Thanks for the quick reply.
[Noto Nastaliq Urdu](https://www.google.com/get/noto/#nastaliq-aran) looks good but [Droid Arabic Naskh (Arabic)](https://fonts.google.com/earlyaccess#Droid+Arabic+Naskh) looks much neat and clear on screen. I _personally_ prefer [Droid Arabic Naskh (Arabic)](https://fonts.google.com/earlyaccess#Droid+Arabic+Naskh) over [Noto Nastaliq Urdu](https://www.google.com/get/noto/#nastaliq-aran).
It makes me really sad to hear that google is dropping support for [Droid Arabic Naskh (Arabic)](https://fonts.google.com/earlyaccess#Droid+Arabic+Naskh) :(

**Comment by shujaatak** [comment]
In fact,  [Droid Arabic Naskh (Arabic)](https://fonts.google.com/earlyaccess#Droid+Arabic+Naskh) is very elegant font. Even with such a small size (88kb) a user can use it for many languages consistently! Having this font one doesn't need any other font for another Arabic like language.

**Comment by shujaatak** [comment]
Most importantly, Urdu readers need **webfont** and I think [Droid Arabic Naskh (Arabic)](https://fonts.google.com/earlyaccess#Droid+Arabic+Naskh) font is the only one which google support.
All is good about this font but unfortunately the reported bugs makes this font unusable for web Urdu font.
I wonder how on android phones this font works perfectly? There could be an updated version of this font for the android phones.

**Comment by davelab6** [comment]
> I personally prefer Droid Arabic Naskh (Arabic) over Noto Nastaliq Urdu. It would make me really sad if google drop support for Droid Arabic Naskh (Arabic) :(

The design of Noto Naskh Arabic is the same as Droid Arabic Naskh, but it is further improved and developed. 

https://www.google.com/get/noto/#naskh-arab

**Comment by davelab6** [comment]
> Does google support it as a webfont? 

Yes :) 

https://fonts.google.com/earlyaccess#Noto+Naskh+Arabic

**Comment by shujaatak** [comment]
Fantastic! :)
