### ISSUE TITLE
No family name for the Google fonts in FontExplorer (Mac)

### ISSUE THREAD

**Issue by fbzh** [google/fonts#123]
I installed Google fonts in my system a few years ago and used them normally with FontExplorer (Mac). Wanting to update this fonts folder I downloaded the current Google fonts folder (.zip) but when I put them in FontExplorer, fonts families are not recognized (classified in a "No Family Name" set).
Would it be possible to obtain files that are entirely recognized as before?

Regards,
François

**Comment by davelab6** [comment]
Hmm. Did you try uninstalling the fonts first? I think the standard Windows font management functionality doesn't handle font upgrades well.

**Comment by fbzh** [comment]
I use **FontExplorer for Macintosh** - great soft that works very fine and there's absolutely no need to uninstall any font to upgrade or install new fonts. When dragging a font on FontExplorer, all useful options are displayed if necessary.

Only Google fonts of the current Google fonts folder have the problem. the family name of Fonts from other sources are well identified when installed.

**Comment by laerm0** [comment]
This appears to no longer be an issue (using FEX v5). Do you still have the problem, @fbzh?

**Comment by thlinard** [comment]
In FEX version 5 and 6 (current version), the only problematic fonts when one import the whole archive, since the recent Josefin Sans update, are:
Alef-Bold.ttf (duplicate)
Alef-Regular.ttf (duplicate)
MrBedfort-Regular.ttf (duplicate)
MrsSaintDelafield-Regular.ttf (duplicate)
Siemreap.ttf (duplicate)
Suwannaphum.ttf (wrong name table, issue #261)
TerminalDosis-Light.ttf (duplicate)

**Comment by laerm0** [comment]
Thanks for checking in, @thlinard. We'll look into those.

**Comment by thlinard** [comment]
Of course, the duplicates are a known problem: https://github.com/google/fonts/blob/master/TRIVIA.md#duplicated-fonts

**Comment by laerm0** [comment]
Aha, thank you. As you can tell, I'm new and am catching up all over. :)

**Comment by thlinard** [comment]
No problem. 🙂 When commit #1083 will be merged, the worst problem of the lot will be gone.
