### ISSUE TITLE
Wrong size for "ç" (cedilla c and C) for Karla

### ISSUE THREAD

**Issue by davidwebca** [google/fonts#1232]
There seems to be a problem with the size of the character. Stylistically, it seems to be ok which means the character has been designed, but the alignment / size is wrong.

**Comment by fitojb** [comment]
The Karla font doesn’t contain a c-cedilla, or any “extended” character for that matter. It’s the single most incomplete font in the collection. You’re looking at a fallback character put in place by your renderer.

If you need an alternative for the time being, please try [this Karla fork](https://github.com/ms-studio/karmilla).

**Comment by m4rc1e** [comment]
@fitojb thanks for this!

**Comment by david-treblig** [comment]
@fitojb Thanks a lot!

**Comment by fitojb** [comment]
This issue should be solved now.
