### ISSUE TITLE
Merriweather font - strange behavior

### ISSUE THREAD

**Issue by rui-willbe** [google/fonts#1233]
i'm facing a strange behavior with merriweather font on firefox and safari.

Chrome (everything ok):
![chrome](https://user-images.githubusercontent.com/29100564/31119735-cfc25f94-a829-11e7-82bf-19713ed50693.png)

Firefox (diacritics out of place):
![firefox](https://user-images.githubusercontent.com/29100564/31119751-de17df88-a829-11e7-8eb8-faf859c3cee2.png)

Safari (letters with diacritics font fallback):
![safari](https://user-images.githubusercontent.com/29100564/31119766-f2993646-a829-11e7-9094-b371d1d7722e.png)

Note: the word "Notícias" on the bottom left corner is with the same font and rendering fine in all browsers.

**Comment by rui-willbe** [comment]
I've already figured it out.

**Comment by andri** [comment]
@rui-willbe what was the problem? I'm having a similar issue.

**Comment by rui-willbe** [comment]
The problem was that I had made copy-paste from other software.
