### ISSUE TITLE
Open Sans Normal 400 is broken

### ISSUE THREAD

**Issue by SatoAV** [google/fonts#124]
Since today, open sans with weight 400 renders extra-bold, both in latin and cyrillic subsets.
Screen from typecast, on the left is how it should look, on the right - how it looks now:
![image](https://cloud.githubusercontent.com/assets/1641218/9885427/d01409e6-5bed-11e5-8eb5-3ff37cf878fa.png)

**Comment by adrientetar** [comment]
@SatoAV Try to uninstall any copy you have installed on your computer, it should fix things.

**Comment by SatoAV** [comment]
@adrientetar Hmm that seem to have fixed thing on my side, however I need to check with my users if that's the problem in their case.

**Comment by SatoAV** [comment]
It seems to be ok by now, thanks for the response :)
