### ISSUE TITLE
Proxima Nova is missing

### ISSUE THREAD

**Issue by poiru** [google/fonts#1243]
The following fonts are not present in this repo: https://fonts.google.com/?query=proxima

**Comment by poiru** [comment]
cc @m4rc1e

**Comment by thlinard** [comment]
https://fonts.google.com/?query=proxima
"No matches in the open source catalog. Viewing 3 families from external foundries. Learn more."

**Comment by poiru** [comment]
Oh derp, I'll go ahead and close the issue ☺️

**Comment by m4rc1e** [comment]
I think we all wish it was present :-)
