### ISSUE TITLE
Lato font weight for accented characters is off

### ISSUE THREAD

**Issue by chalmagean** [google/fonts#1246]
Any idea why this happens? It doesn't matter what font weight I choose, the weight is different between accented and non-accented characters.

<img width="440" alt="lato300" src="https://user-images.githubusercontent.com/8421/31553925-a9d78322-b044-11e7-80b9-143fc26f5f85.png">

**Comment by m4rc1e** [comment]
Because the bolder characters come from a fallback font, in this case Arial.

**Comment by chalmagean** [comment]
Oh? Why is that?

**Comment by chalmagean** [comment]
Yeah, I've enabled it. It might be that Romanian is not supported... :|

**Comment by davelab6** [comment]
@chalmagean thanks for reporting; I believe this will be fixed when #6 is solved, so closing for now :)

**Comment by adrianvintu** [comment]
This major location still does not support diacritics (șț)

https://fonts.google.com/specimen/Lato
