### ISSUE TITLE
ComingSoon-Regular.ttf has Duplicate contours

### ISSUE THREAD

**Issue by none53** [google/fonts#1250]
ComingSoon-Regular.ttf has duplicate countours in index84,169,180

 >Simple glyph index 84
  Contours with incorrect direction
    Contour index 0
    Contour index 1
  Duplicate contours

>Simple glyph index 169
  Contours with incorrect direction
    Contour index 0
    Contour index 1
  Duplicate contours

>Simple glyph index 180
  Contours with incorrect direction
    Contour index 0
    Contour index 1
  Duplicate contours
    Contour index 1

**Comment by davelab6** [comment]
@none53 thanks for reporting! Does this have any visual effect, or its just a filesize problem?

**Comment by none53** [comment]
I checked it with MS Font Validator and I got an glyph error and reported it.
Since it is only overlapping, rasterization does not have any problem.

**Comment by davelab6** [comment]
Okay cool - thanks!
