### ISSUE TITLE
Travis is failing on new pull requests

### ISSUE THREAD

**Issue by m4rc1e** [google/fonts#1254]
Travis isn't happy because we've moved the .travis file.

> Could not find .travis.yml, using standard configuration.

https://travis-ci.org/google/fonts/builds/288543845?utm_source=github_status&utm_medium=notification

**Comment by davelab6** [comment]
This should fix it :)

<img width="821" alt="screen shot 2017-10-16 at 10 39 54" src="https://user-images.githubusercontent.com/261579/31617865-5c81fdd4-b25e-11e7-9011-4543442effc1.png">
