### ISSUE TITLE
Open Sans Hebrew issues

### ISSUE THREAD

**Issue by laerm0** [google/fonts#1258]
I am merging Open Sans Hebrew into Open Sans and there is no semibold in Hebrew. Looks like we need a new instance/interpolation.

**Comment by laerm0** [comment]
Other issues I am finding in Open Sans Hebrew:

- inconsistent character sets (mostly math glyphs)
- glyph names are wrong in italics (Hebrew accents are named various accented Latin glyphs)

**Comment by davelab6** [comment]
> I am merging Open Sans Hebrew into Open Sans and there is no semibold in Hebrew. Looks like we need a new instance/interpolation.

Please make it; measure the stem width of H in the original, and calculate where in the design space you need to be to reproduce it :) 

> inconsistent character sets (mostly math glyphs)
>
> glyph names are wrong in italics (Hebrew accents are named various accented Latin glyphs)

Yeah I suggest you go to town and make the `.glyphs` file "as it should be" - per https://glyphsapp.com/tutorials/porting-to-glyphs and https://glyphsapp.com/tutorials/importing-existing-fonts

**Comment by laerm0** [comment]
Okay, this is all done now, so I am closing. Woo.
