### ISSUE TITLE
Update Reem Kufi to 0.7

### ISSUE THREAD

**Issue by khaledhosny** [google/fonts#1263]
https://github.com/alif-type/reem-kufi/releases/tag/v0.7

**Comment by m4rc1e** [comment]
@khaledhosny thanks! I'll try and take a look at it soon :-). We're dealing with several updates at the moment so it may take some time.

**Comment by davelab6** [comment]
Even more fixes made upstream :D

**Comment by khaledhosny** [comment]
I made a new release and updated this issue.

**Comment by khaledhosny** [comment]
I made another release…

**Comment by m4rc1e** [comment]
Hey @khaledhosny.

I've just sandboxed a pr to my fork. https://github.com/m4rc1e/fonts/pull/55

Only issue is the vert metric changes against the version we currently host.

**Comment by khaledhosny** [comment]
I changed WinAscent in https://github.com/alif-type/reem-kufi/commit/3e84f25bb904e16cb8329c868ccf9b170d43dbce to fix potential clipping issue. I don’t usually keep Win metrics stable since they need to grow when higher glyphs are added and applications that use them for line height are broken from my point of view (unlike Latin, Arabic usually can’t keep Win and Typo metrics the same).

**Comment by m4rc1e** [comment]
Thanks for the explanation.

I usually enable fsSelection bit 7 which means I can set the Win metrics freely, whilst keeping the typo the same (I'm sure you know this technique ;-)). I'm curious why you haven't used this approach? is there an edge case I'm unaware of?

**Comment by khaledhosny** [comment]
I usually do that, too. Let me check why it isn’t the case here.
