### ISSUE TITLE
Add Courier Prime

### ISSUE THREAD

**Issue by sivapvarma** [google/fonts#1272]
Courier Prime is a variant of Courier designed specifically to look good and for screen writing. There are three variant in the family: Courier Prime, Courier Prime Sans, Courier Prime Code

License: SIL OFL
Link: https://quoteunquoteapps.com/courierprime/

**Comment by thlinard** [comment]
https://github.com/google/fonts/blob/master/CONTRIBUTING.md

**Comment by sivapvarma** [comment]
@thlinard I looked at the contributing guidelines. 

Here is the github repo: https://github.com/quoteunquoteapps/CourierPrime

Is there any other requirement ?

**Comment by thlinard** [comment]
I'm not a Google employee, but by showing a GIthub repo, your chances are better. 🙂

**Comment by sivapvarma** [comment]
Courier Prime is also on [Typekit](https://typekit.com/fonts/courier-prime) where the [EULA](https://typekit.com/variations/18505/eula) gives more details on the license

**Comment by thundernixon** [comment]
Additional info re: licensing, I just found [documentation of IBM releasing Courier under an X11 license](https://cgit.freedesktop.org/xorg/font/ibm-type1/tree/COPYING) (which seems to be similar to / the same as an MIT license) in 1991. 

I was curious about whether the font name "Courier Prime" was solid, but I think this indicates that it is. (Someone please correct me if I'm misunderstanding X11/MIT licenses).

**Comment by davelab6** [comment]
You are right, X11 and MIT are basically the same; and I can't find a live trademark on "Courier", so this is good to go

**Comment by felipesanches** [comment]
@davelab6, I see that they're declaring a Reserved Font Name:

https://github.com/quoteunquoteapps/CourierPrime/blob/c9e4bebd4ee7c124da4beddb0d3bd41b85245caf/glyphs/Courier%20Prime.glyphs#L17

**Comment by chibicode** [comment]
Can we close this? https://fonts.google.com/specimen/Courier+Prime

**Comment by m4rc1e** [comment]
Sure. Sorry, I've been busy with other commitments so haven't updated the status of new families for a while.

**Comment by KnotUntied** [comment]
Can we get Courier Prime Sans and Courier Prime Code as well?

**Comment by fitojb** [comment]
@KnotUntied File a separate issue report for those.
