### ISSUE TITLE
Host the Overpass font family

### ISSUE THREAD

**Issue by andyfitz** [google/fonts#128]
https://github.com/RedHatBrand/overpass

**Comment by andyfitz** [comment]
Please let me know if there are any issues with this contribution.

**Comment by davelab6** [comment]
Thanks @andyfitz ! Great stuff, I've posted a couple of minor issues on the project's issue tracker :)

**Comment by andyfitz** [comment]
All issues resolved @davelab6

**Comment by andyfitz** [comment]
@davelab6  also added the metadata.json file for your convenience

**Comment by andyfitz** [comment]
anything waiting on me for @davelab6  ?

**Comment by smpetrey** [comment]
Can't wait to see this hosted. Great work @andyfitz

**Comment by andyfitz** [comment]
ping reminder :+1:

**Comment by andyfitz** [comment]
bump again :+1: :+1:

**Comment by andyfitz** [comment]
bump again :8ball:

**Comment by andyfitz** [comment]
@google-admin please assign someone

**Comment by davelab6** [comment]
Hi Andy! Sadly this is in a queue, being new non-latin fonts :( I'll get to
it when I can, I hope this quarter

**Comment by danburzo** [comment]
Hi everyone, I was looking to introduce Overpass manually in the font collection for our online design app (which already uses Google Fonts), and I noticed that there's a slight mismatch between the weight as defined in the font name (e.g. _Light_, _Extra-light_) and the font-weight being assigned to it in the CSS. I was curious if this is thought to be a problem, and if so, what's the current thinking around it.

I am asking this because, if we release it prior to its inclusion in Google Fonts, and we want to eventually offload the font management to GFonts, it'd be great if we could do that without having to map existing font weights to new font weights. 

Would you favor:
A. Changing the names of the fonts to reflect their optical weight?
B. Assign the CSS font weights based on the name of each font, and just have them be a bit thicker than other fonts of the same weight?

Thank you!

**Comment by roberrrt-s** [comment]
I'd like to bump this, since the current CDN isn't allowing me to select specific fonts. Is there any news on this?

**Comment by mattdm** [comment]
A new version of the font is on the way; that might both be a good occasion to do this, and also, probably worth waiting for now that it's been so long.

**Comment by roberrrt-s** [comment]
Awesome! Could you give it a heads up here if there's any news?

**Comment by davelab6** [comment]
I will update this thread when there is progress :)

**Comment by mattdm** [comment]
New version released! https://github.com/RedHatBrand/Overpass/releases/tag/3.0

**Comment by roberrrt-s** [comment]
I'm bumping this as interest for progress, @m4rc1e

**Comment by m4rc1e** [comment]
@roberrrt-s source [repo](https://github.com/RedHatBrand/overpass/issues) has problems. If they hesitate too much, I'll end up hotfixing them.

**Comment by roberrrt-s** [comment]
Thanks for the fast reply, i'll follow the src. repo!

**Comment by m4rc1e** [comment]
alright, @roberrrt-s temporary repo [here](https://github.com/m4rc1e/OverpassGFVersion). Need to sort an upstream problem before I submit this properly.

**Comment by davelab6** [comment]
@m4rc1e https://github.com/RedHatBrand/Overpass/releases/tag/3.0.1 is dropped and ready for you! :P

**Comment by m4rc1e** [comment]
pr sent #480

**Comment by davelab6** [comment]
While #480 has been merged, its possible @m4rc1e could make a new one for https://github.com/RedHatBrand/Overpass/releases/tag/3.0.2 before Monday =)

**Comment by m4rc1e** [comment]
@davelab6 my last pr already had my metrics included :-), I predicted they'd go with it.

https://github.com/m4rc1e/OverpassGFVersion/blob/master/build/build.sh#L50

We don't have to do anything.

**Comment by davelab6** [comment]
Did you increment the version number?

**Comment by m4rc1e** [comment]
Good point, I didn't. I'll redo it tomorrow on the v3.002 fonts.

**Comment by andyfitz** [comment]
Thank you so much for the effort here!

**Comment by roberrrt-s** [comment]
Bumping this.

**Comment by andyfitz** [comment]
# It has been done
https://fonts.google.com/?query=overpass  

![Party Time](http://media1.giphy.com/media/CkkVulYzFjd72/giphy.gif)

**Comment by davelab6** [comment]
lol @andyfitz 
![elgge](https://cloud.githubusercontent.com/assets/261579/21875162/ceb692d0-d82e-11e6-95ff-ec00fe630e15.gif)

**Comment by roberrrt-s** [comment]
Ahhhh months of anxious waiting and my page loading time has increased with half a second. Thank you so much for your hard work all of you!

**Comment by davelab6** [comment]
@roberrrt-s you ought to account for the cross site caching inherent in a GF hosted version vs self hosted :)

**Comment by roberrrt-s** [comment]
That's also very, very true @davelab6
