### ISSUE TITLE
Baloo Bhaijaan Arabic support is lacking

### ISSUE THREAD

**Issue by khaledhosny** [google/fonts#1309]
The font is listed under Arabic fonts, but it seems to lack support of several important Arabic characters. I can list some of them, but I think it would be better if it was checked against the Arabic glyph list.

**Comment by davelab6** [comment]
@Gue3bara already addressed this upstream but we didn't yet publish that update - if you'd like to check if his work is sufficient, please check https://github.com/Gue3bara/Baloo

**Comment by khaledhosny** [comment]
All good then.
