### ISSUE TITLE
Wrong character on KHAND font (I-acute upcase)

### ISSUE THREAD

**Issue by WP-jk** [google/fonts#131]
Uppercase I - acute (Í) on KHAND family (https://www.google.com/fonts/specimen/Khand) - shows E - acute (É) instead. This problem appears in all the weights available.
Lowercase is ok, 
Character is in Latin-ext subset.

Edit by Rosa:
upstream repo: https://github.com/itfoundry/khand

**Comment by JirkaW** [comment]
I confirm the same problem, is there any solution for it?

**Comment by csararias** [comment]
Indeed, there is a mistake with this character in Khand font. You can fix it with a free software: FontForge-2016-04-04-Windows-r2.exe. I solved in this way.

**Comment by m4rc1e** [comment]
Hey,

I have not been able to replicate this bug in the [repo source](https://github.com/itfoundry/khand) (v2.000) or those from [Google Fonts](https://fonts.google.com/specimen/Khand?selection.family=Khand) v1.00.
![screen shot 2016-08-29 at 12 45 36](https://cloud.githubusercontent.com/assets/7525512/18049133/8f698e3c-6de6-11e6-89d4-3dbc00d22ad9.png)
**top: Khand, bottom: Times**

What version of the fonts were you using and which software?

@davelab6 The Google Fonts download is out of date. V2.00 exists. It includes more weights. I will investigate issue #145 to see if that has been fixed in v2.000.

Cheers,
Marc

**Comment by laerm0** [comment]
This [jsbin](http://jsbin.com/jofahuyigi/edit?html,output) reproduces this in OS X Chrome.

**Comment by wirthandras** [comment]
Hello, the problem occured in our site, any solutions exists is the last two year?

**Comment by chladog** [comment]
As of 2020 any update on this?

**Comment by thlinard** [comment]
Still here:
https://fonts.google.com/specimen/Khand?preview.text=%C3%8D&preview.text_type=custom

**Comment by leandrocastro** [comment]
2021. Alguma solução?

**Comment by tecnicowanatop** [comment]
This is solution, replace "í" for other font:

function modify_home_in_nav_menu_objects( $items, $args ) {
    foreach ( $items as $k => $object ) {
     
            $object->title = str_replace("í","<span style='font-family: Roboto;'>í</span>",$object->title);
        
    }
    return $items;
}
add_filter( 'wp_nav_menu_objects', 'modify_home_in_nav_menu_objects', 10, 2 );

**Comment by tecnicowanatop** [comment]
`function modify_home_in_nav_menu_objects( $items, $args ) {
    foreach ( $items as $k => $object ) {
     
            $object->title = str_replace("í","<span style='font-family: Roboto;'>í</span>",$object->title);
        
    }
    return $items;
}
add_filter( 'wp_nav_menu_objects', 'modify_home_in_nav_menu_objects', 10, 2 );`

**Comment by RosaWagner** [comment]
This keep coming on twitter and here every year, so I inspected the sources upstream: files are very old, not matching the GF requirements, binaries only available as CFF -> would require a bit of engineering (indic specialised) to be able to rebuild and bring up to spec. I added it to the future to-do.

**Comment by davelab6** [comment]
Yeah, probably good to Yanone in Q2.

**Comment by yanone** [comment]
Discussion about weight setup: https://github.com/itfoundry/khand/issues/5

**Comment by yanone** [comment]
It's not possible for me at the moment to upgrade Khand.

The sources and the currently live binaries don't share the same glyph repertoire nor OpenType feature code for Devanagari. The sources appear to be outdated compared to the binaries, and given that glyph names are also inconsistent between the source and the binaries (even when comparing production names), and my lack of Devanagari knowledge, it's not possible for me to reverse-engineer the source from the binary.
