### ISSUE TITLE
Font Versioning

### ISSUE THREAD

**Issue by daniel18387** [google/fonts#1316]
Would it be possible to apply versioning to the query string in order to pull through a specific version of a font? i.e. The link URL `<link href="https://fonts.googleapis.com/css?family=Montserrat:400,500,600,700,800&v=10" rel="stylesheet">`

As a regular user of Montserrat, I've noticed two major changes in the past year. Although I agree that the font looks far better, it would make sense to apply versioning to fonts to ensure designs for existing users do not get affected.

**Comment by davelab6** [comment]
As you can read in #1307 and #1308 we have considered and rejected this feature because it would increase latency, complexity, and leave more old buggy copies in use.

If you want control of when updates are made, you are welcome to self host and the OFL respects your freedom to do so.
