### ISSUE TITLE
In Caveat, ₹ and ₺ are switched

### ISSUE THREAD

**Issue by davelab6** [google/fonts#133]
https://github.com/googlefonts/caveat/issues/1

**Comment by m4rc1e** [comment]
I'll have a look into this today.

I've asked Pablo for the sources.

Cheers,
Marc

**Comment by m4rc1e** [comment]
@davelab6 Apparently you may have sources for this?

The [repo](https://github.com/google/fonts/tree/master/ofl/caveat), doesn't have any.

**Comment by m4rc1e** [comment]
This bug only occurs in the Text version.

**Comment by laerm0** [comment]
@davelab6 Was @m4rc1e correct in asking you for source on this?

**Comment by davelab6** [comment]
@impallari emailed me the sources, I can try to dig the up

**Comment by laerm0** [comment]
Did you find the sources for this, @davelab6?

**Comment by m4rc1e** [comment]
@laerm0 I'm working on building some today
