### ISSUE TITLE
Roboto Slab not loading

### ISSUE THREAD

**Issue by jberg1** [google/fonts#1336]
Anyone else having issues with Roboto fonts? Specifically Roboto Slab.
I have it installed on a couple sites and all of a sudden it isn't loading and falling back to the alternative font. I've tried on a couple sites and static tests with the same result.

**Comment by davelab6** [comment]
This was not updated recently

**Comment by jberg1** [comment]
Hmm. Oh well, I just switched to Zilla Slab that one works fine.
Thanks for your help.

**Comment by AyraGianellie** [comment]
Hi! I have the same problem. the roboto slab font is showing up then suddenly it turns in to an alternative font. But I installed the font on my ftp. Can you help me?

**Comment by jberg1** [comment]
I found my issue was limited to Firefox 57 (new and improved...pfft). And it was limited to Google Fonts that I had installed on on windows and using as an embedded font on a website. Here is the answer that resolved it for me.
[https://support.mozilla.org/en-US/questions/1188968](url)
https://support.mozilla.org/en-US/questions/1188968
