### ISSUE TITLE
Open Sans Condensed, error when including font without specifying a weight

### ISSUE THREAD

**Issue by ndimatteo** [google/fonts#134]
I'm using the following to include fonts in a fontpicker. All of the fonts load except for **Open Sans Condensed**, which throws a 400 error _"The requested font families are not available."_

``` javascript
WebFont.load({
      google: {
        families: [
          'Arvo',
          'Dosis',
          'Droid Serif',
          'Droid Sans',
          'Glegoo',
          'Inconsolata',
          'Josefin Slab',
          'Kalam',
          'Lato',
          'Libre Baskerville',
          'Lobster',
          'Merriweather',
          'Montserrat',
          'Muli',
          'Nobile',
          'Nunito',
          'Open Sans',
          'Open Sans Condensed',
          'Oswald',
          'Playball',
          'Playfair Display',
          'Rajdhani',
          'Raleway',
          'Roboto',
          'Roboto Slab',
          'Source Sans Pro',
          'Rokkitt',
          'Varela Round',
        ]
      }
    })
```

I'm assuming this has something to do with that it's looking for a 400 weight, when the default for this font is 300. This should be fixed so that it's consistent with the other fonts, either change the default weight to 400 or update the scripting so that it accounts for Open Sans Condensed.

**Comment by davelab6** [comment]
I agree :) Thank you for reporting this

**Comment by ndimatteo** [comment]
Totally! Figured it was worth noting.

**Comment by laerm0** [comment]
Looks like #785 fixed this so I'm closing.
