### ISSUE TITLE
Add Antonio

### ISSUE THREAD

**Issue by dlosie** [google/fonts#1344]
The font 'Antonio' is in the project, but not available from the Google Fonts API.

Production notes by @yanone:
- ~~[ ] Contact author~~ (author deceased)
- [x] Build
- [x] Fontbakery QA
- [x] Visual QA
- [x] Version bumped
- [x] Authors and Contributors info
- [x] Catalog designer info up to date
- [x] PR to upstream
- [x] PR to GF
- [ ] Font Images

**Comment by davelab6** [comment]
@dlosie thanks for reporting this. I believe this family failed some QA check and got stuck there.

**Comment by laerm0** [comment]
Yeah, there are a handful of errors here from fontbakery and fontval. I'll have to file issues to track and fix.

**Comment by davelab6** [comment]
Perhaps better to just list them here :)

**Comment by laerm0** [comment]
Sounds good. I'll do the checkboxes later on.

**Comment by davelab6** [comment]
https://www.fontsquirrel.com/fonts/antonio reference TTFs

https://github.com/vernnobile/antonioFont

**Comment by yanone** [comment]
Catalog PR: https://github.com/google/fonts/pull/3175

**Comment by yanone** [comment]
Upstream PR: https://github.com/googlefonts/antonioFont/pull/1
