### ISSUE TITLE
latin: Add ẞ and †

### ISSUE THREAD

**Issue by davelab6** [google/fonts#1346]
In addition to #78 I'd like to propose adding the following characters

- [x] `0x1E9E ẞ LATIN CAPITAL LETTER SHARP S` used in German

- [x] `0x2020 † DAGGER` per @codeman38 's [comment](https://github.com/google/fonts/issues/78#issuecomment-122289597) this is also found in the legacy Latin character set for both Windows and Mac OS 

```py
>>> u'\u2020'.encode('cp1252')
'\x86'
>>> u'\u2020'.encode('macroman')
'\xa0'
```

- [ ] I didn't yet check if there's anything else in the legacy encodings that isn't in latin, but should be.

**Comment by roozbehp** [comment]
U+1E9E is already in latin-ext. I'm not sure what may break if I move it to latin. Since it's still quite rare, we're probably OK with it living in latin-ext.

Dagger and Double dagger (U+2021) are used with English text relatively commonly, so adding to latin.

**Comment by davelab6** [comment]
Ah great! I somehow missed that; maybe case sensitive grepping by accident :) 

2021 sounds good too

**Comment by thlinard** [comment]
Š, š, Ž, ž are included in CP1252, but only found in Latin-Ext.
≠, ∞, ≤, ≥, ∂, ∑, ∏, π, ∫, Ω, √, ≈, ∆, ◊, ﬁ, ﬂ, ˘, ˙, ˚, ˝, ˛ and ˇ are included in MacRoman and ISO-Adobe, and not even in Latin-Ext.
Ł and ł are included in ISO-Adobe, but only found in Latin-Ext.

**Comment by davelab6** [comment]
Thanks so much Thomas!!!

On Nov 23, 2017 3:51 AM, "Thomas Linard" <notifications@github.com> wrote:

Š, š, Ž, ž are included in CP1252, but only found in Latin-Ext.

Ok, I think this is fine

Ł and ł are included in ISO-Adobe, but only found in Latin-Ext


I think this is also fine

> ≠, ∞, ≤, ≥, ∂, ∑, ∏, π, ∫, Ω, √, ≈, ∆, ◊, ﬁ, ﬂ, ˘, ˙, ˚, ˝, ˛ and ˇ are
included in MacRoman and ISO-Adobe, and not even in Latin-Ext.

The math stuff seems good for latin-ext

The Greek stuff is maybe better in the greek subset?

The diacritics is trickier. Assuming these are combining characters,
perhaps we should include combining mark characters in both latin and
latin-ext font slices, so they work with characters in both slices, but
only declare them in one slices unicode-range property..?

**Comment by thlinard** [comment]
> The Greek stuff is maybe better in the greek subset?

Hum, for the most part, it's math stuff too. For exemple, ∂ is “∂” U+2202 Partial Differential and not “δ” U+03B4 Greek Small Letter Delta. ∏ is “∏” U+220F N-ary Product and not “Π” U+03A0 Greek Capital Letter Pi.

But its lowercase counterpart, π, is truly the Greek letter “π” U+03C0 Greek Small Letter Pi.

∑ (“∑” U+2211 N-ary Summation) and ∆ (“∆” U+2206 Increment) are math stuff, but Ω (“Ω” U+03A9 Greek Capital Letter Omega) is the Greek letter.

We have already the same situation in ISO 8859-1, where “µ” U+00B5 Micro Sign is not “μ” U+03BC Greek Small Letter Mu.

> Assuming these are combining characters

Unfortunately, no. ˘ is “˘” U+02D8 Breve Unicode Character and not “◌̆” U+0306 Combining Breve. ˚ is “˚” U+02DA Ring Above, etc. : all standalone (spacing) characters, not combining ones.

Again, we have already the same thing in ISO 8859-1: ¸ is the spacing character “¸” U+00B8 Cedilla.

**Comment by thlinard** [comment]
Hum, my bad. ≠, ∞, ≤, ≥, ∂, etc. aren't in ISO-Adobe, but ATM substituted them by the characters of the Symbol font, so they were formally added to Adobe Latin 2 (the minimum character set for Adobe OpenType fonts).

Adobe Latin 2 also added ℓ (not included in Latin-Ext), ℮ (also not included in Latin-Ext) et €.
https://github.com/adobe-type-tools/adobe-latin-charsets

**Comment by thlinard** [comment]
https://github.com/google/fonts/pull/1355#issuecomment-347308709 reminds me: ∙ U+2219 is a required base character for MS Office. And it is not even in Latin-Ext, though it frequently sharing its glyph with · U+00B7.

https://www.microsoft.com/typography/otfntdev/glyphs.htm

**Comment by roozbehp** [comment]
I'm having second thoughts about adding dagger and double dagger to latin. May try a new "symbols" subset.

**Comment by roozbehp** [comment]
OK, based on @davelab6's comments, let's avoid creating a thinly populated symbols set for now and add the dagger and double dagger to latin-ext.

Please file new issues for the other characters mentioned.

**Comment by simoncozens** [comment]
0x1E9E and 0x2020 are now both in latin-ext.
