### ISSUE TITLE
latin: Add ₹?

### ISSUE THREAD

**Issue by davelab6** [google/fonts#1347]
- [ ] `0x20B9 ₹ INDIAN RUPEE SIGN` is included in all the indian language subsets, but since we always serve latin anyway, de-duplicating this from them into Latin could be good. 

```
$ pwd
/Users/dcrossland/src/github.com/googlefonts/tools/encodings
$ grep 20B9 *nam
bengali_unique-glyphs.nam:0x20B9 ₹
devanagari_unique-glyphs.nam:0x20B9 ₹
gujarati_unique-glyphs.nam:0x20B9  ₹
gurmukhi_unique-glyphs.nam:0x20B9  ₹
kannada_unique-glyphs.nam:0x20B9  ₹
latin-ext_unique-glyphs.nam:0x20B9  ₹
malayalam_unique-glyphs.nam:0x20B9  ₹
tamil_unique-glyphs.nam:0x20B9  ₹
$
```

**Comment by roozbehp** [comment]
latin-ext already has this, and I'm a little worried moving it to latin may break things. Keeping as is for now.

**Comment by davelab6** [comment]
Sounds good!
