### ISSUE TITLE
New subset: IPA (for Voces, Judson, etc)

### ISSUE THREAD

**Issue by jonas-jonas-zz** [google/fonts#135]
Hi

I am trying to get a font with IPA support. There are at least two fonts that have IPA support, Voces and Judson, as both claim in the description:

https://www.google.com/fonts/specimen/Voces
https://www.google.com/fonts/specimen/Judson

However, I have not succeeded in making these fonts work on the web. When I download them, I see that they contain all the IPA characters I need, but when I try using them via Google fonts, the IPA character do not show up, even when I choose the "Latin Extended" characters.

Is there a way to make the IPA fonts work?

Many thanks and kind regards,
Jonas

**Comment by ippeiukai** [comment]
I had a problem with Voces font on Google Fonts not having full Unicode range required by IPA as well.
It's meant to be the glyphs for IPA and missing the IPA Extensions block renders it useless IMHO.
I ended up switching to the same font on Adobe Edge Web Fonts.

TTF file seems okay:
https://github.com/google/fonts/blob/c954e6428ca6b58bb168e546f50e67813f2cf2ee/ofl/voces/Voces-Regular.ttf

Perhaps defining subsets is excluding all the characters not in any of the subset from the font even when subsets are not selected?
https://github.com/google/fonts/blob/c954e6428ca6b58bb168e546f50e67813f2cf2ee/ofl/voces/METADATA.pb

**Comment by davelab6** [comment]
Edge web fonts is probably your best bet right now; ideally gf would add a
new ipa subset, like any other script. But I don't know when this might be
prioritized.

**Comment by machsna** [comment]
I have done some more testing. The strange thing is that it works just fine in Firefox or Safari, as long as you add the additional query `subset=all`. The only browser where it does not work is Google Chrome. Why is that?

Here is a small example I have used for testing:

```html
<!DOCTYPE html>
<html><head>
  <title>IPA example</title>
  <meta charset="UTF-8">
  <link href="https://fonts.googleapis.com/css?family=Judson&amp;subset=all" rel="stylesheet" type="text/css">
  <style>* {font-family: Judson, sans-serif; font-size: 36px;}</style>
</head><body>
  <p>ðə ˈnoɹθ ˌwɪnd ən (ð)ə ˈsʌn wɚ dɪsˈpjutɪŋ ˈwɪtʃ wəz ðə ˈstɹɑŋɡɚ, wɛn ə ˈtɹævəlɚ ˌkem əˈlɑŋ ˈɹæpt ɪn ə ˈwoɹm ˈkloʊk.</p>
</body></html>
```

**Comment by davelab6** [comment]
`subset=all` is unsupported, so you shouldn't use it; if you use it, expect things to break. 

Chrome (and Opera) have implemented suport for `unicode-range` - www.caniuse.com/unicode-range - which means that only explicitly declared ranges of unicode are available; such browsers then download and use the subsets needed for the DOM.

**Comment by ippeiukai** [comment]
> ideally gf would add a new ipa subset, like any other script. But I don't know when this might be
prioritized.

Not sure adding another subset to support less common usage everytime is productive. Perhaps better to make either the default set to be the whole font or provide a way to specify whole font is wanted (like subset=all)? I think the problem is not that IPA range is missing, but that there is no means to utilise the whole character set of the font rather than subsets.

**Comment by davelab6** [comment]
> Perhaps better to make either the default set to be the whole font

I think `unicode-range` is the best way forwards, and if an `ipa` subset is developed, then that would mean that the IPA characters would become used automatically when these fonts are in use, by browsers that support this css feature.

**Comment by ippeiukai** [comment]
> I think unicode-range is the best way forwards

Not disputing that. But isn't it be possible to list all the ranges that is in the ttf in unicode-ranges when subset=all is requested? I feel that would be easier and more generic solution to the problem than painstakingly developing IPA subset.

**Comment by davelab6** [comment]
Back in 2011, @moyogo wrote,

> The Latin extended character subset in subset.py only includes characters from Extended A, B, C, D, and Additional (without Vietnamese characters).
> 
> But some of those characters are only one of bicameral pair of the same letter. For exemple Ɛ (U+0190) is in Latin Extended-B, but its lowercase ɛ (U+025B) is in
> IPA Extensions.
> 
> Not all IPA Extensions characters are used outside of IPA, although in general if it has another case variant in another Latin block it probably is used in
> language orthographies.
> 
> Characters in Combining Diacritical Marks are also used in language orthographies in Latin script. They are used on letters withouth precomposed character forms,
> for example Yoruba uses combining dot below (U+0323) or combining acute (U+301) depending on how accented letters like ẹ́ is represented.
> 
> I don't know if you want to include those whole blocks in the latin-ext subset, considering not all characters are actually used in language orthography. However
> this might not be much of an issue if the font doesn't have all the characters of those blocks.
> 
> I can provide a list of characters I've found to be used in language orthographies.
> 
> > @sladen Perhaps it needs a full-on "Africa languages alphabet" subset?
> 
> Sure, that's a valid subset. However IPA characters are also used outisde of IPA and African orthographies. For example, the letter schwa (ə U+0259 in IPA
> Extensions, Ə U+018F in Latin Extended-B) is used in Azeri (spoken in Azerbaijan and Iran), or the letter ezh (ʒ U+0292 in IPA Extensions, Ʒ U+01B7 in Latin
> Extended-B) is used in Sami languages (spoken in Nordic countries and Russia). Both are in MES-2.
> 
> It would actually make more sense to have latin-ext complete with all Latin characters and diacritics, at least those used in language orthographies. Having a
> European language subset (or renaming latin-ext to match it's intended use) would be more appropriate, and could be similar to MES, along the Vietnamese and
> African subsets.
> 
> There are other possible regional subsets like American, Asian (including Vietnamese, pinyin), Australasian, or by use (much more limited) like transliteration
> (Latin Extended Additional is full of those), phonetic transcriptions (IPA, UPA, APA), or historical. There are many ways to organize subsets, but regional zones
> is probably the most practical.

**Comment by davelab6** [comment]
@ippeiukai 
> wouldn't it be possible to list all the ranges that is in the ttf in the css's unicode-ranges when subset=all is requested? 

`subset=all` is not supported :)

> I feel that would be easier and more generic solution to the problem than painstakingly developing IPA subset.

If we make use unicode-range, we still need to know what that range is... So, I've moved this to the 'glyph set definitions' milestone. I hope that in the next 2 months @kalapi and @alexeiva and @graphicore and @m4rc1e and I can take a look at this, as we attempt to fix all the things.

**Comment by khaledhosny** [comment]
`unicode-range` is an inherently a sub optimal solution, as you are serving different font files for each range which means no OpenType feature of any kind accross the ranges. So even when `unicode-range` is supported there should be a way to tell the API “*I really need every character supported by this font in a* **single** *font file*”.

**Comment by khaledhosny** [comment]
Another way around OP problem is to define one’s own subset and give the `text=` attribute the list of characters, it will be more verbose but AFAIK is should work

**Comment by davelab6** [comment]
> Another way around OP problem is to define one’s own subset and give the text= attribute the list of characters, it will be more verbose but AFAIK is should work

I think that is the answer to OP's question! :)

**Comment by roozbehp** [comment]
Working on adding these to latin-ext.

**Comment by stefanocoretta** [comment]
Any news on this front?

**Comment by simoncozens** [comment]
We added an IPA extensions subset [here](https://github.com/googlefonts/glyphsets/pull/94), so Voces seems to be working nicely now:

<img width="504" alt="Screenshot 2023-08-11 at 10 59 24" src="https://github.com/google/fonts/assets/106728/9dc15eef-e6ad-4dd5-b604-96f209d0bbb1">

**Comment by moyogo** [comment]
@simoncozens that looks like glyphs from a fallback font.

**Comment by moyogo** [comment]
@simoncozens Actually never mind, the design of some IPA symbols in Voces is the problem in that screenshot.
