### ISSUE TITLE
Inconsolata rendering HYPHEN MINUS (-) U+002D same as EN DASH (–) U+2013

### ISSUE THREAD

**Issue by tamsky** [google/fonts#1373]
Rendering test, at https://fonts.google.com/specimen/Inconsolata website, with size set to 110px

Input is the two codepoints: [ `-–` ]

![image](https://user-images.githubusercontent.com/96978/33460431-e6a52868-d5e2-11e7-844f-4b806d9f26f3.png)

the two rendered characters at bottom-right of screenshot shows what appears to be two matching glyphs.

Please adjust the EN DASH length so the difference is more apparent.

Thanks!

**Comment by davelab6** [comment]
@tamsky thanks for reporting this! I've opened an issue upstream :)

**Comment by alexeiva** [comment]
Fixed in https://github.com/cyrealtype/Inconsolata/issues/15, live update pending

**Comment by FloraCanou** [comment]
The hyphen should, admittedly, be shorter than en-dash, but I guess programmers mainly use hyphen-minus as minus sign and thus should be of equal width as plus sign, isn't it?

**Comment by tamsky** [comment]
Satisfied customer.
Would buy again.
A++++ developer.
=)
