### ISSUE TITLE
Add IBM Plex

### ISSUE THREAD

**Issue by hmaesta** [google/fonts#1378]
**https://github.com/IBM/type** ([Demo](https://ibm.github.io/type/))

![screen shot 2017-12-04 at 14 03 47](https://user-images.githubusercontent.com/741969/33562260-fbff6eb4-d8fb-11e7-941b-9da61a7f2a45.png)

**Comment by felipesanches** [comment]
"Typeface: IBM Plex"
"Carbon uses the new IBM open-sourced typeface, IBM Plex." at http://www.carbondesignsystem.com/style/typography/overview

**Comment by hmaesta** [comment]
@felipesanches Thanks, Felipe. Just updated.

**Comment by davelab6** [comment]
@hmaesta thanks for filing this; I am working with IBM to get an RFN permission in place.

**Comment by davelab6** [comment]
@m4rc1e quick update on this, I spoke to IBM folks and we'll not onboard the Text styles, since they are available from upstream for print, and don't fit the 9 weight slots available in CSS. Also, it seems that the OS/2 weightClass values of 100 and 200 don't trigger auto-bolding on Windows for TrueType-flavor OpenType files, only CFF-flavor, so we should be able accept the upstream TTFs without further modifications.

**Comment by win8linux** [comment]
Is there any update on this issue? Are there still any technical or legal roadblocks left to having this typeface on Google Fonts?

**Comment by davelab6** [comment]
@m4rc1e whats the status?

**Comment by m4rc1e** [comment]
Got them lined up on my fork. 

https://github.com/m4rc1e/fonts/pull/28
https://github.com/m4rc1e/fonts/pull/29
https://github.com/m4rc1e/fonts/pull/30

I'm just double checking the FB logs. Should be good for tonight.

**Comment by jmz7v** [comment]
@davelab6  Looks like it's good to go

**Comment by mkylemartin** [comment]
Would love to see Plex available in Google Docs! 
![image](https://user-images.githubusercontent.com/11202404/39550622-2c51dd0c-4e1f-11e8-9239-37fa60245692.png)

**Comment by iheidt** [comment]
@davelab6 Any insight on when this font might make it into Google Docs?

**Comment by MarkyCDavis** [comment]
Any updates on this? I assumed all google fonts would be available on google slides and now a client project might get get fucked up.

**Comment by davelab6** [comment]
I will try to get this done soon.

However as a workaround I believe the Extensis Google Docs Fonts extension
will get you out of the bind.

https://www.extensis.com/products/font-management/fonts-for-google-docs/
