### ISSUE TITLE
Ubuntu 300 showing as 400 weight

### ISSUE THREAD

**Issue by gvnet** [google/fonts#138]
Hi,
I have checked a site using ubuntu 300 and the font is now heavy like the 400 weight?
On checking the google font page, it also shows as heavier?
https://www.google.com/fonts#UsePlace:use/Collection:Ubuntu
![unbuntu 300](https://cloud.githubusercontent.com/assets/15390142/10836924/c7296424-7f07-11e5-9c4e-5662b43a35e4.jpg)

**Comment by davelab6** [comment]
Uninstall the fonts and look again :)

**Comment by gvnet** [comment]
Nice one - thank you sir.
