### ISSUE TITLE
Poppins Bold rendering as Regular

### ISSUE THREAD

**Issue by bgamache** [google/fonts#1380]
Im having an issue similar to issue #386 and #403, where Poppins bold is being recognized as just "poppins" by design programs such as Sketch and Illustrator and therefore rendering bold as regular. This issue does not seem to have been resolved with past updates.

![screen shot 2017-12-05 at 11 50 39 am](https://user-images.githubusercontent.com/34253136/33619196-8d27a3e6-d9b2-11e7-9f2f-22419a727cad.png)

**Comment by davelab6** [comment]
@bgamache thanks for reporting this. I've filed an issue upstream, hopefully this can be fixed in the next release.

**Comment by laerm0** [comment]
Our fonts served are currently at v3.100 and the weights are fixed: can I close this, @davelab6 ?

<img width="447" alt="screen region 2019-02-11 at 14 21 27" src="https://user-images.githubusercontent.com/10780161/52587760-be5ea300-2e08-11e9-8dca-9f9650afb2c1.png">

**Comment by emmamarichal** [comment]
Fixes in https://github.com/google/fonts/pull/1924
