### ISSUE TITLE
Josefin Sans Normal 400 is displaying at italic

### ISSUE THREAD

**Issue by just-trey** [google/fonts#139]
![download](https://cloud.githubusercontent.com/assets/10281380/10891116/174d0320-816a-11e5-951d-4a06989b75d7.png)
Josefin Sans Normal 400 font is deploying as Italic in all cases I have tested. Josefin Sans Normal 400 should not be italicized as Josefin Sans Normal 400 Italic covers this case.

**Comment by adrientetar** [comment]
Have you a copy installed on your computer? If so try to remove it.

**Comment by just-trey** [comment]
that fixed it but how does one remove the font form their phone or tablet?

**Comment by just-trey** [comment]
oh this appears to be identical to issue 28 btw. I did not see it until after i submitted.

**Comment by m4rc1e** [comment]
@just-trey thanks for reporting. You're correct, this is a dup of #28. Closing
