### ISSUE TITLE
Varela Round typeface "special character "ā"

### ISSUE THREAD

**Issue by marcjohnsonfr** [google/fonts#1393]
Dear all, 
How can I download the "Varela Round" typeface with special characters such as "ā"?
It is working on https://fonts.google.com/specimen/Varela+Round
however, when I downloaded it from GitHub it doesn't work.
Do you know why? 
Best, 
Marc
![screenshot 187](https://user-images.githubusercontent.com/18038998/34036161-a190b46a-e184-11e7-9996-955c23f0d28a.png)

**Comment by thlinard** [comment]
?? Version 3, the current version, is available here: https://github.com/alefalefalef/Varela-Round-Hebrew/blob/master/fonts/VarelaRound-Regular.ttf or here: https://github.com/google/fonts/blob/master/ofl/varelaround/VarelaRound-Regular.ttf

**Comment by marcjohnsonfr** [comment]
Thank you very much, you made my day ;)
Marc
