### ISSUE TITLE
Google fonts CDN returns 404 on open-sans cyryllic

### ISSUE THREAD

**Issue by Screatch** [google/fonts#14]
So this issue is not completely related to this repo, but I think here may be people responsible for this.

When loading fonts from
http://fonts.googleapis.com/css?family=Open+Sans:400,600,700&subset=cyrillic,latin

You get 404 error on
```
Request URL:http://fonts.gstatic.com/s/opensans/v10/MTP_ySUJH_bn48VBG8sNSpX5f-9o1vgP2EXwfjgl7AY.woff2
Request URL:http://fonts.gstatic.com/s/opensans/v10/RjgO7rYTmqiVp7vzi-Q5URJtnKITppOI_IvcXXDNrsc.woff2
Request URL:http://fonts.gstatic.com/s/opensans/v10/k3k702ZOKiLJc3WVjuplzJX5f-9o1vgP2EXwfjgl7AY.woff2
```

If shortly, latin fonts seem to load just fine but not cyryllic.

This issue broke fonts on many websites, I hope you can speed up fix for this issue.

**Comment by Screatch** [comment]
Seems to be fixed by now.

**Comment by rsheeter** [comment]
Thank you for filing this. This is the best public issue tracker to use for issues with Google Fonts of any kind.

A rare bad update snuck out :( Our on-call staff fixed it last night. Chrome users of Open Sans for non-latin were temporarily impacted.

**Comment by colethorsen** [comment]
I'm still seeing a problem where Open Sans Regular is rendering a fairly bold weight, it is happening in Safari and Chrome at least. I have only Latin selected, although in Chrome it is sending all the variants http://fonts.googleapis.com/css?family=Open+Sans:400italic,600italic,400,600&subset=latin and http://fonts.googleapis.com/css?family=Open+Sans:400italic,600italic,400,600 both only send Latin to Safari, but send all subsets to Chrome. The rendering of the 400 normal weight appears heavier than the 600 weight. If I activate my local copies of Open Sans it works as expected, and as it did previous to Yesterday.

**Comment by colethorsen** [comment]
Changing my DNS to a different DNS seems to have solved it.

**Comment by monecchi** [comment]
I'm using chrome  52.0.2743.116 (64-bit) on Mac and https://fonts.googleapis.com/css?family=Open+Sans:300,400,600&subset=latin returns all subsets, which takes forever to load. Safari does indeed download only the specified (latin) subset. That's a weird behavior!

**Comment by davelab6** [comment]
It doesn't take forevetto load because of unicode-range :)
