### ISSUE TITLE
Duplicate font families

### ISSUE THREAD

**Issue by groundh0g** [google/fonts#140]
I wrote a tool to parse the files for my project. I found that four font families are duplicated in the repo, usually due to a typo in the name of the folder.

```
Ignoring './google/ofl/misssaintdelafield' ...
Ignoring './google/ofl/mrbedford' ...
Ignoring './google/ofl/siamreap' ...
Ignoring './google/ofl/terminaldosis' ...
```

FYI.

**Comment by nathanhleung** [comment]
In [TRIVIA.md](https://github.com/google/fonts/blob/master/TRIVIA.md):

> There are some similarly named pairs of directories which each have identically named font files. These files are redundant, and exist following the renaming of a family. The initial directories are kept so that people already using that initial name can continue to do so. They are no longer listed in the main www.google.com/fonts directory, but the files exist in this repo since they are still served via the Google Fonts API.

**Comment by groundh0g** [comment]
Good to know it's a known issue. Thanks.
