### ISSUE TITLE
latin-ext: Add superscripts and subscripts unicode characters

### ISSUE THREAD

**Issue by gimler** [google/fonts#1401]
Hello, i try to get `&#2082;` `₂` to work with the [Source Sans Pro](https://fonts.google.com/selection?selection.family=Source+Sans+Pro) or other google fonts but no luck.

On the [test page](https://fonts.google.com/selection?selection.family=Source+Sans+Pro) i saw that the font include the character also in my generated pdf the character exists but not on the webpage. i think the unicode range is missing in the css?

see also 
[Unicode Block 'Superscripts and Subscripts'](http://www.fileformat.info/info/unicode/block/superscripts_and_subscripts/index.htm)

**Comment by davelab6** [comment]
You need to request it using the `text=` API parameter (https://developers.google.com/fonts/docs/getting_started#optimizing_your_font_requests)

@roozbehp another candidate for latin-ext?

**Comment by alabbasinour** [comment]
Any update on this issue?

**Comment by simoncozens** [comment]
This is a duplicate of #1350.
