### ISSUE TITLE
Add Hanken Grotesk

### ISSUE THREAD

**Issue by cssobral2013** [google/fonts#1412]
https://fontlibrary.org/pt/font/hk-grotesk

**Comment by davelab6** [comment]
@cssobral2013  thanks for suggesting this

**Comment by cssobral2013** [comment]
This font doesn't support CJK.

**Comment by chakler** [comment]
Yeah CJK is not supported; I think the HK here stands for “HanKen,” not Hong Kong.
The designer—Alfredo Marco Pradil—is a member of the Type Philippines Facebook group, and here’s his website—

https://hanken.co/

**Comment by lalitpatel** [comment]
HK Grotesk is a great font! I have shared this request the designer of the font. It would be great to get this font on Google Fonts 🤞🏻

**Comment by davelab6** [comment]
Oh - I didn't look closely. 

https://github.com/google/fonts/blob/master/CONTRIBUTING.md says, emphasis added,

> The font family name does not include any copyright holder names or registered trademarks, **and no initials or abbreviations**; it should be a simple and unique name, and a limited but easy way to test for uniqueness is namecheck.fontdata.com

Would Alfredo consider renaming it?

**Comment by lalitpatel** [comment]
Hi @davelab6, I talked to Alfredo from Hanken and he is very happy to rename this font. I have shared the guidelines with him and also shared the link to this thread. He will post an update here once he is done publishing this font under a different name. Cheers!

**Comment by davelab6** [comment]
Awesome, thanks for that!!

**Comment by marcologous** [comment]
Thanks @lalitpatel and @davelab6 for keeping this thread up! It has been a while. Yeah regarding the name of the typeface, I have changed it to Hanken Grotesk. Hopefully that is ok. Thanks @chakler for clearing that one up =)

**Comment by marcologous** [comment]
https://fontlibrary.org/en/font/hk-grotesk

**Comment by lalitpatel** [comment]
Hi @davelab6, let me know if you need any other info / changes to make this happen! Happy to help 😃

**Comment by cssobral2013** [comment]
Title updated to reflect the font name change.

**Comment by thundernixon** [comment]
This would need a repo with font sources (e.g. Glyphs file or UFOs) and an OFL license

**Comment by lalitpatel** [comment]
> This would need a repo with font sources (e.g. Glyphs file or UFOs) and an OFL license

@marcologous FYI

**Comment by marcologous** [comment]
Hi @thundernixon , I will create a repo for this!

**Comment by dnix** [comment]
any chance there is still headway being made on this? would be glad to assist. thanks!

**Comment by thundernixon** [comment]
@dnix nothing is happening right now, as the backlog is fairly large. To onboard new fonts, we need to:
- set them up to build into variable and static fonts, using fontmake
- run the results through fontbakery and clear up any applicable `fail` and `warn` items
- PR to google/fonts

One of the trickier parts currently is that there are some things in flux, from with the introduction of variable fonts into fontbakery and google fonts, so a few of the issues flagged by fontbakery may not be applicable, even though most are. However, if you'd like to take a go, that would be terrific!

More information is here (and in the adjacent docs): https://github.com/googlefonts/gf-docs/tree/master/MasteringNewFamiliesForGF

**Comment by bghryct** [comment]
@marcologous 
Any update on making a repo of Hanken Grotesk? I'm interested in running the required testing and building @thundernixon mentioned.

**Comment by Xylobol** [comment]
Any progress on this?
I emailed @marcologous a bit back regarding source availability, but he never responded.

**Comment by bghryct** [comment]
hey not a lot of progress I'm also not hearing back from @marcologous. If anyone were so inclined they could migrate the font binaries that exist to a new source format and put those sources in source folder of a fork of HK Grotesk.

**Comment by Xylobol** [comment]
I've been thinking of doing it. I've been tracking this issue because I'd love to fork Hanken Grotesk for a brand I've been developing. If I get around to it, I'll "transcribe" the font to a proper format (probably .glyphs or .vcf) and publish it first, so everyone can also get the original version's source, as they should be.

**Comment by bghryct** [comment]
Would have been my course of action as well, I'm just in the middle of several other font migrations atm and don't have the time. LMK if you end up doing it.

**Comment by Xylobol** [comment]
I emailed him again a dozen hours ago or so, still no response. I don't think he's going to be helping with this.

**Comment by marcologous** [comment]
Hey all! I am really sorry for not participating in this. I am for sure going to create a repo for the sources. Anyone can help me achieve this?

**Comment by marcologous** [comment]
@Xylobol I have them... can you please help with the steps?

**Comment by Xylobol** [comment]
Definitely!

The first thing you're going to want to do is to create a Git repo on GitHub. To do this, you can head [here](https://github.com/new). Make sure it's set to public. Initialize the repo with a README. 

Make sure you've got git installed on your computer, and clone the repo. To do this, get the clone URL, and run this command in your terminal: 
```
$ git clone <URL>
```

After that's done, copy the OFL and the source files into the directory, then run these commands:
```
$ git add *

$ git commit -m "Add license and source"

$ git push origin master
```

You may need to provide authentication.

Let us know when that's done!

Thanks in advanced.

**Comment by marcologous** [comment]
@Xylobol Thanks a lot! Will get to it... bear with me

**Comment by Xylobol** [comment]
Any progress?

**Comment by Xylobol** [comment]
It'd appear that @marcologous has created a repo with the files! https://github.com/marcologous/hanken-grotesk

**Comment by bghryct** [comment]
very cool

**Comment by marcologous** [comment]
@Xylobol @bghryct Please let me know how it goes!

**Comment by marcologous** [comment]
> This would need a repo with font sources (e.g. Glyphs file or UFOs) and an OFL license

Done!

**Comment by marcologous** [comment]
@davelab6 / @lalitpatel : Any support still on this?

**Comment by bghryct** [comment]
I think there's limited support at the moment. Have you run HK Grotesk through [FontBakery?](https://github.com/googlefonts/fontbakery)

**Comment by bghryct** [comment]
@marcologous I'm happy to talk about fontbakery QA, FontQA in general.

**Comment by marcologous** [comment]
> @marcologous I'm happy to talk about fontbakery QA, FontQA in general.

hey @bghryct totally cool to talk about that! So basically we need to do some diagnostics on the fonts?

**Comment by bkawk** [comment]
Any updates?

**Comment by willviles** [comment]
Big fan of HK Grotesk, thank you @marcologous. I would love this to be available via Google Fonts if you've got the time to dedicate to it.

**Comment by marcologous** [comment]
> Big fan of HK Grotesk, thank you @marcologous. I would love this to be available via Google Fonts if you've got the time to dedicate to it.

I would love to as well! It is just a matter of time =)

**Comment by marcologous** [comment]
> Any updates?

Need to find time and help on this project! =(

**Comment by marcologous** [comment]
Anybody here who can help me do the diagnostics for uploading to Google Fonts? Please?

**Comment by marcologous** [comment]
> Awesome, thanks for that!!

Hey @davelab6 ! You know who can help me out with preparing Hanken Grotesk?

**Comment by antonija-nosto** [comment]
> Anybody here who can help me do the diagnostics for uploading to Google Fonts? Please?

I never uploaded font to Google Fonts but let me know how can I be of assistance?

**Comment by ArpanSriv** [comment]
Please let me know if I can help @marcologous.

I tried running the Google Fonts > QA Script on the glpyhs in the GlyphsApp from @marcologous's repo . (Specifically on the 'sources/Hansenk Grotesk.glpyhs' file since there are two glyph files.)

I got the following output:

`Start
Traceback (most recent call last):
  File "qa.py", line 817, in <module>
    TestProgram(argv=['--verbose'], exit=False, testRunner=GlyphsTestRunner)
  File "main.py", line 95, in __init__
    self.runTests()
  File "main.py", line 232, in runTests
    self.result = testRunner.run(self.test)
  File "runner.py", line 27, in run
    test(result)
  File "suite.py", line 70, in __call__
    return self.run(*args, **kwds)
  File "suite.py", line 108, in run
    test(result)
  File "suite.py", line 70, in __call__
    return self.run(*args, **kwds)
  File "suite.py", line 108, in run
    test(result)
  File "case.py", line 393, in __call__
    return self.run(*args, **kwds)
  File "case.py", line 333, in run
    result.addFailure(self, sys.exc_info())
  File "result.py", line 11, in addFailure
    self.failures.append((title, (self._exc_info_to_string(err, test))))
  File "result.py", line 40, in _exc_info_to_string
    return ''.join(map(str, msgLines))
UnicodeEncodeError: 'ascii' codec can't encode character u'\xa9' in position 67: ordinal not in range(128)
End
`

I'm new to all this font baking and stuff, so can anyone guide me what to do and how to fix this? I'm ready to help.

**Comment by ArpanSriv** [comment]
I also tried the [Fonts Inspection step](https://github.com/googlefonts/gf-docs/tree/master/MasteringNewFamiliesForGF#design-inspection) and found this:

<img width="370" alt="Screen Shot 2020-03-29 at 7 26 42 PM" src="https://user-images.githubusercontent.com/19208765/77850906-3b0e3580-71f3-11ea-8299-48b8217a91d4.png">


As per my inspection, it looked fine. Anything I had to do here that I'm missing?

**Comment by ArpanSriv** [comment]
I also ran the fonts through fontbakery @bghryct. Seems like there are a lot of errors to fix. @marcologous 

<img width="807" alt="Screen Shot 2020-03-29 at 7 41 07 PM" src="https://user-images.githubusercontent.com/19208765/77851187-3e0a2580-71f5-11ea-87f0-6efca12099af.png">

**Comment by bghryct** [comment]
My understanding is that basically all of those fails need to be addressed before gf will consider merging it into the collection.

**Comment by ArpanSriv** [comment]
Yes so @marcologous  I'll (try) start fixing these errors and submit Pull Request to your repo? Or you will do them?

**Comment by antonija-nosto** [comment]
I have very basic knowledge about creating fonts but if somebody wants me to help I am available.

**Comment by marcologous** [comment]
> Yes so @marcologous I'll (try) start fixing these errors and submit Pull Request to your repo? Or you will do them?

Hi @ArpanSriv , it would be great to get some help in doing the fixes!

**Comment by marcologous** [comment]
> I have very basic knowledge about creating fonts but if somebody wants me to help I am available.

@antonija-nosto I think of myself as a type designer in progress as well! Hanken Grotesk is one of my first typefaces and over the years I did not get a great opportunity to do a practical assessment of it. But your help will be greatly appreciated!

**Comment by antonija-nosto** [comment]
> > I have very basic knowledge about creating fonts but if somebody wants me to help I am available.
> 
> @antonija-nosto I think of myself as a type designer in progress as well! Hanken Grotesk is one of my first typefaces and over the years I did not get a great opportunity to do a practical assessment of it. But your help will be greatly appreciated!

I am unsure of what to do to help. If you would give me a task I would do anything in my power to make this typeface appear on google fonts.

**Comment by marcologous** [comment]
Hi all! I have updated the repo with the new fonts and hopefully will have better results. Question @ArpanSriv . How do I run FontBakery?

**Comment by ArpanSriv** [comment]
@marcologous Hey! Good to hear that.
You'll have to either:
1. Install [font-bakery](https://github.com/googlefonts/fontbakery) depending on your platform. 
2. Or there's a website I just found today (never tried) where you can do it online as well. [Link to Website](https://fontbakery.graphicore.de/)

**Comment by marcologous** [comment]
Hey @ArpanSriv yeah just saw the website yesterday as well... I am working on some changes. I will let you all know regarding updates!

**Comment by davelab6** [comment]
@marcologous please could you schedule a video call with @felipesanches who is in Sao Paulo, he can help you finalize all the details! :)

**Comment by felipesanches** [comment]
@marcologous I'm the maintainer and main developer of FontBakery. I will be glad to help give an overview of our methodology for font QA and onboarding of families into Google Fonts.

**Comment by marcologous** [comment]
> @marcologous please could you schedule a video call with @felipesanches who is in Sao Paulo, he can help you finalize all the details! :)

Awesome!!! That is great T_T

**Comment by marcologous** [comment]
> @marcologous I'm the maintainer and main developer of FontBakery. I will be glad to help give an overview of our methodology for font QA and onboarding of families into Google Fonts.

Hi @felipesanches , I am currently in the UAE, what time would be convenient for you? Sorry for the late reply. Really appreciate it!

**Comment by felipesanches** [comment]
hey, @marcologous! Sorry that it took a while for me to reply, I was a bit busy these past few days. Please join our gitter chat at https://gitter.im/fontbakery/Lobby and then we'll be able to setup a video call.

My intention is to give you an overview of what Font Bakery does and how to use it, and then review the github repo for this font family and suggest some procedures for our collaboration. My goal is to be able to make this font family ready for inclusion on the Google Fonts collection by the end of June. But I am not promising that's going to happen at all. It is just my personal goal. We may have some roadblocks in our path. There's no guarantee that the family will be included in the collection, but I will do my best to make this happen.

**Comment by marcologous** [comment]
@felipesanches Thank you so much for this! I have joined the chat. I don't know the approach in there but maybe will wait when you are available? I also found the FontBakery website that @ArpanSriv mentioned earlier. I am making some improvements to the fonts and haven't updated the repo yet.

**Comment by felipesanches** [comment]
I'm there right now! LOL

**Comment by davelab6** [comment]
I chatted to @felipesanches about this today and we expect this should be ready within a few weeks.

**Comment by marcologous** [comment]
Working on some issues right now @davelab6 !

**Comment by ocripps24** [comment]
If help is still needed, let me know as I'm happy to learn and help!

**Comment by felipesanches** [comment]
I've been working with @marcologous during the past month and we've got it in good shape. I'll be posting a pull request this week with the latest font files we've prepared. Hopefully they're good enough to be added to the collection soon. Still pending a final review though.

**Comment by marcologous** [comment]
Thanks @felipesanches !

**Comment by davelab6** [comment]
@felipesanches what is the status of this? :)

**Comment by felipesanches** [comment]
The font family builds and passes all Font Bakery checks, but there are a few warnings emitted by **fontmake** that I do not understand such as this one:

![Screenshot from 2020-08-01 11-49-55](https://user-images.githubusercontent.com/213676/89104173-9f354600-d3ed-11ea-9562-355b47c2854d.png)

**Comment by felipesanches** [comment]
I'll open a few more issues listing all of the suspicious warnings next Monday morning and I'll try to address them

**Comment by marcologous** [comment]
@felipesanches I saw a thread regarding Axis location on somewhere in the fontbakery repo. I think a custom parameter needs to be added to each of the instances.

**Comment by felipesanches** [comment]
yeah, but I am not sure exactly which setting would that be. We still need to figure it out.

**Comment by pacifier007** [comment]
Guys any update on this one? Been watching this since a year. Really hope this makes it to Google Fonts.

**Comment by marcologous** [comment]
Hi @pacifier007! The process is ongoing! Hopefully, it will make it soon :)

**Comment by maxloh** [comment]
@RosaWagner Any updates?

**Comment by vv-monsalve** [comment]
Hi @marcologous, could you please inspect and merge the [PR opened](https://github.com/marcologous/hanken-grotesk/pull/73) on upstream?
