### ISSUE TITLE
Update Barlow font family (1.101-Pre Release -> 1.208)

### ISSUE THREAD

**Issue by Simek** [google/fonts#1414]
It will be nice if you can update Barlow font family to latest version, because current one have some issues with non english characters/languages.

Git Repo: https://github.com/jpt/barlow
Detailed changelog: https://github.com/jpt/barlow/releases

Changes summary:
- kerning fixed on a number of non-English characters
- various spacing and other kerring tweaks
- optimisation to Condensed Black variant
- and more...

Refs #1330

**Comment by jpt** [comment]
@Simek +1!

This likely hasn't be a priority because jpt/barlow#14 and jpt/barlow#15 have been open, which are fixed in Barlow v1.300, released today :)

so I would guess this is coming soon -- #1330 is about to change to "update to v1.3"

**Comment by Simek** [comment]
Nice to hear that @jpt! Thank you for great font and releasing it on OFL license.

I'm closing that issue, since it's a duplicate and update is on the way.
