### ISSUE TITLE
Problem with poppins font and numbers

### ISSUE THREAD

**Issue by pantonis** [google/fonts#1421]
I am using Poppins in my web app and I have numbers that refresh in real-time.
Problem when I am using Poppins font is that number is keep getting resized based on the number digits. This is very irritating with no good UX.
I have attached a moving gif that shows the problem. On the left I have Tahoma and on the right figure I have Poppins. Check the size of the figure on the right which is being getting resized all the time.

![number-problem](https://user-images.githubusercontent.com/3295086/35149430-b12496d4-fd1e-11e7-8574-e2ba602daf33.gif)

**Comment by m4rc1e** [comment]
Poppins doesn't have tabular figures.

**Comment by pantonis** [comment]
tabular figures?

**Comment by m4rc1e** [comment]
https://www.fonts.com/content/learning/fontology/level-3/numbers/proportional-vs-tabular-figures

**Comment by pantonis** [comment]
@m4rc1e There is no way to solve this?

**Comment by m4rc1e** [comment]
Not unless they're added to the fonts I'm afraid.

**Comment by pantonis** [comment]
OK. Can I request such a change?

**Comment by m4rc1e** [comment]
Sure! make a request in the upstream repo, https://github.com/itfoundry/Poppins

Cheers!

**Comment by pantonis** [comment]
Thanks

**Comment by pantonis** [comment]
@m4rc1e One last question. How can I check if a font is proportional or tabular?

Thanks

**Comment by m4rc1e** [comment]
You can check by inputting a the following string into the type tester

> 000011110000

With Poppins we get

![screen shot 2018-01-19 at 12 45 03](https://user-images.githubusercontent.com/7525512/35151551-a81daaf6-fd16-11e7-870f-e291d6057885.png)

We can see that the 1s are narrower than the 0 (in tabular they must be the same)

For Roboto which is tabular we get:

![screen shot 2018-01-19 at 12 47 32](https://user-images.githubusercontent.com/7525512/35151626-f462d27e-fd16-11e7-89b4-6e8f43e55fda.png)

We can also see that the line lengths for Roman and Italic are consistent.

**Comment by pantonis** [comment]
Thanks again!
