### ISSUE TITLE
bug with url encoding request

### ISSUE THREAD

**Issue by borisov87** [google/fonts#1422]
for example url
https://fonts.googleapis.com/css?family=PT+Sans+Narrow:400,700&subset=latin,latin-ext,cyrillic,cyrillic-ext&ver=1.0.0

open font
but same url encoded not work
https://fonts.googleapis.com/css?family=PT%2BSans%2BNarrow%3A400%2C700&subset=latin%2Clatin-ext%2Ccyrillic%2Ccyrillic-ext&ver=1.0.0

**Comment by borisov87** [comment]
mxm may be theme bug, but i see they use urlencode
if ( $fonts ) {
		$fonts_url = add_query_arg( array(
			'family' => urlencode( implode( '|', $fonts ) ),
			'subset' => urlencode( $subsets ),
		), 'https://fonts.googleapis.com/css' );
	}

i think with urlencode all must be ok?

**Comment by borisov87** [comment]
ok is use htmlentities and now all is ok

**Comment by davelab6** [comment]
@borisov87 thanks for reporting this and @sladen thanks for explaining
