### ISSUE TITLE
Add Space Text

### ISSUE THREAD

**Issue by mightybart** [google/fonts#1425]
https://github.com/floriankarsten/space-text

![Space Text](https://fonts.floriankarsten.com/files/space-grotesk-preview.png)

Look! Space Mono has a new friend...

Some comparison to Space Mono:
https://www.instagram.com/p/Bcsz0tGgpKf/
https://www.instagram.com/p/BdtCc6Sg2tX/

**Comment by davelab6** [comment]
@mightybart haha awesome :)

**Comment by mightybart** [comment]
Update: Space Text is now Space Grotesk
