### ISSUE TITLE
Update Amiri Font

### ISSUE THREAD

**Issue by Cophla** [google/fonts#1426]
new version released:
https://github.com/alif-type/amiri/releases/tag/0.111

**Comment by davelab6** [comment]
@Cophla thanks for reporting this

**Comment by Cophla** [comment]
Welcome

**Comment by khaledhosny** [comment]
Can you please please update the font? I’m regularly getting reports about bugs I fixed years ago. There have been 3 releases, roughly one per year since the font was last updated on Google Fonts, my release rate is not that overwhelming.

**Comment by m4rc1e** [comment]
@khaledhosny feel free to submit a pr and we can review it.

**Comment by m4rc1e** [comment]
Would it be possible to rename the "Slanted" styles to "Italic"? AFAIK, our api doesn't accept slanted.

**Comment by m4rc1e** [comment]
Alright, pr sent https://github.com/google/fonts/pull/2437. I'll get back to you if we need anything fixed.

**Comment by m4rc1e** [comment]
Closing this since Amiri v0.113 is now in production.
