### ISSUE TITLE
Coustard Regular.ttf can't be installed

### ISSUE THREAD

**Issue by enjoytheloop** [google/fonts#143]
Hi,

I can't install Coustard Regular.ttf on Mac OS X, there's no problem installing the Bold one, but when installing the Regular, it just doesn't appear anywhere on the catalogue, nor user fonts, web fonts or system fonts.

I have checked the file with the catalogue tool, and it seems to be OK.

What's wrong?

I need it to match some text on images with website style.

Thank you very much indeed.

**Comment by m4rc1e** [comment]
Hello,

Which version of OS X are you using?

On 10.11.3, I don't get this issue.

![screen shot 2016-08-30 at 11 40 46](https://cloud.githubusercontent.com/assets/7525512/18084259/cc6e2e62-6ea6-11e6-8047-d7fbb8c18432.png)

![screen shot 2016-08-30 at 11 42 37](https://cloud.githubusercontent.com/assets/7525512/18084278/df27b992-6ea6-11e6-8fce-0325d983227f.png)

Cheers,
Marc

**Comment by m4rc1e** [comment]
Closing, LGTM

Font was updated recently, #881 

I still can't replicate this error.

![screen shot 2017-06-15 at 12 28 03](https://user-images.githubusercontent.com/7525512/27179352-1aeaefbe-51c6-11e7-8625-fbecb968eedd.png)


![screen shot 2017-06-15 at 12 28 34](https://user-images.githubusercontent.com/7525512/27179365-2a469d3c-51c6-11e7-898c-d668afcebfc2.png)

https://fonts.google.com/specimen/Coustard
