### ISSUE TITLE
Add Inria

### ISSUE THREAD

**Issue by davelab6** [google/fonts#1439]
https://github.com/BlackFoundry/InriaFonts/

**Comment by davelab6** [comment]
Note, has an RFN

**Comment by m4rc1e** [comment]
Families are now on Google Fonts, https://fonts.google.com/?query=inri

**Comment by yanone** [comment]
Manually linking PRs: 
https://github.com/google/fonts/pull/2272
https://github.com/google/fonts/pull/2273
