### ISSUE TITLE
Scheherazade missing 113 hex and 14d hex

### ISSUE THREAD

**Issue by webservant317** [google/fonts#1449]
My software Speedata/TeX is complaining saying...

```
Error: Glyph 113 (hex) is missing from the font "Scheherazade"
Error: Glyph 14d (hex) is missing from the font "Scheherazade"
``` 

Can these Glyphs be added to Scheherazade?

**Comment by davelab6** [comment]
@webservant317 you should test with the latest version available from SIL, and repor this issue to them.
