### ISSUE TITLE
No full name for Khand

### ISSUE THREAD

**Issue by dywedir** [google/fonts#145]
```
% otfinfo -i Khand-Light.ttf 
Family:              Khand Light
Subfamily:           Regular
Vendor ID:           ITFO
```

**Comment by N-006** [comment]
Khand from Google fonts site is ok.

**Comment by v1kn** [comment]
Any progress on this issue?

**Comment by nekinie** [comment]
This has been causing me troubles, any progress?

fixme:font:get_outline_text_metrics failed to read face_nameW for font L"Khand"!
fixme:font:get_outline_text_metrics failed to read full_nameW for font L"Khand"!
fixme:font:get_outline_text_metrics failed to read face_nameW for font L"Khand Black"!
fixme:font:get_outline_text_metrics failed to read full_nameW for font L"Khand Black"!
fixme:font:get_outline_text_metrics failed to read face_nameW for font L"Khand Bold"!
fixme:font:get_outline_text_metrics failed to read full_nameW for font L"Khand Bold"!
fixme:font:get_outline_text_metrics failed to read face_nameW for font L"Khand ExtraBold"!
fixme:font:get_outline_text_metrics failed to read full_nameW for font L"Khand ExtraBold"!
fixme:font:get_outline_text_metrics failed to read face_nameW for font L"Khand ExtraLight"!
fixme:font:get_outline_text_metrics failed to read full_nameW for font L"Khand ExtraLight"!
fixme:font:get_outline_text_metrics failed to read face_nameW for font L"Khand Light"!
fixme:font:get_outline_text_metrics failed to read full_nameW for font L"Khand Light"!
fixme:font:get_outline_text_metrics failed to read face_nameW for font L"Khand SemiBold"!
fixme:font:get_outline_text_metrics failed to read full_nameW for font L"Khand SemiBold"!
fixme:font:get_outline_text_metrics failed to read face_nameW for font L"Khand SemiLight"!
fixme:font:get_outline_text_metrics failed to read full_nameW for font L"Khand SemiLight"!

**Comment by davidbarton** [comment]
Any progress here guys?

**Comment by jakobhans** [comment]
I don't think this is issue is being addressed at all...

**Comment by abhinavgaur** [comment]
No progress still ? Its 2017 !! :-1:

**Comment by qnoox** [comment]
An update was released but it did not fix this issue :-1:

**Comment by jakebailey** [comment]
FYI, the most recent update to Khand (#899) brings in all of the missing full names:
```
$ for i in *.ttf; do echo -n "$i "; otfinfo -i $i | grep Full; done
Khand-Bold.ttf Full name:           Khand Bold
Khand-Light.ttf Full name:           Khand Light
Khand-Medium.ttf Full name:           Khand Medium
Khand-Regular.ttf Full name:           Khand Regular
Khand-SemiBold.ttf Full name:           Khand SemiBold
```
Noticed the lack of warnings during a package rebuild.
