### ISSUE TITLE
Update Source Code Pro (add italics)

### ISSUE THREAD

**Issue by mrerickdavid** [google/fonts#1453]

**Comment by fitojb** [comment]
The italics of what family?

**Comment by rodriguezponce** [comment]
My bad. I was asking Adobe to upload their italics for Source Code Pro to Google Fonts and they told me to ask here. Am I in the right place?

**Comment by davelab6** [comment]
You are in the right place. I am not sure, do the italics have the same glyph set as the roman?

**Comment by rodriguezponce** [comment]
I don't understand your question about the glyph set. I saw the true **italics** for Source Code Pro on their [repository page](https://adobe-fonts.github.io/source-code-pro) but they're missing from the Google Fonts page.

**Comment by davelab6** [comment]
Its okay, don't worry. Thanks for the reminder to do this :)

**Comment by rodriguezponce** [comment]
Are you guys still working on this?

**Comment by fanninpm** [comment]
(c.f. #1670)

**Comment by m4rc1e** [comment]
Latest release is now on Google Fonts, https://fonts.google.com/specimen/Source+Code+Pro
