### ISSUE TITLE
Add Fira Code - on deck to merge!

### ISSUE THREAD

**Issue by tonsky** [google/fonts#1460]
https://github.com/tonsky/FiraCode

please. Let me know if you need something changed/altered

**Comment by davelab6** [comment]
I decided not to include this (https://github.com/google/fonts/pull/520)

**Comment by tonsky** [comment]
Oh, sorry, this is different.

Fira Code (original, my repo) is a significantly different version that adds more than 100+ ligatures to Fira Mono, designed to improve how programs (code) looks on screen. It’s a big change and huge value added for programmers, compared to “just monospaced letters”.

I released it Nov, 11 2014 and it’s been growing in popularity ever since. To date it’s the most popular programming font with ligatures (20k+ stars on GitHub) and it’s been the pioneer of that movement from the beginning, forcing IDEs to add support for it, for example (Atom, Idea, VS Code, iTerm 2, Sublime Text—none of them had it in 2014, and added ligatures support because of Fira Code pressure). You can browse through some feedback here: https://twitter.com/search?q=Fira%20Code&src=typd

There’s been a long-standing request to get Fira Code on the web https://github.com/tonsky/FiraCode/issues/18, and the Google Fonts is amongst most popular ones and easiest to use. Using ligatures on web is both possible and desirable, and hosted Fira Code would be the best way to do so.

On names: on Oct 17, 2016 (2 years after my Fira Code release) Carrois released another version of Fira Mono, as you noticed, with altered line-height, which they unfortunately called Fira Code as well. As far as I know, nobody is very attached to that version of Fira Mono, either as a name or as a font. 

I hope my arguments convince you that Fira Code name is de facto associated with ligatures font, which I ask you to add in this issue. Please reconsider. And thank you for what you’re doing!

Best,
Nikita

**Comment by eriawan** [comment]
@davelab6 
I support @tonsky comment above. Fira Mono is simply a fork of Fira Code, and both of them are different.

> Fira Code (original, my repo) is a significantly different version that adds more than 100+ ligatures to Fira Mono, designed to improve how programs (code) looks on screen

Yes, his comment above is also true.
Please reconsider to add the original Fira Code to Google Fonts.

**Comment by AronT-TLV** [comment]
👆👆🏻👆🏼👆🏽👆🏾👆🏿

Fira Code is THE best font for code editing. Fira Mono doesn’t come close. Please reconsider

**Comment by ai** [comment]
Ligatures of Fira Code is very useful

**Comment by pozda** [comment]
@tonsky made usable font for developers, i have been using it for year and half. it would be great for us developers to have it as google font so we can use it on posts and pages in code blocks. 

i'm supporting @tonsky 100% on this.

also fira mono? why should i as developer use that instead of tonsky's font?

**Comment by YBogomolov** [comment]
Fira Code's ligatures is one of the best things that happened to my Haskell and JS development experience. I strongly support @tonsky on this.

**Comment by davelab6** [comment]
Thanks for all the context, everyone :) 

If there's real utility in this, I'm happy to add it - but, I would rather see this contributed upstream into Fira Mono proper. 

I heard that @carrois is working on a new version of the Fira font (https://github.com/bBoxType/FiraGO) but that currently has Mono/Code version as a future plan on the roadmap.

@tonsky would you be willing to contribute your work upstream? :)

**Comment by tonsky** [comment]
I discussed that when I just started Fira Code, they didn’t want contributions back then (4 years ago), but had plans to reimplement that themselves. As you can see, they are still plans, Mono hasn’t changed much since then. I think they have different focus (Sans, not Mono) and lack of funding (it’s open font after all) which makes all changes in Fira really, really slow

**Comment by eriawan** [comment]
@davelab6 

> I heard that @carrois is working on a new version of the Fira font (https://github.com/bBoxType/FiraGO) but that currently has Mono/Code version as a future plan on the roadmap.

Why do you insist on using Fira Mono? Knowing the fact that Fira Code is far more active and better font than Fira Mono, also I couldn't even see a concrete roadmap on Fira Mono. Please elaborate.
Also imho @tonsky is correct about the prolonged inactive of Fira Mono.

**Comment by resoursa** [comment]
+ from me

**Comment by MHLut** [comment]
Bump! I love this font. It's easy to read and has been my go-to programming font for years, also, the included ligatures are a plus.

**Comment by blackxored** [comment]
I second this.

**Comment by davelab6** [comment]
@eriawan the product values include simplicity, and having lots of versions of the same typeface is confusing. When I first looked at this, I said line-space can be controlled on the web via CSS so there was no need for this. Now I am ok to add it because there is a value.

**Comment by eriawan** [comment]
@davelab6 
Great! Thanks for this wonderful decision updates!

**Comment by davelab6** [comment]
> Why do you insist on using Fira Mono? 

We have permission from Mozilla to use Fira Mono, but not Fira Code. Maybe Mozilla can drop the RFN :)

Also, I believe FiraGO has been funded, per the legal details in that README :)

**Comment by stamminator** [comment]
> I discussed that when I just started Fira Code, they didn’t want contributions back then (4 years ago), but had plans to reimplement that themselves. As you can see, they are still plans, Mono hasn’t changed much since then. I think they have different focus (Sans, not Mono) and lack of funding (it’s open font after all) which makes all changes in Fira really, really slow
\- @tonsky 

For this reason, I think it's reasonable for Google to reconsider adding this as its own font. Who wants to wait around forever for this?

**Comment by tonsky** [comment]
I’m currently [awaiting reply from Mozilla](https://github.com/mozilla/Fira/issues/218), but they don’t seem to be very responsive. Contact email is dead too :(

**Comment by rob10e** [comment]
Fira Code for the win!
Please add Fira Code, I use it in all of my development environments.

**Comment by johnmichel** [comment]
@davelab6 Given the RFN removal, is there any new traction on getting this added?

**Comment by JavierSegoviaCordoba** [comment]
Fira Code >= Fira Mono

Woops... so ugly this '>=' because GitHub doesn't has ligatures like Fira Mono

**Comment by stamminator** [comment]
@JavierSegoviaCordoba I use https://userstyles.org/styles/37035/github-dark for dark mode on GitHub, and it also makes choosing the font easy. Just enter whatever version of Fira Code you have installed on your OS into the "Code Font" field under "Customize Settings" (in my case, it's "Fira Code Regular"), and you're good to go. 

![image](https://user-images.githubusercontent.com/10633170/44664430-424edb00-a9e1-11e8-9c97-ce4fde96b6e8.png)

**Comment by stamminator** [comment]
@Ir1d Requests have been made, but [Google isn't responding](https://twitter.com/FiraCode/status/1046697379532034048)

**Comment by davelab6** [comment]
Yes with rfn removed we are unblocked, but our queue is processed slowly.

**Comment by napei** [comment]
@davelab6 This would be awesome to add. Best programming font, period

**Comment by rhurstdialpad** [comment]
Any chance this will be in in the coming weeks? I would like to use this font for my Monaco editor instances, and it would be ideal if I could source my fonts from Google fonts.

**Comment by RobertWHurst** [comment]
Any chance this will be added in the next few weeks? I'd like to use FiraCode for my Monaco editor instances, and ideally source my fonts from Google fonts.

**Comment by cfanoulis** [comment]
bump. anything on this?

**Comment by rnetonet** [comment]
Anyway we can help with this ? Testing or something ?

**Comment by davelab6** [comment]
We will add it soon. We've been developing testing and comparison tools to
help accelerate our font onboarding and update processes.

**Comment by thundernixon** [comment]
@davelab6 Wait, is the RFN really removed?

https://github.com/mozilla/Fira/blob/master/LICENSE#L1  currently includes:

> Digitized data copyright (c) 2012-2015, The Mozilla Foundation and Telefonica S.A.
with Reserved Font Name < Fira >,

**Comment by davelab6** [comment]
Yes, but the pr (https://github.com/mozilla/Fira/pull/219) wasn't merged, but the rfn was cleared to be removed.

**Comment by thundernixon** [comment]
Awesome, thanks for letting me know!

**Comment by thundernixon** [comment]
@davelab6 what would you suggest for the designer & copyright info in this font?

Much of the design of the typeface was by Carrois & Edenspiekerman (based on [the font info for Fira Mono](https://github.com/mozilla/Fira/blob/73645a967e9bfc8fc9c67d630cff517e781a0590/source/ufo/Fira%20Mono-Regular.ufo/fontinfo.plist)), then extended by @tonsky.

Here's the existing font info:

![image](https://user-images.githubusercontent.com/7355414/55011148-df93e100-4fbb-11e9-8ffc-be734a55f36f.png)

And here's my proposal – does this look good?

![image](https://user-images.githubusercontent.com/7355414/55011968-13233b00-4fbd-11e9-9276-70882d3dc6c7.png)

**Comment by thundernixon** [comment]
Fira Code is QAed and ready to merge, but is currently blocked by [mozilla/Fira#219](https://github.com/mozilla/Fira/pull/219).

If folks come across this who would like to see Fira Code on Google Fonts, go upvote that PR.

**Comment by cfanoulis** [comment]
The PR above has been merged recently :tada:

cc: @thundernixon @davelab6

**Comment by dhouck** [comment]
How long do things typically remain on deck to merge before they actually get merged?

**Comment by lukepighetti** [comment]
Its like I can hear the machinery turning in the distance.

**Comment by lifepeer** [comment]
The fact that this no-brainer has so far taken 1 year 4 months 18 days and 23 hours, and still isn't done, is quite depressing. :(

**Comment by cfanoulis** [comment]
Uhh, why was this closed? It surely isnt because it was added, since https://fonts.google.com/?query=Fira+Code return no results :(

**Comment by dhouck** [comment]
Usually GitHub bugs are closed when the repository has the issue fixed, not when the fix is actually deployed.

**Comment by cfanoulis** [comment]
yes, I didn't realize that the thing had been added 

Pardon my stupidity

**Comment by m4rc1e** [comment]
Now online https://fonts.google.com/specimen/Fira+Code.
