### ISSUE TITLE
Pacifico L rendering as lowercase?

### ISSUE THREAD

**Issue by davelab6** [google/fonts#1461]
https://twitter.com/jourdanhines/status/968240411402784777 says the Pacifico cap L looks lowercase, but I couldn't reproduce this:

<img width="1054" alt="screen shot 2018-02-26 at 17 17 32" src="https://user-images.githubusercontent.com/261579/36698888-1808f986-1b19-11e8-9cc4-401a9ea049d2.png">

I changed `Lesson` to `lesson` in Chrome inspector and it looks like a lowercase to me:

<img width="1111" alt="screen shot 2018-02-26 at 17 17 17" src="https://user-images.githubusercontent.com/261579/36698889-18179c0c-1b19-11e8-9dd7-2b951e7e7eab.png">

**Comment by designsxhines** [comment]
I'm baffled... Look at the screen shots I'm posting. One HTML is lowercase and the other is uppercase. Clearly a difference but not a true capital L like @davelab6 screen shot.

Odder yet look at https://www.dafont.com/pacifico.font character map. The capital L is different than on https://fonts.google.com/specimen/Pacifico.

When I first was working on this site it showed up like a true capital L and then one day I know noticed all the L's for Pacifico looked lowercase.

**Comment by m4rc1e** [comment]
> Odder yet look at https://www.dafont.com/pacifico.font character map. The capital L is different than on https://fonts.google.com/specimen/Pacifico.

Perhaps this is an older version of Pacifico? This family was upgraded just over a year ago.

On Chrome and Safari, I can't replicate the "L" issue.

![screen shot 2018-02-27 at 09 47 22](https://user-images.githubusercontent.com/7525512/36721617-52d354f0-1ba3-11e8-9dc7-cacd0ba33c80.png)

Which browser are you using?

**Comment by davelab6** [comment]
Sadly https://www.dafont.com/pacifico.font is a very old version.

**Comment by designsxhines** [comment]
That sort of makes sense but why does it still show in Google Fonts character map as the L you have posted?

I'm using Chrome.

![screen shot 2018-02-27 at 9 56 10 am](https://user-images.githubusercontent.com/36866587/36739065-ae98d8e0-1ba4-11e8-981e-769e14044bff.png)

**Comment by davelab6** [comment]
The fonts.google.com uses some special tricks so if you have the old font
installed locally, your local copy may not be used on fonts.google.com but
will be used elsewhere

**Comment by designsxhines** [comment]
@davelab6 You rock! That resolves it:)

Thanks for the help!

**Comment by davelab6** [comment]
Glad we could help :)
