### ISSUE TITLE
Lato Bold / 700 not working

### ISSUE THREAD

**Issue by mmativ** [google/fonts#1462]
Hi guys, i found Lato bold are not working i dont know what reason but other weight are working correctly.
Check this pen for Ref: https://codepen.io/anon/pen/OQajNR

**Comment by m4rc1e** [comment]
Looks fine to me

![screen shot 2018-02-27 at 09 42 25](https://user-images.githubusercontent.com/7525512/36721407-ba7aaa00-1ba2-11e8-81b7-c39575aa67eb.png)

Have you got an old copy installed locally?

**Comment by mmativ** [comment]
hmm, i use macbook air and i try to check my local fonts don't have Lato.

**Comment by mmativ** [comment]
i found that Adobe typekit cause issue on Lato Font.
