### ISSUE TITLE
Rubik Bold and Bold Italic are reversed

### ISSUE THREAD

**Issue by mlgualtieri** [google/fonts#1463]
I'm unsure when this happened, but at some point the bold and bold italic fonts for Rubik became reversed.

When including this font family embed, weight 700 appears as bold italic:
https://fonts.googleapis.com/css?family=Rubik:300,400,700

When including this alternate embed, weight 700i appears as bold without italic:
https://fonts.googleapis.com/css?family=Rubik:300,400,700i

**Comment by mlgualtieri** [comment]
I noticed today that this issue is only happening for me in Chromium (currently running 65.0.3325.146).  In Firefox Rubik appears normal.

**Comment by laerm0** [comment]
I cannot reproduce this issue. @mlgualtieri , can you still see it?

**Comment by mlgualtieri** [comment]
Yes, I'm still seeing this issue.  In Chromium 71.0.3578.80 it appears the issue is with font weight 700.  When this size is specified I see italic text where it should be bold.  When font weight 700 is not specified, the text is bolded but not italicized.

This code demonstrates the issue for me:
```
<html>
<head>
    <link href="https://fonts.googleapis.com/css?family=Rubik:700" rel="stylesheet">
    <style>
        body {
            font-family: 'Rubik', sans-serif;
        }
    </style>
</head>
<body>
    <p>Test normal text</p>
    <p style="font-weight:bold;">Test bold text</p>
</body>                                                                                                                                                                                                  
</html>
```
In Firefox 60.4.0 loading the above HTML shows no text at all.  FYI - I'm running both Chromium and Firefox in Linux.

I'm happy to include any other detail that would help track down the issue.  The two attached files I believe are what is being served up by Google Fonts.

[chromium-rubik-css.txt](https://github.com/google/fonts/files/2829346/chromium-rubik-css.txt)
[firefox-rubik-css.txt](https://github.com/google/fonts/files/2829347/firefox-rubik-css.txt)
