### ISSUE TITLE
Add Solway

### ISSUE THREAD

**Issue by mashavp** [google/fonts#1464]
Solway is a contemporary slab-serif type family https://github.com/mashavp/Solway

**Comment by yanone** [comment]
@mashavp Your repo doesn’t show any license.
Google Fonts prefers the SIL Open Font License. If you add a reference to the license or give me a green light, I can do it and prepare to fonts for submission to Google Fonts.

**Comment by mashavp** [comment]
Dear Yanone,

Please go ahead with the prefered SIL Open Font License. Do let me know if you require anything else. Thank you very much.  

Kind Regards
Mariya

**Comment by m4rc1e** [comment]
Family is now in production, https://fonts.google.com/specimen/Solway
