### ISSUE TITLE
Google Fonts Proxy

### ISSUE THREAD

**Issue by praisedpk** [google/fonts#1466]
Is there any restriction on the use of fonts hosted at Google Fonts other than those specified in respective license of each font?

I wrote a proxy for my own projects that fetches user-agent specific CSS and font files from Google Fonts, caches at my server and serves through own CDN with some value addition. Now I want to open that project to public so that anyone can use the CDN for free (just like they use Google Fonts CDN).

I just wanted to ask if there are any legal restrictions from Google, or from Font owners that should come in the way of doing this?

Thanks.

**Comment by davelab6** [comment]
I'm a project manager at Google working on Google Fonts, so I'm writing this in my personal capacity as an employee, but this is not legal advice or an official company policy:

> Is there any restriction on the use of fonts hosted at Google Fonts other than those specified in respective license of each font?

The fonts themselves are available under libre licenses, so you can redistribute them according to the terms of those licenses.

> I just wanted to ask if there are any legal restrictions from Google

Google's Fonts APIs are made available to use under company-wide Terms of Use (https://policies.google.com/terms?hl=en%20) and Privacy Policy (https://www.google.com/intl/en/policies/privacy/) 

> or from Font owners that should come in the way of doing this?

Many fonts are subject to "Restricted Font Name" or Trademark requirements that may require renaming them.

**Comment by praisedpk** [comment]
Thanks @davelab6 for the help.

I have another question if you can help. The Google APIs are covered under the company-wide terms of use and privacy policy. Are the static font files hosted at fonts.gstatic.com sub-domain a part of the API too? It appears from some online docs that Google has kept the API and static files separate to reduce some privacy concerns and make the fonts as freely available as possible.

The readme in this repo mentions a 3rd party tool that has its own API, but that returns list of Google font files for download and self host. I think if I use that API and use the static files from fonts.gstatic.com then it can bypass the restrictions google has put on API use.

What do you say? Definitely I am asking for your personal opinion (nothing legal), as there is some confusion related to the fonts.gstatic.com

Thanks.
