### ISSUE TITLE
Sunflower 500 should be 500

### ISSUE THREAD

**Issue by rsheeter** [google/fonts#1489]
Sunflower has weight 500 as 400, put 500 in the 500 slot and leave 400 alone.

**Comment by davelab6** [comment]
(The previous policy of always having a 400 is being relaxed where the candidate isn't truly a 400; therefore for Gaegu we won't change that because while it was presented to us as a 500, we think it can be a 400 forever and its better to have a 400 than not.)

**Comment by m4rc1e** [comment]
@rsheeter @davelab6 Both Sunflower and Gugi had their stylenames converted from Med to Reg. I'll do a separate pr for each. It will only take a few mins.

Feel free to close or merge them.
