### ISSUE TITLE
Site not loading in Chrome on Arch Linux

### ISSUE THREAD

**Issue by wolfhoundjesse** [google/fonts#1499]
Thanks to [this issue](https://github.com/google/fonts/issues/1105), I checked to see if I had infinality installed, but I don't.

[My StackOverflow question](https://stackoverflow.com/questions/48646992/google-fonts-not-loading-on-their-own-site) hasn't gained traction, but it has attracted exactly one other person with this issue. 

I'm out of my own ideas, so I'm shopping here for more!

**Comment by DougTy** [comment]
I'm also getting this. No Google web fonts work **on any site** using Chrome 65 on Arch Linux. Everything works fine in Firefox.

**Comment by eric-2d** [comment]
Same problem, here are the browser's console log:

**Comment by eric-2d** [comment]
Proceeded to remove all my fonts one by one until I got to the bottom of this. Turns out the great replace all Noto font by Google itself was causing the issue. Get rid of it, problem solved..

**Comment by RickStanley** [comment]
It turns out, your fonts config (i.e. `/etc/fonts/local.conf`) has to match exactly what your DE is configured to use.
For instance, if there's a rule for sans like:
```
<match>
   <edit mode="prepend" name="family"><string>Liberation Sans Regular</string></edit>
</match>
```
Your DE **has** to be configured to use Liberation Sans **Regular**.
Well, that was my case.
Newbie mistake but it happens 😳

**Comment by wolfhoundjesse** [comment]
@eric-2d That is essentially what was going on with my configuration as well. I spent a weekend becoming familiar with font configuration on Arch, and almost all my problems were being caused by rogue matching.
