### ISSUE TITLE
Font metadata combined

### ISSUE THREAD

**Issue by strarsis** [google/fonts#151]
Is there a way to obtain the metadata of all fonts so one can query 
the font file (url/path) for a given font family name/variant?

With best regards

**Comment by davelab6** [comment]
Try the Google Fonts Developer API :)

**Comment by strarsis** [comment]
Ok, and would it be possible to get the full TTF file (uncompressed) 
- as from this repository - using the very same Google Fonts Developer API?

Thank you and
With best regards

**Comment by davelab6** [comment]
Yes it provides ttf urls

**Comment by strarsis** [comment]
Are those TTFs "optimized" or raw ones?
Because I downloaded some of them (offered by the CSS for example) 
and those were significantly smaller than the original TTF files.

**Comment by davelab6** [comment]
The TTF URLs from the developer API are not modified; the TTFs you can get
from the regular fonts API may be, depending on the user agent string that
requests the CSS>

**Comment by strarsis** [comment]
Thank you.
