### ISSUE TITLE
[IBM Plex Serif] API isn't serving Bold weight

### ISSUE THREAD

**Issue by cssobral2013** [google/fonts#1511]

**Comment by m4rc1e** [comment]
Added in https://github.com/google/fonts/pull/1488

**Comment by davelab6** [comment]
@cssobral2013 thanks! But a duplicate

**Comment by cssobral2013** [comment]
Then why the API shows 13 weights?

**Comment by cssobral2013** [comment]
Looks it'll be updated soon then.
