### ISSUE TITLE
"bold 700" Weight Missing from IBM Plex Serif

### ISSUE THREAD

**Issue by rodriguezponce** [google/fonts#1518]
The bold italic is there, but the bold is missing.

**Comment by rodriguezponce** [comment]
I still don't see it in the fonts.google.com site.

**Comment by cssobral2013** [comment]
As of day April 12, 2018 the site: https://fonts.google.com/specimen/IBM+Plex+Serif has Bold 700 weight so this issue can be closed.

**Comment by davelab6** [comment]
Thanks all
