### ISSUE TITLE
Open Sans font-weight: 13px and different weights issue

### ISSUE THREAD

**Issue by aaarichter** [google/fonts#152]
When having different font-weights next to each other (see example) and setting `font-weight: 13px` the semi-bold speciments of Open Sans are rendered smaller than the normal / light weight

```
<p style="font-size: 13px"><span style="font-weight: 300">1</span><span style="font-weight: 400">2</span><span style="font-weight: 600">3</span>45678<span style="font-weight: 600">9</span>789 </p>
```

output:
![bildschirmfoto 2015-11-16 um 17 23 00](https://cloud.githubusercontent.com/assets/2707029/11187457/bfa2fe22-8c86-11e5-86c2-d151fe5904c7.png)

This is not happening at smaller or larger font-sizes (up to 24px)

**Comment by diwakargupta1983** [comment]
I'm also facing same problem.

**Comment by m4rc1e** [comment]
@aaarichter which OS and browser?

**Comment by laerm0** [comment]
Is anyone still having this issue? I can't duplicate it in Chrome, FF, or IE in OS X and Win 10 using this [jsbin](http://jsbin.com/fepopagage/edit?html,output). (I suspect it had something to do with hinting settings and font-smoothing in browser.)

**Comment by aaarichter** [comment]
@m4rc1e sry .. I didn't see your reply. 

It was happing on OSX 10.11 with Chrome. I haven't checked out the new open sans files from PR #785 yet.

**Comment by laerm0** [comment]
If you could take a look, @aaarichter, I'd be much obliged.

**Comment by aaarichter** [comment]
@laerm0 the issue is fixed for me. Many thanks. 
<img width="109" alt="screen shot 2017-10-29 at 12 11 20 pm" src="https://user-images.githubusercontent.com/2707029/32146260-6f2fde30-bca2-11e7-8343-3f3461f28ed7.png">


Closing this issue

**Comment by davelab6** [comment]
Thanks!
