### ISSUE TITLE
Can support Noto sans fonts?

### ISSUE THREAD

**Issue by techhtml** [google/fonts#1525]
Now Noto Sans families are in Early Access.

If have no problems in Noto Sans,
I think it must support in Google Fonts.

Hows it?

Thanks.

**Comment by m4rc1e** [comment]
Noto Sans is available here https://fonts.google.com/specimen/Noto+Sans

**Comment by techhtml** [comment]
Oh, Wrong Issues.

I need Noto Sans KR in Google Fonts.

**Comment by thlinard** [comment]
Adobe provides it:
https://fonts.adobe.com/fonts/noto-sans-cjk-kr
