### ISSUE TITLE
how can I generate recovery font.png

### ISSUE THREAD

**Issue by chshxi1989** [google/fonts#153]
I want to enlarge my font size , bootable/recover/fonts/18x32.png,, many thanks.

**Comment by davelab6** [comment]
I'm sorry, I don't understand.

**Comment by chshxi1989** [comment]
Do you kown how to generate bootable/recover/fonts/18x32.png?

**Comment by davelab6** [comment]
I'm sorry, I don't know, please ask in an Android developers forum :)
