### ISSUE TITLE
Add Farro

### ISSUE THREAD

**Issue by davelab6** [google/fonts#1533]
https://github.com/grayscaleltd/farro

cc @chakler

**Comment by davelab6** [comment]
@m4rc1e this could be a good issue to pilot documenting what to do after someone submitting a new font gets to this stage :)

**Comment by chakler** [comment]
I’ve already run the fontbakery test on the fonts and tried to fix most of the problems I can, but there are still issues like `This font is missing the following required tables: [head, name, OS/2, maxp, STAT, hmtx, cmap, post, hhea]` — which is outside of my technical knowledge about fonts — where we’ll need some help with. 

Let us know if there’s anything we need to do to improve the font for inclusion; I’ll be happy to learn some new stuff.

Thanks!

**Comment by davelab6** [comment]
That looks like a FB bug. It seems highly unlikely that a font file is
missing such tables. @felipesanches ptal

**Comment by chakler** [comment]
Hi guys, just want to know if there’s any update on this. Got some time freed up to do some changes to improve Farro if anything is needed. 😄

**Comment by chakler** [comment]
Any change of this happening still? 

We’ve also launched a website for Farro a few months ago: [http://playground.grayscale.design/farro/](http://playground.grayscale.design/farro/)

**Comment by davelab6** [comment]
Yes, this  year we worked on tools to make it faster to push fonts, and
next year we will be hammering on all the addition requests :)

**Comment by chakler** [comment]
Cool! Thanks for all the work, and really looking forward to that!

**Comment by m4rc1e** [comment]
Family is now on Google Fonts, https://fonts.google.com/specimen/Farro
