### ISSUE TITLE
Add Gupter

### ISSUE THREAD

**Issue by davelab6** [google/fonts#1534]
https://github.com/octaviopardo/GUPTER

**Comment by yanone** [comment]
@octaviopardo Your repo doesn’t show a license reference.
Google Fonts prefers the SIL Open Font License.
If you add a license to the repo or give me the green light to do it, I can prepare the fonts for submission to Google Fonts.
Also: It looks like your UFOs were exported from Glyphs. In fact GF prefers Glyphs source files. Would you consider adding them?

**Comment by octaviopardo** [comment]
Hi! I am working on it, I will go quite slow this days because I am in a trip but I am planning to have this ready this week, oki??

Thanks!

Octavio Pardo Virto
Graphic Designer /Type Designer
C/ Berriozar 21,
Oficina 35, 2º piso
31013 Pamplona SPAIN
+34 657 106 116
www.octaviopardo.com

**Comment by octaviopardo** [comment]
Hi Yanone!
I reviewed the files already, and added missing stuff, in case you want to take a look. Let me know if there is anything wrong there

Octavio Pardo Virto | Graphic & Type designer
Berriozar 21, Oficina 35, 2º piso 31013 Pamplona SPAIN
Rebslagervej 19, 2400 København DENMARK
T: +34 657106116 | www.ashler.design | www.octaviopardo.com

**Comment by davelab6** [comment]
Oh this was shipped @ https://fonts.google.com/specimen/Gupter

**Comment by kenmcd** [comment]
No SemiBold (600) ?
