### ISSUE TITLE
Open Sans Condensed font family not consistent

### ISSUE THREAD

**Issue by gerritgoetzen** [google/fonts#154]
At least in OS X the font family is _Open Sans_ (notice missing _Condensed_) for _Light_ and _Light Italic_ but _Open Sans Condensed_ for the _bold_ style.

**Comment by m4rc1e** [comment]
Could you clarify this please?

I'm not sure I understand the problem.

**Comment by davelab6** [comment]
I think the name table needs a close look

**Comment by laerm0** [comment]
This is fixed so I am closing.
