### ISSUE TITLE
Roboto Mono: 0 not wide enough in Chrome but fine in Firefox

### ISSUE THREAD

**Issue by SharkWipf** [google/fonts#1540]
For some reason, it seems like the 0 in Roboto Mono is less wide than other characters in Chrome.  
I've had people test it in Firefox and they report it looks fine.  
(Most) other monospaced fonts look fine.

![image](https://user-images.githubusercontent.com/751205/38960014-1cd61080-4363-11e8-9f2d-5e6f5af01d99.png)

Tested with:
Google Chrome 65.0.3325.181 on Gentoo;
Firefox 59.0.2, also on Gentoo.

**Comment by laerm0** [comment]
Hi @SharkWipf. I can't reproduce this anymore. Do you still see it?

**Comment by sladen** [comment]
Since the titles are in Ubuntu Mono, and the first line of zeros looks near-identical to the Ubuntu Mono line of zeros, it could be that the HTML is broken/being mis-parsed, and an explicit font-name is not being set until the second line.

**Comment by sladen** [comment]
@SharkWipf what happens if *the order* of the previewed fonts is changed?

**Comment by SharkWipf** [comment]
It seems to be fixed for me now too:  


![image](https://user-images.githubusercontent.com/751205/51855281-2606ef80-232d-11e9-8f2a-7c7ac24cdc2a.png)

@sladen I actually found out about this issue because I was facing it on a different site, so it was not limited to the preview page.
