### ISSUE TITLE
Improper handling of invalid subset

### ISSUE THREAD

**Issue by AliceWonderMiscreations** [google/fonts#1546]
When one of the subset queries doesn't match what fonts.googleapis.com knows about, the server sends a 404.

Example:

https://fonts.googleapis.com/css?family=Libre+Franklin:200,200i|Karla:400&subset=latin,latin-ext,hebreu,tamil

I mispelled hebrew intentionally to demonstrate. It gives a 404 - even from browsers (FireFox and Chromium) where the subset is ignored because unicode ranges are supported.

The preferred behavior should be to ignore the invalid subset, for two reasons:

A) Webfonts for the valid subsets will still be usable by the browser. So instead of just not providing fonts for the mis-spelled subset, it means you aren't providing fonts for any of the subsets.

B) It means when people like me write classes to generate a google fonts query, we have to check each requested subset to make sure it is valid so that we can manually make sure at least something loads rather than a 404. That means that if you add valid subsets, web applications that use our classes to generate the get parameters can't make use of them until we update the class to recognize the new subset as a valid argument.

Please fix this, serving a 404 page is the wrong thing to do.

**Comment by AliceWonderMiscreations** [comment]
Sorry, it gives a 400 not a 404.

Still wrong thing to do.

**Comment by davelab6** [comment]
We believe this should happen because we want people to know when their queries are not returning what they expect. 

While the API is more forgiving in other aspects (such as if no weight is specified then you get a 400r :) we don't have plans to change this, despite your observations and reasonable position that this could be desirable.

**Comment by AliceWonderMiscreations** [comment]
LOL - I was going to file another ticket suggesting 400,400i,700,700i be assumed when no weight is given as the browser will only download the fonts it actually needs to render the page.

Guess I won't.

Thank you for your time.

**Comment by davelab6** [comment]
In the past, that browser behavior wasn't always true; and in the very near future, variable fonts will make weight specification in the API moot - just as unicode-range makes subset specification moot.

Which is really how your original issue is being solved; as we add new sunsets to fonts, users on newer browsers get them automatically.
