### ISSUE TITLE
Wrong weights for Fira Sans and Playfair Display

### ISSUE THREAD

**Issue by rosenvinge** [google/fonts#155]
I am writing to call to your attention that two otherwise commendable fonts are, as they appear to me, incorrectly shown and served by Google Fonts.

One, Playfair Display Normal 400 is the same weight as shown and served for Bold 700. By contrast, the corresponding Italics are in the correct weights.

Two, Fira Sans Normal 400 is shown and served in a version lighter than the proper Normal and is lighter even than Google’s showing of Fira Sans Light 300. Again, the Italics are shown and served in the correct sequence of weights. Fira, of course, is available elsewhere in an astonishing 16 weights, so perhaps it’s not surprising that an incorrect weight (perhaps ExtraLight?) got uploaded as Fira Sans Normal 400.

Thanks!

Chris von Rosenvinge
chris@vingdesign.com

**Comment by davelab6** [comment]
Thanks @rosenvinge :) As a workaround, uninstall the fonts. 

I see this also reported at https://twitter.com/hybrid_alex/status/726582427297021953

**Comment by Mte90** [comment]
I remember many comments here and I think that they are important to understand how is olda nd serious this issue.

**Comment by laerm0** [comment]
This issue is solved so I am closing.
