### ISSUE TITLE
Documentation: How to automate font installation after git pull

### ISSUE THREAD

**Issue by SKelem** [google/fonts#1551]
If I download all the google fonts via github, how do I (a) install all of them at once, and (b) have them updated and re-installed automatically via git? That's the whole point of automation, right?
Who would want to go into 100 different directories and right click on each one, one at a time?
The point of Git is that it will update whatever files have been updated at Google without you having to search for updates manually, but then you want them updated and "installed" on your computer automatically too.

How do you do that?

**Comment by alexeyten** [comment]
What is your OS?

**Comment by SKelem** [comment]
Windows 10

**Comment by m4rc1e** [comment]
I'd advise against having 1000+ fonts installed on your system. I've found in the past that having many fonts installed has slowed some apps (Adobe) to a crawl.

I'd recommend using a font Manager like https://fontba.se instead.

**Comment by davelab6** [comment]
@SKelem fair question; as Marc said, typically you would use a font manager to do this. However, you could write your own Windows PowerShell or Batch file script to do it (eg https://superuser.com/questions/201896/how-do-i-install-a-font-from-the-windows-command-prompt)

(If you are a developer, you might like to contribute to the www.type.world project which aims to solve this overall problem of font distribution and installation management :)
