### ISSUE TITLE
Google font CSS urls that end with a trailing pipe have started 404ing

### ISSUE THREAD

**Issue by acusti** [google/fonts#1554]
Google font CSS urls that end with a trailing pipe, which as of last night worked the same as those without the trailing pipe, have started 404ing. We have a ton of sites (and web builder) that are no longer getting fonts as a result. An example stylesheet url that now breaks: `https://fonts.googleapis.com/css?family=Crimson+Text:400,400italic|`

We can update our web builder app to remove the trailing pipe, of course, but we cannot do the same for all the live, published websites that are out in the wild. Is it possible to restore the previous behavior?

(Wasn’t sure the best way to urgently get in touch, so I also tweeted @googlefonts about it: https://twitter.com/andpatton/status/992386591556423681)

**Comment by sladen** [comment]
@rsheeter or @davelab6, is there a very recent commit that changed in the processing of arguments:

Selection of inputs to help narrow it done:

* https://fonts.googleapis.com/css?family=Crimson+Text:400,400italic|& (does not work)
* https://fonts.googleapis.com/css?family=Crimson+Text:400,400italic& (works)
* https://fonts.googleapis.com/css?family=Crimson+Text:400,400italic| (does not work)
* https://fonts.googleapis.com/css?family=Crimson+Text:400,400italic|? (works)
* https://fonts.googleapis.com/css?family=Crimson+Text:400,400italic,| (does not work)
* https://fonts.googleapis.com/css?family=Crimson+Text:400,400italic,|? (works)

So it is indeed final pipe ('|') directly at the end.  Is it a case of eg. `split('|')` returning a list with an empty string `['foobar','']` and these being further validated against being empty?

**Comment by davelab6** [comment]
@acusti that is unfortunate; I think in the documentation the pipe is used to separate families, and a trailing pipe was not documented as supported. However, I'll discuss this with the GF engineering team :)

**Comment by acusti** [comment]
@davelab6 Thanks very much for doing so! And thank you, @sladen, for the triage.

**Comment by sladen** [comment]
Another URL for the mix, where deleting any of the full stops ('.') is cause a null-string breaks:
* https://fonts.googleapis.com/css?family=.|.|.|.|Ubuntu:400|.|. (works)

**Comment by rsheeter** [comment]
Thank you for the sample urls

**Comment by rsheeter** [comment]
Confirmed as bug, will rollback latest release

**Comment by garretrieger** [comment]
The rollback is finished. URL's with trailing |'s should now work again.

**Comment by rsheeter** [comment]
Apologies for the inconvenience.

**Comment by acusti** [comment]
@rsheeter Thanks for the quick response, it’s much appreciated by us and by our customers.
