### ISSUE TITLE
RASA font missing i's and j's in MS PDF output

### ISSUE THREAD

**Issue by JerryKnoch** [google/fonts#1555]
We have found that when creating a .PDF document with the Microsoft engine and the RASA font, all occurrences of lower case 'i's and 'j's are missing/blank. I have tons of technical information and details having worked with Microsoft over last 3 months on this and their engineers have indicated the issue is with the RASA font:

"_**The font developer responsible for maintaining our font engine code conveyed the answer is in the implementation details. Specifically, software doesn’t have to rely on the MAXP table in the font, but if it does not, it has to do additional bookkeeping work such as reallocating memory when it detects more components than some initial values. But in case of our font DLL, fontsub.dll, which is used by MXDW (print-to-pdf driver), it doesn’t do these bookkeep operations and solely relies on the numbers in MAXP to be right. It is possible other software such as the Adobe’s apps are doing the extra bookkeeping.

I researched the MSDN documentation in relation to the Rasa font and found the spec which supports the Developer’s explanation. The MSDN article located here https://docs.microsoft.com/en-us/typography/opentype/spec/maxp  says this....

“_This table establishes the memory requirements for this font. Fonts with CFF data must use Version 0.5 of this table, specifying only the numGlyphs field. Fonts with TrueType outlines must use Version 1.0 of this table, where all data is required**_.”

The Rasa font uses the TrueType Outline……
So all elements of this table (1.0) must be used….including the maxComponentElements. The developer says it is set to 0."

[Notepad_test(MS Print to PDF).pdf](https://github.com/google/fonts/files/1975552/Notepad_test.MS.Print.to.PDF.pdf)
[MS Support Incident Details.zip](https://github.com/google/fonts/files/1975554/MS.Support.Incident.Details.zip)

**Comment by laerm0** [comment]
Looks like a quick recalc of MAXP will fix this.

**Comment by laerm0** [comment]
Yep, recalc MAXP fixed it. Thanks @JerryKnoch . 
[test.pdf](https://github.com/google/fonts/files/2833695/test.pdf)

**Comment by bozi23** [comment]
Hi there,
experiencing the same issue with rasa PDF conversion. This issue is a little deeper under the hood than my technical understanding of font handling within Microsoft goes Can anyone give me a hint on how to recalculate MAXP respectively changing it to 1.0?

I'd be very thankful for any clues.

Kind Regards,
Boris

**Comment by thlinard** [comment]
Hi,

In the [current version of the fonts](https://github.com/rosettatype/yrsa-rasa) (version 1.002), [the `maxComponentElements` is set to 4](https://github.com/rosettatype/yrsa-rasa/blob/master/fonts/ttf/Rasa-Regular._m_a_x_p.ttx). Perhaps you should test the current version, and Google should update its version to the current one (@laerm0)?

**Comment by bozi23** [comment]
Thank you so much @thlinard !!

Version 1.002 solves the issue for me \o/

Kind regards
Boris

**Comment by kontur** [comment]
This issue could probably be closed :)
