### ISSUE TITLE
Use Google Fonts Developer API as guest/public user?

### ISSUE THREAD

**Issue by strarsis** [google/fonts#156]
Let's say I want to pull the full TTF from Google Fonts using the Google Fonts Developer API - 
can I do this without using a special API key? Being a guest/public user?

Thank you and
With best regards

**Comment by davelab6** [comment]
No. It's offered as part of the Google Cloud API so you need an api key. Is
there any reason you would be unable to generate a key?

**Comment by strarsis** [comment]
Thank you for your answer.

One instance where a API key would be unwiedly would be a gulp plugin for example 
that just downloads the full TTF file for further custom processing.

With best regards

**Comment by davelab6** [comment]
In this case I would recommend caching the API on your own server and pointing your gulp plugin to your own copy :)
