### ISSUE TITLE
OpenSans: Case mapping for German Sharp S

### ISSUE THREAD

**Issue by spixi** [google/fonts#1560]
ß is not correctly mapped to its counterpart ẞ, but it should do since the new spelling rules from 2017. Instead of this, it is still mapped to SS.

This can be observed with the Capital special in LibreOffice:

![libreoffice](https://user-images.githubusercontent.com/3192596/39750963-f7641eb0-52b6-11e8-8f0b-8e51d7cbdf19.png)

or in Firefox and possible other browsers, for example [here](https://extern.linieplus.de/proposal/fussgaengerueberfuehrung-koeln-airport-businesspark/) (Look at the words „außerhalb“ and „Fußgängerüberführung“).

**Comment by Thielo** [comment]
Using ẞ is still optional. It's still allowed to use "ß" or "SS" in the Uppercase Version of "ß"

> Sie schaffen mit der Zulassung des Großbuchstabens „ẞ“ eine Wahlmöglichkeit,
neben der die Schreibung mit „SS“ für „ß“ bei der Schreibung in Groß-
buchstaben erhalten bleibt

[http://www.rechtschreibrat.com/DOX/rfdr_PM_2017-06-29_Aktualisierung_Regelwerk.pdf](http://www.rechtschreibrat.com/DOX/rfdr_PM_2017-06-29_Aktualisierung_Regelwerk.pdf)

**Comment by davelab6** [comment]
@laerm0 ptal

**Comment by laerm0** [comment]
Ah, well, that's because Open Sans doesn't have a cap eszett. I'll add one. 👍

**Comment by laerm0** [comment]
Okay, it's in there now.

![screen region 2018-05-09 at 14 29 20](https://user-images.githubusercontent.com/10780161/39832513-62a8629c-5395-11e8-8cb2-ff1fa97da617.png)

𝖜𝖔𝖔
