### ISSUE TITLE
Add Objective

### ISSUE THREAD

**Issue by davelab6** [google/fonts#1575]
https://www.behance.net/gallery/60530395/Objective-Free-Font-Family

It is available under OFL

**Comment by m4rc1e** [comment]
https://daltonmaag.com/library/objektiv

**Comment by davelab6** [comment]
I will ask DaMa about it

**Comment by dm-dama** [comment]
Yes, we'd say the name is too similar to, and too confusable with, our "Objektiv" font family.

We'll contact the designer and try to resolve.

**Comment by dm-dama** [comment]
The designer agrees that it's potentially confusing and has offered to change the name to "Objectivity".

Given our domain claim, and the extra two syllables, we think this is far enough away to not be confusing.

So, expect a rename, and you have our confirmation that the new name isn't an issue for us.

**Comment by davelab6** [comment]
Thanks!!

**Comment by emmamarichal** [comment]
@chrissimpkins @davelab6 I contacted the designer, here is his answer:

> Hi Emma! Thanks for reaching out, but I’m afraid I have to decline it, since Objectivity is basically a previous lower-quality version of Object Sans, which is sold via Pangram Pangram 🙂

So I close this issue :)

**Comment by davelab6** [comment]
Since it's widely available elsewhere and users want to use it, I am still keen to onboard it.

**Comment by slobzheninov** [comment]
Hi @davelab6!
There’s a few reasons why I stopped distributing it myself and would prefer others to not do so either:
1. Its quality is rather low and I don’t want to spread bad typography. Various freebies websites indeed still keep it available, but the expectations and responsibility there are totally different from Google fonts.
2. There are no source files;
3. If you go through improving it from the OTFs, you’ll end up close to Object Sans, which is already a commercial family.
