### ISSUE TITLE
Google Fonts Manager or Script?

### ISSUE THREAD

**Issue by narrejin** [google/fonts#1578]
Hi! I'm not sure if this is the right place to mention this. I'm not a developer but a designer and I use Google Fonts a lot. So I'm wondering... any chance to create an exclusive Google Fonts Manager that not only could synchronize with this repository in order to have all Google Fonts syncs on your machine, but also with certain capabilities as:

- Activating fonts (in permanent or temporary mode)
- Ordering by libraries (Serif, Sans Serif, Handwriting, etc.)

I think it would be great to have something like that.

**The issue that I found is next:**

Downloading and manually installing google fonts via any font manager has not the property of sync with NEW Google Fonts, that –if we want to have all Google Fonts downloaded and updated– we need to check, download and installing manually again. So an EXCLUSIVE Google Fonts Manager could be, probably, a great solution.

Or… a script that allows to external Fonts Manager to get Google Fonts synchronized.

**Comment by davelab6** [comment]
Www.Type.world is the nearest you'll get I think

**Comment by m4rc1e** [comment]
https://skyfonts.com apparently serves Google Fonts
