### ISSUE TITLE
Ligature size problem in Droid Serif font

### ISSUE THREAD

**Issue by shiva-108** [google/fonts#1585]
Hi !
There's a ligature size problem with the Droid Serif font in French. We use the ligature «œ» for «o» and «e» together. But in Droid Serif, that ligature is in a too small size compared with the other characters, which is typographically not acceptable.

If the body text is in 14px, then we have to enlarge the ligature to 22px for it to have the same size than the other characters: `(<p><em>Destination coup de c<span style="font-size: 22px;">œ</span>ur de la rédaction, le Japon [...]</em></p>)`

Can you fix it to set the same size to this ligature than the other characters ?

Thanks ibn advance.

Yan
Switzerland
<img width="610" alt="capture d ecran 2018-05-31 a 10 06 15 copie" src="https://user-images.githubusercontent.com/34059947/40771613-1ac707e6-64be-11e8-8d8b-75f20b4bd52b.png">
<img width="610" alt="capture d ecran 2018-05-31 a 10 06 15" src="https://user-images.githubusercontent.com/34059947/40771614-1ae29434-64be-11e8-8809-686d434bc3da.png">

**Comment by laerm0** [comment]
Hi @shiva-108. Droid is not available from Google fonts, so I'm afraid this question is beyond our purview.
