### ISSUE TITLE
Site won't load

### ISSUE THREAD

**Issue by DieLaughing** [google/fonts#1588]
The Google Fonts website chokes and dies if I try and view it using a browser on Linux. Why? Do you not like my DNS being 1.1.1.1 or that I'm blocking your tracking garbage with a pi.hole? I've sent different spoofed headers to no avail. So... what's the deal with hating on Linux?

**Comment by davelab6** [comment]
I can't reproduce this. Which gnu distribution are you using? DNS settings shouldn't matter, but some privacy guarding browser extensions turn on web fonts so try it with no extensions activated and then incrementally enable one at a time and retest.

**Comment by DieLaughing** [comment]
This was a mistake on my end. Apologies.
