### ISSUE TITLE
Roboto : Problem with Quotation Marks

### ISSUE THREAD

**Issue by GothTheFunk** [google/fonts#159]
Hi Guys,

It seems that there is a problem with the Roboto Font!

The open quotation and close quotation are not of the same font :(

Where can we submit the change?

Best,

Gauthier

**Comment by davelab6** [comment]
Could you provide a screenshot, or better, a link to an example of this? 

You can file issues with Roboto's developers in https://github.com/google/roboto/issues but if its a webfont issue, here is good :)

**Comment by rpluvina** [comment]
<img width="755" alt="capture d ecran 2015-12-03 a 19 31 04" src="https://cloud.githubusercontent.com/assets/13452339/11655354/50550cc6-9dad-11e5-9d51-1dd0b0ad0dfd.png">

**Comment by rpluvina** [comment]
The right guillement is missing «  » but only in the weight 300. I don't think it's a webont issue, so I will post it in the right github.

**Comment by codeman38** [comment]
Yeah, that's definitely not the current version of the font - the design of the "R" and "k" are different now.

**Comment by davelab6** [comment]
You likely have an older version installed on your computer; Google Fonts
CSS uses local fonts in preference to web fonts for improved latency, at
the risk of users having old versions installed.

**Comment by rpluvina** [comment]
yes, effectively I just downloaded the last one on my laptop, and all French quotation marks are back there. thanks !

**Comment by davelab6** [comment]
welcome!

**Comment by fitojb** [comment]
It’s always good to check whether you have the latest version of any software (including fonts of course) to see if your problem is already solved before filing bugs…
