### ISSUE TITLE
Add New Material Design Icon Themes

### ISSUE THREAD

**Issue by TangSteven** [google/fonts#1592]
I created [an issue](https://github.com/google/material-design-icons/issues/773) about this in the material design icon repository, however that repository appears to be inactive. Hopefully the Google Fonts team can help us out and add the new material design icon themes (outlined, rounded, two tone, and sharp) to Google Fonts. The issue above contains a few suggestions for implementation from developers using the web font. Thanks!

**Comment by TangSteven** [comment]
If this is the case then I believe that [this documentation](http://google.github.io/material-design-icons/#icon-font-for-the-web) should be updated, it currently recommends the icon font over SVG.

**Comment by laerm0** [comment]
Closing as this issue is outside of the purview of the Google Fonts project.

**Comment by thlinard** [comment]
@laerm0 : I haven't seen it before, but https://fonts.googleapis.com/icon?family=Material+Icons is a valid url. So, I guess Material Design Icons is part of the Google Fonts project, right?
