### ISSUE TITLE
markazitext metadata refer to non-existing files

### ISSUE THREAD

**Issue by benfonty** [google/fonts#1595]
Hello,

The Metadata.pb file for the ofl/markazitext font family refer to non-existing files.

**Comment by davelab6** [comment]
It is a variable font; the STAT table provides them.

**Comment by davelab6** [comment]
Oh I see. Thanks!

**Comment by davelab6** [comment]
Fixed in https://github.com/google/fonts/commit/69d58573f308696283c2b2377bb71e3806c1a632

**Comment by m4rc1e** [comment]
Thank you @benfonty. @davelab6 we'll solve this in https://github.com/googlefonts/tools/issues/49
