### ISSUE TITLE
Enriqueta Bold has overlap on glyph x

### ISSUE THREAD

**Issue by adrientetar** [google/fonts#16]
![enr](https://cloud.githubusercontent.com/assets/1250894/7206352/d394a10e-e530-11e4-87ae-b6a2cd186a6a.png)

**Comment by adrientetar** [comment]
@davelab6 I suspect FontForge didn't remove the overlaps here because path direction wasn't homogenous (same thing I experienced with Crimson). Also you can't do correct direction on a whole glyph that's heterogenous, you have to select a single path in the glyph.
So I'm thinking maybe fontbakery so do a normalization pass using contour.isClockwise() before removing overlaps.

**Comment by m4rc1e** [comment]
Hey,

I've fixed the issue and rebuilt the [repo](https://github.com/m4rc1e/enriqueta).

![screen shot 2016-09-05 at 16 25 27](https://cloud.githubusercontent.com/assets/7525512/18250791/8cb0d57a-7385-11e6-8812-ca55d35e9cd3.png)


However, a far bigger concern is the Bold weight is missing € symbol and other glyphs which are 
present in the Regular.

**Comment by davelab6** [comment]
@m4rc1e could you confirm the glyphs missing from each style that are in the other? :)

**Comment by m4rc1e** [comment]
scircumflex
uni000D
uni1E3F
uni1E3E
wdieresis
uni0000
Wdieresis
Euro

**Comment by davelab6** [comment]
Ah good, not many. I will email the foundry now about this

**Comment by m4rc1e** [comment]
Closing, LGTM.

![screen shot 2017-06-15 at 12 21 57](https://user-images.githubusercontent.com/7525512/27179157-4198c7ea-51c5-11e7-8755-7274f1e0494d.png)

http://jsbin.com/burawesaxa/edit?html,output
