### ISSUE TITLE
Issue with italic characters of Roboto Mono

### ISSUE THREAD

**Issue by erusev** [google/fonts#160]
The italic characters of Roboto Mono seem to be narrower than the regular and bold characters. Texts "shrink" when converted from regular to italic.

Here's a screenshot that should demonstrate the issue: 
![image](https://cloud.githubusercontent.com/assets/184170/11656350/33fc1fc8-9dbd-11e5-85ef-b63fac61d956.png)

**Comment by davelab6** [comment]
This is a known issue. Thanks for reporting. I hope it will be addressed in a future update.

**Comment by erusev** [comment]
Thanks, @davelab6, I look forward to it.

**Comment by davelab6** [comment]
Closing as duplicate of https://github.com/google/fonts/issues/142
