### ISSUE TITLE
ARABIC LETTER DOTLESS FEH incorrectly aligned in Harmattan and Scheherazade

### ISSUE THREAD

**Issue by bzaar** [google/fonts#1603]
Unicode Character 'ARABIC LETTER DOTLESS FEH' (U+06A1) is floating above the base line disconnected from the surrounding characters:

![image](https://user-images.githubusercontent.com/4028922/41944494-f5fadc3e-799f-11e8-975b-97afef0301ed.png)

This happens in Harmattan, Scheherazade and other Arabic fonts.

Can this be fixed please? Many thanks in advance!

**Comment by khaledhosny** [comment]
It looks like the dotless feh is taken from a fallback font, so it might be a case of font subset not having the character.

**Comment by bzaar** [comment]
Could it be added then? Just copy all glyphs from the normal feh with the dot removed. :)

BTW, 'ARABIC LETTER NOON GHUNNA' (U+06BA) is displayed correctly without a dot in these fonts which is why I chose to use them.

**Comment by khaledhosny** [comment]
The fonts most likely have the glyph, but the subset that Google Fonts serve to browsers don’t include it.

**Comment by khaledhosny** [comment]
@davelab6 should know.

**Comment by bzaar** [comment]
Are you talking about the [unicode-range CSS descriptor](https://developer.mozilla.org/en-US/docs/Web/CSS/@font-face/unicode-range)? It includes U+0-10FFFF by default.

**Comment by bzaar** [comment]
@davelab6 Hi Dave, any ideas why this letter is displayed incorrectly?
