### ISSUE TITLE
Add Dhivehi Akuru

### ISSUE THREAD

**Issue by davelab6** [google/fonts#1610]
https://github.com/rafyqpro/Dhivehi-Akuru

This needs licensing clarification, source files, and verification of Unicode/OpenType aspects

**Comment by rafyqpro** [comment]
how i have uploaded all the materials

**Comment by davelab6** [comment]
Excellent! The updates to your repo are good! 

The Fonts API would need to be updated to support this script, and when that is happening then we can do a detailed review of the font and make a pull request with any minor changes. 

I'm sorry I can't offer you a specific schedule for that work.

**Comment by davelab6** [comment]
A Github API key is not needed; there is nothing more that you can do. We have this issue, within the ["add new families"](https://github.com/google/fonts/milestone/2) milestone, and we will (slowly) go through all the issues in that milestone and add them. 

I'm sorry I can't offer you a specific schedule for that, but I expect it will be slower than you would like. Thanks for your patience :)

**Comment by rafyqpro** [comment]
Thank you for your kind help, i really appreciate it.

**Comment by rafyqpro** [comment]
Sir, any goog news for me

**Comment by rafyqpro** [comment]
Hi, what's the updates of my font. Any good news.

**Comment by rafyqpro** [comment]
Any update on this font

**Comment by emwadde** [comment]
Hello @davelab6 ,
Is there any update on when this font will be available in Google Fonts Directory?. It is in great need during this pandemic lockdown. Our local subject teachers are eagerly waiting for this font to become available.
Thanks

**Comment by waheed-isk** [comment]
Hello @davelab6 , any expected time for this. It's in great need at this time

**Comment by Ibbe2011** [comment]
@davelab6 Any good new?? Since i am a graphics designer i really need it.

**Comment by davelab6** [comment]
This would probably be worth prioritizing as its a minority script, but the family name is the name of the script, and the upstream has deleted their github account. So I'll close this and move it to the icebox.
