### ISSUE TITLE
shrink file size using pyftsubset

### ISSUE THREAD

**Issue by bardware** [google/fonts#1619]
Hi,

I recently took notice of a tool [glyphhanger](https://github.com/filamentgroup/glyphhanger). When invoked in a certan way it compresses `.ttf` files. The tool internally uses pyftsubset from [fonttools](https://github.com/fonttools/fonttools); I understand some of you know this tool.
I call `glyphhanger --subset=*.ttf` in a folder with the `OpenSans*.ttf` files you provide. The files are reduced in size from 220 kB to 90 kB. I wonder how this tool does this. I understand it deletes unused glyphs when I provide a whitelist of glyphs to keep. I do not do this. I simply call it and the filesize is reduced. 
Do you have an idea how this tool does this? Why do you not use this tool?

**Comment by m4rc1e** [comment]
Thanks for the post.

We already use pyftsubset to subset a family to specific char ranges

![screen shot 2018-07-19 at 13 34 41](https://user-images.githubusercontent.com/7525512/42942665-8bd66308-8b58-11e8-8eff-05e2e1808a99.png)
