### ISSUE TITLE
IE 10/11 font's not working

### ISSUE THREAD

**Issue by lameco040** [google/fonts#1620]
I'm not sure if anything has changed in the past couple of days.

Loading any Google Font using the `<link>` or `@import` is working in Chrome, Firefox and Safari. But when I'm looking at the same website on IE 10/11 it falls back to Times New Roman.

Looking at the network traffic it shows the font's are in fact loaded. But when trying to open and download the font using the URL in the network traffic it downloads the WOFF without an extension and just adds `_woff` at the end of the file name.

Now I used a FontSquirrel download of **Open Sans** and this works. So I think it has something to do with how Google serves the font's.

Anyone else experiencing the same issue?

**Test:** https://codepen.io/wellmade/pen/yqamWy
**Tested on:** `Windows 7 - IE 11`

**Comment by m4rc1e** [comment]
Thanks for the codepen!

I can't replicate this using Browserstack with Win10, IE11.


![screen shot 2018-07-19 at 13 37 13](https://user-images.githubusercontent.com/7525512/42942852-19055e0a-8b59-11e8-8ea8-f5b786708337.png)

**Comment by m4rc1e** [comment]
Thanks for the codepen

It works for me on Win 7 IE11 via Browserstack

![screen shot 2018-07-19 at 13 44 04](https://user-images.githubusercontent.com/7525512/42943137-e16bd054-8b59-11e8-8a49-825282e2ebf8.png)

Still fine on Win 7 IE10
![screen shot 2018-07-19 at 13 45 26](https://user-images.githubusercontent.com/7525512/42943202-02fc5310-8b5a-11e8-883f-ae997ece8c95.png)

**Comment by lameco040** [comment]
Thanks. That is weird.
Could it be something changed in the settings of IE that would block loading custom fonts?
I'm going to do some more searching around.

**Comment by m4rc1e** [comment]
Try clearing your font cache or check if you have it installed locally?

**Comment by lameco040** [comment]
Apparently the PC needed a reboot and that did the trick.
Sorry for ringing the alarm bell.
