### ISSUE TITLE
Karla 400 regular loading as italic

### ISSUE THREAD

**Issue by joshuaiz** [google/fonts#1624]
Hello,

We are loading Karla 400 regular here: https://www.jockey.co.uk but the italic font is loading. 

I've tried this on a new blank site locally with the following in header.php:

`<head><link href="https://fonts.googleapis.com/css?family=Karla" rel="stylesheet"></head>`

CSS:

`body {
    font-family: 'Karla';
}
`

The regular Karla font is loading as italic. This is repeatable. The italic version is *not* being loaded anywhere on either site. Can you please fix this?

Thanks.

**Comment by fitojb** [comment]
Is this reproducible in other computers? Do you have the font installed locally (that’s known to cause conflicts with browsers)?

**Comment by joshuaiz** [comment]
You nailed it - I had Karla Italic installed locally. Removed and all is good. Thanks!!
