### ISSUE TITLE
OFL.txt line endings Win or Unix?

### ISSUE THREAD

**Issue by m4rc1e** [google/fonts#1630]
The [original OFL.txt](https://scripts.sil.org/cms/scripts/page.php?site_id=nrsi&id=Ofl) uses Windows line endings, whilst the OFL.txts in this repo use unix line endings. Is there a reason why we changed them?

Related to https://github.com/googlefonts/gf-glyphs-scripts/issues/29

**Comment by laerm0** [comment]
Hey all, if `\n` is good, then can I close this?
