### ISSUE TITLE
Why didn't you chose true ligatures for Open Sans typeface?

### ISSUE THREAD

**Issue by cssobral2013** [google/fonts#1632]

**Comment by laerm0** [comment]
Well, I guess I am curious what @cssobral2013 means by "true ligatures"... Do you mean an `fi` ligature with the tittle conjoined to the f's upper contour? That is not on my list of to-dos because the original design doesn't have it that way.

**Comment by cssobral2013** [comment]
I'll close this issue as this's not necessary to ask.

**Comment by davelab6** [comment]
Sure; Micah was working on a new release

**Comment by davelab6** [comment]
So there is an opportunity to fix stuff in OS if it's broken
