### ISSUE TITLE
Lato SemiBold isn't an option on fonts.google.com - but appears in this repo.

### ISSUE THREAD

**Issue by renodubois** [google/fonts#1638]
Hello & apologies in advance if this is the wrong place to post this.

I've noticed that on the Google Fonts website, the page for [Lato](https://fonts.google.com/specimen/Lato) doesn't include a SemiBold option, but when inspecting the repository here, it appears that there is a SemiBold and SemiBold italic option. Is there a reason for this discrepancy? It would be very useful to have the SemiBold option available via the Fonts API to pull like the other font options.

**Comment by m4rc1e** [comment]
We have the mega thread here #6.

Basically we tried to release v2 but it had too many regressions. We had to roll it back. Font authors have also been busy with personal life and other projects so we haven't solved these regressions yet.

**Comment by renodubois** [comment]
Aha, that will do it. Thanks for the quick response!
