### ISSUE TITLE
Add Agane

### ISSUE THREAD

**Issue by dema89** [google/fonts#1639]
This is a font that I designed in 2017. It is in free download. I would like to contribute to Google Fonts. Below there are some links where you can view it.

http://www.danilodemarco.com/agane/
https://www.fontsquirrel.com/fonts/agane

**Comment by laerm0** [comment]
Hi @dema89 . I am happy to hear you want to contribute. 😃 We have a process for submitting fonts. [This document](https://github.com/google/fonts/blob/master/CONTRIBUTING.md) helps explain how. Let us know if you have any questions.

**Comment by davelab6** [comment]
Aha, it was also discussed in #1936 where the upstream designer made it OFL (thanks to @felipesanches explaining that requirement) and its upstream at https://github.com/dema89/aganefont under OFL so we can do it :)

**Comment by dema89** [comment]
Hi @davelab6 thanks for all. I have been waiting for a long time for an answer (2 years). What are the next steps for font approval on Google Font? Thank you.
