### ISSUE TITLE
.woff files are returning 404s

### ISSUE THREAD

**Issue by ajyong** [google/fonts#1642]
I'm currently using Firefox Developer Edition 62.0b16 and noticed that the following URL returns a `.css` file that instructs the browser to download `.woff` files:

https://fonts.googleapis.com/css?family=Roboto:300,400,500,700|Material+Icons

Here's a snippet from the resulting `.css` file:

```
/* fallback */
@font-face {
  font-family: 'Material Icons';
  font-style: normal;
  font-weight: 400;
  src: url(https://fonts.gstatic.com/s/materialicons/v40/flUhRq6tzZclQEJ-Vdg-IuiaDsNaIhI8tYnh.woff) format('woff');
}
```

It just started happening a couple hours ago that any and all `.woff` files requested return a 404.  I tried the same request in Chrome 68 and noticed that Chrome is instructed to download `.woff2` files instead.  

```
/* fallback */
@font-face {
  font-family: 'Material Icons';
  font-style: normal;
  font-weight: 400;
  src: url(https://fonts.gstatic.com/s/materialicons/v40/flUhRq6tzZclQEJ-Vdg-IuiaDsNcIhQ8tQ.woff2) format('woff2');
}
```

It appears those download just fine.  In Firefox, I can edit and resend a request, so I changed the `User-Agent` header to match the one Chrome supplied, and I was given the `.woff2` URL this time.  So it appears that the user agent is driving decisions on which font files to download, but it appears `.woff` files are not publicly accessible as of a few hours ago.

**Comment by garretrieger** [comment]
Thanks for the report, we're rolling back the update that caused this.

**Comment by garretrieger** [comment]
The rollback is finished. You may need to clear your cache, or otherwise force a refresh of the CSS request to get the updated version.

**Comment by ajyong** [comment]
I can confirm it is working on my end again.  Thank you for the prompt response!
