### ISSUE TITLE
All subsets are returned even if none are requested

### ISSUE THREAD

**Issue by Francismori7** [google/fonts#1647]
**Procedure**
Visit https://fonts.googleapis.com/css?family=Montserrat:300,400,600,700

**Expectation**
Response should contain only the latin subset

**Actual response**
Response contains all subsets compatible with the font (cyrillic-ext, cyrillic, vietnamese, latin-ext), resulting in multiple more requests for fonts

**Comment by m4rc1e** [comment]
See #1399 #68.

**Comment by Francismori7** [comment]
Thanks @m4rc1e, I was aware of that, however that does render the selection process in the fonts.google.com drawer useless, since they are returned regardless of selection?

**Comment by Francismori7** [comment]
That makes sense, I keep forgetting that the responses are browser-specific.

**Comment by m4rc1e** [comment]
No worries. Thanks for closing :-)
