### ISSUE TITLE
Update Lato font to 2.015 version?

### ISSUE THREAD

**Issue by dasklney** [google/fonts#165]
Hello,

I really love Lato web font and intend to use on all of my website, but the current version at Google Web Fonts doesn't support Vietnamese.

I can see that the new version from Latofonts.com does support Vietnamese, please update the font for us to have more scripts.

Resource: http://www.latofonts.com/

Many thanks,
Giang

**Comment by davelab6** [comment]
I will do this early next year

**Comment by davelab6** [comment]
Quick update on this, I have not yet processed this but I will do soon :)

**Comment by borissamardzija** [comment]
Hi @davelab6, any chance Lato will be updated soon?

Current version is missing some diacritics, as you can see here
http://jsbin.com/momova/edit?html,css,output

**Comment by davelab6** [comment]
Closing as duplicate of #6
