### ISSUE TITLE
Add Space Grotesk

### ISSUE THREAD

**Issue by mightybart** [google/fonts#1665]
GitHub repository: https://github.com/floriankarsten/space-grotesk

Space Grotesk is a proportional version of Space Mono (Colophon Foundry, 2016). Available in five weights (Light, Regular, Medium, SemiBold, Bold). Designed by [Florian Karsten](https://floriankarsten.com).

![Space Grotesk by Florian Karsten](https://fonts.floriankarsten.com/files/space-grotesk-about.png)

Space Grotesk supports Latin Extended-A character set and several OpenType features. For complete specs see typeface [specimen](https://fonts.floriankarsten.com/space-grotesk/space_grotesk_specimen.pdf) (PDF, 2.3 MB).

Type tester available at [fonts.floriankarsten.com](https://fonts.floriankarsten.com/space-grotesk).

![Space Grotesk Preview](https://fonts.floriankarsten.com/files/space-grotesk-styles.png)

**Comment by mightybart** [comment]
RFN removed

**Comment by iskrisis** [comment]
Is there any progress on this?

**Comment by ryanleichty** [comment]
This would be a great addition to Google Fonts’ collection. How frequently do they add new fonts?

**Comment by davelab6** [comment]
It has been extremely slow the last few years. but we have better tooling
now to speed it up.

**Comment by jlaari** [comment]
Waiting this.

**Comment by riderx** [comment]
same

**Comment by MizR** [comment]
+1 for this.

**Comment by jonijuup** [comment]
+1

**Comment by MizR** [comment]
> It has been extremely slow the last few years. but we have better tooling now to speed it up.

@davelab6 Any update?

**Comment by m4rc1e** [comment]
It's now in production, https://fonts.google.com/specimen/Space+Grotesk.
