### ISSUE TITLE
Bad Ț diacritic in Roboto, even it is OK on Roboto Condensed, Mono and Slab

### ISSUE THREAD

**Issue by bogdandragomir** [google/fonts#167]
These are all Romanian diacritics: ă, â, î, ș, ț, Ă, Â, Î, Ș, Ț.

Roboto Condensed, Mono and Slab shows them correct, but Roboto not.
Attached is a screenshot which shows the error,
Ț character is missing from some font weights and for some it have a wrong cedilla.

I think it is very easy to repair and you will make happy many people from Romania, because this is a very nice font!

![snap](https://cloud.githubusercontent.com/assets/2846921/11969329/9efa7964-a920-11e5-9aad-efd3eb64c21e.png)

**Comment by fitojb** [comment]
Please ensure you don’t have these fonts installed locally, as any local copies will be picked up by the browser instead of displaying the web-served version.

**Comment by bogdandragomir** [comment]
You are right! Thank you
