### ISSUE TITLE
Add Red Rose Typeface

### ISSUE THREAD

**Issue by magictype** [google/fonts#1672]
Hi, I am Jaikishan Patel, Communication Designer from India. I have been working on Latin typefaces for multiple display genres dedicated to films and books under [MagicType](http://magictype.in/red-rose/).

Red Rose Pro is a new typeface designed in 2018 licensed under SIL Open Font License. I would like it to be considered for submission to the Google Fonts.

Please find the project details and source files at https://github.com/magictype/redrose

Please feel free to make suggestions or let me know if any other details required in the repository.

**Comment by m4rc1e** [comment]
Family is now live, https://fonts.google.com/specimen/Red+Rose?query=red
