### ISSUE TITLE
Upgrade Fredoka One

### ISSUE THREAD

**Issue by hafontia-zz** [google/fonts#1677]
Hi! 

I finished designing Fredoka in Hebrew: [Fredoka Hebrew](https://github.com/hafontia/Fredoka-One/)
Plus finished the variation: [Fredoka Var](https://github.com/hafontia/Fredoka-One/tree/gh-pages/Variation)

I wanted to know when will it be on google fonts? 

Cheers!
Ben

**Comment by davelab6** [comment]
<img width="199" alt="Screen Shot 2021-09-29 at 9 48 18 AM" src="https://user-images.githubusercontent.com/261579/135281430-43e26a38-efbd-4ecc-ab43-7c5ff4b04200.png">

What a sad aspiration, lol

Good news, we are working to make the roadmap more clear via Github Issues Milestones, and now it looks like this is going to be done in Q1. 

That may give us time to sort out https://github.com/google/fonts/issues/2411

**Comment by m4rc1e** [comment]
Fixed in #4170. Will be in prod in a couple of weeks.
