### ISSUE TITLE
For each metadata.json now also a metadata.pb

### ISSUE THREAD

**Issue by strarsis** [google/fonts#168]
I have got two questions concerning metadata files:

1. It appears that all font folders with a metadata.json also got a metadata.pb now.
Which one is "authoritative"? Are both always in sync and how is this ensured?

2. Why are pb (protocolbuffer) files used instead of JSON? 
To faster parse and generate the list of available fonts for Google Developer Fonts API?

Thank you and
with best regards

**Comment by davelab6** [comment]
2 is right; for 1, we are in a transition from json to pb so I recommend to
use the pb files from now on.

**Comment by strarsis** [comment]
So the json files are deprecated now and will be removed completely in near future?

**Comment by davelab6** [comment]
Yes

**Comment by strarsis** [comment]
Thank you for the explanations.
