### ISSUE TITLE
Add Diodon

### ISSUE THREAD

**Issue by davelab6** [google/fonts#1681]
https://github.com/atelierequin/diodon

Great work @atelierequin :)

**Comment by atelierequin** [comment]
Thanks ! Will you use it ? :p

**Comment by m4rc1e** [comment]
I love it. Only problem is the glyphset is possibly too small. I've done some mastering so I will send you a pr. Will also submit an issue regarding the charset.

**Comment by atelierequin** [comment]
Hi Marc!

Thanks watching my font project. I haven’t been working on it for a long time. My last year bachelor project took me a lot of time (you can see it on my Instagram if you want @adrienlerequin), I think I’m gonna work on the Diodon this summer and make it more efficient. Can’t wait to see what you made with it!

Thanks to you
Adrien Requin

**Comment by emmamarichal** [comment]
Hello @atelierequin, je t'ai envoyé un mail à propos de ce projet, on peut s'appeler si besoin! :)
Cheers!

**Comment by emmamarichal** [comment]
The designer told me that he no longer did type design, and that he had no plans to work on it again. So I'm closing the issue, and @atelierequin, feel free to open a new one if you change your mind :)

**Comment by emmamarichal** [comment]
I reopen this issue. The designer reached me: he would be interested to continue the work on this project, it could be done at the end of the year. 

@chrissimpkins, since Dave opened the issue, should we add the tag "accepted', or should we have a look during the intake meeting? 
cc @davelab6

**Comment by davelab6** [comment]
Since it is a display family, and so nice, if it has the GF Latin Kernel covered, I think we can accept it and update from there. @emmamarichal shared this is what is missing:

<img width="696" alt="Screenshot 2024-08-06 at 10 16 55 AM" src="https://github.com/user-attachments/assets/c8684d8a-36a6-47b8-9998-404ebc4d1936">

@atelierequin I would love to prioritize this for quick turn around if you are able to collaborate with Emma to fulfil the Kernel glyph set

**Comment by atelierequin** [comment]
Hello Dave! Thanks for giving me the opportunity to finally complete this
project, and also for the kind words!

Emma and I have already set up a meeting and will start working together as
soon as possible.

Sincerely yours,

*Adrien Requin*
2D/3D Graphic & Motion Designer
Mobile +33 6 47 58 43 01
Portfolio : https://www.behance.net/adrienrequfc7a



Le mar. 6 août 2024 à 18:18, Dave Crossland ***@***.***> a
écrit :

**Comment by emmamarichal** [comment]
update: the designer will not work on that project anymore, I close that issue then!
