### ISSUE TITLE
Upgrade Cormorant

### ISSUE THREAD

**Issue by richbowen** [google/fonts#1687]
As the title says. The font is at v3.504.

**Production notes:**

- [x]  Repo structure
- [x]  Fontbakery
- [x]  Visual QA
- [ ]  Build (Swap issue to solve)
- [ ]  PR Upstream
- [ ]  Package

**Comment by rgb-one** [comment]
Here's the repo: https://github.com/CatharsisFonts/Cormorant

**Comment by CatharsisFonts** [comment]
Dear @RosaWagner, I believe we are ready for reingestion with the current Cormorant instance. Would you like me to make a release, or wait until you're done with it?

Cheers, Christian

**Comment by RosaWagner** [comment]
Thanks for updating us, I'll take a look first and send you pull request if I see anything :)

**Comment by RosaWagner** [comment]
@CatharsisFonts we started to look it up. We noted design issues with diacritics but we'll come back to that later. Our first goal is to structure the repo according to GF spec and be have a repeatable export process using a fontmake/fonttools based script. I see 3 sources (Roman Italic Upright) for 7 families (Cormorant + Garamond, Infant, Unicase, Upright, SC), it would be helpful to have an overview of the specialities of each family, so they get correctly exported. We can set up a call if you'd like.
