### ISSUE TITLE
Add Kulim Park

### ISSUE THREAD

**Issue by noponies** [google/fonts#1688]
I would like to submit Kulim Park for consideration and inclusion into Google Fonts. It is licensed under SIL Open Font License. 

Kulim Park is a response to a local park redevelopment and how I might, as a designer create an artefact which captured this process and my intertwined personal history with this site.

Please find the project details and source files at [https://github.com/noponies/Kulim-Park](https://github.com/noponies/Kulim-Park)

![kulim-park-cover](https://user-images.githubusercontent.com/7235916/45399062-d3d57280-b69a-11e8-9c67-f750edb5e6e6.png)

**Comment by davelab6** [comment]
@noponies thanks for proposing this. Github repo looks good. The design is somewhat naieve, but that has a certain charm. I would propose to have a senior type designer review the project before adding it, and I encourage you to keep learning! :) Did you read http://www.tipo-e.com/publicaciones/how-to-create-typefaces.html yet? :)

**Comment by noponies** [comment]
@davelab6 Thanks for the reply. I've not read that publication, but will try to source it. Cheers for the tip about it and for the encouragement! Yes, plenty to learn still :)

**Comment by yanone** [comment]
@davelab I find this legit. The uppercase letters are an accurate representation of the photo posted towards the bottom here in the repo, which couldn't possibly be any wonkier: https://github.com/noponies/Kulim-Park
Just the other day I was looking for a typeface like that.
I would add this.

**Comment by m4rc1e** [comment]
Family is now in production https://fonts.google.com/specimen/Kulim+Park

**Comment by noponies** [comment]
Awesome Marc and thanks to the GF team.

**Comment by yanone** [comment]
Manually linking PR: https://github.com/google/fonts/pull/2181
