### ISSUE TITLE
Add Rowdy Pro Typeface

### ISSUE THREAD

**Issue by magictype** [google/fonts#1690]
[Rowdy Pro](http://magictype.in/rowdy/) is a Latin display typeface inspired by the rough & tough Indian action cinema. It is licensed under SIL Open Font License.

I would like to submit Rowdy for consideration and inclusion into Google Fonts. Source files: https://github.com/magictype/rowdy 
Please feel free to make suggestions or let me know if any other details required in the repository.

Thanks.
Jaiki

**Comment by davelab6** [comment]
Great job!

**Comment by jaikishanpatel** [comment]
Thanks @davelab6 :)
Pls tag me @jaikishanpatel for any further actions on the @magictype repo.

**Comment by yanone** [comment]
@jaikishanpatel HvD Fonts lists a typeface named "Rowdy". 
@davelab6 Please advise how to proceed. Consider renaming?

**Comment by jaikishanpatel** [comment]
Thanks, @yanone We may consider renaming it to 'Rowdies'. [Checked here](https://namecheck.fontdata.com/) for availability.

**Comment by davelab6** [comment]
Rowdies sounds good to me

**Comment by m4rc1e** [comment]
Rowdies is now in production, https://fonts.google.com/specimen/Rowdies

**Comment by yanone** [comment]
Manually linking PR: https://github.com/google/fonts/pull/2195
