### ISSUE TITLE
Add Gold Typeface

### ISSUE THREAD

**Issue by magictype** [google/fonts#1691]
[Gold](http://magictype.in/gold/) is a Latin display typeface with over 640+ Latin plus glyphs. The typeface is designed for Passion, Science Fiction, Sports, Drama, Thriller genres. It is licensed under SIL Open Font License. 

I would like to submit Gold for consideration and inclusion into Google Fonts. Please find the project details and source files at https://github.com/magictype/gold 
Please feel free to make suggestions or let me know if any other details required in the repository.

Thanks.
Jaiki

**Comment by davelab6** [comment]
:)

**Comment by davelab6** [comment]
Thanks!

**Comment by jaikishanpatel** [comment]
Thanks @davelab6 :) 
Pls tag me @jaikishanpatel for any further actions on the @magictype repo.

**Comment by yanone** [comment]
@jaikishanpatel This typeface's name is in conflict with trademarked typeface [Gold by FontMesa](https://www.myfonts.com/fonts/fontmesa/gold/).
Please consider renaming. Available names can be [checked here](https://namecheck.fontdata.com/?q=gold).

**Comment by jaikishanpatel** [comment]
Thanks, @yanone  We may consider renaming it to 'Goldman'. [Checked here](https://namecheck.fontdata.com/) for availability.

**Comment by davelab6** [comment]
Added @ https://fonts.google.com/specimen/Goldman
