### ISSUE TITLE
My font (adobe XD Montserrat) looks different live. How to solve this?

### ISSUE THREAD

**Issue by Ross1307** [google/fonts#1694]

**Comment by m4rc1e** [comment]
screenshot?

Perhaps it's an older version?

**Comment by Ross1307** [comment]
> screenshot?
> 
> Perhaps it's an older version?

Hi!
We have added font-family. It will get latest version always. But see difference in screenshot. 

https://fonts.googleapis.com/css?family=Montserrat

**Screenshot:**
https://user-images.githubusercontent.com/40488601/45739602-a8e7a300-bbf3-11e8-89bc-748de093b9ba.png

**Comment by m4rc1e** [comment]
In the screenshot, the font on the right hand side looks like a fallback font.

**Comment by Ross1307** [comment]
> In the screenshot, the font on the right hand side looks like a fallback font.

Thanks for your help. We solved it in the end with an update of Polymer.
