### ISSUE TITLE
Montserrat not being served with glyphs for ≥ and ≤

### ISSUE THREAD

**Issue by akunohomu** [google/fonts#1698]
Montserrat supports both `≥` and `≤`. However, when selecting it on Google Fonts, the CSS served does not include the codepoints for these glyphs (U+2265 and U+2264). I can't see any way to fix this by myself other than self-hosting the full font and removing unicode-range specifier (which does change the glyph displayed for ≥ by my browser)

CSS being served:

```
/* cyrillic-ext */
@font-face {
  font-family: 'Montserrat';
  font-style: normal;
  font-weight: 400;
  src: local('Montserrat Regular'), local('Montserrat-Regular'), url(https://fonts.gstatic.com/s/montserrat/v12/JTUSjIg1_i6t8kCHKm459WRhyzbi.woff2) format('woff2');
  unicode-range: U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F;
}
/* cyrillic */
@font-face {
  font-family: 'Montserrat';
  font-style: normal;
  font-weight: 400;
  src: local('Montserrat Regular'), local('Montserrat-Regular'), url(https://fonts.gstatic.com/s/montserrat/v12/JTUSjIg1_i6t8kCHKm459W1hyzbi.woff2) format('woff2');
  unicode-range: U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116;
}
/* vietnamese */
@font-face {
  font-family: 'Montserrat';
  font-style: normal;
  font-weight: 400;
  src: local('Montserrat Regular'), local('Montserrat-Regular'), url(https://fonts.gstatic.com/s/montserrat/v12/JTUSjIg1_i6t8kCHKm459WZhyzbi.woff2) format('woff2');
  unicode-range: U+0102-0103, U+0110-0111, U+1EA0-1EF9, U+20AB;
}
/* latin-ext */
@font-face {
  font-family: 'Montserrat';
  font-style: normal;
  font-weight: 400;
  src: local('Montserrat Regular'), local('Montserrat-Regular'), url(https://fonts.gstatic.com/s/montserrat/v12/JTUSjIg1_i6t8kCHKm459Wdhyzbi.woff2) format('woff2');
  unicode-range: U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF;
}
/* latin */
@font-face {
  font-family: 'Montserrat';
  font-style: normal;
  font-weight: 400;
  src: local('Montserrat Regular'), local('Montserrat-Regular'), url(https://fonts.gstatic.com/s/montserrat/v12/JTUSjIg1_i6t8kCHKm459Wlhyw.woff2) format('woff2');
  unicode-range: U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD;
}
```

**Comment by davelab6** [comment]
If its in the font, you can get it via the API using the text= feature

**Comment by laerm0** [comment]
Hi @akunohomu , have you figured this out?

**Comment by MarcelGerber** [comment]
I am also experiencing this problem with the Lato and Roboto fonts, so this is definitely not specific to Montserrat.
One solution is to explicitly load Lato with `&text=≥≤`, but this is not a particularly great solution. I found no other way (subset or stuff like that) to load these glyphs.

A demo can be found here: https://codesandbox.io/s/google-fonts-lato-greater-than-equal-p5icv

**Comment by MarcelGerber** [comment]
What's even worse is that it works without issues on the Google Fonts site (https://fonts.google.com/specimen/Lato?selection.family=Lato:ital,wght@0,300;0,400;0,700;1,400;1,700&preview.text=%E2%89%A5&preview.text_type=custom), suggesting these glyphs would just work out-of-the-box on your site, too.

<img src="https://user-images.githubusercontent.com/2641501/76163343-84fc8200-6145-11ea-90f9-c11b7b6e3d82.png" width="600" />

**Comment by akunohomu** [comment]
I believe my solution (no longer maintaining the relevant site) was to self-host the entire font with long-expiry cache headers. IIRC it was simpler than trying to figure out the (then-beta?) text= feature and resulted in better user experience than using Google Fonts due to faster loading of fonts.
