### ISSUE TITLE
Missing ellipsis for Alegreya Sans

### ISSUE THREAD

**Issue by Jellby** [google/fonts#170]
The glyph for the horizontal eliipsis (&hellip;) is available in the original Alegreya Sans font (https://github.com/huertatipografica/Alegreya-Sans), but not in the Google Fonts version, as far as I can see. It's probably be the same for Alegreya (serif), but I haven't tried.

May be related to #19

**Comment by m4rc1e** [comment]
Closing.

Alegreya Sans now has an elipsis glyph, http://jsbin.com/paribofaha/edit?html,output

![screen shot 2017-06-14 at 11 49 18](https://user-images.githubusercontent.com/7525512/27128702-89cc1e32-50f7-11e7-8afe-eb5e57e98207.png)
