### ISSUE TITLE
Raleway 400 overridden by local version installed through Adobe Typekit

### ISSUE THREAD

**Issue by nhfruchter** [google/fonts#1701]
If you have Adobe Typekit installed, Google Fonts prefers the locally installed font even if it's the wrong weight. For instance, I had Raleway Black installed through Typekit and all instances of Raleway 400 were being rendered as Raleway Black (from Typekit), instead of Raleway 400 from Google's servers.

![Screenshot of issue](https://user-images.githubusercontent.com/490722/46038561-6cc3af00-c0d9-11e8-8e31-2815f1848da1.png)

I'm not sure if this is a fixable problem or not given how Google specifies `src` in the CSS files it generates. May be related to #1508.

**Comment by laerm0** [comment]
Hi @nhfruchter. This is covered in the FAQ:

> Can I download the fonts on Google Fonts to my own computer?
> 
> Yes. To download fonts, simply create a selection of fonts, open the drawer at the bottom of the screen, then click the "Download" icon in the upper-right corner of the selection drawer. You can download the fonts to use in mock-ups, documents, or locally on your machine.
> 
> Note that when browsers render websites that use the Google Fonts API, they will check if a font is installed locally on your computer, and prefer to use the local version over web fonts. To make sure the fonts installed locally on your personal computer are always up-to-date, we recommend using a fonts manager (such as SkyFonts) that automatically syncs the latest versions of fonts from the Google Fonts API to your computer.

https://developers.google.com/fonts/faq
