### ISSUE TITLE
Roboto Thin Umlaut Issue

### ISSUE THREAD

**Issue by matthiasulrich** [google/fonts#1715]
The Thin stye from the Font Roboto does not seem to correctly represent the umlauts

<img width="624" alt="bildschirmfoto 2018-10-04 um 06 53 58" src="https://user-images.githubusercontent.com/12305781/46453537-4d481880-c7a2-11e8-805e-1a2033f68eb6.png">
<img width="644" alt="bildschirmfoto 2018-10-04 um 06 53 49" src="https://user-images.githubusercontent.com/12305781/46453538-4f11dc00-c7a2-11e8-98fb-6db62ad2f30a.png">

**Comment by fitojb** [comment]
You have a very old copy of Roboto installed, which is interfering with your browser display. Remove it and try again.

**Comment by matthiasulrich** [comment]
You are right!
Thank you ver much!
