### ISSUE TITLE
Rubik font not working properly

### ISSUE THREAD

**Issue by DonDi1989** [google/fonts#1718]
Hi, I am using the Rubik font in one of my websites and it doesn't work properly in Google Chrome these days. Attached you can see how the font looks in website and you can see that the "a" and "s" letters are bolder and "e" letter is looking weird. The problem is only in my Chrome browser, I have checked in my other browsers and everything is working properly. Also checked in one of my friends chrome browser and everything was fine. Attached you can find an image which will show to you my problem. How can I resolve this problem ?
![screenshot_28](https://user-images.githubusercontent.com/1840313/46813923-ee713900-cd77-11e8-8d05-dc6bdf7eb38f.png)
.

**Comment by laerm0** [comment]
Hi @DonDi1989 , are you still having this problem? It [looks good](https://jsbin.com/wapaviyuko/edit?html,output) to me.

**Comment by DonDi1989** [comment]
Everything is fine @laerm0 :)
