### ISSUE TITLE
Question about font meta data

### ISSUE THREAD

**Issue by kerstin** [google/fonts#1722]
Hi there, I perused the Fonts [Developer API info page](https://developers.google.com/fonts/docs/developer_api) and this repo and also tried to google (...) for an answer to my question but found nothing conclusive, so I'm asking here: am I right in that the meta data the API provides is not the same as – or only partially overlaps with – the meta data listed in the `METADATA.pb` files? I was looking for designer names and licensing info in particular.

**Comment by davelab6** [comment]
Yes the metadata files in this repo are ingested and may be edited into
Googles infrastructure, then published into the developer API. Ideally they
should all match but they have diverged and defragging them is not a high
priority.

**Comment by m4rc1e** [comment]
@kerstin yes. I'd os.walk the fonts dir and use [Google's Protocol Buffers](https://developers.google.com/protocol-buffers/) to read the METADATA.pb files then extract the designer and license info.

**Comment by kerstin** [comment]
@m4rc1e Thank you!

**Comment by kerstin** [comment]
@m4rc1e Am now also stuck on the problem described in #1591 :P will close this issue though because my original question was anwered.
