### ISSUE TITLE
I want to contribute a font!

### ISSUE THREAD

**Issue by elron** [google/fonts#1725]
Hello
I've designed a font and I want to contribute it to google fonts.
How can I do that?
Who can I contact?

Thanks

**Comment by fanninpm** [comment]
It should go without saying, but please make sure you read [CONTRIBUTING.md](https://github.com/google/fonts/blob/master/CONTRIBUTING.md).

**Comment by davelab6** [comment]
If you want to talk to someone 1:1 privately, DM me on twitter?

**Comment by laerm0** [comment]
How's it going, @elron ? Do you understand the process?
