### ISSUE TITLE
Upgrade Nunito [opsz,slnt,wdth,wght]

### ISSUE THREAD

**Issue by wolftune** [google/fonts#1726]
Compared to most other fonts, the italic versions of Nunito have both very subtle angle and no substantial difference in style otherwise. The result makes it far too easy to not notice an italicized word in a paragraph as being italic.

**Comment by fanninpm** [comment]
I'd recommend you submit an issue to [this place](https://github.com/vernnobile/NunitoFont/issues), instead of here.

**Comment by wolftune** [comment]
Thanks

**Comment by wolftune** [comment]
Thanks but that repo hasn't been updated in 5 years and doesn't even include the italic versions at all, so that can't be the place where issues with italic would be relevant…

**Comment by davelab6** [comment]
This is a fine suggestion, I think the current 'italics' for Nunito and Nunito Sans are really 'oblique' designs - i.e. slanted by hand and optically corrected by @fonthausen, and not 'true' italics with more cursive forms. 

The source files have a `.ss01` stylistic set with a single story 'a' (etc) so you could build your own (even without a font editor, just https://github.com/twardoch/fonttools-utils/tree/master/pyftfeatfreeze :) 

Also in Muli, the x height is a little different but the alternates are already put in default glyph slots there

**Comment by davelab6** [comment]
I'm closing as we have no active plans to do this.

**Comment by davelab6** [comment]
Ah, good news @wolftune! Turns out @fonthausen was aware of this issue and the next-generation of Nunito (with a range of optical size) has a slant axis up to 9°, as the original angle was 4.51° - the idea was to incorporate a slant axis where 50% along the axis would be like the original.
