### ISSUE TITLE
Where is Comic Sans?

### ISSUE THREAD

**Issue by POWERUPT** [google/fonts#1731]
Seems to be missing on my google site. It used to be called comic sans ms, then chenla, now nothing.

**Comment by POWERUPT** [comment]
In case anyone wants to call me unprofessional, it is entirely intentional. :)

**Comment by davelab6** [comment]
Comic Sans is available as a system font on some systems, and can be licensed from Monotype.

**Comment by POWERUPT** [comment]
Makes sense. I don't mean to sound annoying (or stupid, for that matter), but is there a reason why it is in Docs, but not sites? I have been noticing some issues like this with my linux laptop and times new roman in docs; it literally disappeared and reappeardd like a week ago. Thanks!
