### ISSUE TITLE
Update Source Sans Pro with version 2.45

### ISSUE THREAD

**Issue by davelab6** [google/fonts#1744]
https://github.com/adobe-fonts/source-sans-pro/releases

**Comment by fitojb** [comment]
The new TTFs lack hinting, however

**Comment by davelab6** [comment]
Maybe as https://v-fonts.com/fonts/source-sans-variable ?

**Comment by thlinard** [comment]
Fonts version 3.006 (OTF, TTF, WOFF, WOFF2, Variable) released.

- Harmonizes glyph set between Roman and Italic styles (with the exception of small capitals)
- Adds Cyrillic and Greek to italic fonts

**Comment by davidschwegler** [comment]
An improved version of the font has been available for 2+ months, and this issue has been open for a year. Is there something we can do to get attention to this? 

Any issue that's been open for a year leads me to believe something is wrong.

**Comment by thlinard** [comment]
Hi @davelab6 @m4rc1e @laerm0 No one working on it? Am I missing something?

**Comment by thlinard** [comment]
Adobe provides the updated version here:
https://fonts.adobe.com/fonts/source-sans

**Comment by elliottslaughter** [comment]
What's blocking this? Is it the issue with font hinting (mentioned in the first comment on this issue)? Is it time from a contributor to push this through? (If the latter, is it something someone in the community could help with?)

**Comment by davelab6** [comment]
@m4rc1e @RosaWagner please can we expedite this

**Comment by davelab6** [comment]
I spoke to @m4rc1e @RosaWagner about this and I suggest a few steps forwards:

Find out the development history of the source sans and source serif projects. The Sans release in [v2.45 was the last release](https://github.com/adobe-fonts/source-sans/releases/tag/2.045R-ro%2F1.095R-it) in this design-branch, where the italics have less glyphs than the romans

Then the v3.0 from 2019-09 was redrawn and probably introduces an unacceptable amount of regressions, but has a new family name, `Source Sans Pro 3`, so lets PR this new v3 family with the new name.

Then we can de-list the v2 family `Source Sans Pro` from the fonts.google.com catalog.

And a possible 4th step is to fork the v3 files and change the name table to the original name, and push that as an update in place over the top of the v2. However, I want to see what the regressions are, before deciding to do this. 

@m4rc1e please post the regression images here
