### ISSUE TITLE
403 when loading Helvetica in Firefox

### ISSUE THREAD

**Issue by btmdave** [google/fonts#1747]
This is a strange case, where when requesting fonts and specifically Helvetica (which loads Helvetica LT), firefox will throw a 403.  Here's an example: http://jsfiddle.net/0zdw9u2e/

If you check Network panel and Run in Chrome - you'll see 200 for the following requested url: https://fonts.googleapis.com/css?family=Alfa+Slab+One:000,000i|Poppins:000,000i|Fjalla+One:000,000i|Lora:000,000i|Helvetica:000,000i

However, if you do the same in Firefox, you'll see that it returns a 403.  Going directly to that url does  appear to load fine in Firefox, it's when included as a link that it throws the 403.

If you remove Helvetica from the request, it will load correctly in both.

**Comment by m4rc1e** [comment]
Unfortunately Helvetica LT is not served on GF.

Your endpoints are strange, 0000,0000 wont work.

Here's a valid endpoint
```
<link href="https://fonts.googleapis.com/css?family=Raleway:100,100i,200,400" rel="stylesheet">
```

items which are between commas are font-weights. i at the end of a font weight means it's also italic.

Please construct endpoints using the font selection panel on https://fonts.google.com

![Uploading Screen Shot 2018-11-01 at 15.53.46.png…]()


If you need Helvetica LT, you're going to need to load it from another source or self host it, if you have a license which permits self hosting.

**Comment by laerm0** [comment]
Closed as not a Google Fonts font.
