### ISSUE TITLE
Please name Comfortaa VF correctly

### ISSUE THREAD

**Issue by thlinard** [google/fonts#1760]
https://github.com/google/fonts/blob/master/ofl/comfortaa/Comfortaa-Regular.ttf should be named Comfortaa-Roman-VF.ttf.

**Comment by davelab6** [comment]
@nyshadhr9 if we rename the fonts (and update METADATA) can you accept the `-Roman-VF` filename?

**Comment by thlinard** [comment]
Since #1782, the VF font and the Regular static font have the same file name. And we cannot assume the static fonts will always stay in a subfolder: please, give the VF font a different file name.

**Comment by laerm0** [comment]
I think this is what we've decided to do, yes? @nyshadhr9 @m4rc1e

**Comment by thlinard** [comment]
@laerm0 See #1817.
