### ISSUE TITLE
Please restore Comfortaa static fonts

### ISSUE THREAD

**Issue by thlinard** [google/fonts#1761]
The static fonts (3 weights) were suppressed in https://github.com/google/fonts/tree/master/ofl/comfortaa

**Comment by m4rc1e** [comment]
@thlinard Know of any apps which don't support VFs?

**Comment by thlinard** [comment]
Thanks, Dave. InDesign (CC 2019) still can't see the named instances.

**Comment by m4rc1e** [comment]
@thlinard thanks for testing a vf in Indesign.

**Comment by thlinard** [comment]
@m4rc1e I tested InDesign CC 2019, under macOS 10.14.2 : InDesign can't see the named instances (no problem in Illustrator or Photoshop CC 2019, they even give access to the weight axis).

**Comment by m4rc1e** [comment]
@thlinard thank you for testing this! perhaps InDesign still lacks support for vfs?

**Comment by thlinard** [comment]
@m4rc1e Looks like. There is obviously no variation axis support. But above all, I wanted to insist on this point, there is no support for named instances: static fonts are still necessary.
