### ISSUE TITLE
Please name Vollkorn VF correctly

### ISSUE THREAD

**Issue by thlinard** [google/fonts#1762]
https://github.com/google/fonts/blob/master/ofl/vollkorn/Vollkorn-Italic-VFBeta.ttf
https://github.com/google/fonts/blob/master/ofl/vollkorn/Vollkorn-Roman-VFBeta.ttf

should be named
Vollkorn-Italic-VF.ttf
Vollkorn-Roman-VF.ttf

**Comment by laerm0** [comment]
[discussion to follow in #1760]

**Comment by thlinard** [comment]
@laerm0 :  in #1817.
