### ISSUE TITLE
Alegreya kerning missing in the generated TTF

### ISSUE THREAD

**Issue by Ketsuban** [google/fonts#18]
I'm migrating this from [Google Code issue 295](https://code.google.com/p/googlefontdirectory/issues/detail?id=295) as there was no resolution, and this impacts anyone who chooses to use Alegreya.

> The kerning seems to be missing in the generated font files.
> 
> For example, W and e ("We") in Alegreya-Regular should have -75 kerning between them according to Alegreya-Regular-TTF.vfb. According to Fontforge, this does not seem to be the case in the generated TTF-file. Similar issues are present also in the other weights and styles.

**Comment by davelab6** [comment]
Thanks for this. I'll migrate open issues to this tracker by hand, as the
import tools available are quite rough. @adrientetar did you upstream your
combines Alegreya?

**Comment by adrientetar** [comment]
Still in the making.

**Comment by adrientetar** [comment]
@davelab6 I'd upstream the opttimized files from Adobe which have kerning along with improved hinting in some of the weights but they added a txt file in the archive "Copyright (c) 2013 by Adobe Systems Incorporated. All Rights Reserved." Is this a problem for upstreaming?

**Comment by adrientetar** [comment]
To clear things up they added it in the folder that contains the VFBs. This seems to contradict the SIL OFL license.

**Comment by adrientetar** [comment]
cc @gregveen

**Comment by Ketsuban** [comment]
This string is in the metadata for the Alegreya and Alegreya SC font files currently available through Google Fonts.

> Copyright (c) 2011, Juan Pablo del Peral (juan@huertatipografica.com.ar), with Reserved Font Names "Alegreya" "Alegreya SC"

This is repeated verbatim on the Typekit licensing pages for Alegreya ([example](https://typekit.com/eulas/0000000000000000000148b9)) and Alegreya SC ([example](https://typekit.com/eulas/0000000000000000000148b9)), followed by the Adobe copyright string you pointed out. IANAL, but I get the impression this is to indicate conformance with the OFL rather than an assertion in contradiction with it.

**Comment by adrientetar** [comment]
I see, the All Rights Reserved statement I found rather confusing since it's stated along the LICENSE itself.  
@davelab6 Did you just take all src files out of repo? Guess I’ll only PR the binaries then.

**Comment by m4rc1e** [comment]
Closing.

Alegreya Sans has kerning

![alegreya_sans](https://user-images.githubusercontent.com/7525512/27128886-3fd7ddf6-50f8-11e7-95da-5266c2e0caef.gif)
