### ISSUE TITLE
Include Liberation Fonts in Google Fonts Collection

### ISSUE THREAD

**Issue by cashell** [google/fonts#180]
The Liberation Fonts set is among my favorites, particularly the Monospace font (my all-time favorite console/coding font).  I'd love to see it included in the Google Fonts Collection, and as near as I can tell, it meets all of the qualifications for inclusion.

Main URL: https://fedorahosted.org/liberation-fonts/

(Note: I am not involved with the Liberation Fonts, just a huge fan of Liberation Fonts and the Google Fonts Collection.)

**Comment by davelab6** [comment]
The Liberation Fonts were licensed from Ascender to Red Hat under the GPL. Ascender later licensed the same fonts to Google under the OFL, with improved TT hinting, as Arimo, Cousine and Tinos - names that better reflect that they are metric compatible with Monotype's Arial, Courier New and Times New Roman. Ascender was later acquired by Monotype, and Monotype continues to maintain the fonts for Google. 

So please use https://www.google.com/fonts/specimen/Cousine :)

**Comment by cashell** [comment]
Ah!  I knew that the Liberation fonts were licensed to Red Hat, but didn't know the rest of the history.  I just checked out Cousine and verified that it is the same as Liberation Mono.  I will use that from now on.

Thank you again, much appreciated!
