### ISSUE TITLE
Allow subsetting in SIL Open Font License v1.1 with Reserved Font Name …

### ISSUE THREAD

**Issue by fooness** [google/fonts#1805]
Is it possible to add one more line to `OFL.txt`, which says, for example, “Subsetting this Font Software with its Reserved Font Name is explicitly allowed.“?

```
Copyright (c) <dates>, <Copyright Holder> (<URL|email>),
with Reserved Font Name <Reserved Font Name>.

Subsetting this Font Software with its Reserved Font Name is explicitly allowed.

This Font Software is licensed under the SIL Open Font License, Version 1.1.
This license is copied below, and is also available with a FAQ at:
https://scripts.sil.org/OFL


-----------------------------------------------------------
SIL OPEN FONT LICENSE Version 1.1 - 26 February 2007
-----------------------------------------------------------

[…]
```

**Comment by laerm0** [comment]
I don't think it's up to the Google Fonts project to alter a license created by the SIL. @davelab6 ?

**Comment by fooness** [comment]
@n8willis I was just wondering if it’s possible to retain the SIL OFL 1.1 with RFN but allow subsetting … seems like the “solution” to this matter was not really adding anymore fonts licensed with SIL OFL 1.1 with RFN to Google Fonts, which is not ideal in my opinion.

**Comment by s-light** [comment]
@n8willis out of interest i picked a random couple to check - most of them had a RFN defined:
- [Allura](https://github.com/google/fonts/blob/master/ofl/allura/OFL.txt#L2)
- [Ruthie](https://github.com/google/fonts/blob/master/ofl/ruthie/OFL.txt#L2)
- [Antic](https://github.com/google/fonts/blob/master/ofl/antic/OFL.txt#L2)
- [Euphoria Script](https://github.com/google/fonts/blob/master/ofl/euphoriascript/OFL.txt#L2)
- [Hanna](https://github.com/google/fonts/blob/master/ofl/hanna/OFL.txt#L2)

there are also some without defined RFN:
- [Cairo](https://github.com/google/fonts/blob/master/ofl/cairo/OFL.txt)
- [Gothica1](https://github.com/google/fonts/blob/master/ofl/gothica1/OFL.txt)



@fooness the FAQ at SIL states:
[Web Fonts and Reserved Font Names](https://scripts.sil.org/cms/scripts/page.php?site_id=nrsi&id=OFL_web_fonts_and_RFNs#14cbfd4a)
> ... For example, a process that delivers a font alongside a web page, using an RFN, but with degraded, incomplete or incorrect glyph shapes, could increase an author's support burden and damage their reputation. This is clearly against the spirit of the RFN mechanism and would not be allowed.

i think that makes it clear that the SIL OFL should protect exactly case like the suggested...

so this could be closed?

**Comment by fooness** [comment]
@s-light Thank you for your response. Not sure I really get what you’re saying.

I think SIL OFL 1.1 is perfectly fine, but … you can choose to define some RFN for your font, or not.

When you DO define some RFN, other people are not allowed to use your fonts with subsetting in their @font-face css files, which is weird in my opinion, OR they would have to manually rename the font when subsetting them.

**Comment by s-light** [comment]
you are right - the license defines that you have to rename if RFNs are set and you are subsetting.
and in the faq they try to clarify why.

so i think your request to 'change the license' to allow subsetting is 'Not at all possible' - 
because the license / FAQ explicitly states that this type of change is forbidden without name change..
(and therefore i think this issue could be closed as not applicable)

**Comment by davelab6** [comment]
> the fonts served by Google Fonts do not declare RFNs

Just to clarify, many fonts served by GF do have RFNs.

The SIL Open Font License text is copyright SIL all rights reserved and can't be changed by anyone without permission from SIL. No changes are planned afaik.
