### ISSUE TITLE
Add Uma Regular

### ISSUE THREAD

**Issue by UmaCalligraphy** [google/fonts#1813]
Uma Regular 

A whimsical simplified Gothic Sans-Serif typeface featuring a Latin writing system with blocky and bold glyphs. The ascender height of the capital letters is high and the width of lowercase letters is set high.

Uma Regular is designed by Uma Sharma.
Created using FontForge. 

[Uma Regular.zip](https://github.com/UmaCalligraphy/Uma-Regular/files/2758468/Uma.Regular.zip)

FontBakery Validation: http://35.225.170.228/report/6aba0e5d-9cb8-4a89-a39c-7d909f9040d2

![image](https://user-images.githubusercontent.com/45747057/51165556-77a37a80-1855-11e9-969e-172604b7a4f2.png)

https://github.com/UmaCalligraphy/Uma-Regular/issues/1

**Comment by m4rc1e** [comment]
Thanks

The upstream repo is empty though

**Comment by laerm0** [comment]
Hello @UmaCalligraphy. We have [a guide](https://github.com/google/fonts/blob/master/CONTRIBUTING.md) set up here for contributing. Thanks for your font, let us know if you have any questions.

**Comment by UmaCalligraphy** [comment]
Hi laerm0 and m4rcle, 
I added you as contributors- please let me know what I should do next. 

Thank you so much,
Uma

**Comment by davelab6** [comment]
@UmaCalligraphy if you are still interested in this, please email the font source files to fonts@google.com and I can set them up on Github :) Until then, this project will remain in the icebox :)

**Comment by vladimirnikolic1** [comment]
Uma looks nice!
