### ISSUE TITLE
All subset

### ISSUE THREAD

**Issue by PawelPatyk** [google/fonts#1836]
After selecting the appropriate subset and so it loads all versions:

https://fonts.googleapis.com/css?family=Fira+Sans+Extra+Condensed:400,500,600,700,800&amp;subset=latin-ext

https://fonts.googleapis.com/css?family=Fira+Sans+Extra+Condensed:400,500,600,700,800

**Comment by ElGrangar** [comment]
I too have this: 
https://fonts.googleapis.com/css?family=Barlow:300,400,500,700,900&amp;subset=latin-ext also loads vietnamese. I can imagine this costing some performance on fonts with many subsets.

**Comment by laerm0** [comment]
Hi @PawelPatyk and @ElGrangar, please see these issues. #1399 https://github.com/google/fonts/issues/68
