### ISSUE TITLE
Add Chiron Sans HK (Traditional Chinese)

### ISSUE THREAD

**Issue by tamcy** [google/fonts#1842]
Website: https://tamcy.github.io/chiron-sans-hk/
Github repo: https://github.com/tamcy/chiron-sans-hk

Chiron Sans HK is a Source Han Sans HC/Noto Sans CJK HK dervied font. I am the author of this font.

The glyphs in Noto Sans CJK HK mostly adheres what are defined in *Reference Glyphs for Chinese Computer Systems in Hong Kong*. However, some character forms defined in *Reference Glyphs* are different from the well-established, widespread forms commonly seen in commercially successful font products in HK.

I feel there is a demand for a font adopting such de-facto forms be provided to the community. Hence the development of Chiron Sans HK, which takes a page from commercially successful font products and chooses the forms that resembles closer to what people actually see in our daily lives.

As of version 2.021 (released 27 Jan 2020), >3,500 glyphs have been remapped or redesgined.

Despite the name, I believe the font is benefitial to Traditional Chinese users not limited to Hong Kong.

In addition, a webfont build is also avaliable [here](https://github.com/tamcy/chiron-sans-hk/tree/master/build/webfont) ([Specimen](https://tamcy.github.io/chiron-sans-hk/fonts/chiron-sans-hk/Light.html)). I followed the approach in [Noto Sans HK](https://fonts.google.com/specimen/Noto+Sans+HK) to slice the font and prepare the CSS files. I have added some more HK characters to my subset build.

For what it's worth, Chiron Sans HK [is the successor of CYanHeiHK/Chiu Yuen Sans HK which I proposed to add to Google Font two years ago](https://github.com/google/fonts/issues/575).

**Comment by hfhchan** [comment]
The original naming issues seems no longer an issue now, as there are a couple of calligraphic fonts in Google Fonts for Chinese (Simplified) that don't follow the naming guide requested in #575.  I'd like to support the inclusion of Chiron Sans in Google Fonts as it provides much more localized fonts for Hong Kong users.

**Comment by hfhchan** [comment]
The original naming issues seems no longer an issue now. Also, there are a couple of calligraphic fonts in Google Fonts for Chinese (Simplified); it will be better if the Chinese (Traditional) ones could be broadened a bit.  I'd like to support the inclusion of Chiron Sans in Google Fonts as it provides a sans font with much more localized forms for Hong Kong users.

**Comment by hfhchan** [comment]
Hi, is there any update for the addition of this font to Google Webfonts?

Chiron Sans fixes most of the issues present in Noto Sans HK which make Noto Sans HK unsuitable for use for HK users.

**Comment by tamcy** [comment]
Closing as Chiron Sans HK has (again) been superceded by Chiron Hei HK, which comes with a serif counterpart Chiron Sung HK.

As Google Fonts seems not very intested in adding Noto Sans CJK derivatives to the Google Fonts repository, I am not planning to open new issues for the two new fonts. Users interested in my fonts on the web can still use the webfont version by self-hosting or via the jsDelivr CDN. Not posting links here to avoid being seen as self-promotion, please Google it when needed.

**Comment by davelab6** [comment]
We are slow, but not disinterested. We will track down your latest and see about adding it

**Comment by tamcy** [comment]
Thanks @davelab6 for the update, glad to know that inclusion of my font is still on the radar to be included. I decided to close this issue b/c things have changed drastically both on Google Font's side (especially the massive write-up on the [spec](https://github.com/googlefonts/gf-docs/tree/main/Spec) doc, which I haven't gone through) and mine (while the background story and the glyph style on my first post are still valid, the typeface name, the website link, stats on glyph differences etc. aren't). But as you are still interested in adding my fonts, let me write a short summary of the changes as an update for you to decide if it's better to open a new issue for it, or continue the tracking here (I will update the issue title if you prefer the latter).

First, as I have said, `Chiron Sans HK` is now obsolete and has been replaced by `Chiron Hei HK`. There is also a complementary serif typeface called `Chiron Sung HK`. Here is the website and the repos:
Website: https://chiron-fonts.github.io/ (in Chinese)
Github: https://github.com/chiron-fonts/chiron-hei-hk (sans serif/Hei), https://github.com/chiron-fonts/chiron-sung-hk (serif/Sung)

Compared to the original Chiron Sans HK which LGC charset is the same as the upstream, Chiron Hei HK now comes with its own LGC charset (derived from Source Sans 3 with an opinionated scaling ratio; full set included), real LGC italics, and a "Text" style which I believe is more suitable for printing in smaller sizes, and a VF instance. This also applies to the new serif counterpart Chiron Sung HK.

And here comes the CJK glyph differences to their respective upstreams, i.e. the Noto CJK/Source Han family (HK region):
|             | Chiron Sung HK | Chiron Hei HK |
| -- | --- | --- |
| Glyph Remap (to another region) | 3502 | 2841|
| Glyph Redesign |  3418 | 2003 |
| Glyph Addition | 1170 | 1170 |

So overall, I believe the new Chiron typeface family is a worthwhile addition. My main concern (as of now) is the "upstream repository structure" as documented in the spec page and list as a required criterion for inclusion, which I am not sure if I can 100% follow.

**Comment by tamcy** [comment]
I have opened #5323 and #5324 to reflect the latest changes and to give more context on my submission, so I am closing this one.  Thank you!
