### ISSUE TITLE
Life Savers Bold broken curly quotes 

### ISSUE THREAD

**Issue by jameswilson** [google/fonts#1849]
It appears that the curly single and double quotes are somehow using the mask of straight quotes, making them look very odd.  Have not tested this widely across browsers, but woff2 files on Chrome browser are affected.

<img width="753" alt="screen shot 2019-02-12 at 7 18 18 pm" src="https://user-images.githubusercontent.com/243532/52677221-1249b480-2efb-11e9-93b5-16d7674015cd.png">

^ Screenshot take from the following https://jsbin.com/neqerudere

I've noticed this issue does not affect the [Specimen page](https://fonts.google.com/specimen/Life+Savers)  but the [Directory page](https://fonts.google.com/?selection.family=Life+Savers:700&query=Life+Savers) is affected.  (It appears the specimen page doesn't load the font files the same way as the Directory page, so I can only presume that the original files are fine and this is an issue in the conversion to web formats?)

<img width="388" alt="screen shot 2019-02-12 at 7 25 33 pm" src="https://user-images.githubusercontent.com/243532/52677551-4ec9e000-2efc-11e9-9c0d-52dbe964a85f.png">

**Comment by jameswilson** [comment]
The letter "Đ" also seems to be affected. I copied/pasted the letters from the specimen page to the directory page, and got the following:

![life-savers](https://user-images.githubusercontent.com/243532/52677797-56d64f80-2efd-11e9-8637-9c99e20e1adb.gif)

**Comment by davelab6** [comment]
Still live, should be a quick fix, let's aim for Q2 :)

https://fonts.google.com/specimen/Life+Savers?preview.text=%E2%80%9Co%E2%80%9D

<img width="438" alt="Screenshot 2024-03-06 at 10 35 13 PM" src="https://github.com/google/fonts/assets/261579/e8a0246d-ff9f-47c8-ab4b-4e4bd2aada41">

**Comment by chrissimpkins** [comment]
assigned to @emmamarichal

**Comment by emmamarichal** [comment]
There is no repo, no sources for this font. We can create one on `googlefonts` and I can fix that with the binaries (I can't quickly generate a Glyphs file). @chrissimpkins or @davelab6, could you create a repo? thanks!
