### ISSUE TITLE
CrimsonPro VF settings fail validation

### ISSUE THREAD

**Issue by andyjgf** [google/fonts#1857]
Verification failure: {INVALID: /google_src/files/234871320/depot/branches/fonts_dev_branch/google3/third_party/googlefonts/api/ofl/crimsonpro/CrimsonPro-ExtraLightItalic.ttf[os2 weight class (275) != default weight axis position (200.0)]}
E0220 14:39:46.960650 1 main PushFileVerificationPushCommand.lambda$run$0:73 Verification failure: {INVALID: /google_src/files/234871320/depot/branches/fonts_dev_branch/google3/third_party/googlefonts/api/ofl/crimsonpro/CrimsonPro-ExtraLight.ttf[os2 weight class (275) != default weight axis position (200.0)]}

**Comment by m4rc1e** [comment]
Thanks!, I updated the axis wght range from 275-900 to 200-900. I forgot to update the os2 weightClass. I'll make an update now.

**Comment by m4rc1e** [comment]
It would be interesting to know what tests you folks have for VFs. We could then make sure we have these in Fontbakery so we don't waste your time.
