### ISSUE TITLE
Language configuration has no effect

### ISSUE THREAD

**Issue by andreasnylin** [google/fonts#1869]
I don't know if I'm missing something but when I customize the language settings for a font it doesn't seem to effect what languages are being loaded. If I only select Latin as language the CSS-file still imports all the other languages.

These embed urls all give the same response: 

https://fonts.googleapis.com/css?family=PT+Sans
https://fonts.googleapis.com/css?family=PT+Sans&amp;subset=latin-ext
https://fonts.googleapis.com/css?family=PT+Sans&amp;subset=cyrillic,cyrillic-ext,latin-ext

**Comment by m4rc1e** [comment]
See #1399
