### ISSUE TITLE
Question about font-display

### ISSUE THREAD

**Issue by Jdeboysere** [google/fonts#1871]
Hi there,

According to https://github.com/google/fonts/issues/358, the property "font-display" is not implemented by Google Fonts yet. Our client knows about Google PageSpeed and wants to optimize his website. My colleague ask me to add the property "font-display" (I am a Front-End Developer). 

But we are currently importing a Google Fonts using this way:

`<link id='googleapis-fonts-css'  href='https://fonts.googleapis.com/css family=Oxygen%3A300%2C400%2C700' type='text/css' media='all' />`

So, I can not add the property "font-display" because it is a `<link (...)>`. What is the solution?

Can I copy/pass the whole source code from https://fonts.googleapis.com/css?family=Oxygen%3A300%2C400%2C700 and paste it in my SASS/CSS, then remove the `<link id='googleapis-fonts-css'  href='https://fonts.googleapis.com/css family=Oxygen%3A300%2C400%2C700' type='text/css' media='all' />` from all my pages ? So, I will get something like this in my CSS :

```
@font-face {
  font-family: 'Oxygen';
  font-style: normal;
  font-weight: 300;
  src: local('Oxygen Light'), local('Oxygen-Light'), url(https://fonts.gstatic.com/s/oxygen/v8/2sDcZG1Wl4LcnbuCJW8zZmW5Kb8VZBHR.woff2) format('woff2');
  unicode-range: U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF;
  font-display: swap;
}
```

If I can not do that and if there is no solution, what can I say to our client ? Will the property "font-display" will be added to Google Fonts soon?

Best regards,
Jerome

**Comment by Jdeboysere** [comment]
I have to give a solution to my client as soon as possible. I am not an expert with the fonts. Can I have your opinion?

**Comment by davelab6** [comment]
It's a bad idea because what you copy is only one response our API serves; we respond differently to different browsers, and the responses link to different font files that are optimised for that browser/operating-system.

I suggest to tell your client pagespeed is not accurate for Google Fonts.

**Comment by Jdeboysere** [comment]
Thanks for your response.

I have maybe an other idea: can I download the fonts from Google Fonts and host them locally on the website? In this case, I can manually add `font-display`.

Is this idea better ?
