### ISSUE TITLE
Add Kufam, from Original Type

### ISSUE THREAD

**Issue by thundernixon** [google/fonts#1873]
MorcosKey is working on a bilingual Arabic + Latin typeface: https://morcoskey.com/home/kufam

UPDATE: This now has a repo at https://github.com/originaltype/kufam

**Comment by m4rc1e** [comment]
Family is now in production, https://fonts.google.com/specimen/Kufam?query=kufam

We need to fix #2637 though.

**Comment by yanone** [comment]
Manually linking PR: https://github.com/google/fonts/pull/2552
