### ISSUE TITLE
Gentium

### ISSUE THREAD

**Issue by odysseusjak** [google/fonts#1879]
Please update Gentium to the latest version.

**Comment by odysseusjak** [comment]
Anyone?

**Comment by odysseusjak** [comment]
Bueller? Bueller? Anyone?

**Comment by odysseusjak** [comment]
Seriously? Is no one going to even address this inquiry? Please update the Gentium font to the latest version.

**Comment by laerm0** [comment]
According to [the repo](https://github.com/silnrsi/font-gentium)'s readme, "This UFO-based font project is not yet ready for use or distribution," so there won't be any updates happening until it is ready.

**Comment by odysseusjak** [comment]
I don't think that's the right sight. Gentium's site is: https://software.sil.org/gentium/ The font has been out for some time now.

**Comment by laerm0** [comment]
Well, we would need the source to move forward, and that is SIL's repo for the font, so unless someone else is maintaining it, I'm afraid that's what we have to work with.

**Comment by odysseusjak** [comment]
Ah. Thanks for the clarification! Have a good weekend.

**Comment by laerm0** [comment]
No worries, you too. 😁
