### ISSUE TITLE
Archivo SemiBold has wrong font name

### ISSUE THREAD

**Issue by Gerry1135** [google/fonts#1880]
The Archivo-SemiBold.ttf file reports its name as "Archivo Medium".  This can be seen both in the control panel family view of Archivo, where there are two "Archivo Medium"s listed, and in the preview of the actual variantm the title bar shows Archivo SemiBold but the font name in the window shows as "Archivo Medium".  The italic version has the correct name internally of "Archivo SemiBold" and the family list shows "Archivo SemiBold Italic" as the name.

![image](https://user-images.githubusercontent.com/2339455/54351370-3f4acd80-4647-11e9-993b-4810a4d625e4.png)
The selected one is actually semibold.

![image](https://user-images.githubusercontent.com/2339455/54351404-525d9d80-4647-11e9-8594-da02f1000fd1.png)

**Comment by laerm0** [comment]
Fixed in v1.004.
