### ISSUE TITLE
Change Designer text for 'Kantumruy' and 'Kdam Thmor'

### ISSUE THREAD

**Issue by sovichet** [google/fonts#1882]
Hello. Could you help change the Designer text of my two typefaces 'Kantumruy' and 'Kdam Thmor' description to my foundry?

Url: https://anagata.design
Twitter: https://twitter.com/sovichet

Designer text:

Sovichet is a Cambodian self-taught typeface designer based in Phnom Penh, Cambodia. He runs his studio [Anagata](https://anagata.design) offering brand identity and custom font design services. He also talks and teaches Khmer typeface design inside and outside Cambodia. He is interested in Old Khmer and other Southeast Asian scripts.

**Comment by laerm0** [comment]
[fonts no longer offered by google]
