### ISSUE TITLE
Unicode character for ellipsis in Open Sans Semi-Bold 600 Italic is buggy

### ISSUE THREAD

**Issue by majorsic** [google/fonts#1884]
<img width="608" alt="Screen Shot 2019-03-16 at 12 15 57 PM" src="https://user-images.githubusercontent.com/40806107/54551125-0aa28300-4973-11e9-83b5-7d153d65d1dc.png">

The formatting of the Unicode character for ellipsis is acceptable in every Open Sans font configuration EXCEPT for Semi-Bold 600 Italic, where the three `.` appear smashed together.

**Comment by laerm0** [comment]
Thanks. There's a massive Open Sans update coming, so sit tight. 👍

**Comment by laerm0** [comment]
(this is fixed in the update btw)

**Comment by majorsic** [comment]
Thanks @laerm0! Looking forward to the update!
