### ISSUE TITLE
namecheck.fontdata.com insecure?

### ISSUE THREAD

**Issue by aubergine10** [google/fonts#1886]
When I click the namecheck.fontdata.com link in the main README file of the repo, I get this warning:

> ![font-check](https://user-images.githubusercontent.com/1386719/54572266-7ec64080-49de-11e9-9c0b-992f95a10ba3.png)

Entering the URL (namecheck.fontdata.com) direct in search bar seems to work fine.

**Comment by laerm0** [comment]
@graphicore Weren't you working on issues related to this?

**Comment by graphicore** [comment]
No, not working on it and not related.

Looks like the link should start with `https://` instead of `http://` i.e. `https://namecheck.fontdata.com/` but I don't know where the link is.

**Comment by graphicore** [comment]
Hmm `CONTRIBUTING.md` has a link to that service, but it looks OK.

**Comment by aubergine10** [comment]
I've just tried the link again and it's working fine now without any warnings.

**Comment by laerm0** [comment]
Great, thanks @aubergine10 :)
