### ISSUE TITLE
Broken / Misaligned accents on some texts (PT serif, Faricy New)

### ISSUE THREAD

**Issue by LubomirKurpel** [google/fonts#1906]
I have found out, that some of the fonts on my website does not render properly on some browsers. Accents are misaligned, slightly off it's normal position.

It looks like it works nicely in Chrome / Opera and is broken in Edge / Firefox.

Here is the image:

https://i.stack.imgur.com/0kObu.png

Website is running on Drupal 7 and fonts are from fonts.google.com with @include in CSS. I have no clue how to solve such a problem and tried to google but no-one seem to be having the same problems.

Also I found out that when I manually re-write the texts in inspector it magically works again.

**Comment by LubomirKurpel** [comment]
I actually found the solution. Our designer gave us design in Figma (online designing tool) and texts copied from this software were somehow broken. Not sure if it was encoding or what but hand-rewriting all the texts actually solved the problem.

**Comment by fitojb** [comment]
Yeah, Figma is probably [decomposing](https://stackoverflow.com/questions/28581054/unicode-composed-and-decomposed-forms) all the accented characters, following that ludicrous macOS practice. Please report the problem to them.
