### ISSUE TITLE
Playfair Display Rendering Issue, Possibly Due to Ligatures

### ISSUE THREAD

**Issue by brettalton** [google/fonts#1912]
Hi everyone,

I noticed Playfair Display having a rendering issue with the "ff" double character in Google Slides about a month ago.  I'm not sure who to report this to but I figured it's a good place to start.

Here is the issue in Google Slides,

![Screen Shot 2019-03-28 at 10 51 13 AM](https://user-images.githubusercontent.com/108411/55180860-ae481c00-5147-11e9-9302-8048b9010517.png)

The character word is supposed to say  "Zeff's" but instead displays as "Zeffk's".

I then noticed the same issue on another website just now and it appears like this,
 
![Screen Shot 2019-03-28 at 10 47 19 AM](https://user-images.githubusercontent.com/108411/55180904-c455dc80-5147-11e9-8c4a-0ecc8e0c3e8b.png)

The word here is "Identification" but instead displays as "IdentiŃcation" seeming to choke this time on "fi".

If I open Adobe Illustrator and test Playfair Display I notice the same issues with the "ff" and "fi" ligatures.

![Screen Shot 2019-03-28 at 10 59 16 AM](https://user-images.githubusercontent.com/108411/55181340-b94f7c00-5148-11e9-82c9-0ae908b77a32.png)

As I'm writing this, I'm realizing it might be a corrupt version of the font I downloaded from Google Fonts...

So I redownloaded them, removed them from Font Book and reinstalled, and there still appears to be an issue with the ligatures...

![Screen Shot 2019-03-28 at 11 05 05 AM](https://user-images.githubusercontent.com/108411/55181740-75a94200-5149-11e9-96ea-b194d7baf914.png)

Let me know if I need to contribute anything else to have this issue researched. I've attached a ZIP (1.3MB)  of the fonts as well in case you can check them for corruption.
[Playfair_Display.zip](https://github.com/google/fonts/files/3019591/Playfair_Display.zip)

**Comment by thlinard** [comment]
Hi,

You posted Playfair Display version 1.003. The [latest version is 1.2](https://github.com/google/fonts/tree/master/ofl/playfairdisplay).

I suggest you delete your local copy and test again.

**Comment by brettalton** [comment]
That's it. My greatest apologies. Thank you so much for your help.
