### ISSUE TITLE
Diferrences with google fonts API

### ISSUE THREAD

**Issue by zymlok** [google/fonts#192]
Hi, 
is there a way to download only fonts, which are on https://www.google.com/fonts? 
We have download all fonts from this repository, but for example Encode Sans are unrecognized on API...
In Architects Daughter cannot choose latin extended script.

So is there are way to get only fonts available in google fonts API?

**Comment by rsheeter** [comment]
https://developers.google.com/fonts/docs/developer_api?hl=en is probably what you want: "The Developer API gives access to the metadata available for all families served by Google Fonts. It allows the creation of dynamic apps by being able to query Google Fonts and get an accurate list of the families currently available."

**Comment by zymlok** [comment]
Sorry, but not. We project designs (which are next normated to html) in Indesign and we need have downloaded all fonts, but there is diferences betwen fonts on github with this available in API, so my question is: Is there any way to download only this fonts whose are available to use with API?
(example: Architects Daughter don't have extended scripts in API and Encode Sans isn't in API)

**Comment by rsheeter** [comment]
The developer API allows you to enumerate what is available for use with the API. You can use it to download the fonts that are currently available using the API.

**Comment by davelab6** [comment]
You can download the Developer API JSON and grep it for TTF URLs and then
use that set.

I'm working on a script in https://github.com/googlefonts/fontbakery -
fontbakery-metadata-vs-api.py - which will do this, download everything
from the developer api, and compare it to the git repo. I'll then bring
them into sync.

**Comment by zymlok** [comment]
ok, many thanks i download it ;)
