### ISSUE TITLE
Ubuntu: Add missing thin (100) weight

### ISSUE THREAD

**Issue by fitojb** [google/fonts#1922]
There is a new weight in the [Ubuntu family](https://fonts.google.com/specimen/ubuntu/); it should be noted it is upright-only, with no italic counterpart.

It is available [here](https://launchpad.net/ubuntu/+archive/primary/+files/fonts-ubuntu_0.83-4ubuntu1_all.deb) (extract the archive; inside `data.tar.xz` you’ll find `Ubuntu-Th.ttf`)

**Comment by sladen** [comment]
My understanding is, that:

1. at the moment the Ubuntu Thin weight is available for distribution solely under UFL-1.0
2. UFL-1.0 is no longer on the list of allowed licences for *new* family/weight uploads
3. uploading to Google Fonts would require either a reversal of policy, or a high-level exception
4. regardless of licence, the Thin is presently upright only, and was created with a smaller character set

For the record:

* `Created: Wed Aug 19 09:49:40 2015`
* `Modified: Fri Oct 16 11:46:13 2015`

**Comment by fitojb** [comment]
Ubuntu Thin has 1264 glyphs, which I wouldn’t call a “smaller character set”. Anyway, perhaps I should wait for @CanonicalLtd to release the 0.84 version of the family properly, because so far they’ve been a shitty overseer of the project (I already know the family was produced in 2015 because I was the one who announced in Planet Ubuntu ;) )

**Comment by sladen** [comment]
For the record, the Ubuntu Font family was produced in 2010.

Apologies that the oversight has been sub-optimal—feedback is welcomed.

The Ubuntu Font Family began at a time when libre/open source font production, source distribution and re-buildability from source were not well understood.  There have been benefits of being early, and there have been negative benefits from being early.

A decade later, we now have a situation where there is a huge free/libre/open source font industry; and you can got to a proprietary font design studio and order an free/libre/open source font *with source*, and *without* getting funny looks.  Overall this is a good thing; but it required learning steps to get there!
