### ISSUE TITLE
Red Hat Display / Text font submission

### ISSUE THREAD

**Issue by jeremymickel** [google/fonts#1927]
First submission of Red Hat fonts for inclusion on Google Fonts.
https://github.com/jeremymickel/RedHatFonts

These will ultimately be hosted at https://github.com/RedHatOfficial/RedHatFont.

**Comment by m4rc1e** [comment]
I've just prd the families:
https://github.com/google/fonts/pull/1930
https://github.com/google/fonts/pull/1931

The CI is busy running out test suite. We should have the results in an hour.

I'm closing to close this and report any issues I find to the relevant prs.

Thank you for your hard work on this family. It looks great.

**Comment by jeremymickel** [comment]
The source files are now available on the official repository:
https://github.com/RedHatOfficial/RedHatFont
