### ISSUE TITLE
Add Ukranian [і] and [ї] character support for [Quicksand] font

### ISSUE THREAD

**Issue by hyperpanthera** [google/fonts#1942]
Hello.

The Ukranian [і] and [ї] character is displayed as an empty box when [Quicksand] is used as font.

This one will probably have an issue too: [ґ].

**Comment by hyperpanthera** [comment]
@davelab6

**Comment by m4rc1e** [comment]
Quicksand doesn't have Cyrillic. We'd need to add this script first.

**Comment by hyperpanthera** [comment]
@m4rc1e Are you intending to add this?

Russian works perfectly, so as Ukrainian except those characters that I mentioned.

**Comment by m4rc1e** [comment]
There are no Cyrillic characters in this font. What you're seeing is the fallback font.

**Comment by hyperpanthera** [comment]
@m4rc1e Is the fallback font defined in the [Quicksand] font? If so, would it be possible to change the fallback font that supports all Cyrillic characters?

**Comment by fitojb** [comment]
Fallback lists, when not defined by CSS rules, are locally defined by either your browser (e.g. Firefox) or components such as _fontconfig_ (in e.g. Linux) or the Registry (Windows). By definition, a _fallback list_ is a list of fonts; fonts themselves do not define other fonts to use.

**Comment by hyperpanthera** [comment]
@fitojb Thanks so much!
