### ISSUE TITLE
Font weights installing as separate font weights

### ISSUE THREAD

**Issue by mcmillyonaire** [google/fonts#1948]
All font weights are installing as separate font families. macOS 10.14.4. 

<img width="203" alt="Screen Shot 2019-04-19 at 12 30 23 PM" src="https://user-images.githubusercontent.com/1663588/56433479-fe298700-629e-11e9-9cd1-d9a7460b9285.png">

**Comment by mcmillyonaire** [comment]
Update: the issue appears to be isolated to downloading the fonts from fonts.google.com or using Skyfonts.

**Comment by laerm0** [comment]
Confirmed fixed via #2008
