### ISSUE TITLE
Update Chivo

### ISSUE THREAD

**Issue by davelab6** [google/fonts#195]
There are additional styles available on the @omnibus-type website, and at https://github.com/Omnibus-Type/Chivo

**Comment by m4rc1e** [comment]
Closing, new styles were added recently:

![screen shot 2017-06-15 at 12 36 14](https://user-images.githubusercontent.com/7525512/27179625-50842130-51c7-11e7-8c5c-e62c6c017c7a.png)


New styles were included in #514
