### ISSUE TITLE
Mada font for IE11 may be corrupted woff file

### ISSUE THREAD

**Issue by jpunith** [google/fonts#1964]
I am using the link [https://fonts.googleapis.com/css?family=Mada:400,500](https://fonts.googleapis.com/css?family=Mada:400,500|Scheherazade:bold) for the font. it is giving me this CSS file in IE11

`@font-face {
  font-family: 'Mada';
  font-style: normal;
  font-weight: 400;
  src: local('Mada Regular'), local('Mada-Regular'), url(https://fonts.gstatic.com/s/mada/v7/7Auwp_0qnzeSfTLGKw.woff) format('woff');
}

@font-face {
  font-family: 'Mada';
  font-style: normal;
  font-weight: 500;
  src: local('Mada Medium'), local('Mada-Medium'), url(https://fonts.gstatic.com/s/mada/v7/7Au_p_0qnzeSdcHlOCX2yQ.woff) format('woff');
}`

Both the woff files are successfully getting downloaded but fonts are not getting applied and there are no error. The same CSS I copy pasted into the Chrome its not working there also

**Comment by nathan-williams** [comment]
Hi jpunith. Just tested this out at https://codepen.io/nlwilliams/pen/GagxGb and everything seems to be working.

**Comment by jpunith** [comment]
@nathan-williams thanks for the update. My issue was with Arabic fonts when add `subset:arabic` in the URL [https://fonts.googleapis.com/css?family=Mada:400,500&amp;subset=arabic](https://fonts.googleapis.com/css?family=Mada:400,500&amp;subset=arabic) it fixed the issue.
