### ISSUE TITLE
Support font-display on Fonts API

### ISSUE THREAD

**Issue by Antonio-Laguna** [google/fonts#1986]
As per https://github.com/google/fonts/issues/358 being finished recently 🎊 ! I went to update a PostCSS plugin, that includes Google Fonts when you use them, to add a feature to be able to use `font-display`. The plugin is using Font's API to download a list of them but upon inspecting the API I don't see any way to retrieve font-display information/files.

Is there a parameter I'm missing?

**Comment by Panamus** [comment]
This afaik hasn't been shipped yet, so adding the query parameter will not have any effect yet. We're still stuck self-hosting google fonts for now. I have yet to find an ETA.

**Comment by Antonio-Laguna** [comment]
Pinging @thlinard @m4rc1e and @andyjgf . Cool to take this to any other place it might be more appropriate but can't find any other place to report/ask this.

**Comment by Antonio-Laguna** [comment]
It's been well over a month now and no comment whatsoever which leads me to think this might be in the wrong place?

**Comment by Androbin** [comment]
According to https://bugs.chromium.org/p/chromium/issues/detail?id=777846#c10, this feature should be available now.

**Comment by Antonio-Laguna** [comment]
@Androbin that's great news but it didn't make to the API yet:

```
{
      "kind": "webfonts#webfont",
      "family": "Roboto",
      "category": "sans-serif",
      "variants": [
        "100",
        "100italic",
        "300",
        "300italic",
        "regular",
        "italic",
        "500",
        "500italic",
        "700",
        "700italic",
        "900",
        "900italic"
      ],
      "subsets": [
        "cyrillic-ext",
        "greek-ext",
        "greek",
        "latin",
        "latin-ext",
        "cyrillic",
        "vietnamese"
      ],
      "version": "v20",
      "lastModified": "2019-07-24",
      "files": {
        "100": "http://fonts.gstatic.com/s/roboto/v20/KFOkCnqEu92Fr1MmgWxPKTM1K9nz.ttf",
        "100italic": "http://fonts.gstatic.com/s/roboto/v20/KFOiCnqEu92Fr1Mu51QrIzcXLsnzjYk.ttf",
        "300": "http://fonts.gstatic.com/s/roboto/v20/KFOlCnqEu92Fr1MmSU5vAx05IsDqlA.ttf",
        "300italic": "http://fonts.gstatic.com/s/roboto/v20/KFOjCnqEu92Fr1Mu51TjARc9AMX6lJBP.ttf",
        "regular": "http://fonts.gstatic.com/s/roboto/v20/KFOmCnqEu92Fr1Me5WZLCzYlKw.ttf",
        "italic": "http://fonts.gstatic.com/s/roboto/v20/KFOkCnqEu92Fr1Mu52xPKTM1K9nz.ttf",
        "500": "http://fonts.gstatic.com/s/roboto/v20/KFOlCnqEu92Fr1MmEU9vAx05IsDqlA.ttf",
        "500italic": "http://fonts.gstatic.com/s/roboto/v20/KFOjCnqEu92Fr1Mu51S7ABc9AMX6lJBP.ttf",
        "700": "http://fonts.gstatic.com/s/roboto/v20/KFOlCnqEu92Fr1MmWUlvAx05IsDqlA.ttf",
        "700italic": "http://fonts.gstatic.com/s/roboto/v20/KFOjCnqEu92Fr1Mu51TzBhc9AMX6lJBP.ttf",
        "900": "http://fonts.gstatic.com/s/roboto/v20/KFOlCnqEu92Fr1MmYUtvAx05IsDqlA.ttf",
        "900italic": "http://fonts.gstatic.com/s/roboto/v20/KFOjCnqEu92Fr1Mu51TLBBc9AMX6lJBP.ttf"
      }
    },
```

**Comment by rsheeter** [comment]
I'm a bit confused what you are looking for. `font-display` is used for our CSS API, it doesn't seem to apply here. Could you elaborate a little on what you are trying to do?

**Comment by Antonio-Laguna** [comment]
I guess I might be confused by thinking there would be a different file but not sure how I thought that since that doesn't make much sense. :/ 

Closing this then and apologies for any overhead.
