### ISSUE TITLE
Add Darker Grotesque

### ISSUE THREAD

**Issue by davelab6** [google/fonts#1996]
https://github.com/bettergui/DarkerGrotesque

**Comment by bettergui** [comment]
Hi,
I'm happy to say that we have completed all the steps (tests, hinting, etc.) in https://github.com/google/fonts/blob/master/CONTRIBUTING.md ! We also included the Glyph source file in the repo.

FontBakery all passed for the whole family:
```

                           ,@.
                         ,@.@@,.
                   ,@@,.@@@.  @.@@@,.
                 ,@@. @@@.     @@. @@,.
         ,@@@.@,.@.              @.  @@@@,.@.@@,.
    ,@@.@.     @@.@@.            @,.    .@’ @’  @@,
  ,@@. @.          .@@.@@@.  @@’                  @,
 ,@.  @@.                                          @,
 @.     @,@@,.     ,                             .@@,
 @,.       .@,@@,.         .@@,.  ,       .@@,  @, @,
 @.                             .@. @ @@,.    ,      @
  @,.@@.     @,.      @@,.      @.           @,.    @’
   @@||@,.  @’@,.       @@,.  @@ @,.        @’@@,  @’
      \\@@@@’  @,.      @’@@@@’   @@,.   @@@’ //@@@’
       |||||||| @@,.  @@’ |||||||  |@@@|@||  ||
        \\\\\\\  ||@@@||  |||||||  |||||||  //
         |||||||  ||||||  ||||||   ||||||  ||
          \\\\\\  ||||||  ||||||  ||||||  //
           ||||||  |||||  |||||   |||||  ||
            \\\\\  |||||  |||||  |||||  //
             |||||  ||||  |||||  ||||  ||
              \\\\  ||||  ||||  ||||  //
               ||||||||||||||||||||||||

         No check is failing. Get a cupcake!
       <<Art by Tony de Marco, July 26, 2018>>


```

What can we do next to make this available for all Vietnamese designers and the world via Google Fonts?

I tried following the steps in https://github.com/googlefonts/gf-docs/tree/master/MakingPullRequestsToGF but didn't get the permission to do so, I guess this can only be done by Google Fonts' contributors.

Cheers,
Vietanh

**Comment by bettergui** [comment]
Thank everyone for the supports. The Vietnam type community really appreciates this, we hope to have more type projects done by Vietnamese on Google Fonts in the future.

**Comment by bettergui** [comment]
Feel free to close this, Dave.

**Comment by m4rc1e** [comment]
Was released a few weeks back, https://fonts.google.com/specimen/Darker+Grotesque
