### ISSUE TITLE
please add shabnam

### ISSUE THREAD

**Issue by alitalebiuix** [google/fonts#1997]
hi
we have problem with persian/arabic font in google doc and ... there are not any persian standard font in google fonts.
https://github.com/rastikerdar/shabnam-font
https://github.com/rastikerdar/vazir-font
@davelab6 @m4rc1e

**Comment by m4rc1e** [comment]
Vazir has a bit stream license. I don't think we'll be able to host it.

**Comment by alitalebiuix** [comment]
give me a solution to add these two fonts in google fonts please. is there any way? 🙄

**Comment by fitojb** [comment]
Why don’t you self-host?

**Comment by alitalebiuix** [comment]
how? can we use it in apps like google docs? @fitojb

**Comment by davelab6** [comment]
https://github.com/rastikerdar/vazir-font seems good to go

**Comment by amir2mi** [comment]
Hi @m4rc1e, Google font currently does not have any appropriate typeface for Arabic and Persian though they have a lot of users.
@rastikerdar has created high-quality typefaces and they will improve that problem.

So what is the solution for this "stream license"?

**Comment by a5hk** [comment]
@amir2mi, The license has been changed to [OFL](https://github.com/rastikerdar/vazir-font/blob/master/OFL.txt)

**Comment by davelab6** [comment]
Sadly the license can not be changed without removing the 3rd party parts like the dejavu project data, which is where the original license was correctly added. Changing the license on the original parts needs confirmation from every contributor, too. 

So, this is a bit messy and unusual and we will eventually add it but we will prioritize other more straightforward projects.

**Comment by yanone** [comment]
Closing this. Vazir has been onboarded and will be published as Vazirmatn. And the author said that he won't have time to work on Shabnam.
