### ISSUE TITLE
Barcode 39 without text not working

### ISSUE THREAD

**Issue by zealousappex** [google/fonts#2001]
I'm not able to get Barcode 39 without text to work, is this a issue see here:
https://www.w3schools.com/code/tryit.asp?filename=G4J9Y1J95MRR

**Comment by m4rc1e** [comment]
Your example had a non ascii char which stopped the css style from being aprsed.

Here's a cleanup of your example: https://www.w3schools.com/code/tryit.asp?filename=G4KZV5HV33O0
