### ISSUE TITLE
Add Kinto

### ISSUE THREAD

**Issue by laerm0** [google/fonts#2003]
https://github.com/ookamiinc/kinto

It's an improvement to Noto's Japanese and on OFL.

> Kinto [...], a Japanese font family adapted from the typeface itself to match size & balance with made for screen & UI Latin typefaces. Japanese glyphs in this font family has been simply scaled down with its baseline adjusted to align with other glyphs in the family. By process, it is precisely scaled down by 4.4% (100% → 95.6%) to mimick the way Japanese text is rendered on iOS as System Font. Thus, this typeface comes in handy when designing Japanese interfaces for iOS.

**Comment by chrissimpkins** [comment]
Consider upstreaming?

**Comment by davelab6** [comment]
Looks like that doesn't make sense so let's proceed

**Comment by davelab6** [comment]
I think this is too niche.
