### ISSUE TITLE
Add Gayathri

### ISSUE THREAD

**Issue by santhoshtr** [google/fonts#2005]
Add Gayathri - A Malayalam display typeface available in three style variants. 

https://gitlab.com/smc/fonts/gayathri

All fontbakery tests are passing since fontbakery is part of CI for this font..

(Mirror: http://github.com/smc/gayathri)

**Comment by m4rc1e** [comment]
Thanks @santhoshtr!

#2016. We aim to get these and Manjari out. I apologise for the delay.
