### ISSUE TITLE
API / fonts.google.com omitting name table data/breaking up families

### ISSUE THREAD

**Issue by bignell** [google/fonts#2008]
See also #1998, #1948

Fonts being served from the API and web interface appear to be missing name IDs 16 and 17, the Typographic (formerly "Preferred") Family and Subfamily fields.

![name-tables](https://user-images.githubusercontent.com/106692/58996160-e0ab7080-87ab-11e9-83b4-0f63d3f8d111.png)

It fails silently in a browser because CSS handles the font naming, and the effect is unnoticeable in fonts with four styles or fewer because the fallback name IDs (1 and 2) can handle that level of variation.

Families of more than four styles that lack this metadata have no common family name and are broken up in chunks.

<img width="815" alt="plex" src="https://user-images.githubusercontent.com/106692/58997235-8b259280-87b0-11e9-83c3-fe40a351ec4c.png">

I suspect it has something to do with the FontBakery build process, but I have run out of detective mojo and require further assistance.

**Comment by m4rc1e** [comment]
NameIDs 16 and 17 are not needed for fonts which are "Regular, "Bold", "Italic", "Bold Italic". This issue seems to be happening for users of a particular OS X build. What version are you using?

**Comment by thlinard** [comment]
@m4rc1e I think the problem arises because the usual users think the best place to download Google Fonts for desktop use is https://fonts.google.com/

And when you download the fonts from https://fonts.google.com/, they don't have nameID 16 and 17 (unlike the fonts download from https://github.com/google/fonts/). Perhaps something to communicate?

**Comment by floorish** [comment]
I develop an app that uses the Developer API to get Google Fonts. How would you suggest it should download the correct - for desktop use - fonts? Is there some way to map the files list inside the response json to the correct files from the git repo?

**Comment by bignell** [comment]
@m4rc1e 159 of the 916 font families in the Google Fonts library—including all of the 10 most popular—have more than four styles. The 11th most popular (Roboto Slab) only has four styles, but since they are not "regular, italic, bold, bold italic", the way it uses NameIDs 1 and 2 is actually incorrect as well.

The spec ["strongly recommends"](https://docs.microsoft.com/en-us/typography/opentype/spec/name#nid1) the use of NameIDs 16 and 17 for families that include more than the basic four styles (the constraints of NameIDs 1 and 2 are why they added 16 and 17 to the spec [in 1998](https://docs.microsoft.com/en-us/typography/opentype/spec/changes#1.1)).

The additional metadata doesn't add any benefit for font families with only the basic four styles, but larger families cannot be grouped correctly without it. Is there any reason not to include it? If the argument is that the API is for web usage, then why not omit the name table entirely—[browsers don't use it anyway](https://drafts.csswg.org/css-fonts-3/#font-family-desc).

--

I'm using macOS 10.14.5, but this should be irrelevant for the reasons described above.

**Comment by m4rc1e** [comment]
Just tested Montserrat, it seems to have been fixed.

<img width="999" alt="Screenshot 2019-08-22 at 18 33 18" src="https://user-images.githubusercontent.com/7525512/63536369-5ef5f400-c50b-11e9-8166-1511e3d1ac74.png">


@bignell can you confirm the issue has been fixed? Is so I'll close this issue.

**Comment by khaledhosny** [comment]
FontTools subsetter used by Google Fonts removes most name table entries as they are not needed for web fonts.

It seems that some of the reporters here have web apps that use the fonts through the API (probably I use case that was not considered before) and the missing font names are breaking things for them.

**Comment by bignell** [comment]
@m4rc1e Yes, confirmed fixed! Thank you, well done!
