### ISSUE TITLE
Add the italics variants to Source Serif

### ISSUE THREAD

**Issue by apcamargo** [google/fonts#2018]
[Italics were added to Source Serif in August 2018](https://blog.typekit.com/2018/08/16/source-serif-italics/), but they aren't available in Google Fonts.

**Comment by fitojb** [comment]
This is already [reported](#23 ) and tracked. Please search for existing reports before creating new ones. Thanks.

**Comment by apcamargo** [comment]
I did search for Source Serif-related issues but I didn't include closed bugs in my query. I'll close this issue.
