### ISSUE TITLE
Crimson Text printing bug in D and S

### ISSUE THREAD

**Issue by davelab6** [google/fonts#2043]
> I have issues with Crimson Text in printing with @AmazonKDP Someone here has it too https://www.kdpcommunity.com/s/question/0D5f400001VZ1BWCA1/missing-letter-d-in-print-copy?language=en_US
> 
> some letters specially D and S in italic. 
> 
> I spent the whole night with the author trying to fix this and I ended up changing the whole font.

- https://twitter.com/IslamSFarid/status/1141833344092704768

**Comment by emmamarichal** [comment]
Fixed #4416
