### ISSUE TITLE
I cannot open Google Fonts webpage

### ISSUE THREAD

**Issue by SMLVG** [google/fonts#2055]
I'm on Firefox, version 67.0.4 (64-bit) and I'm trying to go Google Fonts, but, just look at the screenshots. I've got an error who is:
`
Content Security Policy: Los ajustes de la página observaron la carga de un recurso en eval ("script-src"). Se está enviando un informe CSP.
m=core line 38 > eval:255:431
Error: "u"
    f https://www.gstatic.com/_/fonts/_/js/k=fonts.app.en_US.uFXBTZCAcU4.O/d=1/rs=AE60u5drX19JH_5B_Em9uKnTfiqli0uafA/m=core:260
    Angular 3
        I
        e
        F
 Possibly unhandled rejection: {} java/com/google/fonts/directory/ui/angular_js.js:137:246
    Angular 2
    b https://www.gstatic.com/_/fonts/_/js/k=fonts.app.en_US.uFXBTZCAcU4.O/d=1/rs=AE60u5drX19JH_5B_Em9uKnTfiqli0uafA/m=core:397
    Angular `

It's in spanish but Google Translator does its work ¯\_(ツ)_/¯

And, here's the screenshot!
![imagen](https://user-images.githubusercontent.com/46191980/60683190-c510b400-9e96-11e9-8ac3-47918a11144a.png)
![imagen](https://user-images.githubusercontent.com/46191980/60683199-cf32b280-9e96-11e9-8bf9-cd4c735af3b7.png)

**Comment by dragonmenorka** [comment]
This happened from I uninstalled Chrome of my device, but I was used Firefox before too so...

**Comment by coliff** [comment]
I see those errors in the console (with Firefox 67.0.4) too, though the site is loading fine  -maybe try again now.

![image](https://user-images.githubusercontent.com/1212885/60702549-2dfd3800-9f3a-11e9-9a8d-a03249df92b1.png)

**Comment by dragonmenorka** [comment]
It keeps without working
(sorry, but i didnt use github those days)

**Comment by coliff** [comment]
is it just Firefox that doesn't work for you? Have you tried Edge - or even IE11 on your computer?

**Comment by dragonmenorka** [comment]
I have tried it on Edge and IE. Same error. When I'd un installed Chrome,
it appears by first time.

**Comment by dragonmenorka** [comment]
Appeard*

**Comment by SMLVG** [comment]
Old issue. I'm using Chrome now.

**Comment by dragonDScript** [comment]
Bruh this is a really old issue. It works now in my Linux computer (and in Windows after a firefox update).
Thanks @coliff
