### ISSUE TITLE
Add Bluu Next

### ISSUE THREAD

**Issue by eliheuer** [google/fonts#2081]
https://velvetyne.fr/fonts/bluu/

**Comment by yanone** [comment]
https://github.com/velvetyne/BluuNext

**Comment by eliheuer** [comment]
I started a variable font fork here: https://github.com/eliheuer/bluu-next-vf

**Comment by RosaWagner** [comment]
I close this issue according to the conclusion brought here : https://github.com/google/fonts/pull/2545

**Comment by davelab6** [comment]
Thanks @eliheuer and @RosaWagner
