### ISSUE TITLE
Opening guillemet character is wrong in Trocchi

### ISSUE THREAD

**Issue by jblouvet** [google/fonts#21]
As you can see in the screenshot, the opening guillement in Trocchi is replaced by the closing guillemet. This is a major flow in french, where these two characters are used for quoting.

![trocchi](https://cloud.githubusercontent.com/assets/1478820/7365389/25925aac-ed90-11e4-987f-4c83a5c96591.png)

Thanks for the great work !

**Comment by m4rc1e** [comment]
Hey,

This should now be fixed.

![screen shot 2016-09-02 at 15 16 15](https://cloud.githubusercontent.com/assets/7525512/18205900/aec60d0a-7124-11e6-93a1-35ca1fecf639.png)

Forked [Repo](https://github.com/m4rc1e/Trocchi) here. Official upload will happen soon.

Cheers,
Marc

**Comment by m4rc1e** [comment]
Closing, LGTM.

![screen shot 2017-06-15 at 12 08 47](https://user-images.githubusercontent.com/7525512/27178753-6a9fb04c-51c3-11e7-8ce7-cd54d935555e.png)

http://jsbin.com/bileqojama/edit?html,output
