### ISSUE TITLE
Add option to disregard local version of font - always download

### ISSUE THREAD

**Issue by mat-b-** [google/fonts#210]
There are fonts which have proper latin-extended support (like Raleway) for Polish language, but the version shipped with Mac OS does not.

It would be great if there was a parameter that would make Google Fonts always download (and cache) it's own version, instead of relying on possibly broken local version.

**Comment by davelab6** [comment]
> the version shipped with Mac OS 

What version is shipped with Mac OS?

If users install a font, they are responsible for keeping it up to date.
