### ISSUE TITLE
Nunito Cyrillic

### ISSUE THREAD

**Issue by jbrooksuk** [google/fonts#2102]
The Nunito font has support for Cyrillic characters, but the Google Fonts version does not. Can this be updated?

**Comment by 4n70w4** [comment]
https://github.com/googlefonts/nunito/pull/16

**Comment by davelab6** [comment]
@m4rc1e, I chatted with @fonthausen and he said,

> Work process was as follow at the time: I completely redrew Nunito Sans Roman. Including the Cyrillic, which weren’t up to par in the first place. From Nunito Sans Roman we made the Slanted and rounded. I added an xHeight axis which was used to recreate Mulish together with the Width axis. Barbara took those file and made sure they fitted the original Mulish.
>
> Nunito, Nunito Sans and Mulish should have Cyrillic.

**Comment by yanone** [comment]
I've been asked to add the Cyrillic to Nunito, Nunito Sans, and Mulish to the static fonts in a first step before looking into upgrading them all to VFs.

The Nunito & Nunito Sans sources (in the master branches) contain Cyrillic indeed, but not Mulish.
@Fonthausen Can you elaborate where I can find them? Thanks.

**Comment by Fonthausen** [comment]
https://github.com/Fonthausen/NunitoSans/tree/ComponentTest/10%20Sources

**Comment by Fonthausen** [comment]
Here you will find all latest sources. Nunito, Nunito Sans and Muli. All contain Cyrillic.

**Comment by yanone** [comment]
Oh, I get it now, thanks.

**Comment by Fonthausen** [comment]
Feel free to DM me if you have questions. Files contain a lot of masters to counteract against the distortion that would have occurred at the corners of the design space.
