### ISSUE TITLE
Add Be Vietnam family

### ISSUE THREAD

**Issue by bettergui** [google/fonts#2104]
https://github.com/bettergui/BeVietnam

This is our second type project, the previous project Darker Grotesque was accepted and [merged](https://github.com/google/fonts/pull/2033).

**Comment by bettergui** [comment]
@davelab6 
Would the next batch of types be published soon to the Google Fonts site?

**Comment by bettergui** [comment]
The font was merged: https://github.com/google/fonts/pull/2105

**Comment by m4rc1e** [comment]
Family is now live, https://fonts.google.com/specimen/Be+Vietnam

Thank you.
