### ISSUE TITLE
Can't fork the sfd file for Inconsolata

### ISSUE THREAD

**Issue by Gutza** [google/fonts#211]
I actually added a few glyphs (no big deal, just combined a few base glyphs for some accented Romanian letters), but there's no way I can see to fork, update and send back a pull request for the sfd file. Is this kind of collaboration something you would consider?

[Inconsolata-Gutza.zip](https://github.com/google/fonts/files/128513/Inconsolata-Gutza.zip)

**Comment by adrientetar** [comment]
cc @raphlinus

**Comment by davelab6** [comment]
@Gutza Thanks for this! @alexeiva developed the bold style, and Inconsolata might be a good candidate for a 3 week improvement sprint later this year. However, the sources will likely migrate from SFD to .glyphs, which can be converted to ufo with http://github.com/googlei18n/fontmake

**Comment by alexeiva** [comment]
@Gutza @davelab6 I just added the Glyphs source file for Bold here: https://github.com/cyrealtype/Inconsolata-Bold/tree/master/src

**Comment by raphlinus** [comment]
If we improve the font, I'd love to see the changes I've made for InconsolataGo (see http://levien.com/type/myfonts/inconsolata/). Also, there are requests for missing glyphs, certainly at least u+2014). I myself am a little fuzzy about the process for pushing improvements, but would like to see this move forward.

**Comment by insanetesterftw** [comment]
Isn't it sad that you are making developing freely licensed typefaces/fonts dependent on a file format from a single platform, closed source, proprietary, very expensive application, based on an even more closed source, proprietary and even more expensive platform?

The barrier to contribute to font development is high enough as it is.

**Comment by davelab6** [comment]
The format will be supported by trufont and metapolator soon enough. If you
have software development skills and want to contribute to liberating
typography I recommend joining the trufont and or metapolator projects :)

**Comment by graphicore** [comment]
> The format will be supported by trufont and metapolator soon enough.

We'll need glyphsLib.js
