### ISSUE TITLE
Noto Georgian update Mtavruli issue

### ISSUE THREAD

**Issue by asukiasov** [google/fonts#2114]
Hello!

 Unicode Consortium has added Georgian Mtavruli. 
https://unicode.org/L2/L2016/16034-n4707-georgian.pdf

Would be great, if we could add Mtavruli to Noto Georgian. I am font designer and can help with that.

**Comment by fitojb** [comment]
This is turf for [googlefonts/noto-fonts](https://github.com/googlefonts/noto-fonts/issues), not this repository :)

**Comment by simoncozens** [comment]
Mtavruli support has been added to the latest builds of Noto Sans and Serif Georgian, and these are going through the pipeline of being added to fonts.google.com now!

**Comment by asukiasov** [comment]
Wow! Super! Thanks!
