### ISSUE TITLE
add Mansalva

### ISSUE THREAD

**Issue by carolinashort** [google/fonts#2115]
Handwritten font that can be use for notes and informal text
https://github.com/carolinashort/mansalva

**Comment by m4rc1e** [comment]
Thanks for the request.

I Just sent you QA report, https://github.com/carolinashort/mansalva/issues/1

**Comment by m4rc1e** [comment]
Family is now live, https://fonts.google.com/specimen/Mansalva

Thank you.

**Comment by carolinashort** [comment]
Thank you Marc!

There is a small typo in the description, nothing serious but just asking
if there is a way to fix it. It says "Mansalve" at the beginning.

Cheers,
Carolina

· — · — · — ·
Carolina Short <carolina.short@waikato.ac.nz>
Senior Tutor
Department of Computer Science |  Faculty of Computing and Mathematical
Sciences
University of Waikato

**Comment by m4rc1e** [comment]
Thanks. Fixed in https://github.com/google/fonts/pull/2185

**Comment by carolinashort** [comment]
Thanks Marc!

- · - · - · - · - · - · - · -
Carolina Short
Senior Tutor
Department of Computer Science |  Faculty of Computing and Mathematical Sciences
University of Waikato
