### ISSUE TITLE
Kerning too loose for I-c pair

### ISSUE THREAD

**Issue by dtwist** [google/fonts#2121]
(I reported this [bug directly in the Pacifico repo](https://github.com/googlefonts/Pacifico/issues/5), but haven't gotten a response in 18 days, hoping this is a better repo for posting bugs)

I was trying Pacifico for a new client that sells ice cream. Found that kerning is off for the capital "I" and lowercase "c" in Google's hosted version of Pacifica.
image
![image](https://user-images.githubusercontent.com/957686/62994095-0ccc1900-be0f-11e9-8424-33cdea3f33d7.png)

I tested and confirmed this behavior in latest versions of FF, Safari and Chrome on Mac; Edge 18, FF and Chrome on Windows; Safari and Chrome on IOS 11 & 12; Chrome and FF on Android 7, 8 and 9.

Edge 17 and IE 11 are the only browsers that show tighter kerning.

Kerning for capital "I" and lowercase "e" are also off. Not really an issue for English, but I don't know if other languages have words with that letter pair.

**Comment by m4rc1e** [comment]
Thanks for reporting this.

I've just made a fix in the upstream repo and submitted #2127. I'll push to get this online asap.

I simply removed the kern which has produced a much better result.

<img width="527" alt="Screenshot 2019-08-19 at 11 21 19" src="https://user-images.githubusercontent.com/7525512/63258238-8894ee00-c273-11e9-8ddd-02f2ecb75e69.png">

**Comment by dtwist** [comment]
Hi Marc,

Thanks for the quick fix. This is definitely better!

I think a more careful kerning could be useful though too. In this case, "Ic" could be a bit tighter, and some of the other pairs with accented characters [here](https://github.com/google/fonts/pull/2127#issuecomment-522527380) look a bit too tight without explicit kerns.

**Comment by davelab6** [comment]
@dtwist thanks for reporting this. @fonthausen note that this fell through the cracks :)

**Comment by bshakespear-arch** [comment]
you can get  icecraem

**Comment by tluch001-dev** [comment]
Is this I-ready

**Comment by tluch001-dev** [comment]
.....
