### ISSUE TITLE
Add Vibes

### ISSUE THREAD

**Issue by bluemix** [google/fonts#2124]
Hello dear,
I hope to include this typeface, that supports Arabic and English

https://github.com/bluemix/vibes-typeface

**Comment by m4rc1e** [comment]
Thank you for your submission and following our guidelines. The fonts have been engineered to a high standard.

Imo the design work could be improved. The spacing and letterforms seem a bit off to me. I will consult our designers to see what they think.

<img width="465" alt="Screenshot 2019-08-21 at 11 42 37" src="https://user-images.githubusercontent.com/7525512/63425783-42719300-c409-11e9-803f-f77493ae91a1.png">

<img width="948" alt="Screenshot 2019-08-21 at 11 43 47" src="https://user-images.githubusercontent.com/7525512/63425792-469db080-c409-11e9-885d-8664879070df.png">

**Comment by bluemix** [comment]
okay @m4rc1e ,
I'll wait

**Comment by m4rc1e** [comment]
We've decided to accept this submission.

**Comment by bluemix** [comment]
thank you very much 🙏🏼

**Comment by bluemix** [comment]
I am wondering if it is possible to publish updates on the typeface after submission; is it possible?

**Comment by m4rc1e** [comment]
Yes, that will be possible.

**Comment by m4rc1e** [comment]
Vibes is now live, https://fonts.google.com/specimen/Vibes

Thank you.
