### ISSUE TITLE
Incomplete Literata

### ISSUE THREAD

**Issue by alexeyten** [google/fonts#2130]
There is only regular weight fonts in this repo, but [release v2.201](https://github.com/googlefonts/literata/releases/tag/v2.201) contains other weights.

**Comment by m4rc1e** [comment]
Most likely related to #2125

**Comment by alexeyten** [comment]
I'm not sure how it's related. There is only two font files in https://github.com/google/fonts/tree/master/ofl/literata while release archive contains 8 files.

**Comment by m4rc1e** [comment]
Apologies, the fonts in that directory are variable fonts. Each font contains four styles.

**Comment by alexeyten** [comment]
Oh, ok.
Makes sense now.
