### ISSUE TITLE
Rendering issue for Malayalam in fonts.google.com preview

### ISSUE THREAD

**Issue by santhoshtr** [google/fonts#2131]
Test string: "പോ"
Rendering: 
![image](https://user-images.githubusercontent.com/161672/63571682-cc8c3980-c578-11e9-84c6-0d5484f23e86.png)

Once you move your cursor to individual fonts, immediately that font's rendering get corrected.
Expected rendering:
![image](https://user-images.githubusercontent.com/161672/63571746-06f5d680-c579-11e9-9a9c-c9c8fbd49055.png)

This is not a font issue, as they are working fine elsewhere(Even in google fonts- but need some pointer moving tricks)

**Comment by asdofindia** [comment]
Can reproduce in Chromium Version 76.0.3809.100 (Official Build) Arch Linux (64-bit) and Mozilla Firefox 68.0.2 (for Arch Linux) and Firefox for Android 68.0.2

**Comment by jeffjose** [comment]
Similarly broken on gLinux + 76.0.3809.132 (Official Build) (64-bit)

**Comment by santhoshtr** [comment]
No longer happens
