### ISSUE TITLE
Add a .github folder with templates for issues and pull requests

### ISSUE THREAD

**Issue by davelab6** [google/fonts#214]
The https://github.com/dear-github/dear-github letter has a practical response in https://github.com/blog/2111-issue-and-pull-request-templates

We should add a .github folder with templates for
- [ ] issues and 
- [ ] pull requests

I think it is good to leave the CONTRIBUTING.md file in the root so it is more visible.

**Comment by rsheeter** [comment]
Template sounds cool. Definitely leave CONTRIBUTING.md in root; pretty sure we are actually required to do that.

**Comment by michaelmior** [comment]
> You can put CONTRIBUTING.md, ISSUE_TEMPLATE.md, and PULL_REQUEST_TEMPLATE.md files in .github/ and everything will work as expected.
