### ISSUE TITLE
Blinker-Light style naming is broken

### ISSUE THREAD

**Issue by davelab6** [google/fonts#2159]
A user wrote in with this issue:

> I have downloaded and installed the Blinker font and I’m having problems with the Light weight. It is called ‘Light’ and it previews like Light, but when I install it, its name changes to Extra-Light, it conflicts with the real Extra-Light and I can’t activate it.
>
> So I have downloaded the font from the type foundry (Supertype) and everything works as it should. I thought I should let you know.

It is possible this error is introduced downstream of the fonts in this repo by the API processing, but reporting here in case the problem is here or even further upstream

**Comment by laerm0** [comment]
Ah, yep, the name tables in these two weights are identical. I'll hotfix.

**Comment by laerm0** [comment]
Fixed in https://github.com/google/fonts/pull/2160

**Comment by AndrewTelkamp** [comment]
Bump. This is happening again

**Comment by kenmcd** [comment]
> Bump. This is happening again

As a work-around you can use the fonts from the upstream repository.
They (v1.017) appear to be fine.
Repo: https://github.com/supertype-de/Blinker/
Download: https://github.com/supertype-de/Blinker/archive/refs/heads/master.zip

**Comment by AndrewTelkamp** [comment]
Oh great point, thanks @kenmcd!
