### ISSUE TITLE
Previous authors credit

### ISSUE THREAD

**Issue by vv-monsalve** [google/fonts#2161]
In cases of Font Projects that are base on previous typefaces, is there any documentation or protocol on how should the first author be credited?

Would it be enough mentioning it in the AUTHORS.txt file? 
Should it also be added to Designer field on Font Info in the source file?
Who's name should appear on the WebPage?

**Comment by m4rc1e** [comment]
[Crimson Pro](https://fonts.google.com/specimen/Crimson+Pro) is the pro version of [Crimson Text](https://fonts.google.com/specimen/Crimson+Text). Crimson Pro only lists Jacques Le Bally as the designer of the family. Its description does mention the original Crimson Text family though.

The answer to all three of your questions is, just list the people who have worked on the family. Also mention the original family in the DESCRIPTION.en_us.html file.
