### ISSUE TITLE
unpublished fonts

### ISSUE THREAD

**Issue by asantewa** [google/fonts#2187]
These fonts: 
Seoul Hangang, Seoul Hangang Condensed, Merge One, Amatica SC, Yinmar, Gemunu Libre, Nikukyu, Mplus1p, Myanmar Sans, Adobe Blank. Carrios Gothic, Carrios Gothic SC, Karla Tamil Incline, Karla Tamil Upright, Lao Muangdon & Lao Muangkhongnot are not available on fonts.google.com (although available in github.com/google/fonts) and should be pushed.

**Comment by fitojb** [comment]
There are good reasons for some of these not be published; Amatica SC, for instance is a deprecated project (temporary fork to expand the character set of Amatic SC; it was never intended to be a separate, hard fork); it remains on the API to serve existing users but it’s unpublished.

**Comment by asantewa** [comment]
Some more unpublished fonts for consideration:
Nikukyu, Mplus1p, Myanmar sans, Adobe blank, Carrios Gothic, Carrios Gothic SC, Karla Tamil Incline, Karla Tamil Upright, Lao Muangdon, Lao Muangkhongnot, Paduak, Jeju Gothic, Jeju Hallasan, Jeju Myeongjo, Kokoro, Phetsarath, Souliyo, Thabit, Redacted, Strong, Bruno Ace, Abyssincasil, Varta, and Bhavuka.

**Comment by fitojb** [comment]
Again, some are not intended for public consumption; e.g., Adobe Blank is not intended to be installable or used by final users.

**Comment by asantewa** [comment]
@fitojb hi Adolfo, I'm well aware :), these are for documentation purposes.

**Comment by RosaWagner** [comment]
We are going to update the list and see which one to remove and which one to release.
cc @m4rc1e @davelab6

**Comment by vv-monsalve** [comment]
[Varta](https://fonts.google.com/specimen/Varta?preview.text_type=custom#standard-styles) was published last year

**Comment by thlinard** [comment]
+ Sedan (Sedán)

**Comment by RosaWagner** [comment]
A lot of this has been resolved. There are still some to go but we are preparing a new list, so closing here.

**Comment by davelab6** [comment]
We should probably redo this exercise and further clean up this repo in Q1 :) Assigning to myself for now
