### ISSUE TITLE
Outdated 'Open Sans' in repo

### ISSUE THREAD

**Issue by eins78** [google/fonts#22]
The Google Webfont API says 'Open Sans' was `lastModified: '2015-04-27'`, but the files in this repo were not updated.

Out of curiosity: Do they need to be synced manually? Is there any other way to find out font changes than asking the API? (Ideally I was looking for a changelog because there were _visual_ in the newer version now served by google, but since I haven't found the actual source repo for 'Open Sans' this was my next best bet)

**Comment by rsheeter** [comment]
Last modified can also mean adjustments outside the font file that impact what ends up getting served on Google Fonts. I did a quick check on OpenSans-Regular.ttf and it appears to me the one here should be the latest copy.

**Comment by eins78** [comment]
@rsheeter I am pretty sure that the font itself was changed, because we are testing the visual output of our styleguide (using Open Sans) by comparing screenshots. This test broke exactly on that 'lastModifed' date… 
(Looking at the diffs revealed that *kerning* of the font changed, if that is of any help).

**Comment by rsheeter** [comment]
Can you see for which glyphs kerning shifted? Also on which browser(s)?

It is possible that serving optimizations might have had an impact.

**Comment by olsonpm** [comment]
wouldn't a file diff between the font served from google fonts and the github repo solve your issues?

**Comment by davelab6** [comment]
There are other problems with Open Sans that I will look into 
- [ ] Bold GPOS table is corrupt, https://github.com/behdad/fonttools/issues/314
- [ ] Likely style naming/fsSelection issues, https://twitter.com/manik314/status/634267763696005122 and https://twitter.com/LorryCaton/status/636084196176490496

**Comment by laerm0** [comment]
Naming flaws are solved with @m4rc1e's hotfix, but the tilde problem is still outstanding (#1199) and the Romanian problem is still outstanding (#213). As both of these problem have stand-alone issues, I think we can close this issue. Thoughts, @davelab6?

**Comment by davelab6** [comment]
Sounds good
