### ISSUE TITLE
Noto Sans Light

### ISSUE THREAD

**Issue by jemali-m** [google/fonts#221]
You can add light style (font-weight: 300) in Noto Sans font family?

**Comment by davelab6** [comment]
When it is released :)

**Comment by arthurwhite** [comment]
@davelab6, it would be nice to reopen this "issue" since *Noto Sans* has all the needed [weights](http://www.google.com/get/noto/#sans-lgc):

- *Thin*
- *ExtraLight*
- *Light*
- *Regular*
- *Medium*
- *SemiBold*
- *Bold*
- *ExtraBold*
- *Black*

...and their italic variants.

**Comment by davelab6** [comment]
@arthurwhite I agree; I believe they are not hinted, but we'll review for rendering regressions on Windows :)

**Comment by slk333** [comment]
update about this?

**Comment by brettdonald** [comment]
Totally ridiculous that Google Fonts doesn't include all the latest Noto Sans stuff. Please fix ASAP.

**Comment by slk333** [comment]
adobes provides a cdn version ?

**Comment by slk333** [comment]
at this point just add the 300 variation to Google Fonts, will solve the issue, don't need to use third party providers like Adobe.

**Comment by slk333** [comment]
@davelab6 it seems you completely forgot this issue, so I ping you!, cheers

**Comment by thlinard** [comment]
Duplicate of #398?

**Comment by martinbean** [comment]
> at this point just add the 300 variation to Google Fonts, will solve the issue, don't need to use third party providers like Adobe.

@slk333 And Google Fonts _isn’t_ a “third party provider”…?

**Comment by brettdonald** [comment]
> And Google Fonts _isn’t_ a “third party provider”…?

Not from a consumer point of view, it isn't. Noto Sans is published by Google, so Google Fonts ought to include it, all of it. From a Google internal point of view, it looks like the folk who produce Noto Sans are in a completely different silo from those who produce Google Fonts.

**Comment by brettdonald** [comment]
@RosaWagner I see you've made some changes to labels and milestones. Can you give us an update on the status of this issue, please.

**Comment by RosaWagner** [comment]
Noto Sans Light was added in https://github.com/google/fonts/pull/4291
