### ISSUE TITLE
Add Typeface “Orelega” (Clarendon type)

### ISSUE THREAD

**Issue by JapanYoshi** [google/fonts#2210]
This is my first project designed with Google Fonts in mind from the start. However, this project is far from finished—I still haven't managed to add kerning, but before that, I'd like to submit what I have for now and get feedback before I progress to the next step.

Link: https://github.com/japanyoshi/orelega

![orelega](https://user-images.githubusercontent.com/8707990/67018212-3e7a9c80-f13e-11e9-81ca-e058adffa983.png)

Production notes by @yanone:
- [x] Contact author
- [x] Build
- [x] Fontbakery QA
- [x] Visual QA
- [x] Version bumped
- [x] [Catalog designer info up to date](https://github.com/google/fonts/pull/3113)
- [x] [PR to upstream](https://github.com/JapanYoshi/Orelega/pull/2)
- [x] [PR to GF](https://github.com/google/fonts/pull/3114)
- [x] Font Images

**Comment by eliheuer** [comment]
Awesome thanks. I'll look at this when I get a chance and leave some issues in the upstream repo.

+1 for the Esperanto name. :-)

**Comment by JapanYoshi** [comment]
I added kerning, but I'm not sure if the kerning I have works as well as it should.
![](https://raw.githubusercontent.com/JapanYoshi/Orelega/master/kerning.png)

**Comment by JapanYoshi** [comment]
I've worked on Orelega a bit. Kerning should be complete now.

**Comment by JapanYoshi** [comment]
There are Cyrillic (Russian) glyphs now. Please note though, that the Cyrillic portion is unfinished.

**Comment by yanone** [comment]
Hi @JapanYoshi 
I’ve started the onboarding process. Please refrain from making changes to the repo for the time being to avoid data conflicts. I will PR necessary changed back to you as soon as possible.

**Comment by yanone** [comment]
Upstream PR regarding family name renaming from "Orelega" to "Orelega One": https://github.com/JapanYoshi/Orelega/pull/3
