### ISSUE TITLE
Add Oxanium

### ISSUE THREAD

**Issue by davelab6** [google/fonts#2217]
https://github.com/sevmeyer/oxanium

**Comment by felipesanches** [comment]
At https://sev.dev/fonts/oxanium/
![Screenshot at 2019-10-21 15:51:40](https://user-images.githubusercontent.com/213676/67234052-ed1b2780-f433-11e9-928e-17223d7e12d4.png)


what's the meaning of this?

**Comment by laerm0** [comment]
@felipesanches I suspect it has to do with @sevmeyer implementation of his own TT hint compiler. https://gitlab.com/sev/htic

**Comment by davelab6** [comment]
It's a Glyph that shows if hinting is being executed or not, because the
hints when active will turn the arrow up

**Comment by laerm0** [comment]
Huh. That's kinda genius.

**Comment by sevmeyer** [comment]
Thank you for considering Oxanium. I have created a [dedicated branch](https://github.com/sevmeyer/oxanium/tree/googlefonts) to prepare the repository for Google Fonts.

It should pass the Font Bakery checks, let me know if additional adjustments are necessary. If the fonts are accepted, I will gladly merge the branch back into master, as a new official release.

**Comment by RosaWagner** [comment]
Closing this since Oxanium is live #2712

**Comment by yanone** [comment]
Manually linking PR: https://github.com/google/fonts/pull/2712

**Comment by yanone** [comment]
Manually linking PR: https://github.com/google/fonts/pull/2327
