### ISSUE TITLE
Avenir does not render bold weight heavy enough in Google Docs

### ISSUE THREAD

**Issue by maya** [google/fonts#2219]
Avenir does not render its bold weight heavy enough in Google Docs.

This is what I see:
<img width="374" alt="Screen Shot 2019-10-21 at 2 50 19 PM" src="https://user-images.githubusercontent.com/5249443/67245994-2b075400-f412-11e9-8c5c-b568621131a0.png">

This is what I expect to see:
<img width="352" alt="Screen Shot 2019-10-21 at 2 49 49 PM" src="https://user-images.githubusercontent.com/5249443/67245999-2cd11780-f412-11e9-888f-1f175fc8f1b7.png">

Is there any way the team can:
1. Increase the boldness
2. Obtain Avenir Bold

?

**Comment by laerm0** [comment]
Avenir is not part of the Google Fonts library, so its behavior in Google Docs (how did you even get it there?) is not within the project's purview.

**Comment by maya** [comment]
This issue is already being looked at by the Google Docs and Google Fonts team, so don't see a need for this to be open.

>how did you even get it there?
Avenir is available for anyone to use in Google Docs.

**Comment by coderesolution** [comment]
Hi @maya, has there been any progress on this? It appears to remain an ongoing issue with Avenir.

**Comment by tseringn** [comment]
Any update?
I am seeing bolded text dispersed in larger screen

**Comment by kenmcd** [comment]
Avenir seems to be listed - but there are no styles listed for it.
Like it is just an error that it is listed at all.
Same with Arial, Times New Roman, etc. - they are in the list, but no styles listed.
All three of these fonts are not going to be a part of Google Docs.
Looks like a bug.
