### ISSUE TITLE
Individual Fonts are not easily installable via bower

### ISSUE THREAD

**Issue by dwt** [google/fonts#222]
There are a boatload of github repositories that do nothing else than add the necessary metadata so individual fonts are installable by bower.

Can you / are you willing to incorporate these changes into this repo and / or provide something along the lines of https://github.com/google-fonts-bower/ so these fonts are installable directly?

Many thanks!

**Comment by davelab6** [comment]
When I look at https://github.com/google-fonts-bower/yesevaone-bower I don't see what has been added - but I see that the fonts are not being updated and so are distributing old buggy fonts :( 

What exactly needs to be added?

**Comment by dwt** [comment]
Yes, that was my impression too. As far as I can see the only thing they did was provide individual repositories for each font so a project can depend on an individual font instead of having to pull in all of them at once.

Some projects do provide some additional metadata like: https://github.com/choffmeister/roboto-fontface-bower/blob/develop/bower.json to ease installation and discoverability. I've also seen additional formats for the css https://github.com/choffmeister/roboto-fontface-bower/tree/develop/css (i.e. sass, less) to ease integration into existing projects.

My impression is that having the alternative to get one font per project would already help immensely, and allowing the community to provide sass/less/stylus (or whatever) inclusion rules could make them even more useful.

**Comment by davelab6** [comment]
Splitting the single repo into per-family repos seems unlikely, since a single repo is more convenient for onboarding the collection into the Google Fonts API CDN. Also one aim of Google Fonts is to make the web faster, and self-hosting works against this (because of the caching benefits of a single font URL for millions of domains.) 

But thanks for the suggestion, I'll bring it up with the team.

**Comment by dwt** [comment]
Some possible arguments: People are going to self host for various reasons (allowing them to be used offline is one of them), and it would be much better to provide them with the ability to still get updates easily.

As a maintainer I also wouldn't like to have the work split into so many repos, but that should be something that would be easy to do with some clever commit hooks and scripted repository creation. 

Perhaps giving a shout to some of the bower repo maintainers could be very fruitful as they probably have more to say about what is required.

**Comment by davelab6** [comment]
Indeed, various 3rd parties are providing bower packaging for these fonts (eg, https://github.com/skounis/montserrat-webfont and https://github.com/FontFaceKit/open-sans)

I will aim to keep version metadata inside font binaries incrementing as updates are made.

**Comment by davelab6** [comment]
Other packaging systems probably also ingest this repo, eg https://github.com/caskroom/homebrew-fonts/issues/445

**Comment by brancusi** [comment]
Would also like to see a solution for this. I need to do offline as well as development offline. Currently pulling in the whole repo which is fine for a one time setup, but doesn't work well with the CI system.

Thanks

**Comment by davelab6** [comment]
https://github.com/majodev/google-webfonts-helper/ is probably your best bet right now

**Comment by Rudloff** [comment]
Hello,
I am the maintainer of https://github.com/google-fonts-bower/.
Sorry for not updating the fonts, I will try to fully automate the process.
Please feel free to report any issue here: https://github.com/Rudloff/google-fonts-bower-import/issues

**Comment by laerm0** [comment]
@davelab6 Should we leave this issue open for people asking about per-font repos or can it be closed as the info is here?

**Comment by davelab6** [comment]
This is a repo management issue, that isn't urgent :)
