### ISSUE TITLE
Can you add this font?

### ISSUE THREAD

**Issue by DorisTB** [google/fonts#2235]
[](https://www.fontsquirrel.com/fonts/agane)

**Comment by laerm0** [comment]
@DorisTB your message is empty.

**Comment by DorisTB** [comment]
Very weird..  okay so this is the font I am kindly asking to add! 😊
https://www.fontsquirrel.com/fonts/agane
[](https://www.fontsquirrel.com/fonts/agane)

**Comment by laerm0** [comment]
Aha! Thank you, but, sadly, the font is not under a libre license, namely the [OFL](https://scripts.sil.org/cms/scripts/page.php?site_id=nrsi&id=OFL). It's free, but the license doesn't match what we need. You could always write [the author](https://www.danilodemarco.com/) and ask them to put the source here on github under the OFL. Sorry, but that's the best we can do.

**Comment by DorisTB** [comment]
Hi, I talked to the autor and he had put here n Github:  https://github.com/dema89/aganefont

**Comment by DorisTB** [comment]
#1936 - It was the author in April asking to put the font in here 😁

**Comment by felipesanches** [comment]
OK, cool. So let's continue this conversation there! :-)

**Comment by DorisTB** [comment]
Yeah! I could contact the author so he sent that issue had no reply... 🙀 So now we might make it happen! 😁😀

**Comment by DorisTB** [comment]
Hi, look I think it is kind confusing the process of licensing the font. Not sure If I understood how to license the font as OLF (https://scripts.sil.org/cms/scripts/page.php?site_id=nrsi&id=OFL) hope you can help.

**Comment by DorisTB** [comment]
@felipesanches I think this issue should not be closed.. because the font still not added even though The author made the update of the font files.

**Comment by felipesanches** [comment]
No need to have more than one issue to discuss this. We already have #1936 open to track progress on this proposal :-)
