### ISSUE TITLE
Add Viaoda Libre

### ISSUE THREAD

**Issue by bettergui** [google/fonts#2239]
https://github.com/bettergui/ViaodaLibre

This is our third type project, the previous projects were Darker Grotesque and Be Vietnam:
https://github.com/google/fonts/pull/2033
https://github.com/google/fonts/pull/2105

**Comment by m4rc1e** [comment]
Thanks!

@graphicore do you think FB dashboard is ready for power users? @bettergui usually provides faultless prs so I think he may be a good user to test the dashboard.

**Comment by thlinard** [comment]
Hi,

@m4rc1e the question is not for me, but in my opinion, the answer is yes. 😉

**Comment by bettergui** [comment]
Are there new features from Font Bakery ♥?
I am more than happy to test out and provide user feedback.
Vietanh

**Comment by m4rc1e** [comment]
I've merged the pr. I'll get it pushed next week.

**Comment by bettergui** [comment]
Hi everyone, would the type be pushed to the Google Fonts site soon?

**Comment by m4rc1e** [comment]
Apologies for the delay. Family is now on Google Fonts, https://fonts.google.com/specimen/Viaoda+Libre?query=vi

**Comment by bettergui** [comment]
Thanks, Marc. We are very happy to hear the news.
Take care and stay safe.
