### ISSUE TITLE
Add Girassol

### ISSUE THREAD

**Issue by liamspradlin** [google/fonts#2242]
Girassol is a single-style all-caps + smallcaps display typeface, inspired by the hand-painted street signs in and around Carcavelos, Portugal.

https://github.com/liamspradlin/girassol-display 

![Girassol](https://user-images.githubusercontent.com/10691248/68332812-5c844e80-00a5-11ea-93ad-d39905367eff.png)

**Comment by m4rc1e** [comment]
Girassol is now in production https://fonts.google.com/specimen/Girassol

Thanks to @yanone and @liamspradlin

**Comment by yanone** [comment]
Manually linking PR: https://github.com/google/fonts/pull/2271
