### ISSUE TITLE
glyphset documentation is very sparse

### ISSUE THREAD

**Issue by laerm0** [google/fonts#2245]
As @yanone [notes](https://github.com/googlefonts/fontbakery/issues/2690#issue-519350497), 

> The new rationale printing at least mentions the GF-latin-core glyph-set, but I couldn't find that glyph set anywhere, either.

I've gone looking for this (and other encodings) several times and they're pretty much not to be found (with some link rot). I assume @felipesanches knows where these files are if fontbakery knows what they are, so can he please put them somewhere? Thanks.

**Comment by thlinard** [comment]
Hi @laerm0 
Do you refer to https://github.com/googlefonts/gftools/blob/master/Lib/gftools/encodings/GF%20Glyph%20Sets/GF-latin-core_unique-glyphs.nam?

**Comment by felipesanches** [comment]
yes. It is all in gftools repo on the `encodings/GF Glyph Sets` directory

**Comment by laerm0** [comment]
D'oh! Thanks. I need to bookmark this.
