### ISSUE TITLE
New font : Vitrailnoir

### ISSUE THREAD

**Issue by Dolendin** [google/fonts#2248]
Hello,
It's my first attempt, all critics and advises are welcome.

https://github.com/Dolendin/Vitrailnoir.git

Thanks

**Comment by laerm0** [comment]
Hi @Dolendin –

Thanks for offering your font to Google Fonts. We have a [document](https://github.com/google/fonts/blob/master/CONTRIBUTING.md) that has guidelines for contributing to the project. You should take a look and go through the directions. I took a look at your font and it is a fine design, but, at first glance, I can see an issue with the metrics: the glyphs overflow the em square. You also need a license. We use the [OFL](https://scripts.sil.org/cms/scripts/page.php?site_id=nrsi&id=OFL_web).

Thanks again!

**Comment by Dolendin** [comment]
I see the problem with the glyph overflow. I first tried to make them fit in the em square, but the font was so tiny (because of the Uppercase letters being so big) that I needed to set the size to 28 to be able to read it as a 12 Arial.

**Comment by laerm0** [comment]
You can try increasing the em square without resizing: that would be my first choice. After that, it's pretty much rescaling glyphs. Thankfully that can be automated.

There is no source file in your repo: what program did you use to make the font? We will require a source file.

**Comment by Dolendin** [comment]
I used FontForge, I just added the source file in the repository.

I will try to resize the em square and then rescale glyphs when I have some time, I'm pretty busy right now (creating my company, looking for a place to host it, etc.)

**Comment by laerm0** [comment]
No problem. Good luck and thanks again.

**Comment by davelab6** [comment]
@Dolendin the repo wasn't updated since this discussion, and while I love your efforts to make the typeface you wanted to see in the world, I don't think this will be popular in Google Fonts. I recommend to submit it to fontlibrary.org and wish you a beautiful journey into the world of type design :)
