### ISSUE TITLE
The '8' in the google font family 'family=Cormorant Garamond|Impallari' seems to be of a different style 

### ISSUE THREAD

**Issue by jeffreyln101** [google/fonts#2249]
Have a client that wants to use the Cormorant Garamond Impallari family font and it seems to me the 8, 6, and 10 do not adhere to the style of the rest of the font family.

**Comment by jeffreyln101** [comment]
yes 1 and 0 sorry not 10 I heard it coming

**Comment by jeffreyln101** [comment]
![hours](https://user-images.githubusercontent.com/55372140/68549903-7ded7f00-03b2-11ea-9de6-950dc10af31f.png)

**Comment by jeffreyln101** [comment]
Looks kind of jacked up to me some numbers over a base line and some over a base line.

**Comment by laerm0** [comment]
https://en.m.wikipedia.org/wiki/Text_figures

**Comment by jeffreyln101** [comment]
So the font is intended to look like **** if you use the numbers?

**Comment by jeffreyln101** [comment]
Give me a link to some code using it, not a reference to a wikipedia page. Our you an admin on stackoverflow as well where no one can find an answer about anything?

**Comment by laerm0** [comment]
My friend.

The page explains that old-style or text figures are common and shows how they are used. Furthermore, you'll note,

>High-quality typesetting generally prefers text figures in body text: they integrate better with lowercase letters and small capitals, unlike runs of lining figures.

So perhaps your client expects high-quality typesetting.

**Comment by jeffreyln101** [comment]
Thank you for the note it is appreciated.
