### ISSUE TITLE
Source Sans missing Cyrillic glyphs 

### ISSUE THREAD

**Issue by jschatz1** [google/fonts#226]
I couldn't find an existing issue for this but it seems that source sans is missing Cyrillic and possibly other glyphs.

**Comment by davelab6** [comment]
They were only added to the upright styles, not italics, and some systems will break on the assumption that a style exists for both roman and italics, so until italic are made and accepted by Adobe, we can't include them.

**Comment by davelab6** [comment]
Related, https://github.com/adobe-fonts/source-sans-pro/issues/90 reports missing Vietnamese glyphs

**Comment by davelab6** [comment]
https://github.com/google/fonts/pull/950
