### ISSUE TITLE
Update Petrona

### ISSUE THREAD

**Issue by davelab6** [google/fonts#2265]
https://github.com/ringorseeber/Petrona is currently a private repo but when it becomes public, we should add it :)

**Comment by thlinard** [comment]
No longer a private repo, perhaps it's time to update Petrona?

**Comment by yanone** [comment]
Manually linking PR: https://github.com/google/fonts/pull/2293

**Comment by yanone** [comment]
Manually linking PR: https://github.com/google/fonts/pull/2542
