### ISSUE TITLE
DESCRIPTION.ll_cc.html should be 'll_CC'

### ISSUE THREAD

**Issue by sladen** [google/fonts#227]
ISO language codes are in the form 'll_CC' where the language code is in lower case, and the country code is in UPPER CASE.  Ideally GF would follow this convention.

This appears in eg. 'DESCRIPTION.en_us.html' rather than the expected 'DESCRIPTION.en_US.html'.  Normal library functions are expecting 'en_US', but for GF this needs further upcasing/downcasing to cope with GF.

**Comment by davelab6** [comment]
btw they are IETF language tags, http://www.langtag.net :)

**Comment by davelab6** [comment]
This will be "fun" to fix given git case handling on macOS (which has a case insensitive file system....) so downgrading priority
