### ISSUE TITLE
Classic Polish font - Antykwa Półtawskiego

### ISSUE THREAD

**Issue by ciembor** [google/fonts#2288]
Antykwa Półtawskiego (Półtawski's antiqua) is an antiqua typeface designed by Adam Półtawski from 1923 to 1928 specifically for the Polish language. It would be awesome if it could be included in Google Fonts Collection. 

The Polish TeX User's Group GUST (Janusz M. Nowacki, Bogusław Jackowski and Piotr Strzelczyk) digitised Antykwa Półtawskiego using Metafont with 4 weights (light, normal, medium, bold), italic and upright styles, as well as specific fonts for 6, 8, 10, 12 and 17 point sizes.

The fonts are available free of charge under the terms of the GUST Font License.

It's available here: http://www.gust.org.pl/projects/e-foundry/poltawski/download/index_html

More info in this PDF document: http://www.gust.org.pl/projects/e-foundry/poltawski/download/ap-info.pdf

Currently the font doesn't pass some of the requirements. JSON report for all TTF fonts generated with fontbakery tool is available here: https://gist.github.com/ciembor/188f58d71789fa37d8907442ff1964d0

The OTF version seems to be better.

**Comment by laerm0** [comment]
Lovely typeface, but, sadly, Google Fonts only accepts [OFL-licensed](https://github.com/google/fonts/blob/master/CONTRIBUTING.md) fonts.

**Comment by ciembor** [comment]
@laerm0 In case of a single `.otf` file there not so many failures from fontbakery. There are 8 failures per file so I think it's quite easy to fix it. The main issue is of course the license. It's based on LPPL and I find it to be very liberal. Maybe even more liberal than OFL.

**Comment by Daymarius** [comment]
> @laerm0 In case of a single `.otf` file there not so many failures from fontbakery. There are 8 failures per file so I think it's quite easy to fix it. The main issue is of course the license. It's based on LPPL and I find it to be very liberal. Maybe even more liberal than OFL.

Possible, but OTF license is one of the important conditions

**Comment by tphinney** [comment]
@laerm0 I thought Google Fonts also accepted the Apache license? Or perhaps that was formerly true, but no longer so for new fonts?

**Comment by laerm0** [comment]
I believe that is the case, yes, that Apache fonts were once accepted but now the contributing doc says OFL only.

**Comment by davelab6** [comment]
Since GUST is broadly similar to OFL, I hope the upstream project could consider making the fonts available under OFL. We only accept OFL.

**Comment by vv-monsalve** [comment]
Followed in #5357
