### ISSUE TITLE
Gothic A1 ellipsis issue

### ISSUE THREAD

**Issue by textarea** [google/fonts#2298]
Ellipsis are shown in the middle of text instead of in the baseline.

![Schermata 2020-01-07 alle 11 35 47](https://user-images.githubusercontent.com/1927403/71889187-e43c1700-3141-11ea-8238-25c072e5a0db.jpg)

**Comment by fitojb** [comment]
There is a reason for why CJK fonts are like that…

https://bugs.launchpad.net/takao-fonts/+bug/956016/comments/2

> This it not true in JIS X 0208/JIS X 0213 conversion maps. That is valid for Japanese historical font rules.
> In JIS X 0208/JIS X 0213, U+2026 code place *must* set as three-point leader that placed at center-line. This implementation are historical constraint. This restriction(and incompatibility for alphabetic/unicode standard fonts) are agonizing choice in upstream(IPA fonts).

**Comment by VasilikiLoukoumi** [comment]
I have found that unicode range fixes the issue. But, I wish there was a 'global' unicode range that works for this font. (Is there?) I found unicode ranges in here [(https://fonts.googleapis.com/css2?family=Gothic+A1:wght@100;200;400;700;800;900&display=swap)] but with each font weight come many different unicode ranges. It seems like we have to include many font files, each with its own unicode range  in order for it to work.

**Comment by textarea** [comment]
Hello @VasilikiLoukoumi, which is the unicode range you found that fixes the issue?

**Comment by VasilikiLoukoumi** [comment]
Hello, you have to use many, not one. If for example you have to use the Gothic A1 Thin font ,
you have to copy the css shown in this google fonts url ->[]( https://fonts.googleapis.com/css2?family=Gothic+A1) As you can see it contains many woff2 files and different unicode ranges for each one of them.

**Comment by textarea** [comment]
Ok @VasilikiLoukoumi, but I didn't understand how to fix the issue. Which is the right unicode range for the Thin font (for example)?

**Comment by VasilikiLoukoumi** [comment]
If you place this <link href="https://fonts.googleapis.com/css2?family=Gothic+A1:wght@100&display=swap" rel="stylesheet"> on your html head tag, the ellipsis will work. 
If you want to self host the files you have to download **all** the provided links (eg 1 -> https://fonts.gstatic.com/s/gothica1/v8/CSR94z5ZnPydRjlCCwl6ac0oQNM8ru4reAXaTlFCBXrC-se62sS-fg.0.woff2, 2 -> https://fonts.gstatic.com/s/gothica1/v8/CSR94z5ZnPydRjlCCwl6ac0oQNM8ru4reAXaTlFCBXrC-se62sS-fg.2.woff2 etc ) and include each font face css -> 
```
 @font-face {
  font-family: 'Gothic A1';
  font-style: normal;
  font-weight: 400;
  font-display: swap;
  src: local('Gothic A1 Regular'), local('GothicA1-Regular'), url(myFonts/0.woff2) format('woff2');
  unicode-range: U+f9ca-fa0b, U+ff03-ff05, U+ff07, U+ff0a-ff0b, U+ff0d-ff19, U+ff1b, U+ff1d, U+ff20-ff5b, U+ff5d, U+ffe0-ffe3, U+ffe5-ffe6;
}
/* [2] */
@font-face {
  font-family: 'Gothic A1';
  font-style: normal;
  font-weight: 400;
  font-display: swap;
  src: local('Gothic A1 Regular'), local('GothicA1-Regular'), url(myFonts/2.woff2) format('woff2');
  unicode-range: U+d723-d728, U+d72a-d733, U+d735-d748, U+d74a-d74f, U+d752-d753, U+d755-d757, U+d75a-d75f, U+d762-d764, U+d766-d768, U+d76a-d76b, U+d76d-d76f, U+d771-d787, U+d789-d78b, U+d78d-d78f, U+d791-d797, U+d79a, U+d79c, U+d79e-d7a3, U+f900-f909, U+f90b-f92e;
}
```

**Comment by textarea** [comment]
@VasilikiLoukoumi it doesn't work, https://jsfiddle.net/textarea/o1f3dp2j/35/

**Comment by VasilikiLoukoumi** [comment]
I can see it working in my browser. If you care about older browsers this does not work, you need a woff file as well. [](url)
![Screenshot 2020-05-04 at 17 38 54](https://user-images.githubusercontent.com/24655237/80978106-4a098880-8e2e-11ea-867a-211f2db05709.png)

**Comment by textarea** [comment]
I'm with Chrome 81 on MacOS.

![Schermata 2020-05-04 alle 16 43 17](https://user-images.githubusercontent.com/1927403/80978490-69041c80-8e26-11ea-9a6b-edbc8c24eea3.jpg)

**Comment by thlinard** [comment]
Works correctly on macOS 10.15.4 with

- Chrome 81
- Firefox 75
- Safari 13.1
