### ISSUE TITLE
Open Sans latin,latin-ext,greek,greek-ext files big

### ISSUE THREAD

**Issue by vijayaraghavanramanan** [google/fonts#230]
There's an issue with subsetting Open Sans. 

latin,latin-ext,greek,greek-ext woff files also have other characters making file sizes upto 90KB/font. 

This is because other subsets also appear in the font file. 

This can be checked by loading 

https://fonts.googleapis.com/css?family=Open+Sans:400,400italic,700,700italic&subset=latin,latin-ext,greek,greek-ext

in a browser which doesn't support woff2 such as Safari or Edge. 

Possible to have a lower file size?

**Comment by rsheeter** [comment]
This is by design; in absence of unicode-range we may choose to deliver the entire font for some requests. That is what is happening here. 

Vote for unicode-range for Edge [here](https://wpdev.uservoice.com/forums/257854-microsoft-edge-developer/suggestions/6510254-unicode-range) :)

**Comment by laerm0** [comment]
Do you think we can close this, @rsheeter?

**Comment by davelab6** [comment]
I do :)
