### ISSUE TITLE
Add JetBrains Mono

### ISSUE THREAD

**Issue by enricob** [google/fonts#2308]
JetBrains has recently released a new free and open source monospaced font that seems like it'd be especially good for rendering snippets of code. More info: https://www.jetbrains.com/lp/mono/

GitHub repo: https://github.com/JetBrains/JetBrainsMono

**Comment by Daymarius** [comment]
At now it's a best free monospace font for my opinion.
Thanks for cyrillic support!

**Comment by fitojb** [comment]
Why didn’t they use the OFL though?

**Comment by gsbhasin123** [comment]
Please do!
Like, I need to use Jetbrains Mono in Google Docs urgently (it's my favorite font :P)
And having it in Google Fonts would allow you to install it in any GSuite products using their "Add more Fonts" feature (in Docs, Sheets, and Slides)

**Comment by fitojb** [comment]
> Like, I need to use Jetbrains Mono in Google Docs urgently (it's my favorite font :P)

You are confusing the meanings of “to need” and “to want”. It’s hardly urgent honestly.

**Comment by Acelator** [comment]
Any update on when it will be added?

**Comment by elkaszcz** [comment]
Any update on when it will be added?

**Comment by rcastellotti** [comment]
yea, please add it

**Comment by soar** [comment]
It would be great!

**Comment by thlinard** [comment]
Released today, version 2.000 add two VF fonts:
https://github.com/JetBrains/JetBrainsMono/releases/tag/v2.000

**Comment by thlinard** [comment]
And version 2.002 is released under OFL:
https://github.com/JetBrains/JetBrainsMono/releases/tag/v2.002

@eliheuer

**Comment by marceloverdijk** [comment]
So nothing should be in the way to add it to Google Fonts lib, right?

**Comment by davelab6** [comment]
Now it's under OFL, **and** as a VF, I'll prioritize it!

@RosaWagner

**Comment by hibissscus** [comment]
Any updates?

**Comment by RosaWagner** [comment]
Yep, it’s happening soon.

**Comment by m4rc1e** [comment]
Family is now live, https://fonts.google.com/specimen/JetBrains+Mono

**Comment by jonmccon** [comment]
Super excited about this typeface, thank you for all the work you did to get this hosted by Google Fonts. However I noticed it's not showing up in the Slides or Docs font picker in a personal or a Gsuite account, any clues on this?

**Comment by morganwk** [comment]
Is there any possibility of adding the no ligatures version (Jetbrains Mono NL)?

**Comment by eliheuer** [comment]
@jonmccon Not every font available on Google Fonts is available in the Slides or Docs font picker.

**Comment by GalihPRep** [comment]
Is there any plan to add new characters? I'd like the font to cover the Latin Extended B–Additional and whole Cyrillic block, and I'd like these characters on Google Docs/Sheets in this font.
