### ISSUE TITLE
Add the Urbanist Family

### ISSUE THREAD

**Issue by coreyhu** [google/fonts#2326]
Hi, I'd love to submit Urbanist (https://github.com/coreywho/Urbanist) to be considered as a new variable font.

- [x] The design is original
- [x] The project is licensed under OFL 1.1
- [x] The name is unique (according to https://namecheck.fontdata.com/)
- [x] The project is open on Github
- [x] All files contain the necessary 215 glyphs
- [x] All files have the same Unicode character set
- [x] All files pass the Font bakery checks (minus the VendorID check since the cached list in the fontbakery package has not yet been updated)
- [x] The README.md contains all github usernames

Please let me know if there's any updates you may need!

**Comment by coreywho** [comment]
Also updated the repo with DESCRIPTION.en_us.html, profile and photo under the documentation directory. Is there anything else I should do?

**Comment by coreywho** [comment]
Hi @laerm0 what's the status on this?

**Comment by coreywho** [comment]
update: work on the variable font should be mostly complete. Just identifying new bugs atm
