### ISSUE TITLE
Reading METADATA.pb files in Objective-C

### ISSUE THREAD

**Issue by kennycarruthers** [google/fonts#233]
Not being familiar with protocol buffers, I'm struggling to read the new METADATA.pb formatted files from within an Objective-C program. 

Am I correct in assuming that the METADATA.pb files are formatted using the `text format` of protocol buffers? 

I can compile the Objective-C codebase for protocol buffers and generate  `FontsPublic.pbobjc.h` and `FontsPublic.pbobjc.m` files but any attempt to read a METADATA.pb files results in an `NSError` with `GPBMessageErrorCodeMalformedData` and the `user_info` set to `Reason = "Last tag: 110 should be 0";`

This is using the `parseFromData...` initializers on `GPBMessage`. The documentation is relatively terse when it comes to the text format but it seems to hint that under the C++ toolchain (and maybe even under Python's) that there's a special text format reader. Is there such a reader for Objective-C or have I overlooked it?

I also discovered that `protoc` can convert from textual format to binary format, but for the life of me I can't figure out the proper syntax and options to pass it. If I can't read text format protocol buffers in Objective-C then can I use `protoc` to convert the METADATA.pb ones to binary format? If so, how? 

Any help on how to read the METADATA.pb files from within an Objective-C application would be greatly helpful. The previous JSON files were very straight-forward to use but these protocol buffer have me stumped.

**Comment by rsheeter** [comment]
You are correct that they are in text format. I would look for something called text_format (or TextFormat or whatever) in the ObjC API. In Python you can use from `google.protobuf import text_format` (`tools/add_font.py` shows this). In C++ you would use `text_format.h`.

To convert to binary format for use with ParseFromString or other APIs that expect a binary message something like this should work:
```
cd <where you cloned google/fonts>
protoc --encode=google.fonts.FamilyProto tools/fonts_public.proto \
  <apache/roboto/METADATA.pb > /tmp/metadata.binary
```

**Comment by kennycarruthers** [comment]
Thanks for the quick follow-up. I don't see any text format support in the downloadable Objective-C release so I've just switched over to using the C++ one for now. Note that I'm downloading the release (3.0.0-beta-2) from here (I _assume_ that it's OK to use v3 against the METADATA.pb files?): 

https://github.com/google/protobuf/releases

In an earlier commit commit, a reference was made to using the Google Fonts API instead of the metadata files. Is there any reason to use the API over just parsing the METADATA.pb files if one has already downloaded the METADATA.pb files (or keeps a cloned repository on their local computer)? Is it safe to _assume_ that the METADATA.pb files are as up-to-date as the font files in the repository? 

https://developers.google.com/fonts/docs/developer_api#Details

**Comment by rsheeter** [comment]
The METADATA files here are time shifted from what is served in production.
Think of them as upstream basically.

The developer API is the authoritative resource for what is currently being
served.
