### ISSUE TITLE
Please add Bronova font to Google Fonts

### ISSUE THREAD

**Issue by designbro** [google/fonts#2333]
New font created following your guidelines:

https://github.com/designbro/Bronova-font

**Comment by laerm0** [comment]
Hi there –

You are close to matching the spec. One thing definitely [required](https://github.com/google/fonts/blob/master/CONTRIBUTING.md) are the sources.

> The project is developed on Github or similar, with complete corresponding sources, open to public participation, and actively maintained. Complete corresponding sources means that the fonts are available in your preferred form of modification, the files you actually use to develop the project, along with all the build instructions or scripts needed to reproduce the process of turning those source files into your released font binaries.

**Comment by designbro** [comment]
> Hi there –
> 
> You are close to matching the spec. One thing definitely [required](https://github.com/google/fonts/blob/master/CONTRIBUTING.md) are the sources.
> 
> > The project is developed on Github or similar, with complete corresponding sources, open to public participation, and actively maintained. Complete corresponding sources means that the fonts are available in your preferred form of modification, the files you actually use to develop the project, along with all the build instructions or scripts needed to reproduce the process of turning those source files into your released font binaries.

Hi @laerm0 - 
Thank you for your message. We now added the .glyph source files in the source directory.

**Comment by laerm0** [comment]
Aha, cool, thanks @designbro. I'll take a look later. 👍

**Comment by christiaan1981** [comment]
Hi @RosaWagner and @laerm0 - Just checking in to see how this is moving along. Do you need anything else from our side?

**Comment by RosaWagner** [comment]
Hi @christiaan1981 thanks for the reminder, this issue was not tracked. I have looked at the sources and the glyphset is too limited. GF requires to support at least GF Latin Core: https://github.com/googlefonts/glyphsets/blob/main/GF_glyphsets/Latin/txt/nice-names/GF_Latin_Core.txt

If that condition gets satisfied, we can review and see if we onboard.

**Comment by davelab6** [comment]
https://googlefonts.github.io/gf-guide/outlines.html provides some info about "type design refinements"
