### ISSUE TITLE
Commas rendered strangely for Schehezarade font when using Latin

### ISSUE THREAD

**Issue by Flimm** [google/fonts#2335]
The commas in the Scheherazade font renders strangely in some browsers. This may be a bug in some browsers, but other fonts do not have this problem. So I think the font could be fixed to avoid this bug.

Take this HTML:

```html
<!DOCTYPE html>
<meta charset="UTF-8">
<link href="https://fonts.googleapis.com/css?family=Scheherazade&display=swap" rel="stylesheet">
<style>p { font-family: 'Scheherazade', serif; }</style>
<p>One, two, three, four.</p>
```

In browsers like Firefox (Windows and Linux), it gets rendered like in this screenshot:

![buggy](https://user-images.githubusercontent.com/355454/74224253-cb7ece00-4cb8-11ea-9781-7157f98f04b6.png)

As you can see, the commas are rendered in the wrong position, they are rendered too high up. Also, the spacing after the comma is missing.

However, in browsers like Chrome (Windows and Linux), it renders correctly like in this screenshot:

![not buggy](https://user-images.githubusercontent.com/355454/74224615-7becd200-4cb9-11ea-9a4b-268057e71189.png)

I've only noticed this issue when using text in the Latin alphabet, not in the Arabic script.

**Comment by Flimm** [comment]
I reported this to Mozilla as well, see this bug report: https://bugzilla.mozilla.org/show_bug.cgi?id=1614575

**Comment by laerm0** [comment]
Hi, this does appear to be a Mozilla bug: I can reproduce your error and the source files are fine. I can't, however, see what the issue could be that would cause the Mozilla bug. There is one trivial issue with this font (an overlapping node at the outline start point) but that's in every glyph so if that were causing the issue, every glyph would have this issue. There is also no kerning so the spacing issue is not due to that.

I'll keep the issue open. Please report back if you hear anything from Mozilla. Thanks!

**Comment by Flimm** [comment]
I got a response very quickly in [the bug reported to Mozilla](https://bugzilla.mozilla.org/show_bug.cgi?id=1614575). I quote [the most relevant comment](https://bugzilla.mozilla.org/show_bug.cgi?id=1614575#c3) by Jonathan Kew:

> Ah, I see ... it appears this is a bug in the font, but only in its Graphite layout behavior. If you set `gfx.font_rendering.graphite.enabled` to `false` in `about:config`, the problem disappears, as we then use the OpenType layout tables. Chrome doesn't support Graphite rendering, so the problem doesn't show up there.
> 
> And the problem doesn't occur when using the font served by Google Fonts (rather than a locally-installed copy) because Google serves a copy of the font where the Graphite tables have been removed.
> 
> Further confirmation: I see the same bad result if I use the font in LibreOffice (which does support Graphite).
> 
> So this is not a Firefox bug, it's a font bug; I'll let the SIL team responsible for Scheherazade know about it. Meanwhile, as a workaround you can disable Graphite in Firefox as mentioned above.

So they think the problem is in the Scheherazade font file.
