### ISSUE TITLE
Proposal: Serve same files for all OS, at least WOFF2s

### ISSUE THREAD

**Issue by vijayaraghavanramanan** [google/fonts#234]
Google Chrome is soon going to be out with preload: 

https://www.smashingmagazine.com/2016/02/preload-what-is-it-good-for/

Using it, one can preload fonts like this: 

https://www.w3.org/TR/preload/

`<link rel="preload" href="https://fonts.example.com/font.woff2" as="font" crossorigin type="font/woff2">`

Since Google Fonts serves different fonts for different OS for the same browser, (for example Chrome on Windows vs Mac), this cannot be used. Instead if the files were to be the same, fonts can be preloaded!

Is this possible?

**Comment by rsheeter** [comment]
There are things like not sending hints to mobile that we wouldn't want to lose, plus unicode-range complicates file selection. It might be we figure out a way to leverage the preload http header at some point.

**Comment by vijayaraghavanramanan** [comment]
Thanks @rsheeter makes sense. 

I'd imagine that all browsers which will support preload will support woff2 and unicode-range. 

In that case we just preload woff2s and load the css for the rest. New browsers will use both and old browsers will just use the css. 

However this cannot be assumed to be true of all future browsers. But I hope it works out well.

**Comment by davelab6** [comment]
This seems related to https://github.com/google/fonts/issues/277
