### ISSUE TITLE
Gentium

### ISSUE THREAD

**Issue by odysseusjak** [google/fonts#2343]
Micah,

Unless I'm mistaken, I think you were going to the wrong site. Gentium's site is: https://software.sil.org/gentium/. It's been out since 2005. It was last updated in 2014. Plus, it's _already_ in Google's font catalog; it's just to be updated to the latest version.

**Comment by thlinard** [comment]
Google Fonts doesn't include Gentium, but Gentium Basic and Gentium Book Basic, in their latest version, version 1.102.
