### ISSUE TITLE
Add Inter font

### ISSUE THREAD

**Issue by EspadaV8** [google/fonts#2347]
This was requested before but needed a name change - https://github.com/google/fonts/issues/1167 and https://github.com/rsms/inter/issues/12 - which has now happened. Would it be possible to get this added to Google Fonts now?

**Comment by fitojb** [comment]
The name isn’t at all the biggest technical hurdle with this family.

Please search for existing threads before opening duplicates. See #1908 but please don’t add to the “I want this too!” pile. People has been working on this already; the least you can do is read and understand the existing threads.

**Comment by EspadaV8** [comment]
My apologies. I did try to check before opening since I thought it odd it would just be closed. Not sure how that was missed
