### ISSUE TITLE
Documentation: Explain how to use all styles in MSIE 8 + 9

### ISSUE THREAD

**Issue by superpoincare** [google/fonts#235]
This is an old bug and for old browsers but doesn't hurt correcting it: 

Old IEs only receive the normal version (weight: 400) of the requested font. This may not be a browser bug because the css just has one @font-face rule. 

This has some background. https://www.smashingmagazine.com/2012/07/avoiding-faux-weights-styles-google-web-fonts/

As long as Google Fonts is supporting eots and svgs, it doesn't hurt removing this bug.

**Comment by davelab6** [comment]
https://www.smashingmagazine.com/2012/07/avoiding-faux-weights-styles-google-web-fonts/#using-a-conditional-comment-works-across-browsers was helpful to better understand this issue :) 

I guess the API is working correctly, it just has to be used in a particular way for web developers who care about MSIE 8 + 9...

So I guess the resolution of this issue will be when that conditional comment is promoted in the developer documentation (and perhaps in the directory's code snippet feature, somehow without overcomplicating it... :)
