### ISSUE TITLE
Font request

### ISSUE THREAD

**Issue by PiotrGrochowski** [google/fonts#2355]
I request the font DMCA Sans Serif be added. https://typedesign.netlify.com/dmcasansserif.html The font as of 9.0 contains 3309 characters, and behaves as a general-purpose sans-serif font while having differences from the most common general-purpose sans serif fonts. The typeface is recommended to be embedded entirely, as partial embedding is discouraged; which fonts to load is the browser's decision. It is also recommended to be the only font used, when it is used.

**Comment by felipesanches** [comment]
Are you sure you want to use the DMCA name? It is not clear to me if you understand that "DMCA" also means "Digital Millennium Copyright Act". More info at https://en.wikipedia.org/wiki/Digital_Millennium_Copyright_Act

I think it is not a good strategy to use a name like this.

**Comment by felipesanches** [comment]
Please also notice that one of the prerequisites to add a font family to the Google Fonts collection is that it should be licensed under the SIL Open Font License. Looking at the website and github repositories I could not find the font files.

The repo at https://github.com/PiotrGrochowski/DMCAsansserif-entity seems to indicate that the files are not publicly available at all, while only the issue tracker is in use. Please open a new issue if you eventually decide to publish the font files under the OFL license.

**Comment by PiotrGrochowski** [comment]
The repository does not host the font, the website does. Also the license is the public domain, for both the copyright and the registered trademark.

**Comment by thundernixon** [comment]
Hey @PiotrGrochowski, thanks for your interest! It's cool to see you're hacking on fonts. :) However, this particular project has some issues which may be blockers for inclusion in the GF directory.

Please see the list of criteria for fonts that can be accepted to Google Fonts: https://github.com/google/fonts/blob/master/CONTRIBUTING.md

**Specific criteria that I'm concern about in regards to this project**

> The project is wholly licensed under the SIL Open Font License v1.1, and there are no proprietary/restricted-license versions available elsewhere

It's not clear on the website or repo how your project is licensed. You may be interested in the Apache 2.0 license, or looking at [other options in this GitHub guide](https://help.github.com/en/github/creating-cloning-and-archiving-repositories/licensing-a-repository). However, Google Fonts requires all new families to be licensed under the OFL.

> The font family name does not include any copyright holder names or registered trademarks, and no initials or abbreviations

Is there a certain reason you've chosen the name "DCMA"? If so, maybe that could help you find a name that doesn't include initials / abbreviations.

> The typeface design is original, or a legitimate revival of a design in the public domain

It appears in [your comparison image to Microsoft Consolas](https://i.redd.it/dfvg0s02adj31.png) that the Roman design of DMCA Sans Serif is extremely close to that of Microsoft Consolas, which is not licensed in a way that allows derivative works. Your site also says, `Contact information: Luc(as) de Groot, the original designer of Consolas, whose design is reused by DMCA Sans Serif.`

> The project is developed on Github or similar, with complete corresponding sources

I can't find sources on GitHub.

---

There are also other criteria in that list and via FontBakery. However, it would be important to resolve the issues above before going further into the process.

**Comment by PiotrGrochowski** [comment]
In https://typedesign.netlify.com/fonts.html , it states that all copyrights and registered trademarks related to Type Design are public domain. I am aware of how public domain works and I'm not interested in any other license. And aside from that, public domain can be relicensed to any license in derivative works because public domain has no copyright restrictions.

The font name, DMCA Sans Serif, is inspired by a game named DMCA Royale that attempted to avoid copyright infringement.

DMCA Sans Serif, despite having the same design as Microsoft Consolas, is not a derivative work. The production process is done in such a way that DMCA Sans Serif cannot really be considered a derivative work. Font designs aren't copyrighted.

A font source would only be useful if the font contains manual hinted data. DMCA Sans Serif unfortunately doesn't as of the current version (instead relying on ttfautohint). While the downloads do currently contain sources, they are nearly useless as one could, uh, directly open the ttf files in FontForge, and deleting the source files to work on the ttf files is in fact done multiple times during the font production.

**Comment by PiotrGrochowski** [comment]
You can lock this. I don't need the font on there.

**Comment by PiotrGrochowski** [comment]
You still haven't locked this.
