### ISSUE TITLE
Add Plus Jakarta Sans

### ISSUE THREAD

**Issue by tokotype** [google/fonts#2357]
Hi, We'd like to contribute to adding +Jakarta Sans Project to Google Fonts.
This custom typeface designed for +Jakarta "City Collaboration" branding in 2020 for Provincial Government Jakarta City.
We intended to make this typeface accessible and open-source for the public.

![plusjakartasans](https://user-images.githubusercontent.com/16661219/75091002-44c0cf80-559b-11ea-9b66-d5f043d49a7b.png)

Please take a look initial released at:

Github: https://github.com/tokotype/PlusJakartaSans

Any contributors are welcome.
Cheers!

**Comment by digitaltim-de** [comment]
UP please!

**Comment by yanone** [comment]
Upstream PR: https://github.com/tokotype/PlusJakartaSans/pull/26

**Comment by bogascorp** [comment]
When will this font be available on Google Fonts website?

**Comment by yanone** [comment]
It could be around two weeks maybe. It's now with another team of Google developers who are responsible for the public fonts API, and their work is entirely out of our scope.

**Comment by bogascorp** [comment]
It's Live 😃 
https://fonts.google.com/specimen/Plus+Jakarta+Sans
