### ISSUE TITLE
Google Web Fonts CSS served without Vary header

### ISSUE THREAD

**Issue by Mircho** [google/fonts#236]
Hello,
I have been researching the usage of web fonts and have stumbled on a specific issue. While there is a single css file url (https://fonts.googleapis.com/css?family=Roboto) that, depending on the user-agent header will be different, there is no way for a caching proxy to determine the decisions made by the server to differentiate between browsers.
I think there should be at least this header added to the response of the css file:
Vary: User-Agent

**Comment by rsheeter** [comment]
This is by design. Intent is that the UA caches but no caching proxy does, hence private: `Cache-Control:private, max-age=86400, stale-while-revalidate=604800`
