### ISSUE TITLE
Ethiopic Font

### ISSUE THREAD

**Issue by yosiasz** [google/fonts#2362]
Greetings,

Would like to contribute to adding Ethiopic fonts. I have created one font I would like to submit and more to come now that I am more comfortable using fontforge. What are next steps?

Thanks

**Comment by laerm0** [comment]
Hi there. Ethiopic would be a lovely addition. [This document](https://github.com/google/fonts/blob/master/CONTRIBUTING.md) provides a pretty good roadmap to meeting the spec. Good luck!

**Comment by yosiasz** [comment]
Would Amharic appear on Language drop drop down once a font is approved?  :)

![image](https://user-images.githubusercontent.com/900951/75468459-1bf55d00-5942-11ea-9ea4-d134a9674b35.png)

**Comment by laerm0** [comment]
I'd sure hope so, but that sounds like a @davelab6 or maybe even @rsheeter question. We do need further development of our sub-Saharan glyph coverage, that is absolutely for certain.

**Comment by yosiasz** [comment]
Thanks @laerm0  aka ማይካ ስቱፓክ

**Comment by yosiasz** [comment]
@laerm0 Am I going in the right direction with this?

https://github.com/geeztypes/inku

Not the final product though.

**Comment by laerm0** [comment]
Looks like a good start, @yosiasz. Question: why are there Rubik files in there? Also, your source directory is missing source files.

**Comment by yosiasz** [comment]
Copy pasta, I used Rubik as a starting point. I think it would be good to have a shell sample repo to help guide new submissions?

**Comment by yosiasz** [comment]
I think I have a lot to learn and a lot more to do from the Elstob submission by @psb1558.

**Comment by yosiasz** [comment]
thanks for guidance!
