### ISSUE TITLE
Missing superscripted ™ character

### ISSUE THREAD

**Issue by stuartpb** [google/fonts#237]
The trademark sign glyph (™) appears as an ordinary, full-height "TM" in Roboto.

**Comment by stuartpb** [comment]
Actually, judging by the preview on https://www.google.com/fonts, this character seems to be missing from *all* Google Fonts.

**Comment by qJake** [comment]
There's a more lengthy discussion about this over in #78, check there. :smiley:

**Comment by davelab6** [comment]
Personally I think that yes, this should be added to all fonts and to the latin-ext subset. I'll see what I can do and update 78 :) So closing this for now
