### ISSUE TITLE
Bitter Bold Italic not on Google Fonts

### ISSUE THREAD

**Issue by strawberry-sundae** [google/fonts#2372]
Hi! Just noticed that **Bitter** has only 3 styles (regular, italic, and bold) available on Google fonts. But its repo also has bold italic. Adobe Fonts even has a black weight.

Is there any chance Google Fonts could at least add the bold italic style, please?

Thanks for your time.

**Comment by thlinard** [comment]
Duplicate of #25.

**Comment by strawberry-sundae** [comment]
Oops. Sorry. I did see #25 but didn’t realise it had come to involve more than its title implies. Thank you.
