### ISSUE TITLE
Add new font Inku - Ethiopic

### ISSUE THREAD

**Issue by yosiasz** [google/fonts#2373]
I think this might be ready now

Repo
https://github.com/geeztypes/inku

Sample
https://geeztypes.github.io/inku/

**Comment by yosiasz** [comment]
Let me restart from zero. Now that I understand  bit more.

**Comment by laerm0** [comment]
Aha, okay. I appreciate your patience. Feel free to contact me for help.

**Comment by laerm0** [comment]
Cool @yosiasz , I'll take a look on Monday. 👍

**Comment by yosiasz** [comment]
Hey @laerm0 Hope you are well being in Crooklyn and all. Any news on this?

**Comment by laerm0** [comment]
Hi @yosiasz, sorry for the delay. This does look really good. I'm excited to get this into the directory. I'll give it a more detailed look tomorrow and let you know. Thanks for reminding me. :)

**Comment by yosiasz** [comment]
Hello @laerm0 hope all is well where you are at. Any update on this font?

**Comment by laerm0** [comment]
Oh haha, I got back to you on your repo before I even saw this message. 😁

**Comment by emmamarichal** [comment]
Indeed, and Abyssinica has been started before this one. I close the issue then!
