### ISSUE TITLE
v2 API for old browsers

### ISSUE THREAD

**Issue by vijayaraghavanramanan** [google/fonts#2379]
The new v2 API works for newer browsers which have unicode-range support but on old browsers, adding something like subset=greek,greek-ext,latin-ext doesn't seem to load woff files for those subsets. Only latin basic is loaded.

**Comment by davelab6** [comment]
Thanks for reporting this. The v2 API ought to return the complete file to ensure text is rendered, but this will come at a filesize cost.

**Comment by garretrieger** [comment]
We've updated the v2 API to return the "all" subset for legacy, non unicode range, browsers since it no longer supports the "subset" parameter.
