### ISSUE TITLE
fonts.google.com: variable sliders 

### ISSUE THREAD

**Issue by m4rc1e** [google/fonts#2381]
Adjusting the weight axis on variable fonts causes them to fade. It would be much nicer if users could see the weight change as they adjust the sliders.

![gf_axis_smooth](https://user-images.githubusercontent.com/7525512/76070504-93536e00-5f8c-11ea-8a58-fb2e65881c3e.gif)

My UA is:
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.122 Safari/537.36

**Comment by graphicore** [comment]
Where can I find this control?

**Comment by graphicore** [comment]
Oh, I see I get it in Chromium/Chrome but not in Firefox. Why is this feature crippled on Firefox? :-(

**Comment by felipesanches** [comment]
Yesterday when I tried it I felt the same. It is extremely annoying!

**Comment by m4rc1e** [comment]
AFAIK, VFs are still disabled for Firefox.

**Comment by graphicore** [comment]
Axis Praxis works fine in my Firefox.

**Comment by felipesanches** [comment]
I can confirm it happens on Firefox Quantum 68.4.1esr (64-bit) running on Debian GNU+Linux version 10.

**Comment by thlinard** [comment]
Firefox (73.0.1), Chrome and Safari have the same (correct) behavior on my Mac (macOS 10.4.6).

**Comment by davelab6** [comment]
This should be fixed very soon

**Comment by m4rc1e** [comment]
It's fixed and it looks glorious. Thank you!
