### ISSUE TITLE
How are Font Load Impact Meter values calculated?

### ISSUE THREAD

**Issue by girish-dalvi** [google/fonts#239]
There seems to be a bug in the google font meter, please see https://www.google.com/fonts#UsePlace:use/Collection:Ek+Mukta for Ek Mukta Latin

The actual font size is quite small. Google displays an incorrect value of 143 for a single weight. I don't know how this is calculated, but it is incorrect. The file size is comparable to other Latin fonts, but here it displays a high page load impact, whereas the page load time is not high.

**Comment by davelab6** [comment]
@girish-dalvi do you have opinions about how this should work? :)

**Comment by girish-dalvi** [comment]
Seems to be fixed in the new website.

**Comment by davelab6** [comment]
I'm re-opening this as I would like to better understand how that works.

**Comment by davelab6** [comment]
So, currently it is very simple: the new site just says if you select more than a few styles your are yellow and if too many styles you are red. In the future this could become more sophisticated and at that time I'll endeavor to explain it so type designers know where the bounds are.
