### ISSUE TITLE
Roboto Mono fonts have incorrect `font family name`

### ISSUE THREAD

**Issue by SidShetye** [google/fonts#2394]
This is for the Roboto Mono fonts at https://github.com/google/fonts/tree/master/apache/robotomono

Open any of the variant of that family (e.g. `Light`) in FontForge and go to element (menu bar) -> font info. You'll see 

### Current (wrong) 

Font Family name: `Roboto Mono Light` 

### Expected

Font Family name: `Roboto Mono` 

As all the `Roboto Mono` fonts belong to a single `Roboto Mono` family. This affect all font variant in that family. Other font families may also be impacted, haven't looked.

![image](https://user-images.githubusercontent.com/2595088/76809754-1bb1ea00-67a9-11ea-8914-d22f8a37c13e.png)

**Comment by m4rc1e** [comment]
The names are correct. For non-RIBBI styles (Regular, Bold, Bold Italic), the style name is included in the family name. Open Montserrat and you'll see the same thing. For more info, read this https://docs.microsoft.com/en-us/typography/opentype/spec/name#name-ids especially nameIDs 1, 2, 16, 17
