### ISSUE TITLE
Amatic SC Bold Weight error

### ISSUE THREAD

**Issue by meanthemes** [google/fonts#24]
I'm using Amatic SC and using the 700 (Bold) version via Google Web fonts. It seems to have an error though, a question mark outputs as a (R) registered trademark glyph.

Is this something you are likely to fix or should I switch to the 400 version?

**Comment by davelab6** [comment]
Yes, I'll get this fixed :)

**Comment by meanthemes** [comment]
Lovely thanks Dave :+1:

**Comment by meanthemes** [comment]
Hi Dave, this doesn't appear to be fixed when browsing Google fonts... https://www.dropbox.com/s/xjjdjv6umu1f832/Screenshot%202015-06-29%2010.28.31.png?dl=0

**Comment by davelab6** [comment]
Right, the issue

**Comment by meanthemes** [comment]
Lovely thanks @davelab6

**Comment by jaschaio** [comment]
Seems like things got worse. I just used the normal weight before, but now **both** versions (normal and bold) have the wrong character for the question mark.

![amatic](https://www.dropbox.com/s/l5r10x46qoxphp4/amatic.png?dl=0)

Thanks for your effort

**Comment by meanthemes** [comment]
Oh no! I can verify this too...

https://www.dropbox.com/s/683qwjmpge2i5de/Screenshot%202015-07-23%2014.56.46.png?dl=0

Please can this be fixed as soon as physically possible (at least just reverting the normal weight would be good)

**Comment by rsheeter** [comment]
I'm not seeing this. Are the steps to reproduce just:

1. Load https://www.google.com/fonts
1. Filter to Amatic
1. Change preview text to ??

And then it renders the wrong symbol? If so, what OS, browser(s) and versions?

**Comment by meanthemes** [comment]
Chrome Version 44.0.2403.89 (64-bit)

Mac 10.10.4

**Comment by meanthemes** [comment]
Update: It looks like a Mac only issue... it's doing it on latest Chrome, Firefox and Safari.

Windows using IE11 is fine, Chrome on Windows is fine.

**Comment by rsheeter** [comment]
Ty for the update. Curiously I am not experiencing this on Chrome Version 44.0.2403.89 beta (64-bit). I tried on OSX 10.10.4 (14E46) and Ubuntu 14.04.

**Comment by meanthemes** [comment]
Have you tried Safari and Firefox?

**Comment by jaschaio** [comment]
I get the error on ** MacOS X 10.10.4 with Chrome 44.0.2403.89 ** as well with Safari 8.0.7 and Firefox 39.0

Tried it as well with a Windows 7 PC and Firefox, same issue. But just with the normal weight.

**Comment by rsheeter** [comment]
Interesting. I tried on Firefox 38.0 and Safari 8.07 without observing the problem.  @davelab6, I'm curious if you can reproduce?

**Comment by davelab6** [comment]
I think you guys have the old version installed. Uninstall it and let us
know how it goes please :)

**Comment by jaschaio** [comment]
Haven't thought of that before. Removed the font from the system and now its looking like it should. Sorry and thanks for the great work!

**Comment by davelab6** [comment]
Okay great!

**Comment by meanthemes** [comment]
Sorry to waste your time @davelab6 and @rsheeter - fonts uninstalled and its working beautifully! Thanks for updating the bold ? :)

**Comment by davelab6** [comment]
Thanks for taking the time to help us! :) Glad we finally got it resolved!

**Comment by webelikka** [comment]
Hi!

I seem to have the same issue as above with the regual font turning out bold. But only for Chrome..... how do I fix this?

**Comment by Azaahhh** [comment]
I can confirm this also webelikka - Chrome 44.0.2403.157 m Win and OSX. Other browsers render it ok.

**Comment by studioorangeNL** [comment]
also the character 
é is strange on any apple device, despite weight value. no issues on my linux device using chrome

**Comment by m4rc1e** [comment]
@studioorangeNL Create a new issue and submit a jsbin and screenshot

**Comment by Deresnoreau** [comment]
So, april 2018 and the issue still doesn't appear to be solved. 
The same issue happens in Adobe Photoshop/Illustrator. Is this been looked into?

**Comment by m4rc1e** [comment]
![screen shot 2018-04-23 at 09 07 25](https://user-images.githubusercontent.com/7525512/39114118-c68cce3c-46d5-11e8-8b45-73dd1191fa18.png)

@Deresnoreau do you have the older version installed locally?

**Comment by globalcow** [comment]
I just downloaded the bold font version from Google Fonts and the question mark is wrong locally on my computer. It seems the downloadable file from Google is older than the web version.

**Comment by pierrotte** [comment]
This is still happening in the bold version in 2021.
