### ISSUE TITLE
Issue in Arabic Font: Aref Ruqaa

### ISSUE THREAD

**Issue by malkhuzayyim** [google/fonts#2408]
Hi,

Using this font: https://fonts.google.com/specimen/Aref+Ruqaa?subset=arabic

On iOS latest version has a certain issue in one of the forms of the letter ك
Check the codepen link on any iphone to see what I'm talking about: https://codepen.io/malkhuzayyim/pen/ExjBKwy?editors=1100

Not sure if this is the correct place to report such issues, if not please let me know who to contact about this.

**Comment by thlinard** [comment]
Hi,

You can report this issue here: https://github.com/alif-type/aref-ruqaa/issues

**Comment by malkhuzayyim** [comment]
Awesome thank you.
