### ISSUE TITLE
Update Viaodalibre font family (1.000 -> 2.000) 

### ISSUE THREAD

**Issue by bettergui** [google/fonts#2419]
We would like to update this font family. Thanks to your helps launching earlier this year, we have achieved 100K+ font served and 900 sites featured within 3 months. Since then, we have collected and addressed user inputs, including your feedback in #2241.

Pull request: https://github.com/google/fonts/pull/2418
Repo & changelog: https://github.com/bettergui/ViaodaLibre

Changes summary:
- The number of glyphs increased to 898.
- Simplified the previously decorated O and H and instead created two stylistic sets for such glyphs. (@m4rc1e , check out the cleaner default O: https://github.com/bettergui/ViaodaLibre/blob/master/samples/5.png?raw=true )
- Refined kerning for Latin and Cyrillic sets.
- Tweaked punctuation.

**Comment by davelab6** [comment]
Thanks @bettergui and thank you for your patience! I expect @RosaWagner will be able to review and update this family in the next few weeks :)

**Comment by RosaWagner** [comment]
Oh but apparently it has already been updated ! See merge https://github.com/google/fonts/pull/2418
So I close this issue ;)
