### ISSUE TITLE
How to solve this error?

### ISSUE THREAD

**Issue by toplisek** [google/fonts#243]
`Error: downloadable font: gasp: changed the version number to 1 (font-family: "Quicksand" style:normal weight:normal stretch:normal src index:2) source: https://fonts.gstatic.com/s/quicksand/v5/....woff2
Source File: https://fonts.googleapis.com/css?family=Quicksand
Line: 2, Column: 12
Source Code:
@font-face {   font-family: "Quicksand";   font-style: normal;   font-weight: 400;   src: local("Quicksand Regular"), local("Quicksand-Regular"), url("https://fonts.gstatic.com/s/quicksand/v5/....woff2") format("woff2");   unicode-range: U+0-FF, U+131, U+152-153, U+2C6, U+2DA, U+2DC, U+2000-206F, U+2074, U+20AC, U+2212, U+2215, U+E0FF, U+EFFD, U+F000; }

As I understand I have put the correct code as instructions per Google system:
css?family=Quicksand"`

How to solve such constant error? Need help.

**Comment by davelab6** [comment]
Where do you see this error?

**Comment by toplisek** [comment]
It is an error at websites (hidden due to security).

**Comment by ppfeufer** [comment]
I do have the same issue with a different font ....

> downloadable font: gasp: changed the version number to 1 (font-family: "Amethysta" style:normal weight:normal stretch:normal src index:2) source: http://fonts.gstatic.com/s/amethysta/v4/uuO0VFu8kdKx34ju6adj-FtXRa8TVwTICgirnJhmVJw.woff2

**Comment by rsheeter** [comment]
Couple of questions:
*  Does the font still render or does the browser use the next font in the fallback chain?
*  What browser(s) do you see this with? 
*  If the specific website cannot be shared, would it be possible to build a tiny jsbin reproduction?

**Comment by ppfeufer** [comment]
The font does render as it seems and it seems to be only appearing in Firefox. At least that's what I figured so far. The project where I have the issue is at the moment in a very early dev stage, so I can't provide any stuff to shar for now.

**Comment by inovek** [comment]
NoScript causes this error. If you disable it, you will see that no error will occur.

**Comment by ppfeufer** [comment]
Not using NoScript or any similar addons ...

**Comment by toplisek** [comment]
Maybe Google can help.

**Comment by Friksel** [comment]
Having the same issue here with a different font. Also using unicode-range btw.

**Comment by m4rc1e** [comment]
I can't replicate this error in Mac Os X 10.12.4, Firefox 53.0.3

Made up a JSBin:
http://jsbin.com/laloliwufo/edit?html,output

Would be keen for others to try this out as well

**Comment by laerm0** [comment]
I can't replicate this error in Chrome 60.0.3112.113 and FF 55.0.3 on OS X 10.12.16 and Win 10.

I'll leave it open for now in case anyone wants to report they still have this issue.

**Comment by davelab6** [comment]
As we can't replicate, I'll close. Please re-open if this is still an issue

**Comment by Sbu-05-exe** [comment]
I have replicated this issue on firefox

**Comment by TheOldMan2000** [comment]
I'm seeing this in the Console on the latest Firefox 117.0.1 (64-bit) on Windows 11, it is marked as a Warning:

`downloadable font: gasp: Changed the version number to 1 (font-family: "Creepster" style:normal weight:400 stretch:100 src index:2) source: https://fonts.gstatic.com/s/creepster/v9/AlZy_zVUqJz4yMrniH4Rcn35.woff2`
