### ISSUE TITLE
Inter Line Height Issues (Firefox)

### ISSUE THREAD

**Issue by rexdesigndk** [google/fonts#2433]
**Describe the bug**
For some reason Inter from Google fonts have line height inconsistencies on Firefox. I've tested on multiple pc's and the issues consist. 

Other fonts doesn't have this issue. The issues only appears to happen in Firefox with Inter.

**To Reproduce**
1. Go to [Example 1](https://shop.rexdigital.group/ ) using Firefox. 
2. Inspect the buttons with the dev tool. You can clearly see that the whitespace isn't even.
3. The issue happens no matter the line height settings.

**Environment**
- OS: Windows 10 Pro 1909
- Firefox/Firefox Developer

**Comment by thlinard** [comment]
The example you give uses Archivo…

**Comment by rexdesigndk** [comment]
Ye sorry i just switched font. Didn't wanna leave it as it was on a live website.
