### ISSUE TITLE
Add new font - Kumbh Sans

### ISSUE THREAD

**Issue by xconsau** [google/fonts#2442]
Hello,

Please find my submission "Kumbh Sans" to be considered for the Google Fonts Collection.

Project URL: https://github.com/xconsau/KumbhSans

The font has been tested from my side as per Google Fonts [Project Specification](https://github.com/googlefonts/gf-docs/tree/master/Spec).

I would like to get design assistance, suggestions and refinement feedback from the staff and the community. I envision to include more variants for weight like 300 and 600 for this font. Any suggestions and feedback on the design is most welcome.

**Comment by davelab6** [comment]
@xconsau thanks for submitting this, and preparing a repo that meets our latest Spec docs. I spoke to @graphicore today about it, and we hope to onboard the font in the next few weeks.

**Comment by xconsau** [comment]
Thanks very much, Dave. Appreciate your response and consideration.

**Comment by graphicore** [comment]
There's a work in progress PR: https://github.com/google/fonts/pull/2526 @xconsau let's coordinate this in the upstream repo: https://github.com/xconsau/KumbhSans/issues/1
