### ISSUE TITLE
Jost doesn't allow italics along with regular weights

### ISSUE THREAD

**Issue by ddamato** [google/fonts#2445]
Here's a [codepen](https://codepen.io/fauxserious/pen/ExVbzGN?editors=0100) outlining the issue.

In an attempt to have the variable font Jost load with a range of weights between 300 and 800 along with an (or any) italic weight. The italic glyphs don't render along with the regular font. If I swap this out for Muli, everything works as expected (italics are applied to `<em>` elements, for example). This is the request for Jost and Muli from the codepen example.

```
https://fonts.googleapis.com/css2?family=Jost:ital,wght@0,300..800;1,400&family=Muli:ital,wght@0,300..800;1,400&display=swap
```

Italics only seems to work if it's not requested with any normal file.
```
https://fonts.googleapis.com/css2?family=Jost:ital,wght@1,700&display=swap
```

So the workaround right now is to request them separately but that sounds like an anti-pattern given the nature of variable fonts.

**Comment by m4rc1e** [comment]
Thanks for the testcase.


Ok, I've worked out what's happened. We were meant to [push](https://github.com/google/fonts/pull/2338#issuecomment-611392662) this family without the italic instances enabled since Chrome doesn't handle the "ital" font axis yet. You'll notice that your codepen does work in Safari.

We'll re-enable the Italic instances once Chrome has better support.

**Comment by m4rc1e** [comment]
Fixed fonts are live, https://fonts.google.com/specimen/Jost?vfonly

**Comment by ddamato** [comment]
> Thanks for the testcase.
> 
> Ok, I've worked out what's happened. We were meant to [push](https://github.com/google/fonts/pull/2338#issuecomment-611392662) this family without the italic instances enabled since Chrome doesn't handle the "ital" font axis yet. You'll notice that your codepen does work in Safari.
> 
> We'll re-enable the Italic instances once Chrome has better support.

I was expecting to handle this in a similar way to the [author's site](https://indestructibletype.com/Jost.html). 
```css
em {
  font-variation-settings: "ital" 1.00;
}
```

Works in Chrome just fine? I just wish a woff2 version of the variable font was offered. Any conversion of the .ttf file I try loses all the axes.

**Comment by ddamato** [comment]
Another possibility in my case is to just use the faux-italics. I didn't realize that Chrome (& Edge) don't display the browser rendered italics, but Firefox and Safari do.

Chrome: https://share.getcloudapp.com/RBuvoGL0
Firefox: https://share.getcloudapp.com/o0ugr2Pg
Safari: https://share.getcloudapp.com/wbu0RGbw
