### ISSUE TITLE
Roboto & Open Sans

### ISSUE THREAD

**Issue by isacfadoni** [google/fonts#245]
Hello, I'm having trouble when trying to find Roboto & Open Sans font families.

**Comment by davelab6** [comment]
Please could you be more specific about what kind of trouble you are facing? :)

**Comment by isacfadoni** [comment]
I need to download these fonts, but I can't find it. I've tried to explore `ofl/` and search for Roboto and Open Sans, but look like it's missing.

**Comment by davelab6** [comment]
They are in `/apache/`

**Comment by isacfadoni** [comment]
My bad!
