### ISSUE TITLE
Heebo font has some missing characters

### ISSUE THREAD

**Issue by richardhsueh** [google/fonts#2453]
https://fonts.google.com/specimen/Heebo?preview.text=,+_+%60&preview.text_type=custom&sort=popularity&query=heebo

all these character will display a square block, please take a look
![Screenshot 2020-05-14 at 12 45 36 PM](https://user-images.githubusercontent.com/33024986/81893759-dbbc8700-95e0-11ea-9bd0-e719dee60d6f.png)

**Comment by FabianRohr** [comment]
Same here. The characters appear in the middle of the words for some reason: https://stackoverflow.com/questions/61791348/heebo-google-font-special-characters-appearing-strangely

<img width="595" alt="Screenshot 2020-05-14 at 09 51 44" src="https://user-images.githubusercontent.com/51318890/81907808-a146f000-95c8-11ea-9c66-3c034949d746.png">

**Comment by Hillcow** [comment]
Same here. Also the missing characters are displayed in the middle of the words:

<img width="595" alt="Screenshot 2020-05-14 at 09 51 44" src="https://user-images.githubusercontent.com/20979750/81907988-e10dd780-95c8-11ea-9342-7d2553b4c427.png">

Thread on StackOverflow: https://stackoverflow.com/questions/61791348/heebo-google-font-special-characters-appearing-strangely

**Comment by mike-roberts-ps** [comment]
Bump on this. We are experiencing the same issue in various environments.

**Comment by Peuge** [comment]
We are experiencing the same issue
![image](https://user-images.githubusercontent.com/52314048/81910560-6777e880-95cc-11ea-9c17-1af13e2b3bda.png)

**Comment by richardhsueh** [comment]
https://github.com/google/fonts/pull/2444
I suspect the recent update on Heebo is related to this problem, so I have commented on the pull request, hopes the developer can help to take a look. 🤞

**Comment by m4rc1e** [comment]
Can confirm the issue. Will request a roll back asap.

**Comment by martin-christensen** [comment]
> Can confirm the issue. Will request a roll back asap.

@m4rc1e do you know when this will happen? We are also seeing major issues on sites using Heebo.

**Comment by aleehedl** [comment]
We are also experiencing this in production.

**Comment by m4rc1e** [comment]
We're working on the rollback. I'll keep you all updated. Apologies for the inconvenience.

**Comment by martin-christensen** [comment]
Thanks @m4rc1e, much appreciated!

**Comment by mike-roberts-ps** [comment]
Thanks @m4rc1e !

**Comment by jordanrolph** [comment]
Thanks @m4rc1e

**Comment by davelab6** [comment]
Roll back underway, should take up to 12 hours to complete.

**Comment by yhilcenko** [comment]
We are also facing the same problem. Thanks @m4rc1e

**Comment by m4rc1e** [comment]
Issue has been diagnosed and apologies for letting this slip through. We'll write a unit test to catch this issue so it doesn't happen in future font pushes.

I really appreciate everyone's kind words as well.

**Comment by dymond** [comment]
@m4rc1e @davelab6 Thanks for the quick update!

**Comment by richardhsueh** [comment]
@m4rc1e Thank you very much !

**Comment by jazzyclimber** [comment]
I am not quite sure where we are in the process of rollbacks. But It looks like there is still and issue with the commas

![2020-05-14_09-39-36](https://user-images.githubusercontent.com/39243773/81950727-f5060900-95c9-11ea-93f4-a927c451d42b.png)

**Comment by jameshoftonspd** [comment]
I am also getting the same problem in Chrome, but seems ok in IE 11

**Comment by m4rc1e** [comment]
@jazzyclimber rollback still hasn't finished. I'll post here once it's done.

**Comment by jazzyclimber** [comment]
@m4rc1e As with everyone else - The fast response on this one is really appreciated!

**Comment by garretrieger** [comment]
The rollback is complete now. You may need to clear your browser cache to get updated CSS as the CSS caches for a day by default.

**Comment by martin-christensen** [comment]
@m4rc1e still seeing problems with the Open Sans font. On mobile devices, it doesn't show hyphens right, but rather show them as underscores. Here is an example and make sure you check it on an actual mobile device: https://www.nyhavn.dk/mexico/rejser/all-inclusive-og-snorkling-i-skildpaddebugten

Also here is an image of the problem,
![IMG_D4290A870898-1](https://user-images.githubusercontent.com/27727657/82189804-4b3bba80-98f0-11ea-9de4-954f788f560b.jpeg)

**Comment by m4rc1e** [comment]
@martin-christensen I'm not able to replicate the issue with a minimal jsbin, https://jsbin.com/daviyuqaji/edit?html,output
