### ISSUE TITLE
Asap TTFs downloaded from Google Fonts print umlauts offset to the left

### ISSUE THREAD

**Issue by davelab6** [google/fonts#2454]
>>> We are using the font „Asap“ for a new magazine design. During the work progress we recognized that the font causes problems with InDesign and some laser printers…: the i-points and points of German „Umlauts“ don't fit and „move“ to the right. How can we solve this problem?
>>>
>>> ![IMG_6222](https://user-images.githubusercontent.com/261579/81928022-98e3ba80-95b2-11ea-9404-3f0b090018cb.jpeg)
>>
>> Can you try to uninstall the version you have used, delete it from your computer and try to download [this version](https://github.com/Omnibus-Type/Asap/tree/master/fonts/otf) (OTFs) and reinstall it?
>
> YES!!! Now it works! We reinstalled the new version. Thanks so much for saving us so immediately ;-)

I see there are a few other issues reported here with the Asap family, and https://github.com/Omnibus-Type/Asap/issues is otherwise clean :) 

https://github.com/google/fonts/issues/240

https://github.com/google/fonts/issues/2436

https://github.com/google/fonts/issues/1190

And likely related closely, https://github.com/google/fonts/issues/1370

**Comment by m4rc1e** [comment]
cc @moyogo

**Comment by moyogo** [comment]
This is probably a bug in printer’s TrueType implementation triggered by the nested components.

/idieresis is composed of /dotlessi and /dieresiscomb, while /dieresiscomb is composed of /dieresis which has an outline.

Flattening the nested components may fix this, meaning having /idieresis composed of /dotlessi and /dieresis directly. Ufo2ft has a filter for this.

We need a Fontbakery check for this.
