### ISSUE TITLE
Add new font - Iconique Sans

### ISSUE THREAD

**Issue by ngmtuan** [google/fonts#2475]
Hello,

Please find my submission "Iconique Sans" to be considered for the Google Fonts Collection.
Project URL: https://github.com/ngmtuan/IconiqueSans

This is my second typeface. I want to make this typeface accessible and open-source for the public.

Thank you!

![Creative Market-03](https://user-images.githubusercontent.com/60652024/83008205-083fbc80-a03f-11ea-8e07-724eac23e788.png)

**Comment by ogxn** [comment]
nice font 👍
