### ISSUE TITLE
Is subset parameter deprecated ?

### ISSUE THREAD

**Issue by CodeExplore** [google/fonts#2480]
I am looking for subset parameter when added a font in https://fonts.google.com/ but can not see..

```html
https://fonts.googleapis.com/css2?family=Roboto:wght@100&display=swap
```

Do not we need that in this new css2 api ?

**Comment by JanisE** [comment]
The developer API still has `subset` parameter listed. Apparently, it's available if you use JSON API requests with the access key.

https://developers.google.com/fonts/docs/developer_api#details

**Comment by esaesa** [comment]
> The developer API still has `subset` parameter listed. Apparently, it's available if you use JSON API requests with the access key.
> 
> https://developers.google.com/fonts/docs/developer_api

This is v1 not v2

**Comment by StreetStrider** [comment]
For some reason there is no `subset` in css v2 api. I see the only possible substitution in `text` option. For latin you can append `&text=thequickbrownfoxjumpsoverthelazydog` to your font uri. However, this is not an absolutely convenient option, as `subset` was. It would be much harder to specify non-latin ranges via this option.

**Comment by garretrieger** [comment]
The subset parameter has been long deprecated and on modern browsers which support unicode range (https://developer.mozilla.org/en-US/docs/Web/CSS/@font-face/unicode-range, https://caniuse.com/?search=unicode-range) it will be ignored. The CSS API uses unicode-range to list out all of the possible subsets supported by each family and then your browser will download subsets as needed if code points are present that intersect with their covered unicode range.

**Comment by imnasnainaec** [comment]
For reference: https://developers.google.com/fonts/docs/getting_started#specifying_script_subsets
