### ISSUE TITLE
'fijn' looks suboptimal in Niramit

### ISSUE THREAD

**Issue by WouterrV** [google/fonts#2484]
See: 
https://fonts.google.com/specimen/Niramit?preview.text=Most+words+look+fine+(hijacked,+multijet)+but+this+dutch+word+not+so+much:+fijnstof&preview.text_type=custom

Is there anything you/I can do about this?

**Comment by driehuis** [comment]
You seem to be getting bitten by the f-i ligature. If you have control over the OpenType features you're using, you could consider disabling the "liga" feature (in CSS, you could try this:)

    .dutch {
        font-variant-ligatures: none !important;
        font-feature-settings: "liga" 0 !important;
    }

As usual, the vagaries of both CSS and OpenType implementation details can still throw a spanner in the works, but I checked Niramit actually implements the "liga" feature.

**Comment by WouterrV** [comment]
Ah, thanks a bunch! That solves it, good idea on using it only for Dutch.
