### ISSUE TITLE
Neuton font is again displaying &nbsp; much wider than a space

### ISSUE THREAD

**Issue by triblytree** [google/fonts#2496]
This was discussed and fixed previously it looks like: https://github.com/google/fonts/issues/347

But seems to be happening again. Here's the old JS Fiddle which had the fix (but now shows the wide space):

https://jsfiddle.net/tg67akud/2/

![neutron-space](https://user-images.githubusercontent.com/5131905/84428160-ddc33700-abda-11ea-8580-dca00cbf9357.jpg)

**Comment by m4rc1e** [comment]
This family was last updated Nov 2019. It looks fine to me.

<img width="313" alt="Screenshot 2020-06-12 at 08 49 59" src="https://user-images.githubusercontent.com/7525512/84478773-c0997180-ac89-11ea-98f1-604f46d2f3c7.png">


Have you got a copy installed locally?

**Comment by triblytree** [comment]
Here's an example:

https://www.mydarlingvegan.com/test-nbsp/

![nbsp](https://user-images.githubusercontent.com/5131905/84524041-24be3480-ac8e-11ea-8737-2aceee54eadd.jpg)

The font is included via Google Font's URL:

https://fonts.googleapis.com/css?family=Neuton%3Aregular%2Citalic%2C700%2C200%2C300|Open+Sans%3Aregular%2Citalic%2C700%2C200%2C300%2C300italic%2C900&display=swap&subset=latin

So it's not installed locally.

Tested in both Chrome and Firefox and it appears on both.

**Comment by thlinard** [comment]
Your test page looks fine on Firefox, Safari, Chrome. Perhaps you should check again a local installation.

**Comment by triblytree** [comment]
Ahh, I see. It was a version I had installed locally on my computer. My bad. Thanks for looking into it!
