### ISSUE TITLE
Open Sans - font stack fallback

### ISSUE THREAD

**Issue by robertkern** [google/fonts#250]
Non-latin characters don't seem to fall back to the next font in the font stack.

Example: http://codepen.io/anon/pen/PNrONX

```
@import url(http://fonts.googleapis.com/css?family=Open+Sans);

* {
  font-family: 'Open Sans', arial, sans-serif;
}
```

I would expect characters that aren't available in the Open Sans font to try and use the next font in the stack, but with Open Sans it just displays the question mark in a box glyph. Is there any way around this as it makes the font unusable on a website that has a mix of languages.

**Comment by davelab6** [comment]
Could you send a screenshot and confirm what platform/browser versions you see this?

**Comment by robertkern** [comment]
Sorry yes on Mac OS X using Chrome 50.0.2661.102

Chrome screenshot: 
![image](https://cloud.githubusercontent.com/assets/2150042/15415210/453e451e-1e95-11e6-8357-1d6c9f13ac1e.png)

But it does actually work fine on Safari v9.1.1: 
![image](https://cloud.githubusercontent.com/assets/2150042/15415220/5b3c8ae2-1e95-11e6-9705-c9373081d0a7.png)

I should have checked in other browsers first sorry as maybe it's more an issue with Chrome than the font.

**Comment by davelab6** [comment]
Chrome Version 52.0.2740.0 canary (64-bit) on OS X 10.11.4 (15E65):

![screen shot 2016-05-19 at 22 24 27](https://cloud.githubusercontent.com/assets/261579/15415415/867795ec-1e10-11e6-9049-f2fa630958ef.png)

**Comment by robertkern** [comment]
Weird - on Chrome 52.0.2741.0 canary (64-bit) on OS X 10.11.5 (15F34) it still looks wrong:

![image](https://cloud.githubusercontent.com/assets/2150042/15415557/71f17c6e-1e97-11e6-8468-c306e73af2e4.png)

**Comment by davelab6** [comment]
Do you have it installed (check ~/Library/Fonts)

**Comment by robertkern** [comment]
I was just about to say it's definitely not installed locally because I can't find it anywhere  (either in ~/Library/Fonts or Font Book or searching in Finder), but using the following (removing the `local()`) does work correctly. So somehow and somewhere yes i must have it installed sorry. Where the heck it is i'm not sure.

```
@font-face {
  font-family: 'Open Sans';
  font-style: normal;
  font-weight: 400;
  src: url(http://fonts.gstatic.com/s/opensans/v13/cJZKeOuBrn4kERxqtaUH3ZBw1xU1rKptJj_0jans920.woff2) format('woff2');
}
```

**Comment by robertkern** [comment]
Ok I've found the issue - Adobe Creative Cloud had Open Sans installed via Typekit. I have removed it from their app and it's now working correctly in Chrome.

Thanks for your help and I apologise for taking your time!
