### ISSUE TITLE
Update Spartan, fixing «» interpolation issues

### ISSUE THREAD

**Issue by marekjez86** [google/fonts#2505]
Spartan font has issues with the right angle quote (raquo) for wght=200,300,400, please see:
https://fonts.google.com/specimen/Spartan?preview.text=%C2%ABSample%C2%BB&preview.text_type=custom#standard-styles

<img width="270" alt="Screen Shot 2020-06-15 at 08 55 44" src="https://user-images.githubusercontent.com/13322623/84810649-7df4d380-afc0-11ea-9b0d-c8cbd14ebec0.png">

**Comment by thlinard** [comment]
The interpolation issue is between Thin and Regular masters for `»`, but there is also an interpolation issue between Regular and Black masters for `«`:

https://fonts.google.com/specimen/Spartan?preview.text=%C2%AB%C2%BB&preview.text_type=custom#standard-styles

**Comment by davelab6** [comment]
I think this is fixed in https://github.com/MattBaileyDesign/Spartan-MB/tree/V-1.006 so we should upgrade to that

**Comment by RosaWagner** [comment]
Since we de-listed spartan to the benefit of Ligue Spartan, I guess we can close all spartan related issues
