### ISSUE TITLE
Source Serif Pro - Outdated

### ISSUE THREAD

**Issue by benedictjohannes** [google/fonts#2516]
The Source Serif Pro in google fonts catalog has only limited weights: 400,600,700.
However, the Adobe's [repo](https://github.com/adobe-fonts/source-serif-pro) has released regular, extra light, light, semibold, bold and black (also with italics for each weights).

The Google web font of Source Serif should be updated. I noticed that the updated binaries are available in this repo, but it is not available on [fonts.google.com](https://fonts.google.com). How is this repo pulled into the online available fonts?

**Comment by fitojb** [comment]
See https://github.com/google/fonts/pull/2498#issuecomment-644168694

**Comment by benedictjohannes** [comment]
Thanks for pointing on the PR, @fitojb 
should this issue be kept open until. It's merged and available in the online font catalog?

**Comment by fitojb** [comment]
After new fonts are merged, they go to an internal sandbox for testing and are then deployed to the public site. In particular cases, the process may be delayed due to issues in the fonts.

Yes, I’d say close this duplicate bug and wait for the deployment to happen.

**Comment by benedictjohannes** [comment]
Thanks for your explanation, I'm closing this.
