### ISSUE TITLE
Source Code Pro version used contains graphical glitches; time for an upgrade?

### ISSUE THREAD

**Issue by WillemMali** [google/fonts#252]
Hi,

I was browsing the Rust docs, and encountered this weird bug:

![untitled](https://cloud.githubusercontent.com/assets/4689687/15573739/384f30da-2349-11e6-8895-4f912311a836.png)

On this page:

https://nercury.github.io/di-rs/di/struct.Deps.html

Those distorted characters are bold `&` character; the bug occurs on the latest Chrome.

Then I found two related on Rust's issue tracker:

https://github.com/rust-lang/rust/issues/24355
https://github.com/rust-lang/rust/issues/16372

Turns out, it's caused by an issue in Source Code Pro, which has been fixed in a newer version:

https://github.com/adobe-fonts/source-code-pro/issues/11

So could you update to a newer version of Source Code Pro, 1.010 or later?

**Comment by WillemMali** [comment]
Hi @davelab6 , could you perhaps post an update on whether this issue was resolved? Or a rough timeline for the fix?

**Comment by m4rc1e** [comment]
Closing, family on GF is newer than v1.010, it is v1.017.
https://fonts.google.com/specimen/Source+Code+Pro

I also can't replicate this issue in Mac OS X Chrome
![screen shot 2017-06-15 at 12 33 00](https://user-images.githubusercontent.com/7525512/27179503-d5d80636-51c6-11e7-8a55-6b9bd727d93b.png)

https://jsbin.com/rugegaveyo/edit?html,output
