### ISSUE TITLE
Mohamed Gaber is not properly credited for fonts he designed and maintains

### ISSUE THREAD

**Issue by eliheuer** [google/fonts#2535]
As of July 7th, 2020 I have observed the following issue when using https://fonts.google.com.

Cairo is still listed as designed by "Multiple Designers", despite [Mohamed Gaber](https://gaber.design/) being the primary designer and maintainer of the upstream repository: https://github.com/Gue3bara/Cairo

There have been a few pull requests and issues in the past trying to fix this:

1. https://github.com/google/fonts/pull/2450
2. https://github.com/google/fonts/pull/2337
3. https://github.com/google/fonts/pull/2380

![cairo-issue-01](https://user-images.githubusercontent.com/5162664/86824204-b1b49d80-c042-11ea-8933-d87095173134.png)

Searching for "Mohamed Gaber" on Google Fonts returns no results, despite the Google Fonts collection containing a few different fonts primarily designed and maintained by Mohamed Gaber...

![cairo-issue-02](https://user-images.githubusercontent.com/5162664/86824646-48815a00-c043-11ea-9538-6c380deca57c.png)

However, searching for designer "Khaled Hosny" returns a collection of properly credited typefaces. This is the expected behavior when searching for "Mohamed Gaber".

![cairo-issue-03](https://user-images.githubusercontent.com/5162664/86824781-72d31780-c043-11ea-9066-9baf25264a41.png)

**Comment by davelab6** [comment]
Thanks @eliheuer 

Merged #2535 - Cairo should be updated with this next week :)

**Comment by davelab6** [comment]
Keeping open until this is verified in production

**Comment by m4rc1e** [comment]
Designers have been updated.

https://fonts.google.com/specimen/Cairo?query=cairo

**Comment by eliheuer** [comment]
Good news @Gue3bara, sorry it took so long to fix this. Thanks Dave and Marc!

**Comment by eliheuer** [comment]
Cairo works as expected, thanks again! But El Messiri and Lemonada are still listed as "Multiple Designers" only. So searching for "Mohamed Gaber" on Google Fonts now only returns Cairo. El Messiri and Lemonada are all primarily designed by Mohamed Gaber if i'm not mistaken or missing another typeface he designed. I can try another PR for these like the one that was recently merged.

**Comment by Gue3bara** [comment]
> Cairo works as expected, thanks again! But [El Messiri](https://fonts.google.com/specimen/El+Messiri) and [Lemonada](https://fonts.google.com/specimen/Lemonada) are still listed as "Multiple Designers" only. So searching for "Mohamed Gaber" on Google Fonts now only returns Cairo. El Messiri and Lemonada are both primarily designed by Mohamed Gaber as well.
> 
> At commit [30383ff](https://github.com/google/fonts/commit/30383ff64d1f7e3019d70c1a9dd6bda8baebc400) the designer metadata for El Messiri and Lemonada seems to be set up correctly, but still show up incorrectly on the site.
> 
> <img alt="screenshot" width="356" src="https://user-images.githubusercontent.com/5162664/87821820-51351580-c825-11ea-96cd-4af843546270.png">

@m4rc1e this issue is still standing is there any update?
