### ISSUE TITLE
Update Muli to include full family

### ISSUE THREAD

**Issue by corygibbons** [google/fonts#255]
Currently only two weights of the full family are represented, is it possible to get the remaining ones added?

[vernnobile/MuliFont](https://github.com/vernnobile/MuliFont)

**Comment by davelab6** [comment]
Will do :)

**Comment by Txonliz** [comment]
It seems that something went wrong in the last update of Muli. Muli Regular is now slanted, as a "faux italic" and Muli italic seems quite heavier than the regular (See: https://www.google.com/fonts/specimen/Muli)

It is ok in the new site of Google fonts (See: https://fonts.google.com/?query=Muli) but I don't find the way to link my styles to the fonts in that site (?). My whole website is now displaying a italic font...

**Comment by davelab6** [comment]
@Txonliz did you check to see if the font is installed? There is a long standing Chrome bug with this

**Comment by Txonliz** [comment]
Yes! That was it!!! Thanks Dave!

**Comment by johnknoop** [comment]
@davelab6 When do you reckon the rest of the styles will show up on Google Fonts?

**Comment by johnknoop** [comment]
@davelab6 Is there any plans to make this happen?

**Comment by fitojb** [comment]
@johnknoop This font, as well as many others, are being upgraded (character set expansion, design refinements, etc.) and processed to ensure they are bug-free. This is not something that can be achieved in a day's sitting. You can follow the team's progress in the `googlefonts-discuss` mailing list at Google Groups.

**Comment by davelab6** [comment]
@johnknoop I can't comment on timelines, sorry :/

**Comment by m4rc1e** [comment]
Closing this.

All 14 styles were add back in December 2016, #663 

![screen shot 2017-06-13 at 12 02 19](https://user-images.githubusercontent.com/7525512/27079611-372b42ec-5030-11e7-8aaa-92d921990007.png)
