### ISSUE TITLE
[Montserrat] Support for tabular number spacing limited to 700 weight

### ISSUE THREAD

**Issue by lachieh** [google/fonts#2553]
Tabular spacing seems to be limited to the 700 weight:

Here is the 500 weight:
<img width="263" alt="Screen Shot 2020-07-16 at 8 11 38 PM" src="https://user-images.githubusercontent.com/1687902/87734436-9c591500-c7a0-11ea-85a4-8c580ed84610.png">

Here is the 700 weight:
<img width="276" alt="Screen Shot 2020-07-16 at 8 11 31 PM" src="https://user-images.githubusercontent.com/1687902/87734475-b72b8980-c7a0-11ea-9d04-496e121a8daf.png">

Notice that the widths of each number are inconsistent (i.e. not good for tabular data). On the 700 example, the percentage signs are all aligned, 500 they are not. I have not looked at any of the other OpenType features to check if this is just tabular data or not.

Live test case:
https://codepen.io/lachieh/pen/yLeRqEw/left/

**Comment by thlinard** [comment]
Hi,

All the boxes have aligned figures in my browser.

- Uninstall any local copy.
- Don't use https://fonts.gstatic.com (and moreover, you mix the versions: v10 in a place in your code, v12 in the url, and v14, the current version, the one you get by https://fonts.googleapis.com).

**Comment by lachieh** [comment]
Thanks, I've updated the code to use the latest CSS import from fonts.google.com. I did have a local version of Montserrat bold installed, so I've removed it and now none of the boxes have aligned figures. I have confirmed this in latest Chrome and Firefox on macOS.

This is the import I have in the example now:
```css
@import url('https://fonts.googleapis.com/css2?family=Montserrat:wght@100;200;300;400;500;600;700;800;900&display=swap');
```

And these are the URLs that are loading:
```
https://fonts.gstatic.com/s/montserrat/v14/JTUQjIg1_i6t8kCHKm45_QpRyS7m0dR9pA.woff2
https://fonts.gstatic.com/s/montserrat/v14/JTURjIg1_i6t8kCHKm45_aZA3gnD_vx3rCs.woff2
https://fonts.gstatic.com/s/montserrat/v14/JTURjIg1_i6t8kCHKm45_cJD3gnD_vx3rCs.woff2
https://fonts.gstatic.com/s/montserrat/v14/JTUSjIg1_i6t8kCHKm459WlhyyTh89Y.woff2
https://fonts.gstatic.com/s/montserrat/v14/JTURjIg1_i6t8kCHKm45_ZpC3gnD_vx3rCs.woff2
https://fonts.gstatic.com/s/montserrat/v14/JTURjIg1_i6t8kCHKm45_bZF3gnD_vx3rCs.woff2
https://fonts.gstatic.com/s/montserrat/v14/JTURjIg1_i6t8kCHKm45_c5H3gnD_vx3rCs.woff2
https://fonts.gstatic.com/s/montserrat/v14/JTURjIg1_i6t8kCHKm45_epG3gnD_vx3rCs.woff2
```

What are some next steps I can take to resolve this?

**Comment by thlinard** [comment]
Oh, yes. I believe Dave's answer is still valid:
https://github.com/google/fonts/issues/1582

Btw, the WOFF and WOFF2 files are already available In the latest version: https://github.com/JulietaUla/Montserrat/tree/master/fonts/webfonts

**Comment by lachieh** [comment]
Ok, thanks. It would be great to add support for enabling OT features with a query string or something of the like. I understand it's not something that everyone uses, but it'd nice to be able to enable them selectively.

I'll close this one in favor of that other ticket or adding a feature request.
