### ISSUE TITLE
Add new font — Fraunces

### ISSUE THREAD

**Issue by alinacsava** [google/fonts#2562]
Fraunces is a beautiful variable serif https://github.com/undercasetype/Fraunces

**Comment by alinacsava** [comment]
Though not specified in the repo, author's website states "Commissioned by: Google Fonts", so I'm closing the issue as redundant.

**Comment by sjclark** [comment]
@alinacsava this still isn't on Google fonts?

**Comment by alinacsava** [comment]
> @alinacsava this still isn't on Google fonts?

Not yet, but it's still in beta https://github.com/undercasetype/Fraunces/releases
I'm guessing it will be added as soon as it has a finished version.
