### ISSUE TITLE
Muli is missing

### ISSUE THREAD

**Issue by SpicyPete** [google/fonts#2563]
I'm using Muli on a few projects, and it looks like it's no longer on Google Fonts.

**Comment by m4rc1e** [comment]
We had to rename the family to Mulish, https://fonts.google.com/specimen/Mulish?query=mulish. Please use this instead. It is identical, apart from the family name.

**Comment by andronocean** [comment]
...but why? _Mulish_ is a horrid name for a beautiful font.

**Comment by neodoubleo** [comment]
Probably legal reasons.
