### ISSUE TITLE
Please Can You Update Amiri Font to Latest Version 0.108

### ISSUE THREAD

**Issue by Cophla** [google/fonts#258]
Before Google i was having many issues with Amiri Font version 0.107 and i was using older version since google chrome in some cases showing arabic words as splitted characters but its been a while using the latest version 0.108 and it works great with all browsers.
Please, if you can Update Amiri font to the latest version 0.108
From This Link:
https://github.com/khaledhosny/amiri-font/releases/tag/0.108

This the Main Developer Khaled Hosny Project Link
Thank You

**Comment by davelab6** [comment]
Thanks for the report @FinalHeaven :)

**Comment by FinalHeaven** [comment]
Welcome :)

**Comment by khaledhosny** [comment]
This should be closed now.

**Comment by m4rc1e** [comment]
Thanks @khaledhosny.

Can confirm v0.109 made it into production, 2017-08-24
