### ISSUE TITLE
Add Nerko

### ISSUE THREAD

**Issue by davelab6** [google/fonts#2588]
https://github.com/nermink99/Nerko

**Comment by Shivansh2407** [comment]
Hi @davelab6 . I will be really glad to contribute to this repository. Can I work on this issue? Also can you please guide me on this.

**Comment by davelab6** [comment]
@Shivansh2407 I'm sorry to say that while our CONTRIBUTING file explains our requirements and links to further process documentation, we aren't currently able to support volunteer contributors like yourself - beyond discussions in this issue tracker.
