### ISSUE TITLE
Roboto - all weights are the same

### ISSUE THREAD

**Issue by marioloncarek** [google/fonts#259]
Something is wrong with roboto font, all weights are the same weight. Here is the screenshot. Fonts are the same weight when used on website too.
![Bug on roboto](http://s33.postimg.org/oephgjfov/robotobug.png)

**Comment by davelab6** [comment]
Please try (a) another computer (such a smartphone) and (b) try
uninstalling the fonts

**Comment by marioloncarek** [comment]
Ok so the bug is only in Chrome, all other browsers have all weights. What do you think with uninstall, the local copy of roboto that i use in PS or?

**Comment by davelab6** [comment]
@marioloncarek yes, I meant uninstalling the fonts :)

**Comment by DanielRuf** [comment]
I've seen the same behavior. But in Firefox forAndroid (latest stable version) on Android 6. Should I file a new issue?

**Comment by m4rc1e** [comment]
@DanielRuf please do and take a screenshot.

**Comment by m4rc1e** [comment]
Just had a look on Firefox for Android Nougat and Chrome. Roboto v2.137 seems to be fine.

*Firefox*
![screenshot_20170512-120627](https://cloud.githubusercontent.com/assets/7525512/25995732/af1f3d14-370b-11e7-973b-ad13c2d1ba15.png)

*Chrome*
![screenshot_20170512-105113](https://cloud.githubusercontent.com/assets/7525512/25995871/3c528aba-370c-11e7-8db8-b3f13df2a5e6.png)




They're working fine

**Comment by DanielRuf** [comment]
Okay thanks. Not sure why this happened. Could have been a wrong local rule in a thirdparty dependency. Worked after an update.

Anyway, I think I will clone the other project and remove all local rules and just use the url rules to have an equal UI on all devices and platforms.
