### ISSUE TITLE
Axis Registry file extensions?

### ISSUE THREAD

**Issue by davelab6** [google/fonts#2595]
For consistency, should the `/axisregistry` files have a `.pb` extension, same as METADATA and profile files?

    casual.textproto -> casual.pb

**Comment by nathan-williams** [comment]
`.textproto` is the correct file extension for text format proto files.

I would say that the other files using the `.pb` extension is a legacy artifact. As discussed over PM, suggest we leave both file extensions as is. There wouldn't be much benefit to updating the `.pb` files. Like you said, it's tech debt

**Comment by davelab6** [comment]
Thanks @nathan-williams! I'll make a note in our TRIVIA file and close this out
