### ISSUE TITLE
Add "Source Serif 4" with that name

### ISSUE THREAD

**Issue by davelab6** [google/fonts#2599]
Per https://github.com/adobe-fonts/source-serif-pro/issues/77 Adobe Fonts will release the next version of Source Serif Pro as "Source Serif 4"

Generally we don't want versions in family names, although there are a few exceptions ([Lobster Two](https://fonts.google.com/specimen/Lobster+Two), [Exo 2](https://fonts.google.com/specimen/Exo+2), etc) 

Adobe have offered to add a GF target to their build script to output a version named for us with the legacy name, which I accepted, but I thought I'd file this issue to discuss.

**Comment by thlinard** [comment]
My comments:

* "Std" and "Pro" are not very relevant suffixes. Especially since they are only used to indicate support for [AL2](https://github.com/adobe-type-tools/adobe-latin-charsets) for Std and [AL3](https://github.com/adobe-type-tools/adobe-latin-charsets) for Pro, but many have used the suffix "Pro" to mean "more professional" (which did not mean much…).
* In the absence of better mangement of versions, putting the version in the font name, like in software (Photoshop 2020, Word 2016, etc.), is not such a bad idea.

My question is mainly: when Source Serif 5 will be released, how will it be handled by Google Fonts?

**Comment by davelab6** [comment]
The same way. We don't want multiple versions, we want a single version of
each family, for caching and simplicity.

**Comment by thlinard** [comment]
> The same way. We don't want multiple versions, we want a single version of each family, for caching and simplicity.

Well, in this case, I think that answers the question: just remove the version number, and keep "Source Serif" (keeping the "Pro" doesn't make sense, as it will disappear, and the name without suffix will ultimately be the part that will stay the longest). You can even rename right away.

**Comment by davelab6** [comment]
We don't rename, though; we can de-list from the catalog, and add a new
family with a new name, and maintain both names in the API.

I'm fine to keep "Source Serif Pro" as "pro" connotes Adobe.

**Comment by thlinard** [comment]
Keeping the "Pro"? In light of [Frank Grießhammer's comment](https://github.com/adobe-fonts/source-serif-pro/issues/77#issuecomment-671466629) "nobody could have known that the three-weight version would stick around on Google Fonts for 5 more years", aren't you afraid everyone will think Google has once again stuck to the old version? And people will ask for another service to get the latest version?

**Comment by frankrolf** [comment]
“Pro” does not necessarily connote Adobe – other foundries have used the same naming system.
Pro really doesn’t mean much anymore (one wonders what’s “professional” about one language using more accented glyphs than another).

e.g. 
https://www.fonts.com/support/faq/opentype-varieties
https://www.fontshop.com/families/ff-good/buy?selected_package_type=styles&selected_product_type=1&selected_characterset=15

**Comment by davelab6** [comment]
> Pro really doesn’t mean much anymore

I'm OK to keep it

**Comment by frankrolf** [comment]
I believe that keeping “Source Serif Pro” on Google Fonts while going forward with ”Source Serif 4” everywhere else will be a  big point of user confusion.

Source Serif 4 has many changes which will make the family behave differently from version 3.
One of these changes is repositioning the text size and -weight master within the design space, to coincide with the Regular style. While the changes to outlines created here are really minute, they will influence all interpolations in the immediate vicinity.
This particular fix, and a fine re-evaluation of kerning pairs which will lead to document reflow.

I understand reflow might not be as big of an issue with digital-only documents, but I would not want to want to destroy a typesetter’s work. Keeping the font name forever certainly is convenient, but (IMO) also irresponsible toward the users.

Suggestion: 
Keep Source Serif Pro on the service, while also serving Source Serif 4?

**Comment by davelab6** [comment]
> Keep Source Serif Pro on the service, while also serving Source Serif 4?

@frankrolf is there a variable font weight axis version of Source Serif 2 or 3?

If so, GF could onboard that as "Source Serif Pro" so that GF is acting responsible toward existing users of bringing the 'compress' benefit of variable fonts to them, and not changing metrics much if at all; then we can de-list that family in the catalog, so its not offered for new users, and there's no confusing double listing of "Source Serif Pro" next to "Source Serif 4" anywhere in any UI; and meanwhile add the new "Source Serif 4" family without changing the name so that it is consistent with the name found elsewheere.

**Comment by frankrolf** [comment]
That’s great news, thanks Dave!

If I understand correctly, you’d want to add https://github.com/adobe-fonts/source-serif/releases/tag/3.001R as Source Serif Pro (this is the version currently is served, I think).
The release linked above includes both CFF2 and TTF VFs.

The release for SS4 is here: https://github.com/adobe-fonts/source-serif/releases/tag/4.004R
