### ISSUE TITLE
Droid Sans license?

### ISSUE THREAD

**Issue by advayDev1** [google/fonts#26]
the droidsans metadata (https://github.com/google/fonts/blob/master/apache/droidsans/METADATA.json) claims it is under the 'Apache2' license at the top, but it doesn't have a full LICENSE.txt file in the directory, and also has the line:
"copyright": "Digitized data copyright © 2007, Google Corporation."

Can Google (@davelab6) confirm that:
a) the content from Steve Matteson is under the Apache License, Version 2.0 at https://www.apache.org/licenses/LICENSE-2.0
b) the digitized data copyright to Google is also available under the same Apache License, Version 2.0
?

https://github.com/google/fonts/tree/master/apache/droidsansmono
and
https://github.com/google/fonts/tree/master/apache/droidserif
may need to be fixed too.

**Comment by davelab6** [comment]
Yes, everything in the /apache directory is licenced under Apache 2. Thanks
for asking :)
