### ISSUE TITLE
Duplicate folder: siemreap vs siamreap

### ISSUE THREAD

**Issue by olivierberten** [google/fonts#260]
`ofl/siamreap` and `ofl/siemreap` are the same. Only the second one should be kept since it's the name of the font...

**Comment by sapics** [comment]
https://github.com/google/fonts/blob/master/TRIVIA.md#duplicated-fonts
would be the reason why first one is kept.

**Comment by davelab6** [comment]
Thanks @olivierberten for reporting, and thanks to @sapics for answering - that's right.
