### ISSUE TITLE
Add Noto Sans Ethopic

### ISSUE THREAD

**Issue by ngunyimacharia** [google/fonts#2610]
It is part of the Noto Sans Family and can be located here: https://www.google.com/get/noto/#sans-ethi

Here is the repository to the font: https://github.com/googlefonts/noto-fonts

**Comment by ngunyimacharia** [comment]
There is no current support for Amharic characters in all existing Google Fonts. Hence why I'd ask for this to be implemented.

**Comment by RosaWagner** [comment]
Noto Sans Ethiopic was added with https://github.com/google/fonts/pull/4863
