### ISSUE TITLE
Google Fonts UI: misalignment of variable sliders

### ISSUE THREAD

**Issue by m4rc1e** [google/fonts#2614]
Weight sliders appear misaligned when a user increases the pt size.

<img width="1392" alt="Screenshot 2020-08-11 at 10 13 47" src="https://user-images.githubusercontent.com/7525512/89879912-83832a00-dbbb-11ea-9426-4e8b90c614df.png">

Mac OS X 10.15.1
Version 84.0.4147.105 (Official Build) (64-bit)

**Comment by davelab6** [comment]
There's a new UI for multiple axes
