### ISSUE TITLE
Can fonts have default colors?

### ISSUE THREAD

**Issue by InputBlackBoxOutput** [google/fonts#2615]
Hi there, 
I have an amazing idea to create a new font but it wont look good if created in all black.

PS:I am posting this as an issue since I searched around on the internet but couldn't find an answer.

Thanks in advance.

**Comment by arrowtype** [comment]
Hey @InputBlackBoxOutput, yes, though there are caveats.

You can make an SVG "color font" in which you preselect the colors.

https://www.colorfonts.wtf/

https://glyphsapp.com/tutorials/creating-an-svg-color-font

The big catch is that Chrome doesn’t support SVG color fonts, and seems to have no plans to do so. But, if you want your font mostly as a graphic design tool, it will work in quite a few desktop design tools, plus Safari & Firefox.

**Comment by arrowtype** [comment]
(Also, this probably isn’t the best forum for this specific question, as it’s not really related directly to Google Fonts. But, I understand that you’re interested, and I hope you follow that curiosity! One good place to research questions like this is https://typedrawers.com/. Font editors like Glyphs & RoboFont also have very helpful forums. There are also tons of really amazing type resources online, such as http://coopertype.org/lectures. Best of luck!)
