### ISSUE TITLE
Arapey problems with kerning

### ISSUE THREAD

**Issue by alafr** [google/fonts#262]
When i use **Arapey** and **Arapey Italic** from Google Fonts the programs FontForge and PdfKit don't recognize correctly some kerning pairs. 
I checked some other fonts and Arapey is the only where the 'kern' matrix has data on the first row, 
While in fonts that work properly, the first row is named {Everything Else} and is filled with zeros, in Arapey the first row contains data for A,À,Á,Â,Ã,Ä,Å, and these are the kerning pairs which don't work correctly.
![arapey](https://cloud.githubusercontent.com/assets/17966696/16018874/0b414c94-31af-11e6-8db8-d8759785b1fc.png)

**Comment by m4rc1e** [comment]
The matrix is telling me following:
- between classes A,À,Á,Â (left) and A,À,Á,Â,Ã,Ä,Å (right) there is no kerning. 
- between classes A,À,Á,Â,Ã,Ä,Å and W,V it is -60.

The values seem correct and behave properly in the browser.
![arapey_kerning](https://user-images.githubusercontent.com/7525512/27685596-d3c8479c-5cc6-11e7-99d2-3ce767ee7b54.gif)


Could you elaborate further?

**Comment by alafr** [comment]
I confirm that now it works.
This is strange because the .ttf files have not been updated.
It was probably a bug in the font parsers.

**Comment by m4rc1e** [comment]
Thanks @alafr
