### ISSUE TITLE
Broken sample text in the new website

### ISSUE THREAD

**Issue by khaledhosny** [google/fonts#263]
Congratulations for the new website. However the sample text are now just gibberish with lots of missing glyph boxes (Firefox 47 on Linux):
![2016-06-14 18-53-02](https://cloud.githubusercontent.com/assets/93914/16052689/ff002120-326d-11e6-99da-e6a709af78aa.png)

Also typing in the text field some simple Arabic text in the Amiri box gives me many missing glyphs (rendered with fallback font this time).

**Comment by rsheeter** [comment]
Ty, we will fix.

**Comment by shyndman** [comment]
Hey Khaled. Seems like this is affecting many Linux users. We're looking at it.

**Comment by khaledhosny** [comment]
FWIW, I just tried with Chrome on the same machine and it looks fine.

**Comment by codeman38** [comment]
I'm seeing missing characters in Firefox on Windows 7, very similar to Khaled's Linux screenshot above.

**Comment by shyndman** [comment]
Looks like we have a fix. We're testing it now.

**Comment by pbhj** [comment]
Same for me FF47.0 on Kubuntu 15.10. All works in Chromium. I apparently have exactly the same glyphs missing as khaledhosny (above).

**Comment by makoConstruct** [comment]
Using linux, but I'm getting trouble on chrome (50.0.2661.94) as well as firefox.

**Comment by shyndman** [comment]
We've rolled out a new release that should fix these issues. Mind giving it another go?

**Comment by khaledhosny** [comment]
Looks fine now. I’m having a different Firefox issue with the Arabic characters in the specimen page, but I think this should be reported separately.

**Comment by rsheeter** [comment]
Awesome, thx for verifying!

**Comment by codeman38** [comment]
Working correctly for me under Windows now as well.
