### ISSUE TITLE
Merriweather Sans v12 Breaks Layout

### ISSUE THREAD

**Issue by NoelAbrahams** [google/fonts#2631]
Hi

We've been rushing around investigate a sudden break in the layout of our website. Finally this has been tracked down to the following: The Merriweather Sans font downloaded automatically seems to have changed without notice.

Here are the URLs for the good (v11) and bad (v12) versions:

```
https://fonts.gstatic.com/s/merriweathersans/v11/2-c49IRs1JiJN1FRAMjTN5zd9vgsFH1OZyDE0hY.woff2
https://fonts.gstatic.com/s/merriweathersans/v12/2-c99IRs1JiJN1FRAMjTN5zd9vgsFHX1QjU.woff2
```

I've had a look at the [Merriweather github releases page](https://github.com/SorkinType/Merriweather/releases) and they don't seem to have released anything for the last few years.

We are scrambling now to resolve this. I have a few questions:

A) Why has a new version of Merriweather been released (when the official repo hasn't done so)?
B) What is the best way to safeguard against this in the future?

I've looked at the rather heated discussion here about self-hosting. Why don't you provide a way to specify version out of the box?

Thanks

**Comment by m4rc1e** [comment]
@NoelAbrahams the issue has been fixed and the fonts have been pushed to production.

**Comment by NoelAbrahams** [comment]
@m4rc1e, thank you for letting me know. We released a fix on Saturday with the version hard-coded to `v11`.

I see that the google font loader now loads `v13`. Where can I find information about what's different between `v11` and `v13`? Also how do we subscribe to Merriweather version changes and release notes?

Thanks
