### ISSUE TITLE
Karla: mathematical signs are misaligned

### ISSUE THREAD

**Issue by thlinard** [google/fonts#2636]
The horizontal bar of + − ÷ should be the same, and aligned vertically (in the middle) with × =. And = should be two − (minus sign).
<img width="929" alt="Karla" src="https://user-images.githubusercontent.com/13808824/90992233-a5fb4700-e5ae-11ea-9fac-1c3aa3e98ce2.png">

**Comment by thlinard** [comment]
More complete specimen (1×<>+÷−¬=≠±≤≥3):
<img width="1353" alt="Karla" src="https://user-images.githubusercontent.com/13808824/91155254-e2b86280-e6c2-11ea-9b88-c3be29cdfb72.png">

**Comment by emmamarichal** [comment]
fixed in https://github.com/googlefonts/karla/pull/11
