### ISSUE TITLE
Kufam VF: small glitch in the 1

### ISSUE THREAD

**Issue by thlinard** [google/fonts#2637]
Especially visible in the bolder weights.

<img width="215" alt="Kufam" src="https://user-images.githubusercontent.com/13808824/90992436-00e16e00-e5b0-11ea-8313-ef6c327cb656.png">

**Comment by m4rc1e** [comment]
Thanks @thlinard.

I'm in the middle of writing a tool to catch these. To close the loop, here's all the characters which have the same issue.

![Kufam wght](https://user-images.githubusercontent.com/7525512/91943233-24b15c00-ecf4-11ea-8ca3-8a659cce2a27.png)

**Comment by vv-monsalve** [comment]
Followed in #3119
