### ISSUE TITLE
Manrope is broken on Mac on Google Fonts CDN

### ISSUE THREAD

**Issue by waterplea** [google/fonts#2643]
Hello. I tried adding Manrope from Google Fonts CDN like following:

`@import 'https://fonts.googleapis.com/css2?family=Manrope:wght@500;800&display=swap';`

And I have a rendering issue only present on Mac:

![image](https://user-images.githubusercontent.com/11832552/91182741-3b9fef00-e6f3-11ea-8ca7-c2528fb7fa74.png)

If you search "Manrope" in Github issues you get some similar problems:
https://github.com/MrMaxie/get-google-fonts/issues/23
https://github.com/majodev/google-webfonts-helper/issues/108

It also looks like Manrope author has fixed the issue:
https://github.com/sharanda/manrope/issues/51

I was told here that if you download and install it from Google Fonts it works fine (haven't tested it myself):
https://github.com/google/fonts/issues/1612#issuecomment-673576328

Please fix CDN version.

**Comment by m4rc1e** [comment]
Which version of OS X?

**Comment by MarsiBarsi** [comment]
Hi @m4rc1e 
I see the problem on 10.14.6 (18G6020)

**Comment by dpkonofa** [comment]
A similar problem occurs on Macs with the Mulish font.

**Comment by waterplea** [comment]
Looks like Manrope is fixed now.

**Comment by gelbehexe** [comment]
I faced this issue now (March 2022). Had to use the variable font. I'm on Mac 10.15.7

**Comment by chewiethepie** [comment]
same problem with 13.3.1 (22E261)

**Comment by Farial-mahmod** [comment]
Manrope-Regular and others aren't working on our macOS Sonoma 14.3.1 version.

**Comment by EbenSorkin** [comment]
Is your copy downloaded or being served by google? If it was downloaded you may need a more up-to-date copy. If it is being served by Google then it is a good idea to say what the problem is... otherwise it might not be investigated.
