### ISSUE TITLE
Kreon in bad shape

### ISSUE THREAD

**Issue by thlinard** [google/fonts#2645]
I have reported these issues upstream https://github.com/googlefonts/kreon/issues/12, but I don't know if it wouldn't be better to do it here.

The font is in production:
https://fonts.google.com/specimen/Kreon?preview.text=%C4%86%C5%9A%C5%B9%C4%84%C4%85%C4%98%C4%99%C4%AE%C4%AF%C5%9E%C5%A2%E1%BA%82%C4%8F%C4%8A%C4%8B%C4%A0%C4%A1%C4%A6%C4%A7%C4%AF%C4%B0%C5%83%C5%94%C5%BB%C5%BC%E2%84%A2&preview.text_type=custom

**Comment by m4rc1e** [comment]
Thanks @thlinard!
