### ISSUE TITLE
Add Open Sauce Sans?

### ISSUE THREAD

**Issue by davelab6** [google/fonts#2657]
https://fontsarena.com/open-sauce-sans-by-creative-sauce/

**Comment by cssobral2013** [comment]
@davelab6 - Could you include also Open Sauce One and Two on this issue? This's because Open Sauce Sans, One and Two are actually a superfamily. Check it out at: https://github.com/marcologous/Open-Sauce-Fonts

**Comment by cssobral2013** [comment]
@davelab6 - This's actually a duplicate of #2421.
