### ISSUE TITLE
Font "Mountains of Christmas" is in the wrong location

### ISSUE THREAD

**Issue by udondan** [google/fonts#267]
The font is located in the apache folder: https://github.com/google/fonts/tree/master/apache/mountainsofchristmas

Though the license file inside this folder states it is licensed under OFL.

**Comment by udondan** [comment]
Then again, the metadata file states it uses Apache 2 license. Maybe just the wrong license file is included.

**Comment by davelab6** [comment]
@udondan thanks for reporting this!
