### ISSUE TITLE
Rokkitt regular and Rokkitt bold have a different x-height

### ISSUE THREAD

**Issue by frivoal** [google/fonts#268]
This makes them very impractical to use together.

http://jsbin.com/quseha/1/edit?html,css,output

<img width="95" alt="screenshot 2016-06-15 22 34 56" src="https://cloud.githubusercontent.com/assets/113268/16081680/76d6a04e-3349-11e6-8bfc-c0b760c3cc66.png">

**Comment by m4rc1e** [comment]
Thank you for the JSBin.

On Mac OS X, Safari v10.1, it looks okayish. 
![screen shot 2017-06-14 at 11 34 02](https://user-images.githubusercontent.com/7525512/27128213-85fcd05a-50f5-11e7-9ee0-d02cca583313.png)

Which OS, browser are you using?

**Comment by davelab6** [comment]
Could be ttfautohint x height snapping creates this effect on Windows

**Comment by m4rc1e** [comment]
On Chrome 59, Win 8.1, it does look a bit strange

**Comment by laerm0** [comment]
This issue appears to be fixed now so I am closing it.

![screen region 2017-09-08 at 10 41 22](https://user-images.githubusercontent.com/10780161/30216862-5eaf35b2-9482-11e7-9aed-463398604e35.png)
