### ISSUE TITLE
Mulish A is showing weird glyphs on Macs only

### ISSUE THREAD

**Issue by dpkonofa** [google/fonts#2684]
Using the Mulish font set, we're seeing weird artifacts on the capital letter A:

![image002](https://user-images.githubusercontent.com/6332378/93105069-78f8fc00-f663-11ea-9d4a-231009c703a1.png)
![image001](https://user-images.githubusercontent.com/6332378/93105077-7b5b5600-f663-11ea-8cdb-37f4858a1f45.png)

It's a subtle graphical glitch but it's definitely there.

**Comment by dpkonofa** [comment]
CodePen that shows the issue:  https://codepen.io/derekkgilbert/pen/RwaJYQg

**Comment by thlinard** [comment]
Duplicate of #2602

**Comment by dpkonofa** [comment]
This particular issue was caused by using the wrong import for the fonts so I’m closing this one out. It’s also a duplicate of another issue with a different font and that’s being worked on.
