### ISSUE TITLE
[Variable font request] Noto sans

### ISSUE THREAD

**Issue by strarsis** [google/fonts#2687]
Please offer the [Noto Sans](https://fonts.google.com/specimen/Noto+Sans?query=Noto+sans) font as variable font!
It has four variants on Google Fonts:
- Regular (400)
- Regular italic (400i)
- Bold (700)
- Bold italic (700i)
So these would need two axises, wght and italic, right?

**Comment by alerque** [comment]
Yup piece of cake. Just add a couple check boxes, what could be easier? Boom, an axis; boom, another axis. Oh, and then redraw one of the largest collections of glyphs in the world.

**Comment by strarsis** [comment]
But... but... AI latent space. 😸

**Comment by alerque** [comment]
@strarsis Sure, go for it. Write the code and train a model and when you have it working well I among many others would use it. It's not impossible, but so far no attempt has even gotten close. It's not as easy as you seem to think. A bunch of hand-waving isn't going to get the job done.

**Comment by moyogo** [comment]
There are already single-axis variable fonts for Noto Sans but they are not being served on Google Fonts:
- https://github.com/googlefonts/noto-fonts/blob/master/unhinted/variable-ttf/NotoSans-VF.ttf
- https://github.com/googlefonts/noto-fonts/blob/master/unhinted/variable-ttf/NotoSans-Italic-VF.ttf
