### ISSUE TITLE
Legality and naming issue of ZCool fonts (Chinese (simplified) fonts)

### ISSUE THREAD

**Issue by NightFurySL2001** [google/fonts#2698]
I would like to raise an issue about [ZCOOL fonts](https://www.zcool.com.cn/special/zcoolfonts/) being released under SIL Open Font License on Google Fonts, namely [ZCOOL KuaiLe](https://fonts.google.com/specimen/ZCOOL+KuaiLe), [ZCOOL QingKe HuangYou](https://fonts.google.com/specimen/ZCOOL+QingKe+HuangYou) and [ZCOOL XiaoWei](https://fonts.google.com/specimen/ZCOOL+XiaoWei).

The included font license in the font packages says that they reserve all rights and only relesed free for commercial use only. No modification of font name and reselling of fonts are permitted.

I shall point out a few points:

1. The ZCOOL teams did not released the fonts under SIL OFL in any of their pages.

2. The reserved name is against the rule of [Contributing](https://github.com/google/fonts/blob/master/CONTRIBUTING.md):-

> The Open Font License should not have any Reserved Font Names (why)

The font file provided in Google Fonts has modified the font file names by removing the Chinese names and I think that is against their copyright stance. There is no specifications of RFN for the fonts in the OFL notice. 

3. The initial ZCOOL is a registered trademark referring to the copyright holder group, which also is against the Contributing rules:-

> The font family name should not include any copyright holder full names (but first names are OK), no registered trademarks, and no initials or abbreviations, and no references to languages or writing systems; it should be a simple and unique name. A limited but easy way to test for uniqueness is namecheck.fontdata.com

4. The included font [license text file for ZCOOL XiaoWei](https://github.com/google/fonts/blob/master/ofl/zcoolxiaowei/OFL.txt) links to a repository that did not exist:-

> Copyright 2018 The ZCOOL XiaoWei Project Authors (https://www.github.com/googlefonts/xiaowei)

Hope you can solve the inquiries. Thanks in advance.

**Comment by davelab6** [comment]
I went to Beijing about 2 years ago and worked with ZCOOL on these releases. As far as I know, the fonts weren't subsequently updated by ZCOOL elsewhere.

The missing repo link is a good catch, that should be fixed before closing this issue

**Comment by NightFurySL2001** [comment]
Thanks for your reply.

I would like to check if the name ZCOOL is against the rules as in (3) as it do seem suspiciously close to registered trademark. Also, should the names be in RFN as stated in their license files on their site as in (2)?

Another thing, I would like to check if the fonts are good to be modified and redistributed under SIL OFL.

Thank you in advance.

**Comment by davelab6** [comment]
The ZCOOL trademark is against the rule, but an exception was made. If you want to display their trademark prominently in your product, you should also reach an agreement to use their trademark with them. You can email fonts@google.com if you'd like an introduction (or message me on WeChat, `davelab6`)

I confirm there should not be any RFNs associated with the ZCOOL fonts.

I confirm the fonts are good to be modified and redistributed under SIL OFL.

**Comment by NightFurySL2001** [comment]
Thank you @davelab6 for your help and info, these are great resources to have under SIL OFL. I'll leave this issue open until the broken link in (4) is fixed.
