### ISSUE TITLE
Source Han Serif

### ISSUE THREAD

**Issue by henrywright** [google/fonts#2699]
Is the Source Han Serif font available using the Google Fonts API?

I am using Source Serif Pro on my website but I display user submitted text and often need to support extra characters

**Comment by NightFurySL2001** [comment]
You can use the Google-branded font Noto Serif CJK (SC/TC/J/K) which is (almost) the same as Adobe's Source Han Serif. Same goes for Adobe's Source Han Sans to Google's Noto Sans CJK (SC/TC/J/K).

**Comment by henrywright** [comment]
Does Noto Serif CJK have Latin, Greek and Cyrillic characters?

**Comment by NightFurySL2001** [comment]
Yes, they're the same as Source Han Serif. Refer to this issue: https://github.com/adobe-fonts/source-han-sans/issues/122.
