### ISSUE TITLE
Arabic in characters list of the new website specimens are shaped

### ISSUE THREAD

**Issue by khaledhosny** [google/fonts#270]
In Firefox the Arabic characters in the Characters list are shaped which I don’t think is intended here (they are not shaped in Chrome). This happens in all fonts:
![2016-06-16 00-21-31](https://cloud.githubusercontent.com/assets/93914/16099380/b24d0444-3360-11e6-9fe2-653dfdd5fc22.png)

But it is especially bad in fonts with vertical stacking like Aref Ruqaa or Rakkas:
![2016-06-16 00-23-10](https://cloud.githubusercontent.com/assets/93914/16099433/fa6672b0-3360-11e6-92fb-f45fd9742511.png)

I don’t know for sure what is going on, but I think the empty span that is used to prevent shaping does not have any effect in Firefox since it tries to shape text across spans when possible. I think a more robust way is to insert ZWNJ inside these spans.

**Comment by davelab6** [comment]
@shyndman

**Comment by shyndman** [comment]
This has been resolved. Thanks for your help.
