### ISSUE TITLE
axisregistry: Can we remove spaces from Weight fallback names?

### ISSUE THREAD

**Issue by m4rc1e** [google/fonts#2701]
@nathan-williams is it possible to remove spaces from the Weight fallback names so "Semi Bold" becomes "SemiBold etc?

This will match our font style names, https://github.com/googlefonts/gftools/blob/master/Lib/gftools/util/google_fonts.py#L85-L95

**Comment by davelab6** [comment]
Since the axis' values are not changing I hope this is possible

**Comment by nathan-williams** [comment]
I'd prefer to preserve spacing so that we can use them to generate labels. It's easier to remove the spaces than add them back in.
