### ISSUE TITLE
Ui -> Load Time: Show actual Kbytes instead of Fast/Slow

### ISSUE THREAD

**Issue by impallari** [google/fonts#273]
The new GF is f**king awesome! Impressive job!

I have a little suggestion:
In loading time, show actual KB instead of Fast/Moderate/Slow
Showing actual Kbytes will be very useful for website developers, I guess.
![screen shot 2016-06-17 at 2 03 37](https://cloud.githubusercontent.com/assets/3036973/16141289/7101bfd6-3430-11e6-94eb-ece6b364f0a8.png)

**Comment by rsheeter** [comment]
The size varies by user agent and, if unicode-range is available,
characters being used. As a result giving an exact size is awkward.
