### ISSUE TITLE
Proposal: “Wonkiness” axis name should be “Wonky” due to its binary usage; "Normal" name should be "NonWonky"

### ISSUE THREAD

**Issue by arrowtype** [google/fonts#2741]
Many font axis names are _properties_, which describe a quantifiable attribute of a font and can be set to a scale. The scale can vary depending on the specific font, within a certain possible range. These include:
- Weight
- Width
- Slant
- Optical Size
- Grade

Other axis names are _adjectives_, which can only be “false” or “true” (or in some cases, “partly true”), and therefore must have a scale of 0–1:
- Italic
- Monospace
- Casual
- Cursive

Due to the way the `WONK` axis is used as a binary option in [Fraunces](https://github.com/undercasetype/Fraunces), I believe it fits into the latter category, and should therefore have the formal name “Wonky.”

A possible counter-argument: “Wonkiness” is more similar to the name of Fraunces’s other axis, “Softness.” So, maybe “Wonkiness” would look better in axis UIs. But, I think the bigger win here would be determining that binary axes get adjective names, while range axes get property names.

If @davelab6, @sponcey, and @flaviazim agree, can we update [the Axis Registry definition](https://github.com/google/fonts/blob/0af700691cb9ad24372186d52bd9cd8c27550f1a/axisregistry/wonkiness.textproto) before we add Fraunces to the library?

**Comment by davelab6** [comment]
If so, doesn't casual become casualness?

**Comment by sponcey** [comment]
I originally specified it as "Wonky" not "Wonkiness". I think just calling it the "Wonky" axis makes more sense.

**Comment by arrowtype** [comment]
> If so, doesn't casual become casualness?

No; see my second category for binary, 0–1 axes that get adjectives for names.

**Comment by arrowtype** [comment]
@sponcey yes, I think you got it right originally, and the axis registry changed it incorrectly.

**Comment by arrowtype** [comment]
Adding something to this proposal: in the Wonky axis, "Normal" should be called "NonWonky."

This is because of two reasons:
- `Normal` is a term already associated with the Italic axis in CSS (e.g. `font-style: normal;` sets roman text)
- Fraunces uses `WONK=1` as an axis default, and this is important to the family, because it allows the tilted legs on characters like `n h m` (plus cool italic forms) in optical sizes above 18. If we made the default `WONK=0`, these features would no longer appear in the high-opsz static instances or in most uses of the variable font. BUT, because "Wonky" is the default style, it should be the elided style name. Fraunces just _is_ Wonky be default, and users have the option to tone it down a bit – i.e. make it NonWonky. It will never be particularly "Normal," though, by design.
- `Normal` is a very general word, so if a font style name is generated from STAT-based menu options, users won’t be likely to know what something like `144pt Black Italic Normal` means, whereas `144pt Black Italic NonWonky` is much self-evident

**Comment by davelab6** [comment]
Wonky axis label is fine, NonWonky I'm less sure on

**Comment by RosaWagner** [comment]
Resolved with #2765
