### ISSUE TITLE
How to use Poppin's double-storey a in a website?

### ISSUE THREAD

**Issue by bochenn** [google/fonts#2752]
Does anyone knows how to use the double storey 'a' by default on a website? I mean with the embedded code by Google.

This screenshot is from Adobe Illustrator https://loom.com/i/3e183581486e40cb9bfb9767a6de603b

I need now to use the same in a website that has Poppins as the main font but don't know how to call it with the CSS.

Thanks,

**Comment by alerque** [comment]
This issue is a duplicate of #2753 (suggest closing in favor of the later one because that's where it got answered first).
