### ISSUE TITLE
Self-hosting Alternative - Fontsource

### ISSUE THREAD

**Issue by DecliningLotus** [google/fonts#2756]
The main [README](https://github.com/google/fonts#self-host-fonts-available-from-google-fonts) has its own individual section addressing self-hosting fonts. 

I was curious whether that section should be updated with references to other solutions such as [Fontsource](https://github.com/fontsource/fontsource) which somewhat addresses other issues and concerns within this repository and serves as useful information for the developers that frequent here. 

Additionally, if there are elements in Fontsource that seem to be concerning, it'd be great to get the feedback and input from the Google team to improve the repository to get it up to standard since there does seem to be demand for a format such as this.

I'd be more than willing to make a PR to update the main README if this sounds like a valid acceptable idea 

Another thing to note is that Kyle Mathews' [Typefaces Project](https://github.com/KyleAMathews/typefaces) did deprecate itself in favour of Fontsource.
References: #222, #472, #1790.

**Comment by davelab6** [comment]
I'm happy to review and accept such a PR. Nice project :)

**Comment by DecliningLotus** [comment]
Resolved in #2757.
