### ISSUE TITLE
Parallel deployment requirements not met by Google Fonts project

### ISSUE THREAD

**Issue by wolfbeast** [google/fonts#277]
We've run into issues in our browser that Google fonts, when served through gstatic/googleapis.com, do not follow the parallel deployment requirement for fonts.

The W3C is pretty clear in the relevant documentation[1] that `@font-face` should be used with alternative entries for different font formats to "fulfill the parallel deployment requirement"[2] to avoid "relying on style sheet switching, content negotiation, user-agent version sniffing or suchlike fragile methods"[3]

The Google font project does none of this, and apparently employs UA version sniffing on googleapis.com to then serve a _singular_ (individual per sniffed browser) css stylesheet with only _one_ format listed instead of using the prioritized list in `@font-face`. This is wrong, and breaks fonts on browsers with e.g. compatibility UA overrides enabled, or with an unknown UA (where googleapis falls back to just assuming woff2 is supported (often _not_ the case)).

Please fix this by using proper css with multiple font entries that don't rely on UA sniffing or similar.

[1]http://www.w3.org/TR/2013/CR-css-fonts-3-20131003/#src-desc
http://www.w3.org/TR/WOFF20ER/
[2]http://www.w3.org/TR/WOFF20ER/#deploy
[3]http://www.w3.org/TR/WOFF20ER/#req-parallel

**Comment by davelab6** [comment]
Thanks for opening this issue :)

> breaks fonts on browsers with e.g. compatibility UA overrides enabled

Please could you be more specific about which browsers do this?

> or with an unknown UA (where googleapis falls back to just assuming woff2 is supported (often not the case))

I can't reproduce this; I believe it falls back to assuming ttf is supported, which is often the case:

    $ curl -A "" https://fonts.googleapis.com/css?family=Oswald
    @font-face {
      font-family: 'Oswald';
      font-style: normal;
      font-weight: 400;
      src: local('Oswald Regular'), local('Oswald-Regular'), url(https://fonts.gstatic.com/s/oswald/v11/Y_TKV6o8WovbUd3m_X9aAA.ttf) format('truetype');
    }

**Comment by wolfbeast** [comment]
> Please could you be more specific about which browsers do this?

Considering Google uses UA sniffing left right and center and only recognizes "the big three", that would be any browser not part of that family that wants to be recognized as a modern browser and not get a severely limited Google UI.
See also linked commits in this issue on Pale Moon to work around your problem. Pale Moon gives users the options to use "Firefox Compatibility mode" which we have to enforce (when users otherwise disable this mode) for Google resources (with different versions depending on the resource in use) -- a special entry has been made as a workaround for this issue here for Google fonts for the time being.

In addition, people do use user agent randomizers and custom overrides out of privacy considerations which would immediately break this sniffing behavior.

> I can't reproduce this; I believe it falls back to assuming ttf is supported, which is often the case:

Last time I checked, it defaulted to woff2; perhaps something changed in the meantime there.

Regardless though, what you really should do is follow the W3C deployment strategies, especially in the case of WOFF, which does not require UA sniffing of any kind, and that is to for each font family provide a prioritized list of available font formats in a comma-separated format in `@font-face` in css served to every browser regardless of detected UA identification. Any web client will only download the font in the first supported format available. E.g. for a fully browser-agnostic css:
````
@font-face {
  font-family: 'Oswald';
  font-style: normal;
  font-weight: 400;
  src: local('Oswald Regular'), 
    local('Oswald-Regular'), 
    url(https://fonts.gstatic.com/s/oswald/v11/Y_TKV6o8WovbUd3m_X9aAA.woff2) format('woff2'),
    url(https://fonts.gstatic.com/s/oswald/v11/Y_TKV6o8WovbUd3m_X9aAA.woff) format('woff'),
    .... (e.g. otf, eot, as-needed/available),
    url(https://fonts.gstatic.com/s/oswald/v11/Y_TKV6o8WovbUd3m_X9aAA.ttf) format('truetype');
}
````

But at the very least for the woff2/woff pair.

**Comment by rsheeter** [comment]
Larger responses mean more human time spent waiting. That alone makes it unlikely the suggested change will be implemented as it would degrade the experience for the vast majority of our users.

WOFF2 has never been default. You only receive it if we think you support it. 

From my POV the ideal solution here would be for Pale Moon to support WOFF2 (it's better than WOFF1 in more or less every way!). I realize that may not be viable.

**Comment by wolfbeast** [comment]
The only larger response will be the css file itself! Overhead for server-side checking and providing an individual CSS file, as well as normal connection overhead will make the size increase of a css file by one line absolutely insignificant and purely theoretical.

A client will check the list of offered font formats and _only_ download the first one that is supported (and ignore previous ones). That is per spec.

"We think you support it" is the wrong approach! Let the client decide which formats it supports instead of not giving it any choice but what you **_think_** a client supports. This has been the problem that came to light because obviously you've been "thinking" my browser supports WOFF2 (incorrectly) and serving it.

Please check the W3C references I linked in the initial issue report. It provides clear mechanisms to do this in CSS with no extra delays or waits for the end user:
````
/* Define a custom web font */
@font-face {
  font-family: 'MyWebFont';
  url('webfont.woff2') format('woff2'), 
  url('webfont.woff') format('woff'), 
  url('webfont.ttf')  format('truetype'),
}
/* Use that font in a page */
body {
  font-family: 'MyWebFont', sans-serif;
}
````
(as taken from "How we use web fonts responsibly, or, avoiding a @font-face-palm" https://www.filamentgroup.com/lab/font-loading.html -- this is proper deployment)

The prioritized src list will have the client decide based on `format()` what to download and use. Google fonts doesn't have to (and shouldn't!) do this.
We are working on implementing WOFF2 in Pale Moon, but it's still only an ideal solution for bandwidth, not for user experience not getting fonts at all due to incorrect guesses by your discerning script. This is still some time away though, and doesn't take away from the fact that **the ideal solution is following proper and robust deployment following the W3C method as outlined**. That has nothing to do with POV even, because it is beneficial no matter how you look at it:

- No UA sniffing/guessing needed: works even in non-standard environments
- Simpler server-side deployment (one file to rule them all)
- No extra bandwidth used (client only downloads what it uses)

**Comment by davelab6** [comment]
> The only larger response will be the css file itself!

Right. https://www.google.com/fonts/#Analytics:total shows that a CSS file for Open Sans was served  24,592,775,275 times in the last 7 days, which is 40,663 CSS files per second; that's just 1 family. 

Therefore a size increase of a css file by one line is significant and not just purely theoretical, especially when you're paying for that bandwidth. 

> Please check the W3C references I linked in the initial issue report

In the introduction to https://www.w3.org/TR/WOFF20ER/ it says,

> This document is non-normative.

So I think probably your immediate fix to change PaleMoon's UA string so that Google Fonts serves it TTF files which it can render; and as you say, a better longer term fix is to implement WOFF2 in Pale Moon.

**Comment by wolfbeast** [comment]
>>  The only larger response will be the css file itself!
> 
> Right. https://www.google.com/fonts/#Analytics:total shows that a CSS file for Open Sans was served 24,592,775,275 times in the last 7 days, which is 40,663 CSS files per second; that's just 1 family. 
> 
> Therefore a size increase of a css file by one line is significant and not just purely theoretical, especially when you're paying for that bandwidth.

Right.
Let's ignore packet sizes for transport because of which it probably won't make a difference.
Let's ignore http compression.
And above all let's ignore the fact that if Google wants to provide this free service to get 40k UA data points/analytics/profiling hits/sec for free they should realize the costs involved. **COME ON!**

If Google doesn't want to pay for (probably negligible) peering bandwidth to provide the service **properly**, then they shouldn't provide the service to begin with. Either you do it right or you don't do it at all. You'd rather do it half-assed? Be honest.

And I know the deployment document is non-normative. That probably has everything to do with the fact that the W3C has a habit of not making something normative if Google doesn't do it in practice. 

I've already put in a site-specific override as a workaround. Looks like I'll have to keep that in place until we support WOFF2, then, eh? Doesn't take away from the fact that you're doing things quite wrong.

**Comment by mattatobin** [comment]
Couldn't logic and maintenance of a complex user agent detection as well as server side processing costs be reduced if Google simply sent the prioritized src list per spec?

Wouldn't that offset any potential increase in bandwidth cost?

I believe assuring complete browser coverage is attained can only benefit Google and this service in the longer run. Not requiring users or webmasters to have to take extra and specific steps to mitigate or transition off the service for reasons of not meeting the needs of said users or webmasters.
