### ISSUE TITLE
Is Newsreader OpSz min really 6?

### ISSUE THREAD

**Issue by davelab6** [google/fonts#2772]
This 0 value should not have been accepted, and has been set to the axis minimum here, 6

https://github.com/google/fonts/commit/92ec7cb6699bcdc28a8c23a38805820a2161cd66

_Originally posted by me at https://github.com/google/fonts/pull/2577#r512413769_

@yanone is that the correct value?

**Comment by felipesanches** [comment]
yes!

![Screenshot from 2020-10-27 08-19-27](https://user-images.githubusercontent.com/213676/97294781-37946880-182d-11eb-9f98-70c06149b8a3.png)

But this family was added back at 4d442fa119714832efd1ad3e019f0b18615e9508 last July 29 when we still did not have these checks on Font Bakery.

We also have a few more problems in this font detected by a recently implemented FB check:
![Screenshot from 2020-10-27 08-22-45](https://user-images.githubusercontent.com/213676/97295096-a376d100-182d-11eb-84f5-398a0d783ed6.png)

**Comment by yanone** [comment]
I'm tackling this, but I want to point out that you're looking at the wrong PR, which got "blocked".
The current one is here: #2661

**Comment by RosaWagner** [comment]
I close this since it is resolved
