### ISSUE TITLE
Ligatures are not formed in several Arabic fonts

### ISSUE THREAD

**Issue by khaledhosny** [google/fonts#2782]
The lam-alef ligature is not formed in several Arabic fonts, currently Harmattan, Lateef, and Mada:
![image](https://user-images.githubusercontent.com/93914/97788964-8c393a00-1bc5-11eb-8e70-8e1ca8608cfa.png)
![image](https://user-images.githubusercontent.com/93914/97788974-952a0b80-1bc5-11eb-95c2-254f8640a050.png)
![image](https://user-images.githubusercontent.com/93914/97788981-9f4c0a00-1bc5-11eb-8cd9-6f65ef6b787c.png)

**Comment by davelab6** [comment]
@khaledhosny added extra context to this on twitter, "Bug in Google Fonts new font subsetter"

@rsheeter

**Comment by garretrieger** [comment]
I'll switch these families back to fontTools. I've got a couple PR's out for harfbuzz that will likely fix these issues. Once I get those merged we can switch these families back to harfbuzz for subsetting.

**Comment by garretrieger** [comment]
This should be fixed now in prod (may need to clear cached fonts to see the updates).

**Comment by khaledhosny** [comment]
Thanks. Regular styles of the affected fonts are still broken though, I don‘t know if it is caching issues but it does not to seem to be a browser cache as nothing I tried makes it go away, including testing in different browsers.

**Comment by garretrieger** [comment]
There's server side caching which can take a day or two to expire. So I'd just give it another day or so.

**Comment by khaledhosny** [comment]
Thanks!
