### ISSUE TITLE
Lexend Peta Kerning of '*ffi*' is wrong

### ISSUE THREAD

**Issue by david-westreicher** [google/fonts#2795]
The kerning of text containing `*ffi*` is off.
Example (traffic):
![image](https://user-images.githubusercontent.com/706827/98223136-fc431980-1f51-11eb-8dd2-25b38c2ee23d.png)
Text with just containing `*fi*` works (trafic):
![image](https://user-images.githubusercontent.com/706827/98223294-30b6d580-1f52-11eb-9b2b-c6442757c88c.png)

**Comment by RosaWagner** [comment]
An update which fix it is on is way #2789, will be live in 1 or 2 weeks, if everything's fine.
