### ISSUE TITLE
Missing weights and styles for Andada ht

### ISSUE THREAD

**Issue by CaroGiovagnoli** [google/fonts#2808]
There are weights and styles for Andada ht:

- Andada Italic
- Andada Bold
- Andada Bold Italic
- Andada Regular Small Caps
- Andada Italic Small Caps
- Andada Bold Small Caps
- Andada Bold Italic Small Caps

Best,
Carolina Giovagnoli

**Comment by thlinard** [comment]
Hi Carolina,
I couldn't find Andada's repository, where is it?

**Comment by CaroGiovagnoli** [comment]
Hi Thomas, 
Here is the link:

[https://github.com/huertatipografica/andada-ht-OLF]

Best,
Caro

**Comment by thlinard** [comment]
Hi Carolina,

Thank you very much!

I hope someone from the Google team will see this thread soon and can take care of a PR of the new version!

@m4rc1e? @davelab6?
