### ISSUE TITLE
Self hosting instructions

### ISSUE THREAD

**Issue by davelab6** [google/fonts#2810]
@m4rc1e has in https://github.com/google/fonts/commit/b439c994fb212fe6f4f978493774b45dfcbdf4af removed the link to a now somewhat stale libre project to provide self-hosting web font file packages based on the files returned by the fonts API.

I propose we document how to self-host based on pulling fonts out of the API with a simple curl/shell or python script.

**Comment by alerque** [comment]
...or link to [fontsource](https://github.com/fontsource/fontsource), which is a not-stale project that does something similar with GF sources.

**Comment by thlinard** [comment]
PR #2757?

**Comment by alerque** [comment]
Yes, pretty much just like that. Except for the tectonic speed of PR review.

**Comment by davelab6** [comment]
Ha :) Thanks!
