### ISSUE TITLE
Add Source Sans Pro variable font

### ISSUE THREAD

**Issue by elliottslaughter** [google/fonts#2824]
Source Sans Pro has had a variable font for at least a couple of years, but it is not available on Google Fonts. You can see the variable font right on the Github page:

https://github.com/adobe-fonts/source-sans-pro

Would it be possible to add? The fixed weight versions of the font are oddly inconsistent, which would make the variable font particularly nice.

Thanks!

**Comment by thlinard** [comment]
Duplicate of #1744.

**Comment by elliottslaughter** [comment]
Huh, I guess my search skill fail me. Thanks!
