### ISSUE TITLE
Update IBM Plex - Add Glyphs for css font-feature support

### ISSUE THREAD

**Issue by raunaqpatel** [google/fonts#2829]
IBM plex sans is a typeface that offers a lot of glyphs including some open type variants like slashed zero.
The google fonts version of the typeface is missing those and is very outdated.

**IBM plex glyphs:**
![image](https://user-images.githubusercontent.com/13498052/99980151-97404e00-2db0-11eb-9aa7-7d523b74b10d.png)

**Glyphs on Google fonts for IBM Plex Sans:**
![image](https://user-images.githubusercontent.com/13498052/99980288-be971b00-2db0-11eb-8e99-8f43fe670296.png)

**Comment by RosaWagner** [comment]
IBM Plex fonts got updated this year, check it out :)
