### ISSUE TITLE
Add "Karantina"

### ISSUE THREAD

**Issue by ronykoch** [google/fonts#2835]
Hi :)
I designed a new Hebrew and Latin typeface called Karantina that was created during lockdown of COVID-19 pandemic.
Please check out my repository-
https://github.com/ronykoch/Karantina

Production notes by @yanone:
- [x] Contact author
- [x] Build
- [x] Fontbakery QA
- [x] Visual QA
- [x] Version bumped
- [x] Authors and Contributors info
- [x] Catalog designer info up to date
- [x] PR to upstream
- [x] PR to GF
- [x] Font Images

**Comment by ronykoch** [comment]
Hi :)
I designed a new Hebrew and Latin typeface called Karantina that was created during lockdown of COVID-19 pandemic.
Please check out my repository-
https://github.com/ronykoch/Karantina

**Comment by davelab6** [comment]
I propose @rosawagner to onboard this :)  Thanks @ronykoch :)

**Comment by yanone** [comment]
Hi @ronykoch 
I've been tasked with onboarding Karantina to Google Fonts. To avoid data conflicts, please refrain from making changes to the repo as I will fork it and PR changes back to you if necessary. Also, please drop me a quick email to post@yanone.de as I want to ask you about submitting information about yourself for the designer profile. Thank you.

**Comment by yanone** [comment]
Issue posted: https://github.com/ronykoch/Karantina/issues/1

**Comment by yanone** [comment]
PR’d designer info: https://github.com/google/fonts/pull/3142

**Comment by yanone** [comment]
Upstream PR: https://github.com/ronykoch/Karantina/pull/2
