### ISSUE TITLE
Add f*ckxed font

### ISSUE THREAD

**Issue by VariableDeclared** [google/fonts#2839]
Hi,

Would it be possible to get the f*ckxed font added?

Many thanks,

The font can be found here: https://extinctionrebellion.nz/portfolio-items/fucxed-caps-regular/

Cheers
VD

**Comment by fitojb** [comment]
Unless it’s licensed under the OFL, it can’t be added to Google Fonts.

**Comment by CliveRussell** [comment]
I don’t want this font added to google fonts. I originated the font for non commercial use only. Putting it on google fonts will mean it can be used for advertising, merchandise etc etc.

**Comment by jestaris** [comment]
Is there an update for this font being added to google fonts?

**Comment by CliveRussell** [comment]
No, adding this font to google fonts is strictly forbidden. If this is added we will sue Google (This Ain’t Rock’n’Roll, designer of the font). This is fob non-commercial use only and Google allows its fonts to be used for commercial projects.

Thanks for your understanding.

Clive Russell

On 3 Apr 2022, at 12:37, jestaris ***@***.***> wrote:

﻿

Is there an update for this font being added to google fonts?
