### ISSUE TITLE
Inclusion of new custom Sharp (SHRP) axis

### ISSUE THREAD

**Issue by vv-monsalve** [google/fonts#2849]
This new custom axis ins included in [Geologisk](https://github.com/monokromskriftforlag/geologisk#variable-axis) to modify the top terminals of stems.
This would be the draft of the axis registry so we can review the ranges, fallbacks and values.

```

#SHARP based on https://github.com/monokromskriftforlag/geologisk/#variable-axis
tag: "SHRP"
display_name: "Sharp"
min_value: 0.0
default_value: 0.0
max_value: 100.0
precision: 1
fallback {
  name: "Flat"
  value: 0.0
}
fallback {
  name: "Sharp"
  value: 100.0
}
description: "Detailing and terminal treatment."
  "Modifies the slope of the sans serif stem terminals from flat to pointed"
  "As the sharpness increase, different levels of acuteness can be set"

```

![Sharp](https://user-images.githubusercontent.com/48698976/100890763-98473e80-3486-11eb-89f7-c169eca4b0e2.gif)

cc @m4rc1e @davelab6 @rsheeter

**Comment by vv-monsalve** [comment]
Note: The "Sharp" fallback name is also used in [SOFT](https://github.com/google/fonts/blob/master/axisregistry/softness.textproto) axis. Not sure if this could be a source of any conflict, in any case, for us to be aware of it.

**Comment by thlinard** [comment]
Perhaps, before creating the custom axes "Lightness" and "Narrowness", it would suffice to use "Weight" and "Width", and for "Soft" it would suffice to have a fairly broad definition, encompassing sharpness to one end and softness to another?

**Comment by m4rc1e** [comment]
Thank you for including the axis def and providing a gif. It's very clear.

> Note: The "Sharp" fallback name is also used in SOFT axis. Not sure if this could be a source of any conflict, in any case, for us to be aware of it.

Good point. I reckon this may cause some confusion so it's worth exploring other names if we do decide to include this axis.

How many glyphs do this axis modify and could you take a screenshot of a paragraph of text please?

**Comment by vv-monsalve** [comment]
**Letters**
![Sharp-letters](https://user-images.githubusercontent.com/48698976/100913844-4d3a2500-34a0-11eb-93c7-bc5ebf82a172.gif)

**Paragraph**
![Sharp-Paragraph](https://user-images.githubusercontent.com/48698976/100913818-47444400-34a0-11eb-8f15-ecc8615b019c.gif)

**SOFT behaviour in Fraunces**
![SOFT-DISPLAY](https://user-images.githubusercontent.com/48698976/100916460-c5561a00-34a3-11eb-9208-e47f251321ca.gif)
![80CBCCFE-89EB-4310-918D-BA52FAC623F2](https://user-images.githubusercontent.com/48698976/100916532-def76180-34a3-11eb-9b59-c29f533744d6.GIF)






As they are related by being antonyms, one may think the same "SOFT" axis could be used in its minimum value 0 with fallback name sharp. However, semantically it would imply a very different thing. You couldn't think on a sharp terminal as in Geologica in terms of soft, which would be particle the name that would appear in the Variable font. E.g. Geologica[SOFT,ital,slnt,wght].ttf instead of Geologica[SHRP,ital,slnt,wght].ttf

**Comment by thlinard** [comment]
> As they are related by being antonyms, one may think the same `SOFT` axis could be used in its minimum value 0 with fallback name `Sharp`. But semantically it would imply a very different thing. You couldn't think on a sharp terminal as in Geologica in terms of _soft_, which would be particle the name that would appear in the Variable font. E.g. Geologica[SOFT,ital,slnt,wght].ttf instead of Geologica[SHRP,ital,slnt,wght].ttf

Well, I see what you mean, but I'm not sure "Weight" is exactly the same thing to describe the weights of Didot and the weights of Futura, and yet we consider the same term "weight" to be suitable for both.

Maybe here a new axis is justified, but I wonder about this multiplication of axes, I have the impression that a new axis is proposed for each new font, and there is surely a way to unify all of that.

**Comment by davelab6** [comment]
If this is indeed limited to terminals, let's call it "Terminal Sharpness"
and have "Flat" and "Sharp" at 0 and 100

**Comment by vv-monsalve** [comment]
> If this is indeed limited to terminals, let's call it "Terminal Sharpness"

With tag: "TSHR" or "TESH" ?

**Comment by davelab6** [comment]
TSHR

**Comment by RosaWagner** [comment]
I would like to suggest "Terminal Angle" with fallback values which would correspond to angle in degrees.

**Comment by davelab6** [comment]
But the angles are all different

**Comment by RosaWagner** [comment]
Like optical size
Although, 0° and 90° are often used

**Comment by RosaWagner** [comment]
I mean, 180° (I thought 0 as flat)

**Comment by davelab6** [comment]
I don't follow. You don't get a style that has A-J as an optical size of 13
and K-Z of 32 and a-z of 64 and everything else 120, all found at opsz
value 8.

**Comment by RosaWagner** [comment]
True… this case is kind of tricky because some of the "sharp" terminals are kind of flat :/ I am searching for a more objective way of defining terminals shape.

**Comment by davelab6** [comment]
> I wonder about this multiplication of axes, I have the impression that a new axis is proposed for each new font, and there is surely a way to unify all of that.

We are currently onboarding a lot of "expressive" fonts, so I can see you might get that impression.

We decided against a unifying single "expression" XPRN axis that @arrowtype proposed, in favor of more specific/concrete but reusable (by other projects) axis definitions (like Casual CASL), so that you don't get wildly different visual results from the same axis. 

Family specific axes like Lexend LXND probably will be redefined for GF, but that won't reduce the sum total of axes defined across the library.

**Comment by thlinard** [comment]
> > I wonder about this multiplication of axes, I have the impression that a new axis is proposed for each new font, and there is surely a way to unify all of that.
> 
> We are currently onboarding a lot of "expressive" fonts, so I can see you might get that impression.
> 
> We decided against a unifying single "expression" XPRN axis that @arrowtype proposed, in favor of more specific/concrete but reusable (by other projects) axis definitions (like Casual CASL), so that you don't get wildly different visual results from the same axis.
> 
> Family specific axes like Lexend LXND probably will be redefined for GF, but that won't reduce the sum total of axes defined across the library.

Thanks Dave for the explanation, this is much clearer!

**Comment by vv-monsalve** [comment]
I see the point on avoiding an adjectival word as sharp/sharpness, although I agree on angles values could create more confusion.

What about "Terminal Slope"? it would be more universal and thus leave space for cases in which you could have a slope but a rounded one, or with a flair, or any other sort of form not as sharp as Geologica


```
tag: "TSLO"

fallback {
  name: "Flat"
  value: 0.0
}
fallback {
  name: "Sloped"
  value: 100.0
```

**Comment by vv-monsalve** [comment]
> > I wonder about this multiplication of axes, I have the impression that a new axis is proposed for each new font, and there is surely a way to unify all of that.
> 
> We are currently onboarding a lot of "expressive" fonts, so I can see you might get that impression.
> 
> We decided against a unifying single "expression" XPRN axis that @arrowtype proposed, in favor of more specific/concrete but reusable (by other projects) axis definitions (like Casual CASL), so that you don't get wildly different visual results from the same axis.
> 
> Family specific axes like Lexend LXND probably will be redefined for GF, but that won't reduce the sum total of axes defined across the library.

Great information also for the discussion on https://github.com/google/fonts/issues/2846 ;)

**Comment by arrowtype** [comment]
I don't see there being too much of a problem in having one family with a Sharp axis and another with a Soft axis. They mean opposite things, and each makes sense within its family – and as has been pointed out would make little sense in the other family.

Really, the main potential benefit I see in there being an axis registry is to avoid multiple families using the same axis name to mean something completely different, which could perhaps be a problem if a user was editing axes of multiple fonts at once in Illustrator, etc.

But, similar to how stylistic sets can have names specific to each family, and just have to make sense in their families, I think that a lot of "expression" or creative types of axes will just make sense to have specific names. We can't predict these before they are invented, and we shouldn't try to restrict them or we will put an artificial cap on creativity in type. So long as axes follow a few basic rules (have a name & four-letter uppercase tag, not conflicting outright with an existing axis), they should be fine.

**Comment by rsheeter** [comment]
I think there is a balance to be found between over-general to the point you can't predict what will happen and over-specific to the point every family has unique axes. Ideally we are able to land on axes that represent intuitive reusable concepts that can (and do) appear in many families.

I feel like we've visited both extremes. "Expression" as an axis was over-general. Now we're seeing every family wanting to do its own bespoke axes.

As ever naming things is the hardest part lol.

**Comment by davelab6** [comment]
> Now we're seeing every family wanting to do its own bespoke axes

What I see is different: Every new "expressive" family is arriving with axes which are new to the GF API, yet still **do** "represent intuitive reusable concepts that can appear in many families". 

They aren't families with "their own" axes. They are merely first.

These axes mostly don't currently appear in more than that initial family as of today, because I didn't commission more families like that, after the initial one. But there's no reason they won't be reused in future. 

For one, as @thlinard and @arrowtype says, each time we register an axis we should and will look to be sure it's not a duplicate concept (and we should consolidate and create reuse when there's an opportunity to do so.)

If we do another round of commissions where the primary goal is again to expand the number of expressive variable fonts in the GF library, I expect we will look to both grow "up" with new expressive axes concepts, and "across" by reusing axes that users are excited about, and do really use, to more and more families. 

That's always been my intent: For example, I've been keen in the last round to support people making all the tools and scripts they might develop during the course of their explorations to be just as available as their final fonts, so that any type designer who wants to apply those axes to their own projects has all the parts of the process in hand.

**Comment by vv-monsalve** [comment]
> Ideally we are able to land on axes that represent intuitive reusable concepts that can (and do) appear in many families.

> What I see is different: Every new "expressive" family is arriving with axes which are new to the GF API, yet still **do** "represent intuitive reusable concepts that can appear in many families".

Considering this, I would advocate again for changing this discussed axis from Terminal Sharpness to Terminal Slope, as I mentioned in the [comment above](https://github.com/google/fonts/issues/2849#issuecomment-738939428) to make it more general and therefore reusable.

**Comment by vv-monsalve** [comment]
When including the new axis values to the project, the fallback name `sloped` didn't feel quite descriptive of what it could mean and even confusing, as it could be taken as some sort of slant value, e.g.  Geologica_Sloped-Regular.ttf

In a conversation @RosaWagner and @yanone we consider this axis could be addressed in a broader way and be called "Terminal Shape" TSHP with different positions for each possible shape. Like this:

```
#TSHP based on https://github.com/monokromskriftforlag/geologisk/#variable-axis
tag: "TSHP"
display_name: "Terminal shape"
min_value: 0.00
default_value: 0.00
max_value: 2.00
precision: -2
fallback {
  name: "Plain"
  value: 0.00
}
fallback {
  name: "Pointy" (or "Spiky")
  value: 1.00
}
fallback {
  name: "Rounded"
  value: 2.00
}
description: "Adjust the shape of the stem terminals."
```

**Comment by vv-monsalve** [comment]
This issue was transferred to https://github.com/googlefonts/axisregistry/issues/43. Please follow up there.
