### ISSUE TITLE
How to when… VF with no weight axis

### ISSUE THREAD

**Issue by RosaWagner** [google/fonts#2859]
We have 2 fonts (Tilt #2854 and Ballet #2696) which have an axis but not a weight one. Ballet has never gone to sandbox and I don't know why, so I suspect the lack of weight axis, but not sure. 

So the question are: 
1. Are fonts without a weight axis allowed ?
2 How can we make it work ?

@yanone 
@m4rc1e 
@davelab6

**Comment by RosaWagner** [comment]
Resolved. We also have to make sure that the default position on the non-weight axes is registered in the axis axis registry.

**Comment by vv-monsalve** [comment]
> Resolved. We also have to make sure that the default position on the non-weight axes is registered in the axis axis registry.

_also_ as in addition to what else exactly?

**Comment by RosaWagner** [comment]
`Also` as `by the way` I guess.

**Comment by vv-monsalve** [comment]
Oh, ok, thanks.

**Comment by davelab6** [comment]
Please file an issue for a FB GF profile check for that.

**Comment by felipesanches** [comment]
new check implemented. Will be available on the next FB release.
