### ISSUE TITLE
Question about Playfair Display (Capital letters: J and Q)

### ISSUE THREAD

**Issue by frankiechanho** [google/fonts#2884]
Hello, 

I am having a question about the letter J and Q (Capital letters) in Playfair Display, please kindly check the image below 
![image](https://user-images.githubusercontent.com/75787181/101768917-31c6be00-3b21-11eb-8f17-4dfb9151e912.png)

______________________________________________________
For comparison, please kindly check the images below:
A - L
![image](https://user-images.githubusercontent.com/75787181/101769325-c5988a00-3b21-11eb-9f5d-c9b6cc5b1705.png)

M - X
![image](https://user-images.githubusercontent.com/75787181/101769448-eeb91a80-3b21-11eb-8e3a-5c6498cb7542.png)

Y - Z
![image](https://user-images.githubusercontent.com/75787181/101769525-114b3380-3b22-11eb-84fc-ba00169d454c.png)

The above images show the "J" and "Q" are the only 2 characters that crossing the bottom red line while the others are "build from there". May I ask are they (J and Q) made by reason, or just a mistake (sorry to say that)?
Thank you

**Comment by fitojb** [comment]
It's normal and there are literally thousands of typefaces designed in the last few centuries to have those two capitals extend below the baseline.

**Comment by fitojb** [comment]
I mean, have you never opened a book?

**Comment by frankiechanho** [comment]
Thank you for the quick response.

As I am doing profile design and tried to increase the first letter about 225% (like the images), and there are some stuffs just below the title.

The reason I asked about that just because I met a problem like the following image
![image](https://user-images.githubusercontent.com/75787181/101775219-18763f80-3b2a-11eb-8f87-287951999286.png)

I will try another way to achieve the similar purpose. 

Thank you for the confirmation.
