### ISSUE TITLE
Mulish corrupted in macOS?

### ISSUE THREAD

**Issue by davelab6** [google/fonts#2886]
A user wrote me,

> I am reaching out because we have a client that is unable to use Mulish font on her MacBook Pro. I have run troubleshooting with her and we continue to have issues with it not showing up correctly in any Word document. This font was working until we updated her to MacOS Big Sur.
> 
> Please note that I am able to replicate this issue on my Macbook as well also running MacOS big Sur.
> 
> Any guidance or known issues?
> 
> Mulish but in the list is illegible and in the following screenshot you can see that it is completely illegible but when I type my name wants to auto complete.
> 
> This client also uses the Lato Google font and that font has not had any issues.
> 
> Downloaded these directly from google fonts. I downloaded these earlier this week.
> 
> 
> <img width="1440" alt="image001" src="https://user-images.githubusercontent.com/261579/101825114-30829a80-3afb-11eb-9fd4-f16be375f05b.png">
>
> <img width="1440" alt="image002" src="https://user-images.githubusercontent.com/261579/101825127-337d8b00-3afb-11eb-914f-b3023ddc8cba.png">

**Comment by thlinard** [comment]
VF fonts don't work on MS Office for macOS, even Office 2019 or Office 365.

Solution:
https://github.com/google/fonts/tree/master/ofl/mulish/static

**Comment by RosaWagner** [comment]
Yep, this issue was part of the discussion for improving the zip's README.txt (to explicitly ask users to use statics in Mac Ms Office apps). 

Sometimes the default instance is displayed correctly though.
