### ISSUE TITLE
Inclusion of new custom axis Contrast Transition

### ISSUE THREAD

**Issue by vv-monsalve** [google/fonts#2888]
This new custom axis ins included in the WIP project Palindrome to change the principle contrast from translation to expansion.
This would be the draft of the axis registry so we can review the ranges, fallbacks and values.

```

#Contrast Principle base on https://github.com/originaltype/palindrome#variable-font
tag: "ctpr"
display_name: "Contrast principle"
min_value: 0.0
default_value: 0.0
max_value: 100.0
precision: 1
fallback {
  name: "Translation"
  value: 0.0
}
fallback {
  name: "Expansion"
  value: 100.0
}
description: "Contrast principle variates between translation and expansion"
  "The stress, construction, and serifs migrate from the angle and pressure control model
  of the broad-nibbed pen to the modulated results of the pointed pen"

```

![GIF-2020-12-10-23-37-14](https://user-images.githubusercontent.com/48698976/101862652-c8ef3e00-3b40-11eb-96b5-a23d623fb5fc.gif)

@m4rc1e @davelab6 @rsheeter

**Comment by davelab6** [comment]
1. ctpr -> CTPR
2. Since this is specifically changing the contrast principle from translation to expansion, I suggest a range 0.00 to 1.00 would be better than 1 to 100 so that it indicates 1 and 0 are "whole" designs and the intermediates are very intermediate.

**Comment by vv-monsalve** [comment]
> * ctpr -> CTPR

Sure, my bad.

> * Since this is specifically changing the contrast principle from translation to expansion, I suggest a range 0.00 to 1.00 would be better than 1 to 100 so that it indicates 1 and 0 are "whole" designs and the intermediates are very intermediate.

Ok, that makes sense

So it would be:

```

#Contrast Principle base on https://github.com/originaltype/palindrome#variable-font
tag: "CTPR"
display_name: "Contrast principle"
min_value: 0.0
default_value: 0.0
max_value: 1.0
precision: 1
fallback {
  name: "Translation"
  value: 0.0
}
fallback {
  name: "Expansion"
  value: 1.0
}
description: "Contrast principle variates between translation and expansion"
  "The stress, construction, and serifs migrate from the angle and pressure control model
  of the broad-nibbed pen to the modulated results of the pointed pen"

```

**Comment by davelab6** [comment]
The string formatting of the description isn't 100% right but yes this is a
great draft!

**Comment by tiroj** [comment]
As described, the axis implies there are only two ‘contrast principles’: _translation_ and _expansion_, to use Noordzij’s terms. While those are certainly the two most common modes of contrast, especially in European script typography, I don't think they are the only contrast principles—Noordzij himself also provides examples of _rotation_, and some forms of Arabic  script involve a possible fourth contrast model derived from tilting a broad nib on its corner for some strokes—, so I wonder if the proposed name and tag might be too general for what the axis actually does?

Re. the proposed description:
```
  "The stress, construction, and serifs migrate from the angle and pressure control model
  of the broad-nibbed pen to the modulated results of the pointed pen"
```
Pressure is the mechanism of expansion in writing, so is more associated with pointed pens, narrow quills, and brushes. In translation, pressure has only a minor role in writing, and in analysis of stroke contrast patterns in type is _all_ angle of the moving front. Maybe something like
```
  "The modulation between thick and thin strokes and their characteristic contrast patterns 
   migrates from that determined by the width and angle of a notional writing tool (e.g. a broad 
   nib pen) to that of the swelling line of a tool reacting to pressure (e.g. a flexible pointed nib 
   or brush)."
```

**Comment by vv-monsalve** [comment]
> so I wonder if the proposed name and tag might be too general for what the axis actually does?

I understand your concern and it is clear those are only two of the possible 'contrast principles', but, at the same time, as you pointed out, those are the most common modes of contrast. 
As I hear more often _Naming is the hardest part_. One of the struggles when [defining a new axis](https://github.com/google/fonts/issues/2849#issuecomment-739056374) is precisely how to achieve a name general enough (so that many other cases could be cover in the future) but also descriptive enough of what it does (so that it gets clear as possible from the tag itself, which is the component that is going to become a particle of the [font name](https://github.com/google/fonts/issues/2849#issuecomment-737421031) e.g. FontName[CTPR,opsz,wght].ttf).


> Pressure is the mechanism of expansion in writing, so is more associated with pointed pens, narrow quills, and brushes.

What I meant but wasn't clear was something like: "migrate from the model of angle and pressure-controlled of the broad-nibbed pen" (as in opposition to the variable pressure/expansion possible with a pointed nib) nevertheless, your suggestion makes it clearer and specific indeed, thanks.

**Comment by arturschmal** [comment]
> As described, the axis implies there are only two ‘contrast principles’: _translation_ and _expansion_, to use Noordzij’s terms. While those are certainly the two most common modes of contrast, especially in European script typography, I don't think they are the only contrast principles—Noordzij himself also provides examples of _rotation_, and some forms of Arabic script involve a possible fourth contrast model derived from tilting a broad nib on its corner for some strokes—, so I wonder if the proposed name and tag might be too general for what the axis actually does?

John raises a good point here. It's not my intention to limit contrast to only translation and expansion. Would "TREX" be a better name?

**Comment by davelab6** [comment]
Think of the ~~children~~ dinosaurs :P

**Comment by vv-monsalve** [comment]
> Would "TREX" be a better name?

I thought about it, but as a tag, I'm not sure it gives a good idea about what it does. I wonder if from the users' point of view it could lead to other associations to common words like Trace, Extreme, Extension, and of course the T. Rex association as is a broadly known expression.

> in my experience, 'modulation' is more internationally

Contrast Modulation sounds both general (to include more cases under it) and specific (to visualize what the axis does) enough.

In that case, I would say `CTMD` could be clearer and even wonder if the fallback names could be more generic, e.g. `Normal` (elidable) and `Modulated`, so that we can include any other case in the future, e.g. translation-rotation.

**Comment by davelab6** [comment]
> so that we can include any other case in the future, e.g. translation-rotation.

We can perhaps extend a range, once registered, but it is better to plan for that not to be possible. If the range is `0..100` then extending it doesn't make so much sense, while `0.00..1.00` can extend to `2.00` and `3.00` and so on more sensibly.

**Comment by vv-monsalve** [comment]
I'm not quite sure if I understand you. I thought of it as:

```
fallback {
  name: "Normal"
  value: 0.0
}
fallback {
  name: "Modulated"
  value: 1.0
}
```

So it wouldn't be limited to Translation to Expansion, and taking into consideration this:

> I suggest a range 0.00 to 1.00 would be better than 1 to 100 so that it indicates 1 and 0 are "whole" designs and the intermediates are very intermediate.

In the future Rotation feature of a design could be at the "Normal" 0.0 extreme and then "Translation" could be at 1.0 Modulated

**Comment by tiroj** [comment]
'Contrast modulation' suggests to me something like changing the amount of contrast between stroke weights, not necessarily the kind of contrast. It may help to pull apart the whole concept of stroke contrast, and consider how each can be addressed at the axis level. I would say stroke contrast has three elements: amount, location, transition.

**Amount** is the relative proportion of contrast between thick and thin strokes, with the polarity low -> high.

**Location** is the pattern of where the thick and thin strokes fall on the glyphs, with the polarity vertical -> horizontal (usually describing location of the heavy strokes, and even when diagonal stress is involved).

**Transition** is the pattern of how thick and thin strokes transition into each other.

I think this discussion is primarily about transition models, since it is in transition that the different patterns of translation and expansion are most evident.

**Comment by tiroj** [comment]
So the question for an axis would be 'What is the polarity of transition?'

**Comment by arturschmal** [comment]
> So the question for an axis would be 'What is the polarity of transition?'

I'm not sure if I'm following your definition of transition as you intend, but if transition is an attribute of contrast it's values can still be translation/expansion/rotation/...
I don't think there's a polarity to that in terms of quantitive opposites such as for other axes: high/low, thick/thin/, wide/narrow, straight/slanted. It's really different sorts.

As I see it this axis should either explicitly describe the transition from translation to expansion ( TR->EX), or the axis should be generic enough to allow for different contrast sorts at the poles. I'm leaning towards the latter with Dave's suggestion of `Contrast Stress`.

**Comment by vv-monsalve** [comment]
Coming back to this with fresh eyes

> It may help to pull apart the whole concept of stroke contrast, and consider how each can be addressed at the axis level. I would say stroke contrast has three elements: amount, location, transition

Considering this, there could be indeed three axis to address Contrast in the future: `Contrast Amount`, `Contrast Stress`, and the one discussed here `Contrast Transition`.

> We can perhaps extend a range, once registered, but it is better to plan for that not to be possible. If the range is 0..100 then extending it doesn't make so much sense, while 0.00..1.00 can extend to 2.00 and 3.00 and so on more sensibly.

>  if transition is an attribute of contrast it's values can still be translation/expansion/rotation/

Then, having this in mind, this Contrast Transition axis could have "Translation", Expansion" and "Rotation" at least to begin with, with values 0.0, 0.1, 0.2 as proposed.

It could be:

```
#Contrast Principle base on https://github.com/originaltype/palindrome#variable-font
tag: "CTTR" 
display_name: "Contrast Transition"
min_value: 0.0
default_value: 0.0
max_value: 2.0
precision: -1
fallback {
  name: "Translation"
  value: 0.0
}
fallback {
  name: "Expansion"
  value: 1.0
}
fallback {
  name: "Rotation"
  value: 2.0
}
description: "The modulation between thick and thin strokes and their characteristic contrast patterns migrates between different models of transition."

```

**Comment by arturschmal** [comment]
Do I understand it correctly that 0.0 and 1.0 values allow for in between variations, or does it mean "off" or "on"?

**Comment by vv-monsalve** [comment]
> Do I understand it correctly that 0.0 and 1.0 values allow for in between variations, or does it mean "off" or "on"?

Values were changed to 0.0, 1.0, 2.0 so that in indicates those are whole designs and the intermediates are very intermediate states, as Dave suggested. Precision `-1` means values can be as precise as one decimal place.

The "on" "off" behaviour would require a binary set, so third or more fallback instances couldn't be included.

**Comment by arturschmal** [comment]
Right, so it is possible to either through a GUI or CSS to acces intermediates. E.g. `CTTR: 0.2`.

**Comment by vv-monsalve** [comment]
> Right, so it is possible to either through a GUI or CSS to acces intermediates. E.g. `CTTR: 0.2`.

Yes, that would be the case.

**Comment by vv-monsalve** [comment]
This issue was transferred to [https://github.com/googlefonts/axisregistry/issues/42](https://github.com/googlefonts/axisregistry/issues/42). Please follow up there.
