### ISSUE TITLE
Add Oi

### ISSUE THREAD

**Issue by davelab6** [google/fonts#2892]
https://github.com/kosbarts/Oi (still private repo for now)

@kosbarts please add @RosaWagner 

@rosawagner kostas is still working on it, so its not ready to onboard yet, but please confirm if you want to take this or delegate to someone else

**Comment by RosaWagner** [comment]
I can take it

**Comment by kosbarts** [comment]
@RosaWagner just added you. Confirming some names with Dave and then I will make it public.

**Comment by RosaWagner** [comment]
Sure, just ping me when you want me to review and ship
