### ISSUE TITLE
Add Qahiri

### ISSUE THREAD

**Issue by davelab6** [google/fonts#2893]
Once https://github.com/alif-type/qahiri/pull/4 is merged and a new OFL release is out :)

@khaledhosny do you want to [learn how to] do the PR here, or should I ask eg @RosaWagner to do?

**Comment by khaledhosny** [comment]
> @khaledhosny do you want to [learn how to] do the PR here, or should I ask eg @RosaWagner to do?

Yes, I’d like to learn the new way of doing PRs here.

**Comment by RosaWagner** [comment]
Hi @khaledhosny, we are using [gftools packager](https://github.com/googlefonts/gftools/tree/master/docs/gftools-packager) now for the PRs. Don't hesitate if you have any questions.

**Comment by khaledhosny** [comment]
#2924
