### ISSUE TITLE
Castoro v1.20 b014

### ISSUE THREAD

**Issue by tiroj** [google/fonts#2898]
New builds of the Castoro fonts are available:
https://github.com/TiroTypeworks/Castoro

1. Revised design of uppercase eszett U+1E9E
2. Assorted minor outline fixes
3. Replaced build script with new tirobuild and associated config files.

**Comment by m4rc1e** [comment]
Thanks John. I've just sent a pr #2901

**Comment by tiroj** [comment]
Please see also b015 with frac feature fix.
