### ISSUE TITLE
Reformatting 'README.md' in tools/encodings/GF 2016 Glyph Sets/

### ISSUE THREAD

**Issue by kalapi** [google/fonts#292]
#### 1. Re-Arrange Text 
Move the 'Language support' list section to after the 'Structure and Heirarchy' section. 

#### 2. Update Some Character Set Descriptions

**Note**: Instead of listing the Unicode Ranges under the 'Google Latin Plus' section, it might be a useful to create a 'Unicode Ranges' sub-section and list all the ranges that the largest set (Expert) covers. This is mainly because the unicode ranges list may be a bit misleading. For e.g. the Latin Extended Additional block supports things like 'Medievalist Additions'. The Latin Extended B block supports 'African Linguistics', and 'Non-European and Historic Latin'. 

So the new contents would be: 

##### Google Latin Plus (Total Glyphs: 600)

* Western & Central European
* Vietnamese
* Currencies (₡ ₣ ₤ ₦ ₧ ₩ ₫ ₭ ₱ ₲ ₵ ₹ ₺ ₼ ₽)
* Alternate Numerals: Proportonal Lining

##### Google Latin Pro (Total Glyphs: 151)

* Math symbols and Units of Measure (∆ Ω π ℓ ℮ ∞ ∂ ∫ √ ∑ ∏ ◊)
* Latin General Use Extensions (u+1E08 to u+1EC9)
* Superiors and Inferiors (⁰ ⁴ ⁵ ⁶ ⁷ ⁸ ⁹ ₀ ₁ ₂ ₃ ₄ ₅ ₆ ₇ ₈ ₉)
* Spacing Modifier Letters (ʻ ʼ ʾ ʿ ˈ ˊ ˋ ˌ)
* Typographic Spaces (figure, punctuation, thin, hair, zero-width)
* Additional General Punctuation (‐ ‒ ― ′ ″)
* Alternate Punctuation Glyphs for Capitals
* Numerators and Denominators

##### Google Latin Expert (Total Glyphs: 274)

* Additional Unicode Fractions (⅓ ⅔ ⅛ ⅜ ⅝ ⅞)
* Arrows (← ↑ → ↓)
* Geometric Shapes (■ □ ▲ △ ▶ ▷ ▼ ▽ ◀ ◁ ◆ ◇)
* Small Capitals
* Discretionary Ligatures (T_h c_t c_h s_t)

**Comment by alexeiva** [comment]
@kalapi could you fix this in the new branch? https://github.com/google/fonts/tree/GF-2016-glyph-sets

**Comment by davelab6** [comment]
@alexeiva since Kalapi is working a deck to present his project, could you please take care of these updates? :)
