### ISSUE TITLE
Urdu fonts

### ISSUE THREAD

**Issue by Zeni241** [google/fonts#293]
May I please request for Urdu fonts in your collection such as 'Jamil Noori Nastaliq' or others. Some are given here http://www.urdujahan.com/font.html.
How can I contribute to your font collection?
Thanks

Zeni

**Comment by davelab6** [comment]
@Zeni241 thanks for you suggestion. The requirements for contributing new fonts are described in https://github.com/google/fonts/blob/master/CONTRIBUTING.md 

In this case, since I assume you're not the copyright holder for the fonts, you can contribute by reaching out to the rightsholders and asking them to "go OFL" :) 

I took a quick look at all 5 fonts available for download on that page, using the 'ttx' program to read their 'name' tables. 

## 1. Fajer Noori Nastalique 15-12-2006.ttf

This font's copyright notice reads,

> Copyright (c) M. G. Abbas Malik, 2006. All rights reserved.

The font also contains a license text which was not the SIL Open Font License:

> Fajer Noori Nastalique License Agreement
> 
> This document is a legal Agreement between you, the licensee, and Mr. M. G. Abbas Malik. Please read this Agreement carefully before downloading the font hereafter called product. By installing the product, you accept the terms of this Agreement. 
> 
> Following are the terms of the agreement:
> 
> 1. This product is licensed free of charge. There is no warranty for this product. Also Mr. M. G. Abbas Malik is not liable for any indirect, special, incidental or consequential damages arising out of the use or inability to use the product.
> 
> 2. This product is meant for personal and commercial use, it cannot however be sold in any form. Sale of this product is prohibited.
> 
> 3. This product cannot be modified, sublicensed, or distributed except with a written permission from Mr. M. G. Abbas Malik. 
> 
> 4. Also a written certificate of permission is required from Mr. M. G. Abbas Malik if this product or any of its components are to be used in a package. Contents of this product in part or whole cannot be copied or\and used for any other development.

Sadly contacting Mr Abbas Malik may be hard, as the font contained a link (puran dot info) which is now a porn site. 

## 2 + 3, Jameel Noori Nastaleeq Kasheeda.ttf + Jameel Noori Nastaleeq.ttf

There was no contact information in these 2 fonts; the copyright notice was, 

> This Font Is Free Of Charge For Urdu Lovers

## 4. Pak Nastaleeq (Beta Release).ttf

> Copyright (c) Center of Excellence for Urdu Informatics, 2005. All rights reserved.

This had a link to http://www.nla.gov/ceui but that domain is no longer working. There was an email to `m_hijazee@yahoo.com`, would you like to contact them?  

## asunaskh.ttf

This font's family name is `Urdu Naskh Asiatype` and the copyright notice is, 

> (C) Asiasoft (A), Asiatype (TM) 1994-2001. All Rights Reserved.

I'd be grateful if you could find them and reach out :)

**Comment by tariqinaam** [comment]
is it possible to add 2 + 3, Jameel Noori Nastaleeq Kasheeda.ttf + Jameel Noori Nastaleeq.ttf, though there is no contact info available. What would be the best way to get this added.

**Comment by eliheuer** [comment]
Ideally, there should be at least a few nastaʿlīq fonts on GF. Jameel Khuskhati Regular has some issues but with a bit of work it could be a good addition.

Here I am testing Jameel Khuskhati Regular in Drawbot:
![Screen Shot 2019-04-13 at 8 45 47 PM](https://user-images.githubusercontent.com/5162664/56086886-01032280-5e2e-11e9-8fd3-62aed005909d.png)

And an idea of what the output should look like, there are some issues:

![nas](https://user-images.githubusercontent.com/5162664/56086895-1d06c400-5e2e-11e9-882f-071f3c583d39.jpeg)

**Comment by davelab6** [comment]
Is it OFL? :)

**Comment by laerm0** [comment]
Nastaʿlīq is always like the final frontier in font technology. I'd love to get it on GF. Let me know if I can help, @eliheuer .

**Comment by davelab6** [comment]
Noto Urdu Nastaliq is likely the best bet. It's in
fonts.google.com/earlyaccess

**Comment by eliheuer** [comment]
I talked to @behdad about this today and he said that it should be fine to move Noto Nastaliq out of early access.

**Comment by baig** [comment]
@eliheuer I'm a native Urdu speaker and I am more familiar with Urdu than Farsi/Persian. The two renderings that you included above, the top one is closer to Urdu Nastaleeq. Here is another example of Urdu Nastaleeq rendering taken from [here](https://www.urduweb.org/mehfil/threads/%D8%AA%D8%B9%D8%A7%D9%88%D9%86-%D8%A8%D8%B1%D8%A7%D8%A6%DB%92-%D8%A7%D8%AE%D8%B1%D8%A7%D8%AC%D8%A7%D8%AA-%D8%A7%D8%B1%D8%AF%D9%88-%D9%88%DB%8C%D8%A8-%D8%B3%D8%A7%D9%84-%D8%B3%DB%8C%D8%B2%D8%AF%DB%81%D9%85.101895/):

![urdu-nastaleeq](https://user-images.githubusercontent.com/231639/58195420-c7b7a100-7c7c-11e9-9d31-6f48fd28ab05.JPG)

**Comment by Zeni241** [comment]
> There was no contact information in these 2 fonts; the copyright notice was,
> 
> This Font Is Free Of Charge For Urdu Lovers

So what is holding you? Get it ( Jameel Noori Nastaleeq ) added as google font please.

**Comment by Zeni241** [comment]
All the news papers in Pakistan are using Jameel Noori Nastaleeq, I think non of them ever bothered about license. May be because its free for all Urdu lovers ( or Lovers of Urdu :))

**Comment by eliheuer** [comment]
If we can get Jameel Noori Nastaleeq licenced under the OFL I will make a pull request. @Zeni241 Would you want to make a Repo for Jameel Noori Nastaleeq and put it under the OFL license?

**Comment by davelab6** [comment]
Is zeni owning the complete copyright?

**Comment by behdad** [comment]
I don't believe zeni owns the copyright.

Two issues:

1. There doesn't seem to be an authoritative release of Jameel Noori Nastaleeq.  The stories I've heard has been varied.  But yes, the font files have "This Font Is Free Of Charge For Urdu Lovers" as license description in name table.  It was originally created by Jameel and Monotype, and ships in the commercial software InPage to this day.

2. The font is 13MB or more.  Basically because it has ligatures for most common Urdu word skeletons.  In comparison, Noto Nastaliq Urdu is like 200kb or so.

There's a couple of good links from https://en.wikipedia.org/wiki/InPage
Maybe we should have someone reach out to the people involved and try to get it released under OFL.  Then we can have others look into possibility of reducing the glyphset.

**Comment by eliheuer** [comment]
For anyone who doesn't have time to open it in a font editor, this is what the metadata looks like:
![Urdu_Lover](https://user-images.githubusercontent.com/5162664/58297017-19a71680-7da4-11e9-928e-c78ab97a9257.png)

**Comment by eliheuer** [comment]
The drawings could use some cleanup and the UPM could be changed to 1000 to reduce file size. Maybe doing a complete redrawing of this would be a good thing to try using GitHub Sponsors for?
![urdu](https://user-images.githubusercontent.com/5162664/58298428-7953f080-7da9-11e9-9673-f94499895b9c.png)

**Comment by Zeni241** [comment]
> I don't believe zeni owns the copyright.

You are right, I don't own the copyright but I believe no one does.


> @Zeni241 would you want to make a repo on GitHub for Jameel Noori Nastaleeq and put it under the OFL license?

I am ready to do anything (short of getting my tail crunched in legal machine :) ) as this would mean a dream come true for me as "Urdu lover".
Give me a few days to complete the project I am currently involved in, and I will try my best to clean it in some font editor and make a repo on GitHub for and put it under the OFL license. If I face any problem in this, I will post it here.

**Comment by davelab6** [comment]
Do not put a license on something you do not own!

**Comment by Zeni241** [comment]
> Do not put a license on something you do not own

Do you mean I shouldn't make a repo on GitHub under OFL or just don't put a license?

**Comment by davelab6** [comment]
If you don't have a license, you shouldn't keep a copy of the fonts. The
confused licensing situation around this font makes it toxic, for me. I
deleted my copy as soon I took a close look.

Definitely don't apply the ofl to fonts you don't own.

**Comment by jabranr** [comment]
The calligrapher who wrote this typeface: https://en.wikipedia.org/wiki/Ahmed_Mirza_Jamil
The digital conversion of this typeface is still unknown but I am trying to find within my circle of friends who are into Urdu typography. Will update here once I have some more information.

@eliheuer which software did you use in your screenshots above? 

I have had long wished to somehow contribute or create an Urdu typeface for web. Typography is not my primary field though but I am sure given the resources and time, I can achieve some good milestones in it with some learning. If anyone could point me to some good starting point regarding this then I would be grateful.

**Comment by jabranr** [comment]
I have also found this extensive newspaper article that goes to history of this font but the article is in Urdu. It seems like the Monotype Imagining Corporation worked with the calligrapher "Ahmad Mirza Jamil" to digitise this font as part of the software "InPage".

https://www.express.pk/story/197175/

**Comment by tariqinaam** [comment]
My brother in India has worked with these people and this is what He says:
The font was written by Ahmad Mirza Jamil and then digitizing was done by Inpage software corp India. But after digitizing, the partnership broke down. 
I have a contact with the person (Manzar Ali) who actually did the digitizing with Inpage corp. He now has it's own company (Axis Media) and created a similar font. I can speak to him about the license.

**Comment by Zeni241** [comment]
With so many urdu lovers something good is bound to happen.

**Comment by Faizi-Apps** [comment]
Any update??????????
font file is about 8 mb .why?

**Comment by zyxhere** [comment]
Should this issue be closed now since noto has an urdu font with  Noto Nataliq urdu?
If you're looking for a similar font to Jameel noori Nastaleeq there is awami nastaliq which is OFL licensed http://software.sil.org/awami

**Comment by simoncozens** [comment]
We have a new version of Noto Nastaliq, and Google has also commissioned a free Urdu font, Gulzar. https://fonts.google.com/specimen/Gulzar

I'm not aware of any other libre Urdu fonts. (Awami Nastaliq requires SIL's custom rendering engine to function correctly, so is not suitable for general purpose use.) If there are any, please open an issue to onboard them.
