### ISSUE TITLE
Add Akshar

### ISSUE THREAD

**Issue by tallchai** [google/fonts#2931]
Request to add **Akshar**, an opentype variable Devanagari (and Latin) display typeface.
It supports two axes: Weight (`wght`) and Contrast (`cntr`).
Github repo: https://github.com/tallchai/akshar-type

Akshar (Hindi: अक्षर) literally means an alphabet or a letter in Hindi, Marathi, Gujarati and other Indic languages.

Development Tool: Glyphsapp
License: OFL

Font hinted with `gftoools`.
Not built with `fontmake` because it currently does not completely support Devanagari conjuncts.
Open GitHub fontmake issue: https://github.com/googlefonts/fontmake/issues/706

Display Posters:
![Akshar Intro](https://raw.githubusercontent.com/tallchai/akshar-type/main/images/Akshar%20Intro.jpg)
![Akshar Weights](https://raw.githubusercontent.com/tallchai/akshar-type/main/images/Akshar%20Weights.jpg)
![Akshar Weights: High Contrast](https://github.com/tallchai/akshar-type/raw/main/images/Akshar%20Weights%20HC.jpg)
![Akshar Headlines](https://github.com/tallchai/akshar-type/raw/main/images/Akshar%20Headlines.jpg)
![Akshar Headlines EN](https://raw.githubusercontent.com/tallchai/akshar-type/main/images/Akshar%20Headlines%20EN.jpg)
![Akshar OpenType](https://user-images.githubusercontent.com/73443155/113074711-91f97280-9199-11eb-8cf9-10e807aa05fa.jpg)
![Akshar 99](https://raw.githubusercontent.com/tallchai/akshar-type/main/images/Akshar%2099.jpg)
![Akshar Default](https://raw.githubusercontent.com/tallchai/akshar-type/main/images/Akshar%20Default.jpg)
![Akshar Default: High Contrast](https://github.com/tallchai/akshar-type/raw/main/images/Akshar%20Default%20HC.jpg)
![Akshar Characters](https://github.com/tallchai/akshar-type/raw/main/images/Akshar%20Characters.jpg)
![Akshar Characters: High Contrast](https://github.com/tallchai/akshar-type/raw/main/images/Akshar%20Characters%20HC.jpg)

**Comment by davelab6** [comment]
This looks great, I'm looking forward to seeing this in the gf library. 🙏

**Comment by tallchai** [comment]
> This looks great, I'm looking forward to seeing this in the gf library. 🙏

Great! 😄 
How do we proceed?

**Comment by tallchai** [comment]
@davelab6 @RosaWagner Just checking on the status for this font.
