### ISSUE TITLE
Noto Sans in every language and can't erase them

### ISSUE THREAD

**Issue by NTJJHY** [google/fonts#2932]
![1](https://user-images.githubusercontent.com/76424494/102751592-6b15ee00-43ab-11eb-921d-9e0f9ccf3745.jpg)
Can somebody help me with this problem?
To start, I have no knowledge of programming because I'm just a photographer, filmmaker using Adobe apps with Mac(Catalina) and Windows 10.
I formatted my Mac drive, Mac font manager, Windows 10 font folder multiple times but this kind of Noto Sans fonts doesn't get deleted! And also, I cant see these fonts in the font manager(Mac), and font folder(Windows 10), but it keep comes out on the Adobe Programs!!
Can somebody plz tell me how to get rid of these Noto Sans fonts?
I asked the biggest artist community in Korea, and found out that a bunch of people have the same problem have the same problem, but none have solved it. Everyone just gave up with this problem.
Plz save the korean artists

**Comment by Daymarius** [comment]
Korean epidemic of Noto Sans?

**Comment by maxloh** [comment]
What OS are you using?

**Comment by NTJJHY** [comment]
> What OS are you using?

To start with the conclusion, I found why it happens and how to solve it.
I'm using Catalina Version of macOS, and this problem happens because of Apple.
Apple added great numbers of fonts as a system default font and didn't allow people to adjust them(Don't know why)
-> 'Fonts included with macOS Catalina' [https://support.apple.com/en-us/HT210192](url)
So sadly, we have to see these fonts whether we like it or not.

**Comment by NTJJHY** [comment]
For people who have the same problem with me and found this article somehow, there were wonderful people who helped me out with this problem.
I don't have enough time to arrange them all, so I'll submit the links to help you solve this problem.
It would be easy if you read the links by number orders.
To add, you would need a Mac(iMac, Mac Mini, Macbook...etc any mac products that works with macOS), USB, External Harddrive.
I strongly recommend you to study about related knowledges in these links
1. Why this happens : 'Catalina Update - font issue' [https://discussions.apple.com/thread/251056217](url)
2. Solving Method : 'Noto Fonts'[https://discussions.apple.com/thread/251126005](url)
3. Solving Method : 'How do I get rid of the Noto font family?'[https://discussions.apple.com/thread/250770888](url)
4. Solving Method : 'How do I get rid of Apple's system fonts from external booting drive?'[https://discussions.apple.com/thread/252223663?answerId=254220599022&page=1](url)
5. Solving Method : 'How to create a bootable installer for macOS'[https://support.apple.com/en-mide/HT201372](url)
