### ISSUE TITLE
[Question] font file size difference

### ISSUE THREAD

**Issue by moocan** [google/fonts#2936]
Hello,

I woud like to know why there is a file size difference between font (for same release and version) downloaded on `https://fonts.google.com/` and `https://github.com/google/fonts/`.

Font files from `https://fonts.google.com/` are always smaller than files from `https://github.com/google/fonts/` for all family.

Sometimes the file size difference is very significant (> 200kb). Is there any "Optimization" or are they unhinted or something else ? I have searched about it but does not find anything.

An example with `Crimson Text`

- From `https://fonts.google.com/` `Download Familly`

```
CrimsonText-Bold.ttf  64424
CrimsonText-BoldItalic.ttf  50132 
CrimsonText-Italic.ttf  87932 
CrimsonText-Regular.ttf 125568
CrimsonText-SemiBold.ttf  52676
CrimsonText-SemiBoldItalic.ttf  50080
```
- From `https://github.com/google/fonts/`

```
CrimsonText-Bold.ttf  93768
CrimsonText-BoldItalic.ttf  75680 
CrimsonText-Italic.ttf  99800 
CrimsonText-Regular.ttf 189596
CrimsonText-SemiBold.ttf  77596
CrimsonText-SemiBoldItalic.ttf  75580
```

I wish you a Merry Christmas and an Happy Ney Year.

Thank you in advance.
Kind Regards

**Comment by Daymarius** [comment]
Different versions.

**Comment by moocan** [comment]
@Daymarius 

Thanks for your answer.
I was thinking a little about that but all files (old and new) are reporting exactly the same version.

Kind Regards

**Comment by kenmcd** [comment]
@moocan 
The fonts here are bigger because they have approx. 570 more glyphs.
Looks like they added the glyphs for many OpenType features but did not add the features.
Glyphs are now there for small caps, subscript, superscript, scientific inferiors, ordinals, proportional figures, slashed zero ... but the OpenType code is not there to use them.
