### ISSUE TITLE
IM Fell italic $ defaulting to M on Firefox

### ISSUE THREAD

**Issue by amandablum** [google/fonts#295]
When using any of italic variants of the IM Fell family font, the dollar sign ($) displays fine in chrome, opera, etc but in Firefox will display as a capital M (M).

**Comment by davelab6** [comment]
@amandablum Thanks for reporting! 

However, I can't reproduce this... I tested with Firefox v50.0a1 (2016-07-16) on Mac OS X 10.11.5 visiting https://jsbin.com/kakima/1/edit - works fine for me. 

<img width="804" alt="screen shot 2016-07-17 at 2 09 27 pm" src="https://cloud.githubusercontent.com/assets/261579/16902262/30263342-4c28-11e6-948f-9dd32787e658.png">

**Comment by amandablum** [comment]
then it might be a windows problem. Win 7, FF47.

**Comment by laerm0** [comment]
This does not appear to be an issue anymore on Windows or Mac.

![screen region 2017-09-06 at 16 02 35](https://user-images.githubusercontent.com/10780161/30132020-f110ae20-931c-11e7-9358-4c456402456f.png)
