### ISSUE TITLE
Add Generative Fonts (Summary)

### ISSUE THREAD

**Issue by davelab6** [google/fonts#2961]
@NaN-xyz has published [generativefonts.xyz](https://generativefonts.xyz) with 28 single-style display families derived from Rubik using 'generative scripts' that work sort of like "Photoshop Filters for Font Editors". 

@nan-xyz has confirmed with Hubert & Fischer to use the Rubik name for these.

**upstream:** https://github.com/NaN-xyz/Rubik-Filtered

- [x] #3705 
- [ ] #4698
- [ ] #4697 
- [x] #3704
- [x] #3706
- [x] #3707 
- [x] #3708 
- [x] #3709 
- [x] #3710 
- [x] #3711 
- [x] #3712 
- [x] #3713 
- [x] #3714 
- [x] ~#3715~ filter doesn't exist 
- [x] #3716 
- [x] #3717 
- [x] #3718 
- [x] #3719 
- [x] #3720 
- [x] #3721 
- [x] #3722 
- [x] #3723 
- [x] #3724 
- [x] #3725 
- [ ] #3726 
- [x] #3727 
- [x] #3728 
- [x] #3729 
- [x] #3730 
- [x] #4725

**Comment by RosaWagner** [comment]
Ok noted in the to do

**Comment by RosaWagner** [comment]
- [ ] Rubik-Bubbles-Regular.ttf
- [ ] Rubik-Beastly-Regular.ttf
- [ ] Rubik-BrokenFax-Regular.ttf
- [ ] Rubik-Burned-Regular.ttf
- [ ] Rubik-Dirt-Regular.ttf
- [ ] Rubik-Distressed-Regular.ttf
- [ ] Rubik-DoodleShadow-Regular.ttf
- [ ] Rubik-DoodleTriangles-Regular.ttf
- [ ] Rubik-Gemstones-Regular.ttf
- [ ] Rubik-Glitch-Regular.ttf
- [ ] Rubik-GlitchPop-Regular.ttf
- [ ] Rubik-Goo-Regular.ttf
- [ ] Rubik-Iso-Regular.ttf
- [ ] Rubik-Lines-Regular.ttf
- [ ] Rubik-Maps-Regular.ttf
- [ ] Rubik-MarkerHatch-Regular.ttf
- [ ] Rubik-Maze-Regular.ttf
- [ ] Rubik-Microbe-Regular.ttf
- [ ] Rubik-MoonRocks-Regular.ttf
- [ ] Rubik-Pixels-Regular.ttf
- [ ] Rubik-Puddles-Regular.ttf
- [ ] Rubik-Scribble-Regular.ttf
- [ ] Rubik-SeaCamouflage-Regular.ttf
- [ ] Rubik-SprayPaint-Regular.ttf
- [ ] Rubik-Storm-Regular.ttf
- [ ] Rubik-Vinyl-Regular.ttf
- [ ] Rubik-WetPaint-Regular.ttf

**Comment by davelab6** [comment]
> `Rubik-Bubbles-Regular.ttf`

Needs to be `RubikBubbles-Regular.ttf` :) I moved to the top post so the Github UI shows progress

**Comment by RosaWagner** [comment]
@NaN-xyz please update progress status for Batch 3 in this issue :)

**Comment by chrissimpkins** [comment]
Closing.  Let's open separate per family issue trackers for any outstanding work here.
