### ISSUE TITLE
dead link

### ISSUE THREAD

**Issue by slk333** [google/fonts#2969]
<img width="1357" alt="Screenshot 2021-01-21 at 00 58 37" src="https://user-images.githubusercontent.com/23578949/105255443-d823cb80-5b83-11eb-9f01-3112b0377607.png">
<img width="216" alt="Screenshot 2021-01-21 at 00 58 42" src="https://user-images.githubusercontent.com/23578949/105255446-d954f880-5b83-11eb-8851-fe35c9bc6638.png">

Clicking Monotype leads to a 404

https://fonts.google.com/?query=Neue+Haas+Grotesk

**Comment by fitojb** [comment]
The redesign dropped the feature that looked up proprietary fonts.
