### ISSUE TITLE
Major and Minor Bugs in GF 2016 Glyph Sets

### ISSUE THREAD

**Issue by kalapi** [google/fonts#298]
#### Major

- [ ] The following characters should be removed from the list as (1) is used in African languages (and part of the non-European and Historic Latin script group), and (2) is the lowercase variant, part of the IPA Extensions script group). 	

(1) [line 180; 'Plus'] 0x019D  Ɲ Nhookleft
(2) [line 181; 'Plus'] 0x0272  ɲ nhookleft
(3) [line 117; 'Expert'] nhookleft.sc

- [ ] [Line 256; 'Expert'] - 'i.sc.TRK.sc' should not be included since it is the same as 'I.sc'.

- [ ] Remove the PUA code points causing 'tofu' as seen the following instances:

![screen shot 2016-07-01 at 09 46 41](https://cloud.githubusercontent.com/assets/15804460/16511742/2b793d26-3f71-11e6-8741-8c4caed902c2.png)
![screen shot 2016-07-01 at 09 46 56](https://cloud.githubusercontent.com/assets/15804460/16511743/2dabf0e8-3f71-11e6-9a0e-57f0e3893043.png)
![screen shot 2016-07-01 at 09 47 07](https://cloud.githubusercontent.com/assets/15804460/16511744/2fb3cf14-3f71-11e6-9092-a697c892be4b.png)

#### Minor

- [ ] Add 'emptyset' 0x2205 (Refer: https://github.com/impallari/Libre-Franklin/issues/6)

**Comment by alexeiva** [comment]
Good point. I will move those ligatures to recommended list

**Comment by alexeiva** [comment]
Empty set is already three. See my GF2016-fix branch

**Comment by kalapi** [comment]
@alexeiva there seem to be some merge conflicts in Gf2016 fix #302. Could you please review these and re-commit?

**Comment by davelab6** [comment]
@kalapi since https://github.com/google/fonts/pull/302 is a branch in this repo, you can push commits to that branch and then merge it

**Comment by alexeiva** [comment]
hi @kalapi. I am working on the GF2016 branch, my 2 commits fix both #298 and #292:
https://github.com/google/fonts/pull/302/commits

I think it's better to work on that branch, and then merge to master. 
Are there any more issues? If not, perhaps we can merge the branches

**Comment by davelab6** [comment]
@alexeiva can this be closed?

**Comment by alexeiva** [comment]
yes
