### ISSUE TITLE
CSS API Bug - Josefin Sans

### ISSUE THREAD

**Issue by DecliningLotus** [google/fonts#2993]
This is a somewhat concerning bug since it seems that Google isn't serving the right weights for the font Josefin Sans. However, I'm not sure if this issue is isolated to this font specifically or others may be experiencing the same issue.

I've quoted the original message from the reference below:

> https://fonts.googleapis.com/css2?family=Josefin+Sans:wght@400;700
>
> You can compare the two weights:
> 
> ```css
> /* latin */
> @font-face {
>   ...
>   font-weight: 400;
>   src: url(https://fonts.gstatic.com/s/josefinsans/v17/Qw3aZQNVED7rKGKxtqIqX5EUDXx4.woff2) format('woff2');
>   ...
> }
> ```
> 
> and
> 
> ```css
> /* latin */
> @font-face {
>   ...
>   font-weight: 700;
>   src: url(https://fonts.gstatic.com/s/josefinsans/v17/Qw3aZQNVED7rKGKxtqIqX5EUDXx4.woff2) format('woff2');
>   ...
> }
> ```
> 
> The source files link to the exact same URL (my user agent is with the current latest Chrome update 88). What's even weirder is that this bug seems to have been present for more than [6 months](https://github.com/fontsource/fontsource/tree/master/packages/josefin-sans/files). 

I haven't had the time to test this around with more user-agents and see if there's a difference, but this does seem to be affecting all the different subsets and other weights (you can try including other weights like 100 into the CSS API query) the same way.

Reference: fontsource/fontsource#142

**Comment by davelab6** [comment]
It's correct; you get the variable font file which contains both weights

**Comment by davelab6** [comment]
You can continue to use the old css API too, so I'm closing this as WAI
