### ISSUE TITLE
Arbutus Slab printer issues

### ISSUE THREAD

**Issue by davious** [google/fonts#301]
When I installed Arbutus Slab on my mac (El Capitan 10.11.15), it noted that their were some minor issues.

When I attempt to print a document with it, I get this message printed:
`ERROR: invalidfont`
`OFFENDING COMMAND: xshow`

**Comment by alexeiva** [comment]
I couldn't reproduce your problem. What program are you using for printing?

The font installs fine via FontBook on El Capitan, meaning it should be valid.
I used latest version of Arbutus Slab from [github](https://github.com/google/fonts/blob/master/ofl/arbutusslab/ArbutusSlab-Regular.ttf)

**Comment by davelab6** [comment]
I downloaded it from fonts.google.com and it installed fine:

![screen shot 2016-07-16 at 4 05 25 pm](https://cloud.githubusercontent.com/assets/261579/16898739/54459d7c-4bb4-11e6-9ac2-3be84fe27668.png)

**Comment by davious** [comment]
@davelab6 I am referring to Arbutus Slab 
![screen shot 2016-07-21 at 8 36 33 am](https://cloud.githubusercontent.com/assets/632416/17022824/41d0fd7c-4f1e-11e6-8b31-c8489a861137.png)

**Comment by davious** [comment]
The font installs fine. 

Here is a related discussion on adobe's forum
https://forums.adobe.com/thread/1572483

Maybe it's just my printer; but, I wonder why it's just for this font.

**Comment by m4rc1e** [comment]
LGTM.

![img_8085](https://user-images.githubusercontent.com/7525512/27689207-67548486-5cd5-11e7-9db0-77c72fcb3ef6.JPG)


Printer HP LaserJet 4100 series, Pages 5.6.2, Mac OS X 10.12.4

I'm guessing the font has been updated since this issue was filed. 

@davious hopefully you can confirm all work well for you now?

**Comment by davious** [comment]
Thanks @m4rc1e. Works for me now too. Who knows what the deal had been. Thanks for checking. 😊
