### ISSUE TITLE
Hindi sentences end with a full stop.

### ISSUE THREAD

**Issue by ivmarkp** [google/fonts#304]
E.g. the sentence in Noto Sans, `अंतरिक्ष यान से दूर नीचे पृथ्वी शानदार ढंग से जगमगा रही थी.` ends with a full stop. But Hindi sentences usually end with "purnaviram" symbol i.e. `|` not a full stop. It's just a pipe symbol or vertical bar and can be typed on a QWERTY keyboard with the combination of shift key and backslash `\` key.

So, probably the best idea is to replace full stops at the end of Hindi sentences with purnaviram symbol.

**Comment by davelab6** [comment]
Thanks @ivmarkp I'll look into this

**Comment by ivmarkp** [comment]
Thanks for acknowledging this issue. Although, I just realised ...
> It's just a pipe symbol or vertical bar and can be typed on a QWERTY keyboard with the combination of shift key and backslash "\" key.

... this might not be a good alternative for purnaviram symbol. It's essentially a symbol from english typography so it might not fit well with hindi typography. We might wanna look at hindi typography for better options.

**Comment by davelab6** [comment]
@ivmarkp yeah using the ascii pipe is an old school hack; the Unicode character is https://en.wikipedia.org/wiki/Danda

**Comment by omerziv** [comment]
@shyndman I think this is related to our text samples?

**Comment by laerm0** [comment]
This appears to still be an issue. I dunno if the fonts we have all have the danda but switching our sample texts seems like a good idea.

**Comment by shyndman** [comment]
All except Decco have the danda.

Do spaces follow a danda as they do a period?

**Comment by shyndman** [comment]
After some searching, it appears that they do. In some cases it looks as if a space precedes as well. Can I get confirmation?

**Comment by ivmarkp** [comment]
To add my little input here; speaking from my experience (Hindi being my native language), I think a space always precedes a danda. But with that said, I've also seen some texts without the preceding space. In any case though, I think a preceding space would eliminate the possibilities of confusing the ending danda with one of the "matras" (`आ`).

**Comment by vikas-ghode** [comment]
it is not best practice to use full stop for hindi. since | is used to. also in marathi language which is child of hindi(which again child of sanskrit, using |) uses full stop(.) for completing sentences. I have problem with google indiac keyboard for not having full stop on marathi keyboard in main panel of letters.

**Comment by anilimcool** [comment]
does any body have any idea while typing how to type hindi full stop(Danda) using voice typing.

**Comment by hemantathalye** [comment]
> it is not best practice to use full stop for hindi. since | is used to. also in marathi language which is child of hindi(which again child of sanskrit, using |) uses full stop(.) for completing sentences. I have problem with google indiac keyboard for not having full stop on marathi keyboard in main panel of letters.

Hindi ago 200 years
Marathi age 2200+ years 😂

**Comment by vikas-ghode** [comment]
धन्यवाद, हिंदी भाषा प्रेमी की तरफ से।
