### ISSUE TITLE
Fonts no longer displaying in Internet Explorer 11

### ISSUE THREAD

**Issue by djaycee** [google/fonts#305]
Fonts were displayed correctly for the longest time, but I started seeing these errors suddenly a few hours ago with the latest version of IE 11 (version: 11.306.10586.0; update version: 11.0.31 - KB3154070) with the 2 fonts I am using (Tangerine & Montez):

CSS3111: @font-face encountered unknown error.
HGfsyCL5WASpHOFnouG-RD8E0i7KZn-EPnyo3HZu7kw.woff
This is for Tangerine

CSS3111: @font-face encountered unknown error.
Zfcl-OLECD6-4EcdWMp-Tw.woff
This is for Montez

I couldn't tell for the Edge browser because it is not even starting on my Windows 10.

**Comment by davelab6** [comment]
@djaycee thanks for reporting this :) Does the issue occur for you on this page too, or on any other browser? https://jsbin.com/luhete/2/edit?html,output

**Comment by djaycee** [comment]
@davelab6 you are welcome :) Yes the problem is the same on this page. I noticed afterwards that the problem seems to be general with all fonts, and the problem extends to those that are available via Adobe edgewebfonts as well. The latest version of Explorer just doesn't want to display them anymore. 

There seems to be history, it has already been the case with previous versions of Explorer in the past and the Google team back then solved the problem by serving WOF fonts instead of EOF fonts if I remember well what I read, so I guess Microsoft decided to be even stricter and bring the problem back on the table. From sources I read here and there on the internet, one cause might be that the font name and font family name are different and Microsoft doesn't like that. I tried fixing that using fontforge but I wasn't successful at getting rid of the problem... so I gave up.

I haven't had the time yet but I am planning on giving it a try to an alternative approach and use the "webfont loader", I found out about it a few days ago on https://developers.google.com/fonts/docs/webfont_loader and https://github.com/typekit/webfontloader , I hope this will work... else I guess it will be game over :)

**Comment by jamiechong** [comment]
@djaycee  I'm having issues with Google webfonts in IE11 as well - I'm just testing with [RemoteIE](https://developer.microsoft.com/en-us/microsoft-edge/tools/remote/). The JSBin above doesn't work for me either.

**Comment by garretrieger** [comment]
Tried on the latest IE 11 (version 11.589.10586, update 11.0.35 (KB3185319)) in Win 10.  Fonts are loading correctly for me.

**Comment by m4rc1e** [comment]
Closing, LGTM.

Win10 IE11:

![screen shot 2017-06-15 at 11 59 57](https://user-images.githubusercontent.com/7525512/27178469-353decb2-51c2-11e7-9412-d217f94cabc6.png)
https://jsbin.com/luhete/2/edit?html,output
