### ISSUE TITLE
Jdotless vs dotlessj

### ISSUE THREAD

**Issue by Fonthausen** [google/fonts#306]
I found a dotlessj in the Plus and Pro encoding. This should be jdotless, which works better with Glyphs.

**Comment by alexeiva** [comment]
Well spotted, @Fonthausen ! 
I am also applying @kalapi's suggestions to this batch of fixes:

> * Should we add 0x02BC (apostrophemod) to the Plus set since it's used in 'napostrophe'. We have > included it the Pro set.
> * Not all fonts require '.case' alternates of the below marks (dotbelowcomb.case, > dieresisbelowcomb.case, commaaccentcomb.case, cedillacomb.case, ogonekcomb.case, > brevebelowcomb.case, macronbelowcomb.case). Maybe we make them optional but keep them in the > Plus set and make a note somwhere of it.
> * Similarly not all fonts require 'zero.zero' (slashed zero). While this may be obvious I think we should document it somewhere (maybe in the Wiki feature on GitHub?).

**Comment by Fonthausen** [comment]
I found you are using euro and Euro. The first one should not be in it.

**Comment by alexeiva** [comment]
I added **commaturnedabovecomb** as per @Fonthausen's request.
From GlyphsData, no info on *commaaccentcomb.alt*

Also, Gcommaaccent does no auto combining. Maybe it is a precomposed character?
```
-------> cat GlyphData.xml | grep Gcommaaccent
	<glyph unicode="0122" name="Gcommaaccent" category="Letter" subCategory="Uppercase" script="latin" altNames="Gcedilla" description="LATIN CAPITAL LETTER G WITH CEDILLA" />
-------> cat GlyphData.xml | grep commaturnedabovecomb
	<glyph unicode="0312" name="commaturnedabovecomb" category="Mark" subCategory="Nonspacing" production="uni0312" altNames="commaturnedabovecmb" description="COMBINING TURNED COMMA ABOVE" />
-------> cat GlyphData.xml | grep commaaccentcomb.alt
-------> cat GlyphData.xml | grep commaaccentcomb
	<glyph unicode="0326" name="commaaccentcomb" category="Mark" subCategory="Nonspacing" production="uni0326" altNames="commaaccent" description="COMBINING COMMA BELOW" />
```

**Comment by alexeiva** [comment]
Update: In Glyphs 'Gcommaaccent' decomposes to 'commaaccentcomb', not 'commaturnedabovecomb'

<img width="538" alt="screen shot 2016-07-05 at 11 31 53" src="https://cloud.githubusercontent.com/assets/16634089/16590115/22d2a94c-42a4-11e6-8ebf-d751a32ee9af.png"> 

Image: LibreFranklin

**Comment by alexeiva** [comment]
I did a decomposing test on our Expert encoding in LibreFranklin. 
<img width="758" alt="screen shot 2016-07-05 at 11 42 16" src="https://cloud.githubusercontent.com/assets/16634089/16590493/cb891994-42a5-11e6-8114-90e7335471c3.png">

* commaaccentcomb.alt  
Still not sure about it's use. I suggest removing it. 

@kalapi any thought on this?

* ʻ commaturnedmod U+02BB MODIFIER LETTER TURNED COMMA. Used in Hawai'ian orthography as `okina (glottal stop). We keep this for Hawaian support.

**Comment by Fonthausen** [comment]
When I was checking the vietnamese, I noticed there is no Uhookabove and uhookabove. When looking at www.vietnamesetypography.com they should be in it.

**Comment by alexeiva** [comment]
You are right, @Fonthausen, these glyphs will be added to Latin Plus to support Vietnamese:
```
Uhookabove, uhookabove, strokeshortcomb, brevecomb_acutecomb, brevecomb_gravecomb, brevecomb_hookabovecomb, brevecomb_tildecomb, circumflexcomb_acutecomb, circumflexcomb_gravecomb, circumflexcomb_hookabovecomb, circumflexcomb_tildecomb
```
<img width="918" alt="screen shot 2016-07-05 at 18 42 29" src="https://cloud.githubusercontent.com/assets/16634089/16602222/5992d8ee-42e0-11e6-9bdd-367406e44f6a.png">

**Comment by alexeiva** [comment]
I have added the missing Vietnamese characters.
