### ISSUE TITLE
Usage count in fonts.google.com goes up and down 

### ISSUE THREAD

**Issue by santhoshtr** [google/fonts#307]
I was checking the usage count for the fonts and observed that some days, the count is less than the previous days. If it is cumulative request statistics, I expect it always increase and never decrease.

To be specific, I observed this in the case of [Meera Tamil font](https://fonts.google.com/specimen/Meera+Inimai?subset=tamil)

**Comment by davelab6** [comment]
Which count specifically are you referring to?

**Comment by santhoshtr** [comment]
"Number of times Google Fonts API served ". For Meera Tamil now I see 13.9K, but I saw 14.1 yesterday. Now that I read the description again, It is cumulative per week. I think that explains the up and down. Nevermind.
