### ISSUE TITLE
Add Allura Script

### ISSUE THREAD

**Issue by davelab6** [google/fonts#3076]
Part of Batch 5 of TypeSetIT fonts. Assigning to @vv-monsalve, cc @RosaWagner

**Comment by vv-monsalve** [comment]
Would this be different from #3002 ?

**Comment by vv-monsalve** [comment]
Already included as part of [Allura project](https://github.com/googlefonts/allura/)
Repo [https://github.com/googlefonts/allura/](https://github.com/googlefonts/allura/)
