### ISSUE TITLE
Ligature bug in Cantora One

### ISSUE THREAD

**Issue by davelab6** [google/fonts#3089]
`ffu` (eg `diffusion`) becomes `ffh`

<img width="208" alt="image003" src="https://user-images.githubusercontent.com/261579/107670639-ee8fe500-6c60-11eb-9101-f626878e85a1.png">
x
https://fonts.google.com/specimen/Cantora+One?preview.text_type=custom&preview.text=Diffusion

**Comment by RosaWagner** [comment]
It is quite easy to hotfix that problem, although while doing it I noticed the font name is actually camel case, creating an inconsistency with METADATA.pb. We can't correct that, right?

cc @davelab6 @chrissimpkins

**Comment by chrissimpkins** [comment]
> It is quite easy to hotfix that problem

Does this mean that you intend to fix directly in the binaries?  If so, do we not have sources to address it there?

**Comment by chrissimpkins** [comment]
> I noticed the font name is actually camel case, creating an inconsistency with METADATA.pb. 

Will you please add more information?  I don't follow where the inconsistency lies across the font name (path?) and the [metadata](https://github.com/google/fonts/blob/main/ofl/cantoraone/METADATA.pb).

**Comment by RosaWagner** [comment]
Sorry @chrissimpkins I was sure I answered this.
Yes we would hotfix the binaries directly to avoid opening the pandora box with the sources
The problem with the name is that the font is named "CantoraOne" (name ID 1), but METADATA.pb displays "Cantora One". In order to not create regression we would need to keep this inconsistency, but it may block the push.

**Comment by chrissimpkins** [comment]
> Yes we would hotfix the binaries directly to avoid opening the pandora box with the sources

Let's discuss this further.  Binary hotfixes to avoid the source Pandora's box means that it becomes even more desirable to avoid source edits on future updates.

**Comment by chrissimpkins** [comment]
> The problem with the name is that the font is named "CantoraOne" (name ID 1), but METADATA.pb displays "Cantora One". In order to not create regression we would need to keep this inconsistency, but it may block the push.

Agree with you that we should not change the production web API family name at this stage, even if it is not correct according to the one with space between "Cantora" and "One" removed as specified in the font name tables.  How does it block the push?  This is metadata and font name table configuration used with previous pushes, correct?

**Comment by RosaWagner** [comment]
> How does it block the push? This is metadata and font name table configuration used with previous pushes, correct?

The eng-team should be able to answer that answer

**Comment by RosaWagner** [comment]
﻿This is an old font with no repository (if there is one, it must be a mess). So basically any fix on the source would be like opening the pandora box and would be really hard to export with the current workflow. Without specific time to spend to upgrade deeply the font, better to just hotfix the font file (one line in the GSUB).

But just this action already started to show problems, sine the name ID1 is CantoraOne and metadata.pb reports Cantora One. I don’t think we can fix that without reflow.
