### ISSUE TITLE
Fix "Multiple Designers" 

### ISSUE THREAD

**Issue by RosaWagner** [google/fonts#3103]
These are the fonts where we need to add the actual designers in METADATA.pb.
I suggest to separate it between @vv-monsalve, @yanone and me, and we take care of it when possible.

Shall we give one issue per font ?

Roro
AmaticaSC (deprecated)
- [x] Amita (#3206)
- [x] ArimaMadurai (#3207)
- [x] Arya (#3208)
Bhavuka (unreleased)
- [x] Chathura (#3209)
- [x] ConcertOne (#3253)
- [x] Convergence (#3227)
- [x] Ewert (#3228)
- [x] Galada (#3229)

Vivi
- [x] Homenaje (#3247)
- [x] Lekton (#3226)
- [x] MeieScript (#3239)
- [x] Oranienbaum (#3240)
- [x] Pattaya (#3241)
- [x] Pavanam (#3217)
- [x] PirataOne (#3242)
- [x] ProstoOne (#3243)
- [x] RalewayDots (#3244)
- [x] Raleway (#3245)
- [x] Revalia (#3246)

Yaya
- [x] Ruluko
- [x] SedgwickAveDisplay
- [x] SedgwickAve
Sniglet (Had proper designer credit, did nothing)
- [x] StalinistOne
StalinOne (Missing from live library, maybe duplicate of Stalinist One?)
- [x] TitilliumWeb
- [x] Underdog
- [x] Voces

**Comment by vv-monsalve** [comment]
> Shall we give one issue per font ?

I would say yes! particularly after our conversation about process and tasks yesterday.

On the other hand, I could take the Spanish speakers designers that could be there. E.g. Ruluko is one of them.

**Comment by RosaWagner** [comment]
Ok, I'll ask @davelab6 his batch script for issues.

Feel free to rearrange the list :)
With a little bit of luck, some font won't need to contact anyone cause the designer is already in the catalog.

I already see some potential conflict with Titlium for example, which has an open PR for ages.

**Comment by yanone** [comment]
One issue per onboarder

**Comment by RosaWagner** [comment]
It is the same case as the Baskervville of the students of the ANRT. Principal design could be, as said, the Institution (ISIA Urbino) and the description could give more info, something like « ... was initiated by the students of ISIA Urbino of the year 20.., (under the direction of Luciano Perondi?). » then, they can drop all the names in their GitHub repo.

**Comment by vv-monsalve** [comment]
Ok, in that case, we could standardise that as a protocol for scholar cases with really multiple designers like this: we should credit the institution, and any further details can be added in the description file.
It would keep it neutral and simple for further cases, and we would avoid overfilling both the project page and the catalogue with information that may not be used later.

**Comment by tiroj** [comment]
How many designers is ‘really multiple designers’? Is there a number?

**Comment by vv-monsalve** [comment]
> How many designers is ‘really multiple designers’? Is there a number?

We have thought of this for particular cases like scholar projects, where 17 different people can be part of it in a learning environment where it could also be hard to determine or measure the individual contributions.
There will always be the description file to provide individual names, as it is used now in that case, and of course the Authors and Contributors files to be more specific about crediting.
Apart from that, this would depend more on a case by case analysis and would also be conditioned by each project/business/foundry policies.

**Comment by yanone** [comment]
Sniglet had a proper designer credit. So I checked it off, but didn't change anything.

**Comment by RosaWagner** [comment]
Ok guys, I am happy to tell you that we are done with this (except if we find spelling errors in sandbox) :)
