### ISSUE TITLE
Add REM font

### ISSUE THREAD

**Issue by vv-monsalve** [google/fonts#3120]
Add REM font 
private repo https://github.com/octaviopardo/REM

***Onboarding Process:***
- [x] Contact author
- [x] QA-assessment / report
- [x] Build
- [x] Fontbakery QA
~~- [ ] Upstream work on fixes needed~~
- [x] Visual QA
- [x] Authors and Contributors info
- [x] Description info
- [x] Font Images
- [x] Catalog designer info up to date
- [x] PR to upstream
- [x] PR to GF

~~Detailed [To-Do List](https://github.com/octaviopardo/REM/issues/8) on repository~~

**Comment by chrissimpkins** [comment]
Needs feedback from type designer.  Viv identified outline issues.

**Comment by vv-monsalve** [comment]
Waiting for designer to review/merge last PR to upstream.
