### ISSUE TITLE
Add Freeman

### ISSUE THREAD

**Issue by vv-monsalve** [google/fonts#3121]
Repo: https://github.com/rfuenzalida/Freeman

***Onboarding Process:***
- [x] Contact author
- [x] QA-assessment / report
- [x] Build
- [x] Fontbakery QA
- [x] Regression QA (for font updates)
- [x] Visual QA

```
New goal for the project 2:
Publishing the new version under a new name 'Freeman'
```

***Onboarding Process Part 2***
- [x] Change the name in the source file
- [x] Ask the Rodrigo for a new description file
- [x] Create new information files: Authors, Contributors, Readme
- [x] Include CI GHA
- [x] Fontbakery QA
- [x] Visual QA
- [x] Proofing html
- [x] Font Images
- [x] PR to upstream
- [x] PR to GF

**Comment by vv-monsalve** [comment]
The available version from the latest source files was [considerably different](https://github.com/rfuenzalida/FrancoisOne-Font/issues/3) from the [published one](https://fonts.google.com/specimen/Francois+One?query=franco). 

In a meeting, @davelab6 said it could be turned into a VF with an optical axis. However, after DB revision to the new VF, he said it wouldn't be an actual opsz. The process was stopped there waiting to be decided how (if) to publish the new version.

**Comment by davelab6** [comment]
Ah yes right. In this case, let's publish the project under a new name,
Freeman.

**Comment by vv-monsalve** [comment]
The designer will work on reinstating the Summer of Type work + African support.

**Comment by vv-monsalve** [comment]
This update will start on Q4

**Comment by vv-monsalve** [comment]
The designer is working on SSA Support.

**Comment by davelab6** [comment]
@chrissimpkins as a SSA project I've moved this to Q1 :)

**Comment by vv-monsalve** [comment]
Under the final SSA Latin definitions, the font needs some added glyphs.

**Comment by chrissimpkins** [comment]
Moving to backlog. Thanks Viv
