### ISSUE TITLE
Add Bona Nova

### ISSUE THREAD

**Issue by RosaWagner** [google/fonts#3123]
Upstream: https://github.com/kosmynkab/Bona-Nova

- [x] Contacted designer
- [x] Mastering / QA
- [x] Add Fontbakery CI
- [x] Repo structure
- [x] Build system
- [x] Package

**Comment by l-d-s** [comment]
Looks like the upstream repo disappeared.

**Comment by RosaWagner** [comment]
Because it is still a private repo.
