### ISSUE TITLE
Add Georgian script to Google fonts

### ISSUE THREAD

**Issue by mishotek** [google/fonts#3133]
Google fonts have helped the developer community for years. Fonts include many scripts, like Greek, Thai, but unfortunately, there is no single font for Georgian.
Google already has many fonts in Georgian like [noto](https://www.google.com/get/noto/#sans-geor), so there is no need to create or license new fonts. Is it possible to add them on google fonts? This would really help the Georgian web development community.

Why is it important:
* It would help about 6 million people to use the web
* It would preserve the language, inscribed on the UNESCO Representative List of the Intangible Cultural Heritage of Humanity

**Comment by AndroLom** [comment]
It is really critical to have us such a great possibility

**Comment by simoncozens** [comment]
Noto Sans Georgian has been added to Google Fonts!

**Comment by mishotek** [comment]
Great news, thanks.
