### ISSUE TITLE
Add Radio Canada: step 1 reduced glyphset

### ISSUE THREAD

**Issue by eliheuer** [google/fonts#3141]
Upstream: private

- [x] QA upstream
- [x] Sent to do list
- [x] Make build system
- [x] Package

**Comment by eliheuer** [comment]
I don't have the access permissions to add this to my projects board, but it should be here in the projects view: https://github.com/google/fonts/projects/9

**Comment by davelab6** [comment]
@eliheuer please update this issue :)
