### ISSUE TITLE
Add HEXP axis

### ISSUE THREAD

**Issue by RosaWagner** [google/fonts#3156]
I would see something kind of following the width spec, value is a percentage of the normal width. Fallback positions can be appended with Ultra, Extra, Semi to widen the ranges in the future.

```
tag: "SPAC"
display_name: "Spacing"
min_value: 50
max_value: 200
default_value: 100
precision: -1

fallback {
  name: "Tight"
  value: 50
}
fallback {
  name: "Normal"
  value: 100
}
fallback {
  name: "Loose"
  value: 150
}

description:
  "Adjust the spacing from tighter to looser, by varying the proportions of sidebearings and kerning."

```

**Comment by RosaWagner** [comment]
In fact it won't be a SPAC axis, but a HEXP.
No idea for the fallback names, if we follow the Lexend scheme or not.

```
tag: "HEXP"
display_name: "Hyper Expansion"
min_value: 0
max_value: 100
default_value: 0
precision: -1

fallback {
  name: "Normal"
  value: 0

fallback {
  name: "Hyper Expanded"
  value: 100
}

description:
  "Expansion of inner and outer space of glyphs."

```

**Comment by davelab6** [comment]
In this case the 7 steps for Lexend will be a family specific override, which will be 

1. 0
2. 16.66
3. 33.33
4. 50
5. 66.66
6. 83.33
7. 100

We'll need to discuss this with Evan and the team at the... opportune moment.

![tumblr_pfurm6O4bn1qauc46o2_540](https://user-images.githubusercontent.com/261579/121458157-e168d580-c976-11eb-81b2-c76329bf8c25.gif)

**Comment by vv-monsalve** [comment]
This issue was transferred to https://github.com/googlefonts/axisregistry/issues/11. Please follow up there.
