### ISSUE TITLE
Noto Sans JP - Accents marks moves to the right in Uppercase

### ISSUE THREAD

**Issue by ddb-jespindola** [google/fonts#3164]
I was using the font in a web project, but when I use the Á, Ó or Ú character, the accent mark moves to the next character. I'd love you can check this issue. THANKS !!

**Comment by simoncozens** [comment]
I think this issue is now fixed; please let me know if not!

<img width="319" alt="Screenshot 2022-05-12 at 12 08 03" src="https://user-images.githubusercontent.com/106728/168058172-8a2bdd17-78b8-4346-8b73-ac6e38d401c9.png">
