### ISSUE TITLE
[2016 Encodings] Some problems on glyphs names

### ISSUE THREAD

**Issue by impallari** [google/fonts#317]
A few glyphs names are problematic, see attached screenshot
![screen shot 2016-07-07 at 12 59 36](https://cloud.githubusercontent.com/assets/3036973/16659979/dc82fa96-4442-11e6-8e3f-803d1572099e.png)

**Comment by alexeiva** [comment]
Thanks, @impallari ,

This has been fixed already. Please redownload the new [list filters](https://github.com/google/fonts/tree/master/tools/encodings/GF%202016%20Glyph%20Sets/FilterLists)
