### ISSUE TITLE
Add Inter Italic

### ISSUE THREAD

**Issue by RosaWagner** [google/fonts#3170]
https://twitter.com/rsms/status/1303372355184386054

**Comment by arrowtype** [comment]
Duplicate of https://github.com/google/fonts/issues/3104

**Comment by arrowtype** [comment]
@RosaWagner I assume this issue should be closed, and issue 3104 should be assigned to Marc. I’m not sure, though, so I will let you handle this.

**Comment by RosaWagner** [comment]
@arrowtype yes you are right, thanks
