### ISSUE TITLE
inconsolata unsharp with freetype2 version 2.6.4-2

### ISSUE THREAD

**Issue by shibumi** [google/fonts#318]
Hello,
I run inconsolata: 20151221.480630d-1 with freetype2 2.6.4-2 on Arch Linux. 
After upgrading to freetype2 version 2.6.4-2 the inconsolata font changed completly in my rxvt-unicode:

Checkout these two screenshots:
[before freetype2 2.6.4.-2](https://paste.archlinux.de/S4BFC/)
[After freetype2 2.6.4.-2](https://paste.archlinux.de/UuU/)

**Comment by fitojb** [comment]
IMHO this should be filed at Freetype’s bug tracker. As a user, this is not the only font that has gone fuzzy after updating.

**Comment by davelab6** [comment]
I agree

**Comment by davelab6** [comment]
cc @lemzwerg

**Comment by lemzwerg** [comment]
Try FreeType 2.6.5.

What you see is the new v40 bytecode engine that essentially disables horizontal hinting, similar to Adobe's CFF engine in FreeType.  It was prematurely activated in 2.6.4 and disabled again in 2.6.5 for consistency.

Note that the forthcoming version 2.7.0 will have v40 mode active by default.  It will, however, also provide an environment variable to easily override FreeType's default engine settings.  So if you prefer v35 (i.e., non-ClearType) as shown in your 'before' snapshot, you can get this without the need to recompile FreeType.
