### ISSUE TITLE
Crimson Text 600 close quote

### ISSUE THREAD

**Issue by roboticarm** [google/fonts#320]
Noticed that the close quote in the 600 weight displays single quote instead. This is only in 600 weight regular and displays correctly in all other styles.  

Here is close quote displaying in all styles on the google fonts website: https://cl.ly/3P0r263K1A2I

**Comment by davelab6** [comment]
@roboticarm thanks for reporting!

**Comment by roboticarm** [comment]
Any update on this?

**Comment by laerm0** [comment]
This appears to still be an issue; in fact, I don't even see a single quote anymore.

![screen region 2017-09-06 at 15 28 44](https://user-images.githubusercontent.com/10780161/30130720-2392bf64-9318-11e7-98a4-c3d2bc7ba0ba.png)
