### ISSUE TITLE
Mulish Dollar Sign glyph issue on some macOS builds

### ISSUE THREAD

**Issue by krummmholz** [google/fonts#3204]
![image](https://user-images.githubusercontent.com/42036724/111175143-7f1e5580-857e-11eb-93ac-54976e285a74.png)

Definitely observed:
macOS Catalina 10.15.1
Safari Version 13.0.3 (15608.3.10.1.4)

Reportedly observed:
macOS High Sierra 10.13.6
Crome, FF, Safari (version not provided in defect report)

**Comment by jgarcialively** [comment]
This issue is causing us to look at pulling this font from our website

**Comment by emmamarichal** [comment]
The dollar sign has been modified in the last release. 
Mulish: Version 3.603 added #3762

<img width="335" alt="Capture d’écran 2022-03-25 à 15 04 09" src="https://user-images.githubusercontent.com/64773544/160135900-3bf158d1-bad4-4780-a667-2617be68ac63.png">
