### ISSUE TITLE
Please update Recursive to Version 1.077 or greater

### ISSUE THREAD

**Issue by arrowtype** [google/fonts#3205]
The version of Recursive currently hosted on Google Fonts is [`1.047`](https://github.com/arrowtype/recursive/releases/tag/1.047), from April 4, 2020. Since then, many issues have been corrected in the project, and it would be very worthwhile to update what we send users on the web and in downloads.

Most urgently, Google Fonts is currently serving fonts with the following issues which have since been solved upstream:
- Nested components, which [break in many printers](https://github.com/arrowtype/recursive/issues/412)
- [Inconsistent line heights on Mac](https://github.com/arrowtype/recursive/issues/308) in some of the Linear styles

...along with about 70 other issues closed since April 4, 2020.

So, I’m hoping that Google Fonts can update to the [latest version](https://github.com/arrowtype/recursive/releases/latest).

Thanks!

---

Notes:
- As of today (March 15, 2021) [FontBakery reports two false warns for GDEF mark glyphs](https://github.com/arrowtype/recursive/issues/451), which shouldn’t block the upgrade.
- Ideally, this upgrade would include Italic static fonts in the font download, which are currently missing. See https://github.com/google/fonts/issues/3104

**Comment by RosaWagner** [comment]
Does the` inconsistent lineheight on Mac` fix creates v-metrics regression with version 1.047 ?

**Comment by arrowtype** [comment]
Yes – inconsistent line metrics on Mac were fixed around version 1.074, and then a few more improvements have been made since then.

**Comment by RosaWagner** [comment]
by the way @arrowtype I got confirmation we can keep the fvar instances and tutti quanti and ship it like that. I'll do a PR next week probably.

**Comment by arrowtype** [comment]
Awesome, thanks for the update, @RosaWagner! That's good to hear. I did just improve the behavior of the backtick (legacy grave) in release v1.078, so hopefully we can use that version. It's still in the same googlefonts folder, so that might happen automatically.
