### ISSUE TITLE
Lowercase Bulgarian Cyrillic letter /л (uni043B.loclBGR or el-cy.loclBGR) in Piazzolla font family is incorrect

### ISSUE THREAD

**Issue by StefanPeev** [google/fonts#3213]
Bulgarian lowecase letter **/л** (uni043B.loclBGR) in Piazzolla_10pt-Regular.ttf downloaded from Google Fonts. See the PNG file.

![uni043B loclBGR_Piazzolla-Regular](https://user-images.githubusercontent.com/12949369/110663365-03fc1e80-81cf-11eb-9b89-0bb12958e1a6.jpg)

Acturally it is not the Bulgarian Cyrillic /л, it is the Greek DELTA. Please, correct this. This is a mistake...
The Glyphs source of **el-cy.loclBGR** (uni043B.loclBGR) is absolutely different.

**Comment by juandelperal** [comment]
Thanks @StefanPeev 
As we discussed on https://github.com/huertatipografica/piazzolla/issues/20 this is already fixed
