### ISSUE TITLE
Add StixTwo Fonts

### ISSUE THREAD

**Issue by vv-monsalve** [google/fonts#3218]
***Onboarding Process:***
- [x] QA-assessment (FB, diffenator, images) / report
- [x] Fontbakery QA
- [x] Authors and Contributors info
- [x] Description info
- [x] Font Images
- [x] Catalog designer info up to date
- [x] PR to upstream
- [x] PR to GF, Text #3256; Math #3304 

repo: https://github.com/stipub/stixfonts

**Comment by tiroj** [comment]
stixfonts_dev is a private development repo. The latest versions of the fonts will be pushed to the public repo https://github.com/stipub/stixfonts shortly. I will post a notification when that happens.

**Comment by davelab6** [comment]
@tiroj has this happened now?

**Comment by tiroj** [comment]
Yes. Sorry I forgot to add note here, but @vv-monsalve is on it already.

Current version is 2.12, now live on [public repo](https://github.com/stipub/stixfonts).

v2.20 planning now in progress.
