### ISSUE TITLE
[REQUEST] Add all Google Noto fonts

### ISSUE THREAD

**Issue by marchellodev** [google/fonts#3233]
Hey, is it possible to add [Google Noto fonts ](https://www.google.com/get/noto) to this repo as well?

Some of them, for example [Noto Sans Sinhala](https://www.google.com/get/noto/#sans-sinh), are not available on Google Fonts

**Comment by davelab6** [comment]
Per https://github.com/google/fonts/pull/2823 we are working on this :) I'll close this for now, but stay tuned, you'll be happy I think

You might find the Fonts you want already in the API if you try them btw
