### ISSUE TITLE
Some braille characters in wrong order?

### ISSUE THREAD

**Issue by sshbio** [google/fonts#325]
I used to see braille characters that were displayed correctly in my laptop and not in my android phone, with the default font.

It is being this one: `⠠`, with vim: `<⠠> 10272, Hex 2820, Octal 24040`.

It is displayed like this with my laptop:

```
 _____
|__|__|
|__|__|
|__|XX|
|__|__|
```

And like this in my Nexus 4 with Cyanogenmod 13.0-20160606-NIGHTLY-mako.

```
 _____
|__|__|
|__|__|
|XX|__|
|__|__|
```

I noticed it while using http://github.com/asciimoo/drawille which can be useful to debug the braille characters.

**Comment by davelab6** [comment]
@sshbio this issue tracker is for the fonts in fonts.google.com, and we can't help resolve that issue. I suggest that if you can reproduce this on another Android devices (such as Nexus 5 or 6 not running Cyanogenmod) then perhaps report it to Android following https://source.android.com/source/report-bugs.html and/or to Cyanogenmod :)

**Comment by sshbio** [comment]
Sorry for my confusion, and thank you for pointing me out the right place. Have a nice day!
