### ISSUE TITLE
Add Azeret Mono Family

### ISSUE THREAD

**Issue by displaay** [google/fonts#3257]
Hi,
we just finished monospaced font family and we would like to offer it to the GF to add it the library. 

[GIT link](https://github.com/displaay/Azeret)

I have a question regarding engineering the font:
* The font is supposed to be monospaced, but few glyphs are double or triple width (exactly) is it a problem. If not how to set isFixedPitch? 

* During testing in fontbakery a lot of errors with naming came through. Mostly suggesting completely different naming scheme for mac name table entries to windows name entries. I'm used to keep them the same. Is it a problem?

* There are 16 + 17 NIDs even for R, I, B, BI is that a trouble?

Let us know any other issues and we try to fix it asap.
Cheers!

**Comment by davelab6** [comment]
Great work!
