### ISSUE TITLE
Spelling mistake in Kapakana + New Tegomin

### ISSUE THREAD

**Issue by RosaWagner** [google/fonts#3260]
Error in designer's name
Kyosuke Nagai (x) → Kousuke Nagai (o)

**Comment by m4rc1e** [comment]
We really need to write a custom fontbakery profile for ourselves that can check these designer profiles. We could then hook it up to the CI.

**Comment by m4rc1e** [comment]
Let's look into this in our meeting later.

**Comment by RosaWagner** [comment]
Yes I agree !
Although for this one, it's a new designer not yet registered in the catalog… so, we basically just wrote it wrong in the metadata.pb
