### ISSUE TITLE
my request

### ISSUE THREAD

**Issue by ayt-2013** [google/fonts#3269]
I work on fonts, I know calligraphy, capitalization, etc. in English, and I also know calligraphy, capitalization, etc. in Persian. Please make me a member of Google Fonts.

**Comment by davelab6** [comment]
@ayt-2013 thanks for reaching out, I love your enthusiasm. Sadly though, I can't add you as a member, until you make a significant and sustained contribution to the project. If you develop a Naskh font to the stage where it passes our requirements (https://github.com/google/fonts/blob/main/CONTRIBUTING.md) I'll be happy to include it :)
