### ISSUE TITLE
Add Libre Bodoni

### ISSUE THREAD

**Issue by impallari** [google/fonts#329]
**Production notes:**
- [x]  Repo S-structure
- [x] Build fonts
- [x]  Fontbakery
- [x]  Visual QA
- [x]  Build
- [x]  PR Upstream
- [ ]  Package

**Comment by impallari** [comment]
Handy link to the repo https://github.com/impallari/Libre-Bodoni :)

**Comment by impallari** [comment]
ping :)

**Comment by RosaWagner** [comment]
@emmamarichal this is the new repo so we can move forward on this projects: [googlefonts/Libre-Bodoni](https://github.com/googlefonts/Libre-Bodoni/)
