### ISSUE TITLE
Add Literata

### ISSUE THREAD

**Issue by rayshan** [google/fonts#33]
https://twitter.com/googleplay/status/600345181779566593

http://www.type-together.com/literata

Looks great :)

Thanks!

**Comment by davelab6** [comment]
It's not libre licensed.

**Comment by rayshan** [comment]
Aww :cry:

**Comment by davelab6** [comment]
It will be in the future, so keeping this open

**Comment by keithzg** [comment]
Any news on it becoming libre? (This github issue appears to be the only mention in public of such a possibility.)

**Comment by sergeevabc** [comment]
Where is Literata with Cyrillic support?

**Comment by inferno986return** [comment]
@sergeevabc Standard Literata has Cyrillic support apparently. https://www.google.co.uk/amp/www.androidauthority.com/literata-font-download-play-books-609371/amp/

**Comment by sergeevabc** [comment]
@inferno986return, indeed, but where to download the latest files while current repository lacks them?

**Comment by laerm0** [comment]
Literata is no longer available from TypeTogether so I'm thinking this can be closed... I'll leave it open for a bit in case any of you has more info on the font.

**Comment by davelab6** [comment]
I expect to be able to ofl this in the future so let's keep this open

**Comment by Ivoz** [comment]
Do you know what exactly has happened to it / is happened with it @davelab6 ? Hard to find any (up to date) 1st-party source info on it nowadays.

**Comment by davelab6** [comment]
It's not yet available for 3rd parties

**Comment by inferno986return** [comment]
I suppose it's red tape.

 It's a nice typeface, certainly better than Spectral as it's clean, readable and has an interesting approach to italic design. I could see myself making use of it both inside and outside of Google Docs. :-)

Keep up your attempts to bring it to Google Fonts. Sure it is a part of the Google Books branding, but it's not as tied to branding as Product Sans is.

Besides Roboto doesn't have an official serif typeface counterpart like Droid Serif. AFAIK

**Comment by keithzg** [comment]
> Besides Roboto doesn't have an official serif typeface counterpart like Droid Serif. AFAIK

That part is not quite true: https://fonts.google.com/specimen/Roboto+Slab

**Comment by inferno986return** [comment]
I was referring more to a transitional/old-style serif counterpart rather than a slab. Roboto Slab while groundbreaking in its inception is problematic, it has no oblique styles and also doesn't currently adhere to the updated glyphs that came out in 2014.

I have asked about it though, in a separate issue: https://github.com/google/fonts/issues/1256

**Comment by inferno986return** [comment]
Good news everyone. The official Google Fonts GitHub profile has made an empty repository for Literata, calling it a _"A contemporary serif typeface family for long-form reading"_.

https://github.com/googlefonts/literata

**Comment by davelab6** [comment]
Soon, soon! :)

**Comment by taciturasa** [comment]
its been about a half a year almost. any word?

**Comment by gingerbeardman** [comment]
I ended up downloading it from elsewhere. ¯\_(ツ)_/¯

**Comment by J0s3f** [comment]
Since the font is released as open source now (https://github.com/googlefonts/literata) it would be great if you could add it.

**Comment by inferno986return** [comment]
Indeed, it would be great if Literata was part of Google Fonts and selectable on Google Docs (and Sheets/Slides). 

As an addendum, I really that the sketches and design briefs were publicised. It's really interesting reading! :smile:

**Comment by davelab6** [comment]
We will add it soon.

**Comment by mbartelsm** [comment]
How is progress on this issue?

**Comment by inferno986return** [comment]
I too would like to know approximately when Literata will be added to Google Fonts and maybe Google Docs/Sheets/Slides too.

**Comment by sjbr** [comment]
When will Literata be added to google fonts?
Thanks

**Comment by fitojb** [comment]
https://fonts.google.com/specimen/Literata

**Comment by gingerbeardman** [comment]
Hoorah!

**Comment by m4rc1e** [comment]
Added in #2021
