### ISSUE TITLE
3rd Party Directory not available: The Anatomy Of a Thousand Typefaces

### ISSUE THREAD

**Issue by theDavidBarton** [google/fonts#3307]
In [TRIVIA.md](https://github.com/google/fonts/blob/main/TRIVIA.md) there is link to:
- https://getflourish.github.io/anatomy-of-typefaces 

...which doesn't exist anymore in its original place (HTTP 404).   
Consider replacing it with this page with the same content (written by [@getflourish](https://github.com/getflourish)): 
- https://useratio.com/the-anatomy-of-a-thousand-typefaces

**Comment by adithyaakrishna** [comment]
Can I Work on This?

**Comment by m4rc1e** [comment]
Thanks both of you. Please feel free to open more.
