### ISSUE TITLE
Hint Radley (was, 'st' ligature broken)

### ISSUE THREAD

**Issue by dotKev** [google/fonts#332]
Trying to use Radley Normal Italic for "Posted by" byline and seeing "Poed".

I verified that it is specifically an issue with the font by testing it on [Typecast](http://typecast.com/preview/google/Radley).

**This text should show "Posted First":**

<img width="570" alt="screen shot 2016-07-21 at 9 57 34 pm" src="https://cloud.githubusercontent.com/assets/1915812/17045343/3aa2e9c8-4f8e-11e6-83e6-34b82fb216db.PNG">

A quick fix in lieu of fixing the glyph is to [disable ligatures](https://css-tricks.com/almanac/properties/f/font-feature-settings/) for the italic version of the font.

```
-webkit-font-feature-settings: "liga" 0;
-moz-font-feature-settings: "liga" 0;
font-feature-settings: "liga" 0;
```

**Comment by m4rc1e** [comment]
Hey,

I can confirm this.

![screen shot 2016-09-02 at 12 02 09](https://cloud.githubusercontent.com/assets/7525512/18200443/2932ea7e-7105-11e6-8e5a-8dd5919aa8f8.png)

Also happens in the Roman as well.

![screen shot 2016-09-02 at 12 03 34](https://cloud.githubusercontent.com/assets/7525512/18200474/4ce6d8e0-7105-11e6-84cf-a8158dab1a0e.png)

@davelab6 any plans to turn this project into an extension/raisin. It is quite a nice font.

Cheers,
Marc

**Comment by Atcold** [comment]
Any fix for this? I'm using Google Doc and *robust* just became *robu*... What the heck...

**Comment by davelab6** [comment]
@Atcold I agree this is a high priority to fix. Soon!

**Comment by ksykes** [comment]
Any idea on a fix for this? I'm still having this issue.

**Comment by davelab6** [comment]
@m4rc1e perhaps cut the OT feature as a hotfix? this is urgent

**Comment by m4rc1e** [comment]
This should be sorted in the pr I just filed. I've forked Vernon's repo to GF, https://github.com/googlefonts/RadleyFont

**Comment by davelab6** [comment]
Keeping this open while https://github.com/googlefonts/RadleyFont/issues/2 is resolved

**Comment by davelab6** [comment]
Fix for the st ligature should be out very soon

**Comment by laerm0** [comment]
PR for hinting submitted

**Comment by davelab6** [comment]
<img width="370" alt="screen shot 2017-08-07 at 13 07 37" src="https://user-images.githubusercontent.com/261579/29037375-67f8c496-7b71-11e7-9d33-d87ba5c84b90.png">

**Comment by Atcold** [comment]
@davelab6, is it *robust*? I mean, can you post the word "robust"?

**Comment by fitojb** [comment]
@Atcold Yes, that is fixed

**Comment by Atcold** [comment]
Yeah, I got it, @fitojb. I was being silly/pedantic and asking for a visual confirmation 😉

**Comment by davelab6** [comment]
@Atcold lol :)

**Comment by laerm0** [comment]
Are we cool to close this now?

**Comment by chudgar** [comment]
Roman ligatures appear to be fixed, but italic — ! 
Behold "listening," "straight," "listen," "strategic." 

<img width="105" alt="screen shot 2017-10-23 at 9 24 36 am" src="https://user-images.githubusercontent.com/6122948/31894434-0e58371a-b7d4-11e7-8bc7-21f90634a9e4.png">  <img width="152" alt="screen shot 2017-10-23 at 9 24 16 am" src="https://user-images.githubusercontent.com/6122948/31894438-10a9b232-b7d4-11e7-8eca-287037666935.png">

**Comment by fitojb** [comment]
@chudgar Are you sure it’s not a caching issue? Also, check that you don’t have the previous version installed locally, as that may conflict with browser display.

**Comment by chudgar** [comment]
THANK YOU. Thank you, thank you, thank you. I _did_ have the previous version installed locally: deleted, installed the new TTFs, and LOOK:

<img width="472" alt="screen shot 2017-10-24 at 1 08 17 pm" src="https://user-images.githubusercontent.com/6122948/31960147-6cca1ad2-b8bc-11e7-984c-2ba75bc5883c.png">

**Comment by davelab6** [comment]
It's a common issue. Thanks for letting us know you are sorted :)
