### ISSUE TITLE
Update Rubik to fix bug in NAME table and improve hinting

### ISSUE THREAD

**Issue by davelab6** [google/fonts#333]
- [x] Rubik italic files have NAME tables incorrectly configured, preventing them from being installed locally
- [x] Rubik has been updated by the designer with new hinting, paid for by a keen user, so pushing this update is a high priority.

**Comment by m4rc1e** [comment]
@davelab6 I see @alexeiva  and the Cyrillic team may be touching these files soonish. Perhaps they could look into this or I could fix it if we need a repo prep?

Is the hinting vtt?

Cheers,
Marc

**Comment by alexeiva** [comment]
@m4rc1e the hinting is VTT AFAIK. Yes, Rubik is currently in work. [repo](https://github.com/alexeiva/rubik). I will be generating new files from Glyphs, and will check the naming scheme.

**Comment by m4rc1e** [comment]
@alexeiva awesome,

VTT is very sensitive to point changes. If a path changes direction or the amount of nodes change, the hinting will be broken for that glyph. I briefly mentioned this [here](https://groups.google.com/d/msg/googlefonts-discuss/H5F6NUzaWFk/akc39Di6BwAJ)

I strongly recommend you drop VTT and rely on ttfautohint instead.

Cheers,
Marc

**Comment by alexeiva** [comment]
@m4rc1e thanks for the information. 
Our work is limited to improving Cyrillic, and generating new TTFs from Glyphs with ttfautohint. Similar to Meir's workflow of Rubik Hebrew, the Cyrillic source files are separate, and can possibly be re-hinted in VTT, and merged onto the the original hinted Latin sources. But this is a separate concern.

**Comment by alexeiva** [comment]
Here is the current naming scheme in Italic. 
@davelab6 @m4rc1e does it look right to you?


<img width="980" alt="screen shot 2016-09-09 at 15 26 08" src="https://cloud.githubusercontent.com/assets/16634089/18386828/f7d8faac-76a1-11e6-8ab6-fb45a5c4b01c.png">
<img width="980" alt="screen shot 2016-09-09 at 15 26 07" src="https://cloud.githubusercontent.com/assets/16634089/18386829/f7dc6b24-76a1-11e6-80b7-6c73d33b29c9.png">
<img width="980" alt="screen shot 2016-09-09 at 15 26 05" src="https://cloud.githubusercontent.com/assets/16634089/18386830/f7e0a1bc-76a1-11e6-942c-69fad1837605.png">
<img width="980" alt="screen shot 2016-09-09 at 15 26 04" src="https://cloud.githubusercontent.com/assets/16634089/18386831/f7e451a4-76a1-11e6-9750-da04679c95c7.png">
<img width="980" alt="screen shot 2016-09-09 at 15 26 03" src="https://cloud.githubusercontent.com/assets/16634089/18386832/f7e6fd00-76a1-11e6-8062-bf87189e169d.png">

**Comment by alexeiva** [comment]
The new v.2.000 files exported from Glyphs App pass fontbakery naming checks
<img width="780" alt="screen shot 2016-09-10 at 13 16 24" src="https://cloud.githubusercontent.com/assets/16634089/18409783/f8d43aea-7758-11e6-871a-6317bf26754f.png">

**Comment by alexeiva** [comment]
The new v.2.000 fonts install fine locally. 
Tested on OS X 10.11.6

Pages App:
<img width="271" alt="screen shot 2016-09-10 at 13 23 09" src="https://cloud.githubusercontent.com/assets/16634089/18409823/c6f85d3e-7759-11e6-88b8-e52ba6d34a22.png">

Font Book:
<img width="212" alt="screen shot 2016-09-10 at 13 21 31" src="https://cloud.githubusercontent.com/assets/16634089/18409825/ccfca79e-7759-11e6-9df9-763466c4c99f.png">

<img width="259" alt="screen shot 2016-09-10 at 13 21 23" src="https://cloud.githubusercontent.com/assets/16634089/18409829/d1e67d98-7759-11e6-93a9-93543dd58632.png">

<img width="735" alt="screen shot 2016-09-10 at 13 20 36" src="https://cloud.githubusercontent.com/assets/16634089/18409830/d781276c-7759-11e6-977d-e1235ed8d2c8.png">

**Comment by davelab6** [comment]
> @davelab6 @m4rc1e does it look right to you?

Yes

**Comment by davelab6** [comment]
> Similar to Meir's workflow of Rubik Hebrew, the Cyrillic source files are separate, and can possibly be re-hinted in VTT, and merged onto the the original hinted Latin sources. But this is a separate concern.

Yes; due to strong user demand, I expect to push the hand-hinted fonts first, with the old Cyrillic, then get the Cyrillic hand hinted, and then push that as a 2nd update

**Comment by alexeiva** [comment]
@davelab6 does rubikmonoone also have manual hinting?

**Comment by m4rc1e** [comment]
@davelab6 any news on these vtt fonts?

My previous pr for Rubik was for autohinted fonts.

**Comment by davelab6** [comment]
Hinted fonts are merged
