### ISSUE TITLE
Proposal: Have css and fonts served from the same domain

### ISSUE THREAD

**Issue by vijayaraghavanramanan** [google/fonts#335]
Right now, the css is served from the domain fonts.googleapis.com and fonts from fonts.gstatic.com. 

This causes delays because the browser has to do a dns lookup, connect and do TLS handshake etc. It's possible to avoid this by link rel=preconnect but not all browsers support this. 

The easiest way is to serve from the same domain such as from fonts.google.com. 

Possible?

**Comment by davelab6** [comment]
Thanks for the suggestion :) The 2 domains are used because fonts.googleapis.com serves CSS, which is dynamic - changing based on evaluating the user agent string - while fonts.gstatic.com serves fonts, which are static files.

**Comment by vijayaraghavanramanan** [comment]
Understand. However I don't see why they can't be served from the same domain.

**Comment by rsheeter** [comment]
Agreed less domains would be better. Changing this is awkward due to implementation details. For now we try to alleviate by sending a preconnect along with the CSS (for example `link:<https://fonts.gstatic.com>; rel=preconnect; crossorigin`).

**Comment by rsheeter** [comment]
Thanks for the feedback. We are tracking internally but I don't anticipate near-term action. Closing for now.
