### ISSUE TITLE
Update Catamaran

### ISSUE THREAD

**Issue by davelab6** [google/fonts#336]
Daniel at wiegand gmbh reported the German accents have issues that have been fixed by Pria

**Comment by davelab6** [comment]
@m4rc1e this is high priority cf. https://twitter.com/aparticula_com/status/824658938100613120

**Comment by m4rc1e** [comment]
Confirmed

German accents added in #716 are good 

... is still not good.

![screen shot 2017-06-15 at 12 05 16](https://user-images.githubusercontent.com/7525512/27178633-e9d11f3c-51c2-11e7-96ed-1b76c345f968.png)

http://jsbin.com/pacorijuce/edit?html,output

**Comment by laerm0** [comment]
This is now fixed so I am closing it.

![screen region 2017-10-03 at 13 03 07](https://user-images.githubusercontent.com/10780161/31138079-3ec37eda-a83b-11e7-8a57-17763c172238.png)
