### ISSUE TITLE
Add Aleo

### ISSUE THREAD

**Issue by KyleAMathews** [google/fonts#338]
Companion to very popular Lato

http://www.fontfabric.com/aleo-free-font/

**Comment by FedericoPonzi** [comment]
Any updates?

**Comment by davelab6** [comment]
Not yet.

**Comment by Jookus** [comment]
Any news? 
Our G Suite-Group would love to have this font for Google Docs as it is a part of our corporate design ... :smirk:

**Comment by kevinconroy** [comment]
I had the same request, so I reached out to the creator of Aleo and he's graciously agreed to release it under the necessary font license for Google Fonts. We are currently working through the submission process and hope to have it live soon. I'll update here once it's available.

https://github.com/AlessioLaiso/aleo

**Comment by estaub** [comment]
@kevinconroy (Sorry, but) any time estimate?

**Comment by kevinconroy** [comment]
The official pull request to add Aleo has been submitted: https://github.com/google/fonts/pull/1502

**Comment by kevinconroy** [comment]
With many thanks to @AlessioLaiso, Aleo is now available from Google Fonts: https://fonts.google.com/specimen/Aleo

**Comment by davelab6** [comment]
Thank you so much for all your help and patience seeing this through!

**Comment by AlessioLaiso** [comment]
Thank you guys for helping with this!
