### ISSUE TITLE
"ς" is invisible in Play font regular

### ISSUE THREAD

**Issue by matthi4s** [google/fonts#343]
The character `ς` ([sigma](https://en.wikipedia.org/wiki/Sigma)) is invisible in the regular style of the [Play](https://www.google.com/fonts/specimen/Play#charset) font, but it is visible in the bold style of the font. I've tested it in Google Chrome and Safari. 

This is a screenshot from the [character set](https://www.google.com/fonts/specimen/Play#charset).
![missing character](https://cloud.githubusercontent.com/assets/8943286/17340055/e5b80a28-58ee-11e6-9c79-1b4f9949f2cb.png)

And another screenshot from the [Google fonts website](https://fonts.google.com/specimen/Play) showing the difference between regular and bold.
![difference regular bold](https://cloud.githubusercontent.com/assets/8943286/17340058/e8907168-58ee-11e6-8081-085aeabad689.png)

Thanks a lot for your help!

Matthias

**Comment by m4rc1e** [comment]
Can confirm the issue.

V1.002 is fine. However, this issue happens in the latest V1.003.

![screen shot 2016-08-11 at 13 45 54](https://cloud.githubusercontent.com/assets/7525512/17587688/07d339ca-5fca-11e6-9563-b20b7a7a3fd1.png)

The glyph has no outlines however, it does exist, under a different name and without a unicode.

**Comment by thlinard** [comment]
Corrected by Play v2.000 (now on github, but still not on GF)

**Comment by m4rc1e** [comment]
@davelab6 @thlinard Thanks for the confirmation.

@davelab6 Before we push this to dev, I've just doubled checked the fonts with the new regression tools. There are a couple of issues that need resolving first. I've filed an [issue](https://github.com/alexeiva/play/issues/3) to the source repo.

cc @alexeiva

**Comment by m4rc1e** [comment]
Closing. [Play](https://fonts.google.com/specimen/Play) now has sigma glyph

![screen shot 2017-06-14 at 11 28 55](https://user-images.githubusercontent.com/7525512/27127937-aeaf9f2e-50f4-11e7-83b8-c792f48bc34b.png)
