### ISSUE TITLE
Add Blackout

### ISSUE THREAD

**Issue by davelab6** [google/fonts#3450]
https://www.theleagueofmoveabletype.com/blackout

upstream: https://github.com/theleagueof/blackout

**Production notes:**
- [x] Repo structure
- [ ]  Fontbakery
- [ ]  Visual QA
- [ ]  Build
- [ ]  PR Upstream

**Comment by emmamarichal** [comment]
There are 3 source files in .ufo and .vfb.
I opened one of them thanks to ufo2glyphs (the others were empty), here is the current glyphset, for one style:
 
<img width="189" alt="Capture d’écran 2021-12-10 à 17 06 27" src="https://user-images.githubusercontent.com/64773544/145605514-f5b9d503-1465-4424-9e88-9bfeae19b310.png">

<img width="1048" alt="Capture d’écran 2021-12-10 à 17 10 22" src="https://user-images.githubusercontent.com/64773544/145605523-ddf1c9e1-72ec-444c-8a7a-c97f9ba7461f.png">

**Comment by davelab6** [comment]
Ah, right. So, I'll close this issue, and keep in mind a commission to flesh out the glyph set in the future.
