### ISSUE TITLE
Adding credit in the Comic Neue entry

### ISSUE THREAD

**Issue by hpapazian** [google/fonts#3459]
The MicroFoundry (Hrant Papazian) was commission by Craig Rozynski to implement extensive improvements to the outlines, spacing, and kerning of all the fonts in the Comic Neue family, to originally prepare it for official release. Please add a credit to that effect in the About section here:
https://fonts.google.com/specimen/Comic+Neue#about

References:
http://comicneue.com
https://en.wikipedia.org/wiki/Comic_Neue

**Comment by RosaWagner** [comment]
Fixed with #3529

**Comment by hpapazian** [comment]
> Fixed with #3529

Sorry, is
https://fonts.google.com/specimen/Comic+Neue#about
supposed to reflected the crediting now? I can't see it...
