### ISSUE TITLE
f_f_ij and f_ij

### ISSUE THREAD

**Issue by alexeiva** [google/fonts#346]
Proposal to remove these ligatures from GF Latin Plus to the recommended list:
```
f_f_ij
f_ij
```	

Their use is only justified in case of a truly ligated `ij` in the font. Non of my `ij` diagraphs are ligated in the three fonts I worked on recently, adding them was redundant.

In other words `f_f_i` + `j` produces same results as the said `f_f_ij` ligature, rendering them unnecessary in the default use-cases.

<img width="356" alt="screen shot 2016-07-28 at 18 43 53" src="https://cloud.githubusercontent.com/assets/16634089/17232035/49794acc-54f3-11e6-8b53-99d8374a52e0.png">
_Top: `f_f_i` + `j` Bottom: `f_f_ij` ligature. Results are identical._

Only fonts with custom ligated `ij`'s, such as perhaps Pacifico may require these ligatures.

**Comment by davelab6** [comment]
@m4rc1e @graphicore @kalapi thoughts? :)
