### ISSUE TITLE
Neuton font displays non-breaking space much wider than a normal space

### ISSUE THREAD

**Issue by lukechilds** [google/fonts#347]
If you add have a mix of `&nbsp;` and normal space characters in your markup the content looks really bad. Many WYSIWYG editors will add `&nbsp;` in strange places and they can also end up in content when it's pasted in from other sources.

Demo https://jsfiddle.net/tg67akud/2/

**Comment by m4rc1e** [comment]
I have replicated the bug and fixed it.

1st line: nbsp
2nd line: space
![screen shot 2016-08-11 at 23 34 51](https://cloud.githubusercontent.com/assets/7525512/17605752/3e93f402-601c-11e6-9865-8678fbdeddd0.png)

This has been checked and implemented for each weight. 

Update will be rolled out soon.

Thank you for reporting this.

**Comment by lukechilds** [comment]
@m4rc1e Any idea when this update will be coming out? The jsfiddle I posted still has the issue.

**Comment by m4rc1e** [comment]
Hey @lukechilds,

My repository with the fix is [here](https://github.com/m4rc1e/Neuton). Count this as an unofficial release for the time being. 

We're in the process of upgrading popular fonts and fixing bugs at the moment.

Cheers,
Marc

**Comment by lukechilds** [comment]
Thanks 👍

**Comment by m4rc1e** [comment]
Closing, LGTM.

![screen shot 2017-06-14 at 12 24 20](https://user-images.githubusercontent.com/7525512/27130033-715a4590-50fc-11e7-8bc0-85ffa8801de3.png)

https://jsfiddle.net/tg67akud/2/
