### ISSUE TITLE
Add woff2 support for Safari 10

### ISSUE THREAD

**Issue by vijayaraghavanramanan** [google/fonts#349]
Safari 10 is already in beta and might soon release. It has woff2 support:

https://developer.apple.com/library/prerelease/content/releasenotes/General/WhatsNewInSafari/Articles/Safari_10_0.html

Not only that, it has fixed the unicode-range issue:

> Web fonts are downloaded only if the characters of the rendered text are within the font's Unicode range.

Is it possible to add support for it?

**Comment by rsheeter** [comment]
Awesome, we will look into delivering woff2 and unicode-range to Safari 10!! Thanks for the heads up and what a fantastic set of text features in 10 :) Happy to CSS Font Loading as well.

Can I offer you a Google Fonts t-shirt? - if so please send your mailing address and shirt size to rsheeter AT google.com.

**Comment by vijayaraghavanramanan** [comment]
Hi @rsheeter,

Sure. I will write to you.

**Comment by dffp** [comment]
Good

**Comment by vijayaraghavanramanan** [comment]
Since iOS 10 is out, is woff2 supported yet by Google Fonts?

**Comment by davelab6** [comment]
@vijayaraghavanramanan please could you email me to follow up on this? :)

**Comment by rsheeter** [comment]
Appologies, I forgot to update this. WOFF2 has been enabled for iOS + Safari 10 since October.

**Comment by vijayaraghavanramanan** [comment]
Hi @rsheeter 

But I don't see it. 

I've tried it on Browserstack with Safari 10 on Sierra and also on Chrome Canary by switching the user agent to 

`Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12) AppleWebKit/602.1.50 (KHTML, like Gecko) Version/10.0 Safari/602.1.50`

It's still downloading woff files. Can you check?

**Comment by vijayaraghavanramanan** [comment]
Here's a demo that woff is being downloaded, not woff2: 

Codepen [link](http://codepen.io/anon/pen/oYqaGM?editors=1111)

Screenshot: 

![codepen safari browserstack](https://cloud.githubusercontent.com/assets/13736892/20913850/3d2d3c1e-bba1-11e6-9e34-ddcfa52fa734.png)

**Comment by vijayaraghavanramanan** [comment]
Any update on this?

**Comment by rsheeter** [comment]
Thanks for the followup. It's enabled for iOS + Safari 10, not for macOS. For example:
```shell
curl -s -D - -H 'User-Agent: Mozilla/5.0 (iPhone; CPU iPhone OS 10_0 like Mac OS X) AppleWebKit/602.1.50 (KHTML, like Gecko) Version/10.0 Mobile/14A5345a Safari/602.1' 'https://fonts.googleapis.com/css?family=Lobster' | grep src:
  src: local('Lobster'), local('Lobster-Regular'), url(https://fonts.gstatic.com/s/lobster/v18/G6-OYdAAwU5fSlE7MlBvhQLUuEpTyoUstqEm5AMlJo4.woff2) format('woff2');
```

macOS coming soon.

**Comment by vijayaraghavanramanan** [comment]
Great. 

I am however seeing no unicode subsetting and the fonts are downloaded like it downloads for Edge. I think iOS 10 Safari both parses unicode-range and downloads only the needed fonts, so I'd imagine you could do it like for Chrome.

**Comment by vijayaraghavanramanan** [comment]
Since this is now implement (I assume), this thread can be closed, correct?

**Comment by davelab6** [comment]
Yes
```
$ curl -s -D - -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.75.14 (KHTML, like Gecko) Version/9.3.2 Safari/537.75.14' 'https://fonts.googleapis.com/css?family=Lobster' | grep src:
  src: local('Lobster'), local('Lobster-Regular'), url(https://fonts.gstatic.com/s/lobster/v18/NIaFDq6p6eLpSvtV2DTNDQLUuEpTyoUstqEm5AMlJo4.woff) format('woff');
$
```
