### ISSUE TITLE
Update Molengo

### ISSUE THREAD

**Issue by davelab6** [google/fonts#350]
@moyogo released an update at https://github.com/moyogo/molengo-fonts/releases

**Comment by moyogo** [comment]
:-) it’s not an update actually. It’s the package from 2010.

**Comment by davelab6** [comment]
Ill arrange a rebuild with Ttfautohint then :)

**Comment by laerm0** [comment]
The composite problem @m4rc1e reports [here](https://github.com/moyogo/molengo-fonts/issues/2) appears to still be an issue.

**Comment by davelab6** [comment]
Duplicate of #193
