### ISSUE TITLE
Poppins font character problem

### ISSUE THREAD

**Issue by JozefBiros** [google/fonts#351]
Problem with Poppins font with character  'ť' it will not render right in Chrome and Firefox but in Edge it's alright.

http://jsbin.com/ferobodowa/edit?html,css,output

This font:
https://fonts.google.com/specimen/Poppins

Screenshot:
![capture](https://cloud.githubusercontent.com/assets/9303703/17600803/76764f08-6005-11e6-979a-9779e3e64ef4.PNG)

**Comment by adrientetar** [comment]
Upstream is itfoundry/poppins#1 and itfoundry/poppins#3. Apparently the bug wasn't fixed yet. cc @lianghai @satyarajpurohit

**Comment by m4rc1e** [comment]
Fixed in #1099 

![screen shot 2017-07-25 at 11 54 33](https://user-images.githubusercontent.com/7525512/28569042-111282f2-7130-11e7-8ecd-d40755ae4835.png)

Keeping open until the family makes it into production

**Comment by laerm0** [comment]
Production is good. Closing this issue. 

![screen region 2017-09-06 at 15 19 28](https://user-images.githubusercontent.com/10780161/30130349-d23c8c36-9316-11e7-9356-e47474e9438e.png)
