### ISSUE TITLE
Update Maven Pro

### ISSUE THREAD

**Issue by klaslundberg** [google/fonts#352]
I'd like to see dotless characters in Maven Pro if possible? Specifically the latin small letter dotless i (ı).

**Comment by davelab6** [comment]
@thomasjockin is working on Maven Pro at the moment and will add this :)

https://groups.google.com/forum/#!topic/googlefonts-discuss/jcYesVslKCM

**Comment by m4rc1e** [comment]
Closing, LGTM.

![screen shot 2017-06-14 at 14 30 10](https://user-images.githubusercontent.com/7525512/27134623-0216342a-510e-11e7-9617-2efd0bb3742c.png)

http://jsbin.com/vosaqimoko/edit?html,output

Was added in #449
