### ISSUE TITLE
Add DIN Regular Font

### ISSUE THREAD

**Issue by xPPx** [google/fonts#353]
http://ufonts.com/fonts/din-regular.html

**Comment by adrientetar** [comment]
lol this is a pirate font. "Albert Jan-Pool, 1995" this is FF DIN. 
You can buy here: https://www.myfonts.com/fonts/fontfont/ff-din/

**Comment by xPPx** [comment]
Ouh thought it was free :/ THX for your reply

Adrien Tétar <notifications@github.com> schrieb am Fr., 12. Aug. 2016,
18:30:

**Comment by adrientetar** [comment]
It looks like ufonts.com hosts a lot of commercial fonts with a free download.
