### ISSUE TITLE
Release tags

### ISSUE THREAD

**Issue by Rudloff** [google/fonts#356]
Hello,
It would be easier to include this repository in other projects if it had release tags.

**Comment by davelab6** [comment]
Interesting... Since the repo contains 100s of projects, what would a release of the repo mean? What state should v1.0.0 be?

How are you trying to include this repo in your projects now? What URLs/etc would a release create for you?

**Comment by Rudloff** [comment]
I understand that it is hard for such a project to have a release cycle.
The main issue for me is that I don't want to update my local copy everytime there is a new commit, but I also don't want to miss major bug fixes or a lot of new fonts.

**Comment by davelab6** [comment]
I recommend that you do update every commit, since we are now using pull requests such that only likely-good fonts are committed to the master branch :)
