### ISSUE TITLE
Update Public Sans to v1.008, to include glyphs for Spanish language support

### ISSUE THREAD

**Issue by ulumills** [google/fonts#3576]
Hello! I'm wondering how often the Public Sans font is updated in Google Fonts. We use it and love it, but currently the [Google Fonts version](https://fonts.google.com/specimen/Public+Sans#glyphs) doesn't have glyphs to support Spanish language (they are [on the developer page](https://public-sans.digital.gov/reading/), though).

Thank you!

**Comment by fitojb** [comment]
The character sampler on Google Fonts specimen pages isn't comprehensive. The font already includes the characters you need.

**Comment by ulumills** [comment]
> The character sampler on Google Fonts specimen pages isn't comprehensive. The font already includes the characters you need.

Thank you for the reply—after some further digging, I now see it was an issue with Figma (which loads Google Fonts natively) rather than the font files itself.
