### ISSUE TITLE
Add YoungSerif

### ISSUE THREAD

**Issue by KyleAMathews** [google/fonts#359]
https://github.com/uplaod/YoungSerif

![image](https://user-images.githubusercontent.com/261579/225946844-066753d5-ea59-4158-9848-bebe1a226749.png)

**Comment by davelab6** [comment]
Thanks @KyleAMathews :)

**Comment by davelab6** [comment]
https://github.com/uplaod/YoungSerif/issues/2 is closed so this can proceed

**Comment by davelab6** [comment]
@noirblancrouge we are finally beginning to paying attention to this project! Since you are speaking French, I suggest you could schedule a call with @RosaWagner and/or @emmamarichal to discuss the project and what can be done to resolve some glyph set issues identified.
