### ISSUE TITLE
open sans 300 stop working

### ISSUE THREAD

**Issue by adambako** [google/fonts#36]
hi,
im using open sans latin-ext weight 300 on my site.. it was working well but today it just stop.. it dont display characters that was working before.. 

check the images

also you can see that characters works fine in all other widths, even in the 300 italic..
can you pls fix this issue?? thanks a lot

![snimka obrazovky 2015-05-27 o 15 43 27](https://cloud.githubusercontent.com/assets/8457004/7837444/3e5d9b56-0487-11e5-9552-002a596eec97.png)
![snimka obrazovky 2015-05-27 o 15 43 05](https://cloud.githubusercontent.com/assets/8457004/7837445/3e5dc5ea-0487-11e5-9398-b905e31ac5a3.png)

**Comment by davelab6** [comment]
Do you have the fonts installed locally?

**Comment by adambako** [comment]
hi,

no.. its online. 
you can see that this mistake is also on fonts.google.com

**Comment by davelab6** [comment]
What OS and browser versions are you using?

Here is Chrome 45 on Mac OS X 10.9.5:

![screen shot 2015-05-27 at 4 56 59 pm](https://cloud.githubusercontent.com/assets/261579/7837708/6c882fc8-0491-11e5-98a8-4e452c79a08b.png)

Do you have access to another computer/tablet/phone to verify this is specific to your computer? :)

**Comment by adambako** [comment]
ok.. so this is strange as i see this also on mac and chrome.. 
but i checked it on my another mac and on that its working fine.. 

now i restarted the main mac and it worked there as well.. 
sorry for this and thanks for your fast answer :)

**Comment by davelab6** [comment]
Welcome!
