### ISSUE TITLE
Upload Khand v2.000

### ISSUE THREAD

**Issue by m4rc1e** [google/fonts#363]
Hey,

A newer version of [Khand](https://github.com/itfoundry/khand) exists.

I need to check this version also fixes #145 and #131 before we upload.

Cheers,
Marc

**Comment by davelab6** [comment]
@m4rc1e have you checked this? :)

**Comment by m4rc1e** [comment]
V2.000 fixes #131, #145 still persists in this release. I also wanted to know if they had [ttfs](https://github.com/itfoundry/khand/issues/1). Unfortunately the font has a complex build chain so I don't want to create ttfs from their otfs. 

Cheers,
Marc

**Comment by yanone** [comment]
Closed this because I found that the sources on the repo are outdated as compared to the binaries
