### ISSUE TITLE
[2016 Encodings] Vietnamese /Acaron /acaron

### ISSUE THREAD

**Issue by impallari** [google/fonts#364]
@davelab6 @alexeiva @crystaltype
Do we need /Acaron U+01CD and /acaron U+01CE in the vietnamese glyphset?
OT Master language checker tool ask for it.

**Comment by crystaltype** [comment]
Hmm... No, Vietnamese doesn't use the caron accent.

**Comment by davelab6** [comment]
Thanks @impallari and @crystaltype :)
