### ISSUE TITLE
Onboard Outfit

### ISSUE THREAD

**Issue by davelab6** [google/fonts#3647]
https://github.com/Outfitio/Outfit-Fonts for @andyfitz

**Comment by andyfitz** [comment]
@aaronbell  please let me or Rodrigo know if you need anything!

**Comment by aaronbell** [comment]
Thanks @davelab6, @andyfitz.

I found a couple of items with the font and have started filing issues on the github repro. 

Missing glyphs from the GF Core glyph set:
https://github.com/Outfitio/Outfit-Fonts/issues/1

OUTFIT shouldn't be a default liga:
https://github.com/Outfitio/Outfit-Fonts/issues/2

I don't know if there's been discussion already about the glyph set, but wanted to mention here :)

**Comment by RosaWagner** [comment]
How is it going with this one? should we move it to Q4 milestone?

**Comment by aaronbell** [comment]
Yes I believe so. We’re just waiting on the new update.
