### ISSUE TITLE
Substantial increase on build size of Open Sans font since yesterday

### ISSUE THREAD

**Issue by rafeca** [google/fonts#3648]
Hey!

We've recently noticed a subantial increase (from 9KB to 70KB) of the latin woff2 font used when requesting the Open Sans font from Google Fonts (from the URL: https://fonts.googleapis.com/css?family=Open+Sans:400,600&display=fallback):

- A few days ago, v18 was being served (https://fonts.gstatic.com/s/opensans/v18/mem8YaGs126MiZpBA-UFVZ0bf8pkAg.woff2), **which weights 9.1KB**
- Now, v20 is being served (https://fonts.gstatic.com/s/opensans/v20/mem8YaGs126MiZpBA-UFVZ0bf8pkAg.woff2), **which weights 73.8KB**

The unicode range of both version seems to be the same, so I'm wondering whether there's some reasoning behind this increase (8X the previous size) or whether this is bug.

Thanks in advance!

**Comment by m4rc1e** [comment]
I've just downloaded the two different versions and you're right. v18 is 9kb and v20 is 74kb which seems pretty crazy. If I convert the woff2 to ttfs the file sizes seem much better. v18 is 18kb and v20 is 23kb.

@garretrieger something seems wrong when we're converting the ttfs to woff2. Has a dependency recently been updated?

**Comment by mathewlewis** [comment]
@m4rc1e @garretrieger Something is definitely wrong with v20 woff2. Websites with Open Sans are not displaying correctly in Firefox. Garbled text, missing characters.

**Comment by nyshadhr9** [comment]
Apologies for the inconvenience. This was happening due to an issue on the Google Fonts server side. 

We rolled out a fix which is live now. Open Sans requests should now return v21 which are back to their normal file sizes.

**Comment by mathewlewis** [comment]
@nyshadhr9 

Websites are returning v21 now and things look the way they should. No more font display issues in FF. Thanks for the quick response and push.
