### ISSUE TITLE
Titillium Web font set "name identifiers" do not follow recommended standards

### ISSUE THREAD

**Issue by DansDadUK** [google/fonts#369]
I'm new to this, so perhaps this needs adding to issue #115  ?

I've responded to a request for help on the Experts-Exchange forum regarding use of the TrueType set of "Titillium Web" fonts on Windows systems, specifically within Office applications.

Because all 11 of the fonts use the same Id=1 (FontFamily) value, Office applications can only 'see' one of the font 'subsets' (and select Regular, Italic, Bold or Bold Italic variants of this).

I've suggested modifications to the 'name idenfifier' entries in the 'name' tables of the fonts, and verified that these work, and allow Office applications to select the various fonts in the set.

The details are too long to type in here, so I'll just (try to) put in a link to the forum question:

[https://www.experts-exchange.com/questions/28966487/PowerPoint-not-providing-access-to-all-installed-fonts-within-a-family.html](url)

**Comment by davelab6** [comment]
Thanks for reporting @DansDadUK

**Comment by laerm0** [comment]
This appears to no longer be an issue.

![screen region 2017-09-06 at 14 50 57](https://user-images.githubusercontent.com/10780161/30129113-e0207e9c-9312-11e7-87f6-5835793037b8.png)

@DansDadUK, do you still have this issue?

**Comment by DansDadUK** [comment]
@laerm0 - I don't use these fonts myself, I merely reported the issue after investigating the symptoms  reported (on the E-E forum) and suggesting what the underlying problem was.

I also suggested a circumvention, and provided a modified test version of the font family (with a slightly different name).

I opened this thread on GitHub so that the problem could be documented and the modification be officially adopted by providing new versions of the font set.

Your image appears to suggest that the fonts have been changed as suggested.
But I haven't downloaded the (new versions of) the font set to confirm this - do you want me to do so?

**Comment by laerm0** [comment]
Ah, I see, thanks for the information. I don't think it's necessary for you to check out the new fonts, but feel free to do so if you want. I'm going to close this issue.

**Comment by JamieG-UK** [comment]
I just go asked about this again and checked with the latest font pack (1.002). Windows shows this in the settings app:

![image](https://user-images.githubusercontent.com/25979166/106513082-111f4280-6498-11eb-8e58-0d3127a99136.png)

And Microsoft Office displays the top level 5 fonts in the font UI:

![image](https://user-images.githubusercontent.com/25979166/106513137-27c59980-6498-11eb-8663-53cff177df25.png)

**Comment by eliheuer** [comment]
@JamieG-UK That might be my fault. I'll make a note about looking into this but can't promise anything beyond that.

**Comment by JamieG-UK** [comment]
No problem @eliheuer. I hadn't realised it had been raised here when I initially raised it on ExpertsExchange so just wanted to provide confirmation of the result. I assume the same might be true for all families but I haven't checked. Thanks for noting :-)
