### ISSUE TITLE
Add Bleed (BLED) Variation Axis

### ISSUE THREAD

**Issue by jenskutilek** [google/fonts#3697]
My [Homecomputer fonts](https://github.com/jenskutilek/homecomputer-fonts) use custom variation axes for visual artefacts related to [display on a cathode ray tube](https://www.masswerk.at/nowgobang/2019/dec-crt-typography): (horizontal) bleed (tag: BLED) and (vertical) scan lines (tag: SCAN).

I propose to add those axes to the Google Fonts axis registry:

### On CRT screens

The horizontal "bleed" of the pixels on a CRT screen is caused by the phospor latency:

![VTterm-phosphor-flanks](https://user-images.githubusercontent.com/3185950/129218316-85144541-d21b-4476-ac0e-7279e4ea57a0.png)
(Source: VT100 Series Technical Manual, EK-VT100-TM-002, p. 4-78)

The "Homecomputer" fonts simulate this effect by elongating the edge pixels horizontally.

![Bildschirmfoto 2021-08-12 um 16 52 26](https://user-images.githubusercontent.com/3185950/129218734-86edf033-00a3-4e29-9e89-401fdc85d184.png)
BLED=0

![Bildschirmfoto 2021-08-12 um 16 52 30](https://user-images.githubusercontent.com/3185950/129218791-e5203a6d-a045-420c-9e54-42e2e4252302.png)
BLED=max

### Other uses

A _Bleed_ axis could also be used to simulate the bleed of ink on paper. This is distinct from the proposed [Grade axis](https://github.com/google/fonts/blob/main/axisregistry/grade.textproto), which adds or subtracts weight from the glyphs uniformly, whereas the _Bleed_ axis could add or subtract weight in a way simulating the distribution of ink on paper when the printing process uses little or too much ink or pressure.

![typewriter-jens-kutilek](https://user-images.githubusercontent.com/3185950/129222127-f974c9b2-f954-47ea-b821-978d895ac39c.jpg)
Ink bleed on typewritten text. Top row: various levels of added bleed due to differences in pressure applied to the keys of a mechanical typewriter. Bottom row: negative bleed due to typing without a ribbon and thus the color fading as a key is struck multiple times.

### Axis proposal

```
tag: "BLED"
display_name: "Bleed"
min_value: -1000
max_value: 1000
default_value: 0
precision: 0
fallback {
  name: "Normal"
  value: 0
}
description:
  "Add or subtract weight from strokes or other forms in a uniform, random,"
  " or logical way, without any changes overall width, inter-letter spacing,"
  " or kerning, so there are no changes to line breaks or page layout."
  " Negative bleed makes the style lighter, while positive bleed makes it bolder."
  " This can be used to simulate different levels of ink bleed on paper, as"
  " commonly found in printed or typewritten materials."
```

**Comment by vv-monsalve** [comment]
This issue was transferred to https://github.com/googlefonts/axisregistry/issues/17. Please follow up there.
