### ISSUE TITLE
Add Scanlines (SCAN) Variation Axis

### ISSUE THREAD

**Issue by jenskutilek** [google/fonts#3699]
My [Homecomputer fonts](https://github.com/jenskutilek/homecomputer-fonts) use custom variation axes for visual artefacts related to [display on a cathode ray tube](https://www.masswerk.at/nowgobang/2019/dec-crt-typography): (horizontal) bleed (tag: BLED) and (vertical) scan lines (tag: SCAN).

I propose to add those axes to the Google Fonts axis registry:

### On CRT screens

Scanlines of pixels separated by a varying amount of black space are characteristic of CRT screens.

The _Scanlines_ axis allows to controls the height of the lines, and as a result of this, the amount of vertical space between the lines. The space may also disappear completely, causing the simulated "pixels" to blur into each other.

![Bildschirmfoto 2021-08-12 um 16 52 26](https://user-images.githubusercontent.com/3185950/129225284-c3f409c6-7906-4588-ae12-27f3ff04011a.png)
SCAN=default (0)

![Bildschirmfoto 2021-08-12 um 17 27 51](https://user-images.githubusercontent.com/3185950/129225338-42190ee6-4627-4aed-9652-66d4a6246010.png)
SCAN=min

![Bildschirmfoto 2021-08-12 um 17 28 08](https://user-images.githubusercontent.com/3185950/129225422-a0802104-601b-4e09-a25a-15f3ce49fd7d.png)
SCAN=max

### Other uses

![Bildschirmfoto 2021-08-12 um 17 39 36](https://user-images.githubusercontent.com/3185950/129226129-97a0af81-77f4-4a15-b85c-86981bacdef2.png)

The axis could also be used to segment glyphs in a way that is not reminiscent of CRT screens, similar to the "Hatch" filter in Glyphs.

### Axis proposal

```
tag: "SCAN"
display_name: "Scanlines"
min_value: -1000
max_value: 1000
default_value: 0
precision: 0
fallback {
  name: "Normal"
  value: 0
}
description:
  "Segment glyphs horizontally without any changes overall width, inter-letter spacing,"
  " or kerning, so there are no changes to line breaks or page layout."
  " Negative values causes the glyphs to become visually segmented,"
  " while positive values may cause the segments to overlap and thus"
  " cause a boldening effect."
```

**Comment by RosaWagner** [comment]
Closing this cause issue has moved to googlefonts/axisregistry repo
