### ISSUE TITLE
Add Albert Sans

### ISSUE THREAD

**Issue by usted** [google/fonts#3700]
https://github.com/usted/Albert-Sans

_The font and repository has been updated completely to the Unified Font Repository v0.3._

**Comment by thlinard** [comment]
The fonts in https://github.com/usted/Albert-Sans/tree/main/fonts are called Rubik (and are indeed https://github.com/googlefonts/rubik).

For a more complete config.yaml, you can take example on https://github.com/Omnibus-Type/Texturina/blob/master/sources/config.yaml

**Comment by usted** [comment]
Thanks for the heads-up and sorry for inconvenience. 
It has now been updated: https://github.com/usted/Albert-Sans/tree/gh-pages

**Comment by usted** [comment]
Hi there. I’ve just finished up and published a new release (https://github.com/usted/Albert-Sans/releases/tag/v1.11).
Is there anything I need to change on it or something I can do to ease the process?

**Comment by emmamarichal** [comment]
Hi @usted, 
I'm Emma, I work with @RosaWagner on the font onboarding.
I checked the font, there doesn't seem to be any problems, I can onboard it directly without changing anything. 
The only thing you have to do is to put the .OFL in the same folder as the fonts folder (in the release), or put the fonts folder in the repo (I don't see it now), they need to be together.
Thanks a lot :)
Cheers!

**Comment by emmamarichal** [comment]
Hi @usted,
You can forget the release, generating one is not an obligation actually. So, what you have to do is adding the fonts folder in the main branch ([https://github.com/usted/Albert-Sans](https://github.com/usted/Albert-Sans)), and it will be perfect! To package a font, we need to have the same path (url), for fonts and .ofl, so yes, you just need to move the font file in the main branch instead the gh-pages branch.
But if you have any doubt, I can do that next week, no problem! 👍 
Thanks,
Emma

**Comment by usted** [comment]
Hi @emmamarichal 
Thanks for the feedback. That should be fixed now. 
Please let me know if there is anything else.

Thanks,
Andreas

**Comment by emmamarichal** [comment]
@usted That's perfect, thank you! :)
