### ISSUE TITLE
Downloading fonts from website downloads not all the fonts selected

### ISSUE THREAD

**Issue by de22zx** [google/fonts#372]
1. Go to Google Fonts directory: https://fonts.google.com/
2. Select first 10 fonts (the more fonts selected is better for reproducing the issue)*
3. Click on "XX Families Selected" at the right bottom corner of the page, where "XX" is the amount of font families selected.
4. Click on "Download this selection" icon in the top right corner of the new modal window.
5. Open the downloaded zip archive with fonts.

Expected result: The amount of folders in zip archive, i.e., corresponding font families should equal the amount of font families selected.
Actual result: The amount of font families from the zip archive is less than the amount of font families selected.

*If select first 9-10 fonts, only 8 fonts are downloaded. If select random 10 fonts, it is possible that the bug is not reproducing. If select 50+ fonts, the bug will be reproduced in the most cases.

![2016-09-10_16-11-18](https://cloud.githubusercontent.com/assets/6173421/18410690/457db638-7771-11e6-9a0a-4c8dec6c14cc.png)

**Comment by davelab6** [comment]
There is a filesize limit on the ZIP that can be downloaded. If you'd like to download more fonts, you can use SkyFonts or Github :)

**Comment by mm47** [comment]
Unfortunately, Skyfonts doesn't work. When I try to download a google font with skyfonts, it says it needs to download skyfonts. But I'm already using skyfonts! Better download from github then.
