### ISSUE TITLE
Playfair Display woff2

### ISSUE THREAD

**Issue by sasoriza** [google/fonts#374]
I am loading these fonts on my page:

https://fonts.googleapis.com/css?family=Raleway:700,900%7CPlayfair+Display:400italic%7COpen+Sans:300,400,600%7CAbril+Fatface

For some reason there is a second request happening for the Playfair Display font:

https://fonts.gstatic.com/s/playfairdisplay/v10/9MkijrV-dEJ0-_NWV7E6NwXiAI3F8adTt8b-_w2WoPM.woff2

Can anybody explain why a woff2 file is requested for that font?

**Comment by davelab6** [comment]
Which browsers are you testing with?

It could be there are several fonts split using "unicode-range" :)

**Comment by sasoriza** [comment]
I tested this with Firefox and Chrome.

If this is the case, is there any way to fix this?

**Comment by davelab6** [comment]
On 13 September 2016 at 12:28, sasoriza <notifications@github.com> wrote:

> is there any way to fix this?
>
> unicode-range is new, so there's nothing to fix :) Please could you tell
me more about your concern? :)

**Comment by runytry1** [comment]
Firefox

Sent from Yahoo Mail on Android 
 
  On Tue, Sep 13, 2016 at 6:57 AM, Dave Crossland<notifications@github.com> wrote:   Which browsers are you testing with?

It could be there are several fonts split using "unicode-range" :)

**Comment by runytry1** [comment]
My error message send two times. 

Sent from Yahoo Mail on Android 
 
  On Tue, Sep 13, 2016 at 5:36 AM, sasoriza<notifications@github.com> wrote:   
I am loading these fonts on my page:

https://fonts.googleapis.com/css?family=Raleway:700,900%7CPlayfair+Display:400italic%7COpen+Sans:300,400,600%7CAbril+Fatface

For some reason there is a second request happening for the Playfair Display font:

https://fonts.gstatic.com/s/playfairdisplay/v10/9MkijrV-dEJ0-_NWV7E6NwXiAI3F8adTt8b-_w2WoPM.woff2

Can anybody explain why a woff2 file is requested for that font?

**Comment by sasoriza** [comment]
> Please could you tell
me more about your concern? :)

Any additional request that can be avoided is of concern to me ;) The question is - can it be. I am not so familiar with unicode range, I though it is only used with @font-face...

**Comment by runytry1** [comment]
Will   /  ? coming soon!
    
   - Welcome to Jonas Gift Card Shop with much more OK, and thank you. I didn't believe it when I first saw it, butit's real.  I verified it myself.   
This new Forex robot has won every single monthfor 12 months straight.   
And it's not stopping there.   
>> Click Here to See for Yourself (http://runytry88.htrader.a.clickbetter.com/)  , I AM SURREY TO MISS YOUR EMAIL I Will get to you very soon in the mean wiled  go to my lead page to find your opportunity    codesystemtestimonials        

 

    On Wednesday, September 14, 2016 4:27 AM, sasoriza <notifications@github.com> wrote:
 

 
Please could you tell
me more about your concern? :)
Any additional request that can be avoided is of concern to me ;) The question is - can it be. I am not so familiar with unicode range, I though it is only used with @font-face...—

**Comment by davelab6** [comment]
Oh I think it is returning the 400 style in addition to the 400i style you are requesting.
