### ISSUE TITLE
Bad metadata for Manuale?

### ISSUE THREAD

**Issue by rsheeter** [google/fonts#3741]
Regular and Italic for Manuale complain that "Variation axes mismatch between font binary and the font metadata: ({wght, 300.0..800.0}) != ({wght, 400.0..700.0})"

Since the metadata appears to be a subset of the fonts capability I'm not planning to block sandbox push on this but please sanity check if this is expected.

**Comment by RosaWagner** [comment]
cc @aaronbell

**Comment by aaronbell** [comment]
Thanks. I've submitted a PR correcting the Metadata file.

**Comment by m4rc1e** [comment]
Using the gftools packager automates running `gftools add-font` on new and updated families. Going forward, I do not want to see any manual pushes since people forget to run different tooling, https://github.com/googlefonts/fontbakery/issues/3429
