### ISSUE TITLE
Add Sofia Sans

### ISSUE THREAD

**Issue by RosaWagner** [google/fonts#3799]
Unblock PR #2889
upstream: https://github.com/lettersoup/Sofia-Sans

Problem of non-orthogonal design space.
- ~We can either convince the author to repair his designspace~
- Or we only onboard static TTF and forget about the VF
- onboard it under another name

**Comment by vv-monsalve** [comment]
After last work was done to have a working VF, these were the considered options:

- ~**Publishing it as a static font.** 
Would support the current fonts in use in Sofia. But not having VF option until Avar 2 table is available~
- ~**Publishing it as a VF.** 
As a different font, with another name or suffix e.g. `Sofia Sans Libre`. as it would not give support current fonts~
- **Publishing four single `wght` axis.** E.g. `Sofia Sans ExtraCondensed`. 
No need to suffix or different name; will have the VF benefits, would give support to current fonts in use, would be possible to update it to a single `Sofia Sans` vf once Avar 2 table is life

**Comment by davelab6** [comment]
Thanks @vv-monsalve , I edited your comment to add explanations of the decisions.

**Comment by vv-monsalve** [comment]
From the above decision, four PR will be made:

- [ ] Sofia Sans (for Normal 100 width)
- [ ] Sofia Sans ExtraCondensed
- [x] Sofia Sans Condensed (#5654)
- [ ] Sofia Sans SemiCondensed
