### ISSUE TITLE
Duplicate fonts

### ISSUE THREAD

**Issue by cmfwyp** [google/fonts#381]
The repository contains `./ofl/misssaintdelafield/MrsSaintDelafield-Regular.ttf`, which is version 1.000 and `./ofl/mrssaintdelafield/MrsSaintDelafield.ttf`, which is version 1.001. `./ofl/mrbedfort/MrBedfort-Regular.ttf` and `./ofl/mrbedford/MrBedfort-Regular.ttf` have the same version, but different hashes. `./ofl/siemreap/Siemreap.ttf` and `./ofl/siamreap/Siemreap.ttf` are exactly the same font, but `siamreap` is apparently an old holding font name. `./ofl/terminaldosislight/TerminalDosis-Light.ttf` is an older version (1.005) of `./ofl/terminaldosis/TerminalDosis-Light.ttf` (1.007). `./ofl/alefhebrew/Alef-Regular.ttf` and `./ofl/alef/Alef-Regular.ttf` have the same font name (this is also true of the bold variants), but they both support Hebrew according to the description so it might not be necessary to have both.

Having duplicate font file names causes conflicts when installing the fonts on a system. The older or identical duplicates should be removed, or, if that is not possible, symlinked to the newer files.

**Comment by davelab6** [comment]
> Having duplicate font file names causes conflicts when installing the fonts on a system

Please don't install them, then :)

> The older or identical duplicates should be removed, or, if that is not possible, symlinked to the newer files.

They are not exactly the same; there is a slight difference in the family names.

**Comment by cmfwyp** [comment]
@davelab6

The fonts are not exactly the same, but I doubt there's any reason to keep older versions of the fonts under different names. Fonts that are exact duplicates could be symlinked instead. The only one where keeping both seems necessary is `./ofl/alefhebrew/Alef-Regular.ttf` and `./ofl/alef/Alef-Regular.ttf`.
