### ISSUE TITLE
Reporter: Better time series control, more graph types, break out new vs updated families

### ISSUE THREAD

**Issue by davelab6** [google/fonts#3812]
@m4rc1e great work on the [reporter](https://google.github.io/fonts)! I have a few requests :)

- [x] Better time series control; I sometimes need to know the data between 2 specific dates.
- [x] Other chart types; I sometimes need to know the cumulative counts for each push type within the time range, and to compare them (pie chart)
- [x] The 'families' line on the 1st graph is good, but ideally I'd like to be able to break that down into 2 line, new vs updated.

**Comment by m4rc1e** [comment]
Thanks Dave,

I'll do tasks 1,3 and cut a new release. Task 3 will take me a bit more time to figure out.

**Comment by m4rc1e** [comment]
Alright, I think I'm done.

![_Users_marcfoley_Desktop_nu5 html](https://user-images.githubusercontent.com/7525512/133800057-8ba3f126-4ea8-43fc-9913-d7c37bbe03ca.png)

Will cut a new gftools release so it gets update on Sunday
