### ISSUE TITLE
Add Handjet

### ISSUE THREAD

**Issue by RosaWagner** [google/fonts#3817]
upstream: https://github.com/rosettatype/handjet

Handjet is a variable font with the following axes:
Weight (wght) (100-900) controls the size of the element,
Element Shape (ESHP) (0.0-16.0) controls the shape of the element,
Element Grid (EGRD) (1.0-2.0) controls how many elements are used per one grid unit.

1. It has been decided last year that custon axes need to be in GF's axis registry before onboarding
2. The font has been blocked in sandbox over a year now (probably because the interpolation needs multiple overlaying elements) and rendering is not good:
<img width="982" alt="Capture d’écran 2021-09-09 à 10 23 27" src="https://user-images.githubusercontent.com/12222436/132651807-7395f339-6364-4fe4-90c2-968b5a6ea6d3.png">

I don't see how the rendering issues could find a resolution in a near future. We shall find a solution to have it onboarded…maybe just as multiple static font families?

cc @davelab6 @MrBrezina

**Comment by davelab6** [comment]
I discussed this in https://github.com/rosettatype/handjet/issues/2 and AFAIK we should just proceed when we are registering new axes.

**Comment by kontur** [comment]
@RosaWagner Can we see inspect this sandbox page anywhere?

**Comment by davelab6** [comment]
@tomasdev became curious about this and noted that the https://rosettatype.com/Handjet page uses the VF at the first hero section with slides, but SVGs below, not only SVGs as I'd mistakenly assumed. Using that file, or using the latest upstream file, then I don't see the rendering bugs any more, here on macOS 12.3.1 (21E258). 

Here's a test page using a github CDN:

https://jsbin.com/zatojof/edit?html,output

Therefore if we can pop the latest VF in and propose axis registry definitions, the GF team can push this to their sandbox and see if the issue persists :)

**Comment by davelab6** [comment]
> @RosaWagner Can we inspect this sandbox page anywhere?

I'll email you private info about that

**Comment by kontur** [comment]
Thanks,

checked out the sandbox, but can only attest the same. One interesting observation from the Sandbox is that the glitching stops at exactly 160px (if I edit one sample line in my browser dev tools); could this be some autohinting mechanism in the renderer just turning off for sizes beyond that? However, the file on rosettatype.com does not display this behaviour, so maybe either this was affected by some change in the tool chain (where the rosettatype.com file is newer and was compiled with something that "fixes" this along the way).

Or, I am wondering if whatever script you run to remove the two ESHP and EGRD axis from the fonts could have an impact here? It would be good to test if the unchanged font without the removed axes renders in the sandbox without glitches.
