### ISSUE TITLE
Add Butler

### ISSUE THREAD

**Issue by KyleAMathews** [google/fonts#382]
It has 7 regular weights and 7 stencil weights. Not sure if the license is compatible with Google Fonts.

http://fabiandesmet.com/portfolio/butler-font/

**Comment by davelab6** [comment]
Yes, I have permission to add this from the designer, its in my queue :)

**Comment by mistersuuns** [comment]
Hello, has this been added yet? Thanks.

**Comment by PierreDickinson** [comment]
+1

**Comment by davelab6** [comment]
Sadly the designer retracted his permission so this can't be added.
