### ISSUE TITLE
Upgrade Oi

### ISSUE THREAD

**Issue by RosaWagner** [google/fonts#3820]
upstream: https://github.com/kosbarts/Oi 
delivery date. 30 oct. 2021
- [x] check repo
- [x] robot QA
- [x] visual QA
- [x] PR upstream
- [x] Package font

**Comment by kosbarts** [comment]
@RosaWagner the source files are updated to the latest version and are ready for production.

**Comment by RosaWagner** [comment]
@kosbarts can you push the new font in the fonts directory of the repo ?

**Comment by kosbarts** [comment]
@RosaWagner done. But these font files are produced with my build, not the action. Shouldn't be any issues. You can check the fontbakery report https://github.com/kosbarts/Oi/blob/main/sources/checks/checks_static.md

**Comment by RosaWagner** [comment]
The build and the action should have the same result. It's okay @emmamarichal already check and it is all good ;)
