### ISSUE TITLE
Upgrade Source Serif with V3

### ISSUE THREAD

**Issue by RosaWagner** [google/fonts#3825]
Update Source **Serif** to match the sans updated in  https://github.com/google/fonts/issues/1744#issuecomment-916149867

upstream: https://github.com/adobe-fonts/source-serif

**Comment by davelab6** [comment]
Per https://github.com/google/fonts/issues/2599 it sounds like the v3 might be close enough to v2 to update the `Source Serif Pro` family name, meanwhile that issue is about adding `Source Serif 4`

**Comment by RosaWagner** [comment]
Duplicate of 1744 that is closed
