### ISSUE TITLE
Add Huballi

### ISSUE THREAD

**Issue by RosaWagner** [google/fonts#3827]
upstream: https://github.com/erinmclaughlin/Hubballi
Sources are from 5 years ago, probably need a refresh in term of metadata and glyph naming.

- [x] Contact author
- [x] Build
- [x] FontGoggles functionality check
- [x] Fontbakery QA
- [x] Visual QA
- [x] Version bumped
- [x] Authors and Contributors info
- [x] Catalog designer info up to date
- [x] PR to upstream
- [x] Font Images (only new or major upgrades)
- [x] PR to GF

**Comment by yanone** [comment]
Upstream PR: https://github.com/erinmclaughlin/Hubballi/pull/10
