### ISSUE TITLE
Add BhuTuka

### ISSUE THREAD

**Issue by RosaWagner** [google/fonts#3828]
upstream: https://github.com/erinmclaughlin/BhuTuka-Extended-One
Font needs to be renamed "expanded" instead of "extended".
Needs to validate Camel Case name.
Sources are from 5 years ago, probably need a refresh in term of metadata and glyph naming.

**Comment by yanone** [comment]
Upstream PR: https://github.com/erinmclaughlin/BhuTuka-Extended-One/pull/3
