### ISSUE TITLE
Add Jaini

### ISSUE THREAD

**Issue by RosaWagner** [google/fonts#3830]
upstream: https://github.com/EkType/Jaini

Needs matching Latin to commison

**Comment by davelab6** [comment]
We can by exception publish font families without Latin; this is a good candidate for this. We simply don't include a `subset: latin` in the METADATA and then ask the GF eng team to set the font 'menu' subset to be made with another family (typically Roboto), which we have to do for unreadable fonts like Barcode and Flow fonts.

I propose we do so in this case, as the typeface is historically specific to India and a companion Latin isn't going to happen soon

**Comment by davelab6** [comment]
I wasn't able to commission anything yet, so this is still blocked.

**Comment by davelab6** [comment]
I was able to get this sorted, https://github.com/EkType/Jaini is good to go, so assigning to Chris to further assign in Q1

**Comment by davelab6** [comment]
I'd like to propose this for Q1, not Q2, and moved its gh milestone

**Comment by vv-monsalve** [comment]
Two font PRs are associated with this add font issue: Jaini and Jaini Purna.

The description says 
>Jaini and Jaini Purva differ in their treatment of conjuncts; Jaini adheres to
    contemporary conventions of horizontal conjuncts, whereas Jaini Purva stays true to vertically stacked conjuncts as
    seen in manuscripts.

However, the differences are very subtle. Do they need to be published separately? (Disclaimer: I'm not a Devanagari expert, but rather confirm about this before onboarding)

cc @davelab6 

![Regular-diffbrowsers_text-macOS-12 6 3-x86_64-i386-64bit_chrome-headless-shell_121 0 6167 85](https://github.com/google/fonts/assets/48698976/62d33848-fbae-4418-90d4-efbeb3ff0173)

**Comment by davelab6** [comment]
Yes, it's to do with historical scholarship where the differences matter and too many systems (cough Workspace) have no OpenType discretionary feature support

**Comment by vv-monsalve** [comment]
Excellent. Thanks for the confirmation.

**Comment by chrissimpkins** [comment]
PR open. Moving to Q2
