### ISSUE TITLE
Upgrade Baloo 2 families

### ISSUE THREAD

**Issue by RosaWagner** [google/fonts#3837]
upstream: https://github.com/EkType/Baloo2-Variable
--> Make single issues when work starts.

- Baloo Da 2 (Bengali)
- Balo 2 (Devanagari)
- Baloo Bhai 2 (Gujarati)
- Baloo Paaji 2 (Gurmukhi)
- Baloo Tamma 2 (Kannada)
- Baloo Chettan 2 (Malayalam)
- Baloo Thambi 2 (Tamil)
- Baloo Tammudu 2 (Telugu)
- Baloo Bhaina 2 (Odia)

**Comment by yanone** [comment]
Closing because I created separate issues for each family
