### ISSUE TITLE
Seems to always return all subsets

### ISSUE THREAD

**Issue by d1g1t** [google/fonts#384]
The following urls seem to return all subsets even though only the latin one is expected:
https://fonts.googleapis.com/css?family=Ubuntu&subset=latin
https://fonts.googleapis.com/css?family=Ubuntu

I tested this on Ubuntu 16.04 (64bit)
Firefox 49.0
Google Chrome 53.0.2785.116

However calling these urls via curl results in only the latin subset being shown, as expected

**Comment by davelab6** [comment]
This is correct, Firefox and Chrome support unicode-range :)

**Comment by d1g1t** [comment]
To clarify, does this mean the browser does not download the woff2 files for unused subsets?

**Comment by davelab6** [comment]
> To clarify, does this mean the browser does not download the woff2 files for unused subsets?

Yes, browsers that support unicode-range will only download the subsets needed to render the unicodes in the DOM as they appear; if no unicodes within the range specified are needed, the font is not downloaded. 

Thus, the CSS for all ranges is served, such that it is cached and works with 0 latency across sites.

**Comment by NisuSan** [comment]
The issue steel [not fixed](https://fonts.googleapis.com/css2?family=Roboto&subset=latin)
