### ISSUE TITLE
Add Maname

### ISSUE THREAD

**Issue by RosaWagner** [google/fonts#3842]
upstream: https://github.com/mooniak/maname-font

**Comment by yanone** [comment]
Dave, can you please assign the issues to my project (Yanone’s pipeline)? Some of the issues are not showing up in the list when I search for issues by author, don't know why. Assigning them to my project instead/additionally seems reliable.



> Am 29.09.2021 um 15:31 schrieb Dave Crossland ***@***.***>:
> 
> 
> Assigned #3842 to @yanone.
> 
> —
> You are receiving this because you were assigned.
> Reply to this email directly, view it on GitHub, or unsubscribe.
> 



--

Yanone
Dipl.-Designer,
Master of Design in Type & Media
https://yanone.de
Twitter/Instagram: @yanone
+49 176 24023268 (Germany)

Type.World project:
https://type.world

Crowd funding on:
https://www.patreon.com/typeWorld

**Comment by davelab6** [comment]
I just went over the roadmap with @RosaWagner and I see this was done via automation

<img width="932" alt="Screen Shot 2021-09-29 at 10 22 11 AM" src="https://user-images.githubusercontent.com/261579/135287852-31885e81-619b-4a24-bcc9-d325678e0c13.png">

and it seems to be fine

<img width="318" alt="Screen Shot 2021-09-29 at 10 21 25 AM" src="https://user-images.githubusercontent.com/261579/135287689-66a16433-46e5-4ff6-8b22-3aa54d35a36f.png">

**Comment by davelab6** [comment]
https://github.com/google/fonts/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+assignee%3Ayanone shows 18 open, 55 closed:

<img width="516" alt="Screen Shot 2021-09-29 at 10 23 20 AM" src="https://user-images.githubusercontent.com/261579/135288154-6c81a523-db78-4096-9926-e7dfec93ca96.png">

https://github.com/google/fonts/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+assignee%3Ayanone+project%3Agoogle%2Ffonts%2F5 has the same:

<img width="673" alt="Screen Shot 2021-09-29 at 10 23 26 AM" src="https://user-images.githubusercontent.com/261579/135288157-f22bc0e3-11d4-43eb-a120-56a62e8bb738.png">

So I think this is now sorted univerally also

**Comment by yanone** [comment]
I get only 8 open issues when I search for it, only 3 from today among them. 
I added all the issues you assigned me today to my roadmap manually to not lose track.

**Comment by yanone** [comment]
@mooniak What's the status of work on Maname?

**Comment by davelab6** [comment]
@pathumego what is the status of this family

**Comment by pathumego** [comment]
Yes! I have to make a release with final glyphset. I will prepare for Q2

**Comment by yanone** [comment]
Pointed out outlines fixes to author, now waiting for updated sources.
(@pathumego No need to react, we're keeping track of the progress here)

**Comment by pathumego** [comment]
@yanone Can you please check the repo and let me know what you need from our end to onboard? I will make a release once we fix anything you catch.

**Comment by yanone** [comment]
Replied [here](https://github.com/mooniak/maname-font/issues/11#issuecomment-2100837573) and comment above it
