### ISSUE TITLE
Poppins Regular Font Weight

### ISSUE THREAD

**Issue by jberg1** [google/fonts#386]
I'm using the Poppins font on a site and last week it was working fine. But all of a sudden (Friday) the regular weight (400) is appearing bold (700). I had to switch to medium weight (500) to make it slightly better. The issue only seems to appear in Firefox & IE.  Safari & Chrome it works as expected.

Has anyone else seen this issue? Not sure why this would of happened all of a sudden.
[http://www.jbergman.net/font-test/](http://www.jbergman.net/font-test/)
Same result with both linking and importing the style.

 Thanks for any help.

**Comment by davelab6** [comment]
As a workaround, please uninstall the fonts

**Comment by jberg1** [comment]
Ok, that worked.
Sorry for the duplicate, I didn't find that other thread when I searched for Poppins.

Thanks.

**Comment by noaptelinistita** [comment]
Hello.

I have the exact same issue with Poppins regular 400 which shows up as bold 700 on Explorer and Firefox (on Chrome it's displayed ok). In the begging it looked as it should, regular, but all of a sudden it turned bold.
But in my case, this problem happens on external websites too, not only on MY website.

It's driving me crazy! What's the problem with this font!?

![untitled-1](https://cloud.githubusercontent.com/assets/23130185/19825679/fa45c2f2-9d84-11e6-9ee7-a90f9b0c338e.jpg)

**Comment by jberg1** [comment]
It seems to happen when the font is installed on your computer (at least on PC). When you uninstall the font it goes back to normal. So it's isolated to people with the font installed on their system. My work around was to use font-weight 500 as a temporary fix. Not ideal, but it is close to the 400 weight.

**Comment by noaptelinistita** [comment]
Aah.. uninstall from the system. Yes, it worked! Thanx a million! I just couldn't move on with my life without knowing a fix :)

**Comment by laerm0** [comment]
Hi @jberg1 amd @noaptelinistita, are your issues solved? May I close this issue?

**Comment by jberg1** [comment]
There is a work around, but still funky behavior. This was added to the Font Bugs list but not technically resolved. I guess close it unless there is a plan to resolve the bug with the font file itself.

**Comment by davelab6** [comment]
Poppins was recently updated, so this *should not* happen any more...

**Comment by MelanieL** [comment]
I am definitely having this issue in Chrome, is anyone else still having it happen?
