### ISSUE TITLE
Add Victor Mono

### ISSUE THREAD

**Issue by davelab6** [google/fonts#3865]
https://github.com/rubjo/victor-mono-font
https://rubjo.github.io/victor-mono

Pending clarification of OFL @ https://github.com/rubjo/victor-mono/issues/120

**Comment by davelab6** [comment]
Project is now OFL so is good to proceed :) Next step is for someone here to review the source files.

Thanks @rubjo for your patience with us!

**Comment by RosaWagner** [comment]
@rubjo we would need clarification on some points:

- Do you expect Italic or Oblique to be the linked style to the upright? (when pressing the `i` button is app)
- Are you open to change the repo structure?
- How do you build the fonts?

**Comment by rubjo** [comment]
Thanks for taking this further.

> * Do you expect Italic or Oblique to be the linked style to the upright? (when pressing the `i` button is app)

Don't really understand this. If the question is which slanted style should be the default, I guess it would be the Italic one.

> * Are you open to change the repo structure?

Yes, if given a meaningful reason. :)

> * How do you build the fonts?

Manual export from Glyphs app.

**Comment by RosaWagner** [comment]
Thanks for your quick reply.

A font technically can't have linked 2 italics. One would have to not be onboarded, or be onboarded as a separated family. 

The reason for changing the repo structure is for making the automated building and onboarding of the font easier :)

More info in this chapter of the guide : https://googlefonts.github.io/gf-guide/upstream.html
If you want to take a look into how we would build the font: https://googlefonts.github.io/gf-guide/build.html
If you want to have a general view on the whole process: https://googlefonts.github.io/gf-guide/index

I think we can onboard the project during the summer, if you are up to we can have a call next week (or whenever you had a look at the Guide) so I can explain to you the process.

**Comment by rubjo** [comment]
All right, in that case probably use the Italic.

After skimming through https://googlefonts.github.io/gf-guide/upstream.html, it looks like some repo restructuring is necessary, yes, and the generation of a lot of GF-specific files and scripts.

As the Victor Mono repo currently is more focused on the site (https://rubjo.github.io/victor-mono) than on the font itself, maybe the cleanest approach is to make a new repo https://github.com/rubjo/victor-mono-font, consisting only of the required GF files...?

**Comment by RosaWagner** [comment]
That is indeed a good idea :)

**Comment by davelab6** [comment]
Amazing! Thank you so much @rubjo that is great news - and I hope our repo template makes it easier for you :)

**Comment by RosaWagner** [comment]
@rubjo I gonna be able to review this this week or the next, can you update teh README.md?

- for the soft dotted, we slightly changed our requirements, if the FAIL still persist, I'll make a PR to fix it. Maybe try to update and recompile the ccmp feature.
- The fail for PANOSE is a bit weird cause you seem to have the correct data in the sources… what happen if you put that data in the instances' custom parameter?

**Comment by RosaWagner** [comment]
Also the arrows in the italic look a bit distorted ;)

**Comment by rubjo** [comment]
- Readme and description updated.
- Soft dotted: tried recompilation, error is the same. Might be a Glyphs thing maybe, I don't know (I only have Glyphs 2, unfortunately).
- Panose: custom parameter is where I have tried to put this info:
<img width="839" alt="SCR-20230615-gyzt" src="https://github.com/google/fonts/assets/42270947/be06f84e-0236-45f4-aeb5-b8fa690fb7e2">

***
- Arrows in the italics have simply been applied the "cursify" transformation in Glyphs (12 degrees):
<img width="1894" alt="SCR-20230615-iyel" src="https://github.com/google/fonts/assets/42270947/8654c8d2-403b-4dda-b897-ab2b91a16961">
I think they look as intended in use:
<img width="846" alt="SCR-20230615-hmud" src="https://github.com/google/fonts/assets/42270947/59c28dbf-1049-41d6-9a3c-6131cd32489a">

**Comment by RosaWagner** [comment]
- For Panose I meant custom parameter of each defined instances in the exports/instance tab (we had a bug like that when we were using gLyphs2)
<img width="850" alt="Capture d’écran 2023-06-15 à 10 23 38" src="https://github.com/google/fonts/assets/12222436/75c324fe-7df2-4cfd-8ff3-9baa696b54d0">


- This is what I see in your sources with Glyphs3, ignore if it's not the case in GLyphs2
<img width="1239" alt="Capture d’écran 2023-06-15 à 10 21 30" src="https://github.com/google/fonts/assets/12222436/f70c8248-6f65-4d8d-b914-8aa8f45e95d6">

**Comment by rubjo** [comment]
Oh, I can understand what you mean by distorted. :D Yeah, it doesn't look like that in Glyphs 2.

Panose parameter per instance is pushed now and that fail is gone.

**Comment by RosaWagner** [comment]
Cool cool. If you want to get rid of the fail about the soft dot you can follow this tuto: https://googlefonts.github.io/gf-guide/diacritics.html#soft-dotted-glyphs

In the release there should also be the binaries. I think there is a github action for that once all fails disappear. Otherwise you can just take the artifacts from the build action and add the zip to the release.

**Comment by rubjo** [comment]
Zip from build action manually added to release. Don't think I have time to look into the soft dot thing unless it is a hard requirement.

**Comment by RosaWagner** [comment]
@rubjo since your font is ready to onboard, you can fill up your bio through this form: https://docs.google.com/forms/d/e/1FAIpQLSeMwHN8J213ZaxHrr5lHCrX56HY_NjGrWB8o604g98YxuMrdA/viewform

**Comment by rubjo** [comment]
Done. :)
