### ISSUE TITLE
Add IBM Plex Sans JP

### ISSUE THREAD

**Issue by davelab6** [google/fonts#3874]
https://github.com/IBM/plex/releases

**Comment by davelab6** [comment]
In short, after @aaronbell reviewed, I decided that since the Latin is scaled differently to the rest, we'll wait for the next IBM release which may resolve this.

**Comment by yanone** [comment]
@davelab6 Both Mike Abbink as well as Paul vd Laan have replied by email saying that the scaling is deliberate and there's no expectation for it to change. Interpolation issues will be fixed in the upcoming release, so I should indeed wait, but shall I otherwise onboard it as is?

**Comment by davelab6** [comment]
@yanone yeah, interpolation issues sounds bad, so moving this to Q3 as we wait for the next release
