### ISSUE TITLE
Open Sans v26: small text looks weird

### ISSUE THREAD

**Issue by HandyMenny** [google/fonts#3876]
Since Open Sans has been updated to version 26, small text seems to lack antilasing.

How small varies depending on display resolution and scaling. I was able to reproduce (clearly) this problem with weight 400 and font-size 16px on Firefox and several Chromium-based browsers\* using Windows 10.

Example:
![opensans_v25](https://user-images.githubusercontent.com/3463028/134816037-fc0568c4-8b52-43fb-ace4-768280217975.png)
Open Sans v25 font-size 16px

![opensans_v26](https://user-images.githubusercontent.com/3463028/134816038-60670408-b004-4daf-b57d-ebd78433efdb.png)
Open Sans v26 font-size 16px

I've uploaded a .css file with Open Sans v25 here: https://gist.github.com/HandyMenny/a581e0c1dd02515e656485b8cf6933e9

\* Brave, Chrome, Edge, Opera

**Comment by davelab6** [comment]
That's working as expected, it was a long standing bug that Open Sans turned on anti aliasing

**Comment by matteocontrini** [comment]
@davelab6 was it really a bug? It doesn't look good at all now, unfortunately...

**Comment by m4rc1e** [comment]
We recently pushed an updated set of fonts which don't have gasp tables. I'm currently releasing an update which will fix this issue.

**Comment by matteocontrini** [comment]
@m4rc1e thank you!

**Comment by davelab6** [comment]
@matteocontrini SORRY :) I read your captions the wrong way around!! I read

```
Example:
[image]
Open Sans v25 font-size 16px
[image]
```

But now I see the labels are actually under each image, not above:
```
Example:
[image]
Open Sans v25 font-size 16px
[image]
Open Sans v26 font-size 16px
```

So, yes, this is a regression, and we'll push a v27 to address this.

**Comment by HandyMenny** [comment]
> I read your captions the wrong way around!!

No problem, out of curiosity is it the "gasp tables" issue mentioned above or is it something else?

**Comment by m4rc1e** [comment]
Apologies. GH auto closed this when I merged #3877.

**Comment by Yash22nov** [comment]
Hi m4c1e,
Still Open sans font looks weird in font-size: 12px; font-weight: 600.  Please solve this issue asap...

![open sans](https://user-images.githubusercontent.com/91519079/135402339-821a431f-38d3-4ed8-a039-67b9a86c9960.png)

**Comment by kvetis** [comment]
We're having the same issue as @Yash22nov. The issue appears in v27 and does not appear in v26. Font size 12px, font weight 600.


> 
> 
> @mark foley Still Open sans font looks weird in font-size: 12px; font-weight: 600. Please solve this issue asap...
>

**Comment by m4rc1e** [comment]
@kvetis which browser and OS. Do you also have a url?

**Comment by matteocontrini** [comment]
In my case v27 fixed the issue that was originally reported.

**Comment by kvetis** [comment]
@m4rc1e Hi, thanks, I dug into it and it turns out the issue was caused by a specific font version on google fonts api - https://fonts.gstatic.com/s/opensans/v27/memvYaGs126MiZpBA-UvWbX2vVnXBbObj2OVTSGmu0SC55K5gw.woff2 - which was linked from a build-system-inlined css.

It does not happen with currently served google api CSS with current link: https://fonts.gstatic.com/s/opensans/v27/memvYaGs126MiZpBA-UvWbX2vVnXBbObj2OVTSGmu1aB.woff2

So re-building the app should fix my problem. Thanks for your time.

**Comment by m4rc1e** [comment]
Not a problem at all. Thanks for reporting!

**Comment by HandyMenny** [comment]
Also in my case this issue has been fixed with V27, so this issue can be closed

**Comment by cvocvo** [comment]
Sorry to bump a closed item, but I'm seeing a similar issue with v28 of OpenSans specifically on higher weight items at small font sizes:
![image](https://user-images.githubusercontent.com/355711/163269030-8a4e49e8-44e4-488b-8c24-41b94116c0dd.png)
This is open sans v28 at size 13
https://fonts.google.com/specimen/Open+Sans?query=open+sans#standard-styles
