### ISSUE TITLE
Cabin Condensed Medium - unsupported Turkish character

### ISSUE THREAD

**Issue by nabak9** [google/fonts#388]
There is a Turkish character that is not supported.
An example would be the word Keşif. 
![selection_249](https://cloud.githubusercontent.com/assets/22450652/18837858/a38b5e24-8405-11e6-882c-4a3f2dad3dc8.png)

The 3rd character is not supported. You can see it by growing the font size, and previewing on the google fonts website will display an empty box.
![selection_257](https://cloud.githubusercontent.com/assets/22450652/18837939/ee10f756-8405-11e6-8c3c-ab47d70abde8.png)

**Comment by davelab6** [comment]
@kalapi please confirm this is supported in the upcoming update

**Comment by kalapi** [comment]
@nabak9 @davelab6 Cabin has been extended to cover a plethora of languages :)

This will be available with the next update!

![cabin_2](https://cloud.githubusercontent.com/assets/15804460/18840808/6d60d216-842d-11e6-81c7-89d4f0e5d903.png)

**Comment by nabak9** [comment]
@kalapi I tested your update. 
The letter is fixed but there is a vertical alignment issue. 
The text using the font available on https://fonts.google.com/selection?selection.family=Cabin+Condensed:500 is always centered in its bounding box like many other fonts.
![selection_263](https://cloud.githubusercontent.com/assets/22450652/18875558/94fac86a-84c6-11e6-80a2-325961380fcd.png)

But in the update, it is aligned to the top. Is it possible to fix that?
![selection_262](https://cloud.githubusercontent.com/assets/22450652/18875568/9af2f35a-84c6-11e6-9db5-3232e4b41936.png)

**Comment by kalapi** [comment]
@nabak9 The update is still 'in progress'. All these problems will be fixed once i'm done with the update. :)

**Comment by graphicore** [comment]
I mastered the changes to Cabin and Cabin Condensed today: https://github.com/impallari/Cabin/pull/3 and https://github.com/google/fonts/pull/390
I believe the bbox issue is fixed:

![selection_112](https://cloud.githubusercontent.com/assets/393132/18897113/8dee4522-8527-11e6-8de3-15d347029023.png)

@nabak9 if you like you could test the fonts from here: https://github.com/graphicore/Cabin/tree/master/fonts/TTF

@kalapi I hope no more action is required.

**Comment by kalapi** [comment]
@graphicore Perfect, thanks!

**Comment by nabak9** [comment]
@graphicore @kalapi I tested only the Cabin Condensed Medium and the issue is resolved.
Thanks a lot to both of you :)
