### ISSUE TITLE
Old version of Montserrat missing extended-Latin glyphs

### ISSUE THREAD

**Issue by alerque** [google/fonts#389]
The version of [Montserrat](https://github.com/JulietaUla/Montserrat) posted [on Google Fonts](https://fonts.google.com/specimen/Montserrat) is quite dated and has a number of issues. Notably the font actually supports extended Latin ranges including Turkish characters, but the version posted doesn't have these.

There is a (way too) long running issue #2 about the missing weights, but this is a slightly different issue. Because the original issue said it wasn't getting done because Latin only fonts were low priority, I thought I'd add this as a separate issue that will get higher priority as the language support has been greatly increased.

**Comment by davelab6** [comment]
Thanks @alerque :) It is in the queue.

**Comment by alerque** [comment]
Thanks for the response @davelab6 and I'm glad to hear there is hope for this.

That being said the process here is a bit opaque and given the issue with weights for this series has been outstanding for a 1 ½ years, could you perhaps enlighten us on what being in the queue means? Is this a bucket to be worked on eventually or has the font been added and put to a review process or what? Are things in this queue estimated to take a week or a month or a year or a decade to clear the queue and be publicly available? Is there anything the community or font author can do to facilitate a short stay in the queue?
