### ISSUE TITLE
Upgrade Expletus Sans

### ISSUE THREAD

**Issue by RosaWagner** [google/fonts#3890]
upstream: https://github.com/googlefonts/Expletus-Sans

**Production notes:**

- [x]  Repo structure
- [x]  Fontbakery
- [x]  Visual QA
- [x]  Build
- [x]  RFN issue solved
- [x]  PR Upstream
- [x]  Package

**Comment by emmamarichal** [comment]
Hello! 
We have noticed that the old metrics are not compatible with the new ones and that there is no use typo metrics. Do we change everything, and if not which ones do we keep? Mac/windows ?

![Capture d’écran 2021-10-20 à 11 41 19](https://user-images.githubusercontent.com/64773544/138070277-f6f36ffc-7739-4c2c-ad13-fe6c54f69f80.png)


![Capture d’écran 2021-10-20 à 11 45 34](https://user-images.githubusercontent.com/64773544/138070284-6b60c535-dfc5-4459-8ce1-616fca0dd80d.png)

**Comment by RosaWagner** [comment]
And we need to contact the author about the RFN

**Comment by emmamarichal** [comment]
We have 2 options for v-metrics.
- keep the old values
- calculate new values according to google specs
@RosaWagner 


**With old values:**

![Desktop_Windows_10_chrome_71 0_](https://user-images.githubusercontent.com/64773544/141449485-aad26258-e1dd-493c-9199-a374cca91f9a.gif)

**With new values**

![Desktop_Windows_10_chrome_71 0_](https://user-images.githubusercontent.com/64773544/141449710-73408aea-f1bd-42b4-b3d7-9a4251049fce.gif)

**Comment by RosaWagner** [comment]
As additional info:
We noted that v-metrics from the version in API were not the same as the version in this repo which were not the same as version upstream. The one from API's version were actually not so bad but lacking cross-platform consistency and centred caps. 

Option 1 is resolving that while keeping former linespacing.

Option 2 is resolving that while having linespacing = 120% UPM

So I would go for option 1 which seems to be a better compromise even if linespacing is a bit large.
