### ISSUE TITLE
Upgrading to latest version breaks VSCode

### ISSUE THREAD

**Issue by memeplex** [google/fonts#3898]
After upgrading with [this brew formula](https://github.com/Homebrew/homebrew-cask-fonts/blob/master/Casks/font-source-code-pro.rb) that AFAICS fetches the latest version of the fonts using svn, VSCode rendering of Source Code Pro is broken as in https://github.com/microsoft/vscode/issues/100840. My original report to homebrew is https://github.com/Homebrew/homebrew-cask-fonts/issues/4993.

**Comment by RosaWagner** [comment]
If I follow the issue you linked, this issue was due to the change of Source Code Pro file name and it has been resolved by Homebrew.
