### ISSUE TITLE
Add Vina Sans

### ISSUE THREAD

**Issue by ngmtuan** [google/fonts#3899]
Hello,

Please find our submission "Vina Sans" to be considered for the Google Fonts Collection.
Project URL: https://github.com/nguyentype/vinasans

![03](https://user-images.githubusercontent.com/60652024/136017899-33842ec7-d020-4246-90ff-6262aa37aafe.png)

**Comment by davelab6** [comment]
@ngmtuan thanks for this, nice work! @yanone will be in touch with next steps
