### ISSUE TITLE
Add Helvetica Neue LT Std family and Playfair Display SC

### ISSUE THREAD

**Issue by jmprestidge** [google/fonts#392]
Please add these fonts if you can
(ZIP removed)

**Comment by m4rc1e** [comment]
Erm this by LinoType.

**Comment by davelab6** [comment]
@jmprestidge Playfair Display SC is already added (but needs an update); Helvetica is not libre licensed.

**Comment by jmprestidge** [comment]
Sorry for my ignorance...what is libre licensed???

**Comment by davelab6** [comment]
https://en.wikipedia.org/wiki/Libre_software
