### ISSUE TITLE
Jura: DemiBold

### ISSUE THREAD

**Issue by m4rc1e** [google/fonts#395]
When I download the family from [Jura](https://fonts.google.com/?query=jura) from [fonts.google.com](https://fonts.google.com), a DemiBold weight exists. This is not allowed, I will rename to SemiBold.

Cheers,
Marc

**Comment by alexeiva** [comment]
I have renamed it to semibold in the new version.

**Comment by m4rc1e** [comment]
Closing, LGTM.

![screen shot 2017-06-15 at 12 09 37](https://user-images.githubusercontent.com/7525512/27178777-89400a06-51c3-11e7-9275-edf808090e7c.png)

https://fonts.google.com/?query=jura&selection.family=Jura
