### ISSUE TITLE
Upload some handwriting academic font

### ISSUE THREAD

**Issue by EscolAssumpcio** [google/fonts#3951]
Hello! We are using Google Worskspace for Education in our school and we really need a handwriting academic font for our beginner students.

We would like to have avaiable some of these fonts: **Escolar1** (normal) or **Massallera** and also **Escolar4** (dots) if it is possible. This is the link where to get them from: [http://innoveduca.com/index.php/es/recurso/fuentes-de-letra](url)

Thank you so much in advance!

**Comment by applecuckoo** [comment]
Hi there @EscolAssumpcio, those fonts don't seem to be under the Open Font License. However, you can get the handwriting fonts used in Australia on Google Fonts (see [here](https://fonts.google.com/?query=Tina+Anderson)). Hope this answers your query!

**Comment by simoncozens** [comment]
I know this is an old issue, but there will be a large number of handwriting primer fonts arriving on Google Fonts soon, including the Playwrite project and many (more) versions of Australia and New Zealand educational fonts.
