### ISSUE TITLE
Support ExtraBlack/Heavy weight (1000) in Axis Registry

### ISSUE THREAD

**Issue by cssobral2013** [google/fonts#3967]
For example: Mulish has an ExtraBlack static weight upstream, but it doesn't appear in API, nor it's automatically generated.

**Comment by justinpenner** [comment]
Just adding my support for this issue, as I was going to file it myself until I found this. The ExtraBlack weight of Mulish is missing from the specimen page at https://fonts.google.com/specimen/Mulish and is also missing in the downloadable `Mulish.zip` package.

**Comment by thlinard** [comment]
Looks like the new version of [METADATA.pb](https://github.com/google/fonts/commit/4fc2349f63644b20792e839849e0f7b418fedb9e#diff-994bfc6b80b58840b7d99a78d6f88b7e58506741fb9b999451e64b2bb9fc106f) never made it to the API…

**Comment by RosaWagner** [comment]
Discussion moved to https://github.com/googlefonts/axisregistry/issues/40
