### ISSUE TITLE
IPA Font License accepted?

### ISSUE THREAD

**Issue by hfhchan** [google/fonts#397]
Is the IPA Font License accepted for inclusion into Google Fonts?
A ton of Chinese/Japanese fonts are licensed under the IPA font license as they were derived from IPA Mincho.

However, the license contains a Reserved Font Name clause.  My understanding is that this applies mainly to the original work (IPA Mincho) and can be waived by authors of derivative works.

**Comment by davelab6** [comment]
No, only OFL is accepted for new fonts; we discuss this with upstream developers who may release their own work under OFL, and strip out any IPA parts.

**Comment by hfhchan** [comment]
Ah... this is quite problematic because new derivative works/glyphs based on IPA Mincho are typically created by moving around components from other characters in IPA Mincho itself.  The sheer amount of characters in Chinese/Japanese makes it extremely hard to be completely original.

**Comment by davelab6** [comment]
Do you think the IPA would switch from their own license to OFL?

**Comment by graphicore** [comment]
>  The sheer amount of characters in Chinese/Japanese makes it extremely hard to be completely original. 

I think we can all easily agree with this :-)

**Comment by hfhchan** [comment]
What about dual licensing?

**Comment by davelab6** [comment]
@hfhchan the OFL says "and no other license" which means its incompatible with everything, even MIT/BSD

**Comment by hfhchan** [comment]
> Permission is hereby granted, free of charge, to any person obtaining
> a copy of the Font Software, to use, study, copy, merge, embed, modify,
> redistribute, and sell modified and unmodified copies of the Font
> Software, subject to the following conditions:
> ...
> 
> 5) The Font Software, modified or unmodified, in part or in whole,
> must be distributed entirely under this license, and must not be
> distributed under any other license.

This means this restriction only applies to any person obtaining a copy of the software, not to the owner of the font himself, right?

**Comment by davelab6** [comment]
On 24 October 2016 at 11:42, hfhchan <notifications@github.com> wrote:

> Permission is hereby granted, free of charge, to any person obtaining
> a copy of the Font Software, to use, study, copy, merge, embed, modify,
> redistribute, and sell modified and unmodified copies of the Font
> Software, subject to the following conditions:
> ...
>
> 5) The Font Software, modified or unmodified, in part or in whole,
> must be distributed entirely under this license, and must not be
> distributed under any other license.
>
> This means this restriction only applies to any person obtaining a copy of
> the software, not to the owner of the font himself, right?
>
(a) That doesn't allow for "heterogeneous" licensing - combining different
works under different but compatible licenses - which is what we need to do
here.

(b) What you are suggesting, distributing a homogeneously licensed work
under several incompatible licenses, perhaps only works for the first
distributor; perhaps all downstream distributors must not distribute the
work under any other license when they have the option to use the OFL. =)
