### ISSUE TITLE
Update Noto

### ISSUE THREAD

**Issue by davelab6** [google/fonts#398]
Per https://github.com/googlei18n/noto-fonts/issues/736 I will update Noto

**Comment by echenley** [comment]
@davelab6 Any update on this? Much appreciated!

**Comment by davelab6** [comment]
@echenley thanks for the ping on this. @m4rc1e we should give this a high priority because the current font is garbling user text. However, prepping a PR is a bit complicated, because the TTFs served in the API are a pyftmerge'd font of Noto Sans LGC + Noto Sans Devanagari which I did as a one-off and I don't think I have the exact command I used documented where it should be - in this repo - but buried in some internal email thread. :)

**Comment by davelab6** [comment]
Per https://twitter.com/badlydrawnrob/status/841685098151989250 and https://github.com/badlydrawnrob/cardinal-material/issues/8 it would be good to confirm the Noto upstream has fixed this, and if not, file an issue about it :)

**Comment by mbevand** [comment]
Any update? I notice Google Fonts is still serving an old Noto Serif that doesn't include fixes made more than 2 years ago (eg. https://github.com/googlei18n/noto-fonts/issues/512)...

**Comment by nickdima** [comment]
Any update on this? I was looking for Noto Serif Medium on Google Fonts but it doesn't seem to be available.

**Comment by thlinard** [comment]
Updated versions available on Adobe Fonts:

- https://fonts.adobe.com/fonts/noto-sans
- https://fonts.adobe.com/fonts/noto-sans-display
- https://fonts.adobe.com/fonts/noto-serif

**Comment by slk333** [comment]
@davelab6

**Comment by timtorres** [comment]
Hello, any updates on this? We're having to use a weird Frankenstein of Google web fonts for Noto Sans regular + bold which loads appropriate resources based on browser support, and then a static web font version for the light weight that I scraped from one of our client's internal pages that somehow has that weight.

**Comment by RosaWagner** [comment]
Noto Sans was updated with https://github.com/google/fonts/pull/4291
