### ISSUE TITLE
Letter "L" on Nunito Sans (and Nunito)

### ISSUE THREAD

**Issue by lucasmodena** [google/fonts#3993]
The original Nunito font shows the lower case character "L" as a straight line, and it looks consistent across versions of the font on the web (example: https://fonts.adobe.com/fonts/nunito-sans#fonts-section). But Google's version has this round leg that differs from others.

Is this supposed to look this way?

**Comment by drewmcdowell** [comment]
The alternative style set would be a solution, but it doesn't appear to work. `font-feature-settings: "ss02";` has no effect.

You can see my attempt to enable it here: https://codepen.io/drewmcdowell/pen/oNojpZQ

**Comment by kenmcd** [comment]
> The alternative style set would be a solution, but it doesn't appear to work. `font-feature-settings: "ss02";` has no effect.
> 
> You can see my attempt to enable it here: https://codepen.io/drewmcdowell/pen/oNojpZQ

The discussion above is about the desktop fonts.
The web fonts served by Google Fonts do not have all the OpenType features.
What is and is not supported is not made clear anywhere.
But they do say this [here](https://fonts.google.com/knowledge/introducing_type/open_type_features_in_practice):
"At the time of writing, non-essential OpenType features aren’t included in web fonts served via Google Fonts’ API; however, the OpenType features are still present in the downloadable fonts, which can then be self-hosted."

If you look at the Google Fonts' API, not much is available (no mention of stylistic sets).
You can assume if something is not mentioned in the API it is not supported.

So your only option is to self-host full versions of the fonts.
