### ISSUE TITLE
fsSelection issue in ofl/montaguslab

### ISSUE THREAD

**Issue by nathan-williams** [google/fonts#3994]
ERROR: fsSelection bold should be 0, is 1

See [ofl/montaguslab/MontaguSlab\[opsz,wght\].ttf](https://github.com/google/fonts/blob/main/ofl/montaguslab/MontaguSlab%5Bopsz%2Cwght%5D.ttf).

**Comment by m4rc1e** [comment]
Rod brought this up previously but the current values we have seem correct to us.

The font's zero origin is the Bold weight which means the OS/2.fsSelection and head.macStyle must have their respective Bold bits enabled which is what we've done.


```
<?xml version="1.0" encoding="UTF-8"?>
<ttFont sfntVersion="\x00\x01\x00\x00" ttLibVersion="4.26">

  <OS_2>
    ...
    <usWeightClass value="700"/> <-- 700 == Bold
    ...
    <fsSelection value="00000000 10100000"/>
    ...
  </OS_2>

  <head>
    ...
    <macStyle value="00000000 00000001"/>
    ...
  </head>

  <fvar>

    <!-- Weight -->
    <Axis>
    ...
      <MinValue>100.0</MinValue>
      <DefaultValue>700.0</DefaultValue> <-- Bold is the zero origin
      <MaxValue>700.0</MaxValue>
    ...
    </Axis>
    ...
</ttFont>
```

I think this is the first family that we've pushed that has a Zero Origin which is greater than the Regular weight.

**Comment by RosaWagner** [comment]
@nathan-williams this is discussed in https://github.com/google/fonts/pull/3858#issuecomment-939160803

**Comment by davelab6** [comment]
Tracking internally so closing
