### ISSUE TITLE
Poppins' doublelowquotemark (201E) seems to be incorrect

### ISSUE THREAD

**Issue by MarcJandt** [google/fonts#404]
<img width="136" alt="bildschirmfoto 2016-10-13 um 22 57 28" src="https://cloud.githubusercontent.com/assets/21021769/19366745/9823573a-9198-11e6-9ab5-52bb2c73ee69.png">
As you can see on the screenshot, the 0x201E  „ DOUBLE LOW-9 QUOTATION MARK displays as a single comma.

**Comment by m4rc1e** [comment]
Confirmed

![screen shot 2017-06-19 at 11 59 51](https://user-images.githubusercontent.com/7525512/27282193-d980fa72-54e6-11e7-89ca-a90900b3fcaa.png)


http://jsbin.com/jifeqedoje/edit?html,output

**Comment by m4rc1e** [comment]
Fixed in #1099 

![screen shot 2017-07-25 at 11 52 31](https://user-images.githubusercontent.com/7525512/28568994-ca36023c-712f-11e7-9c06-34d735dd252b.png)

Leaving open until the family makes it into production

**Comment by laerm0** [comment]
This is active on the site now so I am closing the issue.

![screen region 2017-09-06 at 14 05 01](https://user-images.githubusercontent.com/10780161/30127222-73662190-930c-11e7-97c1-938e3edfcdc4.png)

**Comment by davelab6** [comment]
Thanks @laerm0
