### ISSUE TITLE
Update Rasa/Yrsa binaries to version 2.003

### ISSUE THREAD

**Issue by kontur** [google/fonts#4042]
Hey all,

the Rasa/Yrsa fonts have just [released a minor version bump to 2.003](https://github.com/rosettatype/yrsa-rasa/releases) fixing several smaller issues, but particularly the fix for https://github.com/rosettatype/yrsa-rasa/issues/27 should go to google fonts as soon as possible (seems to have been introduced already with the 2.000-2 updates / Variable fonts).

As far as the repo goes we have also removed Italics from Rasa, since it is a non-Latin family. The Latin + Italics are to be used as Yrsa.

**Comment by RosaWagner** [comment]
Thanks, noted. The problem is that we can't upgrade a font without italics if the current version on GF is served with them. It would create massive regression on the websites using them already. I know this is a bummer but can you re-add them?

**Comment by kontur** [comment]
Okay, I'll take a look next week and reinstate the VF Italics to the repo, the removal was more of a "logical cosmetics" correction, because Yrsa (Latin-centric) should have them, but Rasa (Devanagari-centric) should not have them. However, I think it is preferable to keep the Italics and deploy the fixes rather than not get updates to the GF dsitribution. 

You only need the variable font in place, right?

**Comment by yanone** [comment]
> You only need the variable font in place, right?

Yes

**Comment by kontur** [comment]
Rasa VF italics are back in [v2.004](https://github.com/rosettatype/yrsa-rasa/releases/tag/v2.004), sorry for the back and forth, a bit of miscommunication on my side.

Would be great to get the fixes from 2.003 live 👍

**Comment by yanone** [comment]
@kontur Upstream PR: https://github.com/rosettatype/yrsa-rasa/pull/30
