### ISSUE TITLE
Update Alice to version 2.002

### ISSUE THREAD

**Issue by thlinard** [google/fonts#4043]
https://github.com/cyrealtype/Alice/releases/tag/v2.002

Fixes https://github.com/cyrealtype/Alice/issues/3

**Production notes** 

- [x]  Repo structure
- [x]  Fontbakery
- [x]  Visual QA
- [x]  Build
- [x]  RFN issue 
- [x]  PR Upstream
- [x]  Package

**Comment by Raeskaa** [comment]
Hi, 
I'd like to work on this issue
can you assign this to me!
