### ISSUE TITLE
Update Cyreal fonts

### ISSUE THREAD

**Issue by thlinard** [google/fonts#4044]
Four year old fixes, never PR here:

1. Artifika https://github.com/cyrealtype/Artifika
2. Aubrey https://github.com/cyrealtype/Aubrey
3. Brawler https://github.com/cyrealtype/Brawler
4. Wire One https://github.com/cyrealtype/Wire-One

Partial fixes for https://github.com/google/fonts/issues/1305.

**Comment by yanone** [comment]
Close this issue as I have split it into four separate issues to comply with our current workflow. Thank you.
