### ISSUE TITLE
Two versions of Vollkorn v5.000

### ISSUE THREAD

**Issue by thlinard** [google/fonts#4046]
I looked for the source of the bad paths mentioned in https://type.today/en/journal/transitional#Vollkorn 

![image-kGbzqvha2irsMTaO_H0Sw8-0cVptP6VGDw](https://user-images.githubusercontent.com/13808824/140784119-e9dee513-43ea-4cc5-818d-c0e261f5ea38.jpg)

They weren't in my version, which I got from here https://github.com/google/fonts/tree/main/ofl/vollkorn

But they're present in the version used in the API (https://fonts.google.com/specimen/Vollkorn?preview.text=Kk&preview.text_type=custom#standard-styles).

I found the root of the problem: there were two PRs of the Vollkorn (#2443 and #2960), each of a different version but with the same version number (v5.000).

1. PR #2443 is the source of the API.
2. PR #2960 is the source of the current repository.

**Comment by RosaWagner** [comment]
Thanks @thlinard 
So we need to bump up version number and re-push.
