### ISSUE TITLE
Add Pecita

### ISSUE THREAD

**Issue by bardware** [google/fonts#405]
This repo has a font [Pecita](https://github.com/google/fonts/tree/master/ofl/pecita) I don't see it on the [website](https://fonts.google.com/?query=Pecita). Where is it?

**Comment by davelab6** [comment]
@bardware it was never published in the API, due to file size concerns

**Comment by jesusmtzarvizu** [comment]
So , this issue should be closed due the @davelab6 response don't you think ?

**Comment by davelab6** [comment]
@jesusmtzarvizu eventually I will add it :)

**Comment by jesusmtzarvizu** [comment]
I downloaded the Pecita Font and weigh about 1.1 MB, and Andika weigh 1.5MB and Andika is working any idea why is that?

**Comment by austin-guevara** [comment]
Similarly, I notice that [on the website](https://fonts.google.com/specimen/Montserrat), Montserrat only contains Regular and Bold versions. But [in this repo](https://github.com/google/fonts/tree/master/ofl/montserrat), it includes Black, SemiBold, Bold, ExtraBold, Light, ExtraLight, Medium, and Regular.

Any way we can get the remaining styles hosted and available for use from the main website? Thanks in advance!

And side question – if fonts are listed here, does that mean they're unofficially hosted? Can we use the same @font-face or <style> tag to use them?

**Comment by bardware** [comment]
Hi @austin-guevara,
fonts here are provided as .ttf files. You would want them as .woff or .woff2 in a website.

**Comment by davelab6** [comment]
I will work on getting this repo and the API in sync in 2017

**Comment by austin-guevara** [comment]
Thanks, @davelab6! That also answers my question. I was hoping that maybe the repo showed fonts that were in the API, but not explicitly listed on fonts.google.com. Excited to hear more font-weights are coming this year 👍

**Comment by davelab6** [comment]
http://pecita.eu/b/ has latest sources

**Comment by davelab6** [comment]
@RosaWagner assigning this to you :)

**Comment by RosaWagner** [comment]
@davelab6 shall we set up a googlefonts/ repo for this one?
