### ISSUE TITLE
Barlow Condensed: Extra space after character Ø

### ISSUE THREAD

**Issue by carnevalle** [google/fonts#4055]
There are still issues with the danish character Ø when using capital letters

More on this issue: https://github.com/google/fonts/issues/1851

![136904408-451a37a0-69c2-4e65-a26c-efc86d3f88b9](https://user-images.githubusercontent.com/54747/141257007-4d459281-db4b-425f-9807-b119f75c3ce7.png)

**Comment by RosaWagner** [comment]
Thanks for reporting. I close this in favour if the more detailed issue.

**Comment by schoien** [comment]
This is still an issue, where can I find the updated font files?
