### ISSUE TITLE
[Crimson Text] Semi-bold 600 italic Double qoute is broke

### ISSUE THREAD

**Issue by ypsilon-p** [google/fonts#4060]
If you using semi bold (600) italic as font style, the double qoute  has a misrepresentation:
https://fonts.google.com/specimen/Crimson+Text?preview.text=%22&preview.text_type=custom
<img width="1431" alt="Bildschirmfoto 2021-11-12 um 10 33 48" src="https://user-images.githubusercontent.com/24660297/141444756-a0594182-944e-4161-907f-81a188423ebc.png">

**Comment by RosaWagner** [comment]
Please use Crimson Pro instead: https://fonts.google.com/specimen/Crimson+Pro

**Comment by RosaWagner** [comment]
Crimson text is now deprecated. Websites using this version are still served with it, but they won't get any updates.
