### ISSUE TITLE
Lexend Deca not printing correctly - lowercase e, w, y, h, n and uppercase M, W, Y.

### ISSUE THREAD

**Issue by jnc0614** [google/fonts#4076]
I created a project using the Lexend Deca Font on Google Docs and had it printed through Kindle Direct Publishing (a print-on-demand service). When I received the printed material, the Lexend font didn't print correctly. I contacted Kindle Direct Publishing and they told me that the font through Google Docs is corrupt. If the font is printed in a large font size (about 50 and above) the lower case "e" and capital M, capital W, both lower and uppercase Y do not print correctly. Is there anything that can be done to fix this issue so I can print a document from Google Docs with Lexend Deca through a printing service? Incidentally, the document prints without any problem on my home printer.

I've attached some photos so you can see the problem when the font is printed through Kindle Direct Publishing. I'll also attach the information from the KDP printing department. 

![IMG_6778](https://user-images.githubusercontent.com/29586270/142336660-8eba7711-b48e-45dc-9786-558e01ed7eb0.JPG)
![IMG_6779](https://user-images.githubusercontent.com/29586270/142336672-fb1aa5c6-2dc1-461f-9b6c-cedaea5b8d5c.JPG)
![Screen Shot 2021-11-08 at 1 28 22 PM](https://user-images.githubusercontent.com/29586270/142336675-0dd45c68-5611-486a-8144-418509362828.png)
![Screen Shot 2021-11-08 at 1 28 34 PM](https://user-images.githubusercontent.com/29586270/142336676-8d1d08d0-4b65-40a4-be29-dfbf6a1fa24b.png)

**Comment by kenmcd** [comment]
It appears the overlaps were not removed from the static fonts.
Some applications/printers will have a problem with this.
I just checked and the fonts currently available for download from Google Fonts still have this problem.
And these are the fonts you are using on Google Docs.

I also just checked the repository and the static fonts there look OK.
Here: https://github.com/googlefonts/lexend 
You can download the ZIP of the repository here:
https://github.com/googlefonts/lexend/archive/refs/heads/main.zip 
That will get you the static fonts without any overlaps.

Until the fonts are updated on Google fonts, this is your only option.
Install the static fonts from the repository locally.
Download your document so you can edit it locally.
Then export your PDF with these working fonts.

**Comment by jnc0614** [comment]
kenmcd, thank you - this is very helpful information. 

When you suggest "download your document so you can edit it locally", does that mean I can use Google Docs offline to edit it locally, or will I need to use another platform like Word, Pages or InDesign to accomplish this?

**Comment by kenmcd** [comment]
> When you suggest "download your document so you can edit it locally", does that mean I can use Google Docs offline to edit it locally, or will I need to use another platform like Word, Pages or InDesign to accomplish this?

Yes. 
I am not very familiar with Google Docs, but it is my understanding that you can download your documents in editable formats such as Word .docx, or LibreOffice .odt, etc.
Then you can edit the doc in Word or LibreOffice, and then export it to PDF locally which will use the better fonts that you installed locally.

**Comment by jnc0614** [comment]
Can anyone give an idea of when this issue might be fixed for the Lexend Deca font in Google Docs Fonts? 
Depending on what the approximate timeline is, it would help me choose from a few options for completing my project. 
Thank you!

**Comment by RosaWagner** [comment]
Google Fonts is keeping overlapping contours for static fonts instantiated from a variable fonts, so it won't be fixed. 

What you are experiencing is a PostScript printer that is not handling this kind of outlines (that are proper to true type fonts). If you plan to print with this kind of machine (which happens quite often with external printing services), it is recommended to use a version with merged contours that you can find here: https://github.com/googlefonts/lexend/tree/main/fonts/deca/ttf. Install it on you machine and use it as described in the previous comment. 

You will have this problem with PS Printers with every fonts on GF that is a variable font or that was made from a variable font. If you want to find the version with merged contours, click on the link at the end of the font's description.

**Comment by jnc0614** [comment]
Thanks very much for this information - it is really helpful.
