### ISSUE TITLE
Open Sans showing all text as bold on all active websites

### ISSUE THREAD

**Issue by fishnyc22** [google/fonts#410]
I'm having an issue that just appeared out of nowhere. All sites that i've built using open sans is showing the font as bold. There have been no changes to the sites where this is happening. Is there some issue going on? Or is this some weird hiccup in the universe?

**Comment by davelab6** [comment]
I suggest to uninstall the fonts as a workaround

**Comment by laerm0** [comment]
Do you still have this issue, @fishnyc22?
