### ISSUE TITLE
How to view the fonts past the first 1,000 entries (without using any programs)?

### ISSUE THREAD

**Issue by cssobral2013** [google/fonts#4100]

**Comment by rsheeter** [comment]
I think the best answer we have is use fonts.google.com; if you specifically don't want to do that then I fear you need to at minimum clone the repository. The simplest way I'm aware of is to go to https://github.com/google/fonts, click Code, and then choose to Download Zip (links to https://github.com/google/fonts/archive/refs/heads/main.zip at time of writing)
