### ISSUE TITLE
Can you add my font "Imperfect" to Google Fonts?

### ISSUE THREAD

**Issue by Mwalters75** [google/fonts#4120]
Hi, I made an font called "Imperfect", and I wanted to know if I can have my font on Google Fonts, the repository is here: [https://github.com/Mwalters75/imperfect](https://github.com/Mwalters75/imperfect). If you can get it on there that would be great!

**Comment by Mwalters75** [comment]
Sorry if I'm bothering anyone, but there was no response for almost a week. If my font didn't get accepted, that's fine.

**Comment by Mwalters75** [comment]
> Thanks for the submission.
> 
> It seems your font is a collection of images. Do you plan on making a font binary at some point?

No, because, well, I don't know how to make a font binary.

**Comment by fitojb** [comment]
Fonts are drawn as vectors, not bitmaps, and are usually in the OpenType format, either as TTF or OTF files. You can research font-making software, like Glyphs, FontLab, Robofont and Highlogic Font Creator, among others.

**Comment by Mwalters75** [comment]
> Fonts are drawn as vectors, not bitmaps, and are usually in the OpenType format, either as TTF or OTF files. You can research font-making software, like Glyphs, FontLab, Robofont and Highlogic Font Creator, among others.

Okay, but, what should I do if I'm using a Chromebook?

**Comment by fitojb** [comment]
Emulate, I guess?

**Comment by Mwalters75** [comment]
I don't understand.

**Comment by Mwalters75** [comment]
...Or I can use web ones, or ones that support Android devices?

**Comment by vv-monsalve** [comment]
Hi, thanks for your submission.

Unfortunately, the project doesn't comply with GF requirements. It is impossible for us to give a review if source files (font editor files such .UFO or .glyphs) are missing. Please read the contributing policies and requirements in the [Google Fonts Guide](https://googlefonts.github.io/gf-guide/) carefully, and feel free to re-open an issue when the font complies with them.
