### ISSUE TITLE
Update Paprika (Eduardo Tunni)

### ISSUE THREAD

**Issue by thlinard** [google/fonts#4137]
Same as #4119

Version here & in the API: version 1.001, Western Europe languages support only.

Version [upstream](https://github.com/etunni/paprika): version 1.001, 8 years old. BUT: with [Adobe Latin 3](https://adobe-type-tools.github.io/adobe-latin-charsets/adobe-latin-3.html) support.

**Production notes**

- [x]  Build fonts
- [x]  Fontbakery
- [x]  Visual QA
- [x]  Build
- [x]  PR Upstream
- [ ]  Package

**Comment by RosaWagner** [comment]
please @thlinard don't add stuff like label names into the titles, we get it from the content of the issue.

**Comment by thlinard** [comment]
These labels were missing from the issues: you just added them, so it was not useless.

**Comment by thlinard** [comment]
> It would however be useful if you could in some manner propose labels. Then you could mark an issue as what you think is a bug, so the owner can just confirm that. Many people suggest labels in the title: [proposed Label] actual title
https://stackoverflow.com/questions/13829466/how-to-put-a-label-on-an-issue-in-github-if-you-are-not-a-contributor-owner

**Comment by RosaWagner** [comment]
I didn't say it was useless, I said I can get it from the issue content, so I don't have to rename the issues on top of other stuff :)

If you want to be super explicit about the labels to use, please be my guest and add it in the issue content. I would ignore for other users but since you have your habits here, I prefer to let you know :)

**Comment by thlinard** [comment]
Oh, OK, no problem, if you prefer that I put the suggested labels in the body of the text rather than in the subject, I'll do so. 😀

**Comment by emmamarichal** [comment]
Fixed in #4496
