### ISSUE TITLE
Add "Bell Bottom Laser" 

### ISSUE THREAD

**Issue by kopmanis** [google/fonts#4161]
**Font Project Git Repo URL:**
https://www.dafont.com/bell-bottom-laser.font

**Super short description of the Font Family:**
70's hippie style font

**Requirements:**

I can confirm the project meets these requirements:

- [ ] The entire font project is licensed under the [OFL](https://scripts.sil.org/cms/scripts/page.php?site_id=nrsi&id=OFL)
- [x] Family name is unique according to namecheck.fontdata.com
- [x] I read the [contributing requirements](https://github.com/google/fonts/blob/main/CONTRIBUTING.md)
- [ ] The repository respect the [upstream repo structure](https://github.com/googlefonts/gf-docs/tree/main/Spec#upstream-repo-structure)
- [ ] I will maintain the repository

**Comment by RosaWagner** [comment]
Thanks for your submission @kopmanis, you have to tick the cases to show that you respect the requirements  :)

**Comment by RosaWagner** [comment]
I found the font you recommended online (https://www.dafont.com/bell-bottom-laser.font) and for what I see the glyphset is way too small and I couldn't find any license. That + the fact that a lot of requirements are missing mean we unfortunately can't onboard it.
