### ISSUE TITLE
Asset: acute and grave diacritics are reversed in uppercase letters

### ISSUE THREAD

**Issue by fitojb** [google/fonts#4163]
![imatge](https://user-images.githubusercontent.com/554953/145696855-ee8685fb-f8aa-4bde-ad3e-00162f5d4cab.png)

**Comment by RosaWagner** [comment]
Status: we can't find an upstream repo, so we would have to hotfix the files and eventually open the pandora box of unfixable fontbakery fails.

**Comment by yanone** [comment]
New repo has been created: https://github.com/SorkinType/Asset
