### ISSUE TITLE
Noto Sans Hebrew missing glyphs and numbers

### ISSUE THREAD

**Issue by elirangolan** [google/fonts#4167]
There is missing glyphs and numbers in the hebrew version of noto sans,
instead of numbers it shows empty square.
also doesn't show the english letters.
<img width="1469" alt="Screen Shot 2021-12-13 at 14 09 32" src="https://user-images.githubusercontent.com/96057798/145809770-09e00693-e8ca-4bb1-8517-42e70210f99d.png">

**Comment by RosaWagner** [comment]
Noto Sans Hebrew is supporting only hebrew script, to be able to write in english you can use Noto Sans in combination (as a [fallback font](https://css-tricks.com/css-basics-fallback-font-stacks-robust-web-typography/#aa-individual-characters) for example).

**Comment by ShlomitIDME** [comment]
Hello,
I read your answer but I don't understand it. Hebrew also include Numbers and Pancuation marks. Are you saying that for every Digit and comma, period etc, I need to select the English version of the font?

When I asked for Info of the font file on my mac, I couls see those missing Glyphs. Noto sans also present as such in Google fonts. 

But it will not function in any application. Why to offer a font that does not support it? 

My screenshot shows what I mean. 

Thank you
Shlomit


<img width="360" alt="Noto-Hebrew-Sans-Mac-Info" src="https://user-images.githubusercontent.com/96372479/202980481-7496054b-0586-4e74-98d2-8ee22b7014f8.png">
<img width="761" alt="Noto-Hebrew-Sans-Mac-Adobe-InDesign" src="https://user-images.githubusercontent.com/96372479/202980490-1897c741-db83-481f-9948-fb55d0d1594c.png">
