### ISSUE TITLE
Add [oswald]

### ISSUE THREAD

**Issue by Jbhair** [google/fonts#4169]
**Font Project Git Repo URL: <link rel="preconnect" href="https://fonts.googleapis.com"> 
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin> 
<link href="https://fonts.googleapis.com/css2?family=Oswald:wght@200;300;500;600;700&family=Readex+Pro:wght@500;700&display=swap" rel="stylesheet">**

**Super short description of the Font Family:oswald**

**Requirements:**

I understand that Google Fonts will publish only fonts that matches its requirements, and I can confirm the project meets them (by ticking the cases):

- [x] The entire font project is licensed under the [OFL](https://scripts.sil.org/cms/scripts/page.php?site_id=nrsi&id=OFL)
- [x] Family name is unique according to namecheck.fontdata.com
- [x] If the font targets latin based written languages, it supports at least [GF Latin Core glyphset](https://github.com/googlefonts/gftools/blob/main/Lib/gftools/encodings/GF%20Glyph%20Sets/GF-latin-core_unique-glyphs.nam)
- [x] I read the [contributing requirements](https://github.com/google/fonts/blob/main/CONTRIBUTING.md)
- [x] The repository respect the [upstream repo structure](https://github.com/googlefonts/gf-docs/tree/main/Spec#upstream-repo-structure)
- [x] I will maintain the repository

**Comment by fitojb** [comment]
Did you submit this bug as a test? Please don’t.

**Comment by RosaWagner** [comment]
Doesn't look like a real submission, so I'm closing this
