### ISSUE TITLE
Add Bodeg

### ISSUE THREAD

**Issue by nermink99** [google/fonts#4172]
**Font Project Git Repo URL:**
https://github.com/nermink99/Bodeg

**Super short description of the Font Family:**
Bodeg is a modern font using both sharp and curved edges to stand out from the crowd while maintaining a clean design which makes it adaptable to many situations. 

**Requirements:**

I understand that Google Fonts will publish only fonts that matches its requirements, and I can confirm the project meets them (by ticking the cases):

- [x] The entire font project is licensed under the [OFL](https://scripts.sil.org/cms/scripts/page.php?site_id=nrsi&id=OFL)
- [x] Family name is unique according to namecheck.fontdata.com
- [x] If the font targets latin based written languages, it supports at least [GF Latin Core glyphset](https://github.com/googlefonts/gftools/blob/main/Lib/gftools/encodings/GF%20Glyph%20Sets/GF-latin-core_unique-glyphs.nam)
- [x] I read the [contributing requirements](https://github.com/google/fonts/blob/main/CONTRIBUTING.md)
- [x] The repository respect the [upstream repo structure](https://github.com/googlefonts/gf-docs/tree/main/Spec#upstream-repo-structure)
- [x] I will maintain the repository

**Comment by yanone** [comment]
Hi @nermink99 
We’ve evaluated your submission and have concluded that it’s too crude of a design to be publishable on Google Fonts. Below you’ll find just a few letters I’ve picket that illustrate problems with legibility and design consistency. 

<img width="720" alt="Bildschirmfoto 2022-02-03 um 12 47 04" src="https://user-images.githubusercontent.com/175386/152337449-86e6925e-bc00-4b5e-9cff-665d97f060a0.png">

Fixing this won’t be an easy task. The typeface needs a complete re-design. Please don’t feel discouraged and return to us if you have a more refined design to propose. Meanwhile, I’m closing this issue. Thank you for your submission.
