### ISSUE TITLE
Rosario VF Light isn't light

### ISSUE THREAD

**Issue by davelab6** [google/fonts#4187]
**Describe the bug**
Rosario VF Light isn't light.

**To Reproduce**
Compare the current Light style to the previous one.

**Expected behavior**

The light weight should be lighter than the regular.

**Screenshots**

Here's a specimen from the foundry:

<img width="1440" alt="Captura de pantalla 2021-09-09 a la(s) 13 02 56" src="https://user-images.githubusercontent.com/261579/146661108-554613fb-47b1-469b-8170-ee64cdd9e5ba.png">

Here's the font in GF:

![Rosario-01](https://user-images.githubusercontent.com/261579/146661109-67d40b66-40fb-4bde-b182-0a0511ce5632.png)

**Comment by RosaWagner** [comment]
I just checked the fonts from GF and upstream and I don't see an issue, Light does seem lighter than Regular. Also the values in the AVAR, STAT etc all seems correct.

<img width="1132" alt="Capture d’écran 2022-01-05 à 11 45 47" src="https://user-images.githubusercontent.com/12222436/148205116-833be92c-db86-4185-b553-25f3b3a05958.png">

**Comment by davelab6** [comment]
odd. I now also can't reproduce this. no idea what was going on. Closing :)

**Comment by Omnibus-Type** [comment]
Excuse me. I just see this... Thank you very much!

**Comment by thlinard** [comment]
Actually fixed in https://github.com/Omnibus-Type/Rosario/pull/8
