### ISSUE TITLE
EB Garamond Typographer's quotes not displayed / printed in PDF files using Adobe Indesign 

### ISSUE THREAD

**Issue by michaelfrick111** [google/fonts#4207]
Specify the font name in title with a short description of the bug

**Describe the bug**
When Typographer's quotes are active they are correctly displayed in the UI (opening low and closing high one)  but incorrectly printed in the resulting PDF output. Size 12pt EB Garamond regular font. 

**To Reproduce**
Steps to reproduce the behavior.
Following quotes used to test:  “ “    „ „ „  „ „ „ „ ““““

**Expected behavior**
Result in printing should reprocuce correct layout as in UI.

**Screenshots**

Attached screenshot shows that with google font Zilla Slab the same characters are printed correctly. 

**Additional context**
[Untitled-1.pdf](https://github.com/google/fonts/files/7840246/Untitled-1.pdf)

Adobe Indesign 17.0.1 / latest version on a  Mac Book Air 2019 (Intel) with Mac OS Monterry 12.1

**Comment by RosaWagner** [comment]
I can reproduce, but only with `quote double base`. There is no nested components in this glyph, I don't see outline issues in the sources. Seems specific to this font.

This is a screenshot from the output pdf (using variable font):

<img width="809" alt="Capture d’écran 2022-01-19 à 11 45 39" src="https://user-images.githubusercontent.com/12222436/150115200-fe140ee7-3a38-429c-b3a5-a4680e6ab25e.png">

cc @octaviopardo

**Comment by kenmcd** [comment]
> I can reproduce, but only with `quote double base`. There is no nested components in this glyph, I don't see outline issues in the sources. Seems specific to this font.
> 
> This is a screenshot from the output pdf (using variable font):
> 
> <img alt="Capture d’écran 2022-01-19 à 11 45 39" width="809" src="https://user-images.githubusercontent.com/12222436/150115200-fe140ee7-3a38-429c-b3a5-a4680e6ab25e.png">
> 
> cc @octaviopardo

This appears to be a bug in InDesign introduced in v17.0.
It appears that with components one of the elements appears as the .notdef symbol (the box).
See list of ID bug reports here: https://github.com/huertatipografica/piazzolla/issues/24#issuecomment-1013700747

**Comment by michaelfrick111** [comment]
I can confirm that since last update received from ID the problem has disappeared. ID Version 17.1. 
thank you, 
rgds Michael Frick

**Comment by michaelfrick111** [comment]
See last remark.

**Comment by davelab6** [comment]
I also ran into this on a project with Roboto Serif, and confirmed 17.1 fixed it!
