### ISSUE TITLE
Add Gantari

### ISSUE THREAD

**Issue by Lafontype** [google/fonts#4213]
**Font Project Git Repo URL:**
https://github.com/Lafontype/Gantari

**Super short description of the Font Family:**
Gantari is a geometric sans serif family designed by Anugrah Pasau.

**Requirements:**

I understand that Google Fonts will publish only fonts that matches its requirements, and I can confirm the project meets them (by ticking the cases, or putting x between the square brackets in text mode):

- [x] The entire font project is licensed under the [OFL](https://scripts.sil.org/cms/scripts/page.php?site_id=nrsi&id=OFL)
- [x] There is no "Reserved Font Name" mention in the OFL license
- [x] Family name is unique according to namecheck.fontdata.com
- [x] If the font targets latin based written languages, it supports at least [GF Latin Core glyphset](https://github.com/googlefonts/glyphsets/blob/main/Lib/glyphsets/encodings/GF%20Glyph%20Sets/GF-latin-core_unique-glyphs.nam)
- [x] I read and agree with the full [contributing requirements](https://github.com/google/fonts/blob/main/CONTRIBUTING.md)
- [x] The repository respect the [upstream repo structure](https://github.com/googlefonts/gf-docs/tree/main/Spec#upstream-repo-structure)
- [x] I will maintain the repository

**Comment by Lafontype** [comment]
I don't know how to get a response. At least give an opinion if this is not worth including in google font library, so I can make an update.

**Comment by davelab6** [comment]
While https://namecheck.fontdata.com/?q=Celebes doesn't return anything, https://www.google.com/search?q=Celebes+font appears to show this font family name is already in use, so I would kindly like to request a different name :)

<img width="897" alt="Screen Shot 2022-02-25 at 5 50 01 PM" src="https://user-images.githubusercontent.com/261579/155821637-ca047400-d304-4827-8034-e159548970fa.png">

**Comment by Lafontype** [comment]
I don't know whether to create a new issue or not when renaming the font family. so I posted a comment and changed the repository name and address.
