### ISSUE TITLE
Rubik webfont displays character differently from desktop font

### ISSUE THREAD

**Issue by RokasSkeivys** [google/fonts#4220]
Hey.

I am having this issue that letter Ø is displayed differently on web vs desktop applications like inDesign, Sketch, Word or PowerPoint. 

I attached examples. How can this be fixed?

![Rubik](https://user-images.githubusercontent.com/6932484/150168643-7a809b28-1ca7-4fac-ac0d-2015ed207e25.jpg)

**Comment by RosaWagner** [comment]
Your desktop version is showing the previous version of the font. Did you download the font before and is this version still installed on your computer?

Make sure to remove all versions of the font before installing a new one, clean font cashes and restart your computer (and the app) before installing a new one.

**Comment by RokasSkeivys** [comment]
Thank you for your reply Rosa, in hindsight it seems obvious that I should have just removed and downloaded the font again, but I haven't experienced it before that fonts get updated like that before. 

Thank you once again, have a great day!
