### ISSUE TITLE
cwTexKai font shows a box for <br> and <textarea> on IE Edge

### ISSUE THREAD

**Issue by cheungkonghou** [google/fonts#423]
As subject.. it shows a box for br tag, while for textarea tag the box behaves like a placeholder (disappears when something typed into the textarea). 

http://jsbin.com/rekipehiwe/1/edit?html,css,output

**Comment by cheungkonghou** [comment]
On IOS Safari (9.x), part of the text is not shown occasionally.

**Comment by davelab6** [comment]
@cheungkonghou thanks for reporting. This sounds unusual. I suggest to contact the upstream font developer :)
