### ISSUE TITLE
Add Farsi fonts

### ISSUE THREAD

**Issue by bateni** [google/fonts#4233]
This is for multiple fonts. There has been many discussions on adding Farsi fonts here. Most of the discussion has revolved around Vazir, which has a weak point @davelab6 identified in google/fonts#1997 and google/fonts#2975: DejaVu Sans is not released as OFL but is the basis of Latin glyphs in Vazir. I believe we can/should fix this problem and include Vazir in google-fonts but before that, it might be easier to work on Sahel (by Saber Rastikerdar) as well as Estedad and Mikhad (by Amin Abedi).
- Sahel uses Open Sans (already in google-fonts) for Latin glyphs, while Estedad and Mikhak seem to have original designs for Latin glyphs.
- Both have reserved font names in their OFL license. I hope the developers will change this, so they can be integrated in google-fonts. Or is this something google-fonts team will do (by deriving a version and changing the name)?
- I took the liberty of running fontbakery on these fonts, and I think the reported failures are not difficult to resolve. I actually ran fontbakery on an Arabic font already in google-fonts and noticed many failures. Not sure if those checks were added after onboarding that font, or are they not very serious.

[estedad-report.txt](https://github.com/google/fonts/files/7919551/estedad-report.txt)
[sahel-report.txt](https://github.com/google/fonts/files/7919552/sahel-report.txt)
[mikhak-report.txt](https://github.com/google/fonts/files/7919553/mikhak-report.txt)

**Font Project Git Repo URL:**
https://github.com/rastikerdar/sahel-font
https://github.com/aminabedi68/Estedad
https://github.com/aminabedi68/Mikhak

- [ ] #2227
- [ ] #2228

**Super short description of the Font Family:**
Modern Farsi typefaces with clean license.

**Requirements:**

I understand that Google Fonts will publish only fonts that matches its requirements, and I can confirm the project meets them (by ticking the cases, or putting x between the square brackets in text mode):

- [x] The entire font project is licensed under the [OFL](https://scripts.sil.org/cms/scripts/page.php?site_id=nrsi&id=OFL)
- [ ] There is no "Reserved Font Name" mention in the OFL license
- [x] Family name is unique according to namecheck.fontdata.com
- [x] If the font targets latin based written languages, it supports at least [GF Latin Core glyphset](https://github.com/googlefonts/glyphsets/blob/main/Lib/glyphsets/encodings/GF%20Glyph%20Sets/GF-latin-core_unique-glyphs.nam)
- [x] I read and agree with the full [contributing requirements](https://github.com/google/fonts/blob/main/CONTRIBUTING.md)
- [ ] The repository respect the [upstream repo structure](https://github.com/googlefonts/gf-docs/tree/main/Spec#upstream-repo-structure)
- [ ] I will maintain the repository

**Comment by davelab6** [comment]
Minisites

* https://aminabedi68.github.io/Estedad/
* https://aminabedi68.github.io/Mikhak/

**Comment by Ahmadhosseinbor** [comment]
@yanone Please check the new version of Estedad and Mikhak fonts

**Comment by yanone** [comment]
Closing this because Estedad and Mikhak already existed previously in two separate issues:
https://github.com/google/fonts/issues/2228 (Estedad)
https://github.com/google/fonts/issues/2227 (Mikhak)
