### ISSUE TITLE
The lower end of Readex Pro wght axis is neither a multiple of 100, nor 1. Is this intentional?

### ISSUE THREAD

**Issue by cssobral2013** [google/fonts#4234]
As per Google Fonts' standard, it is recommended that wght axes' extremes be multiples of 100 (or be 1). But that's not the case with Readex Pro.

**Describe the bug**
The lower axis of Readex Pro is the non-standard value of 160

**To Reproduce**
- Go to https://fonts.google.com/specimen/Readex+Pro , then Variable Axes -> Weight
-  You will see that the lower end of wght axis is 160, as per screenshot below

**Expected behavior**
The wght axis lower end should be, in this case, 100 or 200

**Screenshots**
![Screenshot_20220122-225319_Brave](https://user-images.githubusercontent.com/19995437/150661528-dfe13ca7-cd99-4af8-bd7a-dbd18bffe8ec.jpg)

**Additional context**
Add any other context about the problem here (OS version, browser, printer…)

**Comment by RosaWagner** [comment]
The range of Readex Pro is a bit wider than the instances, nothing is wrong with that. The extreme master was design lighter than a Light instance but too thick to be a thin instance, that's it. GF Spec requires instances to be multiple of 100, not the extremes.

**Comment by davelab6** [comment]
I agree with @RosaWagner - it means there won't be a named instance of the lightest weight available on the Weight axis, but I am in favor of tempting users (and app developers) to use (and support) VFs to access "extra" features
