### ISSUE TITLE
Add Finlandica

### ISSUE THREAD

**Issue by tobestobs** [google/fonts#4241]
**Font Project Git Repo URL:**
https://github.com/HelsinkiTypeStudio/Finlandica

**Super short description of the Font Family:**
THE FONT FROM FINLAND
On a trajectory informed by Finnish natural and industrial history.
Its strong and compressed shapes embody a traditional virtue in Finnish culture: honest and resilient determination – “Sisu”. Ink traps like cuts from a blunt ax, makes the typeface reliable in small sizes and gives it character in large headlines.
http://finlandica.fi/

**Requirements:**

I understand that Google Fonts will publish only fonts that matches its requirements, and I can confirm the project meets them (by ticking the cases, or putting x between the square brackets in text mode):

- [x] The entire font project is licensed under the [OFL](https://scripts.sil.org/cms/scripts/page.php?site_id=nrsi&id=OFL)
- [x] There is no "Reserved Font Name" mention in the OFL license
- [x] Family name is unique according to namecheck.fontdata.com
- [x] If the font targets latin based written languages, it supports at least [GF Latin Core glyphset](https://github.com/googlefonts/glyphsets/blob/main/Lib/glyphsets/encodings/GF%20Glyph%20Sets/GF-latin-core_unique-glyphs.nam)
- [x] I read and agree with the full [contributing requirements](https://github.com/google/fonts/blob/main/CONTRIBUTING.md)
- [ ] The repository respect the [upstream repo structure](https://github.com/googlefonts/gf-docs/tree/main/Spec#upstream-repo-structure)
- [ ] I will maintain the repository

**Production notes**

- [x]  Repo structure
- [ ]  Fontbakery
- [ ]  Visual QA
- [ ]  Build
- [ ]  PR Upstream

**Comment by RosaWagner** [comment]
@tobestobs The fonts need to be fixed a bit (to match GF spec) before onbaording, are you already in contact with the designers? Otherwise I just send a message to their studio email to ask for the sources hoping they accept.

**Comment by tobestobs** [comment]
I haven't made contact yet. I came across it and asked Dave if we could onboard it. He suggest I file the request here to get more familiar with our process :)

**Comment by RosaWagner** [comment]
And you did well :) Okay then, I contact them directly by email to see if they want to share their sources so we see if we can make it happen.

**Comment by emmamarichal** [comment]
Hi @geekholm, I totally agree with you, you're right, I was a bit too generous on the medium and the difference is too big with the regular. Let's take your version! :)
