### ISSUE TITLE
Add [Uniol]

### ISSUE THREAD

**Issue by mitradranirban** [google/fonts#4260]
**Font Project Git Repo URL:**

https://github.com/mitradranirban/font-uniol/
**Super short description of the Font Family:**
Unicode compliant Olchiki font

**Requirements:**
none
I understand that Google Fonts will publish only fonts that matches its requirements, and I can confirm the project meets them (by ticking the cases, or putting x between the square brackets in text mode):

- [x] The entire font project is licensed under the [OFL](https://scripts.sil.org/cms/scripts/page.php?site_id=nrsi&id=OFL)
- [x] There is no "Reserved Font Name" mention in the OFL license
- [x] Family name is unique according to namecheck.fontdata.com
- [ ] If the font targets latin based written languages, it supports at least [GF Latin Core glyphset](https://github.com/googlefonts/glyphsets/blob/main/Lib/glyphsets/encodings/GF%20Glyph%20Sets/GF-latin-core_unique-glyphs.nam)
- [x] I read and agree with the full [contributing requirements](https://github.com/google/fonts/blob/main/CONTRIBUTING.md)
- [ ] The repository respect the [upstream repo structure](https://github.com/googlefonts/gf-docs/tree/main/Spec#upstream-repo-structure)
- [x] I will maintain the repository

**Comment by davelab6** [comment]
@mitradranirban thanks for proposing this. Your repo is looking good as a start but there'll be some additional work needed on this project to meet all the gf requirements :) I'm not working full time at the moment and I'll need to look closer at this, which may take some time, but I'm pleased to see you're using fontforge and working on olchiki! Keep going!! :)
