### ISSUE TITLE
Some cyrillic characters aren't displayed in Comfortaa Regular

### ISSUE THREAD

**Issue by J-Qs-archive** [google/fonts#4269]
**Describe the bug**
The cyrillic characters л, б aren't displayed in Fedora Linux 35. The upper case variants don't seem to be affected.

**To Reproduce**
Use Comfortaa Regular with mentioned cyrillic characters in Fedora 35.

**Expected behavior**
Correctly displayed characters

**Screenshots**
Comfortaa Regular:
![Screenshot-20220205115831-229x89](https://user-images.githubusercontent.com/85643516/152633811-dcbd058f-7031-4268-bfea-c8c818deab8c.png)
![Screenshot-20220205120002-1920x1080](https://user-images.githubusercontent.com/85643516/152633812-c6b86091-803a-4101-b2e9-0022ffda9619.png)

Arial:
![Screenshot-20220205121600-199x96](https://user-images.githubusercontent.com/85643516/152634242-e1fa4624-91b6-4875-b868-b299bc15896a.png)
![Screenshot-20220205120055-1920x1080](https://user-images.githubusercontent.com/85643516/152633821-2cf1dbbd-f6a0-4363-a4ee-e6f0ba26c8c2.png)

**Additional context**
Fedora 35 Workstation, Firefox 96.0, GNOME 41.3, LibreOffice Community 7.2.5.2.0+, Comfortaa RPM Version 3.101 from Fedora repository

**Comment by kenmcd** [comment]
This appears to have been fixed in the fonts in the repository
https://github.com/googlefonts/comfortaa
And in the fonts available on Google Fonts 
https://fonts.google.com/specimen/Comfortaa
The current version is 3.105.
You have version 3.101 and I can see this issue with those fonts.
So give the current fonts a try.
That should fix your issue.

**Comment by J-Qs-archive** [comment]
> This appears to have been fixed in the fonts in the repository https://github.com/googlefonts/comfortaa And in the fonts available on Google Fonts https://fonts.google.com/specimen/Comfortaa You have version 3.101 and I can see this issue with those fonts. The current version is 3.105 (and issue is gone). So give the current fonts a try. That should fix your issue.

Thank you. After installing from Google Fonts and restarting GNOME-Shell, all characters begin to be displayed
