### ISSUE TITLE
Issue with Noto Sans Tibetan

### ISSUE THREAD

**Issue by TsheRigs** [google/fonts#4271]
**Font name**
Noto Sans Tibetan

**Screenshots**
![Noto Sans Tibetan Issue](https://user-images.githubusercontent.com/99116487/152673742-ad1a9935-a3d4-48bb-a749-bdf166da317a.PNG)

**Comment by marekjez86** [comment]
@TsheRigs : thank you for the feedback; please also see https://github.com/googlefonts/noto-fonts/issues/1528 and https://github.com/googlefonts/noto-fonts/issues/2218 ; we'll try to fix these and more issues no later than April
