### ISSUE TITLE
Add support for 4 Jawi characters to Noto Nastaliq Urdu

### ISSUE THREAD

**Issue by EmpAhmadK** [google/fonts#4272]
Four (4) characters used in Jawi (Malay in Arabic script) are currently missing in the latest version of Noto Nastaliq Urdu. Although the font is specifically made for Urdu text, Jawi also often uses the Nastaliq script, thus it would be appropriate to add the support for all Jawi letters.

Jawi adds six (6) characters to the Arabic alphabet as listed below, in alphabetical order:

- Ca (چ ARABIC LETTER TCHEHEH; U+0687)
- **Nga (ڠ ARABIC LETTER AIN WITH THREE DOTS ABOVE; U+06A0)**
- Pa (ڤ ARABIC LETTER VEH; U+06A4)
- **Ga (ݢ ARABIC LETTER KEHEH WITH DOT ABOVE; U+0762)**
- **Va (ۏ ARABIC LETTER WAW WITH DOT ABOVE; U+06CF)**
- **Nya (ڽ ARABIC LETTER NOON WITH THREE DOTS ABOVE; U+06BD)**

At the current moment, only two (2) of the six characters are supported, whereas the other four, (Nga, Ga, Va, Nya), are still not supported.

**Comment by rsheeter** [comment]
Attn @marekjez86

**Comment by marekjez86** [comment]
we are tracking Noto issues in https://github.com/googlefonts/noto-fonts/issues . Created duplicate issue https://github.com/googlefonts/noto-fonts/issues/2244 because couldn't transfer this one

**Comment by RosaWagner** [comment]
thanks @marekjez86 for transferring the issue :) Feel free to close all the Noto Fonts related issues from this repo if they are already transferred/duplicated.
