### ISSUE TITLE
Add Chinese Font ‘JingNanFont’

### ISSUE THREAD

**Issue by TimeSheepY** [google/fonts#4292]
**Font Project Git Repo URL:**
https://github.com/Mike1490/JingNanYuanMo
https://github.com/Mike1490/JingNanMaiYuan

**Super short description of the Font Family:**
Bold black advertising font designed for headlines
**Requirements:**

I understand that Google Fonts will publish only fonts that matches its requirements, and I can confirm the project meets them (by ticking the cases, or putting x between the square brackets in text mode):

- [x] The entire font project is licensed under the [OFL](https://scripts.sil.org/cms/scripts/page.php?site_id=nrsi&id=OFL)
- [x] There is no "Reserved Font Name" mention in the OFL license
- [x] Family name is unique according to namecheck.fontdata.com
- [x] The font supports at least [GF Latin Core glyphset](https://github.com/googlefonts/glyphsets/blob/main/Lib/glyphsets/encodings/GF%20Glyph%20Sets/GF-latin-core_unique-glyphs.nam).
- [ ] The source files are available in the repo
- [x] I read and agree with the full [contributing requirements](https://github.com/google/fonts/blob/main/CONTRIBUTING.md)
- [ ] The repository respect the [upstream repo structure](https://github.com/googlefonts/gf-docs/tree/main/Spec#upstream-repo-structure)
- [x] I will maintain the repository

**Comment by RosaWagner** [comment]
We can't add fonts if the source files are not available.
Please re-read te contributing requirements and the upstream repo structure, and feel free to re-open this issue when all requirements are completed :)
