### ISSUE TITLE
Font zip does not work

### ISSUE THREAD

**Issue by hiddensea** [google/fonts#4297]
#This issue also works for requesting features. 

**Describe the issue**
I try to open/extract the main.zip but file explorer says it is invalid

**To Reproduce**
Download and open/ extract the fonts-main.zip file at /archive

**Expected behavior**
to be able to install the fonts

**Additional context**
Using Firefox beta, Windows 11 home (insider)

**Screenshots**
![When I try to open it](https://user-images.githubusercontent.com/86420177/153904069-6baffb27-56a7-463c-bfa1-e887b771abf6.png)

![when I try to extract it](https://user-images.githubusercontent.com/86420177/153904271-d02480c4-6036-4665-89c7-a2c345bdd2f3.png)

**Comment by RosaWagner** [comment]
Can't replicate with Edge / Windows 11. Check out your environment or try another browser :) Closing this since we can't do much on our side.
