### ISSUE TITLE
Still serving old version of the Lato font

### ISSUE THREAD

**Issue by vovkab** [google/fonts#4298]
**Describe the bug**
Even though Lato have been updated to 2.015 in https://github.com/google/fonts/pull/479, service still serving version 1.104.

**To Reproduce**
1. Navigate to https://fonts.google.com/specimen/Lato, 
2. Click "Download Family" 
3. Open any font and verify font version

**Expected behavior**
Should show version 2.015

**Actual behavior**
Downloaded fonts still using version 1.104

**Screenshot**
![Screenshot from 2022-02-14 21-59-31](https://user-images.githubusercontent.com/179741/154002182-d87fd55d-a123-4b92-bfaf-86a71c0e9185.png)

**Comment by RosaWagner** [comment]
The upgrade is already planned in #3978

**Comment by jhansche** [comment]
@RosaWagner that PR is for Lato v3. This issue is about v1 vs V2. I don't think v3 is the solution here?

**Comment by NadiaMubashar** [comment]
@vovkab this may help [#644 (comment)](https://github.com/google/fonts/issues/644#issuecomment-278818369)

It seems V2 caused too many issues so they rolled back. I'm awaiting V3
