### ISSUE TITLE
Add ZoomlaMengyas-A080 逐浪萌芽字

### ISSUE THREAD

**Issue by z01font** [google/fonts#4312]
Font Project Git Repo URL:
https://github.com/z01font/ZoomlaMengyas-A080

Super short description of the Font Family:
A good Chinese character library，by Jiangxi ZoomlaCMS Soft Co. LTD,Belong to the z01 family.
Chinese fonts follow GB2312 standard,English and Latin characters conform to GoogleFonts standards.

Requirements:

I understand that Google Fonts will publish only fonts that matches its requirements, and I can confirm the project meets them (by ticking the cases, or putting x between the square brackets in text mode):

- [x] The entire font project is licensed under the [OFL](https://scripts.sil.org/cms/scripts/page.php?site_id=nrsi&id=OFL)
- [x] There is no "Reserved Font Name" mention in the OFL license
- [x] Family name is unique according to namecheck.fontdata.com
- [x] The font supports at least [GF Latin Core glyphset](https://github.com/googlefonts/glyphsets/blob/main/Lib/glyphsets/encodings/GF%20Glyph%20Sets/GF-latin-core_unique-glyphs.nam).
- [x]  The source files are available in the repository
- [x] I read and agree with the full [contributing requirements](https://github.com/google/fonts/blob/main/CONTRIBUTING.md)
- [x] The repository respect the [upstream repo structure](https://github.com/googlefonts/gf-docs/tree/main/Spec#upstream-repo-structure)
- [x] I will maintain the repository

**Comment by RosaWagner** [comment]
> We updated the Repositories, requested re open this issue, thanks!

It looks like you took the sources from another font and add it to the repo. I am sorry your repo is not respecting the requirements and the font could also need more work. We can't accept this submission but we encourage you to continue improving your design.

**Comment by z01font** [comment]
> > We updated the Repositories, requested re open this issue, thanks!
> 
> It looks like you took the sources from another font and add it to the repo. I am sorry your repo is not respecting the requirements and the font could also need more work. We can't accept this submission but we encourage you to continue improving your design.

Dear, this is not from another font added to our works, but from the handwritten font of a magazine more than 100 years ago, digital creation and artistic innovation have been carried out to create a new open source font. This new open source font has been praised in China and hopes to be added to Google fonts.
We have complete copyright, no plagiarism, no decompilation, no infringement.

亲爱的，这不是从另一种字体添加到我们的作品中，而是从100多年前的一本杂志的手写字体，进行数字化创作、并进行了艺术化的创新，缔造了全新的开源字体，这款新的开源字体在中国受到很多表扬，希望能加到google fonts中。
我们拥有完整的著作权，没有抄袭，没有反编译，没有侵权。
