### ISSUE TITLE
Add Solitreo

### ISSUE THREAD

**Issue by eliheuer** [google/fonts#4325]
**Font Project Git Repo URL:** https://github.com/ladinoprojects/solitreo

**Super short description of the Font Family:**

This font was developed by the [Documenting Judeo-Spanish Project](https://documentingjudeospanish.com/).

Solitreo refers to the Hebrew-based cursive script once used by Sephardim; it is the cursive variety of the Rashi alphabet. Solitreo, or Soletreo, is derived from Galician/Portuguese, meaning ‘to spell.’ For many Sephardim, Solitreo was simply known as ganchos, meaning ‘hooks,’ due to the ligatures that form between letters. This style of writing is distinct from the Ashkenazi-based alphabet used for cursive Hebrew today, making documents in Solitreo undecipherable to the untrained eye. A similar style of writing can also be found in documents written in Judeo-Arabic.

**Requirements:**

I understand that Google Fonts will publish only fonts that matches its requirements, and I can confirm the project meets them (by ticking the cases, or putting x between the square brackets in text mode):

- [x] The entire font project is licensed under the [OFL](https://scripts.sil.org/cms/scripts/page.php?site_id=nrsi&id=OFL)
- [x] There is no "Reserved Font Name" mentioned in the OFL license
- [x] Family name is unique according to namecheck.fontdata.com
- [x] The font supports at least [GF Latin Core glyphset](https://github.com/googlefonts/glyphsets/blob/main/Lib/glyphsets/encodings/GF%20Glyph%20Sets/GF-latin-core_unique-glyphs.nam)
- [x] The repository respect the [upstream repo structure](https://github.com/googlefonts/gf-docs/tree/main/Spec#upstream-repo-structure)
- [x] The source files are available in the repository
- [x] I read, agree and comply with the full [contributing requirements](https://github.com/google/fonts/blob/main/CONTRIBUTING.md)
- [x] I am the author of the font or the author agreed to this submission
- [x] I will maintain the repository

**Comment by eliheuer** [comment]
I have been added as a collaborator with merge rights to the upstream repository, so I'm checking the last box about maintaining the repository.

Working on adding GF Latin Core now...

**Comment by eliheuer** [comment]
This project has no Fontbakery fails and is now ready for onboarding: https://github.com/ladinoprojects/solitreo

The people behind the [Documenting Judeo-Spanish Project](https://documentingjudeospanish.com/) are eager to get this done in time for the new school year. 

I will do as much onboarding work as possible with the public docs this Friday and next week. Please expect this in the onboarding pipeline next week. @RosaWagner @davelab6

**Comment by eliheuer** [comment]
Ok, I just make the PR to add this: https://github.com/google/fonts/pull/5280

**Comment by chrissimpkins** [comment]
This appears to be in production.  Are you waiting on a change to move through with the in dev label @RosaWagner?

**Comment by RosaWagner** [comment]
@chrissimpkins please look at the linked PR for status after merge
