### ISSUE TITLE
Roboto Serif error with utf-8

### ISSUE THREAD

**Issue by sonphung90** [google/fonts#4327]
Some styles not work as expected. Please help fix this. Thank you

![image](https://user-images.githubusercontent.com/13192845/154724193-32f0bd3a-edf3-43f1-baec-ca6da677f2ca.png)
![image](https://user-images.githubusercontent.com/13192845/154724268-5d9ac40f-23b4-4def-9a19-7ebce0cfb0e1.png)

**Comment by RosaWagner** [comment]
What happens if you refresh the page?

**Comment by rsheeter** [comment]
Steps to reproduce:

1. Open the Roboto Serif specimen (e.g. https://fonts.google.com/specimen/Roboto+Serif?subset=vietnamese)
  * no tofu
1. Add a vietnamese vowel, such as by copying from https://en.wikipedia.org/wiki/%C6%A0
  * tofu
  * <img width="170" alt="image" src="https://user-images.githubusercontent.com/6466432/154771498-74ff180a-4079-44fa-adab-b452b54f8cc0.png">
1. Refresh
  * no tofu

**Comment by davelab6** [comment]
It's a problem with the speed of the dynamic subsetter that serves the specimen page, not an issue with the font. We are already tracking this issue internally so I'm closing this issue, thanks for reporting it :)

**Comment by rsheeter** [comment]
Appears to be neither a font nor subsetter issue but a FE issue. Since it won't be fixed here I'm leaving this closed.
