### ISSUE TITLE
Roboto Serif needs better vertical metrics

### ISSUE THREAD

**Issue by RosaWagner** [google/fonts#4328]
typoAscender is way too low and cause clipping in some instances on the specimen page.
Also caps should be centered (cf https://twitter.com/evowizz/status/1494328326139174915?s=28)

<img width="252" alt="Capture d’écran 2022-02-18 à 18 08 29" src="https://user-images.githubusercontent.com/12222436/154729651-42527c95-4732-473b-9144-14728e7c1222.png">

<img width="352" alt="Capture d’écran 2022-02-18 à 18 11 31" src="https://user-images.githubusercontent.com/12222436/154730064-c918c386-0426-4fd9-94a8-f1893d1dbbf2.png">

**Comment by m4rc1e** [comment]
Vertical metrics are based on Roboto, https://github.com/CommercialType/RobotoSerif/issues/3#issuecomment-623671347
