### ISSUE TITLE
Neuton font 300 weight displays colon as middle dot

### ISSUE THREAD

**Issue by nickcernis** [google/fonts#433]
Typing a `:` character results in a middle dot with Neuton's 300 weight:

<img width="809" alt="neuton_-_google_fonts" src="https://cloud.githubusercontent.com/assets/647669/19959083/db8ad152-a19b-11e6-85c7-8355ed5dce17.png">

I found a report of this in a repo at https://github.com/vladpopa33/googlefontdirectory/issues/215 dating back to 2013 but couldn't see anything in the official repo here.

**Comment by davelab6** [comment]
@nickcernis thanks for reporting!

Will be fixed when PR #440 is pushed to production :)

![screen shot 2016-12-06 at 13 02 44](https://cloud.githubusercontent.com/assets/261579/20937291/4fc21c06-bbb4-11e6-8613-f6174a089ae3.png)

**Comment by davelab6** [comment]
Confirmed fixed :) 
    
<img width="279" alt="screen shot 2016-12-12 at 14 51 57" src="https://cloud.githubusercontent.com/assets/261579/21114273/8cb894ee-c07a-11e6-8cd0-ff9cee051c73.png">

**Comment by m4rc1e** [comment]
Closing.

Can confirm
![screen shot 2017-06-14 at 12 05 03](https://user-images.githubusercontent.com/7525512/27129319-b8981a70-50f9-11e7-92a1-bd181291c865.png)

http://jsbin.com/harehenowa/edit?html,output
