### ISSUE TITLE
Ability to sort fonts by license type

### ISSUE THREAD

**Issue by aecarvalho** [google/fonts#4330]
If possible might I request the option to sort fonts by license type, since OFL fonts do not need to be attributed to whereas UFL and Apache licensed fonts need to have a copy of the license added to the work or derivative work whenever the font is redistributed.

**Comment by ritikBhandari** [comment]
Hi,
I would like to work on this issue!

**Comment by davelab6** [comment]
@aecarvalho I'm curious why you believe that about the UFL. Since you are here on Github, the best thing to do will be to clone this repo and grep the METADATA files (or just go by the folder structure :) This would be an 'advanced' user feature in fonts.google.com and so far down the list of priority features for advanced users, that it won't be implemented. 

@ritikBhandari Sadly we aren't set up to accept such a contribution at this time.

**Comment by aecarvalho** [comment]
@davelab6 The preamble of UFL states that:

> Permission is hereby granted, free of charge, to any person obtaining a copy of the Font Software, to propagate the Font Software, subject to the below conditions:

> 1. Each copy of the Font Software must contain the above copyright notice and this licence. These can be included either as stand-alone text files, human-readable headers or in the appropriate machine-readable metadata fields within text or binary files as long as those fields can be easily viewed by the user.

So supposing I create an EPUB book, it does involve propagation of the font as the font gets embedded and therefore does require the license to be attached with the font, if I'm not wrong.

Anyway thanks for your response, I mean after all license is a big part of any font because it is someone's intellectual property. I don't see it being so "advanced" as to be on the bottom of a list of advanced features more basic than the need to understand  and differentiate font license itself. There's even the section to sort by "most popular" probably because someone thought popular = better I guess.

Also sincerely thanking @ritikBhandari for actually wanting to try.

**Comment by davelab6** [comment]
Equally the OFL says,

> 2) Original or Modified Versions of the Font Software may be bundled,
> redistributed and/or sold with any software, provided that each copy
> contains the above copyright notice and this license. These can be
> included either as stand-alone text files, human-readable headers or
> in the appropriate machine-readable metadata fields within text or
> binary files as long as those fields can be easily viewed by the user.

So I'm unclear why you draw a distinction between the two :)

**Comment by aecarvalho** [comment]
The OFL clearly mentions the words "may be bundled,
redistributed and/or sold with any **software**".
So as long as the end product is not a software, it is permissible to not attach the license with the font, and nowhere is an e-book actually defined as a software, it is only defined as an electronic publication or format of a book. You may need a software to read or create an e-book but the e-book itself isn't considered a software.

Whereas the UFL states each copy of the font regardless of the end product needs a copy of the license.

So obviously the distinction is clear.

**Comment by tiroj** [comment]
> So as long as the end product is not a software, it is permissible to not attach the license with the font

A more reasonable reading of the wording of that clause would be that an OFL-licensed font can _only_ be bundled with software, as no permission is explicitly granted for bundling except with software. I don’t think that is the intent of the license, but it makes way more sense than the logcal leap that non-software products do not need to preserve the copyright notice and license.

**Comment by aecarvalho** [comment]
Or we could just read what literally is the intent of the OFL, as stated in the preamble;

> PREAMBLE
The goals of the Open Font License (OFL) are to stimulate worldwide development of collaborative font projects, to support the font creation efforts of academic and linguistic communities, and to provide a free and open framework in which fonts may be shared and improved in partnership
with others.

> The OFL allows the licensed fonts to be used, studied, modified and redistributed freely as long as they are not sold by themselves. The fonts, including any derivative works, can be bundled, embedded, redistributed and/or sold with any software provided that any reserved names are not used by derivative works. The fonts and derivatives, however, cannot be released under any other type of license. The
requirement for fonts to remain under this license does not apply to any **document** created using the fonts or their derivatives.

That means the OFL officially acknowledges that any "document," which can also include books or electronic written matter like e-books as defined by the OALD, doesn't require the license.

The same is also reiterated in the 5th clause of the Conditions list. Better to read and understand than to speculate I'm sure.

**Comment by tiroj** [comment]
I still think you are making a reach. The license does not explicitly state that the copyright and license can be dispensed with when bundled with a document, it only states that it must be retained when bundled with software. You can’t infer an exclusion from an inclusion. Further, ‘software’ is not defined in the license, so you are necessarily applying an external definition, which may be right, which may or may not correspond to what SIL intended by ‘software’.

Clause 5 only means that documents using the font are not subject to the license. It doesn’t mean that if the font is bundled with the document it does not need to retain the copyright and license info.

Perhaps what we can agree on is that OFL is not a very well written license.

**Comment by tiroj** [comment]
We’re perhaps talking at cross-purposes, and the whole question of whether and how the Font Software license is retained when bundled with an ebook or other document is sort of moot in terms of the subject of this issue. For the record, I have also wanted to be able to sort by license type on Google Fonts, but it seems all licenses on GF are migrating to OFL, and in any case do not necessarily capture alternative license options that may exist for the fonts elsewhere, or for other versions of the fonts elsewhere. So this may simply not be a useful feature.

I also think we’re perhaps talking at cross-purposes about what it means for the license to be retained when bundling with a document. The OFL reads that the copyright and license, when bundled with software,

> can be included either as stand-alone text files, human-readable headers or in the appropriate machine-readable metadata fields within text or binary files as long as those fields can be easily viewed by the user.

Personally, I would consider the copyright string and license description and link fields in the font name table to be ‘appropriate machine-readable metadata ... within ... binary files’. So you are talking about a requirement to attach the license to the document, and I am talking about preserving the license that is already associated with the font.

‘Easily viewed by the user’ is open to interpretation, I suppose.

**Comment by aecarvalho** [comment]
I don't see how any of your points correlate to this issue. I can assure you that as an end user wanting to use fonts in an e-book or a document, the need does arise for a tool to sort fonts according to their license type, considering their conditions and terms. That also includes how the font will be placed in the said document or e-book, hence the issue was posted. Not all formats have a metadata folder.

The licenses associated with all Google fonts are supplied as TXT files, which cannot be incorporated into a PDF or AZW3 for example, or at the very least, I have no knowledge of doing so. If and when Google Fonts shift to OFL entirely, I shall be thankful that the issue was prematurely closed.

You may keep extending your arguments into various aspects of the OFL but then again as I said, unless you have legal grounds to explicitly deny or disallow OFL licensed fonts from being embedded into documents without having to add the license into the said document, or can point to any clause which specifically mentions so, it's merely speculation and conjecture.
