### ISSUE TITLE
Inclusion of contrast axis 

### ISSUE THREAD

**Issue by yanone** [google/fonts#4355]
I'm proposing the inclusion of a "contrast" axis (CNTR) into the axis registry. 
https://github.com/tallchai/akshar-type has one, that I’m currently onboarding.

```
tag: "CNTR"
display_name: "Contrast"
min_value: 0.0
default_value: 0.0
max_value: 100.0
precision: 1
fallback {
  name: "Low"
  value: 0.0
}
fallback {
  name: "High"
  value: 100.0
}
description:
  "Stroke contrast describes the stroke width difference"
  " between the thick and thin parts of a pen stroke."
  " Traditionally, a Redis pen nib would yield a low contrast stroke"
  " (monolinear) while a broad nib or pointed nib pen would"
  " yield a high contrast stroke."
```

<img width="820" alt="Bildschirmfoto 2022-03-09 um 17 02 53" src="https://user-images.githubusercontent.com/175386/157480286-492da512-fefa-46fc-9d5d-1917c157c37e.png">
<img width="819" alt="Bildschirmfoto 2022-03-09 um 17 03 02" src="https://user-images.githubusercontent.com/175386/157480317-464379f8-8d0a-4237-af19-54a66bef1308.png">

cc @m4rc1e @davelab6 @rsheeter

**Comment by felipesanches** [comment]
Can I transfer this issue to the new **googlefonts/axisregistry** repo?

https://github.com/googlefonts/axisregistry

**Comment by yanone** [comment]
Of course

**Comment by felipesanches** [comment]
> Can I transfer this issue to the new googlefonts/axisregistry repo?

hmmm... apparently I lack the admin rights here to do so :-P
@davelab6, can you do it for us, please?

**Comment by twardoch** [comment]
I think the registered range should be from -100 to 100: 

min_value: -100.0
default_value: 0.0
max_value: 100.0

The universalized meaning should be something like the "dominance of the thick parts over the thin parts, expressed in percent" or the "difference between 100% and the division between the thickness of the thin parts and the thickness of the thick parts". For example if the thin parts are 30 units and the thick parts are 230 units, the division yields 13% so the CONT value should be 100%–13% = 87.

Positive values should be used if the contrast follows the traditional contrast axis of the dominant writing system, and negative values should be used if the contrast follows the reversed contrast axis of the dominant writing system.

So 0 should stand for "no contrast", 100 should stand for "thin strokes are invisible and the contrast axis is traditional", and -100 should stand for "thin strokes are invisible and the contrast axis is reversed". This way, some design could go from fully reversed contrast to fully traditional contrast.

**Comment by davelab6** [comment]
> > Can I transfer this issue to the new googlefonts/axisregistry repo?
> 
> hmmm... apparently I lack the admin rights here to do so :-P @davelab6, can you do it for us, please?

You can only transfer issues within an org, and this repo is on the /google org, so, no, alas I can not.

To the main point, I will respond on https://github.com/googlefonts/axisregistry/issues/4

**Comment by tiroj** [comment]
> The universalized meaning should be something like the "dominance of the thick parts over the thin parts, expressed in percent" or the "difference between 100% and the division between the thickness of the thin parts and the thickness of the thick parts". For example if the thin parts are 30 units and the thick parts are 230 units, the division yields 13% so the CONT value should be 100%–13% = 87.

I’m not sure that math would make a lot of sense to a font maker or user. I think I would favour the axis scale expressed as the percentage relationship of thin stroke to thick stroke. So in your example the value would be 13, and the contrast approaches monolinear by increasing the thickness of the thin strokes until the value reaches 100. I think most font makers will think of increasing contrast in terms of making some parts thinner, rather than in terms of making some parts thicker, and the relationship between the value and the glyph appearance is easier if thinner = smaller value.

**Comment by felipesanches** [comment]
@tiroj (and anybody else interested in this issue), please post followup comments at https://github.com/googlefonts/axisregistry/issues/3
