### ISSUE TITLE
Add DynaPuff

### ISSUE THREAD

**Issue by davelab6** [google/fonts#4357]
**Font Project Git Repo URL:**

https://github.com/googlefonts/dynapuff

**Super short description of the Font Family:**

A fun display variable font for sticker art.

<img width="1299" alt="Capture d’écran 2022-06-01 à 16 21 37" src="https://user-images.githubusercontent.com/12222436/171427318-de795126-b988-4720-9a03-fe494b427158.png">

**Comment by emmamarichal** [comment]
@RosaWagner 
A lot of Glyphs are missing (but most of accents, easy to generate)

<img width="475" alt="Capture d’écran 2022-04-13 à 14 32 03" src="https://user-images.githubusercontent.com/64773544/163180608-ab119eae-41bb-4a87-b9f8-c74d0e102f26.png">

**Comment by davelab6** [comment]
I suggest you go ahead and add them and let @Tosche know when ready to review :)

**Comment by Tosche** [comment]
Sorry about the discrepancy. The Google Latin Core list that I've got was somehow much smaller (more like Latin-1 equivalent).

**Comment by emmamarichal** [comment]
@Tosche No problem, it's my fault, I forgot to mention that I had taken the new list. I'll add what's missing :)

**Comment by davelab6** [comment]
Right, we just updated it :)

**Comment by davelab6** [comment]
Yes this looks fine to me :) @Tosche please could you confirm "what each stylistic set is for" or a name directly? :)

**Comment by Tosche** [comment]
I think the weights look fine too. The stylistic sets are just sets used for pseudo-randomisation without distinct purpose for each set. Just calling them by numbers make the most sense to me.
