### ISSUE TITLE
Add Abyssinica (SIL)

### ISSUE THREAD

**Issue by emmamarichal** [google/fonts#4369]
**Font Project Git Repo URL:**
https://github.com/silnrsi/font-abyssinica

The Abyssinica SIL font supports the Ethiopic script.

**Fonts**
[AbyssinicaSIL-Regular.ttf.zip](https://github.com/google/fonts/files/8520368/AbyssinicaSIL-Regular.ttf.zip)

![Desktop_OS_X_High_Sierra_safari_11 1_](https://user-images.githubusercontent.com/64773544/164200712-d1f5f43b-4e30-4c7c-ac30-90819bf2c509.png)

**Comment by emmamarichal** [comment]
We should discuss these fails with SIL:

🔥 FAIL: Name table entries should not contain line-breaks. ([com.google.fonts/check/name/line_breaks](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/googlefonts.html#com.google.fonts/check/name/line_breaks))
🔥 FAIL: OS/2.fsSelection bit 7 (USE_TYPO_METRICS) is set in all fonts. ([com.google.fonts/check/os2/use_typo_metrics](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/googlefonts.html#com.google.fonts/check/os2/use_typo_metrics))
🔥 FAIL: Ensure dotted circle glyph is present and can attach marks. ([com.google.fonts/check/dotted_circle](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/universal.html#com.google.fonts/check/dotted_circle)[](https://github.com/emmamarichal)[](https://github.com/emmamarichal)[](https://github.com/emmamarichal)[](https://github.com/emmamarichal)[](https://github.com/emmamarichal)[](https://github.com/emmamarichal)[](https://docs.github.com/github/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax)[](https://github.com/emmamarichal)[](https://github.com/))

**Comment by jvgaultney** [comment]
Our understanding is that GF will hot fix bit 7 and ignore the missing dotted circle for now. We will permanently fix those issues in the next release.

**Comment by RosaWagner** [comment]
@emmamarichal From the look in sandbox, we should remove the the latin-ext subset from metadata.pb. Clearly the font doesn't support it. 

<img width="1090" alt="Capture d’écran 2022-05-18 à 09 39 20" src="https://user-images.githubusercontent.com/12222436/168985560-6b32d2e1-3c3a-42b5-ac9e-881595d412e5.png">

For the glyphs that look heavier, I think it is meant to go with the Ethiopic subset, but this one is not appearing in the sample glyphs section, which is a concern I will raise somewhere (although the subset is enabled and works). The choice of punctuation for the right script largely rely on substitution features, some of which may be subsetted by the API, making the font useless in some context. I wonder if that's maybe why the font was blocked in sandbox for ages before we upgraded it. 

Anyway re-opening this until further instructions.

**Comment by jvgaultney** [comment]
The heavier punctuation marks are ones specifically intended for use with Ethiopic text. Lighter Latin-style versions are available through a user-selectable feature `cv01`. See https://software.sil.org/abyssinica/support/smart-font-features/

The font does not support extended Latin, so the c+diacritic combps would not be expected to work.
