### ISSUE TITLE
How to convert svg icons folder to eot, woff2... font file?

### ISSUE THREAD

**Issue by mahdi1dev** [google/fonts#4381]
Hello
I am new to creating fonts. Can i know how to convert svg icons folder to eot, woff2, woff, ttf, and svg font file like Material Icons.
Or create woff2 font icons file in an easy way.

**Comment by rsheeter** [comment]
I would try https://github.com/googlefonts/nanoemoji to produce a font from a set of svgs and then https://github.com/fonttools/fonttools to save a woff2 version. Off the top of my head I can't think of anyone who supports woff but not woff2 so then you'd just have to find an eot converter if you care about old versions of IE.
