### ISSUE TITLE
Upgrade Radio Canada with expanded glyphset

### ISSUE THREAD

**Issue by RosaWagner** [google/fonts#4384]
**Font Project Git Repo URL:**
https://github.com/cbcrc/radiocanadafonts

**Super short description of the upgrade:**
Addition of 1 script

**Comment by RosaWagner** [comment]
@Fonthausen Please update us about the progress in this issue :)

**Comment by Fonthausen** [comment]
– Last corrections were made.
– Currently preparing the Roman for Variable font format.
– Next steps are kerning and adding the Italic (slanted) axes.

**Comment by RosaWagner** [comment]
Awesome, thanks! Do you think it would be finished in quarter 4 or shall I change the expected deadline for Q1 2023? (currently planning on next quarter workload)

**Comment by chrissimpkins** [comment]
This is now complete https://github.com/cbcrc/radiocanadafonts/pull/86

and in the main branch of the upstream repository.  The Q1 2023 milestone for this update is appropriate.

**Comment by RosaWagner** [comment]
@Fonthausen I don't understand the sources, can we schedule a call? or if you can document here how the fonts are built and why the sources are not gather in 2 files (R/I), it would be of great help

**Comment by Fonthausen** [comment]
@RosaWagner Sure, we can schedule a call !

**Comment by chrissimpkins** [comment]
Upstream PR made.  May require another round of review.  Rosalie looking into it.
