### ISSUE TITLE
Update Impallari Type's fonts (summary)

### ISSUE THREAD

**Issue by RosaWagner** [google/fonts#4437]
Many of the type designers who have developed Latin font families have continued to work on them, and reviewing their collections and bringing them up to date would be good. 

#### Done
- [x] #329 
- [x] #3953
- [x] https://github.com/google/fonts/pull/2721
- [x] https://github.com/google/fonts/pull/2571
- [x] https://github.com/google/fonts/pull/3821
- [x] https://github.com/google/fonts/pull/3788
- [x] https://github.com/google/fonts/pull/2669
- [x] https://github.com/google/fonts/pull/2492

#### In progress / planned
- [ ] #4390 
- [ ] https://github.com/google/fonts/pull/1473 Amiko: maybe can be improved

####  / To plan
- [ ] Raleway Dots / No upgrade available
- [ ] Libre Baskerville / only 20 glyphs more in the last version but could be upgraded
- [ ] Libre Caslon Text / No upgrade available
- [ ] Libre Caslon Display / No upgrade available
- [ ] Cabin Condensed
- [ ] Cabin Sketch
- [ ] Lobster
- [ ] Caveat Brush
- [ ] Lobster Two
- [ ] Kaushan Script
- [ ] Quattrocento
- [ ] Quattrocento Sans
- [ ] Racing Sans One
- [ ] Petit Formal Script
- [ ] Ranchers
- [ ] Life Savers
- [ ] Cantora One
- [ ] New Rocker
- [ ] Milonga
- [ ] Miltonian Tattoo
- [ ] Miltonian

**Comment by chrissimpkins** [comment]
Closing.  We will open separate per family issue threads for any outstanding work here
