### ISSUE TITLE
Update Eduardo Tunni's Fonts (summary)

### ISSUE THREAD

**Issue by RosaWagner** [google/fonts#4439]
Many of the type designers who have developed Latin font families have continued to work on them, and reviewing their collections and bringing them up to date would be good. 

### Eduardo Tunni

**Done**
- [x] [Lemonada](https://github.com/google/fonts/pull/5593)
- [x] #3873
- [x] #551 : last upgrade 7 years ago
- [x] #4137 
- [x] #4119 
- [x] #4133 
- [x] #4440
- [x] #5803
- [x] #5802
- [x] #5804
- [x] #4138 
- [x] #5835
- [x] #5836
- [x] #5837
- [x] #5881
- [x] #5886
- [x] #5882
- [x] #5888
- [x] #5887
- [x] #5884
- [x] #5885
- [x] #5883
- [x] #5889
- [x] #5938

**In progress / To do**
- [ ] #4139 
- [ ] #4134 
- [ ] #5834
- [ ] #4366
- [ ] #4362 
- [x] #5939
- [ ] Changa One : **to de-list?**
- [ ] Merienda One: **to de-list?**

**To plan**
- [ ] Glegoo: devanagari + no recent sources
- [ ] Average Sans: no repo
- [ ] Croissant One: no repo
- [ ] Combo: no repo
- [ ] Surrana: https://github.com/etunni/suranna/issues/1 : no recent sources

**Comment by chrissimpkins** [comment]
Closing.  Let's open per family issues for any outstanding onboarding work here.
