### ISSUE TITLE
Add Plusko Font

### ISSUE THREAD

**Issue by KarenFarias2022** [google/fonts#4449]
**Font Project Git Repo URL:**
https://github.com/KarenFarias2022/plusko

**Super short description of the Font Family:**
Medium

**Requirements:**

I understand that Google Fonts will publish only fonts that matches its requirements, and I can confirm the project meets them (by ticking the cases, or putting x between the square brackets in text mode):

- [ ] The entire font project is licensed under the [OFL](https://scripts.sil.org/cms/scripts/page.php?site_id=nrsi&id=OFL)
- [ ] There is no "Reserved Font Name" mention in the OFL license
- [x] Family name is unique according to namecheck.fontdata.com
- [ ] The font supports at least [GF Latin Core glyphset](https://github.com/googlefonts/glyphsets/blob/main/Lib/glyphsets/encodings/GF%20Glyph%20Sets/GF-latin-core_unique-glyphs.nam)
- [ ] The repository respect the [upstream repo structure](https://github.com/googlefonts/gf-docs/tree/main/Spec#upstream-repo-structure)
- [ ] The source files are available in the repository
- [ ] I read, agree and comply with the full [contributing requirements](https://github.com/google/fonts/blob/main/CONTRIBUTING.md)
- [ ] I am the author of the font or the author agreed to this submission
- [ ] I will maintain the repository

**Comment by RosaWagner** [comment]
Hi @KarenFarias2022, thanks for your submission. Unfortunately the family doesn't match Google Fonts requirements, and therefore we can't onboard it. These are the most important ones: https://googlefonts.github.io/gf-guide/onboarding.html. Fell free to re-submit when you feel you achieve to match them :)
