### ISSUE TITLE
Add Shantell Sans

### ISSUE THREAD

**Issue by davelab6** [google/fonts#4465]
@thundernixon has a new VF project, expected for onboarding in early Q3

**Font Project Git Repo URL:**
 https://github.com/arrowtype/shantell-sans

**Comment by arrowtype** [comment]
Thank you, Dave! This one will be exciting to launch.

**Comment by chrissimpkins** [comment]
Requires three new axis registrations.

https://github.com/googlefonts/axisregistry/pull/62
https://github.com/googlefonts/axisregistry/pull/64
https://github.com/googlefonts/axisregistry/pull/63

**Comment by Whizboy-Arnold** [comment]
this font has issues on windows, adobe illustrator could not load the font, and windows could not uninstall it. had to go through a huge problem spanning days restoring my system back, editing regex, deleting files manually, safemode, deleting temp files and caches, for the problem to disappear.

**Comment by Whizboy-Arnold** [comment]
@google-admin  i would prefer if fonts that have not been fully tested are put in a separate folder.

**Comment by Whizboy-Arnold** [comment]
@davelab6 did you fully test this font on windows, that it installs loads and also to uninstall. It froze my system up.

**Comment by davelab6** [comment]
> issues on windows

Please open a new issue about that, either on this repo or the upstream ArrowType one, since this issue is scoped to adding the family and is closed. 

It is important to note the exact version of Windows you tested on, and describe the problems (ideally with screenshots) such that someone else can follow you step by step to reproduce the issue.

> adobe illustrator could not load the font

Please note the exact version of apps you find that have problems, and if possible, links to where you reported the problem to the app developer.

> windows could not uninstall it

Please describe this in more detail on that new issue :)
