### ISSUE TITLE
Droid Sans Missing From fonts.google.com

### ISSUE THREAD

**Issue by hifocus** [google/fonts#4469]
**Describe the bug**
The Droid Sans font is no longer listed on fonts.google.com, despite it's still callable from [fonts.googleapis.com](https://fonts.googleapis.com/css2?family=Droid+Sans)

**To Reproduce**
- https://fonts.google.com/?query=droid
- https://www.google.com/search?q=droid+sans

**Expected behavior**
Droid Sans listed on fonts.google.com so that it can be explored

**Screenshots**
![image](https://user-images.githubusercontent.com/30528433/161448126-01278a85-46a7-4237-a9c6-3a3db5e65fb2.png)

**Comment by fitojb** [comment]
Just use Noto Sans Display. It’s the same design with bug fixes and a much wider character set. Like, why would you need Droid Sans for specifically?

**Comment by hifocus** [comment]
> Just use Noto Sans Display. It’s the same design with bug fixes and a much wider character and weight set. Like, why would you need Droid Sans for specifically?
> 
> Deprecated fonts can be hidden from the catalog but remain in the API to avoid breaking websites.

I simply didn't know the reason of the unlist of Droid Sans. Is Noto Sans Display officially replacing Droid Sans?

I don't mean to create hassle just asking.

**Comment by fitojb** [comment]
Yes, no worries, first it was succeeded by Open Sans and then by the Noto project.

**Comment by twardoch** [comment]
Ps. Droid Serif, Droid Arabic Naskh and Droid Arabic Kufi are also succeeded by the corresponding Noto fonts, which are basically the same designs but with improvements.

**Comment by twardoch** [comment]
Ps2. Noto Sans is the direct replacement for Droid Sans. Noto Sans Display is a variant for larger font sizes.

**Comment by hifocus** [comment]
> Ps2. Noto Sans is the direct replacement for Droid Sans. Noto Sans Display is a variant for larger font sizes.

Thanks a bunch!

**Comment by kuscholdMNG** [comment]
Droid Sans and Noto Sans are not the same font. The characters in Noto Sans Regular are wider than those in Droid Sans Regular

**Comment by kuscholdMNG** [comment]
Droid Serif and Noto Serif are the same

**Comment by ferdnyc** [comment]
@kuscholdMNG 
> Droid Sans and Noto Sans are not the same font. The characters in Noto Sans Regular are wider than those in Droid Sans Regular

That's true, but (despite @twardoch saying that it's a larger-size variant) Noto Sans Display has narrower glyphs than Noto Sans, and appears to be roughly equivalent to Droid Sans. Quirks and all.<sup>1</sup>

![image](https://user-images.githubusercontent.com/538020/206681696-d4fbadee-d217-4f6f-b9a5-454aa8d43854.png)

### Notes
1. Quirks like Noto Sans having the same exclamation-points-that-reduce-to-vertical-lines-at-small-point-sizes issue that's always bothered me about Droid Sans. To the point where I took it into Fontforge and chopped the bottom third off the vertical portion of the glyph, to better distance it from the dot below. Hence, the first of those four samples above.
    
    Because, of those four 20-point lines of text, which do you think will still be clearly readable at 8 or 9 points, and which will turn into "Droid Sansl"? ...But I digress.
