### ISSUE TITLE
Provide variable subsets for Source Sans Pro

### ISSUE THREAD

**Issue by doompadee** [google/fonts#4488]
**Describe the feature request**
It would be great if variable subsets could be added to Source Sans Pro. Upstream already provides a variable variant version. Ideally a weightonly variant should be added as well, as the full version is quite big.

**Comment by RosaWagner** [comment]
A varaible font of Source Sans Pro has been already onboarded under the name Source Sans 3: https://fonts.google.com/specimen/Source+Sans+3
