### ISSUE TITLE
There is no marketplace icon on the Google Material Design. I need it, can you guys please create it? Thank you!!

### ISSUE THREAD

**Issue by ruddhisundar** [google/fonts#4499]
#This issue also works for requesting features. 

**Describe the issue**
A clear and concise description of what the issue is.

**To Reproduce**
Steps to reproduce the behavior.

**Expected behavior**

**Additional context**
Add any other context about the problem here (OS version, browser, printer…)

**Screenshots**

**Comment by RosaWagner** [comment]
This repo is for font families of google fonts, please try this repo for stuff related to icons: https://github.com/google/material-design-icons
