### ISSUE TITLE
Add Ezra (SIL)

### ISSUE THREAD

**Issue by emmamarichal** [google/fonts#4513]
**Font Project Git Repo URL:**
The font is in the [list](https://github.com/google/fonts/issues/4354#event-6210937441) of fonts to onboard but there is no repo created yet.

**Comment by jvgaultney** [comment]
This project cannot be easily prepared for GF for two reasons: The licensing is currently a mix of OFL and MIT and it would take special negotiations to unify it as OFL-only. It is also a complex project that is not in our current UFO-based workflow, so sources are not easily buildable. It would take considerable work to convert the project and we're not sure we can invest the effort required. I suggest that this issue be closed.
