### ISSUE TITLE
Add Nuosu (SIL)

### ISSUE THREAD

**Issue by emmamarichal** [google/fonts#4516]
**Font Project Git Repo URL:**
https://github.com/silnrsi/font-nuosu

**Super short description of the Font Family:**
The Nuosu SIL font supports writing systems that use the Yi script.

**Fonts**
[NuosuSIL-Regular.ttf.zip](https://github.com/google/fonts/files/8520824/NuosuSIL-Regular.ttf.zip)
![Desktop_OS_X_High_Sierra_safari_11 1_](https://user-images.githubusercontent.com/64773544/164215400-86b24569-34c4-4046-9baf-505b3539790c.png)
![Desktop_Windows_10_chrome_71 0_](https://user-images.githubusercontent.com/64773544/164215410-ab208132-d335-49af-b34a-5497e5f70d23.png)
![Desktop_Windows_10_edge_18 0_](https://user-images.githubusercontent.com/64773544/164215417-33ea8587-2dd4-4e1c-bb54-effd2c1330d4.png)

**Comment by emmamarichal** [comment]
## Fontbakery report

Fontbakery version: 0.8.9.dev3+gcf7de707

<details><summary><b>[1] Family checks</b></summary><div><details><summary>ℹ <b>INFO:</b> Check axis ordering on the STAT table.  (<a href="https://font-bakery.readthedocs.io/en/stable/fontbakery/profiles/googlefonts.html#com.google.fonts/check/STAT/axis_order">com.google.fonts/check/STAT/axis_order</a>)</summary><div>


* ℹ **INFO** From a total of 1 font files, 1 of them (100.00%) lack a STAT table.

	And these are the most common STAT axis orderings:
	 [code: summary]
</div></details><br></div></details><details><summary><b>[25] NuosuSIL-Regular.ttf</b></summary><div><details><summary>🔥 <b>FAIL:</b> Check license file has good copyright string. (<a href="https://font-bakery.readthedocs.io/en/stable/fontbakery/profiles/googlefonts.html#com.google.fonts/check/license/OFL_copyright">com.google.fonts/check/license/OFL_copyright</a>)</summary><div>


* 🔥 **FAIL** First line in license file does not match expected format: "copyright (c) 1999-2020 sil international (http://www.sil.org)"
</div></details><details><summary>🔥 <b>FAIL:</b> Check OFL body text is correct. (<a href="https://font-bakery.readthedocs.io/en/stable/fontbakery/profiles/googlefonts.html#com.google.fonts/check/license/OFL_body_text">com.google.fonts/check/license/OFL_body_text</a>)</summary><div>


* 🔥 **FAIL** The OFL.txt body text is incorrect. Please use https://github.com/googlefonts/Unified-Font-Repository/blob/main/OFL.txt as a template. You should only modify the first line. [code: incorrect-ofl-body-text]
</div></details><details><summary>🔥 <b>FAIL:</b> Check copyright namerecords match license file. (<a href="https://font-bakery.readthedocs.io/en/stable/fontbakery/profiles/googlefonts.html#com.google.fonts/check/name/license">com.google.fonts/check/name/license</a>)</summary><div>


* 🔥 **FAIL** License file OFL.txt exists but NameID 13 (LICENSE DESCRIPTION) value on platform 3 (WINDOWS) is not specified for that. Value was: "Copyright (c) 1999-2020 SIL International (https://www.sil.org/) with Reserved Font Names "Nuosu" and "SIL".

This Font Software is licensed under the SIL Open Font License, Version 1.1. This license is copied below, and is also available with a FAQ at: https://scripts.sil.org/OFL


-----------------------------------------------------------
SIL OPEN FONT LICENSE Version 1.1 - 26 February 2007
-----------------------------------------------------------

PREAMBLE
The goals of the Open Font License (OFL) are to stimulate worldwide development of collaborative font projects, to support the font creation efforts of academic and linguistic communities, and to provide a free and open framework in which fonts may be shared and improved in partnership with others.

The OFL allows the licensed fonts to be used, studied, modified and redistributed freely as long as they are not sold by themselves. The fonts, including any derivative works, can be bundled, embedded, redistributed and/or sold with any software provided that any reserved names are not used by derivative works. The fonts and derivatives, however, cannot be released under any other type of license. The requirement for fonts to remain under this license does not apply to any document created using the fonts or their derivatives.

DEFINITIONS
"Font Software" refers to the set of files released by the Copyright Holder(s) under this license and clearly marked as such. This may include source files, build scripts and documentation.

"Reserved Font Name" refers to any names specified as such after the copyright statement(s).

"Original Version" refers to the collection of Font Software components as distributed by the Copyright Holder(s).

"Modified Version" refers to any derivative made by adding to, deleting, or substituting -- in part or in whole -- any of the components of the Original Version, by changing formats or by porting the Font Software to a new environment.

"Author" refers to any designer, engineer, programmer, technical writer or other person who contributed to the Font Software.

PERMISSION & CONDITIONS
Permission is hereby granted, free of charge, to any person obtaining a copy of the Font Software, to use, study, copy, merge, embed, modify, redistribute, and sell modified and unmodified copies of the Font Software, subject to the following conditions:

1) Neither the Font Software nor any of its individual components, in Original or Modified Versions, may be sold by itself.

2) Original or Modified Versions of the Font Software may be bundled, redistributed and/or sold with any software, provided that each copy contains the above copyright notice and this license. These can be included either as stand-alone text files, human-readable headers or in the appropriate machine-readable metadata fields within text or binary files as long as those fields can be easily viewed by the user.

3) No Modified Version of the Font Software may use the Reserved Font Name(s) unless explicit written permission is granted by the corresponding Copyright Holder. This restriction only applies to the primary font name as presented to the users.

4) The name(s) of the Copyright Holder(s) or the Author(s) of the Font Software shall not be used to promote, endorse or advertise any Modified Version, except to acknowledge the contribution(s) of the Copyright Holder(s) and the Author(s) or with their explicit written permission.

5) The Font Software, modified or unmodified, in part or in whole, must be distributed entirely under this license, and must not be distributed under any other license. The requirement for fonts to remain under this license does not apply to any document created using the Font Software.

TERMINATION
This license becomes null and void if any of the above conditions are not met.

DISCLAIMER
THE FONT SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO ANY WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT OF COPYRIGHT, PATENT, TRADEMARK, OR OTHER RIGHT. IN NO EVENT SHALL THE COPYRIGHT HOLDER BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, INCLUDING ANY GENERAL, SPECIAL, INDIRECT, INCIDENTAL, OR CONSEQUENTIAL DAMAGES, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF THE USE OR INABILITY TO USE THE FONT SOFTWARE OR FROM OTHER DEALINGS IN THE FONT SOFTWARE." Must be changed to "This Font Software is licensed under the SIL Open Font License, Version 1.1. This license is available with a FAQ at: https://scripts.sil.org/OFL" [code: wrong]
* ⚠ **WARN** Please consider using HTTPS URLs at name table entry [plat=3, enc=1, name=13] [code: http-in-description]
* ⚠ **WARN** For now we're still accepting http URLs, but you should consider using https instead.
 [code: http]
</div></details><details><summary>🔥 <b>FAIL:</b> Is the Grid-fitting and Scan-conversion Procedure ('gasp') table set to optimize rendering? (<a href="https://font-bakery.readthedocs.io/en/stable/fontbakery/profiles/googlefonts.html#com.google.fonts/check/gasp">com.google.fonts/check/gasp</a>)</summary><div>


* 🔥 **FAIL** Font is missing the 'gasp' table. Try exporting the font with autohinting enabled.
If you are dealing with an unhinted font, it can be fixed by running the fonts through the command 'gftools fix-nonhinting'
GFTools is available at https://pypi.org/project/gftools/ [code: lacks-gasp]
</div></details><details><summary>🔥 <b>FAIL:</b> Copyright notices match canonical pattern in fonts (<a href="https://font-bakery.readthedocs.io/en/stable/fontbakery/profiles/googlefonts.html#com.google.fonts/check/font_copyright">com.google.fonts/check/font_copyright</a>)</summary><div>


* 🔥 **FAIL** Name Table entry: Copyright notices should match a pattern similar to: "Copyright 2019 The Familyname Project Authors (git url)"
But instead we have got:
"Copyright (c) 1999-2020 SIL International" [code: bad-notice-format]
</div></details><details><summary>🔥 <b>FAIL:</b> Check glyphs do not have components which are themselves components. (<a href="https://font-bakery.readthedocs.io/en/stable/fontbakery/profiles/googlefonts.html#com.google.fonts/check/glyf_nested_components">com.google.fonts/check/glyf_nested_components</a>)</summary><div>


* 🔥 **FAIL** The following glyphs have components which themselves are component glyphs:
	* Atilde
	* Aring
	* Ntilde
	* Otilde
	* atilde
	* aring
	* ntilde and otilde [code: found-nested-components]
</div></details><details><summary>🔥 <b>FAIL:</b> Font enables smart dropout control in "prep" table instructions? (<a href="https://font-bakery.readthedocs.io/en/stable/fontbakery/profiles/googlefonts.html#com.google.fonts/check/smart_dropout">com.google.fonts/check/smart_dropout</a>)</summary><div>


* 🔥 **FAIL** The 'prep' table does not contain TrueType instructions enabling smart dropout control. To fix, export the font with autohinting enabled, or run ttfautohint on the font, or run the `gftools fix-nonhinting` script. [code: lacks-smart-dropout]
</div></details><details><summary>🔥 <b>FAIL:</b> Name table entries should not contain line-breaks. (<a href="https://font-bakery.readthedocs.io/en/stable/fontbakery/profiles/googlefonts.html#com.google.fonts/check/name/line_breaks">com.google.fonts/check/name/line_breaks</a>)</summary><div>


* 🔥 **FAIL** Name entry LICENSE_DESCRIPTION on platform WINDOWS contains a line-break. [code: line-break]
</div></details><details><summary>🔥 <b>FAIL:</b> Check font follows the Google Fonts CJK vertical metric schema (<a href="https://font-bakery.readthedocs.io/en/stable/fontbakery/profiles/googlefonts.html#com.google.fonts/check/cjk_vertical_metrics">com.google.fonts/check/cjk_vertical_metrics</a>)</summary><div>


* 🔥 **FAIL** OS/2.sTypoAscender is "2200" it should be 1802.24 [code: bad-OS/2.sTypoAscender]
* 🔥 **FAIL** OS/2.sTypoDescender is "-500" it should be -245.76 [code: bad-OS/2.sTypoDescender]
</div></details><details><summary>⚠ <b>WARN:</b> License URL matches License text on name table? (<a href="https://font-bakery.readthedocs.io/en/stable/fontbakery/profiles/googlefonts.html#com.google.fonts/check/name/license_url">com.google.fonts/check/name/license_url</a>)</summary><div>


* ⚠ **WARN** Please consider using HTTPS URLs at name table entry [plat=3, enc=1, name=13] [code: http-in-description]
* ⚠ **WARN** Please consider using HTTPS URLs at name table entry [plat=3, enc=1, name=13] [code: http-in-description]
* ⚠ **WARN** Please consider using HTTPS URLs at name table entry [plat=3, enc=1, name=13] [code: http-in-description]
</div></details><details><summary>⚠ <b>WARN:</b> Check name table: FULL_FONT_NAME entries. (<a href="https://font-bakery.readthedocs.io/en/stable/fontbakery/profiles/googlefonts.html#com.google.fonts/check/name/fullfontname">com.google.fonts/check/name/fullfontname</a>)</summary><div>


* ⚠ **WARN** [FULL_FONT_NAME(4):WINDOWS(3)]
Got "Nuosu SIL" which lacks "Regular", but it is probably OK in this case. [code: lacks-regular]
</div></details><details><summary>⚠ <b>WARN:</b> Ensure fonts have ScriptLangTags declared on the 'meta' table. (<a href="https://font-bakery.readthedocs.io/en/stable/fontbakery/profiles/googlefonts.html#com.google.fonts/check/meta/script_lang_tags">com.google.fonts/check/meta/script_lang_tags</a>)</summary><div>


* ⚠ **WARN** This font file does not have a 'meta' table. [code: lacks-meta-table]
</div></details><details><summary>⚠ <b>WARN:</b> Check font contains no unreachable glyphs (<a href="https://font-bakery.readthedocs.io/en/stable/fontbakery/profiles/universal.html#com.google.fonts/check/unreachable_glyphs">com.google.fonts/check/unreachable_glyphs</a>)</summary><div>


* ⚠ **WARN** The following glyphs could not be reached by codepoint or substitution rules:
	- uniFF1F_reject
	- .null
	- uniFF01_reject 
	- And nonmarkingreturn
 [code: unreachable-glyphs]
</div></details><details><summary>⚠ <b>WARN:</b> Check if each glyph has the recommended amount of contours. (<a href="https://font-bakery.readthedocs.io/en/stable/fontbakery/profiles/universal.html#com.google.fonts/check/contour_count">com.google.fonts/check/contour_count</a>)</summary><div>


* ⚠ **WARN** This font has a 'Soft Hyphen' character (codepoint 0x00AD) which is supposed to be zero-width and invisible, and is used to mark a hyphenation possibility within a word in the absence of or overriding dictionary hyphenation. It is mostly an obsolete mechanism now, and the character is only included in fonts for legacy codepage coverage. [code: softhyphen]
* ⚠ **WARN** This check inspects the glyph outlines and detects the total number of contours in each of them. The expected values are infered from the typical ammounts of contours observed in a large collection of reference font families. The divergences listed below may simply indicate a significantly different design on some of your glyphs. On the other hand, some of these may flag actual bugs in the font such as glyphs mapped to an incorrect codepoint. Please consider reviewing the design and codepoint assignment of these to make sure they are correct.

The following glyphs do not have the recommended number of contours:

	- Glyph name: percent	Contours detected: 4	Expected: 5
	- Glyph name: uni00AD	Contours detected: 1	Expected: 0
	- Glyph name: Eth	Contours detected: 3	Expected: 2
	- Glyph name: quoteleft	Contours detected: 2	Expected: 1
	- Glyph name: uniFFFC	Contours detected: 0	Expected: 22
	- Glyph name: Eth	Contours detected: 3	Expected: 2
	- Glyph name: percent	Contours detected: 4	Expected: 5
	- Glyph name: quoteleft	Contours detected: 2	Expected: 1
	- Glyph name: uni00AD	Contours detected: 1	Expected: 0 
	- And Glyph name: uniFFFC	Contours detected: 0	Expected: 22
 [code: contour-count]
</div></details><details><summary>⚠ <b>WARN:</b> Does the font contain chws and vchw features? (<a href="https://font-bakery.readthedocs.io/en/stable/fontbakery/profiles/universal.html#com.google.fonts/check/cjk_chws_feature">com.google.fonts/check/cjk_chws_feature</a>)</summary><div>


* ⚠ **WARN** chws feature not found in font. Use chws_tool (https://github.com/googlefonts/chws_tool) to add it. [code: missing-chws-feature]
* ⚠ **WARN** vchw feature not found in font. Use chws_tool (https://github.com/googlefonts/chws_tool) to add it. [code: missing-vchw-feature]
</div></details><details><summary>⚠ <b>WARN:</b> Does GPOS table have kerning information? This check skips monospaced fonts as defined by post.isFixedPitch value (<a href="https://font-bakery.readthedocs.io/en/stable/fontbakery/profiles/gpos.html#com.google.fonts/check/gpos_kerning_info">com.google.fonts/check/gpos_kerning_info</a>)</summary><div>


* ⚠ **WARN** GPOS table lacks kerning information. [code: lacks-kern-info]
</div></details><details><summary>⚠ <b>WARN:</b> Do any segments have colinear vectors? (<a href="https://font-bakery.readthedocs.io/en/stable/fontbakery/profiles/<Section: Outline Correctness Checks>.html#com.google.fonts/check/outline_colinear_vectors">com.google.fonts/check/outline_colinear_vectors</a>)</summary><div>


* ⚠ **WARN** The following glyphs have colinear vectors:
	* OE (U+0152): L<<1721.0,0.0>--<1217.0,0.0>> -> L<<1217.0,0.0>--<1041.0,0.0>>
	* uniA003 (U+A003): L<<944.0,0.0>--<944.0,0.0>> -> L<<944.0,0.0>--<1119.0,0.0>>
	* uniA107 (U+A107): L<<280.0,1793.0>--<280.0,988.0>> -> L<<280.0,988.0>--<279.0,896.0>>
	* uniA107 (U+A107): L<<280.0,988.0>--<279.0,896.0>> -> L<<279.0,896.0>--<280.0,714.0>>
	* uniA240 (U+A240): L<<491.0,825.0>--<491.0,979.0>> -> L<<491.0,979.0>--<492.0,998.0>>
	* uniA240 (U+A240): L<<492.0,998.0>--<491.0,1019.0>> -> L<<491.0,1019.0>--<491.0,1793.0>>
	* uniA260 (U+A260): L<<488.0,1182.0>--<396.0,1204.0>> -> L<<396.0,1204.0>--<385.0,1207.0>>
	* uniA295 (U+A295): L<<1287.0,0.0>--<1287.0,0.0>> -> L<<1287.0,0.0>--<1375.0,0.0>>
	* uniA296 (U+A296): L<<1287.0,0.0>--<1287.0,0.0>> -> L<<1287.0,0.0>--<1375.0,0.0>>
	* uniA2B3 (U+A2B3): L<<1267.0,1604.0>--<1268.0,978.0>> -> L<<1268.0,978.0>--<1268.0,969.0>> and 8 more.

Use -F or --full-lists to disable shortening of long lists. [code: found-colinear-vectors]
</div></details><details><summary>⚠ <b>WARN:</b> Do outlines contain any jaggy segments? (<a href="https://font-bakery.readthedocs.io/en/stable/fontbakery/profiles/<Section: Outline Correctness Checks>.html#com.google.fonts/check/outline_jaggy_segments">com.google.fonts/check/outline_jaggy_segments</a>)</summary><div>


* ⚠ **WARN** The following glyphs have jaggy segments:
	* uniA004 (U+A004): B<<467.0,1383.0>-<465.0,1385.0>-<465.0,1386.0>>/L<<465.0,1386.0>--<466.0,1381.0>> = 11.309932474020195
	* uniA004 (U+A004): L<<465.0,1386.0>--<466.0,1381.0>>/B<<466.0,1381.0>-<466.0,1382.0>-<467.0,1383.0>> = 11.309932474020195
	* uniA179 (U+A179): B<<393.0,1317.5>-<302.0,1342.0>-<247.0,1355.0>>/L<<247.0,1355.0>--<248.0,1355.0>> = 13.298570330494275
	* uniA17A (U+A17A): B<<393.0,1317.5>-<302.0,1342.0>-<247.0,1355.0>>/L<<247.0,1355.0>--<248.0,1355.0>> = 13.298570330494275
	* uniA19A (U+A19A): L<<503.0,1376.0>--<501.0,1379.0>>/L<<501.0,1379.0>--<503.0,1374.0>> = 11.888658039627936
	* uniA1A4 (U+A1A4): B<<448.0,1438.0>-<446.0,1440.0>-<446.0,1441.0>>/L<<446.0,1441.0>--<447.0,1435.0>> = 9.462322208025613
	* uniA1A4 (U+A1A4): L<<446.0,1441.0>--<447.0,1435.0>>/B<<447.0,1435.0>-<447.0,1437.0>-<448.0,1438.0>> = 9.462322208025613
	* uniA1A7 (U+A1A7): B<<448.0,1438.0>-<446.0,1440.0>-<446.0,1441.0>>/L<<446.0,1441.0>--<447.0,1435.0>> = 9.462322208025613
	* uniA1A7 (U+A1A7): L<<446.0,1441.0>--<447.0,1435.0>>/B<<447.0,1435.0>-<447.0,1437.0>-<448.0,1438.0>> = 9.462322208025613 and uniA3B5 (U+A3B5): B<<899.0,199.0>-<865.0,297.0>-<812.0,391.0>>/L<<812.0,391.0>--<813.0,388.0>> = 10.980650010173488 [code: found-jaggy-segments]
</div></details><details><summary>⚠ <b>WARN:</b> Do outlines contain any semi-vertical or semi-horizontal lines? (<a href="https://font-bakery.readthedocs.io/en/stable/fontbakery/profiles/<Section: Outline Correctness Checks>.html#com.google.fonts/check/outline_semi_vertical">com.google.fonts/check/outline_semi_vertical</a>)</summary><div>


* ⚠ **WARN** The following glyphs have semi-vertical/semi-horizontal lines:
 * uni300E (U+300E): L<<713.0,0.0>--<870.0,1.0>>
 * uni300E (U+300E): L<<840.0,1655.0>--<830.0,30.0>>
 * uni300F (U+300F): L<<1034.0,1792.0>--<1191.0,1793.0>>
 * uni300F (U+300F): L<<1074.0,1763.0>--<1064.0,128.0>>
 * uni3016 (U+3016): L<<798.0,1687.0>--<1196.0,1688.0>>
 * uni3017 (U+3017): L<<404.0,1688.0>--<802.0,1687.0>>
 * uniA107 (U+A107): L<<279.0,896.0>--<280.0,714.0>>
 * uniA1FC (U+A1FC): L<<737.0,657.0>--<739.0,0.0>>
 * uniA1FD (U+A1FD): L<<737.0,657.0>--<739.0,0.0>>
 * uniA209 (U+A209): L<<739.0,384.0>--<740.0,0.0>> and 23 more.

Use -F or --full-lists to disable shortening of long lists. [code: found-semi-vertical]
</div></details><details><summary>ℹ <b>INFO:</b> Show hinting filesize impact. (<a href="https://font-bakery.readthedocs.io/en/stable/fontbakery/profiles/googlefonts.html#com.google.fonts/check/hinting_impact">com.google.fonts/check/hinting_impact</a>)</summary><div>


* ℹ **INFO** Hinting filesize impact:

 |               | NuosuSIL-Regular.ttf          |
 |:------------- | ---------------:|
 | Dehinted Size | 255.1kb |
 | Hinted Size   | 255.1kb   |
 | Increase      | -24 bytes      |
 | Change        | -0.0 %  |
 [code: size-impact]
</div></details><details><summary>ℹ <b>INFO:</b> Font has old ttfautohint applied? (<a href="https://font-bakery.readthedocs.io/en/stable/fontbakery/profiles/googlefonts.html#com.google.fonts/check/old_ttfautohint">com.google.fonts/check/old_ttfautohint</a>)</summary><div>


* ℹ **INFO** Could not detect which version of ttfautohint was used in this font. It is typically specified as a comment in the font version entries of the 'name' table. Such font version strings are currently: ['Version 2.200'] [code: version-not-detected]
</div></details><details><summary>ℹ <b>INFO:</b> EPAR table present in font? (<a href="https://font-bakery.readthedocs.io/en/stable/fontbakery/profiles/googlefonts.html#com.google.fonts/check/epar">com.google.fonts/check/epar</a>)</summary><div>


* ℹ **INFO** EPAR table not present in font. To learn more see https://github.com/googlefonts/fontbakery/issues/818 [code: lacks-EPAR]
</div></details><details><summary>ℹ <b>INFO:</b> Check for font-v versioning. (<a href="https://font-bakery.readthedocs.io/en/stable/fontbakery/profiles/googlefonts.html#com.google.fonts/check/fontv">com.google.fonts/check/fontv</a>)</summary><div>


* ℹ **INFO** Version string is: "Version 2.200"
The version string must ideally include a git commit hash and either a "dev" or a "release" suffix such as in the example below:
"Version 1.3; git-0d08353-release" [code: bad-format]
</div></details><details><summary>ℹ <b>INFO:</b> Font contains all required tables? (<a href="https://font-bakery.readthedocs.io/en/stable/fontbakery/profiles/universal.html#com.google.fonts/check/required_tables">com.google.fonts/check/required_tables</a>)</summary><div>


* ℹ **INFO** This font contains the following optional tables:
	- loca [code: optional-tables]
</div></details><details><summary>ℹ <b>INFO:</b> List all superfamily filepaths (<a href="https://font-bakery.readthedocs.io/en/stable/fontbakery/profiles/universal.html#com.google.fonts/check/superfamily/list">com.google.fonts/check/superfamily/list</a>)</summary><div>


* ℹ **INFO** . [code: family-path]
</div></details><br></div></details>
### Summary

| 💔 ERROR | 🔥 FAIL | ⚠ WARN | 💤 SKIP | ℹ INFO | 🍞 PASS | 🔎 DEBUG |
|:-----:|:----:|:----:|:----:|:----:|:----:|:----:|
| 0 | 9 | 10 | 114 | 7 | 85 | 0 |
| 0% | 4% | 4% | 51% | 3% | 38% | 0% |

**Note:** The following loglevels were omitted in this report:
* **SKIP**
* **PASS**
* **DEBUG**

**Comment by RosaWagner** [comment]
We should discuss this with SIL, but seeing the font it probably can be ignored.
🔥 FAIL: Check font follows the Google Fonts CJK vertical metric schema ([com.google.fonts/check/cjk_vertical_metrics](https://font-bakery.readthedocs.io/en/stable/fontbakery/profiles/googlefonts.html#com.google.fonts/check/cjk_vertical_metrics))
🔥 FAIL OS/2.sTypoAscender is "2200" it should be 1802.24 [code: bad-OS/2.sTypoAscender]
🔥 FAIL OS/2.sTypoDescender is "-500" it should be -245.76 [code: bad-OS/2.sTypoDescender]

**Comment by jvgaultney** [comment]
Agreed - thanks!

**Comment by devosb** [comment]
Nuosu 2.300 has been released, which should fix all issues. Can this be onboarded? 

https://github.com/silnrsi/font-nuosu/releases/tag/v2.300

This new version adds several new characters, and fixes a mis-encoded character.
