### ISSUE TITLE
[Radio-Canada] No italics?

### ISSUE THREAD

**Issue by cssobral2013** [google/fonts#4553]
**Describe the bug**
The font should display variable fonts for italics too, not just the roman

**To Reproduce**
Navigate to https://fonts.google.com/specimen/Radio+Canada?vfonly=true&sort=date
You'll see Radio-Canada has no italics, despite these existing upstream at  https://github.com/cbcrc/radiocanadafonts/tree/main/fonts/variable
**Expected behavior**
The font should display the italics, as upstream

**Comment by davelab6** [comment]
@RosaWagner I see in [the PR that added it](https://github.com/google/fonts/pull/4383/files) that you didn't include [the Italic VF file](https://github.com/cbcrc/radiocanadafonts/blob/main/fonts/variable/RadioCanada-Italic%5Bwdth%2Cwght%5D.ttf), please could you share more context on when it can be added?

**Comment by RosaWagner** [comment]
Oopsy. Sorry I must have forgotten them, I gonna do it now.

**Comment by cssobral2013** [comment]
@RosaWagner - Could you please reopen this issue? As of now, 2022-05-03, the italics still not appear on API.

**Comment by cssobral2013** [comment]
@RosaWagner - Nevermind it. The font Was just updated with italics now, 2022-05-26.

**Comment by RosaWagner** [comment]
@cssobral2013 we close automatically the issue once the PR is merged, it then takes few weeks before the font appears on the API. We do need to proceed this way for organisation efficiency and avoiding laborious manual tasks.
