### ISSUE TITLE
Couldn't find Noto Sans Ethiopic

### ISSUE THREAD

**Issue by yonathan97** [google/fonts#4554]
all the fonts for Noto Sans Ethiopic have disappeared

**Comment by fitojb** [comment]
What do you mean? https://fonts.google.com/noto/specimen/Noto+Serif+Ethiopic works for me.

**Comment by yonathan97** [comment]
The ones you stated is **Serif,** I meant the **Sans** version

**Comment by fitojb** [comment]
Whoops! Oh right! I was a bit too fast. Yep, they don’t seem to be listed, but in the meantime you can get them [here](https://github.com/googlefonts/noto-fonts/tree/main/hinted/ttf/NotoSansEthiopic) or [here](https://github.com/googlefonts/noto-fonts/blob/main/unhinted/variable-ttf/NotoSansEthiopic-VF.ttf) for a variable version.

I’d say it’s an oversight.

**Comment by RosaWagner** [comment]
Noto Sans Ethiopic is available in the catalog: https://fonts.google.com/noto/specimen/Noto+Sans+Ethiopic
