### ISSUE TITLE
Font metadata issues with fonts in to_sandbox.txt

### ISSUE THREAD

**Issue by nathan-williams** [google/fonts#4562]
All issues below related to filenames and postscript names not aligning with expectations enforced by automatic checks.

Finding in ofl/nuosu/NuosuSIL-Regular.ttf:
    ERROR: ofl/nuosu/NuosuSIL-Regular.ttf: Bad filename 'NuosuSIL-Regular.ttf', expected 'Nuosu-Regular.ttf'
Finding in ofl/tirodevanagarihindi/TiroDevaHindi-Italic.ttf:
    ERROR: ofl/tirodevanagarihindi/TiroDevaHindi-Italic.ttf: Bad filename 'TiroDevaHindi-Italic.ttf', expected 'TiroDevanagariHindi-Italic.ttf'
Finding in ofl/tirodevanagarihindi/TiroDevaHindi-Regular.ttf:
    ERROR: ofl/tirodevanagarihindi/TiroDevaHindi-Regular.ttf: Bad filename 'TiroDevaHindi-Regular.ttf', expected 'TiroDevanagariHindi-Regular.ttf'
Finding in ofl/tirodevanagarimarathi/TiroDevaMarathi-Italic.ttf:
    ERROR: ofl/tirodevanagarimarathi/TiroDevaMarathi-Italic.ttf: Bad filename 'TiroDevaMarathi-Italic.ttf', expected 'TiroDevanagariMarathi-Italic.ttf'
Finding in ofl/tirodevanagarimarathi/TiroDevaMarathi-Regular.ttf:
    ERROR: ofl/tirodevanagarimarathi/TiroDevaMarathi-Regular.ttf: Bad filename 'TiroDevaMarathi-Regular.ttf', expected 'TiroDevanagariMarathi-Regular.ttf'
Finding in ofl/tirodevanagarisanskrit/TiroDevaSanskrit-Italic.ttf:
    ERROR: ofl/tirodevanagarisanskrit/TiroDevaSanskrit-Italic.ttf: Bad filename 'TiroDevaSanskrit-Italic.ttf', expected 'TiroDevanagariSanskrit-Italic.ttf'
Finding in ofl/tirodevanagarisanskrit/TiroDevaSanskrit-Regular.ttf:
    ERROR: ofl/tirodevanagarisanskrit/TiroDevaSanskrit-Regular.ttf: Bad filename 'TiroDevaSanskrit-Regular.ttf', expected 'TiroDevanagariSanskrit-Regular.ttf'

**Comment by RosaWagner** [comment]
Those are files we had to take as the designers delivered. Postscript names have to match other versions distributed by some OS.

If only the file path are problematic then the file names can be corrected. Can you do it @nathan-williams ? Or would you rather pause their push and I’ll inspect tomorrow?

**Comment by nathan-williams** [comment]
Unfortunately, we probably wouldn't get to it till tomorrow, either (although this would hopefully take <5 min to resolve). Pretty heads down on other time-sensitive things.

**Comment by RosaWagner** [comment]
Ok I’ll do it in my morning

**Comment by rsheeter** [comment]
Bonus points for adding name checks to the CI on this repo :)

**Comment by m4rc1e** [comment]
@nathan-williams Can you copy and paste the code which is raising the fail? would be good to have this so our implementation matches. If you can't share it here, feel free to email it.
