### ISSUE TITLE
Fix Arabic sample texts again

### ISSUE THREAD

**Issue by simoncozens** [google/fonts#4566]
#4549 replaced the full stop in Arabic sample texts with an Urdu full stop; this was to stop Noto fonts without the Latin full stop from showing tofu. However, this only affected one font (Noto Kufi Arabic), which I fixed by adding a Latin subset to it. When that goes into production, we should revert #4549.

**Comment by khaledhosny** [comment]
This text is now shown for all fonts not only Noto, so please give this a higher priority.

**Comment by simoncozens** [comment]
Done (and working its way through the system).

**Comment by khaledhosny** [comment]
Thanks!
