### ISSUE TITLE
PlusJakartaSans not showing up in Google Doc, Google Slides, etc.

### ISSUE THREAD

**Issue by Ph15** [google/fonts#4593]
Hi!
I came across the [PlusJakartaFont](https://fonts.google.com/specimen/Plus+Jakarta+Sans) on Google Font and found it very nice. I was thinking of using it as my go-to font of the moment and tried to add it on a Google Doc, but the font does not appear, despite being publicly listed as a Google Font.
Any clue?
Many thanks in advance for your answer!
Kind regards,
Phil

**To Reproduce**
Open a new Google Doc or Google Slide, select a text and try to put the PlusJakartaFont.

**Expected behavior**
I expect the font to be listed among the Google fonts I can install on my document, since it is a publicly listed Google Font.

**Screenshots**
![Font not found](https://user-images.githubusercontent.com/11819455/166970660-5b8effb7-3679-4f53-8697-75dd289bc131.png)

**Additional context**
Nothing to add.

**Comment by RosaWagner** [comment]
This font was added to GF catalog very recently, the process to add new fonts to Google Docs is longer. It will happen eventually :)

The team tracking the missing fonts in google doc is probably already aware of the fonts to add, so I am closing this.

**Comment by jltanner** [comment]
Hello @RosaWagner — I'm also interested in using this font in a large project, but would need to use it in Google Slides & Docs as well. Is there possibly an estimated date when Plus Jakarta Sans would be available in Slides? Or is there anywhere I could contact the team you mention who are tracking those missing fonts in Docs, to ask about its progress?

Thanks for your help!
