### ISSUE TITLE
Abhaya Libre Colon in Semibold and Bold Correction

### ISSUE THREAD

**Issue by pietrogregorini** [google/fonts#460]
In Abhaya Libre font, the colon symbol ( : ) in Semibold and Bold weights appears weird, more precisely the two dots forming it seems overlapped.

In Medium weight they look a bit too close between each other, compared to Regular and ExtraBold.

![colon](https://cloud.githubusercontent.com/assets/3169323/20179126/e8a3b05c-a754-11e6-96da-8506ce78e61d.png)

**Comment by davelab6** [comment]
@pathumego is this resolved in the latest release?

**Comment by pathumego** [comment]
@davelab6 I fixed it, will release the binaries v1.051 in a bit. @pietrogregorini thanks for the report.

**Comment by pietrogregorini** [comment]
@pathumego My pleasure!

**Comment by m4rc1e** [comment]
Hey @pathumego any chance we could have the binaries? I'll be sending a pr for this project.

Cheers,
Marc

**Comment by pietrogregorini** [comment]
Guys, still any update for this bug?
