### ISSUE TITLE
Add Martian Mono

### ISSUE THREAD

**Issue by davelab6** [google/fonts#4610]
Pending source provision and RFN resolution

https://github.com/evilmartians/mono/issues/3

**Comment by romashamin** [comment]
Hi there!

Please consider publishing [Martian Mono](https://github.com/evilmartians/mono) on Google Fonts.

- I removed RFN.
- The source .glyphs file is available in `sources` folder.
- Ttf (with TrueType hinting) files are available in the [Releases page](https://github.com/evilmartians/mono/releases/tag/v0.9.1).

Let me know if I can help 🙂

**Comment by romashamin** [comment]
Also, I submitted a designer profile and foundry information.

**Comment by davelab6** [comment]
@RosaWagner who may be available to work on onboarding this, when? @romashamin is excited to respond so I think it's worth prioritizing soon to keep his momentum

**Comment by RosaWagner** [comment]
@emmamarichal told me she was actually still working this week, but I am a bit unsure of her calendar now that I am in holidays, otherwise we'll have to wait mid-september

**Comment by emmamarichal** [comment]
@davelab6 Yes I'm available this week, I can onboard it soon :)

**Comment by romashamin** [comment]
@davelab6 @RosaWagner I don’t mean to push you too much, folks. Just in case, if there’s something—anything—I can do to speed up the process (whether it helps if I try to prepare a PR?), please, please, let me know 🙌

**Comment by emmamarichal** [comment]
I will export the font respecting the Google Fonts specs, will do some QA and then make you a PR that you will have to merge, and that's it 👌🏻

**Comment by romashamin** [comment]
@emmamarichal perfect! Thank you very much.

**Comment by RosaWagner** [comment]
@davelab6 Just seeing now that the Grotesk style of the family is not under OFL
https://www.myfonts.com/collections/martian-grotesk-font-martian-fonts

**Comment by davelab6** [comment]
Like Prosa, Abhaya and Vesper, this isn't a subset of styles within a family but a sibling family, and I discussed this with @romashamin and thought it was not ideal yet acceptable. @romashamin  understands the risks that someone like @eliheuer might make a proportional spaced derivative of the libre mono.

**Comment by RosaWagner** [comment]
Thanks for clarifying the exception @davelab6
