### ISSUE TITLE
Mahjong Tile Designs - Circle Suite

### ISSUE THREAD

**Issue by tjablin** [google/fonts#4617]
The design of the circle suite in the Mahjong Tile Unicode Block look weird in Noto Sans Symbols 2.

Currently, the sizes of the circles for the four, five, six, seven, and eight of dots are non-uniform. Typically, these circles are the same size and only one, two, and three have larger circles.

Currently, the six of circles features six equally spaced circles in a rectangular two by three layout. Typically, the bottom four circles on the six of circle are arranged in a tight square and the top two circles are offset by a large gap. Without the gap between the two dot and bottom four circles, I think it is difficult to rapidly distinguish the six and eight of circles, particularly at small font sizes.

Currently, the seven of circles has four circles in a tight rectangle on the bottom and three circles at a thirty degree angle on top. Typically, the bottom four circles should be arranged in a square identical to the six of circles.

Currently, the eight of circles has two columns of four circles separated by a gap. Typically, these two columns touch.

Photos of Typical Mahjong Sets
* [Photo from Wikipedia](https://upload.wikimedia.org/wikipedia/commons/1/12/MJTiles_Fullset.png)
* [Japanese Style](https://www.amazon.com/Nintendo-Mahjong-Tiles-Yakuman-Phoenix/dp/B00GMCH026)
* [Singaporean Style](https://shopee.sg/168-Tiles-Mahjong-36mm-Singapore-Mahjong-Dear-J--i.76755838.11780781001?sp_atk=5a0b1f8f-8e74-4d75-bcbf-6d4545874d1d&xptdk=5a0b1f8f-8e74-4d75-bcbf-6d4545874d1d)
* [American Style](https://www.amazon.com/American-Mah-Jongg-All-One/dp/B01N0NJEJU)
* [Chinese Style](https://www.ymimports.com/collections/modern-1/products/fx-cm005-a)

**Comment by RosaWagner** [comment]
Please report any issue related to Noto fonts in this repository: https://github.com/googlefonts/noto-fonts/issues.

**Comment by tjablin** [comment]
Duplicate of googlefonts/noto-fonts/issues/2351
