### ISSUE TITLE
Review removed links

### ISSUE THREAD

**Issue by rsheeter** [google/fonts#4628]
https://github.com/google/fonts/pull/4600/commits/a052d0b03447b14e53d0ac4d9712e65e09bfcd05 removed a couple of links that seemed to be invalid to unblock activating the graph checker. PTAL. If removal was correct you can just close this, if the graph checker screwed up please lmk so we can fix it.

**Comment by davelab6** [comment]
The removal should be followed by replacement with the correct links :)

**Comment by elliotjaystocks** [comment]
@rsheeter @davelab6  Not sure if I’m doing this right, but in theory the correct links are now in this PR: https://github.com/google/fonts/pull/4632
