### ISSUE TITLE
Amatic SC - vertical positioning of '&'

### ISSUE THREAD

**Issue by felipesanches** [google/fonts#463]
I'm using Amatic SC on an Inkscape drawing and I did not like the vertical positioning of the '&' glyph. Is that correct?
![sample text](https://cloud.githubusercontent.com/assets/213676/20239472/e7308d64-a8e7-11e6-9c20-014de2e093cd.png)

**Comment by davelab6** [comment]
Confirmed in production @ https://output.jsbin.com/qohahof

@thomasjockin is respacing Amatica to make it closer to Amatic

**Comment by m4rc1e** [comment]
Closing, fixed.

![screen shot 2017-06-15 at 11 44 08](https://user-images.githubusercontent.com/7525512/27177906-f8b35f40-51bf-11e7-8f3f-4a51ff39dd74.png)

http://jsbin.com/dorakobiva/edit?html,output

@felipesanches You opening a juice bard or something?
