### ISSUE TITLE
Add Linefont

### ISSUE THREAD

**Issue by davelab6** [google/fonts#4630]
**Font Project Git Repo URL:**

https://github.com/a-vis/linefont/

**Super short description of the Font Family:**

Similar to barcode, redacted and flow fonts, linefont is a 'non text' font that uses variable fonts tech to provide a typo-graphic utility, in the long history of border/dingbat fonts.

Dima Iv (who has the enviable github username @dy  :) has agreed to make the project meet our requirements soon, and I've asked him to update this issue when he is ready for us to review his repo and PR any other changes that we need. I've filled out the check-list below to roughly match that intent and the current state.

**Requirements:**

I understand that Google Fonts will publish only fonts that matches its requirements, and I can confirm the project meets them (by ticking the cases, or putting x between the square brackets in text mode):

- [ ] The entire font project is licensed under the [OFL](https://scripts.sil.org/cms/scripts/page.php?site_id=nrsi&id=OFL)
- [x] There is no "Reserved Font Name" mention in the OFL license
- [x] Family name is unique according to namecheck.fontdata.com
- [ ] The font supports at least [GF Latin Core glyphset](https://github.com/googlefonts/glyphsets/tree/main/GF_glyphsets/Latin/)
- [ ] The repository respect the [upstream repo structure](https://github.com/googlefonts/gf-docs/tree/main/Spec#upstream-repo-structure)
- [x] The source files are available in the repository
- [x] I read, agree and comply with the full [contributing requirements](https://github.com/google/fonts/blob/main/CONTRIBUTING.md)
- [x] I am the author of the font or the author agreed to this submission
- [x] I will maintain the repository

**Comment by RosaWagner** [comment]
@dy can you update us about the progress? There is no sources in the repository. Please ask if you need help. Same for #4631

**Comment by ayoolafelix** [comment]
Hi, I believe you are asking for the source of the typeface. in that case, here is the author according to the internet https://github.com/dy/linefont, v-font attests to this.

If I'm mistaken, I apologize for the inconvenience

**Comment by dy** [comment]
@RosaWagner it will take me around a week to get things up to date. The internals need to be refurbished, as well as externals cleaned up. I've done an update for wavefont today, to include algn axis. Linefont needs to get on par with wavefont ranges / stubbed characters etc. I will post here once I get to review stage. Thanks for pinging!

**Comment by RosaWagner** [comment]
@dy great, but you can take your time we are all in holidays ;)

**Comment by RosaWagner** [comment]
@dy you can start to align Linefont to Wavefont's spec ;)

**Comment by dy** [comment]
Ok, I've updated [linefont](https://github.com/dy/linefont/tree/main) to be on-par with wavefont @RosaWagner.
Can you please check and give improvement comments.
Likely will need to calibrate axes boundaries and other minor details.

**Comment by dy** [comment]
It seems font passes all checks

**Comment by felipesanches** [comment]
**Oh, wow! This is so cool!** :-D

**Comment by dy** [comment]
Just finished with designspace changes. It incorporates enhanced typographic scale mapping of `wght` axis.

**Comment by RosaWagner** [comment]
@dy to summarise we are waiting for:
- addition of a master at `100` (Thin)
- expand range to `1` (Hairline) so it follows Wavefont ?

**Comment by dy** [comment]
Ok, fixed to match wavefont.
It now provides wght default at 100, ExtraBlack, expanded wght range to 4..1000.

**Comment by RosaWagner** [comment]
@dy There are some controversy with the SuperCondensed instance. It doesn't prevent us from moving forward with the family, but as a side note, there is a chance that it gets removed from the Axis Registry at some point. In that case, there won't be a static instance available anymore for users who download the font from the API. So as for now user would have access to it, but in the future they might complain that they can't download a SuperCondensed static instance anymore. 

It doesn't change anything for the variable font of course.

Are you okay with that?

**Comment by dy** [comment]
@RosaWagner yes, I'm ok with that - font isn't intended much to be used via instances - users are encouraged to use variable font and adjust axes to their preference.
