### ISSUE TITLE
Add Wavefont

### ISSUE THREAD

**Issue by davelab6** [google/fonts#4631]
**Font Project Git Repo URL:**

Related to https://github.com/google/fonts/issues/4630

https://github.com/a-vis/wavefont/

**Super short description of the Font Family:**

Similar to barcode, redacted and flow fonts, wavefont is a 'non text' font that uses variable fonts tech to provide a typo-graphic utility, in the long history of border/dingbat fonts.

Dima Iv (who has the enviable github username @dy  :) has agreed to make the project meet our requirements soon, and I've asked him to update this issue when he is ready for us to review his repo and PR any other changes that we need. I've filled out the check-list below to roughly match that intent and the current state.

**Requirements:**

I understand that Google Fonts will publish only fonts that matches its requirements, and I can confirm the project meets them (by ticking the cases, or putting x between the square brackets in text mode):

- [x] The entire font project is licensed under the [OFL](https://scripts.sil.org/cms/scripts/page.php?site_id=nrsi&id=OFL)
- [x] There is no "Reserved Font Name" mention in the OFL license
- [x] Family name is unique according to namecheck.fontdata.com
- [x] The font supports at least [GF Latin Core glyphset](https://github.com/googlefonts/glyphsets/tree/main/GF_glyphsets/Latin/)
- [x] The repository respect the [upstream repo structure](https://github.com/googlefonts/gf-docs/tree/main/Spec#upstream-repo-structure)
- [x] The source files are available in the repository
- [x] I read, agree and comply with the full [contributing requirements](https://github.com/google/fonts/blob/main/CONTRIBUTING.md)
- [x] I am the author of the font or the author agreed to this submission
- [x] I will maintain the repository

**Comment by dy** [comment]
@RosaWagner is that better to create a separate issue for new axis registration? It seems that ALGN axis must be there, it seems to be useful to have for multiple purposes. Can you please forward to existing issues that can act as an example?

**Comment by RosaWagner** [comment]
hi @dy, sorry for the delayed answer, I was in a long holidays.
For the axis registration it happens here: https://github.com/googlefonts/axisregistry

Good example of submission would be: https://github.com/googlefonts/axisregistry/issues/38 and https://github.com/googlefonts/axisregistry/issues/42

**Comment by dy** [comment]
@RosaWagner I got stuck with transitioning, it turned out to be more complicated than just reordering folders, will spend some time today.

**Comment by chrissimpkins** [comment]
I'm sorry to hear that Dmitry.  Will you please let us know where you are stuck so that we understand how to help you?

**Comment by davelab6** [comment]
@dy thanks for attempting. This is very useful feedback for us. We are willing to take care of everything for your project and just submit a PR to you, and so your involvement is limited to discussion and review/approval only.

**Comment by davelab6** [comment]
Ah, the key thing we need is your confirmation to change the license from the cc license in https://github.com/a-vis/wavefont/blob/master/license.md today to the sil open font license :)

**Comment by dy** [comment]
@davelab6 sure, I'm fine with changing the license.
A bit of problem here comes with generating 0-56 values for a-zA-Z latin range, also stubbing rest of Latin Core. If you can help I'd greatly appreciate. 
Also to note - that font is generated from template via plopfile, so likely that would be a separate step.

**Comment by dy** [comment]
@chrissimpkins mostly docs - they are super-detailed and time-consuming. I'd suggest a list of example font repos or cases of "googlifying" would help more, rather than longreads.

**Comment by davelab6** [comment]
We provide a template repo in this org and fontbakery to lint your project so you don't need to read everything if you don't want to. Definitely good feedback to know there should be a "quick start, tldr" page at the front of Googlefonts.github.io/gf-guide :)

We have the libre barcode fonts project that's similar, maybe we don't need to make the Core, it even Kernel, as they do; or maybe we can do something like what Adobe Blank/NotDef do and have 64k character support :)

**Comment by dy** [comment]
Thanks! Stubbing rest with blanks would be preferrable, because wavefont falls back to adobe blank anyways via css. I don't know how to do that compact though as it's done in https://github.com/adobe-fonts/adobe-blank-vf (1kb only)

**Comment by RosaWagner** [comment]
@dy I can look it up next week.

**Comment by RosaWagner** [comment]
@dy I need your help to understand how the font is build, can we set up a call?

**Comment by dy** [comment]
@RosaWagner I've updated folders structure, you can see UFOs stored under `source/wavefont100` folder.
I've added short description for gftools in https://github.com/dy/wavefont#building

**Comment by dy** [comment]
@davelab6 @RosaWagner it seems all of the tasks in a set are covered.
Please let know if any other changes are necessary.

**Comment by RosaWagner** [comment]
note to self: this family will need a custom sample text for the specimen page to render interesting shapes. I don't think the usual sentence will make sense here. @dy you can write down here several strings of characters we could use :)

**Comment by dy** [comment]
Sure.
Here are some strings.

Bottom-align:
```
ĈĉċĊĉċčīıēģĹĶĲĺķĺĺĳĽĳĶĵĦČģĹĪĞĠĝġđČĐĤĨĳħģĚģĢıĞĢİķīİĳķĴĲĪĬģęĬķĦĒěěėďĒĚĪĢēČċěĩĘđēĞĝĚČčĖħĨĝđđĒīīĚďĕĚġĔċċĖĭİĮğĔĢĤĮĪĘįĹĵĶĳįĸııĳĢĚĭĥĪıĦĦĨĤĪġĤĴĭĵįĐĕĠĤħĦĨĩĪĶĶĲĹĲįĮĪķĺĵĹĶİĲįĪİĨĮĩġĤĜğĘğīĞęīĬĹĶĨįĲİĳĪıİİĸĴĶĮĭĳĵĭīĨĭħĬįĵĳĶįĤĨģĥĝĘĠĦĲĮĦıİįĸįıĵİĭİĩĬĢģħħīěĜġġĠĞĦĩīĹĵĺĶİĮĭİĲīīģĕĒČČďĐđċčďčċċċĉĉċĉĉĈĈċčėįĢĥłĻĲ
```

Center-align:
```
ЁЂЈЉЋЊЉЋЍЫбГУйжвкзккгнгжеЦЌУйЪОРНСБЌАФШгЧУКУТбОТазЫагздвЪЬУЙЬзЦВЛЛЗЏВКЪТГЌЋЛЩИБГОНКЌЍЖЧШНСЉЈІЃЂ
```

**Comment by RosaWagner** [comment]
Hi @dy, let me know when the font has the `YALN` axis. #5721 was not reviewed while I was out, so will onboard Wavefont with all the axes at once.

**Comment by dy** [comment]
Thank you @RosaWagner, refactored axis to YALN.

**Comment by davelab6** [comment]
@dy YALN was approved by the GF engineering lead for axis registration and @RosaWagner will pick this up soon
