### ISSUE TITLE
Upgrade Pinyon Script

### ISSUE THREAD

**Issue by emmamarichal** [google/fonts#4676]
@EbenSorkin, I open this issue, you can comment it when the font is ready :)

**Font Project Git Repo URL:**
https://github.com/SorkinType/Pinyon

**Current version:**
[1.005](https://fonts.google.com/specimen/Pinyon+Script?query=Pinyon#standard-styles) 

**New available version:**
1.007

**Super short description of the upgrade:**
Expand glyphset + kerning

**Font preview**
<img width="1087" alt="Capture d’écran 2022-05-16 à 16 24 43" src="https://user-images.githubusercontent.com/64773544/168615246-98c6c71f-97b8-4f09-993c-8ca22ff0beb8.png">

**Comment by EbenSorkin** [comment]
Hi! This font is ready for merging now that the kerning is complete.

Cheers!

-e.

**Comment by emmamarichal** [comment]
Hi @EbenSorkin, perfect, thanks a lot! 👍 
Cheers!

**Comment by EbenSorkin** [comment]
I updated this font today.

https://github.com/SorkinType/Calistoga

I think it is also ready like Pinyon but for some odd reason that I can't
seem to discover the badges are broken.

Should I try remaking this from the first steps or are the badges to needed
for bring this to GF sandbox?

-e.
