### ISSUE TITLE
.loclPLN have to be .loclPLK

### ISSUE THREAD

**Issue by davelab6** [google/fonts#468]
@alexeiva please update the glyph sets as `.loclPLN` should be `.loclPLK` according to @falthausen via Georg :)

Thanks @falthausen for reporting

**Comment by davelab6** [comment]
This is partially addressed in https://github.com/google/fonts/pull/467

**Comment by alexeiva** [comment]
That's right, thank you. `.loclPLK` is not in any glyph set, just in the recommended section. 

We can merge in @falthausen [PR](https://github.com/google/fonts/pull/467) after he signes CLA. 
https://msdn.microsoft.com/en-us/library/ee825488(v=cs.20).aspx

**Comment by alexeiva** [comment]
This has been fixed in eb58ae36a4b70369d9e48c1a4c00f337d8e43012.
