### ISSUE TITLE
Update Kumbh Sans with contrast axis

### ISSUE THREAD

**Issue by RosaWagner** [google/fonts#4696]
upstream repo: https://github.com/xconsau/KumbhSans

![p1](https://user-images.githubusercontent.com/12222436/169329613-a6369b48-dc71-40e8-ad6a-5c9da2cc69b7.jpg)

**Comment by RosaWagner** [comment]
I need confirmation that we don't need to register a new axis for the font, but would use the YOPQ axis (https://github.com/googlefonts/axisregistry/blob/main/Lib/axisregistry/data/y_opaque.textproto)

cc @davelab6 @chrissimpkins

**Comment by xconsau** [comment]
Thanks for looking into this, Rosalie. The current (proposed) axis is Contrast Geometric (CTGO) with range 0-100. If we use YOPQ (which also seems almost close to what results we have with the current axis), then the range need to be changed from -2000 to 1000 with 166 as default.

**Comment by vv-monsalve** [comment]
HI @xconsau,
From what I see on `KumbhSans[CTGO,wght].ttf`, the range used in the font (8--72) is already covered by the `YOPQ - Thin Stroke` parametric axis (-1000--2000), so it wouldn't be an issue.
Otoh, the *default_value* (166) could be overridden in the METADATA.pb file of the font. So `YOPQ` axis seems to work fine for Kumbh Sans.

**Comment by xconsau** [comment]
Thanks for the heads up, @vv-monsalve. So, am I required to only rename the axis in source file as `YOPQ` and generate the var ttf as `KumbhSans[YOPQ,wght].ttf` ?

Also, thank you for the information about `METADATA.pb` file. I was not aware of this method and was searching across Fonttools documentation for a way for overriding axes and ranges post production.

**Comment by davelab6** [comment]
Sounds good everyone

**Comment by vv-monsalve** [comment]
> Also, thank you for the information about METADATA.pb file. I was not aware of this method and was searching across Fonttools documentation for a way for overriding axes and ranges post production.

The `default_value` is the only one that could be overridden for the time being.

**Comment by xconsau** [comment]
Thanks @davelab6 and @vv-monsalve .

@RosaWagner, should I change the axis name in source file and generate new ttf? Or it will be handled at your end.

**Comment by RosaWagner** [comment]
Yes @xconsau you can rename the axis and generate ttf, I'll QA and onboard ;)

**Comment by xconsau** [comment]
Sorry for the delay, @RosaWagner . Apart from the axis name change, it was required to add some new glyphs as per latest GF Latin Core glyph requirements. I have added new glyphs and renamed the axis. The VF is [here](https://github.com/xconsau/KumbhSans/blob/master/fonts/variable/KumbhSans%5BYOPQ%2Cwght%5D.ttf)

Fontbakery shows some errors related to YOPQ range defaults. Current range is 8-72 mapped as 0-100. The default value is the maximum value only.

**Comment by xconsau** [comment]
@RosaWagner Any update on the QA please?

**Comment by RosaWagner** [comment]
AH sorry, I didn't see your previous notification, will look at it today

**Comment by RosaWagner** [comment]
@dberlow we would need confirmation from you on this project. We decided to go with YOPQ axis to avoid registering a new axis that would do almost the same thing, although the axis is not fully parametric in this project. Indeed, whilst YOPQ decreases here, it also slightly tighten the glyph width to compensate the lost of "black". Is it something that you would accept as part of the YOPQ axis?


https://user-images.githubusercontent.com/12222436/205296701-a119122d-8dfd-43eb-9035-cc1a77bfdff1.mov

**Comment by dberlow** [comment]
@RosaWagner maintaining a the glyph's side bearings to compensate for the lost of "black" is what I would expect as part of the YOPQ axis, and this changes the width of such glyphs. So I' would accept this as an YOPQ axis if it's consistently applied to all the glyphs.

**Comment by RosaWagner** [comment]
@dberlow great, thank you!

**Comment by xconsau** [comment]
Thanks very much, Sir @dberlow for your time and feedback on the issue.

Thank you @RosaWagner for the technical QA and moving the update forward.
