### ISSUE TITLE
Contribute question:

### ISSUE THREAD

**Issue by s-a** [google/fonts#47]
Does the info in https://github.com/google/fonts/blob/master/designers have to point to Google plus?  I d like to link my github profile instead.

Do I only need to commit the ```.ttf``` fileformat?

**Comment by davelab6** [comment]
> I d like to link my github profile instead.

I think a github profile is okay, G+ was good as it was (less likely ) to result in 404-style errors. 

> Do I only need to commit the .ttf fileformat?

Yes, but ideally there should be full sources in your own github repo, and a link in the description file :)
