### ISSUE TITLE
Add Braah

### ISSUE THREAD

**Issue by artandtype** [google/fonts#4702]
**[Font Project Git Repo URL:](https://github.com/ashishdes/Braah)**

**An absolute mix of boldness and playfulness. Braah is a friendly display typeface, available in Gurmukhi script along with a Latin counterpart.**

**Requirements:**

I understand that Google Fonts will publish only fonts that matches its requirements, and I can confirm the project meets them (by ticking the cases, or putting x between the square brackets in text mode):

- [x] The entire font project is licensed under the [OFL](https://scripts.sil.org/cms/scripts/page.php?site_id=nrsi&id=OFL)
- [x] There is no "Reserved Font Name" mention in the OFL license
- [x] Family name is unique according to namecheck.fontdata.com
- [x] The font supports at least [GF Latin Core glyphset](https://github.com/googlefonts/glyphsets/tree/main/GF_glyphsets/Latin/)
- [ ] The repository respect the [upstream repo structure](https://github.com/googlefonts/gf-docs/tree/main/Spec#upstream-repo-structure)
- [x] The source files are available in the repository
- [x] I read, agree and comply with the full [contributing requirements](https://github.com/google/fonts/blob/main/CONTRIBUTING.md)
- [x] I am the author of the font or the author agreed to this submission
- [x] I will maintain the repository

**Image:**
![Braah specimen2-06](https://user-images.githubusercontent.com/60364133/169643744-04357006-4cd8-4c84-bd92-8cc90cca177f.jpg)
![Braah specimen2-07](https://user-images.githubusercontent.com/60364133/169643782-d2088093-8468-4926-9077-ca3c84bcad7d.png)

Attach here a pic or a screenshot of the font; one is enough, it can be few letters, to give a quick overview.

**Comment by davelab6** [comment]
Amazing! Very happy to host this!

**Comment by ashishdes** [comment]
Hello, 
I am just following up to check if anything is required from my end.

Thank you!

**Comment by davelab6** [comment]
@ashishdes things have been slow here due to summer holidays. I hope we can provide feedback in September :)

**Comment by ashishdes** [comment]
Hello @yanone, I have updated the repository with the latest ttf. 
1 FAIL is still there, please help me to resolve that.

Report link: https://github.com/ashishdes/Braah/issues/1
 
Thanks

**Comment by yanone** [comment]
Apologies for the late response. I will look at this in the coming few days.
