### ISSUE TITLE
Update Exo 2

### ISSUE THREAD

**Issue by therealrwoodson** [google/fonts#4704]
**Font Project Git Repo URL:**
https://github.com/NDISCOVER/Exo-2.0

**Current version:**
2.00 (downloaded files say 2.001 but they aren't matching the fixes available in Git Repo) https://fonts.google.com/specimen/Exo+2

**New available version:**
2.001

**Super short description of the upgrade:**
The version available on Google Fonts breaks when being rendered in certain apps, revealing the overlaps. The version updated on github solves the issue.

**Bugs reported in this repo which this upgrade would fix:**

**Comment by RosaWagner** [comment]
Hi, we thought that you were refeering to an actual upgrade but GF is distributing the proper version already. GF distributes a variable font that is having overlapping outlines and static version are generated from it. If you want a version with merged outlines, then you must use the static fonts in the repository. This is not a GF issue.
