### ISSUE TITLE
Source Sans Pro light not working correctly

### ISSUE THREAD

**Issue by GertjanRoke** [google/fonts#471]
I'm using Source Sans Pro on a website and I found out that there is no difference between the font-weight: 400 and 200.

(In the following text I'm talking about "docs", I'm referring to the follow page: https://fonts.google.com/specimen/Source+Sans+Pro?selection.family=Source+Sans+Pro:200,300,400,600 )

In the docs you clearly see a difference between the font-weights 400 and 200.

But when I use that font-family and include the fonts using the <link> tag, I don't get a difference between font-weight 400 and 200 like it has been shown in the docs.

Is this a bug? or is it my Chrome browser that is not working correctly?

Hope it's a clear story.

**Comment by davelab6** [comment]
@GertjanRoke thanks for filing this issue. 

In that fonts.google.com link, you have "customized" the link to include the 200:

![screen shot 2016-12-06 at 13 04 29](https://cloud.githubusercontent.com/assets/261579/20937336/88ddf532-bbb4-11e6-882d-50392490bc78.png)

So I guess that your `<link>` also includes the specification of the weights, eg

    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:200,300,400,600" rel="stylesheet">

When I do, this it work for me:

https://jsbin.com/setoji/edit?html,output 

![screen shot 2016-12-06 at 13 18 29](https://cloud.githubusercontent.com/assets/261579/20937802/818e36b4-bbb6-11e6-8acf-945a482a3cfb.png)

Could you provide the URL of the page you are seeing this?

**Comment by GertjanRoke** [comment]
Hello,

Thanks for replying, I'm checking it agean and it seems to work fine now. maybe it was a cache issue.
