### ISSUE TITLE
Update Familjen Grotesk

### ISSUE THREAD

**Issue by ktkm** [google/fonts#4732]
**Font Project Git Repo URL:** https://github.com/Familjen-Sthlm/Familjen-Grotesk

**Current version:** 2.000

**New available version:** 2.001

**Super short description of the upgrade:**
- dotaccentcomb_macroncomb no longer uses the dotaccentcomb as a component.
- Ellipsis interpolation master incompatible in Familjen Grotesk 2.000 and concerns the weights Medium and SemiBold (Italic excluded).

**Bugs reported in this repo which this upgrade would fix:**
- https://github.com/Familjen-Sthlm/Familjen-Grotesk/issues/3
- https://github.com/Familjen-Sthlm/Familjen-Grotesk/issues/4

**Comment by ktkm** [comment]
@emmamarichal I have e-mailed you as well.

**Comment by emmamarichal** [comment]
Thanks, I'll do that today! :)
