### ISSUE TITLE
Unable to load multiple font families using '&text' in the url using the variable fonts api

### ISSUE THREAD

**Issue by jbcortez** [google/fonts#4744]
When trying to load individual characters of multiple families in one link tag, none of the fonts are being loaded. 

For example:
https://fonts.googleapis.com/css2?family=Karla&text=Karla&family=Heebo&text=Heebo -- DOESN'T WORK
https://fonts.googleapis.com/css2?family=Karla&text=Karla -- WORKS
https://fonts.googleapis.com/css2?family=Karla&family=Heebo -- WORKS

Am I doing this incorrectly, or does it just not work?

**Comment by garretrieger** [comment]
the 'text' parameter can only be specified once and it applies to all families in the request. So in the first example the first text="Karla" will be used to subset both Heebo and Karla. The solution is to do something like a single ...&text=KarlaHeebo... or have two separate CSS api links, one per family.

**Comment by davelab6** [comment]
We should add this to the API docs before closing

**Comment by RosaWagner** [comment]
@davelab6 @garretrieger has it been added to the API doc? Can I close this issue?

**Comment by davelab6** [comment]
It's https://developers.google.com/fonts/docs/css2

**Comment by chrissimpkins** [comment]
I opened the documentation update CL.  I'll close this issue when it is published.

**Comment by chrissimpkins** [comment]
The documentation update is live in production on https://developers.google.com/fonts/docs/css2
