### ISSUE TITLE
No ellipsis for Amaranth

### ISSUE THREAD

**Issue by Iggyblogue** [google/fonts#475]
Horizontal ellipsis (U+2026) is missing for the beautiful Amaranth font.

**Comment by davelab6** [comment]
@Iggyblogue thanks for reporting

**Comment by m4rc1e** [comment]
Can confirm.

![screen shot 2017-06-16 at 11 19 22](https://user-images.githubusercontent.com/7525512/27222810-ad2f8bc2-5285-11e7-84a5-200483726475.png)

**Comment by m4rc1e** [comment]
Can confirm its fixed, http://jsbin.com/yexinacala/edit?html,output

![screen shot 2017-08-31 at 10 28 29](https://user-images.githubusercontent.com/7525512/29916625-36964166-8e37-11e7-9bac-44da15c8c595.png)

Family updated on 2017-08-24
