### ISSUE TITLE
OpenDyslexic

### ISSUE THREAD

**Issue by mlong007** [google/fonts#4750]
**Font Project Git Repo URL:**
https://github.com/antijingoist/open-dyslexic

**Super short description of the Font Family:**
Typeface/font to help readability, and help readability for some of the symptoms of dyslexia

**Requirements:**

I understand that Google Fonts will publish only fonts that matches its requirements, and I can confirm the project meets them (by ticking the cases, or putting x between the square brackets in text mode):

- [x] The entire font project is licensed under the [OFL](https://scripts.sil.org/cms/scripts/page.php?site_id=nrsi&id=OFL)
- [x] There is no "Reserved Font Name" mention in the OFL license
- [x] Family name is unique according to namecheck.fontdata.com
- [ ] The font supports at least [GF Latin Core glyphset](https://github.com/googlefonts/glyphsets/tree/main/GF_glyphsets/Latin/)
- [ ] The repository respect the [upstream repo structure](https://github.com/googlefonts/gf-docs/tree/main/Spec#upstream-repo-structure)
- [ ] The source files are available in the repository
- [ ] I read, agree and comply with the full [contributing requirements](https://github.com/google/fonts/blob/main/CONTRIBUTING.md)
- [ ] I am the author of the font or the author agreed to this submission
- [ ] I will maintain the repository

**Image:**

Attach here a pic or a screenshot of the font; one is enough, it can be few letters, to give a quick overview.
![Screenshot 2022-06-07 123608](https://user-images.githubusercontent.com/73477817/172287099-12a12864-8952-46cd-8773-d1d35c0b7741.jpg)

**Comment by n8willis** [comment]
I expect that someone will point out https://github.com/google/fonts/issues/558 where shortfalls of this sort of letterform-driven experimentation have been discussed in pretty good detail, but I feel like it's also worth pointing out that the font in question here does actually use an RFN on its font name: https://github.com/antijingoist/opendyslexic/blob/e7ac50af1aabb8cb0fbf81db105f21f81fbb5284/OFL.txt#L2

**Comment by mlong007** [comment]
Thank you for the comments, it was a very interesting read, and due to the font being restricted, I will close this case.

Thanks again.
