### ISSUE TITLE
Minecraft Fonts. 

### ISSUE THREAD

**Issue by MarianneL1** [google/fonts#4757]
**Font Project Git Repo URL:**

/Users/marianneleongschool/Downloads
**Super short description of the Font Family:**
I found this font online and downloaded it I am hoping to add it to google fonts for the minecraft lovers. 
**Requirements:**

I understand that Google Fonts will publish only fonts that matches its requirements, and I can confirm the project meets them (by ticking the cases, or putting x between the square brackets in text mode):

- [ ] The entire font project is licensed under the [OFL](https://scripts.sil.org/cms/scripts/page.php?site_id=nrsi&id=OFL)
- [ ] There is no "Reserved Font Name" mention in the OFL license
- [x] Family name is unique according to namecheck.fontdata.com
- [ ] The font supports at least [GF Latin Core glyphset](https://github.com/googlefonts/glyphsets/tree/main/GF_glyphsets/Latin/)
- [ ] The repository respect the [upstream repo structure](https://github.com/googlefonts/gf-docs/tree/main/Spec#upstream-repo-structure)
- [ ] The source files are available in the repository
- [ ] I read, agree and comply with the full [contributing requirements](https://github.com/google/fonts/blob/main/CONTRIBUTING.md)
- [ ] I am the author of the font or the author agreed to this submission
- [ ] I will maintain the repository

**Image:**
<img width="420" alt="Minecraft font image" src="https://user-images.githubusercontent.com/107180426/172811842-9db18168-7504-4f66-86e1-8613e3dfd28f.png">

Attach here a pic or a screenshot of the font; one is enough, it can be few letters, to give a quick overview.

**Comment by Crimsn64** [comment]
That's very clearly not the same font
Here is the preview @MarianneL1 used
<img width="840" alt="Image" src="https://github.com/user-attachments/assets/2a2ac0ea-28cd-423b-acdb-7ed54b5957c6" />

Here's the same text using the font @RosaWagner mentioned
![Image](https://github.com/user-attachments/assets/f50a73a9-5a0d-44ef-830b-88d1cb2957fa)

Yes, both are pixel-esque but they are not the same font
Here is a Minecraft Wiki Article about the Minecraft font @MarianneL1 is referencing: [Mojangles](https://minecraft.wiki/w/Mojangles)

**Comment by emmamarichal** [comment]
Hi @Crimsn64, we still need a github repo with the font sources inside, so we can review it (.glyphs or .ufo).
