### ISSUE TITLE
Advent Pro Kerning Issue

### ISSUE THREAD

**Issue by davelab6** [google/fonts#476]
> Advent Pro font has a kerning problem, specially the all caps words

https://twitter.com/gturbiani/status/799569398319157248

**Comment by amandamcg** [comment]
Here are other examples of the kerning issues.
<img width="226" alt="screen shot 2017-04-05 at 2 10 06 pm" src="https://cloud.githubusercontent.com/assets/8716226/24727103/a0defc90-1a09-11e7-8703-72b416d3d794.png">
<img width="113" alt="screen shot 2017-04-05 at 2 10 03 pm" src="https://cloud.githubusercontent.com/assets/8716226/24727105/a0f33f20-1a09-11e7-8cf0-de4d5ccc00c7.png">

**Comment by m4rc1e** [comment]
Confirmed, thanks @amandamcg 

![screen shot 2017-06-16 at 12 01 15](https://user-images.githubusercontent.com/7525512/27224159-8b1d1c2e-528b-11e7-945e-ec6ad0465d30.png)

http://jsbin.com/vovuhucuki/edit?html,output

**Comment by laerm0** [comment]
So it appears that the issue here is not just kerning, but poor spacing, not just in the caps. It's my inclination to fix the spacing, blow up the kerning, and start over with a light kern. Your thoughts, @davelab6?

**Comment by laerm0** [comment]
PR created (just QU kerning in this fix)

**Comment by davelab6** [comment]
> So it appears that the issue here is not just kerning, but poor spacing, and not just in the caps. It's my inclination to fix the spacing, blow up the kerning, and start over with a light kern. Your thoughts, @davelab6?

While the whole font needs a type designer to spend 3-10 days on it, this bug is just about the letter collision caused by the Q right side, so please just fix that :)
