### ISSUE TITLE
Create a curated list of "interesting" families to run when testing compilers

### ISSUE THREAD

**Issue by rsheeter** [google/fonts#4772]
As we begin to contemplate a faster compiler I want to get a good set of families to test it. In attempting to locate families via the upstream.yaml file I end up with 96 families with what looks like config files for gfbuilder from an initial 386 upstream.yaml files, see https://github.com/googlefonts/oxidize/issues/25#issuecomment-1152993157.

Please provide a curated list of families, my guess is something like 10-50, that cover a broad range of compile scenarios and are buildable by cloning the repository from upstream.yaml and running gfbuilder. I suggest a CSV file in the form:

```
# path_to_family, why_interesting
ofl/acme, "Super simple latin font, as basic as it gets"
ofl/acme2, "CJK family, huge but minimal layout"
ofl/acme3, "Arabic family, very complex layout"
```

Ideally I would like to have this early Q3, say by end of July. 

EDIT: originally thought there were 53 families with config files, but that was based on the mistaken assumption familyName was required. Updated to 96.

**Comment by rsheeter** [comment]
QQ, is doing this by ~end July plausible?

**Comment by rsheeter** [comment]
Friendly ping?

**Comment by RosaWagner** [comment]
maybe @rsheeter you can give us the list of the 96 families that you have, and from that we can ask @yanone @vv-monsalve and @emmamarichal (who are onboarding most of the fonts) to give us a top 10 each of interesting builds ?

Can you confirm you need a broad variety of build cases such as:
 
- normal fonts
- normal fonts with complex features/interpolation
- custom axes
- complex script
- sibling families from same source
- Roman/italic from same source
- with manual hinting
- from UFO sources

What do you mean by complex or minimal layout? What do you call here layout?

**Comment by m4rc1e** [comment]
Families which take a long time to compile:
- Roboto Serif, https://github.com/googlefonts/roboto-serif (~1hr with fontmake)
- Google Symbols, https://github.com/googlefonts/google-symbols (~2-3hr with custom chain)
- Our NDA project which used to be managed by Chris (~15mins with fontmake

Families with multiple axes
- Roboto Flex, https://github.com/googlefonts/roboto-flex (about 12 axes in total)
- Amstelvar, https://github.com/googlefonts/amstelvar

Colr v1 families:
- https://github.com/SophiaDesign/Foldit


Complex GSUB/GPOS:
- Gulzar, https://github.com/googlefonts/Gulzar

Low Hanging fruit (static, no vf, no color):
- Send Flowers, https://github.com/googlefonts/send-flowers (single font family)

**Comment by rsheeter** [comment]
> Can you confirm you need a broad variety of build cases

Confirmed

> What do you mean by complex or minimal layout? What do you call here layout?

Minimal layout: No kerning, ligatures, complex shaping rules. A simple monospace or CJK, e.g. you advance, draw glyph, not much else.
Complex layout: hand wavily, anything with lots of stuff in GSUB/GPOS, particularly if the rules are complex, involve multiple glyphs or are contextual. Indix or Arabic fonts typically qualify. To my understanding Gulzar is on the extreme end of how complex we get with layout. I would expect we have some that are complex but not that complex.

Does that adequately answer?

**Comment by vv-monsalve** [comment]
Added a couple of items to Marc's above list

**Comment by rsheeter** [comment]
Oh sorry, yes indeed. Thank you @m4rc1e and @vv-monsalve.
