### ISSUE TITLE
Mac Pop EX Font

### ISSUE THREAD

**Issue by macin23** [google/fonts#4775]
**Font Project Git Repo URL:** [Mac Pop EX.zip](https://github.com/google/fonts/files/8885760/Mac.Pop.EX.zip)

**Super short description of the Font Family:**
It is a Mac Pop EX Font for Cool Styles for **sans-serif**

**Requirements:**

I understand that Google Fonts will publish only fonts that matches its requirements, and I can confirm the project meets them (by ticking the cases, or putting x between the square brackets in text mode):

- [x] The entire font project is licensed under the [OFL](https://scripts.sil.org/cms/scripts/page.php?site_id=nrsi&id=OFL)
- [ ] There is no "Reserved Font Name" mention in the OFL license
- [x] Family name is unique according to namecheck.fontdata.com
- [ ] The font supports at least [GF Latin Core glyphset](https://github.com/googlefonts/glyphsets/tree/main/GF_glyphsets/Latin/)
- [ ] The repository respect the [upstream repo structure](https://github.com/googlefonts/gf-docs/tree/main/Spec#upstream-repo-structure)
- [x] The source files are available in the repository
- [ ] I read, agree and comply with the full [contributing requirements](https://github.com/google/fonts/blob/main/CONTRIBUTING.md)
- [x] I am the author of the font or the author agreed to this submission
- [x] I will maintain the repository

**Image:**
![Screenshot 2022-06-12 173217](https://user-images.githubusercontent.com/74599728/173232175-3a9f9295-73e9-44e6-9c89-0adc7f043fab.png)

**Comment by RosaWagner** [comment]
Hi, thanks for your submission. I un-ticked the requirements which were not fulfilled. Please read them carefully and feel free to re-open this issue once the project matches them all :)
