### ISSUE TITLE
cookierun font

### ISSUE THREAD

**Issue by cookierunfont** [google/fonts#4776]
**Font Project Git Repo URL:**
https://www.cookierunfont.com/#section1

**Super short description of the Font Family:**

Cookie Run font is a font that contains the unique identity of Cookie Run, which is cute and challenging.
The Cookie Run font, which supports the Latin alphabet and Korean, is used throughout communication such as games, characters, and advertisements.
Cookie Run's unique concept and identity will be maintained and harmonized in any field.
The formative characteristics of cute and unique cookies and the rounded, bold impression were reflected in the font as a design principle.

**Requirements:**

I understand that Google Fonts will publish only fonts that matches its requirements, and I can confirm the project meets them (by ticking the cases, or putting x between the square brackets in text mode):

- [x] The entire font project is licensed under the [OFL](https://scripts.sil.org/cms/scripts/page.php?site_id=nrsi&id=OFL)
- [x] There is no "Reserved Font Name" mention in the OFL license
- [x] Family name is unique according to namecheck.fontdata.com
- [x] The font supports at least [GF Latin Core glyphset](https://github.com/googlefonts/glyphsets/tree/main/GF_glyphsets/Latin/)
- [ ] The repository respect the [upstream repo structure](https://github.com/googlefonts/gf-docs/tree/main/Spec#upstream-repo-structure)
- [ ] The source files are available in the repository
- [ ] I read, agree and comply with the full [contributing requirements](https://github.com/google/fonts/blob/main/CONTRIBUTING.md)
- [x] I am the author of the font or the author agreed to this submission
- [x] I will maintain the repository

**Image:**
 
<img width="1247" alt="스크린샷 2022-06-13 오후 12 27 17" src="https://user-images.githubusercontent.com/107380896/173276077-e40d5cee-30cf-4f1b-9767-650e6113cf5b.png">
<img width="1246" alt="스크린샷 2022-06-13 오후 12 27 25" src="https://user-images.githubusercontent.com/107380896/173276083-b9f02b24-6f8e-4c22-9736-3a0f64f4611a.png">
<img width="1251" alt="스크린샷 2022-06-13 오후 12 27 31" src="https://user-images.githubusercontent.com/107380896/173276091-9702b3b1-6f20-423a-bda3-8d02f994d2e1.png">
<img width="1244" alt="스크린샷 2022-06-13 오후 12 27 35" src="https://user-images.githubusercontent.com/107380896/173276093-c88ac0f9-6336-4cf4-9297-4a6c526de864.png">
<img width="1246" alt="스크린샷 2022-06-13 오후 12 27 38" src="https://user-images.githubusercontent.com/107380896/173276096-f8c4638b-6934-49c4-8b6f-56977d0297f7.png">
<img width="1252" alt="스크린샷 2022-06-13 오후 12 27 43" src="https://user-images.githubusercontent.com/107380896/173276097-052291d0-91f9-4802-8e29-f8b1d09a9ff7.png">

Attach here a pic or a screenshot of the font; one is enough, it can be few letters, to give a quick overview.
[StoryBook_CookieRunTypeface_11.16.pdf](https://github.com/google/fonts/files/8887688/StoryBook_CookieRunTypeface_11.16.pdf)

**Comment by RosaWagner** [comment]
Hi, thanks for the submission. I un-ticked the requirements that were not fulfilled. Unfortunately we can't review the font without actual binaries nor sources. Please read the contributing requirements carefully and feel free to re-open this issue when your project matches them :)

**Comment by cookierunfont** [comment]
Upload a file.
Are there any areas that need to be checked?
[CookieRunFont_TTF.zip](https://github.com/google/fonts/files/8945111/CookieRunFont_TTF.zip)
[CookieRunFont_OTF.zip](https://github.com/google/fonts/files/8945109/CookieRunFont_OTF.zip)
