### ISSUE TITLE
Fonts archive does not unzip

### ISSUE THREAD

**Issue by samjhill** [google/fonts#4788]
**Describe the issue**

When I attempt to download and unzip the fonts archives, they do not unzip successfully.
<img width="368" alt="Screen Shot 2022-06-15 at 9 51 41 AM" src="https://user-images.githubusercontent.com/1424050/173844308-fc797317-41cb-4000-b189-4cc1505b07b2.png">

I've tried both https://github.com/google/fonts/archive/main.tar.gz and https://github.com/google/fonts/archive/main.zip.

<img width="569" alt="Screen Shot 2022-06-15 at 9 56 44 AM" src="https://user-images.githubusercontent.com/1424050/173845347-616d03ea-f628-4a15-855a-113de88d4892.png">

**To Reproduce**

```shell
wget https://github.com/google/fonts/archive/main.tar.gz 
tar -xf main.tar.gz 
```

**Workarounds**
~~I'm able to work around this issue by excluding the `ofl/yeonsung` folder during unzip:~~

I thought this workaround would work, but it only works locally, not in GHA.

```shell
 tar -xf main.tar.gz --exclude="ofl/yeonsung/*"
```

**Expected behavior**
The folder unzips successfully

**Additional context**
I see the issue on both Mac OSX and Docker python:3.7-alpine

Thank you in advance for your help!

**Comment by travist** [comment]
Same issue here. This is currently breaking our automated builds so would like to see a resolution.

**Comment by m4rc1e** [comment]
Just recieved:

> Rick (GitHub Support)
Jun 16, 2022, 5:34 PM UTC​​Hi
Marc,Thank you for writing in! I'm sorry you have experienced this problem.
> I’ve escalated your report to our engineering team for further investigation.
> While we don’t yet have a specific ETA, we’ll be sure to update you if there’s any news to share.All the best,RickGitHub Support

**Comment by m4rc1e** [comment]
All fixed! thanks Github!
