### ISSUE TITLE
Baloo Bhaijaan 2: يخ when in bold the second one is in normal instead of bold

### ISSUE THREAD

**Issue by abdelhakim-hoopow** [google/fonts#4804]
Specify the font name in title with a short description of the bug. 
Please report any issue related to Noto fonts in this repository: https://github.com/googlefonts/noto-fonts/issues.

**Describe the bug**
If a word in bold is ending with  يخ , the entire is in bold as expected except the خ.

**To Reproduce**
It can be easily reproduce when you write the word بِطّيخٌ in bold.

**Expected behavior**
We expect to have the entire word in bold.

**Screenshots**
<img width="1065" alt="image" src="https://user-images.githubusercontent.com/80564957/174338650-681c9606-7445-41f0-afeb-266fbb523ab0.png">

**Additional context**
No need

**Comment by RosaWagner** [comment]
@yanone when you come back from holidays ;)
