### ISSUE TITLE
Isolated lam-alef ligature is not formed in Noto Kufi Arabic

### ISSUE THREAD

**Issue by khaledhosny** [google/fonts#4811]
**Describe the bug**
The isolated lam-alef ligature is not formed in Noto Kufi Arabic

**To Reproduce**
Check:
https://fonts.google.com/noto/specimen/Noto+Kufi+Arabic?query=noto+kufi&preview.text=%D9%84%D8%A7%20%D8%A8%D9%84%D8%A7&preview.text_type=custom

**Expected behavior**
Lam-alef ligature is a required ligature and should be formed all the time.

**Screenshots**
Rendering on fonts.google.com:
![](https://user-images.githubusercontent.com/93914/174662444-62dbadc9-1a96-4045-9602-938363adada6.png)

Expected rendering:
![a](https://user-images.githubusercontent.com/93914/174662813-ef9b36a4-de4c-4953-9767-ee1fd722bbea.png)

**Comment by khaledhosny** [comment]
I don’t know what subsetter is used, but I can’t reproduce this with either `hb-subset` or `fonttools subset`. cc @garretrieger

**Comment by garretrieger** [comment]
Don't think this is subsetter related. I believe the issue is that the copy of Noto Kufi Arabic we are serving on fonts.google.com is outdated. I can reproduce the issue on our unsubstted internal copy of the font. I'll get our copy updated.
