### ISSUE TITLE
Missing i's in Libre Baskerville

### ISSUE THREAD

**Issue by International-DBA** [google/fonts#4812]
I believe there may be an issue with Libre Baskerville.
I have documented it here:
https://andrews-python-blog.blogspot.com/2022/06/there-are-no-is-in-libre-baskerville.html

FYI: I have a workaround. I used Roboto instead and that seems fine.

**Comment by RosaWagner** [comment]
I just opened the font and used it locally and from the API, and there is a lowercase /i in it. So closing this since it might come  for your script.
