### ISSUE TITLE
Add Figtree

### ISSUE THREAD

**Issue by erikdkennedy** [google/fonts#4817]
**Font Project Git Repo URL:**
https://github.com/erikdkennedy/figtree

**Super short description of the Font Family:**
A friendly geometric sans serif, meant for UI designers who'd otherwise be reaching yet again for Montserrat or pirating Circular.

**Requirements:**
fontbakery
gftools

I understand that Google Fonts will publish only fonts that matches its requirements, and I can confirm the project meets them (by ticking the cases, or putting x between the square brackets in text mode):

- [x] The entire font project is licensed under the [OFL](https://scripts.sil.org/cms/scripts/page.php?site_id=nrsi&id=OFL)
- [x] There is no "Reserved Font Name" mention in the OFL license
- [x] Family name is unique according to namecheck.fontdata.com
- [x] The font supports at least [GF Latin Core glyphset](https://github.com/googlefonts/glyphsets/tree/main/GF_glyphsets/Latin/)
- [x] The repository respect the [upstream repo structure](https://github.com/googlefonts/gf-docs/tree/main/Spec#upstream-repo-structure)
- [x] The source files are available in the repository
- [x] I read, agree and comply with the full [contributing requirements](https://github.com/google/fonts/blob/main/CONTRIBUTING.md)
- [x] I am the author of the font or the author agreed to this submission
- [x] I will maintain the repository

**Image:**
<img width="830" alt="sample" src="https://user-images.githubusercontent.com/3440839/174744949-4d09e2f1-1da9-432b-8098-782c2f23ed6c.png">

**Comment by fitojb** [comment]
(I love the terseness and honesty of your “super short description” :P. Your design is very nice as well, with nicely proportioned glyphs and well-drawn curves. AND it has a personality, unlike what they did to Montserrat! Congrats!!)
