### ISSUE TITLE
Update Vazirmatn

### ISSUE THREAD

**Issue by rastikerdar** [google/fonts#4830]
Font Project Git Repo URL: https://github.com/rastikerdar/vazirmatn

Current version: 32.102

New available version: 33.003

Super short description of the upgrade:
More glyphs, improved design, bug fixes.

https://github.com/google/fonts/pull/4352#issuecomment-1164295595

**Comment by emmamarichal** [comment]
Hello @rastikerdar,
I work on the google fonts onboarding, and I just had a look to your font.
I run a fontbakery on the fonts to see if everything was ok, but this fail seems problematic, especially in the case of an arabic font: 

> 🔥 FAIL: Ensure dotted circle glyph is present and can attach marks. ([com.google.fonts/check/dotted_circle](https://font-bakery.readthedocs.io/en/stable/fontbakery/profiles/universal.html#com.google.fonts/check/dotted_circle))
> 🔥 FAIL The following glyphs could not be attached to the dotted circle glyph:
> uni030F
> tildecomb
> dotbelow
> gravecomb
> acutecomb
> And hook [code: unattached-dotted-circle-marks]
> 

The thing is, this fail also points out that the accents used are legacy accents and not combining accents (which is recommended).
I think the current accents should be replaced by combining accents (see: [https://googlefonts.github.io/gf-guide/diacritics.html](https://googlefonts.github.io/gf-guide/diacritics.html))
What do you think @RosaWagner?

**Comment by rastikerdar** [comment]
Hello,
This font was accepted with this `fontbakery` report. In fact, the font already has this symbol and there is no problem with the Arabic marks attached to it. Since this is an Arabic font, Latin marks will never be used for this symbol. However, I do not know if this is still acceptable with your policy. 
![Screenshot at 2022-06-24 19-32-36](https://user-images.githubusercontent.com/3116038/175563212-668456d6-db86-47d6-ae90-856cdfc294c1.png)

https://github.com/google/fonts/pull/4352
https://github.com/rastikerdar/vazirmatn/issues/231#issuecomment-1059277003
