### ISSUE TITLE
Noto Sans CJK cannot be found.(From:Japan)

### ISSUE THREAD

**Issue by Kima-00** [google/fonts#4849]
From Japan

The download page for "Noto sans CJK SC" is
I can't find it by searching Google fonts.

https://www.google.com/get/noto/#sans-hans 

Did you have a problem with "Noto sans CJK SC"?

Do I need to change the font of the catalog I'm currently using?

**Comment by RosaWagner** [comment]
Remove CJK from the search and you'll find it; https://fonts.google.com/?query=Noto+Sans+SC&sort=date

**Comment by Kima-00** [comment]
I want to create a catalog with NotoSansCJKsc.
If there is no problem with the font, I want to use it as it is.

https://github.com/googlefonts/noto-cjk/tree/main/Sans
You can continue to download it from Github.
Why did "CJK" disappear from the top page?

Or did you change the name to NotoSansSC?

**Comment by RosaWagner** [comment]
A font containing all CJK glyphs is too heavy to be served as such by Google Fonts API. It is therefore needed to distribute subsetted versions of the font to allow website to charge them in a smaller amount of time. These sets are distributed as separated families for Noto Sans:

- Simplified Chinese (SC)
- Traditional Chinese (TC)
-  Hong Kong (HK)
- Japanese
- Korean 

But if you download any of these families from Google Fonts platform, you will get a font with the entire CJK glyphset. 

<img width="1276" alt="Capture d’écran 2022-06-30 à 12 12 30" src="https://user-images.githubusercontent.com/12222436/176653096-8241e1f4-5200-4279-9b6b-a05af98aa35a.png">


A font served by Google Fonts API is never the exact same one as the one you find in the repo.

**Comment by Kima-00** [comment]
thank you for answering.

There seems to be no problem other than the operation with the Google Fonts API, so
I will use it for catalog leaflets for a while.

I am using the officially downloaded font.
https://noto-website-2.storage.googleapis.com/pkgs/NotoSansCJKsc-hinted.zip
