### ISSUE TITLE
Add [Nouveaba Plate]

### ISSUE THREAD

**Issue by fabiorug** [google/fonts#4857]
**[Font Project Git Repo URL](https://github.com/fabiorug/Nouveaba-Plate):**

**Square, design font also for office and neurological differences**

**Requirements:**

I understand that Google Fonts will publish only fonts that matches its requirements, and I can confirm the project meets them (by ticking the cases, or putting x between the square brackets in text mode):

- [x] The entire font project is licensed under the [OFL](https://scripts.sil.org/cms/scripts/page.php?site_id=nrsi&id=OFL)
- [x] There is no "Reserved Font Name" mention in the OFL license
- [x] Family name is unique according to namecheck.fontdata.com
- [x] The font supports at least [GF Latin Core glyphset](https://github.com/googlefonts/glyphsets/tree/main/GF_glyphsets/Latin/)
- [ ] The repository respect the [upstream repo structure](https://github.com/googlefonts/gf-docs/tree/main/Spec#upstream-repo-structure)
- [ ] The source files are available in the repository
- [ ] I read, agree and comply with the full [contributing requirements](https://github.com/google/fonts/blob/main/CONTRIBUTING.md)
- [x] I am the author of the font or the author agreed to this submission
- [x] I will maintain the repository

**Image:**
![font](https://user-images.githubusercontent.com/69140751/176881726-3c437e42-6e91-4f6a-b3bb-afe2e0cc6289.png)
Attach here a pic or a screenshot of the font; one is enough, it can be few letters, to give a quick overview.

**Comment by RosaWagner** [comment]
Hi, thanks for your submission. 

Unfortunately the font doesn't comply with the requirement. It is impossible for us to give a review if source files (font editor file such .UFO or .glyphs) are missing. Re-read carefully the contributing policies, and feel free to re-open an issue when the font comply with GF requirements.

**Comment by fabiorug** [comment]
Is against to generate three ufo files from the otf?

**Comment by fabiorug** [comment]
I don't want to regenerate the file from ufo to change the name i would lose quality of the font.

**Comment by fabiorug** [comment]
All info between the font, the source, and the license should match. https://googlefonts.github.io/gf-guide/license-file.html I'm regenerating all i can with fontforge, i expect loss in quality, i would do only otf.
