### ISSUE TITLE
Update Edu fonts description

### ISSUE THREAD

**Issue by RosaWagner** [google/fonts#4858]
**Font Project Git Repo URL:**
https://github.com/MezMerrit/AU-School-Handwriting-Fonts

We should update the descriptions with the last info added to the upstream repo + the designers profile.

Description should also contain a note about the vertical metrics; they are made to match the dotted paper teachers use in Australia. Although to have caps centered, clipping the descender was inevitable. 

About authors, Corey sketches and Tina digitalised.

**Comment by vv-monsalve** [comment]
- Name change to the collection. It should be `Foundation Fonts for Australian Schools collection` instead of _Educational School Fonts collection_
