### ISSUE TITLE
Add Inter Tight

### ISSUE THREAD

**Issue by RosaWagner** [google/fonts#4869]
**Font Project Git Repo URL:**
https://github.com/rsms/inter-tight

**Super short description of the Font Family:**
A version of Inter with a tighter spacing. It is needed in Workspace.

**Image:**
![sample](https://user-images.githubusercontent.com/12222436/176999310-284edf31-adad-43e6-9f0f-cf566dd5e25e.png)

**Comment by dev-ncbao** [comment]
@RosaWagner Hi. Hi. I have a trouble when I'm using this font in Vietnamese. I don't know how to discribe it in English but I have a picture to show that.
![image](https://user-images.githubusercontent.com/100339984/197347521-9f19c4ef-baa0-4572-b074-e0f138f35aae.png)

**Comment by kenmcd** [comment]
> @RosaWagner Hi. I have a trouble when I'm using this font in Vietnamese. I don't know how to discribe it in English but I have a picture to show that. ![image](https://user-images.githubusercontent.com/100339984/197347521-9f19c4ef-baa0-4572-b074-e0f138f35aae.png)

These are interpolation issues.
The horn element has different start points in the different masters.
Same issue with other horn characters.

There is also an interpolation issue with the grave.
Which affects many other characters based on grave.

Both would need to be fixed upstream.
But there is no issue tracker in the repo linked above.

**Comment by RosaWagner** [comment]
@kenmcd thanks for reporting, please open a font bug issue with these screenshots in this repo, I'll make a fix

**Comment by kenmcd** [comment]
> @kenmcd thanks for reporting, please open a font bug issue with these screenshots in this repo, I'll make a fix

The Inter Tight repo does not have an issue tracker enabled.
Suppose I can open a bug in the main Inter repo.
Will do that.

**Comment by RosaWagner** [comment]
I meant a new issue in this repo: the google/fonts repo please

**Comment by kenmcd** [comment]
> I meant a new issue in this repo: the google/fonts repo please

OK. I will make a new issue.
