### ISSUE TITLE
Noto Sans Simplified Chinese download always failed after about 26mb downloaded

### ISSUE THREAD

**Issue by The98765theedi** [google/fonts#4914]
Noto Sans Simplified Chinese

**Describe the bug**
When try to download the font family on this page it always failed after about 26mb downloaded
https://fonts.google.com/noto/specimen/Noto+Sans+SC

**To Reproduce**
Click Download family button which redirect to
https://fonts.google.com/download?family=Noto%20Sans%20SC

**Expected behavior**
Complete download just like Noto Sans Traditional has no problem
https://fonts.google.com/noto/specimen/Noto+Sans+TC

**Additional context**
Tried Chrome and Firefox both failed to complete download.

**Comment by chrissimpkins** [comment]
I cannot reproduce the download issue with Noto Sans SC.  Is this still a problem for you?

**Comment by vv-monsalve** [comment]
I could reproduce it once under a low wifi connection, but later it worked under a higher speed connection.

@The98765theedi could you please provide the following information:

- Operative system
- Browsers version
- Internet speed

**Comment by The98765theedi** [comment]
Problem solved, I just tried download twice and successfully completed.
Thanks!

**Comment by chrissimpkins** [comment]
Thank you for confirming!
