### ISSUE TITLE
Google Drive font improperly displays unicode character “ḥ” (U+1E25) and other Arabic transliteration code points.

### ISSUE THREAD

**Issue by eliheuer** [google/fonts#4918]
I use Google Drive for an Arabic class, and have noticed that some common characters used for Arabic transliteration display in a weight not matching the other characters in the typeface used. See a screenshot below for an example showing “ḥ” (U+1E25) and “Ḍ” (U+1E0C).

<img width="339" alt="U+1E0C" src="https://user-images.githubusercontent.com/5162664/178128832-9f894ac5-1ea2-43dc-b3a8-1692ebb0778b.png">

**Comment by eliheuer** [comment]
If a list of Unicode characters used for Arabic transliteration is needed, I can compile one.

**Comment by eliheuer** [comment]
Joumana Medlej has a great Twitter thread about Arabic transliteration support for type design: https://twitter.com/joumajnouna/status/1526889160258240512?t=8IrXccsg2a-8MFHzx50-pg&s=19

![Screenshot_20220711-115632-01.jpeg](https://user-images.githubusercontent.com/5162664/178338206-c2876f24-3a7a-44ba-80c4-0a9e5f875fa1.jpeg)

**Comment by moyogo** [comment]
ʾ U+02BE and ʿ U+02BE can be useful if they are designed to be large enough. They should pretty much as large as ʔ U+0294 and ʕ U+0295 without the vertical stem or as lasrge as ᵓ U+1D53 and ᶜ U+1D9C.

**Comment by vv-monsalve** [comment]
Hi @eliheuer are you referring to a particular font? Or are you proposing to include a new Glyphset for Arabic transliteration?

Have you checked this one? https://github.com/googlefonts/glyphsets/blob/main/GF_glyphsets/TransLatin/txt/nice-names/GF_TransLatin_Arabic.txt

On the other hand, depending on the selected font, you could always use the `combining marks` on it, type the base letter, and then insert the mark from an `Emojis & Symbols` panel to get the desired combination.

<img width="1130" alt="Screen Shot 2022-07-12 at 18 46 22" src="https://user-images.githubusercontent.com/48698976/178616843-49ced636-8ca4-432d-bea2-9fbd28f2d859.png">

**Comment by eliheuer** [comment]
Thanks, I opened this to report a specific visual typography bug in a Google product, figuring this was the best chance at getting it fixed. Please close this issue if nothing can be done.

I'll try to close this myself soon if no one else does it first.

**Comment by fitojb** [comment]
You filed a Google Drive issue to the Google Fonts team. Pretty much off-topic, yeah.

You have issuetracker.google.com for other products.
