### ISSUE TITLE
ofl/mplus1p: Filenames in METADATA.pb file do not match filesystem

### ISSUE THREAD

**Issue by nathan-williams** [google/fonts#4952]
**Describe the bug**
Filenames in METADATA.pb file do not match filesystem

**Expected behavior**
Filenames cited in METADATA.pb should match the actual filenames in the filesystem.

**Comment by davelab6** [comment]
The filename and metadata values should match, but it's not always the case that the metadata values are wrong.

**Comment by chrissimpkins** [comment]
@RosaWagner @vv-monsalve D/W Dave, Andy, and Nate.  The goal is consistency across file and family names and IIUC we should use the following approach as defined by Dave in https://github.com/google/fonts/pull/4841#issuecomment-1172938800:

- Font file names: `MPLUS1p-Regular.ttf`, `MPLUS1p-Medium.ttf`, ... (same approach for the rest of the family styles)
- Family name: `M PLUS 1p`

Will you please submit a new PR with changes to make the file paths, file path strings listed in METADATA.pb, and family name consistent with the definitions that I listed above? Ty!

**Comment by vv-monsalve** [comment]
Done in #4976
