### ISSUE TITLE
Update Noto CJK

### ISSUE THREAD

**Issue by pkj-l** [google/fonts#4959]
**Font Project Git Repo URL:** https://github.com/googlefonts/noto-cjk

**Current version:** Noto Sans CJK Version 2.002, Noto Serif CJK Version 1.001

**New available version:** [Noto Sans CJK Version 2.004](https://github.com/googlefonts/noto-cjk/releases/tag/Sans2.004), [Noto Serif CJK Version 2.001](https://github.com/googlefonts/noto-cjk/releases/tag/Serif2.001)

**Super short description of the upgrade:**
- Variable fonts
- Noto Serif Hong Kong

**Bugs reported in this repo which this upgrade would fix:**
Search in the [issue tracker](https://github.com/google/fonts/issues) if there is some opened issues containing the font name.

**Comment by RosaWagner** [comment]
The PRs to upgrade Noto CJK has been merged already, it will hit the live server in few weeks or so. Thanks for your patience.
