### ISSUE TITLE
Missing CORS Response Header on fonts.google.com

### ISSUE THREAD

**Issue by boundmaidlea** [google/fonts#4960]
**Describe the issue**
Random fonts on fonts.google.com cause the page to vanish leaving only the "Something went wrong. Please try again soon." error message. 

The Console displays a Missing CORS Response Header error for a fonts.gstatic.com url.

**To Reproduce**
Either scroll far enough through a search result list on fonts.google.com, or try to access the direct link to a problematic font description page like https://fonts.google.com/specimen/Source+Serif+4

**Expected behavior**
Nothing Noticable happens; the font gets loaded.

**Additional context**
Browser: Google Chrome Version 103.0.5060.114

I am not using any Proxy, VPN, or similar service.

For whatever reason the Source Serif font was not problematic in the search result list, yet it's own page is impossible to access.

The exact URLs accessed:
https://fonts.google.com/?category=Serif&vfonly=true&preview.text=CHAMPIONS&preview.size=64&preview.text_type=custom
https://fonts.google.com/specimen/Source+Serif+4

**Screenshots**
Error message on the search result list:
![image](https://user-images.githubusercontent.com/106570003/179831229-37d8f979-5660-46a7-8727-c765f9f8f9db.png)

Error Message on the Font Page:
![image](https://user-images.githubusercontent.com/106570003/179831138-f5ad3541-58ee-4d66-b37b-4a785a144240.png)

**Comment by garretrieger** [comment]
Thanks for the report, this should be fixed now.
