### ISSUE TITLE
GF Latin Kernel glyphset?

### ISSUE THREAD

**Issue by NightFurySL2001** [google/fonts#4998]
This page describes the glyphset for Google Font submission: https://googlefonts.github.io/gf-guide/requirements.html#glyphsets . There is a new GF Latin Kernel but it points to a 404 page. (https://github.com/googlefonts/glyphsets/tree/main/GF_glyphsets/Latin/latin-kernel)

**Comment by NightFurySL2001** [comment]
Just checking, is the GF Guide repo at https://github.com/googlefonts/googlefonts.github.io/issues/44?

**Comment by RosaWagner** [comment]
Yes 👍
