### ISSUE TITLE
Webfont Khula is missing some characters

### ISSUE THREAD

**Issue by weberdominik** [google/fonts#5004]
It looks like Khula doesn't support a lot of characters, german Umlauts for example. 

See this example:
https://fonts.google.com/specimen/Khula?query=khula&preview.text=%C3%B6%C3%A4%C3%BC%C3%96%C3%84%C3%9C%C3%9F&preview.text_type=custom
https://fonts.google.com/specimen/Khula?query=khula&preview.text=%C3%B6%C3%A4%C3%BC%C3%96%C3%84%C3%9C%C3%9F&preview.text_type=custom#glyphs

**Comment by fitojb** [comment]
Khula is a Devaganari typeface. If you are writing in Latin, just use Open Sans directly

**Comment by weberdominik** [comment]
Thanks but this is not helpful as Open Sans is another font.

**Comment by fitojb** [comment]
Yeah, but it’s the same design.

**Comment by vv-monsalve** [comment]
@weberdominik Indeed, the Latin Kernell Glyphset, is the minimum Latin set required for fonts targeting non-Latin scripts like Khula.

You would like to use Open Sans if you need complete Latin support and reading about [Glyphsets in the GF-guide](https://googlefonts.github.io/gf-guide/requirements.html#glyphsets) for more details.
