### ISSUE TITLE
Update Fruktur

### ISSUE THREAD

**Issue by EbenSorkin** [google/fonts#5015]
**Font Project Git Repo URL: **

**Current version:1.004**

**New available version: 1.008**

**Super short description of the upgrade:**
(expand glyphset, add kerning)

**Bugs reported in this repo which this upgrade would fix:**
Search in the [issue tracker](https://github.com/google/fonts/issues) if there is some opened issues containing the font name.
None Found

**Comment by vv-monsalve** [comment]
Hi @EbenSorkin, please provide the Git Repo where the `v1.008` is available.

[SorkinType/-Fruktur](https://github.com/SorkinType/-Fruktur) referred in the published specimen page is still showing `v1.004`. Would it still be the one?

**Comment by EbenSorkin** [comment]
No, it is this one

https://github.com/SorkinType/Fruktur
