### ISSUE TITLE
Update Noto HK, SC, TC metadata to address missing UI languages

### ISSUE THREAD

**Issue by chrissimpkins** [google/fonts#5041]
Related: https://github.com/google/fonts/pull/4722 (did not fully address the original issue)

We want to include all of the following languages:

- languages: "cjy_Hant" # Chinese, Jinyu
- languages: "gan_Hant" # Gan Chinese
- languages: "hak_Hant" # Hakka Chinese, Traditional
- languages: "hsn_Hant" # Xiang Chinese
- languages: "lzh_Hant" # Literary Chinese, Traditional
- languages: "nan_Hant" # Min Nan Chinese, Traditional
- languages: "wuu_Hant" # Wu Chinese
- languages: "yue_Hant" # Cantonese
- languages: "za_Hant" # Zhuang, Traditional Han
- languages: "zh_Hant" # Chinese (Traditional)

in the UI language preview filter dropdown for the following projects:

- notosanshk
- notosanssc
- notosanstc
- notoserifsc
- notoseriftc

Based on Nate's comment in https://github.com/google/fonts/pull/4722#issuecomment-1206858336, we can address this by adding a new `region: "CN"` definition in the project textprotos.

**Comment by vv-monsalve** [comment]
@chrissimpkins, the metadata update to Noto projects was done in #4722, and the inclusion of the `region: "CN"` for the missing languages on the list was done in #5063.

I think we can close this issue.

**Comment by chrissimpkins** [comment]
https://github.com/googlefonts/lang/pull/13 will be necessary to close this

**Comment by vv-monsalve** [comment]
> [googlefonts/lang#13](https://github.com/googlefonts/lang/pull/13) will be necessary to close this

It was merged there, and it was merged now here in `google/fonts` on #5088.
Closing this Issue here.
