### ISSUE TITLE
Cairo Play slanted values (STAT, fvar)

### ISSUE THREAD

**Issue by thlinard** [google/fonts#5043]
**Describe the bug**
The commented slanted values in https://github.com/Gue3bara/Cairo/blob/master/sources/cairoplay.yaml seems to be used to create `fvar` entries, but not `STAT` ones, leading to discrepancy between the two tables, and Microsoft Word for Mac doesn't like it.

PR #4786

**Screenshots**
<img width="290" alt="Cairo Play" src="https://user-images.githubusercontent.com/13808824/183383903-288790de-fb03-4157-b9e2-70166cdf2875.png">

**Comment by m4rc1e** [comment]
Both fvar and STAT tables are fine. This is an issue with Word. I'll send the font over to them.

**Comment by m4rc1e** [comment]
We will not be "fixing" fonts so they work in specific applications. We will fix fonts so they comply with font specifications instead. The implementation of these applications can change overnight and render all of our fixes "redundant" way too easily.

**Comment by thlinard** [comment]
> Both fvar and STAT tables are fine.
> We will not be "fixing" fonts so they work in specific applications. We will fix fonts so they comply with font specifications instead. The implementation of these applications can change overnight and render all of our fixes "redundant" way too easily.

This seems perfectly reasonable, but in this case the flaw observed in Word reveals a flaw in the implementation of the `STAT` table, not a Word bug.

The `STAT` table has no `AxisValue` for the Slant axis, while the `fvar` table is full of instances of various Slant values. It doesn't seem to make sense, and it's not what you do for other fonts with a slant axis.

**Comment by m4rc1e** [comment]
> This seems perfectly reasonable, but in this case the flaw observed in Word reveals a flaw in the implementation of the STAT table, not a Word bug.


From https://docs.microsoft.com/en-us/typography/opentype/spec/stat#axis-value-tables:

> In a variable font, it is strongly recommended that axis value tables be included for every element of typographic subfamily names for all of the named instances defined in the 'fvar' table.
>> Note: Some applications could rely on these axis value tables to compose subfamily names for named instances. Unexpected user interface behavior could result if a complete set of axis value tables is not included in the font.

"It is strongly recommended" doesn't mean "must". However, they do mention that there may be unexpected behaviour if you don't include em all.

**Comment by thlinard** [comment]
> However, they do mention that there may be unexpected behaviour if you don't include em all.

Exactly, and that's why you're right to have the practice of including them in every other font you release with a Slant axis.

**Comment by RosaWagner** [comment]
This has been fixed with #5327
