### ISSUE TITLE
Rokkitt Bold and Diaeresis

### ISSUE THREAD

**Issue by bardware** [google/fonts#505]
I view Rokkitt Font in [font viewer](http://us.fontviewer.de/).
The Dots on top of aou chacters looks strange. In fact there's only one dot, not two.
Is this expected?

![20161204_google_fonts_rokkitt_bold](https://cloud.githubusercontent.com/assets/802702/20902254/98639418-bb36-11e6-8db7-dc8548261454.PNG)

**Comment by davelab6** [comment]
@bardware thanks for reporting

The version available from GF today seems to have no issue with this:

![screen shot 2016-12-06 at 10 47 18](https://cloud.githubusercontent.com/assets/261579/20938835/66694226-bba1-11e6-8165-4d5b1d59d3b7.png)

However, the update made a few days ago - https://github.com/google/fonts/pull/432 - does have some issues with this

![screen shot 2016-12-06 at 10 48 06](https://cloud.githubusercontent.com/assets/261579/20938859/7f0fa77a-bba1-11e6-923c-577a7a4c2ea9.png)

cc @m4rc1e @kalapi

**Comment by kalapi** [comment]
Fixed. Pull request open on Marc's repo.

**Comment by davelab6** [comment]
Thank you so much Kalapi!!!

**Comment by m4rc1e** [comment]
Closing. Rokkit's Bold diaeresis is fine.

![screen shot 2017-06-14 at 11 32 04](https://user-images.githubusercontent.com/7525512/27128074-20fe6092-50f5-11e7-9172-6833784e66bc.png)
