### ISSUE TITLE
Wrong author name for Dela Gothic One

### ISSUE THREAD

**Issue by NightFurySL2001** [google/fonts#5051]
The author name for Dela Gothic One is [aratakana from the AUTHORS.txt](https://github.com/syakuzen/DelaGothic/blob/master/AUTHORS.txt), but in Google Fonts the named is changed to artakana, with one less 'a'.
![image](https://user-images.githubusercontent.com/33471049/183941787-4b6db42b-b8e0-40d3-b589-4a659b4c6441.png)
![image](https://user-images.githubusercontent.com/33471049/183941887-efbccea9-d55f-40c0-a440-00758bf70604.png)

**Comment by RosaWagner** [comment]
In this case AUTHORS.txt is wrong :)
