### ISSUE TITLE
Add Gloock

### ISSUE THREAD

**Issue by duartp** [google/fonts#5060]
**Font Project Git Repo URL:**
https://github.com/duartp/gloock

**Super short description of the Font Family:**
A contemporary high-contrast serif typeface intended for display use.

**Requirements:**

I understand that Google Fonts will publish only fonts that match its requirements, and I can confirm the project meets them:

- [x] The entire font project is licensed under the [OFL](https://scripts.sil.org/cms/scripts/page.php?site_id=nrsi&id=OFL)
- [x] There is no "Reserved Font Name" mention in the OFL license
- [x] Family name is unique according to namecheck.fontdata.com
- [x] The font supports at least [GF Latin Core glyphset](https://github.com/googlefonts/glyphsets/tree/main/GF_glyphsets/Latin/)
- [x] The repository respects the [upstream repo structure](https://github.com/googlefonts/gf-docs/tree/main/Spec#upstream-repo-structure)
- [x] The source files are available in the repository
- [x] I read, agree, and comply with the full [contributing requirements](https://github.com/google/fonts/blob/main/CONTRIBUTING.md)
- [x] I am the author of the font or the author agreed to this submission
- [x] I will maintain the repository

**Image:**
![Gluck_00](https://user-images.githubusercontent.com/53453513/184010117-7ea1db0a-51b3-476f-bb55-4c668048c9ff.jpg)

**Comment by inferno986return** [comment]
I like this one reminds me of newspaper headlines by the British Daily Telegraph newspaper.

**Comment by duartp** [comment]
@RosaWagner, can you please tell me what the issue is?

**Comment by RosaWagner** [comment]
Hi @duartp, thanks for the submission. We didn't have time to review the font to see if we would accept it or not, I just looked if the listed requirements were indeed respected and it seems that the GF_Latin_Core glyphset is not complete.

**Comment by duartp** [comment]
I apologize for the mistake. It seems there are indeed a few glyphs missing. I managed to find /ogonek /florin /mu, is there any easy way to find what glyphs still need to be designed? It's the first time I am submitting something like this and I am finding it quite hard to confirm which of the 337 I do not have yet. Thank you

**Comment by applecuckoo** [comment]
@duartp I'm no expert at making fonts, though I think you can use [this](https://github.com/googlefonts/glyphsets) Python API to generate a Glyphs filter.

**Comment by vv-monsalve** [comment]
@duartp you could follow the instructions on that Glyphsets repo (linked above) to use the `Glyphsets` tool to create the `.plist` file, or use the [GF Latin Core txt](https://github.com/googlefonts/glyphsets/blob/main/GF_glyphsets/Latin/txt/nice-names/GF_Latin_Core.txt) to manually create the filter list within Glyphs app.

**Comment by applecuckoo** [comment]
Okay, I've generated a .plist for Glyphs that has the minimal GF Latin Core glyphset. It should get recognised by Glyphs. [Here's](https://gist.github.com/applecuckoo/16b7a41084fc0b26e16f07d615ec8e16) the .plist uploaded as a Gist.

**Comment by duartp** [comment]
Wow. Thanks!

**Comment by applecuckoo** [comment]
No problem, GF also recommends having the GF Latin Plus glyphset, [here's](https://gist.github.com/applecuckoo/bc0b9046853be2535ee0f3c3aaada605) the filter.

**Comment by duartp** [comment]
Thank you all for the help :)
@RosaWagner, everything should be fine; the GF_Latin_Core glyphset is now complete.

**Comment by applecuckoo** [comment]
@duartp might be a good idea to add the GF Latin Plus glyphset, the filter file is linked above.

From the glyphset repo:
> Fonts submitted to Google Fonts must support at least **GF Latin Core**, and designers are strongly encouraged to consider adding the **GF Latin Plus set**.

**Comment by duartp** [comment]
Sure, I'll work on it

**Comment by duartp** [comment]
Gf_Latin_Plus glyphset added :)
