### ISSUE TITLE
Kumbh Sans - GF specimen unable to show some glyphs which are available in the font

### ISSUE THREAD

**Issue by xconsau** [google/fonts#5067]
When using the font [specimen preview](https://fonts.google.com/specimen/Kumbh+Sans/glyphs), some mathematical glyphs like Integral, Summation, Infinity, Radical, etc. are not shown. Instead, it shows a default font. Upon downloading the Kumbh Sans font files, I can see that the glyphs are available in the font files (both static and variable).

**To Reproduce**
Click on [this link](https://fonts.google.com/specimen/Kumbh+Sans/glyphs). Next, navigate to the "Math Operators" and hover on the Integral, Summation, Infinity symbols. The preview will be from a default serif font. If you try pasting these glyphs inside the Specimen preview, a notdef symbol is shown.

**Expected behavior**
Since the glyphs are available in the font, the preview shall display original glyph and not a fallback or missing ".notdef".

**Screenshots**
![screenshot-fonts google com-2022 08 15-14_45_09](https://user-images.githubusercontent.com/11784237/184609484-03b5d701-8474-4dc8-8cc1-c53ff2985e9f.png)

**Additional context**
I am checking on Windows 10, Chrome 104.0.5.

**Comment by davelab6** [comment]
The math subset wasn't declared in the family METADATA file, and the new specimen page surfaced this. An easy fix :)

**Comment by xconsau** [comment]
Thank you, Dave. Inside the "Punctuation" panel, the `perthousand` and the `daggerdbl` glyph also doesn't show.
