### ISSUE TITLE
[Question] Noto Sans/Serif with only static weights (and only 1 width) but Sans/Serif Display variable in width and weight?

### ISSUE THREAD

**Issue by cssobral2013** [google/fonts#5083]
**Describe the bug**
Noto Sans/Serif display only 9 static weights plus matching italics, and also only one width (despite having sources to make to variable), whereas Sans/Serif Display display a variable font with width/weight axes

**To Reproduce**
Access https://fonts.google.com/specimen/Noto+Sans and https://fonts.google.com/specimen/Noto+Sans+Display, and see the aforementioned issues

**Expected behavior**
Noto Sans/Serif should display a full variable font with width and weight axes

**Screenshots**

**Additional context**
Add any other context about the problem here (OS version, browser, printer…)

**Comment by applecuckoo** [comment]
@simoncozens did anything ever happen here?

**Comment by amdiv** [comment]
> @simoncozens did anything ever happen here?
good question

**Comment by simoncozens** [comment]
Yes, it's definitely on my list to happen; probably next quarter. I did have a try at upgrading Noto Sans but it's complicated. (For historical reasons, Noto Sans on Google Fonts also contains Noto Sans Devanagari.)

**Comment by MauriceArikoglu** [comment]
@simoncozens any News?

**Comment by simoncozens** [comment]
Noto Sans variable has been accepted for onboarding to the Google Fonts, but for horrible technical reasons (to do with null offsets in a GSUB table) they're having problems getting it into production.

**Comment by simoncozens** [comment]
(Noto Serif variable is live on Google Fonts.)

**Comment by glennsweeney** [comment]
Thanks for the work on this @simoncozens  - looking forward to variable Noto Sans as well when the issues are sorted!

**Comment by simoncozens** [comment]
Good news:

<img width="350" alt="Screenshot 2023-12-06 at 09 42 47" src="https://github.com/google/fonts/assets/106728/1175dd08-144e-462c-bc03-13af0c97dc4c">
