### ISSUE TITLE
Add Foldit

### ISSUE THREAD

**Issue by vv-monsalve** [google/fonts#5093]
**Font Project Git Repo URL:**
https://github.com/SophiaDesign/Foldit

**Super short description of the Font Family:**
Foldit is a variable-gradient COLRv1 font which uses gradients to play with dimension and sense of space.

**Image:**

![image1](https://user-images.githubusercontent.com/48698976/185455218-7191495b-26d1-4f99-91c4-934b4aa60b58.png)

**Comment by applecuckoo** [comment]
Hi there, does this count as a color font, since it uses COLRv1?
