### ISSUE TITLE
Add Comic Neue

### ISSUE THREAD

**Issue by crozynski** [google/fonts#51]
Hi Dave. You've made the submission process transparent and trackable. Thank you.

Call me paranoid but I feel you've written the first requirement with me in mind:

> The typeface design is original, or a legitimate revival of a design in the public domain...

Is that going to be a problem? While Comic Sans is not in the public domain, I don't consider Comic Neue to be a revival of Comic Sans. Comic Neue was inspired by the negative perception around Comic Sans. The glyphs were drawn from scratch and while they are altogether different, a similarity can be seen between the two. Technically, and for example, you could say the same about Open Sans and the humanist typefaces that preceded it, however in my case the connection to the source is much stronger. What do you think?

https://github.com/crozynski/comicneue

**Comment by davelab6** [comment]
No, i was not thinking of any particular project! :) I'm just processing
the backlog of requests behind the backlog of non Latin fonts. Thanks for
your patience :)

**Comment by sivapvarma** [comment]
Having this font on google fonts would be great.  Will this be included someday ?

**Comment by crozynski** [comment]
@sivapvarma, @davelab6 told me it would be and asked me to fulfil a number of requirements, which I did at considerable time and expense. Nothing ever happened.

**Comment by davelab6** [comment]
I regret the delay and I will add it soon :)

**Comment by AndreasWebdev** [comment]
What is the current status on this? Is this Issue on hold or anything? @davelab6 @crozynski

**Comment by m4rc1e** [comment]
We'll need to rename some of the styles so they conform with our API. Obliques need to be renamed to Italic etc

**Comment by crozynski** [comment]
@m4rc1e Hi Marc. Thanks for this. Forgive me for being skeptical, but the last time the Google Fonts team requested a change to add Comic Neue to the library, nothing happened for 3 year. Now more changes are being requested. If I make the change is it going to take days, weeks, years? Also you've finished your request with "etc", could you please be more specific, i.e. is changing obliques to italic all that needs to be done? Thank you

**Comment by m4rc1e** [comment]
@crozynski I'm more than happy to do this for you. It shouldn't take me too long. If there's any issue that means we can't release it, I'll drop you the QA report.

**Comment by crozynski** [comment]
Hi @davelab6 and @m4rc1e,

Marc thanks for your willingness to add Comic Neue to Google Fonts with the condition that the font files be renamed from 'oblique' to 'italic'. Could I please get both your input on the following:

Oblique and italic are two different classifications: italic a cursive representation of a roman typeface; oblique an angled one. Helvetica is Helvetica Oblique not Helvetica Italic, because it's an angled iteration not a cursive one. The same goes with Futura, Avenir or any typeface found in the Linotype library, as an example.

I'm not against changing Comic Neue's font names to "italic", but as it's technically incorrect it does feel like a degradation. Could you confirm Google Fonts doesn't consider the distinction important and it's unlikely the classification will be added to Google Fonts in future? 

I ask because I'm not setup to rename the UFO files that make up the package of fonts, and will need to outsource that work as an expense. I need some confirmation on your part that going ahead with that work is necessary.

Thanks

**Comment by AndreasWebdev** [comment]
Any status on this @davelab6 @m4rc1e?

I've been following this issue since 2016 and would like to see this font in Google Fonts in the future :smile:

**Comment by Kitteh6660** [comment]
I've been wanting to see this finally come to fruition. I personally LOVE Comic Neue.

**Comment by m4rc1e** [comment]
Family now on Google Fonts, https://fonts.google.com/specimen/Comic+Neue.

Apologies for the delay. Special thanks to @crozynski for his work and @vv-monsalve for finalising the family.

**Comment by crozynski** [comment]
Thanks for getting this done @m4rc1e and @vv-monsalve for your amazing handiwork. Very happy to see this come together.

**Comment by vv-monsalve** [comment]
Thanks. Happy to see it published :)

**Comment by gsbhasin123** [comment]
Yayy!
