### ISSUE TITLE
Update Educational School Fonts collection About section

### ISSUE THREAD

**Issue by vv-monsalve** [google/fonts#5104]
**Font Project Git Repo URL:**

- [ ] [Edu VIC WA NT Beginner](https://fonts.google.com/specimen/Edu+VIC+WA+NT+Beginner#about )
- [ ] [Edu QLD Beginner ](https://fonts.google.com/specimen/Edu+QLD+Beginner?query=Edu#about )
- [ ] [Edu TAS Beginner](https://fonts.google.com/specimen/Edu+TAS+Beginner?query=Edu#about )
- [ ] [Edu SA Beginner](https://fonts.google.com/specimen/Edu+SA+Beginner?query=Edu#about )
- [ ]  [Edu VIC WA NT Beginner](https://fonts.google.com/specimen/Edu+VIC+WA+NT+Beginner?query=Edu#about )

Current text: 
The [Educational School Fonts collection](https://fonts.google.com/?query=Edu) is a set of handwriting fonts for teachers and pupils.

Replace with: 
The [Foundation Fonts for Australian Schools collection](https://fonts.google.com/?query=Edu) is a set of handwriting fonts for teachers and pupils.

**Comment by RosaWagner** [comment]
There is more to it cf #4858

**Comment by vv-monsalve** [comment]
I've added the task to that previous issue. Closing this here.
