### ISSUE TITLE
Add [Pricedown

### ISSUE THREAD

**Issue by ChaceTech108** [google/fonts#5124]
**Font Project Git Repo URL:**

**Super short description of the Font Family:**

**Requirements:**

I understand that Google Fonts will publish only fonts that matches its requirements, and I can confirm the project meets them (by ticking the cases, or putting x between the square brackets in text mode):

- [x] The entire font project is licensed under the [OFL](https://scripts.sil.org/cms/scripts/page.php?site_id=nrsi&id=OFL)
- [x] There is no "Reserved Font Name" mention in the OFL license
- [x] Family name is unique according to namecheck.fontdata.com
- [x] The font supports at least [GF Latin Core glyphset](https://github.com/googlefonts/glyphsets/tree/main/GF_glyphsets/Latin/)
- [x] The repository respect the [upstream repo structure](https://github.com/googlefonts/gf-docs/tree/main/Spec#upstream-repo-structure)
- [x] The source files are available in the repository
- [x] I read, agree and comply with the full [contributing requirements](https://github.com/google/fonts/blob/main/CONTRIBUTING.md)
- [x] I am the author of the font or the author agreed to this submission
- [x] I will maintain the repository

**Image:**

Attach here a pic or a screenshot of the font; one is enough, it can be few letters, to give a quick overview.
![OIP](https://user-images.githubusercontent.com/111990506/186432370-3fbc756e-f4ee-4dc9-a0a8-714d16035e96.jpeg)

**Comment by kenmcd** [comment]
Pricedown is one free font weight out of an entire commercial family.
And that one free font is not OFL.

**Comment by vv-monsalve** [comment]
Hi, thanks for your submission. However, the font doesn't fulfill crucial requirements indeed. It is not licensed under OFL and is part of a more extensive commercial font project. 
You can find more details about this in the GF-Guide under the [New Fonts](https://googlefonts.github.io/gf-guide/onboarding.html#new-fonts) section.
