### ISSUE TITLE
Elsie Font

### ISSUE THREAD

**Issue by diogocfernandes** [google/fonts#515]
When I type the letters f and i together (fi - lowercase)  it becomes another letter.

**Comment by davelab6** [comment]
Thanks for reporting! Confirmed in https://jsbin.com/yovapax/1/edit?html,output

![screen shot 2016-12-06 at 12 52 55](https://cloud.githubusercontent.com/assets/261579/20936989/eb19e21c-bbb2-11e6-8bda-6a777f6a1320.png)

You can make a workaround while the fix is pending:

```css
font-feature-settings: "kern" on, "liga" off; 
-moz-font-feature-settings: "kern" on, "liga" off; 
-webkit-font-feature-settings: "kern" on, "liga" off; 
-ms-font-feature-settings: "kern" on, "liga" off; 
-o-font-feature-settings: "kern" on, "liga" off;
```

**Comment by m4rc1e** [comment]
Isn't this just a good old fashioned fi lig? is this a design issue?

**Comment by davelab6** [comment]
No. Confirmed:

<img width="1522" alt="screen shot 2017-06-15 at 08 28 11" src="https://user-images.githubusercontent.com/261579/27181219-99b57b60-51a4-11e7-8e6a-f4addd907df0.png">

**Comment by laerm0** [comment]
I can't find source for this anywhere. Any suggestions?

**Comment by davelab6** [comment]
https://bitbucket.org/lassefister/old-googlefontdirectory/src/21142f3bf7ad39d89c1c682d30830494ef1c905c/ofl/elsie/src/?at=default

**Comment by laerm0** [comment]
Thanks!

**Comment by m4rc1e** [comment]
@laerm0 Have you started converting this?

**Comment by laerm0** [comment]
I haven't started on this yet, @m4rc1e. We could have gone over this one last week. D'oh. Show me the process on bringing in old data soon, please.

**Comment by laerm0** [comment]
@m4rc1e took care of this a few days ago, so hopefully it's PR'd soon.

**Comment by attenzione** [comment]
any update on this?

**Comment by davelab6** [comment]
Sadly it looks like #884 didn't resolve this; here's the file from that PR in www.fontgoggles.org 

<img width="1512" alt="Screen Shot 2020-10-13 at 8 44 04 PM" src="https://user-images.githubusercontent.com/261579/95930628-eac48280-0d94-11eb-843f-74aedfee1e9b.png">

And here's the font live in fonts.google.com

<img width="1719" alt="elsie-fi" src="https://user-images.githubusercontent.com/261579/95930647-fa43cb80-0d94-11eb-970b-ef534ff8b3dd.png">

@RosaWagner could you take a look at this, this week?

**Comment by RosaWagner** [comment]
I don't have access to the bitbucket where the sources are. 

For what I see, the regular style doesn't contain a `fi` glyphs like the bold, but a `f_i` which misses an `f`. So for whatever reason, the ligature actually works. So I would suggest a hotfix which removes this `f_i` (and `f_j`, same issue) glyph or/and deactivates the ligature feature.

**Comment by thlinard** [comment]
InDesign is able to "OpenTypized" a font, substituting f + i with f_i (when 3 glyphs have these names in the font), even without a liga feature. So, I recommend instead removing the f_i glyph (or, if it's not a hotfix, creating it correctly).
