### ISSUE TITLE
Add DT Phudu

### ISSUE THREAD

**Issue by duongtrtype** [google/fonts#5201]
**Font Project Git Repo URL:**
https://github.com/duongtrtype/DTPhudu

**Super short description of the Font Family:**
An open-source display typeface inspired by Vietnamese hand-lettering billboards in the past.

**Requirements:**

I understand that Google Fonts will publish only fonts that matches its requirements, and I can confirm the project meets them (by ticking the cases, or putting x between the square brackets in text mode):

- [x] The entire font project is licensed under the [OFL](https://scripts.sil.org/cms/scripts/page.php?site_id=nrsi&id=OFL)
- [x] There is no "Reserved Font Name" mention in the OFL license
- [x] Family name is unique according to namecheck.fontdata.com
- [x] The font supports at least [GF Latin Core glyphset](https://github.com/googlefonts/glyphsets/tree/main/GF_glyphsets/Latin/)
- [x] The repository respect the [upstream repo structure](https://github.com/googlefonts/gf-docs/tree/main/Spec#upstream-repo-structure)
- [x] The source files are available in the repository
- [x] I read, agree and comply with the full [contributing requirements](https://github.com/google/fonts/blob/main/CONTRIBUTING.md)
- [x] I am the author of the font or the author agreed to this submission
- [x] I will maintain the repository

**Image:**
![image-03](https://user-images.githubusercontent.com/112008811/188561155-cc893740-e4ee-4531-9310-c097c5cff8e1.png)

**Comment by RosaWagner** [comment]
Thanks for the submission. It looks good and we'll try to review it. We'll get back to you if it gets accepted. Be aware that it may take a while though.

**Comment by RosaWagner** [comment]
The Spanish reversed question mark should turn its head to the right ;)

**Comment by duongtrtype** [comment]
Thank you for the help and comment. I've fixed the reversed question mark and updated the files in the repo
![image-03](https://user-images.githubusercontent.com/112008811/193100162-9a3ca004-12bf-4301-bc58-1aeb66fa8290.png)

**Comment by duongtrtype** [comment]
@RosaWagner Hi Rosa, while we are waiting for the review, I want to remove the name of the font from "DT Phudu" to just "Phudu" for short, is it allow at the moment? Some people might misunderstand "DT" as a trade mark, so if we are okay, I can update the informations right away

**Comment by RosaWagner** [comment]
@duongtrtype yes of course, do as you prefer.

**Comment by duongtrtype** [comment]
After a while for consideration, I decided to keep everything the same, no change is required.

**Comment by davelab6** [comment]
@duongtrtype thanks for your submission! We are happy to accept it and @yanone will be in touch early next year. 

https://googlefonts.github.io/gf-guide/onboarding says no abbreviations or acronyms, so I hope you are still willing to simplify the name :)

<img width="717" alt="Screenshot 2022-12-07 at 11 23 38 AM" src="https://user-images.githubusercontent.com/261579/206264881-af49e170-9b37-4cf5-ad4a-d18c5b445e3f.png">

**Comment by duongtrtype** [comment]
I understand, I've already updated new files with the new name, just "Phudu"
