### ISSUE TITLE
Montserrat Bold and Diaeresis 

### ISSUE THREAD

**Issue by bardware** [google/fonts#524]
The dots above characters aou don't look good in `Montserrat Bold`. Also look at the Bold `Montserrat Alternates`

![20161207_google_fonts_montserrat_bold](https://cloud.githubusercontent.com/assets/802702/20986539/59b5ab18-bcc9-11e6-93d6-0f0201daf645.PNG)

**Comment by m4rc1e** [comment]
Thanks @bardware.

Can confirm this is a design issue:
![screen shot 2016-12-07 at 22 26 39](https://cloud.githubusercontent.com/assets/7525512/20987280/4cbc6dae-bccc-11e6-85ab-7c3e29886ad9.png)

**Comment by davelab6** [comment]
@julietaula @juandelperal @CaroGiovagnoli please review

**Comment by bardware** [comment]
Much better in upstream

**Comment by m4rc1e** [comment]
![screen shot 2016-12-14 at 10 22 41](https://cloud.githubusercontent.com/assets/7525512/21176500/4af81a52-c1e7-11e6-8173-72f2c5b61923.png)

Can confirm it has been fixed. I'll pr now. Thanks @CaroGiovagnoli
