### ISSUE TITLE
[web] Slanted styles shown on https://fonts.google.com/specimen/Cairo+Play?coloronly=true on Safari

### ISSUE THREAD

**Issue by twardoch** [google/fonts#5247]
On macOS 12.5.1, Chrome 105.0.5195.102 shows the Styles section of https://fonts.google.com/specimen/Cairo+Play?coloronly=true as expected: 

<img width="1536" alt="scr- 2022-09-15 at 17 40 25" src="https://user-images.githubusercontent.com/519108/190447704-bb6a7356-4bcd-4f36-8fca-4b6adf090de3.png">

But Safari Version 15.6.1 (17613.3.9.1.16) shows the styles as slanted 

<img width="1536" alt="scr- 2022-09-15 at 17 40 10" src="https://user-images.githubusercontent.com/519108/190447823-5976f994-200e-49bd-bec2-5446c4ed5756.png">

though it shows the upright font at the top

<img width="1536" alt="scr- 2022-09-15 at 17 42 50" src="https://user-images.githubusercontent.com/519108/190447888-38b4ef20-f25f-4de8-9b81-caaec8b61721.png">

Must be something wrong with the instantiation of the OpenType+SVG fonts from the variable OpenType+COLR font, which does have a `slnt` axis.

**Comment by RosaWagner** [comment]
Thanks for reporting Adam, it adds to our case. The idea for now is to remove the slant instances from Cairo Play to avoid slant related bugs.
