### ISSUE TITLE
Lobster font show double зз russian letters incorrectly

### ISSUE THREAD

**Issue by ramzes1401ss3** [google/fonts#525]
Hi! Check and fix it, please in "Lobster" cyrillic font. When i wrote word "gazzal" (yarn) on russian language "газзал", the letters was wrote how "гаsзал". Thanks.

**Comment by ramzes1401ss3** [comment]
Only in Mozilla Firefox 50.0.2

**Comment by omerziv** [comment]
@alexeiva Is this something you've looked at by any chance?

**Comment by davelab6** [comment]
Confirmed: 

<img width="211" alt="screen shot 2016-12-12 at 15 00 06" src="https://cloud.githubusercontent.com/assets/261579/21114629/b00a5ee0-c07b-11e6-82d0-06be6adc36a3.png">

**Comment by alexeiva** [comment]
This is an issue with `liga`  OT feature. I am inspecting this. 

<img width="484" alt="screen shot 2016-12-12 at 9 08 57 pm" src="https://cloud.githubusercontent.com/assets/16634089/21114937/4920b402-c0af-11e6-850d-28e4e7217ea1.png">
<img width="463" alt="screen shot 2016-12-12 at 9 09 04 pm" src="https://cloud.githubusercontent.com/assets/16634089/21114938/49215ca4-c0af-11e6-952d-9e2b672b3ed4.png">

**Comment by ramzes1401ss3** [comment]
Thank you!

2016-12-12 23:40 GMT+03:00 Alexei Vanyashin <notifications@github.com>:

**Comment by davelab6** [comment]
Thanks @alexeiva - @ramzes1401ss3 hope this will go live early next year

**Comment by ramzes1401ss3** [comment]
Thanks! All working fine now!

**Comment by alexeiva** [comment]
I have added an actual `зз` ligature to further improve this rendering. 

<img width="355" alt="screen shot 2016-12-12 at 10 54 31 pm" src="https://cloud.githubusercontent.com/assets/16634089/21118450/3d977116-c0be-11e6-889e-b2bab626b62f.png">

Problem was in incorrect naming and OT code for dze-based ligatures:
<img width="229" alt="screen shot 2016-12-12 at 9 16 11 pm" src="https://cloud.githubusercontent.com/assets/16634089/21118464/4f31453c-c0be-11e6-9433-05d7de72811b.png">

**Comment by davelab6** [comment]
Nice. Re-opening to track this all the way to the production Fonts API

**Comment by m4rc1e** [comment]
Thank you @alexeiva 

I've increased the version number and added a pr.

@ramzes1401ss3 thank you for reporting this.
