### ISSUE TITLE
Maven Pro horizontal ellipsis

### ISSUE THREAD

**Issue by bardware** [google/fonts#527]
The horizontal ellipsis in Maven Pro Bold and Medium has only 2 dots, not three in this repo. Looks good on [GF](https://fonts.google.com/specimen/Maven+Pro), though.

![20161207_google_fonts_maven_pro](https://cloud.githubusercontent.com/assets/802702/21029749/77cb0206-bd9b-11e6-94f8-62d28cb98b7c.PNG)

**Comment by davelab6** [comment]
@thomasjockin please review and fix this :)

**Comment by ThomasJockin** [comment]
@davelab6 On it. Will review tomorrow. Thank you @bardware for the alert.

**Comment by m4rc1e** [comment]
Can confirm @ThomasJockin has fixed this 

**bold**
![screen shot 2016-12-13 at 14 25 14](https://cloud.githubusercontent.com/assets/7525512/21141927/02662998-c140-11e6-9185-ac552865836f.png)

**medium**
![screen shot 2016-12-13 at 14 26 10](https://cloud.githubusercontent.com/assets/7525512/21141949/1dca6370-c140-11e6-9870-0c4534b89c50.png)

Cheers,
Marc

**Comment by bardware** [comment]
Looks very good in upstream!
