### ISSUE TITLE
Anuphan

### ISSUE THREAD

**Issue by cadsondemakoffice** [google/fonts#5273]
https://github.com/cadsondemak/Anuphan

Anuphan: A Cadson Demak version of IBM Plex Thai (Loopless)

**Requirements:**

I understand that Google Fonts will publish only fonts that matches its requirements, and I can confirm the project meets them (by ticking the cases, or putting x between the square brackets in text mode):

- [x] The entire font project is licensed under the [OFL](https://scripts.sil.org/cms/scripts/page.php?site_id=nrsi&id=OFL)
- [x] There is no "Reserved Font Name" mention in the OFL license
- [x] Family name is unique according to namecheck.fontdata.com
- [x] The font supports at least [GF Latin Core glyphset](https://github.com/googlefonts/glyphsets/tree/main/GF_glyphsets/Latin/)
- [x] The repository respect the [upstream repo structure](https://github.com/googlefonts/gf-docs/tree/main/Spec#upstream-repo-structure)
- [x] The source files are available in the repository
- [x] I read, agree and comply with the full [contributing requirements](https://github.com/google/fonts/blob/main/CONTRIBUTING.md)
- [x] I am the author of the font or the author agreed to this submission
- [x] I will maintain the repository

**Image:**
![anuphan](https://user-images.githubusercontent.com/12027459/191070108-40711394-699b-4d17-b20a-4eb52ef911ad.png)

**Comment by RosaWagner** [comment]
Thanks for the submission. It looks good and we will try to review it to see we'll onboard it or not.

- The repository is not following the complete expected structure. Please read https://googlefonts.github.io/gf-guide/upstream.html to match the GF requirements.

**Comment by yanone** [comment]
@cadsondemakoffice Did you try to pitch this as a contribution to the official IBM Plex family?

**Comment by cadsondemakoffice** [comment]
Yes, I did. I would like to pitch this as a contribution to the official IBM Plex family.

**Comment by yanone** [comment]
Okay. Please let us know of the outcome. Google Fonts probably doesn't want to onboard this as **Anuphan** when it would later come down as part of **IBM Plex** anyway.

**Comment by cadsondemakoffice** [comment]
We have no problem with the name change as long as our drawings are in place.

**Comment by yanone** [comment]
Okay. I need to ask something for my understanding: Are you asking Google Fonts to onboard it as part of IBM Plex?

Google Fonts is hosting copies of the IBM Plex fonts but it not authoring it.
Plex is hosted  here: https://github.com/IBM/plex

**Comment by yanone** [comment]
@cadsondemakoffice I'm tasked with onboarding Anuphan as-is. Expect a PR from me in a few days with changes to the source file that are necessary to meet Google Fonts specifications.
In the meantime, please fill out [this form](https://docs.google.com/forms/d/e/1FAIpQLSeMwHN8J213ZaxHrr5lHCrX56HY_NjGrWB8o604g98YxuMrdA/viewform) with your bios, as you want to be represented on the font’s info page. Please fill the form multiple times in case you would like to see multiple designers referenced.
Thank you.

**Comment by yanone** [comment]
@cadsondemakoffice My apologies. I just saw that you already have fonts out on Google Fonts. Please ignore my request to fill in your bio.

**Comment by cadsondemakoffice** [comment]
@yanone Thank you very much for this hard work. If you need anything else please let me know. 😃

**Comment by cadsondemakoffice** [comment]
@yanone Thank you very much for this hard work. If you need anything else please let me know. 😃

**Comment by yanone** [comment]
> If you need anything else please let me know

@cadsondemakoffice Yes, please merge this PR: https://github.com/cadsondemak/Anuphan/pull/2
Thank you

**Comment by cadsondemakoffice** [comment]
@yanone Thank you, I'm merged.

**Comment by yanone** [comment]
@cadsondemakoffice I've [PR'd](https://github.com/google/fonts/pull/5927) the fonts to Google Fonts. Unless any errors are found by our reviewers, it will take around 2 to 3 weeks until the fonts go live.
Thank you.
