### ISSUE TITLE
Frank Ruhl Bold < > + broken

### ISSUE THREAD

**Issue by davelab6** [google/fonts#5294]
> There is a bug in the 700 style of the Frank Ruhl Libre font. The shape of < > + " is broken. Please fix it.

https://twitter.com/goingmerrygo/status/1572872626711629824?t=sZ-kAwemwY-P20MllK8r-Q&s=19

**Comment by keano12** [comment]
Hi guys do you know when this issue might be fixed regarding Bold + " ? Our company uses the font and causing issues. Thank you much

**Comment by emmamarichal** [comment]
Hi @keano12, 
it's coming very soon, I took care of it this week so in a few weeks the update will be available on Google Fonts!

**Comment by keano12** [comment]
> Hi @keano12,
> it's coming very soon, I took care of it this week so in a few weeks the update will be available on Google Fonts!

Thank you!!!
