### ISSUE TITLE
Update Chivo

### ISSUE THREAD

**Issue by Omnibus-Type** [google/fonts#5299]
**Font Project Git Repo URL:**
https://github.com/Omnibus-Type/Chivo

**Current version:**
1.007

**New available version:**
2.0

**Super short description of the upgrade:**
(Update Chivo to VF)

**Bugs reported in this repo which this upgrade would fix:**
None

**Comment by applecuckoo** [comment]
Hmm, this issue needs a `III VF Replacement` label.
