### ISSUE TITLE
Add STIX Text

### ISSUE THREAD

**Issue by davelab6** [google/fonts#530]
http://www.stixfonts.org

**Comment by m4rc1e** [comment]
I'll tackle this.

@davelab6 hotfix with minimal changes good enough?

**Comment by laerm0** [comment]
ping for @davelab6 and @m4rc1e as I go through this milestone ;)

**Comment by davelab6** [comment]
What's the upstream project like? Will they take our changes?

What's the rfn and tm status of the project?

**Comment by davelab6** [comment]
https://github.com/stipub/stixfonts

**Comment by thlinard** [comment]
Version 2.10 released today, and with a VF version!
https://github.com/stipub/stixfonts/releases/tag/v2.10

(I know Chrome looks at the MATH table of those fonts like a hen looks at a toothbrush, but there are browsers out there that know what to do with them.)

**Comment by tiroj** [comment]
You beat me to it @thlinard 

Yes, new version is live, and includes sources and reproducible, scripted build process. Big thanks to @davelab6 for helping us steer towards the variable font, and @vv-monsalve for the ongoing QA work. @khaledhosny and I spent time the last two days smacking down assorted FontBakery issues, so I think the fonts are probably close to being ready for GF.

With regard to the Math font, I was always unsure whether GF would want it as well as the Text fonts, but it is chance to lead on font support for [MathML](https://www.w3.org/Math/).

**Comment by fred-wang** [comment]
> (And you could even add STIX Math: I know Chrome looks at the MATH table of this font like a hen looks at a toothbrush, but there are browsers out there that know what to do with it.)

FWIW, MathML is being implemented in Chrome under a preference flag and the MATH table is supported. See https://mathml.igalia.com/

**Comment by thlinard** [comment]
> FWIW, MathML is being implemented in Chrome under a preference flag and the MATH table is supported. See https://mathml.igalia.com/

Oh oh, so a Math font by Google Fonts would really be a way to encourage Chrome to full support. 😉
