### ISSUE TITLE
Agrandir

### ISSUE THREAD

**Issue by ixqquek** [google/fonts#5330]
**Font Project Git Repo URL:**

**Super short description of the Font Family:**

**Requirements:**

I understand that Google Fonts will publish only fonts that matches its requirements, and I can confirm the project meets them (by ticking the cases, or putting x between the square brackets in text mode):

- [ ] The entire font project is licensed under the [OFL](https://scripts.sil.org/cms/scripts/page.php?site_id=nrsi&id=OFL)
- [ ] There is no "Reserved Font Name" mention in the OFL license
- [ ] Family name is unique according to namecheck.fontdata.com
- [ ] The font supports at least [GF Latin Core glyphset](https://github.com/googlefonts/glyphsets/tree/main/GF_glyphsets/Latin/)
- [ ] The repository respect the [upstream repo structure](https://github.com/googlefonts/gf-docs/tree/main/Spec#upstream-repo-structure)
- [ ] The source files are available in the repository
- [ ] I read, agree and comply with the full [contributing requirements](https://github.com/google/fonts/blob/main/CONTRIBUTING.md)
- [ ] I am the author of the font or the author agreed to this submission
- [ ] I will maintain the repository

**Image:**

Attach here a pic or a screenshot of the font; one is enough, it can be few letters, to give a quick overview.
![Screenshot (5)](https://user-images.githubusercontent.com/114567590/192723638-9f64d4d9-6987-421c-9e20-59b0ceebcdf1.png)

**Comment by applecuckoo** [comment]
@ixqquek Hello there! This seems to be a non-OFL font, and Google Fonts only accepts fonts under the Open Font License, so I don't think this is a valid entry. Thanks!

**Comment by RosaWagner** [comment]
Thanks for submission. Unfortunately the font doesn't match any of the requirements listed above. Therefore we can't accept it.
