### ISSUE TITLE
Excalibur Nouveau Regul

### ISSUE THREAD

**Issue by marijkehuisman** [google/fonts#5335]
**Font Project Git Repo URL:**
[
](https://www.dafont.com/excalibur-nouveau.font)

**Super short description of the Font Family:**
This Art Nouveau period text type is very well suited for headlines. It is beautiful and easily readable with that special 1920’s touch. It comes with a selection of special characters to cover languages like German, French, and Swedish too. The font is public domain, free for all uses, commercial and private.
![excalibur_nouveau](https://user-images.githubusercontent.com/114666923/193028831-bb7dcbf9-ac48-40bc-ada5-b18e8bfe5188.png)

**Requirements:**

I understand that Google Fonts will publish only fonts that matches its requirements, and I can confirm the project meets them (by ticking the cases, or putting x between the square brackets in text mode):

- [ ] The entire font project is licensed under the [OFL](https://scripts.sil.org/cms/scripts/page.php?site_id=nrsi&id=OFL)
- [ ] There is no "Reserved Font Name" mention in the OFL license
- [ ] Family name is unique according to namecheck.fontdata.com
- [ ] The font supports at least [GF Latin Core glyphset](https://github.com/googlefonts/glyphsets/tree/main/GF_glyphsets/Latin/)
- [ ] The repository respect the [upstream repo structure](https://github.com/googlefonts/gf-docs/tree/main/Spec#upstream-repo-structure)
- [ ] The source files are available in the repository
- [ ] I read, agree and comply with the full [contributing requirements](https://github.com/google/fonts/blob/main/CONTRIBUTING.md)
- [ ] I am the author of the font or the author agreed to this submission
- [ ] I will maintain the repository

**Image:**

Attach here a pic or a screenshot of the font; one is enough, it can be few letters, to give a quick overview.

**Comment by RosaWagner** [comment]
Thanks for the submission. Unfortunately the font doesn't comply to any of the requirements listed above, therefore we can't  accept it.
