### ISSUE TITLE
Update Preview Text dropdown not working

### ISSUE THREAD

**Issue by troyjack1** [google/fonts#5347]
#This issue also works for requesting features. 

**Describe the issue**
When clicking the font preview dropdown to switch between custom, sentence, alphabet, etc., it does not change the font preview. 

**To Reproduce**
clicking the font preview dropdown

**Expected behavior**
It should change the font preview

**Additional context**
Same behavior in chrome, firefox and safari latest updates

**Screenshots**
![Screen-Shot-2022-09-29-at-1 27 39-PM](https://user-images.githubusercontent.com/114692950/193113970-497846da-a851-4849-9f92-9136eec3d8d7.jpg)

**Comment by RosaWagner** [comment]
I believe the alphabet option is now removed, can you confirm you don't have further issues?
