### ISSUE TITLE
Update SMC Gayathri

### ISSUE THREAD

**Issue by vv-monsalve** [google/fonts#5379]
**Font Project Git Repo URL:**

- [ ] [Gayathri ](https://gitlab.com/smc/fonts/gayathri). Current version: 1.000. New version available 1.220

**Super short description of the upgrade:**
Update SMC font projects to include a reported [shaping bug](https://github.com/smc/manjari/issues/2).

**Comment by davelab6** [comment]
I'm reassigning this from @vv-monsalve to @RosaWagner, as @yanone is away for the summer and Rosalie hasn't got many assignments at the moment :)

**Comment by davelab6** [comment]
@RosaWagner I guess there are more SMC updates, please reach out to Santhosh Thottingal to find out if any other SMC updates pending :)

**Comment by vv-monsalve** [comment]
A [regression on some marks](https://github.com/smc/Gayathri/issues/11#issuecomment-1499681993) was reported to upstream. Designer says the fix will not happen.

**Comment by chrissimpkins** [comment]
We discussed this family in our pipeline meeting today and, given the lack of commitment to address the Latin shaping requests, we are going to close this issue and will not take the update.  We are open to re-review if/when we have upstream design participation in the discussion about how to approach this here.
