### ISSUE TITLE
Add Sligoil

### ISSUE THREAD

**Issue by tobestobs** [google/fonts#5381]
Let's add some ink traps?

**Font Project Git Repo URL:**
n/a

https://velvetyne.fr/fonts/sligoil/

**Super short description of the Font Family:**
"Sligoil is a monospace typeface. It has been designed for the interface of the [Unknown Number](https://store.steampowered.com/app/1692340/Unknown_Number_A_First_Person_Talker/) game, published by Godolphin Games. "Sligoil" is also the name of an evil fictional company within the game.

The Sligoil typeface has been influenced by the culture of the British isles (the work of Matthew Carter, of course, but also signs on Irish whiskey distilleries) and also by the letters on vintage Space Cadet keyboards (produced by the MIT). It presents wide language support for Latin-based European languages and a collection of symbols and alternate forms (including upright italic letters)."

**Image:**

<img width="1338" alt="Screen Shot 2022-10-07 at 10 04 23 AM" src="https://user-images.githubusercontent.com/49656407/194504312-12f37a41-f816-4970-9a5a-e1ebacfe9b2f.png">

**Comment by RosaWagner** [comment]
Two years ago we asked Velvetyne if they would integrate their font catalog to GF, and they came to the consensus among their designers to not do it. There is nothing against GF forking the fonts etc, but it was decided to respect their choice. I think we have a closed issue in the tracker with more input.
