### ISSUE TITLE
Specimen text not in Tai Viet script for Tai Heritage Pro

### ISSUE THREAD

**Issue by jvgaultney** [google/fonts#5388]
The sample text on the [Tai Heritage Pro specimen page](https://fonts.google.com/specimen/Tai+Heritage+Pro) should be in the Tai Viet script, but is instead in some unknown Latin-script language.

A possible text would be part of [UDHR article 26](https://unicode.org/udhr/d/udhr_blt.txt):

ꪋꪴ ꫛ ꪝꪮꪣ ꪼꪒ ꪣꪲ ꪁꪫꪸꪙ ꪵꪮꪚ ꪭꪸꪙ - ꪼꪒ ꪹꪤꪸꪒ ꪕꪮꪥ ꪹꪊꪸ ꪶꪒ ꪤꪱꪫ ꪤꪴꪀ ꪹꪚꪱ ꪎꪸ ꪁꪱ ꪙꪮꪥ ꪹꪭꪸꪉ ꪁꪷ ꪼꪒ ꪵꪮꪚ ꪬꪮꪉ ꪋꪽ ꪔꪾꪣ ꪀꪾꪚ ꪤꪱꪫ ꪤꪴꪀ ꪘꪰꪉ ꪶꪠꪉ ꪶꪩ - ꪤꪱꪫ ꪤꪴꪀ ꪋꪽ  ꪔꪾꪣ ꪭꪳ ꪵꪣꪙ ꪄꪮꪉ ꪄꪰꪒ ꪹꪭꪸꪉ, ꪤꪱꪫ ꪥꪴꪀ ꪀꪲ ꪗꪺꪒ ꪀꪾꪚ ꪝꪳꪉ ꪹꪉꪸ  ꪭꪳ ꪹꪜꪸꪙ ꪼꪄ ꪀꪫꪱꪉ ꪀꪾꪚ ꪤꪱꪫ ꪥꪴꪀ ꪋꪽ ꪎꪴꪉ ( ꪀꪱꪫ ꪭꪮꪀ ) ꪹꪜꪸꪙ ꪕꪮꪥ ꪈꪫꪸꪙ ꪔꪰꪀ ꪹꪋꪷꪉ ꪝꪸꪉ ꪻꪬ ꪹꪚꪱ ꪁꪫꪱꪙ ꫛ ꪻꪒ ꪵꪮꪚ ꪼꪒ.

**Comment by RosaWagner** [comment]
@jvgaultney actually it is a deeper problem, I opened an issue in the related repository to track it: https://github.com/googlefonts/lang/issues/31
