### ISSUE TITLE
Specimen text not in Lepcha script for Mingzat

### ISSUE THREAD

**Issue by jvgaultney** [google/fonts#5389]
The sample text on the [Mingzat specimen page](https://fonts.google.com/specimen/Mingzat) should be in the Lepcha script, but is instead in some unknown Latin-script language.

A possible text would be part of the [Two Lepcha Girls story from the Github project](https://github.com/silnrsi/font-mingzat/blob/master/tests/TwoLepchaGirls.ftml):

᰿᱁᰿ ᰂᰦᰮᰛᰧᰶᰕᰩ ᰂᰦᰮᰛᰧᰶ ᰣᰦᰜᰬᰮᰌᰨ ᰌᰧᰜᰬ ᰣᰧᰵᰶ ᰿᱂᰿ ᰂᰦᰮᰛᰧᰶ ᰣᰦᰍᰩᰮ ᰂᰦᰮᰛᰧᰶᰕᰩ ᰣᰦᰍᰩᰮ ᰿᱃᰿ ᰠᰛᰩᰵ ᰀᰦᰚᰫ ᰀᰤᰩᰵᰠᰦ ᰣᰦᰛᰧᰵᰶ ᰀᰦᰳᰉᰬᰳ ᰜᰧᰀᰦ ᰜᰬ ᰣᰧᰵᰶᰌᰨᰮ ᰗᰪᰮᰓᰦ ᰿᱄᰿ ᰡᰫ ᰣᰦᰛᰧᰵᰶ ᰜᰧᰰᰶᰡᰬᰳ ᰃᰩ ᰣᰦᰍᰩᰮ ᰿᱅᰿ ᰀᰦᰚᰫᰠᰦ ᰀᰤᰩᰵᰠᰦ ᰡᰬᰙᰫᰮᰛᰬ ᰠᰜᰨᰮ ᰅᰫᰰᰌᰬᰳᰓᰦᰮ ᰿᱆᰿ ᰀᰦᰚᰫᰠᰦ ᰀᰤᰩᰵ ᰡᰬᰙᰫᰮ ᰠᰜᰨᰮ ᰕᰦᰳᰡᰴ ᰣᰦᰍᰪᰮᰠᰴᰌᰨ ᰗᰪᰮ ᰕᰋᰨᰰ ᰿᱇᰿ ᰗᰪᰮ ᰕᰃᰦᰳ ᰣᰦᰀᰶ ᰣᰦᰜᰩᰵ ᰀᰦᰚᰫᰌᰨ ᰙᰫᰭᰀᰦ ᰿᱈᰿ ᰣᰨᰜᰨᰮ ᰃᰴᰍᰬ ᰣᰦᰜᰩᰵ ᰣᰦᰍᰩᰮᰌᰨ ᰚᰶ ᰕ ᰿᱉᰿ ᰀ᰷ᰥᰫᰕᰦᰳᰀᰦ ᰜᰬ ᰀᰦᰚᰫ ᰠᰪᰭᰉᰧᰮᰶᰀᰦᰳ ᰀᰦᰚᰫ ᰀᰤᰩᰵᰠᰦ ᰃᰪᰰᰛᰬᰮ ᰜᰧᰭᰶᰓᰦᰰ ᰀᰕᰦᰳᰀᰦ ᰿᱁᱀᰿ ᰅᰫᰰ ᰣᰦᰍᰩᰮ ᰣᰨᰜᰨᰮ ᰃᰴᰍᰬ ᰿᱁᱁᰿ ᰠᰋᰦ ᰜᰧᰭᰶᰡᰴ ᰿᱁᱂᰿ ᰘᰶᰀᰊᰧᰀᰦ ᰜᰧᰭᰶᰃᰦᰳ ᰡᰨᰜᰤᰩᰭ ᰿᱁᱃᰿ ᰃᰨ ᰜᰫᰭᰝᰥᰩᰵᰛᰬ ᰜᰫᰵᰡᰨ ᰜᰤᰩᰭᰣᰦᰮ ᰿᱁᱄᰿ ᰘᰶᰀᰊᰧᰀᰦᰌᰨ ᰋᰨᰀᰦ ᰿᱁᱅᰿ ᰅᰫᰰ ᰿᱁᱆᰿ ᰀᰦᰚᰫ ᰛᰩᰵᰀᰪᰱᰠᰴᰛᰬᰮ ᰠᰜᰨᰮ ᰕᰦᰳᰡᰴ ᰿᱁᱇᰿ ᰃᰨᰜᰦ ᰡᰫᰜᰦ ᰜᰧᰰᰶ ᰕᰂᰪᰰ ᰕᰚᰰᰶ ᰣᰦᰍᰩᰮ ᰿᱁᱈᰿ ᰋᰦᰯ ᰜᰫᰵᰊᰦᰲᰡᰴ ᰠᰦ ᰠᰪᰵᰀᰦᰳᰠᰦ ᰜᰦ ᰕᰉᰧᰰᰶ ᰿᱁᱉᰿ ᰜᰧᰰᰀᰨᰌᰨ ᰣᰦᰍᰩᰮ ᰣᰦᰍᰩᰮ ᰛᰩᰵᰀᰪᰱᰠᰦ ᰟᰧᰌᰨ ᰕᰉᰧᰰᰶ ᰜᰤᰩᰭ ᰿᱂᱀᰿ ᰟᰧ ᰡᰫᰕᰦᰳᰍᰬ ᰕᰉᰧᰰᰶ ᰀᰦᰚᰫ ᰛᰤᰩᰳᰀᰪᰱ ᰕᰦᰃᰰ ᰀᰦᰚᰫᰠᰦ ᰎᰍᰨ ᰉᰧᰶ ᰿᱂᱁᰿ ᰎᰍᰨᰠᰦ ᰣᰦᰓᰛᰬ ᰡᰫ ᰅᰫᰰᰎᰫ ᰀᰠᰪᰮᰍᰪ ᰣᰨᰛᰬ ᰕᰚᰰᰶ ᰿᱂᱂᰿ ᰝᰩ ᰃᰬᰓᰫᰣᰦᰇᰫᰭᰶ ᰋᰤᰦᰭ ᰕᰋᰨᰍᰬ ᰿᱂᱃᰿ ᰃᰨ ᰋᰤᰦᰭ ᰕᰋᰨᰍᰬ ᰿᱂᱄᰿ ᰃᰬᰓᰫᰣᰦᰇᰭᰶᰠᰦ ᰣᰦᰓᰨᰠᰦ ᰣᰦᰓ ᰣᰎᰥᰦᰙᰦᰱ ᰣᰦᰕᰫᰠᰦ ᰣᰦᰡᰬᰭᰕᰧᰳᰶ ᰣᰦᰡᰬᰭᰕᰧᰳᰶᰠᰦ ᰊᰃᰥᰧᰀᰪᰱᰛᰬ ᰃᰬᰓᰫᰣᰦᰇᰫᰭ ᰃᰨᰕ ᰿᱂᱅᰿ ᰣᰬ ᰿᱂᱆᰿ ᰝᰩᰍᰪ ᰌᰦᰜᰧᰵᰶ ᰃ᰷ᰥᰧ ᰀᰨᰲᰋᰨ ᰿᱂᱇᰿ ᰃᰨ ᰀᰨᰲ ᰕᰋᰨᰰ ᰣᰦᰍᰩᰮ ᰿᱂᱈᰿ ᰌᰦᰮᰠᰦᰵᰃ᰷ᰥᰧ ᰀᰨᰲᰋᰨ ᰿᱂᱉᰿ ᰃᰨ ᰠᰓᰦᰜᰦ ᰍᰩᰵ ᰕᰦᰋᰰ ᰣᰦᰆᰦ ᰿᱃᱀᰿ ᰀᰦᰚᰫᰌᰨ ᰌᰔᰧᰵ ᰀᰤᰩᰵᰀᰦᰜᰦ ᰃᰬᰓᰫ ᰣᰦᰇᰫᰭ ᰠᰦ ᰃ᰷ᰥᰧ ᰉᰧᰰᰶᰣᰦᰮ ᰿᱃᱁᰿ ᰠᰓᰦᰌᰨ ᰿᱃᱂᰿ ᰠᰃᰩᰲᰀᰦ ᰣᰫᰰᰋᰧᰭᰶ ᰜᰤᰦᰵ ᰿᱃᱃᰿ ᰣᰦᰍᰩᰮ ᰝᰩ ᰀᰨᰲ ᰝᰦᰳᰋᰨ ᰿᱃᱄᰿ ᰃᰨ ᰀᰨᰲ ᰿᱃᱅᰿ ᰃᰨ ᰍᰩᰵ ᰕᰋᰨᰰ ᰣᰨᰓᰦᰜᰦ ᰿᱃᱆᰿ ᰀᰦᰮ ᰀᰨᰲᰡᰴ ᰜᰦᰕᰦᰳ ᰜᰬ ᰝᰩ ᰀᰤᰩᰵᰀᰦ ᰿᱃᱇᰿ ᰣᰦᰜᰩᰵ ᰃᰨ ᰀᰨᰲᰡᰨ ᰣᰦᰍᰩᰮ ᰿᱃᱈᰿ ᰀᰤᰩᰵ ᰀᰤᰩᰵᰀᰦ ᰡᰫ ᰅᰫᰰᰓᰦᰮ ᰀᰦᰮ ᰅᰭᰶ ᰃᰦᰳ ᰀᰦᰚᰫ ᰿᱃᱉᰿ ᰣᰦᰜᰩᰵᰛᰬᰍᰪ ᰃᰨ ᰀᰨᰲᰡᰨ ᰣᰦᰍᰩᰮ ᰿᱄᱀᰿ ᰛᰩᰵᰀᰪᰱᰠᰴ ᰠᰦ ᰀ᰷ᰥᰫᰛᰬ ᰃᰪᰰ ᰆᰦ ᰀᰦᰳᰣᰦᰱ ᰅᰫᰰᰃᰦᰳ ᰿᱄᱁᰿ ᰀᰦᰒᰧᰭᰶᰍᰪ ᰙᰫᰭᰡᰴ ᰀᰦᰒᰧᰭᰶᰍᰪ ᰕᰙᰫᰭᰡᰴ ᰣᰨᰜᰨᰮ ᰠᰦᰭᰆᰧᰵᰶ ᰕᰅᰫᰰ ᰀᰦᰳᰍᰪ ᰣᰦᰋᰨᰵ ᰝᰥᰫᰱ ᰃᰴ ᰃᰪᰰᰍᰪ ᰝᰥᰫᰱ ᰃᰦᰳ ᰿᱄᱂᰿ ᰣᰦᰍᰩᰮ ᰃᰨ ᰕᰂᰪᰰᰡᰨᰜᰤᰩᰭᰣᰦᰮ ᰿᱄᱃᰿ ᰝᰩ ᰕᰂᰪᰰ ᰜᰧᰍᰪ ᰕᰅᰫᰰ ᰿᱄᱄᰿ ᰝᰩ ᰛᰩᰵ ᰚᰦᰵᰍᰬ ᰜᰫᰮᰀᰪᰱ ᰿᱄᱅᰿ ᰃᰨ ᰛᰩᰵ ᰃᰨ ᰛᰩᰵᰀᰪᰱᰌᰨ ᰿᱄᱆᰿ ᰣᰦᰌᰨᰠᰦ ᰀᰫᰕᰧᰵᰶ ᰡᰫ ᰿᱄᱇᰿ ᰀᰠᰪᰠᰦ ᰣᰦᰣᰧᰶᰊᰦᰕᰧᰳᰶ ᰛᰩᰵᰀᰪᰱ ᰿᱄᱈᰿ ᰝᰩ ᰛᰩᰵᰀᰪᰱ ᰡᰫᰕᰦᰳᰍᰬ ᰎᰧ ᰛᰩᰵᰀᰪᰱ ᰕᰃᰨᰰ ᰃᰴ ᰿᱄᱉᰿ ᰣᰦᰍᰩᰮᰠᰦ ᰀᰫᰕᰧᰵᰶ ᰡᰫ ᰃᰩ ᰿᱅᱀᰿ ᰀᰠᰪᰠᰦ ᰣᰩᰵᰕᰧᰳᰶ ᰛᰩᰵᰀᰪᰱ ᰿᱅᱁᰿ ᰣᰦᰍᰩᰮᰠᰦ ᰀᰫᰕᰧᰵᰶ ᰃᰨ ᰠᰛᰩᰵᰌᰨ ᰌᰤᰨᰕ ᰿᱅᱂᰿ ᰝᰩᰍᰪ ᰀᰠᰪᰠᰦ ᰀᰫᰕᰧᰵᰶ ᰠᰛᰩᰵᰌᰨ ᰚᰮᰶᰓᰫ ᰝᰩ ᰣᰦᰆᰦᰜᰦ ᰃᰬᰭ ᰃᰦᰳ ᰛᰩᰵ ᰕᰦᰚᰬᰯ ᰠᰪᰭᰌᰪᰮᰀᰦ ᰿᱅᱃᰿ ᰀᰦᰚᰫ ᰣᰦᰜᰩᰵ ᰣᰦᰜᰨᰮ ᰓᰦᰮᰍᰪ ᰕᰅᰫᰰ ᰿᱅᱄᰿ ᰀᰤᰩᰵᰀᰦ ᰅᰭᰶ ᰃᰦᰳ ᰛᰩᰵᰀᰪᰱᰠᰴ ᰠᰓᰦᰠᰓᰦ ᰗᰩᰮᰣᰦᰮ ᰠᰓᰦ ᰓᰥᰦᰮᰣᰦᰮ ᰿᱅᱅᰿ ᰣᰦᰜᰩᰵ ᰝᰩ ᰃᰨ ᰕᰚᰰᰶ ᰜᰧᰍᰪ ᰕᰜᰧᰰᰶ ᰿᱅᱆᰿ ᰀᰦᰚᰫ ᰀᰨᰲᰍᰪ ᰜᰩᰮᰍᰪ ᰛᰩᰵᰀᰪᰱᰠᰦ ᰠᰦᰭᰗᰪᰮ ᰊᰤᰵᰶᰠᰦ ᰋᰤᰦᰭᰀᰦ ᰣᰦᰕᰫᰠᰦ ᰌᰫᰵᰃᰧᰳᰶ ᰜᰦ ᰗᰪᰮᰀᰦ ᰣᰦᰓ ᰕ ᰀᰤᰩᰯᰍᰬᰀᰦ ᰿᱅᱇᰿ ᰀᰦᰚᰫ ᰛᰩᰵᰀᰪᰱᰛᰬ ᰠᰦᰓᰦᰍᰪ ᰣᰧᰳᰶ ᰿᱅᱈᰿ ᰆᰫᰍᰪ ᰿᱅᱉᰿ ᰝᰩ ᰋᰤᰦᰭᰣᰦᰮ ᰿᱆᱀᰿ ᰣᰨᰛᰬ ᰃᰨ ᰣᰦᰕᰫᰓᰨᰍᰪ ᰀᰦᰮᰀᰦᰮ ᰌᰪᰰᰣᰦᰮᰋᰨᰍᰪ ᰜᰧ ᰕᰦ ᰿᱆᱁᰿ ᰀᰦᰚᰫ ᰛᰩᰵᰀᰪᰱᰠᰦ ᰊᰰᰶᰀᰦ ᰣᰦᰜᰨᰮ ᰙᰫᰭᰍᰪ ᰣᰦᰛᰤᰫᰮ ᰅᰫᰰᰍᰪ ᰿᱆᱂᰿ ᰀᰦᰚᰫ ᰊᰤᰵᰶ ᰃᰪᰰ ᰀᰤᰩᰵᰀᰦ ᰀᰨᰲᰀᰦ ᰿᱆᱃᰿ ᰅᰫᰰ ᰣᰦᰍᰩᰮ ᰀᰨᰲᰀᰦ ᰣᰦᰜᰩᰵ ᰿᰿

**Comment by RosaWagner** [comment]
@jvgaultney I changed the primary script for Mingzat, the specimen page will appear in Lepcha within few weeks. It will be the same as https://fonts.google.com/noto/specimen/Noto+Sans+Lepcha

**Comment by jvgaultney** [comment]
This is still not showing properly.

**Comment by RosaWagner** [comment]
@jvgaultney the issue with this language is reported in the related repository: https://github.com/googlefonts/lang/issues/31
