### ISSUE TITLE
Bubbly

### ISSUE THREAD

**Issue by RosadoAbbby** [google/fonts#5391]
**Font Project Git Repo URL:**

**Super short description of the Font Family:**

**Requirements:**

I understand that Google Fonts will publish only fonts that matches its requirements, and I can confirm the project meets them (by ticking the cases, or putting x between the square brackets in text mode):

- [ ] The entire font project is licensed under the [OFL](https://scripts.sil.org/cms/scripts/page.php?site_id=nrsi&id=OFL)
- [ ] There is no "Reserved Font Name" mention in the OFL license
- [ ] Family name is unique according to namecheck.fontdata.com
- [ ] The font supports at least [GF Latin Core glyphset](https://github.com/googlefonts/glyphsets/tree/main/GF_glyphsets/Latin/)
- [ ] The repository respect the [upstream repo structure](https://googlefonts.github.io/gf-guide/upstream.html)
- [ ] The source files are available in the repository
- [ ] I read, agree and comply with the full [contributing requirements](https://googlefonts.github.io/gf-guide/onboarding.html)
- [ ] I am the author of the font or the author agreed to this submission
- [ ] I will maintain the repository

**Image:**

Attach here a pic or a screenshot of the font; one is e
![image](https://user-images.githubusercontent.com/115517880/194986493-affd48a9-d5d5-4fed-9dc1-b91ac43d78cc.png)
nough, it can be few letters, to give a quick overview.

**Comment by RosadoAbbby** [comment]
![image](https://user-images.githubusercontent.com/115517880/194987003-b07cf6b4-ba6d-40e3-b4d2-ed8db3d79f86.png)

**Comment by RosaWagner** [comment]
Hi, thanks for your submission. As you can see the font doesn't match the requirements listed above, therefore we can't add it to the catalogue. If you are looking for similar design, you can brose the "handwriting category on Google fonts: https://fonts.google.com/?category=Handwriting.
