### ISSUE TITLE
Add Penang Sans

### ISSUE THREAD

**Issue by isaacdamnweird** [google/fonts#5409]
**Font Project Git Repo URL:**
https://drive.google.com/file/d/1N75VLeB1_MTbR7fU2arG3LNjxEOXmT_n/view?usp=drivesdk

**Super short description of the Font Family:**
A new, modern geometric sans-serif with the simplest design

**Requirements:**

I understand that Google Fonts will publish only fonts that matches its requirements, and I can confirm the project meets them (by ticking the cases, or putting x between the square brackets in text mode):

- [x] The entire font project is licensed under the [OFL](https://scripts.sil.org/cms/scripts/page.php?site_id=nrsi&id=OFL)
- [x] There is no "Reserved Font Name" mention in the OFL license
- [x] Family name is unique according to namecheck.fontdata.com
- [x] The font supports at least [GF Latin Core glyphset](https://github.com/googlefonts/glyphsets/tree/main/GF_glyphsets/Latin/)
- [x] The repository respect the [upstream repo structure](https://googlefonts.github.io/gf-guide/upstream.html)
- [x] The source files are available in the repository
- [x] I read, agree and comply with the full [contributing requirements](https://googlefonts.github.io/gf-guide/onboarding.html)
- [x] I am the author of the font or the author agreed to this submission
- [x] I will maintain the repository

**Image:**
![1665505621661.png](https://user-images.githubusercontent.com/115384089/195722100-6e60bd2d-2f2c-433d-b46d-5d271e4109fc.png)
![1665505570917.png](https://user-images.githubusercontent.com/115384089/195770632-1dd0a0c7-02ee-45ea-b6ed-65c5106ae467.png)

Attach here a pic or a screenshot of the font; one is enough, it can be few letters, to give a quick overview.

**Comment by RosaWagner** [comment]
Hi @isaacdamnweird thanks for your submission. This is a great start, unfortunately the font doesn't match Google Fonts quality standards and therefore we won't onboard it.

We want to encourage you to continue practicing type design, there are resources online that could help you progress in your craft, I gathered plenty of them here: http://rosaliewagner.com/type-links/

**Comment by isaacdamnweird** [comment]
Oh, thanks for letting me know!
