### ISSUE TITLE
Add MyNerve

### ISSUE THREAD

**Issue by carolinashort** [google/fonts#5415]
**Font Project Git Repo URL:**
https://github.com/carolinashort/MyNerve

**Super short description of the Font Family:**
MyNerve is a handwriting typeface designed to annotate and comment on documents with a fresh style.

**Requirements:**

I understand that Google Fonts will publish only fonts that matches its requirements, and I can confirm the project meets them (by ticking the cases, or putting x between the square brackets in text mode):

- [x] The entire font project is licensed under the [OFL](https://scripts.sil.org/cms/scripts/page.php?site_id=nrsi&id=OFL)
- [x] There is no "Reserved Font Name" mention in the OFL license
- [x] Family name is unique according to namecheck.fontdata.com
- [x] The font supports at least [GF Latin Core glyphset](https://github.com/googlefonts/glyphsets/tree/main/GF_glyphsets/Latin/)
- [x] The repository respect the [upstream repo structure](https://googlefonts.github.io/gf-guide/upstream.html)
- [x] The source files are available in the repository
- [x] I read, agree and comply with the full [contributing requirements](https://googlefonts.github.io/gf-guide/onboarding.html)
- [x] I am the author of the font or the author agreed to this submission
- [x] I will maintain the repository

**Image:**
![MyNerve-all](https://user-images.githubusercontent.com/44884112/196011547-fc428e8e-c625-4cbf-ae9c-2be254f3edce.png)

Attach here a pic or a screenshot of the font; one is enough, it can be few letters, to give a quick overview.

**Comment by RosaWagner** [comment]
Thanks @carolinashort it looks great.

- Was it commissioned by GF, I don't remember ?
- We do have a policy for CamelCase family name, although we make exceptions. This is because users often research font with adding space in between usual words, and CamelCase family names often failed to be found. A small explanation on why it is needed for this project would help to make an exception.

**Comment by carolinashort** [comment]
Hi Rosa, 
It was not commissioned by GF
Regarding the name, it is a word game, but I am happy just to call it Mynerve. I though the CamelCase could be a problem. Do you need me to change it in all the documents?

**Comment by RosaWagner** [comment]
First let's see if the project gets accepted ;) We'll let you know, it might take a while.

**Comment by carolinashort** [comment]
Ok, sounds good! Maybe this was the problem when trying to create the repository using the googlefonts project template?
Anyway I am happy to use Mynerve if it is easier

**Comment by RosaWagner** [comment]
@carolinashort I assigned Emma to onboard the font next quarter since you already worked with her ;) You can already rename the font Mynerve if you think it doesn't remove anything for its identity.
