### ISSUE TITLE
Fix website links for Huerta Tipográfica

### ISSUE THREAD

**Issue by applecuckoo** [google/fonts#5416]
Hey there, the URL for Huerta Tipográfica have changed and the site now ends with .com instead of .com.ar.

**Describe the issue**
https://huertatipografica.com.ar/ should be replaced with https://huertatipografica.com/

**To Reproduce**
Go to the website for Huerta Tipográfica as listed in some font descriptions and you will see that the link is no longer valid.

**Expected behavior**
The link should take me to the right website.

**Additional context**
I have already made the changes in a seperate fork, let me know if you want me to do a PR.

**Screenshots**
![Screen Shot 2022-10-16 at 3 33 41 PM](https://user-images.githubusercontent.com/113647417/196015264-82d857ee-1377-4fe6-a31d-512f3ded81a4.png)

**Comment by RosaWagner** [comment]
Hi @applecuckoo. Thanks for the update, you are welcome to make a PR to correct the URL.
