### ISSUE TITLE
Why don't use `local` function first in `src`?

### ISSUE THREAD

**Issue by chris-zhu** [google/fonts#5418]
Thanks for such great library support. Since there is no discussion, I created an issue to make more people discover and help me solve the problem.

**Describe the issue**
i used Google Fonts with apis, and i found the data that i fetched url to return are not use `local` first, is this intentional, I don't know why, can someone answer me this question?

Below is the information on this issue: 
- The api link:  https://fonts.googleapis.com/css2?family=Roboto&family=Fira+Code&family=Fira+Mono:wght@400;700&family=Lobster&family=Lato:ital,wght@0,400;0,700;1,400;1,700&display=swap
- About `@font-face` docs: [MDN Docs with @font-face](https://developer.mozilla.org/en-US/docs/Web/CSS/@font-face/src)

**Expected behavior**
Like this: 
```diff
@font-face {
  font-family: 'Fira Code';
  font-style: normal;
  font-weight: 400;
  font-display: swap;
-  src: url(https://fonts.gstatic.com/s/firacode/v21/uU9eCBsR6Z2vfE9aq3bL0fxyUs4tcw4W_D1sJV37NuzlojwUKaJO.woff2) format('woff2');
+  src: local('Fira Code'), url(https://fonts.gstatic.com/s/firacode/v21/uU9eCBsR6Z2vfE9aq3bL0fxyUs4tcw4W_D1sJV37NuzlojwUKaJO.woff2) format('woff2');
  unicode-range: U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F;
}
```

**Comment by rsheeter** [comment]
We used to use it broadly and the primary impact was an endless stream of upset users who had bizarre and wonderful local fonts installed. These days we use local only in select cases where the font is likely present and correct, e.g. local Roboto on Android. To broadly enable local again we'd need stronger matching capabilities than are currently offered.

**Comment by chris-zhu** [comment]
Thanks your reply, i get it.
