### ISSUE TITLE
Pull Lang last changes

### ISSUE THREAD

**Issue by RosaWagner** [google/fonts#5438]
@m4rc1e 
Using this issue to track the changes in the Lang repo that still need to be pulled here.

- [x] Close #5351 
- [x] git subtree googlefonts/lang

@RosaWagner 
I add the list of modified textprotos so I remember to push them into sandbox and prod:
- yo_Latn
- vi_Latn
- unr_Orya

**Comment by m4rc1e** [comment]
Haven't forgotten about this. Just getting credentials so I can cut the release.

**Comment by RosaWagner** [comment]
Honestly this issue is more for me to remember everything that needs to be checked ;)
