### ISSUE TITLE
Redundant `swsh` feature definitions in Bellota

### ISSUE THREAD

**Issue by drott** [google/fonts#5446]
Tip-of-tree `./ofl/bellota/Bellota-Regular.ttf` dumped with ttx shows in the GSUB table:

```
      <FeatureRecord index="163">
        <FeatureTag value="swsh"/>
        <Feature>
          <!-- LookupCount=1 -->
          <LookupListIndex index="0" value="20"/>
        </Feature>
      </FeatureRecord>
[...]
      <FeatureRecord index="173">
        <FeatureTag value="swsh"/>
        <Feature>
          <!-- LookupCount=1 -->
          <LookupListIndex index="0" value="20"/>
        </Feature>
      </FeatureRecord>
```

All of these feature definitions are pointing to the same lookup list index `20` without changing any glyph mappings. 

I am expecting the font not to duplicate this feature, unless it would point to a different lookup list index. (But it may be intended to activate the feature in case the application uses a higher feature index?)

**Comment by drott** [comment]
Looks like they exist because each `LangSysRecord` points to a new one.  Closing. Even though this could be optimized, it's not a bug.

**Comment by drott** [comment]
Cosimo points out that the current `fontTools.feaLib.builder` already avoids duplicating these. Might be worthwhile rebuilding the font.

**Comment by anthrotype** [comment]
it's possible that this font's opentype features were not built using fonttools..

actually, it looks like it was generated directly with Glyphs.app according to https://github.com/kemie/Bellota-Font#build

**Comment by anthrotype** [comment]
I don't think it would make such a great deal of difference anyway
