### ISSUE TITLE
Add Fragment Mono

### ISSUE THREAD

**Issue by weiweihuanghuang** [google/fonts#5460]
[Fragment Mono](https://github.com/weiweihuanghuang/fragment-mono)

Fragment Mono is a monospaced coding version of Helvetica created by modifying and extending [Nimbus Sans](https://github.com/twardoch/urw-core35-fonts) by URW Design Studio.

**Requirements:**

I understand that Google Fonts will publish only fonts that matches its requirements, and I can confirm the project meets them (by ticking the cases, or putting x between the square brackets in text mode):

- [x] The entire font project is licensed under the [OFL](https://scripts.sil.org/cms/scripts/page.php?site_id=nrsi&id=OFL)
- [x] There is no "Reserved Font Name" mention in the OFL license
- [x] Family name is unique according to namecheck.fontdata.com
- [x] The font supports at least [GF Latin Core glyphset](https://github.com/googlefonts/glyphsets/tree/main/GF_glyphsets/Latin/)
- [x] The repository respect the [upstream repo structure](https://googlefonts.github.io/gf-guide/upstream.html)
- [x] The source files are available in the repository
- [x] I read, agree and comply with the full [contributing requirements](https://googlefonts.github.io/gf-guide/onboarding.html)
- [x] I am the author of the font or the author agreed to this submission
- [x] I will maintain the repository

![Image of Fragment Mono character set](https://github.com/weiweihuanghuang/fragment-mono/raw/main/documentation/FragmentMonoCharSet.png)

**Comment by cwgabel** [comment]
The zip file name (from the download option) contains an underscore between "Fragment Mono" as in 'Fragment_Mono".  This is inconsistent with all the monospaced fonts available on Google Fonts that use a space/blank separator rather than an underscore.
