### ISSUE TITLE
Ops...I cant preview the Chinese Fonts

### ISSUE THREAD

**Issue by ZenkieBear** [google/fonts#5462]
# Dear Google Developers

**Describe the bug**
There're 2 problems:
When I browse the Chinese fonts, they looks like the same.However, I tried edit the text content, the style haven't change.
I had look for the browser devtools(network module), serveral requests named "GetFontInfo" at the end of the list seems has been refused.

Those preview cards can't open like English preview cards when I clicked the font name. Althought I don't use this function, this problem should be resolve, or Chinese users might think google is not friendly with Chinese... :)

**To Reproduce**
In the description.

**Expected behavior**
Hop these problems will be resolved soon! XD

**Screenshots**
I haven't found image upload button on Github Issue page.

**Additional context**
- Windows 11
- Google Chrome 106.0.5249.119

> Zenkie Bear
>18 years old.

**Comment by applecuckoo** [comment]
Hey there @ZenkieBear, you just click the bar at the bottom to upload an image. Here's a screenshot:
![Screen Shot 2022-10-25 at 4 08 39 PM](https://user-images.githubusercontent.com/113647417/197673165-8c2c3187-4948-427b-bafe-f0b1e6756b72.png)

**Comment by ZenkieBear** [comment]
i'll put the screenshots











ZENKIE

---Original---
From: ***@***.***&gt;
Date: Tue, Oct 25, 2022 11:09 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [google/fonts] Ops...I cant preview the Chinese Fonts (Issue #5462)

**Comment by ZenkieBear** [comment]
Here're the reproduces







ZENKIE

---Original---
From: ***@***.***&gt;
Date: Tue, Oct 25, 2022 11:09 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [google/fonts] Ops...I cant preview the Chinese Fonts (Issue #5462)




 
Hey there @ZenkieBear, you just click the bar at the bottom to upload an image. Here's a screenshot:

**Comment by ZenkieBear** [comment]
Here're the reproduces
![font_preview_the_same](https://user-images.githubusercontent.com/62818957/197676746-d345e497-49f5-4a1c-bed6-bf2f14b7e861.png)

![access_refused](https://user-images.githubusercontent.com/62818957/197675845-a84a28d6-a20b-43f7-b265-919976ba0112.png)

**Comment by RosaWagner** [comment]
@ZenkieBear try to download the fonts from https://fonts.google.com/ it may work better.

**Comment by ZenkieBear** [comment]
> @ZenkieBear try to download the fonts from https://fonts.google.com/ it may work better.

Hmmm... I can not access the "specimen" page, so there's not way to download these fonts for me.

**Comment by RosaWagner** [comment]
Are you looking at any font, or fonts containing chinese glyphsets? Some fonts don't have chinese. Try: https://fonts.google.com/?subset=chinese-simplified

**Comment by RosaWagner** [comment]
If you are already doing that, maybe look into your state's laws regarding Google. It might be that Google Fonts API appears broken or blocked according to where you live.

**Comment by ZenkieBear** [comment]
> Are you looking at any font, or fonts containing a chinese glyph set? Some fonts don't have chinese. Try: https://fonts.google.com/?subset=chinese-simplified

That's sad, I can't access this page.
Err_code: ERR_PROXY_CONNECTION_FAILED

**Comment by ZenkieBear** [comment]
> If you are already doing that, maybe look into your state's laws regarding Google. It might be that Google Fonts API appears broken or blocked according to where you live.

Actually, so many google services can't be use in China.

**Comment by applecuckoo** [comment]
Note the use of the site googlefonts.net
