### ISSUE TITLE
Data Protection Issues With Google Fonts

### ISSUE THREAD

**Issue by thelanguagesecret** [google/fonts#5463]
My name is John Stedman, the owner of [www.thelanguagesecret.com](http://www.thelanguagesecret.com/), a site built with Google. On Friday I received a letter from a lawyer in Berlin, Kilian Lenard, alleging that the use of Google fonts on my website is in breach of European data protection laws.
Since I built the site myself using your software and fonts, it seems that there is no way of storing your fonts on my local server or of installing a cookie consent banner.
This is an issue affecting thousands of small website owners. We are all being sued, and it may be that Google will be as well. Please help.
Kind regards,
John Stedman
[www.thelanguagesecret.com](http://www.thelanguagesecret.com/)

**Comment by danielehrhardt** [comment]
Persönlichkeitsrechtsverletzung, Datenschutz "GoogleFonts" hier: Abmahnung
Kilian Lenard
::::::
Sehr geehrter Herr xxx,
wir schreiben Ihnen namens und im Auftrag von ---. Ordnungsgemäße Vollmacht anbei.
Unsere Mandantschaft ist Teil der lnteressensgemeinschaft Datenschutz; kurz: IG Datenschutz (www.igdatenschutz.de). Die IG Datenschutz hat sich der Verteidigung und Durchsetzung des Datenschutzes auf zivilrechtlichem Weg verschrieben. Der IG Datenschutz ist aufgefallen, dass Sie auf Ihrer Webseite Google Fonts verwenden. Google Fonts ist auf Ihrer Webseite derart installiert, dass u.a. die IP-Adresse des Besuchers Ihrer Webseite an Google in den USA weitergeleitet wird. Dieser Vorgang wurde auf Bitten unserer Mandantschaft mit ihrer IP-Adresse technisch, wie anliegend dargestellt, gesichert, wobei sich die Weiterleitung an Google aus dem hervorgehobenen Link bestätigt.
Die unerlaubte Weitergabe der IP-Adresse durch Sie an Google stellt eine Verletzung des allgemeinen Persönlichkeitsrechts unserer Mandantschaft in Form des informationellen Selbstbestimmungsrechts nach § 823 Absatz 1 BGB dar. Eine IP-Adresse ist eine personenbezogene Date im Sinne von Art. 4 Nr. 1 DSGVO (BGH, Urteil vom 16.05.2017 - VI ZR 135/13). Das Recht auf informationelle Selbstbestimmung beinhaltet das Recht des Einzelnen, über die Preisgabe und Verwendung seiner personenbezogenen Daten zu bestimmen.

Unsere Mandantschaft hat in den Eingriff nicht gemäß Art. 6 Abs. 1 a) DSGVO eingewilligt. Ein Rechtfertigungsgrund für den Eingriff i.S.d. Art. 5 Abs. 1 f) DSGVO liegt nicht vor. Google Fonts kann auch ohne den Aufbau einer Verbindung zum Google Server genutzt werden, womit eine Übertragung der IP-Adresse an Google ausgeschlossen ist.
Aufgrund des Verstoßes hat unsere Mandantschaft gegen Sie u.a. einen Anspruch auf Unterlassung. Deutsche Gerichte haben in den letzten zwei Jahren Betroffenen von unterschiedlichsten Datenschutzverstößen Schmerzensgelder in einer Breite bis zu einem Maximum von 2.500,00 € zugesprochen (beispielhaft LG München 1, Urteil vom 09.12.2021 - 31 0 16606/20 (2.500,00 €); LAG Hamm, Urteil vom 14.12.2021 - 17 Sa 1185/20 (2.000,00 €); LAG Hannover, Urteil vom 22.10.2021 - 16 Sa 761/20 (1.250,00 €); LG Lüneburg, Urteil vom 14.07.2020 - 9 0 145/19 (1.000,00 €); AG Hildesheim, Urteil vom 05.10.2020 - 43 C 145/19 (800,00 €); AG Pfaffenhofen/Ilm, Urteil vom 09.09.2021 - 2 C 133/21 (300,00 €); LAG Köln, Urteil vom 14.09.2020 - 2 Sa 358/20 (300,00 €); LG
Unsere Mandantschaft ist im Falle der unverzüglichen Beendigung des Verstoßes und Zahlung eines Betrags in Höhe von
170,00€
auf unser Treuhand-Mandanten-Konto bei der

**Comment by applecuckoo** [comment]
@thelanguagesecret Hey there, this is a very real issue. I don't live in Europe, but I do know that Google tracks the use of their fonts, though I doubt they'll remove that. You should switch to [Fontsource](https://fontsource.org/) if possible, they provide NPM packages that you can use. Else, you can self host the fonts on your server.

**Comment by davelab6** [comment]
Hello,

Thank you for your interest in using Google Fonts and thank you for your question.

Lawyers (specifically those in Austria and Germany) began sending letters to companies that use Google Fonts on their website threatening them with legal action based on alleged violations of the GDPR if they do not pay a fine.

These lawyers are not acting on the behalf of or at the direction of Google. Google Fonts is available for any use, without cost, in any country. While we cannot provide you with legal advice as to how or whether to respond to such demand letters, we encourage you to review the guidance issued from the Austrian Data Protection Authority and the Austrian Chamber of Commerce on their respective websites.

Details about the Google Fonts Web API from Google:

* The Google Fonts Web API [does not log or store IP addresses](https://developers.google.com/fonts/faq#what_does_using_the_google_fonts_api_mean_for_the_privacy_of_my_users).
* The Google Fonts Web API is designed to limit the collection, storage, and use of data to only what is needed to serve fonts efficiently and for aggregated usage statistics. Such data is kept secure and separate from other data. Google does not use any information collected by Google Fonts for other purposes, including for advertising.
* The fonts available in Google Fonts may be used without sending end-user data to Google, but there are several [significant advantages of using the Google Fonts Web API](https://web.dev/api-for-fast-beautiful-web-fonts/).
* To learn more about "self hosting" web fonts, see this [Google Fonts Knowledge article on Self-hosting web fonts written by Elliot Jay Stocks](https://fonts.google.com/knowledge/using_type/self_hosting_web_fonts)

Thanks,
Dave

**Comment by allefeld** [comment]
The FAQ item <https://developers.google.com/fonts/faq#what_does_using_the_google_fonts_api_mean_for_the_privacy_of_my_users> does no longer exist.
