### ISSUE TITLE
有新的免费可商业使用的中文字体（好几个），希望尽快支持

### ISSUE THREAD

**Issue by kwooshung** [google/fonts#5485]
# 两拨免费字体！

- **[免费字体第01波](https://www.iconfont.cn/fonts/index)**
- **[免费字体第02波](https://www.alibabafonts.com/#/font)**

**Comment by applecuckoo** [comment]
Hi there, these fonts probably won't be accepted since all Google Fonts aren't commercial.

**Comment by kwooshung** [comment]
> Hi there, these fonts probably won't be accepted since all Google Fonts aren't commercial.

可是，他们确实是可以免费的，虽然有版权，但是可以免费使用

However, they are indeed free, although copyrighted, but free to use

**Comment by kwooshung** [comment]
> Hi there, these fonts probably won't be accepted since all Google Fonts aren't commercial.

这里有版权声明，可商用也可非商用
https://www.yuque.com/lujunxiang/alibabapuhuiti/puzbh9

**Comment by kwooshung** [comment]
> Hi there, these fonts probably won't be accepted since all Google Fonts aren't commercial.

![image](https://user-images.githubusercontent.com/3413930/199116341-c4b60f63-29ed-45cd-88e9-85e35294766a.png)

**Comment by kwooshung** [comment]
> Hi there, these fonts probably won't be accepted since all Google Fonts aren't commercial.

说了那么多，希望能仔细看下他们的版权声明，确实是免费的。

**Comment by RosaWagner** [comment]
Hi, thanks for your submission. GF only onboards fonts licensed under [OFL](https://scripts.sil.org/cms/scripts/page.php?site_id=nrsi&id=OFL).

Unfortunately, this statement is not compatible with OFL and therefore GF can't publish the font;
> Except as expressly set forth herein, Alibaba does not grant User any other rights in relation to Alibaba Font. Without prior written permission by Alibaba, User shall not: 1) alter, modify, translate, convert, reverse engineer, decompile, disassemble, or otherwise attempt to discover the source codes or instructions of Alibaba Font;

You can check the contributing requirements in the [dedicated article](https://googlefonts.github.io/gf-guide/onboarding.html). If you want to know more about GF and licensing, you can read [this article](https://googlefonts.github.io/gf-guide/license-file.html).

Please feel free to open another submission if you see a font which would match all requirements.

**Comment by kwooshung** [comment]
> 虽然是商用免费字体，但 Google Fonts 只允许提交 `SIL OFL 1.1` 许可（可以修改字体等）的，像“阿里巴巴普惠体”用的是汉仪的商用免费字体许可（不能修改字体等）就不行。**商用免费字体并不等于开源字体！**

了解，多谢，原来是必须得开源字体

**Comment by kwooshung** [comment]
> Hi, thanks for your submission. GF only onboards fonts licensed under [OFL](https://scripts.sil.org/cms/scripts/page.php?site_id=nrsi&id=OFL).
> 
> Unfortunately, this statement is not compatible with OFL and therefore GF can't publish the font;
> 
> > Except as expressly set forth herein, Alibaba does not grant User any other rights in relation to Alibaba Font. Without prior written permission by Alibaba, User shall not: 1) alter, modify, translate, convert, reverse engineer, decompile, disassemble, or otherwise attempt to discover the source codes or instructions of Alibaba Font;
> 
> You can check the contributing requirements in the [dedicated article](https://googlefonts.github.io/gf-guide/onboarding.html). If you want to know more about GF and licensing, you can read [this article](https://googlefonts.github.io/gf-guide/license-file.html).
> 
> Please feel free to open another submission if you see a font which would match all requirements.

了解，多谢，原来是必须得开源字体
