### ISSUE TITLE
AR One Sans

### ISSUE THREAD

**Issue by niteeshy** [google/fonts#5487]
**https://github.com/niteeshy/ar-one-sans**

**AR One is a type family designed for augmented reality headsets. The design of letterforms is based on research and thorough testing on various devices ranging from high-end headsets to low-resolution smartphone-based devices. Its low contrast, generous spacing and robust shapes allow it to work well and be highly readable on busy backgrounds. It has optical weights for high and low resolution.**

**Requirements:**

I understand that Google Fonts will publish only fonts that matches its requirements, and I can confirm the project meets them (by ticking the cases, or putting x between the square brackets in text mode):

- [x] The entire font project is licensed under the [OFL](https://scripts.sil.org/cms/scripts/page.php?site_id=nrsi&id=OFL)
- [x] There is no "Reserved Font Name" mention in the OFL license
- [x] Family name is unique according to namecheck.fontdata.com
- [x] The font supports at least [GF Latin Core glyphset](https://github.com/googlefonts/glyphsets/tree/main/GF_glyphsets/Latin/)
- [x] The repository respect the [upstream repo structure](https://googlefonts.github.io/gf-guide/upstream.html)
- [x] The source files are available in the repository
- [x] I read, agree and comply with the full [contributing requirements](https://googlefonts.github.io/gf-guide/onboarding.html)
- [x] I am the author of the font or the author agreed to this submission
- [x] I will maintain the repository

**Image:**
![3  Anatomy](https://user-images.githubusercontent.com/26871553/198930406-03e3fdd5-f47f-4191-9362-26c81099fd8f.png)

**Comment by kenmcd** [comment]
The repository link returns a 404.
Which probably mean the repo is set to Private.
Please make sure the repository is set to Public.

**Comment by RosaWagner** [comment]
@niteeshy please update us here when it is ready for review ?

**Comment by niteeshy** [comment]
> @niteeshy please update us here when it is ready for review ;)

@RosaWagner The Type Family is ready for the initial review :)
These are some issues (from Fontbakery run) which I would need help with:
- Naming
- Meta Table
- Vendor Name (I will get this registered soon).
- Vertical Metrics: here I would need some guidance

**Comment by RosaWagner** [comment]
Thanks @niteeshy for letting us know!

You can ignore the warn about the meta table ;)

About vertical metrics: https://googlefonts.github.io/gf-guide/metrics.html
There is some stuff about naming too in the guide: 
- https://googlefonts.github.io/gf-guide/statics.html#supported-styles 
- https://googlefonts.github.io/gf-guide/variable.html#fvar-instances

But these technical requirements are quite hard to assimilate and you are not expected to do it all yourself. So if I were you, I would wait for @vv-monsalve to jump in. That the queue is a bit long, therefore patience is needed. We added the project for Q1 of 2023, anything production related can be handled by us when we will review your repository :)

**Comment by niteeshy** [comment]
Thanks @vv-monsalve, looking forward to your feedback :)

**Comment by vv-monsalve** [comment]
Pending revision to the [`ARRR` custom axis](https://github.com/googlefonts/axisregistry/issues/132)

**Comment by vv-monsalve** [comment]
`ARRR` axis was approved. Designer is working on last fixes and improvements.
