### ISSUE TITLE
Add Kalnia

### ISSUE THREAD

**Issue by vv-monsalve** [google/fonts#5494]
**Font Project Git Repo URL:**
Private repo still

**Super short description of the Font Family:**
Kalnia is a display typeface with high contrast and delicate terminals for poster headlines. 

**Image:**
![image](https://user-images.githubusercontent.com/48698976/199533568-87b7167a-269f-4623-8658-cb92333388d9.png)

**Comment by vv-monsalve** [comment]
The font is mostly ready to go, but since it works in coordination (shared shapes) with Kalnia-Color #5495 it could have further improvements out of the developing job of the latter.
It would be published simultaneously with the color version.

**Comment by chrissimpkins** [comment]
This is live correct? Or do we have a followup PR in the pipeline?  It is still labeled as being in sandbox

**Comment by vv-monsalve** [comment]
> It is still labeled as being in sandbox

This is what I've been reporting in the meetings and chat. It seems to be a bug in the tool, so I haven't changed it manually cause Marc is going to fix it. So as a test case.
