### ISSUE TITLE
Incorrect sentence on the Cyrillic's Glossary page

### ISSUE THREAD

**Issue by XenBG** [google/fonts#5515]
### URL: https://fonts.google.com/knowledge/glossary/cyrillic

> Cyrillic is the writing system used for Russian and various other languages across Eurasia and beyond, originally developed in the 10th century for speakers of the Proto-Slavic language.
> 
> Image with the Russian phrase “настоящий мастер научной фантастики”—which translates in English to “a true master of science fiction”—set in three different typefaces that support the Cyrillic script.
> 
> So-called because of the missionary work of St. Cyril in the first Bulgarian Empire, the original Cyrillic script was based on uppercase Greek [letterforms](https://fonts.google.com/knowledge/glossary/letterform).

As we can read from the third sentence from the quote above, the Cyrillic script was created by St. Cyril during the First Bulgarian Empire after whom it was later named. Nowadays, Bulgaria is the country that should inherit this script, both as a country that uses it in its official language and as a location where it is located.

I believe that the first sentence should describe the script as an origin, not which language today forms the largest number of Cyrillic users. For this reason, I think that in the first sentence it is incorrect to leave only the Russian language as such, using the Cyrillic alphabet, and to put Bulgarian in the column "various other languages in Eurasia and beyond".

The image on the page should be in Bulgarian as well - “истински майстор на научната фантастика”, based on the original English sentence - “a true master of science fiction”.

History homework paper: https://medium.com/exploring-history/origin-of-cyrillic-script-e7e0efa71f7d

**Comment by elliotjaystocks** [comment]
Thanks, @XenBG. I’ll work on an edit to this term based on your recommendations.

**Comment by elliotjaystocks** [comment]
@XenBG Just letting you know that this has now been actioned and will go live in the near future.

**Comment by XenBG** [comment]
@elliotjaystocks I found out that the alternative text on the image still uses the Russian text.

![cyrillic-image-alt](https://user-images.githubusercontent.com/4932709/211792354-43a376e0-07cc-4222-bbdf-455ff540144e.png)

**Comment by elliotjaystocks** [comment]
I’ll correct. Thank you, @XenBG!

**Comment by elliotjaystocks** [comment]
@XenBG Fixed in https://github.com/google/fonts/pull/5771 — but please note this will not go live immediately.
