### ISSUE TITLE
Add Mona Sans

### ISSUE THREAD

**Issue by RosaWagner** [google/fonts#5540]
**Font Project Git Repo URL:**
https://github.com/github/mona-sans

**Comment by benjamindenboer** [comment]
Hi @RosaWagner! Very excited about this. Would you happen to have any rough ETA you could share? :-)

**Comment by applecuckoo** [comment]
@benjamindenboer Well I don't work for Google Fonts, but the GitHub milestone is set for sometime this quarter.

**Comment by chrissimpkins** [comment]
Still blocked on resolution of the RFN issue.  Updated the issue metadata accordingly and assigned Dave

**Comment by chrissimpkins** [comment]
We resolved the RFN issue with the GitHub team and are prepared to continue with the QA.  Do we need anything else from type design team @RosaWagner?

**Comment by chrissimpkins** [comment]
Upstream is working on design changes that will cause visible H spacing regressions for users. We are going to wait for these to land before we onboard this family.

Tentatively pushing back to Q4 2023

**Comment by chrissimpkins** [comment]
Still waiting on information from GitHub on the timing of their font development updates / release

**Comment by RosaWagner** [comment]
status: no answer from the github team about the updated files yet. When they give an update, the onboarding process will have to start over as usual. All the PRs I made were merged, so there is nothing to do until they deliver new files.

**Comment by chrissimpkins** [comment]
The GitHub team verified this week that the development is nearly complete.  Will add this project to the Q1 queue.

**Comment by chrissimpkins** [comment]
We've made multiple attempts over the last few months to connect with the GitHub development team on this project and are not receiving input on the development status.  I'm going to transition this project to the backlog until they have an opportunity to collaborate with us on the onboarding.

**Comment by yanone** [comment]
Asked Sebastian Carewe (Github contractor) for updates by email and told him I'll be away after end of the month and asked if we can finish this asap.

**Comment by elioqoshi** [comment]
Just wanted to add that including Mona Sans in Google Fonts would be an immense achievement, thank you for your work on that! Is there any blocker (are there updates from the GitHub development team) on this or do we simply need to be more patient?

**Comment by chrissimpkins** [comment]
Thanks for your interest! We are working closely with the GitHub development team to make this happen.  We hope to launch the family on Fonts this quarter.  Stay tuned!

**Comment by paytonealexis** [comment]
Eagerly awaiting this milestone!

**Comment by emmamarichal** [comment]
@chrissimpkins Status: PR upstream opened here: https://github.com/github/mona-sans/pull/82
