### ISSUE TITLE
Incorrect usage text for Aboreto

### ISSUE THREAD

**Issue by una** [google/fonts#5544]
**Describe the bug**
The link and @import text to use the "Aboreto" font point to "Nabla"

**To Reproduce**
Go to [https://fonts.google.com/specimen/Aboreto](https://fonts.google.com/specimen/Aboreto)

**Expected behavior**
Should be "Aboreto" instead of "Nabla"

**Screenshots**
<img width="341" alt="Screen Shot 2022-11-11 at 5 38 11 PM" src="https://user-images.githubusercontent.com/1693164/201440309-43a0185a-1cea-4805-9aaa-4fff015e08c7.png">
<img width="1484" alt="Screen Shot 2022-11-11 at 5 38 02 PM" src="https://user-images.githubusercontent.com/1693164/201440311-1ad4a057-f805-4c30-9fb0-3ff2ea27720f.png">

**Comment by applecuckoo** [comment]
That's probably because you have Nabla selected, it says Nabla Regular 400 in the image above. Selects fine on my end, don't think this is a bug.

**Comment by RosaWagner** [comment]
@una in the specimen tab of Aboreto, go at the bottom of the page where the styles are displayed, and click the button "select Regular". You will then see it correctly linked in the selected families panel. Remove Nabla style from previous selection if you don't want it selected.

Tell me if it worked.

<img width="313" alt="Capture d’écran 2022-11-16 à 15 00 50" src="https://user-images.githubusercontent.com/12222436/202200738-cf6b68e0-9acf-4140-b6b4-5b0175f7a915.png">
<img width="1028" alt="Capture d’écran 2022-11-16 à 15 00 38" src="https://user-images.githubusercontent.com/12222436/202200746-e9db0912-7954-4827-8be9-c444c8b04d07.png">
