### ISSUE TITLE
Fix four characters in "Noto Naskh Arabic"

### ISSUE THREAD

**Issue by earmin** [google/fonts#5546]
The following characters are not displaying right on "Noto Naskh Arabic" font. 
Three numbers (4, 6, 7) in Persian language which are "۴","۶","۷" and dash character "-".
How it is displayed and how it should be. 
![2022-11-i1i](https://user-images.githubusercontent.com/3898995/201545966-1cf9fddc-3a0f-495e-8bce-8b53e0f14636.png)

The same text on Twitter android app which uses similar (or the same) font is correct:
![Screenshot_20221113-164802_Twitter](https://user-images.githubusercontent.com/3898995/201546258-79735c02-bd0d-43f1-af8e-3f5c3d2344f7.png)

**Comment by simoncozens** [comment]
This has just been addressed by this PR: https://github.com/google/fonts/pull/5009 and should be reflected on the fonts.google.com site within the next month.
