### ISSUE TITLE
Add Cusac

### ISSUE THREAD

**Issue by fabiorug** [google/fonts#5562]
**[Font Project Git Repo URL:](https://github.com/fabiorug/Cusac-font)**

**Cusac is a sans serif font for web browsing**

**Requirements:**

I understand that Google Fonts will publish only fonts that matches its requirements, and I can confirm the project meets them (by ticking the cases, or putting x between the square brackets in text mode):

- [x] The entire font project is licensed under the [OFL](https://scripts.sil.org/cms/scripts/page.php?site_id=nrsi&id=OFL)
- [x] There is no "Reserved Font Name" mention in the OFL license
- [x] Family name is unique according to namecheck.fontdata.com
- [x] The font supports at least [GF Latin Core glyphset](https://github.com/googlefonts/glyphsets/tree/main/GF_glyphsets/Latin/)
- [x] The repository respect the [upstream repo structure](https://googlefonts.github.io/gf-guide/upstream.html)
- [x] The source files are available in the repository
- [x] I read, agree and comply with the full [contributing requirements](https://googlefonts.github.io/gf-guide/onboarding.html)
- [x] I am the author of the font or the author agreed to this submission
- [x] I will maintain the repository

**Image:**

Attach here a pic or a screenshot of the font; one is enough, it can be few letters, to give a quick overview.
![readme-images](https://user-images.githubusercontent.com/69140751/202541944-b39662b8-b21e-44fd-bf48-524d360b621b.png)

**Comment by RosaWagner** [comment]
Hi @fabiorug thanks for your submission. 

The child handwriting aesthetic is very cute. Although, I looked into the sources and it seems that outlines were copy pasted from another source into a new one, and all the other technical aspects of a proper font source are missing. There is no metric data at all, nor font informations for example. Also a lot of glyphs are missing for us to be able to publish the font (such as numbers).

If you are eager to learn more about how to make a font, I encourage you to follow this list of resources: https://justinpenner.github.io/type-design-resources/ which is made to enter the type design practice step by step.
