### ISSUE TITLE
Supplied woff2 files are different, for different operating systems.

### ISSUE THREAD

**Issue by flavio-b** [google/fonts#5566]
**Describe the issue**
I've noticed that the woff2 files that are served by Google, are **different**, depending on which OS is being used.  For example, for the **exact same latin set** of Roboto, the files are:

Mac: https://fonts.gstatic.com/s/roboto/v30/KFOmCnqEu92Fr1Mu4mxKKTU1Kg.woff2
Windows: https://fonts.gstatic.com/s/roboto/v30/KFOmCnqEu92Fr1Mu4mxK.woff2

**To Reproduce**
1. Open the link https://fonts.googleapis.com/css2?family=Roboto&display=swap on any browser, on both Windows and Mac.
2. Locate the URL of the woff2 fonts that is served. Download the latin set from each, for example, and compare.

**Expected behavior**
I expected the files would be exactly the same, but they have different names and sizes. However, testing the file supplied for one OS didn't seem to affect the result when used in the _other_ OS.

**Additional context**
Tested on Chrome, Safari and Firefox and Edge. MacOS Ventura and Windows 11 (via parallels).

Is that difference due to some optimizations done in the file, for each OS?

**Comment by ayuhito** [comment]
Iirc Google serves fonts for MacOS differently because of things such as #2602.

**Comment by flavio-b** [comment]
Thanks! I suspected it could be OS-specific optimizations in the file, but didn't expect it would be necessary with the woff2 format, and I'm using variables fonts.

**Comment by davelab6** [comment]
> I expected the files would be exactly the same, but they have different names and sizes. However, testing the file supplied for one OS didn't seem to affect the result when used in the other OS.
...
> didn't expect it would be necessary with the woff2 format, and I'm using variables fonts.

Kindly, I'm confused, please could you explain why you think this? :)

Woff2 is just a compression wrapper, like zip.

Variable fonts can be hinted. 

Some systems ignore hints. 

Therefore a font API can return smaller files without hinting data to systems that will never use the data. Etc.

**Comment by flavio-b** [comment]
I just thought that, with variable fonts being relatively new, any quirks or differences in how modern OSes render these wouldn't apply anymore.

TBH, so far I haven't noticed any difference when using the file that was supplied for Windows, on Mac, and vice-versa

But if you had to choose only 1 file to self-host, which one would it be? The version for Windows or Mac?
