### ISSUE TITLE
Update Great Vibes

### ISSUE THREAD

**Issue by vv-monsalve** [google/fonts#5575]
This font is part of TSI Batch 1

Font Project Git Repo URL:
https://github.com/googlefonts/great-vibes

Current version:
v1.010

New available version:
v1.020

Super short description of the upgrade:
Expand glyphset to GF Latin Plus (previous version)

**Comment by vv-monsalve** [comment]
New goal for this font: Including African language support. The designer is working on it.

**Comment by vv-monsalve** [comment]
Designer is finishing the Latin-SSA extension and working on the Cyrillic one.

**Comment by vv-monsalve** [comment]
The designer is working on the Cyrillic portion of the upgrade.

**Comment by chrissimpkins** [comment]
The Cyrillic updates are now available in the [Cyrilliv-Vik](https://github.com/googlefonts/great-vibes/tree/Cyrillic-Vik) branch of the repository.

**Comment by davelab6** [comment]
I'd like to propose this for Q1, not Q2, and moved its gh milestone

**Comment by vv-monsalve** [comment]
PR made to GF
