### ISSUE TITLE
Add FangZhengShaoEr Font, FangZhengKaTong Font

### ISSUE THREAD

**Issue by ItzMegaGatlingPea** [google/fonts#5596]
**Font Project Git Repo URL:**

**The FangZheng Font Family**

**Requirements:**

I understand that Google Fonts will publish only fonts that matches its requirements, and I can confirm the project meets them (by ticking the cases, or putting x between the square brackets in text mode):

- [x] The entire font project is licensed under the [OFL](https://scripts.sil.org/cms/scripts/page.php?site_id=nrsi&id=OFL)
- [x] There is no "Reserved Font Name" mention in the OFL license
- [x] Family name is unique according to namecheck.fontdata.com
- [x] The font supports at least [GF Latin Core glyphset](https://github.com/googlefonts/glyphsets/tree/main/GF_glyphsets/Latin/)
- [x] The repository respect the [upstream repo structure](https://googlefonts.github.io/gf-guide/upstream.html)
- [x] The source files are available in the repository
- [x] I read, agree and comply with the full [contributing requirements](https://googlefonts.github.io/gf-guide/onboarding.html)
- [x] I am the author of the font or the author agreed to this submission
- [x] I will maintain the repository

**Image:**

Attach here a pic or a screenshot of the font; one is enough, it can be few letters, to give a quick overview.
![IMG_20221121_131504.jpg](https://user-images.githubusercontent.com/114299459/202971098-ff142812-4479-49a7-9078-3f72a7d8ff89.jpg)![Screenshot_2022-11-21-13-11-50-95_40deb401b9ffe8e1df2f1cc5ba480b12.jpg](https://user-images.githubusercontent.com/114299459/202971109-424439d5-ac30-4add-92ac-587ec8aca291.jpg)

**Comment by lxgw** [comment]
These fonts are commercially copyrighted fonts instead of open-source fonts. Any unauthorized copy or commercial use of these fonts will result in copyright infringement.
