### ISSUE TITLE
Poppins font error.

### ISSUE THREAD

**Issue by bilalmalkoc** [google/fonts#560]
Hello. This font works correctly in only google browsers. It is worng view in some latin characters. I have this error in samsung stock browser and UC browser. Maybe it has other browsers.

**Comment by davelab6** [comment]
https://github.com/itfoundry/Poppins/commit/566916e33b3e7a2956e34cc7a5f4a9c508ccb592 should resolve this. @m4rc1e please make a PR :)

**Comment by laerm0** [comment]
Poppins is updated and all good now.
