### ISSUE TITLE
Hebrew Fonts

### ISSUE THREAD

**Issue by eblecher** [google/fonts#5600]
#This issue also works for requesting features. 

**Describe the issue**
There are not enouph hebrew fonts in google fonts.
As many applications, web or others, rely on google fonts, it is really inconvenient to add fonts manually,
and even that is somtimes not possible, so we, hebrew font users, can't use the application to its fullest.
also for google docs, that is getting to be real alternative for microsoft office, for which you are able to add fonts.

**To Reproduce**
see application https://apitemplate.io/ for example. you cant add your own font.

**Expected behavior**
on the the web there are many free hebrew fonts which are not on goole fonts yet.
so many fonts from this site are there, but some, like "GAN" are missing:
http://freefonts.co.il/
each font contain the required license for use by google

**Additional context**
another site:
https://oketz.com/fonts/

**Screenshots**

**Comment by RosaWagner** [comment]
Hi @eblecher, thanks for your request. Please understand that Google Font is a complicated API and can only be onboarded fonts that follow GF requirements and quality standards — which are partly listed here:https://googlefonts.github.io/gf-guide/onboarding.html. 

GF tries to not add font without the designer consent, and it is also impossible to take a ttf binary on a website and add it into the catalog. It is just not that simple, unfortunately.

If you know any type designer willing to distribute their Hebrew font with GF, and therefore willing to make the necessary modifications to comply with its requirements (or give the GF team the authorization to do so), they are more than welcome to manifest through this issue tracker :)
