### ISSUE TITLE
Invalid Top DICT data in Noto Sans Japanese

### ISSUE THREAD

**Issue by IvanUkhov** [google/fonts#5620]
**Describe the bug**
According to the [CFF standard](https://adobe-type-tools.github.io/font-tech-notes/pdfs/5176.CFF.pdf), the Top DICT should contain the Private operator, which is absent in Noto Sans Japanese as downloaded from the [UI](https://fonts.google.com/noto/specimen/Noto+Sans+JP?query=noto+sans+ja):

> A Private DICT is required, but may be specified as having a length of 0 if there are no non-default values to be stored.

**To Reproduce**
Check the presence of Private in Top DICT. For instance, using `fonttools`:

```python
from fontTools.ttLib import TTFont

font = TTFont("NotoSansJP-Regular.otf")
font['CFF '].cff[0].rawDict
# {
#     'ROS': ('Adobe', 'Identity', 0),
#     'Notice': 'Copyright -2020 Adobe (http://www.adobe.com/). Noto is a trademark of Google Inc.',
#     'FullName': 'Noto Sans JP Regular',
#     'FamilyName': 'Noto Sans JP',
#     'Weight': 'Regular',
#     'UnderlinePosition': -150,
#     'FontBBox': [-1002, -1048, 2928, 1808],
#     'CIDFontVersion': 2.00200009,
#     'CIDCount': 65529,
#     'charset': 7068,
#     'CharStrings': 43287,
#     'FDSelect': 42687,
#     'FDArray': 43013
# }
```

**Expected behavior**
Private should be present regardless of whether it contains values other than the default ones.

**Comment by anthrotype** [comment]
that is font is a CID-keyed CFF font, which thus it contains an FDArray which in turn contains multiple FontDicts each with its own Private dict. So it is valid, the CFF spec has multiple sections dedicated to those.
You can read more about CID-keyed fonts in [this Ken Lunde's post](https://ken-lunde.medium.com/to-cid-or-not-to-cid-e8e623dcde92).

**Comment by IvanUkhov** [comment]
This is interesting! Thank you for taking the time to explain! I’ll read the article and update my implementation.
