### ISSUE TITLE
KonKhmer_SleokChher

### ISSUE THREAD

**Issue by suonmaysophanith7** [google/fonts#5621]
**Font Project Git Repo URL:** https://github.com/suonmaysophanith7/KonKhmer_SleokChher

**Super short description of the Font Family:** Leaf letter in Khmer alphabet

**Requirements:**

I understand that Google Fonts will publish only fonts that matches its requirements, and I can confirm the project meets them (by ticking the cases, or putting x between the square brackets in text mode):

- [x] The entire font project is licensed under the [OFL](https://scripts.sil.org/cms/scripts/page.php?site_id=nrsi&id=OFL)
- [x] There is no "Reserved Font Name" mention in the OFL license
- [x] Family name is unique according to namecheck.fontdata.com
- [x] The font supports at least [GF Latin Core glyphset](https://github.com/googlefonts/glyphsets/tree/main/GF_glyphsets/Latin/)
- [x] The repository respect the [upstream repo structure](https://googlefonts.github.io/gf-guide/upstream.html)
- [x] The source files are available in the repository
- [x] I read, agree and comply with the full [contributing requirements](https://googlefonts.github.io/gf-guide/onboarding.html)
- [x] I am the author of the font or the author agreed to this submission
- [x] I will maintain the repository

![image1](https://user-images.githubusercontent.com/111719409/203858545-3a485e21-13ce-4060-bcef-9f9da3411bdd.png)

**Image:**

Attach here a pic or a screenshot of the font; one is enough, it can be few letters, to give a quick overview.

**Comment by applecuckoo** [comment]
Hello there! I don't think you need to open a separate issue since you already made one, you probably just need to signal @RosaWagner to recheck your font. Thanks!

**Comment by suonmaysophanith7** [comment]
> Hello there! I don't think you need to open a separate issue since you already made one, you probably just need to signal @RosaWagner to recheck your font. Thanks!

Thank you Dear,   @applecuckoo 

Hello @RosaWagner  kindly recheck the update issue in my font, Thanks

**Comment by applecuckoo** [comment]
That's alright, I think you can just close this issue.
