### ISSUE TITLE
Vietnamese Guide: missing update OT Feature

### ISSUE THREAD

**Issue by m4rc1e** [google/fonts#563]
@alexeiva. I followed your guide and everything worked superbly, apart from you missed a step.

Your guide doesn't mention updating the locl OT feature.

![screen shot 2017-01-04 at 14 57 17](https://cloud.githubusercontent.com/assets/7525512/21646448/2878a732-d28e-11e6-9e42-f40f12938d12.png)

This should be the last step.

Cheers,
Marc

**Comment by alexeiva** [comment]
I will update this, thanks you @m4rc1e
