### ISSUE TITLE
Add Achieve

### ISSUE THREAD

**Issue by lrenhrda** [google/fonts#5630]
**Font Project Git Repo URL:**
https://github.com/Isosceles/Achieve

**Super short description of the Font Family:**
Achieve is a NASA-inspired typeface in multiple weights.

**Requirements:**

I understand that Google Fonts will publish only fonts that matches its requirements, and I can confirm the project meets them (by ticking the cases, or putting x between the square brackets in text mode):

- [x] The entire font project is licensed under the [OFL](https://scripts.sil.org/cms/scripts/page.php?site_id=nrsi&id=OFL)
- [x] There is no "Reserved Font Name" mention in the OFL license
- [x] Family name is unique according to namecheck.fontdata.com
- [x] The font supports at least [GF Latin Core glyphset](https://github.com/googlefonts/glyphsets/tree/main/GF_glyphsets/Latin/)
- [x] The repository respect the [upstream repo structure](https://googlefonts.github.io/gf-guide/upstream.html)
- [x] The source files are available in the repository
- [x] I read, agree and comply with the full [contributing requirements](https://googlefonts.github.io/gf-guide/onboarding.html)
- [x] I am the author of the font or the author agreed to this submission
- [x] I will maintain the repository

**Image:**

Attach here a pic or a screenshot of the font; one is enough, it can be few letters, to give a quick overview.

![Achieve-Example-Image](https://user-images.githubusercontent.com/80609/204034871-b8a3061c-78dd-4229-94a6-766877894a6b.png)

**Comment by RosaWagner** [comment]
Hi @lrenhrda thanks for your submission. We'll try to review the font before the end of the year and we'll let you know if it is accepted. In the meanwhile, would you consider adding the `capital german double s` into your glyphset?

**Comment by lrenhrda** [comment]
Thanks @RosaWagner ! I've updated the font to include `capital german double s`; there was previously an existing design for it but it was only included as a case-sensitive form—I've fixed that and included it at the correct code point.

**Comment by vv-monsalve** [comment]
Hi @lrenhrda, I'll start Achieve's onboarding process. I've forked the repo now and I'll be communicating during the process through issues in your repository.

**Comment by vv-monsalve** [comment]
- [PR to upstream](https://github.com/Isosceles/Achieve/pull/6) pending to be merged
- [To-Do list issue](https://github.com/Isosceles/Achieve/issues/5)

**Comment by vv-monsalve** [comment]
Hi @lrenhrda, do you have an estimated date to address the required changes reported in the To-Do list issue?

**Comment by lrenhrda** [comment]
I anticipate addressing this by early August. Other projects have demanded my attention lately but I'm still committed to making the necessary revisions.

**Comment by vv-monsalve** [comment]
Excellent news. Please let me know when you get back on it.

**Comment by vv-monsalve** [comment]
> I anticipate addressing this by early August. 

Hi @lrenhrda, have you got the opportunity to return to the project?

**Comment by chrissimpkins** [comment]
Will close.  Please re-open when you have time to address the requests. Thanks!
