### ISSUE TITLE
UnifrakturCook not working

### ISSUE THREAD

**Issue by israelblenn** [google/fonts#5633]
I'm trying to use UnifrakturCook on a website but it won't display, no error messages are triggered the text just reverts to default.

I'm using chrome but I've tested it in firefox to the same result - other google fonts work fine.

**Comment by tomxbarnesx** [comment]
Confirming I'm experiencing the same. It also looks like this issue was flagged first back in 2019, with no progress since then: https://github.com/google/fonts/issues/2284. Not sure what's going on here

**Comment by usermfubu** [comment]
I am having the same issue trying to use UnifrakturCook with the extensis fonts add-on. Couldn't get it to work with either docs or slides. Tried using the link nyshadhr9 posted but didn't do anything

**Comment by davelab6** [comment]
UnifrakturCook is prevented from appearing in WorkSpace since it lacks a 400 and the Workspace backend requires one.

**Comment by davelab6** [comment]
@israelblenn the API URL @nyshadhr9 posted should resolve this for you, so closing.
