### ISSUE TITLE
Add [Font Name]

### ISSUE THREAD

**Issue by natepowers2009** [google/fonts#5634]
**Font Project Git Repo URL:**

**Super short description of the Font Family:**

**Requirements:**

I understand that Google Fonts will publish only fonts that matches its requirements, and I can confirm the project meets them (by ticking the cases, or putting x between the square brackets in text mode):

- [ ] The entire font project is licensed under the [OFL](https://scripts.sil.org/cms/scripts/page.php?site_id=nrsi&id=OFL)
- [ ] There is no "Reserved Font Name" mention in the OFL license
- [ ] Family name is unique according to namecheck.fontdata.com
- [ ] The font supports at least [GF Latin Core glyphset](https://github.com/googlefonts/glyphsets/tree/main/GF_glyphsets/Latin/)
- [ ] The repository respect the [upstream repo structure](https://googlefonts.github.io/gf-guide/upstream.html)
- [x] The source files are available in the repository
- [x] I read, agree and comply with the full [contributing requirements](https://googlefonts.github.io/gf-guide/onboarding.html)
- [ ] I am the author of the font or the author agreed to this submission
- [x] I will maintain the repository

**Image:**

Attach here a pic or a screenshot of the font; one is enough, it can be few letters, to give a quick overview.

**Comment by fitojb** [comment]
Google Fonts will not distribute fonts with proprietary licenses. Please remove the attachment as it constitutes illegal distribution.

**Comment by natepowers2009** [comment]
I want to use the font in google docs, but I don't know how.
If this is possible could you please tell me how,
and if not could you provide an alternative?

Thank you!

**Comment by applecuckoo** [comment]
Hey there, I think [Kaushan Script](https://fonts.google.com/specimen/Kaushan+Script?category=Handwriting) is a good alternative, but it depends on personal choice. Have a look in the [Handwriting category](https://fonts.google.com/?category=Handwriting) on Google Fonts to see what works for you.
