### ISSUE TITLE
Add ZoomlaCusong

### ISSUE THREAD

**Issue by simoncozens** [google/fonts#5635]
This is a manual issue transform from googlefonts/gftools#185:

> We are a Chinese font manufacturer, font brand name: z01, and was included in:https://docs.microsoft.com/en-us/typography/vendors/#z

> We developed ZoomlaCusong fonts,There are CJK and Latin, and it is licenses are SIL Open Font License OFL 1.1.
> We want to contribute this font add to Google Font.
> GitHub repo: https://github.com/z01font/ZoomlaCusong
> Releases: https://github.com/z01font/ZoomlaCusong/releases

> Thanks.

**Comment by RosaWagner** [comment]
Hi @zoomla, thanks for your submission. Would it be possible to have the sources accessible in the repository? It would be the file from the font editor (.glyphs, UFO or else).

**Comment by RosaWagner** [comment]
@zoomla, I also don't see the OFL license in the repository. If you want to know more about our requirements, they are listed here:
- (Contributing a new font to GF)[https://googlefonts.github.io/gf-guide/onboarding.html]
- [Repository structure](https://googlefonts.github.io/gf-guide/upstream.html)
- [Font file requirements](https://googlefonts.github.io/gf-guide/requirements.html)

**Comment by NightFurySL2001** [comment]
Please be aware that this font is suspicious of copyright infringement of a commercial font. I have reported this issue to them in 2021 and they have stop releasing it under OFL. This issue can be closed safely (original issue is from 2020).

(top from repo, bottom from https://www.foundertype.com/index.php/FontInfo/index/id/178)

![image](https://user-images.githubusercontent.com/33471049/205449194-89683afa-37c0-420b-a97c-ea3750f26b89.png)
![image](https://user-images.githubusercontent.com/33471049/205449459-fee1fe76-6ab8-4a5d-99cb-d78b983a99a4.png)
