### ISSUE TITLE
Add [Voltaire]

### ISSUE THREAD

**Issue by EbenSorkin** [google/fonts#5636]
**Font Project Git Repo URL:**

** A highly expressive geometric font in a single weight**

**Requirements:**

I understand that Google Fonts will publish only fonts that matches its requirements, and I can confirm the project meets them (by ticking the cases, or putting x between the square brackets in text mode):

- [ x ] The entire font project is licensed under the [OFL](https://scripts.sil.org/cms/scripts/page.php?site_id=nrsi&id=OFL)
- [ x ] There is no "Reserved Font Name" mention in the OFL license
- [ x ] Family name is unique according to namecheck.fontdata.com
- [ x ] The font supports at least [GF Latin Core glyphset](https://github.com/googlefonts/glyphsets/tree/main/GF_glyphsets/Latin/)
- [ x ] The repository respect the [upstream repo structure](https://googlefonts.github.io/gf-guide/upstream.html)
- [ x ] The source files are available in the repository
- [ x ] I read, agree and comply with the full [contributing requirements](https://googlefonts.github.io/gf-guide/onboarding.html)
- [ x ] I am the author of the font or the author agreed to this submission
- [ x ] I will maintain the repository

**Image:**

<img width="454" alt="image" src="https://user-images.githubusercontent.com/2181213/204192008-9e28ff53-300a-4db6-9d4a-a44536605073.png">

**Comment by applecuckoo** [comment]
@EbenSorkin I believe this is being tracked in #4647.

**Comment by RosaWagner** [comment]
Thanks @EbenSorkin indeed there is an open issue already, so closing this one ;)
