### ISSUE TITLE
PT sans narrow - w700, latin extended not rendering

### ISSUE THREAD

**Issue by conica** [google/fonts#566]
I am working on a project that requires PT Sans Narrow weight 700. However, the project has to use glyph from Latin extended subset. On Google fonts site, they do render properly, but when I try to use it on the page, the weight 700 doesn't show as it should (the weight 400 does work properly).
Now - on Google fonts website it does render, but in the same browser (FF 50) nothing is at it should be.
I checked in Chrome - it works well - both weights.
i tried to use the fonts from local, as well as embed directly from g.fonts website - nothing worked.
I would be grateful for some assistance.

CODE:
`

	<head>
		<meta charset="utf-8">
		<link href="https://fonts.googleapis.com/css?family=PT+Sans+Narrow:400,700&amp;subset=latin,latin-ext" rel="stylesheet">
	</head>
	<body>
		<div style="font-family:'PT Sans Narrow', sans-serif;font-weight: 700;font-size:18px;">sdccz SDCCZ abcdefg ABCDEFG šđčćž ŠĐČĆŽ</div>
		<div style="font-family:'PT Sans Narrow', sans-serif;font-weight: 400;font-size:18px;">sdccz SDCCZ abcdefg ABCDEFG šđčćž ŠĐČĆŽ</div>
	</body>

`

Image from G.fonts site
![gfonts](https://cloud.githubusercontent.com/assets/2979633/21680365/94ba57c2-d349-11e6-9353-26528a7f9536.png)

Local website FF 50
![local](https://cloud.githubusercontent.com/assets/2979633/21680372/a2f2a02e-d349-11e6-9efb-357d3b0ab4bf.png)

**Comment by davelab6** [comment]
@conica thanks for reporting!

**Comment by laerm0** [comment]
@conica Do you still have this issue? FF (55.0.3) looks good to me.

![screen region 2017-09-19 at 14 36 14](https://user-images.githubusercontent.com/10780161/30608957-fa05420e-9d47-11e7-8258-7b4e932512a0.png)
