### ISSUE TITLE
Maven Pro: interpolated glyphs

### ISSUE THREAD

**Issue by m4rc1e** [google/fonts#567]
Hey @ThomasJockin,

It appears Maven Pro has some incorrect interpolations in v2.001. This version hasn't made its way onto the server yet.

![screen shot 2017-01-05 at 14 49 27](https://cloud.githubusercontent.com/assets/7525512/21684603/30b84ad8-d356-11e6-9ab2-64d3820ad46e.png)

Please take a look at the compatibility of these:
-equal
-approxequal
-equal
-approxequal

Since this issue keeps cropping up, I've written a test for it in my [mf_glyphs_scripts](https://github.com/m4rc1e/mf-glyphs-scripts). Install/repull it then go to QA > Check Font.

![screen shot 2017-01-05 at 14 52 03](https://cloud.githubusercontent.com/assets/7525512/21684661/8d7dbc8a-d356-11e6-858b-5deeef67bc89.png)

Please repull your Maven repo, so you inherit the mastering I've done.

Cheers,
Marc

cc @davelab6

**Comment by ThomasJockin** [comment]
Thank you Marc, for your prompt and continued inventiveness to compensate for feeble humans ;-)

I'm traveling until Monday. 
Will repull and make corrections when I get back to NYC.

**Comment by fitojb** [comment]
Also ‘%’ is having problems:
![q](https://cloud.githubusercontent.com/assets/554953/23146817/cdd543b2-f79f-11e6-918d-909e9541d5cd.png)

**Comment by m4rc1e** [comment]
Issue still exists:
![screen shot 2017-06-14 at 14 26 22](https://user-images.githubusercontent.com/7525512/27134440-78d0d6b6-510d-11e7-9fb5-09924a64a47e.png)

http://jsbin.com/deceyopolo/edit?html,output

I will fix it this week.

**Comment by m4rc1e** [comment]
Should be addressed in #1073

**Comment by m4rc1e** [comment]
Maven Pro v2.003 made it into production, 2017-08-29. This issue is solved

![screen shot 2017-08-31 at 10 42 32](https://user-images.githubusercontent.com/7525512/29917193-1f3ae7fe-8e39-11e7-8045-0a66d13a4e82.png)
