### ISSUE TITLE
No idea what's happening with Roboto Serif. Sometimes I can download it, sometimes it gives me a "500" error.

### ISSUE THREAD

**Issue by ngalerchalegocity60330** [google/fonts#5671]
**Describe the bug**
I'm not sure exactly what's happening, whether it's server maintenance or a bug, but in the past when I downloaded Roboto Serif I would often get a "500" error. Sometimes I've been able to get it to work by trying to download it again multiple times in a row, but other times it doesn't work and I get the "500" error instead. 

**To Reproduce**
Just download Roboto Serif as usual. See if you get directed to a 500 error. Then try to download it again a few times in a row and see if it works or not.

**Additional context**
I also have used my phone, logged in into another account I have, just to confirm it wasn't something about the way my computer or web browser is configured, just to see if the problem is also seen in other devices. And I confirmed that even with a different account on a phone it doesn't work.

**Comment by davelab6** [comment]
Thanks for reaching out about this. Sadly it is a known problem internally, due to the large number of static fonts making the zip very large. It is most likely to occur when downloading a set of selected families from the sidebar, but even the solo family from it's specimen page can trigger this.

**Comment by ngalerchalegocity60330** [comment]
No wonder. Glad to hear it truly wasn't something about my network configuration. Sad to hear that it's due to the large size of the font pack. I was thinking, since not everybody needs that huge amount of static fonts, they should have put the condensed, expanded, and all the other variants, as their own separate font packs in Google Fonts. 

Thank you very much for everything.

**Comment by RosaWagner** [comment]
Since it's known issue tracked internally, I close it here.
