### ISSUE TITLE
Add Rethink Sans

### ISSUE THREAD

**Issue by emmamarichal** [google/fonts#5683]
**Font Project Git Repo URL:**
Private repo for now: https://github.com/hans-thiessen/Rethink-Sans
email discussion with @RosaWagner 

**Super short description of the Font Family:**
It's currently four weights (Regular, Medium, Bold, Extrabold), covers GF Latin Core glyphset, and has gone through several rounds of design testing/refining.

There are a few things still in development:
ITALICS: still WIP, but they'd be expanded to cover all four weights and the full glyphset
VARIABLE: it's built to be variable (weight axis), which could be exported/included in the final product. 

**Requirements:**

I understand that Google Fonts will publish only fonts that matches its requirements, and I can confirm the project meets them:

- [x] The entire font project is licensed under the [OFL](https://scripts.sil.org/cms/scripts/page.php?site_id=nrsi&id=OFL)
- [x] There is no "Reserved Font Name" mention in the OFL license
- [x] Family name is unique according to namecheck.fontdata.com
- [x] The font supports at least [GF Latin Core glyphset](https://github.com/googlefonts/glyphsets/tree/main/GF_glyphsets/Latin/)
- [x] The repository respect the [upstream repo structure](https://googlefonts.github.io/gf-guide/upstream.html)
- [x] The source files are available in the repository
- [ ] I read, agree and comply with the full [contributing requirements](https://googlefonts.github.io/gf-guide/onboarding.html)
- [ ] I am the author of the font or the author agreed to this submission
- [ ] I will maintain the repository

**Image:**
<img width="1327" alt="Capture d’écran 2022-12-08 à 09 49 59" src="https://user-images.githubusercontent.com/64773544/206402660-a6b17cfe-2069-4720-80d3-1c3f5102cfe1.png">

**Comment by yanone** [comment]
I got invited to collaborate on the upstream repo. Shall I assign myself to this issue to keep track of it?

**Comment by emmamarichal** [comment]
Yes same, and @vv-monsalve too. As you want, I can do it also.

**Comment by yanone** [comment]
Sure, do it. I'm just making sure that I wasn't the only one getting invited to collaborate.

**Comment by RosaWagner** [comment]
I asked for everyone in the team to be invited until someone gets assigned. The project is not finished but the designer may need guidance to set up everything so he can develop further without going in the wrong direction. I'd like to test a process of pre-onboarding review during the design phase to avoid designers being surprised a bit too late by GF requirements. @emmamarichal feel free to open issues in the upstream repo to help (like adding an intermediate style etc, or design problems), and ask progress status etc.

**Comment by luciascarlet** [comment]
The original repository is gone :( Anyone know what happened to it?

**Comment by emmamarichal** [comment]
Hello @luciascarlet, about which repo are you talking about? If you can't see the one linked on the top of this issue, it's because it's private :)

**Comment by luciascarlet** [comment]
Ah, yeah I was talking about the one linked. I see, thanks for explaining :)

**Comment by emmamarichal** [comment]
Re-opened because some changes are needed in metadatas, readme and description

**Comment by emmamarichal** [comment]
The designer postponed the release, so it's frozen for now
