### ISSUE TITLE
De-list Coda Caption

### ISSUE THREAD

**Issue by NiketBahety** [google/fonts#5689]
Specify the font name in title with a short description of the bug. 
Please report any issue related to Noto fonts in this repository: https://github.com/googlefonts/noto-fonts/issues.

**Describe the bug**
While selecting Coda Caption font the URL generated is invalid
**To Reproduce**
Steps to reproduce the behavior.
Select the Coda Caption font and try to open the url it does not exist because it has missing font weight in URL so it tries to find 400 weight by default but it does not exist,
**Expected behavior**
Normally it should have added the weight in the URL
**Screenshots**
<img width="220" alt="image" src="https://user-images.githubusercontent.com/86421121/206673267-00992188-10e2-4557-827b-ca058c09eb82.png">
<img width="455" alt="image" src="https://user-images.githubusercontent.com/86421121/206673309-17484da2-cfb8-44c2-8c08-355ae417d2a0.png">

**Additional context**
Add any other context about the problem here (OS version, browser, printer…)

**Comment by RosaWagner** [comment]
Thanks for reporting. This is an old font and it shouldn't have been release with "ExtraBold" as a default style. Please use Coda instead: https://fonts.google.com/specimen/Coda it as a similar ExtraBold style with better spacing.

**Comment by NiketBahety** [comment]
Thank you for such a quick response. I am using Coda.
