### ISSUE TITLE
Add Tyrowo Inked

### ISSUE THREAD

**Issue by Tyrowo** [google/fonts#5699]
**Font Project Git Repo URL:**
https://github.com/Tyrowo/TyrowoInked

**Super short description of the Font Family:**
This is a font derived from the personal pen-and-ink handwriting of Tyrowo.

**Requirements:**

I understand that Google Fonts will publish only fonts that matches its requirements, and I can confirm the project meets them (by ticking the cases, or putting x between the square brackets in text mode):

- [x] The entire font project is licensed under the [OFL](https://scripts.sil.org/cms/scripts/page.php?site_id=nrsi&id=OFL)
- [x] There is no "Reserved Font Name" mention in the OFL license
- [x] Family name is unique according to namecheck.fontdata.com
- [ ] The font supports at least [GF Latin Core glyphset](https://github.com/googlefonts/glyphsets/tree/main/GF_glyphsets/Latin/)
- [ ] The repository respect the [upstream repo structure](https://googlefonts.github.io/gf-guide/upstream.html)
- [ ] The source files are available in the repository
- [ ] I read, agree and comply with the full [contributing requirements](https://googlefonts.github.io/gf-guide/onboarding.html)
- [x] I am the author of the font or the author agreed to this submission
- [x] I will maintain the repository

Attach here a pic or a screenshot of the font; one is enough, it can be few letters, to give a quick overview:

![tyrowoInkedPreview](https://user-images.githubusercontent.com/74413184/207468525-7a94e3fa-7a7b-4223-b691-b0a5d14c39bf.png)

**Comment by Tyrowo** [comment]
> I'd like to suggest making the name Tyrowo not Tyro to avoid a confusion with Tiro as in Tiro Typeworks, although I defer to @tiroj on this
> 
> Overall I've seen handwriting fonts like this become extremely widely used, IF the glyph set is wide and the kerning, technical quality and file size is good. I defer to the other GF submission reviewers on that.

I'd be more than happy to change the name to Tyrowo, is there any easy way to edit the metadata without rebuilding the font?

**Comment by Tyrowo** [comment]
> I'd like to suggest making the name Tyrowo not Tyro to avoid a confusion with Tiro as in Tiro Typeworks, although I defer to @tiroj on this

I've updated the metadata for all my files to be named Tyrowo Inked now. Preview pictures (including in this submission) have been updated as well.

**Comment by RosaWagner** [comment]
Hi @Tyrowo, thanks for your submission. 

As @davelab6 said, handwriting fonts are indeed very popular. Unfortunately, the font is made using https://www.calligraphr.com/en/ which is not a font making method we can accept. We need to be able to repeat the font building process, and also to have some power over the metadata and the production process — which is impossible using this kind of font generator. There is also no control over the outline quality, which makes it extremely difficult to improve the rendering or to fix some glyphs if needed.

If you are interested in pursuing your type design practice, I would recommend to follow this curated type design resource: https://justinpenner.github.io/type-design-resources/ by Justin Penner. It is made to accompany people in their journey to learn professional type design :) You can also find plenty of resources here: http://rosaliewagner.com/type-links/.

Enjoy all the fun ahead of you, and don't hesitate to come back to us when the font is matching GF requirements :)

**Comment by Tyrowo** [comment]
> Hi @Tyrowo, thanks for your submission.
> 
> As @davelab6 said, handwriting fonts are indeed very popular. Unfortunately, the font is made using https://www.calligraphr.com/en/ which is not a font making method we can accept. 

Disappointing, but understandable. Thanks for the resources, eventually I might revisit this project and see what I can do.
