### ISSUE TITLE
Add Honk

### ISSUE THREAD

**Issue by davelab6** [google/fonts#5711]
New commission of a color vf from @ektype, will be delivered middle of 2023, so putting in 2023 Q2 milestone as it might be ready late Q2 if we are lucky, but could be later :)

**Comment by chrissimpkins** [comment]
The team estimates ~ 4 months of development time to go.  Moving back to Q3 milestone

**Comment by davelab6** [comment]
@yanone will be back in September. @girish-dalvi do you think it be may completed in August?

**Comment by girish-dalvi** [comment]
Yes, the project is on track to be completed by the end of August.

**Comment by chrissimpkins** [comment]
Girish contacted us this week.  The source files are ready for review / QA @ https://github.com/EkType/Honk

**Comment by yanone** [comment]
@chrissimpkins @davelab6 

Before we have our call later today, I’ll start with this one, as it's marked as P1.

Dave, could you add Chris to the "Yanone / Dave" call later? I tried but don't have permission to add people. He said he'd like to join if possible.

**Comment by chrissimpkins** [comment]
Needs axis registrations for style and shadow axes.
