### ISSUE TITLE
google font and icon site is down

### ISSUE THREAD

**Issue by MrShahidBabar** [google/fonts#5712]
google font and icons site is down.
https://fonts.googleapis.com/icon?family=Material+Icons|Material+Icons+Outlined
I am getting site is not accessible error. please fix it asap. my site is affected due to this.
Regards,
Shahid

**Comment by m4rc1e** [comment]
Works for me.

**Comment by RosaWagner** [comment]
I guess it was fixed? @MrShahidBabar please ask us to re-open this issue if there is still a problem.
