### ISSUE TITLE
Bodoni Moda has no symbol for "+"

### ISSUE THREAD

**Issue by chloeaster** [google/fonts#5722]
Specify the font name in title with a short description of the bug. 
Please report any issue related to Noto fonts in this repository: https://github.com/googlefonts/noto-fonts/issues.

**Describe the bug**
- When using the font on my site, there is no "+" icon that gets displayed. 

**To Reproduce**
Steps to reproduce the behavior.
- type "+" in the google fonts "selected fonts" area (https://fonts.google.com/share?selection.family=Bodoni+Moda:opsz@6..96)
- when you type "+" in the regular view (https://fonts.google.com/?preview.text=Hello%2B&preview.text_type=custom&query=bodoni+moda), you see the "+" sign

**Expected behavior**
- When using the font, all common symbols should be visible.  

**Screenshots**
<img width="891" alt="Screen Shot 2022-12-16 at 12 27 18 PM" src="https://user-images.githubusercontent.com/99741643/208154608-6787fbfd-ecbf-48ce-ab72-bd9c20928b1e.png">

**Additional context**
Add any other context about the problem here (OS version, browser, printer…)

**Comment by thlinard** [comment]
Interpolation bug of + and × on the opsz axis.
