### ISSUE TITLE
Roboto Light Issue/inconsistency between Windows and MacOS

### ISSUE THREAD

**Issue by naptownposse** [google/fonts#5723]
I'm seeing an issue of inconsistencies in the use of Roboto Light in Windows 10 and MacOS Monterrey.  

Specifically, on Windows I can apply a bold setting to Roboto Light and it appears to display properly.  However in MacOS when I apply a bold format to Roboto Light it converts to italics and then bolds italics.  This was in Microsoft 365 version of Word on each operating system.  I've also tried bolding Roboto Light in Pages on MacOS and instead of formatting in italics it converts it from Roboto Light to Roboto Bold rather than applying bold to Roboto Light.

I've tried uninstalling and reinstalling the font on the Mac, but this doesn't appear to change the behavior.  I've also rebooted, but same issue.

Any helpful tips, advice, or education on why this is occurring or how to get Roboto Light to format in bold on my Mac like it does on my PC would be gratefully appreciated.

Thanks!

![RobotoScreenshotWord](https://user-images.githubusercontent.com/19803671/208187558-28a79679-e916-4d2e-992a-e771cf77f8e7.JPG)
![RobotoScreenshotPages](https://user-images.githubusercontent.com/19803671/208187578-4f7d2874-3d06-418f-a61e-0ba593b0c728.JPG)

https://user-images.githubusercontent.com/19803671/208187710-6aa4cdcf-3e98-41f6-a94d-543387caf37b.mov

https://user-images.githubusercontent.com/19803671/208187734-058e4f51-cfe9-4527-bb77-7f990ecd8dc2.mov

**Comment by kenmcd** [comment]
Microsoft 365 Cloud Fonts did/does have a version of Roboto available - just Regular, no Italics - last time I saw all the cloud fonts in Word (they disabled my developer account so I can no longer get the updates).

The fonts from GF are fine, so they are not the issue.

So I am wondering if you have a conflicting mix of fonts you have installed from GF, 
and some duplicates from the M365 cloud fonts.
And that is confusing the style-linking in Word.
The cloud fonts are only supposed to download if you do not have the fonts installed.
But it may not work perfectly all the time.

Makes sure there are no Roboto fonts from the M635 cloud fonts on your Mac.
I think the cloud fonts folders would be in here:
`Library/Group Containers/UBF8T346G9.Office/FontCache/4/CloudFonts`
and then look for a `Roboto` folder.
Delete the `Roboto` folder if there is one.
Then clear your Mac font cache (doing this first alone may also fix the issue).
The re-start Word and see if that helps.

**Comment by naptownposse** [comment]
Great!  Thanks for the tip and the timely response.  I’ll get back to you once I’ve had a chance to try this.

**Comment by kenmcd** [comment]
> Specifically, on Windows I can apply a bold setting to Roboto Light and it appears to display properly. However in MacOS when I apply a bold format to Roboto Light it converts to italics and then bolds italics.

I just read your initial post again, more closely this time.
Word will apply fake bold or fake italics if the actual styles are not available.
There is no Bold of the Light.
There is no BoldItalic of the Light Italic.
So what you are seeing are these faked versions.

Apparently on the Mac this causes different styles to be selected.
Only the Regular, Italic, Bold, and BoldItalic are linked together.
The Thin, Light, Medium, and Black are only linked to their respective Italics.

**Comment by naptownposse** [comment]
Thanks for clarification.  I think the suggestion in your first response seems to have done was I was hoping for.  Fingers crossed.  I’ll let you know if I notice any more peculiarities.  Thanks  for you time.

**Comment by kenmcd** [comment]
Great. Glad you got it working. 
So it sounds like it was a combination both issues.
