### ISSUE TITLE
Update Outfit

### ISSUE THREAD

**Issue by andyfitz** [google/fonts#5726]
**Font Project Git Repo URL:**
https://github.com/Outfitio/Outfit-Fonts

**Current version:**
1.0

**New available version:**
1.1

**Super short description of the upgrade:**
Expanded glyph set. See https://github.com/Outfitio/Outfit-Fonts/pull/17
Updated copyright owner (acquired by Smartsheet)

**Comment by andyfitz** [comment]
Heads up @davelab6  :)

**Comment by andyfitz** [comment]
any update on this ?

**Comment by chrissimpkins** [comment]
Moving to the Q2 milestone
