### ISSUE TITLE
Add Labrada

### ISSUE THREAD

**Issue by Omnibus-Type** [google/fonts#5731]
Font Project Git Repo URL:
https://github.com/Omnibus-Type/Labrada

New Typeface Family version: 1.0

Labrada is a contemporary serif typeface family inspired by the art of woodcut. This family was designed by Mercedes Jáuregui. In 2022 was developed as 1 axis (weight) variable font. Initial release under SIL Open Font License. To contribute, see https://github.com/Omnibus-Type/Labrada

Bugs reported in this repo which this upgrade would fix: None

I understand that Google Fonts will publish only fonts that matches its requirements, and I can confirm the project meets them (by ticking the cases, or putting x between the square brackets in text mode):

- [X] The entire font project is licensed under the [OFL](https://scripts.sil.org/cms/scripts/page.php?site_id=nrsi&id=OFL)
- [X] There is no "Reserved Font Name" mention in the OFL license
- [X] Family name is unique according to namecheck.fontdata.com
- [X] The font supports at least [GF Latin Core glyphset](https://github.com/googlefonts/glyphsets/tree/main/GF_glyphsets/Latin/)
- [X] The repository respect the [upstream repo structure](https://googlefonts.github.io/gf-guide/upstream.html)
- [X] The source files are available in the repository
- [X] I read, agree and comply with the full [contributing requirements](https://googlefonts.github.io/gf-guide/onboarding.html)
- [X] I am the author of the font or the author agreed to this submission
- [X] I will maintain the repository

**Labrada Specimen**

![Labrada-01](https://user-images.githubusercontent.com/8041808/209986688-d0576719-4479-4fec-a454-6c4877d85b0b.png)

**Comment by fitojb** [comment]
The best typography of the last decade has been made in South America

**Comment by xconsau** [comment]
Great work. Beautiful.

**Comment by applecuckoo** [comment]
@Omnibus-Type the paragraph still has an instance of the old Albura link

> Labrada is a contemporary serif typeface family inspired by the art of woodcut. This family was designed by Mercedes Jáuregui. In 2022 was developed as 1 axis (weight) variable font. Initial release under SIL Open Font License. To contribute, see **https://github.com/Omnibus-Type/Albura**

**Comment by Omnibus-Type** [comment]
Thanks @applecuckoo! 
Done!

**Comment by Omnibus-Type** [comment]
Hi, @emmamarichal!
Labrada (formerly Albura) is a *commissioned* project. 
Please change the label *Submission* by *Commissioned*.
