### ISSUE TITLE
Add [Font Name] comic Sans

### ISSUE THREAD

**Issue by klm5985** [google/fonts#5734]
**Font Project Git Repo URL:**

**Super short description of the Font Family:**

**Requirements:**

I understand that Google Fonts will publish only fonts that matches its requirements, and I can confirm the project meets them (by ticking the cases, or putting x between the square brackets in text mode):

- [x] The entire font project is licensed under the [OFL](https://scripts.sil.org/cms/scripts/page.php?site_id=nrsi&id=OFL)
- [x] There is no "Reserved Font Name" mention in the OFL license
- [x] Family name is unique according to namecheck.fontdata.com
- [ ] The font supports at least [GF Latin Core glyphset](https://github.com/googlefonts/glyphsets/tree/main/GF_glyphsets/Latin/)
- [ ] The repository respect the [upstream repo structure](https://googlefonts.github.io/gf-guide/upstream.html)
- [ ] The source files are available in the repository
- [ ] I read, agree and comply with the full [contributing requirements](https://googlefonts.github.io/gf-guide/onboarding.html)
- [ ] I am the author of the font or the author agreed to this submission
- [ ] I will maintain the repository

**Image:**

Attach here a pic or a screenshot of the font; one is enough, it can be few letters, to give a quick overview.

**Comment by applecuckoo** [comment]
Nope, won't happen, Comic Sans belongs to Microsoft and is a commercial font, so it won't be accepted. Do try [Comic Neue](https://fonts.google.com/specimen/Comic+Neue) though, it was developed as an alternative to Comic Sans and is similar in tone.

**Comment by RosaWagner** [comment]
Hi @klm5985, thanks for your suggestion. As @applecuckoo mentioned, GF only distributes open source fonts and therefore won't distribute Comic Sans MS. I how the alternative suggested will be of help.
