### ISSUE TITLE
Noto Sans KR line height is too large

### ISSUE THREAD

**Issue by Dev-james1112** [google/fonts#5735]
Specify the font name in title with a short description of the bug. 
Please report any issue related to Noto fonts in this repository: https://github.com/googlefonts/noto-fonts/issues.

**Describe the bug**
In React Native, The line height of Noto Sans KR is too large

**To Reproduce**
1. In React Native, apply a Noto Sans KR font at text component

**Expected behavior**
The line height should be similar to the font height

**Screenshots**
![image](https://user-images.githubusercontent.com/79844149/210167334-133c073c-3fc5-4b35-af84-a0d8b4498a8a.png)

**Additional context**
android version: Android 10
device: Galaxy Note 9
react-native version: 0.70.5

**Comment by applecuckoo** [comment]
@Dev-james1112 You might want to open an issue in https://github.com/adobe-fonts/source-han-sans, Google uses the sources from there. (No, that's not an error, Google rebrands Adobe Source Han Sans as Noto Sans KR, but that's not the point)

**Comment by RosaWagner** [comment]
Hi @Dev-james1112, thanks for your report. Unfortunately we can't do anything here about how the line height is displayed in React Native. Maybe report the problem to the app directly?
