### ISSUE TITLE
Update Tiro Telugu (critical shape fixes)

### ISSUE THREAD

**Issue by tiroj** [google/fonts#5742]
**Font Project Git Repo URL: https://github.com/TiroTypeworks/Indigo**

**Current version: 1.52**

**New available version: 1.53**

**Super short description of the upgrade:**
Fixed incorrect shape of four glyphs in both TiroTelugu-Regular and TiroTelugu-Italic

**Bugs reported in this repo which this upgrade would fix:**
https://github.com/TiroTypeworks/Indigo/issues/31
https://github.com/TiroTypeworks/Indigo/issues/53

**Comment by sonymoparthi** [comment]
Thank you very much for fixing the issue so quickly.

I have used the following links to use the font in my webpage.

[<link rel="preconnect" href="https://fonts.googleapis.com"/>
 <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin/>
 <link href="https://fonts.googleapis.com/css2?family=Tiro+Telugu&display=swap" rel="stylesheet"/> 
](url)

What should I do now to reflect the fix in my page?

Thanks you!
Sony

**Comment by sonymoparthi** [comment]
Thank you very much for fixing the issue so quickly.

I have used the following links to use the font in my webpage.

> 
    <link rel="preconnect" href="https://fonts.googleapis.com"/>
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin/>
    <link href="https://fonts.googleapis.com/css2?family=Tiro+Telugu&display=swap" rel="stylesheet"/> 
    

What should I do now to reflect the fix in my page?

Thanks you!
Sony

**Comment by tiroj** [comment]
You will have to wait for Google Fonts to test the update and pull it into their system. This issue only alerts Google Fonts to the fact that an update is available in the source repo.

**Comment by tiroj** [comment]
Not really. It depends on Google Fonts’ staff availability to run tests and review the updates, then create a PR for the update. The testing itself should not be an issue, since only the shapes of four glyphs were adjusted and no other changes to the font data.

**Comment by sonymoparthi** [comment]
Thanks Mr.John Hudson. Thanks a lot. 

Best Regards,
Sony
