### ISSUE TITLE
IBM Plex family missing font feature settings

### ISSUE THREAD

**Issue by 0hwow** [google/fonts#5745]
IBM Plex family font features are missing . For example, Plex Mono slashed zero.
If the font is self hosted with CSS `font-feature-settings: "zero"` the slashed zero glyph works, but not if the font is referenced via goggleapis.
Thank you

**Comment by RosaWagner** [comment]
Hi @0hwow, thanks for your report. You would find that issue with all fonts from the catalog because, unfortunately, GF API doesn't support opentype features for stylistic variant such as slashed zero or stylistic sets. To be able to use you would have to self host the font.
