### ISSUE TITLE
Add Chiu Yuen Sans HK to Early Access

### ISSUE THREAD

**Issue by tamcy** [google/fonts#575]
I am the author of the font named "[CYanHeiHK](https://github.com/tamcy/CYanHeiHK)", which is a fork of Noto Sans CJK (TW). As Noto Sans CJK (Traditional Chinese) conforms to Taiwan's glyph standard, I made this fork as an alternative for Hong Kong users.

CYanHeiHK includes remapping and redesigning of current glyphs to meet the HK glyph standard. However, my font isn't all about fulfilling HK glyph standard - for some codepoints, the traditional forms of the glyphs are used as they are adopted by most commercial font products in HK. This makes the font more appealing to users or readers, at least before their "standard" forms become more common in use.

The font also provides a subsetted version. It can be used as a drop-in replacement to the current "Noto Sans TC (Chinese Traditional)" offering in Google Fonts Early Access. Currently, many written Cantonese words are missing from "Noto Sans TC".

I would like to propose the subsetted version of CYanHeiHK to be included in Google Fonts. I've read the contribution page, but given the nature of this font (i.e. a CJK font) and the status of similar fonts (i.e. in "early access" stage), I am not sure if the font is qualified for inclusion. Thank you!

**Comment by davelab6** [comment]
@tamcy thanks for filing this issue. I'm very happy to see your efforts to localize Noto Sans CJK to meet your specific needs. I wonder if your version could be contributed upstream to the Noto project; the "Noto Font" Google Group mailing list is the best place for that (<https://groups.google.com/forum/#!forum/noto-font>)

cc @marekjez86 and @kenlunde :)

**Comment by kenlunde** [comment]
In the spirit of "the more fonts, the merrier," I don't see a problem with using CYanHeiHK as an interim solution for HK users, or as an alternative once Noto Sans CJK Version 2.000 is developed, which will include separate HK fonts and font instances. The delay for the latter is related to the forthcoming release of the new version of Hong Kong SCS.

BTW, I prefer the shape of the U+8FB6 辶 component in CYanHeiHK, and this is likely to be another change for Version 2.000. And yes, I am aware that you suggested such a change in Source Han Sans [Issue 50](https://github.com/adobe-fonts/source-han-sans/issues/50).

**Comment by hfhchan** [comment]
Is there any update for this issue? As a Hong Kong user, I see CYanHeiHK as a decent competitor to Source Han Sans.

**Comment by davelab6** [comment]
@tamcy could you tell me more about the name? "CYanHeiHK" isn't ideal for me; I would prefer 
something which can be spoken in a flow of syllables that make a single word, like "Tamcy", rather than "Cee Yan Hei Achsh Kay"

**Comment by davelab6** [comment]
@hfhchan thanks for the ping :)

**Comment by tamcy** [comment]
@davelab6 Thanks for the question. I understand that the name CYanHeiHK can look strange to non-Chinese users as the name doesn’t line up with the English fonts like Times New Roman, Noto Sans, Source Sans, Roboto, Garmond etc. I'll explain how I came up with this name.

The font’s Chinese name is 昭源甄黑體, which could be transcribed as “Chiu Yuen Yan Hak Tai”. 昭源 (Chiu Yuen) is the brand, while 甄黑體 (Yan Hak Tai) is the name of the font. 

1. The suffix, HK, indicates that the font is primarily for Hong Kong users.

2. I didn't want to stick my name on the font (it’d make the font too personal), so “Tamcy” isn't an option from the beginning. “昭源” reads like “Chiu Yuen” in Cantonese, which is abbreviated to CY. I chose this brand so that there's still a weak trace of my name on it.

3. “黑體” means sans-serif/gothic typeface. Font vendors in Taiwan/Hong Kong usually uses “Hei” to name the fonts of this family (like Microsoft’s JhengHei, Monotype’s YingHei, Dynalab’s LiHei etc). I chose to follow this convention, thus “YanHei” for “甄黑體”.

4. Initially, 昭源甄黑體 is “CYYanHeiHK”. But that two Ys look odd, so I make it “CYanHeiHK”. I didn’t use space mostly because it saves me some typings when accessing from an auto-complete list and defining it in CSS.

5. In fact, the “Prefixed brand name - font name” naming scheme is quite common in Traditional Chinese fonts. For instance, Monotype names their fonts as MHeiHK, MYingHeiHK and MSungHK. “M” is the brand's prefix. Another font foundry, DynaLab, has their fonts prefixed with “DF” (DynaFont), like DFMing, DFLiHei etc. I believe this is for quicker access to the available fonts from the same vendor.

6. I am not sure if Chiu Yuen or ChiuYuen, the Cantonese transliteration of 昭源, looks fine for non-Chinese speakers. Even the Mandarin transliteration doesn’t look very good to me. If a non-abbreviated name is desired, I’d rather call it something like “Shougen Gothic” or “Shougen Sans”, as “Shougen” (Japanese transliteration of 昭源) looks more like an English word than Chiu Yuen or ChiuYuen/Chiuyuen/Chiu-yuen, no matter how you arrange it. The only problem is that the Shougen Gothic looks like a Japanese typeface. I probably need more time to come up with a better name if the current one cannot be used.

**Comment by hfhchan** [comment]
@tamcy @davelab6 I'd rather the name CYanHeiHK be kept, or CYanHei Hong Kong if that looks more natural.  Compare with cwTeXKai / cwTeXYen / cwTeXHei, which is hard to pronounce in English, but more or less instantly recognizable as a Chinese font by Chinese users.

Otherwise, CY YanHei HK may be a reasonable compromise along the lines of "Microsoft Jhenghei" and "Dynalab LiHei".

**Comment by kenlunde** [comment]
Alternatively, especially if this isn't critical, we can simply wait until Noto Sans CJK Version 2.000 is available. 😉

**Comment by hfhchan** [comment]
Unless Noto Sans CJK HK subset is willing to diverge strongly from the official reference glyphs, I think CYanHeiHK would be a very strong competitor to Noto Sans CJK ;)

Below is an excerpt of "necessary" deviations, shamelessly pulled from @tamcy 's repository and edited:
![image](https://cloud.githubusercontent.com/assets/8191296/26615611/b4b4405a-45fa-11e7-8a80-0d73dd68b8b6.png)
(The two uncircled glyphs on the left are no longer proposed by the government)

Affected glyphs are upwards of 500 (but most differences can be directly lifted from Noto Sans CJK SC/JP), if @adobe-fonts would prefer to take the risk.

**Comment by davelab6** [comment]
@kenlunde 

> Alternatively, especially if this isn't critical, we can simply wait until Noto Sans CJK Version 2.000 is available. 

When will that be? :D

@tamcy @hfhchan 

I am (slowly) moving the GF collection away from any brand names, such that there is no friction for anyone who wants to integrate the entire collection into their own program. 

I think this name would be ideal: `Shougen Gothic HK`

**Comment by hfhchan** [comment]
I am a bit wary of using a Japanese name for CYanHei.  I don't think it is a good thing to name a localized product with a Japanese name.  It will certainly put off the more conservative Hong Kong website users.

**Comment by kenlunde** [comment]
@davelab6: It's being worked on. Our target is later this year.

**Comment by tamcy** [comment]
@hfhchan I am also thinking about this, although to me it's just like borrowing names from Latin words.  Naming things is difficult, I'll probably settle with something like `Chiu Yuen Sans HK`.

@davelab6 What should I do once I decide on the name? Do I need to rebuild the font?

**Comment by davelab6** [comment]
That name also works for me. You can avoid rebuilding​ by editing the name
table. @m4rc1e has a script to do it off the fiename

Ken, thank you for the tip :)

**Comment by tamcy** [comment]
@davelab6 I couldn't spot the script, hope you can give me some hints :)

Anyway I've rebuilt the font with the new name `Chiu Yuen Sans HK`, which can be found [here](https://github.com/tamcy/CYanHeiHK/tree/webfont-binary). Please check if it's ok. Thanks!

**Comment by tamcy** [comment]
As Source Han Sans / Noto Sans CJK 2.0 with proper HK support should be coming in near future, I am closing this issue for now. Although my font isn't 100% compliant to HK's reference glyph (but more a resemble of the shape commonly used in HK published materials), this font will probably look immediately outdated when Noto Sans CJK 2.0 is released. I think it'd be better to wait for its release so that I could evaluate how to further enhance my font base on the new version, and resubmit this request again. Please reopen this issue if you found inappropriate. Thanks!

**Comment by davelab6** [comment]
Thanks for the update!
