### ISSUE TITLE
Monofett: Poor diacritics, "dcaron" and "tcaron" totally useless

### ISSUE THREAD

**Issue by designiq** [google/fonts#5783]
The font has very poor diacritics, it is missplaced, the shapes are very thin and very tall. The accents are designed neither in harmony with the type nor in harmony with each other. 

What is completely wrong, however, are the carons on the letters dcaron and tcaron. Here an apostrophe is used instead of the correct standard caron. If the letter d or t has a capital form, the standard caron is always used. The apostrophe-like form is used exclusively for the lower case characters. Just use the capital letter for lower case as well, the should look the same. And make sure, the caron is centered above T and properly placed above D (now it is far more on the left).

<img width="408" alt="image" src="https://user-images.githubusercontent.com/6051357/212476712-d54f265c-1205-4da6-9723-b7b28d12f75e.png">

**Comment by RosaWagner** [comment]
Hi @designiq thanks for your report. We'll remember to fix that bug when we'll upgrade Monofett.

**Comment by fitojb** [comment]
This issue is no longer reproducible.
