### ISSUE TITLE
Invalid cap height and x-height in Sancreek

### ISSUE THREAD

**Issue by IvanUkhov** [google/fonts#5786]
**Describe the bug**
The cap height and x-height are set to 281 and 402, respectively, which are very low values when looking at the actual glyphs (and also contradictory as the former should probably be larger than the latter).

**To Reproduce**
For instance, using `fonttools`:
```shell
ttx -t 'OS/2' ofl/sancreek/Sancreek-Regular.ttf
cat ofl/sancreek/Sancreek-Regular.ttx | grep CapHeight
#     <sCapHeight value="281"/>
```

**Expected behavior**
They should be set to adequate values.

**Comment by RosaWagner** [comment]
Hi @IvanUkhov, thanks for your report. We'll remember to correct that when we'll upgrade the font.
