### ISSUE TITLE
Add LXGW WenKai GB

### ISSUE THREAD

**Issue by pkj-l** [google/fonts#5790]
**Font Project Git Repo URL:**
https://github.com/lxgw/LxgwWenkaiGB

**Super short description of the Font Family:**
An open-source Simplified Chinese font which matches [the _Table of General Standard Chinese Characters_](https://en.wikipedia.org/wiki/Table_of_General_Standard_Chinese_Characters), derived from Klee One.

**Requirements:**

I understand that Google Fonts will publish only fonts that matches its requirements, and I can confirm the project meets them (by ticking the cases, or putting x between the square brackets in text mode):

- [x] The entire font project is licensed under the [OFL](https://scripts.sil.org/cms/scripts/page.php?site_id=nrsi&id=OFL)
- [x] There is no "Reserved Font Name" mention in the OFL license
- [x] Family name is unique according to namecheck.fontdata.com
- [x] The font supports at least [GF Latin Core glyphset](https://github.com/googlefonts/glyphsets/tree/main/GF_glyphsets/Latin/)
- [x] The repository respect the [upstream repo structure](https://googlefonts.github.io/gf-guide/upstream.html)
- [x] The source files are available in the repository
- [x] I read, agree and comply with the full [contributing requirements](https://googlefonts.github.io/gf-guide/onboarding.html)
- [ ] I am the author of the font or the author agreed to this submission
- [ ] I will maintain the repository

**Image:**
![Introduction](https://raw.githubusercontent.com/lxgw/LxgwWenkaiGB/main/documentation/wenkaigb-1.png)
![Difference](https://raw.githubusercontent.com/lxgw/LxgwWenkaiGB/main/documentation/wenkaigb-3.png)

**Comment by RosaWagner** [comment]
Hi @pkj-l, thanks for your submission. It was already submitted here https://github.com/google/fonts/issues/4601, so I'll close this issue to avoid duplicate.

**Comment by RosaWagner** [comment]
What I meant is that we are in contact with the author and already tracking the family.
