### ISSUE TITLE
Bug in Noto Sans Bengali v2.003

### ISSUE THREAD

**Issue by Tomasz-Wiatr** [google/fonts#5793]
**Font name:** Noto Sans Bengali v2.003
**Problem:** bug in the font.
**OS:** macOS 13.1, Windows 10, 
**App:** Adobe Indesign 18.1

Bug Description
An incorrect presence of some characters when using Noto Sans Bengali **v2.003** in Adobe InDesign.

![image_2023_01_17T14_41_26_AAA](https://user-images.githubusercontent.com/122973584/213142533-156e5e40-2614-4c77-8832-5c340f66db2a.png)

![image_2023_01_17T14_41_26_BBB](https://user-images.githubusercontent.com/122973584/213142655-975cbac3-6ff9-4087-af75-19fcb7552e2c.png)

After changing the font back to version **2.001**, text presence is correct, as shown in the screenshots below:

<img width="1208" alt="image_2023_01_17T14_52_47_DDD" src="https://user-images.githubusercontent.com/122973584/213143533-6caad551-bad5-4b1a-babb-72562ebab4d6.png">

<img width="904" alt="image_2023_01_17T14_52_04_CCC" src="https://user-images.githubusercontent.com/122973584/213143486-ded25eb2-432b-41b3-9c02-59c9659c876b.png">

**Comment by chrissimpkins** [comment]
@simoncozens

**Comment by simoncozens** [comment]
I've just tested with v2.003, and found that the "t'ru" conjunct is being formed correctly using Harfbuzz and CoreText:

```
$ shape ../notofonts.github.io/fonts/NotoSansBengali/hinted/ttf/NotoSansBengali-Regular.ttf 'ত্ত্রুটি'
[tarubeng=0+921|ttibeng=4+833]
```
![shape](https://user-images.githubusercontent.com/106728/224299818-247758e4-3292-407b-905e-6c17984a8df8.png)

I don't think there is a bug in the font but it's possible that InDesign is doing something wrong here. Please see [this blog post](https://rajeeshknambiar.wordpress.com/2020/11/09/harfbuzz-shaping-engine-in-indesign/) and InDesign's struggles with -u vowels in Indic compounds, and how to fix it by turning on Harfbuzz in InDesign.
