### ISSUE TITLE
Add Doulos SIL Cipher

### ISSUE THREAD

**Issue by chrissimpkins** [google/fonts#5797]
User request: 

> I would like to suggest a font to add to Google Fonts. It is Doulos SIL Cipher, the information can be found [here](https://software.sil.org/doulos-sil-cipher/). The font is licensed under SIL Open Font License. The font has a unique feature, displaying musical notation. Notation is widely used in Indonesia. Given that Google has a large user base in Indonesia, I think it would add value to both Google and its users.

Tentatively adding to the Q2 2023 milestone

**Comment by RosaWagner** [comment]
@chrissimpkins in this comment https://github.com/google/fonts/issues/4354#issuecomment-1079123957 @jvgaultney told us to not onboard this font because they support it only for legacy reason. So I guess we won't proceed with this one.
