### ISSUE TITLE
Update Oswald 

### ISSUE THREAD

**Issue by fowlerj** [google/fonts#58]
When using the font like this...

`<link href='https://fonts.googleapis.com/css?family=Oswald:400,300,700|Quattrocento:400,700|Open+Sans:300italic,400italic,600italic,700italic,400,600,300,700' rel='stylesheet' type='text/css'>`

... within a webpage rendered in IE10 when you print a document the text with Oswald will print the 's' character with these long lines that span over text below it until another element with Oswald begins.  This can look like lines that span from h2 over numerous paragraphs until the next h2 is encountered. 

The print previews all work without error, this only seems to be an issue when printing to a printer.

**Comment by adrientetar** [comment]
@fowlerj Did you mean to include an illustration?

**Comment by fowlerj** [comment]
I didn't realise that I needed three marks around code in markdown, my apology.  I hope that the updated comment will suffice.

**Comment by davelab6** [comment]
This is a known bug with earlier versions of ttfautohint. (Also Oswald family naming is not working in Word.)

**Comment by ldeks** [comment]
Are there any plans to fix this?  I *love* this font, but it doesn't print from Publisher 2013 correctly.  I can workaround this by publishing to PDF before printing, but the other user of my document will *hate* having to do that. :)

Is there a way I can remove the ttfautohint command and rebuild the Oswald ttf file?  I'm an experienced Linux developer.

**Comment by davelab6** [comment]
Yes, you can use `ttfautohint -d font.ttf out.ttf` to de-hint the font.ttf and produce out.ttf, and then you can reapply ttfautohint using the latest version to out.ttf

I can't give an estimate of when this will be fixed

**Comment by davelab6** [comment]
This will be fixed with the new build from https://github.com/m4rc1e/OswaldFont

**Comment by davelab6** [comment]
https://twitter.com/kirstyatx/status/806986802741526530 says

> @googlefonts Please fix the strangely sized punctuation in Oswald!

**Comment by laerm0** [comment]
Hm, I don't think the punctuation size in Oswald is odd. Or it isn't now, anyway. I think this can be closed.

![screen region 2017-09-12 at 10 56 14](https://user-images.githubusercontent.com/10780161/30332733-16e5b7b8-97a9-11e7-8c1b-9f83528a9800.png)

**Comment by davelab6** [comment]
I've asked for confirmation on Twitter

**Comment by adrientetar** [comment]
The square part of colon/semicolon should sit on the baseline if you ask me, it's kinda levitating right now.

Punctuation could be larger indeed, e.g. if you look at Action condensed, right now it doesn't seem as black as the text.

**Comment by davelab6** [comment]
Those are quality changes, not bug fixes... I'd rather tackle that across the collection than family by family.

**Comment by adrientetar** [comment]
"strangely sized punctuation" is a quality req indeed.
