### ISSUE TITLE
LT Funk Font 

### ISSUE THREAD

**Issue by ghost** [google/fonts#5839]
**Font Project Git Repo URL:**

**Super short description of the Font Family:**

**Requirements:**

I understand that Google Fonts will publish only fonts that matches its requirements, and I can confirm the project meets them (by ticking the cases, or putting x between the square brackets in text mode):

- [ ] The entire font project is licensed under the [OFL](https://scripts.sil.org/cms/scripts/page.php?site_id=nrsi&id=OFL)
- [ ] There is no "Reserved Font Name" mention in the OFL license
- [ ] Family name is unique according to namecheck.fontdata.com
- [ ] The font supports at least [GF Latin Core glyphset](https://github.com/googlefonts/glyphsets/tree/main/GF_glyphsets/Latin/)
- [ ] The repository respect the [upstream repo structure](https://googlefonts.github.io/gf-guide/upstream.html)
- [ ] The source files are available in the repository
- [ ] I read, agree and comply with the full [contributing requirements](https://googlefonts.github.io/gf-guide/onboarding.html)
- [ ] I am the author of the font or the author agreed to this submission
- [ ] I will maintain the repository

**Image:**

Attach here a pic or a screenshot of the font; one is enough, it can be few letters, to give a quick overview.
![lt_funk](https://user-images.githubusercontent.com/40067645/214972314-fce5f39b-80a3-4c78-9801-affc7c585bb1.png)

**Comment by applecuckoo** [comment]
Hello there! This font doesn't seem to be OFL, so it will be rejected.

**Comment by applecuckoo** [comment]
@RosaWagner Seems like this issue hasn't been closed. If anyone comes across this issue, the font came from DaFont at the link https://www.dafont.com/lt-funk.font. The link indicates that it has a "100% Free" license and not an OFL license.

**Comment by eliheuer** [comment]
Without a Git repository and the OFL license, this can't be added to Google Fonts. I'm closing this issue.
