### ISSUE TITLE
OFIRhebrew

### ISSUE THREAD

**Issue by ofiralon2006** [google/fonts#5866]
**Font Project Git Repo URL:**
[https://drive.google.com/file/d/1pM8o_Qe44aUW-_5Br8EmLRQJlnNtwlSN/view?usp=sharing](url)

**Super short description of the Font Family:**
Authentic handwriting in Hebrew. Its imperfection and individuality bring a touch of personality, making it stand out from other Hebrew fonts.

**Requirements:**

I understand that Google Fonts will publish only fonts that matches its requirements, and I can confirm the project meets them (by ticking the cases, or putting x between the square brackets in text mode):

- [X] The entire font project is licensed under the [OFL](https://scripts.sil.org/cms/scripts/page.php?site_id=nrsi&id=OFL)
- [X] There is no "Reserved Font Name" mention in the OFL license
- [X] Family name is unique according to namecheck.fontdata.com
- [X] The font supports at least [GF Latin Core glyphset](https://github.com/googlefonts/glyphsets/tree/main/GF_glyphsets/Latin/)
- [X] The repository respect the [upstream repo structure](https://googlefonts.github.io/gf-guide/upstream.html)
- [X] The source files are available in the repository
- [X] I read, agree and comply with the full [contributing requirements](https://googlefonts.github.io/gf-guide/onboarding.html)
- [X] I am the author of the font or the author agreed to this submission
- [X] I will maintain the repository

**Image:**

![image](https://user-images.githubusercontent.com/124634365/217109525-0308b907-c2fe-48af-b781-2850619d0f72.png)

**Comment by RosaWagner** [comment]
Hi @ofiralon2006, thanks for your submission. Indeed font generator such as Calligraphr goes against our requirements. So same comment as https://github.com/google/fonts/issues/5699#issuecomment-1350787186 applies. I would also encourage you to follow the suggestions written in that comment to transfer your design into a more professional font editor :) 

I wish you a beautiful journey in type making!
