### ISSUE TITLE
Anta

### ISSUE THREAD

**Issue by Typedesigners** [google/fonts#5869]
**Font Project Git Repo URL: * https://github.com/Typedesigners/Anta-Regular *

**Super short description of the Font Family:
Anta, a modern font family, is intelligently designed for screen publications. Anta Typeface has several interesting, constructed glyph shapes that give the typeface a modern look. The typeface is particularly suitable for graphic design, but also for branding projects. ![Anta](https://user-images.githubusercontent.com/124695645/217273021-aee3ab7e-3f7f-4866-9a62-94f4f81bea47.png)**

**Requirements:**

I understand that Google Fonts will publish only fonts that matches its requirements, and I can confirm the project meets them (by ticking the cases, or putting x between the square brackets in text mode):

- [x] The entire font project is licensed under the [OFL](https://scripts.sil.org/cms/scripts/page.php?site_id=nrsi&id=OFL)
- [x] There is no "Reserved Font Name" mention in the OFL license
- [x] Family name is unique according to namecheck.fontdata.com
- [x] The font supports at least [GF Latin Core glyphset](https://github.com/googlefonts/glyphsets/tree/main/GF_glyphsets/Latin/)
- [x] The repository respect the [upstream repo structure](https://googlefonts.github.io/gf-guide/upstream.html)
- [x] The source files are available in the repository
- [x] I read, agree and comply with the full [contributing requirements](https://googlefonts.github.io/gf-guide/onboarding.html)
- [x] I am the author of the font or the author agreed to this submission
- [x] I will maintain the repository
![Anta](https://user-images.githubusercontent.com/124695645/217273132-9baa1027-ffd3-4b8c-9571-2e646c410a0d.png)

**Image:**

Attach here a pic or a screenshot of the font; one is enough, it can be few letters, to give a quick overview.

**Comment by kenmcd** [comment]
Need a link to the public repository with the source files.

**Comment by Typedesigners** [comment]
> Need a link to the public repository with the source files.

Hello kenmcd, can you help me and explain where I can publish the Font Anta here? I would like to make it available only to Google Team for the time being.

**Comment by Typedesigners** [comment]
> Need a link to the public repository with the source files.

Hi kenmcd, I am new to github and need your support to understand how everything works here. I have now put in a font project git repo URL: * https://github.com/Typedesigners/anta * inserted. I have uploaded a ready made True Type Font Anta Regular designed by me. Can you tell me how to enable you and Google Fonts Team for this initially private project?

**Comment by kenmcd** [comment]
Thank you, and I really like the font ... BUT, I am not associated with Google Fonts (GF).
Someone from GF will eventually comment here in this thread.
But in the meantime I can give you a few suggestions.

Take a close look at the checklist above, and follow the links for more info.
- You do need to add the OFL license to your repo.
 - You should take a look at the recommended repo structure link and make some changes to the repo to follow those guidelines.
- You do need to add the source files (e.g. the `.glyphs` source).
- You should check that the font has all the required glyphs - follow the link and add the needed glyphset file to Glyphs App and then you can check (a cursory review looks pretty good).

The font will eventually need to be run through the GF Font Bakery quality check.
That will undoubtedly come up with a few needed changes.

I did notice a couple things with just a quick scan - the /tcaron, /Lcaron, etc. (for Czech) have some positioning issues on the caron. And there are some other issues. Need to see the source.

So you do have some stuff which you should probably do while waiting for a GF rep to respond.

I do recommend you make the repo Public as soon as you rearrange it - this will make it a lot easier for the many people who will get involved.

Like the font! 
One of the better ones I have seen submitted to GF.

**Comment by Typedesigners** [comment]
Thank you very much for your support. I am pleased that you like the Anta Regular. I have now uploaded the original anta.sfd file. The font was designed entirely in FontForge. I think FontForge is a great type design software.

**Comment by Typedesigners** [comment]
I have uploaded an Anta-Regular.ttf update. I have also uploaded the original anta.sfd.

**Comment by m4rc1e** [comment]
@Typedesigners thanks for the submission.

Your repo https://github.com/Typedesigners/Anta-Regular 404s for me. Please ensure it is a public repo. Also please ensure your project adheres to the following guides:

- https://googlefonts.github.io/gf-guide/#the-upstream-repo-administrate-your-project-files
- https://googlefonts.github.io/gf-guide/#pre-production-getting-your-fonts-ready-for-gf
- https://googlefonts.github.io/gf-guide/#production-compiling-your-fonts-for-gf

**Comment by Typedesigners** [comment]
@m4rc1e Hello Marc Foley, thank you for your message. I'm new to GitHub and don't quite understand how it works yet. How can I make it public?

**Comment by Typedesigners** [comment]
@m4rc1e Hello Marc Foley, thank you for your message. I'm new to GitHub and don't quite understand how it works yet. I have now made repo public.

**Comment by Typedesigners** [comment]
@m4rc1e Hello Marc, how does the communication with Google Fonts work, do I get an email from you? Or does all communication with Google Fonts go through GitHub?

**Comment by Typedesigners** [comment]
Hi there,
Fontforge already has very good validation features to check fonts for problems. Is there a way to run Fontbakery directly from within Fontforge? 

Even better would be a Fontbakery GUI dashboard outside of Fontforge as it works with premade fonts. That way it would be more flexible as a standalone application.

**Comment by m4rc1e** [comment]
> FontForge already has very good validation functions to check fonts. Is there a way to run Fontbakery directly from within FontForge?

I'm afraid not.

> Even better would be a Fontbakery GUI dashboard outside of Fontforge as it works with premade fonts. That way it would be more flexible as a standalone application.

We've pondered this idea in the past. However, packaging Python apps into GUIs is hard,

Btw, we liked your submission and will onboard it at some point. I will take a look at the files when I get the time (may be next quarter)

**Comment by Typedesigners** [comment]
> > FontForge already has very good validation functions to check fonts. Is there a way to run Fontbakery directly from within FontForge?
> 
> I'm afraid not.
> 
> > Even better would be a Fontbakery GUI dashboard outside of Fontforge as it works with premade fonts. That way it would be more flexible as a standalone application.
> 
> We've pondered this idea in the past. However, packaging Python apps into GUIs is hard,
> 
> Btw, we liked your submission and will onboard it at some point. I will take a look at the files when I get the time (may be next quarter)

Thank you very much for this information. I am pleased that GF likes my Anta Regular. From my point of view, Anta Regular is ready. The font has been carefully validated and checked in FontForge. I would be happy about publication in Google Fonts.

**Comment by Typedesigners** [comment]
@kenmcd Hello kenmcd, can I ask you if you have a LinkedIn profile or a website? I would like to know more about you. Thanks.

**Comment by Typedesigners** [comment]
@m4rc1e I have installed Python 3.11 on Windows 11. However, I have not been able to use Font Bakery. The information at https://font-bakery.readthedocs.io/en/latest/user/USAGE.html is incomprehensible to me. It documents several lines of code. How this code can be applied to a font stored on my PC is completely unclear to me. I need support with Fontbakery and GFtools.

**Comment by felipesanches** [comment]
I've unchecked "The repository respect the [upstream repo structure](https://googlefonts.github.io/gf-guide/upstream.html)" on the original message, because the repo does not include the `scripts` and the `.github/workflows` directories (as in the template available at https://github.com/googlefonts/googlefonts-project-template). So it means it does not perform automated quality checking with FontBakery, which is a prerequisite for onboarding new fonts into the Google Fonts Library.

**Comment by Typedesigners** [comment]
> I've unchecked "The repository respect the [upstream repo structure](https://googlefonts.github.io/gf-guide/upstream.html)" on the original message, because the repo does not include the `scripts` and the `.github/workflows` directories (as in the template available at https://github.com/googlefonts/googlefonts-project-template). So it means it does not perform automated quality checking with FontBakery, which is a prerequisite for onboarding new fonts into the Google Fonts Library.

@felipesanches Which files are missing? What specifically needs to be corrected?

**Comment by Typedesigners** [comment]
@felipesanches The Google Fonts Guide states that the design source files can be supplied by fontforge. GFtools must therefore work with fontforge.
https://googlefonts.github.io/gf-guide/production.html

**Comment by Typedesigners** [comment]
@felipesanches I have uploaded a new Anta-Regular.sfd in folder sources. Please try GFtools with this file.

**Comment by Typedesigners** [comment]
@felipesanches 
I have uploaded UFO files. You probably don't need .sfd files anymore and can use GFtool and Font Bakery.
https://github.com/Typedesigners/Anta-Regular/tree/main/sources/Anta-Regular.ufo

**Comment by Typedesigners** [comment]
@kenmcd Do you have professional experience with GFtools? Can you make the repository more complete by adding the scripts and the .github/workflows directories?

**Comment by Typedesigners** [comment]
@felipesanches I have completed the repository by adding the directories the scripts and the github/workflows.

**Comment by Typedesigners** [comment]
@felipesanches 

build.yaml machte folgender Hinweis: Do first-run script if necessary
Wie ist das zu verstehen?
https://github.com/Typedesigners/Anta-Regular/actions/runs/4225168743/jobs/7337084723

**Comment by Typedesigners** [comment]
Someone from GF should correct that then, please.
![Screenshot 2023-02-21 122025](https://user-images.githubusercontent.com/124695645/220331877-c45acd8a-3aff-42b1-b17a-8ddba661684a.jpg)

https://github.com/Typedesigners/Anta-Regular/actions/runs/4225168743

**Comment by Typedesigners** [comment]
@m4rc1e 
I would be interested to know why build.yaml has a shorter source code in MavenPro? MavenPro does not have a scripts folder either. So why was I asked to create a scripts folder? Is there no standard criteria for repositories?
By the way, MavenPro is a great font family that I like very much.
https://github.com/googlefonts/mavenproFont
https://github.com/googlefonts/mavenproFont/blob/main/.github/workflows/build.yaml

**Comment by Typedesigners** [comment]
@m4rc1e I have added all the necessary files to the repo. My work is done for now.

**Comment by Typedesigners** [comment]
@m4rc1e I would be happy if the Anta Font family would be released on Google Fonts soon. I would like to create more font families for Google Fonts. But first I have to wait for the release of Anta.

**Comment by Typedesigners** [comment]
@RosaWagner Can you please tell me which letters are missing or what I need to correct? I will correct immediately. Thank you.

**Comment by RosaWagner** [comment]
@Typedesigners, thanks again for your interest in releasing a font with Google Fonts. After your design got accepted, I looked into the files and noted several technical quality issues mostly related to:

- design of diacritics
- positioning of diacritics
- confusion between legacy (space) accents and combining (non space) accents
- building of accented glyphs (they are all decomposed)

I suggest the reading of theses articles to improve the technical aspect of your font project:
- http://designwithfontforge.com/en-US/Diacritics_and_Accents.html
- https://googlefonts.github.io/gf-guide/diacritics.html

Please note that since your font contains only basic latin script coverage, and since the design concept is very similar to already existing fonts from catalog (such as: https://fonts.google.com/specimen/Audiowide), or already accepted submissions (such as https://github.com/google/fonts/issues/5630), the inclusion of this project to the catalog is not a priority and will depend on the time the team can allocate to this project. Thanks for your patience and I wish you a beautiful journey in type making.

**Comment by Typedesigners** [comment]
@RosaWagner Thank you for this information. The design of diacritics and positioning of diacritics was created automatically with Fontforge. Please see the latest Anta-Regular.tft (https://github.com/Typedesigners/Anta-Regular/tree/main/fonts). There is a big difference in design between my design and the font families #5630 you mentioned. This difference is much bigger than between for example Open Sans and Source Sans Pro.

**Comment by RosaWagner** [comment]
I am sorry for the misunderstanding :) Yes, there are a lot of differences in the designs, undeniably. I am talking here of preferred concepts, and priorities I have no control over. I am trying to be as much transparent as possible so you can understand the agenda and don't loose energy in insisting on this thread. 

Thanks again for your patience, we will come back to you when someone gets assign to the project.

**Comment by Typedesigners** [comment]
@RosaWagner I don't quite understand, how do you mean when someone gets assigned to the project?

FontForge can automatically create accented characters in two main ways.
1. FontForge contains rudimentary information on where to place diacritic marks, so can automatically build most accented characters.

So the accents in Anta were automatically set in FontForge. As explained here: 
http://designwithfontforge.com/en-US/Diacritics_and_Accents.html

If you want specific changes, please tell me and I will try and correct them.

**Comment by Typedesigners** [comment]
@RosaWagner I have just updated: 
https://github.com/Typedesigners/Anta-Regular/tree/main/sources/Anta-Regular.ufo/glyphs

Also have a look at this file:
https://github.com/Typedesigners/Anta-Regular/blob/main/sources/Anta-Regular.ufo/glyphs/contents.plist

Thank you.

**Comment by Typedesigners** [comment]
@RosaWagner I have revised the following: 

- design of diacritics
- positioning of diacritics
- building of accented glyphs in the UFO

I have using Anchor Points to place diacritics. Creating anchor points for placing diacritic marks (mark to base positioning).
http://designwithfontforge.com/en-US/Diacritics_and_Accents.html

I have created new UFO3 files. I have also created new Anta-Regular.tft.
https://github.com/Typedesigners/Anta-Regular/tree/main/sources/Anta-Regular-Release.ufo

From my point of view, the Anta-Regular font family is ready. If you have any further advice, please let me know.

**Comment by Typedesigners** [comment]
@RosaWagner Google is one of the largest companies in the world. Isn't there a support team that handles projects and that designers can contact at any time? For me, it would be a planning advantage to know when my font family will be published on Google Fonts.

**Comment by davelab6** [comment]
@Typedesigners I'm sorry to disillusion you, but no, there is no large support team. Google is a large company, but the entire size of the Google Fonts team is very small, and we don't run ANYthing on calendar schedules, and "donation track" submissions like this are lower priority than the projects we commission.

**Comment by Typedesigners** [comment]
@davelab6 Thank you very much for this information.  I think Google Fonts is really a great library. It's a pity that the Google Fonts team is so small. You are also welcome to give me a project assignment. Working with you would certainly be very creative and interesting.

**Comment by davelab6** [comment]
Well after the layoffs I'm just grateful we have a team at all ;) 

Assignment here means that I have commissioned a handful of people to manage the process of accepting font projects into gf and getting them through to production and only those people can be assigned. 

I agree that collaborating closely with you would be a great experience for and you would learn a lot, but, currently I am not able to offer that kind of collaboration; there are various "further education" classes offered around the world, from online short courses to fill Masters degree programmes, and these are specifically intended to offer that kind of experience. 

> The design of diacritics and positioning of diacritics was created automatically with Fontforge.

This basically disqualifies the design, since the auto-logic in fontforge is poor quality and only useful as a quick start. 

As Rosalie said, we wish you a beautiful hero's journey into the world of type making, and I regret we currently don't offer more support for folks along that journey, but that's the current situation.

**Comment by Typedesigners** [comment]
@davelab6 In the meantime, I have created the diacritics and positioning of diacritics manual. In fact, the manual positioning is better and more targeted. 
I have created new UFO3 files. I have also created new Anta-Regular.ttf.
https://github.com/Typedesigners/Anta-Regular/tree/main/sources/Anta-Regular-Release.ufo

**Comment by davelab6** [comment]
Thanks for clarifying!! :) That's very good to hear. I'm not looking at the font, just the text in this thread XD

**Comment by Typedesigners** [comment]
@kenmcd Thanks for your comment. I have added the glyphs you mentioned. I have also added the following characters according to ISO-8859 - 14 and ISO-8859 - 16:

U+1e1e
U+1e1f
U+1e02
bdotaccent
Ddotaccent
Mdotaccent
mdotaccent
ddotaccent
Pdotaccent
pdotaccent
Sdotaccent
sdotaccent
tdotaccent
Tdotaccent

I have also created new Anta-Regular.ttf.

Which font families did you design, if you don't mind me asking? 
Do you have a LinkedIn profile or website?

**Comment by Typedesigners** [comment]
@RosaWagner  Hello Rosalie Wagner, I have exported my Anta-Regular font family as a .glyphs file. Please have a look at the Anta-Regular.glyphs file. https://github.com/Typedesigners/Anta-Regular/blob/main/sources/Anta-Regular.glyphs
I have designed the font in FontForge and not in Glyphs. Nevertheless, you can use Anta-Regular.glyphs for FontBakery.

**Comment by RosaWagner** [comment]
@Typedesigners thanks for your updates. It is noted. We will come back to you when somebody is assigned. Whatever you may add at this point won't change our agenda, no need to insist.

**Comment by Typedesigners** [comment]
@RosaWagner  All right, thanks.

**Comment by Typedesigners** [comment]
@RosaWagner We had contact here 3 weeks ago. Has anything happened since then? I see you added the Anta font to Google Fonts 5 days ago. Would be happy to move forward.

**Comment by Typedesigners** [comment]
@RosaWagner Please excuse me for asking. You have just done something here. Do I have to do something myself as the designer of the font, or do you do it internally for the GF team?

**Comment by RosaWagner** [comment]
@Typedesigners if we have something to ask, be sure we will. Please don't insist anymore, it won't change anything. onbaording can take several month.

**Comment by Typedesigners** [comment]
@RosaWagner Thank you for pointing this out.

**Comment by Typedesigners** [comment]
@RosaWagner By the way, I filled out my designer profile a few days ago. I hope the GF team received it.
https://googlefonts.github.io/gf-guide/profile.html

**Comment by Typedesigners** [comment]
@RosaWagner I would like to enquire, are assignees salaried employees at Google or simply volunteers?

**Comment by felipesanches** [comment]
"Please don't insist anymore, it won't change anything. Onboarding can take several months."

**Comment by Typedesigners** [comment]
@felipesanches I'm just asking. I would like to understand the onbording better.
