### ISSUE TITLE
Minify CSS

### ISSUE THREAD

**Issue by CallMeMantas** [google/fonts#587]
The CSS that’s being served, is not minified. There could be some (small) gains in page load. The gains would mostly be seen & benefit those with really bad connections or non-Western country citizens.

**Comment by davelab6** [comment]
@CallMeMantas thanks for asking. I'll see what the gf engineering thinks :)

**Comment by davelab6** [comment]
@CallMeMantas Long story short, https://en.wikipedia.org/wiki/HTTP_compression can obtain the gains in page load you expect, especially with Brotli packing; and a secondary benefit is that when a human does look at it, it is immediately useful and readable by them.

**Comment by kireerik** [comment]
I think these CSS files are not targeting humans. So it would be good to have minification and the folks can still add support for an URL like this: `//fonts.googleapis.com/css/human`
