### ISSUE TITLE
slow_motion_video icon is missing in Material Icons.

### ISSUE THREAD

**Issue by wkhr-m** [google/fonts#5870]
**Describe the bug**
slow_motion_video icon isn't perfect in Material Icons.
It is missing.
status quo:
<img width="129" alt="スクリーンショット 2023-02-08 20 13 20" src="https://user-images.githubusercontent.com/43362066/217517162-6cfd2d21-eaae-49be-9d0a-7c7de959a976.png">

**To Reproduce**
You make web application with Angular material and slow_motion_video icon.
https://stackblitz.com/edit/slow-motion-video-icon?file=src%2Findex.html,src%2Fmain.ts

**Expected behavior**
![slow_motion_video_FILL0_wght400_GRAD0_opsz48](https://user-images.githubusercontent.com/43362066/217517340-38b7af6d-1071-4d25-8944-75e0083f4ac2.png)
from: https://fonts.google.com/icons?selected=Material%20Symbols%20Outlined%3Aslow_motion_video%3AFILL%400%3Bwght%40400%3BGRAD%400%3Bopsz%4048

**Comment by RosaWagner** [comment]
Sorry for the late answer, but issues regarding Icons should be reported in this repository: https://github.com/google/material-design-icons
