### ISSUE TITLE
Hebrew google fonts 

### ISSUE THREAD

**Issue by gil14** [google/fonts#5877]
I  Can`t get any more the option to see a list of all the hebrew fonts in Google font site.
I can chose from only Arabic, Bengali and Chinese.

**Comment by applecuckoo** [comment]
Hmm... go to https://fonts.google.com/?subset=hebrew&noto.script=Hebr and it should look like below:
![Screenshot 2023-02-10 at 07-35-06 Google Fonts](https://user-images.githubusercontent.com/113647417/217906159-e355f77d-833e-4358-9e43-7e33ef5b56a7.png)

**Comment by gil14** [comment]
> Hmm... go to https://fonts.google.com/?subset=hebrew&noto.script=Hebr and it should look like below:
> 
> ![Screenshot 2023-02-10 at 07-36-34 Google Fonts](https://user-images.githubusercontent.com/113647417/217906316-f095bff2-6da7-46a5-8559-d478a105fe3e.png)

Thanks!!!!!!!1
