### ISSUE TITLE
Bebas Neue not rendering correctly on non-desktop browsers

### ISSUE THREAD

**Issue by qetsiankulu** [google/fonts#5879]
**Describe the bug**
I have linked the Google Fonts using the `<link>` tag in the `<head>` element of my html file. The font works perfectly fine when viewing the website on my desktop.

 After deploying my website, I noticed that the font did not appear correctly when viewed on my tablet and phone. 

I have tried downloading the font file and creating @font-face in my css and the same issue arises. Even when I use the @import method. 

![link  google fonts](https://user-images.githubusercontent.com/95947073/217926694-8243a5ed-fb00-4b0d-88cf-e6a901
![font-family declaration](https://user-images.githubusercontent.com/95947073/217926720-8ab1a49b-64ad-4e39-9a34-3c26f942e90c.png)
7871c8.png)

This how the font is rendered on the desktop. (Correct)
![desktop font rendered correctly](https://user-images.githubusercontent.com/95947073/217927070-a5080f94-7797-4c0b-9f1c-d8d40a95e3b9.png)

This how the font is rendered on non-desktop browsers (Incorrect). 
![mobile font not displaying correctly](https://user-images.githubusercontent.com/95947073/217927160-aa4cd42c-51b7-4f78-8c93-1074da8e0031.jpg)

**Comment by nyshadhr9** [comment]
Sorry, I couldn't reproduce this on my end. A minimal reproduction of the issue would be helpful along with the browser+OS info you are seeing this issue on.
