### ISSUE TITLE
Hanoded Hand - New font ingoo

### ISSUE THREAD

**Issue by Mon75FF** [google/fonts#5902]
**Font Project Git Repo URL:**

**Super short description of the Font Family:**
Hanoded Hand font family designed by David Kerkhoff has a total of 1 different styles

**Requirements:**

I understand that Google Fonts will publish only fonts that matches its requirements, and I can confirm the project meets them (by ticking the cases, or putting x between the square brackets in text mode):

- [ ] The entire font project is licensed under the [OFL](https://scripts.sil.org/cms/scripts/page.php?site_id=nrsi&id=OFL)
- [ ] There is no "Reserved Font Name" mention in the OFL license
- [ x] Family name is unique according to namecheck.fontdata.com
- [ ] The font supports at least [GF Latin Core glyphset](https://github.com/googlefonts/glyphsets/tree/main/GF_glyphsets/Latin/)
- [ ] The repository respect the [upstream repo structure](https://googlefonts.github.io/gf-guide/upstream.html)
- [x ] The source files are available in the repository
- [ x] I read, agree and comply with the full [contributing requirements](https://googlefonts.github.io/gf-guide/onboarding.html)
- [ ] I am the author of the font or the author agreed to this submission
- [ ] I will maintain the repository

**Image:**

Attach here a pic or a screenshot of the font; one is enough, it can be few letters, to give a quick overview.

![hanoded hand font](https://user-images.githubusercontent.com/125556349/219363151-31e378da-4111-470a-b8b6-8a0de6577322.jpg)

**Comment by applecuckoo** [comment]
Hello there! The metadata in the font file states the following:

>Free for personal use; donation required for commercial use (websites, projects, exhibitions, print, school, etc.). Donations can be made through PayPal, at [email]

That isn't an OFL license, so will not be accepted.

**Comment by m4rc1e** [comment]
Thanks for inspecting @applecuckoo. @Mon75FF are you the owner of the font?

**Comment by Mon75FF** [comment]
Hello,
I am not the owner of the font. But, I need use it in the google doc I do
for me.

Thanks.
Mónica

**Comment by m4rc1e** [comment]
Since it isn't an OFL license, we cannot accept the family.
