### ISSUE TITLE
Support Noto Sans CJK variants in the Android API

### ISSUE THREAD

**Issue by AbelToy** [google/fonts#5905]
This file has a list of all the fonts supported in the Android Downloadable Fonts API: https://fonts.gstatic.com/s/a/directory.xml

Unfortunately, only Noto Sans Regular / Bold is supported, and not any of the CJK variants (such as Noto Sans JP) nor any other weights.

Could support for all the CJK variants and weights supported by Noto Sans be included for the Android Downloadable Fonts API?

**Comment by davelab6** [comment]
I acknowledge they are missing, along with all variable fonts, and the team is working to address those systemic issues with the file size impact of cjk, but this is a long term effort. I'm closing this as we don't track that work publicly and can't offer any ETA.

**Comment by MichaelJokAr** [comment]
still no support
