### ISSUE TITLE
"Surprised" (u1f62f) downloads missing from Noto Emoji Animation site

### ISSUE THREAD

**Issue by KW802** [google/fonts#5909]
When visiting the Noto Emoji Animated site the "Surprised" emoji (u1f62f) is listed but none of the downloadable files (webp / gif / lottie) are available and return a 404 error. 

To see in action, view the Noto Emoji Animation site at https://googlefonts.github.io/noto-emoji-animation/, click on the "Surprised" emoji (😯), attempt to download of the file types listed.

**Comment by rsheeter** [comment]
Fixed by https://github.com/googlefonts/emoji-metadata/pull/52.
