### ISSUE TITLE
Comfortaa.ttf Premiere Pro CS6 artifacts

### ISSUE THREAD

**Issue by UltraCaustic** [google/fonts#5921]
When using Comfortaa font in Adobe Premiere Pro CS6, the uppercase A, M, V, W, Y and lowercase v and w symbol appear to be bugged, not rendered properly. When i use this font in newer version of Premiere Pro - CC 2022, it works flawlessly, without a single glitched symbol.

When creating a text in Premiere Pro CS6 and applying Comfortaa font to this text, this bug happens.

I expected to see an absolutely normal symbols without bugs.

Windows 10 21H2, Adobe Premiere Pro CS6, version 6.0.0, Comfortaa font installed from Google Fonts.
![font problem](https://user-images.githubusercontent.com/86152612/220710418-e17b975a-fc93-412e-9293-bcc1f6ffcef2.png)

**Comment by kenmcd** [comment]
It appears that PP CS6 has problems rendering looped corners.
Use the OTF fonts from the repo (which have no looped corners).
Note they are in two folders - `OTF` and `otf`.
https://github.com/googlefonts/comfortaa/tree/main/fonts
