### ISSUE TITLE
Update Alkalami

### ISSUE THREAD

**Issue by LornaSIL** [google/fonts#5922]
**Font Project Git Repo URL: https://github.com/silnrsi/font-alkalami/releases/tag/v3.000**

**Current version: 2.000**

**New available version: 3.000**

**Super short description of the upgrade:**
(fixed small advanced width issues, add new characters, add OpenType support for Hausa language)

**Bugs reported in this repo which this upgrade would fix:**
Search in the [issue tracker](https://github.com/google/fonts/issues) if there is some opened issues containing the font name.
None.

**Comment by RosaWagner** [comment]
Thanks @LornaSIL I added it in the queue, @emmamarichal will contact you if any question :)
