### ISSUE TITLE
A pasted glyph (☞) gets renderd correctly in the preview but not if I click on the font or use the font.

### ISSUE THREAD

**Issue by mogoh** [google/fonts#5935]
This issue is probably generally about sub-setting and not about the cormorant font.
However I have not tested it on other fonts.

**Describe the issue / To Reproduce**

To see if a font supports the glyph "☞" I pasted the glyph in the "Type something"-area. 
Some fonts, like Cormorant, render the glyph .(Screenshot 1)

See: https://fonts.google.com/?preview.text=%E2%98%9E&preview.text_type=custom&query=cormorant&category=Serif

If I click on "Cormorant Garamond" for example the glyph isn't rendered any more. (Screenshot 2 and 3)

**The glyph is in the woff (not woff2) file**

However, if I fake my user-agent to IE11, and go here:

https://fonts.googleapis.com/css2?family=Cormorant+Garamond&display=swap

I get this CSS:

```CSS
@font-face {
  font-family: 'Cormorant Garamond';
  font-style: normal;
  font-weight: 400;
  font-display: swap;
  src: url(https://fonts.gstatic.com/s/cormorantgaramond/v16/co3bmX5slCNuHLi8bLeY9MK7whWMhyjorQ.woff) format('woff');
}
```

So, if I use that CSS like this, it works:

```html
<!DOCTYPE html>
<html>
<head>
<link href="https://fonts.googleapis.com/css2?family=Cormorant+Garamond&display=swap" rel="stylesheet">
<style>
@font-face {
  font-family: 'Cormorant Garamond';
  font-style: normal;
  font-weight: 400;
  font-display: swap;
  src: url(https://fonts.gstatic.com/s/cormorantgaramond/v16/co3bmX5slCNuHLi8bLeY9MK7whWMhyjorQ.woff) format('woff');
}
p { font-family: "Cormorant Garamond", serif; }
</style>
</head>
<body>
<p>☞</p>
</body>
</html>
```

**The glyph is in the downloadable ttf file**

See Screenshot 4.

**Additional context**
Testet on Ubuntu 22.04 with Chromium 110 and Firefox 110

**Screenshots**

![Screenshot 2023-02-26 at 23-05-09 Google Fonts](https://user-images.githubusercontent.com/580975/221441391-2a3b86dc-9ab8-4047-8484-ff91c050c5f4.png)

![Screenshot 2023-02-26 at 23-05-18 Google Fonts](https://user-images.githubusercontent.com/580975/221441393-f135b7c3-17a9-4dd9-b149-775760f60af3.png)

![Screenshot 2023-02-26 at 23-05-26 Google Fonts](https://user-images.githubusercontent.com/580975/221441400-441bfab9-b1b8-4aba-b465-69cb1ab4f96a.png)

**Downloadable ttf file**

![Screenshot_20230226_233406](https://user-images.githubusercontent.com/580975/221441552-e645c138-0dc2-41f4-833f-60c20f5a1552.png)

**Comment by nyshadhr9** [comment]
Thanks for reporting, we are looking into this issue.

**Comment by davelab6** [comment]
@mogoh I'm sorry I only just saw this, I think I was out on leave at that time.

Hopefully https://davelab6.jsbin.com/guzevoq/edit?html,output is a sufficient demo of how the CSS API text parameter can be used to solve this in a simple way. 

Please do not ever use the CSS response of the API as your own CSS, it isn't guaranteed to work, or if it does work, not for the lifetime of the gf product, unlike the API.

**Comment by mogoh** [comment]
@davelab6 I am sorry, but I think this issue is **not** fixed.

Here is a hopefully better demonstration of this issue: https://google-fonts-bug-5935-mogoh-4a2bde17fe9a0b62d2b94262fc98866ff76.gitlab.io/
https://gitlab.com/mogoh/google-fonts-bug-5935/

> Please do not ever use the CSS response of the API as your own CSS, it isn't guaranteed to work, or if it does work, not for the lifetime of the gf product, unlike the API.

OK, but in the example I just posted I did exactly as the google fonts page suggested.

**Comment by mogoh** [comment]
@davelab6 can you please take another look at this issue?
