### ISSUE TITLE
Update Fjalla One (Eben Sorkin)

### ISSUE THREAD

**Issue by emmamarichal** [google/fonts#5940]
Font Project Git Repo URL:
https://github.com/SorkinType/Fjalla

Current version:
v.1.001
https://fonts.google.com/specimen/Fjalla+One?query=fja

New available version:
Version [upstream](https://github.com/SorkinType/Fjalla) [Adobe Latin 3](https://adobe-type-tools.github.io/adobe-latin-charsets/adobe-latin-3.html) support.

Super short description of the upgrade:
expand glyphset

@ebensorkin, can I update this? The sources on the repo are more completed than the version on the API.

**Comment by EbenSorkin** [comment]
I have updated the project here to support more languages and with the addition of kerning. 

https://github.com/SorkinType/FjallaOne

Please let me know if this source is ready to onboard.

**Comment by emmamarichal** [comment]
Hi @EbenSorkin, it looks great to me, I'll let you know if I see any problem. Thanks a lot!
