### ISSUE TITLE
Droid Sans Fallback - invalid rendering of Korean characters

### ISSUE THREAD

**Issue by pparik** [google/fonts#5946]
Font: Droid Sans Fallback

**Describe the bug**
Most Korean characters are not rendered correctly; they are instead decomposed to individual letters.

**To Reproduce**
Generally, the bug is manifested on any web page that uses Droid Sans Fallback. On my system (Fedora 35 + Chrome 110), that happens because Droid Sans Fallback is automatically selected as a fallback font for Arial / sans-serif that is used on a lot of web pages.

Please see the attached test files.

**Expected behavior**
Korean characters are displayed correctly as a compound.

**Screenshots**
Invalid rendering with Droid Sans Fallback `test-droid.html`:
![image](https://user-images.githubusercontent.com/26385735/222107780-6e8e1e3a-9d12-42bd-9e14-363720fad021.png)

Correct rendering with Noto Sans KR `test-noto.html`:
![image](https://user-images.githubusercontent.com/26385735/222107919-a5fbb7ca-9d85-479e-b77c-bbbbbbbb8967.png)

[test-droid.html.txt](https://github.com/google/fonts/files/10859676/test-droid.html.txt)
[test-noto.html.txt](https://github.com/google/fonts/files/10859677/test-noto.html.txt)

**Comment by invisibleroads** [comment]
As a workaround, you can disable google-droid-sans-fonts altogether.

Adding the following configuration to `~/.config/fontconfig/fonts.conf` fixed the issue in Fedora 42:

```
<?xml version="1.0"?>
<!DOCTYPE fontconfig SYSTEM "urn:fontconfig:fonts.dtd">
<fontconfig>
  <rejectfont>
    <glob>/usr/share/fonts/google-droid-sans-fonts/*</glob>
  </rejectfont>
</fontconfig>
```

Thanks to https://802.11ac.net/2022/06/10/fedora-korean-font/ for the tip.
