### ISSUE TITLE
Add minisite_url for Nabla and Climate Crisis

### ISSUE THREAD

**Issue by applecuckoo** [google/fonts#5957]
Hi there, I suggested the addition of the https://nabla.typearture.com/ site to the API metadata back in December of last year, at https://github.com/google/fonts/pull/5570#issuecomment-1320384563. I have also since found that the new font Climate Crisis has the minisite https://kampanjat.hs.fi/climatefont/index.html (it's even in the description) as well, so that should also be added.

**Comment by chrissimpkins** [comment]
https://github.com/google/fonts/pull/5964 ty!
