### ISSUE TITLE
Fix Tiro Tamil description

### ISSUE THREAD

**Issue by tiroj** [google/fonts#5965]
Tiro Tamil: https://fonts.google.com/specimen/Tiro+Tamil/about
Note: ‘About’ bug, not font bug.

**Describe the bug**
There is a small typo in the description text for Tiro Tamil: it says Kannada where it should say Tamil.

This has been fixed in the upstream source repo:
https://github.com/TiroTypeworks/Indigo/commit/aba722a749cd4c389cb548835b6831fe9ee1efc2

**Screenshots**
<img width="856" alt="Screenshot 2023-03-03 at 12 58 33 PM" src="https://user-images.githubusercontent.com/5614500/222828592-317b6aec-f466-449e-9b26-ebe6eded3ced.png">

**Comment by chrissimpkins** [comment]
https://github.com/google/fonts/pull/5968

Thanks John!
