### ISSUE TITLE
[CodeNext]

### ISSUE THREAD

**Issue by drhamidfar** [google/fonts#5970]
**Font Project Git Repo URL:**

**Super short description of the Font Family:**

**Requirements:**

I understand that Google Fonts will publish only fonts that matches its requirements, and I can confirm the project meets them (by ticking the cases, or putting x between the square brackets in text mode):

- [ ] The entire font project is licensed under the [OFL](https://scripts.sil.org/cms/scripts/page.php?site_id=nrsi&id=OFL)
- [ ] There is no "Reserved Font Name" mention in the OFL license
- [ ] Family name is unique according to namecheck.fontdata.com
- [ ] The font supports at least [GF Latin Core glyphset](https://github.com/googlefonts/glyphsets/tree/main/GF_glyphsets/Latin/)
- [ ] The repository respect the [upstream repo structure](https://googlefonts.github.io/gf-guide/upstream.html)
- [ ] The source files are available in the repository
- [ ] I read, agree and comply with the full [contributing requirements](https://googlefonts.github.io/gf-guide/onboarding.html)
- [ ] I am the author of the font or the author agreed to this submission
- [ ] I will maintain the repository

**Image:**

Attach here a pic or a screenshot of the font; one is enough, it can be few letters, to give a quick overview.

**Comment by drhamidfar** [comment]
Could anybody help me adding this free license font to google font, please?

**Comment by RosaWagner** [comment]
Hi @drhamidfar thanks for your submission. I read the license attached in the zip file, and I would like to stress that this is not a free font. This is a commercial font from FontFabric which you have access to thanks to a trial license. The license is very well written and you recommend to read it fully before using the font.

Google Fonts only distribute fonts under the OFL (open source license). Therefore this font won't be added in the catalog.

Thanks for your understanding :)
