### ISSUE TITLE
Which variable fonts include an Optical Size (opsz) axis?

### ISSUE THREAD

**Issue by callumlocke** [google/fonts#5973]
The Knowledge Glossary page [Optical Size axis (opsz)](https://fonts.google.com/knowledge/glossary/optical_size_axis) says this:

> “Optical Size” (controlled with `font-optical-sizing` or `font-variation-setting: ‘opsz’ VALUE` in CSS) is an [axis](https://github.com/google/fonts/blob/main/glossary/axis_in_variable_fonts) found in some [variable fonts](https://github.com/google/fonts/blob/main/glossary/variable_fonts). It controls the [font](https://github.com/google/fonts/blob/main/glossary/font) file’s [optical size](https://github.com/google/fonts/blob/main/glossary/optical_sizes) optimizations.

How do I tell if a font supports this `opsz` axis? I can't see any mention of it when browsing fonts on fonts.google.com, and I don't think there's a way to filter the search results by axis.

**Comment by vv-monsalve** [comment]
Hi @callumlocke,

In [fonts.google.com/variablefonts](https://fonts.google.com/variablefonts) you can filter them by picking the `opsz` axis from the drop-down menu.

**Comment by MarkFonts** [comment]
It would be great if these would have #opsz or etc appendages on the url bc I want to send people just the opsz fonts
