### ISSUE TITLE
Frank Ruhl Libre - No italics.

### ISSUE THREAD

**Issue by SBozin** [google/fonts#5974]
#This issue also works for requesting features. 

**Describe the issue**
Frank Ruhl Libre is a font that doesn't have italics available to download. In Google slides, you can apply the _italics_ style to the document, but if I want to use the font for other projects (in Figma), I'm not able to download with italics.

**Expected behavior**
Can we get .ttfs for an italics version of Frank Ruhl Libre so that it looks like what's available in Google Slides? Screenshot attached below.

**Additional context**
https://fonts.google.com/specimen/Frank+Ruhl+Libre?preview.text=Toronto%20shows%20its%20ugly,%20brutish%20side%20in%20clearing%20of%20Trinity%20Bellwoods%20encampment&preview.text_type=custom&query=Frank&category=Serif&vfonly=true

**Screenshots**
<img width="1176" alt="Frank Ruhl Libre" src="https://user-images.githubusercontent.com/127143855/223225535-476d0b9a-21b3-4267-9ecf-e40f8caa5ade.png">

**Comment by m4rc1e** [comment]
I reckon Google Slides may be italicising the Roman weight. I'll ask.

**Comment by RosaWagner** [comment]
Hi @SBozin, Marc is right. Frank Ruhl Libre is not a font that contains italics—the designer didn't design them. Therefore some apps like Google Slide but also MS Words or Powerpoint may slant the existing upright outlines to give the illusion of an italic font. This seems not to be an available feature in Figma.

I am closing this issue cause there is nothing we can do about it. Some fonts have italic, some don't :)

**Comment by SBozin** [comment]
Thanks @m4rc1e @RosaWagner! I figured as much, just wanted to verify.
