### ISSUE TITLE
There has to be a way to get a wallet back after 3 pin attempts

### ISSUE THREAD

**Issue by binarycurious** [google/fonts#5993]
#This issue also works for requesting features. 

After three incorrect pin attempts the wallet wipes the pin_data from the wallet file. This is so brutal and unnecessary. If there has to be a burn function it should not happen after just 3 pin attempts and should be up to the user to configure. Anyone really wanting to continue entering pins just has to copy the wallet file as far as I can tell. This is not security. It is just plain stupid, and it might have cost me over 50k, as it just happened to me and now I find the key phrase I have appears to be incomplete = \

**To Reproduce**
Enter incorrect pin 3 times and watch your encrypted data get wiped, but only if you don't know about the workings of the system. Unfortunately I was overly confident in my key storage when I let mine get wiped.

**Expected behavior**
Time lock on pin entry. Encryption lock on file after more attempts that can only be unlocked after a period of days, weeks months, years.

**Additional context**
This "feature" has possibly lost me ~ 50,000 USD. I am very not happy and if I can't get it back will be pretty devastated. For some people this could lead to suicide.

**Comment by applecuckoo** [comment]
Hi there! This is Google Fonts, not the right place to rant about digital wallets.

**Comment by RosaWagner** [comment]
Hi @binarycurious, I am sorry for what happened to you. Unfortunately this not the correct repository to file a complain about this topic. This public repository is here to host the font collection from https://fonts.google.com. I hope you gonna find the right people to communicate your issue.
