### ISSUE TITLE
Update Figtree

### ISSUE THREAD

**Issue by emmamarichal** [google/fonts#5996]
In progress - Issue created to follow the project

**Font Project Git Repo URL:**
https://github.com/erikdkennedy/figtree

**Current version:**
2.000 https://fonts.google.com/specimen/Figtree?query=figtr

**New available version:**
2.001

**Super short description of the upgrade:**
bug fix https://github.com/erikdkennedy/figtree/pull/24

**Bugs reported in this repo which this upgrade would fix:**
https://github.com/erikdkennedy/figtree/issues/23

**Comment by chrissimpkins** [comment]
Moving to the Q2 milestone

**Comment by emmamarichal** [comment]
Closed because we have the same here: https://github.com/google/fonts/issues/6162
