### ISSUE TITLE
Add Clear Fantastic Serif

### ISSUE THREAD

**Issue by jjAugust** [google/fonts#6000]
**Font Project Git Repo URL:**
https://github.com/jjAugust/Clear-Fantastic-Serif

**Super short description of the Font Family:**
Clear Fantastic Serif is a condensed, display serif font that has been designed for open-source usage, making it ideal for web-based and application design.

**Requirements:**

I understand that Google Fonts will publish only fonts that matches its requirements, and I can confirm the project meets them (by ticking the cases, or putting x between the square brackets in text mode):

- [x] The entire font project is licensed under the [OFL](https://scripts.sil.org/cms/scripts/page.php?site_id=nrsi&id=OFL)
- [x] There is no "Reserved Font Name" mention in the OFL license
- [x] Family name is unique according to namecheck.fontdata.com
- [x] The font supports at least [GF Latin Core glyphset](https://github.com/googlefonts/glyphsets/tree/main/GF_glyphsets/Latin/)
- [x] The repository respect the [upstream repo structure](https://googlefonts.github.io/gf-guide/upstream.html)
- [x] The source files are available in the repository
- [x] I read, agree and comply with the full [contributing requirements](https://googlefonts.github.io/gf-guide/onboarding.html)
- [x] I am the author of the font or the author agreed to this submission
- [x] I will maintain the repository

**Image:**
<img width="805" alt="preview3" src="https://user-images.githubusercontent.com/9345477/224162046-3f107537-9dce-4170-b39d-a3cf5977c417.png">

**Comment by RosaWagner** [comment]
Hi @jjAugust, look I don't know what is the intention here after opening that last issue https://github.com/google/fonts/issues/5994. Please bear in mind that this is the actual workspace of a dozen of people and you may get blocked if we feel that you are trolling us.

I am sorry if you meant well.

**Comment by applecuckoo** [comment]
@RosaWagner I think @jjAugust just skewed the outlines to make it more unique?
