### ISSUE TITLE
When will Monserrat Light will be available on CDN?

### ISSUE THREAD

**Issue by jonathanrp** [google/fonts#601]
Hi, I noticed that Monserrat Light was added to the repo but it's not available to use thru the CDN, do you have an estimate on when this will be possible?

**Comment by davelab6** [comment]
Soon! There is a bug with it, I am waiting for @juandelperal to tag a release (https://github.com/JulietaUla/Montserrat/issues/36) and then I'll get the new 18 style family pushed :)

**Comment by davelab6** [comment]
(Closing as a duplicate of #2)
