### ISSUE TITLE
Ensure new Noto scripts are available (summary)

### ISSUE THREAD

**Issue by simoncozens** [google/fonts#6011]
The following Noto families are *new* and have PRs:

~- [ ] #5390~
- [x] #5392
- [x] #5700
- [x] #5740
- [x] #5397
- [x] #5395
- [x] #5393
- [x] #5394
- [x] #5767
- [x] #6025 

The following Noto families are new, but have not been PRed yet; I need to make a release of them:

- [ ] Syriac Estrangela
- [ ] Syriac Western

**Comment by simoncozens** [comment]
* Dives Akuru, Old Uyghur, Vithkuqi, Khitan: Needs us to find some sample text
* Chorasmian: Should be OK?
* Makasar: Needs lang PR merge. (https://github.com/googlefonts/lang/pull/74)
* Ottoman Siyaq: Needs glyphsets PR merge. (https://github.com/googlefonts/glyphsets/pull/108)

**Comment by chrissimpkins** [comment]
Any updates on these projects Simon?  Will we be able to onboard any of the families in Q2?

**Comment by simoncozens** [comment]
I've taken out Dives Akuru, as there are significant questions about whether this design is acceptable to the user community. We still need to find sample texts for Vithkuqi and Old Uyghur. Everything else is done.

**Comment by chrissimpkins** [comment]
@simoncozens is your checklist accurate here?  If so, do you expect to wrap up the last three families during Q4?

**Comment by simoncozens** [comment]
Old Uyghur is now done. Vithquki is, I think, blocked on sample text.

**Comment by simoncozens** [comment]
I'm wrong about this, we have text for Vithquki (sq_Vith). I just need to add languages/primary_script to the metadata nad we should be good to go.
