### ISSUE TITLE
Add Noto Sans Nag Mundari

### ISSUE THREAD

**Issue by simoncozens** [google/fonts#6013]
Font Project Git Repo URL:

Still in development. [notofonts/nag-mundari](https://github.com/notofonts/nag-mundari)

Super short description of the Font Family:

Noto font covering Unicode Nag Mundari (Mundari Bani) block.

Requirements:

I understand that Google Fonts will publish only fonts that matches its requirements, and I can confirm the project meets them (by ticking the cases, or putting x between the square brackets in text mode):

- [x]  The entire font project is licensed under the [OFL](https://scripts.sil.org/cms/scripts/page.php?site_id=nrsi&id=OFL)
- [x]  There is no "Reserved Font Name" mention in the OFL license
- [x]  Family name is unique according to namecheck.fontdata.com
- [x]  The font supports at least [GF Latin Core glyphset](https://github.com/googlefonts/glyphsets/tree/main/GF_glyphsets/Latin/?rgh-link-date=2023-03-13T16%3A47%3A53Z)
- [x]  The repository respect the [upstream repo structure](https://googlefonts.github.io/gf-guide/upstream.html)
- [x]  The source files are available in the repository
- [x]  I read, agree and comply with the full [contributing requirements](https://googlefonts.github.io/gf-guide/onboarding.html)
- [x]  I am the author of the font or the author agreed to this submission
- [x]  I will maintain the repository

**Comment by simoncozens** [comment]
PRed as #6039.

**Comment by chrissimpkins** [comment]
This is a new Unicode script.  Requires eng team to update glyph sets from definitions that Simon provided in lang and glyphsets repository

**Comment by chrissimpkins** [comment]
@simoncozens Will you please link the PRs where the lang and glyphsets changes landed to this issue tracker?

**Comment by simoncozens** [comment]
Lang upstream PR: https://github.com/googlefonts/lang/pull/65
Lang pull into google/fonts: https://github.com/google/fonts/pull/6059
Glyphsets PR: https://github.com/googlefonts/glyphsets/pull/105

**Comment by chrissimpkins** [comment]
I discussed this issue with Simon today.  As I understand it, these language and glyph set updates have now landed in production and this project is no longer blocked.
