### ISSUE TITLE
Upgrade three Noto Arabic families

### ISSUE THREAD

**Issue by simoncozens** [google/fonts#6014]
**Font Project Git Repo URL:**

https://github.com/notofonts/arabic

These families are being re-engineered to provide:

* bug fixes!
* consistent engineering practices!!
* glyphset expansion!!!
* smaller font sizes!!!!

- [x] Noto Naskh Arabic https://github.com/google/fonts/pull/4885
- [x] Noto Kufi Arabic *(in progress)*
- [x] Noto Sans Arabic

**Comment by simoncozens** [comment]
Noto Sans Arabic went out in #6860. 
Noto Kufi went out in #6860. 
Noto Naskh is merged but not live, tracking in #6857.

**Comment by chrissimpkins** [comment]
This is nearly complete.  Noto Naskh Arabic is in sandbox and should land in production on the next prod data push. Moving this tracker back to Q2 to wrap up the rest of the Noto Arabic work here.
