### ISSUE TITLE
Update Noto Sans (for Unicode 14.0 support)

### ISSUE THREAD

**Issue by simoncozens** [google/fonts#6015]
Open PR here: https://github.com/google/fonts/pull/5789

The new version has a number of bug fixes, plus a number of new glyphs added in Unicode 14.0. I did a release and PR, but the GF version of Noto Sans is Very Special (embedded Devanagari) for historical reasons, and I messed up the Devanagari and need to do it again.

**Comment by chrissimpkins** [comment]
Addressing an OTS issue documented @ https://github.com/google/fonts/pull/5789#issuecomment-1562852328
