### ISSUE TITLE
Upgrade Tier 1 Noto fonts (summary)

### ISSUE THREAD

**Issue by simoncozens** [google/fonts#6016]
The focus of Noto development for Q1 is triaging and fixing issues in the tier 1 fonts, particularly the Indic families. These families will be released by the end of Q1, ready for onboarding during Q2.

- [ ] Noto Sans/Serif Bengali
	- [ ] Issue triaging/fixing
	- [ ] QA
	- [ ] Release/PR
- [ ] Noto Sans/Serif Devanagari
	- [x] Issue triaging/fixing
	- [x] QA
	- [x] Release/PR
- [x] Noto Sans/Serif Gujarati
	- [x] Issue triaging/fixing
	- [x] QA
	- [x] Release/PR
- [x] Noto Sans/Serif Gurmukhi
	- [x] Issue triaging/fixing
	- [x] QA
	- [x] Release/PR
- [ ] Noto Sans/Serif/Rashi Hebrew
	- [ ] Issue triaging/fixing
	- [ ] QA
	- [ ] Release/PR
- [x] Noto Sans/Serif Kannada
	- [x] Issue triaging/fixing
	- [x] QA
	- [x] Release/PR
- [x] Noto Sans/Serif Malayalam
	- [x] Issue triaging/fixing
	- [x] QA
	- [x] Release/PR
- [ ] Noto Sans/Serif Oriya
	- [x] Issue triaging/fixing
	- [ ] QA
	- [ ] Release/PR
- [x] Noto Sans/Serif Sinhala
	- [x] Issue triaging/fixing
	- [x] QA
	- [x] Release/PR
- [x] Noto Sans/Serif Tamil
	- [x] Issue triaging/fixing
	- [x] QA
	- [x] Release/PR
- [x] Noto Sans/Serif Telugu
	- [x] Issue triaging/fixing
	- [x] QA
	- [x] Release/PR

**Comment by chrissimpkins** [comment]
Are all of these projects still on track to land for onboarding in Q2?

**Comment by simoncozens** [comment]
Not sure I'll get to Hebrew. The rest will be released next week.

**Comment by simoncozens** [comment]
Tier 1 dev is done for this year, apart from Arabic which is tracked separately, and LGC which will have further updates in the year.

**Comment by chrissimpkins** [comment]
> Tier 1 dev is done for this year, apart from Arabic which is tracked separately, and LGC which will have further updates in the year.

Is the checklist in https://github.com/google/fonts/issues/6016#issue-1621893793 accurate?  Do we want to spin up a new issue for anything that was not done in that OP?

**Comment by RosaWagner** [comment]
@simoncozens Noto Sans Oryia is still blocked in dev because of the wdth axis not working at wght=400
