### ISSUE TITLE
Add [Voodoo-typeset]

### ISSUE THREAD

**Issue by Nnennav** [google/fonts#6019]
**Font Project Git Repo URL:**

**Super short description of the Font Family:**

**Requirements:**

I understand that Google Fonts will publish only fonts that matches its requirements, and I can confirm the project meets them (by ticking the cases, or putting x between the square brackets in text mode):

- [ ] The entire font project is licensed under the [OFL](https://scripts.sil.org/cms/scripts/page.php?site_id=nrsi&id=OFL)
- [ ] There is no "Reserved Font Name" mention in the OFL license
- [ ] Family name is unique according to namecheck.fontdata.com
- [ ] The font supports at least [GF Latin Core glyphset](https://github.com/googlefonts/glyphsets/tree/main/GF_glyphsets/Latin/)
- [ ] The repository respect the [upstream repo structure](https://googlefonts.github.io/gf-guide/upstream.html)
- [ ] The source files are available in the repository
- [ ] I read, agree and comply with the full [contributing requirements](https://googlefonts.github.io/gf-guide/onboarding.html)
- [ ] I am the author of the font or the author agreed to this submission
- [ ] I will maintain the repository

**Image:**

Attach here a pic or a screenshot of the font; one is enough, it can be few letters, to give a quick overview.
![175355a0ec495f831b2186c9a77ce3ab](https://user-images.githubusercontent.com/127825240/224916317-66af1394-c952-43ee-903b-2811c2468b36.jpg)

**Comment by RosaWagner** [comment]
Hi @Nnennav, thanks for your submission. There seems to be a misunderstanding cause this doesn't look like a font software product that you can install or use on a computer. The image seems to be a hand drawing of a display latin alphabet. Therefore we can distribute it.
