### ISSUE TITLE
Update Noto Serif CJK fonts to variable (summary)

### ISSUE THREAD

**Issue by simoncozens** [google/fonts#6024]
This is a tracking issue for landing the following PRs:

* #5535 (This is merged but needs a follow-up to fix a small vertical metrics change)
* #6020
* #6021 
* #6022 
* #6023

**Comment by simoncozens** [comment]
Paused awaiting a new release from Adobe to fix the Japanese curve direction issues.

**Comment by chrissimpkins** [comment]
Do we want to do this when the GB18030-2022 changes land?

**Comment by chrissimpkins** [comment]
Files are available from Adobe.  Ready for QA testing and onboarding

**Comment by simoncozens** [comment]
New PRs are:

* #6692 
* #6693 
* #6691 
* #6694 
* #6695

**Comment by simoncozens** [comment]
Confirm GB18030-2022 then move to live.

**Comment by chrissimpkins** [comment]
CJK subsetting policy updates are in place so that we preserve the GB18030-2022 updates.  I am confirming if the eng team has done an internal push to re-subset or if we need to list the families on the to_sandbox list

**Comment by chrissimpkins** [comment]
@emmamarichal We need to re-list these Noto Serif CJK families on the to_sandbox list so that the subsetter is run on them again following the CJK slicing policy update.  Ty!

**Comment by chrissimpkins** [comment]
What is the status here?
