### ISSUE TITLE
Pushter-Regular.ttf is really Lobster-Regular.ttf

### ISSUE THREAD

**Issue by Enpheebled** [google/fonts#6034]
The font named 'Pushter-Regular.ttf' is actually a misnamed copy of 'Lobster-Regular.ttf'.

I discovered this by downloading the zip containing all fonts, extracting all the fonts, and then running "fdupes --recurse --order=NAME --reverse . | grep '.ttf'"

Result:
./Google Fonts/pushster/Pushster-Regular.ttf
./Google Fonts/lobster/Lobster-Regular.ttf

**Expected behavior**
Either there should be a different font file for 'Pushter-Regular.ttf' or Pushter-Regular should be removed.

**Screenshots**
![Pushster-Regular](https://user-images.githubusercontent.com/13029060/225459204-6fce4ae3-056f-4973-b5b8-a786e045f62a.jpg)

**Comment by m4rc1e** [comment]
Pushter is our test family. We use this family to test our automated font pipeline. It isn't on the Google Fonts website. I'll drop a note in its description to signify this.

**Comment by IvanUkhov** [comment]
But does this fixture font have to be in the same folder as the real ones? Would it be possible to move it to a dedicated folder or at least update the naming table to disambiguate? It causes duplication issues down the line. Thank you.
