### ISSUE TITLE
Nunito Sans Asterisks

### ISSUE THREAD

**Issue by henrikschonstrom** [google/fonts#604]
The asterisks on the Nunito Sans font has a couple of issues.
I didn't know where to report this, so I thought giving it a try here.

Regular, SemiBold and Bold are really squashed and marked with red.
ExtraLight and Black are just a bit off and marked with blue.

![image](https://cloud.githubusercontent.com/assets/25330836/22274487/16db1e46-e2a7-11e6-8144-6acc7598acf2.png)

**Comment by fitojb** [comment]
The issue has been fixed already: please see report #585. This is a duplicate.
