### ISSUE TITLE
Why is there not an option to select English fonts in the language drop down

### ISSUE THREAD

**Issue by Kiritchell** [google/fonts#6049]
#This issue also works for requesting features. 

**Describe the issue**
A clear and concise description of what the issue is.

**To Reproduce**
Steps to reproduce the behavior.

**Expected behavior**

**Additional context**
Add any other context about the problem here (OS version, browser, printer…)

**Screenshots**

**Comment by applecuckoo** [comment]
Latin basically covers English, as Latin is the script that English uses (as in we have a Latin alphabet)
https://fonts.google.com/?subset=latin&noto.script=Latn

**Comment by tiroj** [comment]
The ‘Language’ dropdown is a mess. Most of the entries are not languages, but scripts, but to confuse things a few entries are languages.
