### ISSUE TITLE
Inter font is different than rsms.me version

### ISSUE THREAD

**Issue by key88sf** [google/fonts#6052]
Specify the font name in title with a short description of the bug. 
Please report any issue related to Noto fonts in this repository: https://github.com/googlefonts/noto-fonts/issues.

**Describe the bug**
Comparing the regular Inter font from Google Fonts to the creator's version https://rsms.me/inter/  shows clear differences in font weight, especially for the "light" 300 and "regular" 400 weights.

**To Reproduce**
* Create an HTML page using Google Fonts version of Inter with light, regular
* Create same HTML page using  `<%= stylesheet_link_tag "https://rsms.me/inter/inter.css" %>` instead of Google Fonts.

**Expected behavior**
Fonts should look exactly the same.

**Screenshots**
Google Fonts: (appears darker, bolder)
<img width="708" alt="Screenshot 2023-03-20 at 9 14 05 PM" src="https://user-images.githubusercontent.com/211776/226497686-f3feabdf-dcf6-4dc3-96df-23f25c964744.png">

RSMS.ME fonts:  (appears lighter)
<img width="692" alt="Screenshot 2023-03-20 at 9 14 55 PM" src="https://user-images.githubusercontent.com/211776/226497746-1933df38-8277-4abf-b91e-61f23479e75f.png">

**Additional context**
Chrome `Version 111.0.5563.64 (Official Build) (arm64)`

**Comment by applecuckoo** [comment]
@key88sf If you want to track the progress it's in #3429.
