### ISSUE TITLE
Add Onest

### ISSUE THREAD

**Issue by vcebotari** [google/fonts#6057]
**Font Project Git Repo URL:**
https://github.com/simpals/onest

**Super short description of the Font Family:**
Onest is designed as a hybrid of geometric and humanistic grotesques.

**Requirements:**

I understand that Google Fonts will publish only fonts that matches its requirements, and I can confirm the project meets them (by ticking the cases, or putting x between the square brackets in text mode):

- [x] The entire font project is licensed under the [OFL](https://scripts.sil.org/cms/scripts/page.php?site_id=nrsi&id=OFL)
- [x] There is no "Reserved Font Name" mention in the OFL license
- [x] Family name is unique according to namecheck.fontdata.com
- [x] The font supports at least [GF Latin Core glyphset](https://github.com/googlefonts/glyphsets/tree/main/GF_glyphsets/Latin/)
- [x] The repository respect the [upstream repo structure](https://googlefonts.github.io/gf-guide/upstream.html)
- [x] The source files are available in the repository
- [x] I read, agree and comply with the full [contributing requirements](https://googlefonts.github.io/gf-guide/onboarding.html)
- [x] I am the author of the font or the author agreed to this submission
- [x] I will maintain the repository

**Image:**
![Onest 7](https://user-images.githubusercontent.com/8831983/226861930-6d3ebe04-0377-4745-94ed-aedc46090e6b.jpg)

Attach here a pic or a screenshot of the font; one is enough, it can be few letters, to give a quick overview.

**Comment by vcebotari** [comment]
need to fix some build errors

**Comment by chrissimpkins** [comment]
@davelab6 cleared to proceed with onboarding today
