### ISSUE TITLE
Didact Gothic missing "-" character

### ISSUE THREAD

**Issue by kriswillis** [google/fonts#606]
![screenshot_2017-01-25_11-51-35](https://cloud.githubusercontent.com/assets/2786947/22289715/0194be0e-e2f5-11e6-92ea-ce56335f0cfb.png)

**Comment by m4rc1e** [comment]
Thank you.

prs sent to source repo https://github.com/ossobuffo/didact-gothic/pull/9 and here #607.

cc @alexeiva
