### ISSUE TITLE
Teko font has broken colon in Medium and Semibold Weights

### ISSUE THREAD

**Issue by melissabeth** [google/fonts#6065]
Specify the font name in title with a short description of the bug. 
Please report any issue related to Noto fonts in this repository: https://github.com/googlefonts/noto-fonts/issues.

**Describe the bug**
In the Medium and Semibold weights of Teko, the colon appears as a single, centered dot instead of 2 dots. 

**To Reproduce**
Attempt to type a colon in these weights in Google docs, slides, etc. 

**Expected behavior**
A colon character to appear

**Screenshots**
<img width="447" alt="Screenshot 2023-03-22 at 9 16 38 AM" src="https://user-images.githubusercontent.com/128623164/226969557-8e3f09ef-b76a-4ad9-b0d2-987dbf268a5f.png">

**Additional context**
Known issue originally reported here under incorrect headline (references semicolon not colon): https://github.com/google/fonts/issues/610

**Comment by RosaWagner** [comment]
Closing this issue since the other one is already tracked
