### ISSUE TITLE
Bebas Neue incorrect fallback. Cursive instead of sans-serif

### ISSUE THREAD

**Issue by mrleblanc101** [google/fonts#6075]
Specify the font name in title with a short description of the bug. 
Please report any issue related to Noto fonts in this repository: https://github.com/googlefonts/noto-fonts/issues.

**Describe the bug**
Currently, Google Fonts suggest this fallback for Bebas Neue `font-family: 'Bebas Neue', cursive;`

**Expected behavior**
Bebas Neue is a sans-serif font so the fallback should be `font-family: 'Bebas Neue', sans-serif;`

**Screenshots**
![Capture d’écran, le 2023-03-23 à 11 58 47](https://user-images.githubusercontent.com/17392251/227262750-70c2a27f-da6e-445a-9e81-1e776c3f29ff.png)

**Comment by RosaWagner** [comment]
Ah, it is a sans serif display font. I added sans serif as primary category.

**Comment by mrleblanc101** [comment]
Thanks, it caused confusing because our dev copy-pasted the snippet with the incorrect fallback and the client noticed the FOUC 😅
