### ISSUE TITLE
Add Lunasima (was: Dr Vivigray)

### ISSUE THREAD

**Issue by chrissimpkins** [google/fonts#6091]
**Font Project Git Repo URL:**

https://github.com/docrepair-fonts/lunasima-fonts

**Super short description of the Font Family:**

Lunasima is a DocRepair font intended for improving document compatibility with the ISO/IEC 29500 standard. Lunasima is based on Noto Sans, which is an unmodulated (“sans serif”) design.

**Requirements:**

I understand that Google Fonts will publish only fonts that matches its requirements, and I can confirm the project meets them (by ticking the cases, or putting x between the square brackets in text mode):

- [x] The entire font project is licensed under the [OFL](https://scripts.sil.org/cms/scripts/page.php?site_id=nrsi&id=OFL)
- [x] There is no "Reserved Font Name" mention in the OFL license
- [x] Family name is unique according to namecheck.fontdata.com
- [ ] The font supports at least [GF Latin Core glyphset](https://github.com/googlefonts/glyphsets/tree/main/GF_glyphsets/Latin/)
- [x] The repository respect the [upstream repo structure](https://googlefonts.github.io/gf-guide/upstream.html)
- [x] The source files are available in the repository
- [x] I read, agree and comply with the full [contributing requirements](https://googlefonts.github.io/gf-guide/onboarding.html)
- [x] I am the author of the font or the author agreed to this submission
- [x] I will maintain the repository

**Comment by twardoch** [comment]
@chrissimpkins @yanone This is now actually ready for onboarding. We have changed the name to "Lunasima".
