### ISSUE TITLE
Add Belanosima (was: Dr Beverlin)

### ISSUE THREAD

**Issue by chrissimpkins** [google/fonts#6095]
**Font Project Git Repo URL:**

https://github.com/docrepair-fonts/belanosima-fonts

**Super short description of the Font Family:**

Belanosima is a DocRepair font, intended to improve compliance with the ISO/IEC 29500 standard by providing fallback that minimizes text reflow in Office Open XML documents. Belanosima is based on Josefin Sans, a geometric, elegant family with a vintage feeling, for use at larger sizes. Josefin Sans is inspired by geometric sans serif designs from the 1920s. 

**Requirements:**

I understand that Google Fonts will publish only fonts that matches its requirements, and I can confirm the project meets them (by ticking the cases, or putting x between the square brackets in text mode):

- [x] The entire font project is licensed under the [OFL](https://scripts.sil.org/cms/scripts/page.php?site_id=nrsi&id=OFL)
- [x] There is no "Reserved Font Name" mention in the OFL license
- [x] Family name is unique according to namecheck.fontdata.com
- [ ] The font supports at least [GF Latin Core glyphset](https://github.com/googlefonts/glyphsets/tree/main/GF_glyphsets/Latin/)
- [x] The repository respect the [upstream repo structure](https://googlefonts.github.io/gf-guide/upstream.html)
- [x] The source files are available in the repository
- [x] I read, agree and comply with the full [contributing requirements](https://googlefonts.github.io/gf-guide/onboarding.html)
- [x] I am the author of the font or the author agreed to this submission
- [x] I will maintain the repository

**Comment by twardoch** [comment]
@yanone @chrissimpkins This is ready to be onboarded
