### ISSUE TITLE
Add Playpen and Playpen Sans (new how-to-write families)

### ISSUE THREAD

**Issue by chrissimpkins** [google/fonts#6097]
**Font Project Git Repo URL:**

Currently private

**Super short description of the Font Family:**

The project is constituted of two subfamilies

- Playpen, tracked in #6449 
- PlaypenSans, tracked in #6377 

**Image:**

Attach here a pic or a screenshot of the font; one is enough, it can be few letters, to give a quick overview.

**Comment by chrissimpkins** [comment]
Playpen Sans will be the first of these families.  The tracker for this family is https://github.com/google/fonts/issues/6377

**Comment by davelab6** [comment]
Closing as tracked in #6449 and #6277

**Comment by chrissimpkins** [comment]
Updated title and OP contents to reflect the name change "Playpen" ==> "Playwrite"
