### ISSUE TITLE
Unblock Sedan & Sedan SC

### ISSUE THREAD

**Issue by yanone** [google/fonts#6119]
https://github.com/googlefonts/googlefontsdirectory-old/tree/main/ofl/sedan
https://github.com/googlefonts/googlefontsdirectory-old/tree/main/ofl/sedansc

**Comment by chrissimpkins** [comment]
What needs to be done here?

**Comment by yanone** [comment]
This is one of the fonts that is on the GF repo but never got published, and we have a document that lists those as fonts to be unblocked.
Specifically, the sources hold the RFN statement and Dave says he doesn't recall ever having interacted with the author, but it was once already on track to be published. It's a super magnificent font that I'd like to see with GF.

**Comment by chrissimpkins** [comment]
Got it, thanks!  Moved this into Q2 and added Dave so that we can look into, discuss the RFN issue.

**Comment by yanone** [comment]
Yes, Dave did by email on March 31st 2023:


> Hi Sebastián 
> It's been over a decade, I think, and I have no longer any memory at all of the reason I did 
> not publish your lovely Sedan font project in Google Fonts. 
> +Yanone is available to help get the project published, and I'd like to confirm with you that I can remove the Open Font License "Reserved Font Name" and publish the fonts with the name "Sedan" :) 

Reply:

> Yes, please! Would be great

**Comment by vv-monsalve** [comment]
Sedan is now live
