### ISSUE TITLE
Nunito vs Ninuto Sans: odd difference in a couple characters

### ISSUE THREAD

**Issue by wolftune** [google/fonts#612]
See these two pages:

* https://fonts.google.com/specimen/Nunito
* https://fonts.google.com/specimen/Nunito+Sans

Swap back and forth, and you can see the height of the crossbar on the capital A and that of the ÷ symbol are different between the two, although there's no justification for the difference that I'm aware of.

**Comment by davelab6** [comment]
@fonthausen thoughts?

**Comment by Fonthausen** [comment]
I had a look and compared both fonts. The crossbar of the capital A and the divide glyph (÷) is at the same height in both versions.

The only thing I could find, is that the divide glyph is not interpolating well across the weights of Nunito (rounded). We should have a look at this. (This an issue we have with Glyphsapp)

If you are talking about the design, the position of the crossbar of the capital A is not a reference for the position of the crossbar of the divide glyph.

**Comment by wolftune** [comment]
All I know is that on Firefox on my GNU/Linux system (KDE Neon), the bars do not render at the same height on those pages I linked.

**Comment by davelab6** [comment]
Please could you provide a screenshot?

**Comment by Fonthausen** [comment]
I made screenshots in the original Glyph data. These are the masters used to render the instances.
In the background (gray) you can see Nunito (rounded)

I also made screenshot in Chrome of the links you sent (google fonts) and overlaid them in Photoshop.

J.


Op 29 jan. 2017, om 23:00 heeft Dave Crossland <notifications@github.com> het volgende geschreven:

> Please could you provide a screenshot?
> 
> > All I know is that on Firefox on my GNU/Linux system (KDE Neon), the bars
> > do not render at the same height on those pages I linked.

**Comment by Fonthausen** [comment]
<img width="650" alt="schermafbeelding 2017-01-29 om 23 03 54" src="https://cloud.githubusercontent.com/assets/20181530/22408369/1b5911ce-e678-11e6-9b23-9f0fff5ee321.png">
<img width="675" alt="schermafbeelding 2017-01-29 om 23 04 11" src="https://cloud.githubusercontent.com/assets/20181530/22408371/1b5ac33e-e678-11e6-891d-7aad9bdd4ff0.png">
<img width="474" alt="schermafbeelding 2017-01-29 om 23 05 44" src="https://cloud.githubusercontent.com/assets/20181530/22408370/1b5abee8-e678-11e6-89ef-990c3a18eed2.png">

**Comment by m4rc1e** [comment]
@Fonthausen Thank you so much for the effort here, this is great! 

Judging by the images, the only reason other reason I can think of is autohinting in Windows.

@wolftune What OS are you using? please upload some screenshots.

I don't see this issue in OS X (the line bounce is just misaligned browser tabs)
![jan-29-2017 22-17-43](https://cloud.githubusercontent.com/assets/7525512/22408443/d63b62f6-e670-11e6-9e71-7c3274b4d531.gif)

**Comment by m4rc1e** [comment]
Ok, It's auto hinting in Win 7.

![jan-29-2017 22-23-17](https://cloud.githubusercontent.com/assets/7525512/22408491/9ddcaa68-e671-11e6-9e84-8c06c33e004f.gif)

Thanks @wolftune,

@davelab6 I'll file an issue tomorrow on his tomorrow, after I have collected my thoughts. This is an issue which is collection wide.

**Comment by davelab6** [comment]
ttfautohint has a new "family stability" feature, maybe running over both
families in one pass can help?

On Jan 29, 2017 5:25 PM, "Marc Foley" <notifications@github.com> wrote:

Ok, It's auto hinting in Win 7.

[image: jan-29-2017 22-23-17]
<https://cloud.githubusercontent.com/assets/7525512/22408491/9ddcaa68-e671-11e6-9e84-8c06c33e004f.gif>

Thanks @wolftune <https://github.com/wolftune>,

@davelab6 <https://github.com/davelab6> I'll file an issue tomorrow on his
tomorrow, after I have collected my thoughts. This is an issue which is
collection wide.

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/google/fonts/issues/612#issuecomment-275951330>, or mute
the thread

**Comment by chreekat** [comment]
I see the same thing @wolftune reports, on Chromium "Version 53.0.2785.143 Built on Ubuntu , running on Ubuntu 14.04 (64-bit)"

![anim](https://cloud.githubusercontent.com/assets/538538/22413742/148d62c2-e66f-11e6-8489-b4bc47fb2563.gif)

**Comment by mray** [comment]
When I noticed this first in Firefox ÷ was even getting truncated partially _(sorry no screenshot)_. So I'm not sure in how far this is more of a browser issue.

**Firefox** 51.0.1 (64-bit) Ubuntu 16.10 now renders it fine like this:
![nunito](https://cloud.githubusercontent.com/assets/164785/22502502/6649324e-e86d-11e6-852e-cd0ebb8818b0.gif)

**Chromium** Version 55.0.2883.87  on Ubuntu 16.10 (64-bit)
![nunito-chromium](https://cloud.githubusercontent.com/assets/164785/22502909/63d356a0-e86f-11e6-9b24-79736b3ab67c.gif)

**Comment by davelab6** [comment]
I said, 

> ttfautohint has a new "family stability" feature, maybe running over both families in one pass can help?

@alexeiva please try this out when prepping the next Nunito + Nunito Sans release with Cyrillic

**Comment by alexeiva** [comment]
I have some thoughts on this:

NunitoSans `2.002` has custom ttfautohint parameters assigned, while Nunito uses default. I will try to match them and see if this helps. If not I will try the `family stability`.
<img width="793" alt="screen shot 2017-11-23 at 8 19 17 pm" src="https://user-images.githubusercontent.com/16634089/33182071-e81be7a6-d08b-11e7-81aa-94fe09304b58.png">

**Comment by alexeiva** [comment]
I am looking for volunteers to test the `hintingfix1` on Nunito fonts. New ttf's are here:
https://github.com/alexeiva/NunitoFont/tree/998f57b88251ef825928debc89d4bfce0eb3347f/fonts

**Comment by m4rc1e** [comment]
I'll review this now.

**Comment by alexeiva** [comment]
Also please review https://github.com/alexeiva/NunitoFont/tree/hintingfix2/fonts
with `Save as TrueType` custom parameter as suggested in  https://forum.glyphsapp.com/t/ttfautohint-different-from-project/3186/5

**Comment by m4rc1e** [comment]
@alexeiva I just looked at the Reg and Black

```
Regression Report:

Fonts: ["Nunito-Black.ttf", "Nunito-Regular.ttf"]

View: waterfall
WARNING: Desktop_OS_X_El_Capitan_safari_9.1_.jpg is different by 124 pixels
PASSED: Desktop_Windows_7_ie_9.0_.jpg is the same
PASSED: Desktop_Windows_7_chrome_50.0_.jpg is the same
PASSED: Desktop_Windows_10_edge_15.0_.jpg is the same
WARNING: Desktop_Windows_7_firefox_45.0_.jpg is different by 48849 pixels
```

Here's the FireFox gif.

![desktop_windows_7_firefox_45 0_](https://user-images.githubusercontent.com/7525512/33184178-42679dfe-d073-11e7-96d3-4b7b6b16435c.gif)

looks worse imo. The 'A' hasn't changed at all.

If I was you, I'd do the autohinting tests on fonts downloaded from Google Fonts, so we know nothing else has regressed. The FF image above gives the impression kerns have changed.

**Comment by alexeiva** [comment]
It is worse. I don't think it is a kerning change because not all sizes are affected. To me it is a grid fitting issue of glyphs `A c q`.

**Comment by alexeiva** [comment]
No changes after the Save as TrueType trick. Tested on Win7 Firefox latest.

**Comment by alexeiva** [comment]
Achieved partial success using ttfautohints `reference=file` option. Used Nunito as a Reference for Nunito Sans. The A is still jittering, but other glyphs are stable.

![nunito-hint1](https://user-images.githubusercontent.com/16634089/36798077-0a318b06-1cc3-11e8-9cfd-db557a69249b.gif)

Screenshots were made from these pages:
http://www.cyreal.org/testR/index.html > [Nunito][n]
http://www.cyreal.org/testS/index.html > [Nunito Sans][sans] (hint1 branch)

[n]: https://github.com/alexeiva/NunitoFont/tree/master/fonts/TTF
[sans]: https://github.com/alexeiva/NunitoSans/tree/hint1/fonts/TTF

Maybe manual hints in `A` will help.

**Comment by alexeiva** [comment]
Here are some more tests:

![all](https://user-images.githubusercontent.com/16634089/36803510-2eee106e-1cd1-11e8-98be-c5525b6bf633.gif)

Best pair:

![best](https://user-images.githubusercontent.com/16634089/36803523-3a9554ae-1cd1-11e8-8cbf-7feb358035b2.gif)

However this still does not fix the jittering in A. I assume a control file is required to deal with it. At this point this is beyond my knowledge.

List of autohinting parameters applied:

Nunito Sans:
http://www.cyreal.org/testS1/index.html autohinted in Glyphs App
http://www.cyreal.org/testS2/index.html `-v -a nnn` (=natural stems)

Nunito:
http://www.cyreal.org/testR1/index.html  autohinted in Glyphs App
http://www.cyreal.org/testR2/index.html `-v -a nnn` with reference file S1
http://www.cyreal.org/testR3/index.html `-v -a nnn` with reference file S2
http://www.cyreal.org/testR4/index.html  `-v -a sss` (=strong stems)

**Comment by alexeiva** [comment]
Left: Nunito, Right: Nunito Sans in Glyphs App showing identical rendering.

<img width="911" alt="screen shot 2018-02-28 at 9 24 48 pm" src="https://user-images.githubusercontent.com/16634089/36803809-23b00134-1cd2-11e8-9bc7-d0a49556de9a.png">

<img width="883" alt="screen shot 2018-02-28 at 9 25 18 pm" src="https://user-images.githubusercontent.com/16634089/36803825-2ed9effc-1cd2-11e8-939a-363826239d57.png">
