### ISSUE TITLE
Typo of "Edge" on the Google Fonts Analytics page

### ISSUE THREAD

**Issue by Arsalan04** [google/fonts#6128]
It says "Edg" instead of "Edge" in the Browsers section on [Google Fonts Analytics page](https://fonts.google.com/analytics).

**Comment by RITCHIEsingh** [comment]
Hey, I would like to work on this issue. Can I get assigned to this project ?

**Comment by nyshadhr9** [comment]
"Edg" is parsed from the User-Agent string and the reason why it's not called "Edge" is explained here: https://learn.microsoft.com/en-us/microsoft-edge/web-platform/user-agent-guidance#user-agent-strings
