### ISSUE TITLE
Source Sans Pro 4 does not render correctly in Firefox 1.1.1 for Windows and Android

### ISSUE THREAD

**Issue by ScribbleGhost** [google/fonts#6138]
Specify the font name in title with a short description of the bug. 
Please report any issue related to Noto fonts in this repository: https://github.com/googlefonts/noto-fonts/issues.

**Describe the bug**
Source Serif 4 looks like rectangles on Firefox 111.0 on Windows 10 and on Firefox 111.1.1 on Android.
This works fine Microsoft Edge.

**To Reproduce**
- Use the latest version of Firefox,
- Go to: https://fonts.google.com/specimen/Source+Serif+4?query=source+ser

**Expected behavior**
I expected the font to render letters, not rectangles.

**Screenshots**
![228803849-49e41b3a-927a-46a7-9d14-da3b1cd95a8f](https://user-images.githubusercontent.com/49068170/228920485-3b4dcfe0-cd26-47e9-a2da-433fd0466c4f.png)

**Additional context**

**Comment by RosaWagner** [comment]
Hi @ScribbleGhost, thanks for you report. What happens if you refresh the page?

**Comment by kenmcd** [comment]
> What happens if you refresh the page?

Nothing on multiple refresh.
Tried yesterday on Win 10 with Firefox 110.0.1.
No Source Sans files downloaded at all.
So all .notdef symbols. 
Vivaldi (chromium) worked fine.

**Comment by ScribbleGhost** [comment]
Yeah, I can confirm what kenmcd is saying.

**Comment by frankrolf** [comment]
Originally I suspected the issue might have to do with VF, but it seems that some static fonts have the same problem:
![image](https://user-images.githubusercontent.com/2049645/229187040-2f69cf4d-80a4-4e1c-a4b4-0d0718198b08.png)

**Comment by tphinney** [comment]
On Mac, I see the problem in Firefox, but Chrome and Safari are fine for me.

**Comment by chrissimpkins** [comment]
This is fixed. Thank you very much for reporting it.  We really appreciate it!
