### ISSUE TITLE
Update DM Sans

### ISSUE THREAD

**Issue by Colophon-Foundry** [google/fonts#6193]
**Font Project Git Repo URL:**
https://github.com/googlefonts/dm-fonts

**Current version:**
`v1.001`

**New available version:**
`v2.001`

**Super short description of the upgrade:**
Expand the coverage of the weight range to ExtraHairline & ExtraBlack (100–1000 weight range) along with two new optical sizes (Text & Display). These extensions apply to both the Upright and Italic styles, and will also include a Variable font file build including all styles (separated into Upright/Italic files).

**Bugs reported in this repo which this upgrade would fix:**
Search in the [issue tracker](https://github.com/google/fonts/issues) if there is some opened issues containing the font name.

[#17](https://github.com/googlefonts/dm-fonts/issues/17)
[#15](https://github.com/googlefonts/dm-fonts/issues/15)
[#8](https://github.com/googlefonts/dm-fonts/issues/8)

**Comment by Colophon-Foundry** [comment]
@emmamarichal — Do you have a guide as to where to push sources?

**Comment by emmamarichal** [comment]
@Colophon-Foundry You can send a PR to the repo, like you did before, or you can send me them by email (bonjour@emmamarichal.fr). Thanks!

**Comment by RosaWagner** [comment]
@emmamarichal expected in STAT table: 14, 18, 24, 36
don't forget to bump up the version number ;)
