### ISSUE TITLE
Add Sour Gummy

### ISSUE THREAD

**Issue by eifetx** [google/fonts#6210]
Font Project Git Repo URL: https://github.com/eifetx/Sour-Gummy-Fonts

Super short description of the Font Family:

Sour Gummy Font is a fun and playful typeface has recently been updated to offer even more versatility and style. This font is perfect for adding a touch of whimsy and character to your designs.

Requirements:

I understand that Google Fonts will publish only fonts that matches its requirements, and I can confirm the project meets them (by ticking the cases, or putting x between the square brackets in text mode):

- [x] The entire font project is licensed under the [OFL](https://scripts.sil.org/cms/scripts/page.php?site_id=nrsi&id=OFL)
- [x] There is no "Reserved Font Name" mention in the OFL license
- [x] Family name is unique according to namecheck.fontdata.com
- [x] The font supports at least [GF Latin Core glyphset](https://github.com/googlefonts/glyphsets/tree/main/GF_glyphsets/Latin/)
- [x] The repository respect the [upstream repo structure](https://googlefonts.github.io/gf-guide/upstream.html)
- [x] The source files are available in the repository
- [x] I read, agree and comply with the full [contributing requirements](https://googlefonts.github.io/gf-guide/onboarding.html)
- [x] I am the author of the font or the author agreed to this submission
- [x] I will maintain the repository

Image:
![Preview](https://user-images.githubusercontent.com/123919967/233465936-fdd516a0-4eda-4b80-9b01-ce668fdec734.jpg)

Attach here a pic or a screenshot of the font; one is enough, it can be few letters, to give a quick overview.

**Comment by emmamarichal** [comment]
@chrissimpkins you moved this from `submission to review` to `Q3` + `P3` label, but the label `submission` hasn't been changed to `accepted`. I just want to be sure I can start the onboarding here.

**Comment by chrissimpkins** [comment]
Ok to onboard.  Thanks Emma.

**Comment by emmamarichal** [comment]
@chrissimpkins 
Status:
fonts ready and QA done: https://github.com/emmamarichal/Sour-Gummy-Fonts 
But still waiting for the name table strategy (font origin name in name ID1)
