### ISSUE TITLE
Open Sans Italic Backtick character has 0 width

### ISSUE THREAD

**Issue by pkim168** [google/fonts#6221]
Backticks in italic Open Sans font have 0 width, causing them to stack on each other and other letters
![image](https://user-images.githubusercontent.com/25191963/234100426-b2680a7c-25e6-4afb-a8a7-d855ccfd87ab.png)
![image](https://user-images.githubusercontent.com/25191963/234100497-3bd9c643-0374-4689-8237-218d907d51f3.png)

**Comment by davelab6** [comment]
@moyogo could you take a look at this?

**Comment by chrissimpkins** [comment]
@emmamarichal This is marked as live.  Can you confirm?  And if so, can we close this issue?

**Comment by emmamarichal** [comment]
I confirm!
