### ISSUE TITLE
Jua: space glyph is missing, .notdef is blank

### ISSUE THREAD

**Issue by justinpenner** [google/fonts#6237]
**Describe the bug**
Space glyph is not present. U+0020 points to `.notdef`. Also, the .notdef glyph is blank, rather than displaying a tofu box.

**Screenshots**
<img width="1243" alt="image" src="https://user-images.githubusercontent.com/46039243/234934124-65f905db-dad0-4341-8534-d568904afc48.png">
<img width="621" alt="image" src="https://user-images.githubusercontent.com/46039243/234935057-d796eb7e-1f98-458c-9d13-218095307508.png">
<img width="453" alt="image" src="https://user-images.githubusercontent.com/46039243/234935460-1990a31d-81de-4ee1-9141-4a3a4345c06c.png">
*Note: the .notdef shown here is from the special Tofu font used on fonts.google.com*

**Comment by RosaWagner** [comment]
Hi @justinpenner, thanks for the report. Indeed that is problematic. The public repo (https://github.com/woowabros/Jua) also doesn't provide sources so it looks we will have to hotfix that.

@woowabros can you make the sources of this font available in the repository?

**Comment by RosaWagner** [comment]
I made a global issue about the collection from the designer in #6329 so closing here
