### ISSUE TITLE
How to use tools/encodings

### ISSUE THREAD

**Issue by graphicore** [google/fonts#624]
I'm working on getting language coverage information for the encodings in tools/encodings. I'm going to ask some questions here in order to make sure I use the provided files correctly.

The [README.md in GF 2016 Glyph Sets](https://github.com/google/fonts/blob/master/tools/encodings/GF%202016%20Glyph%20Sets/README.md) mentions "Core" encodings for Latin and Cyrillic, but it seems there are no files `encodings/GF 2016 Glyph Sets/GF-latin-core_unique-glyphs.nam` and `encodings/GF 2016 Glyph Sets/Cyrillic/GF-cyrillic-core_unique-glyphs.nam`, are the "Core" encodings `encodings/latin_unique-glyphs.nam` and `encodings/cyrillic_unique-glyphs.nam`?

---

[README.md](https://github.com/google/fonts/blob/master/tools/encodings/README.md) says:
> Typically all the Unicodes in each file are in each font. If the fonts go beyond that list, those additional characters will not be available to Fonts API end users.

So, I guess the Fonts API uses these files directly for subsetting.

But from the data I see, some files must be dependent on other files, e.g. [latin-ext_unique-glyphs.nam](https://github.com/google/fonts/blob/master/tools/encodings/latin-ext_unique-glyphs.nam) does not include the chars of [latin_unique-glyphs.nam](https://github.com/google/fonts/blob/master/tools/encodings/latin_unique-glyphs.nam)
Thus, implicitly, `latin-ext_unique-glyphs` includes the charcodes of `latin_unique-glyphs`, this is not documented, as far as I can see.

Is there anywhere a description what exactly the subsetter does for each encoding provided by the Fonts API?

Similarly, my unicode cldr based coverage script produces output like this:

```
googleFontsTools/encodings/sinhala_unique-glyphs.nam
lax language detection: true
language: Sinhala 72 % having: 74 needed: 103 missing: 29 ("-" U+002d,"–" U+2013,"—" U+2014,"," U+002c,";" U+003b,":" U+003a,"!" U+0021,"?" U+003f,"." U+002e,"…" U+2026 … and 19 more) laxSkipped: 3
```

([full output for all nam files](https://gist.github.com/graphicore/00a79eded3553a64ad409559246d853c))

In this case, some very common punctuation marks are missing, it seems impossible that the fonts API would ship a font without e.g. the exclamation mark. Is there a rule, like that all encodings include `latin_unique-glyphs`?

**Comment by graphicore** [comment]
> are the "Core" encodings encodings/latin_unique-glyphs.nam and encodings/cyrillic_unique-glyphs.nam?

It seems to me now that "Core" is included in [GF-latin-plus_unique-glyphs.nam](https://github.com/google/fonts/blob/master/tools/encodings/GF%202016%20Glyph%20Sets/GF-latin-plus_unique-glyphs.nam), as there are all the basic alphabet and punctuation chars present.

**Comment by graphicore** [comment]
> But from the data I see, some files must be dependent on other files

Answering myself a bit. I discovered [`tools/util/google_fonts.py`](https://github.com/google/fonts/blob/master/tools/util/google_fonts.py), which implements the dependency resolving in its [`CodepointFiles`](https://github.com/google/fonts/blob/master/tools/util/google_fonts.py#L261) function, here the essential lines:

```py
  files = [subset]

  # y-ext includes y
  # Except latin-ext which already has latin.
  if subset != 'latin-ext' and subset.endswith('-ext'):
    files.append(subset[:-4])

  # almost all subsets include latin.
  if subset not in ('khmer', 'latin'):
    files.append('latin')
```

**Comment by alexeiva** [comment]
>  are the "Core" encodings encodings/latin_unique-glyphs.nam and encodings/cyrillic_unique-glyphs.nam?

That is right. But there are list filters for Core sets Glyphs in the [2016](https://github.com/google/fonts/tree/master/tools/encodings/GF%202016%20Glyph%20Sets/filter%20lists) folder. 

> Thus, implicitly, latin-ext_unique-glyphs includes the charcodes of latin_unique-glyphs, this is not documented, as far as I can see.

Similarly, Latin Pro builds on top of Latin Plus as a prerequisite. Our list filters only feature the unique (additional) glyphs.

**Comment by alexeiva** [comment]
> It seems to me now that "Core" is included in GF-latin-plus_unique-glyphs.nam, as there are all the basic alphabet and punctuation chars present.

Plus is the new "Core". For sake of sanity we started defining Plus from scratch. Technically some glyphs from Core are missing in Plus, such as `uniE0FF`, `uniEFFD`, `uniF000`. I don't know what is their use

**Comment by thlinard** [comment]
PUA characters `uniE0FF`, `uniEFFD`, `uniF000` are for logo: #75

**Comment by graphicore** [comment]
@alexeiva 

> But there are list filters for Core sets Glyphs in the 2016 folder.

Ok, but these are for designers using glyphs. What is the point of talking about the core glyph set in the README anyways, if:

> Plus is the new "Core".

So there is no core anymore?

**Comment by alexeiva** [comment]
Core still exists. What I mean is when we defined the 2016 set, we absorbed
existing Core glyphs rather than making a unique glyphs list on top of
Core.

**Comment by graphicore** [comment]
But it exists more like a concept than like a real thing, heh? Or, will there be new fonts that just include the Core set, or Glyph Sets that include Core but not Plus?

**Comment by alexeiva** [comment]
Recently there was a request for the Core set filter list in the
discussions thread. I asume it may be still used as a bare minimum for
non-Latin fonts, i.e. Arabic, etc.

**Comment by davelab6** [comment]
Exactly. Core is what is served when only the Latin subset is served, the
others are all more and more reaching into the Latin-Ext subset range. The
Latin subset (core) is a bug test for what is required to be in a font.

**Comment by graphicore** [comment]
So, there should be a nam file for core.

**Comment by graphicore** [comment]
> PUA characters uniE0FF, uniEFFD, uniF000 are for logo: #75

I just made a Latin-Core file. It doesn't include these PUA chars. Do we need them?

**Comment by graphicore** [comment]
@davelab6 wrote in that other issue:

> The PUA glyphs are included because some foundries keep their logo there (which Jason P appears to only have the Ubuntu font installed with such a logo) and the other has a hinting debugging character (also appearing in the Ubuntu fonts.) Feel free to leave those ones out :)

Which sounds OK to me, and also another reason to agree with https://github.com/graphicore/specimenTools/issues/20

**Comment by graphicore** [comment]
closing this because of #685
