### ISSUE TITLE
Add Krabei Prey

### ISSUE THREAD

**Issue by hemnarin** [google/fonts#6244]
**Font Project Git Repo URL: https://github.com/hemnarin**

**Krabei Prey Regular is a modern Khmer display typeface suitable for headings and large typography**

**Krabei Prey Version: 1.0**

I understand that Google Fonts will publish only fonts that matches its requirements, and I can confirm the project meets them (by ticking the cases, or putting x between the square brackets in text mode):

- [x] The entire font project is licensed under the [OFL](https://scripts.sil.org/cms/scripts/page.php?site_id=nrsi&id=OFL)
- [x] There is no "Reserved Font Name" mention in the OFL license
- [x] Family name is unique according to namecheck.fontdata.com
- [x] The font supports at least [GF Latin Core glyphset](https://github.com/googlefonts/glyphsets/tree/main/GF_glyphsets/Latin/)
- [ ] The repository respect the [upstream repo structure](https://googlefonts.github.io/gf-guide/upstream.html)
- [ ] The source files are available in the repository
- [ ] I read, agree and comply with the full [contributing requirements](https://googlefonts.github.io/gf-guide/onboarding.html)
- [x] I am the author of the font or the author agreed to this submission
- [x] I will maintain the repository

**Image:*
![Krabei Prey 01 copy](https://user-images.githubusercontent.com/132242314/235395097-b5f41033-99ab-4cd3-a2ab-5c2352e4eff3.jpg)
*

Attach here a pic or a screenshot of the font; one is enough, it can be few letters, to give a quick overview.

**Comment by RosaWagner** [comment]
Hi @hemnarin, thanks for your submission. We can't review the font without an access to a public repository containing the sources.

**Comment by hemnarin** [comment]
Hello, @RosaWagner  Do you have a guide as to where to push sources?

**Comment by RosaWagner** [comment]
Thanks for asking, you'll find our guide here: https://googlefonts.github.io/gf-guide/

**Comment by RosaWagner** [comment]
Closing this submission since no development since last summer. @hemnarin please feel free to re-open an issue when the sources are available in a public repository :)
