### ISSUE TITLE
Bug in Josefin Sans font: Accent marks are out of position in Vietnamese text

### ISSUE THREAD

**Issue by thanh-p** [google/fonts#6245]
**Describe the bug**

In Vietnamese text using the Josefin Sans font, the accent marks are not positioned correctly, causing them to appear misplaced.

**To Reproduce**

1. Go to https://fonts.google.com/specimen/Josefin+Sans using the Chrome browser.
2. Select "Asia" and "Vietnamese" in the "Select preview text" option.
3. Observe that the accent marks in the preview text are out of position.

**Expected behavior**
The accent marks in Vietnamese text using the Josefin Sans font should be correctly positioned above or below the corresponding vowel, according to the rules of Vietnamese orthography.

**Screenshots**
The screenshot below shows an example of incorrect accent mark positions in the JosefinSans font:
<img width="1331" alt="wrong positions - JosefinSans" src="https://user-images.githubusercontent.com/78190188/235866223-79f33294-2c34-44e7-899e-434bbef58188.png">

=> The accent marks for the words "Sự", "thường", "quyền", "dẫn", "đến", and "những" are misplaced. It's worth noting that the accent marks are displayed correctly in the font of GitHub.

**Additional context**
- OS: macOS Ventura, version 13.3
- Browser: Chrome Version 112.0.5615.137 (Official Build) (x86_64)
- Other notes:
  - The issue also occurs on the Safari browser, but to a lesser extent with fewer broken words.
  - The issue is reproducible on Windows and Linux using the Chrome browser.

**Comment by RosaWagner** [comment]
Hi @thanh-p, thanks for your report. This is a subsetting issue from the API, but no worries, the font is fine. If you download it you will see that it is complete and that the diacritics are behaving properly. The team is actively working on fixing this issue on the API.

**Comment by rsheeter** [comment]
API test https://codepen.io/rs42/pen/bGmYRer

**Comment by rsheeter** [comment]
Appears to be due to recent changes to the definition of latin-ext.

**Comment by rsheeter** [comment]
For example, using vietnamese and latin-ext from https://fonts.googleapis.com/css2?family=Josefin+Sans:

```
# vietnamese has a single glyph for 0x1edd
$ hb-shape --unicodes U+1edd --ned vietnamese.ttf
[uni1EDD]

# latin-ext gives separate glyphs for ohorn and gravecomb, evidently not appropriately positioned
$ hb-shape --unicodes U+1edd --ned latin_ext.ttf
[ohorn|gravecomb@545,0]
```

**Comment by rsheeter** [comment]
We believe we understand root cause and have a fix coming. The test page now works in our pre-prod environment.

**Comment by damnedbrain** [comment]
Any updates on this bug ?

**Comment by rsheeter** [comment]
We have pushed a partial fix that is believed to fix Vietnamese. Full support for marks is a bit fiddly and will take rather longer. I am now seeing this on https://fonts.google.com/specimen/Josefin+Sans (force-refresh if you go to check):

![image](https://user-images.githubusercontent.com/6466432/236517796-57168251-b2ed-4146-946d-9cc84259decf.png)

**Comment by damnedbrain** [comment]
Tks for the hardwork ! Looking forward to the full fix.
