### ISSUE TITLE
Add Tamba Sans

### ISSUE THREAD

**Issue by hankthemute** [google/fonts#6261]
**Font Project Git Repo URL:**

**Super short description of the Font Family:**

**Requirements:**

I understand that Google Fonts will publish only fonts that matches its requirements, and I can confirm the project meets them (by ticking the cases, or putting x between the square brackets in text mode):

- [ x] The entire font project is licensed under the [OFL](https://scripts.sil.org/cms/scripts/page.php?site_id=nrsi&id=OFL)
- [ x] There is no "Reserved Font Name" mention in the OFL license
- [ x] Family name is unique according to namecheck.fontdata.com
- [ x] The font supports at least [GF Latin Core glyphset](https://github.com/googlefonts/glyphsets/tree/main/GF_glyphsets/Latin/)
- [ x] The repository respect the [upstream repo structure](https://googlefonts.github.io/gf-guide/upstream.html)
- [ x] The source files are available in the repository
- [ x] I read, agree and comply with the full [contributing requirements](https://googlefonts.github.io/gf-guide/onboarding.html)
- [ x] I am the author of the font or the author agreed to this submission
- [ x
<img width="815" alt="Screenshot 2023-05-08 at 8 06 17 PM" src="https://user-images.githubusercontent.com/132808183/236983718-c9f571ab-1b8f-4c1a-95d6-0c4d876d60ad.png">
] I will maintain the repository

**Image:**

Attach here a pic or a screenshot of the font; one is enough, it can be few letters, to give a quick overview.
<img width="815" alt="Screenshot 2023-05-08 at 8 06 17 PM" src="https://user-images.githubusercontent.com/132808183/236983787-379f0ccd-05ae-40ec-9d1d-0c503ed1f960.png">

**Comment by applecuckoo** [comment]
Hello! Tamba Sans is a commercial typeface from Dharma Type, which is available to purchase [here](https://www.myfonts.com/collections/tamba-sans-font-dharma-type). The one on DaFont is just a demo font, and therefore is not the entire typeface itself. This isn't licensed under OFL, so it can't be accepted.

**Comment by RosaWagner** [comment]
Hi @hankthemute, thanks for your submission. Indeed Google Fonts onboards only OFL fonts, and this one is not. Therefore it can't be onboarded.
