### ISSUE TITLE
Adinkra

### ISSUE THREAD

**Issue by adinkraalphabet** [google/fonts#6267]
**https://github.com/adinkraalphabet/adinkra:**

**Adinkra Alphabet font for the languages of Akan, Ewe, Ga and Dagbani found in Ghana and Cote D'Ivoire:**

**Requirements:**

I understand that Google Fonts will publish only fonts that matches its requirements, and I can confirm the project meets them (by ticking the cases, or putting x between the square brackets in text mode):

- [x] The entire font project is licensed under the [OFL](https://scripts.sil.org/cms/scripts/page.php?site_id=nrsi&id=OFL)
- [x] There is no "Reserved Font Name" mention in the OFL license
- [x] Family name is unique according to namecheck.fontdata.com
- [x] The font supports at least [GF Latin Core glyphset](https://github.com/googlefonts/glyphsets/tree/main/GF_glyphsets/Latin/)
- [x] The repository respect the [upstream repo structure](https://googlefonts.github.io/gf-guide/upstream.html)
- [x] The source files are available in the repository
- [x] I read, agree and comply with the full [contributing requirements](https://googlefonts.github.io/gf-guide/onboarding.html)
- [x] I am the author of the font or the author agreed to this submission
- [x] I will maintain the repository

**Image:**
![AdinkraSnapShot](https://github.com/google/fonts/assets/25257917/70303aa4-8d23-42f3-9f8c-a2f544f83736)

**Comment by fitojb** [comment]
The repository doesn't include any source files to build the font. A TTF is not source.

**Comment by adinkraalphabet** [comment]
I just uploaded the source files. Thank you.

Charles

**Comment by adinkraalphabet** [comment]
We have been working with Unicode for a while now. Here is a link to the
initial submission of Adinkra to Unicode @
https://www.unicode.org/L2/L2021/21020-adinkra.pdf. The characters that you
have are what we submitted to Unicode.
I would recommend you double check with them before making any changes.
Thank you for working on this.

**Comment by adinkraalphabet** [comment]
Here is a link to the most recent submission of Adinkra to Unicode @
https://www.unicode.org/L2/L2021/21237-adinkra-response.pdf

**Comment by adinkraalphabet** [comment]
I don't understand what you mean by the outlines are subpar. The characters were not autotraced. I hand drawn each of them myself. This was done in keeping with the tradition of Adinkra symbols which are hand drawn.

**Comment by davelab6** [comment]
@adinkraalphabet thanks so much for your proposal! Sadly, our systems are only capable to handle Unicode encoded scripts, and we can't accept this project until it the script is accepted by the Unicode Consortium and included in an annual Unicode release. Personally I've met a couple of folks who are also keen to see this script become established in the digital world and I wish you luck and patience with the Unicode process! Please open a new issue after Unicode acceptance, before the annual release.

**Comment by adinkraalphabet** [comment]
Sounds good. Thank you very much.
