### ISSUE TITLE
Designer information update on Advent font

### ISSUE THREAD

**Issue by VivaRado** [google/fonts#6279]
Would like the designer information for advent font updated please, would like it to be switched from Andreas Kalpakidis to VivaRado and https://vivarado.com/ If an image is required please use this https://pbs.twimg.com/profile_images/1582026119418716162/CF0KWPEC_400x400.png

The about text is great!

Thank you

**Comment by RosaWagner** [comment]
thanks @VivaRado for letting us know. The request is added to the queue.

**Comment by emmamarichal** [comment]
@VivaRado Have you seen my last comment?
thanks!

**Comment by davelab6** [comment]
@emmamarichal please could you execute only the change as provided and leave a bio text for another update later?
