### ISSUE TITLE
Add Berenis ADF Pro

### ISSUE THREAD

**Issue by Elendil03** [google/fonts#6281]
Berenis ADF is a condensed Didone with a large character set (including Greek and Cyrillic) and some OpenType features. It is available under the GPL V2 from the creator's website: http://arkandis.tuxfamily.org/adffonts.html.

**Comment by RosaWagner** [comment]
Hi @Elendil03, thanks for your submission. Unfortunately, GF doesn't accept fonts under that format and that license. You can read the contributing document to know more about fonts that GF may accept:
- https://github.com/google/fonts/blob/main/CONTRIBUTING.md
- https://googlefonts.github.io/gf-guide/onboarding.html
