### ISSUE TITLE
Add U+1E9E to Barlow Font

### ISSUE THREAD

**Issue by AliRISEmann** [google/fonts#6286]
Specify the font name in title with a short description of the bug. 
Please report any issue related to Noto fonts [here](https://notofonts.github.io/reporter.html).

**Describe the bug**
German language support is specified, but the new German letter U+1E9E (i.e. the big ß) is not available.

**Comment by applecuckoo** [comment]
@AliRISEmann Barlow's repo is https://github.com/jpt/barlow/, probably best to make an issue there.

**Comment by AliRISEmann** [comment]
@applecuckoo Thanks, I will do that. Should I then close this issue?

**Comment by applecuckoo** [comment]
Sure!
