### ISSUE TITLE
Oswald font - nonconformant version number

### ISSUE THREAD

**Issue by gilbahat** [google/fonts#63]
Hi,

the version specifier for Oswald-Light is wrong:

$ otfinfo -i "Oswald-Light (1).ttf"
Family:              Oswald
Subfamily:           Light
Full name:           Oswald Light
PostScript name:     Oswald-Light
Mac font menu name:  Oswald Light
Version:             Version ; ttfautohint (v0.92.18-e454-dirty) -l 8 -r 50 -G 200 -x 0 -w "g"

should be 'Version 2.002 ; ttfautohint (v0.92.18-e454-dirty) -l 8 -r 50 -G 200 -x 0 -w "g"'  to be conformant with spec. this will make version-aware font installers track this correctly.

**Comment by davelab6** [comment]
Thanks for reporting this :)

**Comment by davelab6** [comment]
Per https://github.com/behdad/fonttools/issues/372 Oswald has another bug that a ttx roundtrip will fix

**Comment by davelab6** [comment]
Fixed in https://github.com/m4rc1e/OswaldFont and will be pushed in next update :)
