### ISSUE TITLE
Add minisite_url for various fonts

### ISSUE THREAD

**Issue by thlinard** [google/fonts#6308]
Hi,

I suggest to add some minisites to the API metadata:

- https://brygada1918.eu/ for Brygada 1918
- http://bonanova.wtf/ for Bona Nova
- https://googlefonts.github.io/ebgaramond-specimen/ for EB Garamond
- https://rsms.me/inter/ for Inter
- https://indestructibletype.com/Jost.html for Jost
- https://etceteratype.co/grandstander/ for Grandstander
- https://piazzolla.huertatipografica.com/ for Piazzolla
- https://fonts.withgoogle.com/roboto-serif for Roboto Serif
- http://vollkorn-typeface.com/ for Vollkorn

**Comment by applecuckoo** [comment]
Here's another handful of URLs to add:

- <https://indestructibletype.com/Besley.html> for Besley
- <https://overpassfont.org/> for Overpass
- <https://www.lexend.com/> for Lexend
- <https://public-sans.digital.gov/> for Public Sans
- <https://huertatipografica.com/en/fonts/alegreya-ht-pro> for Alegreya
- <https://huertatipografica.com/en/fonts/alegreya-sans-ht> for Alegreya Sans
- <https://huertatipografica.com/en/fonts/andada-ht-pro> for Andada Pro
- <https://huertatipografica.com/en/fonts/cambo-ht> for Cambo

**Comment by chrissimpkins** [comment]
Added all recommended sites in this thread in #7074

Thank you very much for these lists!
