### ISSUE TITLE
Nunito (and Nunito Sans) Extra-Light not selectable in Inkscape

### ISSUE THREAD

**Issue by mray** [google/fonts#633]
I'm not sure if this is more of an Inkscape related issue.
In both fonts (Nunito + Nunito Sans) Extra-Light and Extra-Light Italic show up as "weight=280"  and "weight=280 italic".
When selected, Inkscape only uses the Light weight instead of the Extra-Light.

![screenshot](https://cloud.githubusercontent.com/assets/164785/22617732/3a0f2696-eacc-11e6-97bb-05f2afdc5b3e.png)

**Comment by m4rc1e** [comment]
@mray do you get the same problem using https://fonts.google.com/specimen/Raleway?

**Comment by davelab6** [comment]
Thin also appears missing from that list

**Comment by mray** [comment]
@m4rc1e yes, exactly the same behavior. The only difference is that "Raleway" features weights 250 and 280.

**Comment by mray** [comment]
![pi_ctxn6_r](https://cloud.githubusercontent.com/assets/164785/22620674/28925308-eb11-11e6-80af-109622d8a68d.png)

**Comment by ab-in** [comment]
same problem here
![inkscape_bug](https://cloud.githubusercontent.com/assets/3079893/23330248/d4019d14-fb49-11e6-978d-e27f37af45b0.png)

**Comment by olivierberten** [comment]
Just in case it helps, typing the font full name ("Nunito Extra-Light") in the font box should allow you to use it...

**Comment by mray** [comment]
@olivierberten thanks for that hint! I didn't even try that!!!

**Comment by ab-in** [comment]
hmm...Inkscape can't find Raleway font. this is actually a google web font.
Coul it be some problem for Inkscape?

2017-02-25 15:30 GMT+01:00 mray <notifications@github.com>:

**Comment by fitojb** [comment]
IIRC, this was already reported to Inkscape developers. Their bug tracker is at https://bugs.launchpad.net/inkscape

**Comment by fitojb** [comment]
Please follow the upstream report at https://bugs.launchpad.net/inkscape/+bug/1555109

**Comment by laerm0** [comment]
As this mostly seems to be an Inkscape bug, I am going to close it.

**Comment by davelab6** [comment]
@mray does any font family work?

**Comment by mray** [comment]
No. Now that I'm checking. Seems like all fonts containing extra light weights don't work (tried Exo 2, Titillium Web, Lato, Montserrat, Fira Sans)
