### ISSUE TITLE
Nabla minisite_url not showing

### ISSUE THREAD

**Issue by applecuckoo** [google/fonts#6334]
**Describe the issue**
I'm the author of #5957. It seems that the link for Nabla isn't showing up? Climate Crisis still shows up with a link, but Nabla's link seems to have disappeared. The `METADATA.pb` file doesn't seem to have been altered since #5964 which closed my issue.

**To Reproduce**
1. Go to <https://fonts.google.com/specimen/Nabla>
2. Check the header, the URL is not there

**Expected behavior**
The URL <https://nabla.typearture.com/> should show up in the header.

**Additional context**
N/A

**Screenshots**
![Screenshot 2023-06-02 at 15-51-32 Browse Fonts - Google Fonts](https://github.com/google/fonts/assets/113647417/300a26c2-ff51-4b28-b537-17d858fd2f5f)

**Comment by RosaWagner** [comment]
It's sandbox, will be in prod in 1-2 weeks. If an issue got closed it mean we took care of it and it always take time before it get to the live server.
