### ISSUE TITLE
Foldit: dubious data in HVAR table

### ISSUE THREAD

**Issue by Lorp** [google/fonts#6343]
**Describe the bug**
The [Foldit](https://github.com/SophiaDesign/Foldit) variable font has an HVAR table for variable metrics as one would expect. The HVAR table consists primarily of an _ItemVariationStore_ subtable (`VarStore` in TTX), which itself consists of multiple _ItemVariationData_ subtables (`VarData` in TTX).

The issue concerns the fact that one of the `VarData` items has a _regionIndexCount_ (`VarRegionCount` in TTX) with value 0, which does not make sense in variation math, and results in an empty array in TTX.

I recommend that Font Bakery rejects such fonts, as some parsers may not deal with it cleanly. I have not discovered any special meaning for a _regionIndexCount_ of zero in the [HVAR spec](https://learn.microsoft.com/en-us/typography/opentype/spec/hvar) or the [_ItemVariationStore_ spec](https://learn.microsoft.com/en-us/typography/opentype/spec/otvarcommonformats#item-variation-store-header-and-item-variation-data-subtables).

Here follows the start of the TTX dump of the HVAR table.

```xml
<?xml version="1.0" encoding="UTF-8"?>
<ttFont sfntVersion="\x00\x01\x00\x00" ttLibVersion="3.44">

  <HVAR>
    <Version value="0x00010000"/>
    <VarStore Format="1">
      <Format value="1"/>
      <VarRegionList>
        <!-- RegionAxisCount=1 -->
        <!-- RegionCount=1 -->
        <Region index="0">
          <VarRegionAxis index="0">
            <StartCoord value="0.0"/>
            <PeakCoord value="1.0"/>
            <EndCoord value="1.0"/>
          </VarRegionAxis>
        </Region>
      </VarRegionList>
      <!-- VarDataCount=3 -->
      <VarData index="0">
        <!-- ItemCount=1 -->
        <NumShorts value="0"/>
        <!-- VarRegionCount=0 -->
        <Item index="0" value="[]"/>
      </VarData>
      <VarData index="1">
        <!-- ItemCount=3 -->
        <NumShorts value="0"/>
        <!-- VarRegionCount=1 -->
        <VarRegionIndex index="0" value="0"/>
        <Item index="0" value="[44]"/>
        <Item index="1" value="[100]"/>
        <Item index="2" value="[116]"/>
      </VarData>
      <VarData index="2">
        <!-- ItemCount=171 -->
        <NumShorts value="1"/>
        <!-- VarRegionCount=1 -->
        <VarRegionIndex index="0" value="0"/>
        <Item index="0" value="[136]"/>
        <Item index="1" value="[145]"/>
        <Item index="2" value="[154]"/>
        <Item index="3" value="[155]"/>
        <Item index="4" value="[165]"/>
        <Item index="5" value="[174]"/>
        <Item index="6" value="[176]"/>
...
```

**To Reproduce**
`$ ttx -t HVAR Foldit[wght].ttf`

**Expected behavior**
All `VarData` items in the .ttx file should have `VarRegionCount` > 0.

**Comment by Lorp** [comment]
Obviously also important to track down the upstream process that created the table.

**Comment by anthrotype** [comment]
when in https://github.com/fonttools/fonttools/issues/2211 @behdad added support for NO_VARIATION_INDEX 0xFFFFFFFF to OnlineVarStoreBuilder, he decided to not enable that for H/VVAR, with the following comment

> Note that, in constrained uses of the ItemVariationStore, like in HVAR/VVAR tables, it might be still beneficial to encode no-variations explicitly.

The optimize method is called with use_NO_VARIATION_INDEX=False for H/VVAR specifically: https://github.com/fonttools/fonttools/blob/65598197c8afd415781f6667a7fb647c2c987fff/Lib/fontTools/varLib/__init__.py#L566

I'm not entierly sure why exactly he chose not to use it there, but it was definitely intentional, and not a bug.

**Comment by Lorp** [comment]
Ok, thanks, if it’s definitely valid I’ll close the issue. Is there a use case or optimization rationale for null regions?

**Comment by anthrotype** [comment]
well it is _not_ invalid, and I'm sure Behdad has good reason for doing that in the varStore optimizer for H/VVAR, I'll leave it to him to answer.

**Comment by behdad** [comment]
Encoding 0xFFFFFFFF IN DeltaIndexMap struct forces it to four-byte entrees, which is suboptimal.

**Comment by Lorp** [comment]
Understood about 0xFFFFFFFF, but is that relevant here?

In this font the HVAR ItemVariationStore has 3 ItemVariationData structures:

* VarData #0 has 0 regions and 0 deltaSets
* VarData #1 has 1 region (region #0) with 3 deltaSets (all int8)
* VarData #2 has 1 region (also region #0) with 171 deltaSets (all int16)

Surely it would be more efficient and less risky as 1 ItemVariationData structure containing 174 deltaSets (all int16)? VarData #0 wastes 6 bytes and seems a bit risky; VarData #1 wastes 3 bytes (6 bytes - 3 bytes saved by using int8).

On the matter of "riskiness", should I assume that all count fields in OFF may be zero, e.g. fvar.axisCount and so on, and that such fonts remain valid?

**Comment by behdad** [comment]
> Understood about 0xFFFFFFFF, but is that relevant here?
> 
> In this font the HVAR ItemVariationStore has 3 ItemVariationData structures:
> 
> * VarData 0 has 0 regions and 0 deltaSets
> * VarData 1 has 1 region (region #0) with 3 deltaSets (all int8)
> * VarData 2 has 1 region (also region #0) with 171 deltaSets (all int16)
> 
> Surely it would be more efficient and less risky as 1 ItemVariationData structure containing 174 deltaSets (all int16)? VarData 0 wastes 6 bytes and seems a bit risky; VarData 1 wastes 3 bytes (6 bytes - 3 bytes saved by using int8).

There were some bugs in the optimizer that I recently fixed. It's possible that would fix this issue. I tried building FoldIt from source but it's failing for me.

> On the matter of "riskiness", should I assume that all count fields in OFF may be zero, e.g. fvar.axisCount and so on, and that such fonts remain valid?

I believe so.

**Comment by behdad** [comment]
> Surely it would be more efficient and less risky as 1 ItemVariationData structure containing 174 deltaSets (all int16)? VarData 0 wastes 6 bytes and seems a bit risky; VarData 1 wastes 3 bytes (6 bytes - 3 bytes saved by using int8).

Rebuilding the font, I get one:
```
      <!-- VarDataCount=1 -->
      <VarData index="0">
        <!-- ItemCount=175 -->
        <NumShorts value="1"/>
        <!-- VarRegionCount=1 -->
        <VarRegionIndex index="0" value="0"/>
```

**Comment by behdad** [comment]
If I go back to fonttools 9334a9117b21a35bee29122194ad0ef1f46e806f, then the 3 VarData are generated, which is suboptimal.

**Comment by Lorp** [comment]
Thanks for looking into this @behdad. Good to know it’s safe if unfixed, and that new builds will optimize the issue away.
