### ISSUE TITLE
API / CSS Issue with Font Wix Madefor Text

### ISSUE THREAD

**Issue by Phascolarctidae** [google/fonts#6344]
Issue: 
Missing css for the font "Wix Madefor Text" on googleapis.

Reproduce: Try to get css for the font "Wix Madefor Text"
http://fonts.googleapis.com/css?family=Wix%20Madefor%20Text&subset=latin

Expected behavior: Response like for the font"Wix Madefor Display"
http://fonts.googleapis.com/css?family=Wix%20Madefor%20Display&subset=latin

Best regards

**Comment by davelab6** [comment]
Curiously css2 API works

https://fonts.googleapis.com/css2?family=Wix%20Madefor%20Text&subset=latin

**Comment by garretrieger** [comment]
I've found the issue and a fix is coming.

**Comment by garretrieger** [comment]
Fix was released to production yesterday.
