### ISSUE TITLE
Add Playpen Sans

### ISSUE THREAD

**Issue by vv-monsalve** [google/fonts#6377]
**Font Project Git Repo URL:**

Currently private. 

**Super short description of the Font Family:**

This would be the first family of the [handwriting fonts](https://github.com/google/fonts/issues/6097).

**Requirements:**

I understand that Google Fonts will publish only fonts that matches its requirements, and I can confirm the project meets them (by ticking the cases, or putting x between the square brackets in text mode):

- [x] The entire font project is licensed under the [OFL](https://scripts.sil.org/cms/scripts/page.php?site_id=nrsi&id=OFL)
- [x] There is no "Reserved Font Name" mention in the OFL license
- [x] Family name is unique according to namecheck.fontdata.com
- [x] The font supports at least [GF Latin Core glyphset](https://github.com/googlefonts/glyphsets/tree/main/GF_glyphsets/Latin/)
- [x] The repository respect the [upstream repo structure](https://googlefonts.github.io/gf-guide/upstream.html)
- [x] The source files are available in the repository

**Image:**

Attach here a pic or a screenshot of the font; one is enough, it can be few letters, to give a quick overview.

**Comment by chrissimpkins** [comment]
We are resolving vertical metrics discussions/issues in https://github.com/TypeTogether/Playpen-Sans/issues/4.  Development is still in progress.

**Comment by vv-monsalve** [comment]
Icons improvements and access system is also in progress https://github.com/TypeTogether/Playpen-Sans/issues/3
To-Do list issue https://github.com/TypeTogether/Playpen-Sans/issues

**Comment by chrissimpkins** [comment]
Onboarding will be pushed back to tentatively early September following discussion with Dave, Viv, and Jose today.  We need to resolve v metrics and develop a broader icon weight range.

**Comment by vv-monsalve** [comment]
Metrics have been resolved. After the last QA round, two [Warns were reported](https://github.com/TypeTogether/Playpen-Sans/issues/10).
