### ISSUE TITLE
Add Afacad

### ISSUE THREAD

**Issue by ktkm** [google/fonts#6402]
**Font Project Git Repo URL:**
Currently private.

**Super short description of the Font Family:**

A custom lettering project conformed to the proportions used by Architect Sture Elmén in the 1940s.

**Requirements:**

I understand that Google Fonts will publish only fonts that matches its requirements, and I can confirm the project meets them (by ticking the cases, or putting x between the square brackets in text mode):

- [x] The entire font project is licensed under the [OFL](https://scripts.sil.org/cms/scripts/page.php?site_id=nrsi&id=OFL)
- [x] There is no "Reserved Font Name" mention in the OFL license
- [x] Family name is unique according to namecheck.fontdata.com
- [x] The font supports at least [GF Latin Core glyphset](https://github.com/googlefonts/glyphsets/tree/main/GF_glyphsets/Latin/)
- [x] The repository respect the [upstream repo structure](https://googlefonts.github.io/gf-guide/upstream.html)
- [x] The source files are available in the repository
- [x] I read, agree and comply with the full [contributing requirements](https://googlefonts.github.io/gf-guide/onboarding.html)
- [x] I am the author of the font or the author agreed to this submission
- [x] I will maintain the repository

**Image:**

![afacad_02_promo](https://github.com/google/fonts/assets/19203711/cd3da9d0-b986-427b-a5bb-23742107f352)

**Comment by ktkm** [comment]
@davelab6 @emmamarichal @RosaWagner I’m trying to reach you for an assessment regarding a couple of projects. Please get in touch.

**Comment by RosaWagner** [comment]
Hi @ktkm, thanks for reaching out. I understood from your emails you expect some kind of budget for these projects, and so only @davelab6 can answer to that. Emma and I are only contractors who onboard fonts, we can’t give any hint on financing matters.

**Comment by ktkm** [comment]
Hello @RosaWagner, nice to hear from you again. Yes, I was a little vague -- I started some budget and commission talks with @davelab6 last fall regarding another project. I’m still waiting to hear back from him. Hence, this latest add is not waiting to be commissioned. If you’re ready I can share the repository.

**Comment by RosaWagner** [comment]
Sure, we can take a look. I can't guarantee that it will be for sure onboarded cause we need to see the sources for that.

**Comment by ktkm** [comment]
Sounds good! You should have an invite by now.

**Comment by ktkm** [comment]
Good morning @RosaWagner, nice to see that “Afacad” has been accepted. Please let me know what my following objectives are.

**Comment by RosaWagner** [comment]
I'll get in touch when we get to it, it will depends on the priorities for next quarter ;)
