### ISSUE TITLE
Add [Font DAZZED]

### ISSUE THREAD

**Issue by legalintakepros** [google/fonts#6424]
**Font Project Git Repo URL:**

**Super short description of the Font Family:**
Dazzed is a sans-serif typeface with narrow proportions which started as a bespoke typeface for a cinematic project proposal. In the same way that all kinds of movies exist, Dazzed aims to comprise them in its overall look. You can see comic, grotesque, dramatic and quirky moments in “a, e, C, G” meeting technical, steel cold, action, crime and sci-fi shapes in “t, f, r” where the terminals are cut-off. Also these contrast with the classical forms of other letters. The dots are rounded for accents contrary punctuation is squared this leads to better recognition. Italics are in 18°, lower degrees on request.

Design: Martin Vácha
Spacing and Kerning: Alex Slobzheninov
First Sketch: 8/2016, Released: 7/2019, Update: 11/2019
7 weights, 14 styles

**Requirements:**

I understand that Google Fonts will publish only fonts that matches its requirements, and I can confirm the project meets them (by ticking the cases, or putting x between the square brackets in text mode):

- [ ] The entire font project is licensed under the [OFL](https://scripts.sil.org/cms/scripts/page.php?site_id=nrsi&id=OFL)
- [ ] There is no "Reserved Font Name" mention in the OFL license
- [ ] Family name is unique according to namecheck.fontdata.com
- [ ] The font supports at least [GF Latin Core glyphset](https://github.com/googlefonts/glyphsets/tree/main/GF_glyphsets/Latin/)
- [ ] The repository respect the [upstream repo structure](https://googlefonts.github.io/gf-guide/upstream.html)
- [ ] The source files are available in the repository
- [ ] I read, agree and comply with the full [contributing requirements](https://googlefonts.github.io/gf-guide/onboarding.html)
- [ ] I am the author of the font or the author agreed to this submission
- [ ] I will maintain the repository

**Image:**

Attach here a pic or a screenshot of the font; one is enough, it can be few letters, to give a quick overview.
[DP_Dazzed_specimen_A4.pdf](https://github.com/google/fonts/files/11839460/DP_Dazzed_specimen_A4.pdf)

**Comment by RosaWagner** [comment]
Hi @legalintakepros, thanks for your suggestion. Unfortunately this is not an open-source font, it has a commercial license: https://displaay.net/typeface/dazzed/. Therefore GF can't onboard it.
