### ISSUE TITLE
Overnight my Lato looks quite different

### ISSUE THREAD

**Issue by websevendev** [google/fonts#644]
I noticed the Lato on my site looks different than it used to.
I had some older tabs open overnight, so I compared.

Open in tabs and flick back and forth:
Before:
http://i.imgur.com/boAj26Q.png
After:
http://i.imgur.com/w6yCaVd.png

In dev tools, under Sources, a new source has appeared: fonts.gstatic.com

To me, the change has taken place on other pages using Lato too: http://semantic-ui.com/elements/header.html

---

So can anyone help me understand this? 

Is the change personal to me only?

I have Lato installed on my Windows. Has my browser been using it for the past 6 months and then suddenly decided to request it from fonts.gstatic.com instead? Or is my local Lato never used when a website specifically imports a Google font?

---

I like the old version better, so how would I go about achieving the old look, if the font size and variant are exactly the same?

**Comment by dominiklaube** [comment]
I've got the same problem. But I currently don't have any solution for this.

**Comment by Banandrew** [comment]
@dominiklaube self-hosting?

**Comment by m4rc1e** [comment]
@websevendev The change is not personal. Lato hadn't been upgraded in several years. We've upgraded it recently to the latest version, 2.015.

Lato 2.015 uses a newer version of ttfauothint which had x-height pixel rounding applied. We didn't add this ourselves but the creator of the font.

@davelab6 Since this issue keeps cropping up, we should by default match the previous version's settings. I'll look into how we can write a test for this.

**Comment by lowwa132** [comment]
Same problem here.
@m4rc1e indeed, it's frustrating having such a change, without any notice or warning of the potential noticeable visual effects. It could be great to have at least the correct settings for this new version, to behave like the previous one, do you have it ?

**Comment by m4rc1e** [comment]
@lowwa132 I understand your frustrations. This is a fine balancing act between being backwards compatible with the previous version and allowing modifications. 

When preparing fonts, I try and stay as faithful as possible to the original source. I usually end up modifying just the name table. My process to convert Lato 2.0 so it's GF api friendly is [here](https://github.com/googlefonts/LatoGFVersion/blob/master/build/build.sh). I didn't modify any hinting settings. The x-height rounding was introduced in the original source.

I've done some further tests between the version we have uploaded and the newest version available on the [official site](http://www.latofonts.com/lato-free-fonts/#download). The rendering is identical. The hinting difference was introduced in the original sources. 

*left tab: fonts.google.com Lato 2.0 right tab: Latofonts.com 2.0*
![lato](https://cloud.githubusercontent.com/assets/7525512/22781936/b563d0a0-eebc-11e6-922a-298c3eaf0ef4.gif)

**Comment by leonardooliveira95** [comment]
I'm having the same issue, here is how it used to look until yesterday:  

![antes](https://cloud.githubusercontent.com/assets/16289733/22782357/dab0b1d4-eead-11e6-8218-ae8412bf2828.png)  

And this is how it looks now:

![depois](https://cloud.githubusercontent.com/assets/16289733/22782366/ebed10be-eead-11e6-8763-12ad4caa2733.png)

I'm using the following import statement in my CSS:  
`` 
@import url("https://fonts.googleapis.com/css?family=Lato:400,700,400italic");
``

Is there a way to make the font look like it was?

**Comment by dominiklaube** [comment]
I also use the version hostet by google //fonts.googleapis.com/css?family=Lato:400,400italic,700italic,700

**Comment by lmdsp** [comment]
Same problem here, my website looks completely off now ...

**Comment by davelab6** [comment]
I spoke to @twardoch and 

1. I will ask to rollback the update and 

2. the latest ttfautohint has a xheight snapping per-family feature that he will apply (and work with @m4rc1e on) and make a 2 point something release soon and I'll push that in time

**Comment by davelab6** [comment]
Another issue found in the update pushed yesterday:

> Due to new ligatures in Lato, the cursor only renders in front of the 't' or after the 'i'. Using the keyboard, you can confirm that the actual cursor is in the right place, but the ligature (combined 'ti' character/grapheme) prevents it from rendering normally.

**Comment by jaycen** [comment]
I'm experiencing issues with Lato aswell. Woke up to see our site's main navigation looking terrible. Seems like the font is stretching vertically when at small sized (12px-16px) and at weight 700.

Please roll back or provide a legacy version. I'd rather not swap our main font, but at least in our case it looks very awkward.
http://imgur.com/a/ImU1y

**Comment by sfarbota** [comment]
We also had issues with this update (in fact, images were being pushed out of their proper containers as a result of the CSS changes). However, just as I was about to fix our UI issues from my end, I noticed that the change had been reverted. Thanks for the fix!

**Comment by davelab6** [comment]
> Please roll back or provide a legacy version

Roll back has been completed
