### ISSUE TITLE
Update Shanti [Vernon Adams]

### ISSUE THREAD

**Issue by emmamarichal** [google/fonts#6447]
Will need a googlefonts repo

Font Project Git Repo URL:
https://github.com/vernnobile/ShantiFont

Current version:
1.000
https://fonts.google.com/specimen/Shanti

New available version:
Not available / we can fix bugs and upgrade to 1.100

Super short description of the upgrade:
expand glyphset, fix bugs

Bugs reported in this repo which this upgrade would fix:
a lot of fails

**Comment by emmamarichal** [comment]
This is the version I have in the repo (Vernon Adams): some serifs were added (+ some other differences, see the images). I can't find the version we have currently on GF.
Possibilities:

- [ ] create a new family for this "serif" version (what name?)
- [ ] replace the current version (but the design is too different I think)
- [ ] remove the serifs to get the same result as before (but should we change the x-height also?)

![Shanti](https://github.com/google/fonts/assets/64773544/656cc6e8-c8e2-408f-8c8a-5fcd2da61e17)
![Shanti2](https://github.com/google/fonts/assets/64773544/bed88b5d-3396-416b-9056-16868a0684a6)

**Comment by emmamarichal** [comment]
@davelab6 can I have your opinion on it? :)

**Comment by davelab6** [comment]
Ship the serif glyphs as a stylistic set, base the project on the binaries in the gf API and hand transplant Vernon's WIP sources into them :)
