### ISSUE TITLE
Text specimen length on Akatab family

### ISSUE THREAD

**Issue by chrissimpkins** [google/fonts#6454]
The text specimen string for the [Akatab family](https://fonts.google.com/specimen/Akatab) is too long.

![5zCXoyFEDcgQjrU](https://github.com/google/fonts/assets/4249591/e6ca1ccd-6f2e-4de0-addc-d9831b97aa76)

This is defined in the `styles:` field of the [METADATA.pb file](https://github.com/google/fonts/blob/main/ofl/akatab/METADATA.pb).

We'll need to shorten the text length.

cc @RosaWagner who has been revising text length in other fields of the file in recent weeks 
cc @jvgaultney in case you have any recommendations about a shorter phrase that will work better with the front end dimensions

**Comment by RosaWagner** [comment]
I did. It's a new sample text for that font specifically.
They already gave a shorter sentence, I just confused the different sizes in METADATA.pb cause they are not very explicit on what goes where. I'll shorten it tomorrow.

**Comment by chrissimpkins** [comment]
Thanks Rosalie!
