### ISSUE TITLE
Font Issue: Bungee Spice - Number "4" hanging line

### ISSUE THREAD

**Issue by ptbarnum4** [google/fonts#6455]
**Describe the bug**
**Font:** Bungee Spice
The number "4" seems to have a line hanging from it. I believe the line is intended to wrap around the inside of the number, similar to all of the other letters/numbers

**To Reproduce**
Take a look at [Bungee Spice on google fonts](https://fonts.google.com/specimen/Bungee+Spice?coloronly=true&preview.text=0123456789&preview.text_type=custom).  ([Here's just the number 4](https://fonts.google.com/specimen/Bungee+Spice?coloronly=true&preview.text=4&preview.text_type=custom))

**Expected behavior**
The number "4" should match the other glyphs in the Bungee Spice set

**Screenshots**
<img width="314" alt="Screenshot 2023-06-26 at 7 44 15 PM" src="https://github.com/google/fonts/assets/37914211/a1958ef8-d5d6-4f40-989c-2dcff7fb8730">

<img width="855" alt="Screenshot 2023-06-26 at 7 30 21 PM" src="https://github.com/google/fonts/assets/37914211/ff3d86b2-aa7f-4952-99fc-8ee46b3a6acb">

---

**Additional context**
Operating System: macOS Ventura Version 13.4.1 (22F82)
Browser: Brave - Version 1.52.126 Chromium: 114.0.5735.133 (Official Build) (arm64)

**Comment by kenmcd** [comment]
Strange.
Appears to only affect the COLRv0 and COLRv1 fonts.
The SVG, SBIX, and plain TTF fonts all appear to be fine.

You may want to file this issue with the upstream repo here:
https://github.com/djrrb/Bungee

**Comment by RosaWagner** [comment]
cc @anthrotype @rsheeter @djrrb

**Comment by ptbarnum4** [comment]
Closing here and reopening at https://github.com/djrrb/Bungee/issues/88
