### ISSUE TITLE
I sended a Google Form to include my font

### ISSUE THREAD

**Issue by jjelizondo** [google/fonts#646]
Hi, sorry but I am confused. I already send a Google Form (that is the "oficial" channel in the Google Fonts website) and now you answerme via twitter that I need to do some complicated flow with GitHub.

The font is from my company "LATAM Airlines Group", that is a multinational with more than 50.000 employees. I need to undertand how acomplish your upload rules for a company, and step by step because I am only a UX Designer and dont have a deep knowledge about GitHub or code respositories. 

Can you recover my Google Form (sing with my corporate mail juanjose.elizondo@latam.com) and help me please?

Thank you so much and sorry for the incoveniences.

**Comment by davelab6** [comment]
@jjelizondo I emailed you :) Let's continue the discussion there or on a call :)
