### ISSUE TITLE
Add Ruwudu (SIL)

### ISSUE THREAD

**Issue by LornaSIL** [google/fonts#6463]
**Font Project Git Repo URL:**
https://github.com/silnrsi/font-ruwudu

Release:
https://github.com/silnrsi/font-ruwudu/releases/tag/v3.000

**Super short description of the Font Family:**
Ruwudu is the Manga word for “writing”. This style of writing is used by the Manga people in Niger, West Africa. The design is very much influenced by the Rubutun Kano style, but was based on the monoline samples of footnotes from the market edition manuscripts. 

**Requirements:**

I understand that Google Fonts will publish only fonts that matches its requirements, and I can confirm the project meets them (by ticking the cases, or putting x between the square brackets in text mode):

- [x] The entire font project is licensed under the [OFL](https://scripts.sil.org/cms/scripts/page.php?site_id=nrsi&id=OFL)
- [ ] There is no "Reserved Font Name" mention in the OFL license **(RFNs are allowed in SIL fonts per agreement)**
- [x] Family name is unique according to namecheck.fontdata.com
- [ ] The font supports at least [GF Latin Core glyphset](https://github.com/googlefonts/glyphsets/tree/main/GF_glyphsets/Latin/)
- [ ] The repository respect the [upstream repo structure](https://googlefonts.github.io/gf-guide/upstream.html)
- [x] The source files are available in the repository
- [x] I read, agree and comply with the full [contributing requirements](https://googlefonts.github.io/gf-guide/onboarding.html)
- [x] I am the author of the font or the author agreed to this submission
- [x] I will maintain the repository

**Image:**

Attach here a pic or a screenshot of the font; one is enough, it can be few letters, to give a quick overview.

![image](https://github.com/google/fonts/assets/7071907/c6b7e628-a95f-4220-ac80-e8cec33fd5ba)

**Comment by RosaWagner** [comment]
@emmamarichal we didn't see that the arabic subset was missing in metadata.pb

**Comment by RosaWagner** [comment]
@LornaSIL we have some tofu in sandbox. The font doesn't seem to support the glyphs "ae", is it something you want to add to the font or does it mean we should limit the specimen to specific arabic languages? In case of the latter, which one?

<img width="757" alt="Screenshot 2023-07-20 at 12 29 49" src="https://github.com/google/fonts/assets/12222436/189d1014-969e-4ba3-915c-5a4f1473f356">

**Comment by LornaSIL** [comment]
@RosaWagner it has the same character set as Alkalami.
