### ISSUE TITLE
Change icon color for material icons/symbols when downloading as .svg and .png

### ISSUE THREAD

**Issue by snebens** [google/fonts#6472]
#This issue also works for requesting features. 

**Describe the issue**
I am trying to use my custom brand hex codes to change the color of the icon. How can I do this? 

**To Reproduce**
N/a

**Expected behavior**
N/a

**Additional context**
N/a

**Screenshots**
N/a

**Comment by RosaWagner** [comment]
Please open an issue there: https://github.com/google/material-design-icons
