### ISSUE TITLE
/ofl/notoemoji is missing

### ISSUE THREAD

**Issue by davelab6** [google/fonts#6479]
https://fonts.google.com/noto/specimen/Noto+Emoji exists but unlike https://github.com/google/fonts/blob/main/ofl/notocoloremoji/ it doesn't exist in this repo. I'll fix that directly now, but, @m4rc1e could we have the CI check that we don't get out of sync again? I seem to recall there was an effort to resync the API and this repo, I'd like to see that redone to bring them up to date plus have the CI prevent the gap reappearing.

**Comment by RosaWagner** [comment]
@davelab6 Shouldn't this be part of the Noto repo dans then onboarded like the other Noto fonts by @simoncozens to create a proper link between upstream and downstream?

**Comment by chrissimpkins** [comment]
closed by https://github.com/google/fonts/pull/6480
