### ISSUE TITLE
Can you make myanmar unicode font can be used correctly in Adobe Illustrator?

### ISSUE THREAD

**Issue by yanlinaung30** [google/fonts#648]
Can you make myanmar unicode font can be used correctly in Adobe Illustrator?

**Comment by davelab6** [comment]
@yanlinaung30 thanks for reporting this! The best we can do it make myanmar unicode fonts available; you'll need to contact Adobe about Illustrator, though... Sorry I can't offer more help! :)

**Comment by Yekokodesigner** [comment]
Can you make myanmar unicode font for Asoka Myanmar Unicode (Beta)

**Comment by sladen** [comment]
@Yekokodesigner, please could you describe (precisely) what does not work, including a screenshot with the (precise) problem highlighted?

**Comment by Yekokodesigner** [comment]
Yes, illustrator cc 2018

**Comment by sladen** [comment]
@Yekokodesigner, and when using "illustrator cc 2018", what (precisely) should happen, that is not happening.

Please described the exact steps required to reproduce the problem, along with screenshots at each step.
