### ISSUE TITLE
Cyrillic symbols disappeared from Lato font

### ISSUE THREAD

**Issue by pelid** [google/fonts#649]
Just yesterday i have included Lato font to my site and it worked well:

```
link(href="https://fonts.googleapis.com/css?family=Lato:300,400,400i,700&amp;subset=cyrillic,cyrillic-ext", rel="stylesheet")
```

But today support of cyrillic symbols dissapeared. Why ? What the reason?

**Comment by m4rc1e** [comment]
@pelid The fonts have been rolled back to v1.104, you should have your Cyrillic back.

Apologies for the inconvenience. We're working on regression tools to void these issues in the future.

**Comment by davelab6** [comment]
@pelid thanks for reporting this! I hope to push an updated point release with Cyrillic support soon, but I can't give a specific date. Meanwhile you could self-host the web fonts, from http://www.latofonts.com

**Comment by rinart73** [comment]
Any moment now? The good thing about Google Fonts (besides that it's CDN) is that every font has language subsets thus reducing overall size of the font. Of course, users can chop font into pieces manually, but not everybody even knows how to do that. Can you please add Cyrillic support?

**Comment by DrDarbin** [comment]
Hi! Was the Cyrillic support added?

**Comment by trenkwill** [comment]
Hey ! Has the Cyrillic support been re-added ?

**Comment by leoankit1984** [comment]
Is Cyrillic support added now ?

**Comment by sashabeep** [comment]
Hello! Still can't use Lato Cyrillic from Google fonts

**Comment by Parallaps** [comment]
Hi! I'm waiting for a Lato Cyrillic font too. Are any updates?

**Comment by lockie** [comment]
Hello, I was wondering if Cyrillic support in Lato font would be added anytime soon.
