### ISSUE TITLE
IBM Plex Serif does not include slashed zero variant

### ISSUE THREAD

**Issue by michaelficarra** [google/fonts#6506]
**Describe the bug**
When using IBM Plex Serif from Google Fonts together with `font-variant-numeric: slashed-zero`, I do not get a slashed zero. If I instead download the font from the Google Fonts website and install it, I get a slashed zero.

**To Reproduce**

Create an HTML document with 

```html
<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=IBM%20Plex%20Serif:ital,wght@0,400;0,700;1,400;1,700&amp;display=swap">
```

and

```html
<style>
body {
  font-family: IBM Plex Serif, serif;
  font-variant-numeric: slashed-zero;
}
</style>
```

and

```html
<body>ZERO: 0</body>
```

**Expected behavior**
Expect to see a slashed `0`.

Possibly related: #3522. Has the font been stripped of these variant glyphs?

**Comment by RosaWagner** [comment]
Hi, thanks for your report. Unfortunately the Google Fonts API does not support this type of opentype feature. You would have to download and self host the font to benefit from it — if the font does contain it.
