### ISSUE TITLE
Suggestion to bring back previous version of Montserrat as separate font

### ISSUE THREAD

**Issue by tempusrname** [google/fonts#651]
Montserrat has progressed with many changes and styles. For those using the font for the first time it might mean more variety and better performance, but for the millions of websites that have Montserrat because of the '400' and '700' font-weights it would be inconveniente to have the font suddenly change without warning. The '400' fontweight is too thin and may drastically change the typography on the many websites its being used.

I propose bringing back the previous version of Montserrat as a standalone font, while keeping the new version separate.

**Comment by davelab6** [comment]
Sorry, I believe that the new weight is best for text, and the old version was too heavy. If you want to self host the earlier version, you are free to do so, that's the point of a libre license. Let me know if you have any questions about how to do that.

**Comment by tempusrname** [comment]
People pick the font based on what it looks like at the moment. Having a font look a certain way for years and there being people who picked that font because of the way it looked on their design, then changing that appearance all of a sudden is not a good way to do things. Bringing back the old version alongside the new one would be a quick and easy solution.
