### ISSUE TITLE
Add Agbalumo

### ISSUE THREAD

**Issue by eliheuer** [google/fonts#6515]
**Font Project Git Repo URL:** https://github.com/SorkinType/Agbalumo

**Super short description of the Font Family:**

This project is part of the African scripts effort currently underway.

Curvy, chunky, and compact. The Agbalumo display typeface has been designed to represent and capture the beauty of African languages. Primarily taking shape from the use of a brush pen, it's charming, playful, and cute look lends itself to a variety of commercial use cases. From beautifully curated eye catching websites to brightly colored packaged items, if you aim to communicate personality, Agbalumo is a sure selection.

Agbalumo is a single weight font. The glyph set includes standard opentype features and an assortment of stylistic alternates. Agbalumo can be used for African languages that make use of the Latin script, European languages, and Vietnamese.

Agbalumo is designed by ColumnType

**Requirements:**

I understand that Google Fonts will publish only fonts that matches [its requirements](https://googlefonts.github.io/gf-guide/), and I can confirm the project meets them (by ticking the cases, or putting x between the square brackets in text mode):

- [x] The entire font project is licensed under the [OFL](https://scripts.sil.org/cms/scripts/page.php?site_id=nrsi&id=OFL)
- [x] There is no "Reserved Font Name" mention in the OFL license
- [x] Family name is unique according to namecheck.fontdata.com
- [x] The font supports at least [GF Latin Core glyphset](https://github.com/googlefonts/glyphsets/tree/main/GF_glyphsets/Latin/)
- [x] The repository respect the [upstream repo structure](https://googlefonts.github.io/gf-guide/upstream.html)
- [x] The source files are available in the repository
- [x] I read, agree and comply with the full [contributing requirements](https://googlefonts.github.io/gf-guide/onboarding.html)
- [x] I am the author of the font or the author agreed to this submission
- [x] I will maintain the repository

**Image:**

![image](https://github.com/google/fonts/assets/5162664/69251d81-bdda-415f-84a1-9264cc99aece)

**Comment by chrissimpkins** [comment]
@EbenSorkin will development of this family wrap up before the end of the year?

**Comment by EbenSorkin** [comment]
Yes. Maybe this month or even early this month.

**Comment by eliheuer** [comment]
The name of this project changed from Danfo to Agbalumo

The new Git repo is here: https://github.com/SorkinType/Agbalumo
