### ISSUE TITLE
Mulish - weird result when using -webkit-text-stroke

### ISSUE THREAD

**Issue by lcnogueira** [google/fonts#6516]
**Describe the bug**
I'm not sure if this is exactly a bug or if I should do something different, but `-webkit-text-stroke` produces a weird result on Mulish font.

**To Reproduce**
1. Add an html element that uses the Mulish font:
```
<h1 class="style-two">Some content <span>join our team</span></h1>
```

2. Apply the `webkit-text-stroke`:
```
h1 {
  color: #fff;
  text-shadow: -4px 6px #000;
  font-size: 30px;
  font-style: italic;
  
  & span  {
     text-shadow: -4px 6px #000;
     font-size: 60px;
     display: block;
    letter-spacing: 0.60px;
    -webkit-text-stroke: 3px #ace200;
    color: #222;
  }
}
```

**Screenshots**
You can see below how it renders (Mulish) x how it should render (Rubik):
<img width="1497" alt="Screenshot 2023-07-06 at 21 42 38" src="https://github.com/google/fonts/assets/12154623/95ddb530-ad1e-4c90-afb1-63efa180bc60">

**Additional context**
Add any other context about the problem here (OS version, browser, printer…)
This issue is present on Chrome, Safari and Firefox.

**Comment by RosaWagner** [comment]
You'll find answer about that issue in #4212.

**Comment by lcnogueira** [comment]
Thank you @RosaWagner !
