### ISSUE TITLE
No English language selection?

### ISSUE THREAD

**Issue by kdschlosser** [google/fonts#6520]
**Describe the issue**
While there is the availability to select different languages, English is not one of the possible choices. Rather odd that isn't available.

**To Reproduce**
go to https://fonts.google.com/ and click on language. 

**Expected behavior**
To be able to filter the fonts showing only English fonts

**Comment by tiroj** [comment]
The ‘Language’ dropdown is mislabeled, and also inconsistently implemented. It is mostly a _script_ — i.e. writing system — list, so to see fonts that support English language you would select Latin script. Note that the results may show fonts that appear to be in other scripts, but this means that the fonts support Latin alongside those other scripts.

**Comment by kdschlosser** [comment]
Yes and no. The files located here https://github.com/google/fonts/tree/main/lang/Lib/gflanguages/data/languages are broken down as `{language_code}_{script)`  Granted the language code is a 2 letter code "en" for english" But I would imagine it would not be that difficult to create a list.

I have a python script that I wrote that specifically handles languages along with countries. It has all of the ISO codes for them and they are properly married together.

It could be ported to javascript without too much effort I am sure. If it would be of any help I offer that.

**Comment by RosaWagner** [comment]
Hi @kdschlosser, thanks for your report. All fonts on Google Fonts support English, it is the minimal required glyphset. If you see an exception, it means there is an error we must plan on fixing. If you want to see only English on the catalog view, you can type a custom sentence in english.

**Comment by kdschlosser** [comment]
well that is useful information that probably should be put on the site somewhere so people will know.

This is what is seen if no custom text is entered

![image](https://github.com/google/fonts/assets/10932297/bb244da9-ceba-494f-a29d-0a6a057802c5)


some being English and some being in other languages make a person assume that a font is only for that language and that is not the case.
