### ISSUE TITLE
Download Is Corrupted at the source.

### ISSUE THREAD

**Issue by KrillinsWorld** [google/fonts#6521]
#This issue also works for requesting features. 
### The File Is Corrupted at The Source

**Describe the issue**
I have downloaded this files 10+ times in the past 18 hours. When I attempt to unzip / extract the file, every source I have tried ends in the same manner. "The File Is Invalid" message displays and the file never gets extracted or unzipped. I have tried this on 3 devices, A Server running Windows Server 2022 Datacenter, Laptop Running Windows 11 and on Android OS 13 on a Samsung galaxy note 20 ultra 5g downloaded over mobile network just to try a different connection.

**To Reproduce**
Downloaded from this link https://codeload.github.com/google/material-design-icons/zip/refs/tags/4.0.0 (308 MB) Android OS reports it is 309 MB.

**Expected behavior**
Expected the file to UNZIP or EXTRACT the contents.

**Additional context**
Tried several sources all of them ended in failed attempts, indicating the file is corrupted at the source. I am currently downloading "master" file from github. We'll see how that goes as I am already at 1.1 GB (the file shows 1.16GB). Wasting 1.5 GB of storage space with invalid files is wasted overhead, so these files were deleted.

**Screenshots**
Downloading the "master" file produced the following error message, this one said it was EMPTY!?
![Master File Error Message](https://github.com/google/fonts/assets/38374421/31dcdd6f-7bd4-4bfd-8de7-1e6b9e24c821)
Downloading the "icons-4.0.0" file produced the following error message, saying it is invalid.
![material-design-icons-4 0 0 Error Message (308MB) zip](https://github.com/google/fonts/assets/38374421/34dcc986-e314-4f2b-b232-7416d9c599ec)

**Comment by RosaWagner** [comment]
Hi @KrillinsWorld, thanks for your report. Please report any issue with Google Icon/Symbols [in this repository](https://github.com/google/material-design-icons).
