### ISSUE TITLE
Why is there still no way to download all animated emojis?

### ISSUE THREAD

**Issue by yuraiz** [google/fonts#6524]
There's no normal way to download all emojis from https://googlefonts.github.io/noto-emoji-animation/ 

[documentation](https://googlefonts.github.io/noto-emoji-animation/documentation) states that "the world is not ready for that many simultaneously dancing emoji." but that seems like an outdated information. Even smartphones can play many animations (telegram, for example)

Here's my demo that displays animations without huge problems, so I think it's reasonable to be able to download them at least for testing

[Screencast from 2023-07-12 18-22-00.webm](https://github.com/google/fonts/assets/63008755/189ded0f-9118-4005-9286-b9157033dffa)

**Comment by RosaWagner** [comment]
Hi @yuraiz, thanks for your report. Please report any issue with Google Icon/Symbols [here](https://github.com/google/material-design-icons).

**Comment by yuraiz** [comment]
> Hi @yuraiz, thanks for your report. Please report any issue with Google Icon/Symbols [here](https://github.com/google/material-design-icons).

Animated emojis aren't icons, and https://googlefonts.github.io/noto-emoji-animation/documentation links to that issue tracker

**Comment by RosaWagner** [comment]
Thanks for pointing it out, but from my point of view this is an error, I'll ask if it can be changed. 

You can try the issue tracker of [Noto Emoji](https://github.com/googlefonts/noto-emoji) then. The point is we can't take care of your request from here, this repo manages [fonts.google.com](https://fonts.google.com), not [https://googlefonts.github.io/noto-emoji-animation/](https://googlefonts.github.io/noto-emoji-animation/documentation)
