### ISSUE TITLE
Kelson

### ISSUE THREAD

**Issue by kgilmo01** [google/fonts#6528]
[kelson.zip](https://github.com/google/fonts/files/12063315/kelson.zip)
**Font Project Git Repo URL:**

**Super short description of the Font Family:**

**Requirements:**

Google Fonts will publish only fonts that match its requirements. Please familiarize yourself with the complete documentation in the [Google Fonts Guide](https://googlefonts.github.io/gf-guide/) (GF-Guide) and ensure your font project complies with them before submitting the font family. You can also use the [Google Fonts Project Template](https://github.com/googlefonts/googlefonts-project-template), which will help you create a repository that follows the needed structure and includes build requirements.

By filling this issue, you can confirm the project meets the  requirements (by ticking the cases or putting x between the square brackets in text mode):

- [x] I read, agree, and comply with the full [contributing requirements](https://googlefonts.github.io/gf-guide/index#pre-production-getting-your-fonts-ready-for-gf)
- [x] The entire font project is licensed under the [OFL](https://scripts.sil.org/cms/scripts/page.php?site_id=nrsi&id=OFL)
- [x] There is no "Reserved Font Name" mention in the OFL license
- [ ] Family name is unique according to [namecheck.fontdata.com](https://namecheck.fontdata.com/)
- [x] The font supports at least [GF Latin Core glyphset](https://github.com/googlefonts/glyphsets/tree/main/GF_glyphsets/Latin/)
- [x] The repository respect the [upstream repo structure](https://googlefonts.github.io/gf-guide/upstream.html)
- [x] The source files are available in the repository
- [ ] I am the author of the font, or the author agreed to this submission
- [x] I will maintain the repository and participate in the onboarding process (addressing, solving, and responding to issues, merging pull requests, etc)

**Image:**

Attach here a pic or a screenshot of the font. One image is enough, it can be a few letters, to give a quick overview.

**Comment by eliheuer** [comment]
Thanks, but there is no font Project Git repo URL or Image.

You have checked `I will maintain the repository` so there should be a Git repository you can link to.

**Comment by ravid-dubsteper** [comment]
i found this font in myfonts: https://www.myfonts.com/collections/kelson-font-armasen

**Comment by RosaWagner** [comment]
Hi @kgilmo01, thanks for your submission. Unfortunately, we can't onboard font that are not open source (OFL license linked abouve), even if it is distributed for free. Monotype has a particular license that prevents from third-party distribution.
