### ISSUE TITLE
Oswald: broken 'ffl' ligature, appears as 'ffi'

### ISSUE THREAD

**Issue by davelab6** [google/fonts#653]
The update to Oswald pushed last week has a broken `ffl` ligature that appears as `ffi`

http://jsbin.com/mabixizovu/edit?html,output looks like this:

<img width="377" alt="screen shot 2017-02-13 at 12 41 52" src="https://cloud.githubusercontent.com/assets/261579/22895283/e5f59048-f1e9-11e6-898d-bef2a506d55b.png">

Should look like

<img width="374" alt="screen shot 2017-02-13 at 12 39 24" src="https://cloud.githubusercontent.com/assets/261579/22895284/e5f8d456-f1e9-11e6-8e5b-57b75763bd51.png">

cc @m4rc1e @kalapi

**Comment by thlinard** [comment]
The f_f_l has a bad glyph (a ffi ligature).

**Comment by davelab6** [comment]
Thanks for the correction :)

**Comment by thlinard** [comment]
You're welcome. But it's a `ffl` ligature (the `ffl` ligature is substituted by a `ffi` glyph – I'm not sure I'm very clear! 😆)

**Comment by davelab6** [comment]
Thanks for the correction to the correction ;)
