### ISSUE TITLE
Update Tier 2 Noto Fonts (summary)

### ISSUE THREAD

**Issue by simoncozens** [google/fonts#6540]
The main bug fixing focus of Noto in Q3 is Tier 2 fonts. There will be other development as well, but I'll open separate issues for those.

- [ ] Noto Sans Adlam
	- [x] Development
	- [ ] QA
	- [ ] Release
- [ ] Noto Sans Balinese
	- [ ] Development
	- [ ] QA
	- [ ] Release
- [ ] Noto Serif Balinese
	- [ ] Development
	- [ ] QA
	- [ ] Release
- [ ] Noto Sans Georgian
	- [x] Development
	- [ ] QA
	- [ ] Release
- [ ] Noto Sans Khmer
	- [x] Development
	- [ ] QA
	- [ ] Release
- [ ] Noto Serif Khmer
	- [x] Development
	- [ ] QA
	- [ ] Release
- [x] ~Noto Sans Lisu~ (No updates required)
- [x] ~Noto Sans Myanmar~ (Redraw required)
- [x] ~Noto Serif Myanmar~ (Redraw required)
- [x] Noto Sans Thai
	- [x] Development
	- [ ] QA
	- [ ] Release
- [x] Noto Sans Thai Looped
	- [x] Development
	- [ ] QA
	- [ ] Release
- [x] Noto Serif Thai
	- [x] Development
	- [ ] QA
	- [ ] Release

**Comment by chrissimpkins** [comment]
@simoncozens do you still need this tracker?

**Comment by simoncozens** [comment]
No, these are all done.

**Comment by chrissimpkins** [comment]
Thanks!
