### ISSUE TITLE
Add Dreamscape

### ISSUE THREAD

**Issue by AlsoShy** [google/fonts#6543]
**Has no git repo**

**Very good for the aesthetic side**

**Don't know the auther but it says "everybody can use it" it meets the req**

![dreamscape.zip](https://github.com/google/fonts/files/12089431/dreamscape.zip)
^ the file I downloaded of a fonts website

**Image:**

![06fd4fd8-295c-4eb5-8739-1f2d9c4acb61.jpg](https://github.com/google/fonts/assets/120041780/f49fe508-4958-4852-ae56-822816b73f81)

![407fbae7-93b6-456f-a69f-c169ff3671cb.jpg](https://github.com/google/fonts/assets/120041780/a97ef725-f1cf-45cc-8806-4f21dce92501)

![8b8568b8-7863-445e-aadb-afdefcf26c84.jpg](https://github.com/google/fonts/assets/120041780/e6cf87c5-20df-438a-9f71-3101670d4d83)

![26e8436f-1153-4126-8f3c-fdab7c144420.jpg](https://github.com/google/fonts/assets/120041780/d49cd243-7de6-44bf-87e1-f2d9c0e7a416)

**Comment by RosaWagner** [comment]
Hi @AlsoShy, thanks for your submission. Unfortunately the font does not match the requirements: the license is not one we accept and the font contains only a hundred of glyphs when our minimum language coverage requires around 340. Therefore we won't be able to onboard it.

If you are interested in submitting more font to Google Fonts, this documentation should help you to understand the expectations :) https://googlefonts.github.io/gf-guide/onboarding.html
