### ISSUE TITLE
Issue with displaying the Piazzolla font on its specimen page 

### ISSUE THREAD

**Issue by MariannaPaszkowska** [google/fonts#6545]
**Describe the issue**
On the Piazzolla font specimen page, all weights display as Thin weights in the weights presentation section (see Screenshots below).

**To Reproduce**
I noticed this in the mobile version of Safari on iPhone. I cannot reproduce this on desktop browsers. 

**Expected behavior**

**Additional context**
https://fonts.google.com/specimen/Piazzolla 

**Screenshots**

![1](https://github.com/google/fonts/assets/22956348/807b74b3-ec5e-4f02-9458-71ffb83c252a)

The issue is not occurring in the longer text section:

![1](https://github.com/google/fonts/assets/22956348/b89d88ab-c388-463f-98b2-0b437ff1d4c5)

**Comment by chrissimpkins** [comment]
The front end team will look into this. Thanks for reporting it Marianna!

**Comment by nathan-williams** [comment]
Thanks again for filing this issue, @MariannaPaszkowska. The team hasn't been able to reproduce the issue, so I'm hopeful that it's resolved on your end, as well. Please let us know if that is not the case!
