### ISSUE TITLE
Torus Pro Regular

### ISSUE THREAD

**Issue by Saighedd** [google/fonts#6555]
**Font Project Git Repo URL:**
https://www.myfonts.com/collections/torus-pro-font-monotype-imaging?tab=familyPackages

**Super short description of the Font Family:**
Torus Pro is a rounded monoline typeface. As its name suggests, this is a more professional version of my original Torus family released in 2017. Each glyph has been scrutinised and redrawn where necessary. In addition, there are now italics, small caps, old style figures, and numerous other improvements.

**Requirements:**

Google Fonts will publish only fonts that match its requirements. Please familiarize yourself with the complete documentation in the [Google Fonts Guide](https://googlefonts.github.io/gf-guide/) (GF-Guide) and ensure your font project complies with them before submitting the font family. You can also use the [Google Fonts Project Template](https://github.com/googlefonts/googlefonts-project-template), which will help you create a repository that follows the needed structure and includes build requirements.

By filling this issue, you can confirm the project meets the  requirements (by ticking the cases or putting x between the square brackets in text mode):

- [ ] I read, agree, and comply with the full [contributing requirements](https://googlefonts.github.io/gf-guide/index#pre-production-getting-your-fonts-ready-for-gf)
- [ ] The entire font project is licensed under the [OFL](https://scripts.sil.org/cms/scripts/page.php?site_id=nrsi&id=OFL)
- [ ] There is no "Reserved Font Name" mention in the OFL license
- [ ] Family name is unique according to [namecheck.fontdata.com](https://namecheck.fontdata.com/)
- [ ] The font supports at least [GF Latin Core glyphset](https://github.com/googlefonts/glyphsets/tree/main/GF_glyphsets/Latin/)
- [ ] The repository respect the [upstream repo structure](https://googlefonts.github.io/gf-guide/upstream.html)
- [ ] The source files are available in the repository
- [ ] I am the author of the font, or the author agreed to this submission
- [ ] I will maintain the repository and participate in the onboarding process (addressing, solving, and responding to issues, merging pull requests, etc)

**Image:**

Attach here a pic or a screenshot of the font. One image is enough, it can be a few letters, to give a quick overview.

**Comment by RosaWagner** [comment]
Hi @Saighedd, thanks for your submission. This is a commercial font distributed by Monotype therefore Google Fonts can't distribute it.
