### ISSUE TITLE
Full List of Google Fonts

### ISSUE THREAD

**Issue by Cr8zyIvan** [google/fonts#6556]
#This issue also works for requesting features. 

**Describe the issue**
Is there a Full List of all the Google Fonts? In text form, that can be copy-pasted easily. I've downloaded the full repository, and I can see that each folder corresponds to a specific Font (\Fonts GitHub\ofl). The full "correct" name of each Font seems to be in each ofl file of each folder.

Is there a txt file, or a spreadsheet that is easily accessible?

Thanks, cheers!

**To Reproduce**
N/A

**Expected behavior**
N/A

**Additional context**
N/A

**Screenshots**
N/A

**Comment by kenmcd** [comment]
@RosaWagner 
> A quick prompt in chatGPT can give you a python script to easily extract that data and output a txt file.

Would you please share that script?
In my quest to find how to process `METADATA.pb` files I found this thread.
After some searching I have finally determined that a `.pb` is a ProtoBuf file - now I need to understand using that.
I did also go thru the `gftools` files to see how it works, but they are a bit advanced for me (a python beginner).
Your script would give me a head start on how it works.
Thank you!

p.s. If you can please also include what request text you gave to ChatGPT to get the script.
In my quest for how to do this with Python I did come across some ChatGPT tutorials, but no examples with this sort of request.

But just the script would be fantastic.
That would get me headed in the right direction.
Thanks.
