### ISSUE TITLE
Issue on font "Black Han Sans"

### ISSUE THREAD

**Issue by 1751127** [google/fonts#6559]
Specify the font name in title with a short description of the bug. 
Please report any issue related to Noto fonts [here](https://notofonts.github.io/reporter.html).
Report any issue with Google Icon/Symbols [here](https://github.com/google/material-design-icons)

**Describe the bug**
When using the font "Black Hansans", the letter "몇" is displayed as "몋".

**To Reproduce**
1. Download the font from the page below.(This font file was created on September 22, 2022 at 2:27:10 PM.)
https://fonts.google.com/specimen/Black+Han+Sans
2. Install the font and type "몇".
3. The screen displays "몋".

**Expected behavior**
I think the font is mapped incorrectly in the font file.

**Screenshots**
<img width="663" alt="image" src="https://github.com/google/fonts/assets/140520532/d2fc9b53-18e0-4a48-b213-fb5bcf45601d">
<img width="1185" alt="image" src="https://github.com/google/fonts/assets/140520532/07015e72-43f7-4b3f-a694-114df6617297">

**Additional context**
The letter is used frequently, so the problem may have already been recognized. However, the download page still lists the wrong version.

**Comment by RosaWagner** [comment]
Hi @1751127, thanks for your report. Unfortunately we don't have any technician available at the moment to fix a korean script. It would help to report that issue directly to the designer in their repository: https://github.com/zesstype/Black-Han-Sans. With a little bit of luck, they would be faster than us to fix.
