### ISSUE TITLE
Update Noto Emoji BW for Unicode 15.1 release

### ISSUE THREAD

**Issue by chrissimpkins** [google/fonts#6578]
The Noto Emoji BW glyphs will be updated to address changes in the Unicode 15.1 release.

**Comment by chrissimpkins** [comment]
Designs are complete and the pipeline push is in progress

**Comment by bsoap-cat** [comment]
![image](https://github.com/google/fonts/assets/127647009/10e2b982-9d73-4c1b-b26f-55d357fdb4c9)

**Comment by bsoap-cat** [comment]
The colored version still isn't out yet, but it'll release eventually

**Comment by bsoap-cat** [comment]
The fonts were made today at 2:07 AM PDT
![image](https://github.com/google/fonts/assets/127647009/3677c421-40be-4d56-8372-1f8b4fc86362)

**Comment by bsoap-cat** [comment]
The font seems to have been downgraded to NCE 15.0. I'm not sure why, but it's frustrating. 
![image](https://github.com/google/fonts/assets/127647009/afec7e60-179d-4712-9f0d-ba2826d927ff)

**Comment by bsoap-cat** [comment]
![image](https://github.com/google/fonts/assets/127647009/11c38c12-fb0c-4ed1-b736-3a93efdd9dc9)
