### ISSUE TITLE
Add Gabarito

### ISSUE THREAD

**Issue by harbortype** [google/fonts#6583]
**Font Project Git Repo URL:**

https://github.com/naipefoundry/gabarito

**Super short description of the Font Family:**

Gabarito is a light-hearted geometric sans typeface with 6 weights ranging from Regular to Black originally designed for an online learning platform in Brazil.

**Requirements:**

Google Fonts will publish only fonts that match its requirements. Please familiarize yourself with the complete documentation in the [Google Fonts Guide](https://googlefonts.github.io/gf-guide/) (GF-Guide) and ensure your font project complies with them before submitting the font family. You can also use the [Google Fonts Project Template](https://github.com/googlefonts/googlefonts-project-template), which will help you create a repository that follows the needed structure and includes build requirements.

By filling this issue, you can confirm the project meets the  requirements (by ticking the cases or putting x between the square brackets in text mode):

- [x] I read, agree, and comply with the full [contributing requirements](https://googlefonts.github.io/gf-guide/index#pre-production-getting-your-fonts-ready-for-gf)
- [x] The entire font project is licensed under the [OFL](https://scripts.sil.org/cms/scripts/page.php?site_id=nrsi&id=OFL)
- [x] There is no "Reserved Font Name" mention in the OFL license
- [x] Family name is unique according to [namecheck.fontdata.com](https://namecheck.fontdata.com/)
- [x] The font supports at least [GF Latin Core glyphset](https://github.com/googlefonts/glyphsets/tree/main/GF_glyphsets/Latin/)
- [x] The repository respect the [upstream repo structure](https://googlefonts.github.io/gf-guide/upstream.html)
- [x] The source files are available in the repository
- [x] I am the author of the font, or the author agreed to this submission
- [x] I will maintain the repository and participate in the onboarding process (addressing, solving, and responding to issues, merging pull requests, etc)

**Image:**

Attach here a pic or a screenshot of the font. One image is enough, it can be a few letters, to give a quick overview.

![Image4](https://github.com/google/fonts/assets/10968309/d6388eef-818c-4477-a739-dd00c02fbc1b)

---

Font Bakery tests are currently errored out because https://namecheck.fontdata.com is down. It should pass when it comes back online.

Please let me know if there’s anything else I need to adjust.

Cheers!

**Comment by eliheuer** [comment]
Thanks! I just looked at the source file and this looks pretty easy to work with, my only nitpick at this point is the lack of a separate set of `.case` marks for uppercase glyphs. See the documentation on that subject, but this might not be need for all typefaces depending on the design: https://googlefonts.github.io/gf-guide/diacritics.html 

This is now in the [Submissions to review](https://github.com/google/fonts/milestone/25) queue.

**Comment by davelab6** [comment]
@harbortype this is excellent work! I am so happy to see this submission :) We will be in touch

**Comment by naipefoundry** [comment]
Amazing news Dave, thanks for your kind words! And thanks @harbortype for the stellar work helping us make this commons-ready

**Comment by harbortype** [comment]
@davelab6 I’m glad to hear Gabarito was approved! It is all work of @naipefoundry, I’m just here to help them in this process :)
