### ISSUE TITLE
Update Ubuntu

### ISSUE THREAD

**Issue by djrrb** [google/fonts#6592]
**Font Project Git Repo URL:** http://github.com/canonical/Ubuntu-fonts/issues

**Current version:** 0.831

**New available version:** 1.001

**Super short description of the upgrade:**

* Variable Weight (wght) and Width (wdth) axes
* Regular (400) weight made lighter, and other weights shifted
* Condensed variants added for all Proportional styles
* Small caps added for upright Proportional styles
* Oldstyle figures added
* Monospace rescaled to match proportional fonts
* Monospace Thin added (upright only)
* Vertical metrics reset to meet with Fontbakery standards

**Please note this version is a breaking change from the Ubuntu fonts on Google Fonts, with rearranged weight names and updated vertical metrics.**

**Pull request**: https://github.com/google/fonts/pull/6589

**Bugs reported in this repo which this upgrade would fix:** None to my knowledge

**Comment by djrrb** [comment]
Please also note that this variable font now covers the separately-listed [“Ubuntu Condensed” family on Google Fonts](https://fonts.google.com/specimen/Ubuntu+Condensed?query=ubuntu+condensed). [Here is a pull request](https://github.com/google/fonts/pull/6591) that removes this possibly-redundant listing.

**Comment by thlinard** [comment]
I don't see anything about this in the changelog, but I believe `subsets: "vietnamese"` could be added with this new version. Same for Ubuntu Mono (#6593).

**Comment by davelab6** [comment]
We will publish this as a new family to prevent disrupting users of the decade+ old design. 

@thlinard The Vietnamese will be available in that new family automatically thanks to the gftools packager auto detection.
