### ISSUE TITLE
Font WorkSans difference on lettter g italic and regular

### ISSUE THREAD

**Issue by alexandrefett** [google/fonts#6595]
**Describe the bug**
Font WorkSans, the letter 'g' is different in italics and regular

**To Reproduce**
Check https://fonts.google.com/specimen/Work+Sans

**Expected behavior**
In both italic and regular styles the letter 'g' should be similar

**Screenshots** 
![Captura de Tela 2023-08-03 às 16 41 52](https://github.com/google/fonts/assets/20704785/91600eb8-8b75-4252-add5-9aac55a8366f)
your problem.

**Additional context**

**Comment by Cogli** [comment]
@alexandrefett If you wish to use the same single-storey g, you can activate the stylistic set 1 feature in upright styles!
