### ISSUE TITLE
Glyph Sets CLDR compatibility

### ISSUE THREAD

**Issue by graphicore** [google/fonts#660]
We have code that matches language support as defined in the CLDR to other char-sets, be it a font or a Namelist defined in tools/encodings.

For some characters I used a "lax" list, characters on this list are treated as optional. That means, they can not be in the glyph set in that is examined but we still claim that the language is supported.

This is of course a rather bad idea, because it undermines the authority of the CLDR, which is probably much more carefully designed than the lax list.

The current lax-list which yields in good language compatibility is:

```
0x2010 ‐ HYPHEN
0x2032 ′ PRIME
0x2033 ″ DOUBLE PRIME
0x27E8 ⟨ MATHEMATICAL LEFT ANGLE BRACKET
0x27E9 ⟩ MATHEMATICAL RIGHT ANGLE BRACKET
0x2052 ⁒ COMMERCIAL MINUS SIGN
0x2020 † DAGGER
0x2021 ‡ DOUBLE DAGGER
```

Additionally @alexeiva mentioned in a [discussion](https://groups.google.com/d/msg/googlefonts-discuss/x2oRYyP4gMQ/Ca0eFk9NDwAJ) with a similar topic

> I think we should move these glyphs from Pro to Plus for compatibility with CLDR:
>```
> 0x2010  ‐ hyphentwo
> 0x02B9  ʹ primemod
> 0x02BA  ″ doubleprimemod
> ```

It's interesting that besides the hyphen two, which is in my lax list as well we good the "modifier" versions of prime and double prime in the latter list and the "regular" versions in the former one.

I personally think we should move all of the chars above to the Plus glyph set. That would end the ambiguity and put our claims of languages supported on a solid ground. 

From the mail of @alexeiva again:

> For previously released fonts I suggest making exceptions for these mentioned glyphs. 
>
> So, a double-edged sword solution for the compatibility issue. 

Double standards are fine with me :-D I mean, seriously, we can still use the lax list explicitly depending on the font/context. I think it's more important to just get this right for the future. Then in later iterations we can add these chars to the fonts.

**Comment by alexeiva** [comment]
Fully agree, I will add all this to the Latin Plus 2017 glyphs set, which will be the standard for new projects. Eventually we can populate existing Plus fonts with these glyphs. Considering their number the lax list is essential for the time.

**Comment by graphicore** [comment]
When you do a "Latin Plus 2017" will it be in `tools/encodings/GF 2017 Glyph Sets`? Maybe it's a good situation to think about how to structure the encodings directory overall?

**Comment by graphicore** [comment]
At least we should document the concept of the directory structure and how it is meant to evolve. That'll make it much easier to write code for it.

**Comment by alexeiva** [comment]
> "Latin Plus 2017" will it be in tools/encodings/GF 2017 Glyph Sets?

I think updating the 2016 folder will be a better idea. There is always git
diff to track down the evolution of glyph sets. Moving the CLDR glyphs from
Pro to Plus will be a noticable change that should be documented in a log.

**Comment by davelab6** [comment]
Let's remove 2016 from the folder name then 😂

**Comment by graphicore** [comment]
> Let's remove 2016 from the folder name then :joy:

Totally!

**Comment by graphicore** [comment]
@alexeiva given that we have a `GF-latin-core_unique-glyphs.nam` with my PR #685, I wonder if we should move some of the glyphs above from latin-plus to latin-core.

**Comment by graphicore** [comment]
closing, because of #685
