### ISSUE TITLE
Add Pitagon Sans Mono

### ISSUE THREAD

**Issue by travistran1989** [google/fonts#6606]
**Font Project Git Repo URL:**
https://github.com/ThePitagon/pitagon-sans-mono

**Super short description of the Font Family:**
Pitagon Sans Mono is a monospaced, unmodulated (“sans serif”) design suitable for programming code and other uses where
a fixed-width font is needed.

**Requirements:**

I understand that Google Fonts will publish only fonts that matches its requirements, and I can confirm the project meets them (by ticking the cases, or putting x between the square brackets in text mode):

- [x] I read, agree, and comply with the full [contributing requirements](https://googlefonts.github.io/gf-guide/index#pre-production-getting-your-fonts-ready-for-gf)
- [x] The entire font project is licensed under the [OFL](https://scripts.sil.org/cms/scripts/page.php?site_id=nrsi&id=OFL)
- [x] There is no "Reserved Font Name" mention in the OFL license
- [x] Family name is unique according to [namecheck.fontdata.com](https://namecheck.fontdata.com/)
- [x] The font supports at least [GF Latin Core glyphset](https://github.com/googlefonts/glyphsets/tree/main/GF_glyphsets/Latin/)
- [x] The repository respect the [upstream repo structure](https://googlefonts.github.io/gf-guide/upstream.html)
- [x] The source files are available in the repository
- [x] I am the author of the font, or the author agreed to this submission
- [x] I will maintain the repository and participate in the onboarding process (addressing, solving, and responding to issues, merging pull requests, etc)

**Image:**

![](https://github.com/ThePitagon/pitagon-sans-mono/blob/main/documentation%2Fimage1.png)

**Comment by eliheuer** [comment]
Thanks! I added this to the "submissions to review" queue.

Looking at the source files I noticed some quality issues like this: 

<img width="1259" alt="Screenshot 2023-08-08 at 12 37 12 PM" src="https://github.com/google/fonts/assets/5162664/a6b179ea-0fc0-47a9-88dc-fdb4d3ea0b33">

And some of these overlaps might be too complex and need clean up, see this part of the Google Fonts guide: https://googlefonts.github.io/gf-guide/outlines.html#donts

<img width="1229" alt="Screenshot 2023-08-08 at 12 38 40 PM" src="https://github.com/google/fonts/assets/5162664/c6be44f3-7ed6-4e73-b2b5-9964fce9d882">

**Comment by Cogli** [comment]
Is this a rounded corner version of [JetBrains Mono](https://www.jetbrains.com/lp/mono/)?

**Comment by eliheuer** [comment]
@Cogli It might be? thanks I'll look. In order for it to be included it needs to have some feature or quality that isn't already available in the catalog.

Sometimes with fonts that are made specifically for business like this one is, they turn out to just be low effort forks of existing OFL fonts that don't really add anything new to the OFL ecosystem and are not actively maintained projects with users beyond the maker. I'm not saying that is what is going on here, but it was one of the first concerns that I thought of when I saw this issue.

**Comment by eliheuer** [comment]
Looking at the source files again I see that only some of the characters are rounded, and some are not. The drawing styles between the various glyphs are also inconsistent.
<img width="1469" alt="Screenshot 2023-08-08 at 2 49 50 PM" src="https://github.com/google/fonts/assets/5162664/06208a5d-4e47-4366-9ccb-37294c6d92b0">

**Comment by eliheuer** [comment]
I compared this to the Jet Brains Mono source files, and it looks like yes, this is a rounded fork of Jet Brains Mono.

<img width="1920" alt="Screenshot 2023-08-08 at 3 00 19 PM" src="https://github.com/google/fonts/assets/5162664/86c32b92-d603-4783-90f6-2f9ced56bf0c">

Two things make me feel like this should not be onboarded.

1. The repo copy is not honest about this being a Jet Brains Mono fork, and cites other fonts as inspiration
2. The rounding is inconsistent and the outline quality is low
<img width="882" alt="Screenshot 2023-08-08 at 3 01 45 PM" src="https://github.com/google/fonts/assets/5162664/01c713c8-db69-4ad8-ac7e-cca87ac14791">

I'm going to suggest that this is not considered for onboarding to Google Fonts, but I want to give @travistran1989 a chance to comment before I close the issue. Thanks @Cogli !

**Comment by Cogli** [comment]
![immagine](https://github.com/google/fonts/assets/55837580/21c5d961-4882-4be6-b12b-133418096e95)
even the readme file is unoriginal.

**Comment by travistran1989** [comment]
I understand the issue and we will improve our works. Thank you @eliheuer , @Cogli !

**Comment by eliheuer** [comment]
Thanks @travistran1989! If you want to update the description and create more consistent rounded outlines, this might still be a good fork of Jet Brains Mono. Just please be clear about the project's provenance in the main README.

**Comment by travistran1989** [comment]
@eliheuer I will create another issue when our team improves the work to match with GF guidelines. Also I will update the README about inspiration, as we did in other fonts. It's my mistake when gathering information from our team members. See you soon ^^

**Comment by eliheuer** [comment]
Thanks @travistran1989! There is no need to make a new issue though, you can address the issues and reopen this one.
