### ISSUE TITLE
Add Radio-Canada Display

### ISSUE THREAD

**Issue by JulieDesilets** [google/fonts#6610]
**Font Project Git Repo URL:**
Radio-Canada Display

**Super short description of the Font Family:**
Addition of Radio-Canada Display to the Radio-Canada Family font, mostly used for titling purposes is offered in Medium, Medium Italic, Bold and Bold Italic. 

Addition of this line under «About» section, after the words «Indigenous languages»: , and Etienne Aubert Bonn (Coppers and Brasses) completed the family by creating the title font Display.

**Requirements:**

Google Fonts will publish only fonts that match its requirements. Please familiarize yourself with the complete documentation in the [Google Fonts Guide](https://googlefonts.github.io/gf-guide/) (GF-Guide) and ensure your font project complies with them before submitting the font family. You can also use the [Google Fonts Project Template](https://github.com/googlefonts/googlefonts-project-template), which will help you create a repository that follows the needed structure and includes build requirements.

By filling this issue, you can confirm the project meets the  requirements (by ticking the cases or putting x between the square brackets in text mode):

- [x] I read, agree, and comply with the full [contributing requirements](https://googlefonts.github.io/gf-guide/index#pre-production-getting-your-fonts-ready-for-gf)
- [x] The entire font project is licensed under the [OFL](https://scripts.sil.org/cms/scripts/page.php?site_id=nrsi&id=OFL)
- [x] There is no "Reserved Font Name" mention in the OFL license
- [x] Family name is unique according to [namecheck.fontdata.com](https://namecheck.fontdata.com/)
- [x] The font supports at least [GF Latin Core glyphset](https://github.com/googlefonts/glyphsets/tree/main/GF_glyphsets/Latin/)
- [x] The repository respect the [upstream repo structure](https://googlefonts.github.io/gf-guide/upstream.html)
- [x] The source files are available in the repository
- [x] I am the author of the font, or the author agreed to this submission
- [x] I will maintain the repository and participate in the onboarding process (addressing, solving, and responding to issues, merging pull requests, etc)

**Image:**

Attach here a pic or a screenshot of the font. One image is enough, it can be a few letters, to give a quick overview.
[RadioCanada_Display.zip](https://github.com/google/fonts/files/12303983/RadioCanada_Display.zip)

**Comment by eliheuer** [comment]
Thanks! Should this have a new Git repository similar to https://github.com/cbcrc/radiocanadafonts ?

Something like https://github.com/cbcrc/radiocanadadisplay for example.

**Comment by JulieDesilets** [comment]
Hi @eliheuer the second link produces a page 404 ;-/ sorry if I am not very familiar to Git repository ;)

**Comment by eliheuer** [comment]
We need to figure out where the files should live to move forward, they could be added to the Radio-Canada repository here: https://github.com/cbcrc/radiocanadafonts or a new repository could be made specifically for Radio-Canada Display. 

I don't see any source files in the [RadioCanada_Display.zip](https://github.com/google/fonts/files/12303983/RadioCanada_Display.zip), and source file will be needed.

**Comment by JulieDesilets** [comment]
Ho! I undestand. Better to include the specimen into the RadioCanada, instead of creating RadioCandaDisplay. Strange for the zip file, you can upload here[https://drive.google.com/file/d/1sDx9wuSgSr0zp-ZC81r3s9DeCJhEPQx9/view](url)

**Comment by JulieDesilets** [comment]
[https://drive.google.com/file/d/1sDx9wuSgSr0zp-ZC81r3s9DeCJhEPQx9/view?usp=sharing](url)
[Radio-Canada Display.zip](https://github.com/google/fonts/files/12307182/Radio-Canada.Display.zip)

**Comment by JulieDesilets** [comment]
Hello @eliheuer! Can only find the variable version on the site, are the OTF not offered... I do remember we could download the Regular family and the Condensed family https://fonts.google.com/specimen/Radio+Canada?query=radio+canada+

**Comment by eliheuer** [comment]
@JulieDesilets The downloaded `zip` file should have a folder called static with all the non-variable fonts included. They are in the `ttf` format, but that is almost exactly the same as `otf`, with very minor technical differences.

<img width="1130" alt="Screenshot 2023-08-10 at 1 39 57 PM" src="https://github.com/google/fonts/assets/5162664/b28f8b07-73c9-478a-8263-e92a9168fcd8">

**Comment by eliheuer** [comment]
Looking at the files from the `zip` provided above, the display style is very different from the regular Radaio-Canada typeface. That is fine, just something I'm noticing and making a note of. It looks like it was developed by the same studio (Coppers & Brass) though. I couldn't find any information about this style online.

<img width="1774" alt="Screenshot 2023-08-10 at 1 36 45 PM" src="https://github.com/google/fonts/assets/5162664/68f4b559-6224-4508-9d0f-2a0112f0d8fd">

**Comment by JulieDesilets** [comment]
Yes @eliheuer it is indeed in the static file upon download, but no mention of the Condensed on the specimen page. Anyway way to show it as much as the Regular family (shown in variable) and the Display ?

Yes the Display is quite different but respects a few styling patterns of the RC Regular.

Coppers & Brasses didn't mention it specifically on their website yet, but it is the same foundry and typeface designer who worked on this new family.

**Comment by eliheuer** [comment]
Hi @JulieDesilets I still do not have source files from you in `.ufo` or `.glyphs` format. Do source files exist for this project and do you have access to them?

I still do not have access to this Google Drive, but I requested it again today: https://drive.google.com/file/d/1sDx9wuSgSr0zp-ZC81r3s9DeCJhEPQx9/view?usp=sharing

This zip file only contains `.otf` fonts with their diacritics decomposed: https://github.com/google/fonts/files/12307182/Radio-Canada.Display.zip

It would be possible to try onboarding Radio Canada Display using only the `.otf` files provided in that zip file, but it would be more work and produce worse results than if the source files were available.

Also, the files from the above `.zip` file only contain a Medium - Bold weight range, is that correct? Radio-Canada ranges from light to Bold.

**Thanks, just let us know where the source files are, or if there are no source files and this can move forward.**

**Comment by JulieDesilets** [comment]
hello @eliheuer do you have any news regarding the Radio-Canada Display Font? I've send the source files on Oct 17, but adding it here: 
[RadioCanada_Display.zip](https://github.com/google/fonts/files/13419362/RadioCanada_Display.zip)

**Comment by JulieDesilets** [comment]
Thanks for the update Chris.

Dave Crossland mentionned to me that i could be in Q2, so please let me
know when you have a better view of your bandwidth.

Julie Desilets
Directrice du design, Stratégie et création
m  514 214-6546  *|*  Niveau 4S, bureau RP140
CBC/Radio-Canada
1000, av. Papineau, Montréal Qc H2K 0C2

**Comment by chrissimpkins** [comment]
@JulieDesilets quick update:

@emmamarichal will take over the onboarding here.  We have it tentatively slated in Q1.  We'll do our best to fit it in.
