### ISSUE TITLE
UpdateUpdate [Etherium]

### ISSUE THREAD

**Issue by alan-m-thomas** [google/fonts#6616]
**Font Project Git Repo URL:**

**Current version:**

**New available version:**

**Super short description of the upgrade:**
(expand style, expand glyphset, improve rendering, bug fix…)

**Bugs reported in this repo which this upgrade would fix:**
Search in the [issue tracker](https://github.com/google/fonts/issues) if there is some opened issues containing the font name.

**Comment by fitojb** [comment]
You have not provided any URLs to look at

**Comment by eliheuer** [comment]
There is zero information here and no font in the catalog called "Etherium". I'm closing this.

@alan-m-thomas Please reopen and provide more information if you want.
