### ISSUE TITLE
Add Host Grotesk

### ISSUE THREAD

**Issue by ibo-o** [google/fonts#6621]
**Font Project Git Repo URL:** https://github.com/Element-Type/HostGrotesk

**Super short description of the Font Family:**
Host Grotesk is a versatile uniwidth sans-serif typeface, offering both upright and italic variations across a range of weights. This typeface is meticulously crafted for optimal usage in user interfaces, by modifying and extending [Poppins](https://fonts.google.com/specimen/Poppins) by [Indian Type Foundry](https://www.indiantypefoundry.com/), Jonny Pinhorn.

**Requirements:**

@element-Type understands that Google Fonts will publish only fonts that matches its requirements, and I can confirm the project meets them:

By filling this issue, you can confirm the project meets the  requirements (by ticking the cases or putting x between the square brackets in text mode):

- [x] I read, agree, and comply with the full [contributing requirements](https://googlefonts.github.io/gf-guide/index#pre-production-getting-your-fonts-ready-for-gf)
- [x] The entire font project is licensed under the [OFL](https://scripts.sil.org/cms/scripts/page.php?site_id=nrsi&id=OFL)
- [x] There is no "Reserved Font Name" mention in the OFL license
- [x] Family name is unique according to [namecheck.fontdata.com](https://namecheck.fontdata.com/)
- [x] The font supports at least [GF Latin Core glyphset](https://github.com/googlefonts/glyphsets/tree/main/GF_glyphsets/Latin/)
- [x] The repository respect the [upstream repo structure](https://googlefonts.github.io/gf-guide/upstream.html)
- [x] The source files are available in the repository
- [x] I am the author of the font, or the author agreed to this submission
- [x] I will maintain the repository and participate in the onboarding process (addressing, solving, and responding to issues, merging pull requests, etc)

![HostGrotesk-Promo](https://github.com/google/fonts/assets/48119402/f88c1307-1328-423f-ae79-5f97d206657f)

**Comment by eliheuer** [comment]
Thanks! I added this to the list of projects to review for onboarding.

There are a few FontBakery fails related to `com.google.fonts/check/soft_dotted`, but that can be fixed with some custom OpenType code, in the `cmap` table if I remember correctly. I reviewed the source files and the look pretty good from a technical perspective.

**Comment by eliheuer** [comment]
Spacing and kerning could use a little work, but I'm not sure if that is a blocker for onboarding this.  

<img width="1051" alt="Screenshot 2023-08-15 at 8 55 20 PM" src="https://github.com/google/fonts/assets/5162664/bb618d00-5601-443c-92d7-b8fd2c40d7f7">

<img width="629" alt="Screenshot 2023-08-15 at 8 55 37 PM" src="https://github.com/google/fonts/assets/5162664/1deaa84c-cdf1-467b-87ac-aa1102620180">

**Comment by ibo-o** [comment]
Thank you so much @eliheuer The remaining FontBakery fails errors are all beyond my knowledge as I'm learning along the way. I'd be happy to fix them with a little bit of help. A pull request sounds great.

I agree that there are some spacing & kerning inconsistencies because of being uniwidth. We'll see how we can mitigate these issues.

**Comment by davelab6** [comment]
@ibo-o any updates? I like this project, from what I see above :)

**Comment by ibo-o** [comment]
We planned to release this version (from our website) as v1 and then release the v1.1 with improvements. We're aiming to have spacing & kerning improvements in that version.

**Comment by ibo-o** [comment]
@davelab6 Hello, version 1.001 is pushed now.

Pasting the changelog that I wrote into README.md

**9 May 2024. Version 1.001**
- Bug fixes: Some glyphs had different width accros styles and weights.
- Reworked spacing.
- Reworked kerning.
- Drawing improvements.
- Tabular numbers, currency symbols.
- Tabular math symbols. They share same width but different than numbers and currencies.
- Removed `ℓ (U+2113)` and `₨ (U+20A8)`, as they were just place holders.
- Removed `Alternative Quotes` stylistic set that consists: `/comma.ss01/quotesinglbase.ss01/quotedblbase.ss01/quotedblleft.ss01/quotedblright.ss01/quoteleft.ss01/quoteright.ss01 ` as they were redundant.

**Comment by ibo-o** [comment]
Hello @eliheuer @davelab6, Any plans to proceed with this project?

**Comment by davelab6** [comment]
@ibo-o yes! I expect we will process it in the next 3 months :)

**Comment by vv-monsalve** [comment]
@ibo-o I've opened a PR with initial production fixes and reported some additional required fixes in the issue tracker.

**Comment by ibo-o** [comment]
Hey @vv-monsalve  Thank you for handling the project! I merged the pull request and then pushed the required fixes. All the issues should be resolved now. I'll close all the open issues in the tracker as soon as you confirm.

**Comment by vv-monsalve** [comment]
Hi @ibo-o, I'll pull the latest file and go another revision round. Will report back in the repo.

**Comment by vv-monsalve** [comment]
PR to GF done

**Comment by vv-monsalve** [comment]
Hi @ibo-o the font is now live :)

**Comment by ibo-o** [comment]
Thank you so much for your assitance @vv-monsalve. Also thanks @emmamarichal and the whole google fonts team.
