### ISSUE TITLE
Inter's font-feature-settings doesnt know "salt" flag

### ISSUE THREAD

**Issue by rejas** [google/fonts#6623]
I have tried adding the stylistic alternatives to the Inter font delivered but they don't have any effect (for example on the https://fonts.google.com/specimen/Inter page):

    `font-feature-settings: "salt" 1;`

Using the woff2-font file from the official Inter homepage does work with the stylistic alternatives  turned on.

**Comment by kenmcd** [comment]
Google Fonts online fonts do not include many OpenType features.
For example they do not include stylistic sets or salt.

To get those features you would need to host the fonts yourself,
or use the free Inter CDN.
See here: https://github.com/rsms/inter#using--installing-inter

**Comment by rejas** [comment]
Thx for the clarification @kenmcd 
Do you know if that is something that can be changed by opening a PR with a correct font file?
