### ISSUE TITLE
monotype corsiva [Font Name]

### ISSUE THREAD

**Issue by parneetkaur7729** [google/fonts#6632]
**Font Project Git Repo URL:**. -- https://www.freebestfonts.com/monotype-corsiva-font

**Super short description of the Font Family:** -- it is a new font available in italic and bold  and these days it is used the most

**Requirements:**
I request you provide italic type for this font.  
Kindly provide this new font to google fonts for the further use of it in the web pages.

![Screenshot 2023-08-18 at 10 38 07 PM](https://github.com/google/fonts/assets/109802307/d5e490f4-7bcd-4e5c-aa60-65e81c21e71a)

**Comment by lxgw** [comment]
This fonts is a commercially copyrighted font instead of an open-source font.
