### ISSUE TITLE
Noto_Serif_Devangari

### ISSUE THREAD

**Issue by DannyGS23** [google/fonts#6638]
I am very happy with the Noto Serif Devanagari Fonts. But when I was using them, I noticed that 2 combined letter are rendering correctly in the Regular Type Face but in all the other Type Faces, the rendering although is correct, but is not used much these days. (I have attached a pdf file showing the issues.)

Can I get permission to modify theses fonts and use them for my work. I am sure it will be rectified after seeing my post, but I am not sure how long I will have to wait.

Kindly give me the permission to modify these fonts. If permission is given to me, I can modify only the static fonts and upload them here. I am not exposed to working with the variable font.

Awaiting your reply.

Thanks and Regards,

Daniel Shekeran
[Noto Serif Font Issues.pdf](https://github.com/google/fonts/files/12428259/Noto.Serif.Font.Issues.pdf)

**Comment by eliheuer** [comment]
@DannyGS23 Thanks for the bug report! This image is very helpful! <img width="573" alt="Screenshot 2023-08-24 at 7 23 28 AM" src="https://github.com/google/fonts/assets/5162664/31198c7b-5849-4029-857f-95bd73e00884">

@simoncozens might be able to help fix this, but would probably need to consult with a Devanagari expert to make sure there isn't a good reason for this.

The [OFL font license](https://en.wikipedia.org/wiki/SIL_Open_Font_License) already gives you permission to modify any font using the OFL license, so you are free to modify any of the Noto fonts without asking permission first.

**Comment by DannyGS23** [comment]
Dear Sir,

Thanks a lot. I am so happy that I can modify the fonts and use them.

With regards to your comment:
@simoncozens might be able to help fix this, but would probably need to consult with a Devanagari expert to make sure there isn't a good reason for this.

The Noto Regular type face renders the character correctly. The other rendering also is correct but this rendering was used and taught some decades ago.

Thanks again.

Daniel Shekeran

**Comment by simoncozens** [comment]
I can't replicate this, in that the latest Noto Serif Devanagari Regular *also* uses the precomposed forms:

```
$ shape NotoSerifDevanagari-Regular.ttf 'श्च श्व'
[uni0936094D091A=0+686|space=3+260|uni0936094D0935=4+686]
```

![shape](https://github.com/google/fonts/assets/106728/3abc495f-6cc5-47aa-87d7-f8c5af7464f4)

(Noto Sans Devanagari also does the same.)

In general people seem to *want* extra ligature forms, rather than have them removed. (See e.g. https://github.com/notofonts/devanagari/issues/7) If you think there is a bug here, please open it at [the notofonts/devangari repository](https://github.com/notofonts/devanagari/issues/new) rather than in google/fonts. But I am not convinced that this is wrong.

**Comment by tiroj** [comment]
The horizontal conjunct form
<img width="72" alt="image" src="https://github.com/google/fonts/assets/5614500/fbcace3f-7cfa-4e23-872e-c60b1ffd932d">
can be achieved by inserting a ZWJ (U+220D) formatting control character after the halant.
