### ISSUE TITLE
Update Bitter

### ISSUE THREAD

**Issue by Lorp** [google/fonts#6639]
**Describe the bug**
Bitter Regular and Bitter Italic have an issue with the .notdef glyph. In each case, the glyph has an intermediate master whose outlines are the reverse direction of the masters at the extremes. It is arguable whether variations should be allowed in a .notdef glyph at all; but if they are allowed, then the outlines should have correct path direction.

In addition, the Bitter Regular .notdef glyph at wght=900 appears to be slightly scaled up compared with wght=100.

**To Reproduce**
Load the font files into Glyphs or [Samsa](https://lorp.github.io/samsa/src/samsa-gui.html). Select the .notdef glyph. Adjust the Weight axis from min to max, and observe the "flip" as the outlines reverse direction twice.

**Expected behavior**
No change as one adjusts the Weight axis from min to max. Removing all variation data for this glyph would save data as well as avoiding this error.

**Screenshots**

https://github.com/google/fonts/assets/587440/74987a71-0b03-49d9-aaf3-7a73b685208c

https://github.com/google/fonts/assets/587440/155dd126-849c-486f-ae5e-fbcbc5aad653

**Comment by RosaWagner** [comment]
Hey @Lorp I saw you opened the same issue in the upstream repo: https://github.com/solmatas/BitterPro/issues/21, and that Sol has updated the files so I gonna change this issue to track an update. Thanks.

**Comment by yanone** [comment]
Reported by email back to author how to fix the build in the `back-to-glyphs` branch. Now waiting for updated sources.
