### ISSUE TITLE
REM font does not show up on Google workspace

### ISSUE THREAD

**Issue by missmai27** [google/fonts#6655]
Specify the font name in title with a short description of the bug. 
Please report any issue related to Noto fonts [here](https://notofonts.github.io/reporter.html).
Report any issue with Google Icon/Symbols [here](https://github.com/google/material-design-icons)

**Describe the bug**
The REM font does not show up on Google workspace/slides without Extensis fonts. This font was specifically chosen for a client as it is a Google font, their requirement. We expected it to work in Google workspace without the sue the extension.

**To Reproduce**
The Google products do not find this specific font

**Expected behavior**
I need to use it as its a client font
**Screenshots**

**Additional context**
Add any other context about the problem here (OS version, browser, printer…)

**Comment by RosaWagner** [comment]
@missmai27 thanks for your report, REM was added to the catalog recently, it takes few weeks before a new family is also available in Workspace.
