### ISSUE TITLE
Elsie Swash Caps does not render the letters "fi" and it renders a weird "1" character instead

### ISSUE THREAD

**Issue by avernalismart** [google/fonts#6657]
If you type the letter **f** followed by the letter **i** it renders a weird **1** character instead of the 2 expected ones.
Happens in lowercase only and with Regular 400

To reproduce go to:
https://fonts.google.com/specimen/Elsie+Swash+Caps?preview.text=FI%20f%20-%20i%20-%20fi&preview.text_type=custom
you will see how typing "fi" does not show the 2 letters.

<img width="1155" alt="image" src="https://github.com/google/fonts/assets/128107597/366b6c60-a67d-4d87-b863-74184dc4b844">

Tested from a mac using google chrome and edge browsers. Could not test from another OS yet.

**Comment by kenmcd** [comment]
Actually that "weird 1" is the glyph for a dotless i.
It does the same thing with `fj` - it becomes a dotless j glyph.
Also happens in the Elsie-Regular.ttf.
Both the Black fonts do no have this odd ligature.
 
The error is in the ligature code, and the glyphs are wrong.
```
    sub f i by f_i.liga;
    sub f j by f_j.liga;
```
And
`f_i.liga` is a dotless i glyph.
`f_j.liga` is a dotless j glyph.
So there actually are no `fi` or `fj` ligatures (glyphs are missing).

The Google Fonts folks will need to fix this.
It is the same in versions of the fonts found out on free fonts sites.

If you do not need web fonts you could just delete the ligature code.

**Comment by RosaWagner** [comment]
It's an old font, and I can't find the sources so we may as well hotfix directly the binaries to remove these ligatures.
