### ISSUE TITLE
U+218A and U+218B don't act the same like other Unicode characters (Noto Sans Symbols)

### ISSUE THREAD

**Issue by bsoap-cat** [google/fonts#6681]
When U+218A "Turned Digit Two" and U+218A "Turned Digit Three" characters are next to other Unicode characters in weights except for the thinnest weight, the digits get taller and aren't as thick as the others depending on how heavy the font is.

An example for reproducing this issue would be typing/pasting "0123456789↊↋" into
[the Noto Sans Symbols page on Google Fonts](https://fonts.google.com/noto/specimen/Noto+Sans+Symbols/tester) and moving the slider to different weights. The aforementioned digits get taller and don't have the same weight as the other digits.

The dek and eleven characters should act like their turned counterparts 2 and 3 respectively 

With lightest weight:
![image](https://github.com/google/fonts/assets/127647009/08112075-c31d-4c66-9d10-241ef32e11b5)

With normal weight:
![image](https://github.com/google/fonts/assets/127647009/58ccc910-58b5-47c9-a011-4599a5506848)

With heaviest weight:
![image](https://github.com/google/fonts/assets/127647009/2ab4417b-a6fa-46f5-a3d6-2e3df8f82d45)

**Comment by simoncozens** [comment]
Thanks; this is an issue with the Noto Symbols font so I have opened it over at https://github.com/notofonts/symbols/issues/74. We'll track (and work on) it there.

**Comment by bsoap-cat** [comment]
You're welcome! I'm looking forward to seeing the fixed digits soon.
