### ISSUE TITLE
Cannot add font Alexandria using FontRequest API

### ISSUE THREAD

**Issue by lklong1551019** [google/fonts#6683]
**Describe the bug**
Cannot add font Alexandria using FontRequest API. It shows reason font not found
<img width="720" alt="image" src="https://github.com/google/fonts/assets/32784650/8d972fcf-52af-4b0f-b940-5aed49b75c3c">

**To Reproduce**
Just use ordinary FontRequest API with query = "name=Alexandria"

**Expected behavior**
onTypeFaceRetrieved call successfully

**Screenshots**
<img width="570" alt="image" src="https://github.com/google/fonts/assets/32784650/1c60519d-de2b-45c9-aabf-0e3963e0104c">

<img width="700" alt="image" src="https://github.com/google/fonts/assets/32784650/fc5c27af-c534-40e1-8d35-3097924454a7">

**Additional context**
I tested with some other fonts like Trirong, Work Sans, Gotu and they worked fine. Tested on android 13 devices.

**Comment by eliheuer** [comment]
Thanks! I don't have enough Android development experience to give you an answer right now, but I'm trying to find someone who does to answer this question. If all else fails I will set up a development environment and try to reproduce this.

**Comment by davelab6** [comment]
Not all fonts available in the CSS API are available in the android GMS Core API, sadly. @nyshadhr9 might be able to say more

**Comment by nyshadhr9** [comment]
I can confirm that this font is not currently available via the Android API. I'm planning to roll out an update which adds missing fonts (including Alexandria) to the Android API in the coming weeks.
