### ISSUE TITLE
Teko font is not placed on the right height inline

### ISSUE THREAD

**Issue by Atchferox** [google/fonts#6684]
**Describe the bug**
The teko font is not the same as the rest of the google fonts.

**Expected behavior**
It should be the same as the heights as the rest of the fonts. 

**Screenshots**
![Screenshot 2023-09-08 at 14 56 28](https://github.com/google/fonts/assets/93676830/f332622a-8c6e-4ebe-8c41-b6393422638b)

**Comment by eliheuer** [comment]
Thanks for the issue, but there is no guarantee that all Google Fonts will have the same vertical metrics.

Teko includes both Latin and Devanagari support, multi-script fonts sometimes have vertical metrics that make it difficult for them to align vertically, I have a codepen here showing the problem: https://codepen.io/eliheuer/pen/KKrOamg

See the vertical metrics here and note that they are non-standard: 
<img width="823" alt="Screenshot 2023-09-10 at 7 32 52 PM" src="https://github.com/google/fonts/assets/5162664/d474bdd3-0276-440f-9155-ac57cdcd6ebf">

Teko is open source software, you are free to modify the fonts to have any vertical metrics you want, here is the source: https://github.com/googlefonts/teko
