### ISSUE TITLE
Ensure soft_dotted characters lose their dot when combined with marks that replace the dot.

### ISSUE THREAD

**Issue by ThanosPoulakidas** [google/fonts#6687]
I am having this problem on the Fontbakery review
"Ensure soft_dotted characters lose their dot when combined with marks that replace the dot."

Geom https://github.com/google/fonts/issues/4874
 
Similar issue https://github.com/fonttools/fontbakery/issues/4085

**Comment by eliheuer** [comment]
This requires custom `ccmp` feature code that is not currently auto generated by glyphs, many people struggle with this.

There is a section of the Google Fonts Guide here that goes over this here: https://googlefonts.github.io/gf-guide/diacritics.html#soft-dotted-glyphs

Please make an issue on the [gf-guide issue tracker](https://github.com/googlefonts/googlefonts.github.io/issues) if the instruction are unclear and you can't figure out how to pass this check.

Good luck! This is possible to fix, but it will take some concentration and focus, don't get discouraged if it seems overwhelming at first.

**Comment by ThanosPoulakidas** [comment]
Thanks again @eliheuer! And for the link too! I think I solved it
