### ISSUE TITLE
Check license file has good copyright string

### ISSUE THREAD

**Issue by ThanosPoulakidas** [google/fonts#6688]
I am having this problem on the Fontbakery review
"Check license file has good copyright string." & "Copyright notices match canonical pattern in fonts"

Geom https://github.com/google/fonts/issues/4874

Even though I was changing the information on the OFL file and the glyphs files, the review didn't show the changes.

**Comment by eliheuer** [comment]
@ThanosPoulakidas Hello, I looked at your upstream Git repository, and the way you have the license copyright string is not formatted in a way that will pass the FontBakery QA tests.

Please read the Google Fonts Guide carefully here: https://googlefonts.github.io/gf-guide/license-file.html

And also look at other fonts in the Google Fonts catalog to the how their copyright strings are formatted.

**Comment by ThanosPoulakidas** [comment]
Thanks @eliheuer!
