### ISSUE TITLE
Update new Q3 2023 font metadata to work with the new category system

### ISSUE THREAD

**Issue by eliheuer** [google/fonts#6689]
A new version of https://fonts.google.com/ went live in Q3 2023 that has a more detailed category system.

There was a batch update to the METADATA.pb files for this:
https://github.com/google/fonts/pull/6596
https://github.com/google/fonts/pull/6604
https://github.com/google/fonts/pull/6622
https://github.com/google/fonts/pull/6625

The packager workflow needs to be updated so that new fonts are added with METADATA.pb files that conform to the new category system. I'm currently working on this here: https://github.com/googlefonts/gftools/issues/720

This issue is to track all new fonts with multiple categories that were added to Google Fonts between the batch metadata update and when gftools is finally updated to work with the new metadata system. These fonts will need to have their `METADATA.pd` files manually updated.

Fonts that need updating so far*:
- [ ] Playpen Sans: https://github.com/google/fonts/pull/6673

_*Note that fonts with only one category will not need to be updated_

**Comment by chrissimpkins** [comment]
Does this issue need to remain open?

**Comment by eliheuer** [comment]
Yes

**Comment by vv-monsalve** [comment]
Can this issue be closed now?
