### ISSUE TITLE
Add Soft Type knitting fonts projects

### ISSUE THREAD

**Issue by vv-monsalve** [google/fonts#6702]
**Font Project Git Repo URL:**
https://github.com/scfried/soft-type

__________
### **PR GF:**
- [x] Micro 5 https://github.com/google/fonts/pull/7081
- [x] Micro 5 Charted https://github.com/google/fonts/pull/7082
- [x] Jacquarda 9 Bastarda https://github.com/google/fonts/pull/7083
- [x] Jacquarda 9 Bastarda Charted https://github.com/google/fonts/pull/7084
- [x] Jacquard 12 https://github.com/google/fonts/pull/7152
- [x] Jacquard 12 Charted
- [x] Jacquard 24 
- [x] Jacquard 24 Charted
- [x] Jersey 10
- [x] Jersey 10 Charted
- [x] Jersey 15 
- [x] Jersey 15 Charted
- [ ] Jersey 20
- [ ] Jersey 20 Charted
- [ ] Jersey 25 #7386 
- [ ] Jersey 25 Charted #7536 
- [ ] Yarndings 12 https://github.com/google/fonts/pull/7215
- [ ] Yarndings 12 Charted https://github.com/google/fonts/pull/7216
- [ ] Yarndings 20 https://github.com/google/fonts/pull/7219
- [ ] Yarndings 20 Charted https://github.com/google/fonts/pull/7220
__________

### **ISSUES**

**_Micro_**
- https://github.com/google/fonts/issues/6986
- https://github.com/google/fonts/issues/7153

**_Jacquarda Bastarda_**
- https://github.com/google/fonts/issues/6989
- https://github.com/google/fonts/issues/7180

**_Jersey_**

- https://github.com/google/fonts/issues/7076
- https://github.com/google/fonts/issues/7184
- https://github.com/google/fonts/issues/7186
- https://github.com/google/fonts/issues/7185
- https://github.com/google/fonts/issues/7188
- https://github.com/google/fonts/issues/7187
- https://github.com/google/fonts/issues/7189
- https://github.com/google/fonts/issues/7190

**_Jacquard_**

- https://github.com/google/fonts/issues/6988
- https://github.com/google/fonts/issues/7177
- https://github.com/google/fonts/issues/7178
- https://github.com/google/fonts/issues/7179

**_Yarndings_**

- https://github.com/google/fonts/issues/6987
- https://github.com/google/fonts/issues/7181
- https://github.com/google/fonts/issues/7183
- https://github.com/google/fonts/issues/7182

____________

**Super short description of the Font Family:**
Set of pixel fonts + symbols 

**Requirements:**

By filling this issue, you can confirm the project meets the  requirements (by ticking the cases or putting x between the square brackets in text mode):

- [x] I read, agree, and comply with the full [contributing requirements](https://googlefonts.github.io/gf-guide/index#pre-production-getting-your-fonts-ready-for-gf)
- [x] The entire font project is licensed under the [OFL](https://scripts.sil.org/cms/scripts/page.php?site_id=nrsi&id=OFL)
- [x] There is no "Reserved Font Name" mention in the OFL license
- [x] Family name is unique according to [namecheck.fontdata.com](https://namecheck.fontdata.com/)
- [x] The font supports at least [GF Latin Core glyphset](https://github.com/googlefonts/glyphsets/tree/main/GF_glyphsets/Latin/)
- [x] The repository respect the [upstream repo structure](https://googlefonts.github.io/gf-guide/upstream.html)
- [x] The source files are available in the repository
- [ ] I am the author of the font, or the author agreed to this submission
- [x] I will maintain the repository and participate in the onboarding process (addressing, solving, and responding to issues, merging pull requests, etc)

-----
**Image:**

#### Jacquard
<img width="1788" alt="Jacquard12" src="https://github.com/google/fonts/assets/48698976/7bf0235e-0462-49d1-8992-920f68f17a27">
<img width="1788" alt="Jacquard24" src="https://github.com/google/fonts/assets/48698976/021e63ae-2fd7-4ce4-bf03-e59f3a03ec5d">

-----

#### Jacquarda Bastarda
<img width="1776" alt="JacquardaBastarda9" src="https://github.com/google/fonts/assets/48698976/2876d74b-e899-464a-b2b9-999066165b34">

-----

#### Jersey
<img width="1756" alt="Jersey" src="https://github.com/google/fonts/assets/48698976/fd2c32c5-ec65-44b5-b534-9d068b58ee08">

-----

#### Micro 5
<img width="1782" alt="Micro5" src="https://github.com/google/fonts/assets/48698976/b290534a-9394-426a-bd09-bab4181bfd5c">

-----

#### Yardings
<img width="1782" alt="Yardings12" src="https://github.com/google/fonts/assets/48698976/7652f8c0-9f9c-4706-bad9-f38cc3c2e36e">
<img width="1782" alt="Yardings24" src="https://github.com/google/fonts/assets/48698976/03bcca6f-1986-42c8-a51e-be468dc459c6">

**Comment by vv-monsalve** [comment]
Hi @scfried,

We have reviewed and accepted the fonts to be included in the catalog. The next necessary steps would be:

- [ ] Create a repository for each font using googlefonts-project-template.
- [ ] After creating the repos, filing an individual Add-Font issue for each font is a required step to incorporate them into the pipeline workflow
- [ ] Please read the documentation, particularly the [Pre-Production chapter](https://googlefonts.github.io/gf-guide/#pre-production-getting-your-fonts-ready-for-gf), to get the fonts ready to meet the requirements.
- [ ] Following the above, completing the GF Latin Core, is required. There are an average of ~100 glyphs missing on each font, but many of them are composite glyphs.

**Comment by scfried** [comment]
Hi @vv-monsalve,

I'm so excited to have my work on google fonts soon! When I spoke to David I told him about my fear of github, but I will do my best to work with it! For now it sounds like I should just read up on documentation and wait to hear from @emmamarichal

**Comment by vv-monsalve** [comment]
@scfried Happy to hear you're happy, they are nice projects :)

> but I will do my best to work with it!

No need to be afraid at all, as with many things is just a matter of exercise. We have a section in the GF-Guide that is intended to help as a starting point https://googlefonts.github.io/gf-guide/hosting.html

> For now it sounds like I should just read up on documentation and wait to hear from @emmamarichal

The list provided above is for the tasks you could start with while Emma can reach out :)

**Comment by scfried** [comment]
@vv-monsalve great! thank you for clarifying

**Comment by davelab6** [comment]
@scfried and @emmamarichal will work on bringing this to gf core

**Comment by emmamarichal** [comment]
@chrissimpkins 
STATUS: Only Jersey 25 Charted need to be onboarded. Marc is working on a script that will allow a less heavy file.

**Comment by emmamarichal** [comment]
There are on their way to reach the API :) I closed that issue because all the PRs are merged in the GF repo!

**Comment by scfried** [comment]
Perfect, thanks! Just making sure it wasn't lost in the shuffle :)
