### ISSUE TITLE
Hindi Text not printing exact on PDF

### ISSUE THREAD

**Issue by amitatale** [google/fonts#6716]
I am using Hind -Medium font. it is working fine for English language however when I try to show Hindi/Marathi language on PDF it is not printing exact,

I am doing it in Flutter for android. 
Like this word लोकसत्ता, महाराष्ट्र टाईम्स it not printing exact.

![WhatsApp Image 2023-09-17 at 8 29 02 PM](https://github.com/google/fonts/assets/13673104/3bd29b3b-e34e-47cb-ac8e-69fffdb99aa1)

**Comment by RosaWagner** [comment]
Hi @amitatale, thanks for your report. Unfortunately I have trouble to understand the problem. Can you give more details, such as:

- What is different between the screen and the PDF?
- Which font are you using exactly?
- If you use it from another device, does it work as expected? 
- Do you use the variable font or the static font?

**Comment by RosaWagner** [comment]
So, tell me if I understood the problem correctly:
- You are developing an app for Android with Flutter
- Exporting to PDF leads to Marathi script shaping issues
- You tried with several fonts, and the shaping is still incorrect in the PDF  

If several fonts are failing, it might be an issue from the app you are using. It might be that Flutter doesn't handle properly the Marathi script and fails to export it properly to PDF. Or maybe a language tag is missing to tell PDF to shape the script correctly? Unfortunately, this is out of my technical knowledge, but it sounds that the issue should be reported to Flutter to get help from them. You may even already find your issue in their issue tracker: https://github.com/flutter/flutter/issues

**Comment by simoncozens** [comment]
It looks to me like the problem is that the PDF engine is not correctly shaping the text. The problem will most likely be with whatever software you are using the generate the PDF. As Rosalie says, this is likely not to be a problem with the font (which displays fine for you, so we know it is working), so you might want to try the issue tracker for the PDF library.
