### ISSUE TITLE
Paraxian

### ISSUE THREAD

**Issue by jalonsdale** [google/fonts#6720]
**Font Project Git Repo URL:**
https://github.com/jalonsdale/font-parax/

**Super short description of the Font Family:**
Crypto / Paraxian

**Requirements:**

Google Fonts will publish only fonts that match its requirements. Please familiarize yourself with the complete documentation in the [Google Fonts Guide](https://googlefonts.github.io/gf-guide/) (GF-Guide) and ensure your font project complies with them before submitting the font family. You can also use the [Google Fonts Project Template](https://github.com/googlefonts/googlefonts-project-template), which will help you create a repository that follows the needed structure and includes build requirements.

By filling this issue, you can confirm the project meets the  requirements (by ticking the cases or putting x between the square brackets in text mode):

- [x] I read, agree, and comply with the full [contributing requirements](https://googlefonts.github.io/gf-guide/index#pre-production-getting-your-fonts-ready-for-gf)
- [x] The entire font project is licensed under the [OFL](https://scripts.sil.org/cms/scripts/page.php?site_id=nrsi&id=OFL)
- [x] There is no "Reserved Font Name" mention in the OFL license
- [x] Family name is unique according to [namecheck.fontdata.com](https://namecheck.fontdata.com/)
- [x] The font supports at least [GF Latin Core glyphset](https://github.com/googlefonts/glyphsets/tree/main/GF_glyphsets/Latin/)
- [x] The repository respect the [upstream repo structure](https://googlefonts.github.io/gf-guide/upstream.html)
- [x] The source files are available in the repository
- [x] I am the author of the font, or the author agreed to this submission
- [x] I will maintain the repository and participate in the onboarding process (addressing, solving, and responding to issues, merging pull requests, etc)

**Image:**

Attach here a pic or a screenshot of the font. One image is enough, it can be a few letters, to give a quick overview.
![Paraxdemo](https://github.com/google/fonts/assets/22757957/ff9b6bb1-2cf1-436c-bd51-c84a2fc32a1f)

**Comment by eliheuer** [comment]
@jalonsdale Thanks! But I think this might be too avant-garde for Google Fonts right now. 

Also on the requirements checklist you marked that the project uses the OFL license, but looking at the repo it uses a custom license written by the author.

 You also checked "The repository respects the [upstream repo structure](https://googlefonts.github.io/gf-guide/upstream.html)", which is not the case the upstream repository.

I'm closing this issue, but please feel free to read to [Google Fonts documentation](https://googlefonts.github.io/gf-guide/) and open a new request to add a font in the future.
