### ISSUE TITLE
Update Noto Sans Japanese with Hentaigana Letters (Block Kana Supplement, Kana Extended-A, Kana Extended-B, and Small Kana Extension)

### ISSUE THREAD

**Issue by AshtonTameirao1225** [google/fonts#6726]
**Font Project Git Repo URL:**

**Current version:**

**New available version:**

**Super short description of the upgrade:**
(expand style, expand glyphset, improve rendering, bug fix…)

**Bugs reported in this repo which this upgrade would fix:**
Search in the [issue tracker](https://github.com/google/fonts/issues) if there is some opened issues containing the font name.

**Comment by simoncozens** [comment]
This is not an issue for the google/fonts repository, but for notofonts. A hentaigana font is currently being designed, and is scheduled to be released by the end of the year.
