### ISSUE TITLE
Update Noto Music (Znamenny Musical Notation Block)

### ISSUE THREAD

**Issue by AshtonTameirao1225** [google/fonts#6728]
**Font Project Git Repo URL:**

**Current version:**

**New available version:**

**Super short description of the upgrade:**
(expand style, expand glyphset, improve rendering, bug fix…)

**Bugs reported in this repo which this upgrade would fix:**
Search in the [issue tracker](https://github.com/google/fonts/issues) if there is some opened issues containing the font name.

**Comment by simoncozens** [comment]
A Znamenny musical symbols font is in development at https://github.com/notofonts/znamenny and will be available by the end of the year. (For technical reasons it needs to be separate to Noto Music.) Please raise any further issues about Znamenny in that repository.
