### ISSUE TITLE
Update Noto Sans Simplifed Chinese, Noto Sans Traditional Chinese, and Noto Sans Hong Kong (Kana Supplement, Kana Extended-A, Kana Extended-B, and Small Kana Extension Block)

### ISSUE THREAD

**Issue by AshtonTameirao1225** [google/fonts#6729]
**Font Project Git Repo URL:**

**Current version:**

**New available version:**

**Super short description of the upgrade:**
(expand style, expand glyphset, improve rendering, bug fix…)

**Bugs reported in this repo which this upgrade would fix:**
Search in the [issue tracker](https://github.com/google/fonts/issues) if there is some opened issues containing the font name.

**Comment by simoncozens** [comment]
I'm not sure it makes sense to add small kana and hentaigana to Chinese fonts. But these codepoints will be supported by Noto Sans Hentaigana when it is released.
