### ISSUE TITLE
Update All Noto Han Fonts (U+2FFC-U+2FFF), (U+31EF), (U+31BC-U+31BF), (U+4DB7-U+4DBF), and (U+9FF0-U+9FFF)

### ISSUE THREAD

**Issue by AshtonTameirao1225** [google/fonts#6730]
**Font Project Git Repo URL:**

**Current version:**

**New available version:**

**Super short description of the upgrade:**
(expand style, expand glyphset, improve rendering, bug fix…)

**Bugs reported in this repo which this upgrade would fix:**
Search in the [issue tracker](https://github.com/google/fonts/issues) if there is some opened issues containing the font name.

**Comment by simoncozens** [comment]
This is not an issue for google/fonts, but for notofonts/noto-cjk. I will ask Adobe to add these additional characters.
