### ISSUE TITLE
Update Noto Sans Syriac Eastern (Syriac Supplement Block)

### ISSUE THREAD

**Issue by AshtonTameirao1225** [google/fonts#6733]
**Font Project Git Repo URL:**

**Current version:**

**New available version:**

**Super short description of the upgrade:**
(expand style, expand glyphset, improve rendering, bug fix…)

**Bugs reported in this repo which this upgrade would fix:**
Search in the [issue tracker](https://github.com/google/fonts/issues) if there is some opened issues containing the font name.

**Comment by simoncozens** [comment]
Duplicate of https://github.com/notofonts/syriac/issues/11.
