### ISSUE TITLE
Update Noto Sans Khojki (U+11240, U+11241, U+11242)

### ISSUE THREAD

**Issue by AshtonTameirao1225** [google/fonts#6735]
**Font Project Git Repo URL:**

**Current version:**

**New available version:**

**Super short description of the upgrade:**
(expand style, expand glyphset, improve rendering, bug fix…)

**Bugs reported in this repo which this upgrade would fix:**
Search in the [issue tracker](https://github.com/google/fonts/issues) if there is some opened issues containing the font name.

**Comment by simoncozens** [comment]
These codepoints have been added to Noto Sans Khojki; a new release will happen at the end of this quarter (i.e. end of this month) and will automatically trigger a pull request here to update Google Fonts.
