### ISSUE TITLE
Montserrat serving only 2 font weights

### ISSUE THREAD

**Issue by danyj** [google/fonts#674]
I see that the Montserrat  has been updated with new weights but seems like you are still serving only 2  

Se this please  https://github.com/JulietaUla/Montserrat/issues/39#issuecomment-281099833

is that going to be updated soon or is it a bug?

**Comment by m4rc1e** [comment]
V1 only had Regular and Bold
V6.001 (current) has 18 styles. They're all working.

http://jsbin.com/jiketezove/edit?html,output


Could you please elaborate further what the problem is?

**Comment by danyj** [comment]
Thnx  for the bin bud , hell of  a cache in Chrome ,  not even developer clear cache could not help
