### ISSUE TITLE
Plagiarism allegations for Ruslan Display

### ISSUE THREAD

**Issue by yanone** [google/fonts#6740]
Twitter user [Tanita26086361](https://twitter.com/Tanita26086361) has flagged Google Fonts in a [retweet](https://twitter.com/Tanita26086361/status/1704399732943048911) of user [viterzbayraku](https://twitter.com/viterzbayraku), saying that Google Fonts’ [Ruslan Display](https://fonts.google.com/specimen/Ruslan+Display?query=ruslan) typeface originates from Ukrainian designer Oleg Snarskii and has been plagiarized by Russian designer Denis Masharov.

Masharov’s claim in the font’s description that Ruslan is derived from a _poluustav_ lettering style can only be remotely supported by a quick [image search](https://www.google.com/search?sca_esv=566929587&sxsrf=AM9HkKmgO-1WbfpGlTcNiu9-f1B3kMdCeA:1695216429777&q=poluustav&tbm=isch&source=lnms&sa=X&ved=2ahUKEwiTxvSopbmBAxUQ_rsIHWlJAaQQ0pQJegQICxAB&biw=2236&bih=1418&dpr=2). 

Instead, the typeface’s origin in Ukraine is apparent from photos of the [Teremky metro station](https://www.google.com/search?sca_esv=566929587&sxsrf=AM9HkKnZJ0iE_bsOyxjXtKhTMO8guMDglA:1695216601406&q=Teremky+metro+station&tbm=isch&source=lnms&sa=X&ved=2ahUKEwjc9N_6pbmBAxWi1QIHHXJRCdwQ0pQJegQICBAB&biw=2236&bih=1418&dpr=2#imgrc=Khveqv0oYMFoWM).

Can we find any printed evidence that confirms Snarskii as the design’s author? If so, I propose to re-release Ruslan under a different name and correct crediting of the authors (which probably must still include Masharov as a secondary author as having drawn the outlines).

**Comment by moyogo** [comment]
| Ruslan | Snarsky’s design in Snarsky 1979 p. 94 |
| -- | -- |
| <img width="331" alt="Screenshot 2023-09-20 at 15 40 46" src="https://github.com/google/fonts/assets/1923747/ce58dbab-e362-43ee-a40a-e7e7317e65e6"> | <img width="349" alt="Screenshot 2023-09-20 at 15 42 03" src="https://github.com/google/fonts/assets/1923747/d4e5e5a9-e1c3-4baf-ad31-c746956a7587"> |

- [Snarsky 1979] О.В. Снарский, *Шрифты-алфавиты для рекламных и декоративно-оформительских работ*, Киев: Реклама, 1979 (online at https://my.etnoua.info/novyny/knyha-shryfty-alfavity-osnarskyj-1979/)

**Comment by viterzbayraku** [comment]
At least Oleg Snarsky will be added to the description as an author.

**Comment by yanone** [comment]
@viterzbayraku Do you support a re-release under a different name as well? I’m not versed in Slavik languages but I have a feeling the name Ruslan would not sit well with its original designer.

**Comment by viterzbayraku** [comment]
As a type designer I can fix it. For the sake of justice, I would keep
Masharov's name as a co-author, because he did make the Latin letters of
this font. And in general he digitized Cyrillic letters. But it is obvious
that the Russian Masharov did not ask permission to use the letter design
from the family of the Ukrainian Oleg Snarskyi. It was unfair not to
mention the author's name. I don't know what rules Google Fonts has, but
the name "Ruslan" has no relation to the work of the real author. The
description should also be changed, because it is not an Old Russian font.
This is the author's work of Snarsky based on the style of the Ruthenian
period.

ср, 20 вер. 2023, 16:51 користувач Yanone ***@***.***> пише:

**Comment by yanone** [comment]
@viterzbayraku Google Fonts has no rules regarding font naming other than preventing the usage of an already existing font name.

My personal opinion is that since Ruslan is a neutral name that didn't originate in Russia but is a version of an old Azeri/Albanian/Turkic name, we should stick with the name and simply update the font’s description and authors as discussed. This name is as good as any other name and given that a great portion of famous people named Ruslan mentioned on the Wikipedia page posted above are actually Ukrainian, the name shouldn't pose an issue to anyone.

@davelab6 What's your take on this?

**Comment by viterzbayraku** [comment]
We have 2 different fonts based on the same design. The "Snarsky Ustav"
font by Ukrainian type designer Henadiy Zarechnyuk from 2000's. And the
same work by Masharov. "Ruslan" is neutral, but not related to the original
author and original idea. So, the question of the name is up for
discussion. Personally, I would just change the name to Snarsky. Or at your
choice. But the description and the author must be changed exactly. There
should be at least two authors of this particular font. Snarsky, and only
then Masharov. And in the description it should be clearly indicated that
this is the author's design of the letters of Snarsky, digitized by
Masharov. From the point of view of Russians, the name Ruslan is part of
their folklore and imperial myth. It would seem that this is just a name,
but no. Everything is more complicated.

ср, 20 вер. 2023, 17:44 користувач Yanone ***@***.***> пише:

**Comment by Cogli** [comment]
[The Behance page](https://www.behance.net/gallery/3350387/Ruslan-Display) of the project does mention Snarsky as author of the original design, though the cover photo speak of "russian character".

**Comment by viterzbayraku** [comment]
> [The Behance page](https://www.behance.net/gallery/3350387/Ruslan-Display) of the project does mention Snarsky as author of the original design, though the cover photo speak of "russian character".

It's not a Russian character. It's manipulation. I would not like to enter into a historical discussion now, but other than that, the mention on Behance does not negate the fact that Masharov did not mention the actual author in the description here on Google Fonts, and digitized this font without permission from the author or his family. At least we can change the description, and replace the font name. For example on "Snarsky" or "Snarsky Display". It will be fair. I am not calling to remove Masharov's name from everywhere. As co-author is ok.

**Comment by viterzbayraku** [comment]
> > > [The Behance page](https://www.behance.net/gallery/3350387/Ruslan-Display) of the project does mention Snarsky as author of the original design, though the cover photo speak of "russian character".
> > 
> > It's not a Russian character. It's manipulation. I would not like to enter into a historical discussion now, but other than that, the mention on Behance does not negate the fact that Masharov did not mention the actual author in the description here on Google Fonts, and digitized this font without permission from the author or his family. At least we can change the description, and replace the font name. For example on "Snarsky" or "Snarsky Display". It will be fair. I am not calling to remove Masharov's name from everywhere. As co-author it's ok.
> 
> Sure, I was just pointing out that Masharov seems well aware of the origin of his work and did not happen to end up on a photo of the font or something.

He did not hide where he got the original source from. I talked to him about it a few years ago.

**Comment by moyogo** [comment]
Snarsky 1979:7 indicates "Шрифты декоративные, стилизованные на основе полуустава XVI века- стр. 94" for both samples on page 94 (the relevant one is the left one).

The Behance description could be used with a few modifications struck or in bold:
> Decorative display unicase font, stylized as <s>an ancient Russian script</s> **16th century poluustav**. Based on <s>the</s> **a** Cyrillic alphabet by <s>O.</s> **Oleg** Snarsky. Suitable for lettering, Ruslan Display can also be used in to set short texts.
Ruslan Display was done in collaboration with Vladimir Rabdu.

http://luc.devroye.org/fonts-39263.html indicates "Most of his fonts were co-designed with Dubina nikolay." It would be good to know if Nikolay Dubina was involved in the original design.

> From the point of view of Russians, the name Ruslan is part of
their folklore and imperial myth. It would seem that this is just a name,
but no. Everything is more complicated.

@viterzbayraku could you expand on why the name should be changed? Ruslan seems to be a common given name in Ukraine.

**Comment by Cogli** [comment]
Maybe [here](https://bibliotekus.artlebedev.ru/books/dekorativnye-shrifty-1987/92/) some info could be found about possible co-authorship by Nikolay Dubina? I'm not a cyrillic speaker...

**Comment by viterzbayraku** [comment]
Sorry, but in Ukraine all Russian websites are blocked. I can't read it
without proxy.

чт, 21 вер. 2023, 13:29 користувач Cogli ***@***.***> пише:

**Comment by Cogli** [comment]
![91](https://github.com/google/fonts/assets/55837580/710c7076-b440-43b4-938f-ee3351791a70)
Sorry but the book is just a collection of images. The page in question has just a brief caption, I was hoping to find an index with more data, but it seems there isn't one.

**Comment by viterzbayraku** [comment]
Yes, because in this book everything is designs by Oleg Snarsky. It is
obvious that in those days, when there were no computers in use, such
catalogs were a kind of guide for copying and designing sign or advert. And
that is why the author did not invent the names of the fonts. Perhaps there
was no such culture of names at that time in the same catalogs. Just
generated a lot of samples of different styles. But in general, this
catalog, which, by the way, I physically have, it was all created by
Snarsky. Therefore, there is no doubt that the author is Mr. Oleg. The
style itself appeals to ustav and semiustav of the 11th-16th centuries. But
in custom Snarsky's author's interpretation. This is not a just copy of
ancient letters. This is a interpretation on behalf of the author.

чт, 21 вер. 2023, 14:32 користувач Cogli ***@***.***> пише:

**Comment by viterzbayraku** [comment]
The caption is "The stylization of the semiustav" [by the author]

чт, 21 вер. 2023, 14:32 користувач Cogli ***@***.***> пише:

**Comment by viterzbayraku** [comment]
Here is my copy of this catalog.

чт, 21 вер. 2023, 14:32 користувач Cogli ***@***.***> пише:

**Comment by Cogli** [comment]
The "Ruslan" name is a reference to the [Ruslan and Ludmilla](https://en.wikipedia.org/wiki/Ruslan_and_Ludmila) poem by Pushkin, given the cover image on Behance.

I think that adding a "'Snarsky" part to the name of the font is just fitting, since the cyrillic script and core of the font is a digitization of his work. Something in the vein of Goudy Old Style. It's not only the best way of crediting the designer, but also of driving the most curious ones to do some researches, thus preserving his memory. That is, if there is not some technical reason to avoid font renaming as much as possible.

**Comment by viterzbayraku** [comment]
Guys, any progress?

**Comment by yanone** [comment]
Sorry that no one got back to you yet. The issue has been discussed internally and management has decided that Ruslan is good enough of a name, given that a name change poses much greater difficulty in re-ordering the API than altering the description. Other nations are using the lion symbolism in their national narratives and there is no clear reason for Google Fonts to act here.

Google Fonts is confronted foremost with a plagiarism issue here, not a naming issue. It will react by properly crediting Snarky as the original author and Masharov as having digitized the original Cyrillic drawings and added a Latin.

I'm an external contractor for Google Fonts and am only forwarding the results here, so my apologies if they are not what you were hoping for. I will personally see about the change of credits.

**Comment by setnemo** [comment]
The elder Russian tradition: to steel someting and say "it's mine"...

**Comment by imax9000** [comment]
@davelab6 Dave, can we please reconsider? There's a long history of russia appropriating our works of art and presenting them as their own, so keeping things this way is outright offensive. 

In both Ukraine and russia the name "Ruslan" is not associated with lions in any way, and while used in Ukraine, it's not very common. If it's indeed dedicated to a poem by Pushkin - that makes it a lot worse.
