### ISSUE TITLE
Update Noto Color Emoji

### ISSUE THREAD

**Issue by bsoap-cat** [google/fonts#6741]

**Comment by eliheuer** [comment]
We need more information than this for an issue to be acted on. Update Noto Color Emoji to what and why?

**Comment by AshtonTameirao1225** [comment]
15.1 Emoji

**Comment by bsoap-cat** [comment]
@eliheuer Noto Color Emoji has been updated to version 2.040 https://github.com/googlefonts/noto-emoji
