### ISSUE TITLE
Noto Q3 releases 

### ISSUE THREAD

**Issue by simoncozens** [google/fonts#6743]
Here's what's on deck for the Noto Q3 release cycle, which will begin next Monday:

- [x] Noto Serif Ahom https://github.com/google/fonts/pull/6756
- [x] Noto Sans Armenian  https://github.com/google/fonts/pull/6759
- [x] Noto Serif Armenian https://github.com/google/fonts/pull/6758
- [ ] Noto Sans Balinese - needs qa
- [ ] Noto Serif Balinese - needs qa
- [x] Noto Sans Batak https://github.com/google/fonts/pull/6757
- [x] Noto Sans Caucasian Albanian https://github.com/google/fonts/pull/5281#pullrequestreview-1644307358
- [x] Noto Sans Cham https://github.com/google/fonts/pull/6761
- [x] Noto Sans Chorasmian https://github.com/google/fonts/pull/6760
- [x] Noto Sans Coptic https://github.com/google/fonts/pull/6762
- [x] Noto Serif Dogra https://github.com/google/fonts/pull/6763
- [x] Noto Sans Elymaic https://github.com/google/fonts/pull/5283
- [x] Noto Sans Georgian https://github.com/google/fonts/pull/6766
- [x] Noto Serif Georgian https://github.com/google/fonts/pull/6765
- [x] Noto Sans Glagolitic https://github.com/google/fonts/pull/6764
- [x] Noto Sans Gujarati https://github.com/google/fonts/pull/6778
- [x] Noto Serif Gujarati https://github.com/google/fonts/pull/6779
- [x] Noto Sans Kaithi https://github.com/google/fonts/pull/6767
- [x] Noto Sans Kannada https://github.com/google/fonts/pull/6795
- [x] Noto Serif Kannada https://github.com/google/fonts/pull/6790
- [x] Noto Sans Khmer https://github.com/google/fonts/pull/6809
- [x] Noto Serif Khmer https://github.com/google/fonts/pull/6810
- [x] Noto Sans Khojki https://github.com/google/fonts/pull/6773
- [x] Noto Serif Khojki https://github.com/google/fonts/pull/6774
- [x] Noto Sans https://github.com/google/fonts/pull/6819
- [x] Noto Serif https://github.com/google/fonts/pull/6820
- [x] Noto Sans Mono https://github.com/google/fonts/pull/6821
- [x] Noto Sans Lydian https://github.com/google/fonts/pull/6771
- [x] Noto Sans Manichaean https://github.com/google/fonts/pull/6777
- [x] Noto Sans Meroitic https://github.com/google/fonts/pull/6775
- [x] Noto Sans Nandinagari https://github.com/google/fonts/pull/6776
- [x] Noto Nastaliq Urdu https://github.com/google/fonts/pull/6824
- [x] Noto Serif Old Uyghur https://github.com/google/fonts/pull/5395
- [x] Noto Sans Sundanese https://github.com/google/fonts/pull/6784
- [x] Noto Sans Takri https://github.com/google/fonts/pull/6785
- [x] Noto Sans Tangsa https://github.com/google/fonts/pull/6786
- [x] Noto Sans Telugu https://github.com/google/fonts/pull/6806
- [x] Noto Serif Telugu https://github.com/google/fonts/pull/6807
- [x] Noto Sans Thaana https://github.com/google/fonts/pull/6792
- [x] Noto Sans Thai https://github.com/google/fonts/pull/6789
- [x] Noto Serif Thai https://github.com/google/fonts/pull/6788

**Comment by AshtonTameirao1225** [comment]
There are no extended blocks in Batak and Elymaic

**Comment by simoncozens** [comment]
Symbols/Symbols2 should go out as well, thanks to Emma's work.

**Comment by chrissimpkins** [comment]
Closing due to the title. Let's open new issues for any outstanding work here.
