### ISSUE TITLE
[tools/encodings] Document "Filter Lists"

### ISSUE THREAD

**Issue by graphicore** [google/fonts#675]
I just found the content of `tools/encodings/GF 2016 Glyph Sets/Greek/GF-greek-expert.nam`:

```
# GF Greek Expert
# This set contains no characters with unicode values. See Filter Lists folder
```

I'm not sure if I know how these Filter List files are used. Thus, it would be really nice if we could have a description of what purpose(s) these Filter Lists serve. Also, because we already have Namelist files without any unicodes, e.g `tools/encodings/GF 2016 Glyph Sets/GF-latin-plus_optional-glyphs.nam`

**Comment by davelab6** [comment]
> I'm not sure if I know how these Filter List files are used. Thus, it would be really nice if we could have a description of what purpose(s) these Filter Lists serve. 

https://github.com/google/fonts/commit/0c2a677e9b35e0a82393db5782395a93e5a06295 :)

> Also, because we already have Namelist files without any unicodes, e.g tools/encodings/GF 2016 Glyph Sets/GF-latin-plus_optional-glyphs.nam

Right, but those files are 'parents' and the filter lists are 'children', derived for a specific purpose (using with GlyphsApp.)

**Comment by alexeiva** [comment]
The readme in GF 2016 sets gives info on filter lists
