### ISSUE TITLE
Add Metropolis

### ISSUE THREAD

**Issue by davelab6** [google/fonts#676]
https://github.com/chrismsimpson/Metropolis

**Comment by chenxeed** [comment]
Up for this 👍

**Comment by carasmo** [comment]
Yep!

**Comment by andrelevi** [comment]
Sir, I need it

**Comment by m4rc1e** [comment]
I also need a cure for my ibs :-) 

Anyways, I attempted a pr. Some changes need to be made to the family for us to accept it https://github.com/chrismsimpson/Metropolis/issues/23

**Comment by sdurnov** [comment]
@davelab6 pls, this is really very needed font, used by Angular UI library Clarity UI.

**Comment by sladen** [comment]
@sdurnov, think the status on this is that @chrismsimpson is willing to accept a pull request fixing whatever is needed to meet Google Fonts' on-boarding requirements:

  https://github.com/chrismsimpson/Metropolis/issues/14#issuecomment-343899683

**Comment by davelab6** [comment]
@m4rc1e worth prioritizing because of it's use in themes

**Comment by m4rc1e** [comment]
@davelab6 there's several issues that need fixing first, https://github.com/chrismsimpson/Metropolis/issues/14#issuecomment-343899683

**Comment by davelab6** [comment]
He wants us to make them and give him a PR that takes care of everything.
Make it so :)

**Comment by sandman21** [comment]
@m4rc1e is it possible for you to make this happen? Would love to be able to use this great font with G Suite. Is it something @chrismsimpson has to do himself?

**Comment by sdurnov** [comment]
@sandman21 I'm afraid that Chris won't do that. Looks like he's too busy with other projects.

**Comment by chrismsimpson** [comment]
Hey guys, as @davelab6 mentioned, happy to receive a PR :)

**Comment by mbana** [comment]
Dear folks, any updates on this?

**Comment by felipesanches** [comment]
> Dear folks, any updates on this?

I just sent this message to @chrismsimpson to see if he's willing to accept the removal of RFN from the licensing terms, which is a prerequisite. If he agrees on that, then I can prepare a PR doing so:
https://github.com/chrismsimpson/Metropolis/issues/14#issuecomment-539994886

...and then, later, we can look at the rest of the requirements (the technical review of the font files)

**Comment by felipesanches** [comment]
I am working on this. https://github.com/chrismsimpson/Metropolis/pull/35

**Comment by robsonpsdesv** [comment]
@felipesanches was there a block for this solution?

**Comment by fitojb** [comment]
Has Hoefler & Co. reviewed this and confirmed it’s not an illegal rip-off of Gotham?

**Comment by chrismsimpson** [comment]
Well that's rude

**Comment by davelab6** [comment]
@chrismsimpson it might be a good idea to add something to your project to address this kind of concern, and point out how this is an original design in a popular genre, and that all the font outline data is not derived from any 3rd party, and so on.

**Comment by chrismsimpson** [comment]
Monolith PRs and accusations of plagiarism likely means this will never end up in Google Fonts

**Comment by joefitzgerald** [comment]
@fitojb Is there basis for [your message](https://github.com/google/fonts/issues/676#issuecomment-578936682)? If so, could you please include citations, or at a minimum more specificity?

@davelab6 Is it common for authors of a font to be asked to [defend accusations of plagiarism proactively](https://github.com/google/fonts/issues/676#issuecomment-578986113) in their repo? What is the threshold for such requests?

It seems apparent both from @chrismsimpson's response here and in the commit history for his repo around the same time that he was upset by one or both of these messages. There are many of us who wish to see Metropolis included in Google Fonts, while respecting the work that Chris has put into the production of the font over many years.

What can we do to improve the trajectory of this issue?

**Comment by xotypeco** [comment]
I own a license to Gotham, so I can show its outlines from original files; here are a few glyphs from Gotham Black & Metropolis Black layered. Chris' x-height and counter weights are clearly very different. Gotham itself was derived from 1930s urban signage around NYC and as such wasn't the genesis point for these sorts of forms anyway, so drawing comparisons based on the last decade's worth of saturation of the typeface seems like a little bit of a straw horse.

![Screenshot 2020-02-23 08 36 12](https://user-images.githubusercontent.com/52611676/75113967-f867a500-5617-11ea-8b60-dfc18b0a729f.png)
![Screenshot 2020-02-23 08 36 53](https://user-images.githubusercontent.com/52611676/75113969-f998d200-5617-11ea-8af4-c253c2609447.png)
![Screenshot 2020-02-23 08 37 19](https://user-images.githubusercontent.com/52611676/75113971-fa316880-5617-11ea-809a-3ed9aabd4b88.png)

**Comment by applemonkey496** [comment]
Any updates on this?

**Comment by pumano** [comment]
Would love to use very clear Metropolis font via Google Fonts :)

Hope it will be added soon!
@chrismsimpson thank you for beauty!

**Comment by pushpendraKh** [comment]
Any idea by what time will it be added to google fonts? Anyone?

**Comment by mrleemon** [comment]
Apparently, Hoefler's lawyer has threatened Chris, so I doubt we'll see Metropolis in Google Fonts anytime soon. A pity...

 https://discourse.mozilla.org/t/metropolis-font-repo-missing/69415

**Comment by chrismsimpson** [comment]
I’m working on something new with a less contentious name ;)

**Comment by wayward-turnip** [comment]
**Thank you** @chrismsimpson for your work.   

You've probably seen there is an issue #3414 to adopt the ''Clarity City'' derivative into Google fonts.  Hopefully, it won't be hard to sort out their derivative changes, and yours. :-|
