### ISSUE TITLE
All Fonts for Q3.

### ISSUE THREAD

**Issue by AshtonTameirao1225** [google/fonts#6768]
### Here are all the fonts for Q3:

- [x] Noto Nastiliq Urdu
- [x] Noto Naskh Arabic
- [x] Noto Sans Arabic
- [x] Noto Serif Ahom
- [x] Noto Sans Balinese
- [x] Noto Serif Balinese
- [ ] Noto Sans Cham
- [x] Noto Serif Dives Akuru
- [ ] Noto Serif Dogra
- [ ] Noto Sans Elymaic
- [x] Noto Sans Hebrew
- [x] Noto Serif Hebrew
- [ ] Noto Sans Japanese
- [ ] Noto Serif Japanese
- [x] Noto Sans Khojki
- [x] Noto Serif Khojki
- [ ] Noto Sans Lao Looped
- [ ] Noto Sans Mongolian
- [ ] Noto Sans Newa
- [x] Noto Serif Old Uyghur
- [x] Noto Sans Symbols 2
- [ ] Noto Serif Tangut
- [ ] Noto Sans Wancho

**Comment by simoncozens** [comment]
These is not (in any way) the Noto Q3 release plan, which can be found at #6743.
