### ISSUE TITLE
Yu Gothic is Missing Hentaigana Letters

### ISSUE THREAD

**Issue by AshtonTameirao1225** [google/fonts#6783]
#This issue also works for requesting features. 

**Describe the issue**
A clear and concise description of what the issue is.

**To Reproduce**
Steps to reproduce the behavior.

**Expected behavior**

**Additional context**
Add any other context about the problem here (OS version, browser, printer…)

**Screenshots**

**Comment by RosaWagner** [comment]
@AshtonTameirao1225 As you were told several times already; noto related issues should be opened in the Noto repository. Since most of the issues you opened don't make so much sense, we decided to consider your messages as spam. You may also be blocked in the next days.
