### ISSUE TITLE
Add Hedvig Letters

### ISSUE THREAD

**Issue by KanonFoundry** [google/fonts#6798]
**[Font Project Git Repo URL:](https://github.com/KanonFoundry/HedvigLetters)**

Hedvig Letters is a small font family consisting of three fonts; Hedvig Letters Big, Hedvig Letters Small, and Hedvig Letters Standard.
Hedvig Letters Big and Small are serifs designed in two optical sizes.
Hedvig Letters Standard is a sans serif designed with the same skeleton as Big and Small.

The conceptual idea behind the design is that it embraces the small mistakes and imperfections that comes from drawing letters without optical corrections. 

**Requirements:**

Google Fonts will publish only fonts that match its requirements. Please familiarize yourself with the complete documentation in the [Google Fonts Guide](https://googlefonts.github.io/gf-guide/) (GF-Guide) and ensure your font project complies with them before submitting the font family. You can also use the [Google Fonts Project Template](https://github.com/googlefonts/googlefonts-project-template), which will help you create a repository that follows the needed structure and includes build requirements.

By filling this issue, you can confirm the project meets the  requirements (by ticking the cases or putting x between the square brackets in text mode):

- [x] I read, agree, and comply with the full [contributing requirements](https://googlefonts.github.io/gf-guide/index#pre-production-getting-your-fonts-ready-for-gf)
- [x] The entire font project is licensed under the [OFL](https://scripts.sil.org/cms/scripts/page.php?site_id=nrsi&id=OFL)
- [x] There is no "Reserved Font Name" mention in the OFL license
- [x] Family name is unique according to [namecheck.fontdata.com](https://namecheck.fontdata.com/)
- [ ] The font supports at least [GF Latin Core glyphset](https://github.com/googlefonts/glyphsets/tree/main/GF_glyphsets/Latin/)
- [x] The repository respect the [upstream repo structure](https://googlefonts.github.io/gf-guide/upstream.html)
- [x] The source files are available in the repository
- [x] I am the author of the font, or the author agreed to this submission
- [x] I will maintain the repository and participate in the onboarding process (addressing, solving, and responding to issues, merging pull requests, etc)

![600b4dc090c137a502281511e09dfd8fff412a5a-4000x2250](https://github.com/google/fonts/assets/146174931/804b1e6a-3f59-403f-99ae-1ccf75f864ea)
![828b27c3a0f9607ef95bb9d2dce1d7e93e22cdfd-4000x2250](https://github.com/google/fonts/assets/146174931/4231dcf0-70eb-4eda-af15-ddf1b4dc3f91)
![cc067a181d7e2bfa5b9ac2fc1ab464a2d40e452a-4000x2250](https://github.com/google/fonts/assets/146174931/cec0dff2-7c75-47ad-8c55-723bab40543d)

**Comment by RosaWagner** [comment]
Thanks @KanonFoundry for opening the issue, I'll take a first look before the end of the week.

**Comment by eliheuer** [comment]
Source files look clean and easy to work with to me after a quick look, only missing 5 GF-Core glyphs in each font.
![Screenshot 2023-09-27 at 6 14 02 PM](https://github.com/google/fonts/assets/5162664/039510c3-2b11-4e69-a130-b5c2b90baf5c)

**Comment by bsoap-cat** [comment]
Seeing the other Latin editions, along with Greek and Cyrillic letters would be cool
