### ISSUE TITLE
subset parameter in URL is ignored for resulting CSS

### ISSUE THREAD

**Issue by alistairjcbrown** [google/fonts#68]
Setting the subset parameter is ignored and all languages are output in the resulting CSS.
These URLs have been generated from the quick use page.

### Example

Requesting "Open Sans, Light 300"

##### Default (Latin)

[`http://fonts.googleapis.com/css?family=Open+Sans:300`](http://fonts.googleapis.com/css?family=Open+Sans:300)

Output contains all languages

```
/* cyrillic-ext */
  ...
}
/* cyrillic */
  ...
}
/* greek-ext */
  ...
}
/* greek */
  ...
}
/* vietnamese */
  ...
}
/* latin-ext */
  ...
}
/* latin */
  ...
}
```

##### Setting specifically (Greek)

[`http://fonts.googleapis.com/css?family=Open+Sans:300&subset=greek`](http://fonts.googleapis.com/css?family=Open+Sans:300&subset=greek)

Output contains all languages

```
/* cyrillic-ext */
  ...
}
/* cyrillic */
  ...
}
/* greek-ext */
  ...
}
/* greek */
  ...
}
/* vietnamese */
  ...
}
/* latin-ext */
  ...
}
/* latin */
  ...
}
```

**Comment by davelab6** [comment]
This is working as intended :)

You're using a browser with support for `unicode-range` (eg, Chrome) which is in your `...`. That means the font files are only fetched when the DOM includes characters that require them.

One can be a little misled by page load impact graphics, which show what would happen to browsers for which unicode-range is not supported; but those browsers are always served CSS that enumerates only the subset-requested files.

**Comment by alistairjcbrown** [comment]
@davelab6 TIL - thanks!
I'd forgotten that the CSS returned is tailored to the requesting browser.
