### ISSUE TITLE
Bhale Mindu Signs (Devanagari Extended-A) is Missing a Font

### ISSUE THREAD

**Issue by AshtonTameirao25** [google/fonts#6802]
#This issue also works for requesting features. 

**Describe the issue**
A clear and concise description of what the issue is.

**To Reproduce**
Steps to reproduce the behavior.

**Expected behavior**

**Additional context**
Add any other context about the problem here (OS version, browser, printer…)

**Screenshots**

**Comment by eliheuer** [comment]
@AshtonTameirao25 Please provide more information if possible, is this issue about Noto Sans/Serif Devanagari?

**Comment by eliheuer** [comment]
It looks to me like these were added in Unicode version 15.0, some reference I found:
https://www.unicode.org/L2/L2021/21102-devanagari-bhale-mindu.pdf
https://unicode.org/charts/PDF/Unicode-15.0/U150-11B00.pdf

I don't see these in Noto Sans/Serif Devanagari, so yes these codepoints do need a font

**Comment by eliheuer** [comment]
this would get more attention if you filed the issue in the Noto Fonts Git repository: https://github.com/notofonts
