### ISSUE TITLE
Cyrillic Extended-D needs a Font

### ISSUE THREAD

**Issue by AshtonTameirao25** [google/fonts#6803]
#This issue also works for requesting features. 

**Describe the issue**
A clear and concise description of what the issue is.

**To Reproduce**
Steps to reproduce the behavior.

**Expected behavior**

**Additional context**
Add any other context about the problem here (OS version, browser, printer…)

**Screenshots**

**Comment by eliheuer** [comment]
Thanks, but this would get more attention if you filed the issue in the Noto Fonts Git repository: https://github.com/notofonts
