### ISSUE TITLE
Noto Sans Old Sogdian, Noto Sans Sogdian, Noto Sans Elymaic, Noto Serif Dogra, Noto Sans Zanabazar Square, Noto Sans Soyombo, Noto Sans Anatolian Hieroglyphs, Noto Sans Medefaidrin, Noto Serif Tangut, Noto Sans Nushu, Noto Sans Mayan Numerals, Noto Sans SignWriting, Noto Sans Indic Siyaq Numbers, and A lot of symbols from Noto Sans Symbols 2 are missing a font on iOS.

### ISSUE THREAD

**Issue by AshtonTameirao25** [google/fonts#6804]
#This issue also works for requesting features. 

**Describe the issue**
Apple Decided to Skip it in 2020, Apple must add the font to iOS 17 or iOS 18.

**To Reproduce**
Steps to reproduce the behavior.

**Expected behavior**

**Additional context**
Add any other context about the problem here (iOS, iPadOS, macOS, watchOS, and tvOS)

**Screenshots**

Check any boxes that you want to add the font to iOS 17 and/or iOS 18.

- [ ] Noto Sans Lao Looped Pali Lao and Sanskrit Letters
- [ ] Noto Serif Balinese Extensions
- [ ] Noto Sans Symbols 2 Astrological Symbols
- [ ] Noto Sans Symbols 2 Phaistos Disc
- [ ] Noto Sans Vithkuqi
- [ ] Noto Serif Vithkuqi
- [ ] Noto Sans Latin Extended-F
- [ ] Noto Sans Old Sogdian
- [ ] Noto Sans Sogdian
- [ ] Noto Serif Old Uyghur
- [ ] Noto Sans Chorasmian
- [ ] Noto Sans Elymaic
- [ ] Noto Sans Khojki Extensions
- [ ] Noto Sans Newa Extensions
- [ ] Noto Serif Ahom Extensions
- [ ] Noto Serif Dogra
- [ ] Noto Serif Dives Akuru
- [ ] Noto Sans Nandinagari
- [ ] Noto Sans Zanabazar Square
- [ ] Noto Sans Soyombo
- [ ] Noto Serif Makasar
- [ ] Noto Sans Kawi
- [ ] Noto Sans Lisu Extensions
- [ ] Noto Sans Cypro Minoan
- [ ] Noto Sans Anatolian Hieroglyphs
- [ ] Noto Sans Tangsa
- [ ] Noto Sans Medefaidrin
- [ ] Noto Serif Tangut
- [ ] Noto Serif Khitan Small Script
- [ ] Noto Sans Hentaigana
- [ ] Noto Sans Nushu
- [ ] Noto Znamenny Musical Notation
- [ ] Noto Music
- [ ] Noto Sans Symbols 2 Kaktovik Numerals
- [ ] Noto Sans Mayan Numerals
- [ ] Noto Sans SignWriting
- [ ] Noto Sans Latin Extended-G
- [ ] Noto Serif Toto
- [ ] Noto Sans Nag Mundari
- [ ] Noto Sans Indic Siyaq Numbers
- [ ] Noto Serif Ottman Siyaq
- [ ] Noto Sans Symbols 2 Chess Symbols
- [ ] Noto Sans Symbols 2 Symbols for Legacy Computing

**Comment by eliheuer** [comment]
iOS, iPadOS, macOS, watchOS, and tvOS, etc are beyond out control in this repo, please file an issue with Apple.
