### ISSUE TITLE
Update Overpass

### ISSUE THREAD

**Issue by mrleblanc101** [google/fonts#6818]
**Font Project Git Repo URL:** 
https://github.com/RedHatOfficial/Overpass/tree/master
**Current version:**
No idea
**New available version:**
4.0.0
**Super short description of the upgrade:**
Added support for tabular number. `font-variant-numeric: tabular-nums;`

**Comment by kenmcd** [comment]
Where did you find a v4.0.0?
It is not in the repository.

**Comment by mrleblanc101** [comment]
https://github.com/RedHatOfficial/Overpass/issues/59

Maybe I'm misunderstanding something. I changed my Google font to a self-hosted version from Redhat git repo and now I can make tabular numbers works.

**Comment by thlinard** [comment]
> Where did you find a v4.0.0? It is not in the repository.

No, there is no **release** of version 4, but version 4 is the version of the repository (like the version of Google Fonts, by the way — the problem of missing OpenType features in the version served by the API is a different issue, and a very old one btw).

**Comment by mrleblanc101** [comment]
> the problem of missing OpenType features in the version served by the API is a different issue, and a very old one btw

And what is the solution ?

**Comment by thlinard** [comment]
> > the problem of missing OpenType features in the version served by the API is a different issue, and a very old one btw
> 
> And what is the solution ?

For the moment? Self-hosting.

**Comment by RosaWagner** [comment]
@mrleblanc101 thanks for your report. Indeed GF API subsets non-required opentype features. This is unfortunately not in our hand at the moment, better to self host the font to access its full potential.
