### ISSUE TITLE
What characters will be added to Noto Sans Symbols 2 in Q3?

### ISSUE THREAD

**Issue by AshtonTameirao25** [google/fonts#6822]
#This issue also works for requesting features. 

**Describe the issue**
A clear and concise description of what the issue is.

**To Reproduce**
Steps to reproduce the behavior.

**Expected behavior**

**Additional context**
Add any other context about the problem here (OS version, browser, printer…)

**Screenshots**

**Comment by eliheuer** [comment]
Q3 is over, this is Q4 now.

You can just look at the incoming pull requests and figure it out: https://github.com/google/fonts/pulls
