### ISSUE TITLE
How do I update or add a Noto Font in Google Fonts?

### ISSUE THREAD

**Issue by AshtonTameirao25** [google/fonts#6823]
#This issue also works for requesting features. 

**Describe the issue**
A clear and concise description of what the issue is.

**To Reproduce**
Steps to reproduce the behavior.

**Expected behavior**

**Additional context**
Add any other context about the problem here (OS version, browser, printer…)

**Screenshots**

**Comment by eliheuer** [comment]
Here is some info for you: https://fonts.google.com/noto/contribute#how-you-can-help-with-noto
