### ISSUE TITLE
Add Bomberg Display Sans

### ISSUE THREAD

**Issue by iframefonts** [google/fonts#6825]
**Font Project Git Repo URL: https://github.com/iframefonts/bomberg-sans/**

**Super short description of the Font Family: Bomberg Sans**

**Requirements:**

Google Fonts will publish only fonts that match its requirements. Please familiarize yourself with the complete documentation in the [Google Fonts Guide](https://googlefonts.github.io/gf-guide/) (GF-Guide) and ensure your font project complies with them before submitting the font family. You can also use the [Google Fonts Project Template](https://github.com/googlefonts/googlefonts-project-template), which will help you create a repository that follows the needed structure and includes build requirements.

By filling this issue, you can confirm the project meets the  requirements (by ticking the cases or putting x between the square brackets in text mode):

- [x] I read, agree, and comply with the full [contributing requirements](https://googlefonts.github.io/gf-guide/index#pre-production-getting-your-fonts-ready-for-gf)
- [x] The entire font project is licensed under the [OFL](https://scripts.sil.org/cms/scripts/page.php?site_id=nrsi&id=OFL)
- [x] There is no "Reserved Font Name" mention in the OFL license
- [x] Family name is unique according to [namecheck.fontdata.com](https://namecheck.fontdata.com/)
- [x] The font supports at least [GF Latin Core glyphset](https://github.com/googlefonts/glyphsets/tree/main/GF_glyphsets/Latin/)
- [x] The repository respect the [upstream repo structure](https://googlefonts.github.io/gf-guide/upstream.html)
- [x] The source files are available in the repository
- [x] I am the author of the font, or the author agreed to this submission
- [x] I will maintain the repository and participate in the onboarding process (addressing, solving, and responding to issues, merging pull requests, etc)

**Image:**
<img width="1440" alt="Desktop-1" src="https://github.com/google/fonts/assets/146736987/25e0d90c-66f8-429e-966e-c2eb89a64733">

Attach here a pic or a screenshot of the font. One image is enough, it can be a few letters, to give a quick overview.

**Comment by eliheuer** [comment]
Thanks for using the Google Fonts Project Template for the Git repo, I added this to the backlog of fonts to review

**Comment by iframefonts** [comment]
thank you @eliheuer !

**Comment by davelab6** [comment]
From the preview image this looks good to include to me, and should be fully reviewed :)

**Comment by vv-monsalve** [comment]
Hello @iframefonts, we finally got the time to review the family. 

We think that is a great start; the typeface has personality and an interesting concept for contrast. Unfortunately, it doesn't match technical and design expectations yet. We really encourage you to keep up with the work, and in the following, please find the main points where you can improve and also related links:

<img width="2084" alt="Screenshot 2024-08-22 at 14 28 32" src="https://github.com/user-attachments/assets/5d38f24f-c835-4c30-bad2-415d3339d583">

- The outlines exhibit some quality issues, such as uneven distribution of the glyphs' weights and widths, missing nodes at the extremes, and rounded connections that are “pushed in”, among others. We recommend reviewing the chapter on [outline quality](https://googlefonts.github.io/gf-guide/outlines.html), which explains some initial technical aspects of the subject.
- Some diacritics need to be positioned correctly. Please take a look at the [diacritics chapter](https://googlefonts.github.io/gf-guide/diacritics.html) of our documentation, as well as the other useful links suggested at the end of it.
- To create the font and understand other GF specificities, please familiarize yourself with the entire [Documentation](https://googlefonts.github.io/gf-guide/index), especially these chapters: [Font file requirements](https://googlefonts.github.io/gf-guide/requirements.html) and [VF specificities](https://googlefonts.github.io/gf-guide/variable)

You can also learn more about type design on this amazing website: https://typedesignschool.com

Don't hesitate to re-open a submission issue when you think the font is ready again ;)

**Comment by tphinney** [comment]
Hey, this is a great start, and clearly represents a ton of work.

With regard to the diacritics, some appear in the wrong character (ogonek in tcedilla), wrong position top vs bottom (rcaron), or just badly positioned (dot on udotbelow, slash on lslash). Here is a great resource on central/eastern European diacritics: https://theinsectsproject.eu/

Regarding point placement, most of the type design books and courses have good info about points-at-extrema and not crossing over nodes. In the source for a few glyphs such as “a” you have retracted off-curve nodes (that is, an off-curve node that is right on top of its corresponding on-curve node), which is bad form.

**Comment by tphinney** [comment]
Also, there are a couple of letters assembled from components that probably should not be. For example, re-using the P for the R; the bowl of the P should come down just a little bit lower than that of the R.
