### ISSUE TITLE
ASAP font - add different font widths presets to the variable ttf files

### ISSUE THREAD

**Issue by lwchkg** [google/fonts#6828]
Font name: ASAP

**Describe the bug**
Condensed and expanded versions of the font should be shown after the variable font is installed, but does not.

**Screenshots**
![image](https://github.com/google/fonts/assets/4113719/f45a5046-12ad-41c3-bcd8-65a7830bd46e)

**Additional context**
OS: Windows 11

**Comment by kenmcd** [comment]
GF only includes the normal width instances.
And that is not likely to change anytime soon.

Often the upstream repository will include a version with all the instances.
The source files include 46 instances with five widths and nine weights (plus one duplicate ???).
It appears they used to have a VF with all the instances, but now it is only the minimal GF version (even in the version on their website - which is quite odd).
So you should create a request in the upstream repo.
Here: https://github.com/Omnibus-Type/Asap
Perhaps they will create a VF which is actually useful in applications like LibreOffice and Word which only support named instances.

**Comment by RosaWagner** [comment]
Hi @lwchkg, thanks for your request. @kenmcd is right. 
- If you use an app that properly supports variable fonts, then the other width are accessible through the slider and no additional instances are necessary.
- If you use an app that doesn't support variable fonts properly, and thus can't access other width through a slider, than we highly recommend to use the static families instead. If you download the zip file from Google Fonts platform, you will be able to use all kind of different width.


<img width="1680" alt="Screenshot 2023-10-05 at 12 39 35" src="https://github.com/google/fonts/assets/12222436/7b4b0ba2-8289-4a87-af21-33e9bccd9ca2">
<img width="904" alt="Screenshot 2023-10-05 at 12 40 17" src="https://github.com/google/fonts/assets/12222436/9c13172b-6e16-4339-a5ec-c21927e7b7f3">

**Comment by RosaWagner** [comment]
note: uninstall the variable font prior to installing the static files to avoid conflicts.
