### ISSUE TITLE
Update Alike

### ISSUE THREAD

**Issue by RosaWagner** [google/fonts#6838]
**Font Project Git Repo URL:**
https://github.com/cyrealtype/Alike

**Current version:**

**New available version:**

**Super short description of the upgrade:**
see discussion #6817 
- copyright update + description update
- family needs re-QA

**Bugs reported in this repo which this upgrade would fix:**
Search in the [issue tracker](https://github.com/google/fonts/issues) if there is some opened issues containing the font name.

**Comment by emmamarichal** [comment]
I sent a first PR, correcting all the fails: https://github.com/cyrealtype/Alike/pull/4 
But we need some design work. Also, the font has a RFN, @davelab6, how do we handle it?
