### ISSUE TITLE
Add NASALIZATION

### ISSUE THREAD

**Issue by nutsocharles** [google/fonts#6841]
![Screenshot 2023-10-07 171507](https://github.com/google/fonts/assets/147281042/c8de846d-8035-40a0-9fcc-98cf205617b6)
**Font Project Git Repo URL:**https://github.com/nutsocharles/NASALIZATION

**Super short description of the Font Family:**
Nasalization is an ultramodern sans serif typeface inspired by the NASA logo from 1975. It's the go-to typeface for depicting science, futurism, space exploration, and high-tech subjects. A slanted M and W will automatically flip or straighten up in OpenType-savvy programs based on adjacent characters. You can turn off the "standard ligatures" functionality in your software to disable the flipped-letter effect. To add a crossbar to the A, use your application's OpenType “stylistic alternates” function. Nasalization is available in six weights as well as some eye-catching italics. 

Most Latin-based European, Vietnamese, Greek, and most Cyrillic-based writing systems are supported, including the following languages. Afaan Oromo, Afar, Afrikaans, Albanian, Alsatian, Aromanian, Aymara, Azerbaijani, Bashkir, Bashkir (Latin), Basque, Belarusian, Belarusian (Latin), Bemba, Bikol, Bosnian, Breton, Bulgarian, Buryat, Cape Verdean, Creole, Catalan, Cebuano, Chamorro, Chavacano, Chichewa, Crimean Tatar (Latin), Croatian, Czech, Danish, Dawan, Dholuo, Dungan, Dutch, English, Estonian, Faroese, Fijian, Filipino, Finnish, French, Frisian, Friulian, Gagauz (Latin), Galician, Ganda, Genoese, German, Gikuyu, Greenlandic, Guadeloupean Creole, Haitian Creole, Hawaiian, Hiligaynon, Hungarian, Icelandic, Igbo, Ilocano, Indonesian, Irish, Italian, Jamaican, Kaingang, Khalkha, Kalmyk, Kanuri, Kaqchikel, Karakalpak (Latin), Kashubian, Kazakh, Kikongo, Kinyarwanda, Kirundi, Komi-Permyak, Kurdish, Kurdish (Latin), Kyrgyz, Latvian, Lithuanian, Lombard, Low Saxon, Luxembourgish, Maasai, Macedonian, Makhuwa, Malay, Maltese, Māori, Moldovan, Montenegrin, Nahuatl, Ndebele, Neapolitan, Norwegian, Novial, Occitan, Ossetian, Ossetian (Latin), Papiamento, Piedmontese, Polish, Portuguese, Quechua, Rarotongan, Romanian, Romansh, Russian, Rusyn, Sami, Sango, Saramaccan, Sardinian, Scottish Gaelic, Serbian, Serbian (Latin), Shona, Sicilian, Silesian, Slovak, Slovenian, Somali, Sorbian, Sotho, Spanish, Swahili, Swazi, Swedish, Tagalog, Tahitian, Tajik, Tatar, Tetum, Tongan, Tshiluba, Tsonga, Tswana, Tumbuka, Turkish, Turkmen (Latin), Tuvaluan, Ukrainian, Uzbek, Uzbek (Latin), Venda, Venetian, Vepsian, Vietnamese, Võro, Walloon, Waray-Waray, Wayuu, Welsh, Wolof, Xavante, Xhosa, Yapese, Zapotec, Zarma, Zazaki, Zulu and Zuni.   

**Requirements:**

Google Fonts will publish only fonts that match its requirements. Please familiarize yourself with the complete documentation in the [Google Fonts Guide](https://googlefonts.github.io/gf-guide/) (GF-Guide) and ensure your font project complies with them before submitting the font family. You can also use the [Google Fonts Project Template](https://github.com/googlefonts/googlefonts-project-template), which will help you create a repository that follows the needed structure and includes build requirements.

By filling this issue, you can confirm the project meets the  requirements (by ticking the cases or putting x between the square brackets in text mode):

- [X ] I read, agree, and comply with the full [contributing requirements](https://googlefonts.github.io/gf-guide/index#pre-production-getting-your-fonts-ready-for-gf)
- [X ] The entire font project is licensed under the [OFL](https://scripts.sil.org/cms/scripts/page.php?site_id=nrsi&id=OFL)
- [X ] There is no "Reserved Font Name" mention in the OFL license
- [X ] Family name is unique according to [namecheck.fontdata.com](https://namecheck.fontdata.com/)
- [X ] The font supports at least [GF Latin Core glyphset](https://github.com/googlefonts/glyphsets/tree/main/GF_glyphsets/Latin/)
- [X ] The repository respect the [upstream repo structure](https://googlefonts.github.io/gf-guide/upstream.html)
- [X ] The source files are available in the repository
- [X ] I am the author of the font, or the author agreed to this submission
- [X ] I will maintain the repository and participate in the onboarding process (addressing, solving, and responding to issues, merging pull requests, etc)

**Image:**
![Screenshot 2023-10-07 171507](https://github.com/google/fonts/assets/147281042/9211f163-0a41-47e5-b5bb-377d00e773a2)

**Comment by RosaWagner** [comment]
Hi @nutsocharles, thanks for your submission. Unfortunately this is not an open-source font and Google Fonts can't onboard it. Typodermics is making one style of the family accessible for free, but it doesn't make it an open font that everyone can distribute. If you read the license attached with the file you will see that it is also illegal to distribute it on the web if you are not an official distributors of the font, I would therefore recommend you take down the github repo you made to host the file.
