### ISSUE TITLE
Can't download fonts, console shows syntax error

### ISSUE THREAD

**Issue by justintemps** [google/fonts#6845]
#This issue also works for requesting features. 

**Describe the issue**
It's not possible to download a font family. The Download circle closes but the font never downloads. I see this in the console when I try. 

<img width="916" alt="image" src="https://github.com/google/fonts/assets/12401179/3f7d0f2f-612f-493f-b04e-c5266d0eed53">

**To Reproduce**
1. Navigate to this page: https://fonts.google.com/noto/specimen/Noto+Sans+Arabic
2. Click the download button in the top right hand corner

**Expected behavior**
The font family should download

**Additional context**
https://whatismybrowser.com/w/AXJ5F47

**Comment by MrFarhan** [comment]
**Facing same issue, i am unable to download the fonts**

![Screenshot 2023-10-10 at 4 33 10 PM](https://github.com/google/fonts/assets/26528236/d3ee7123-97ca-4934-90d3-f4cb1a1b70cf)

**Comment by chrissimpkins** [comment]
Thank you very much for reporting this!  Our engineering team is looking into it today.

**Comment by jaysrobinson** [comment]
We also have this exact issue, as above - as does our entire design studio. We tried it on several different machines, across Safari and Chrome. Download ring completes but nothing happens and get the Syntax error in Dev tab.
