### ISSUE TITLE
Will the Noto Hentaigana Font be Sans or Serif?

### ISSUE THREAD

**Issue by AshtonTameirao25** [google/fonts#6847]
#This issue also works for requesting features. 

**Describe the issue**
A clear and concise description of what the issue is.

**To Reproduce**
Steps to reproduce the behavior.

**Expected behavior**

**Additional context**
Add any other context about the problem here (OS version, browser, printer…)

**Screenshots**

**Comment by AshtonTameirao25** [comment]
Make sure you comment something.

**Comment by MiguelX413** [comment]
I'm interested in a Noto Sans Hentaigana.
