### ISSUE TITLE
Update Gelasio

### ISSUE THREAD

**Issue by EbenSorkin** [google/fonts#6869]
**Font Project Git Repo URL:** https://github.com/SorkinType/Gelasio

**Current version:** 1.007

**New available version:** 1.008

**Super short description of the upgrade:**
Extended Glyph set to GF Africa Pri, Improved diacritics, and added other easy language support from 'Beyond' glyph set. Added currency and other Symbols, Added spaces, added NSM localization, and changed ENg to the new standard construction. Updated source metadata so it builds correctly in Fontmake and passes the new font Bakery

**Bugs reported in this repo which this upgrade would fix:**
None. However, an unreported bug in non-combining dieresis was fixed.

**Comment by EbenSorkin** [comment]
The changes Denis an Neil asked for in his issue are done now, but the possible changes to glyph set in Africa Pri Denis recently suggested are not. I'll look to resolve what to do this Wed and hopefully, it can be ready to onboard that day.

**Comment by EbenSorkin** [comment]
I added the glyphs requested by Denis here: https://github.com/googlefonts/glyphsets/pull/137 which were Ɛ ɛ Ɲ ɲ Ɔ ɔ

**Comment by EbenSorkin** [comment]
pushed

**Comment by EbenSorkin** [comment]
There may be one more fix to put in re: anchors

**Comment by chrissimpkins** [comment]
See the latest update to the PriAfrican glyph set based on feedback from Neil and Denis

https://github.com/googlefonts/glyphsets/pull/137/commits/772fe9c07aab90108d70b2907657975a562b8aff

**Comment by EbenSorkin** [comment]
Updated to support CCMP made letters for PRI and parts of SSA.

**Comment by EbenSorkin** [comment]
I think this can be onboarded now.

**Comment by EbenSorkin** [comment]
Updated with localization for Eng recommended by Denis

**Comment by EbenSorkin** [comment]
Denis made some excellent updates and I have added some diacritic placement refinements. This is again ready.

**Comment by emmamarichal** [comment]
Hi @EbenSorkin! Fonts are ready, but I noticed there is no kerning at all. Would you like to add some? Gelasio seams to share the same metrics than Georgia, maybe you can just copy past them?
Thanks!
