### ISSUE TITLE
Update Alatsi

### ISSUE THREAD

**Issue by EbenSorkin** [google/fonts#6873]
**Font Project Git Repo URL:** https://github.com/SorkinType/Alatsi

**Current version:** 1.005

**New available version:** 1.006

**Super short description of the upgrade:**
Improve language coverage. This is not quite full African support but is much more than GF Africa Pri

**Bugs reported in this repo which this upgrade would fix:**
None.

**Comment by EbenSorkin** [comment]
Additional kerning was added today and an additional letter. It still passes fontbakery.

**Comment by EbenSorkin** [comment]
Also it now covers 527 languages of Latin script which is past SSA and almost Beyond.

**Comment by EbenSorkin** [comment]
This has the CCMP check done and it ready to onboard.

**Comment by EbenSorkin** [comment]
Updated with localization for Eng recommended by Denis

**Comment by yanone** [comment]
I skipped posting the first upstream PR here, but here's a second one from today: https://github.com/SorkinType/Alatsi/pull/7
