### ISSUE TITLE
FiraSans missing characters whenever 'f' and 'i' are next to each other?

### ISSUE THREAD

**Issue by Sprinkles22** [google/fonts#688]
Having a truly odd problems with Fira Sans - have tried both loading from my server and directly linking to google fonts, and in either case any instance of 'f' and 'i' touching results in both characters showing blank in Chrome on my PC as well as my supervisor's. This is not happening in IE...

Any ideas on what I can do for this?

http://morris.caitlinalexander.net

http://i68.tinypic.com/xngahi.jpg

http://i66.tinypic.com/2s9ztdz.jpg

http://i64.tinypic.com/4t3wj7.jpg

**Comment by m4rc1e** [comment]
Hey @Sprinkles22,

[jsbin](http://jsbin.com/?html,output) is super useful to diagnose these issues. I really appreciate the image, url and effort :-)

I've quickly mocked up a jsbin sample of the [issue](http://jsbin.com/bupekagece/edit?html,output)

I'm running OS X V10.11.6 with Chrome Version 56.0.2924.87 (64-bit). Everything seems to be working just fine for me

![screen shot 2017-03-02 at 21 44 11](https://cloud.githubusercontent.com/assets/7525512/23528325/64039728-ff91-11e6-837f-079315845e93.png)

Please check you do not have an old version of Fira installed on your machine locally. Clearing the Browser cache will also help. Apologies if this sounds like sucking eggs. I often get caught out with this as well.

Regards,
Marc

**Comment by davelab6** [comment]
@m4rc1e thanks for the explanation. @Sprinkles22 please reopen if you have further concerns :)

**Comment by sahibsingh** [comment]
Hello, 

I have same issue as @Sprinkles22, yeah i know @m4rc1e already provided us jsbin link, i didn't recognize why this happens with me, when i create webfontkit from fontsquirrel then same thing happens characters is missing whenever 'f' and 'i' are next to each other, but when i load link file direct from google then font appears good.
I don't know what and where is the issue.

![firefox with webfontkit ](https://cloud.githubusercontent.com/assets/3992135/24598922/91fa92b0-186b-11e7-8983-ae9e423dc38d.jpg)
![Google Chrome with webfontkit](https://cloud.githubusercontent.com/assets/3992135/24598945/a5f2f6d6-186b-11e7-9acd-9aa2382e7b42.jpg)
![iPad Air](https://cloud.githubusercontent.com/assets/3992135/24598961/b4e50418-186b-11e7-9526-9193db2f632b.jpg)
![Microsoft Edge](https://cloud.githubusercontent.com/assets/3992135/24599003/dfecb76e-186b-11e7-8ef6-4ec16d31df30.jpg)

And When i load font styles direct from Google 
![Firefox Direct Google](https://cloud.githubusercontent.com/assets/3992135/24599023/fda80876-186b-11e7-88bf-87cf21b67afb.jpg)
![google-chrome-live](https://cloud.githubusercontent.com/assets/3992135/24599109/4e6023d4-186c-11e7-83ad-0ebd87a876a9.jpg)

**Comment by m4rc1e** [comment]
@sahibsingh Thanks, I'm reopening this.

**Comment by m4rc1e** [comment]
@sahibsingh Here's my results using Browser stack on my jsbin:

Ipad Air 2, IOS 5:
![screen shot 2017-04-03 at 10 36 10](https://cloud.githubusercontent.com/assets/7525512/24603635/8959c8b8-1859-11e7-9187-63144b8c04e2.png)


Win 10 Chrome 52.0:
![screen shot 2017-04-03 at 10 36 10](https://cloud.githubusercontent.com/assets/7525512/24603672/a8ae97ac-1859-11e7-9933-24699325fc00.png)


I still can't replicate the issue. Are you sure you don't have an older version installed locally?

GF hosts v4.203

**Comment by sahibsingh** [comment]
Thanks @m4rc1e for the quick reply, I sort out this issue by using Font originally form Firefox "https://mozilla.github.io/Fira/", now everything is good on all browsers.

Thanks

**Comment by m4rc1e** [comment]
@sahibsingh thanks.
