### ISSUE TITLE
Remove the glyph-substitution table from Seoul Hangang

### ISSUE THREAD

**Issue by IvanUkhov** [google/fonts#6889]
**Describe the bug**
The glyph-substitution table has zero length, which is not adequate according to the specification.

**To Reproduce**
```shell
ttx -l ./ofl/seoulhangang/SeoulHangang-Light.ttf
```

**Expected behavior**
It should be absent.

**Comment by RosaWagner** [comment]
Hi @IvanUkhov, thanks for your bug reports. The fonts your are reporting are quite old, not well produced, not popular and, for some of them, not even listed on `fonts.google.com`. Unfortunately if the sources are not accessible, we can't rebuild them anymore and so we can't fix them. For the others, except if there is an issue that prevents from using the font, Google Fonts won't take time and budget to fix them. A wrong checksum doesn't prevent from using the font.

Don't be offended if I close "as not planned" the issues your opened.

**Comment by IvanUkhov** [comment]
Of course. I understand. Thank you!
