### ISSUE TITLE
Fix the checksum of the glyph-substitution table in Lao Muang Khong

### ISSUE THREAD

**Issue by IvanUkhov** [google/fonts#6890]
**Describe the bug**
The checksum is incorrect.

**To Reproduce**
```python
from fontTools import ttLib

ttLib.TTFont("./ofl/laomuangkhong/LaoMuangKhong-Regular.ttf", checkChecksums=2)["GSUB"]
```

**Expected behavior**
The checksum should be correct.

**Comment by RosaWagner** [comment]
Thanks for reporting, will fix by deleting from this repo.
