### ISSUE TITLE
Fix the checksum of the font header in Kaushan Script

### ISSUE THREAD

**Issue by IvanUkhov** [google/fonts#6892]
**Describe the bug**
The checksum is incorrect.

**To Reproduce**
```python
from fontTools import ttLib

ttLib.TTFont("./ofl/kaushanscript/KaushanScript-Regular.ttf", checkChecksums=2)["head"]
```

**Expected behavior**
The checksum should be correct.

**Comment by RosaWagner** [comment]
cf answer in https://github.com/google/fonts/issues/6889#issuecomment-1781196726
