### ISSUE TITLE
Fix the checksum of the font header in Iceland

### ISSUE THREAD

**Issue by IvanUkhov** [google/fonts#6893]
**Describe the bug**
The checksum is incorrect.

**To Reproduce**
```python
from fontTools import ttLib

ttLib.TTFont("./ofl/iceland/Iceland-Regular.ttf", checkChecksums=2)["head"]
```

**Expected behavior**
The checksum should be correct.

**Comment by RosaWagner** [comment]
Cf answer in https://github.com/google/fonts/issues/6889#issuecomment-1781196726
