### ISSUE TITLE
More Classifications for Filters

### ISSUE THREAD

**Issue by troyjack1** [google/fonts#6895]
#This issue also works for requesting features. 

Please add more classification filters to fonts.google.com. For example: When you select Sans Serif, the only classifications are Display, Handwriting, Mono and Not Text. Makes it difficult to find an adequate font when searching for a particular classification, like Grotesque, Humanist, or Geometric. When trying to narrow down to a specific classification, too many "novelty" fonts are included in results.
![Screenshot 2023-10-24 at 8 32 29 AM](https://github.com/google/fonts/assets/114692950/cf343cb5-6d9e-4066-9bcc-3eb8e620d43a)

**Comment by eliheuer** [comment]
Thanks @troyjack1! We are currently in the process of adding exactly what you are asking for here, sometime next year, hopefully early, there will be more categories like Grotesque, Humanist, or Geometric, etc, and improved search.
