### ISSUE TITLE
Update Noto Music

### ISSUE THREAD

**Issue by AshtonTameirao25** [google/fonts#6898]
**Font Project Git Repo URL:**

**Current version:**

**New available version:**

**Super short description of the upgrade:**
(expand style, expand glyphset, improve rendering, bug fix…)

**Bugs reported in this repo which this upgrade would fix:**
Search in the [issue tracker](https://github.com/google/fonts/issues) if there is some opened issues containing the font name.
![2023-10-24](https://github.com/google/fonts/assets/146303618/e59187e0-3abf-482a-adb7-24331caaa114)

**Comment by eliheuer** [comment]
Thanks! The about and license page on Google Fonts for Noto Music has a link where you give feedback: https://fonts.google.com/noto/specimen/Noto+Music/about?noto.query=noto+music

The Noto project maintainers know about unicode updates and will implement them eventually.
