### ISSUE TITLE
Saanjo Chanan Mukh (Punjabi & Allied)

### ISSUE THREAD

**Issue by ejaz-saanju** [google/fonts#6899]
**[Font Project Git Repo URL:](https://github.com/ejaz-saanju/chanan-mukh.git)**

**1st ever script for the language of masses: Punjabi & Allied**

![Saanjo - Chanan Mukh](https://github.com/google/fonts/assets/147651839/10b342bd-310a-45d1-8b9e-28e553c7fc3e)

**Requirements:**

Google Fonts will publish only fonts that match its requirements. Please familiarize yourself with the complete documentation in the [Google Fonts Guide](https://googlefonts.github.io/gf-guide/) (GF-Guide) and ensure your font project complies with them before submitting the font family. You can also use the [Google Fonts Project Template](https://github.com/googlefonts/googlefonts-project-template), which will help you create a repository that follows the needed structure and includes build requirements.

By filling this issue, you can confirm the project meets the  requirements (by ticking the cases or putting x between the square brackets in text mode):

- [x] I read, agree, and comply with the full [contributing requirements](https://googlefonts.github.io/gf-guide/index#pre-production-getting-your-fonts-ready-for-gf)
- [x] The entire font project is licensed under the [OFL](https://scripts.sil.org/cms/scripts/page.php?site_id=nrsi&id=OFL)
- [x] There is no "Reserved Font Name" mention in the OFL license
- [x] Family name is unique according to [namecheck.fontdata.com](https://namecheck.fontdata.com/)
- [x] The font supports at least [GF Latin Core glyphset](https://github.com/googlefonts/glyphsets/tree/main/GF_glyphsets/Latin/)
- [x] The repository respect the [upstream repo structure](https://googlefonts.github.io/gf-guide/upstream.html)
- [x] The source files are available in the repository
- [x] I am the author of the font, or the author agreed to this submission
- [ ] I will maintain the repository and participate in the onboarding process (addressing, solving, and responding to issues, merging pull requests, etc)

**Image:**

Attach here a pic or a screenshot of the font. One image is enough, it can be a few letters, to give a quick overview.

**Comment by eliheuer** [comment]
Thanks for the submission @ejaz-saanju! I have added it to the list of fonts to review for potentially onboarding to Google Fonts. 

Are you the designer of this font? Please tell us more about it.

Are there source files? I only see a compiled `ttf` in the Git repository.

Please read the Google Fonts guide to understand the requirements for onboarding a font to Google Fonts: https://googlefonts.github.io/gf-guide/

In your post you checked: "The entire font project is licensed under the [OFL](https://scripts.sil.org/cms/scripts/page.php?site_id=nrsi&id=OFL)", but looking at the Git I see the Apache License, are you ok with using the OFL instead?

**Comment by ejaz-saanju** [comment]
Hello Eli Heuer,

I'm pleased to receive your message and would like to address your inquiries below:

  1.
Yes, I am the exclusive designer and owner of this script font, known as Saanjo Chanan Mukh. To provide some context, Punjabi is one of the few languages in the world that is written in multiple scripts. It never had a dedicated script of its own, which is why I dedicated my entire life to creating this font. You can find more information about it at https://saanjo.com/saanjo-font/, and you can also watch my video where I teach this font to interested individuals at this link<https://drive.google.com/file/d/1Sbn3dac6SKohYyp-uoDDuhnB1wC3T7NK/view?pli=1>. Additionally, you can explore details about the Saanjo keyboard<https://saanjo.com/saanjo-keyboard-images/>, the founder<https://saanjo.com/about-founder/>, and information about Saanjo<https://saanjo.com/about-saanjo-2/>

  2.
Thanks for pointing out. I have now uploaded the source file (.fcp) to the repo<https://github.com/ejaz-saanju/chanan-mukh>, which was originally created with Font <https://fontcreator.software.informer.com/download> Creator<https://fontcreator.software.informer.com/download/#downloading> software about 15 years back. The given .TTF font file also be used with other font software's like Font Forge<https://fontforge.org/en-US/downloads/windows-dl/>

  3.
I have signed an agreement with Google at https://cla.developers.google.com/ (See. attached). I did not find an option for OFL in GitHub, so I opted for the Apache license instead. If you can provide guidance on using OFL, I am open to making that change. It is important for me that this font is public, but cannot be modified, changed or altered in any way

Please feel free to share your thoughts. I am eager to assist in any way possible to have this script recognized by Google.

Best regards,


Ejaz Mahmood

Founder of Saanjo Script - Punjabi & Allied

P  +92 300 2575832
E  ***@***.******@***.***>

W https://saanjo.com/



________________________________

**Comment by ejaz-saanju** [comment]
@eliheuer I've been able to figure out OFL license. Its done. The source file is also uploaded and I have adjusted repo structure a bit.

Let me know if you need anything from my end to move forward

**Comment by RosaWagner** [comment]
Hi @ejaz-saanju, 

Unfortunately, Google Fonts can only onboard fonts which scripts are encoded in the Unicode. I see in the file that the glyphs are mapped to the latin characters which is not something Google Fonts can support. Indeed, it would mean that a text is readable only with using this font, and all documents using the font would become obsolete and unreadable when the script finally made it to Unicode. This practice is highly discouraged by linguists. 

Therefore we would recommend to first submit the script to the Unicode: this is a guide from their website on how to do so: http://www.unicode.org/pending/proposals.html?utm_source=webtekno. Is it a process you already started? Or is it already done and therefore it is only a font file issue we could fix?

Once the codepoints are allocated by the Unicode Consortium; it will be possible for companies to integrate them to some system fonts. A proposal could be made to the Noto collection as well. And of course, any new font such as Saanjo could be onboarded and use on Google Fonts.

**About the OFL or Apache license.** 
>  It is important for me that this font is public, but cannot be modified, changed or altered in any way

Unfortunately, that is not how the OFL/Apache licenses work. By giving such a license to the font, you allow anyone to appropriate the font and eventually modify, change or alter the design or the informations contained in the font. If you want to distribute the font for free, but forbid any modification, you can look into the different CC licenses (Creative Commons): https://creativecommons.org/share-your-work/cclicenses/. They have different options and a tool to help you choose that license that fits the most your expectations: https://chooser-beta.creativecommons.org. 

I am truly sorry it doesn't go in a the most forward direction for you here, the project looks fascinating and I hope we gave you enough answers to know how to continue this journey.

Best
Rosalie

**Comment by ejaz-saanju** [comment]
Hi @RosaWagner Thanks for the detailed response. The process of encoding Saanjo font to Unicode was started earlier, but it could not proceed. 

The Unicode Consortium informed me that the Saanjo Script needs to gain wider usage before they can proceed with my initial proposal. You may check the proposal I sent to them with the following link
[Initial Proposal for Encoding.pdf](https://github.com/google/fonts/files/13177747/Initial.Proposal.for.Encoding.pdf)

On the other hand, Google Font has mentioned that they require Unicode allocation first before they can incorporate the Saanjo keyboard. Unfortunately, without widespread adoption via mobile keyboards, it's challenging to promote the script to the public.

This has created a situation I'd like to call a "Circular Caught-Up." 

As a layman, I'd like to present the following points to help navigate this "Circular Caught-Up" situation:

1- I've successfully installed the Saanjo Font on my laptop. When I select it in the font selection window, my keyboard switches to Saanjo alphabets, with no other changes affecting the computer system. This applies to various applications like Microsoft Word and Excel, and even emails can be sent and received in Saanjo script on other computers by selecting Saanjo in their font selection window.

2- To facilitate the inclusion of the Saanjo script keyboard in Google, it might be beneficial to categorize it under "Punjabi" or "Saanjo Punjabi" to prevent interference with other languages and their fonts during downloading and installation on mobile devices.

3- I have been using Saanjo Fonts for the past 15 years on my computer, converting them into images for social media campaigns and my website. Despite this effort, I have not found a way to break out of this "Circular Caught-Up."

The question remains: Will the Unicode Consortium, Google Font, software engineers, and AI come together to help me navigate this "Circular Caught-Up"? 

I have no definitive answer at this time. Please advise

**Comment by RosaWagner** [comment]
Ah indeed the script has to be adopted my a certain number of people by writing before getting into the unicode as a guarantee of its wide-adoption. It has happen in the past that some characters were introduced to never be used, and they have therefore took codepoint spaces that will never be available anymore. I understand the challenge that it represents. The unicode consortium may be convinced by the script if it becomes a State initiative.

In any case Google Fonts doesn't deal with custom keyboard layout, this is a user/OS set up. It won't be possible for them to onboard the font. So closing this issue but wishing you the best. Thanks for linking the proposal it is very interesting.

**Comment by ejaz-saanju** [comment]
Thank you, @RosaWagner. I comprehend that having a Unicode-encoded font is a prerequisite for progressing with this. I will explore this requirement and assess its feasibility. My intention is to retain this issue or ticket for potential future use. Although we may temporarily close it, I hope to be able to reopen it when I am better prepared to reapply with Google Fonts.
