### ISSUE TITLE
Add new Lodrina family styles ( Thin, Book, Black )

### ISSUE THREAD

**Issue by jlsync** [google/fonts#69]
Google fonts already contains

Londrina Solid
Londrina Sketch
Londrina Shadow
Londrina Outline

@marcelommp has added 3 new styles/weights to the family: Thin, Book, and Black. They are available here: https://github.com/marcelommp/Londrina-Typeface

The existing Londrina fonts can be combined together for different effects, so including these new styles will also add more value to the existing ones!

**Comment by davelab6** [comment]
Awesome!

**Comment by m4rc1e** [comment]
Londrina was updated 2017-08-28

![screen shot 2017-08-31 at 10 34 56](https://user-images.githubusercontent.com/7525512/29916906-219696f2-8e38-11e7-88c6-760a9f17f81b.png)

Our api does not accept Book weights so we did the following, https://github.com/marcelommp/Londrina-Typeface/issues/1#issue-242386753

**Comment by marcelommp** [comment]
Thanks! 👍
