### ISSUE TITLE
Add Geist & Geist Mono

### ISSUE THREAD

**Issue by davelab6** [google/fonts#6922]
https://github.com/vercel/geist-font

- [x] Geist #8246 
- [x] Geist Mono #8264

**Comment by fakerybakery** [comment]
Unfort. Geist has the "reserved font name" clause. Opened an issue [there](https://github.com/vercel/geist-font/issues/41).

**Comment by kenmcd** [comment]
And the design coordinates are being used as the instance weights in the variable fonts.

**Comment by arnoldsandoval** [comment]
I think this can be closed? https://github.com/vercel/geist-font/issues/41#issuecomment-1791039360

**Comment by eliheuer** [comment]
There was some discussion about this being an Inter fork, and if the copy the font uses to describe itself if onboarded to Google Fonts should be changed to reflect that.

The bottom of the [Geist README](https://github.com/vercel/geist-font#inspiration) has this note linking to other fonts it was inspired by, and this would be included in the font description if onboarded to Google Fonts:
<img width="1051" alt="Screenshot 2023-11-16 at 10 35 12 AM" src="https://github.com/google/fonts/assets/5162664/2a2539b1-f733-4057-b7ce-85815324445d">

Below are some screenshots from the Geist and Inter source files showing how these two font are drastically different. Also note that Geist has a UPM of 1000, and Inter has a UPM of 2048. Even if Geist started as a fork of Inter, it is now a completely unique typeface.

There is nothing wrong with using an existing OFL font to start a project, The OFL is designed for that and encourages it. Forking saves time and money, as a font engineer, my job is to make font production as easy and cost effective as possible, so we can have more high-quality OFL fonts.

In my opinion font engineers and type designers should have a bias towards creating value for users, not doing “work” or being original. I'm fine with the copy only saying this font was inspired by Inter and not directly calling it a fork, but I would like to hear anyone else's opinions on this.

Geist:
<img width="824" alt="Screenshot 2023-11-16 at 10 21 33 AM" src="https://github.com/google/fonts/assets/5162664/52edc81e-38c2-4934-89a5-22187646ce49">
Inter:
<img width="806" alt="Screenshot 2023-11-16 at 10 22 15 AM" src="https://github.com/google/fonts/assets/5162664/c30ef0ac-2228-4d20-9c3f-35b054371138">
Geist:
<img width="864" alt="Screenshot 2023-11-16 at 10 29 13 AM" src="https://github.com/google/fonts/assets/5162664/ed1f4eab-f6b6-4fc2-adf2-673d8e3641c3">
Inter:
<img width="869" alt="Screenshot 2023-11-16 at 10 29 56 AM" src="https://github.com/google/fonts/assets/5162664/8cec97b1-1426-477c-a138-de29eb8cf7c6">
Geist:
<img width="810" alt="Screenshot 2023-11-16 at 10 30 58 AM" src="https://github.com/google/fonts/assets/5162664/98088e24-3c12-4481-b87d-3c857b867665">
Inter:
<img width="917" alt="Screenshot 2023-11-16 at 10 31 09 AM" src="https://github.com/google/fonts/assets/5162664/2fafe332-8b03-473d-b1d6-989656ea6028">

**Comment by eliheuer** [comment]
There is some discussion about this being a fork of Inter here: https://twitter.com/rsms/status/1717999283662971205
<img width="736" alt="Screenshot 2023-11-16 at 11 12 43 AM" src="https://github.com/google/fonts/assets/5162664/cb04b3c7-3d0f-4c31-be9d-2e2f6abf622d">

**Comment by chrissimpkins** [comment]
Added to our Q1 2024 onboarding queue for further review

**Comment by fakerybakery** [comment]
Hi, is there any update on this?

**Comment by yanone** [comment]
Inquired about how to proceed in [issue](https://github.com/vercel/geist-font/issues/99).

**Comment by vv-monsalve** [comment]
@guidoferreyra is helping the designers solve some issues and prepare the fonts for GF. I've filed an issue in his repo about the [VM](https://github.com/guidoferreyra/Geist/issues/1).

**Comment by vv-monsalve** [comment]
The font is ready for PR to GF. Upstream needs to cut a new release that includes the OFL.txt

**Comment by vv-monsalve** [comment]
PRs were made to GF for both fonts.
