### ISSUE TITLE
Add Moderustic

### ISSUE THREAD

**Issue by Tural** [google/fonts#6926]
**Font Project Git Repo URL:** https://github.com/Tural/moderustic

**Description:**  Moderustic is a versatile typeface meticulously designed for user interfaces, crafted with the aim of enhancing the user experience. This font maintains a consistent width across different styles, ensuring that your UI elements always occupy the same space on the page. It supports a variety of languages, including Latin, Cyrillic and Greek making it an ideal choice for designing user-friendly digital applications. Moderustic offers exceptional readability and adaptability, allowing you to create sleek and modern user interfaces that cater to a global audience.

**Requirements:**

Google Fonts will publish only fonts that match its requirements. Please familiarize yourself with the complete documentation in the [Google Fonts Guide](https://googlefonts.github.io/gf-guide/) (GF-Guide) and ensure your font project complies with them before submitting the font family. You can also use the [Google Fonts Project Template](https://github.com/googlefonts/googlefonts-project-template), which will help you create a repository that follows the needed structure and includes build requirements.

By filling this issue, you can confirm the project meets the  requirements (by ticking the cases or putting x between the square brackets in text mode):

- [x] I read, agree, and comply with the full [contributing requirements](https://googlefonts.github.io/gf-guide/index#pre-production-getting-your-fonts-ready-for-gf)
- [x] The entire font project is licensed under the [OFL](https://scripts.sil.org/cms/scripts/page.php?site_id=nrsi&id=OFL)
- [x] There is no "Reserved Font Name" mention in the OFL license
- [x] Family name is unique according to [namecheck.fontdata.com](https://namecheck.fontdata.com/)
- [x] The font supports at least [GF Latin Core glyphset](https://github.com/googlefonts/glyphsets/tree/main/GF_glyph![tamoderustic5](https://github.com/google/fonts/assets/518994/13f3682b-dd2c-4610-9483-607c6b3c596a))
- [x] The repository respect the [upstream repo structure](https://googlefonts.github.io/gf-guide/upstream.html)
- [x] The source files are available in the repository
- [x] I am the author of the font, or the author agreed to this submission
- [x] I will maintain the repository and participate in the onboarding process (addressing, solving, and responding to issues, merging pull requests, etc)

**Image:** ![tamoderustic5](https://raw.githubusercontent.com/Tural/Moderustic/main/documentation/moderusticv2.1.png)

Attach here a pic or a screenshot of the font. One image is enough, it can be a few letters, to give a quick overview.

**Comment by RosaWagner** [comment]
Hi @Tural, thanks for your submission. We'll review the font in the next month or so and will get back to you if it gets accepted or rejected. Thanks for your patience.

**Comment by eliheuer** [comment]
I'm reviewing the sources, UFO, and Glyphs files exported from FontLab have some outline issues: 
<img width="1710" alt="Screenshot 2023-12-07 at 6 22 30 AM" src="https://github.com/google/fonts/assets/5162664/ef59cbff-0048-4897-9c43-95a92160d93a">

**Comment by eliheuer** [comment]
Numerals have a non-standard design, to me it looks strange how the 2 has a much wider gap than the 3 between the almost touching elements. 

<img width="1710" alt="Screenshot 2023-12-07 at 6 31 52 AM" src="https://github.com/google/fonts/assets/5162664/143030fc-92d1-4f11-be42-e16039870b3d">

**Comment by eliheuer** [comment]
<img width="1710" alt="Screenshot 2023-12-07 at 6 41 14 AM" src="https://github.com/google/fonts/assets/5162664/adaf8fcc-773f-4af7-9f93-c4f973e928cf">

**Comment by eliheuer** [comment]
Here is the Behance page for the project: https://www.behance.net/gallery/130321655/TA-Moderustic-TYPEFACE

And the designers website: https://taft.work/

**Comment by eliheuer** [comment]
I also believe it is Google Fonts policy to not include acronyms appended to font names.

**Comment by eliheuer** [comment]
@Tural Hello, [Moderustic](https://github.com/google/fonts/issues/6926#top) was reviewed and given the OK for onboarding to Google Fonts in the first quarter of next year(2024).

Please see the Google Fonts Guide for the guidelines, requirements, and specifications: https://googlefonts.github.io/gf-guide/

I can help get things up to spec in the new year. Please ask any questions here. Thanks!

**Comment by Tural** [comment]
@eliheuer Hello. Thank you for your feedback and information. This is good news. Taking into account your comments, I will make changes and additions to the font.

**Comment by Tural** [comment]
Hello, @eliheuer . I updated Moderustic. Please check it out. Let me know any errors you encounter.

**Comment by Tural** [comment]
Hi @eliheuer @chrissimpkins  @RosaWagner  @jtbandes  I've updated Moderustic. I posted it under the label [I Font Upgrade]. I'm honestly not sure if I posted this correctly. Would you please watch if possible. Thanks
