### ISSUE TITLE
Oma

### ISSUE THREAD

**Issue by alapgoogle** [google/fonts#6931]
**Font Project Git Repo URL:**
https://github.com/alapgoogle/Oma

**Super short description of the Font Family:**
Oma in german means Grandma. This font is based on all the warm, fuzzy, over-eaten, loved, comfortable feelings when you think of your grandma. 
This idea was initially a part of branding for another project which got extended into a whole typeface of its own.

**Requirements:**

Google Fonts will publish only fonts that match its requirements. Please familiarize yourself with the complete documentation in the [Google Fonts Guide](https://googlefonts.github.io/gf-guide/) (GF-Guide) and ensure your font project complies with them before submitting the font family. You can also use the [Google Fonts Project Template](https://github.com/googlefonts/googlefonts-project-template), which will help you create a repository that follows the needed structure and includes build requirements.

By filling this issue, you can confirm the project meets the  requirements (by ticking the cases or putting x between the square brackets in text mode):

- [ ] I read, agree, and comply with the full [contributing requirements](https://googlefonts.github.io/gf-guide/index#pre-production-getting-your-fonts-ready-for-gf)
- [x ] The entire font project is licensed under the [OFL](https://scripts.sil.org/cms/scripts/page.php?site_id=nrsi&id=OFL)
- [x ] There is no "Reserved Font Name" mention in the OFL license
- [x ] Family name is unique according to [namecheck.fontdata.com](https://namecheck.fontdata.com/)
- [x ] The font supports at least [GF Latin Core glyphset](https://github.com/googlefonts/glyphsets/tree/main/GF_glyphsets/Latin/)
- [x ] The repository respect the [upstream repo structure](https://googlefonts.github.io/gf-guide/upstream.html)
- [ x] The source files are available in the repository
- [x ] I am the author of the font, or the author agreed to this submission
- [x ] I will maintain the repository and participate in the onboarding process (addressing, solving, and responding to issues, merging pull requests, etc)

**Image:**
![image](https://github.com/google/fonts/assets/149191897/bbc3fed1-4e0c-4261-96b7-7832d6bee369)

Attach here a pic or a screenshot of the font. One image is enough, it can be a few letters, to give a quick overview.

**Comment by alapgoogle** [comment]
Hi @RosaWagner, thanks for the quick response and helpful tips. I have started creating the expected glyphs but it seems like the "Latin core" section has 333 gylphs. Do I need to create all of them or there's a subset of minimum required?

**Comment by RosaWagner** [comment]
Latin_Core is the minimal subset required. It covers the languages from Europe and America spoken by more than 5M people.

**Comment by RosaWagner** [comment]
Closing this issue since the font does not match the requirement. @alapgoogle please feel free to re-open an issue when you think the font is complete :)

**Comment by alapgoogle** [comment]
Thanks Rosalie. I am working on completing it. Might take some time over
these holidays. :)
