### ISSUE TITLE
TRIVIA.md has incorrectly written words

### ISSUE THREAD

**Issue by krisztipely** [google/fonts#6941]
**Describe the bug**
Some words are not correctly written here: https://github.com/google/fonts/blob/main/TRIVIA.md

**To Reproduce**
1. Go to: https://github.com/google/fonts/blob/main/TRIVIA.md
2. Search: Interesting Libre Fonts Not In Google Fonts 
3. Check this line: Here is a list of some libre fonts made for special purposes (emoij, math, icon, etc) that are not available in Google Fonts.
    
**Expected behavior**
    "emoij" should be corrected to "emoji."
    "icon" should be pluralized as "icons.

**Comment by applecuckoo** [comment]
Just made a PR to fix the typos raised: #6945
