### ISSUE TITLE
Add Gothic Nguyen

### ISSUE THREAD

**Issue by vienvu1** [google/fonts#6950]
**Font Project Git Repo URL:**
https://github.com/TKYKmori/Gothic-Nguyen

**Super short description of the Font Family:**
This font is a sans-serif gothic typeface commissioned by the Han-Nom Revival Committee of Vietnam. It supports all the standard and simplified characters in the [Common Standard Han Nom Table](http://www.hannom-rcv.org/wi/index.php/%E6%A8%99%E6%BA%96%E5%8C%96:%E6%A6%9C%F0%A1%A8%B8%E6%BC%A2%E5%96%83%E6%BA%96). This font is based on Source Han Sans.

**Requirements:**

Google Fonts will publish only fonts that match its requirements. Please familiarize yourself with the complete documentation in the [Google Fonts Guide](https://googlefonts.github.io/gf-guide/) (GF-Guide) and ensure your font project complies with them before submitting the font family. You can also use the [Google Fonts Project Template](https://github.com/googlefonts/googlefonts-project-template), which will help you create a repository that follows the needed structure and includes build requirements.

By filling this issue, you can confirm the project meets the  requirements (by ticking the cases or putting x between the square brackets in text mode):

- [x] I read, agree, and comply with the full [contributing requirements](https://googlefonts.github.io/gf-guide/index#pre-production-getting-your-fonts-ready-for-gf)
- [x] The entire font project is licensed under the [OFL](https://scripts.sil.org/cms/scripts/page.php?site_id=nrsi&id=OFL)
- [x] There is no "Reserved Font Name" mention in the OFL license
- [x] Family name is unique according to [namecheck.fontdata.com](https://namecheck.fontdata.com/)
- [x] The font supports at least [GF Latin Core glyphset](https://github.com/googlefonts/glyphsets/tree/main/GF_glyphsets/Latin/)
- [ ] The repository respect the [upstream repo structure](https://googlefonts.github.io/gf-guide/upstream.html)
- [ ] The source files are available in the repository
- [x] I am the author of the font, or the author agreed to this submission
- [x] I will maintain the repository and participate in the onboarding process (addressing, solving, and responding to issues, merging pull requests, etc)

**Image:**

![gothic-nguyen](https://github.com/google/fonts/assets/148301222/995ebab3-e2e8-46aa-bdcb-aa7a396a19ab)

**Comment by RosaWagner** [comment]
Hi @vienvu1, thanks for your submission. Unfortunately we can't review fonts which repository is incomplete. Please read these chapters of the Google Fonts Guide to make sure you comply with the submission requirements: 
- https://googlefonts.github.io/gf-guide/onboarding.html
- https://googlefonts.github.io/gf-guide/upstream.html

We would need at least available sources (.glyphs or .ufo) to know if we can onboard the family.
