### ISSUE TITLE
Letters dropped from find function when font is rendered in PDF

### ISSUE THREAD

**Issue by jmente1** [google/fonts#6956]
I’m having an issue with the Roboto font when using it in a pdf generated by SAP Crystal Reports. No other font I use seems to have the same issue.

When using the “Find” function (in multiple PDF viewers), to search the document, the letter after the letter f seems to be missing from the search criteria.

For instance, when the word “butterfly” is in the document, it can’t be found. However, “butterfy” (“i” is missing) is there. I’ve also seen the same problem with the second i in “certificate”. See the screenshots below.

Has anyone reported this issue and if so, found a solution?

“butterfly” not found despite clearly being on the third line of text shown
![image](https://github.com/google/fonts/assets/41795015/72814187-ee8e-4c6f-b7d7-07d1fd307dc3)

“butterfly” being found when searching for “butterfy” 
![image](https://github.com/google/fonts/assets/41795015/f0880ab5-89d0-40e2-a574-2a172a6bfb4e)

“certificate” not found despite clearly being on the first line of text shown 
![image](https://github.com/google/fonts/assets/41795015/8a76d829-8106-4b18-91ef-ca2b29ec52f9)

“certificate” being found when searching for “certifcate”
![image](https://github.com/google/fonts/assets/41795015/d2541015-97ad-4368-bd0a-f96d19c7900a)

**Comment by kenmcd** [comment]
Sounds like their PDF library is not embedding/encoding the `fi` and `fl` ligatures properly.
Sometimes those ligatures will be embedded with their own ligature code points, and sometimes embedded with the separate `f` and `i` code points.
In this case based on the search results you have it appears they are dropping the `i` and `l`.
Have to see the PDF.
With the PDF we can see exactly which shapes they embedded, and the Unicode code point(s) they put behind those shapes.

If you can, try disabling standard ligatures and see if that helps.

**Comment by RosaWagner** [comment]
Hi @jmente1, thanks for your report. As @kenmcd says, this is not a font issue but a problem with the software you are using that doesn't seem to handle ligatures correctly. The other fonts that don't have this issue may not have encoded ligatures. This bug should be reported to SAP Crystal Reports.
