### ISSUE TITLE
Inter SemiBold becomes Regular when saving Word or Powerpoint file as PDF

### ISSUE THREAD

**Issue by katoiv** [google/fonts#6957]
We chose Inter as our brand font. However, we have now noticed that if we save Word or PowerPoint files into PDF (which we do a lot if we share content with customers) the font-weight changes from SemiBold/Bold to Regular.

With Word we came up with a solution to go around the problem. The font weight does not change if we utilize Print > Microsoft Print to PDF. 

However, with PowerPoint we don't want to utilize Print, since there is no option to adjust "paper size" to match 16:9 size. It just looks bad if the "paper" behind is bigger than the slide has been in PowerPoint. 

Here are the steps to reproduce the bug: 

1. I have here a couple Google fonts installed the same way:

![image](https://github.com/google/fonts/assets/150440798/0d622d86-fdb9-4e79-a47a-da2ea4a3298d)

2.  I will save it as PDF

![image](https://github.com/google/fonts/assets/150440798/b29df767-e489-4981-8746-b0780cc63977)

3. The PDF have regular Inter font instead of SemiBold or Bold

![image](https://github.com/google/fonts/assets/150440798/2f08e834-03d3-47d5-b9ed-5ac797e399e6)

Please inform me, if there is some proper fix that can be applied without extra cost to all my colleagues' computers. Or is this something that cannot be done - then I need to consider changing the font.

**Comment by kenmcd** [comment]
Assume you are using the v3.19 fonts downloaded from Google Fonts - correct?
 
First, make sure you do not have the variable font installed at the same time as the static fonts. If you do, un-install the variable font.

The instance names in the variable font will conflict with the style names in the static fonts - which can result in odd behavior like this.

If that does not fix it, there are other things to check.
Would need to see your test doc above.

**Comment by RosaWagner** [comment]
Hi @katoiv, thanks for your report. Did the solution brought by @kenmcd solved your issue? Powerpoint has a very poor font support, and most of the time we can't do much on our end. It is recommended to use only the static fonts with the MS Office Suite.

**Comment by RosaWagner** [comment]
Closing this issue since no answer, assuming this was a conflict issue between static and variable.
