### ISSUE TITLE
Update Pinyon

### ISSUE THREAD

**Issue by EbenSorkin** [google/fonts#6972]
**[Font Project Git Repo URL:](https://github.com/SorkinType/Pinyon)**

**Current version:1.006?**

**New available version:1.008**

**Super short description of the upgrade:**
(Extended language support to Africa PRI and tested and fixed CCMP letters, which are composed when rendered and which are not precomposed with or without Unicode values) Note a PRI level language update was made earlier, but an issue was not filed here to announce it and this lacked the CCMP oriented update. Not too that the repo isn't building for reasons I don't understand.

**Bugs reported in this repo which this upgrade would fix: Non-rendering or Incorrectly rendering letters for African PRI supported languages**
Search in the [issue tracker](https://github.com/google/fonts/issues) if there is some opened issues containing the font name.

**Comment by emmamarichal** [comment]
@chrissimpkins, I saw you added two stars priority for this one, I moved it from backlog to Q2.

**Comment by chrissimpkins** [comment]
Is the project ready to onboard?

**Comment by emmamarichal** [comment]
Yes, I'm working on it!
