### ISSUE TITLE
Hotfix minor Ruslan Display issues

### ISSUE THREAD

**Issue by davelab6** [google/fonts#6975]
_Issues originally described by @RosaWagner in https://github.com/google/fonts/issues/6946#issuecomment-1810167322_

Ruslan Display is super old and has things that we should fix:

1. 🔥 FAIL Expected "RuslanDisplay-Regular.ttf. Got RuslanDisplay.ttf. [code: bad-filename]
2. 🔥 FAIL METADATA.pb subsets are not sorted in alphabetical order: Got ['menu', 'cyrillic', 'latin', 'latin-ext'] and expected ['cyrillic', 'latin', 'latin-ext', 'menu'] [code: not-sorted]
3. 🔥 FAIL: Description strings in the name table must not contain copyright info. (Easy hotfix)
4. 🔥 FAIL The following unwanted font tables were found: FFTM (Easy hotfix with 'fix-unwanted-tables' in gftools)
5. 🔥 FAIL Some namerecords with ID=10 (NameID.DESCRIPTION) containing copyright info should be removed

**Comment by thlinard** [comment]
Btw, is there a repo with the sources somewhere?
