### ISSUE TITLE
fonts on the real phone skip letters in our language

### ISSUE THREAD

**Issue by Luciadla** [google/fonts#6979]
Hi

on bewitch.design we use this font : https://fonts.google.com/specimen/Philosopher . On my computer in the Czech version of the phylosopher font is fine, all the letters of our alphabet fit in the mobile, but in the real mobile I omit for example: tchschl and others. This is important for our language. I don't understand why this happens only on mobile. Thank you for your hel

**Comment by RosaWagner** [comment]
Hi @Luciadla, thanks for your report. Unfortunately I have a hard time understanding the issue. What do you mean by " all the letters of our alphabet fit in the mobile but in the real mobile I omit for example: tchschl and others."

- what is the difference between the mobile and "the real" mobile?
- what is "tchschl"?
- what do you mean by "_I_ omit"?
- what do you mean exactly by "skip letters"? Do you have images to make it clearer?

**Comment by RosaWagner** [comment]
I checked the font, and it doesn't seem that this one was meant to support Czech language. Most of the codepoints specific to Czech are missing; there is no accented letters with caron, no ring accent, no y with acute etc. I would strongly recommend to use a font with a better language support.

To make sure that a font supports the language your looking for, a first method consist in using the region and language drop down menu in each specimen page. 
1. Select a font that you like
2. Select "Europe"
3. Select "Czech". If the language doesn't appear, it means that the font doesn't support it.

See this example Roboto.
<img width="1494" alt="Screenshot 2023-11-21 at 11 38 28" src="https://github.com/google/fonts/assets/12222436/b13c6f91-831d-4c7e-8e58-4c1920ac62af">

A second method would be to filter your search by specific codepoints:
1. Select filters in the main view
2. type specific letters such as: https://fonts.google.com/?preview.text=ž%20š%20č%20ř%20ď%20ť%20ň%20ý%20ů
3. Only the fonts displaying all these letters (correctly and without squares) would be supporting Czech.

<img width="1185" alt="Screenshot 2023-11-21 at 11 44 06" src="https://github.com/google/fonts/assets/12222436/4e4922a5-4692-4761-84de-e8c438d736ed">

I hope you find this helpful.
