### ISSUE TITLE
Bad Script: ћЋ mixed up

### ISSUE THREAD

**Issue by thlinard** [google/fonts#6981]
**Describe the bug**
The glyphs were reversed for U+045B: CYRILLIC SMALL LETTER TSHE and U+040B: CYRILLIC CAPITAL LETTER TSHE in Bad Script.

**To Reproduce**
https://fonts.google.com/specimen/Bad+Script?preview.text=%D1%9B%D0%8B

**Additional context**
Originally reported in https://tomorrow.type.today/en/journal/scripts#BadScript

I believe the most up-to-date repo is https://github.com/alexeiva/badscript/.

**Comment by emmamarichal** [comment]
@chrissimpkins I see "backlog" but two stars. Should we move it in a quarter?

**Comment by chrissimpkins** [comment]
Do you have the ability to address it this quarter with the rest of the priority work you have in your queue?

**Comment by emmamarichal** [comment]
Maybe we can move it to Q4! We could update the milestones if I finish all my Q3 projects sooner

**Comment by chrissimpkins** [comment]
Let's leave it in the backlog in that case and we can decide later this quarter.
