### ISSUE TITLE
Font Anuphan does not display correctly for the Thai

### ISSUE THREAD

**Issue by nuengla** [google/fonts#6983]
problem
![image](https://github.com/google/fonts/assets/81779600/66b5a812-9bb3-444d-b845-eb73c2ff704b)

expected
![image](https://github.com/google/fonts/assets/81779600/cd31cea0-e83f-4784-b367-98b7f28b6e7f)

**Comment by emmamarichal** [comment]
Close this one, I let opened the duplicate one: https://github.com/google/fonts/issues/7618
