### ISSUE TITLE
Sacramento iOS issue

### ISSUE THREAD

**Issue by davelab6** [google/fonts#699]
https://twitter.com/missphips/status/836966545200930817

> I seem to be having problems with sacramento but only when reading on the ipad... Can you tell what's up? Thank you!

![c52acrkwuaq66a6](https://cloud.githubusercontent.com/assets/261579/23753537/d3df8aa0-04a7-11e7-9ca7-65d0889472c6.jpg)

**Comment by m4rc1e** [comment]
On a virtualised IOS 10.3, it looks ok to me.

http://jsbin.com/hiqevucuge/edit?html,output


![screen shot 2017-06-30 at 15 21 15](https://user-images.githubusercontent.com/7525512/27739823-d2fd2580-5da7-11e7-8fc3-39fa8a8fbdbb.png)

My my Iphone SE IOS 10.3, it looks fine as well... apart from jsbin doesn't work on it too well.

![img_0722](https://user-images.githubusercontent.com/7525512/27739985-5d42d456-5da8-11e7-8c31-a9967c18579c.PNG)

**Comment by laerm0** [comment]
It looks fine on my iPad as well.

**Comment by laerm0** [comment]
> Looks like font-weight:bold is being applied (which is automatic, if its a h1 tag) and thus getting auto-bolded. Try to set font-weight:400

Is that you, @davelab6? :) Can we close this?

**Comment by laerm0** [comment]
The user has responded with everything's ok so I am closing.

**Comment by davelab6** [comment]
Yes, it was I
