### ISSUE TITLE
Felipe Neue

### ISSUE THREAD

**Issue by FrygTM** [google/fonts#6997]
)https://github.com/FrygTM/Felipe-Neue)

A tall, sans serif, pixelated font supporting all European languages and Vietnamese along with 5 other scripts.

fontmake>=2.4
fontbakery[googlefonts]>=0.9.2
gftools[qa]>=0.9.23
drawbot-skia>=0.4.8
sh>=1.14.2
bumpfontversion>=0.2.0
diffenator2>=0.2.5

By filling this issue, you can confirm the project meets the  requirements (by ticking the cases or putting x between the square brackets in text mode):

- [x] I read, agree, and comply with the full [contributing requirements](https://googlefonts.github.io/gf-guide/index#pre-production-getting-your-fonts-ready-for-gf)
- [x] The entire font project is licensed under the [OFL](https://scripts.sil.org/cms/scripts/page.php?site_id=nrsi&id=OFL)
- [x] There is no "Reserved Font Name" mention in the OFL license
- [x] Family name is unique according to [namecheck.fontdata.com](https://namecheck.fontdata.com/)
- [x] The font supports at least [GF Latin Core glyphset](https://github.com/googlefonts/glyphsets/tree/main/GF_glyphsets/Latin/)
- [ ] The repository respect the [upstream repo structure](https://googlefonts.github.io/gf-guide/upstream.html)
- [ ] The source files are available in the repository
- [x] I am the author of the font, or the author agreed to this submission
- [x] I will maintain the repository and participate in the onboarding process (addressing, solving, and responding to issues, merging pull requests, etc)

![image](https://github.com/google/fonts/assets/151695770/42af4412-a37d-4e88-b2ec-ad6d41cfb981)

**Comment by RosaWagner** [comment]
Hi @FrygTM, thanks for your submission. Unfortunately, the sources (.ufo or .glyphs) are missing from the repository, therefore we can't review the font. Please comment here when all the requirements have been fulfilled so we can review your submission :)

These chapters of the Google Fonts Guide can be of help:
- Requirements for submitting a font to GF: https://googlefonts.github.io/gf-guide/onboarding.html
- How to set up your repository: https://googlefonts.github.io/gf-guide/upstream.html
- How to handle diacritics: https://googlefonts.github.io/gf-guide/diacritics.html

**Comment by eliheuer** [comment]
@FrygTM Please add sources or this add font issue will be closed soon.

**Comment by vv-monsalve** [comment]
@FrygTM An available source file is a strong requirement. Please read them carefully and feel free to re-open this issue once the project meets all of them.
