### ISSUE TITLE
Update Lora

### ISSUE THREAD

**Issue by emmamarichal** [google/fonts#7009]
**Font Project Git Repo URL:**
https://github.com/cyrealtype/Lora-Cyrillic
cc @alexeiva 

**Current version:**
3.004 

**New available version:**
3.007

**Super short description of the upgrade:**
Interpolation issue fixed in italic
See:  https://github.com/cyrealtype/Lora-Cyrillic/issues/64

**Comment by alexeiva** [comment]
New available version:
3.008

Super short description of the upgrade:
Interpolation issue fixed in italic — adds another fix
See: https://github.com/cyrealtype/Lora-Cyrillic/issues/64
