### ISSUE TITLE
Why does Noto Sans Mongolian claim chinese-simplified support?

### ISSUE THREAD

**Issue by rsheeter** [google/fonts#7022]
https://github.com/google/fonts/pull/6938#issuecomment-1814161016 says it's being done but not why.

**Comment by eliheuer** [comment]
There is a bit of explanation in a previous comment, but still unclear to me what the rationale is: https://github.com/google/fonts/pull/6938#issuecomment-1793499426

**Comment by chrissimpkins** [comment]
Is there anything to do here?  If not, ok to close?

**Comment by simoncozens** [comment]
Yes, I should add CJK fullwidth punctuation to the Mongolian subset in glyphsets and remove chinese-simplified from the subsets in METADATA.pb. I also want to clarify that fontbakery warning.

**Comment by simoncozens** [comment]
(I will do this after we've moved the glyphsets to the nam-files repo, or else it will probably get lost in the move.)

**Comment by EbenSorkin** [comment]
Probably for trade reasons. Does it also contain Cyrillic?
