### ISSUE TITLE
Update Inter to v4

### ISSUE THREAD

**Issue by Santas** [google/fonts#7023]
**Font Project Git Repo URL:**
https://github.com/rsms/inter

**Current version:**
3.x

**New available version:**
4

**Super short description of the upgrade:**
https://github.com/rsms/inter/releases/tag/v4.0
https://twitter.com/rsms/status/1726397679880773876

**Comment by RosaWagner** [comment]
Thanks @Santas, we already have an issue to track the update of Inter #3429 so closing.
