### ISSUE TITLE
Update Asset

### ISSUE THREAD

**Issue by EbenSorkin** [google/fonts#7042]
**Font Project Git Repo URL:https://github.com/SorkinType/Asset**

**Current version:1.002**

**New available version:1.003**

**Super short description of the upgrade:**
Expand glyphset to GF Africa Pri, Add kerning

**Bugs reported in this repo which this upgrade would fix:**
This font had no Githib repo before because it was made before GF used repos. But does now. :-)

**Comment by yanone** [comment]
Closing because duplicate of https://github.com/google/fonts/issues/4163
