### ISSUE TITLE
Upgrade Bungee font families to `2.000` version

### ISSUE THREAD

**Issue by vv-monsalve** [google/fonts#7045]
**Font Project Git Repo URL:**
https://github.com/djrrb/Bungee

**Current version:**
Most of them `v1.000`
Bungee Spice `0.01`

**New available version:**
 `v2.00` is in preparation

- [x] Bungee `2.000` #7794 
- [x] Bungee Hairline `2.000` #7795 
- [x] Bungee Inline `2.000` #7797  
- [x] Bungee Outline `2.000` #7796 
- [x] Bungee Shade `2.000` #7798 
- [x] Bungee Spice `2.000` #7799 

**Super short description of the upgrade:**

The reported #5724, Vertical Metrics fixes, and other improvements.

**Comment by vv-monsalve** [comment]
We're waiting for the new `v2.000` release to be cut before proceeding. @justvanrossum is working on it.

**Comment by justvanrossum** [comment]
🎉 https://github.com/djrrb/Bungee/releases/tag/v2.000 🎉
