### ISSUE TITLE
Update Inter-4.0

### ISSUE THREAD

**Issue by kooriookami** [google/fonts#7047]
**Font Project Git Repo URL:**
https://github.com/rsms/inter

**Current version:**
3.19

**New available version:**
4.0

**Super short description of the upgrade:**
See: https://github.com/rsms/inter/releases/tag/v4.0

**Bugs reported in this repo which this upgrade would fix:**
Search in the [issue tracker](https://github.com/google/fonts/issues) if there is some opened issues containing the font name.

**Comment by 0xdhrv** [comment]
This is being tracked here: #3429

**Comment by RosaWagner** [comment]
closing because of duplicate
