### ISSUE TITLE
Fixing the display of numbers in the font Sorts Mill Goudy

### ISSUE THREAD

**Issue by MieszkoNowacki** [google/fonts#7048]
Hello,
Sorts Mill Goudy is a beautiful font, but I noticed that numbers display very weirdly. Some numbers are smaller, some are bigger. Some are starting lower, which is not aligned with the letters and some go higher.

**Describe the bug**
The display of numbers is not consistent. 
Numbers 0, 1, 2 are the same size and on the same line as lowercase letters.
Numbers 3, 4, 5, 7, 9 are brought lower, they are not inlined with the letters and their length is of a an uppercase letter.
Numbers 6, 8 are in line with the letters and have the length of uppercase letters.

**To Reproduce**
It's best to write something, few words, and then to type the numbers from 0 to 9.
That way the difference can be easily spotted.

**Expected behavior**
I expected numbers to be in line with the text when writing them and to be in the regular size.

**Screenshots**
Uploaded a screenshot when working with the font for a title.

**Additional context**
It's on a browser for sure, not sure about other places

<img width="1124" alt="Zrzut ekranu 2023-11-30 o 08 04 42" src="https://github.com/google/fonts/assets/152474901/7038b4f0-26ee-4318-8d85-25133dbff3ef">

Thank you!

**Comment by thlinard** [comment]
https://fonts.google.com/knowledge/introducing_type/understanding_numerals

**Comment by RosaWagner** [comment]
Hi @MieszkoNowacki, this family doesn't support aligned numbers. Most families have an opentype feature to switch from a style of numbers to the other but it is not the case here. If you find a family that does, you would have to download the font and make a search to know how to enable certain opentype features from the app you are using (usually it is in the advanced font settings)
