### ISSUE TITLE
maven-pro has problems with dotted small i while using chrome in Turkish locale

### ISSUE THREAD

**Issue by ykaragol** [google/fonts#705]
Dotted small `i` characters cannot be shown in Chrome with Turkish locale. All I can see is the dot of `i`.
I'm using Windows 10 and Chrome 56.

How to reproduce:
1. Open settings page of Chrome. ( chrome://settings/ ) 
2. type "lang" at the search box
3. Click "language and input settings" 
4. Add language: Turkish
5. Pick "Display Chrome in this language"
6. Restart Chrome.
7. Go to font page: https://fonts.google.com/specimen/Maven+Pro
8. Look at the `i` character.

**Comment by m4rc1e** [comment]
Thanks @ykaragol, just filed a pr for this.

**Comment by davelab6** [comment]
Thanks @ykaragol for reporting and @m4rc1e for queuing up a fix quickly :)

**Comment by ykaragol** [comment]
What is the plan about this issue? When will we see it in production?
