### ISSUE TITLE
Update OFL-FAQ in all projects to latest version (1.1-update7)

### ISSUE THREAD

**Issue by jvgaultney** [google/fonts#7061]
**Describe the issue**
The SIL Open Font License OFL-FAQ.txt has been updated to version 1.1-update7, and all OFL projects are encouraged to switch to the new version.

Site: https://openfontlicense.org/ofl-faq/
Direct download: https://openfontlicense.org/documents/OFL-FAQ.txt

**Comment by djrrb** [comment]
@davelab6 done! 
https://github.com/canonical/Ubuntu-fonts/commit/6d0930b3fa99d79a12bfe85da6fec682e901ba9e
https://github.com/canonical/UbuntuMono-fonts/commit/cafa16566849b6896adc7712a414c6bdec743193
