### ISSUE TITLE
Local font problems:  missing weights and font versioning

### ISSUE THREAD

**Issue by trompx** [google/fonts#707]
Hello,

While modifying the typography on my website, I stumble upon a bug already encoutered by other users:
https://github.com/google/fonts/issues/89
https://github.com/google/fonts/issues/647

In my case, I have bold and regular Montserrat font on my laptop and trying to use 200/300 weights from google fails as it uses only the local version.

So there are two problems:
1. google try first to load the local font and if exists, does not check if the weights required by the website are already available locally.
2. if the user has an old version of the font locally, then the website will not look like it is intended to.

Of course I could disable the font on my machine but the problem is for users visiting my website that really never ever should care about deleting/disabling fonts on their system.

I see why google try first to load local version when it comes to common fonts already known to be installed on linux/macos/windows machines.
But when it comes to fonts not already preinstalled on thoses systems, why not always use the google version and cache it rather than loading the local version which could have either missing weights or be and old version, thus completly breaking the user experience?

Would it be possible at least that google uses the local version in the weights available but still load the missing weights from google? In my case, it should detects that the 200/300 weights are missing on the machine, load them from google and cache them.

Would it also be possible for fonts introducing breaking changes (even a slight visual change) to have versioning on google font?

**Comment by davelab6** [comment]
> In my case, I have bold and regular Montserrat font on my laptop

Please uninstall the ones you have installed and install the latest release. 

> if the user has an old version of the font locally, then the website will not look like it is intended to.

They should update their fonts. 

> Of course I could disable the font on my machine but the problem is for users visiting my website that really never ever should care about deleting/disabling fonts on their system.

Then they should not install them :)

> I see why google try first to load local version when it comes to common fonts already known to be installed on linux/macos/windows machines. But when it comes to fonts not already preinstalled on thoses systems, why not always use the google version and cache it rather than loading the local version which could have either missing weights or be and old version, thus completly breaking the user experience?

Because the installed fonts are 'pre-cached,' if you will. 

> Would it be possible at least that google uses the local version in the weights available but still load the missing weights from google?

Isn't that the current situation? :)

> In my case, it should detects that the 200/300 weights are missing on the machine, load them from google and cache them.

Isn't that also the current situation? :)

> Would it also be possible for fonts introducing breaking changes (even a slight visual change) to have versioning on google font?

No. Simplicity is important, and updating the fonts used by websites to the latest versions of fonts automatically is important. If you want to have total control of when fonts are updated, the libre licenses of the fonts available from Google Fonts respect you freedom to self-host, so please exercise that freedom :)

**Comment by trompx** [comment]
@davelab6 

> They should update their fonts. 

Fair enough to consider that a user that downloaded a font himself is supposed to update it and know how to do it. But so we just exclude all users who can have on their machines some out dated font that can conflict with google ones and who don't necessarly know how to update them and may not even be aware that they should do it.

>> Would it be possible at least that google uses the local version in the weights available but still load the missing weights from google?

> Isn't that the current situation? :)

Precisely not, just like I described it above. On my system I just have bold and regular montserrat and when loading
`<link href="https://fonts.googleapis.com/css?family=Montserrat:200,300,400,500,600,700,800" rel="stylesheet">` and trying to use `font-weight: 200` or `font-weight: 300` it uses weight 400 instead so google is not loading the missing weights not present on my computer.

Thanks for your other clarifications.

**Comment by davelab6** [comment]
>>> Would it be possible at least that google uses the local version in the weights available but still load the missing weights from google?
>>
>> Isn't that the current situation? :)
>
> Precisely not, just like I described it above.

Oh, I see. I believe this is due to browser implementation, where the font FAMILY is detected locally so the browser loads (or, attempts to) all the styles locally.
