### ISSUE TITLE
Questions for a research project

### ISSUE THREAD

**Issue by Rozsavaria** [google/fonts#709]
Who is in charge of Google Fonts? (i.e. who's the CEO?)
Do you have a base of operations; a headquarters? I read some things that say you use GitHub to collaborate online with your designers. I am wondering if this is done from everyone's home or an office. 
How is your company benefiting from this service?
Are there any fonts that do cost money on Google Fonts?

**Comment by davelab6** [comment]
I'm a Program Manager on the Google Fonts team, and am the most externally facing member of the team.

> Who is in charge of Google Fonts? (i.e. who's the CEO?)

It is a team effort within a larger company, so no individual is in charge in the way that CEOs are.

> Do you have a base of operations; a headquarters?

Google is headquartered in Mountain View, California, one of the towns that make up Silicon Valley, and has offices around the world. I myself live in New York City. 

https://www.google.com/intl/en/about/locations/

> I read some things that say you use GitHub to collaborate online with your designers. 

Yes, Github and Google Groups are the main points of online collaboration between the type designers and them with Google Fonts. 

https://groups.google.com/forum/#!topic/googlefonts-discuss/

> I am wondering if this is done from everyone's home or an office.

The fonts in the Google Fonts collection have been contributed from a variety of sources, from individual freelance designers to foundries of all sizes, up to and including the biggest font company, Monotype. Some foundries do have an international set of offices, too, but most foundries are much smaller and some may consist entirely of home-offices around the world, while an individual freelance designer may make use of a more formal office space. 

> How is your company benefiting from this service?

https://fonts.google.com/about explains, and a couple of particular quotes include "bring personality and performance to websites and products is through great design and technology" and "making beautiful type accessible to anyone for any project" and "makes product and web pages run faster." 

You might also be interested to read the speculation at https://www.typewolf.com/blog/will-google-fonts-ever-be-shut-down about this topic.

> Are there any fonts that do cost money on Google Fonts?

End users are not charged to access fonts directly, but, of course, all things cost money to develop, and for many of the font projects Google has paid that cost entirely; in some cases, however, a font project's development was paid fully by another organization or individual.

**Comment by theghostkill** [comment]
> For many of the font projects Google has paid that cost entirely

Do font designers receive compensation for their font design efforts on a volunteer basis, or does Google have the authority to decide which fonts are eligible for payment? How does this work?
