### ISSUE TITLE
Kaffeesatz VF recognition problem

### ISSUE THREAD

**Issue by yanone** [google/fonts#7099]
Someone writes me by email:

> I've tried to use your font - Yanone Kaffeesatz, and noticed a little problem. Its variable version is titled as Yanone Kaffeesatz ExtraLight (as was told by my system and website https://fontdrop.info/). Because of this some software doesn't detect this font as variable, in our case that was Adobe InDesign. Can you please fix this, so the font would be detectable as variable and could be used to its full potential?

**Comment by thlinard** [comment]
InDesign 2024? https://indesign.uservoice.com/forums/601180-adobe-indesign-bugs/suggestions/47344655-problem-with-variable-font-weights

**Comment by yanone** [comment]
Indeed, the issue seems fixed in the latest Indesign, but I updated Kaffeesatz to the latest technical standard regardless. See [linked PR](https://github.com/google/fonts/pull/7100)
