### ISSUE TITLE
Arivo Sans

### ISSUE THREAD

**Issue by luisjar55** [google/fonts#7114]
** https://github.com/luisjar55/arivo-sans **

** Arivo Sans: Sans-Serif font from 6 families created by LJ Design Studios **

**Requirements:**

Google Fonts will publish only fonts that match its requirements. Please familiarize yourself with the complete documentation in the [Google Fonts Guide](https://googlefonts.github.io/gf-guide/) (GF-Guide) and ensure your font project complies with them before submitting the font family. You can also use the [Google Fonts Project Template](https://github.com/googlefonts/googlefonts-project-template), which will help you create a repository that follows the needed structure and includes build requirements.

By filling this issue, you can confirm the project meets the  requirements (by ticking the cases or putting x between the square brackets in text mode):

- [x] I read, agree, and comply with the full [contributing requirements](https://googlefonts.github.io/gf-guide/index#pre-production-getting-your-fonts-ready-for-gf)
- [ ] The entire font project is licensed under the [OFL](https://scripts.sil.org/cms/scripts/page.php?site_id=nrsi&id=OFL)
- [ ] There is no "Reserved Font Name" mention in the OFL license
- [x] Family name is unique according to [namecheck.fontdata.com](https://namecheck.fontdata.com/)
- [ ] The font supports at least [GF Latin Core glyphset](https://github.com/googlefonts/glyphsets/tree/main/GF_glyphsets/Latin/)
- [ ] The repository respect the [upstream repo structure](https://googlefonts.github.io/gf-guide/upstream.html)
- [ ] The source files are available in the repository
- [x] I am the author of the font, or the author agreed to this submission
- [x] I will maintain the repository and participate in the onboarding process (addressing, solving, and responding to issues, merging pull requests, etc)

**<img width="1354" alt="Arivocover" src="https://github.com/google/fonts/assets/152026685/70fad13d-fc33-48c5-b1f6-7580e473afe4">**

Attach here a pic or a screenshot of the font. One image is enough, it can be a few letters, to give a quick overview.

**Comment by kenmcd** [comment]
Note: I am not affiliated with Google Fonts. Just another user.

You should only check the required boxes when it is actually true.
- There are NO SOURCES in the repository.
- The repository DOES NOT respect the upstream repo structure
- The entire font project is NOT licensed under the OFL

This font project will not even be considered until you actually meet the requirements.

**Comment by inferno986return** [comment]
Says on the website that it's a commercial font: https://ljdesignstudios.com/arivo-sans/#more-3706

Hopefully, you do re-licence the project under SIL OFL, release the sources and open the repo to the public. 😊

**Comment by vv-monsalve** [comment]
Hi @luisjar55, Thanks for your submission. I un-ticked the requirements that were not fulfilled. Please read them carefully and feel free to re-open this issue once the project meets all of them.
