### ISSUE TITLE
fix CI with Travis

### ISSUE THREAD

**Issue by m4rc1e** [google/fonts#713]
Travis fails when submitting prs. 

@graphicore explains this in #710 

> Because, when I activated Travis for the repository there were no tests available, nor a travis.yaml file. Travis fails because it is not configured in this branch. Now a git fetch master; git rebase master; git push -fwould solve this, but it is not a problem either. The tests are only concerned with the contents of tools/encodings.

> From the build log, line 6:
Could not find .travis.yml, using standard configuration.

**Comment by graphicore** [comment]
new PRs based on the current master should not fail anymore, though.

**Comment by m4rc1e** [comment]
@davelab6 @graphicore once the false positives are ironed out of FontBakery, I suggest we throw this into the CI chain as well.

**Comment by davelab6** [comment]
> once the false positives are ironed out of FontBakery, I suggest we throw this into the CI chain as well

By 'this' you mean FB?

**Comment by davelab6** [comment]
https://travis-ci.org/google/fonts/builds/213871538 now passes
