### ISSUE TITLE
Add Teachers font

### ISSUE THREAD

**Issue by chankfonts** [google/fonts#7133]
Teachers Font Project Git Repo URL:

https://github.com/chankfonts/Teachers-fonts

Super short description of the Font Family:
The Teachers font is an educational font family created for use by publishers, teachers, students and parents of children in grades K through 6.

- [x] I read, agree, and comply with the full [contributing requirements](https://googlefonts.github.io/gf-guide/index#pre-production-getting-your-fonts-ready-for-gf)
- [x] The entire font project is licensed under the [OFL](https://scripts.sil.org/cms/scripts/page.php?site_id=nrsi&id=OFL)
- [x] There is no "Reserved Font Name" mention in the OFL license
- [x] Family name is unique according to [namecheck.fontdata.com](https://namecheck.fontdata.com/)
- [x] The font supports at least [GF Latin Core glyphset](https://github.com/googlefonts/glyphsets/tree/main/GF_glyphsets/Latin/)
- [x] The repository respect the [upstream repo structure](https://googlefonts.github.io/gf-guide/upstream.html)
- [x] The source files are available in the repository
- [x] I am the author of the font, or the author agreed to this submission
- [x] I will maintain the repository and participate in the onboarding process (addressing, solving, and responding to issues, merging pull requests, etc)

<img width="603" alt="Teachers_fonts_8styles" src="https://github.com/google/fonts/assets/142630130/0097441d-2ea0-454b-955f-0697536b8041">

**Comment by davelab6** [comment]
Amazing project Chank! 

We will onboard the VFs in https://github.com/chankfonts/Teachers-fonts/tree/main/fonts/Variable and therefore the API will generate a Medium (500) weight in addition to the 400, 600, 700, 800 shown above and in https://github.com/chankfonts/Teachers-fonts/tree/main/fonts/TrueType 

We'd also like to modify the OFL copyright notice string slightly to make it more future proof

But overall the repo looks set up nicely for us to pick up :)

**Comment by emmamarichal** [comment]
Hi @chankfonts!

I tried to export the fonts as variable and it works well! There some few things we need to correct, such as copyrights and v-metrics, but I can do it.

I just need you to complete the Latin Core glyphset, with these glyphs, and it will be perfect!

section
guillemetleft
guillemetright
quotesinglbase
quotedblbase
guilsinglleft
guilsinglright

Thank you, and don't hesitate if you have any questions :)

**Comment by chankfonts** [comment]
hi @emmamarichal !

ok, I added all those glyphs and a couple more. 

new updated files are in the repo.

-chank

**Comment by emmamarichal** [comment]
Thanks a lot Chank!
I'll take a look this week :)

Cheers!

Emma


Le mar. 16 janv. 2024 à 03:46, Chank Diesel ***@***.***> a
écrit :

**Comment by emmamarichal** [comment]
Hi @chankfonts! I see the fonts folder updated, but not the sources. Could you add them? I need them to export the variable properly, according the GF specs. Thanks a lot! :)

**Comment by chankfonts** [comment]
@emmamarichal  ah, oops! ok, updated source files uploaded now :)

**Comment by emmamarichal** [comment]
Excellent! The project is on the queue, I'll try to onboard it this quarter :)
