### ISSUE TITLE
Roboto Regular 400 Missing some glyphs

### ISSUE THREAD

**Issue by bksubhuti** [google/fonts#7138]
**Font Project Git Repo URL:**

**Current version:**
https://fonts.google.com/specimen/Roboto?preview.text=p%C4%81%E1%B8%B7i

Words with roman pāḷi cannot be displayed only on the regular  (the most used version of Robot on google fonts).

![image](https://github.com/google/fonts/assets/18184280/c03be2d8-aa57-4289-b222-896da669d935)

Need to test the following labial characters.
ṭ ḍ ṇ ḷ Ṭ Ḍ Ṇ Ḷ

Possible usage in Tipitaka Pali Reader app.

**Comment by bksubhuti** [comment]
While I'm complaining.. we also use the following language fonts and run into problems with roman at the same time.

  - family: Pyidaungsu
      fonts:
        - asset: assets/fonts/Pyidaungsu-Regular.ttf
        - asset: assets/fonts/Pyidaungsu-Bold.ttf
    - family: NotoSansDevanagari
      fonts:
        - asset: assets/fonts/NotoSansDevanagari-Regular.ttf
        - asset: assets/fonts/NotoSansDevanagari-Bold.ttf
    - family: NotoSansSinhala
      fonts:
        - asset: assets/fonts/NotoSansSinhala-Regular.ttf
        - asset: assets/fonts/NotoSansSinhala-Bold.ttf
    - family: Lao Pali Regular
      fonts:
        - asset: assets\fonts\LaoPaliRegular.ttf
    - family: NotoSansTaiTham
      fonts:
        - asset: assets/fonts/NotoSansTaiTham-Medium.ttf
        - asset: assets/fonts/NotoSansTaiTham-Bold.ttf

**Comment by moyogo** [comment]
By default Google Fonts serves a subsetted version of the fonts, including Roboto and others.
The font displayed on  https://fonts.google.com/specimen/Roboto?preview.text=p%C4%81%E1%B8%B7i is not the full Roboto and the missing characters are not part of the default subset being served.
Unfortunately none of the predefined subsets for Latin (latin or latin-ext) provide the characters you need.

For Roboto, the best option is to host yourself the full font as it covers the characters you need.

For Noto Sans Devanagari, Noto Sans Sinhala, Noto Sans Tai Tham or Lao Pali, they do not have full versions that support the characters you need. You should probably use those fonts only for the scripts they aim to cover and use Noto Sans for Latin.

**Comment by bksubhuti** [comment]
Yes.  Spent some time working on putting the direct script when using roman . I added my other fonts as a side note in case you wanted to fix all.  

 However , if you look at the screenshot.  You will see that the characters (with dots)  s supported by all other variants of roboto family but not the actual "regular". It is this inconsistency that I'm pointing out.

We are using noto sans from Google fonts instead, but it would be better to use roboto.

We also have other choices as many fonts support these letters (about half or more on font Google website)

So again my complaint is the inconsistency between the roboto  font family ironically missing in the "regular"

**Comment by m4rc1e** [comment]
Thanks for the report. 

> So again my complaint is the inconsistency between the roboto font family ironically missing in the "regular"

If I click on each style, I get the same tofu so this looks like an issue on the frontend. cc @garretrieger 

![robo](https://github.com/google/fonts/assets/7525512/f4b806a8-5f2d-4b2f-bc1f-d59976909034)

**Comment by bksubhuti** [comment]
Okay.. well at least something came out of this issue.. You can close this issue and create a new issue for the front end people.. or haha.. you can add my letter glyph request.  :)

**Comment by moyogo** [comment]
> you can add my letter glyph request. :)

What letter glyph request?

**Comment by applecuckoo** [comment]
@moyogo I believe @bksubhuti wants to add the Roman glyphs to the fonts mentioned above (https://github.com/google/fonts/issues/7138#issuecomment-1873297115).

By the way, only the Noto fonts you specified came from Google Fonts, the 'Lao Pali' and 'Pyidaungsu' fonts seem to have come from somewhere else.

**Comment by bksubhuti** [comment]
These glyphs here (copied from my original post up top).. 
ṭ ḍ ṇ ḷ Ṭ Ḍ Ṇ Ḷ
notice you don't need a special font to read these.

About the lao font.. It was made based off of google font and the person has it on his drive.
I think he should put it somewhere on your google website for TheAll.

It has some special pāḷi characters in the native script language.
We use this for tipitaka pāḷi reader app.    Theravāda Buddhism uses these letters for the pāḷi language which are standard roman transliteration letters for native scripts.
If you are going to add it.. there are some IAST  roman sanskrit letters that I don't use but might be useful for others .
I can get a list.


I'm not sure about the backstory of Pyidaungsu.  
The original programmer is Myanmar and it is used for Myanmar script.


This is the whole of special letters for the whole alphabet.. The letters with the dot underneath represent the sound of the t and d that is characteristic of an indian accent, but having the tip tongue at the roof of the mouth (it this is an exaggerated position).
ā, ī, u, ū, ṅ,  ñ, ṭ,  ḍ, ṇ, ḷ, ṃ  (some use the ṁ  )

Maybe this might help for Roman Pāḷi   https://en.wikipedia.org/wiki/Pali
List of letters is at the title Alphabet with diacritics of the above page.


for sanskrit , you can look here.  they have special r's and s's
https://en.wikipedia.org/wiki/International_Alphabet_of_Sanskrit_Transliteration

**Comment by applecuckoo** [comment]
@bksubhuti Ah, now I get what you mean. 
**Quick version**: This is a problem with the Google Fonts API and not the font itself. Go to the Google Fonts website, download the font files for Roboto and use that instead. Here's a screenshot in LibreOffice Writer showing the Pāḷi glyphs:
![Screenshot from 2024-01-03 18-28-32](https://github.com/google/fonts/assets/113647417/6de46733-0ed6-40ac-a0eb-f06c9d59fa08)

**Long version**: Google Fonts uses something called subsetting to keep font sizes low. Usually they do this by stripping out glyphs you don't need, i.e. if you have a website with a predominantly English-speaking audience then you probably don't need the glyphs for Vietnamese. In scenarios like this the web developer can request a subset from Google Fonts that only contains Latin glyphs. The Pāḷi glyphs aren't found in any of these subsets, which explains why they don't show up on the website.

**Comment by bksubhuti** [comment]
I'll try it in my software and see what happens.
We have a problem where it shows up with android only if the glyph is not there.. 
Linux can display the glyphs well.. because it is well.. linux.
But I'll  plug the font into the app and see what it does in android  (we have other fonts that work fine in android)..
It could be good news.but let me test.  
I installed fontforge.. I didn't see the glyph.. but I'll install and load with android and get back to you.
We "discovered" our font bug from android actually.  Usually there is a fallback font for missing glyphs on certain software and OS.  

Give me 8 hours.  I'll plug it in

**Comment by bksubhuti** [comment]
So.. I think the interface is correct.
In the zip file there is Roboto-Medium.ttf (which I complained about)
and there is Roboto-Regular.ttf

This is a screenshot of Regular of a pāḷi grammar book that lists all the letters (ignore the bold)
![image](https://github.com/google/fonts/assets/18184280/16f3f4fb-4d9f-4f84-bba0-31366b21b801)



*********


This is a screenshot of roboto medium  It is difficult to tell, but the ṅ is a different font.. usually it has a fallback to the system font when it cannot find a glyph.
![image](https://github.com/google/fonts/assets/18184280/19450c1e-dd7c-467e-9ea8-428bd730054d)
 
I'll add a screen shot of android in my next comment.

**Comment by bksubhuti** [comment]
Ironically.. not sure how this would be .. but the medium looks okay on android.
But.. as you said.. the letters you typed in libre-writer.. were okay.. there was one letter not in my list..  "ṅ"
This one does not display well.  Not sure why.. but we load the fonts specifically.
I can tell the sections of the code which do not use the specific font by loading sinhala language which uses Noto Sans Sinhala.. it is much worse in Android.
There we will get strikethru-boxes with

**Comment by bksubhuti** [comment]
Both medium and Regular are fine on Android.  However, there was that picture where I showed you the ṅ font.
This letter is almost never capital unless someone is explaining the letter and uses upper case to explain the single letter.

However, the sinhala font does not contain the roman equivalents .. the same with the other listed fonts (from google fonts and not the private hosted ones).

**Comment by moyogo** [comment]
OK. Ṅ ṅ are not in the version of Roboto in the zip file downloaded from fonts.google.com but they are in the latest version from https://github.com/googlefonts/roboto-classic/releases/tag/v3.008. The Google Fonts version should be updated to the latest version. There’s already an issue for that: #6099.

**Comment by bksubhuti** [comment]
Great.. I'm using regular... so I'm finished with my issue.  You can close it.
I assume you have issues for the web interface.

I'll see what I can do to contact those in charge of the  language fonts not included in your archive and see if they can be PR to your github.   At least I'll send a message to the Lao one.

Aloha.

**Comment by bksubhuti** [comment]
I just found that the Bold ṅ does not work in android during morning chanting.  This was for the Heading class.
I'm assuming the Roboto-Bold.ttf  .  I will download the newest version from github as you said.

**Comment by applecuckoo** [comment]
@bksubhuti Just so you know, you can close the issue yourself. There should be a close button at the bottom.

**Comment by bksubhuti** [comment]
I inserted the AllInOne file from the version 3 github and tested it.  All is well.
