### ISSUE TITLE
Secular not working on MSIE/Edge?

### ISSUE THREAD

**Issue by davelab6** [google/fonts#715]
https://github.com/MichalSahar/Secular/issues/3

**Comment by m4rc1e** [comment]
Works for me in Win 10, Edge 15

![screen shot 2017-07-10 at 13 34 30](https://user-images.githubusercontent.com/7525512/28018274-8fc7df10-6574-11e7-9b49-8f1126e42677.png)


http://jsbin.com/cemifuxesu/edit?html,output

Closing this because @yarivhab found his solution in the upstream repo
