### ISSUE TITLE
Add damn content description search for the fonts

### ISSUE THREAD

**Issue by babakfp** [google/fonts#7155]
I want to search a damn font, based on the content of the description of that font. Currently, it's not possible. Why the hell not? This is a feature request. Add a damn proper search functionality.

**Comment by chrissimpkins** [comment]
Hi Babak. This is not a current priority for us but we appreciate the feedback and will keep it in mind for future front end planning.

I recognize that you are likely frustrated by the lack of a feature that you'd like to use, but the profanity is not necessary on the repository tracker.  Please reference the repository [Code of Conduct](https://github.com/google/fonts/blob/main/CODE_OF_CONDUCT.md) for future reports.

Thanks for taking the time to report this issue to us.
