### ISSUE TITLE
I cannot select any font

### ISSUE THREAD

**Issue by Kristiansky** [google/fonts#7166]
**I can't select any font**
Anywhere on the screen i don't see a checkbox for each differen font weight in order to add them in the selected families

**To Reproduce**
Go to any font, for example here: https://fonts.google.com/specimen/Roboto and see on the right part of the screen, each separate font weight must have a checkbox, it is simply not there.

**Expected behavior**
I expected to have a checkbox, in order to choose each font modification and later use them in my website.

**Screenshots**
![image](https://github.com/google/fonts/assets/11662094/99576746-64c1-42b4-a0df-f22121091cc3)

**Comment by vv-monsalve** [comment]
Hi @Kristiansky, I cannot reproduce the issue on Mac. Is this still a problem for you?

**Comment by emmamarichal** [comment]
@Kristiansky @vv-monsalve I can't reproduce either on Mac. I close this issue for now, feel free to tag us if you meet the problem again!

**Comment by AvJay23** [comment]
I have same problem right now after reinstall Win11. Yesterday everything was ok.

**Comment by emmamarichal** [comment]
Ah indeed, I managed to replicate it on Windows > Chrome (it works on Edge)
Let me check with the eng team, I'll come back to you!

**Comment by briannarenni** [comment]
Commenting to follow, same thing is happening here. I can't see the button on Firefox, but it's there on Safari and Chrome.

<img width="800" alt="new-screen" src="https://github.com/google/fonts/assets/69635579/f7790694-c8f6-4cb4-91e3-8f085b751f8c">

**Comment by davelab6** [comment]
There is a massive "get font" blue button at the top :)

**Comment by briannarenni** [comment]
> There is a massive "get font" blue button at the top :)

There is, but that includes the entire family and all styles, and not specific styles. I found this out earlier, leading me here :)

**Comment by davelab6** [comment]
> issue was solved by switching browsers, so the buttons came back anyway.

Sadly no - this is a new UI rolling out, via an increasing percent of all sessions in the typical A/B testing way, so, not everyone will see the new UI yet, and switching browers (or going incognito mode) will roll the dice on if you get an A or B session, but you're going to get the new UI 100% of the time fairly soon.

> > There is a massive "get font" blue button at the top :)
> 
> There is, but that includes the entire family and all styles, and not specific styles, like the original poster mentions. I found this out earlier, leading me here :)

If you go to "get font" page, then you see another big blue button, "`<> Get embed code`", and that gives you per style selection:

<img width="961" alt="Screenshot 2024-02-07 at 12 49 36" src="https://github.com/google/fonts/assets/261579/138f7429-db60-4d8d-bc50-614283f4dade">

The download ZIPs were always entire-family, and the GF UX team has created this new selection/checkout UI based on extensive user feedback and iterative testing.

**Comment by briannarenni** [comment]
> Sadly no - this is a new UI rolling out

Ah, this is what I was wondering when I came to check the issues here but the earlier replies then made me think it was a bug of some kind. I'll have to get used to the change then.

**Comment by davelab6** [comment]
@briannarenni indeed :)

**Comment by AvJay23** [comment]
Anyone can help with that issue? Nobody had it or nobody resolved it?

**Comment by briannarenni** [comment]
> Anyone can help with that issue? Nobody had it or nobody resolved it?

Apparently it's not a bug, it's intentional. An interesting choice of UI update, that's for sure.

**Comment by davelab6** [comment]
@AvJay23 indeed @briannarenni has it right; 100% of all visits to the fonts.google.com site now get the new UI, and there's a blog post at https://material.io/blog/get-google-fonts-update about it. If you have suggestions for how to improve the new UI (other than "change it back" lol) please post them :)

**Comment by elnobun** [comment]
The gist is that not all the variable fonts have a selectable font-weight. Example `Inter family` don't have multiple selectable font-weight. You may have to do this manually. But fonts like `Merriweather`, have selectable font-weights.

Why it's this way, I KNOW NOT!

**Comment by vv-monsalve** [comment]
Merriweather is a family of _static_ fonts. Inter is a variable font (like Merriweather Sans).

**Comment by Sharikaparveen** [comment]
👍

**Comment by silvertiger1** [comment]
Very Helpful. Thanks a bunch!

**Comment by muadhhaji320** [comment]
some fonts have 8 style and more and some not have more so if fonts have more style you'll get selection or if less font you get full fonts style button . very sadly update

**Comment by riadc916** [comment]
is there any solutation about this problem

**Comment by robizzt** [comment]
Please update the "One value" option where you can select only one weight, to be able to select multiple weights. I don't want to use all weights, but in most cases I need at least two, normal text and bold text.

I know I can get each weight when I download a whole family inside of a "static" folder, but all those files are in .ttf format, and I want to use .woff/.woff2.

**Comment by Aaron-193** [comment]
Hello everyone. This issue has popped up again on my end. There is no way for me to interact with the styles and as a result I can only pick one style or all of them

<img width="1893" height="824" alt="Image" src="https://github.com/user-attachments/assets/5fc82f03-01c4-4b12-b786-7782c4b12398" />

<img width="1884" height="826" alt="Image" src="https://github.com/user-attachments/assets/ff11bf73-9d6b-4ecf-8d55-d94cb1fd436a" />
