### ISSUE TITLE
Add Platypi

### ISSUE THREAD

**Issue by d-sargent** [google/fonts#7173]
**Font Project Git Repo URL:** 

https://github.com/d-sargent/platypi

**Super short description of the Font Family:** 

_Platypi_ is a wedge serif typeface family of five weights designed for long copy text setting.

**Requirements:**

By filling this issue, you can confirm the project meets the  requirements (by ticking the cases or putting x between the square brackets in text mode):

- [x] I read, agree, and comply with the full [contributing requirements](https://googlefonts.github.io/gf-guide/index#pre-production-getting-your-fonts-ready-for-gf)
- [x] The entire font project is licensed under the [OFL](https://scripts.sil.org/cms/scripts/page.php?site_id=nrsi&id=OFL)
- [x] There is no "Reserved Font Name" mention in the OFL license
- [x] Family name is unique according to [namecheck.fontdata.com](https://namecheck.fontdata.com/)
- [x] The font supports at least [GF Latin Core glyphset](https://github.com/googlefonts/glyphsets/tree/main/GF_glyphsets/Latin/)
- [x] The repository respect the [upstream repo structure](https://googlefonts.github.io/gf-guide/upstream.html)
- [x] The source files are available in the repository
- [x] I am the author of the font, or the author agreed to this submission
- [x] I will maintain the repository and participate in the onboarding process (addressing, solving, and responding to issues, merging pull requests, etc)

**Image:**

![platypi-sample-images-jan-2024-2](https://github.com/google/fonts/assets/137256517/cccc6891-ec50-44f0-a036-c3d3758483a4)

**Comment by emmamarichal** [comment]
Thank you for your submission, I added it to the submissions review list :)

**Comment by d-sargent** [comment]
Thanks for the update @emmamarichal!

Just noting that the project currently fails a few Font Bakery tests... I'm very willing to fix these but may need some guidance if the design is accepted :)

**Comment by emmamarichal** [comment]
@emmamarichal, you can try to solve what you can. If the project is accepted, I'll fork your repo, fix the last fails, export the fonts and send you a PR :)

**Comment by davelab6** [comment]
Wow @d-sargent this is really fabulous. Thank you so much for sharing this with the world under OFL! 

@emmamarichal @vv-monsalve @m4rc1e @chrissimpkins please could we prioritize this, it looks like @d-sargent has leveraged the gf guide, fb, glyphsets, etc etc so I expect this should be a quick turnaround ❤️

**Comment by d-sargent** [comment]
Thanks for the kind words @davelab6 excited to see this project in use!
