### ISSUE TITLE
Nunito line-heigth inconsistency

### ISSUE THREAD

**Issue by lawnzapper** [google/fonts#718]
I found a bug related to Nunito line-heights inconsistency between regular and italic style on latest chrome and firefox, tested on some macbook ( see attached image ). I could not find any css solution for this, no vertical-align nor fixed line-height on elements. Is this something already fixed on the last version of the font? Is the google font version the last available?
![screen shot 2017-03-23 at 11 09 55](https://cloud.githubusercontent.com/assets/6951321/24243048/13bbbf64-0fba-11e7-98f6-525f99c972a7.png)

**Comment by m4rc1e** [comment]
Vertical metrics values are the same across the family:

```
Nunito-Italic.ttf
hhea ascent: 1011
OS/2 sTypoAscender: 1011
OS/2 usWinAscent: 1089
hhea descent: -353
OS/2 sTypoDescender: -353
OS/2 usWinDescent: 279
hhea lineGap: 0
OS/2 sTypoLineGap: 0

Nunito-Regular.ttf
hhea ascent: 1011
OS/2 sTypoAscender: 1011
OS/2 usWinAscent: 1089
hhea descent: -353
OS/2 sTypoDescender: -353
OS/2 usWinDescent: 279
hhea lineGap: 0
OS/2 sTypoLineGap: 0
```

Latest version on fonts.google.com is v3.000, v3.001 is being uploaded soonish. This update doesn't change the vertical metrics.

Could you use [jsbin](http://jsbin.com/?html,output) instead of an image?

**Comment by davelab6** [comment]
> Is this something already fixed on the last version of the font? 

Yes, I expect to

> Is the google font version the last available?

A major update was made in the last few months; a minor point release might be available upstream, though

**Comment by m4rc1e** [comment]
I've made up a test:
http://jsbin.com/rumivakihe/edit?html,output

Seems to be a difference in browsers. Fonts are fine.

**Comment by lawnzapper** [comment]
Thank you both for answering

@davelab6 What do you mean with "Yes, I expect to"? Was there a known bug related to this issue?

@m4rc1e thank you, I checked your jsbin and still,

 I'm having issue both on firefox, safari and chrome.
I'd like to investigate further, but I have no clue where to start, maybe it's just related to the macbook
( MacBookAir6,2 | 13,3-inch (1440 x 900) | Intel HD Graphics 5000 1536 MB )

firefox
![firefox_jsbin](https://cloud.githubusercontent.com/assets/6951321/24323044/0293d52a-1170-11e7-8bf3-1ca45c949c30.png)

safari
![safari_jsbin](https://cloud.githubusercontent.com/assets/6951321/24323047/0e04b4ce-1170-11e7-961b-f7fa8a44413b.png)

chrome
![chrome_jsbin](https://cloud.githubusercontent.com/assets/6951321/24323040/ec0edc64-116f-11e7-98f7-a01ef0e7c8ef.png)

**Comment by romamilkovic** [comment]
I got problem with line-height too. Check the example I've made: http://codepen.io/anon/pen/aJrvVL?editors=1100

**Comment by laerm0** [comment]
I haven't been able to reproduce this on any browser in OS X or Windows. Do you still have this issue, @lawnzapper?
