### ISSUE TITLE
Losing Weights in Script Tag Render

### ISSUE THREAD

**Issue by jimmynames** [google/fonts#719]
![screen shot 2017-03-23 at 14 30 31](https://cloud.githubusercontent.com/assets/13485129/24253471/591da3c4-0fd8-11e7-8134-c0d173d43478.png)

Using [React Boilerplate](https://github.com/react-boilerplate/react-boilerplate) 

Not sure what to do..

**Comment by davelab6** [comment]
Can you make a jsbin.com example? :)
