### ISSUE TITLE
Add Sankofa Display

### ISSUE THREAD

**Issue by n8willis** [google/fonts#7192]
[**Sankofa Display Upstream**](https://github.com/batsimadz/Sankofa-Display)

**Super short description of the Font Family:**
Sankofa Display is a typeface that draws inspiration from African art styles, with a focus on straight-line geometric designs.

**Requirements:**

Google Fonts will publish only fonts that match its requirements. Please familiarize yourself with the complete documentation in the [Google Fonts Guide](https://googlefonts.github.io/gf-guide/) (GF-Guide) and ensure your font project complies with them before submitting the font family. You can also use the [Google Fonts Project Template](https://github.com/googlefonts/googlefonts-project-template), which will help you create a repository that follows the needed structure and includes build requirements.

By filling this issue, you can confirm the project meets the  requirements (by ticking the cases or putting x between the square brackets in text mode):

- [x] I read, agree, and comply with the full [contributing requirements](https://googlefonts.github.io/gf-guide/index#pre-production-getting-your-fonts-ready-for-gf)
- [x] The entire font project is licensed under the [OFL](https://scripts.sil.org/cms/scripts/page.php?site_id=nrsi&id=OFL)
- [x] There is no "Reserved Font Name" mention in the OFL license
- [x] Family name is unique according to [namecheck.fontdata.com](https://namecheck.fontdata.com/)
- [x] The font supports at least [GF Latin Core glyphset](https://github.com/googlefonts/glyphsets/tree/main/GF_glyphsets/Latin/)
- [x] The repository respect the [upstream repo structure](https://googlefonts.github.io/gf-guide/upstream.html)
- [x] The source files are available in the repository
- [x] I am the author of the font, or the author agreed to this submission
- [x] I will maintain the repository and participate in the onboarding process (addressing, solving, and responding to issues, merging pull requests, etc)

**Image:**
![sankofa-cover](https://github.com/google/fonts/assets/2192132/33f2e715-4232-462d-81dd-06c7d7512ab2)

**Comment by chrissimpkins** [comment]
Status?

**Comment by n8willis** [comment]
Glyph set is complete. Builds are working, with no FB check fails/fatals/errors. There are about 10 glyphs that require some adjustments to diacritic placement (mostly collisions or too-tight m2mk stacked diacritics; a couple of horizontal alignment tweaks). About 5 or 6 that need some other form of fix, such as path direction or sidebearings.

**Comment by chrissimpkins** [comment]
Thanks Nate. Do we have timing to land these fixes from the development team?

**Comment by chrissimpkins** [comment]
Per Nate, this should be ready by Q2. Moving the milestone

**Comment by n8willis** [comment]
At https://github.com/google/fonts/pull/7581
