### ISSUE TITLE
Open Sans Vietnamese not working in Chrome?

### ISSUE THREAD

**Issue by davelab6** [google/fonts#721]
https://twitter.com/kurz_me/status/844930831193964545 reports an issue with Open Sans Vietnamese in Chrome:

<img width="598" alt="screen shot 2017-03-24 at 15 49 53" src="https://cloud.githubusercontent.com/assets/261579/24311205/8ad46534-10a9-11e7-8596-570955a10e06.png">

**Comment by m4rc1e** [comment]
On Chrome 58.03029.110 (64 bit), browsing http://www.bbc.com/vietnamese/world-40201118, using [fontdragr](http://fontdragr.com) with these [fonts](https://github.com/google/fonts/tree/master/apache/opensans). Everything appears as it should.

![screen shot 2017-06-08 at 11 57 15](https://user-images.githubusercontent.com/7525512/26925472-d8d1b07e-4c41-11e7-8b0a-72565790af82.png)

I'd like to know which tool he is using?

**Comment by laerm0** [comment]
OS X Chrome looks good to me. http://jsbin.com/fiqaleqopi/edit?html,output

![screen region 2017-09-22 at 13 56 25](https://user-images.githubusercontent.com/10780161/30757783-e2dddec6-9f9d-11e7-8d84-282dd7009de7.png)

**Comment by laerm0** [comment]
I wonder what web thinger the user was using. I don't recognize it and that may be the issue.

**Comment by davelab6** [comment]
I asked on Twitter, closing for now as we can't reproduce
