### ISSUE TITLE
Update Lato to v2.015

### ISSUE THREAD

**Issue by DamianGlowala** [google/fonts#7217]
**Font Project Git Repo URL:**
https://github.com/latofonts/lato-source

v2.015:
https://github.com/latofonts/lato-source/issues/47#issuecomment-1851096393

**Current version:**
v1.x

**New available version:**
v2.015

**Super short description of the upgrade:**
Lato v2.015 contains **currently incomplete set of font weights** amongst [other improvements](https://latofonts.github.io/lato-source/#changelog).

**Bugs reported in this repo which this upgrade would fix:**
https://github.com/google/fonts/issues/1415

**Comment by m4rc1e** [comment]
We already attempted this upgrade in the past, https://github.com/google/fonts/issues/6

**Comment by DamianGlowala** [comment]
I am fully aware about the attempted upgrade and unforseen consequences at the time. As per our past email correspondence, this can be added separately as Lato 2 instead of upgrading the existing font.

Was this eventually raised internally? Haven't heard from you on the outcome of these discussions. Could this be issue reopened and considered after so many years?

**Comment by thlinard** [comment]
A bit of a duplicate of #3978?

**Comment by DamianGlowala** [comment]
Thanks for sharing the above issue! I wasn't aware the development of v3 is still in active progress (there weren't any updates for a long time), hence wanted to benefit for now from what we already have available (v2.015). Provided that v3 is meant to be ready _quite soon_, surely let's wait a month or two more :)
