### ISSUE TITLE
Cinzel has latin-extended, yet Google Font reports only latin

### ISSUE THREAD

**Issue by hangya** [google/fonts#722]
Just like the case of Raleway in #119 - Cinzel does have extended latin chars, but they are not available when the font is hosted from Google Web Fonts.
![image](https://cloud.githubusercontent.com/assets/1468753/24322766/d790d940-116a-11e7-8285-32b095dc92e9.png)

**Comment by davelab6** [comment]
Thanks for reporting this! I'll get this enabled soon :)

**Comment by djkoza** [comment]
This problem for me too, please enable latin-ext for it

**Comment by m4rc1e** [comment]
Updated METADATA.py file. Once this goes live, I'll close it.
