### ISSUE TITLE
Update Libre Franklin

### ISSUE THREAD

**Issue by alexeiva** [google/fonts#7228]
**Font Project Git Repo URL:**
https://github.com/alexeiva/Libre-Franklin
**Current version:**
2
**New available version:**
1.500
**Super short description of the upgrade:**
Cyrillic glyph set expansion

**Bugs reported in this repo which this upgrade would fix:**
The Cyrillic version should be synced with latest v2. update before merging.

cc @emmamarichal

**Comment by Twilightssuperb** [comment]
The newer version 3.012 was released on March 31. ;)
