### ISSUE TITLE
Clean up Qahiri

### ISSUE THREAD

**Issue by IvanUkhov** [google/fonts#7234]
The outlines have redundant points as illustrated below.

<img width="1124" alt="Skärmavbild 2024-01-28 kl  10 27 35" src="https://github.com/google/fonts/assets/57440/d9a7646f-81b1-4dc3-b7b3-ace0d924e4b8">

<img width="1126" alt="Skärmavbild 2024-01-28 kl  10 28 29" src="https://github.com/google/fonts/assets/57440/9cec87a3-6dc8-4d23-9668-5268579cc2f5">

**Comment by emmamarichal** [comment]
Thank you @IvanUkhov!
I opened an issue in the upstream repo: https://github.com/aliftype/qahiri/issues/14
I close this one for now, we will open a new one when the font will be ready to update :)

**Comment by khaledhosny** [comment]
FWIW, this appears to be an issue with https://github.com/fonttools/skia-pathops overlap removal, since these glyphs are built from components/multiple paths then skia-pathops is used to remove overlaps, and it leaves these duplicate points.
