### ISSUE TITLE
Add Parastoo

### ISSUE THREAD

**Issue by ubchh** [google/fonts#7241]
**Font Project Git Repo URL:**
https://github.com/rastikerdar/parastoo-font

**Requirements:**

Google Fonts will publish only fonts that match its requirements. Please familiarize yourself with the complete documentation in the [Google Fonts Guide](https://googlefonts.github.io/gf-guide/) (GF-Guide) and ensure your font project complies with them before submitting the font family. You can also use the [Google Fonts Project Template](https://github.com/googlefonts/googlefonts-project-template), which will help you create a repository that follows the needed structure and includes build requirements.

By filling this issue, you can confirm the project meets the  requirements (by ticking the cases or putting x between the square brackets in text mode):

- [x] I read, agree, and comply with the full [contributing requirements](https://googlefonts.github.io/gf-guide/index#pre-production-getting-your-fonts-ready-for-gf)
- [x] The entire font project is licensed under the [OFL](https://scripts.sil.org/cms/scripts/page.php?site_id=nrsi&id=OFL)
- [x] There is no "Reserved Font Name" mention in the OFL license
- [x] Family name is unique according to [namecheck.fontdata.com](https://namecheck.fontdata.com/)
- [x] The font supports at least [GF Latin Core glyphset](https://github.com/googlefonts/glyphsets/tree/main/GF_glyphsets/Latin/)
- [x] The repository respect the [upstream repo structure](https://googlefonts.github.io/gf-guide/upstream.html)
- [x] The source files are available in the repository
- [ ] I am the author of the font, or the author agreed to this submission
- [ ] I will maintain the repository and participate in the onboarding process (addressing, solving, and responding to issues, merging pull requests, etc)

**Image:**

Attach here a pic or a screenshot of the font. One image is enough, it can be a few letters, to give a quick overview.

![301257091-7e231c87-48be-4eef-892d-d5eb62021544](https://github.com/google/fonts/assets/64773544/4da07638-be6c-44f9-8057-696da2857626)

**Notes:**
This font named "Parastoo Font" ,originally created by the Saber Rastikerdar. This font has greatly interested me, and I would love to have the ability to use it in Google Slides. However, due to the unfortunate passing of the author,  no one will be able to maintain and update the font in the future. Thanks!
Parastoo Font on this free font site: https://fontserver.ir/font/Parastoo

**Comment by ubchh** [comment]
Hi @emmamarichal , 
Thank you very much for adding this into queue.
Since the author passed away. Is there anything I can do from my end?

Henry

**Comment by applecuckoo** [comment]
@emmamarichal Parastoo is already tracked in #5917.

**Comment by emmamarichal** [comment]
thanks! I'm closing this one
