### ISSUE TITLE
Add Nsibidi Libre => renamed to Agu Display

### ISSUE THREAD

**Issue by n8willis** [google/fonts#7243]
**Font Project Git Repo URL:** https://github.com/theseunbadejo/nsibidi-libre

**Super short description of the Font Family:** Nsibidi (also known as nsibiri, nchibiddi or nchibiddy) is an ancient system of graphic communication indigenous to the Ejagham peoples of southeastern Nigeria and southwestern Cameroon in the Cross River region. It is also used by neighboring Ibibio, Efik and Igbo peoples.

The Nsibidi Libre typeface is a vehicle for cultural preservation, storytelling, and bridging the gap between ancient symbolic communication and modern typographic expression.

**note:** the name Nsibidi Libre is slated to change prior to release.

**Requirements:**

Google Fonts will publish only fonts that match its requirements. Please familiarize yourself with the complete documentation in the [Google Fonts Guide](https://googlefonts.github.io/gf-guide/) (GF-Guide) and ensure your font project complies with them before submitting the font family. You can also use the [Google Fonts Project Template](https://github.com/googlefonts/googlefonts-project-template), which will help you create a repository that follows the needed structure and includes build requirements.

By filling this issue, you can confirm the project meets the  requirements (by ticking the cases or putting x between the square brackets in text mode):

- [x] I read, agree, and comply with the full [contributing requirements](https://googlefonts.github.io/gf-guide/index#pre-production-getting-your-fonts-ready-for-gf)
- [x] The entire font project is licensed under the [OFL](https://scripts.sil.org/cms/scripts/page.php?site_id=nrsi&id=OFL)
- [x] There is no "Reserved Font Name" mention in the OFL license
- [x] Family name is unique according to [namecheck.fontdata.com](https://namecheck.fontdata.com/)
- [x] The font supports at least [GF Latin Core glyphset](https://github.com/googlefonts/glyphsets/tree/main/GF_glyphsets/Latin/)
- [x] The repository respect the [upstream repo structure](https://googlefonts.github.io/gf-guide/upstream.html)
- [x] The source files are available in the repository
- [x] I am the author of the font, or the author agreed to this submission
- [x] I will maintain the repository and participate in the onboarding process (addressing, solving, and responding to issues, merging pull requests, etc)

**Image:**

Attach here a pic or a screenshot of the font. One image is enough, it can be a few letters, to give a quick overview.

**Comment by n8willis** [comment]
There are about 18 glyphs remaining that require completion in one or more masters (out of three). It looks like all of those are in the extended Latin African set.

**Comment by chrissimpkins** [comment]
Updating to P2 in Q4

**Comment by chrissimpkins** [comment]
What's the development status of this project @n8willis?

**Comment by chrissimpkins** [comment]
> If we have the thumbs-up to ship it with custom style names for the MORF axis, that's doable. But it has to go in the "exception" column because, like Kablammo and Sixtyfour, it doesn't use an off-the-shelf set of style/subfamily names.

Will you please detail this issue here so that we can decide on it?  What are the names and axes involved?

**Comment by m4rc1e** [comment]
@chrissimpkins I'm revising how we master fonts with MORF. Will bring it up in the meeting later.

**Comment by n8willis** [comment]
Sure. First thing, for the record, is that the font was renamed and thus so was the repo; it's now at https://github.com/theseunbadejo/Agu-Display

Details: 
- Only one variable axis, `MORF`
- Three named instances:
  - Uzo (at `MORF = 0`)
  - Ala (at `MORF = 30`)
  - Osisi (at `MORF=60`)

Those instances each correspond to a distinct set of decorations/ornaments with different shapes; in the variable font, moving through in-between values causes the current set of decorations/ornaments to rotate or move. At the breakpoints, the decorations are swapped via Alternate layers in the Glyphs source. So each of the three instances (and/or static instantiated fonts) gives the user one of the three ornament sets.

**Comment by chrissimpkins** [comment]
Marc believes that he has an approach to address this, and that it will work across environments. Including InDesign.  Further testing in progress to finalize the plan.  Nate plans to open a PR for this family over ~ the next week.  We do not see a current onboarding blocker.

**Comment by n8willis** [comment]
PR is open: https://github.com/google/fonts/pull/8487
