### ISSUE TITLE
Voor

### ISSUE THREAD

**Issue by renatoforster** [google/fonts#7254]
**Font Project Git Repo URL:**

**Super short description of the Font Family:**

**Requirements:**

Google Fonts will publish only fonts that match its requirements. Please familiarize yourself with the complete documentation in the [Google Fonts Guide](https://googlefonts.github.io/gf-guide/) (GF-Guide) and ensure your font project complies with them before submitting the font family. You can also use the [Google Fonts Project Template](https://github.com/googlefonts/googlefonts-project-template), which will help you create a repository that follows the needed structure and includes build requirements.

By filling this issue, you can confirm the project meets the  requirements (by ticking the cases or putting x between the square brackets in text mode):

- [ ] I read, agree, and comply with the full [contributing requirements](https://googlefonts.github.io/gf-guide/index#pre-production-getting-your-fonts-ready-for-gf)
- [ ] The entire font project is licensed under the [OFL](https://scripts.sil.org/cms/scripts/page.php?site_id=nrsi&id=OFL)
- [ ] There is no "Reserved Font Name" mention in the OFL license
- [ ] Family name is unique according to [namecheck.fontdata.com](https://namecheck.fontdata.com/)
- [ ] The font supports at least [GF Latin Core glyphset](https://github.com/googlefonts/glyphsets/tree/main/GF_glyphsets/Latin/)
- [ ] The repository respect the [upstream repo structure](https://googlefonts.github.io/gf-guide/upstream.html)
- [ ] The source files are available in the repository
- [ ] I am the author of the font, or the author agreed to this submission
- [ ] I will maintain the repository and participate in the onboarding process (addressing, solving, and responding to issues, merging pull requests, etc)

**Image:**

Attach here a pic or a screenshot of the font. One image is enough, it can be a few letters, to give a quick overview.

**Comment by inferno986return** [comment]
You seem to be the font designer: https://www.behance.net/Forster

Can you create a GitHub repository using Google's recommended guidelines and provide the source files under the SIL OFL without a reserved name?

![image](https://github.com/google/fonts/assets/1838420/35b45516-6e3a-4b9d-a23d-359820c93345)

**Comment by emmamarichal** [comment]
There are no repo, no sources. I close this issue, feel free to open a new one when the font respect the Google Fonts requirements: https://googlefonts.github.io/gf-guide/upstream.html

**Comment by renatoforster** [comment]
Hi Emma, apparently is super hard to meet the Google Fonts requirements as
a designer and not a coder. I’ll need some help to do that.
Thank you, anyway.


*RENATO FORSTER*
+55 11 *998* *347* *527*
***@***.**** ***@***.***>




*LESTERS.BY <http://LESTERS.BY>*

**Comment by emmamarichal** [comment]
Yes of course, I can help.
What software are you using? And could you edit your first comment, checking the requirements, adding the repo link etc?
Then, you will find all the documentation you will need here: https://googlefonts.github.io/gf-guide/, and you doesn't need to be a coder. I'll help with the more difficult part (like exporting fonts with our tools)

**Comment by emmamarichal** [comment]
But first, we need to review the project, to see if we accept it or not, and for that, we would need at least the sources.

**Comment by renatoforster** [comment]
Hi Emma, I'm gonna need to hit a pause on that. I just found out that I lost the original Glyphs source files so I'll have to build that again. In the end, this is going to be for the best as I can finally create a 3 weights/styles family out of it as it was originally planned but I never had the time (or energy) to do so. 

Should I delete this project or keep it alive until I rebuild the typeface Glyph source files?

**Comment by emmamarichal** [comment]
@renatoforster, ok no problem. I let closed that issue, feel free to open a new one when/if the project is ready to onboard :)
Cheers!

**Comment by renatoforster** [comment]
Thank you so much!
