### ISSUE TITLE
keep_off icon missing in Google Material+Icons but used in apps like Google Meet, which is opposite of push_pin

### ISSUE THREAD

**Issue by mattiLeBlanc** [google/fonts#7255]
I am using Material Font icons for Angular with Angular Material Design components. I use push_pin to pin something, but I cant use `keep_off` which is available in google material icons used in apps like Google Meet. So there is no `unpin` icon available.

<img width="41" alt="image" src="https://github.com/google/fonts/assets/5285035/675b0540-af4d-483b-9a15-140592a8927b">

Is it possible to add this icon to the collection?

**Comment by emmamarichal** [comment]
Hello @mattiLeBlanc!
Thank you for the suggestion. I invite you to open an issue in the corresponding repo: https://github.com/google/material-design-icons/issues

I close this issue,
Cheers!
