### ISSUE TITLE
رفض التنزيل

### ISSUE THREAD

**Issue by MOHAMMEDABBASELHAG** [google/fonts#7257]
Specify the font name in title with a short description of the bug. 
Please report any issue related to Noto fonts [here](https://notofonts.github.io/reporter.html).
Report any issue with Google Icon/Symbols [here](https://github.com/google/material-design-icons)

**Describe the bug**

**To Reproduce**
Steps to reproduce the behavior.

**Expected behavior**

**Screenshots**

**Additional context**
Add any other context about the problem here (OS version, browser, printer…)

**Comment by emmamarichal** [comment]
No context, I close that issue
