### ISSUE TITLE
Inter: After a serie of "@", "(", or ")" and a capital letter, the tail shifts up

### ISSUE THREAD

**Issue by retueZe** [google/fonts#7258]
**Describe the bug**

If you type a serie of "@", "(', or ")" (you may mix them), and a capital latin letter, the tail of the line shifts up (doesn't work with other punctuation characters or lowercase letters).

**To Reproduce**

```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Inter&display=swap" rel="stylesheet">
    <style>
        textarea {
            font-family: Inter;
            font-size: 20px;
            font-weight: 400;
        }
    </style>
</head>
<body>
    <textarea></textarea>
</body>
</html>
```

**Expected behavior**

The baseline of each letter in the line should be equal.

**Screenshots**

![image](https://github.com/google/fonts/assets/84510709/789381f9-13c8-4814-bf39-c8fa3aedb14e)
![image](https://github.com/google/fonts/assets/84510709/d483ad45-7965-48cd-823b-0d294ab0f08d)
![image](https://github.com/google/fonts/assets/84510709/d3c3139a-b462-4718-bdcb-d01c36f7af9f)
![image](https://github.com/google/fonts/assets/84510709/1a095a5d-9d0e-4d2c-b712-fce302e074ea)

**Additional context**

OS: Windows 10 x64
Browser: Chrome 121.0.6167.140 64-bit

**Comment by tiroj** [comment]
My guess is that Inter might be applying the OpenType Layout ‘case’ feature contextually, rather than relying on software to trigger the feature in all-caps settings. This is causing the raised glyphs for parentheses and @ symbol to be triggered in some situations where not appropriate.

**Comment by retueZe** [comment]
Is there anything I can do to fix this bug besides switching the font?

**Comment by The-MAZZTer** [comment]
Easiest to see with * instead of @ ( ).

Also happens if the ending character is ?

![image](https://github.com/user-attachments/assets/1bc2c188-4821-4d98-a31c-48532f308012)

**Comment by The-MAZZTer** [comment]
Applying the following CSS works around this issue:

```css
font-feature-settings: 'calt' 0;
```

![image](https://github.com/user-attachments/assets/afe75082-a3fb-4261-b9fa-c09a2e0057d0)

**Comment by davelab6** [comment]
@The-MAZZTer that is what I was going to say :) I think its an upstream issue so closing here and directing your attention to https://github.com/rsms/inter/issues/737
