### ISSUE TITLE
Improve Josefin Slab kerning 

### ISSUE THREAD

**Issue by davelab6** [google/fonts#7264]
On 2016-03-04 an internal user reported `We` needs kerning; this is still the case.

https://fonts.google.com/specimen/Josefin+Slab?preview.text=Wedding&query=josefin

<img width="206" alt="Screenshot 2024-02-07 at 09 50 11" src="https://github.com/google/fonts/assets/261579/41d10c68-3885-49a0-a437-5c718232ea28">

**Comment by emmamarichal** [comment]
I only found this repo: https://github.com/davelab6/josefinslab
Let me know if you know another one, otherwise, could you create one on googlefonts/ ?

**Comment by m4rc1e** [comment]
Last update was https://github.com/google/fonts/pull/2749 so Dave's version is correct.

**Comment by emmamarichal** [comment]
@chrissimpkins @davelab6 
I solved this kerning issue, but there are a lot of fails remaining. https://github.com/googlefonts/josefinslab/pull/31

Let me know if you want to me to spend more time on it or if the kerning update is enough for now.

**Comment by chrissimpkins** [comment]
IMO, yes we can stage the improvements. But will require a new issue on the tracker for what we intend to address when this kerning update lands.  Can I ask you to add this to the pipeline meeting agenda and we can go through the FB fails/warns to decide? Ty!
