### ISSUE TITLE
Single quote in the place of double quote in Oswald Light

### ISSUE THREAD

**Issue by debugfi** [google/fonts#729]
Oswald Light have single quote in the place of double quote. Other weights of the font have the correct double quotes.

<img width="323" alt="screenshot 2017-04-01 23 15 19" src="https://cloud.githubusercontent.com/assets/3791627/24582157/63c7c546-1732-11e7-99ff-8d26a1beb846.png">
<img width="322" alt="screenshot 2017-04-01 23 15 03" src="https://cloud.githubusercontent.com/assets/3791627/24582158/63c7cf0a-1732-11e7-81e9-5ed2b21ab0e0.png">

**Comment by davelab6** [comment]
@debugfi thanks for reporting this! 

@m4rc1e please could you take care of this :)

cc @kalapi

**Comment by m4rc1e** [comment]
Has been fixed in #659

![oswald-light-dbl-quote](https://cloud.githubusercontent.com/assets/7525512/24615648/c67fcbc0-1886-11e7-80a6-24146888977c.gif)


Version served on GF is v4.001, #659 is v4.002. It should be uploaded soonish

**Comment by davelab6** [comment]
Ah yes, great :)

**Comment by laerm0** [comment]
This is online now, so I'm closing.

![screen region 2017-09-19 at 16 00 12](https://user-images.githubusercontent.com/10780161/30612773-a87b5778-9d53-11e7-88d3-1ec393b9f8a9.png)
