### ISSUE TITLE
+Select this styleが表示されない

### ISSUE THREAD

**Issue by mizu33333** [google/fonts#7294]
![スクリーンショット 2024-02-17 100912](https://github.com/google/fonts/assets/160292892/a36b4e48-b940-4e61-8738-dba9ee6dde01)

webブラウザはGooglechromeを使用しています。
chromeは新しいバージョンになっており、正常に動作しております。

Googlefontsを開いてフォントをインストールせずに使用しようとしたところ、
各フォントの右横に　+Select this style　という青文字で表記されたものが出ません。
スクリーンショットのように何も選択ができない、ただフォントが表示されるだけになります。

解決方法はありますでしょうか。

**Comment by simoncozens** [comment]
ご利用ありがとうございます。最近、解決方法が変わったのですね。もう少し「ショッピングカート」みたいな選択方法にしました。

つまり、フォントを選択してから、上右の「買物袋」アイコンをクリックすると、ダウンロードとエムベッドの説明が表示されます。

<img width="458" alt="Screenshot 2024-02-19 at 07 07 34" src="https://github.com/google/fonts/assets/106728/df47bd63-a427-44fa-a60a-bed8ea9c50d3">
