### ISSUE TITLE
Add Moderustic

### ISSUE THREAD

**Issue by Tural** [google/fonts#7295]
**Font Project Git Repo URL:** https://github.com/Tural/moderustic

**Current version:*2.000*

**New available version:*2.100*

**Super short description of the upgrade:**
Some of the glyphs have been updated. Source folder and Fonts folders have been updated.

**Bugs reported in this repo which this upgrade would fix:**
Search in the [issue tracker](https://github.com/google/fonts/issues) if there is some opened issues containing the font name.

**Comment by m4rc1e** [comment]
Thank you for the submission. Looks pretty polished. I'll raise it with the team on Thursday.

![Bold-diffbrowsers_glyphs-macOS-13 1-arm64-arm-64bit_firefox_108 0 1](https://github.com/google/fonts/assets/7525512/1b5c21e8-19b0-4d4d-bac4-cda8c11bae5d)

![Bold-diffbrowsers_text-macOS-13 1-arm64-arm-64bit_firefox_108 0 1](https://github.com/google/fonts/assets/7525512/c4533a78-1b78-46bb-81a6-58c12f926470)


![Bold-diffbrowsers_waterfall-macOS-13 1-arm64-arm-64bit_firefox_108 0 1](https://github.com/google/fonts/assets/7525512/ad936f35-b520-4076-a883-a5db4d03363d)

**Comment by m4rc1e** [comment]
![Regular-diffbrowsers_waterfall-macOS-13 1-arm64-arm-64bit_firefox_108 0 1](https://github.com/google/fonts/assets/7525512/a5d1435e-f2d5-4d82-ad9d-61c57f40d77d)


![Regular-diffbrowsers_text-macOS-13 1-arm64-arm-64bit_firefox_108 0 1](https://github.com/google/fonts/assets/7525512/136bda21-8b59-44b9-bfbd-e000c6be7f80)

**Comment by Tural** [comment]
Thanks, @m4rc1e Moderustic font should be released this year first quarter. It would be best if this change were accepted before release.

**Comment by Tural** [comment]
@emmamarichal Hi. This is not considered a new font. You have approved this font. I just updated the approved font in a bit. I ask because I don't know, is it supposed to be like this? Should it be marked as "I new font"?

**Comment by applecuckoo** [comment]
Just linking back the original issue which was indeed specified in the original title: #6926. @eliheuer was helping onboard this font.
