### ISSUE TITLE
womanDancing and manDancing emojis are shown as the same

### ISSUE THREAD

**Issue by SimpleHK** [google/fonts#7298]
Are these two expressions designed to look the same?

![image](https://github.com/google/fonts/assets/44436877/fdf65a56-305e-45c2-a83f-ce05f9e540d1)
![image](https://github.com/google/fonts/assets/44436877/9698b5fd-5a65-437e-882e-6a688dc18fd7)

**Comment by m4rc1e** [comment]
What font are you inspecting?

**Comment by SimpleHK** [comment]
noto emoji

**Comment by SimpleHK** [comment]
Thank you very much, I have learned a lot.
