### ISSUE TITLE
Fix italic metadata for Android

### ISSUE THREAD

**Issue by davelab6** [google/fonts#73]
These families have multiple distinct styles/weights for which the same Android `SkFontStyle` is returned, typically because Italic reports as non-Italic because a bit isn't set:
- [x] `ofl/exo2`
- [ ] `ofl/jaldi`
- [x] `ofl/josefinsans`
- [x] `ofl/kantumruy`
- [x] `ofl/muli`
- [ ] `ofl/scheherazade`
- [ ] `ofl/share`
- [x] `ofl/vollkorn`

**Comment by rsheeter** [comment]
FYI, the following seem to have fonts thatget the same `Typeface.getStyle` value (eg `Skia's SkTypeface->style()`) even when just looking at 400/700 upright/italic:

```
Jaldi is BROKEN ([0, 0])
Josefin Sans is BROKEN ([0, 0, 1, 3])
Muli is BROKEN ([2, 2])
Share is BROKEN ([0, 0, 1, 1])
Vollkorn is BROKEN ([0, 0, 1, 1])
```

**Comment by davelab6** [comment]
@m4rc1e please could you verify this is all fixed?

**Comment by m4rc1e** [comment]
We're good. All the Android fonts you requested to be hotfixed have made it into production:

| family            | date       |
|-------------------|------------|
| abeezee           | 2017-08-24 |
| abhayalibre       | 2017-08-24 |
| alegreyasc        | 2017-08-24 |
| alegreyasans      | 2017-08-24 |
| alegreyasanssc    | 2017-08-24 |
| allan             | 2017-08-24 |
| atma              | 2017-08-24 |
| averiagruesalibre | 2017-08-24 |
| benchnine         | 2017-08-24 |
| biryani           | 2017-08-24 |
| cambay            | 2017-08-24 |
| carroisgothic     | 2017-08-24 |
| carroisgothicsc   | 2017-08-24 |
| chathura          | 2017-08-24 |
| chauphilomeneone  | 2017-08-24 |
| cinzel            | 2017-08-31 |
| cinzeldecorative  | 2017-08-24 |
| coda              | 2017-08-24 |
| codacaption       | 2017-08-24 |
| coustard          | 2017-08-24 |
| crimsontext       | 2017-08-28 |
| eczar             | 2017-08-28 |
| elsie             | 2017-08-28 |
| elsieswashcaps    | 2017-08-28 |
| fingerpaint       | 2017-08-28 |
| flamenco          | 2017-08-28 |
| halant            | 2017-08-28 |
| hanuman           | 2017-08-28 |
| hind              | 2017-08-28 |
| hindguntur        | 2017-08-28 |
| hindmadurai       | 2017-08-28 |
| hindsiliguri      | 2017-08-28 |
| hindvadodara      | 2017-08-28 |
| inknutantiqua     | 2017-08-28 |
| josefinslab       | 2017-08-28 |
| kanit             | 2017-08-28 |
| karma             | 2017-08-28 |
| khand             | 2017-08-28 |
| khula             | 2017-08-28 |
| kreon             | 2017-08-28 |
| kristi            | 2017-08-28 |
| laila             | 2017-08-28 |
| londrinaoutline   | 2017-08-28 |
| mada              | 2017-08-28 |
| martelsans        | 2017-08-29 |
| mirza             | 2017-08-29 |
| mitr              | 2017-08-29 |
| mogra             | 2017-08-29 |
| novascript        | 2017-08-29 |
| opensans          | 2017-08-24 |
| opensanscondensed | 2017-08-24 |
| orbitron          | 2017-08-29 |
| overlock          | 2017-08-29 |
| oxygen            | 2017-08-29 |
| palanquin         | 2017-08-29 |
| palanquindark     | 2017-08-29 |
| passionone        | 2017-08-29 |
| pathwaygothicone  | 2017-08-29 |
| poppins           | 2017-08-29 |
| pridi             | 2017-08-29 |
| rajdhani          | 2017-08-29 |
| ranga             | 2017-08-29 |
| rasa              | 2017-08-29 |
| rozhaone          | 2017-08-29 |
| ruda              | 2017-08-29 |
| sarpanch          | 2017-08-29 |
| share             | 2017-08-29 |
| shrikhand         | 2017-08-29 |
| signika           | 2017-08-29 |
| signikanegative   | 2017-08-29 |
| simonetta         | 2017-08-29 |
| sofadione         | 2017-08-29 |
| sourcecodepro     | 2017-08-29 |
| sourcesanspro     | 2017-08-29 |
| tangerine         | 2017-08-29 |
| taviraj           | 2017-08-29 |
| teko              | 2017-08-29 |
| tienne            | 2017-08-29 |
| tillana           | 2017-08-29 |
| titilliumweb      | 2017-08-29 |
| trirong           | 2017-08-29 |
| ubuntu            | 2017-08-29 |
| vollkorn          | 2017-08-31 |
| yantramanav       | 2017-08-29 |
| yatraone          | 2017-08-29 |
| yrsa              | 2017-08-29 |

**Comment by davelab6** [comment]
@rsheeter could you verify and close this?
