### ISSUE TITLE
Nunito line-height issues in web

### ISSUE THREAD

**Issue by romamilkovic** [google/fonts#731]
Hello everyone,

I found a bug with line-height using Nunito. Text with Nunito a bit higher and align to top. 
<img width="1272" alt="screen shot 2017-04-06 at 15 47 59" src="https://cloud.githubusercontent.com/assets/10784316/24743386/9a02c71c-1ae0-11e7-8b67-4ca9d1cf6be2.png">

Tested on:
1. Mac OS[10.12.4] - Chrome[Version 57.0.2987.133 (64-bit)] – bug;
2. Ubuntu[16.04 64bit] - Chrome[Version 57.0.2987.133 (64-bit)] – bug;
3. Win 7 - Chrome – bug.;
4. Latest iOS Safari - works fine;

Live example: 
http://codepen.io/anon/pen/aJrvVL?editors=1100

**Comment by m4rc1e** [comment]
If we also include a serif font, the alignments are different.

![screen shot 2017-04-06 at 15 35 44](https://cloud.githubusercontent.com/assets/7525512/24759885/cce91c46-1ade-11e7-9ed3-5d8019d99d0c.png)

The vertical metrics for a family can be unique, they don't have to conform to Helvetica's.

**Comment by romamilkovic** [comment]
Is there a way to fix this visual issue?

**Comment by m4rc1e** [comment]
@romamilkovic in the .btn css style, change the line-height. Its currently at 40px.

**Comment by romamilkovic** [comment]
@m4rc1e yeah you are right, if change line-height to 39px it looks perfect. Just looks like Nunito is aligned higher on 1px. Is it not bug?

**Comment by m4rc1e** [comment]
@romamilkovic you can also align the button. Apologies, I'm away from the laptop so I can't help you further.

**Comment by romamilkovic** [comment]
@m4rc1e What you mean 'align the button'?

**Comment by romamilkovic** [comment]
Looks like the font has bottom offset 1px. 😟

**Comment by laerm0** [comment]
The fonts are fine with regard to glyph metrics and I see no issues otherwise so I'm going to suggest that this is entirely due to differences in the way Nunito is hinted compared to Helvetica.

**Comment by davelab6** [comment]
Agreed
