### ISSUE TITLE
Noto Serif Khojki and Noto Sans Khojki have tofu

### ISSUE THREAD

**Issue by emmamarichal** [google/fonts#7317]
@simoncozens 

No problem in the sandbox, but some tofu appeared then, on the API.

Sample text to test:

𑈩𑈤𑈨𑈦𑈬𑈺𑈀𑈞𑈩𑈬𑈞𑈺𑈁𑈐𑈶𑈬𑈛𑈺𑈂𑈺𑈀𑈐𑈶𑈙𑈺𑈂𑈺𑈪𑈈𑈶𑈞𑈺𑈑𑈥𑈺𑈪𑈨𑈬𑈧𑈥𑈺𑈈𑈀𑈞𑈺𑈞𑈦𑈬𑈞𑈦𑈺𑈟𑈥𑈛𑈬𑈔𑈥𑈬

<img width="584" alt="Screenshot 2024-02-23 at 10 56 38" src="https://github.com/google/fonts/assets/64773544/d20738ef-91ae-4a1f-b53c-f81a5d9a017d">

**Comment by simoncozens** [comment]
This seems to be fixed now.
