### ISSUE TITLE
Inconsolata doesn't have box-drawing characters

### ISSUE THREAD

**Issue by aditsu** [google/fonts#732]
I was trying to display some [box-drawing characters](https://en.wikipedia.org/wiki/Box-drawing_character) using Inconsolata, and they didn't line up properly because it was using a different fallback font. Please add these characters, as they are often used in contexts that require monospaced fonts.

**Comment by davelab6** [comment]
While I could add them, I don't think they will be included in the [Google Fonts API `latin-ext` subset](https://github.com/google/fonts/blob/master/tools/encodings/latin-ext_unique-glyphs.nam)

For this special case, I suggest finding (or making) a derivative that has what you want ant self-hosting it.

**Comment by aditsu** [comment]
My request is not related to Google Fonts, I just wanted to file this issue against Inconsolata in general.
The information I found says the official upstream is here, but if there's a better place for that, please let me know.
It looks like some people have already published modified versions of Inconsolata, some of which include box-drawing characters, but a change to the official release would be much preferable, as it would ensure both wide availability and consistent quality.

**Comment by ekevoo** [comment]
Agreed. I ended up here to request Braille characters (which are also very useful for monospace drawing use cases), and to me this effectively means this amazing font is abandoned.
