### ISSUE TITLE
Issue with google font Roboto

### ISSUE THREAD

**Issue by frenky2334** [google/fonts#735]
Hi! I use Roboto font in my project and I noticed that on iphone font looks different from desktop.
I compared site in Chrome DevTools on two devices and when i used Nexus 5X (look at first image), i got woff2 font format and it look fine. However when i choose iphone 6 (look at second image), i got woff font fomat and it was no roboto. It feels like in Roboto woff format is no cyrillic. Who faced this problem? Please, help me!
![selection_108](https://cloud.githubusercontent.com/assets/26610655/25327080/715c239a-28db-11e7-93e0-ce8fecf47594.jpg)
![selection_109](https://cloud.githubusercontent.com/assets/26610655/25327085/770b3e70-28db-11e7-8367-799ffaf26464.jpg)

**Comment by davelab6** [comment]
Could you post the URL (or recreate with jsbin.com) so I can reproduce? :)

**Comment by frenky2334** [comment]
@davelab6 
sure :)
https://m.repka.ua/noutbuki/hp-255-w4m79ea-337058/

**Comment by m4rc1e** [comment]
Just made up a jsbin and tested it on my Iphone SE, IOS 10.3.2.

![img_0657](https://user-images.githubusercontent.com/7525512/27281206-c7d85fbc-54e2-11e7-8275-374c6c05f72c.PNG)

Looks like Roboto to me. I'm certain this is an implementation issue on your site.

**Comment by m4rc1e** [comment]
@frenky2334 is this still an issue?

**Comment by Gerry1135** [comment]
The original report mentions Cyrillic chars.  Perhaps you could change your jsbin to use them?  It may still be an implementation issue on his site (e.g. specifying a silly subset) but it may not be...

**Comment by davelab6** [comment]
@frenky2334 please reopen if this issue persists
