### ISSUE TITLE
Commercial use 

### ISSUE THREAD

**Issue by jplajpla23** [google/fonts#7371]
I read in google documentation that the icons fonts can be used for commercial projects. And read too that are not required attribution.

my questions is the next

can I convert the icons to others formats (vectorial formats like svg, adobe ,….) and sell that digital files without specify that are a google icons. And if is allowed too sell the files converted in others formats only.

best regards Joao

**Comment by davelab6** [comment]
Please read the license and comply with the requirements. We can't offer legal advice.
