### ISSUE TITLE
Why does Roboto not display in Firefox Nightly?

### ISSUE THREAD

**Issue by sucrose** [google/fonts#738]
I receive these errors in the console on my Windows 7 system using Firefox 54.0a2 (2017-04-26) (64-bit):

`downloadable font: Layout: DFLT script doesn't satisfy the spec. DefaultLangSys is NULL (font-family: "Roboto" style:normal weight:normal stretch:normal src index:2) source: http://fonts.gstatic.com/s/roboto/v16/CWB0XYA8bzo0kSThX0UTuA.woff2  css:50:12`

`downloadable font: Layout: Failed to parse script table 0 (font-family: "Roboto" style:normal weight:normal stretch:normal src index:2) source: http://fonts.gstatic.com/s/roboto/v16/CWB0XYA8bzo0kSThX0UTuA.woff2  css:50:12`

`downloadable font: GSUB: Failed to parse script list table (font-family: "Roboto" style:normal weight:normal stretch:normal src index:2) source: http://fonts.gstatic.com/s/roboto/v16/CWB0XYA8bzo0kSThX0UTuA.woff2  css:50:12`

`downloadable font: rejected by sanitizer (font-family: "Roboto" style:normal weight:normal stretch:normal src index:2) source: http://fonts.gstatic.com/s/roboto/v16/CWB0XYA8bzo0kSThX0UTuA.woff2`

This happens when `gfx.downloadable_fonts.otl_validation` is set to true (the default for Nightly but not stable releases)

**Comment by scheinercc** [comment]
Here is a related comment from Firefox's bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1331797#c19

**Comment by davelab6** [comment]
Thanks @sucrose and @scheinercc :) Will take a look at this!

**Comment by JosepBarrera** [comment]
I receive similar errors in console, win 10 Firefox 54.02a (2017-05-11) (32-bit)
downloadable font: Layout: DFLT script doesn't satisfy the spec. DefaultLangSys is NULL (font-family: "Roboto" style:normal weight:normal stretch:normal src index:2) source: https://fonts.gstatic.com/s/roboto/v16/CWB0XYA8bzo0kSThX0UTuA.woff2  css:106:12
downloadable font: Layout: Failed to parse script table 0 (font-family: "Roboto" style:normal weight:normal stretch:normal src index:2) source: https://fonts.gstatic.com/s/roboto/v16/CWB0XYA8bzo0kSThX0UTuA.woff2  css:106:12
downloadable font: GSUB: Failed to parse script list table (font-family: "Roboto" style:normal weight:normal stretch:normal src index:2) source: https://fonts.gstatic.com/s/roboto/v16/CWB0XYA8bzo0kSThX0UTuA.woff2  css:106:12
downloadable font: rejected by sanitizer (font-family: "Roboto" style:normal weight:normal stretch:normal src index:2) source: https://fonts.gstatic.com/s/roboto/v16/CWB0XYA8bzo0kSThX0UTuA.woff2  css:106:12
downloadable font: Layout: DFLT script doesn't satisfy the spec. DefaultLangSys is NULL (font-family: "Roboto" style:normal weight:500 stretch:normal src index:2) source: https://fonts.gstatic.com/s/roboto/v16/RxZJdnzeo3R5zSexge8UUVtXRa8TVwTICgirnJhmVJw.woff2  css:162:12
downloadable font: Layout: Failed to parse script table 0 (font-family: "Roboto" style:normal weight:500 stretch:normal src index:2) source: https://fonts.gstatic.com/s/roboto/v16/RxZJdnzeo3R5zSexge8UUVtXRa8TVwTICgirnJhmVJw.woff2  css:162:12
downloadable font: GSUB: Failed to parse script list table (font-family: "Roboto" style:normal weight:500 stretch:normal src index:2) source: https://fonts.gstatic.com/s/roboto/v16/RxZJdnzeo3R5zSexge8UUVtXRa8TVwTICgirnJhmVJw.woff2  css:162:12
downloadable font: rejected by sanitizer (font-family: "Roboto" style:normal weight:500 stretch:normal src index:2) source: https://fonts.gstatic.com/s/roboto/v16/RxZJdnzeo3R5zSexge8UUVtXRa8TVwTICgirnJhmVJw.woff2  css:162:12

**Comment by K900** [comment]
Any update on this?

**Comment by DanielRuf** [comment]
Also I see another issue with `local("Roboto") in Firefox for Android which does not use the right font-weight on Android 6.

Can anyone confirm this?

**Comment by jonthegiant** [comment]
Seeing the same issue.

Windows 8.1

Firefox Developer Edition version
(aurora update channel)
```
54.0a2 (2017-04-18) (32-bit)
```
Requested URL
```
https://material.io/components/web/catalog/buttons/
```

Console output
```
downloadable font: Layout: DFLT script doesn't satisfy the spec. DefaultLangSys is NULL (font-family: "Roboto" style:normal weight:normal stretch:normal src index:2) source: https://fonts.gstatic.com/s/roboto/v16/CWB0XYA8bzo0kSThX0UTuA.woff2  css:106:12
downloadable font: Layout: Failed to parse script table 0 (font-family: "Roboto" style:normal weight:normal stretch:normal src index:2) source: https://fonts.gstatic.com/s/roboto/v16/CWB0XYA8bzo0kSThX0UTuA.woff2  css:106:12
downloadable font: GSUB: Failed to parse script list table (font-family: "Roboto" style:normal weight:normal stretch:normal src index:2) source: https://fonts.gstatic.com/s/roboto/v16/CWB0XYA8bzo0kSThX0UTuA.woff2  css:106:12
downloadable font: rejected by sanitizer (font-family: "Roboto" style:normal weight:normal stretch:normal src index:2) source: https://fonts.gstatic.com/s/roboto/v16/CWB0XYA8bzo0kSThX0UTuA.woff2  css:106:12
downloadable font: Layout: DFLT script doesn't satisfy the spec. DefaultLangSys is NULL (font-family: "Roboto" style:normal weight:500 stretch:normal src index:2) source: https://fonts.gstatic.com/s/roboto/v16/RxZJdnzeo3R5zSexge8UUVtXRa8TVwTICgirnJhmVJw.woff2  css:162:12
downloadable font: Layout: Failed to parse script table 0 (font-family: "Roboto" style:normal weight:500 stretch:normal src index:2) source: https://fonts.gstatic.com/s/roboto/v16/RxZJdnzeo3R5zSexge8UUVtXRa8TVwTICgirnJhmVJw.woff2  css:162:12
downloadable font: GSUB: Failed to parse script list table (font-family: "Roboto" style:normal weight:500 stretch:normal src index:2) source: https://fonts.gstatic.com/s/roboto/v16/RxZJdnzeo3R5zSexge8UUVtXRa8TVwTICgirnJhmVJw.woff2  css:162:12
downloadable font: rejected by sanitizer (font-family: "Roboto" style:normal weight:500 stretch:normal src index:2) source: https://fonts.gstatic.com/s/roboto/v16/RxZJdnzeo3R5zSexge8UUVtXRa8TVwTICgirnJhmVJw.woff2  css:162:12
```

**Comment by Tigerino** [comment]
+1

**Comment by cesarbruno16** [comment]
there's soluction to this problem?

**Comment by m4rc1e** [comment]
I'm not able to replicate this with Firefox 55.0b2 (64 bit).

I'm guessing Mozilla changed the settings for OTS sanitizer in 54.0a2 and have now reverted them back.

**Comment by scheinercc** [comment]
It is fine in 55 (macOS; beta/dev) indeed, though the issue still there in current nightly (v56). Default setting for gfx.downloadable_fonts.otl_validation in v55 currently is 'false' while in v56 it is (still!?) 'true'.

**Comment by wisniewskit** [comment]
Only the nightly Firefox builds specifically should have `gfx.downloadable_fonts.otl_validation` set to true, whereas betas (including dev edition) and stable versions do not.

**Comment by scheinercc** [comment]
Maybe @sucrose can change the title to "Roboto not displaying in Firefox Nightly (gfx.downloadable_fonts.otl_validation set to true)" or similar?

**Comment by davelab6** [comment]
OpenType spec v1.8.2 released recently (http://typedrawers.com/discussion/2276/opentype-1-8-2-released#latest) which changes the spec to make this valid.

**Comment by davelab6** [comment]
The solution is going to be for OTS to be updated by @khaledhosny to reflect the latest spec, and for that to trickle down to Firefox.

**Comment by davelab6** [comment]
> The solution is going to be for OTS to be updated by @khaledhosny to reflect the latest spec, and for that to trickle down to Firefox.

Per https://github.com/khaledhosny/ots/issues/131 and https://bugzilla.mozilla.org/show_bug.cgi?id=1331797#c29 I was wrong about this; we now see Nightly has the latest OTS (https://github.com/khaledhosny/ots/) but the problem persists, and Khaled has confirmed that OTS should not be changed to allow the error. (Also, I found the overall rationale for using OTS is in https://bugzilla.mozilla.org/show_bug.cgi?id=964696#c5) 

So, since the fonts imported into the Google Fonts API are valid, and OTS is valid in rejecting the fonts exported from the API, the issue lies with the https://github.com/fonttools/fonttools subsetter which the GF API uses. I hope someone at Mozilla can provide a patch.

**Comment by davelab6** [comment]
@behdad has fixed the underlying problem in the fonttools subsetter -
 https://github.com/fonttools/fonttools/commit/6eb807b55f4fcc55a9b5fd8f3e320c89428462dd - so when the fonttools copy used by the GF API is updated, Nightly should stop barfing :)

Thank you Behdad!!!

![unnamed](https://user-images.githubusercontent.com/261579/29233834-4873da86-7ec1-11e7-94bf-9295e7060137.gif)

**Comment by jfkthame** [comment]
We're still seeing invalid Roboto resources served by Google Fonts; e.g.

> downloadable font: Layout: DFLT script doesn't satisfy the spec. DefaultLangSys is NULL (font-family: "Roboto" style:normal weight:100 stretch:normal src index:2) source: http://fonts.gstatic.com/s/roboto/v16/2tsd397wLxj96qwHyNIkxHYhjbSpvc47ee6xR_80Hnw.woff2

Any chance the fix could get deployed sometime soon?

**Comment by davelab6** [comment]
Soon! :)

**Comment by scheinercc** [comment]
FYI, Roboto is working for me in Nightly 58.0a1 (2017-09-30) 

When I load all fonts, I get the error "Native load test failed:" for these fonts:
- Pangolin
- Philosopher
- Sedgwick Ave
- Sedgwick Ave Display
- Sedgwick Ave
- Sedgwick Ave Display
- Cabin Sketch
- Kurale
- Bellefair
- Londrina Solid
- Londrina Shadow
- Londrina Sketch
- Baloo Tammudu

**Comment by jfkthame** [comment]
I didn't check all of these, but at least the first few seem to have a different problem than the missing defaultLangSys that was the problem in Roboto:

downloadable font: Layout: Lookup flags require GDEF table, but none was found: 8 (font-family: "Pangolin script=latin rev=1" style:normal weight:normal stretch:normal src index:0) source: https://fonts.gstatic.com/l/font?kit=Fs3vif300i0sWG_8cwtUgWadrG7xQ6Sn31MgoLunhwSlWBXZHJxtwUAuAQMHUQarESqeeMWmvUdEBTEQHmkQAw&skey=3db57adcfc639c2d&v=v2

downloadable font: Layout: Lookup flags require GDEF table, but none was found: 8 (font-family: "Philosopher script=latin rev=1" style:normal weight:normal stretch:normal src index:0) source: https://fonts.gstatic.com/l/font?kit=oZLTrB9jmJsyV0u_T0TKERMNIvgBSNmnIXwlL72ISo046TfR3Aq3eiTq1JszwU6rue2wV9aw1mLs183lDYuodg&skey=da0a2147adba7eff&v=v8

downloadable font: Layout: Lookup flags require GDEF table, but none was found: 8 (font-family: "Sedgwick Ave Display script=latin rev=1" style:normal weight:normal stretch:normal src index:0) source: https://fonts.gstatic.com/l/font?kit=_2bQpgd1Hl3UOD3yDrU-cM0XQamUJZ2addZRR_tQTxY1Ucq_GzRNXE4T8CP-2p4q5RA8htVOKoTC4wIMmGrJKqNRLSGfS6bMLReYoLlofcI&skey=bd380dabc39e09ab&v=v2

**Comment by behdad** [comment]
> downloadable font: Layout: Lookup flags require GDEF table, but none was found: 8

That's BS. The spec is clear that GDEF glyph classes may be automatically synthesized.

I suggest we stop wasting Google's and Khaled's time and resources on fixing this crap of a code that is GSUB/GPOS/GDEF in OTS and let Firefox do whatever they want.  They apparently have not been caring enough to fix the code themselves or just disable it as it should be.

@khaledhosny I suggest you remove that code from OTS.  Jonathan can maintain a fork if he wants.

This is my last comment on this matter.

**Comment by jfkthame** [comment]
>>  downloadable font: Layout: Lookup flags require GDEF table, but none was found: 8

> That's BS. The spec is clear that GDEF glyph classes may be automatically synthesized.

According to https://www.microsoft.com/typography/otspec/chapter2.htm, under _LookupFlag bit enumeration_: "IgnoreBaseGlyphs, IgnoreLigatures, or IgnoreMarks refer to base glyphs, ligatures and marks as defined in the Glyph Class Definition Table in the GDEF table. If any of these flags are set, a Glyph Class Definition Table must be present."

That's what OTS is implementing here, AFAICS. Is there another part of the spec that contradicts this? If so, please point it out, as we should ask for the inconsistency to be resolved in the spec.

**Comment by scheinercc** [comment]
@davelab6 @jfkthame if someone else can confirm that Robot is working in Nightly I guess we can close this bug and rather reopen new ones for the above accordingly!?

**Comment by wisniewskit** [comment]
@scheinercc, unfortunately, I just tried loading the [Google Fonts Roboto page](https://fonts.google.com/specimen/Roboto) with a completely fresh profile with today's nightly, and it's still not showing any text (I get the same "Native load test failed:" messages on that page) :(

**Comment by scheinercc** [comment]
Ah, interesting. @wisniewskit thanks for checking! 
I thought if it loads on the main page, it would generally load, but I can see the characters are missing (and the error appearing in the console), even though I can see the preview text - until I use a character like "è" or "ē", than even the preview fails with additional error messages.

<img width="829" alt="image" src="https://user-images.githubusercontent.com/817856/31058388-76b26a84-a73e-11e7-8d7e-54e6b2fdeae5.png">

**Comment by khaledhosny** [comment]
This only affects Firefox Nightly, right? Beta and Stable already disable OTS sanitizing of OTL tables.

**Comment by jfkthame** [comment]
Right.

**Comment by englishextra** [comment]
FF 54.01 64bit 

```
downloadable font: rejected by sanitizer (font-family: "Roboto" style:normal weight:normal stretch:normal src index:0) source: http://fonts.gstatic.com/stats/Roboto/normal/400
```

**Comment by fitojb** [comment]
@englishextra Firefox 54 is obsolete and was superseded by 56; please always keep it current.

**Comment by englishextra** [comment]
@fitojb 

> Firefox 54 is obsolete 

Are you serious? It's of Jun 29, 2017

> please always keep it current.

What?

**Comment by wisniewskit** [comment]
@englishextra, I certainly won't stop you from running old versions if you'd prefer, but it is generally unsafe to run browser versions older than the latest one (even ones that are only a few months old). You can see the known vulnerabilities fixed in version 55 [here](https://www.mozilla.org/en-US/security/advisories/mfsa2017-18/) and version 56 [here](https://www.mozilla.org/en-US/security/advisories/mfsa2017-21/).

**Comment by englishextra** [comment]
Hey, I'm doing webdev, and I know that regular users, that I'm writing sites for, use ancient browsers. I do have Nightly and the whole zoo of browsers. I gave an info as of FF 54 - which is in my case the benchmark version of FF. That's it and nothing alse more. 

> 55 here and version 56 here.

That's what I came here for, to make sure the sanitaze error is non on my side as a web dev.
Thanks

**Comment by davelab6** [comment]
This should now be fixed

<img width="1920" alt="screen shot 2017-10-18 at 19 31 53" src="https://user-images.githubusercontent.com/261579/31747471-0f87dd08-b43b-11e7-9635-e32d65b71582.png">

**Comment by wisniewskit** [comment]
Thanks a ton to all involved!
