### ISSUE TITLE
Modified Fonts

### ISSUE THREAD

**Issue by HelinID** [google/fonts#7383]
Hey
I am new on Github and I have a quick question.
I modified the Questrial from google fonts. Does anyone know if I have to share my modified Version? 
Thankss

**Comment by EbenSorkin** [comment]
Are you making a suggestion for improving the font? Or did you make a change to it for your own purposes? If it is a suggestion you can make a pull request. If it is a change for your own use you need to modify the family name so the two fonts are not confused.

**Comment by tiroj** [comment]
> Does anyone know if I have to share my modified Version?

You do not have to _actively_ share your modified version, i.e. there is no obligation to publish or distribute a modified OFL font, but the modified font is subject to the same license terms as the original, so if you do choose to publish or distribute the font it must be under OFL.

**Comment by HelinID** [comment]
> Are you making a suggestion for improving the font? Or did you make a change to it for your own purposes? If it is a suggestion you can make a pull request. If it is a change for your own use you need to modify the family name so the two fonts are not confused.

I made a change for my own purpose
Thank you for your help!
