### ISSUE TITLE
Failure to combine Lithuanian diacritics and accents

### ISSUE THREAD

**Issue by clockworkpc** [google/fonts#739]
Ubuntu combines Lithuanian diacritics and accents, however **Ubuntu Condensed** and **Ubuntu Mono** fail to do so.

I discovered this in Atom whilst writing a program for analysing Lithuanian verbs, which include both diacritics and accents: [Verbalyser](https://github.com/clockworkpc/verbalyser/)

An example of this is in the screenshot below:
![screenshot from 2017-04-28 17-42-16](https://cloud.githubusercontent.com/assets/9858440/25519156/0e3dc31a-2c3a-11e7-84b9-248a62d2a145.png)

A workaround is to install either Liberation Mono or Cousine Mono, both of which handle the combination thereof, for Ubuntu Mono to fall back on.

As things stand, for anyone wishing to do anything serious in a Mono font with Lithuanian, I recommend either Liberation or Cousine.

**Comment by m4rc1e** [comment]
Why use a Monospace font for this? 

[Noto](https://www.google.com/get/noto/) exists for this type of stuff. 

Sibling font families often don't support the same character sets. This is especially true when their use cases differ.

**Comment by fitojb** [comment]
For bugs in the Ubuntu font family, please go to https://launchpad.net/ubuntu-font-family/+filebug

**Comment by clockworkpc** [comment]
@m4rc1e 
`Why use a Monospace font for this?`

Why use a Monospace font at all?  As I wrote in my description, I'm writing software that deals with verbs in Lithuanian, which means I have to process strings that contain combined unicode characters.  Ask a stupid question...

`Noto exists for this type of stuff.`

I don't want to use another font: I want to use the Ubuntu Mono font and give feedback to help the project improve.  If you'd like to direct me to where I might learn the necessaries to contribute the code to improve, I'd be happy to do so myself.  I don't see the point of hopping over to another project -- font or otherwise -- whenever there is something I don't like.  If you can use Ubuntu font in Chinese, you sure as hell should be able to display the letter "e" with a dot and an accent.

`Sibling font families often don't support the same character sets. This is especially true when their use cases differ.`

Firstly, all I'm dealing with is lowercase, so that consideration is irrelevant.

Secondly, the shoddiness of other projects is no reason to hold this one to a lowlier standard.

Thirdly, I refer you to the [Ubuntu Font Family's own copy on the matter](http://font.ubuntu.com/about/):

> The scope of the Ubuntu Font Family includes **all the languages used by the various Ubuntu users around the world** in tune with Ubuntu's philosophy which states that every user should be able to use their software in the language of their choice. So the Ubuntu Font Family project will be extended to cover many more written languages.

I agree with this statement and want to help the project realize it.

**Comment by clockworkpc** [comment]
@fitojb Thank you, I will do so.

**Comment by davelab6** [comment]
@clockworkpc thanks for reporting this! However, the upstream issue tracker on launchpad is the best place to raise this topic... we can't help you :)
