### ISSUE TITLE
[Noto Sans Syriac Eastern] Include Syriac Supplement characters

### ISSUE THREAD

**Issue by ramesh-k** [google/fonts#7398]
Include [Syriac Supplement](https://unicode.org/charts/nameslist/n_0860.html) characters to the font, which are used for writing Suriyani Malayalam, also known as Garshuni (Karshoni) and Syriac Malayalam.

**Comment by simoncozens** [comment]
This is the same as https://github.com/notofonts/syriac/issues/11 - Noto issues are tracked in their individual repositories.
