### ISSUE TITLE
Philosopher font bug: dots of the letters ä, ö, ü are not centred

### ISSUE THREAD

**Issue by MonikaGrieser** [google/fonts#7466]
Font: Philosopher (Designed by Jovanny Lemonad)
The dots of the letters ä, ö, ü are not centred – especially in regular and bold. It would be great if this could be corrected. Many thanks. 

![philosopher-bold](https://github.com/google/fonts/assets/164869207/0e05288b-3d57-4def-b88d-db2762e27f15)
![philosopher-regular](https://github.com/google/fonts/assets/164869207/670759d7-a7b1-4ccf-88f2-677124ca51c3)
![philosopher-regular-02](https://github.com/google/fonts/assets/164869207/0fae29d8-b443-4612-bf43-82051aeefea8)

**Comment by emmamarichal** [comment]
Hi @MonikaGrieser! Thank you for that report. I'll add it to the queue.

**Comment by dassams** [comment]
See also https://github.com/google/fonts/issues/1225

**Comment by emmamarichal** [comment]
closed because duplicated!
