### ISSUE TITLE
Add Fustat

### ISSUE THREAD

**Issue by khaledhosny** [google/fonts#7476]
https://github.com/Kief-Type-Foundry/Fustat

Fustat is a modern typeface inspired by manuscript Kufic style of Arabic.

**Requirements:**

- [x] I read, agree, and comply with the full [contributing requirements](https://googlefonts.github.io/gf-guide/index#pre-production-getting-your-fonts-ready-for-gf)
- [x] The entire font project is licensed under the [OFL](https://scripts.sil.org/cms/scripts/page.php?site_id=nrsi&id=OFL)
- [x] There is no "Reserved Font Name" mention in the OFL license
- [x] Family name is unique according to [namecheck.fontdata.com](https://namecheck.fontdata.com/)
- [x] The font supports at least [GF Latin Core glyphset](https://github.com/googlefonts/glyphsets/tree/main/GF_glyphsets/Latin/)
- [x] The repository respect the [upstream repo structure](https://googlefonts.github.io/gf-guide/upstream.html)
- [x] The source files are available in the repository
- [x] I am the author of the font, or the author agreed to this submission
- [x] I will maintain the repository and participate in the onboarding process (addressing, solving, and responding to issues, merging pull requests, etc)

![image](https://github.com/google/fonts/assets/93914/ad92cc9d-4220-44da-9ec6-055c4ac291d9)

**Comment by chrissimpkins** [comment]
Thanks Khaled!
