### ISSUE TITLE
Can't use the /download URLs to fetch static font files

### ISSUE THREAD

**Issue by reaktor-esakoskinen** [google/fonts#7481]
**Describe the issue**

Hi! Our team is relying on accessing font files using the `https://fonts.google.com/download?family=Noto+Sans+SC` URL format. The URLs used to point directly to a ZIP file, which we download with `wget`, unzip, and load into the system as part of the CI process.

However, now that the page returns HTML that initiates the download with JavaScript, it's not clear how we should get access to the files programmatically. I scoured the documentation but couldn't find any indication of download paths for static font resources, only different options for using webfonts.

**To Reproduce**

1. `wget https://fonts.google.com/download?family=Noto+Sans+SC -O noto-sans-sc.zip`
2. `unzip noto-sans-sc.zip`
3. Unzip fails since the downloaded file is now HTML instead of a ZIP archive.

**Expected behavior**

We've relied on the (currently undocumented?) /download URLs to return single files instead of HTML pages.

**Additional context**

The base image for our container is `public.ecr.aws/lambda/nodejs:18`. Can also be reproduced on recent Linux and macOS versions (although you may need to download the `unzip` utility first, e.g. `yum install unzip`).

**Comment by rathboma** [comment]
This is also breaking my build for the Beekeeper Studio docs - https://github.com/beekeeper-studio/beekeeper-studio/actions/runs/8469768189/job/23205855650, would love for this change to be reverted!

**Comment by garretrieger** [comment]
fonts.google.com/download (and all other endpoints under fonts.google.com/*) are internal not meant for external use as they may change at any time without warning. If you need access to font metadata and the font binaries you can instead use the public developer api: https://developers.google.com/fonts/docs/developer_api

**Comment by reaktor-esakoskinen** [comment]
Thanks for the info. We decided to fix this by adding the font resources into our repo and COPYing them in the Dockerfile. Was much easier than handling a dynamic list of font families, at the cost of a slightly larger repo 😅
