### ISSUE TITLE
Cipher Symbols

### ISSUE THREAD

**Issue by LindaKAat** [google/fonts#7493]
**Font Project Git Repo URL:**

**Super short description of the Font Family:**

**Requirements:**

Google Fonts will publish only fonts that match its requirements. Please familiarize yourself with the complete documentation in the [Google Fonts Guide](https://googlefonts.github.io/gf-guide/) (GF-Guide) and ensure your font project complies with them before submitting the font family. You can also use the [Google Fonts Project Template](https://github.com/googlefonts/googlefonts-project-template), which will help you create a repository that follows the needed structure and includes build requirements.

By filling this issue, you can confirm the project meets the  requirements (by ticking the cases or putting x between the square brackets in text mode):

- [X] I read, agree, and comply with the full [contributing requirements](https://googlefonts.github.io/gf-guide/index#pre-production-getting-your-fonts-ready-for-gf)
- [X] The entire font project is licensed under the [OFL](https://scripts.sil.org/cms/scripts/page.php?site_id=nrsi&id=OFL)
- [X] Family name is unique according to [namecheck.fontdata.com](https://namecheck.fontdata.com/)
- [X] The font supports at least [GF Latin Core glyphset](https://github.com/googlefonts/glyphsets/tree/main/GF_glyphsets/Latin/)
- [ ] The repository respect the [upstream repo structure](https://googlefonts.github.io/gf-guide/upstream.html)
- [ ] The source files are available in the repository
- [X] I am the author of the font, or the author agreed to this submission
- [X] I will maintain the repository and participate in the onboarding process (addressing, solving, and responding to issues, merging pull requests, etc)

**Image:**

A<img width="325" alt="Snímek obrazovky 2024-03-28 195315" src="https://github.com/google/fonts/assets/165320405/c30aa884-f53d-40e9-843a-eb1ab11640a4">

**Comment by LindaKAat** [comment]
I have made it myself, so I guess it's an original creation.

**Comment by emmamarichal** [comment]
@LindaKAat Yes, but is there any repository where I can find the sources (.glyphs, .ufo) of the font? thank you!

**Comment by vv-monsalve** [comment]
@LindaKAat, I un-ticked the requirements that were not fulfilled. A GitHub repository with available source files is a strong requirement. Please read them carefully and feel free to re-open this issue once the project meets all of them.
