### ISSUE TITLE
why is U+E0FF a required char?

### ISSUE THREAD

**Issue by ctrlcctrlv** [google/fonts#75]
Huh?

https://github.com/google/fonts/blob/master/tools/encodings/latin_unique-glyphs.nam#L217

This is Unicode Private Use Area. I have no idea what to put there. :stuck_out_tongue: 

The only thing I can think of is this is maybe where Apple put their logo, but I can't find any source for that and I don't have an Apple computer, and also this is Google Fonts not Apple Fonts so I have no idea.

**Comment by ctrlcctrlv** [comment]
Just noticed 0xEFFD and 0xF000 are also required.

![g2](https://cloud.githubusercontent.com/assets/838783/8647333/9f023fa8-2989-11e5-8425-b161a900415d.png)

???

**Comment by ctrlcctrlv** [comment]
Hmm...

From https://github.com/google/fonts/blob/master/CONTRIBUTING.md#font-requirements : 

> All font files have at a minimum the 215 glyphs listed in our latin_unique-glyphs.nam

But latin_unique-glyphs.nam is 219 lines long.

My LCD font is almost ready but I will wait until I understand the requirements properly to release.

Paging @davelab6 :D 
![dl6](https://cloud.githubusercontent.com/assets/838783/8647470/b9c00a4a-298a-11e5-998f-624794aa7480.png)

**Comment by ultrasquid** [comment]
U+F8FF is the apple, which is in PUA. It was part of the old MacRoman
encoding and therefore might (speculatively) be required for legacy support
purposes, though you should not put an Apple, inc. logo unless the font
you're making is commissioned by Apple, inc. You could put a generic apple
picture or something else in there. I use it for my foundry logo.

I don't know what to tell you about the rest of those addresses except that
U+E0FF shows as a Ubuntu logo in whatever font I have labeling the Font
view.

On Mon, Jul 13, 2015 at 3:12 AM, Fredrick Brennan <notifications@github.com>
wrote:

> Hmm...
>
> From
> https://github.com/google/fonts/blob/master/CONTRIBUTING.md#font-requirements
> :
>
> All font files have at a minimum the 215 glyphs listed in our
> latin_unique-glyphs.nam
>
> But latin_unique-glyphs.nam is 219 lines long.
>
> My LCD font is almost ready but I will wait until I understand the
> requirements properly to release.
>
> Paging @davelab6 <https://github.com/davelab6> :D
> [image: dl6]
> <https://cloud.githubusercontent.com/assets/838783/8647470/b9c00a4a-298a-11e5-998f-624794aa7480.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/google/fonts/issues/75#issuecomment-120882995>.
>



-- 
-- 
Jason Pagura
zimbach at gmail dot com

**Comment by ctrlcctrlv** [comment]
I added Greek, Cyrillic, Hebrew, and Runic while waiting for reply :D 

![greekcyrillic](https://cloud.githubusercontent.com/assets/838783/8651241/58e5a61a-29aa-11e5-95e8-f4cd90b39ca5.png)
![runic](https://cloud.githubusercontent.com/assets/838783/8651252/5e30f3c2-29aa-11e5-9b2f-1a744df729be.png)
![hebrew](https://cloud.githubusercontent.com/assets/838783/8651255/61286664-29aa-11e5-8fa9-7e12b2dcc643.png)

**Comment by davelab6** [comment]
The 215/219 mismatch is because there are some 'blank' characters which
have no glyph data.
The PUA glyphs are included because some foundries keep their logo there
(which Jason P appears to only have the Ubuntu font installed with such a
logo) and the other has a hinting debugging character (also appearing in
the Ubuntu fonts.)

Feel free to leave those ones out :)
