### ISSUE TITLE
Add "ǝ" to Poppins character set 

### ISSUE THREAD

**Issue by rokapoz** [google/fonts#7502]
Dear Indian Type Foundry,

I am a copywriter at Happy Minds Agency, where we proudly use the Poppins font for all our corporate communications.

We have recently embraced an inclusive communication policy that reflects the evolving Italian language towards a more gender-neutral expression. Specifically, we are incorporating the use of the schwa, the letter ǝ, to replace traditional masculine and feminine endings, aligning with current trends in Italy.

However, we have noticed that the Poppins font currently does not include the symbol ǝ in its character set. This omission limits our ability to communicate fully inclusively and in alignment with our company values and visual identity.

Therefore, we are writing to formally request the addition of the symbol ǝ to the Poppins font. We believe this addition will not only enrich the font but also support organizations like ours that are committed to promoting inclusive language in Italy.

We appreciate your dedication to keeping the Poppins font up-to-date and thank you in advance for considering our request.

Warm regards,

**Comment by chrissimpkins** [comment]
This is an expansion feature request rather than a bug.  I moved this issue to the upstream development repository so that the dev team is aware.

https://github.com/itfoundry/Poppins/issues/61
