### ISSUE TITLE
Google fonts

### ISSUE THREAD

**Issue by 21jhez2003** [google/fonts#7506]
#This issue also works for requesting features. 

**Describe the issue**
The issue of Google fonts is i don't have "Select this style with + in the circle

**To Reproduce**
Steps to reproduce the behavior.

**Expected behavior**

**Additional context**
Add any other context about the problem here (OS version, browser, printer…)

**Screenshots**

**Comment by 21jhez2003** [comment]
![Screenshot (20)](https://github.com/google/fonts/assets/116240466/a2cb7cba-865e-43c9-9f04-5a14425f9c3b)

**Comment by applecuckoo** [comment]
Duplicate of issue #7166. You click the big blue 'get font' button, then the bag icon, then the 'Get embed code' button to select individual styles.

**Comment by davelab6** [comment]
Thanks @applecuckoo
