### ISSUE TITLE
Add GaMaamli

### ISSUE THREAD

**Issue by EbenSorkin** [google/fonts#7510]
**Font Project Git Repo URL: https://github.com/SorkinType/GaMaamli**

**Super short description of the Font Family:**  (placeholder only) GaMaamli is a display typeface inspired by poster lettering seen in Ghana. It has a lively feeling and sometimes surprising constructions making text set in it very distinctive. GaMaamli is an all caps design in which the lowercase uses an alternative capital construction. 

**Requirements:  ** GF Core, Kernel, Vietnamese, and AfricaPri glyph sets are complete.

Google Fonts will publish only fonts that match its requirements. Please familiarize yourself with the complete documentation in the [Google Fonts Guide](https://googlefonts.github.io/gf-guide/) (GF-Guide) and ensure your font project complies with them before submitting the font family. You can also use the [Google Fonts Project Template](https://github.com/googlefonts/googlefonts-project-template), which will help you create a repository that follows the needed structure and includes build requirements.

By filling this issue, you can confirm the project meets the  requirements (by ticking the cases or putting x between the square brackets in text mode):

- [X] I read, agree, and comply with the full [contributing requirements](https://googlefonts.github.io/gf-guide/index#pre-production-getting-your-fonts-ready-for-gf)
- [X]  The entire font project is licensed under the [OFL](https://scripts.sil.org/cms/scripts/page.php?site_id=nrsi&id=OFL)
- [X]  There is no "Reserved Font Name" mention in the OFL license
- [X] Family name is unique according to [namecheck.fontdata.com](https://namecheck.fontdata.com/)
- [X] The font supports at least [GF Latin Core glyphset](https://github.com/googlefonts/glyphsets/tree/main/GF_glyphsets/Latin/)
- [X] The repository respect the [upstream repo structure](https://googlefonts.github.io/gf-guide/upstream.html)
- [X] The source files are available in the repository
- [X] I am the author of the font, or the author agreed to this submission
- [X] I will maintain the repository and participate in the onboarding process (addressing, solving, and responding to issues, merging pull requests, etc)

**Image:**
<img width="905" alt="image" src="https://github.com/google/fonts/assets/2181213/da2b1465-6cda-44d1-af3f-ba80922a2f5e">

**Comment by emmamarichal** [comment]
@davelab6 @chrissimpkins i added "accepted" but I don't know if it's a commissioned one

**Comment by EbenSorkin** [comment]
Wheatpaste was commissioned.

It has had a last-minute name change. The new name is 'Ga Maamli'.

-e.

**Comment by EbenSorkin** [comment]
Apparently, a push was just made and I will review it today and let you
know on Monday if it will need another round or it is ready.

-e.

**Comment by emmamarichal** [comment]
Excellent! thanks!

**Comment by emmamarichal** [comment]
Hi @EbenSorkin, any update? :)

**Comment by EbenSorkin** [comment]
I added some kerning today to account for the additional glyphs that are
present and any changes to shapes & side bearings that may have been made.
So this should be ready to onboard now.

Please let me know if you have any questions. I did note that there are 3
fails but they all seem to be ignorable in the context of this design. e.g.
loc caron shapes not used: this is an all caps design that imposes caps on
lc unicodes. Stuff like this.

But you may see some of it differently.

Cheers!

-e.
