### ISSUE TITLE
Add Cs-f

### ISSUE THREAD

**Issue by Cjs21** [google/fonts#7512]
**Font Project Git Repo URL:**
https://github.com/Cjs21/Handwritten-fonts

**Super short description of the Font Family:**

Handwriten Font by me and my friends.

ALL FONTS ARE FREE OF ANY LICENSING OR BONDING

Fonts created using calligraphr.
Cs_f1-Regular.ttf is by Cjs21. My hand wrighting. Not all characters work. sorry

**Requirements:**

Google Fonts will publish only fonts that match its requirements. Please familiarize yourself with the complete documentation in the [Google Fonts Guide](https://googlefonts.github.io/gf-guide/) (GF-Guide) and ensure your font project complies with them before submitting the font family. You can also use the [Google Fonts Project Template](https://github.com/googlefonts/googlefonts-project-template), which will help you create a repository that follows the needed structure and includes build requirements.

By filling this issue, you can confirm the project meets the  requirements (by ticking the cases or putting x between the square brackets in text mode):

- [x] I read, agree, and comply with the full [contributing requirements](https://googlefonts.github.io/gf-guide/index#pre-production-getting-your-fonts-ready-for-gf)
- [x] The entire font project is licensed under the [OFL](https://scripts.sil.org/cms/scripts/page.php?site_id=nrsi&id=OFL)
- [x] There is no "Reserved Font Name" mention in the OFL license
- [x] Family name is unique according to [namecheck.fontdata.com](https://namecheck.fontdata.com/)
- [x] The font supports at least [GF Latin Core glyphset](https://github.com/googlefonts/glyphsets/tree/main/GF_glyphsets/Latin/)
- [x] The repository respect the [upstream repo structure](https://googlefonts.github.io/gf-guide/upstream.html)
- [x] The source files are available in the repository
- [x] I am the author of the font, or the author agreed to this submission
- [x] I will maintain the repository and participate in the onboarding process (addressing, solving, and responding to issues, merging pull requests, etc)

**Image:**

Attach here a pic or a screenshot of the font. One image is enough, it can be a few letters, to give a quick overview.

**Comment by Cjs21** [comment]
I have not received any updates so I will be removing this font request shortly.

Sorry 

Cjs-24

**Comment by applecuckoo** [comment]
Hi! I'm just a volunteer, but there were a couple things that stood out to me about your font.

The first thing is that you've used Calligraphr.com to create your font. That wouldn't work out for the reasons described in https://github.com/google/fonts/issues/5699#issuecomment-1350787186. Basically, it's not very flexible if any changes need to be made.

The other thing is that the font isn't licensed under OFL. As shown in the checklist above, Google Fonts needs you to submit your font under an OFL license.

That's all from me, but I'll ping @davelab6 in case he has anything to say.

**Comment by Cjs21** [comment]
Hi @applecuckoo thanks for the info. Is there a way I can use my font in google docs. That is the main reason I uploaded it. Thanks

CS
