### ISSUE TITLE
Update Noto Sans Math

### ISSUE THREAD

**Issue by simoncozens** [google/fonts#7528]
**Font Project Git Repo URL:** notofonts/math

**Current version:** 2.001

**New available version:** 2.003 (not available yet, but coming soon)

**Super short description of the upgrade:**

Rationalisation of sans serif fonts to create a true sans math font.

**Comment by chrissimpkins** [comment]
Reopening to address the fixes required in this family before we can move it into production.

**Comment by chrissimpkins** [comment]
The current plan as of our latest discussion yesterday is that we will expand the internal pipeline `math` subset definition to include the required encodings as recommended by Khaled.  Let's transition to use this issue as the tracker for landing this project in production and close it when we have the subsetting issue fixed and the family update launches.

**Comment by chrissimpkins** [comment]
D/W Rod today. Fonts eng is still working on the math subset update

**Comment by emmamarichal** [comment]
seems to be live, I close the issue!
