### ISSUE TITLE
Request for Anton font to support cyrillic 

### ISSUE THREAD

**Issue by rokapoz** [google/fonts#7529]
![ButpLc7JQpVAYiW](https://github.com/google/fonts/assets/46518820/c098450a-9329-475f-bd76-ccb12fc8bdda)

**Comment by Tural** [comment]
Hi. I take it upon myself. I will add the Cyrillic alphabet.

**Comment by Tural** [comment]
Hi. As promised, I added the Cyrillic alphabet to the Anton font. Additionally, I made necessary adjustments to support Polish, Serbian, Bulgarian, Macedonian, and Khinalig alphabets. I made minor corrections to the eth and Schwa letters.

[Anton.zip](https://github.com/google/fonts/files/14968499/Anton.zip)

**Comment by Tural** [comment]
[Update Anton font #7552](https://github.com/google/fonts/issues/7552)

**Comment by Tural** [comment]
Could you please let me know if this contribution will be considered or if I have not done it correctly?

**Comment by chrissimpkins** [comment]
Thank you very much for the contribution!  I've asked @emmamarichal to try to find time in Q2 to review this.  Let's close this issue and transition the discussion to the https://github.com/google/fonts/issues/7552 tracker that you opened.
