### ISSUE TITLE
Noto Sans SC Macron Misalignment

### ISSUE THREAD

**Issue by jrmanrique** [google/fonts#7541]
**Description**
The macron is misaligned if one were to use Noto Sans SC to display Pinyin.

**Current and Expected Behavior**
The current behavior is shown below, together with the expected behavior as seen in other typefaces.
![image](https://github.com/google/fonts/assets/23200011/89108aac-27c2-4c01-bd54-d5b2be759b1b)

**Comment by vv-monsalve** [comment]
HI @jrmanrique, please report any issue related to Noto fonts [here](https://notofonts.github.io/reporter.html).
