### ISSUE TITLE
KG Ten Thousand Reasons Add [Font Name]

### ISSUE THREAD

**Issue by guardgirlgab** [google/fonts#7560]
**Font Project Git Repo URL:**

**Super short description of the Font Family:**

**Requirements:**

Google Fonts will publish only fonts that match its requirements. Please familiarize yourself with the complete documentation in the [Google Fonts Guide](https://googlefonts.github.io/gf-guide/) (GF-Guide) and ensure your font project complies with them before submitting the font family. You can also use the [Google Fonts Project Template](https://github.com/googlefonts/googlefonts-project-template), which will help you create a repository that follows the needed structure and includes build requirements.

By filling this issue, you can confirm the project meets the  requirements (by ticking the cases or putting x between the square brackets in text mode):

- [x] I read, agree, and comply with the full [contributing requirements](https://googlefonts.github.io/gf-guide/index#pre-production-getting-your-fonts-ready-for-gf)
- [ ] The entire font project is licensed under the [OFL](https://scripts.sil.org/cms/scripts/page.php?site_id=nrsi&id=OFL)
- [x] There is no "Reserved Font Name" mention in the OFL license
- [x] Family name is unique according to [namecheck.fontdata.com](https://namecheck.fontdata.com/)
- [ ] The font supports at least [GF Latin Core glyphset](https://github.com/googlefonts/glyphsets/tree/main/GF_glyphsets/Latin/)
- [ ] The repository respect the [upstream repo structure](https://googlefonts.github.io/gf-guide/upstream.html)
- [ ] The source files are available in the repository
- [ ] I am the author of the font, or the author agreed to this submission
- [ x
<img width="778" alt="Screenshot 2024-04-16 at 10 35 25 AM" src="https://github.com/google/fonts/assets/167226148/b46e6078-1473-495b-86be-30248ce17741">
] I will maintain the repository and participate in the onboarding process (addressing, solving, and responding to issues, merging pull requests, etc)

**Image:**

Attach here a pic or a screenshot of the font. One image is enough, it can be a few letters, to give a quick overview.

**Comment by vv-monsalve** [comment]
Hi, thanks for your submission. I un-ticked the requirements that still needed to be fulfilled. A GitHub repository with available source files is a strong requirement, please add a repository that includes them.

**Comment by applecuckoo** [comment]
@vv-monsalve Just so you know, this font is not OFL-licensed as per [DaFont](https://www.dafont.com/kg-ten-thousand-reasons.font). It's free for personal use, but needs to be licensed for any commercial use.

**Comment by vv-monsalve** [comment]
Thanks, @applecuckoo.

@guardgirlgab, as previously stated, a GitHub repository containing source files and the font is a crucial requirement. Without it, we cannot verify the others' compliance. Please read them carefully and feel free to re-open this issue once the project matches them all.
