### ISSUE TITLE
Saira font is always Thin when exported to PDF

### ISSUE THREAD

**Issue by alXDraghiciu** [google/fonts#7564]
**Describe the bug**
When exporting a Word document into PDF, all the variable font weights get disregarded in the final PDF file, and all Saira fonts are at Thin (100) Weight.

**To Reproduce**
1. Install Saira font locally
2. Open a new Word document
3. Enter some texts using different weight variants
4. Export to PDF
5. All the Saira text will be in the same weight

**Expected behavior**
The specified to be exported in the PDF successfully

**Screenshots**
![saira weight bug ss1](https://github.com/google/fonts/assets/88316605/53cbf1dd-4018-45e3-9159-23ca101550fd)
![saira weight bug ss2](https://github.com/google/fonts/assets/88316605/c1b9a2a4-6503-4502-9e5b-8f238dc20e98)

**Additional context**
OS: Windows 11 Business
Word: v2403 Build 17425.20176
Adobe Acrobat Reader: v2024.002.20687

**Comment by kenmcd** [comment]
Note: You can also use the static fonts instead of the variable fonts.
The static fonts export to PDF fine in Word.
