### ISSUE TITLE
Iranairx

### ISSUE THREAD

**Issue by AriafarKhosravi** [google/fonts#7565]
**Font Project Git Repo URL:**
https://github.com/AriafarKhosravi/Iranairx.git

**Super short description of the Font Family:**
Iranairx typeface consists of two styles: regular and slanted. It has a weight of 400 and includes Latin glyphs. The typeface is designed with both full-width and half-width sharp/soft-curved lines.

1.I am the author of the Iranairx font.
2.I will maintain the repository after acception and participate in the onboarding process (addressing, solving, and responding to issues, merging pull requests, etc)
3.OFL 1.1 license file is available.

Ariafar Khosravi / Designer-Author

**Comment by vv-monsalve** [comment]
Hi @AriafarKhosravi, the submission must include and check the full list in the issue template. The available sources in the repo are a strong requirement.

Also, specific and explanatory details are needed as part of the family description. "A new typeface" is not informative enough to review it.

**Requirements:**


Google Fonts will publish only fonts that match its requirements. Please familiarize yourself with the complete documentation in the [Google Fonts Guide](https://googlefonts.github.io/gf-guide/) (GF-Guide) and ensure your font project complies with them before submitting the font family. You can also use the [Google Fonts Project Template](https://github.com/googlefonts/googlefonts-project-template), which will help you create a repository that follows the needed structure and includes build requirements.

By filling this issue, you can confirm the project meets the  requirements (by ticking the cases or putting x between the square brackets in text mode):

- [ ] I read, agree, and comply with the full [contributing requirements](https://googlefonts.github.io/gf-guide/index#pre-production-getting-your-fonts-ready-for-gf)
- [ ] The entire font project is licensed under the [OFL](https://scripts.sil.org/cms/scripts/page.php?site_id=nrsi&id=OFL)
- [ ] There is no "Reserved Font Name" mention in the OFL license
- [ ] Family name is unique according to [namecheck.fontdata.com](https://namecheck.fontdata.com/)
- [ ] The font supports at least [GF Latin Core glyphset](https://github.com/googlefonts/glyphsets/tree/main/GF_glyphsets/Latin/)
- [ ] The repository respect the [upstream repo structure](https://googlefonts.github.io/gf-guide/upstream.html)
- [ ] The source files are available in the repository
- [ ] I am the author of the font, or the author agreed to this submission
- [ ] I will maintain the repository and participate in the onboarding process (addressing, solving, and responding to issues, merging pull requests, etc)

**Comment by AriafarKhosravi** [comment]
@vv-monsalve Thank you for your help. I will try again.
