### ISSUE TITLE
font-feature-settings is not working for imported google fonts

### ISSUE THREAD

**Issue by nkkibelen** [google/fonts#7587]
Hi, Can I please have some help with adding font-feature-settings? I imported the Hanken Grotesk from google fonts using this code @import "https://fonts.googleapis.com/css2?family=Hanken+Grotesk:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap";

The font works, but I'm trying to changed the letter "g" format. I added the setting "font-feature-settings:"ss01" 1;" to the body tag but it seems it did not changed anything. Is there someone have the same issue with this? Thanks

**Comment by kenmcd** [comment]
Google online web fonts only support a subset of OpenType features.
And Stylistic Sets (`ssNN`) are not supported.
So your only option is to host the fonts yourself.

**Comment by vv-monsalve** [comment]
Hi @nkkibelen, indeed, GF doesn't support extended OT features yet, and it won't happen soon. As @kenmcd says, you could host the full font yourself.
