### ISSUE TITLE
Add designer profile for StefanSchmidt

### ISSUE THREAD

**Issue by m4rc1e** [google/fonts#7596]
He's the designer of Tiny5, #7583

**Comment by Gissio** [comment]
Done.

**Comment by vv-monsalve** [comment]
@Gissio, the information provided doesn't include an image. Would you like to provide one? It doesn't have to be a portrait. It could be an abstract image like a logo or a symbol.

**Comment by Gissio** [comment]
Ok, here is an image to use:

![icon-about](https://github.com/google/fonts/assets/119644301/2db628d1-dea7-4fec-ad69-9e48695b315e)
