### ISSUE TITLE
jura font - lowercase f and i intersect

### ISSUE THREAD

**Issue by relax81** [google/fonts#7612]
**Describe the bug**
The lowercase "f" followed by an "i" results in a strange intersection of the two letters which makes it hard to read. 

**To Reproduce**
lowercase "fi" like in Grid**fi**nity

**Expected behavior**
Adjustment in the gap or other solution to avoid that intersection which makes two letters look like one. 

**Screenshots**
![2024-04-28_23h49_23](https://github.com/google/fonts/assets/34972983/d6d472be-c053-4ce5-8c59-0fa543223336)

**Comment by kenmcd** [comment]
Just turn-Off Standard Ligatures (`liga`)

![2024-04-29_10-24-50](https://github.com/google/fonts/assets/844920/8a02d8e8-ed89-454d-a543-a2c6dcd34065)
