### ISSUE TITLE
Request for additional currency symbols in Roboto Flex

### ISSUE THREAD

**Issue by rokapoz** [google/fonts#7617]
Listnr feedback on Roboto Flex: Some currency symbols, namely ₪ (new sheqel) for Israel and ₮ (tugrik) for Mongolia, as well as
₨ (Rupee) are missing from this font.

![image](https://github.com/google/fonts/assets/46518820/2cc0b03e-cadb-4e2f-8620-d1259d52e32c)

**Comment by emmamarichal** [comment]
Hello @rokapoz :) Thanks for reporting this!
You can open a new issue on the Roboto Flex repo, or complete this one: https://github.com/googlefonts/roboto-flex/issues/12
