### ISSUE TITLE
How to check the font version

### ISSUE THREAD

**Issue by Suuzuuki** [google/fonts#7621]
Is it possible to check the update history and update contents of the version of the font that can be used in GoogleFont?

**Comment by emmamarichal** [comment]
Hello @Suuzuuki! For now it's not possible, you have to check the font github repo, where you can find more infos in the readme. If it follow well our template, you should find a ChangeLog part, with all the updates.

**Comment by Suuzuuki** [comment]
@emmamarichal 
Thank you for your answer.
I understand that it's impossible.
Let me ask you an additional question. Is it possible to fix the version of the font obtained from GoogleFonts?
