### ISSUE TITLE
Add Zain

### ISSUE THREAD

**Issue by davelab6** [google/fonts#7626]
**Font Project Git Repo URL:**

https://github.com/JuergenWillrodt/Zain (now); will be https://github.com/googlefonts/zain shortly

**Super short description of the Font Family:**

Related to https://github.com/google/fonts/issues/7625 this is a new arabic-latin family from Boutros.

**Requirements:**

Maintaining this is being delegated to Google Fonts by Boutros.

**Comment by chrissimpkins** [comment]
This project is currently blocked and should not move into production until we have a plan for the landing of the necessary outstanding changes and sign off from the upstream development team.

**Comment by chrissimpkins** [comment]
Moving to Q3 at upstream team's request.
