### ISSUE TITLE
Add: Funnel Sans and Funnel Display

### ISSUE THREAD

**Issue by ktkm** [google/fonts#7648]
**Font Project Git Repo URL:**
(https://github.com/Dicotype/Funnel)

**Super short description of the Font Family:**
Funnel Sans and Funnel Display is a contemporary neo-grotesque typeface family in 15 weights and styles—the sturdy Sans pairs well with the more eccentric Display version.

**Requirements:**
- [x] I read, agree, and comply with the full [contributing requirements](https://googlefonts.github.io/gf-guide/index#pre-production-getting-your-fonts-ready-for-gf)
- [x] The entire font project is licensed under the [OFL](https://openfontlicense.org/open-font-license-official-text/)
- [x] There is no "Reserved Font Name" mention in the OFL license
- [x] Family name is unique according to [namecheck.fontdata.com](https://namecheck.fontdata.com/)
- [x] The font supports at least [GF Latin Core glyphset](https://github.com/googlefonts/glyphsets/blob/main/data/results/txt/nice-names/GF_Latin_Core.txt)
- [x] The repository respect the [upstream repo structure](https://googlefonts.github.io/gf-guide/upstream.html)
- [x] The source files are available in the repository
- [x] I am the author of the font, or the author agreed to this submission
- [x] I will maintain the repository and participate in the onboarding process (addressing, solving, and responding to issues, merging pull requests, etc)

**Images:**

![funnel_aw](https://github.com/google/fonts/assets/19203711/697f0aab-5e01-41ad-8cea-6ee84d04abe7)

![funnel_aw_pangram](https://github.com/google/fonts/assets/19203711/a3efa11f-bcb6-4c9d-b425-f500ceb487ad)

**Comment by kenmcd** [comment]
> **Font Project Git Repo URL (currently private):**
> (https://github.com/Dicotype/Funnel)

Please make the repository public.

**Comment by ktkm** [comment]
@kenmcd I’ll do that right away.

**Comment by ktkm** [comment]
Hello, @emmamarichal. Please let me know if you need anything from me and when you have more information regarding the onboarding.

**Comment by emmamarichal** [comment]
Hi @ktkm, this project is planned for the Q3, I'll let you know if I have any questions, thanks a lot! :)

**Comment by ktkm** [comment]
Hello @emmamarichal and @chrissimpkins, is there any news regarding the Funnel project? P4, is that some priority order?

**Comment by emmamarichal** [comment]
Hi @ktkm, I take a look asap :)

**Comment by ktkm** [comment]
Hello Emma, what is the status as of now?

**Comment by emmamarichal** [comment]
I'll try to start this week!
