### ISSUE TITLE
Add Syncopate font package

### ISSUE THREAD

**Issue by LGRFDanielle** [google/fonts#7656]
**Font Project Git Repo URL:** https://fonts.google.com/specimen/Syncopate

**Super short description of the Font Family:**
Installing Syncopate package with Regular and Bold version on Windows OS.  In Word and Adobe it only shows Syncopate regular. Is the intention for a user to utilize the bold feature in both applications for this OS system or should there be a bold option present ?

**Requirements:**

Google Fonts will publish only fonts that match its requirements. Please familiarize yourself with the complete documentation in the [Google Fonts Guide](https://googlefonts.github.io/gf-guide/) (GF-Guide) and ensure your font project complies with them before submitting the font family. You can also use the [Google Fonts Project Template](https://github.com/googlefonts/googlefonts-project-template), which will help you create a repository that follows the needed structure and includes build requirements.

By filling this issue, you can confirm the project meets the  requirements (by ticking the cases or putting x between the square brackets in text mode):

- [x] I read, agree, and comply with the full [contributing requirements](https://googlefonts.github.io/gf-guide/index#pre-production-getting-your-fonts-ready-for-gf)
- [ ] The entire font project is licensed under the [OFL](https://openfontlicense.org/open-font-license-official-text/)
- [ ] There is no "Reserved Font Name" mention in the OFL license
- [ ] Family name is unique according to [namecheck.fontdata.com](https://namecheck.fontdata.com/)
- [ ] The font supports at least [GF Latin Core glyphset](https://github.com/googlefonts/glyphsets/blob/main/data/results/txt/nice-names/GF_Latin_Core.txt)
- [ ] The repository respect the [upstream repo structure](https://googlefonts.github.io/gf-guide/upstream.html)
- [ ] The source files are available in the repository
- [ ] I am the author of the font, or the author agreed to this submission
- [ ] I will maintain the repository and participate in the onboarding process (addressing, solving, and responding to issues, merging pull requests, etc)

**Image:**

Attach here a pic or a screenshot of the font. One image is enough, it can be a few letters, to give a quick overview.
![syncopate font in word](https://github.com/google/fonts/assets/169686834/474893f5-cdbb-4d66-b0bd-5a04b047a54b)

**Comment by kenmcd** [comment]
Word displays the family name and uses style-linking to access the italic and bold styles.
Syncopate only has Regular and Bold available.
So you just select the font family name in the list above and then press the Bold button to get the bold style.

In Adobe you should be able to select the family name in the font list and then select Regular or Bold from the Font Style drop-down.

Hmmm... Adobe may be having a problem because the Regular width is configured as Expanded, and the Bold width is configured as Normal.
This may be confusing the Adobe application.

**Comment by emmamarichal** [comment]
I don't have any issue in adobe. in indd, the font show up well in the drop down menu, and the style linking works well too (shift+cmd+B).
As @kenmcd said, it's normal to only have regular in Windows, you can access to the bold only thanks to the style linking.
