### ISSUE TITLE
Add Iansui

### ISSUE THREAD

**Issue by ButTaiwan** [google/fonts#7742]
**Font Project Git Repo URL:**
https://github.com/ButTaiwan/iansui

**Super short description of the Font Family:**

- Iansui is a Traditional Chinese font, which is divided from Klee One Project.
- Iansui complies with the font specifications of Taiwan's Ministry of Education and is suitable for education and school-age reading.
- Iansui supports Taiwanese, Hakka Chinese characters, and phonetic symbols of Taiwanese, Hakka, and aboriginal languages.

**Requirements:**

Google Fonts will publish only fonts that match its requirements. Please familiarize yourself with the complete documentation in the [Google Fonts Guide](https://googlefonts.github.io/gf-guide/) (GF-Guide) and ensure your font project complies with them before submitting the font family. You can also use the [Google Fonts Project Template](https://github.com/googlefonts/googlefonts-project-template), which will help you create a repository that follows the needed structure and includes build requirements.

By filling this issue, you can confirm the project meets the  requirements (by ticking the cases or putting x between the square brackets in text mode):

- [x] I read, agree, and comply with the full [contributing requirements](https://googlefonts.github.io/gf-guide/index#pre-production-getting-your-fonts-ready-for-gf)
- [x] The entire font project is licensed under the [OFL](https://openfontlicense.org/open-font-license-official-text/)
- [x] There is no "Reserved Font Name" mention in the OFL license
- [x] Family name is unique according to [namecheck.fontdata.com](https://namecheck.fontdata.com/)
- [x] The font supports at least [GF Latin Core glyphset](https://github.com/googlefonts/glyphsets/blob/main/data/results/txt/nice-names/GF_Latin_Core.txt)
- [x] The repository respect the [upstream repo structure](https://googlefonts.github.io/gf-guide/upstream.html)
- [x] The source files are available in the repository
- [x] I am the author of the font, or the author agreed to this submission
- [x] I will maintain the repository and participate in the onboarding process (addressing, solving, and responding to issues, merging pull requests, etc)

**Image:**

![image](https://github.com/google/fonts/assets/5418570/1854434e-422a-4abe-932d-9e0439fd615d)

Attach here a pic or a screenshot of the font. One image is enough, it can be a few letters, to give a quick overview.

**Comment by aaronbell** [comment]
Hi there. The OFL license file in the repository states `with Reserved Font Name "芫荽".` Our preference is no RFN, per the submission guidelines. @ButTaiwan Please advise.

**Comment by vv-monsalve** [comment]
@ButTaiwan could you please confirm about the RFN?

**Comment by ButTaiwan** [comment]
> [@ButTaiwan](https://github.com/ButTaiwan) could you please confirm about the RFN?

I thought that Chinese font names are not included in Google Fonts subsets, so I just removed the English name Iansui from RFN.
I can change it in the next version if it is necessary.

**Comment by aaronbell** [comment]
IMO, it is a little odd to have an RFN for the name in Chinese characters but not for the name in Latin. Feels like the same name either way. I’d say either remove it, or get a license agreement in place with GF.

Also? GF will require name table ID 1 to be in Latin characters, so the Chinese name needs to be moved to a localized string anyway. If you’re OK with the overall removal of the RFN, then I’ll remove it across the board so we can move forward without it.

**Comment by ButTaiwan** [comment]
> If you’re OK with the overall removal of the RFN, then I’ll remove it across the board so we can move forward without it.

It's OK.
