### ISSUE TITLE
ufo file of CJK font is too large

### ISSUE THREAD

**Issue by ButTaiwan** [google/fonts#7745]
I want to submit some of my font families, which divided from Noto CJK: 
https://github.com/ButTaiwan/genseki-font
https://github.com/ButTaiwan/gensen-font
https://github.com/ButTaiwan/genryu-font
https://github.com/ButTaiwan/genwan-font

These font families are built with open-source tools, e.g. fonttools, AFDKO and otfcc, but I don't have any UFO, glyphs or Fontforge files in source code. (The original source codes are ttx, svg files and AFDKO cid files.)

I tried to generate ufo files, but they're too large.
A .ttf file with 36,000 glyphs cost 230MB, so a font family with 5 weights and 2 language (TW&JP) will cost 2.3GB.
That's too large to push to github repository.

In ShipporiMincho project (https://github.com/fontdasu/ShipporiMincho/tree/master), source files are be zipped.
I tried to zip the .ufo file, 230MB will down to 47MB. It's smaller, but still large.
(One font family still cost 470MB. The total size of all familes also more than github transfer limit.)

Just like there are no .ufo, .glyphs source files in https://github.com/notofonts/noto-cjk
Can I submit these font families without sources folder?

**Screenshots**
![image](https://github.com/google/fonts/assets/5418570/c7594d52-8bb8-499e-afe3-558354db859c)

**Comment by vv-monsalve** [comment]
Hi @ButTaiwan, thank you for your submission. However, source files are a strong requirement, especially for submitted fonts. Noto is a separate project that can't work as a reference.

On the other hand, file size is also a crucial factor; the fonts can't be shipped at the massive size they are right now.

If you are adding some features you would like to suggest in the Noto fonts, please [consider filing an issue here](https://notofonts.github.io/reporter.html).
