### ISSUE TITLE
Lato font - Missing Czech characters and additional weights

### ISSUE THREAD

**Issue by Vendy2024** [google/fonts#7775]
The [Lato font ](https://fonts.google.com/specimen/Lato?preview.text=%C5%BDlu%C5%A5ou%C4%8Dk%C3%BD%20k%C5%AF%C5%88%20p%C4%9Bl%20%C3%BAd%C4%9Bsn%C4%9B%20%C4%8Dard%C3%A1%C5%A1,%20zat%C3%ADmco%20%C5%A1ediv%C3%BD%20vlk%20%C4%8F%C3%A1belsky%20%C5%99val%20pod%20obrovsk%C3%BDm%20%C5%99e%C5%99ichem,%20v%C4%9B%C5%99%C3%ADc%20v%20l%C3%A9%C4%8Divou%20s%C3%ADlu%20v%C5%99esu.&query=lato)
available on Google Fonts does not include all the weights and special Czech characters that are available on the [official Lato website](https://www.latofonts.com/lato-free-fonts/). This discrepancy limits the font's usability for Czech language content.

The Lato font on Google Fonts should include all the weights and full support for Czech characters, as available on the official Lato website?

Best regards,
Vendula

Here is example from Adobe Fonts
![image](https://github.com/google/fonts/assets/170965896/72a37ca0-6b1b-4f62-ac21-60654a5110a2)

**Comment by vv-monsalve** [comment]
Hi @Vendy2024, thank you for pointing out the new version.

The current distributed font in GF API is `v1.104`, and the new version on the Lato website is `v2.015`. We'll review the possibility of updating in our next meeting.

**Comment by applecuckoo** [comment]
@vv-monsalve Lato progress is being tracked in #3978, in fact there's a v3 currently available as source.

**Comment by vv-monsalve** [comment]
@Vendy2024 I'm sorry, but this update has been attempted in the past and has been moved to backlog due to its complexity. Please follow this addition int #3978.
