### ISSUE TITLE
Impossible to use "Noto [Sans/Serif] [SC/TC/JP/KR]" fonts in Google Chrome/MSEdge

### ISSUE THREAD

**Issue by verdy-p** [google/fonts#7805]
**All** "Noto [Sans/Serif] [SC/TC/HK/JP/KR]" fonts, in **all** 7 weights.

**Describe the bug**
It's still impossible to use "Noto [Sans/Serif] [SC/TC/JP/HK/KR]" fonts in Google Chrome/MSEdge, even if they are fully installed (all 7 weights from "UltraLight" to "Black", including "Regular" and "Medium") on the system (Windows), shown in Windows>Settings>Fonts.

Instead other fallback fonts from Windows (e.g. "SimSun", "SimSun-ExtA", "SimSun-ExtB") are used instead. This affects CJK characters in ALL planes (including in the BMP).

Apparently, the "Noto [Sans/Serif] [SC/TC/HK/JP/KR]" fonts have forgotten to include **"[dlng]/[slng]" metadata, visibly required now by text rendering engines for Chromium-based web browsers**:

This "[dlng][slng]" metadata is present in default Japanese/Chinese/Korean Windows OpenType fonts, like "SimSun*", and may explain why these system fonts are the only one selected and used as fallbacks. This "[dlng][slng]" metadata is preferred now to the older mechanism (broken and very slow) based on looking at character-to-glyph mappings, it is part of modern standards.

**All Noto fonts should include the [dlng][slng] OpenType metadata.** This is not the case for now. Any fonts without this (now required) metadata will never be used by modern web browsers, even if they are installed on the system; fallback fonts (listed in CSS, or implied by generic font names like "serif" or "sans-serif", or added in the default builtin list of browsers) will be used instead (if there are existing candidate fallbacks), or the web browser will just display "tofu" (not what the "Noto" fonts were designed for!).

**To Reproduce**
Look at these example web pages with Google Chrome or MS Edge:
* https://commons.wikimedia.org/wiki/Category:Unicode_4E00-9FFF_CJK_Unified_Ideographs
* https://commons.wikimedia.org/wiki/Category:Unicode_3400-4DBF_CJK_Unified_Ideographs_Extension_A
* https://commons.wikimedia.org/wiki/Category:Unicode_20000-2A6DF_CJK_Unified_Ideographs_Extension_B
* https://commons.wikimedia.org/wiki/Category:Unicode_2A700-2B73F_CJK_Unified_Ideographs_Extension_C

Open the list of characters with the "[hide/display]" button, select a single character in the list, inspect details in Google Chrome's developer console, then go to the "style" panel, and look at the bottom of the "Computed" tab, that shows which fonts are used to display characters (see the example screenshot below).

**Expected behavior**
"Noto Serif TC" should be used, but system fallback fonts (e.g. "SimSun", "SimSun-ExtA", "SimSun-ExtB") are used instead.

**Screenshots**
![image](https://github.com/google/fonts/assets/1387035/ef67efee-45e5-4a7f-895a-e6221666167e)

**Additional context**
Google Chrome (current release) on Windows 11

**Comment by verdy-p** [comment]
Hmmm.. In fact the problem here is that there's no support in Noto fonts, for any CJK characters in Planes 2 (SIP) or 3 (TIP)... and not even for **many** characters in Plane 0 (BMP). So we always get fallback fonts (like SimSun or SimSun-ExtB on Windows) for them, or just tofus if they are not in system-provided fonts (notably for now, all CJK characters in Plane 3).

So Noto CJK fonts are still too much incomplete (why are they not complete at least in Plane 0, just like Microsoft's "SimSun"?).
And we'll still need additional Noto CJK fonts for planes 2 (like Microsoft's "SimSun-ExtB") and 3.

**Comment by applecuckoo** [comment]
I'm going to ping in @simoncozens here, since if I remember correctly he's in charge of the Noto fonts. This might actually be a problem for the Adobe folks since it's their font though.

**Comment by verdy-p** [comment]
Note that I could finlly use Noto fonts, but only when asking for specific font-weight (in the example page shown above, listing characters, I forced using "font-weight:200" instead of the default weight; may be something is wrong with the "regular" weight; anyway the font-weigth:200 is also the most readable, to show distinctions notably for CJK ideographs with many strokes, including "kStrange" variants with more than 40 total strokes, and with a reasonable minimum font-size: that page is tuned to increase a bit the font-size, and reducing the default line-height, so that the list of characters is usable; this works with all CJK characters in planes 0 and 2, even if for now there's no font for plane 3, and plane 2 is only displayed by Microsoft CJK fonts; I'm still looking for more free CJK fonts available for planes 2 and 3, and with a reasonable quality).

**Comment by simoncozens** [comment]
We already have some ideas for how to do the expansions: (a) obtain/derive sources, (b) convert to variable components, (c) fill in the glyphs from radical recipes.

**Comment by verdy-p** [comment]
Thanks, but how will we resolve the problem of overlapping glyphs (or glyph components)? Something is missing in OpenType specifications for that (and it is needed not just for CJK ideographs, but also all scripts and symbols that need to render ligatures and overlaps, including notably Arabic, Devagari, handwritten Latin/Greek/Cyrillic...). SVG has a limited support for them implemented in their renderers (see "fill-mode: non-zero", unfortunately limtied in use jsut for filling and not for deriving geometries).

In my idea, if OpenType had "full support" of overlaps, and the capability of computing derived geometries, if would be possible to generate very small CJK fonts and improve the rendering of all scripts, with much less work needed for font designers (most of the work would be done by the renderer, using technics already implemented for SVG filling, but as well for other graphical projects like cartography: computing geometries is also implemented in many SVG drawing tools). And it would greatly increase the support for variable fonts for other axis (e.g. shape variants for stroke ends: cap/rounded, serif vs. sans-serif). However all this will depend on technical evolutions of OpenType renderers (and its specs).

**Comment by simoncozens** [comment]
> Something is missing in OpenType specifications for that

I'm not sure what you're implying, because there is an overflap flag on the glyph table.

At any rate, changing the opentype spec and all existing renderers is somewhat out of scope for a Noto CJK bug.

**Comment by verdy-p** [comment]
This "overlap" flag is apparently not implemented (we know the bug, you've even documented it in the Google Fonts site, notably for pages explaining if all sttyles can be used, this does not work for now for generating "outline" style (only borders with transparent filling, or semi-transparent filling where overlaps are also visible, even with the "filling-rule: nonzero" rather than "evenodd" where overlaps cause problems even for opaque filling, as they can create "holes").

I did not find anything in OpenType that discusses overlaps, and if it exists, it has been forgotten in many OpenType renderers or it was misunderstood due to possibly ambiguous specification (so then it creates unsolved compatibility problems).

Supporting overlaps is critical for using fonts with variable weight (this is already a problem for all existing Noto CJK fonts, and for Arabic, Devanagari, and handwritten cursive Latin styles, many ligatures needed for maths symbols, and many composed characters with diacritics which may overlap in some cases, notably at small font sizes or bold weights). Overlapping glyphs are not sufficiently specified, and not correctly implemented. This merits some further studies.
