### ISSUE TITLE
Rquest to alter line spacing and size in Noto Nastaliq Urdu

### ISSUE THREAD

**Issue by rokapoz** [google/fonts#7810]
From Listnr, submitted from the Noto Nastaliq Urdu specimen page:

''
This font does not contain characters from many Arabic script languages. Please include all characters.

The font size is too large and the glyphs are problematic and the line spacing is too high. Please adjust the size and line spacing of the letters and all glyphs in this font to the size of the Noto Naskh Arabic font.

The letters Kaf (ک) and Gaf (گ) are the biggest problem. These letters are not visible in their entirety and the words formed from them are also not visible. While in Noto-Naskh Arabic font, these two letters and the words formed from them are fully visible
Some other characters have this problem
Please fix these problems as soon as possible
''

![image](https://github.com/google/fonts/assets/46518820/4c53e27c-be2a-4f4a-97bf-afc0a53f744e)

**Comment by chrissimpkins** [comment]
It sounds like there is nothing actionable here.  Will close.  Please feel free to re-open if anyone feels otherwise.
