### ISSUE TITLE
Add Badeen Display

### ISSUE THREAD

**Issue by haniadnansd** [google/fonts#7814]
https://github.com/haniadnansd/Badeen-Display

# Badeen Display
Badeen Display is a retro typeface that takes a bold dive into the vibrant world of youth and Arab pop culture. It challenges the norms of Arabic typography with its unique blend of contrasts, featuring a daring mix of thick and thin strokes paired with both soft and hard edges. This creates a typeface with a strong, youthful character.

**Requirements:**

Google Fonts will publish only fonts that match its requirements. Please familiarize yourself with the complete documentation in the [Google Fonts Guide](https://googlefonts.github.io/gf-guide/) (GF-Guide) and ensure your font project complies with them before submitting the font family. You can also use the [Google Fonts Project Template](https://github.com/googlefonts/googlefonts-project-template), which will help you create a repository that follows the needed structure and includes build requirements.

By filling this issue, you can confirm the project meets the  requirements (by ticking the cases or putting x between the square brackets in text mode):

- [x] I read, agree, and comply with the full [contributing requirements](https://googlefonts.github.io/gf-guide/index#pre-production-getting-your-fonts-ready-for-gf)
- [x] The entire font project is licensed under the [OFL](https://openfontlicense.org/open-font-license-official-text/)
- [x] There is no "Reserved Font Name" mention in the OFL license
- [x] Family name is unique according to [namecheck.fontdata.com](https://namecheck.fontdata.com/)
- [x] The font supports at least [GF Latin Core glyphset](https://github.com/googlefonts/glyphsets/blob/main/data/results/txt/nice-names/GF_Latin_Core.txt)
- [x] The repository respect the [upstream repo structure](https://googlefonts.github.io/gf-guide/upstream.html)
- [x] The source files are available in the repository
- [x] I am the author of the font, or the author agreed to this submission
- [x] I will maintain the repository and participate in the onboarding process (addressing, solving, and responding to issues, merging pull requests, etc)

![sampleimage](https://github.com/google/fonts/assets/171486163/82043ae5-4058-4ebf-8422-b51a99e39a34)

**Comment by haniadnansd** [comment]
# Badeen Display
Badeen Display is a retro typeface that takes a bold dive into the vibrant world of youth and Arab pop culture. It challenges the norms of Arabic typography with its unique blend of contrasts, featuring a daring mix of thick and thin strokes paired with both soft and hard edges. This creates a typeface with a strong, youthful character.

https://github.com/haniadnansd/Badeen-Display

**Comment by davelab6** [comment]
@haniadnansd wow this is an awesome submission, the github looks nice and clean :) Thanks! @chrissimpkins will triage this with our group of 'onboarding' font engineers soon :)

**Comment by haniadnansd** [comment]
Thanks @davelab6  for the kind words :) Really happy to hear that. Looking forward to see this coming to live.
