### ISSUE TITLE
Add Bungee Tint

### ISSUE THREAD

**Issue by vv-monsalve** [google/fonts#7831]
**Font Project Git Repo URL:**
https://github.com/djrrb/Bungee

**Super short description of the Font Family:**
Bungee Color contains experiments with the various color font formats out there, including SVG, COLR/CPAL and sbix.

This is the only version pending to be included to complete the full set of Bungee families.

**Image:**

<img width="813" alt="Screen Shot 2024-06-06 at 13 43 58" src="https://github.com/google/fonts/assets/48698976/cc778e55-4ffb-4e73-a21a-3a8731e2b3b8">

**Steps needed**

- [x] Decide on a different word to replace "Color" in the font name
- [ ] New palettes will be added to the font. Upstream is working on it.

**Comment by vv-monsalve** [comment]
The decision-making around the name + new palette additions work is ongoing.

**Comment by emmamarichal** [comment]
@vv-monsalve I see it in the dev-sandbox. Do you have more infos about this? 

<img width="1506" alt="Screenshot 2024-06-25 at 15 41 22" src="https://github.com/google/fonts/assets/64773544/a7ad1ee2-ee75-4d48-af37-0fa7c9a03d8c">

**Comment by vv-monsalve** [comment]
Rod added the font in Dev as the first [exploratory of Color additions in the past](https://github.com/google/fonts/pulls?q=is%3Apr+Bungee+Color+is%3Aclosed), but didn't reach prod at that time.

After confirming in the chat if it would be okay to add it now, I created this issue and have been reporting about it. Last week, the approved name was `Bungee Tint`. I've updated the issue title now.

**Comment by emmamarichal** [comment]
Ok cool, thanks for the infos :)
