### ISSUE TITLE
Request for more style options for Bellefair

### ISSUE THREAD

**Issue by rokapoz** [google/fonts#7843]
User feedback from Listr: 

"I love the Bellefair font and was going to use it for a website, but noticed that it only has the "Regular" option, no bold. When I tried using it for a heading, some of the characters changed style. I would love to use this font in the future if ever it has additional style options! Please please please add!"

**Comment by emmamarichal** [comment]
An issue has been opened in the upstream repo. I close this one! https://github.com/shinntype/bellefair/issues/12
