### ISSUE TITLE
Add [Vogue]

### ISSUE THREAD

**Issue by vladimirnikolic1** [google/fonts#7856]
**Font Project Git Repo URL:**

https://github.com/vladimirnikolic1/Vogue/

**Super short description of the Font Family:**

**Requirements:**

Google Fonts will publish only fonts that match its requirements. Please familiarize yourself with the complete documentation in the [Google Fonts Guide](https://googlefonts.github.io/gf-guide/) (GF-Guide) and ensure your font project complies with them before submitting the font family. You can also use the [Google Fonts Project Template](https://github.com/googlefonts/googlefonts-project-template), which will help you create a repository that follows the needed structure and includes build requirements.

By filling this issue, you can confirm the project meets the  requirements (by ticking the cases or putting x between the square brackets in text mode):

- [x] I read, agree, and comply with the full [contributing requirements](https://googlefonts.github.io/gf-guide/index#pre-production-getting-your-fonts-ready-for-gf)
- [x] The entire font project is licensed under the [OFL](https://openfontlicense.org/open-font-license-official-text/)
- [x] There is no "Reserved Font Name" mention in the OFL license
- [x] Family name is unique according to [namecheck.fontdata.com](https://namecheck.fontdata.com/)
- [x] The font supports at least [GF Latin Core glyphset](https://github.com/googlefonts/glyphsets/blob/main/data/results/txt/nice-names/GF_Latin_Core.txt)
- [x] The repository respect the [upstream repo structure](https://googlefonts.github.io/gf-guide/upstream.html)
- [x] The source files are available in the repository
[vogue.zip](https://github.com/user-attachments/files/15817137/vogue.zip)

- [x] I am the author of the font, or the author agreed to this submission
- [x] I will maintain the repository and participate in the onboarding process (addressing, solving, and responding to issues, merging pull requests, etc)

**Image:**

Attach here a pic or a screenshot of the font. One image is enough, it can be a few letters, to give a quick overview.
![vogue_specimen](https://github.com/google/fonts/assets/172590770/67970ac4-0245-4074-8b28-94efefe502fc)

**Comment by m4rc1e** [comment]
Thank you for the submission. I take it you drew this beautiful Didone typeface? and you'd like to license it under an OFL license? Please be honest here. We also require the project to be in a github repo with sources. I'm not going to touch "vogue.zip" since I got burned too many times downloading mp3s from Limewire in the early 2000s.

**Comment by applecuckoo** [comment]
@m4rc1e Did a check of the .zip for you, seems like it's definitely the author submitting the font.
![vogue](https://github.com/google/fonts/assets/113647417/0e51ae12-a330-40c4-808c-87d544905906)

**Comment by davelab6** [comment]
@applecuckoo thanks for that. Indeed, looking at it in https://wakamaifondue.com/beta/ I see a link, https://www.coroflot.com/vladimirnikolic which seems legit. 

But sadly @vladimirnikolic1 while this is a fine "MVP" of a typeface, the 72 glyphs is far below our required minimum glyph set, which per https://github.com/googlefonts/glyphsets/blob/main/Lib/glyphsets/results/nam/GF_Latin_Core.nam is now about 320 glyphs. 

So I am closing this issue for now, and encourage you to keep going on your journey into the world of typeface design, and hope you will be able to open a new issue in the future when your project has more glyphs :)

**Comment by vladimirnikolic1** [comment]
Repo url:
https://github.com/vladimirnikolic1/Vogue./
