### ISSUE TITLE
Add [RainbowFleshNBP]

### ISSUE THREAD

**Issue by rainbowflesh** [google/fonts#7867]
**Font Project Git Repo URL:**
https://github.com/rainbowflesh/NBP-font

**Super short description of the Font Family:**
ErbosDraco1StNbp minor tweak version, follow SIL Open Font License. 

**Requirements:**

Google Fonts will publish only fonts that match its requirements. Please familiarize yourself with the complete documentation in the [Google Fonts Guide](https://googlefonts.github.io/gf-guide/) (GF-Guide) and ensure your font project complies with them before submitting the font family. You can also use the [Google Fonts Project Template](https://github.com/googlefonts/googlefonts-project-template), which will help you create a repository that follows the needed structure and includes build requirements.

By filling this issue, you can confirm the project meets the  requirements (by ticking the cases or putting x between the square brackets in text mode):

- [x] I read, agree, and comply with the full [contributing requirements](https://googlefonts.github.io/gf-guide/index#pre-production-getting-your-fonts-ready-for-gf)
- [ ] The entire font project is licensed under the [OFL](https://openfontlicense.org/open-font-license-official-text/)
- [ ] There is no "Reserved Font Name" mention in the OFL license
- [x] Family name is unique according to [namecheck.fontdata.com](https://namecheck.fontdata.com/)
- [ ] The font supports at least [GF Latin Core glyphset](https://github.com/googlefonts/glyphsets/blob/main/data/results/txt/nice-names/GF_Latin_Core.txt)
- [x] The repository respect the [upstream repo structure](https://googlefonts.github.io/gf-guide/upstream.html)
- [ ] The source files are available in the repository
- [x] I am the author of the font, or the author agreed to this submission
- [x] I will maintain the repository and participate in the onboarding process (addressing, solving, and responding to issues, merging pull requests, etc)

**Image:**

![preview](https://raw.githubusercontent.com/rainbowflesh/NBP-font/main/preview.png)

**Comment by applecuckoo** [comment]
Just a bit of a licensing note here: This is a derivative of [Erbos Draco Monospaced](https://www.fontspace.com/erbos-draco-monospaced-nbp-font-f14579) as stated in the description. That font is licensed under CC BY-SA 3.0, which requires any modifications to be licensed under a compatible license approved by CC. Unfortunately, the OFL doesn't seem to be part of [that list of licenses](https://creativecommons.org/share-your-work/licensing-considerations/compatible-licenses/).

**Comment by rainbowflesh** [comment]
> Just a bit of a licensing note here: This is a derivative of [Erbos Draco Monospaced](https://www.fontspace.com/erbos-draco-monospaced-nbp-font-f14579) as stated in the description. That font is licensed under CC BY-SA 3.0, which requires any modifications to be licensed under a compatible license approved by CC. Unfortunately, the OFL doesn't seem to be part of [that list of licenses](https://creativecommons.org/share-your-work/licensing-considerations/compatible-licenses/).

Thanks for the mention and I have a question, dose google font accept CC4 or CC3?

**Comment by applecuckoo** [comment]
I don't believe so, but I'll leave the Google Fonts team to respond on that question.

**Comment by vv-monsalve** [comment]
Hi @rainbowflesh, I've unchecked the boxes that don't apply in this case. The checkboxes in the submission font issue are intended to draw attention to and reinforce our strong requirements, and the OFL license is one of them.
