### ISSUE TITLE
User feedback on Edu VIC WA NT Beginner: "the flicks on the letters are not correct"

### ISSUE THREAD

**Issue by rokapoz** [google/fonts#7871]
Listnr report: 

"
This is a great font, and I use it regularly as it is the closest on Google Docs to Victorian Cursive. However for it to match the Victorian Cursive the flicks on the letters are not correct, many are missing and the cross bars on I and J are also incorrect. See this link https://www.education.vic.gov.au/Documents/school/teachers/teachingresources/discipline/english/alphabetmodela.pdf 
I'm not sure if you can update it to better represent the victorian font.
"

**Comment by chrissimpkins** [comment]
@EbenSorkin Mind having a look at this bug report to see if this requires design revisions? This is an anonymous user report that came in through our front end.  We won't be able to seek additional clarifications. They are anonymous reports.

**Comment by EbenSorkin** [comment]
Sure!

It makes sense that the woman who made this font would have found different
details salient in terms of recognizing the taught pattern than the
reporting woman did.

If it looks like it makes sense to make a revision I'll let Simon know
especially since (I think) he is nearly done getting it ready to go live.

-e.

**Comment by emmamarichal** [comment]
@EbenSorkin @simoncozens, I let you open an issue in the upstream repo, if some revisions are needed here. I close this one for now!
thanks!

**Comment by EbenSorkin** [comment]
I do plan on updating this starting today.

-e.

**Comment by vv-monsalve** [comment]
Confirming: So, should the recently merged #7628 be blocked for now and updated before proceeding further in the pipeline?

**Comment by EbenSorkin** [comment]
I don’t know. I feel like if I do hold it to update this it might take
longer than internal customers in sales would prefer. But that’s just an
impression and might be false.

**Comment by vv-monsalve** [comment]
If you will address it now (today) and include it in all [subsequent Edu VIC PRs](https://github.com/google/fonts/issues/7485), I think this one should be updated before, for consistency's sake.

**Comment by simoncozens** [comment]
Wait a minute. This is Edu VIC WA NT Beginner, *not* Edu VIC WA NT Hand. Different family.

**Comment by vv-monsalve** [comment]
Ough! The name structure within this wide range of Edu families makes them a bit confusing or difficult to differentiate! :')
Okay, these changes would not apply to any current PRs, right?

**Comment by EbenSorkin** [comment]
This is a one-source-to-many build so it would apply to that source but
just one product. Is that correct Simon?

**Comment by simoncozens** [comment]
The *Hand* families (https://github.com/SorkinType/VICWANTSchoolHandAustralia) produce multiple fonts from the same source, but they do not produce Edu VIC WA NT Beginner. This font comes from completely separate sources (https://github.com/MezMerrit/AU-School-Handwriting-Fonts), and we onboarded it some time ago.

This issue might actually apply to *both* sets of handwriting families - I haven't checked - but I want to be clear that the reporter is talking about the Beginner font which is already in prod.

**Comment by vv-monsalve** [comment]
> This is a one-source-to-many build so it would apply to that source but

It was from this understanding that I made the question. Beginners is one of the previous families in prod for a long time now. But, when Eben said he would apply the changes, I understood he was referring to the current source files, hence the question.

> This issue might actually apply to both sets of handwriting families - I haven't checked

If this is the case, we should be sure that any change that gets incorporated now and if it applies to the recently merged family should receive it also.

**Comment by simoncozens** [comment]
OK, I have reviewed this again. The crossbars on I and J are incorrect and should be removed from both families. The model that the user is referring to is for the Cursive and Precursive variants, so it is correct that the "Beginner" family and the "Hand" apex family do not have the "flicks"; the Cursive and Precursive variants of Edu VIC WA NT Hand do contain the correct flicks. So all we need to do is drop the crossbars (and respace). I will do this.

**Comment by vv-monsalve** [comment]
So, confirming to be clear, you'll update both #7628 and, eventually, the currently distributed [Edu VIC WA NT Beginner](https://fonts.google.com/specimen/Edu+VIC+WA+NT+Beginner) font.
