### ISSUE TITLE
Brightos (calligraphy)

### ISSUE THREAD

**Issue by this-random-user** [google/fonts#7872]
**Font Project Git Repo URL:**

**Super short description of the Font Family:**

**Requirements:**

Google Fonts will publish only fonts that match its requirements. Please familiarize yourself with the complete documentation in the [Google Fonts Guide](https://googlefonts.github.io/gf-guide/) (GF-Guide) and ensure your font project complies with them before submitting the font family. You can also use the [Google Fonts Project Template](https://github.com/googlefonts/googlefonts-project-template), which will help you create a repository that follows the needed structure and includes build requirements.

By filling this issue, you can confirm the project meets the  requirements (by ticking the cases or putting x between the square brackets in text mode):

- [x] I read, agree, and comply with the full [contributing requirements](https://googlefonts.github.io/gf-guide/index#pre-production-getting-your-fonts-ready-for-gf)
- [ ] The entire font project is licensed under the [OFL](https://openfontlicense.org/open-font-license-official-text/)
- [ ] There is no "Reserved Font Name" mention in the OFL license
- [x] Family name is unique according to [namecheck.fontdata.com](https://namecheck.fontdata.com/)
- [ ] The font supports at least [GF Latin Core glyphset](https://github.com/googlefonts/glyphsets/blob/main/data/results/txt/nice-names/GF_Latin_Core.txt)
- [ ] The repository respect the [upstream repo structure](https://googlefonts.github.io/gf-guide/upstream.html)
- [ ] The source files are available in the repository
- [x] I am the author of the font, or the author agreed to this submission
- [ ] I will maintain the repository and participate in the onboarding process (addressing, solving, and responding to issues, merging pull requests, etc)

**Image:**
![image](https://github.com/google/fonts/assets/119680914/cf709cc6-00d3-412b-ac28-704d7115ef85)

Attach here a pic or a screenshot of the font. One image is enough, it can be a few letters, to give a quick overview.

**Comment by applecuckoo** [comment]
You didn't make this, did you? [This font](https://www.creativefabrica.com/product/brightos/ref/777922) is free for personal use, but not commercial use.

**Comment by vv-monsalve** [comment]
Hi @this-random-user, the font is indeed for sale or bundled into a paid service, so it's not an OFL project. 

I've unchecked the ones that either don't apply or can't be confirmed in this case. The checkboxes in the submission font issue are intended to draw attention to and reinforce our strong requirements. Please read them carefully (including the linked contents), and feel free to open a new submission for any other project that meets the requirements.
