### ISSUE TITLE
New Scripts Noto Fonts still displays as notdefs on iOS 18 Beta 1

### ISSUE THREAD

**Issue by Ashtontameirao** [google/fonts#7879]
Specify the font name in title with a short description of the bug. 
Please report any issue related to Noto fonts [here](https://notofonts.github.io/reporter.html).
Report any issue with Google Icon/Symbols [here](https://github.com/google/material-design-icons)

**Describe the bug**
In the apps all the new scripts are displayed as notdef Super Mario Blocks and The Website are displayed as notdef bars, Apple, Please add these! iOS 18 needs Vithkuqi, Old Sogdian, Sogdian, Chorasmian, Elymaic, Dogra, Dives Akuru, Nandinagari, Zanabazar Square, Soyombo, Makasar, Kawi, Cypro Minoan, Anatolian Hieroglyphs, Tangsa, Medefaidrin, Tangut, Khitan Small, Nushu, Znamenny, All Musical Symbols, SignWriting, Toto, Nag Mundari, Indic Siyaq, and Ottoman Siyaq

**To Reproduce**
Steps to reproduce the behavior.

**Expected behavior**

**Screenshots**

**Additional context**
Every 4 Years add 2 scripts and the other Every 4 years adds numerous scripts

**Comment by applecuckoo** [comment]
Hey, wait a second. Aren't you that same guy who opened [15 confusing, nonsensical, sloppy issues](https://github.com/google/fonts/issues?q=is%3Aissue+author%3AAshtonTameirao25) under another account?

In case you haven't realised, Google isn't Apple. And no, Google isn't going to design a Noto font for every single script in the Unicode standard, not unless there's actual demand for them. This is, by no means, a small project, and there are real people that have to design each and every glyph that goes into all these fonts. And designing those glyphs takes time. In a sense, font making is an art form. Not a science.

That's all I've got, but before you try and open another one of these 'design requests', think about the work that goes behind them.
