### ISSUE TITLE
Update Noto Sans Hebrew to v3

### ISSUE THREAD

**Issue by chrissimpkins** [google/fonts#7883]
This is a tracker for onboarding the Noto Sans Hebrew v3 major release update in the Fonts catalog. This is a major design change release that will significantly alter the design that users see in their documents.  

We received the following feedback from a user:

> I am writing to express my concerns regarding the change that has affected the Israeli UX/UI design community significantly.
>
>A few years ago, the introduction of the Noto Sans Hebrew font, designed by Ben Nathan, was a groundbreaking moment for many Israeli UX designers. This font, part of the larger Noto Sans family, was unique, highly professional, and had an international touch that was sorely missing from the landscape of Hebrew fonts.
>
>The Noto Sans Hebrew font quickly became the default choice for numerous Israeli UX/UI designers due to its exceptional quality and the variety of weights it offered. Unlike English fonts, the availability of free Hebrew fonts that are both professional and versatile is quite limited. Therefore, the Noto Sans Hebrew font filled a crucial gap and elevated the standard of design within our community.
>
>However, the Noto Sans Hebrew font, which was briefly available on Google Fonts, has been inexplicably replaced by its previous, outdated version. This older version lacks the professionalism and uniqueness of the updated design, and its sudden reintroduction has caused significant disappointment and disruption within the design community.
>
>Attached to this letter is an image comparing the beautiful, renewed glyphs of the Noto Sans Hebrew font (marked with a smiling emoji) with the unattractive, older glyphs (marked with a sad emoji). The difference is stark, and the impact on our work is substantial.
>
>We ask to understand if there are specific reasons for the reversion to the older glyphs. We would greatly appreciate an explanation.Understanding the rationale behind this change would help us find the right solution, that benefits all parties involved.
>
>Thank you for your attention to this matter. We look forward to your response and hope for a swift resolution that restores the quality and professionalism that the Noto Sans Hebrew font brought to our work.

Addressed in https://github.com/google/fonts/pull/7806

**Comment by simoncozens** [comment]
https://github.com/google/fonts/pull/7806 already merged...

**Comment by chrissimpkins** [comment]
Good timing. We'll land this early Q3 then.  Sg.  Ty!

**Comment by chrissimpkins** [comment]
@emmamarichal Do you want this issue closed since the PR has already landed in main?

**Comment by simoncozens** [comment]
Let's hold it open until it lands in prod.

**Comment by chrissimpkins** [comment]
> Let's hold it open until it lands in prod.

I tend to agree, but the Maintainers have a workflow with their repo automation tooling.  I believe that the issues close when the PR lands and the rollout is tracked in a status label.

**Comment by emmamarichal** [comment]
I assigned this issue to myself, so I can remember to close it manually once the font reach the API. It's currently in the sandbox!

**Comment by emmamarichal** [comment]
Live!

**Comment by bezalel8** [comment]
Thanks! On behalf of the entire Israeli design community!
