### ISSUE TITLE
Thai font named `Anuphan` has ( ' ) tone marks in wrong place when combined with this vowel symbol ( ำ )

### ISSUE THREAD

**Issue by Note5019** [google/fonts#7885]
Specify the font name in title with a short description of the bug. 

**Describe the bug**
this is Anuphan tone marks bug, notice the `จ่ำ` in the first word.
![Screenshot 2567-06-26 at 11 03 25](https://github.com/google/fonts/assets/40689551/fe2660da-bbd3-4e33-abde-46d182ce078a)
![Screenshot 2567-06-26 at 11 08 42](https://github.com/google/fonts/assets/40689551/1431950a-8502-4094-a590-3808d93e2ead)

this is normal tone marks place, notice the `จ่ำ` in the first word.
![Screenshot 2567-06-26 at 11 03 56](https://github.com/google/fonts/assets/40689551/79502289-b339-4db9-b173-5b19ea2d7c90)

**To Reproduce**
Steps to reproduce the behavior. 
go to this google-font and enter this text.
`จ่ำ จ้ำ จ๊ำ จ๋ำ ก็ กิ กิ่ กิ้ กิ๊ กิ๋ ดี ดี่ ดี้ ดี๋ ดือ ดื่อ ดื้อ ดื๊อ ดื๋อ  กั กั่ กั้ กั๊ กั๋  ดุ ดู `

https://fonts.google.com/specimen/Anuphan?subset=thai&noto.script=Thai&preview.text=%E0%B8%88%E0%B9%88%E0%B8%B3%20%E0%B8%88%E0%B9%89%E0%B8%B3%20%E0%B8%88%E0%B9%8A%E0%B8%B3%20%E0%B8%88%E0%B9%8B%E0%B8%B3%20%E0%B8%81%E0%B9%87%20%E0%B8%81%E0%B8%B4%20%E0%B8%81%E0%B8%B4%E0%B9%88%20%E0%B8%81%E0%B8%B4%E0%B9%89%20%E0%B8%81%E0%B8%B4%E0%B9%8A%20%E0%B8%81%E0%B8%B4%E0%B9%8B%20%E0%B8%94%E0%B8%B5%20%E0%B8%94%E0%B8%B5%E0%B9%88%20%E0%B8%94%E0%B8%B5%E0%B9%89%20%E0%B8%94%E0%B8%B5%E0%B9%8B%20%E0%B8%94%E0%B8%B7%E0%B8%AD%20%E0%B8%94%E0%B8%B7%E0%B9%88%E0%B8%AD%20%E0%B8%94%E0%B8%B7%E0%B9%89%E0%B8%AD%20%E0%B8%94%E0%B8%B7%E0%B9%8A%E0%B8%AD%20%E0%B8%94%E0%B8%B7%E0%B9%8B%E0%B8%AD%20%20%E0%B8%81%E0%B8%B1%20%E0%B8%81%E0%B8%B1%E0%B9%88%20%E0%B8%81%E0%B8%B1%E0%B9%89%20%E0%B8%81%E0%B8%B1%E0%B9%8A%20%E0%B8%81%E0%B8%B1%E0%B9%8B%20%20%E0%B8%94%E0%B8%B8%20%E0%B8%94%E0%B8%B9%20&query=a

**Expected behavior**

**Screenshots**

**Additional context**
Add any other context about the problem here (OS version, browser, printer…)

**Comment by applecuckoo** [comment]
Duplicate of issues #6983 and #7618

**Comment by emmamarichal** [comment]
Close this one, I let opened the duplicate one: https://github.com/google/fonts/issues/7618
