### ISSUE TITLE
Add "New Amsterdam"

### ISSUE THREAD

**Issue by vladimirnikolic1** [google/fonts#7889]
![image1](https://github.com/google/fonts/assets/172590770/bd88bc8f-df89-4057-b7e7-a65ac3617580)

**Font Project Git Repo URL:**
https://github.com/vladimirnikolic1/NewAmsterdam

**Super short description of the Font Family:**
New Amsterdam is unique Sans Serif typeface that will fit any of Your designs.

**Requirements:**

Google Fonts will publish only fonts that match its requirements. Please familiarize yourself with the complete documentation in the [Google Fonts Guide](https://googlefonts.github.io/gf-guide/) (GF-Guide) and ensure your font project complies with them before submitting the font family. You can also use the [Google Fonts Project Template](https://github.com/googlefonts/googlefonts-project-template), which will help you create a repository that follows the needed structure and includes build requirements.

By filling this issue, you can confirm the project meets the  requirements (by ticking the cases or putting x between the square brackets in text mode):

- [x] I read, agree, and comply with the full [contributing requirements](https://googlefonts.github.io/gf-guide/index#pre-production-getting-your-fonts-ready-for-gf)
- [x] The entire font project is licensed under the [OFL](https://openfontlicense.org/open-font-license-official-text/)
- [x] There is no "Reserved Font Name" mention in the OFL license
- [x] Family name is unique according to [namecheck.fontdata.com](https://namecheck.fontdata.com/)
- [x] The font supports at least [GF Latin Core glyphset](https://github.com/googlefonts/glyphsets/blob/main/data/results/txt/nice-names/GF_Latin_Core.txt)
- [x] The repository respect the [upstream repo structure](https://googlefonts.github.io/gf-guide/upstream.html)
- [x] The source files are available in the repository
- [x] I am the author of the font, or the author agreed to this submission
- [x] I will maintain the repository and participate in the onboarding process (addressing, solving, and responding to issues, merging pull requests, etc)

**Image:**
![New Amsterdam 53a349065c](https://github.com/google/fonts/assets/172590770/f79611c2-adc2-4bc5-80bf-4b558e299a1d)

Attach here a pic or a screenshot of the font. One image is enough, it can be a few letters, to give a quick overview.

**Comment by emmamarichal** [comment]
Hi @vladimirnikolic1!
Thank you for the submission! I guess the good repo is this one, following the google repo template? https://github.com/vladimirnikolic1/New_Amsterdam/

Please add the sources so I can take a look to font, and give you a first feedback :)
And don't hesitate to read the documentation: https://googlefonts.github.io/gf-guide/index

Cheers!

**Comment by emmamarichal** [comment]
Ok great, thank you! But don't hesitate to use the template and the Readme. Please let me know if you have any questions!
I'll add your font to the list of submissions to review, once I've examined the source file!

**Comment by emmamarichal** [comment]
Hi @vladimirnikolic1 please check my request of adding sources to your repositories for all the ones you've opened. If I don't see any sources, I will have to close all the issues you created.

**Comment by vladimirnikolic1** [comment]
Hey Emma!
I will be able to add sources during next week!

All the best 

Vlad

**Comment by vladimirnikolic1** [comment]
> Hi @vladimirnikolic1 please check my request of adding sources to your repositories for all the ones you've opened. If I don't see any sources, I will have to close all the issues you created.

Hey Emma!

Please see updated sources folder

Vladimir

**Comment by emmamarichal** [comment]
Hi @vladimirnikolic1, thank you for the sources!

For this projects, some glyphs are missing, but I think it should be easy to complete the glyphset. Here you can find the list of missing glyphs:

/Germandbls/idotaccent/jdotless/ordfeminine/ordmasculine/nbspace/periodcentered.loclCAT/periodcentered.loclCAT.case/paragraph/dieresiscomb/dotaccentcomb/gravecomb/acutecomb/hungarumlautcomb/caroncomb.alt/circumflexcomb/caroncomb/brevecomb/ringcomb/tildecomb/macroncomb/commaaccentcomb/cedillacomb/ogonekcomb/dotaccent/macron

<img width="2305" alt="Screenshot 2024-06-28 at 10 59 01" src="https://github.com/google/fonts/assets/64773544/a2569dd5-197b-4ce9-a58b-d1dfb663e200">

Please have a look to our guide for accents (it's better to use comb accents):
https://googlefonts.github.io/gf-guide/diacritics.html
The Glyphs tutorial is also nice: https://glyphsapp.com/learn/diacritics

**Comment by vv-monsalve** [comment]
@vladimirnikolic1, we will review the source submission and let you know if it is accepted. If given the case, the font must meet all of our requirements, the Latin Core glyph set being one of them. In the meantime, feel free to familiarize yourself with our requirements, detailed in the [GF-Guide](https://googlefonts.github.io/gf-guide/).

**Comment by vladimirnikolic1** [comment]
Hello @Emma Marichal
I will upload the new sources and fonts folder!

**Comment by vladimirnikolic1** [comment]
Hello @emmamarichal please see updated folders !

**Comment by emmamarichal** [comment]
Hi @vladimirnikolic1!
Did you see Dave's email yesterday? It would be nice if we could plan a videocall! thank you!

**Comment by vladimirnikolic1** [comment]
Hello @emmamarichal !
Yes !
I suggest we have a call in Monday on this !

Vladimir

**Comment by emmamarichal** [comment]
@vv-monsalve and I don't work on Monday. @vv-monsalve is there another time that would fit to your schedule?

**Comment by vladimirnikolic1** [comment]
@emmamarichal  can You test the font ?
To see If there are any missing glyphs?

**Comment by vladimirnikolic1** [comment]
Hello Emma!
I just managed to reach Dave on our meeting !
Our meeting is in Tuesday 5pm Denver time .

**Comment by emmamarichal** [comment]
I'll do a review before the meeting, so we can discuss about it. Thank you!
Some glyphs are still missing: 
- /Germandbls/idotaccent/nbspace/periodcentered.loclCAT/periodcentered.loclCAT.case/dieresiscomb/dotaccentcomb/gravecomb/acutecomb/hungarumlautcomb/caroncomb.alt/circumflexcomb/caroncomb/brevecomb/ringcomb/tildecomb/macroncomb/commaaccentcomb/cedillacomb/ogonekcomb

**Comment by vladimirnikolic1** [comment]
Hey @emmamarichal 
I just reuploaded files!

**Comment by vladimirnikolic1** [comment]
@emmamarichal can You do the glyphs test again?
