### ISSUE TITLE
Add "Pudding"

### ISSUE THREAD

**Issue by vladimirnikolic1** [google/fonts#7893]
![bfdbfd](https://github.com/google/fonts/assets/172590770/1ac20950-daef-4a01-9191-5be905275d5e)
**Font Project Git Repo URL:**
https://github.com/vladimirnikolic1/Pudding

**Super short description of the Font Family:**
Pudding is a stylish font !

**Requirements:**

Google Fonts will publish only fonts that match its requirements. Please familiarize yourself with the complete documentation in the [Google Fonts Guide](https://googlefonts.github.io/gf-guide/) (GF-Guide) and ensure your font project complies with them before submitting the font family. You can also use the [Google Fonts Project Template](https://github.com/googlefonts/googlefonts-project-template), which will help you create a repository that follows the needed structure and includes build requirements.

By filling this issue, you can confirm the project meets the  requirements (by ticking the cases or putting x between the square brackets in text mode):

- [ ] I read, agree, and comply with the full [contributing requirements](https://googlefonts.github.io/gf-guide/index#pre-production-getting-your-fonts-ready-for-gf)
- [ ] The entire font project is licensed under the [OFL](https://openfontlicense.org/open-font-license-official-text/)
- [ ] There is no "Reserved Font Name" mention in the OFL license
- [ ] Family name is unique according to [namecheck.fontdata.com](https://namecheck.fontdata.com/)
- [ ] The font supports at least [GF Latin Core glyphset](https://github.com/googlefonts/glyphsets/blob/main/data/results/txt/nice-names/GF_Latin_Core.txt)
- [ ] The repository respect the [upstream repo structure](https://googlefonts.github.io/gf-guide/upstream.html)
- [ ] The source files are available in the repository
- [ ] I am the author of the font, or the author agreed to this submission
- [ ] I will maintain the repository and participate in the onboarding process (addressing, solving, and responding to issues, merging pull requests, etc)

![image4](https://github.com/google/fonts/assets/172590770/aa14e922-4d9c-4d61-a811-035f06a4f67c)

**Comment by emmamarichal** [comment]
Same as New Amsterdam: add sources and follow the template.

**Comment by vladimirnikolic1** [comment]
> Same as New Amsterdam: add sources and follow the template.

I will be able to add sources in the next week.
Please be patient!

Many Thanks for everything sofar!


Vladimir

**Comment by vladimirnikolic1** [comment]
> Same as New Amsterdam: add sources and follow the template.

I will also follow the template :)

**Comment by vv-monsalve** [comment]
> Google Fonts will publish only fonts that match its requirements. Please familiarize yourself with the complete documentation in the [Google Fonts Guide](https://googlefonts.github.io/gf-guide/) (GF-Guide) and ensure your font project complies with them before submitting the font family.

Hi, @vladimirnikolic1. The checkboxes in the submission issue are intended to draw attention to and reinforce our strong requirements. Please read them carefully (including the linked contents), and feel free to re-open this issue once the project meets all of them.
