### ISSUE TITLE
 Add "Consequences"

### ISSUE THREAD

**Issue by vladimirnikolic1** [google/fonts#7895]
![image2](https://github.com/google/fonts/assets/172590770/c7162b96-ffe8-4296-a7c1-fdd540e74f9b)

**Font Project Git Repo URL:**
https://github.com/vladimirnikolic1/consequences

**Super short description of the Font Family:**
Consequences is cool display typeface.

**Requirements:**

Google Fonts will publish only fonts that match its requirements. Please familiarize yourself with the complete documentation in the [Google Fonts Guide](https://googlefonts.github.io/gf-guide/) (GF-Guide) and ensure your font project complies with them before submitting the font family. You can also use the [Google Fonts Project Template](https://github.com/googlefonts/googlefonts-project-template), which will help you create a repository that follows the needed structure and includes build requirements.

By filling this issue, you can confirm the project meets the  requirements (by ticking the cases or putting x between the square brackets in text mode):

- [ ] I read, agree, and comply with the full [contributing requirements](https://googlefonts.github.io/gf-guide/index#pre-production-getting-your-fonts-ready-for-gf)
- [ ] The entire font project is licensed under the [OFL](https://openfontlicense.org/open-font-license-official-text/)
- [ ] There is no "Reserved Font Name" mention in the OFL license
- [ ] Family name is unique according to [namecheck.fontdata.com](https://namecheck.fontdata.com/)
- [ ] The font supports at least [GF Latin Core glyphset](https://github.com/googlefonts/glyphsets/blob/main/data/results/txt/nice-names/GF_Latin_Core.txt)
- [ ] The repository respect the [upstream repo structure](https://googlefonts.github.io/gf-guide/upstream.html)
- [ ] The source files are available in the repository
- [ ] I am the author of the font, or the author agreed to this submission
- [ ] I will maintain the repository and participate in the onboarding process (addressing, solving, and responding to issues, merging pull requests, etc)

**Image:**
![image1](https://github.com/google/fonts/assets/172590770/c96dd596-5d63-4f59-812a-259fe782093d)

Attach here a pic or a screenshot of the font. One image is enough, it can be a few letters, to give a quick overview.

**Comment by emmamarichal** [comment]
Same as New Amsterdam: add sources and follow the template.

**Comment by vv-monsalve** [comment]
Hi @vladimirnikolic1, the current glyphs in the font are behind our minimum requirements. Please read again all the requirements (starting with the list included in this template) and feel free to reopen this issue when the project meets all of them.
<img width="1601" alt="Screen Shot 2024-07-10 at 15 40 46" src="https://github.com/google/fonts/assets/48698976/6b56eb79-5d00-49b5-9e14-99dc16ba70dc">
