### ISSUE TITLE
Add "Smashed"

### ISSUE THREAD

**Issue by vladimirnikolic1** [google/fonts#7898]
![image13](https://github.com/google/fonts/assets/172590770/c186873a-fadf-4323-9a3d-954dfbc61251)

**Font Project Git Repo URL:**
https://github.com/vladimirnikolic1/Smashed

**Super short description of the Font Family:**
Smashed is striking typeface.

**Requirements:**

Google Fonts will publish only fonts that match its requirements. Please familiarize yourself with the complete documentation in the [Google Fonts Guide](https://googlefonts.github.io/gf-guide/) (GF-Guide) and ensure your font project complies with them before submitting the font family. You can also use the [Google Fonts Project Template](https://github.com/googlefonts/googlefonts-project-template), which will help you create a repository that follows the needed structure and includes build requirements.

By filling this issue, you can confirm the project meets the  requirements (by ticking the cases or putting x between the square brackets in text mode):

- [ ] I read, agree, and comply with the full [contributing requirements](https://googlefonts.github.io/gf-guide/index#pre-production-getting-your-fonts-ready-for-gf)
- [ ] The entire font project is licensed under the [OFL](https://openfontlicense.org/open-font-license-official-text/)
- [ ] There is no "Reserved Font Name" mention in the OFL license
- [ ] Family name is unique according to [namecheck.fontdata.com](https://namecheck.fontdata.com/)
- [ ] The font supports at least [GF Latin Core glyphset](https://github.com/googlefonts/glyphsets/blob/main/data/results/txt/nice-names/GF_Latin_Core.txt)
- [ ] The repository respect the [upstream repo structure](https://googlefonts.github.io/gf-guide/upstream.html)
- [ ] The source files are available in the repository
- [ ] I am the author of the font, or the author agreed to this submission
- [ ] I will maintain the repository and participate in the onboarding process (addressing, solving, and responding to issues, merging pull requests, etc)

![image12](https://github.com/google/fonts/assets/172590770/35d87941-3507-4d39-9fa6-939594e7abc3)

**Comment by vv-monsalve** [comment]
> Google Fonts will publish only fonts that match its requirements. Please familiarize yourself with the complete documentation in the [Google Fonts Guide](https://googlefonts.github.io/gf-guide/) (GF-Guide) and ensure your font project complies with them before submitting the font family.

Hi, @vladimirnikolic1. The checkboxes in the submission issue are intended to draw attention to and reinforce our strong requirements. Please read them carefully (including the linked contents), and feel free to re-open this issue once the project meets all of them.

**Comment by davelab6** [comment]
@vladimirnikolic1 I wonder how you created the smashed effect, was this some kind of filter/plugin for a illustration app? Since Google Fonts is more about digital (web) typography than print, I wonder if the resolution of the effect (and thus the filesize) is too high, and it would be more effective if reduced. Back in 2012 there was a font kickstarter that made adjustments in this way, https://www.kickstarter.com/projects/typesenses/font-design-euphoria-script

**Comment by vladimirnikolic1** [comment]
Hey @davelab6!
About kickstarter projects - they are not my portals. 
Vlad

**Comment by vladimirnikolic1** [comment]
Hey again @davelab6
Resolution seems to be ok for now.
If I manage to make all glyphs in this manner - The results would be amazing .
I will make sure to “finish” this font and to open a new issue!

Vlad
