### ISSUE TITLE
Add "Angelica"

### ISSUE THREAD

**Issue by vladimirnikolic1** [google/fonts#7899]
![image1](https://github.com/google/fonts/assets/172590770/40651875-8eb3-4375-bfcd-218b9f8c72da)

**Font Project Git Repo URL:**
https://github.com/vladimirnikolic1/Angelica

**Super short description of the Font Family:**
Angelica is elegant typeface!

**Requirements:**

Google Fonts will publish only fonts that match its requirements. Please familiarize yourself with the complete documentation in the [Google Fonts Guide](https://googlefonts.github.io/gf-guide/) (GF-Guide) and ensure your font project complies with them before submitting the font family. You can also use the [Google Fonts Project Template](https://github.com/googlefonts/googlefonts-project-template), which will help you create a repository that follows the needed structure and includes build requirements.

By filling this issue, you can confirm the project meets the  requirements (by ticking the cases or putting x between the square brackets in text mode):

- [ ] I read, agree, and comply with the full [contributing requirements](https://googlefonts.github.io/gf-guide/index#pre-production-getting-your-fonts-ready-for-gf)
- [ ] The entire font project is licensed under the [OFL](https://openfontlicense.org/open-font-license-official-text/)
- [ ] There is no "Reserved Font Name" mention in the OFL license
- [ ] Family name is unique according to [namecheck.fontdata.com](https://namecheck.fontdata.com/)
- [ ] The font supports at least [GF Latin Core glyphset](https://github.com/googlefonts/glyphsets/blob/main/data/results/txt/nice-names/GF_Latin_Core.txt)
- [ ] The repository respect the [upstream repo structure](https://googlefonts.github.io/gf-guide/upstream.html)
- [ ] The source files are available in the repository
- [ ] I am the author of the font, or the author agreed to this submission
- [ ] I will maintain the repository and participate in the onboarding process (addressing, solving, and responding to issues, merging pull requests, etc)

![image2](https://github.com/google/fonts/assets/172590770/319bcdb6-b4cb-4da8-87de-f598613bea1d)

**Comment by vv-monsalve** [comment]
> Google Fonts will publish only fonts that match its requirements. Please familiarize yourself with the complete documentation in the [Google Fonts Guide](https://googlefonts.github.io/gf-guide/) (GF-Guide) and ensure your font project complies with them before submitting the font family.

Hi, @vladimirnikolic1. The checkboxes in the submission issue are intended to draw attention to and reinforce our strong requirements. Please read them carefully (including the linked contents), and feel free to re-open this issue once the project meets all of them.

**Comment by davelab6** [comment]
I wonder if this could be paired somehow with #7973

**Comment by vladimirnikolic1** [comment]
Hey @davelab6 
This issue is way different than #7973 

Vlad

**Comment by vladimirnikolic1** [comment]
> I wonder if this could be paired somehow with #7973

Hey @davelab6 
I had made Angelica-Bold using this font!

**Comment by vladimirnikolic1** [comment]
> I wonder if this could be paired somehow with #7973
I was able to pair two of these fonts together!

**Comment by vladimirnikolic1** [comment]
> I wonder if this could be paired somehow with #7973


I was able to pair two fonts together!

**Comment by vladimirnikolic1** [comment]
![Image](https://github.com/user-attachments/assets/6a70208f-af07-4c2c-9ebd-88ad94ce241c)
