### ISSUE TITLE
Add Jupiter Pro Bold

### ISSUE THREAD

**Issue by crustytaco** [google/fonts#7902]
**Font Project Git Repo URL:**

**Super short description of the Font Family:**

- Jupiter Pro is a a font with a roman or fantasy type style that remains completely legible.

**Requirements:**

Google Fonts will publish only fonts that match its requirements. Please familiarize yourself with the complete documentation in the [Google Fonts Guide](https://googlefonts.github.io/gf-guide/) (GF-Guide) and ensure your font project complies with them before submitting the font family. You can also use the [Google Fonts Project Template](https://github.com/googlefonts/googlefonts-project-template), which will help you create a repository that follows the needed structure and includes build requirements.

By filling this issue, you can confirm the project meets the  requirements (by ticking the cases or putting x between the square brackets in text mode):

- [x ] I read, agree, and comply with the full [contributing requirements](https://googlefonts.github.io/gf-guide/index#pre-production-getting-your-fonts-ready-for-gf)
- [x ] The entire font project is licensed under the [OFL](https://openfontlicense.org/open-font-license-official-text/)
- [x ] There is no "Reserved Font Name" mention in the OFL license
- [ x] Family name is unique according to [namecheck.fontdata.com](https://namecheck.fontdata.com/)
- [ x] The font supports at least [GF Latin Core glyphset](https://github.com/googlefonts/glyphsets/blob/main/data/results/txt/nice-names/GF_Latin_Core.txt)
- [ x] The repository respect the [upstream repo structure](https://googlefonts.github.io/gf-guide/upstream.html)
- [ x] The source files are available in the repository
- [ x] I am the author of the font, or the author agreed to this submission
- [ x] I will maintain the repository and participate in the onboarding process (addressing, solving, and responding to issues, merging pull requests, etc)

![image](https://github.com/google/fonts/assets/144213667/a66ebc57-8ded-47e4-b20b-31b6496392e1)

**Comment by emmamarichal** [comment]
Any repository?

**Comment by emmamarichal** [comment]
So I can check the sources :)

**Comment by crustytaco** [comment]
Hello!

My apologies! I am setting it up right now!

Respectfully,

Zachary Haddon-Dennis

**Comment by crustytaco** [comment]
https://github.com/crustytaco/jupiterpro

**Comment by emmamarichal** [comment]
I only see a .OTF, and we would need glyphs file or UFO. 
Also, we need to see the OFL licence, to be sure the font is under OFL. Is that the case?

When I open the file, I see this in the licence URL field:
http://www.canadatype.com/cteula.php

**Comment by applecuckoo** [comment]
Hi! I can see that this is a commercial font available from [Canada Type](https://www.canadatype.com/product/jupiter-pro/), so it can't be added to Google Fonts. FYI, this is probably in breach of the font's license, so you should probably take down the repository.

If you're looking for a free alternative to use on Google Docs, I'd suggest the [Cormorant fonts](https://fonts.google.com/?query=cormorant).

**Comment by crustytaco** [comment]
Hello,

Oh I bought it online but i’ll remove it to prevent any issues thanks!!!

Respectfully,

Zachary Haddon-Dennis
