### ISSUE TITLE
Google Fonts Website is missing Noto Serif Dives Akuru and Noto Serif Hentaigana

### ISSUE THREAD

**Issue by Ashtontameirao** [google/fonts#7908]
Specify the font name in title with a short description of the bug. 
Please report any issue related to Noto fonts [here](https://notofonts.github.io/reporter.html).
Report any issue with Google Icon/Symbols [here](https://github.com/google/material-design-icons)

**Describe the bug**

**To Reproduce**
Steps to reproduce the behavior.

**Expected behavior**

**Screenshots**

**Additional context**
Add any other context about the problem here (OS version, browser, printer…)

**Comment by applecuckoo** [comment]
*sigh...* Have you not read what I said over [here](https://github.com/google/fonts/issues/7879#issuecomment-2185398152)? This is a place that is for adding existing fonts. Google **will not** add every single script under the sun, despite your constant requests for them to do so. Are you actually going to use these fonts, or are you just giving font designers another burden to work on? You seem to have **zero appreciation** for the hard work, and the countless hours that go into maintaining fonts. Instead, you just take it for granted and give absolutely nothing in return.

Don't come back, unless you have something to contribute.

**Comment by kenmcd** [comment]
> **Describe the bug**
> A clear and concise description of what the bug is.

Severe cluelessness.
