### ISSUE TITLE
Confusion related to attribution 

### ISSUE THREAD

**Issue by sanskaarGithub06** [google/fonts#7921]
Hi I am a youtuber from india and I want to use your animated emojis but I am really confused about your attribution section will I have to give attribution to Github or not or if yes how can I attribute you please provide me attribution text if I have to give attribution actually I saw other youtubers to use GitHub animated emojis without give attribution that's why I am confused pls answer this ASAP!!

Regards 
Sanskaar Johari

**Comment by applecuckoo** [comment]
From https://googlefonts.github.io/noto-emoji-animation/documentation:
>Animated Noto Emoji is licensed under [CC BY 4.0](https://creativecommons.org/licenses/by/4.0/legalcode). See the full license for all details.

So something like the following would work:
> [Laughing emoji](https://googlefonts.github.io/noto-emoji-animation/?selected=Animated%20Emoji%3Aemoji_u1f606%3A) by [Google Fonts](https://googlefonts.github.io/noto-emoji-animation/) is licensed under [CC BY 4.0](https://creativecommons.org/licenses/by/4.0/)

**Comment by vv-monsalve** [comment]
Hi @sanskaarGithub06, as @applecuckoo says, please refer to the FAQ in the documentation section of the [Animated Emoji webpage](https://googlefonts.github.io/noto-emoji-animation/), under the first question/answer.
