### ISSUE TITLE
Add [Fira Sans sustainable]

### ISSUE THREAD

**Issue by design-change** [google/fonts#7943]
**Font Project Git Repo URL: https://github.com/design-change/fira-sans-sustainable-google-fonts**

**Super short description of the Font Family: fira sans re-design for ink & paper usage optimization • ryman eco project inspired • inline font with original way for extra reduction & kerning optimization in case • humanistic design to improve readability, narrow enough to reduce the number of printed pages, with high readability when optimisation is also a reduction in text size • **

**Requirements:**

Google Fonts will publish only fonts that match its requirements. Please familiarize yourself with the complete documentation in the [Google Fonts Guide](https://googlefonts.github.io/gf-guide/) (GF-Guide) and ensure your font project complies with them before submitting the font family. You can also use the [Google Fonts Project Template](https://github.com/googlefonts/googlefonts-project-template), which will help you create a repository that follows the needed structure and includes build requirements.

By filling this issue, you can confirm the project meets the  requirements (by ticking the cases or putting x between the square brackets in text mode):

- [x ] I read, agree, and comply with the full [contributing requirements](https://googlefonts.github.io/gf-guide/index#pre-production-getting-your-fonts-ready-for-gf)
- [x ] The entire font project is licensed under the [OFL](https://openfontlicense.org/open-font-license-official-text/)
- [x ] There is no "Reserved Font Name" mention in the OFL license
- [x ] Family name is unique according to [namecheck.fontdata.com](https://namecheck.fontdata.com/)
- [x ] The font supports at least [GF Latin Core glyphset](https://github.com/googlefonts/glyphsets/blob/main/data/results/txt/nice-names/GF_Latin_Core.txt)
- [x ] The repository respect the [upstream repo structure](https://googlefonts.github.io/gf-guide/upstream.html)
- [x ] The source files are available in the repository
- [x ] I am the author of the font, or the author agreed to this submission
- [x ] I will maintain the repository and participate in the onboarding process (addressing, solving, and responding to issues, merging pull requests, etc)

**Image:**

![plakat final kopia](https://github.com/user-attachments/assets/191899de-438e-4fff-919f-66b90324ff7e)

Attach here a pic or a screenshot of the font. One image is enough, it can be a few letters, to give a quick overview.

**Comment by ravid-dubsteper** [comment]
![image](https://github.com/user-attachments/assets/08d75687-01ee-4663-ac57-d1f8e5264fc4)

**Comment by emmamarichal** [comment]
Hi @ravid-dubsteper @design-change!
Can you please add sources in your repo so I can take a look to the font? A .glyphs file for example.
Thank you!

**Comment by design-change** [comment]
> Hi @ravid-dubsteper @design-change! Can you please add sources in your repo so I can take a look to the font? A .glyphs file for example. Thank you!

hi is this file like that? https://github.com/design-change/fira-sans-sustainable/blob/fira-sans-sustainble/final.vfc
my font software trial has ended :(

**Comment by emmamarichal** [comment]
Thank you! I managed to open it with Glyphs.
I think that all the glyphset should follow the inline design :)

We will have a look with the team, I'll let you know if the project is accepted!



<img width="1821" alt="Screenshot 2024-08-07 at 11 20 49" src="https://github.com/user-attachments/assets/b0fb4651-dab8-4f52-be12-ff810813eb19">

**Comment by design-change** [comment]
@emmamarichal thanks for pointing

But as a non-basic latin language user through years of frustration with working with the base fonts blank, I decided to keep the rest of the characters that I didn't redesign in the original version instead of publishing blank characters. 

You know fira is a very complex font to make every single character, especially as I have no knowledge of characters from languages I do not know, so I also did not want to create characters without knowledge that are wrong but seem correct to me  - from experience even the most popular fonts have extended characters designed in a misleading way.

and as I try to point everywhere, this is just my redesign of the fira and I do not attribute authorship to the base font.

Therefore these are my design decisions

**Comment by davelab6** [comment]
I agree about the characters for languages you do not know - I think it is better to remove the "unsustainable" characters entirely from the font, and use Fira as a fallback. But the basic 0123456789 numerals, `$ + <` and other important symbols. are also not modified. 

If you can complete the Google Fonts Latin Base set from https://github.com/googlefonts/glyphsets/ in the sustainable set, please file a new issue.
