### ISSUE TITLE
Add music fonts?

### ISSUE THREAD

**Issue by davelab6** [google/fonts#7954]
A user wrote in

> I would like to use a specific font in Google Sheets, and I see in your FAQ that you take suggestions of fonts to add that are licensed under the SIL Open Font License. The font is called "MusiSync" by Robert Allgeyer and can be found here: https://www.fontspace.com/musisync-font-f3723
>
> MusiSync is much more extensive than the music font currently available in Google Fonts, and the reason many music teachers and students continue to use Microsoft Office instead of Google Workspace.
>
> Please let me know if adding this font would be possible!

I also found https://github.com/MuseScoreFonts while looking around.

**Comment by thlinard** [comment]
Hi @davelab6 

There are several OFL music fonts around, notably those compliant with [Standard Music Font Layout (SMuFL)](https://w3c.github.io/smufl/gitbook/), like indeed Leland from MuseScore. The SMuFL site gives a [list of compliant fonts](https://www.smufl.org/fonts/ ), several under OFL license.

Probably the most interesting one (because the sources are public) is [Sebastian](https://github.com/fkretlow/sebastian).

**Comment by davelab6** [comment]
@thlinard awesome tip, thanks! The user noted MusiSync is ascii encoded and hopes that isn't a problem for us; I think with the 'not text' category, this is OK, with the precedent for the knitting font.

**Comment by thlinard** [comment]
MusiSync is ASCII-encoded, while SMuFL is based on the Private Use Area of ​​Unicode, which could be better for a modern environment (this remains to be verified for GF). In addition, several music notation software have adopted SMuFL ([Steinberg](http://www.steinberg.net/), [Finale v27](https://www.finalemusic.com/products/finale/whats-new/), [capella 8](https://www.capella-software.com/us/index.cfm/products/capella/info-capella/)…).

It could also be interesting to convince publishers of SMuFL fonts under the OFL license to publish their sources, such as Steinberg for [Bravoura](url) and [Petaluma](https://github.com/steinbergmedia/petaluma), MuseScore for [Leland](https://github.com/MuseScoreFonts/Leland), MakeMusic for [Finale](https://makemusic.zendesk.com/hc/en-us/articles/1500013053461-MakeMusic-Fonts-and-Licensing-Information), RISM Digital Center for [Verovio](https://github.com/rism-digital/verovio/tree/develop/fonts).

**Comment by thlinard** [comment]
(Also, we could check, but I'm not sure if [MusiSync](https://www.fontspace.com/musisync-font-f3723) has something that [Noto Music](https://fonts.google.com/noto/specimen/Noto+Music) doesn't — SMuFL coverage is something else entirely though.)

**Comment by felipesanches** [comment]
Regarding **Leland**, created for **MuseScore**:
https://www.youtube.com/watch?v=XGo4PJd1lng

![Screenshot from 2024-07-19 12-39-39](https://github.com/user-attachments/assets/2a118ed7-e004-4f6e-aabe-95ceead0b2ef)

**Comment by moyogo** [comment]
https://w3c.github.io/smufl/latest/about/how-smufl-is-organised.html

> SMuFL is a superset of the Unicode Musical Symbols range

SMuFL is both Unicode and PUA.
If the characters only in SMuFL PUA are useful, they should be standardized in Unicode.

**Comment by davelab6** [comment]
@thlinard thanks for sharing your expertise and insight :)

> Probably the most interesting one (because the sources are public) is [Sebastian](https://github.com/fkretlow/sebastian).

I suggest that @emmamarichal and co start with that one, then :) 

@moyogo @simoncozens do you foresee any problems with onboarding these, or has the path been beaten by Noto already?

**Comment by simoncozens** [comment]
Sebastian won't work for us, because it's PUA encoded and the whole thing will be eaten by the subsetter.

**Comment by davelab6** [comment]
Fair. What's next up :)

**Comment by rvilarl** [comment]
I am really struggling with SVGs using SMuFL. The styles in SVGs are now ignored for security reasons and I get empty squares in Google Drive. I thought that a Google Fonts SMuFL font might resolve the issue.

**Comment by davelab6** [comment]
Sadly I think we can only support unicode only encoded fonts, so I think maybe we have to close this as infeasible as its too niche for us.
