### ISSUE TITLE
Noto Sans Simplified Chinese font is blurred

### ISSUE THREAD

**Issue by luminecs** [google/fonts#7968]
In flutter web (build by canvaskit), some characters are blurred after the Noto Sans Simplified Chinese font is bolded.

https://fonts.google.com/noto/specimen/Noto+Sans+SC

https://wonderous.app/web/#/home/wonder/tajMahal?t=0

![image](https://github.com/user-attachments/assets/dc367e31-dcdf-4420-961a-7597a4e7a755)

![image](https://github.com/user-attachments/assets/0d80fda1-64f5-4ea0-a6db-93eed80771a6)

**Comment by simoncozens** [comment]
We do not supply italic versions of the CJK fonts (nor does Adobe, there aren't any to supply).

Canvaskit is applying fake italics, messing up the rendering; canvaskit bug.
