### ISSUE TITLE
Inter changed unexpectedly

### ISSUE THREAD

**Issue by lkatkus** [google/fonts#7985]
**Describe the bug**

[Inter](https://fonts.google.com/specimen/Inter) font changed unexpectedly at somepoint in the last couple of days.

**Expected behavior**

Expect font not to change

**Screenshots**

Before
![google-inter-before](https://github.com/user-attachments/assets/5c050db8-f809-4579-94df-074ebfd85fe8)

After
![google-inter-after](https://github.com/user-attachments/assets/6463acd0-a5f7-45ad-809a-8a7d3cc8ba66)

**Additional context**

I'm using nextjs [next/font/google](https://nextjs.org/docs/pages/building-your-application/optimizing/fonts#google-fonts) , but believe that something changed with the font itself, as this can be reproduced by directly importing font without nextjs.

**Comment by m4rc1e** [comment]
Thanks for opening the issue.

We recently updated Inter so we're now serving the latest version, which includes Italics, https://github.com/google/fonts/pull/7776. 

We received a lot of requests to update this family #7661.

**Comment by lkatkus** [comment]
Cool! Thanks for the clarification.

**Comment by davelab6** [comment]
> **Expected behavior**
>
> Expect font not to change

I'm sorry but if you want this you'll need to self-host. Google Fonts team regularly updates fonts in the API, the millions of websites that use the API therefore get force-updated fonts.

**Comment by Inclushe** [comment]
I noticed that my Inter variable embed URL has stopped working. It now sends a 400 error.

https://fonts.googleapis.com/css2?family=Inter:slnt,wght@-10..0,100..900&display=swap

I believe this was the default URL when you clicked Get font > Get embed code on the [Google Fonts page](https://fonts.google.com/specimen/Inter).

[Here's a link to all GitHub repos that use that embed code.](https://github.com/search?utf8=%E2%9C%93&q=%22Inter%3Aslnt%2Cwght%40-10..0%2C100..900%26display%3Dswap%22&type=code)

**Comment by ljs19923** [comment]
Same error.. I can't deploy my project anymore. What's the best solution?

**Comment by Inclushe** [comment]
> Same error.. I can't deploy my project anymore. What's the best solution?

[Google Fonts has updated their embed code/URL to reflect their updated italics.](https://fonts.google.com/specimen/Inter)

**Comment by vv-monsalve** [comment]
> I noticed that my Inter variable embed URL has stopped working. It now sends a 400 error.
> 
> https://fonts.googleapis.com/css2?family=Inter:slnt,wght@-10..0,100..900&display=swap

Please inspect the updated [embed code](https://fonts.google.com/selection/embed)
