### ISSUE TITLE
Add Richard One

### ISSUE THREAD

**Issue by KyleNathan1827** [google/fonts#7993]
**Font Project Git Repo URL:**

[DELETE THIS LINE of example URL https://github.com/your/repo and remember to change the [Font Name] in the title]

[Download source files...](https://github.com/user-attachments/files/16504877/Richard_One.zip)

**Super short description of the Font Family:**
Richard One is a bold serif font. This font is perfect for coffee shops, brochures, etc. Richard One is based on Aleo by Alessio Laiso.

**Requirements:**

[DELETE THIS PARAGRAPH BEFORE CLICKING Google Fonts will publish only fonts that match its requirements. Please familiarize yourself with the complete documentation in the [Google Fonts Guide](https://googlefonts.github.io/gf-guide/) (GF-Guide) and ensure your font project complies with them before submitting the font family. You can also use the [Google Fonts Project Template](https://github.com/googlefonts/googlefonts-project-template), which will help you create a repository that follows the needed structure and includes build requirements. Read the bullet list below and add x between the square brackets to confirm each point, or go ahead and open it and confirm the points later and then tick the boxes on your issue page.

By opening this issue, I confirm the project meets the following requirements:

- [ ] The entire font project is available in a Github repository (repo) and licensed under the [OFL](https://openfontlicense.org/open-font-license-official-text/)
- [ ] The source files are available in the repo
- [ ] I am the sole copyright author of the entire project, or, all other copyright authors have licensed their work to me under the OFL
- [ ] There are no "Reserved Font Names" in the OFL license information, or in the project documentation of any known upstream projects. If there are RFNs, they are not used in whole or in part in this family name, or, I want to discuss how Google can work with my use of them.
- [ ] The family name is unique according to [namecheck.fontdata.com](https://namecheck.fontdata.com/)
- [ ] The font supports at least the Google Fonts 'Latin Core' glyphset from [github.com/googlefonts/glyphsets](https://github.com/googlefonts/glyphsets) ([direct link](https://github.com/googlefonts/glyphsets/blob/main/data/results/txt/nice-names/GF_Latin_Core.txt))
- [ ] The repo has the [Google Fonts preferred upstream repo structure](https://googlefonts.github.io/gf-guide/upstream.html)
- [ ] I have read, agree with, and comply with, the full [Google Fonts contributing requirements](https://googlefonts.github.io/gf-guide/index#pre-production-getting-your-fonts-ready-for-gf)
- [ ] I will maintain the repository and participate in the onboarding process (addressing, solving, and responding to issues, merging pull requests, etc)

**Image:**

[DELETE THIS LINE after attaching here an image or just a screenshot of the font family. One image is enough! And it can be just a few letters, to give a quick overview.]

**Comment by vv-monsalve** [comment]
Hi @KyleNathan1827, A GitHub repository with available source files is a strong requirement. Please read the requirements carefully and feel free to re-open this issue once the project meets all of them.
