### ISSUE TITLE
Wyatt's Hand

### ISSUE THREAD

**Issue by MrTGWS** [google/fonts#7997]
**Font Project Git Repo URL:**

**Super short description of the Font Family:**
This my hand writing.

**Requirements:**

By opening this issue, I confirm the project meets the following requirements:

- [ x] The entire font project is available in a Github repository (repo) and licensed under the [OFL](https://openfontlicense.org/open-font-license-official-text/)
- [ x] The source files are available in the repo
- [ x] I am the sole copyright author of the entire project, or, all other copyright authors have licensed their work to me under the OFL
- [x ] There are no "Reserved Font Names" in the OFL license information, or in the project documentation of any known upstream projects. If there are RFNs, they are not used in whole or in part in this family name, or, I want to discuss how Google can work with my use of them.
- [x ] The family name is unique according to [namecheck.fontdata.com](https://namecheck.fontdata.com/)
- [x ] The font supports at least the Google Fonts 'Latin Core' glyphset from [github.com/googlefonts/glyphsets](https://github.com/googlefonts/glyphsets) ([direct link](https://github.com/googlefonts/glyphsets/blob/main/data/results/txt/nice-names/GF_Latin_Core.txt))
- [x ] The repo has the [Google Fonts preferred upstream repo structure](https://googlefonts.github.io/gf-guide/upstream.html)
- [ x] I have read, agree with, and comply with, the full [Google Fonts contributing requirements](https://googlefonts.github.io/gf-guide/index#pre-production-getting-your-fonts-ready-for-gf)
- [ x] I will maintain the repository and participate in the onboarding process (addressing, solving, and responding to issues, merging pull requests, etc)
![WyattHand-Regular](https://github.com/user-attachments/assets/12808b36-c0d7-43c1-80fe-b8259f56b3a0)

**Image:**

[DELETE THIS LINE after attaching here an image or just a screenshot of the font family. One image is enough! And it can be just a few letters, to give a quick overview.]

**Comment by emmamarichal** [comment]
Hello, I'm sorry but we can't accept this project since it doesn't match our specs and there is no repository.
Feel free to open an issue again if the font matches the requirements.
