### ISSUE TITLE
Add Faculty Glyphic

### ISSUE THREAD

**Issue by DylanYoungKoto** [google/fonts#8006]
[**Font Project Git Repo URL:**](https://github.com/DylanYoungKoto/FacultyGlyphic/tree/main)

**Super short description of the Font Family:**

Faculty Glyphic is a typeface that pays homage to London's rich history and spirit of innovation, taking cues from carved typography, it combines modernity and heritage.

**Requirements:**

By opening this issue, I confirm the project meets the following requirements:

- [x] The entire font project is available in a Github repository (repo) and licensed under the [OFL](https://openfontlicense.org/open-font-license-official-text/)
- [x] The source files are available in the repo
- [x] I am the sole copyright author of the entire project, or, all other copyright authors have licensed their work to me under the OFL
- [x] There are no "Reserved Font Names" in the OFL license information, or in the project documentation of any known upstream projects. If there are RFNs, they are not used in whole or in part in this family name, or, I want to discuss how Google can work with my use of them.
- [x] The family name is unique according to [namecheck.fontdata.com](https://namecheck.fontdata.com/)
- [x] The font supports at least the Google Fonts 'Latin Core' glyphset from [github.com/googlefonts/glyphsets](https://github.com/googlefonts/glyphsets) ([direct link](https://github.com/googlefonts/glyphsets/blob/main/data/results/txt/nice-names/GF_Latin_Core.txt))
- [x] The repo has the [Google Fonts preferred upstream repo structure](https://googlefonts.github.io/gf-guide/upstream.html)
- [x] I have read, agree with, and comply with, the full [Google Fonts contributing requirements](https://googlefonts.github.io/gf-guide/index#pre-production-getting-your-fonts-ready-for-gf)
- [x] I will maintain the repository and participate in the onboarding process (addressing, solving, and responding to issues, merging pull requests, etc)

**Image:**

![FacultyGlyphic_Glyphset](https://github.com/user-attachments/assets/3a00293a-9fe9-4a07-894e-68c82aeebd2b)

**Comment by DylanYoungKoto** [comment]
Thanks @davelab6 , looking forward to seeing this progress!

**Comment by vv-monsalve** [comment]
Hi @DylanYoungKoto, The Legacy accents are part of the required GF Latin Core glyphset. In the meantime, you could add the them to the font.

You could find more information here

- [GF-Guide Diacritics marks section](https://googlefonts.github.io/gf-guide/diacritics.html)
- Glyphs app [Learn Diacritics](https://glyphsapp.com/learn/diacritics)

<img width="551" alt="Screenshot 2024-08-13 at 16 55 05" src="https://github.com/user-attachments/assets/3215600d-c834-45a8-921c-30bde85172e2">
