### ISSUE TITLE
Add Shafarik

### ISSUE THREAD

**Issue by typiconman** [google/fonts#8012]
**Font Project Git Repo URL:**

https://github.com/slavonic/Shafarik

**Super short description of the Font Family:**

Shafarik is a specialized font intended for an academic presentation of Old Church Slavonic (OCS) texts written in either the Cyrillic or Glagolitic alphabets. It supports the entire range of OCS Cyrillic, as well as both Round (Bulgarian) and Angular (Croatian) Glagolitic.

**Requirements:**

By opening this issue, I confirm the project meets the following requirements:

- [X] The entire font project is available in a Github repository (repo) and licensed under the [OFL](https://openfontlicense.org/open-font-license-official-text/)
- [X] The source files are available in the repo
- [X] I am the sole copyright author of the entire project, or, all other copyright authors have licensed their work to me under the OFL
- [X] There are no "Reserved Font Names" in the OFL license information, or in the project documentation of any known upstream projects. If there are RFNs, they are not used in whole or in part in this family name, or, I want to discuss how Google can work with my use of them.
- [X] The family name is unique according to [namecheck.fontdata.com](https://namecheck.fontdata.com/)
- [X] The font supports at least the Google Fonts 'Latin Core' glyphset from [github.com/googlefonts/glyphsets](https://github.com/googlefonts/glyphsets) ([direct link](https://github.com/googlefonts/glyphsets/blob/main/data/results/txt/nice-names/GF_Latin_Core.txt))
- [X] The repo has the [Google Fonts preferred upstream repo structure](https://googlefonts.github.io/gf-guide/upstream.html)
- [X] I have read, agree with, and comply with, the full [Google Fonts contributing requirements](https://googlefonts.github.io/gf-guide/index#pre-production-getting-your-fonts-ready-for-gf)
- [X] I will maintain the repository and participate in the onboarding process (addressing, solving, and responding to issues, merging pull requests, etc)

**Image:**

![image](https://github.com/user-attachments/assets/3d0f694c-95e7-44db-bc0b-2d0b97f68b9e)

**Comment by vv-monsalve** [comment]
Hi @typiconman, Thank you for your submission. I'll add it to the list of submissions to review, and we'll let you know about the decision.

However, inspecting the source file, I noticed that the Latin design does not match the Cyrillic. So, a couple of questions in the meantime: 

- Which font is used for the Latin? 
- In the repository, it is stated
   > The initial design of this font was based on several freeware fonts available on the Internet
   Which are the base fonts?
- In a given case, could you produce a Latin companion that matches the Cyrillic design?

<img width="1387" alt="Screenshot 2024-08-13 at 10 42 54" src="https://github.com/user-attachments/assets/75644b43-dd75-40b2-b3eb-799d132d5db6">

**Comment by typiconman** [comment]
Hello, @vv-monsalve:

This submission is part of a set of urgently needed fonts required for support of Church Slavonic and Old Church Slavonic in Google products. See also #7982 and #2403.

Regarding your questions:

> Which font is used for the Latin?

The Latin is copied from Liberation Serif.

> Which are the base fonts?

The initial design is based on CyrillicaShafarik by SynthesisSoft, 1994. I added this information to the README file.

> In a given case, could you produce a Latin companion that matches the Cyrillic design?

No. The font is not intended for representing text in the Latin script. It is intended only for an academic presentation of Church Slavonic texts written in Cyrillic or Glagolitic scripts. The Latin characters are provided only in order to pass the various minimum character set tests.

**Comment by vv-monsalve** [comment]
Thanks, @typiconman, for the details. We'll consider this when reviewing all the related projects as a set.
