### ISSUE TITLE
Rename ofl/ralewaydots/RalewayDots-Regular.ttf into RalewayDots-Thin.ttf ?

### ISSUE THREAD

**Issue by lazytyper** [google/fonts#8028]
The "Raleway Dots" font is classified as regular, but it looks ultra thin.

So, imho, I think it could be renamed into `RalewayDots-Thin.ttf`.

The link to the font page is https://fonts.google.com/specimen/Raleway+Dots

**Comment by vv-monsalve** [comment]
Hi, @lazytyper. Since this is the only weight available for this font, it is, by definition, in its 'Regular' style, so it shouldn't be renamed.
