### ISSUE TITLE
[tag tool] UX issues

### ISSUE THREAD

**Issue by vv-monsalve** [google/fonts#8034]
- The sample text for fonts oriented to different scripts from Latin need to be displayed in the actual font (currently a fallback font is used).  E.g. Baloo

    <img width="1356" alt="Screenshot 2024-08-14 at 12 19 25" src="https://github.com/user-attachments/assets/00005b57-e89b-4fb0-8dc1-34d3718fa5f2">

- The `Open Pull Request` option is not fully working. It triggers the pop-up window warning that a new tab will be opened, but then nothing happens.
- The `Edited` message reporting a value was added needs to be more noticeable. A bright background color like green would help.
- Suggestion: using `Value` or `Percentage` instead of `Weight` (which could lead to confusion)

**Comment by m4rc1e** [comment]
Issue with the Baloo 2 family is the fonts aren't loading. Just solved this.

<img width="1552" alt="Screenshot 2024-08-16 at 10 10 28" src="https://github.com/user-attachments/assets/a6b76ff5-9a1e-4991-9a59-252205a5b472">
