### ISSUE TITLE
Update Noto Sans Symbols 2

### ISSUE THREAD

**Issue by nataliakeniganti** [google/fonts#8039]
**Font Project Git Repo URL:**
https://github.com/notofonts/symbols

**Current version:** 2.008

**New available version:** 2.009

**Super short description of the upgrade:**
This release includes new symbols U+1F1AD, U+1F10D-U+1F10F, U+1F16D-U+1F16F, U+1F774-1F776, U+1F77B-1F77F, U+1F900-1F90B (thanks to Emma Marichal!)

**Bugs reported in this repo which this upgrade would fix:**

Search this repo [issue tracker](https://github.com/google/fonts/pull/6460) for the font family name and add here any links to existing issues about the font - and remember to change the Noto Sans Symbols 2 in the title]

**Comment by vv-monsalve** [comment]
> This release includes new symbols U+1F1AD, U+1F10D-U+1F10F, U+1F16D-U+1F16F, U+1F774-1F776, U+1F77B-1F77F, U+1F900-1F90B (thanks to Emma Marichal!)

@nataliakeniganti, Simon wrote this [comment](https://github.com/google/fonts/pull/6861#issuecomment-1761368150) in the PR to upgrade the font. The distributed font already includes the listed codepoints.
