### ISSUE TITLE
Request for Overpass to include Greek and Arabic  

### ISSUE THREAD

**Issue by rokapoz** [google/fonts#8058]
User feedback: "Hello, I have a question and would appreciare your quick response. 
Are there any plans for expanding the language packages for the Overpass font? We would really like to use it for websites but for that we need to be able to use it for Greek and Arabic as well. As it is not covering these languaes at the moment, we won't be able to use it :("

**Comment by chrissimpkins** [comment]
Flagging to @davelab6 as this is a significant development undertaking.

**Comment by chrissimpkins** [comment]
I moved the issue to the upstream development repository @ https://github.com/RedHatOfficial/Overpass/issues/103

Closing this issue in favor of that one.
