### ISSUE TITLE
Request to modify lowercase "k" in Cyrillic in Alumni Sans

### ISSUE THREAD

**Issue by rokapoz** [google/fonts#8060]
User request: "Hello. There is a proposal to improve the Cyrillic letter "к" in small case. it should be identical in spelling to the large letter "К". For example, like the letter "Жж". It is easy to verify this in other fonts."

**Comment by chrissimpkins** [comment]
Moved to upstream dev repository @ https://github.com/googlefonts/alumni/issues/12

Closing this issue in favor of that one.
