### ISSUE TITLE
User feedback on lowercase "t" in Teachers not being the same height as "tall" letters bdfhkl

### ISSUE THREAD

**Issue by rokapoz** [google/fonts#8062]
User feedback: "As an OT, I am loving that there is a student-friendly font option! I have found that there are a couple of letters that do not follow the standard handwriting "rules." Lowercase /t/ is a "tall letter" ; however, it is not the same size as the other tall letters /bdfhkl/. Additionally, capital /J/ when teaching letters to students, tends to have the horizontal line across the top. This font is much appreciated!"

![image](https://github.com/user-attachments/assets/38dae303-a932-4a4a-b50c-8c0f285f63da)

**Comment by chrissimpkins** [comment]
I believe that this is an intentional design feature in this family
