### ISSUE TITLE
Add DAKKHINEE 

### ISSUE THREAD

**Issue by mitradranirban** [google/fonts#8073]
**Font Project Git Repo URL:**

https://github.com/mitradranirban/font-dakkhinee/

**Super short description of the Font Family:**
A Bengali and Latin Font with glyphs designed like a South Indian Script 

**Requirements:**

By opening this issue, I confirm the project meets the following requirements:

- [x] The entire font project is available in a Github repository (repo) and licensed under the [OFL](https://openfontlicense.org/open-font-license-official-text/)
- [x] The source files are available in the repo
- [x] I am the sole copyright author of the entire project, or, all other copyright authors have licensed their work to me under the OFL
- [x] There are no "Reserved Font Names" in the OFL license information, or in the project documentation of any known upstream projects. If there are RFNs, they are not used in whole or in part in this family name, or, I want to discuss how Google can work with my use of them.
- [x] The family name is unique according to [namecheck.fontdata.com](https://namecheck.fontdata.com/)
- [x] The font supports at least the Google Fonts 'Latin Core' glyphset from [github.com/googlefonts/glyphsets](https://github.com/googlefonts/glyphsets) ([direct link](https://github.com/googlefonts/glyphsets/blob/main/data/results/txt/nice-names/GF_Latin_Core.txt))
- [x] The repo has the [Google Fonts preferred upstream repo structure](https://googlefonts.github.io/gf-guide/upstream.html)
- [x] I have read, agree with, and comply with, the full [Google Fonts contributing requirements](https://googlefonts.github.io/gf-guide/index#pre-production-getting-your-fonts-ready-for-gf)
- [x] I will maintain the repository and participate in the onboarding process (addressing, solving, and responding to issues, merging pull requests, etc)

**Image:**
![image2](https://github.com/user-attachments/assets/0568900a-96f0-4878-ba3f-8d85d482ab73)

**Comment by emmamarichal** [comment]
@mitradranirban thank you! I'm adding it to the submission to review milestone, and we will take a look :)

**Comment by davelab6** [comment]
@mitradranirban Hi Sir, I thank you so much for submitting this. I am sad to say, I don't find it yet to be at the level of design quality that I am seeking. But please do not be discouraged! I hope you'll to continue to push ahead in your type design journey, and I recommend you to obtain the following books to help you along your way :) 

- Cyrus' Inside Paragraphs (1st edition)
- Cheng's Designing Type (2nd edition)
- Campe & Rausch's Designing Fonts
- McNeil's The Visual History of Type
- Hochuli's Detail in typography
- How to Create Typefaces (Henestrosa/Meseguer/Scaglione)
- http://www.bi-scriptual.com
