### ISSUE TITLE
Open Sans Condensed give CSS3114 error in IE 11

### ISSUE THREAD

**Issue by maguijo** [google/fonts#81]
I am linking to Open Sans Condensed on the Google CDN this way:
@import url(http://fonts.googleapis.com/css?family=Open+Sans+Condensed:700);

When I pull up the web page in IE 11, using IE/Edge mode (the default) I get this error:
CSS3114: @font-face failed OpenType embedding permission check. Permission must be Installable.
File: k3k702ZOKiLJc3WVjuplzInF5uFdDttMLvmWuJdhhgs.ttf

This file number appears to be an alias(?) for http://fonts.gstatic.com/s/opensans/v13/xjAJXh38I15wypJXxuGMBp0EAVxt0G0biEntp43Qt6E.ttf

Not sure I understand how that's working, but that's the situation. I am not getting the CSS3117 error, just this one, for each instance I call the font on the page.
![screenshotcss3114](https://cloud.githubusercontent.com/assets/3968679/8757143/da8d2a00-2ca5-11e5-86d8-647156603248.JPG)

I've researched this issue and nothing seems to apply. It seems odd that Open Sans Condensed would not have the "embedding bits" required. Also, I don't get this error in Firefox or Chrome. Help?

Seems to be happening also with Open Sans. I switched to PT Sans like so, and the problem went away.
@import url(http://fonts.googleapis.com/css?family=PT+Sans);

**Comment by maguijo** [comment]
Well, for the next person who encounters this, when I added the Google fonts as a link in the head, instead of with @import in my LESS files, it started working.
Ergo:
`<link href='http://fonts.googleapis.com/css?family=Open+Sans+Condensed:300,700|Open+Sans:400,400italic,700' rel='stylesheet' type='text/css'>`
Dunno why. Just glad it works so I can move on.

**Comment by oscar-g** [comment]
I also encountered this problem in IE 11.  I am using Open Sans (truetype converted to base64) and embedded in a css file.

Since the license does allow embeding, I am thinking of modifying the source to flip the 'embedding bits'.

**Comment by thujone** [comment]
@maguijo or anyone: Does anyone have a technical explanation for why a LESS import wouldn't work, but a straight < link > reference would?

**Comment by maguijo** [comment]
@thujone sorry! I still don't know why.
