### ISSUE TITLE
Noto Serif Khmer Font Problem in Microsoft Word

### ISSUE THREAD

**Issue by ssleyley** [google/fonts#8100]
The first one with Battambang font is what is expected to happen

But the second font (Noto Serif Khmer) we can see that the (៉) drops to the lower bottom. 

This happens in Microsoft Word but it is fine in Google Docs.

https://github.com/user-attachments/assets/56a10a87-931f-4b4a-b4c9-0d5aaf5c7f38

**Comment by emmamarichal** [comment]
The video seems to not work. Can you upload images instead? thanks!

**Comment by applecuckoo** [comment]
@emmamarichal Here's a screencap:
![361664990-56a10a87-931f-4b4a-b4c9-0d5aaf5c7f38 mp4-00:00:13 467](https://github.com/user-attachments/assets/716d0e89-68ad-499f-9672-8b6d9a6e7a9d)

**Comment by simoncozens** [comment]
Thanks. The sequence is ឃ៉ា U+1783,U+17C9,U+17B6. I suspect it's another instance of a mark attachment bug I recently reported to Microsoft, but I will investigate.

**Comment by ssleyley** [comment]
> Thanks. The sequence is ឃ៉ា U+1783,U+17C9,U+17B6. I suspect it's another instance of a mark attachment bug I recently reported to Microsoft, but I will investigate.
 
Thank you!

**Comment by simoncozens** [comment]
OK, I'm going to transfer this to notofonts/khmer. What I've found is that (a) the anchors in this font are unduly complicated, which might be causing a problem, but (b) DirectWrite is also definitely doing something strange.

**Comment by simoncozens** [comment]
Moving discussion to https://github.com/notofonts/khmer/issues/30.
