### ISSUE TITLE
Fix shaping of the dot in the j caron dot below 

### ISSUE THREAD

**Issue by chrissimpkins** [google/fonts#8104]
We received a Roboto VF / static formats bug report from Samsung: https://github.com/googlefonts/roboto-classic/issues/121

@m4rc1e identified the issue and feels that it is a reasonably straightforward layout issue to address. Adding the onboarding of the fix to the Q3 2024 queue.

**Comment by emmamarichal** [comment]
@chrissimpkins I was reviewing issues, and saw nobody was assigned here, and it seems quite urgent. I assigned @m4rc1e, correct me if I'm wrong!

**Comment by chrissimpkins** [comment]
Marc fixed it but it is stuck in the pipeline behind the VF format roll out.  We shared the file directly with the Samsung team. We should roll this fix out when we can push Roboto again.

**Comment by chrissimpkins** [comment]
Closing in favor of the default tracker for Roboto onboarding.  @m4rc1e is the latest release with this bug fix in sandbox? If not, can we push it there and link the PR with the Roboto onboarding tracker?  Ty!
