### ISSUE TITLE
Add [Open Sans Condensed]

### ISSUE THREAD

**Issue by lliinnii** [google/fonts#8113]
**Font Project Git Repo URL:**

https://github.com/Fleshgrinder/google-open-sans/tree/master/open-sans-condensed

**Super short description of the Font Family:**

Open Sans Condensed is a font. It belongs to the [Open Sans](https://online-fonts.com/taxonomy/term/1177) font family. The typeface contains 3 files and supports 71 languages. The license is [Apache 2.0](https://online-fonts.com/licenses/apache-license-version-2.0). The font can be used in commercial and non-commercial use. Open Sans Condensed was developed [Steve Matteson](https://online-fonts.com/designers/steve-matteson).

**Image:**

![image](https://github.com/user-attachments/assets/738bdc9d-96e1-46f6-ba88-bb8ed5454a6d)

**Comment by m4rc1e** [comment]
Open Sans has a wdth axis + downloadable Condensed static fonts so I'm going to close this.

https://fonts.google.com/specimen/Open+Sans

**Comment by davelab6** [comment]
Yeah, I agree @m4rc1e - sadly I expect users are looking for Open Sans Condensed (as it used to exist in the GF library as a family) and aren't finding it.
