### ISSUE TITLE
18 kubrat musamim

### ISSUE THREAD

**Issue by Josefaboshady** [google/fonts#8114]
18 Kubrat Musamim Font Family
Font Project Git Repo URL:

https://github.com/Josefaboshady/18-kubrat-musamim.git

Super short description of the Font Family:

18 Kubrat Musamim is a unique and stylish font family, perfect for headlines, branding, and creative projects. Its bold lines and distinctive curves add a touch of personality to any design.

Requirements:

Google Fonts only publishes fonts that meet specific criteria. Please ensure your font project complies with these guidelines before submitting.

Familiarity with Google Fonts Requirements:

Review the complete Google Fonts Guide: https://github.com/google/fonts/blob/main/CONTRIBUTING.md
Utilize the Google Fonts Project Template: https://github.com/googlefonts/googlefonts-project-template (recommended for correct structure and build requirements)
Confirming Project Requirements:

By opening an issue, you confirm your project meets these requirements:

[ ] Entire project on Github with an [OFL](https://openfontlicense.org/open-font-license-official-text/) license.
[ ] Source files available in the repository.
[ ] You hold sole copyright or have obtained necessary permissions under OFL.
[ ] No "Reserved Font Names" used in the family name.
[ ] Unique family name according to [namecheck.fontdata.com](https://namecheck.fontdata.com/).
[ ] Supports at least Google Fonts "Latin Core" glyphset: https://github.com/koeberlin/Latin-Character-Sets
[ ] Follows the Google Fonts preferred upstream repo structure: https://github.com/orgs/community/discussions/64833
[ ] Reviewed and agree with the Google Fonts contributing requirements: https://github.com/google/fonts/blob/main/CONTRIBUTING.md
[ ] Committed to maintaining the repository and participating in the onboarding process.
Image:

https://github.com/Josefaboshady/18-kubrat-musamim.git
Note:

Replace bracketed text with the appropriate information for your specific font project.

**Comment by emmamarichal** [comment]
Sorry, I don't see any sources in the repo, and no OFL licence. I close the issue!
