### ISSUE TITLE
Update Rubik Doodle Shadow

### ISSUE THREAD

**Issue by ImaneDardour124** [google/fonts#8120]
**Font Project Git Repo URL:**

https://github.com/NaN-xyz/Rubik-Filtered

**Current version:**

[DELETE THIS LINE of example version v1.000]

**New available version:**

[DELETE THIS LINE of example version v2.000]

**Super short description of the upgrade:**

[DELETE THIS LINE of example descriptions: I expanded the language support with X additions to the glyphset, expanded the design space, improved rendering by X, fixed bugs about X, etc]

**Bugs reported in this repo which this upgrade would fix:**

[DELETE THIS LINE Search this repo [issue tracker](https://github.com/google/fonts/issues) for the font family name and add here any links to existing issues about the font - and remember to change the [Font Name] in the title]

**Comment by emmamarichal** [comment]
Not all of these fonts are ready, or are still encountering technical problems, and some of them are already on GF. So I'm closing all these issues and will let the designers open some if the situation improves.
