### ISSUE TITLE
Google url added to minisite url

### ISSUE THREAD

**Issue by thlinard** [google/fonts#8136]
**Describe the issue**
The "https://" part in minisite_url property in METADATA.pb becomes "https://fonts.google.com/" on the website.

**To Reproduce**

- [Bricolage+Grotesque](https://fonts.google.com/specimen/Bricolage+Grotesque): link to "https://fonts.google.com/ateliertriay.github.io/bricolage"
- [Fraunces](https://fonts.google.com/specimen/Fraunces): link to "https://fonts.google.com/fraunces.undercase.xyz"
- Etc.

**Comment by emmamarichal** [comment]
@thlinard I tested last week and it was the case. But now, I can't reproduce the error, do you still have it?

**Comment by thlinard** [comment]
@emmamarichal No, you're right, everything is fine now. Thanks!

**Comment by emmamarichal** [comment]
perfect!
