### ISSUE TITLE
Update Tektur 

### ISSUE THREAD

**Issue by janpier91** [google/fonts#8138]
Hello everyone, the font "Black Ops" has a problem transcribing a letter in Russian, this lowercase letter "д", which turns into a "g". Can anyone solve the problem? Thanks

**Comment by emmamarichal** [comment]
Hi @janpier91!
Do you have screenshots to show your issue?

Black Ops doesn't support cyrillic, so it's normal you don't see any "д".

**Comment by janpier91** [comment]
Sorry , i'm wrong , is Tektur font

**Comment by applecuckoo** [comment]
@emmamarichal I've reproduced this on Tektur's GF page, so there's definitely something wrong here. The 'д' glyph exists on the glyph page, so it's probably not a design issue.

**Comment by emmamarichal** [comment]
I just checked the files. A `g` is drawn on the `д` (uni0434). 
I add this issue in our todo. Thanks!

**Comment by emmamarichal** [comment]
https://github.com/hyvyys/Tektur/issues/6

**Comment by janpier91** [comment]
Hi, I spoke to the creator of this font, he should update it soon

**Comment by emmamarichal** [comment]
See: https://github.com/hyvyys/Tektur/issues/6#issuecomment-2344245303
