### ISSUE TITLE
Outfit font issue

### ISSUE THREAD

**Issue by sugubina** [google/fonts#8143]
With the size 48px and line-height set to 1, second line if text has cut of down part of letters: `j`, `y`, `ą` etc

**To Reproduce**

set size to 48px and line-height to 1 on a text that is 2 lines long, and the second line has words that contain letters: `j`, `y`, `ą` etc.

**Expected behavior**

All letters should be fully visible

**Screenshots**
<img width="1229" alt="Screenshot 2024-09-06 at 12 22 12" src="https://github.com/user-attachments/assets/a90e9823-aeab-454f-a8ea-cba770a53301">

**Additional context**
Chrome, Safari on macos Ventura

**Comment by emmamarichal** [comment]
Sorry, I can't reproduce. Do you have any issues with the vertical metrics (line-height) when you use it on the web (not on Google Fonts)?
<img width="1032" alt="Screenshot 2024-09-11 at 10 16 14" src="https://github.com/user-attachments/assets/3b77a2ef-ab4e-4985-b1c8-7fa5b3b35b71">

**Comment by vv-monsalve** [comment]
@sugubina I can't replicate this issue either. The font does not suffer from clipping when line-height = 1

<img width="1189" alt="Screenshot 2024-09-25 at 13 12 36" src="https://github.com/user-attachments/assets/d8afba82-2acb-44da-b6bc-21341ffe18c9">
