### ISSUE TITLE
Playwrite België Walloon font name is a faux pas

### ISSUE THREAD

**Issue by moyogo** [google/fonts#8161]
The name "Playwrite België Walloon" is problematic, a linguistic faux pas using the wrong language and alluding to only one of the 2 French speaking regions.

**Describe the bug**
"Playwrite België Walloon" is named with the same country name as "Playwrite België Vlaams Gewest", in the Dutch language but is intended for the French language community of Walloonia and the bilingual Brussels Region.

Belgium is a trilingual country with 3 languages communities (Flemish Community, "Vlaams Gewest" in Dutch is actually one of the regions, the French speaking Wallonia-Brussels Federation called "Fédération Wallonie-Bruxelles" and the German speaking German community) and with 3 regions (Flanders, Wallonia and Brussels regions).
Without counting the exceptional cases: Dutch is spoken in Flanders and Brussels, French is spoken in Wallonia and Brussels, German is spoken in a small part of Wallonia. The Brussels Region is nowadays mostly French speaking, at least when counting residents.

It makes no sense to name the Playwrite version meant for the French speaking parts of Belgium with the Dutch name of the country "België" when the French "Belgique" is distinct and expected.

There’s a minor inconsistency between "Vlaams Gewest", i.e. the Flemish Region, and "Walloon", the adjective for Wallonia or the name of a Romance language distinct from French spoken in Wallonia.
One would expect both Belgian versions to either use the language communities names or use the language names themselves. However "Fédération Wallonie-Bruxelles" is likely too long. Using region names is inadequate as there are languages overlaps.

It’s a pity the simple and short "Playwrite België" and "Playwrite Belgique" couldn’t be used.

**Expected behavior**

French speaking users should find a Playwrite font with a name using their community’s language as is done for all the other Playwrite fonts.

**Screenshots**

When searching for the incomplete "Playwrite Belg" while typing both "Playwrite België Vlaams Gewest" and "Playwrite België Walloon" match, which is fine:
<img width="1022" alt="Screenshot 2024-09-11 at 19 02 14" src="https://github.com/user-attachments/assets/7d06eb56-d210-45b6-b776-d6d80e503bc5">

When searching for the expected first part "Playwrite Belgique", no match is found:
<img width="1032" alt="Screenshot 2024-09-11 at 19 01 49" src="https://github.com/user-attachments/assets/8b9ce91b-264a-4451-a537-3ec9da8636ed">

**Additional context**

Languages in Belgium are a sensitive topic for many people, particularly in politics for the past couple of hundred years. It would be sound not to mess this up.

**Comment by emmamarichal** [comment]
@vv-monsalve

**Comment by vv-monsalve** [comment]
> French speaking users should find a Playwrite font with a name using their community’s language as is done for all the other Playwrite fonts.


@moyogo If I'm understanding the issue correctly, the solution would be to change the display from `Playwrite Belgïe Walloon` to `Playwrite Belgique Walloon`, is that correct?

**Comment by moyogo** [comment]
@vv-monsalve Possibly.

"Walloon" is still problematic, as the "Fédération Wallonie-Bruxelles" (Wallonia-Brussels Federation) is responsible for French education, and "Walloon" refers to "Wallonia" ("Wallonie" in French) which is 1 of the 2 regions of the FWB. "Walloon" is also a language distinct from French, so it’s a bit confusing.

I guess "Playwrite Belgïe Vlaams Gewest" is problematic to a lesser degree as well.
The "Vlaamse Gemeenschap" (Flemish Community) is responsible for the Dutch education, not the "Vlaamse Gewest" (Flemish Region) which is 1 of the 2 regions of the "Vlaamse Gemeenschap". "Vlaamse" is the adjective for "Vlaanderen" (Flanders) which can be used for both the Flemish region or, in the broader sense, the regions of the language community (Flemish region + Brussels).

| Schemes | Dutch language font | French language font | Note
| -- | -- | -- | -- |
| Country | Playwrite Belgïe |  Playwrite Belgique | 
| Country + language | Playwrite Belgïe Nederlands | Playwrite Belgique Français |
| Country + language adjective | Playwrite Belgïe Nederlandstalig | Playwrite Belgique Francophone
| Country + main region | Playwrite Belgïe Vlaams Gewest | Playwrite Belgique Wallonie | Brussels Region not referred to
| Country + language community | Playwrite Belgïe Vlaamse Gemeenschap | Playwrite Belgique Fédération Wallonie-Bruxelles | 
| Country + language community short names | Playwrite Belgïe Vlaanderen | Playwrite Belgique Wallonie-Bruxelles | 

I think one of "Country", "Country + language adjective", "Country + language community short name" would be best. If needed, because some names are too long, schemes can be mixed like "Playwrite Belgïe Vlaanderen" and "Playwrite Belgique Francophone".

**Comment by vv-monsalve** [comment]
Thank you, @moyogo, for the added details. Following them and considering the space in the UI for the DIsplay Name, I think the best option for these fonts would be

```
| Country + language community short names | Playwrite België Vlaanderen | Playwrite Belgique Wallonie-Bruxelles |
```

 @davelab6 and @josescaglione sounds good for you?

**Comment by josescaglione** [comment]
are they short enough?

**Comment by vv-monsalve** [comment]
The family and file name will not (can't) change. This would be a change for the Display Name in the UI (see below image).

| Family and file name | Display name|
|---|---|
| Playwrite BE WAL | Playwrite Belgique Wallonie-Bruxelles |
| Playwrite BE VLG | Playwrite België Vlaanderen|

<br>

<img width="727" alt="Screenshot 2024-09-26 at 09 58 32" src="https://github.com/user-attachments/assets/c36b5d11-e48c-42a2-82ce-72883d170b0f">

**Comment by josescaglione** [comment]
apologies, now I see. I agree with moving ahead @vv-monsalve
