### ISSUE TITLE
Me Font

### ISSUE THREAD

**Issue by PumelloBread** [google/fonts#8162]
[webfontkit-20240911-175345.zip](https://github.com/user-attachments/files/16970855/webfontkit-20240911-175345.zip)
**Font Project Git Repo URL:**

**Comment by emmamarichal** [comment]
This issue doesn't follow the usual template with the repo link, the checklist etc.
Please open a new issue when it's ready (we prefer to not open .zip files).
Thank you!

**Comment by applecuckoo** [comment]
@emmamarichal I should also point out that even if this font *was* in a repo, a quick check in Wakamai Fondue shows that the font was made using Calligraphr which can't be accepted on Google Fonts for the reasons outlined in https://github.com/google/fonts/issues/5699#issuecomment-1350787186.
