### ISSUE TITLE
Update Noto Sans (Simplified and Traditional) Chinese (and Hong Kong) and Noto Sans Japanese

### ISSUE THREAD

**Issue by MatthewtheUnicoder** [google/fonts#8163]
**List of Unicode Characters that need to get added**
- Ideographic Description Characters (U+2FFC-U+2FFF)
- Cantonese Bopomofo (U+31BC-U+31BF)
- CJK Strokes (U+31E4-U+31E5)
- Ideographic Description Character (U+31EF)
- Katakana Square Patu (U+332C)
- CJK Unified Ideographs (U+4DB7-U+4DBF) (Fix)
- CJK Unified Ideographs (U+9FF0-U+9FFF) (Fix)
- Old Chinese Punctuation (U+16FE2-U+16FE3)
- Vietnamese Marks (U+16FF0-U+16FF1)
- Katakana Minnan Tones (U+1AFF0-U+1AFF3, U+1AFF5-U+1AFFB, U+1AFFD-U+1AFFE)
- Archaic Kana Letters (U+1B000-U+1B001)
- Hentaigana (U+1B002-U+1B0FF)
- Hentaigana (U+1B100-U+1B11E)
- Archaic Kana Letters (U+1B11F-U+1B122)
- Extended Small Kana Letters (U+1B132, U+1B150-U+1B152, U+1B155, U+1B164-U+1B167)
- Some New Ideographs in Plane 2 and Plane 3

**I hope you reply something nice and hope this fix this problem and font these new characters**

**Comment by emmamarichal** [comment]
Hello @MatthewtheUnicoder, thank you for this issue.
We receive many requests of this kind for Noto fonts, and we cannot address them immediately. Updating the Noto fonts follows a complex process and takes time before certain updates can be made. Therefore, I am closing this issue for now. However, I am forwarding your suggestions to @simoncozens!

**Comment by simoncozens** [comment]
Yes, we're very aware of the Noto "gaps", and track them at https://notofonts.github.io/overview/gaplist.txt
Please note that Hentaigana is covered in Noto through its own separate font. Drawing CJK ideographs is a very specialist form of type design and there are very many glyphs to cover; we are looking into new technologies such as variable components that would help us to have these glyphs designed in a more efficient way, but it will take time.
