### ISSUE TITLE
Update Noto Sans Egyptian Hieroglyphs

### ISSUE THREAD

**Issue by MatthewtheUnicoder** [google/fonts#8165]
**New Unicode Characters for this Font**
- Egyptian Hieroglyph Format Controls (U+13430-U+13442, U+13447-U+13455)
- Extended Egyptian Hieroglyphs (U+13460-143FF) (Possibly will get it for the Hieratic characters (U+143F3-U+143F6))

**Comment by emmamarichal** [comment]
Hi @MatthewtheUnicoder, same as https://github.com/google/fonts/issues/8163#issuecomment-2345588421
cc @simoncozens
