### ISSUE TITLE
List of Gap Characters Unicode 16.0

### ISSUE THREAD

**Issue by MatthewtheUnicoder** [google/fonts#8168]
**List of Gap List Characters that need a font**
- Syriac Supplement (U+0860-U+086A)
- Arabic Pepet (U+0897)
- Extended Combining Marks (U+1AC1-U+1AC6)
- Balinese Punctuation (U+1B4E-U+1B4F, U+1B7F)
- Cyrillic Letter Tje (U+1C89-U+1C8A)
- Combining Dot Below Left (U+1DFA)
- Checker Forms (U+2427-U+2429)
- Glagolitic Letter Caudate Chrivi (U+2C2F, U+2C5F)
- Ideographic Description Characters (U+2FFC-U+2FFF)
- Cantonese Bopomofo (U+31BC-U+31BF)
- CJK Strokes (U+31E4-U+31E5)
- Ideographic Description Character Subtraction (U+31EF)
- Square Paatu (U+332C)
- CJK Unified Ideographs (U+4DB6-U+4DBF)
- CJK Unified Ideographs (U+9FF0-U+9FFF)
- Latin Extended-D Characters (U+A7CB-U+A7CD, U+A7DA-U+A7DC)
- Todhri (U+105C0-U+105F3)
- Garay (U+10D40-U+10D65, U+10D69-U+10D85, U+10D8F)
- Two Dot Arabic Characters (U+10EC2-U+10EC4)
-  Tulu-Tigalari (U+11380-U+113E2)
- Myanmar Extended-C (U+116D0-U+116E3)
- Sunuwar (U+11BC0-U+11BE1, U+11BF0-U+11BF9)
- Kawi Sign Nukta (U+11F5A)
- Egyptian Hieroglyph Format Controls (U+13430-U+13440, U+13447-U+13455)
- Egyptian Hieroglyphs Extended-A (U+13460-U+143FA)
- Gurung Khema (U+16100-+U+16139)
- Kirat Rai (U+16D40-U+16D79)
- Ideographic Symbols and Punctuation (U+16FE2-U+16FE3, U+16FF0-U+16FF1)
- Khitan Small Script Character-18CFF (U+18CFF)
- Kana Extended-B (U+1AFF0-U+1AFF3, U+1AFF5-U+1AFFB, U+1AFFD-U+1AFFE)
- Kana Supplement (U+1B000-U+1B0FF)
- Kana Extended-A (U+1B100-U+1B122)
- Small Kana Extension (U+1B132, U+1B150-U+1B152, U+1B155, U+1B164-U+1B167)
- Symbols for Legacy Computing Supplement (U+1CC00-U+1CCF9, U+1CD00-U+1CEB3)
- Latin Extended-G Hook Characters (U+1DF25-U+1DF2A)
- Cyrillic Extended-D (U+1E030-U+1E06D, U+1E08F)
- Ol Onal (U+1E5D0-U+1E5FA, U+1E5FF)
- Chinese Rounded Symbols (U+1F260-U+1F265)
- Extended Arrows (U+1F8B2-U+1F8BB, U+1F8C0-U+1F8C1)
- Harp, Shovel, Leafless Tree, Fingerprint, Root Vegetable, Splatter, and Face with Bags Undereyes (U+1FA89, U+1FA8F, U+1FABE, U+1FAC6, U+1FADC, U+1FADF, U+1FAE9)
- Extended Symbols for Legacy Computing (U+1FBCB-U+1FBEF)
- Missing CJK Unified Ideographs (Plane 2 and Plane 3)

**Comment by applecuckoo** [comment]
*sigh*

I'm just a keen observer here on GitHub, but I should make it clear: this issue tracker is meant for fonts that **already exist**. You can't just say 'Hey, please design [large amount of characters]' and just walk off into nowhere.

**Font design is an art, not a science.**

For that reason, these 'wide-scope' issues are going to be closed. You have to appreciate the time and effort that goes into creating a font. There is a real human being on the other end that will have to end up drawing **every single glyph** that you have stated above, and doing that will use up their precious time. Not everyone will just make fonts pro bono. After the glyphs have been drawn, there will probably be a language expert who will review the designs and make sure they are suitable for use.

And that's not mentioning the countless other people who help out Google Fonts, like the folks who make sure that there won't be any technical issues when people use these fonts, or the folks who forward any font complaints that come through from Google Fonts' anonymous feedback system.  So you see, it's not just about you.

To quote @simoncozens:
> We know about the gaps and will cover them when **time and resources** allow.

You see that? Time and resources. Making a font isn't one of those jobs where you can't just have an AI do it for free. It will always need that human touch.

So, @MatthewtheUnicoder. before you click that shiny green 'New Issue' button again and request something, maybe you should make sure you actually *have* a font to contribute.
