### ISSUE TITLE
Request for Lanna style Tai Tham

### ISSUE THREAD

**Issue by grande1900** [google/fonts#8183]
A lot of people use Tai Tham in northern Thailand, but the style used there is different from the one portrayed in ‘Noto Sans Tai Tham.’ This can cause confusion for people who are used to reading the Lanna style when trying to read ‘Noto Sans Tai Tham.’
Additionally, maybe this could be released under ‘Noto Serif Tai Tham.’

This also is desired because most Lanna-style Tai Tham fonts are very small compared to other fonts in the same size.
![Tai Tham Sripanyawut](https://github.com/user-attachments/assets/bc3f1b25-489b-4ae4-a757-f0a4c431289e)
<sup>Demonstrated font: [Tai Tham Sripanyawut](https://www.taithamunicode.com/fonts)</sup>

**Comment by emmamarichal** [comment]
@simoncozens ?

**Comment by simoncozens** [comment]
It would be nice, but we don't have one! SIL have one (Payap Lanna) but it's Graphite only; this is because the OpenType model for Tai Tham is unsuitable.
