### ISSUE TITLE
Feedback - Noto Chinese

### ISSUE THREAD

**Issue by Kimjisung2** [google/fonts#8198]
Noto fonts rarely support Chinese characters. Special characters such as 𪚥 and most characters used in Vietnamese and Chinese dialects are not supported.

**Comment by vv-monsalve** [comment]
Hi @Kimjisung2, Thanks for sharing this feedback. Have you checked all the [Noto fonts](https://fonts.google.com/?query=Noto+Chinese) for Chinese? Could you provide more details, like specifying which one could be improved?

cc @simoncozens

**Comment by simoncozens** [comment]
Thanks for the feedback! There are several "extended" CJK blocks in Unicode which contain many tens of thousands of characters. We hope to be able to support them in the future, but currently this would require commissioning a huge number of glyph drawings from type designers. We are looking into alternative ways of filling out this range, for example using a "recipe" of radicals and/or AI adjustments to positioning and sizing, but this is some way in the future. 

So we are aware of the problem and are trying to find good solutions, but there is no solution at present.

**Comment by NightFurySL2001** [comment]
Currently https://github.com/Fitzgerald-Porthmouth-Koenigsegg/Plangothic-Project (a derivative of Noto Sans CJK SC) covers quite a large chunk of CJK Extended blocks. Except for the largest Extension B, the remaining blocks have been filled in quite well.
