### ISSUE TITLE
Update Source Code Pro with closest v2

### ISSUE THREAD

**Issue by adrientetar** [google/fonts#82]

**Comment by rayshan** [comment]
+1

reference: https://github.com/adobe-fonts/source-code-pro/releases/tag/2.010R-ro%2F1.030R-it

**Comment by lf-** [comment]
+1 for powerline support

**Comment by laerm0** [comment]
The Source family is now updated to v2 so I am closing this issue.

**Comment by davelab6** [comment]
Are all 3 families updated? I'm not sure about this

**Comment by laerm0** [comment]
You're right, Source Code is not.

**Comment by m4rc1e** [comment]
Alright,

Google Fonts is currently serving the following:
```
Source Code Pro v1.017
Source Serif Pro v1.014
Source Sans Pro  2.021
```

Are we still ok with the vertical metrics and weight issue for Source Serif #602?

I'm not keen for the pitch forks to come out during the festive season to be honest :-). We don't need another repeat of this, https://github.com/google/fonts/issues/1307.

If we're good, I'll get them pr'd

cc @frankrolf @davelab6

**Comment by davelab6** [comment]
We a new process for announcing such changes, please make the PRs to push
the updates and we'll see if it any better at reducing the pitchforks

**Comment by RosaWagner** [comment]
same process to follow as in https://github.com/google/fonts/issues/1744
