### ISSUE TITLE
Jost

### ISSUE THREAD

**Issue by JPM9623** [google/fonts#8289]
**Describe the bug**

When using the Jost font, I am experiencing issues with macrons shifting on Chrome Version 129.0.6668.101 (Official Build) (arm64).

**To Reproduce**

Using the Jost font on a website in viewed in Chrome, render text such as 'xāxēxīxōxūx' and see that it renders as it does in the screenshots below.

**Expected behavior**

I expect the macrons to not shift.

**Screenshots**

![image](https://github.com/user-attachments/assets/2f381fd2-a089-4493-9261-12f08911596e)

**Additional context**

On macOS Sequoia 15.0.1 (24A348)

**Comment by JPM9623** [comment]
The behaviour is the same with capital letters.

**Comment by emmamarichal** [comment]
Hello @JPM9623! Thank you for opening that issue. We already know about this and are tracking it here: https://github.com/google/fonts/issues/7017
I'm currently working on it. I close this issue then, since it's duplicated :)
