### ISSUE TITLE
Add SEKUYA

### ISSUE THREAD

**Issue by kevinnseptian** [google/fonts#8325]
**Font Project Git Repo URL:**

(https://github.com/kevinnseptian/SEKUYA)

**Description:**

SEKUYA is a serif all-uppercase typeface that give a strong impression to your design. The main goal was to bring a boldness and modern feel to serif font by reworking the curves also corners and balance of modern serif font families. This font is a great choice for main text / header text on a website or layout design. SEKUYA font originally created for SEKUYA game that has anime epic fantasy vibes.

**Requirements:**

By opening this issue, I confirm the project meets the following requirements:

- [x] The entire font project is available in a Github repository (repo) and licensed under the [OFL](https://openfontlicense.org/open-font-license-official-text/)
- [x] The source files are available in the repo
- [x] I am the sole copyright author of the entire project, or, all other copyright authors have licensed their work to me under the OFL
- [x] There are no "Reserved Font Names" in the OFL license information, or in the project documentation of any known upstream projects. If there are RFNs, they are not used in whole or in part in this family name, or, I want to discuss how Google can work with my use of them.
- [x] The family name is unique according to [namecheck.fontdata.com](https://namecheck.fontdata.com/)
- [ ] The font supports at least the Google Fonts 'Latin Core' glyphset from [github.com/googlefonts/glyphsets](https://github.com/googlefonts/glyphsets) ([direct link](https://github.com/googlefonts/glyphsets/blob/main/data/results/txt/nice-names/GF_Latin_Core.txt))
- [x] The repo has the [Google Fonts preferred upstream repo structure](https://googlefonts.github.io/gf-guide/upstream.html)
- [x] I have read, agree with, and comply with, the full [Google Fonts contributing requirements](https://googlefonts.github.io/gf-guide/index#pre-production-getting-your-fonts-ready-for-gf)
- [x] I will maintain the repository and participate in the onboarding process (addressing, solving, and responding to issues, merging pull requests, etc)

**Image:**

![Image](https://github.com/user-attachments/assets/c48166a2-1d0a-41af-b2fa-bcedae90fed8)

**Comment by emmamarichal** [comment]
Hello @kevinnseptian!
Thank you for your submission. 
For now, the project doesn't follow our Google Fonts glyphset

> The font supports at least the Google Fonts 'Latin Core' glyphset from [github.com/googlefonts/glyphsets](https://github.com/googlefonts/glyphsets) ([direct link](https://github.com/googlefonts/glyphsets/blob/main/data/results/txt/nice-names/GF_Latin_Core.txt))

![Image](https://github.com/user-attachments/assets/6bb8d629-9433-4e3e-8726-752bd255ebcc)


Here are the missing ones:

Aacute
Abreve
Acircumflex
Adieresis
Agrave
Amacron
Aogonek
Aring
Atilde
AE
Cacute
Ccaron
Ccedilla
Cdotaccent
Dcaron
Dcroat
Eth
Eacute
Ecaron
Ecircumflex
Edieresis
Edotaccent
Egrave
Emacron
Eogonek
Gbreve
Gcommaaccent
Gdotaccent
Hbar
Iacute
Icircumflex
Idieresis
Idotaccent
Igrave
Imacron
Iogonek
Kcommaaccent
Lacute
Lcaron
Lcommaaccent
Lslash
Nacute
Ncaron
Ncommaaccent
Ntilde
Oacute
Ocircumflex
Odieresis
Ograve
Ohungarumlaut
Oslash
Otilde
OE
Thorn
Racute
Rcaron
Sacute
Scaron
Scedilla
Scommaaccent
Germandbls
Tcaron
Tcommaaccent
Uacute
Ucircumflex
Udieresis
Ugrave
Uhungarumlaut
Umacron
Uogonek
Uring
Wacute
Wcircumflex
Wdieresis
Wgrave
Yacute
Ycircumflex
Ydieresis
Ygrave
Zacute
Zcaron
Zdotaccent
aacute
abreve
acircumflex
adieresis
agrave
amacron
aogonek
aring
atilde
ae
cacute
ccaron
ccedilla
cdotaccent
dcaron
dcroat
eth
eacute
ecaron
ecircumflex
edieresis
edotaccent
egrave
emacron
eogonek
gbreve
gcommaaccent
gdotaccent
hbar
idotless
iacute
icircumflex
idieresis
idotaccent
igrave
imacron
iogonek
jdotless
kcommaaccent
lacute
lcaron
lcommaaccent
lslash
nacute
ncaron
ncommaaccent
ntilde
oacute
ocircumflex
odieresis
ograve
ohungarumlaut
oslash
otilde
oe
thorn
racute
rcaron
sacute
scaron
scedilla
scommaaccent
germandbls
tcaron
tcommaaccent
uacute
ucircumflex
udieresis
ugrave
uhungarumlaut
umacron
uogonek
uring
wacute
wcircumflex
wdieresis
wgrave
yacute
ycircumflex
ydieresis
ygrave
zacute
zcaron
zdotaccent
ordfeminine
ordmasculine
nbspace
ellipsis
exclamdown
questiondown
periodcentered
bullet
periodcentered.loclCAT
periodcentered.loclCAT.case
endash
emdash
quotesinglbase
quotedblbase
quotedblleft
quotedblright
quoteleft
quoteright
guillemetleft
guillemetright
guilsinglleft
guilsinglright
paragraph
section
copyright
registered
trademark
degree
cent
euro
sterling
yen
minus
multiply
divide
dieresiscomb
dotaccentcomb
gravecomb
acutecomb
hungarumlautcomb
caroncomb.alt
circumflexcomb
caroncomb
brevecomb
ringcomb
tildecomb
macroncomb
commaaccentcomb
cedillacomb
ogonekcomb
dieresis
dotaccent
acute
hungarumlaut
circumflex
caron
breve
ring
tilde
macron
cedilla
ogonek

**Comment by kevinnseptian** [comment]
Hi Emma, thanks for the information. Actually, I'm new in this kind of
thing so I don't know how to deal with this problem. But I just wondering,
can I fill the "Latin Core Glyphset" with Regular Glyphset so it can
fulfilled the requirement but at the end there's no different between Latin
Core and Regular while we type the text, or there's no other way to solve
this unless I make the "Latin Core Glyphset" itself, or can I just simply
uncheck the requirement box that you've mention and the font go with no
"Latin Core Glyphset" ?

**Comment by emmamarichal** [comment]
What are you calling "Regular Glyphset"? 
We actually need to have this Latin Core glyphset (it means you need to add and draw the missing glyphs). It's a part of our requirements, for onboarding fonts on Google Fonts. If you don't want or having time to develop the glyphset, we understand, and we will not onboard it.

But please, wait for our decision about it or not before doing all the job :)

**Comment by kevinnseptian** [comment]
Ok Emma, I get it now. Thanks for the explanation and I will fill the Latin
Core later :)

**Comment by emmamarichal** [comment]
Alright thank you! 
For now I close that issue, feel free to open a new one once the glyphset is completed :)
