### ISSUE TITLE
User confusion about  ® superscript not looking like a superscript in Lora

### ISSUE THREAD

**Issue by rokapoz** [google/fonts#8329]
A user wrote in: 

![Image](https://github.com/user-attachments/assets/b9bfe88f-4ade-465d-91f7-d446364b3152)

**Comment by thlinard** [comment]
This report will be better addressed at https://github.com/cyrealtype/Lora-Cyrillic by @alexeiva

**Comment by moyogo** [comment]
There is no requirement to have the REGISTERED SIGN as a superscript.

Some people prefer it superscript so it is a common practice.
But plenty of fonts have it close to or at cap-size.
In fact, it was full size in the hearings documents or in the law that introduced its use.

**Comment by thlinard** [comment]
When faced with a request, a creator can choose to create an alternative glyph. But I totally agree, it's a design decision.

**Comment by emmamarichal** [comment]
close this issue, since we already have this one: https://github.com/google/fonts/issues/8372
