### ISSUE TITLE
Anton SC has a ligature problem

### ISSUE THREAD

**Issue by davelab6** [google/fonts#8337]
**Describe the bug**

Anton SC has an `ff` ligature problem where the conversion of lowercase to small caps mishandled the ligature, so a lowercase ligature is substituted over two small-scaps `f`s.

**To Reproduce**

https://fonts.google.com/specimen/Anton+SC?preview.text=Waffles%20WAFFLES

**Expected behavior**

No ligature

**Screenshots**

![Image](https://github.com/user-attachments/assets/c6914d36-2b02-427f-8389-7c5e1de86db3)

@simoncozens might have insights

**Comment by simoncozens** [comment]
Looks like an issue with the order of lookups. The small cap rules are moved to the ccmp feature but they're in lookup 30; the liga feature is lookup 24. `ccmp` and `liga` are run in the same shaping "pause", so the rules are executed in order of lookup ID. This means the ligature happens first and the small caps afterwards. Our small-capifier should put the smcp rules into a fairly early lookup ID.

**Comment by vv-monsalve** [comment]
Repeated: This was reported by a user in #8331.
