### ISSUE TITLE
Where is the current Roboto repo?

### ISSUE THREAD

**Issue by thlinard** [google/fonts#8448]
I wanted to report a bug in Roboto 3.010, and all repos have been archived, in read-only state, except for the ones for Roboto Flex, Roboto Mono, Roboto Serif, and Roboto Slab but I doubt they are the right ones. Has the current Roboto repo become non-public or https://github.com/googlefonts/roboto-3-classic was archived by mistake?

https://fonts.google.com/specimen/Roboto/about points to https://github.com/googlefonts/roboto-2, which is archived, and https://github.com/google/fonts/blob/main/ofl/roboto/METADATA.pb points to https://github.com/googlefonts/roboto-3-classic, which is also archived.

**Comment by vv-monsalve** [comment]
Hi @thlinard, thank you for the report.  I can confirm they are archived now.  I raised the issue during a meeting today, but we'll need to investigate further to know if there is a reason behind it.

cc @chrissimpkins

**Comment by thlinard** [comment]
I see that https://github.com/googlefonts/roboto-3-classic is no longer archived, so that answers my question. You can close the ticket. Thanks!

**Comment by vv-monsalve** [comment]
Indeed, we reviewed them and unarchived the corresponding one.
