### ISSUE TITLE
Update Anton SC

### ISSUE THREAD

**Issue by A-timeout-occurred** [google/fonts#8478]
**Font Project Git Repo URL:**

https://globalfonts.pro/font/anton-sc

**Current version:**

2.116

**New available version:**

3.000

**Super short description of the upgrade:**

[DELETE THIS LINE of example descriptions: I expanded the language support with X additions to the glyphset, expanded the design space, improved rendering by X, fixed bugs about X, etc]

**Bugs reported in this repo which this upgrade would fix:**

[DELETE THIS LINE Search this repo [issue tracker](https://github.com/google/fonts/issues) for the font family name and add here any links to existing issues about the font - and remember to change the [Font Name] in the title]

**Comment by applecuckoo** [comment]
@A-timeout-occurred There *is* no 3.000. Why did you open this issue?
