### ISSUE TITLE
Missing vertical spacing information for Traditional Chinese fonts

### ISSUE THREAD

**Issue by NightFurySL2001** [google/fonts#8694]
The two new Traditional Chinese font, [Chocolate Classical Sans](https://fonts.google.com/specimen/Chocolate+Classical+Sans?lang=zh_Hant) and [Cactus Classical Serif](https://fonts.google.com/specimen/Cactus+Classical+Serif?lang=zh_Hant) have issues with vertical typesetting.

**Describe the bug**

Chinese text when typeset vertically has extraneous gap between character.

Chocolate Classical Sans:
![Image](https://github.com/user-attachments/assets/818a1a81-c917-4a1a-97e6-577e68bf6af4)

Cactus Classical Serif:
![Image](https://github.com/user-attachments/assets/c53d555b-3f95-439e-9690-748ae0455c7a)

It seems like the rebuild by @aaronbell in https://github.com/aaronbell/ChocolateSans and https://github.com/aaronbell/CactusSerif (missing ttf by the way) mistakenly dropped the `vhea`/`vmtx` table that were present in the original upstream font.

**To Reproduce**

1. Create a HTML with `<p style="writing-mode: vertical-rl" lang="zh-Hant"></p>`
2. Load the font in HTMl and apply to the `<p>`
3. View in Google Chrome browser/Microsoft Edge browser.

**Expected behavior**

Text should have no spacing between characters vertically. [LXGW WenKai TC](https://fonts.google.com/specimen/LXGW+WenKai+TC?lang=zh_Hant) does not show this problem.
![Image](https://github.com/user-attachments/assets/443a5faf-92e0-4b16-8885-7c4272d269ed)

**Additional context**

<details>
  <summary>Sample HTML</summary>

```html
<html>
    <head>
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Cactus+Classical+Serif&family=Chocolate+Classical+Sans&family=LXGW+WenKai+TC&display=swap" rel="stylesheet">
        <style>
            body {
                writing-mode: vertical-rl;
                font-family: "Chocolate Classical Sans";  //change the font-family here
                font-size: 20pt;
                padding: 1em;
            }
        </style>
    </head>
    <body>
        <h1>漢字</h1>
        <p>
            漢字，又稱漢文、華文、中文、華語字、唐話字、唐人字、中國字，是書寫漢語所使用的文字系統，也是現今世界上唯一仍廣泛使用的語素文字，主要流行於漢字文化圈（特別是大中華地區），也是聯合國四種官方文字之一（另外三種皆為拼音文字，分別是英語、法語與西班牙語使用的拉丁文字、俄語使用的西里爾文字和阿拉伯語使用的阿拉伯文字）。
        </p>
        <p>
            漢字是世界歷史上唯一被高度發展的語素文字，從基礎的象形字和指事字發展出了現今以形聲字和會意字為主流的六書系統，加上各類異體字和生僻字在所有字典中總共收錄超過十萬字。每個漢字在結構上由最基礎的筆畫進行二維排列組成，每個筆畫不包含任何語素，相當於表音文字的字母；由筆畫組成的偏旁部首是漢字內部結構上的最小語素單位，相當於一些表音文字的詞根。除形聲字外的漢字通常不具備音素，而形聲字的聲旁則帶有一定表音功能，但因為其大多基於上古漢語的發音所以與現代標準漢語有一些差異。現今漢字通常使用額外獨立的標音幫助閱讀，在中華民國時期主要使用注音符號，但在台灣以外的地區（特別是中國大陸）主要使用拉丁化的漢語拼音。雖然絕大多數漢字單字都擁有自身的獨立含義，在語法上相當於英文的單詞，但漢語詞彙通常都是由兩個以上單字組成的合成詞。
        </p>
    </body>
</html>
```
</details>

**Comment by chrissimpkins** [comment]
Thank you for the report!  Aaron included fixes in:

- https://github.com/google/fonts/pull/8699
- https://github.com/google/fonts/pull/8700

We'll roll these out in early Q1.

**Comment by NightFurySL2001** [comment]
Any progress on the two PRs since Iansui has been deployed to prod? @aaronbell

**Comment by emmamarichal** [comment]
@NightFurySL2001, there are currently moving to the API, it can takes several weeks :)
