### ISSUE TITLE
Rokkitt - T rendering odd above 99px

### ISSUE THREAD

**Issue by KB1RMA** [google/fonts#87]
I've run into an odd issue with the Rokkitt font. It only seems to rear its head **above 99px** (so 100px does it) and in Internet Explorer and Firefox.

Here is a JSFiddle illustrating the issue: https://jsfiddle.net/0yn08j68/7/embedded/result/

![image](https://cloud.githubusercontent.com/assets/223527/8916978/34e24498-347d-11e5-9195-c65372f3d9f7.png)

I don't know enough about font definitions to recognize if this is something simple to fix, but does anyone have an idea what might be causing it?

**Comment by davelab6** [comment]
An older version of ttfautohint, I bet!

**Comment by KB1RMA** [comment]
Ah cool - Looks like a relatively easy fix then. I've been using this great font for eons but only recently discovered this funky bug. Rarely used above 99px, but annoying when you do!

**Comment by miscfiles** [comment]
I've also encountered this problem when using a 56px font size in IE on Windows 10 running on a MacBook Pro. It seems that due to the "retina" screen, this is doubled to 112px, which causes the problem to appear.

**Comment by KB1RMA** [comment]
@davelab6 Is there any sort of timetable for deploying a fix for this? I know it's a pretty high profile font so likely requires a good deal of QA testing but curious for a general sense of when this can be expected.

**Comment by davelab6** [comment]
I expect to sort this out before the end of the year. I have a lot of new families coming which have priority over bug fixes.

**Comment by HanlonCreative** [comment]
Dave thanks for the font first off. Please let us know when resolved, I have a few areas where I am using the text as an image and would like to revert to pure html text when fixed. Thanks!

**Comment by SergeyMalkin** [comment]
Another real site is affected: arcade.com/news/post/2016/01/26/potential-thingness
And this happens in Chrome as well, just at much higher ppem size.
