### ISSUE TITLE
Remove overlap in Lateef

### ISSUE THREAD

**Issue by IvanUkhov** [google/fonts#8712]
**Describe the bug**

Lateef seems to have retained overlaps when it was built. My understanding is that it is a bad practice.

**Screenshots**

![Image](https://github.com/user-attachments/assets/4b71d821-6f39-4699-be28-d0da4fd7f7df)

**Comment by emmamarichal** [comment]
Hi @IvanUkhov!
Indeed, we tend to avoid them, since they can create some rendering issues (especially in variable fonts). 
It doesn't seem to be the case here, so we will not plan any specific upgrade for this.
