### ISSUE TITLE
Google Sans - "fft" ligature in font weight 500 bug

### ISSUE THREAD

**Issue by MrPeanut12** [google/fonts#8738]
In Google Sans, the "fft" ligature in 500 font weight appears as "ft".

**To Reproduce**

1. Type "fft"
2. Set the font weight as 500

**Expected behavior**

Text displays as "fft"

**Screenshots**

![Image](https://github.com/user-attachments/assets/d064f5c5-1736-44d5-8477-57d844a8f9a4)

**Additional context**

Windows 10/Edge
Android Google Drive app

**Comment by emmamarichal** [comment]
Hi @MrPeanut12, thank you for this report.
I ping @MariannaPaszkowska, who is in charge of that project :)

**Comment by chrissimpkins** [comment]
I can't reproduce this with our latest Google Sans release.  We don't use this tracker for our brand font projects, but I'll pass this along to the Drive team.  Thanks for the report!

**Comment by MrPeanut12** [comment]
@chrissimpkins Thanks for the update. I also experience this issue in embedded Google Calendars. I didn't figure it was tracked here, but I wasn't sure where to submit the bug.
