### ISSUE TITLE
Libre Franklin font - corrupt?

### ISSUE THREAD

**Issue by SiestaLOL** [google/fonts#8746]
Libre Franklin font shows as corrupt
**Describe the bug**

I have tried converting both the static fonts and the variable font at Font Squirrel. I'm trying to convert to woff.
When I upload the variable font, it shows as Libre Franklin Thin
When I upload the static fonts, it says they are all corrupt.

**To Reproduce**

Download the font files here: 
https://fonts.google.com/specimen/Libre+Franklin?preview.text=Whereas%20recognition%20of%20the%20inherent%20dignity

Upload the static fonts to https://www.fontsquirrel.com/tools/webfont-generator

When the variable font is uploaded to font squirrel, it only shows as the thin weight and the other weights aren't included.

**Expected behavior**

It is meant to make a woff file of each font uploaded, but it just says they are all corrupt. 

**Screenshots**

<img width="1009" alt="Image" src="https://github.com/user-attachments/assets/c859370c-060b-4f08-b3c9-b91ac1a14b00" />

This is how the different weights look when I try to upload the static fonts to my website: <img width="807" alt="Image" src="https://github.com/user-attachments/assets/e75312de-5ad5-4cd7-8997-d61889d87ab2" />

**Comment by kenmcd** [comment]
Web fonts are available in the repository. 
https://github.com/googlefonts/Libre-Franklin/tree/master/fonts/webfonts
