### ISSUE TITLE
Open Sans Condensed Light conflict in Safari

### ISSUE THREAD

**Issue by spadilha** [google/fonts#88]
Hi there,

I'm having a problem with Open Sans Condensed Light on Safari when I have both "Open Sans Condensed" and at least one of the main sets of "Open Sans" (I mean light, regular, bold, semibold and extrabold). 

If the font-size is 36px or 64px it renders correct (and 36px is the size displayed on Google Font's Character Set page...), but if you change that size it renders as it was with regular "Open Sans".

You can check that by going to the font page on google ( https://www.google.com/fonts/specimen/Open+Sans+Condensed ) , inspect the Light 300 frase and increase/decrease the font-size.

Remember that you must have both "Open Sans" and "Open Sans Condensed" installed on your machine.

With 36px
![screen shot 2015-07-29 at 02 38 18](https://cloud.githubusercontent.com/assets/336758/8950693/31882776-359b-11e5-9306-8b3098c16fed.png)

With 37px
![screen shot 2015-07-29 at 02 38 36](https://cloud.githubusercontent.com/assets/336758/8950670/febe3146-359a-11e5-8033-cba09cf3c2a7.png)

In this sample the font fallsback to "Open Sans Semibold" as I've disabled the others.

**Comment by davelab6** [comment]
https://twitter.com/snicolos/status/826741682284662785 notes, 

> "Open Sans Condensed" OT family names are awkward ("Open Sans Cond" for light and italic) on desktop

**Comment by m4rc1e** [comment]
Couldn't replicate it with Safari 10.1

![opensansfix](https://user-images.githubusercontent.com/7525512/26934495-730c9e14-4c61-11e7-9caf-2da257e95eb1.gif)
