### ISSUE TITLE
Fjalla One bug (reported in Mac Font Book)

### ISSUE THREAD

**Issue by shanecarmody** [google/fonts#91]
Is it normal that I get this error when I try to install fonts in Font Book? (OSX 10.10.4)

<img width="735" alt="screen shot 2015-08-02 at 23 38 46" src="https://cloud.githubusercontent.com/assets/433990/9025964/e9a6577e-396f-11e5-8d02-7102dade4b0d.png">

**Comment by davelab6** [comment]
@shanecarmody no, not normal, should be fixed :)

@ebensorkin I'll look into fixing this, are there any updates from your side since this version was published?

**Comment by EbenSorkin** [comment]
I think Github has the most recent version and that it should solve this problem.

-e.

**Comment by shanecarmody** [comment]
> I think Github has the most recent version and that it should solve this problem.

@EbenSorkin @davelab6 sorry I don’t understand, should the problem be fixed already? I don’t think the GitHub version works.

**Comment by shanecarmody** [comment]
So I think this might be a problem on my side. I think there are some permission issues in `~/Library/Fonts`. Anyway I solved my problem using **SilverSkyRat**’s solution in [this thread](https://discussions.apple.com/thread/6028603) on apple.com. I’m going to paste his answer here just in case anybody comes across the same issue:

> OK, next thing is to see if there are any permissions issues with your home folders. Rather than changing them right now, open Font Book, Preferences..., and change "Default install location" to "Computer". It will then try to put them in /Library/Fonts. If this works, there are permission issues with your ~/ structure somewhere inside. If it doesn't work, the most likely thing is indeed a corrupt font file. Try to get access to another Mac or even Windows Machine and locate a font that your mac doesn't have (Windows location is something like C:\Windows\Fonts). This should be a known good .otf or .ttf file from it working on the other machine. Copy that file to your mac and try to import it. Let us know 

<img width="824" alt="screen shot 2015-08-12 at 20 57 22" src="https://cloud.githubusercontent.com/assets/433990/9222381/c778be18-4134-11e5-8c49-1526034bfa71.png">

**Comment by m4rc1e** [comment]
Hey,

I installed[ Fjalla One](https://fonts.google.com/?query=fjalla&selection.family=Fjalla+One). I had no issues. Font version is 1.001, Os X 10.11.6,

![screen shot 2016-09-01 at 14 16 54](https://cloud.githubusercontent.com/assets/7525512/18167102/07585d96-704f-11e6-9642-1bd0877915d9.png)

Cheers,
Marc

**Comment by JXParker** [comment]
I'm having issue with Fjalla also, downloads with an alert via Google fonts which I ignore, works fine on layouts but then will not print correctly, skews the 'S', 'Q' and numerals. I can't present any printed versions to clients. I've tried removing the font and downloading both truetype and opentype and nothing works . . . any ideas?

![fjalla](https://cloud.githubusercontent.com/assets/22798282/19320318/8ebf0754-9065-11e6-8ba6-06c0c0394c66.JPG)

**Comment by m4rc1e** [comment]
@JXParker Which OS and Software?

**Comment by JXParker** [comment]
MacOS Sierra 10.2, I just upgraded but it was also doing it on my older OS. I'm using the font in Indesign cloud version.

**Comment by m4rc1e** [comment]
Thank you.

Please try this [version](https://www.dropbox.com/s/y677rynfphkhz1f/FjallaOne-Regular_dehint.ttf?dl=0) via Dropbox. I remember coming across this problem a few years back. Let me know if this solves your issue. Also, what printer?

**Comment by JXParker** [comment]
THANK YOU!!!! It worked, sending virtual smooches! So happy for my client, so happy that I finally jumped on a forum and actually got a solution and had the skills to apply it and gain resolution.

Have a brilliant day . . . I have other fonts that glitch like this but happy to switch back to this one and ignore the other. Truly appreciate your help.

**Comment by m4rc1e** [comment]
@JXParker no problem and thank you for the lovely reply. 

I have a massive favour to ask. I'm currently printerless. Could you try and print again using this [font](https://www.dropbox.com/s/6gua3kanzb47n5p/FjallaOne-Regular_autod.ttf?dl=0)?

I've been mastering fonts at GF for around 3 months now. I don't want this problem repeating.

A high level explanation of the problem:
-Possibly the font's vmtx table is buggered or a hinting related table is buggered.

The font I previously sent you had the hints stripped out. The new version includes autohinting from the newest version of [ttfautohhint](https://www.freetype.org/ttfautohint/)

Cheers and glad it worked.
Marc Foley

**Comment by JXParker** [comment]
Hi Marc,

I dumped the first font and installed the second one, works perfectly so I will keep the latter in the font book. Hope that info helps . . . as for the vmtx part I'm off to google that so I can be better educated.

**Comment by davelab6** [comment]
> I have other fonts that glitch like this

Please do tell us about all glitches you encounter :)

**Comment by m4rc1e** [comment]
@JXParker thank you so much. One final request, what was the model of your printer?

@davelab6 We probably need to test the whole collection on a printer now ;).
Cheers,
Marc

**Comment by JXParker** [comment]
Oswald, but fewer letters for sure. I'd have to go a research the rest, these two were my most immediate issues.

**Comment by JXParker** [comment]
@m4rc1e 
HP Color LaserJet CP1518ni . . . it's pretty old.

**Comment by m4rc1e** [comment]
Thank you!

**Comment by davelab6** [comment]
Pretty sure this is a pre-v1.0 TTFAutohint issue

https://speakerdeck.com/davelab6/ttfautohint-making-hinting-fast-easy-and-global-typecon-2016?slide=38

**Comment by JXParker** [comment]
Thanks everyone!

**Comment by laerm0** [comment]
These issues appear to be solved now so I am closing.
