### ISSUE TITLE
Some fonts duplicated in misspelled directories?

### ISSUE THREAD

**Issue by terrycloth** [google/fonts#93]
I've noticed some similarly named pairs of directories which each have identically named font files. Are these redundant?

Both the directories `ofl/mrbedford` and `ofl/mrbedfort` contain `MrBedfort-Regular.ttf`, and both font files look the same to me.

Both the directories `ofl/mrssaintdelafield` and `ofl/misssaintdelafield` contain `MrsSaintDelafield-Regular.ttf` and both font files look the same to me.

Both the directories `ofl/siamreap` and `ofl/siemreap` contain `Siemreap.ttf`, although my font previewer shows them as somewhat different.

Both the directories `ofl/terminaldosis` and `ofl/terminaldosislight` contain `TerminalDosis-Light.ttf`, and if the two fonts aren't *exactly* the same, they are at least very close...

**Comment by impallari** [comment]
The old "dosis" folders are there for for legacy compatibility.

When you add new fonts to the directory (or when renaming fonts), you can just kill the older ones.
They must remain there, to allow people already using them to continue doing so.
They are no longer listed in the main listing, but the files are keep active so the service is not broken.

I don't know about the other 3 families, but maybe is the same legacy compatibility case.

**Comment by terrycloth** [comment]
So, out of dosis, terminaldosis, and terminaldosislight, *terminaldosis* is the most up-to-date? The commit history got obliterated when this repository moved to GitHub, but terminaldosis is the only folder with edits more recent than the "initial commit" 5 months ago.

Anyone know about the others?

**Comment by impallari** [comment]
1) Terminal Dosis Ligth is the initial 1 style only release.
2) Terminal Dosis is the initial Family release (multiple weights). Due to
a trademark issue we have to rename it.
3) Dosis is the current version.

**Comment by davelab6** [comment]
Thank you @impallari :) 

@terrycloth the other directories were initially published with typos in the names, but once a family is made available to users, it can not be removed without breaking those users' webpages, so they remain.

**Comment by impallari** [comment]
Maybe you can check the stats, and if they are not longer requested by any user you may be able to delete them safely.

**Comment by davelab6** [comment]
It is conceivable by anyone that some kind of redirect could be made _in the cloud_ such that the files could be removed from this repo and still served to users, but I'm not sure when that could be prioritised by the Google Fonts engineering team - there are so many good problems to solve :)
