### ISSUE TITLE
Update Mogra

### ISSUE THREAD

**Issue by davelab6** [google/fonts#946]
Per https://github.com/googlefonts/fontbakery/issues/1335 Mogra needs fixing (I think just ttfautohinting fresh will do) and updating.

**Comment by davelab6** [comment]
@graphicore I'm assigning to you

**Comment by graphicore** [comment]
Hmm, ftstring is broken on my system with:

`ftstring: symbol lookup error: ftstring: undefined symbol: FT_Get_Font_Format`

**Comment by graphicore** [comment]
ok, I compiled all the freetype stuff from the latest release.

I can confirm the error and I can confirm that ttfautohint makes it go away. I ran ttfautohnt without any further options.

Interestingly, Mogra was added to this repository 5 hours ago with #943 but that version is also erroneous and needs ttfautohint.
