### ISSUE TITLE
Add Bevan Stencil (Stencil version of Bevan font face)

### ISSUE THREAD

**Issue by cajhne** [google/fonts#949]
First post! I was going to do a pull request from my fork of the repo, but apparently this is the recommended way to submit a file still? :)

At any rate, this is my variation of Bevan font face. The contact info for the original artist is a broken email address. Bevan is already a part of this archive, so I'm happy to help extend it with this variation and also to take over maintaining the original if no one is presently doing it (the lower-case e needs patching).

Bevan stencil is here: https://github.com/cajhne/bevanstencil.git

All licenses are the same, and I've updated the font log and other docs to reflect the changes made from the original Bevan font.

Thanks!
-C

**Comment by m4rc1e** [comment]
@cajhne Thanks for this.

The original upstream Bevan repo is [here](https://github.com/googlefonts/BevanFont). Could you copy this folder structure and include your source files.

**Comment by cajhne** [comment]
Will do! Would it be better to fork your repo add my files, and do a pull request to combine the two? I can then erase my repo, since it's basically a version of this font. Maybe it makes more sense to add the changes to your repo. What do you think?

-C

**Comment by cajhne** [comment]
I also need to submit a patch to the lowercase e character in the regular Bevan font. I can make this a separate pull request if you like. Just let me know where you'd like me to add everything.

-C

**Comment by m4rc1e** [comment]
@cajhne yes please, I'll then do a review.

Thank you for your cooperation.

**Comment by cajhne** [comment]
Done. :)

**Comment by m4rc1e** [comment]
@cajhne I've had a quick look and I quite like it. @davelab6 maybe we should include this in the summer?

@cajhne there's still no source file in the repository and it doesn't match the origin upstream [repo](https://github.com/googlefonts/BevanFont). Did you use .glyphs for this?

**Comment by cajhne** [comment]
@m4rc1e Thanks! I was pretty meticulous about getting all the glyphs handled. The source file is there in the source folder- It's a .bf (birdfont) file. I did not use glyphs (software) to make this variation, as I prefer to use open source software. Let me know if you can't find it, or if you need something else.

Cheers!
-C

**Comment by cajhne** [comment]
I should note, the repo I cloned and submitted the pull request to was this one: https://github.com/vernnobile/BevanFont/pulls

It's all a bit confusing having so many different repos. :)
Let me know if you need something else...

**Comment by davelab6** [comment]
@cajhne yes, I understand the confusion. I hope to improve on that soon :) Thanks for this! I will check in with the team to confirm about adding this, but I like what you've done here :)

**Comment by cajhne** [comment]
Apparently all that work was Not Urgent or Important. Good to know.
