### ISSUE TITLE
AmaticSC regular does not work on Windows 7

### ISSUE THREAD

**Issue by Ziriax** [google/fonts#95]
When opening the Google Font repo version of this font (1.003) on Windows 7, all characters are displayed using a fallback font (Arial I guess). On OSX this works fine.

Version 1.001 of this font (as found on e.g. http://www.fontsquirrel.com/fonts/amatic) works fine on Windows, but might have other issues

Re-generating the TTF using FontForge fixes the problem.

**Comment by Ziriax** [comment]
It only seems to be problematic with GDI-based rendering software (Notepad, Windows 7 Font Preview, etc). DirectWrite based software handles the font correctly

**Comment by davelab6** [comment]
Thanks for reporting this. There seems to be another bug, where having the files from pre-june 2015 installed and viewing sites that use the post-june update fonts via the Google Fonts API appear as bold. https://twitter.com/larshaeuser/status/634023836502085633

**Comment by graphicore** [comment]
I can't really report this as fixed, but the TTF files in https://github.com/graphicore/MaticFonts work fine on a win 7 virtual machine here, see screen shots:

![selection_107](https://cloud.githubusercontent.com/assets/393132/18245434/725303e4-7365-11e6-9ace-90401ce79ce8.png)

![selection_108](https://cloud.githubusercontent.com/assets/393132/18245439/78c7e37a-7365-11e6-92e7-256b52215be7.png)

**Comment by laerm0** [comment]
This is no longer an issue.

![screen region 2017-09-11 at 16 10 01](https://user-images.githubusercontent.com/10780161/30294608-ae8fbc4c-970b-11e7-9d73-8bb0de1f6a7d.png)
