### ISSUE TITLE
Please add Odibee Sans

### ISSUE THREAD

**Issue by barnard555** [google/fonts#952]
https://github.com/barnard555/odibeesans

Hi guys. Never used Github before, so I hope I've completed the process correctly. I designed a font that I'd like to contribute to Google Fonts. Please let me know if I need to complete anything additional, and my apologies if I've missed anything.

Many thanks.

**Comment by davelab6** [comment]
@barnard555 great project! The source file (eg `OdibeeSans.glyphs`) is missing from your repo. https://github.com/googlefonts/gf-docs/blob/master/ProjectChecklist.md has more details about how to set up a repo :) 

However, before adding this, I'd like to see some additional work made to refine the design. I know that is somewhat against the spirit of your project, but I hope you'll be willing to see the project as something that had v1 made in one day, and then continued to grow :)

**Comment by barnard555** [comment]
@davelab6 

Thanks very much! I'd assumed that the original one day build was a little rough around the edges, and have since then added all the extra glyphs (I think) required for extended latin support.

Over the last day, I've also made some major changes to around 30 of the glyphs, including new styles for the letters (caps) S, B, R, and lower case s, c, y, a, e, r, f, t, p, q and j, as well as a couple of number tweaks. On top of this, there are now more than 1500 kerning pairs, which has made a massive improvement to the typeface. 

I'm pretty proud of how this has come out. I've included my glyphs source file in the repo. Let me know if I've missed anything. I'll update my website (odibeesans.com) with our final version, once you've approved it.

Thanks! JB

**Comment by barnard555** [comment]
@davelab6 Hey Dave. Is there anything else you need from me on this?

**Comment by barnard555** [comment]
Hey guys. Odibee Sans has had a fair amount of attention over the last few days. Any word on when/if it'll be added? I understand you're (_very_) busy...

**Some press:**
[Design Taxi](http://designtaxi.com/news/397991/Designer-Creates-Font-From-Scratch-And-Submits-It-To-Google-Within-24-Hours/)
[The Next Web](https://thenextweb.com/syndication/2018/01/23/made-font-scratch-got-submitted-google-24-hours/)
[Medium](https://medium.freecodecamp.org/designing-a-font-from-scratch-and-submitting-it-to-google-fonts-in-24-hours-152a30c57095)

**Comment by davelab6** [comment]
Sorry for the delay; no, we are set for now :) Thanks for your patience

**Comment by barnard555** [comment]
Hey guys. Is there anything I can do to help speed things along at all? It's been more than two years since I submitted this. Is the font not suitable for use?

**Comment by chddaniel** [comment]
Get this man's font on Google Fonts please!

**Comment by m4rc1e** [comment]
@barnard555 qa sent to your upstream. Please solve all checks which have failed.

**Comment by Enrico-Huzu** [comment]
Never give up

**Comment by m4rc1e** [comment]
Family is now in production, https://fonts.google.com/specimen/Odibee+Sans

**Comment by barnard555** [comment]
Thank you so much guys!

**Comment by yanone** [comment]
Manually linking PR: https://github.com/google/fonts/pull/2247
