### ISSUE TITLE
Suggestion: Serve WOFF to IE 11 on Window 7

### ISSUE THREAD

**Issue by superpoincare** [google/fonts#953]
It seems using Google Fonts fetches ttf files instead of woff or IE 11 on Windows 7. 

The user agent is: 

> Mozilla/5.0 (Windows NT 6.1; Trident/7.0; rv:11.0) like Gecko PTST/379

**Comment by davelab6** [comment]
Confirmed that TTF are served: 

```sh
$ curl -A "Mozilla/5.0 (Windows NT 6.1; Trident/7.0; rv:11.0) like Gecko PTST/379" "https://fonts.googleapis.com/css?family=Lobster"
@font-face {
  font-family: 'Lobster';
  font-style: normal;
  font-weight: 400;
  src: local('Lobster'), local('Lobster-Regular'), url(https://fonts.gstatic.com/s/lobster/v18/TSDaXhyJuDJ-NBU0popSWA.ttf) format('truetype');
}
```

**Comment by davelab6** [comment]
To confirm, do you see this as an active problem, or an opportunity for further optimization? :)

**Comment by vijayaraghavanramanan** [comment]
Just further optimization.
