### ISSUE TITLE
Asap missing latin-ext subset

### ISSUE THREAD

**Issue by tobiasz** [google/fonts#97]
Font "asap" shows compliance with latin ext subset, however chars are missing.

https://www.google.com/fonts#UsePlace:use/Collection:Asap

http://codepen.io/tobiasz/pen/qdwzVY

**Comment by m4rc1e** [comment]
Hey,

We're going to upload a [new version](https://github.com/Omnibus-Type/Asap) soon. This version covers the characters you included in your test. We already have an issue submitted to upload the font, #196 

![screen shot 2016-08-31 at 16 25 38](https://cloud.githubusercontent.com/assets/7525512/18132562/a59f6444-6f97-11e6-99cf-aa285ba9e210.png)

Cheers,
Marc
